{
  "hash": "115bb1af64d0b04e5c99d5d0b3f8c189",
  "result": {
    "markdown": "---\ntitle: \"Homework 2 - Emily Duryea\"\nauthor: \"Emily Duryea\"\ndescription: \"The second homework assignment for DACSS 603\"\ndate: \"10/17/2022\"\nformat:\n  html:\n    toc: true\n    code-fold: true\n    code-copy: true\n    code-tools: true\ncategories:\n  - hw2\n  - Emily Duryea\n---\n\n\n# Homework 2\n\nUploading packages to be used for this assignment:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(readxl)\nlibrary(tidyverse)\n```\n\n::: {.cell-output .cell-output-stderr}\n```\n── Attaching packages ─────────────────────────────────────── tidyverse 1.3.2 ──\n✔ ggplot2 3.3.6      ✔ purrr   0.3.5 \n✔ tibble  3.1.8      ✔ dplyr   1.0.10\n✔ tidyr   1.2.1      ✔ stringr 1.4.1 \n✔ readr   2.1.3      ✔ forcats 0.5.2 \n── Conflicts ────────────────────────────────────────── tidyverse_conflicts() ──\n✖ dplyr::filter() masks stats::filter()\n✖ dplyr::lag()    masks stats::lag()\n```\n:::\n\n```{.r .cell-code}\nlibrary(dplyr)\n```\n:::\n\n\n## Question 1\n\nBelow is the code used for setting up the degrees of freedom (df = sample size - 1). Thus, Bypass df would be 539 - 1 = 538, and, Angiography would be 847 - 1 = 846.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nBypass_df = 538\nAngio_df = 846\n```\n:::\n\n\nBelow is the code for setting up the mean and standard deviation.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nBypass_mean = 19\nBypass_sd = 10\nAngio_mean = 18\nAngio_sd = 9\n```\n:::\n\n\nThe code for calculating t-score with 90% confidence interval is below.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nBypass_tscore <- qt(p = 0.9, df = Bypass_df)\nAngio_tscore <- qt(p = 0.9, df = Angio_df)\n```\n:::\n\n\nThe code for calculating the standard error (sd/sqrt(sample size)) is below.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nBypass_se <- Bypass_sd/sqrt(539)\nAngio_se <- Angio_sd/sqrt(847)\n```\n:::\n\n\nThe code for calculating the margin of error (T-score multiplied by the standard error) is below.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nBypass_me <- Bypass_tscore*Bypass_se\nAngio_me <- Angio_tscore*Angio_se\n```\n:::\n\n\nBelow is the code for calculating the upper and lower ranges (add mean to margin of error for upper, subtract for lower).\n\n\n::: {.cell}\n\n```{.r .cell-code}\nBypass_low <- Bypass_mean - Bypass_me\nBypass_up <- Bypass_mean + Bypass_me\nAngio_low <- Angio_mean - Angio_me\nAngio_up <- Angio_mean + Angio_me\nBypass <- c(Bypass_low, Bypass_up)\nAngio <- c(Angio_low, Angio_up)\nBypass\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 18.44732 19.55268\n```\n:::\n\n```{.r .cell-code}\nAngio\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 17.60338 18.39662\n```\n:::\n:::\n\n\nThe 90% confidence interval for Bypass is \\[18.45, 19.55\\], and for Angio it is \\[17.60, 18.40\\]. Thus, Angio has the narrower confidence interval, which is logical to conclude because it has a larger sample size (847 \\> 539), which reduces the margin of error. Additionally, the standard deviation is smaller (9\\<10), which signifies less variance.\n\n## Question 2\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Number who believed college ed is essential for success\nN <- 567\n\n# Total sample size\nS <- 1031\n\n# Calculating point estimate\nPE <- N/S\n\n# Using the function prop.test() to find the confidence interval range & p-value\nprop.test(N, S, PE)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n\n\t1-sample proportions test without continuity correction\n\ndata:  N out of S, null probability PE\nX-squared = 6.9637e-30, df = 1, p-value = 1\nalternative hypothesis: true p is not equal to 0.5499515\n95 percent confidence interval:\n 0.5194543 0.5800778\nsample estimates:\n        p \n0.5499515 \n```\n:::\n:::\n\n\nThe 95% confidence interval is \\[0.519, 0.580\\], with a p-value of 0.550.\n\n## Question 3\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Calculating confidence interval of 95%\nCI95 <- qnorm(0.025, lower.tail = F)\n# Calculating sample size needed using confidence interval equation\nStudent_sample <- ((170*0.25/5)*CI95)^2\nStudent_sample\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 277.5454\n```\n:::\n:::\n\n\nBased on these calculations, the needed sample size would be 278 students for a significance level of 5%.\n\n## Question 4\n\n### Part A\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Calculating the standard error (sd = 90 sample = 9)\ncompany_se <- 90/sqrt(9)\ncompany_se\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 30\n```\n:::\n\n```{.r .cell-code}\n# Calculating the t-score\ncompany_tscore <- (410-500)/company_se\ncompany_tscore\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] -3\n```\n:::\n\n```{.r .cell-code}\n# Calculating the p-value (df = 9-1 = 8)\ncompany_pvalue <- (pt(q=-3, df=8))*2\ncompany_pvalue\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 0.01707168\n```\n:::\n:::\n\n\nIt is possible to reject the null hypothesis, as the p-value is statistically significant (0.017), less than 0.05.\n\n### Part B\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Calculating the probability of a random sample with a mean of 410 or less\nless_company <- pt(-3, 8)\nless_company\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 0.008535841\n```\n:::\n:::\n\n\nThe p-value for the lower tail is 0.00854.\n\n### Part B\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Calculating the probability of a random sample with a mean of 410 or more\nmore_company <- pt(-3, 8, lower.tail = F)\nmore_company\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 0.9914642\n```\n:::\n:::\n\n\nThe p-value for the upper tail is 0.991.\n\n\n::: {.cell}\n\n```{.r .cell-code}\ntotal_company <- less_company + more_company\ntotal_company\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 1\n```\n:::\n:::\n\n\nThe total of both tails is equal to 1.\n\n## Question 5\n\n### Part A\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Calculating t-scores\nJones_tscore <- (519.5-500)/10\nJones_tscore\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 1.95\n```\n:::\n\n```{.r .cell-code}\nSmith_tscore <- (519.7-500)/10\nSmith_tscore\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 1.97\n```\n:::\n\n```{.r .cell-code}\n# Calculating p-values\nJones_pvalue <- (pt(q=1.95, df=999, lower.tail=FALSE))*2\nJones_pvalue\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 0.05145555\n```\n:::\n\n```{.r .cell-code}\nSmith_pvalue <- (pt(q=1.97, df=999, lower.tail=FALSE))*2\nSmith_pvalue\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 0.04911426\n```\n:::\n:::\n\n\n### Part B\n\nIf the significance level is 0.05, then Smith has statistically significant study findings, while Jones does not.\n\n### Part C\n\nBoth of the studies could be statistically significant, depending on the significance level. For example, a 0.1 significance level would mean Jones also had statistically significant results. In this case, since the t-scores were so similar (0.2 off), it would not be unreasonable for both studies to reject the null hypothesis.\n\n## Question 6\n\n\n::: {.cell}\n\n```{.r .cell-code}\ngas_taxes <- c(51.27, 47.43, 38.89, 41.95, 28.61, 41.29, 52.19, 49.48, 35.02, 48.13, 39.28, 54.41, 41.66, 30.28, 18.49, 38.72, 33.41, 45.02)\n\n# Getting the mean\nmean_gtaxes <- mean(gas_taxes)\nmean_gtaxes\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 40.86278\n```\n:::\n\n```{.r .cell-code}\n# Conducting t-test\nt.test(gas_taxes, mu=45.0, alternative=\"less\")\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n\n\tOne Sample t-test\n\ndata:  gas_taxes\nt = -1.8857, df = 17, p-value = 0.03827\nalternative hypothesis: true mean is less than 45\n95 percent confidence interval:\n     -Inf 44.67946\nsample estimates:\nmean of x \n 40.86278 \n```\n:::\n:::\n\n\nBecause the p-value is 0.03827 on a 95% confidence interval, on the 0.05 significance level, it is possible the null hypothesis that gas prices are equal to or greater than \\$0.45.\n",
    "supporting": [],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}