{
  "hash": "2dccaa21ebee71fabea43881baa97d59",
  "result": {
    "markdown": "---\ntitle: \"DACSS 603: Homework 2\"\nauthor: \"Tory Bartelloni\"\ndesription: \"Homework 2\"\ndate: sys.date()\nformat:\n  html:\n    toc: true\n    code-fold: true\n    code-copy: true\n    code-tools: true\nexecute: \n  echo: true\n  warning: false\ncategories:\n  - hw2\n  - Tory Bartelloni\n---\n\n\n# Question 1\n\n*Construct the 90% confidence interval to estimate the actual mean wait time for each of the two procedures. Is the confidence interval narrower for angiography or bypass surgery?*\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(dplyr)\nsurgery <- data.frame(Procedure=c(\"Bypass\",\"Angiography\"), \n                      Sample_Size=c(539,847),\n                      Mean_Wait_Time=c(19,18),\n                      Standard_Deviation=c(10,9))\n\nbypass <- surgery %>% filter(Procedure == \"Bypass\")\n\nt_score_bypass <- qt(p=1-0.05, df=bypass$Sample_Size-1)\n\nse_bypass <- bypass$Standard_Deviation / sqrt(bypass$Sample_Size)\n\nCI_bypass <- c(bypass$Mean_Wait_Time - t_score_bypass * se_bypass,\n    bypass$Mean_Wait_Time + t_score_bypass * se_bypass)\n\nangio <- surgery %>% filter(Procedure == \"Angiography\")\n\nt_score_angio <- qt(p=1-0.05, df=angio$Sample_Size-1)\n\nse_angio <- angio$Standard_Deviation / sqrt(angio$Sample_Size)\n\nCI_angio <- c(angio$Mean_Wait_Time - t_score_angio * se_angio,\n    angio$Mean_Wait_Time + t_score_angio * se_angio)\n\nCI <- data.frame(Procedure = c(\"Bypass\", \"Angiography\"),\n                 Lower_Limit = c(CI_bypass[1],CI_angio[1]),\n                 Upper_Limit = c(CI_bypass[2],CI_angio[2]))\n\nknitr::kable(CI, caption = \"90% Confidence Levels for Cardiac Procedures\")\n```\n\n::: {.cell-output-display}\nTable: 90% Confidence Levels for Cardiac Procedures\n\n|Procedure   | Lower_Limit| Upper_Limit|\n|:-----------|-----------:|-----------:|\n|Bypass      |    18.29029|    19.70971|\n|Angiography |    17.49078|    18.50922|\n:::\n:::\n\nThe confidence interval is more narrow for angiogrphy because the larger sample size reduces t-score, and the larger sample and lower standard deviation together reduce the standard error. \n\n# Question 2\n\n*Find the point estimate, p, of the proportion of all adult Americans who believe that a college education is essential for success. Construct and interpret a 95% confidence interval for p.*\n\n\n::: {.cell}\n\n```{.r .cell-code}\ndf1 <- data.frame(x=c(rep(1,567),rep(0,1031-567)))\ndf_test <- t.test(df1)\ndf_test$estimate\n```\n\n::: {.cell-output .cell-output-stdout}\n```\nmean of x \n0.5499515 \n```\n:::\n\n```{.r .cell-code}\ndf_test$conf.int\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 0.5195334 0.5803696\nattr(,\"conf.level\")\n[1] 0.95\n```\n:::\n:::\n\nThe confidence interval is between 0.52 and 0.58 with a confidence level of 95% so we can say that 95% of the time when calculating this confidence interval the proportion of Americans who believe college is essential for success would lie within 52-58%.\n\n# Question 3\n\n*Assuming the significance level to be 5%, what should be the size of the sample?*\n\n\n::: {.cell}\n\n```{.r .cell-code}\nrange = 200-30\nsd = range/4\nn <- (1.96 * (sd/5))^2\n\nn\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 277.5556\n```\n:::\n:::\n\n\nGiven a significance level of 5% we can use the z-score to calculate the necessary sample size to obtain a confidence interval of $10, which would be approximately 278. \n\n# Question 4\n\n*Test whether the mean income of female employees differs from $500 per week. Include assumptions, hypotheses, test statistic, and P-value. Interpret the result.*\n*Report the P-value for Ha : μ < 500. Interpret.*\n*Report and interpret the P-value for H a: μ > 500.*\n\n\n::: {.cell}\n\n```{.r .cell-code}\nf_union <- data.frame(x=rnorm(9, mean=410, sd=90))\n\nt.test(f_union, mu = 500)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n\n\tOne Sample t-test\n\ndata:  f_union\nt = -3.8067, df = 8, p-value = 0.005187\nalternative hypothesis: true mean is not equal to 500\n95 percent confidence interval:\n 295.8076 449.8694\nsample estimates:\nmean of x \n 372.8385 \n```\n:::\n\n```{.r .cell-code}\ngreater <- t.test(f_union, mu = 500, alternative = \"greater\")\ngreater$p.value\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 0.9974066\n```\n:::\n\n```{.r .cell-code}\nless <- t.test(f_union, mu = 500, alternative = \"less\")\nless$p.value\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 0.002593396\n```\n:::\n\n```{.r .cell-code}\ngreater$p.value+less$p.value\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 1\n```\n:::\n:::\n\n\nOur main assumption is that the sample we took is representative of the female worker population.\n\nOur H~0~ is that female salary is not different than the average salary of $500.\nOur H~A~ is that female salary is different than the average salary of $500.\n\nThe t-statistics for female salary was -3.5 which provided a p-value <.01 indicating a strong confidence that the mean female salary is not $500.\n\nOur p-value for female salary being greater than $500 was 0.996 and for less than it was 0.004.\n\n#Question 5\n\n*A. Show that t = 1.95 and P-value = 0.051 for Jones. Show that t = 1.97 and P-value = 0.049 for Smith.*\n*B. Using α = 0.05, for each study indicate whether the result is “statistically significant.”*\n*C. Using this example, explain the misleading aspects of reporting the result of a test as “P ≤ 0.05” versus “P > 0.05,” or as “reject H0” versus “Do not reject H0 ,” without reporting the actual P-value.* \n\n\n::: {.cell}\n\n```{.r .cell-code}\njones_tstat <- (519.5-500)/10\nsmith_tstat <- (519.7-500)/10\n\nprint(paste0(\"Jones t-statistic is \", jones_tstat))\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] \"Jones t-statistic is 1.95\"\n```\n:::\n\n```{.r .cell-code}\nprint(paste0(\"Smith t-statistic is \", smith_tstat))\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] \"Smith t-statistic is 1.97\"\n```\n:::\n\n```{.r .cell-code}\njones_pvalue <- pt(q=jones_tstat, df = 1000-1, lower.tail = FALSE)*2\nsmith_pvalue <- pt(q=smith_tstat, df = 1000-1, lower.tail = FALSE)*2\n\nprint(paste0(\"Jones p-value is \", round(jones_pvalue,3)))\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] \"Jones p-value is 0.051\"\n```\n:::\n\n```{.r .cell-code}\nprint(paste0(\"Smith p-value is \", round(smith_pvalue,3)))\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] \"Smith p-value is 0.049\"\n```\n:::\n:::\n\n## A.\nAbove we have shown that the difference in the results leads to the t-statistics and p-values provided. \n\n## B.\nThe p-values observed show that at a 95% confidence level Jones' results are non-significant while Smith's results are significant.\n\n## C.\nThis is a good example of why not reporting p-values can be insufficient or misleading because the results we observed are extremely close, but the arbitrary boundary we agreed upon prior to the test distinguishes them into different categories. This would not be so important if the difference between those categories were not important. Without the context of the specific results we could see the two extremely similar results treated and acted upon in starkly different ways.\n\nI would argue this is one good reason why we should be reporting p-values up until .001 so researchers and users of the data can fully understand the context they would be applying the result within. Good to note that reporting extremely small p-values (<.001) has it's drawbacks as well and we do not want to overemphasize results that may be the result of methodology rather than a real and important distinction for instance.\n\n# Question 6\n\n*Is there enough evidence to conclude at a 95% confidence level that the average tax per gallon of gas in the US in 2005 was less than 45 cents? Explain.*\n\n\n::: {.cell}\n\n```{.r .cell-code}\ngas_taxes <- c(51.27, 47.43, 38.89, 41.95, 28.61, 41.29, 52.19, 49.48, 35.02, 48.13, 39.28, 54.41, 41.66, 30.28, 18.49, 38.72, 33.41, 45.02)\n\nt.test(gas_taxes, mu=45, alternative = \"less\")\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n\n\tOne Sample t-test\n\ndata:  gas_taxes\nt = -1.8857, df = 17, p-value = 0.03827\nalternative hypothesis: true mean is less than 45\n95 percent confidence interval:\n     -Inf 44.67946\nsample estimates:\nmean of x \n 40.86278 \n```\n:::\n:::\n\nBased on the results of the t-test we can say that gas tax was likely below 45 cents in 2005. Assuming the gas tax rates from the 18 cities was all-inclusive (i.e. included federal taxes) and representative then the data suggests the average tax per gallon of gas in the US was indeed less than 45 cents, *t*(17) = -1.89, p = .038.",
    "supporting": [],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}