{
  "hash": "aaa29945ec974e7eab9a5b32716eb513",
  "result": {
    "markdown": "---\ntitle: \"KPopiela HW2\"\neditor: visual\n---\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(dplyr)\n```\n\n::: {.cell-output .cell-output-stderr}\n```\n\nAttaching package: 'dplyr'\n```\n:::\n\n::: {.cell-output .cell-output-stderr}\n```\nThe following objects are masked from 'package:stats':\n\n    filter, lag\n```\n:::\n\n::: {.cell-output .cell-output-stderr}\n```\nThe following objects are masked from 'package:base':\n\n    intersect, setdiff, setequal, union\n```\n:::\n\n```{.r .cell-code}\nlibrary(ggplot2)\nlibrary(stats)\n```\n:::\n\n\n## Question 1\n\n### The time between the date a patient was recommended for heart surgery and the surgery date for cardiac patients in Ontario was collected by the Cardiac Care Network (\"Wait Times Data Guide,\" Ministry of Health and Long-Term Care, Ontario, Canada, 2006). The sample mean and sample standard deviation for wait times (in days) of patients for two cardiac procedures are given in the accompanying table. Assume that the sample is representative of the Ontario population. Construct the 90% confidence interval to estimate the actual mean wait time for each of the two procedures. Is the confidence interval narrower for angiography or bypass surgery?\n\n\n::: {.cell}\n\n```{.r .cell-code}\n#Bypass values\nn_bypass <- 539\nx_bypass <- 19\nsd_bypass <- 10\ndf_bypass <- n_bypass-1\nalpha = 0.10\n```\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\n#t-score  \ntscore_bypass = qt(p=alpha/2,df=df_bypass,lower.tail = F)\ntscore_bypass\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 1.647691\n```\n:::\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\n#standard error  \nse_bypass <- sd_bypass/sqrt(n_bypass)\nse_bypass\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 0.4307305\n```\n:::\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\n#margin of error and confidence interval (bypass)\nmargin_error <- tscore_bypass*se_bypass\nlower_CI <- x_bypass - margin_error\nupper_CI <- lower_CI+margin_error\nprint(c(lower_CI,upper_CI))\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 18.29029 19.00000\n```\n:::\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\n#Angiography values  \nn_angio <- 847\nx_angio <- 18\nsd_angio <- 9\ndf_angio <- n_angio-1\n#alpha value remains the same at 0.10 \n```\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\n#t-score\ntscore_angio <- qt(p=alpha/2,df=df_angio,lower.tail = F)\ntscore_angio\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 1.646657\n```\n:::\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\n#standard error\nse_angio <-sd_angio/sqrt(n_angio)\nse_angio\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 0.3092437\n```\n:::\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\n#margin of error and confidence interval (angiography)\nmargin_error_angio <- tscore_angio*se_angio\nangio_lowerCI <- x_angio - margin_error_angio\nangio_upperCI <- angio_lowerCI+margin_error_angio\nprint(c(angio_lowerCI,angio_upperCI))\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 17.49078 18.00000\n```\n:::\n:::\n\n\nThe bypass confidence interval for the true mean wait time is 18.290, 19.000, or 0.710.\\\nThe angiography confidence interval the true mean wait time is 17.491, 18.000, or 0.509.\n\nThe confidence interval is narrower for angiography.\n\n## Question 2\n\n### A survey of 1031 adult Americans was carried out by the National Center for Public Policy. Assume that the sample is representative of adult Americans. Among those surveyed, 567 believed that college education is essential for success. Find the point estimate, p, of the proportion of all adult Americans who believe that a college education is essential for success. Construct and interpret a 95% confidence interval for p.\n\n\n::: {.cell}\n\n```{.r .cell-code}\n#Sample proportion/Point estimate\nn <- 1031\nx <- 567\nsample_prop <- x/n\nsample_prop\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 0.5499515\n```\n:::\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\n#Margin of error\nmargin_error2 <- qnorm(0.975)*sqrt(sample_prop*(1-sample_prop)/n)\nmargin_error2\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 0.03036761\n```\n:::\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\n#95% Confidence Interval\nCI_lower <- sample_prop - margin_error2\nCI_upper <- CI_lower + margin_error2\nprint(c(CI_lower,CI_upper))\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 0.5195839 0.5499515\n```\n:::\n:::\n\n\nThe point estimate p, of the proportion of all adult Americans who believe that college is essential for success is 0.549, or \\~55%. The margin of error is 0.030, which lines up, since the confidence interval is 0.519, 0.549.\n\n## Question 3\n\n### Suppose that the financial aid office of UMass Amherst seeks to estimate the mean cost of textbooks per semester for students. The estimate will be useful if it is within \\$5 of the true population mean (i.e. they want the confidence interval to have a length of \\$10 or less). The financial aid office is pretty sure that the amount spent on books varies widely, with most values between \\$30 and \\$200. They think that the population standard deviation is about a quarter of this range (in other words, you can assume they know the population standard deviation). Assuming the significance level to be 5%, what should be the size of the sample?\n\n\n::: {.cell}\n\n```{.r .cell-code}\n#Since most formulas require a value for sample size (n), whichever one I use will have to be reorganized: the confidence interval formula. But because I am looking for n, it has to read z*(s/5)^2=n.\n\nf <-function(n, z = 1.96, s = 42.5) {\n  res <- z*s/sqrt(n)\n  return(res)\n}\n\nvec <- vapply(1:300, FUN = f, FUN.VALUE = 5.0)\nwhich(vec < 5) [1]\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 278\n```\n:::\n\n```{.r .cell-code}\n#The sample contains at least 278 people.\n```\n:::\n\n\n\n\n## Question 4  \n### According to a union agreement, the mean income for all senior-level workers in a large service company equals $500 per week. A representative of a women’s group decides to analyze whether the mean income μ for female employees matches this norm. For a random sample of nine female employees, ȳ = $410 and s = 90.\n#### C. Report and interpret the P-value for H a: μ > 500.\n####(Hint: The P-values for the two possible one-sided tests must sum to 1.)\n\n\n#### A. Test whether the mean income of female employees differs from $500 per week. Include assumptions, hypotheses, test statistic, and P-value. Interpret the result. \n\n::: {.cell}\n\n```{.r .cell-code}\n#In order to test whether or not the mean income for female employees differs from $500/week, we must first condect a one-sample, two-sided significance test.\n\n#We can also assume the following:  \n#1. The sample is random and the population has a normal distribution  \n#2. The mean income for all senior-level workers = $500/week  \n#3. From the random sample of 9 female employees, the mean income = $410/week  \n#4. Standard deviation = 90  \n#5. Null Hypothesis: H0: μ = 500  \n#6. Alternative Hypothesis: Ha: μ ≠ 500  \n```\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\n#Test statistic\nybar <- 410\nmean <- 500\ns <- 90\nn <- 9\n(ybar - mean)/(s/sqrt(n))\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] -3\n```\n:::\n\n```{.r .cell-code}\n#The test statistic value is -3\n```\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\n#P-value\nn <- 9 \ndf_n <- (n - 1)  \nt_test <- (410 - 500)/(90/sqrt(9))  \np_value <- pt(t_test, df_n)*2  \np_value\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 0.01707168\n```\n:::\n\n```{.r .cell-code}\n#P-value is 0.017. If we hold to the assumption that a=0.05, we can easily see that 0.017 < 0.05, which means the null hypothesis can be rejected. Therefore, there is enough statistical evidence to support the claim that the mean income for female employees differs from the overall mean of $500/week.\n```\n:::\n\n\n\n#### B. Report the P-value for Ha : μ < 500. Interpret.\n\n::: {.cell}\n\n```{.r .cell-code}\n#Hypotheses\n    #H0:mu = $500/week  \n    #Ha:mu = <$500/week  \n    #P-value = p(t<t_test)*p(t<-3)\n```\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\n#P-value for Ha:my > 500\nq <- -3\nleft_p_value <- pt(q,df_n,lower.tail=TRUE,log.p=FALSE)\nleft_p_value\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 0.008535841\n```\n:::\n\n```{.r .cell-code}\n#P-value for Ha:my > 500 is 0.0085. This can be rounded up to 0.01, which indicates that there's strong evidence against the mean weekly income being $500+\n```\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\n#P-value for H0:mu < 500\nright_p_value <- pt(q,df_n,lower.tail = FALSE,log.p=FALSE)\nright_p_value\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 0.9914642\n```\n:::\n\n```{.r .cell-code}\n#The p-value for H0:mu < 500 is 0.99, indicating strong evidence in favor of the null hypothesis. This contradicts the claim that mean mu > 500. To make sure my findings are correct, I must confrim that the sum of each p-value totals to 1. I could code this but it's not hard to tell that 0.01 + 0.99 = 1.\n```\n:::\n\n\n\n\n## Question 5\n### Jones and Smith separately conduct studies to test H0: μ = 500 against Ha : μ ≠ 500, each with n = 1000. Jones gets ȳ = 519.5, with se = 10.0. Smith gets ȳ = 519.7 ,with se = 10.0\n\n#### A. Show that t = 1.95 and P-value = 0.051 for Jones. Show that t = 1.97 and P-value = 0.049 for Smith.\n\n::: {.cell}\n\n```{.r .cell-code}\n#Let's start with Jones and confirming that t=1.95 and the p-value = 0.051\n\n#t-test\nt_testj <- (519.5-500)/10.0\nt_testj\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 1.95\n```\n:::\n\n```{.r .cell-code}\n#The t-test value, is in fact 1.95\n```\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\n#P-value\nn5 <- 1000\ndf_5 <- (n5-1)\n\npvaluej <- pt(t_testj, df_5,lower.tail = FALSE,log.p = FALSE)*2\npvaluej\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 0.05145555\n```\n:::\n\n```{.r .cell-code}\n#Like the t-test value, the p-value is also accurate to the question at 0.051.\n```\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\n#Now lets move onto Smith with t = 1.97 and p-value = 0.049\n\n#t-test\nt_testSmith <- (519.7 - 500)/10.0\nt_testSmith\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 1.97\n```\n:::\n\n```{.r .cell-code}\n#Smith's t-test value is 1.97.\n```\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\n#P-value\n\n#sample size n is the same as in the Jones section: n5 <- 1000  \n#df is also the same as the Jones section: df_5 <- (n5-1)  \n\np_valueSmith <- pt(t_testSmith, df_5,lower.tail = FALSE, log.p = FALSE)*2\np_valueSmith\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 0.04911426\n```\n:::\n\n```{.r .cell-code}\n#Smith's p-value, like the t-test value, is accurate to what the question presents at 0.049\n```\n:::\n\n\n\n#### B. Using α = 0.05, for each study indicate whether the result is “statistically significant.”\n\n::: {.cell}\n\n```{.r .cell-code}\n#In order for a p-value to be statistically significant, it must be greater than 0.05. Smith’s p-value is 0.049 which, while close, is still less than 0.05. Jones’s p-value, however, is statistically significant at 0.051.\n```\n:::\n\n\n\n#### C. Using this example, explain the misleading aspects of reporting the result of a test as “P ≤ 0.05” versus “P > 0.05,” or as “reject H0” versus “Do not reject H0 ,” without reporting the actual P-value.\n\n::: {.cell}\n\n```{.r .cell-code}\n#Smith's and Jones's results were extremely similar, but the difference between the two lies right on the threshold of statistical significance; only Jones's results were statistically significant. But given the result values' closeness (0.051 and 0.049), there is moderate evidence against H0.\n```\n:::\n\n\n\n\n## Question 6\n### Are the taxes on gasoline very high in the United States? According to the American Petroleum Institute, the per gallon federal tax that was levied on gasoline was 18.4 cents per gallon. However, state and local taxes vary over the same period. The sample data of gasoline taxes for 18 large cities is given below in the variable called gas_taxes.\n\n### gas_taxes <- c(51.27, 47.43, 38.89, 41.95, 28.61, 41.29, 52.19, 49.48, 35.02, 48.13, 39.28, 54.41, 41.66, 30.28, 18.49, 38.72, 33.41, 45.02)\n\n### Is there enough evidence to conclude at a 95% confidence level that the average tax per gallon of gas in the US in 2005 was less than 45 cents? Explain.\n\n::: {.cell}\n\n```{.r .cell-code}\n#I'm going to start by calculating the t-score to find the upper and lower values in the gas_taxes interval\n\ngas_taxes <- c(51.27, 47.43, 38.89, 41.95, 28.61, 41.29, 52.19, 49.48, 35.02, 48.13, 39.28, 54.41, 41.66, 30.28, 18.49, 38.72, 33.41, 45.02)\n\ngas_tax_sample <- 18\ndf_gt <- gas_tax_sample - 1\nmean_gt <- mean(gas_taxes)\ntscore_gt <- qt(p=0.05,df=df_gt,lower.tail=FALSE)\ngas_sd <- sd(gas_taxes)\nme_gas_taxes <- qt(0.05,df = df_gt)*gas_sd/sqrt(18)\n\nlower_int_gt<-(mean_gt+me_gas_taxes)\nlower_int_gt\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 37.0461\n```\n:::\n\n```{.r .cell-code}\n#The lower interval value is 37.046\n```\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\nupper_int_gt <- (mean_gt- me_gas_taxes)\nupper_int_gt\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 44.67946\n```\n:::\n\n```{.r .cell-code}\n#The upper interval value is 44.679\n\n#The average tax/gallon of gas is less than $0.45, so it is within the upper and lower bounds of the confidence interval. However, we will test an alternate outcome via a t-test\n```\n:::\n",
    "supporting": [],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}