{
  "hash": "c8a07735737a9744faff515b8e4e8b1b",
  "result": {
    "markdown": "---\ntitle: \"Homework 5\"\nauthor: \"Emily Duryea\"\ndesription: \"Final Project Proposal\"\ndate: \"12/09/2022\"\nformat:\n  html:\n    toc: true\n    code-fold: true\n    code-copy: true\n    code-tools: true\ncategories:\n  - Emily Duryea\n  - hw5\n  - homework5\n---\n\n\n# Homework 5\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(alr4)\n```\n\n::: {.cell-output .cell-output-stderr}\n```\nLoading required package: car\n```\n:::\n\n::: {.cell-output .cell-output-stderr}\n```\nLoading required package: carData\n```\n:::\n\n::: {.cell-output .cell-output-stderr}\n```\nLoading required package: effects\n```\n:::\n\n::: {.cell-output .cell-output-stderr}\n```\nlattice theme set by effectsTheme()\nSee ?effectsTheme for details.\n```\n:::\n\n```{.r .cell-code}\nlibrary(smss)\n```\n\n::: {.cell-output .cell-output-stderr}\n```\nWarning: package 'smss' was built under R version 4.2.2\n```\n:::\n\n```{.r .cell-code}\nlibrary(stargazer)\n```\n\n::: {.cell-output .cell-output-error}\n```\nError in library(stargazer): there is no package called 'stargazer'\n```\n:::\n\n```{.r .cell-code}\nlibrary(tidyverse)\n```\n\n::: {.cell-output .cell-output-stderr}\n```\n── Attaching packages\n───────────────────────────────────────\ntidyverse 1.3.2 ──\n```\n:::\n\n::: {.cell-output .cell-output-stderr}\n```\n✔ ggplot2 3.4.0      ✔ purrr   0.3.5 \n✔ tibble  3.1.8      ✔ dplyr   1.0.10\n✔ tidyr   1.2.1      ✔ stringr 1.4.1 \n✔ readr   2.1.3      ✔ forcats 0.5.2 \n```\n:::\n\n::: {.cell-output .cell-output-stderr}\n```\nWarning: package 'ggplot2' was built under R version 4.2.2\n```\n:::\n\n::: {.cell-output .cell-output-stderr}\n```\n── Conflicts ────────────────────────────────────────── tidyverse_conflicts() ──\n✖ dplyr::filter() masks stats::filter()\n✖ dplyr::lag()    masks stats::lag()\n✖ dplyr::recode() masks car::recode()\n✖ purrr::some()   masks car::some()\n```\n:::\n:::\n\n\n## Question 1\n\n\n::: {.cell}\n\n```{.r .cell-code}\ndata(house.selling.price.2)\nsummary(lm(P ~ ., data = house.selling.price.2))\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n\nCall:\nlm(formula = P ~ ., data = house.selling.price.2)\n\nResiduals:\n    Min      1Q  Median      3Q     Max \n-36.212  -9.546   1.277   9.406  71.953 \n\nCoefficients:\n            Estimate Std. Error t value Pr(>|t|)    \n(Intercept)  -41.795     12.104  -3.453 0.000855 ***\nS             64.761      5.630  11.504  < 2e-16 ***\nBe            -2.766      3.960  -0.698 0.486763    \nBa            19.203      5.650   3.399 0.001019 ** \nNew           18.984      3.873   4.902  4.3e-06 ***\n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n\nResidual standard error: 16.36 on 88 degrees of freedom\nMultiple R-squared:  0.8689,\tAdjusted R-squared:  0.8629 \nF-statistic: 145.8 on 4 and 88 DF,  p-value: < 2.2e-16\n```\n:::\n:::\n\n\n### Part A\n\nQuestion: For backward elimination, which variable would be deleted first? Why?\n\nAnswer: For backward elimination, the first variable to be deleted would be the beds variable, as it is the weakest indicator with the highest p-value (0.486763) in the regression analysis.\n\n### Part B\n\nQuestion: For forward selection, which variable would be added first? Why?\n\nAnswer: For forward selection, the first variable to be added would be size, as it has the highest t-value (11.504) in the regression analysis.\n\n### Part C\n\nQuestion: Why do you think that BEDS has such a large P-value in the multiple regression model, even though it has a substantial correlation with PRICE?\n\nAnswer: I think that the beds variable is not statistically significant, which has little to do with the correlation (correlation does not equal causation). There could be another, stronger indicator that is influencing the high correlation with price, such as the size of the house.\n\n### Part D\n\nQuestion: Using software with these four predictors, find the model that would be selected using each criterion:\n\n#### Part 1: R2\n\n\n::: {.cell}\n\n```{.r .cell-code}\nm1 <- lm(P ~ S, house.selling.price.2)\nstargazer(m1, type = 'text')\n```\n\n::: {.cell-output .cell-output-error}\n```\nError in stargazer(m1, type = \"text\"): could not find function \"stargazer\"\n```\n:::\n\n```{.r .cell-code}\nm2 <- lm(P ~ Be, house.selling.price.2)\nstargazer(m2, type = 'text')\n```\n\n::: {.cell-output .cell-output-error}\n```\nError in stargazer(m2, type = \"text\"): could not find function \"stargazer\"\n```\n:::\n\n```{.r .cell-code}\nm3 <- lm(P ~ Ba, house.selling.price.2)\nstargazer(m3, type = 'text')\n```\n\n::: {.cell-output .cell-output-error}\n```\nError in stargazer(m3, type = \"text\"): could not find function \"stargazer\"\n```\n:::\n\n```{.r .cell-code}\nm4 <- lm(P ~ New, house.selling.price.2)\nstargazer(m4, type = 'text')\n```\n\n::: {.cell-output .cell-output-error}\n```\nError in stargazer(m4, type = \"text\"): could not find function \"stargazer\"\n```\n:::\n\n```{.r .cell-code}\nm5 <- lm(P~., house.selling.price.2)\nstargazer(m5, type = 'text')\n```\n\n::: {.cell-output .cell-output-error}\n```\nError in stargazer(m5, type = \"text\"): could not find function \"stargazer\"\n```\n:::\n\n```{.r .cell-code}\nm6 <- lm(P~.-Be, house.selling.price.2)\nstargazer(m6, type = 'text')\n```\n\n::: {.cell-output .cell-output-error}\n```\nError in stargazer(m6, type = \"text\"): could not find function \"stargazer\"\n```\n:::\n:::\n\n\nm1 = 0.808\n\nm2 = 0.348\n\nm3 = 0.509\n\nm4 = 0.127\n\nm5 = 0.869\n\nm6 = 0.868\n\n#### Part 2: Adjusted R2\n\nm1 = 0.806\n\nm2 = 0.341\n\nm3 = 0.504\n\nm4 = 0.118\n\nm5 = 0.863\n\nm6 = 0.864\n\n#### Part 3: PRESS\n\n\n::: {.cell}\n\n```{.r .cell-code}\nPRESS <- function(linear.model) {\n  pr <- residuals(linear.model)/(1-lm.influence(linear.model)$hat)\n  PRESS <- sum(pr^2)\n  return(PRESS)\n}\n\ncat('       ', 'PRESS', '\\n',\n'm1:  ', PRESS(m1), '\\n',\n'm2:  ', PRESS(m2), '\\n',\n'm3:  ', PRESS(m3), '\\n',\n'm4:  ', PRESS(m4), '\\n',\n'm5:  ', PRESS(m5), '\\n',\n'm6:  ', PRESS(m6), '\\n')\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n        PRESS \n m1:   38203.29 \n m2:   122984.3 \n m3:   95732.14 \n m4:   164039.3 \n m5:   28390.22 \n m6:   27860.05 \n```\n:::\n:::\n\n\nm1 = 38203.29\n\nm2 = 122984.3\n\nm3 = 95732.14\n\nm4 = 164039.3\n\nm5 = 28390.22\n\nm6 = 27860.05\n\n#### Part 4: AIC\n\n\n::: {.cell}\n\n```{.r .cell-code}\ncat('       ', 'AIC', '\\n',\n'm1:  ', AIC(m1), '\\n',\n'm2:  ', AIC(m2), '\\n',\n'm3:  ', AIC(m3), '\\n',\n'm4:  ', AIC(m4), '\\n',\n'm5:  ', AIC(m5), '\\n',\n'm6:  ', AIC(m6), '\\n')\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n        AIC \n m1:   820.1439 \n m2:   933.7168 \n m3:   907.3327 \n m4:   960.908 \n m5:   790.6225 \n m6:   789.1366 \n```\n:::\n:::\n\n\nm1 = 820.1439\n\nm2 = 933.7168\n\nm3 = 907.3327\n\nm4 = 960.908\n\nm5 = 790.6225\n\nm6 = 789.1366\n\n#### Part 5: BIC\n\n\n::: {.cell}\n\n```{.r .cell-code}\ncat('       ', 'BIC', '\\n',\n'm1:  ', BIC(m1), '\\n',\n'm2:  ', BIC(m2), '\\n',\n'm3:  ', BIC(m3), '\\n',\n'm4:  ', BIC(m4), '\\n',\n'm5:  ', BIC(m5), '\\n',\n'm6:  ', BIC(m6), '\\n')\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n        BIC \n m1:   827.7417 \n m2:   941.3146 \n m3:   914.9305 \n m4:   968.5058 \n m5:   805.8181 \n m6:   801.7996 \n```\n:::\n:::\n\n\nm1 = 827.7417\n\nm2 = 941.3146\n\nm3 = 914.9305\n\nm4 = 968.5058\n\nm5 = 805.8181\n\nm6 = 801.7996\n\n### Part E\n\nQuestion: Explain which model you prefer and why.\n\nAnswer: The model that I prefer would be m6, which includes all variables but the beds variable. It was the best fit model in most of the tests. A second choice would be m5, which includes all variables, as it also performed similarly to m6.\n\n## Question 2\n\n### Part A\n\nFit a multiple regression model with the Volume as the outcome and Girth and Height as the explanatory variables.\n\n\n::: {.cell}\n\n```{.r .cell-code}\ntree <- lm(Volume ~ Girth + Height, data=trees)\ntree\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n\nCall:\nlm(formula = Volume ~ Girth + Height, data = trees)\n\nCoefficients:\n(Intercept)        Girth       Height  \n   -57.9877       4.7082       0.3393  \n```\n:::\n:::\n\n\n### Part B\n\nRun regression diagnostic plots on the model. Based on the plots, do you think any of the regression assumptions is violated?\n\n\n::: {.cell}\n\n```{.r .cell-code}\npar(mfrow = c(2,3)); plot(tree, which = 1:6)\n```\n\n::: {.cell-output-display}\n![](Homework-5_files/figure-html/unnamed-chunk-8-1.png){width=672}\n:::\n:::\n\n\nAnswer: In the first plot, residuals vs fitted, the assumption of linearity is violated as the line is a curved line rather than linear. The other plot that has a violation is the scale-location plot, as it is not a horizontal line, but rather, interestingly skewed.\n\n## Question 3\n\n### Part A\n\nRun a simple linear regression model where the Buchanan vote is the outcome and the Bush vote is the explanatory variable. Produce the regression diagnostic plots. Is Palm Beach County an outlier based on the diagnostic plots? Why or why not?\n\n\n::: {.cell}\n\n```{.r .cell-code}\nvote <- lm(Buchanan ~ Bush, data=florida)\npar(mfrow = c(2,3)); plot(vote, which = 1:6)\n```\n\n::: {.cell-output-display}\n![](Homework-5_files/figure-html/unnamed-chunk-9-1.png){width=672}\n:::\n:::\n\n\nYes, Palm Beach does appear to be an outlier on the plots. It falls outside the line of best fit in all the plots.\n\n### Part B\n\nTake the log of both variables (Bush vote and Buchanan Vote) and repeat the analysis in (a). Does your findings change?\n\n\n::: {.cell}\n\n```{.r .cell-code}\nvote_log <- lm(log(Buchanan)~log(Bush),data=florida)\npar(mfrow = c(2,3)); plot(vote_log, which = 1:6)\n```\n\n::: {.cell-output-display}\n![](Homework-5_files/figure-html/unnamed-chunk-10-1.png){width=672}\n:::\n:::\n\n\nPalm Beach is still an outlier, but additional counties appear as outliers in several plots, such as Calhoun and Liberty.\n",
    "supporting": [
      "Homework-5_files"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}