{
  "hash": "562d82defd9989822888fdede7630aaa",
  "result": {
    "markdown": "---\ntitle: \"Homework 1 - Donny Snyder\"\nauthor: \"Donny Snyder\"\ndescription: \"The first homework on descriptive statistics and probability\"\ndate: \"10/1/2022\"\nformat:\n  html:\n    toc: true\n    code-fold: true\n    code-copy: true\n    code-tools: true\ncategories:\n  - hw1\n  - desriptive statistics \n  - probability\n---\n\n\n# Question 1\n\n## a\n\nFirst, let's read in the data from the Excel file:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(readxl)\ndf <- read_excel(\"_data/LungCapData.xls\")\n```\n:::\n\n\n\nThe distribution of LungCap looks as follows:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nhist(df$LungCap)\n```\n\n::: {.cell-output-display}\n![](HW1answers_DonnySnyder_files/figure-html/unnamed-chunk-2-1.png){width=672}\n:::\n:::\n\n\nThe histogram suggests that the distribution is close to a normal distribution. Most of the observations are close to the mean. Very few observations are close to the margins (0 and 15).\n\n##b \n\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(ggplot2)\nggplot(df, aes(x = Gender, y = LungCap)) + geom_boxplot()\n```\n\n::: {.cell-output-display}\n![](HW1answers_DonnySnyder_files/figure-html/unnamed-chunk-3-1.png){width=672}\n:::\n:::\n\nThe probability distribution suggests that the lung capacity of males tends to be higher. \n\n##c\n\n\n::: {.cell}\n\n```{.r .cell-code}\naggregate(data = df, LungCap~Smoke, mean)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n  Smoke  LungCap\n1    no 7.770188\n2   yes 8.645455\n```\n:::\n:::\n\n\nThe mean lung capacity of smokers vs nonsmokers appears to be higher for smokers. This doesn't really make sense because I've been taught to think smokers tend to have reduced lung capacity. \n\n##d and e\n\n\n::: {.cell}\n\n```{.r .cell-code}\nx=1\ndf$AgeGroup <- rep(c(\"NA\"),times=725)\nwhile(x <= 725){\n  if(df$Age[x] <= 13){\n    df$AgeGroup[x] = \"less than or equal to 13\"\n  }\n  else if((df$Age[x] >= 14)&&(df$Age[x] <= 15)){\n    df$AgeGroup[x] = \"14 to 15\"\n  }\n  else if((df$Age[x] >= 16)&&(df$Age[x] <= 17)){\n    df$AgeGroup[x] = \"16 to 17\"\n  }\n  else if(df$Age[x] >= 18){\n    df$AgeGroup[x] = \"greater than 18\"\n  }\nx = x + 1\n}\naggregate(data = df, LungCap~AgeGroup+Smoke, mean)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n                  AgeGroup Smoke   LungCap\n1                 14 to 15    no  9.138810\n2                 16 to 17    no 10.469805\n3          greater than 18    no 11.068846\n4 less than or equal to 13    no  6.358746\n5                 14 to 15   yes  8.391667\n6                 16 to 17   yes  9.383750\n7          greater than 18   yes 10.513333\n8 less than or equal to 13   yes  7.201852\n```\n:::\n\n```{.r .cell-code}\naggregate(data = df,LungCap~AgeGroup+Smoke,length)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n                  AgeGroup Smoke LungCap\n1                 14 to 15    no     105\n2                 16 to 17    no      77\n3          greater than 18    no      65\n4 less than or equal to 13    no     401\n5                 14 to 15   yes      15\n6                 16 to 17   yes      20\n7          greater than 18   yes      15\n8 less than or equal to 13   yes      27\n```\n:::\n\n```{.r .cell-code}\naggregate(data = df,Age~Smoke,mean)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n  Smoke      Age\n1    no 12.03549\n2   yes 14.77922\n```\n:::\n:::\n\nIt seems like people tend to have a lung capacity that increases with age. However, nonsmokers have a higher lung capacity for  each age break down besides less than or equal to 13. It seems like smokers just might tend to be older. I confirmed this by looking at the length and mean ages per group, where you can see a majority of smokers are older, whereas non smokers tend to be younger. The mean age for smokers also tends to be older.\n\n\n##f\n\n\n::: {.cell}\n\n```{.r .cell-code}\ncor(x= df$LungCap, y = df$Age)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 0.8196749\n```\n:::\n\n```{.r .cell-code}\ncov(x= df$LungCap, y = df$Age)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 8.738289\n```\n:::\n:::\n\nLung capacity appears to be quite correlated with age. This means that Lung capacity tends to go up as age goes up, and vice versa. This is confirmed also by the covariance.\n\n#Question 2 \n\n##a\n\n\n::: {.cell}\n\n```{.r .cell-code}\nprint((160/810) * 100)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 19.75309\n```\n:::\n:::\n\nThe probability is 19.75309% that a randomly selected inmate has exactly 2 prior convictions.\n\n##b\n\n\n::: {.cell}\n\n```{.r .cell-code}\nprint(((434+128)/810) * 100)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 69.38272\n```\n:::\n:::\n\nThe probability is 69.38272% that a randomly selected inmate has fewer than 2 prior convictions.\n\n##c\n\n\n::: {.cell}\n\n```{.r .cell-code}\nprint(((160+434+128)/810) * 100)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 89.1358\n```\n:::\n:::\n\nThe probability is 89.1358% that a randomly selected inmate has 2 or fewer prior convictions.\n\n##d\n\n\n::: {.cell}\n\n```{.r .cell-code}\nprint(((64+24)/810) * 100)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 10.8642\n```\n:::\n:::\n\nThe probability is 10.8642% that a randomly selected inmate has more than 2 prior convictions.\n\n##e\n\n\n::: {.cell}\n\n```{.r .cell-code}\nnewDf <- NA\nnewDf[1:128] <- 0\nnewDf[129:562] <- 1\nnewDf[563:722] <- 2\nnewDf[723:786] <- 3\nnewDf[787:810] <- 4\nnewDf <- as.data.frame(newDf)\nmean(newDf$newDf)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 1.28642\n```\n:::\n:::\n\n\nThe expected value, known as the \"mean\" when it deals in data that are not probability distributions, is 1.28642. Because I created a vector here, I took the mean, though I also could have calculated the expected value by multiplying the probabilities by the numbers. They are both the same value in this case.\n\n##f\n\n\n::: {.cell}\n\n```{.r .cell-code}\nsd(newDf$newDf)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 0.9259016\n```\n:::\n\n```{.r .cell-code}\nvar(newDf$newDf)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 0.8572937\n```\n:::\n:::\n\nThe variance of prior convictions is 0.8572937, the standard deviation of prior convictions is 0.9259016.\n",
    "supporting": [
      "HW1answers_DonnySnyder_files"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}