{
  "hash": "4aec0d39e4331a21662e5c21844cb2a6",
  "result": {
    "markdown": "---\ntitle: \"Homework-2\"\nauthor: \"Niharika Pola\"\ndescription: \"Homework-2\"\ndate: \"17/10/2022\"\nformat:\n  html:\n    df-print: paged\n    css: styles.css\n    toc: true\n    code-fold: true\n    code-copy: true\n    code-tools: true\ncategories:\n  - hw2\n---\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(tidyverse)\nlibrary(readxl)\nlibrary(ggplot2)\nlibrary(stats)\n\nknitr::opts_chunk$set(echo = TRUE)\n```\n:::\n\n\n## Question 1:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nprocedure <- c(\"Bypass\", \"Angiography\")\ns_size <- c(539, 847)\nmean_wait_time <- c(19, 18)\ns_sd <- c(10, 9)\n\nsurgery <- data.frame(procedure, s_size, mean_wait_time, s_sd)\nsurgery\n```\n\n::: {.cell-output-display}\n`````{=html}\n<div data-pagedtable=\"false\">\n  <script data-pagedtable-source type=\"application/json\">\n{\"columns\":[{\"label\":[\"procedure\"],\"name\":[1],\"type\":[\"chr\"],\"align\":[\"left\"]},{\"label\":[\"s_size\"],\"name\":[2],\"type\":[\"dbl\"],\"align\":[\"right\"]},{\"label\":[\"mean_wait_time\"],\"name\":[3],\"type\":[\"dbl\"],\"align\":[\"right\"]},{\"label\":[\"s_sd\"],\"name\":[4],\"type\":[\"dbl\"],\"align\":[\"right\"]}],\"data\":[{\"1\":\"Bypass\",\"2\":\"539\",\"3\":\"19\",\"4\":\"10\"},{\"1\":\"Angiography\",\"2\":\"847\",\"3\":\"18\",\"4\":\"9\"}],\"options\":{\"columns\":{\"min\":{},\"max\":[10]},\"rows\":{\"min\":[10],\"max\":[10]},\"pages\":{}}}\n  </script>\n</div>\n`````\n:::\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\nstandard_error <- s_sd / sqrt(s_size)\nstandard_error\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 0.4307305 0.3092437\n```\n:::\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\nconfidence_level <- 0.90\ntail_area <- (1-confidence_level)/2\ntail_area\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 0.05\n```\n:::\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\nt_score <- qt(p = 1-tail_area, df = s_size-1)\nt_score\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 1.647691 1.646657\n```\n:::\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\nCI <- c(mean_wait_time - t_score * standard_error,\n        mean_wait_time + t_score * standard_error)\nCI\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 18.29029 17.49078 19.70971 18.50922\n```\n:::\n:::\n\n\nWe can be 90% confident that the population mean wait time for the bypass procedure is between 18.29029 and 19.70971 days.\n\nWe can be 90% confident that the population mean wait time for the angiography procedure is between 17.49078 and 18.50922 days.\n\nFrom the above results, we can be sure that confidence interval of angiography procedure is narrower.\n\n## Question 2\n\n\n::: {.cell}\n\n```{.r .cell-code}\nprop.test(567, 1031, conf.level = .95)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n\n\t1-sample proportions test with continuity correction\n\ndata:  567 out of 1031, null probability 0.5\nX-squared = 10.091, df = 1, p-value = 0.00149\nalternative hypothesis: true p is not equal to 0.5\n95 percent confidence interval:\n 0.5189682 0.5805580\nsample estimates:\n        p \n0.5499515 \n```\n:::\n:::\n\n\nThe point estimate, p, of the proportion of all adult Americans who believe that a college education is essential for success is 0.5499515 and confidence interval at 95% confidence level for p is \\[0.5189682, 0.5805580\\].\n\n## Question 3\n\n\n::: {.cell}\n\n```{.r .cell-code}\nME <- 5\nz <- 1.96\ns_sd <- (200-30)/4\n\ns_size <- ((z*s_sd)/ME)^2\ns_size\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 277.5556\n```\n:::\n:::\n\n\nThe necessary size for the sample is 278.\n\n## Question-4\n\n### A\n\nWe assume that the sample is random and that the population has a normal distribution.\n\nNull hypothesis: H0: μ = 500\n\nAlternative hypothesis: Ha: μ ≠ 500\n\nWe will reject the null hypothesis at a p-value less than or equal to 0.05\n\n\n::: {.cell}\n\n```{.r .cell-code}\ns_mean <- 410\nμ <- 500\ns_sd <- 90\ns_size <- 9\n```\n:::\n\n\n### Calculating test-statistic\n\n\n::: {.cell}\n\n```{.r .cell-code}\np <- 2*pt(t_score, s_size-1)\np\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 1.861970 1.861755\n```\n:::\n:::\n\n\nThe test-statistic is -3 and p-value is 0.01707168. As p-value is less than the 0.05, we reject the null hypothesis. Therefore, the mean income of female employees is not equal to \\$500.\n\n### B\n\nWe assume that the sample is random and that the population has a normal distribution.\n\nNull hypothesis: H0: μ = 500\n\nAlternative hypothesis: Ha: μ \\< 500\n\nWe will reject the null hypothesis at a p-value less than 0.05\n\n\n::: {.cell}\n\n```{.r .cell-code}\np <- pt(t_score, s_size-1, lower.tail = TRUE)\np\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 0.9309851 0.9308776\n```\n:::\n:::\n\n\nThe p-value is 0.008535841. As p-value is less than the 0.05, we reject the null hypothesis. Therefore, the mean income of female employees is less than \\$500.\n\n### C\n\nWe assume that the sample is random and that the population has a normal distribution.\n\nNull hypothesis: H0: μ = 500\n\nAlternative hypothesis: Ha: μ \\> 500\n\nWe will reject the null hypothesis at a p-value less than 0.05\n\n\n::: {.cell}\n\n```{.r .cell-code}\np <- pt(t_score, s_size-1, lower.tail = FALSE)\np\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 0.06901494 0.06912239\n```\n:::\n:::\n\n\nThe p-value is 0.9914642. As p-value is less than the 0.05, we reject the null hypothesis. Therefore, the mean income of female employees is greater than \\$500.\n\n## Question 5\n\n### A\n\nWe assume that the sample is random and that the population has a normal distribution.\n\nNull hypothesis: H0: μ = 500\n\nAlternative hypothesis: Ha: μ ≠ 500\n\nWe will reject the null hypothesis at a p-value less than 0.05\n\n### Calculating t-statistic and p-value for Jones\n\n\n::: {.cell}\n\n```{.r .cell-code}\ns_mean <- 519.5\nμ <- 500\nse <- 10\ns_size <- 1000\n\njt <- (s_mean-μ)/se\njt\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 1.95\n```\n:::\n\n```{.r .cell-code}\np <- 2*pt(jt, s_size-1, lower.tail = FALSE)\np\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 0.05145555\n```\n:::\n:::\n\n\n### Calculating t-statistic and p-value for Smith\n\n\n::: {.cell}\n\n```{.r .cell-code}\ns_mean <- 519.7\nμ <- 500\nse <- 10\ns_size <- 1000\n\njt <- (s_mean-μ)/se\njt\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 1.97\n```\n:::\n\n```{.r .cell-code}\np <- 2*pt(jt, s_size-1, lower.tail = FALSE)\np\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 0.04911426\n```\n:::\n:::\n\n\nThe test-statistic is 1.95, p-value is 0.05145555 for Jones and the test-statistic is 1.97, p-value is 0.05145555 for Smith.\n\n### B\n\nThe p-value is 0.05145555 for Jones. As p-value is greater than the 0.05, we fail to reject the null hypothesis. The p-value is 0.04911426 for Jones. As p-value is less than the 0.05, we reject the null hypothesis. Therefore, the result is statistically significant for Smith, but not Jones.\n\n### C\n\nIf we fail to report the P-value and simply state whether the P-value is less than/equal to or greater than the defined significance level of the test, one cannot determine the strength of the conclusion. In the Jones/Smith example, reporting the results only as \\*P ≤ 0.05\\* versus \\*P \\> 0.05\\* will lead to different conclusions about very similar results.\n\n## Question 6\n\n\n::: {.cell}\n\n```{.r .cell-code}\ngas_taxes <- c(51.27, 47.43, 38.89, 41.95, 28.61, 41.29, 52.19, 49.48, 35.02, 48.13, 39.28, 54.41, 41.66, 30.28, 18.49, 38.72, 33.41, 45.02)\n\nt.test(gas_taxes, mu = 18.4, conf.level = .95)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n\n\tOne Sample t-test\n\ndata:  gas_taxes\nt = 10.238, df = 17, p-value = 1.095e-08\nalternative hypothesis: true mean is not equal to 18.4\n95 percent confidence interval:\n 36.23386 45.49169\nsample estimates:\nmean of x \n 40.86278 \n```\n:::\n:::\n\n\nThe 95% confidence interval for the mean tax per gallon is 36.23386 through 45.49169. We cannot conclude with 95% confidence that the mean tax is less than 45 cents, since the 95% confidence interval contains values above 45 cents.\n",
    "supporting": [],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {
      "include-in-header": [
        "<link href=\"../site_libs/pagedtable-1.1/css/pagedtable.css\" rel=\"stylesheet\" />\r\n<script src=\"../site_libs/pagedtable-1.1/js/pagedtable.js\"></script>\r\n"
      ]
    },
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}