{
  "hash": "dc380f37c684020b3e8cfde01ea4b7c2",
  "result": {
    "markdown": "---\ntitle: \"Homework 2 - Prahitha Movva\"\nauthor: \"Prahitha Movva\"\ndescription: \"The second homework\"\ndate: \"10/17/2022\"\nformat:\n  html:\n    toc: true\n    code-fold: true\n    code-copy: true\n    code-tools: true\ncategories:\n  - hw2\n  - p-value \n  - confidence level\n---\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(readxl)\nlibrary(tidyverse)\n```\n\n::: {.cell-output .cell-output-stderr}\n```\n── Attaching packages ─────────────────────────────────────── tidyverse 1.3.2 ──\n✔ ggplot2 3.3.6      ✔ purrr   0.3.5 \n✔ tibble  3.1.8      ✔ dplyr   1.0.10\n✔ tidyr   1.2.1      ✔ stringr 1.4.1 \n✔ readr   2.1.3      ✔ forcats 0.5.2 \n── Conflicts ────────────────────────────────────────── tidyverse_conflicts() ──\n✖ dplyr::filter() masks stats::filter()\n✖ dplyr::lag()    masks stats::lag()\n```\n:::\n\n```{.r .cell-code}\nlibrary(dplyr)\nlibrary(stats)\nknitr::opts_chunk$set(echo=TRUE, warning=FALSE)\n```\n:::\n\n\n# Question 1\n\n## Angiography\n\n\n::: {.cell}\n\n```{.r .cell-code}\nsample.mean <- 18\nsample.n <- 847\nsample.sd <- 9\nsample.se <- sample.sd/sqrt(sample.n)\n\nalpha <- 0.10\ndegrees.freedom <- sample.n - 1\nt.score <- qt(p=alpha/2, df=degrees.freedom,lower.tail=F)\n\nmargin.error <- t.score * sample.se\nlower.bound <- sample.mean - margin.error\nupper.bound <- sample.mean + margin.error\nprint(c(lower.bound,upper.bound))\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 17.49078 18.50922\n```\n:::\n\n```{.r .cell-code}\nprint(upper.bound - lower.bound)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 1.018436\n```\n:::\n:::\n\n## Bypass\n\n\n::: {.cell}\n\n```{.r .cell-code}\nsample.mean <- 19\nsample.n <- 539\nsample.sd <- 10\nsample.se <- sample.sd/sqrt(sample.n)\n\nalpha <- 0.10\ndegrees.freedom <- sample.n - 1\nt.score <- qt(p=alpha/2, df=degrees.freedom,lower.tail=F)\n\nmargin.error <- t.score * sample.se\nlower.bound <- sample.mean - margin.error\nupper.bound <- sample.mean + margin.error\nprint(c(lower.bound,upper.bound))\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 18.29029 19.70971\n```\n:::\n\n```{.r .cell-code}\nprint(upper.bound - lower.bound)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 1.419421\n```\n:::\n:::\n\n\nThe 90% confidence interval for angiography is [17.49, 18.51] wait days (1.02) and for bypass is [18.29, 19.71] wait days (1.42). The confidence interval for angiography is slightly narrower (by 0.4).\n\n\n# Question 2\n\n\n::: {.cell}\n\n```{.r .cell-code}\nsample.trials <- 1031\nsample.successes <- 567\np <- sample.successes/sample.trials\nprint(p)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 0.5499515\n```\n:::\n\n```{.r .cell-code}\n# Here both the mean and the standard deviation are unknown\nprop.test <- prop.test(sample.successes, sample.trials, p=p, conf.level=0.95)\nprint(prop.test$conf.int)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 0.5194543 0.5800778\nattr(,\"conf.level\")\n[1] 0.95\n```\n:::\n:::\n\n\nThe point estimate, p, is 0.55 and the 95% confidence interval for p is [0.52, 0.58]. We can say that we are 95% confident that the true proportion of all adult Americans who believe that a college education is essential for success lies between 0.52 and 0.58. In other words, 95% of confidence intervals will contain the true proportion.\n\n# Question 3\n\n\n::: {.cell}\n\n```{.r .cell-code}\nrange <- 200-30\nmargin.error <- 5\npopulation.sd <- range/4\nalpha <- 0.05\nz_score <- qnorm(p=alpha/2, lower.tail=F)\nsample.n <- ((z_score*population.sd)/margin.error)^2\nprint(sample.n)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 277.5454\n```\n:::\n:::\n\n\nThe sample size should be 278.\n\n# Question 4\n\n\n::: {.cell}\n\n```{.r .cell-code}\npopulation.mean <- 500\nsample.mean <- 410\nsample.s <- 90\nsample.n <- 9\n```\n:::\n\n## a\nHo: The true mean income of female employees is $500/week\n\nHa: The true mean income of female employees is not $500/week\n\nAssumptions:\n\n1. The data is normally distributed\n\n2. Ho is true\n\n3. 95% CI\n\n\n::: {.cell}\n\n```{.r .cell-code}\nt.numerator <- sample.mean - population.mean\nt.denominator <- sample.s/sqrt(sample.n)\nt.statistic <- t.numerator/t.denominator\n\np.value <- pt(q=abs(t.statistic), df=sample.n-1, lower.tail=F)*2\nprint(t.statistic)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] -3\n```\n:::\n\n```{.r .cell-code}\nprint(p.value)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 0.01707168\n```\n:::\n:::\n\n\nThe t statistic is -3 and the p-value at 5% significance level is 0.017. Since the p-value is less than 0.05, it is evidence against Ho, i.e., the mean income of female employees differ significantly from $500 per week.\n\n## b\n\n::: {.cell}\n\n```{.r .cell-code}\np.value_less <- pt(q=t.statistic, df=sample.n-1, lower.tail=T)\nprint(p.value_less)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 0.008535841\n```\n:::\n:::\n\n\nHere too, the p-value at 5% significance level is less than 0.05. So we reject Ho and can say that the mean income of female employees is significantly less than $500 per week.\n\n## c\n\n::: {.cell}\n\n```{.r .cell-code}\np.value_greater <- pt(q=t.statistic, df=sample.n-1, lower.tail=F)\nprint(p.value_greater)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 0.9914642\n```\n:::\n:::\n\n\nHere, the p-value at 5% significance level is higher than 0.05 and we fail to reject Ho. This means, we do not have evidence that the mean income of female employees is more than $500 per week.\n\n\n::: {.cell}\n\n```{.r .cell-code}\np.value_greater + p.value_less\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 1\n```\n:::\n:::\n\n\n# Question 5\n\n\n::: {.cell}\n\n```{.r .cell-code}\nsample.n <- 1000\njones.mean <- 519.5\njones.se <- 10\nsmith.mean <- 519.7\nsmith.se <- 10\npopulation.mean <- 500\n```\n:::\n\n\n## a\n\n::: {.cell}\n\n```{.r .cell-code}\njones.t <- ((jones.mean-population.mean)/jones.se)\njones.t\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 1.95\n```\n:::\n\n```{.r .cell-code}\njones.p <- pt(q=abs(jones.t), df=sample.n-1, lower.tail=F)*2\njones.p\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 0.05145555\n```\n:::\n\n```{.r .cell-code}\nsmith.t <- ((smith.mean-population.mean)/smith.se)\nsmith.t\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 1.97\n```\n:::\n\n```{.r .cell-code}\nsmith.p <- pt(q=abs(smith.t), df=sample.n-1, lower.tail=F)*2\nsmith.p\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 0.04911426\n```\n:::\n:::\n\n\n## b\nAt 5% significance level, the result for Smith is statistically significant but that of Jones is not\n\n## c\nThis example shows using P > 0.05 or P <= 0.05 to see if we can the reject the null hypothesis or not is misleading, if the actual p-value is not reported. Both the p-values are only 0.1 significance level away from 0.05 but only one is significant, so the experiment might not be meaningful without the actual p-values.\n\n# Question 6\n\n\n::: {.cell}\n\n```{.r .cell-code}\ngas_taxes <- c(51.27, 47.43, 38.89, 41.95, 28.61, 41.29, 52.19, 49.48, 35.02, 48.13, 39.28, 54.41, 41.66, 30.28, 18.49, 38.72, 33.41, 45.02)\nt.test(gas_taxes, alternative = c(\"less\"), mu = 45)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n\n\tOne Sample t-test\n\ndata:  gas_taxes\nt = -1.8857, df = 17, p-value = 0.03827\nalternative hypothesis: true mean is less than 45\n95 percent confidence interval:\n     -Inf 44.67946\nsample estimates:\nmean of x \n 40.86278 \n```\n:::\n:::\n\n\nAt a 95% confidence level, we see that the p-value of 0.038. Since this value is less than 0.05, we reject the null hypothesis and say that the average tax per gallon of gas in the US in 2005 was significantly less than 45 cents.\n\n",
    "supporting": [],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}