{
  "hash": "c80cd129758b79498e83c9073a5f5b33",
  "result": {
    "markdown": "---\ntitle: \"DACSS 603 Final Project Pt 1\"\nauthor: \"Karen Kimble\"\ndesription: \"First part of final project\"\ndate: \"10/07/2022\"\nformat:\n  html:\n    toc: true\n    code-fold: true\n    code-copy: true\n    code-tools: true\ncategory: finalpart1\n---\n\n::: {.cell}\n\n```{.r .cell-code}\n# Setup\n\nlibrary(tidyverse)\n```\n\n::: {.cell-output .cell-output-stderr}\n```\n── Attaching packages ─────────────────────────────────────── tidyverse 1.3.2 ──\n✔ ggplot2 3.3.6      ✔ purrr   0.3.5 \n✔ tibble  3.1.8      ✔ dplyr   1.0.10\n✔ tidyr   1.2.1      ✔ stringr 1.4.1 \n✔ readr   2.1.3      ✔ forcats 0.5.2 \n── Conflicts ────────────────────────────────────────── tidyverse_conflicts() ──\n✖ dplyr::filter() masks stats::filter()\n✖ dplyr::lag()    masks stats::lag()\n```\n:::\n\n```{.r .cell-code}\nlibrary(readr)\nlibrary(scales)\n```\n\n::: {.cell-output .cell-output-stderr}\n```\n\nAttaching package: 'scales'\n\nThe following object is masked from 'package:purrr':\n\n    discard\n\nThe following object is masked from 'package:readr':\n\n    col_factor\n```\n:::\n\n```{.r .cell-code}\n# Importing datasets\n\nNYC_2019 <- read_csv(\"_data/2018-2019_School_Demographic_Snapshot.csv\", col_types = cols(`Grade PK (Half Day & Full Day)` = col_skip(), `# Multiple Race Categories Not Represented` = col_skip(), `% Multiple Race Categories Not Represented` = col_skip()))\n\nNYC_2019$`% Poverty` <- percent(NYC_2019$`% Poverty`, accuracy=0.1)\n\nNYC_2021 <- read_csv(\"_data/2020-2021_Demographic_Snapshot_School.csv\", col_types = cols(`Grade 3K+PK (Half Day & Full Day)` = col_skip(), `# Multi-Racial` = col_skip(), `% Multi-Racial` = col_skip(), `# Native American` = col_skip(), `% Native American` = col_skip(), `# Missing Race/Ethnicity Data` = col_skip(), `% Missing Race/Ethnicity Data` = col_skip()))\n\n# In order to bind the data, I had to remove columns that were not present in the other spreadsheet: Grade PK or 3K, Native American, the different multi-racial categories, and Missing Data\n\nschool_data <- rbind(NYC_2019, NYC_2021)\n\n# Making values coded as \"above 95%\" to equal 95% and \"below 5%\" to equal 5% for the purposes of this analysis\n\nschool_data$`% Poverty` <- recode(school_data$`% Poverty`, \"Above 95%\" = \"95%\", \"Below 5%\" = \"5%\")\n\n# Re-coding variables as numeric\n\nschool_data$`% Poverty` <- sapply(school_data$`% Poverty`, function(x) gsub(\"%\", \"\", x))\n\nschool_data$`% Poverty` <- as.numeric(school_data$`% Poverty`)\n\nschool_data$`Economic Need Index` <- as.numeric(school_data$`Economic Need Index`)\n```\n\n::: {.cell-output .cell-output-stderr}\n```\nWarning: NAs introduced by coercion\n```\n:::\n:::\n\n\n## Research Question\n\nThe research question I want to explore is whether child poverty has increased in schools that are predominantly made up of non-white students from the 2014-2015 school year to the 2020-2021 school year. I think this is extremely important to look at because of the pandemic's impact on not only child learning but also families' economic resources. According to the Columbia University Center on Poverty and Social Policy, \"nearly a quarter of children ages 0-3 live in poverty and nearly half of the city's young children live in lower-opportunity neighborhoods where the poverty rate is at least 20 percent\" (\"Poverty\"). Unfortunately, research shows that poverty is disproportionately felt according to one's race or ethnicity. In New York State, as of 2021, child poverty among children of color is almost 30%, with Black or African American children more than twice as likely to live in poverty than White, Non-Hispanic children (\"New York State\", 2021). With this disproportionate level of economic need in children of color, it seems important to investigate if the poverty level within New York City schools that are predominately non-White has increased significantly compared to schools that are predominantly White. When searching the UMass Libraries databases and other sources, it was hard to find studies that used this data in this way. It is important to understand if there is increasing poverty levels within an already vulnerable group.\n\n## Hypothesis\n\nI hypothesize that the poverty rate in NYC schools that are predominantly children of color will have increased more between the 2014-2015 and the 2020-2021 school years than the poverty rate in schools that are predominantly White. Since I have not found many previous studies on this, it is hard to know if this hypothesis was tested before. However, this data is fairly recent and also relates to the pandemic's effects on economics, so I think it is still a significant contribution to test this hypothesis.\n\n## Descriptive Statistics\n\nA description and summary of your data. How was your data collected by its original collectors? What are the important variables of interest for your research question? Use functions like glimpse() and summary() to present your data.\n\nThe data was collected by New York City and put on its Open Data source. The data covers NYC schools in the academic years 2014-2015 to 2020-2021. The important variables of interest included in the data are:\n\n-   Academic year\n\n-   Number and percentage of Asisan, Black, Hispanic, and White students\n\n-   Number and percentage of students in poverty\n\n-   Economic need index, which is the average of students' \"Economic Need Values\"\n\n    -   The Economic Need Index (ENI) estimates the percentage of students facing economic hardship\n\nThe other variables included are: DBN (district, borough, school number), school name, total enrollment, enrollment numbers for K-12, number and percentage of female and male students, number and percentage of students with disabilities, and number and percentage of English-Language Learner (ELL) students.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nglimpse(school_data)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\nRows: 18,142\nColumns: 36\n$ DBN                            <chr> \"01M015\", \"01M015\", \"01M015\", \"01M015\",…\n$ `School Name`                  <chr> \"P.S. 015 Roberto Clemente\", \"P.S. 015 …\n$ Year                           <chr> \"2014-15\", \"2015-16\", \"2016-17\", \"2017-…\n$ `Total Enrollment`             <dbl> 183, 176, 178, 190, 174, 270, 270, 271,…\n$ `Grade K`                      <dbl> 27, 32, 28, 28, 20, 44, 47, 37, 34, 30,…\n$ `Grade 1`                      <dbl> 47, 33, 33, 32, 33, 40, 43, 46, 38, 39,…\n$ `Grade 2`                      <dbl> 31, 39, 27, 33, 30, 39, 41, 47, 42, 43,…\n$ `Grade 3`                      <dbl> 19, 23, 31, 23, 30, 35, 43, 40, 46, 41,…\n$ `Grade 4`                      <dbl> 17, 17, 24, 31, 20, 40, 35, 43, 42, 44,…\n$ `Grade 5`                      <dbl> 24, 18, 18, 26, 28, 42, 40, 34, 42, 42,…\n$ `Grade 6`                      <dbl> 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, …\n$ `Grade 7`                      <dbl> 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, …\n$ `Grade 8`                      <dbl> 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, …\n$ `Grade 9`                      <dbl> 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, …\n$ `Grade 10`                     <dbl> 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, …\n$ `Grade 11`                     <dbl> 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, …\n$ `Grade 12`                     <dbl> 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, …\n$ `# Female`                     <dbl> 84, 83, 83, 99, 85, 132, 125, 127, 114,…\n$ `% Female`                     <dbl> 0.459, 0.472, 0.466, 0.521, 0.489, 0.48…\n$ `# Male`                       <dbl> 99, 93, 95, 91, 89, 138, 145, 144, 143,…\n$ `% Male`                       <dbl> 0.541, 0.528, 0.534, 0.479, 0.511, 0.51…\n$ `# Asian`                      <dbl> 8, 9, 14, 20, 24, 30, 27, 24, 23, 14, 2…\n$ `% Asian`                      <dbl> 0.044, 0.051, 0.079, 0.105, 0.138, 0.11…\n$ `# Black`                      <dbl> 65, 57, 51, 52, 48, 47, 55, 51, 49, 52,…\n$ `% Black`                      <dbl> 0.355, 0.324, 0.287, 0.274, 0.276, 0.17…\n$ `# Hispanic`                   <dbl> 107, 105, 105, 110, 95, 158, 169, 180, …\n$ `% Hispanic`                   <dbl> 0.585, 0.597, 0.590, 0.579, 0.546, 0.58…\n$ `# White`                      <dbl> 2, 2, 4, 6, 6, 27, 16, 15, 16, 18, 25, …\n$ `% White`                      <dbl> 0.011, 0.011, 0.022, 0.032, 0.034, 0.10…\n$ `# Students with Disabilities` <dbl> 64, 60, 51, 49, 38, 82, 82, 88, 90, 92,…\n$ `% Students with Disabilities` <dbl> 0.350, 0.341, 0.287, 0.258, 0.218, 0.30…\n$ `# English Language Learners`  <dbl> 17, 16, 12, 8, 8, 18, 13, 9, 8, 8, 120,…\n$ `% English Language Learners`  <dbl> 0.093, 0.091, 0.067, 0.042, 0.046, 0.06…\n$ `# Poverty`                    <chr> \"169\", \"149\", \"152\", \"161\", \"145\", \"200…\n$ `% Poverty`                    <dbl> 92.3, 84.7, 85.4, 84.7, 83.3, 74.1, 80.…\n$ `Economic Need Index`          <dbl> 0.930, 0.889, 0.882, 0.890, 0.880, 0.60…\n```\n:::\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\nsummary(school_data)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n     DBN            School Name            Year           Total Enrollment\n Length:18142       Length:18142       Length:18142       Min.   :   7.0  \n Class :character   Class :character   Class :character   1st Qu.: 323.0  \n Mode  :character   Mode  :character   Mode  :character   Median : 477.0  \n                                                          Mean   : 592.3  \n                                                          3rd Qu.: 695.0  \n                                                          Max.   :6040.0  \n                                                                          \n    Grade K          Grade 1          Grade 2          Grade 3      \n Min.   :  0.00   Min.   :  0.00   Min.   :  0.00   Min.   :  0.00  \n 1st Qu.:  0.00   1st Qu.:  0.00   1st Qu.:  0.00   1st Qu.:  0.00  \n Median : 32.00   Median : 33.00   Median : 32.00   Median : 28.00  \n Mean   : 44.25   Mean   : 45.79   Mean   : 45.73   Mean   : 45.33  \n 3rd Qu.: 78.00   3rd Qu.: 81.00   3rd Qu.: 82.00   3rd Qu.: 81.00  \n Max.   :393.00   Max.   :383.00   Max.   :349.00   Max.   :369.00  \n                                                                    \n    Grade 4         Grade 5          Grade 6          Grade 7      \n Min.   :  0.0   Min.   :  0.00   Min.   :  0.00   Min.   :  0.00  \n 1st Qu.:  0.0   1st Qu.:  0.00   1st Qu.:  0.00   1st Qu.:  0.00  \n Median : 22.0   Median : 19.00   Median :  0.00   Median :  0.00  \n Mean   : 44.8   Mean   : 44.18   Mean   : 43.15   Mean   : 42.37  \n 3rd Qu.: 80.0   3rd Qu.: 80.00   3rd Qu.: 64.00   3rd Qu.: 62.00  \n Max.   :376.0   Max.   :351.00   Max.   :771.00   Max.   :796.00  \n                                                                   \n    Grade 8          Grade 9           Grade 10         Grade 11      \n Min.   :  0.00   Min.   :   0.00   Min.   :   0.0   Min.   :   0.00  \n 1st Qu.:  0.00   1st Qu.:   0.00   1st Qu.:   0.0   1st Qu.:   0.00  \n Median :  0.00   Median :   0.00   Median :   0.0   Median :   0.00  \n Mean   : 41.88   Mean   :  49.34   Mean   :  48.7   Mean   :  39.85  \n 3rd Qu.: 60.00   3rd Qu.:  68.00   3rd Qu.:  69.0   3rd Qu.:  54.00  \n Max.   :784.00   Max.   :1555.00   Max.   :3832.0   Max.   :1529.00  \n                                                                      \n    Grade 12          # Female         % Female          # Male      \n Min.   :   0.00   Min.   :   0.0   Min.   :0.0000   Min.   :   0.0  \n 1st Qu.:   0.00   1st Qu.: 146.0   1st Qu.:0.4620   1st Qu.: 163.0  \n Median :   0.00   Median : 232.0   Median :0.4880   Median : 248.0  \n Mean   :  39.58   Mean   : 287.4   Mean   :0.4827   Mean   : 304.9  \n 3rd Qu.:  53.00   3rd Qu.: 347.0   3rd Qu.:0.5130   3rd Qu.: 364.0  \n Max.   :1566.00   Max.   :2405.0   Max.   :1.0000   Max.   :3635.0  \n                                                                     \n     % Male          # Asian           % Asian          # Black      \n Min.   :0.0000   Min.   :   0.00   Min.   :0.0000   Min.   :   0.0  \n 1st Qu.:0.4870   1st Qu.:   5.00   1st Qu.:0.0130   1st Qu.:  42.0  \n Median :0.5120   Median :  17.00   Median :0.0400   Median : 105.0  \n Mean   :0.5173   Mean   :  95.38   Mean   :0.1136   Mean   : 154.1  \n 3rd Qu.:0.5380   3rd Qu.:  79.00   3rd Qu.:0.1400   3rd Qu.: 198.0  \n Max.   :1.0000   Max.   :3671.00   Max.   :0.9470   Max.   :1493.0  \n                                                                     \n    % Black        # Hispanic     % Hispanic        # White       \n Min.   :0.000   Min.   :   1   Min.   :0.0060   Min.   :   0.00  \n 1st Qu.:0.083   1st Qu.:  89   1st Qu.:0.1980   1st Qu.:   6.00  \n Median :0.251   Median : 180   Median :0.3990   Median :  15.00  \n Mean   :0.316   Mean   : 241   Mean   :0.4251   Mean   :  87.24  \n 3rd Qu.:0.502   3rd Qu.: 313   3rd Qu.:0.6323   3rd Qu.:  78.00  \n Max.   :0.987   Max.   :2056   Max.   :1.0000   Max.   :3190.00  \n                                                                  \n    % White       # Students with Disabilities % Students with Disabilities\n Min.   :0.0000   Min.   :  0.0                Min.   :0.0000              \n 1st Qu.:0.0140   1st Qu.: 66.0                1st Qu.:0.1570              \n Median :0.0330   Median : 98.0                Median :0.2030              \n Mean   :0.1205   Mean   :121.6                Mean   :0.2295              \n 3rd Qu.:0.1440   3rd Qu.:146.0                3rd Qu.:0.2540              \n Max.   :0.9450   Max.   :925.0                Max.   :1.0000              \n                                                                           \n # English Language Learners % English Language Learners  # Poverty        \n Min.   :   0.0              Min.   :0.0000              Length:18142      \n 1st Qu.:  18.0              1st Qu.:0.0430              Class :character  \n Median :  43.0              Median :0.0950              Mode  :character  \n Mean   :  81.1              Mean   :0.1363                                \n 3rd Qu.: 100.0              3rd Qu.:0.1800                                \n Max.   :1219.0              Max.   :1.0000                                \n                                                                           \n   % Poverty      Economic Need Index\n Min.   :  2.90   Min.   :0.030      \n 1st Qu.: 69.30   1st Qu.:0.579      \n Median : 81.40   Median :0.743      \n Mean   : 75.89   Mean   :0.691      \n 3rd Qu.: 89.90   3rd Qu.:0.846      \n Max.   :100.00   Max.   :0.998      \n                  NA's   :9169       \n```\n:::\n\n```{.r .cell-code}\n# Note: the summary data for the enrollment numbers split by grade is somewhat off (especially minimums) because there is no variable listed for type of school (i.e., middle versus high school). So, for example, an elementary school would have an enrollment total of 0 for grade 12, which would show up as the minimum.\n```\n:::\n\n\nAs we can see from this summary, the median percent of poverty in NYC schools (81.4%) is higher than the mean percent (75.89%), indicating that there may be low outliers with very low percentages of poverty. The same holds true for the Economic Need Index, with the mean (0.691) lower than the median (0.743). It is troubling, however, that both the mean and median percentages of poverty in NYC schools overall is more than three-fourths of the population.\n\n## References\n\nNew York State Child Poverty Facts. Schuyler Center for Analysis and Advocacy. (2021, February 18). Retrieved from https://scaany.org/wp-content/uploads/2021/02/NYS-Child-Poverty-Facts_Feb2021.pdf\n\nPoverty in New York City. Columbia University Center on Poverty and Social Policy. (n.d.). Retrieved from https://www.povertycenter.columbia.edu/poverty-in-new-york-city#:\\~:text=Children%20and%20Families%20in%20New%20York%20City&text=Through%20surveys%2C%20we%20find%20that,is%20at%20least%2020%20percent.\n",
    "supporting": [],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}