{
  "hash": "59f4946f8fa37707176be3a3a8555062",
  "result": {
    "markdown": "---\nauthor: \"Emma Rasmussen\"\ndescription: \"Final Project Part 1\"\ndate: \"10/11/2022\"\nformat:\n  html:\n    toc: true\n    code-fold: true\n    code-copy: true\n    code-tools: true\ncategories:\n  - finalpart1\n---\n\n::: {.cell}\n\n```{.r .cell-code}\nknitr::opts_chunk$set(echo = TRUE, warning=FALSE, message=FALSE)\n\nlibrary(readxl)\nlibrary(tidyverse)\nlibrary(ggplot2)\nlibrary(dplyr)\n```\n:::\n\n\n## Research Question: \nDoes political partisanship correlate with COVID-19 death rates?\n\nThe COVID-19 pandemic became a political matter. Behaviors associated with COVID-19 prevention were adopted on partisan lines (masking, social distancing, and vaccine uptake). Early in the pandemic, mask mandates were protested in some communities. My research question is have these behaviors affected COVID-19 death rates along partisan lines? If so, public health interventions could target communities that may be higher risk for COVID-19 deaths based on political partisanship. \n\nI am thinking death toll would make the most sense to measure than infection rates as infection rates are constantly changing (other studies have looked at infection rates over waves of the pandemic, see this study from the Pew Research Center (Jones 2022)). I also think that one way to measure partisanship will be the 2020 county-level election results (% voting for Trump). In other words, my research is looking to see if (county-level) Trump support correlates with COVID-19 death rates. Both these variables can be found in county-level data sets so I can join multiple dataset with county name (or FIPS code) as the \"key\".\n\nOther variables to consider at the county-level (confounding variables): vaccine (and booster) uptake, average age of population\n\n\n## Hypothesis: \nWhile I came up with this research idea on my own, other organizations such as NPR (Wood and Brumfiel 2021) and the Pew Research Center ()have already tested this. For this project, I will use the most recent data I can find. I was hoping to consider the confounding variable of population density, for instance I am guessing more urban populations will tend to vote democratic but these more densely populated places may also have higher infection rates. However, I cannot find any county level population density data sets, so I may use the \"Urban Rural Description\" variable in one of my datasets.\n\nH0: B1 (and all beta values) is zero. There is no correlation\nHa: B1 (or any beta value) is not zero. There is a correlation between partisanship and COVID-19 death rates. \n\n## Descriptive Statistics: \n\n::: {.cell}\n\n```{.r .cell-code}\n#set wd to change file path so I can access data on my computer without adding to posts folder\nsetwd(\"/Users/emmarasmussen/Documents\")\nvotedf<- read_csv(\"countypres_2000-2020.csv\")\nhead(votedf, 12)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n# A tibble: 12 × 12\n    year state   state_po county_…¹ count…² office candi…³ party candi…⁴ total…⁵\n   <dbl> <chr>   <chr>    <chr>     <chr>   <chr>  <chr>   <chr>   <dbl>   <dbl>\n 1  2000 ALABAMA AL       AUTAUGA   01001   US PR… AL GORE DEMO…    4942   17208\n 2  2000 ALABAMA AL       AUTAUGA   01001   US PR… GEORGE… REPU…   11993   17208\n 3  2000 ALABAMA AL       AUTAUGA   01001   US PR… RALPH … GREEN     160   17208\n 4  2000 ALABAMA AL       AUTAUGA   01001   US PR… OTHER   OTHER     113   17208\n 5  2000 ALABAMA AL       BALDWIN   01003   US PR… AL GORE DEMO…   13997   56480\n 6  2000 ALABAMA AL       BALDWIN   01003   US PR… GEORGE… REPU…   40872   56480\n 7  2000 ALABAMA AL       BALDWIN   01003   US PR… RALPH … GREEN    1033   56480\n 8  2000 ALABAMA AL       BALDWIN   01003   US PR… OTHER   OTHER     578   56480\n 9  2000 ALABAMA AL       BARBOUR   01005   US PR… AL GORE DEMO…    5188   10395\n10  2000 ALABAMA AL       BARBOUR   01005   US PR… GEORGE… REPU…    5096   10395\n11  2000 ALABAMA AL       BARBOUR   01005   US PR… RALPH … GREEN      46   10395\n12  2000 ALABAMA AL       BARBOUR   01005   US PR… OTHER   OTHER      65   10395\n# … with 2 more variables: version <dbl>, mode <chr>, and abbreviated variable\n#   names ¹​county_name, ²​county_fips, ³​candidate, ⁴​candidatevotes, ⁵​totalvotes\n# ℹ Use `colnames()` to see all variable names\n```\n:::\n\n```{.r .cell-code}\ncoviddf<- read_csv(\"Provisional_COVID-19_Deaths_by_County__and_Race_and_Hispanic_Origin.csv\")\nhead(coviddf, 12)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n# A tibble: 12 × 21\n   Data …¹ Start…² End D…³ State Count…⁴ Urban…⁵ FIPS …⁶ FIPS …⁷ FIPS …⁸ Indic…⁹\n   <chr>   <chr>   <chr>   <chr> <chr>     <dbl>   <dbl>   <dbl>   <dbl> <chr>  \n 1 10/05/… 01/01/… 10/01/… AK    Anchor…       3       2      20    2020 Distri…\n 2 10/05/… 01/01/… 10/01/… AK    Anchor…       3       2      20    2020 Distri…\n 3 10/05/… 01/01/… 10/01/… AK    Anchor…       3       2      20    2020 Distri…\n 4 10/05/… 01/01/… 10/01/… AK    Fairba…       4       2      90    2090 Distri…\n 5 10/05/… 01/01/… 10/01/… AK    Fairba…       4       2      90    2090 Distri…\n 6 10/05/… 01/01/… 10/01/… AK    Fairba…       4       2      90    2090 Distri…\n 7 10/05/… 01/01/… 10/01/… AK    Matanu…       3       2     170    2170 Distri…\n 8 10/05/… 01/01/… 10/01/… AK    Matanu…       3       2     170    2170 Distri…\n 9 10/05/… 01/01/… 10/01/… AK    Matanu…       3       2     170    2170 Distri…\n10 10/05/… 01/01/… 10/01/… AL    Autaug…       3       1       1    1001 Distri…\n11 10/05/… 01/01/… 10/01/… AL    Autaug…       3       1       1    1001 Distri…\n12 10/05/… 01/01/… 10/01/… AL    Autaug…       3       1       1    1001 Distri…\n# … with 11 more variables: `Total deaths` <dbl>, `COVID-19 Deaths` <dbl>,\n#   `Non-Hispanic White` <dbl>, `Non-Hispanic Black` <dbl>,\n#   `Non-Hispanic American Indian or Alaska Native` <dbl>,\n#   `Non-Hispanic Asian` <dbl>,\n#   `Non-Hispanic Native Hawaiian or Other Pacific Islander` <dbl>,\n#   Hispanic <dbl>, Other <dbl>, `Urban Rural Description` <chr>,\n#   Footnote <chr>, and abbreviated variable names ¹​`Data as of`, …\n# ℹ Use `colnames()` to see all variable names\n```\n:::\n\n```{.r .cell-code}\n#counting the number of distinct counties in df\nn_distinct(votedf$county_name)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 1892\n```\n:::\n\n```{.r .cell-code}\nn_distinct(coviddf$\"County Name\")\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 857\n```\n:::\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\nsummary(votedf)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n      year         state             state_po         county_name       \n Min.   :2000   Length:72617       Length:72617       Length:72617      \n 1st Qu.:2004   Class :character   Class :character   Class :character  \n Median :2012   Mode  :character   Mode  :character   Mode  :character  \n Mean   :2011                                                           \n 3rd Qu.:2020                                                           \n Max.   :2020                                                           \n county_fips           office           candidate            party          \n Length:72617       Length:72617       Length:72617       Length:72617      \n Class :character   Class :character   Class :character   Class :character  \n Mode  :character   Mode  :character   Mode  :character   Mode  :character  \n                                                                            \n                                                                            \n                                                                            \n candidatevotes      totalvotes         version             mode          \n Min.   :      0   Min.   :      0   Min.   :20220315   Length:72617      \n 1st Qu.:    115   1st Qu.:   5175   1st Qu.:20220315   Class :character  \n Median :   1278   Median :  11194   Median :20220315   Mode  :character  \n Mean   :  10782   Mean   :  42514   Mean   :20220315                     \n 3rd Qu.:   5848   3rd Qu.:  29855   3rd Qu.:20220315                     \n Max.   :3028885   Max.   :4264365   Max.   :20220315                     \n```\n:::\n\n```{.r .cell-code}\nsummary(coviddf)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n  Data as of         Start Date          End Date            State          \n Length:3495        Length:3495        Length:3495        Length:3495       \n Class :character   Class :character   Class :character   Class :character  \n Mode  :character   Mode  :character   Mode  :character   Mode  :character  \n                                                                            \n                                                                            \n                                                                            \n                                                                            \n County Name        Urban Rural Code   FIPS State     FIPS County    \n Length:3495        Min.   :1.000    Min.   : 1.00   Min.   :  1.00  \n Class :character   1st Qu.:2.000    1st Qu.:18.00   1st Qu.: 31.00  \n Mode  :character   Median :4.000    Median :33.00   Median : 71.00  \n                    Mean   :3.645    Mean   :30.47   Mean   : 99.37  \n                    3rd Qu.:5.000    3rd Qu.:42.00   3rd Qu.:121.00  \n                    Max.   :6.000    Max.   :56.00   Max.   :840.00  \n                                                                     \n   FIPS Code      Indicator          Total deaths    COVID-19 Deaths  \n Min.   : 1001   Length:3495        Min.   :   621   Min.   :  101.0  \n 1st Qu.:18053   Class :character   1st Qu.:  1690   1st Qu.:  176.0  \n Median :33007   Mode  :character   Median :  3284   Median :  364.0  \n Mean   :30567                      Mean   :  7163   Mean   :  852.7  \n 3rd Qu.:42095                      3rd Qu.:  6990   3rd Qu.:  844.0  \n Max.   :56037                      Max.   :220829   Max.   :31013.0  \n                                                                      \n Non-Hispanic White Non-Hispanic Black\n Min.   :0.0270     Min.   :0.0010    \n 1st Qu.:0.6677     1st Qu.:0.0230    \n Median :0.8300     Median :0.0690    \n Mean   :0.7742     Mean   :0.1242    \n 3rd Qu.:0.9290     3rd Qu.:0.1800    \n Max.   :1.0000     Max.   :0.7610    \n NA's   :3          NA's   :592       \n Non-Hispanic American Indian or Alaska Native Non-Hispanic Asian\n Min.   :0.0000                                Min.   :0.0010    \n 1st Qu.:0.0020                                1st Qu.:0.0070    \n Median :0.0040                                Median :0.0130    \n Mean   :0.0214                                Mean   :0.0261    \n 3rd Qu.:0.0100                                3rd Qu.:0.0280    \n Max.   :0.8610                                Max.   :0.5170    \n NA's   :1701                                  NA's   :1360      \n Non-Hispanic Native Hawaiian or Other Pacific Islander    Hispanic     \n Min.   :0.0000                                         Min.   :0.0030  \n 1st Qu.:0.0000                                         1st Qu.:0.0220  \n Median :0.0010                                         Median :0.0480  \n Mean   :0.0023                                         Mean   :0.0987  \n 3rd Qu.:0.0010                                         3rd Qu.:0.1090  \n Max.   :0.2000                                         Max.   :0.9870  \n NA's   :2183                                           NA's   :740     \n     Other        Urban Rural Description   Footnote        \n Min.   :0.0010   Length:3495             Length:3495       \n 1st Qu.:0.0090   Class :character        Class :character  \n Median :0.0150   Mode  :character        Mode  :character  \n Mean   :0.0174                                             \n 3rd Qu.:0.0220                                             \n Max.   :0.2410                                             \n NA's   :1633                                               \n```\n:::\n:::\n\n\nThis data is going to require some tidying before merging. In the coviddf, each county is listed 3 times, (once per indicator) so I will likely filter out just the indicator \"Distribution of COVID-19 deaths (%)\" so each county is listed only once. Similarly, the votedf contains extra years. For my research, I am only concerned with 2016 data so I will filter out % voting for Trump in 2016 as a measure of political affiliation/partisanship. Then I will merge the two dfs based on county names (will also require some data tidying).\n\nThe votedf was compiled by the MIT Election Data and Science Lab. It was first published in 2018 and has been updated with the 2020 election. It contains county-level presidential election data beginning in 2000 and going up to the 2020 election. The data has 12 columns, and 72,617 rows (many of which I will filter out before conducting analysis.) There are 1,892 distinct county names in the data set. \n\nThe coviddf only has 857 unique county names in the data frame. This may be because not all counties reported COVID-19 death counts. When I join the data sets, I will join so as to only include observations that we have information from both data frames. The coviddf is provisional, meaning that it is consistently updated (I believe on a weekly basis) with current COVID-19 death toll data. It is likely compiled by counties/towns reporting these numbers to the CDC. This data has limitations, not all counties report this, and not all report it accurately/ attribute COVID-19 as the true cause of death in all circumstances. Using the summary function, we can see the \"mean\" COVID-19 deaths by county is 852.7, however this isn't super meaningful given each county has this reported 3 times in the data and the median is significantly lower. Statistics provided by the summary function will be more meaningful once the data is tidied.  \n\n## References\nJones, B. (2022). The Changing Political Geography of COVID-19 Over the Last Two Years. Pew Research Center. March 3, 2022. https://www.pewresearch.org/politics/2022/03/03/the-changing-political-geography-of-covid-19-over-the-last-two-years/\n\nMIT Election Data and Science Lab. (2021) County Presidential Election Returns 2000-2020. Accessed from the Harvard Dataverse [October 11, 2022]. https://doi.org/10.7910/DVN/VOQCHQ\n\nNational Center for Health Statistics. (2022). Provisional COVID-19 Deaths by County, and Race and Hispanic Origin. Accessed from the Centers for Disease Control [October 11, 2022]. https://data.cdc.gov/d/k8wy-p9cg\n\nWood, D. and Brumfiel, G. (2021). Pro-Trump counties now have far higher COVID death rates. Misinformation is to blame. NPR. December 5, 2021. https://www.npr.org/sections/health-shots/2021/12/05/1059828993/data-vaccine-misinformation-trump-counties-covid-death-rate\n\n\n[Need to add italics to references]",
    "supporting": [],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}