{
  "hash": "d6dc03097613b74aa7e2244f822775cf",
  "result": {
    "markdown": "---\ntitle: \"HW2\"\nauthor: \"Steph Roberts\"\ndesription: \"Homework 2 - Confidence Intervals\"\ndate: \"10/17/2022\"\nformat:\n  html:\n    toc: true\n    code-fold: true\n    code-copy: true\n    code-tools: true\ncategories:\n  - hw2\n  - confidence intervals\n  - Steph Roberts\n---\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(tidyverse)\n\nknitr::opts_chunk$set(echo = TRUE)\n```\n:::\n\n\n###Homework 2\n\n##Question 1 \n\nThe time between the date a patient was recommended for heart surgery and the surgery date for cardiac patients in Ontario was collected by the Cardiac Care Network (“Wait Times Data Guide,” Ministry of Health and Long-Term Care, Ontario, Canada, 2006). The sample mean and sample standard deviation for wait times (in days) of patients for two cardiac procedures are given in the accompanying table. Assume that the sample is representative of the Ontario population\n\nSurgical Procedure\nSample Size\nMean Wait Time\nStandard Deviation\nBypass\n539\n19\n10\nAngiography\n847\n18\n9\n\nConstruct the 90% confidence interval to estimate the actual mean wait time for each of the two procedures. Is the confidence interval narrower for angiography or bypass surgery?\n\n\n::: {.cell}\n\n```{.r .cell-code}\n#Assign values\nbypass_ss <- 539\nbypass_mean <- 19\nbypass_sd <- 10\nangio_ss <- 847\nangio_mean <- 18\nangio_sd <- 9\n\n#calculate bypass t-score\nalpha <- 0.1\nt_score_b <- qt(p = 1-alpha/2, df = bypass_ss-1)\nprint(t_score_b)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 1.647691\n```\n:::\n:::\n\nThe t-score for bypass wait time is 1.65.\n\n\n::: {.cell}\n\n```{.r .cell-code}\n#Calculate 90% confidence interval of bypass wait time\nCI_bypass <- c(bypass_mean - t_score_b * bypass_sd ,\n               bypass_mean + t_score_b * bypass_sd)\nprint(CI_bypass)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1]  2.523092 35.476908\n```\n:::\n:::\n\nThe 90% confidence interval for bypass wait time is 2.53 to 35.48 days. \n\n\n::: {.cell}\n\n```{.r .cell-code}\n#calculate angiography t-score\nalpha <- 0.1\nt_score_a <- qt(p = 1-alpha/2, df = angio_ss-1)\nprint(t_score_a)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 1.646657\n```\n:::\n:::\n\nThe t-score for bypass wait time is 1.65.\n\n\n::: {.cell}\n\n```{.r .cell-code}\n#Calculate 90% confidence interval of bypass wait time\nCI_angio <- c(angio_mean - t_score_a * angio_sd ,\n               angio_mean + t_score_a * angio_sd)\nprint(CI_angio)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1]  3.180089 32.819911\n```\n:::\n:::\n\nThe 90% confidence interval for angiography wait time is 3.18 to 32.82 days.\n\n\n##Question 2 \nA survey of 1031 adult Americans was carried out by the National Center for Public Policy. Assume that the sample is representative of adult Americans. Among those surveyed, 567 believed that college education is essential for success. Find the point estimate, p, of the proportion of all adult Americans who believe that a college education is essential for success. Construct and interpret a 95% confidence interval for p.\n\n\n::: {.cell}\n\n```{.r .cell-code}\n#Sample size\nn <- 1031\n\n#Number of those who believed that college education is essential for success\nk <- 567\n\n#find sample proportion\np <- k/n\np\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 0.5499515\n```\n:::\n\n```{.r .cell-code}\nprop.test(x=k, n=n, p=p, alternative=\"two.sided\")\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n\n\t1-sample proportions test without continuity correction\n\ndata:  k out of n, null probability p\nX-squared = 6.9637e-30, df = 1, p-value = 1\nalternative hypothesis: true p is not equal to 0.5499515\n95 percent confidence interval:\n 0.5194543 0.5800778\nsample estimates:\n        p \n0.5499515 \n```\n:::\n:::\n\nThe proportion of all adult Americans who believe that a college education is essential for success is 0.55.The confidence interval for the proportion is 0.52 to 0.58.\n\n\n##Question 3\nSuppose that the financial aid office of UMass Amherst seeks to estimate the mean cost of textbooks per semester for students. The estimate will be useful if it is within $5 of the true population mean (i.e. they want the confidence interval to have a length of $10 or less). The financial aid office is pretty sure that the amount spent on books varies widely, with most values between $30 and $200. They think that the population standard deviation is about a quarter of this range (in other words, you can assume they know the population standard deviation). Assuming the significance level to be 5%, what should be the size of the sample?\n\nThis information gives us a confidence interval of 10, a confidence level of 95%, and an unknown population size.\n\n::: {.cell}\n\n```{.r .cell-code}\nz <- 1.96\nbook_sd <- (200-30)/4\nmargin <- 5\n\nbook_ss <- ((z*book_sd)/margin)^2\nbook_ss\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 277.5556\n```\n:::\n:::\n\nThe sample size should be at least 278 students.\n\n\n##Question 4\nAccording to a union agreement, the mean income for all senior-level workers in a large service company equals $500 per week. A representative of a women’s group decides to analyze whether the mean income μ for female employees matches this norm. For a random sample of nine female employees, ȳ = $410 and s = 90.\n\nTest whether the mean income of female employees differs from $500 per week. Include assumptions, hypotheses, test statistic, and P-value. Interpret the result.\nReport the P-value for Ha : μ < 500. Interpret.\nReport and interpret the P-value for H a: μ > 500.\nHint: The P-values for the two possible one-sided tests must sum to 1.\n\n\nThe null hypothesis is that female employees income is $500, H0 : μ = 500.\nThe alternative hypothesis is that female employees income is not, H1 : μ ≠  500.\nA second alternative is that income is under $500, H2 : μ < 500.\nA third alternative is that income is greater than $500, H3 : μ > 500.\nWe assume that the sample is random and that the population has a normal distribution.\nWe will use a p-value of 0.05 and reject the null if it is any less.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nsample <- 9\nmean_income <- 410\ns <- 90\nμ <- 500\n\n#Calculate t-score\nt_score_income <- (mean_income-μ)/(s/sqrt(sample))\nt_score_income\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] -3\n```\n:::\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\n#Calculate p-value\nincome_p <- (pt(t_score_income, sample-1))*2\nincome_p\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 0.01707168\n```\n:::\n:::\n\nWe find a p-value of 0.017. With a p-value of less than 0.05, we reject the null hypothesis. The female employee mean income is not equal to that of all senior-level workers.\n\n\n::: {.cell}\n\n```{.r .cell-code}\n#Calculate p-value <500\nincome_p_lower <- pt(t_score_income, sample-1, lower.tail = TRUE)\nincome_p_lower\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 0.008535841\n```\n:::\n:::\n\nWe find a p-value of 0.009 when assessing the lower limits of the distribution. The smaller number suggests a stronger correlation. Again, we reject the null hypothesis. The mean female income is likely less than $500.\n\n\n::: {.cell}\n\n```{.r .cell-code}\n#Calculate p-value >500\nincome_p_upper <- pt(t_score_income, sample-1, lower.tail = FALSE)\nincome_p_upper\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 0.9914642\n```\n:::\n:::\n\nWe find a p-value of 0.99. Here the p-value is much greater than 0.05, so we fail to reject the null hypothesis. \n\n\n##Question 5\nJones and Smith separately conduct studies to test H0: μ = 500 against Ha : μ ≠ 500, each with n = 1000. Jones gets ȳ = 519.5, with se = 10.0. Smith gets ȳ = 519.7,\nwith se = 10.0.\nShow that t = 1.95 and P-value = 0.051 for Jones. Show that t = 1.97 and P-value = 0.049 for Smith.\nUsing α = 0.05, for each study indicate whether the result is “statistically significant.”\nUsing this example, explain the misleading aspects of reporting the result of a test as “P ≤ 0.05” versus “P > 0.05,” or as “reject H0” versus “Do not reject H0 ,” without reporting the actual P-value.\n\nNull hypothesis: H0: μ = 500\nAlternative hypothesis: Ha: μ ≠ 500\nWe will reject the null hypothesis at a p-value less than 0.05\nWe assume that the sample is random and that the population has a normal distribution.\n\n\n::: {.cell}\n\n```{.r .cell-code}\njmean <- 519.5\njse <- 10\nss <- 1000\nμ <- 500\nsmean <- 519.7\nsse <- 10\n\n#Calculate t-score for Jones study\nt_score_j <- (jmean-μ)/jse\nt_score_j\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 1.95\n```\n:::\n\n```{.r .cell-code}\n#Calculate p-value for Jones study\njp <- 2*pt(t_score_j, ss-1, lower.tail = FALSE)\njp\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 0.05145555\n```\n:::\n:::\n\nThe p-value for Jones's study is 0.051, which exceeds our threshold of 0.05. Therefore, we reject the null. \n\n\n::: {.cell}\n\n```{.r .cell-code}\n#Calculate t-score for Smith study\nt_score_s <- (smean-μ)/sse\nt_score_s\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 1.97\n```\n:::\n\n```{.r .cell-code}\n#Calculate p-value for Smith study\nsp <- 2*pt(t_score_s, ss-1, lower.tail = FALSE)\nsp\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 0.04911426\n```\n:::\n:::\n\nThe p-value for Smith's study is 0.049, which falls under our threshold of 0.05. Therefore, we fail to reject the null.\n\nThese studies have nearly identical means and p-values. It illustrates the importance of reporting the actually calculated p-value along with its interpretation. Without the number, we might conclude Jones's study indicates strong statistical significance while Smith's did not, when in fact they were almost identical. \n\n\n##Question 6\nAre the taxes on gasoline very high in the United States? According to the American Petroleum Institute, the per gallon federal tax that was levied on gasoline was 18.4 cents per gallon. However, state and local taxes vary over the same period. The sample data of gasoline taxes for 18 large cities is given below in the variable called gas_taxes.\n\ngas_taxes <- c(51.27, 47.43, 38.89, 41.95, 28.61, 41.29, 52.19, 49.48, 35.02, 48.13, 39.28, 54.41, 41.66, 30.28, 18.49, 38.72, 33.41, 45.02)\n\nIs there enough evidence to conclude at a 95% confidence level that the average tax per gallon of gas in the US in 2005 was less than 45 cents? Explain.\n\n\n::: {.cell}\n\n```{.r .cell-code}\ngas_taxes <- c(51.27, 47.43, 38.89, 41.95, 28.61, 41.29, 52.19, 49.48, 35.02, 48.13, 39.28, 54.41, 41.66, 30.28, 18.49, 38.72, 33.41, 45.02)\n\nt.test(gas_taxes, mu = 18.4)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n\n\tOne Sample t-test\n\ndata:  gas_taxes\nt = 10.238, df = 17, p-value = 1.095e-08\nalternative hypothesis: true mean is not equal to 18.4\n95 percent confidence interval:\n 36.23386 45.49169\nsample estimates:\nmean of x \n 40.86278 \n```\n:::\n:::\n\n\nThe 95% confidence level of state and local taxes per gallon is 36.23 to 45.49. We can interpret this by saying that if we took another 100 samples, 95 of them would have a mean that falls within our confidence interval. We cannot conclude, however, that the mean is less than 45 cents per gallon, because that number falls within our 95% confidence interval range. \n",
    "supporting": [],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}