{
  "hash": "8fdf01e4a04bf2a5679d74c4f8ec9baa",
  "result": {
    "markdown": "---\ntitle: \"Homework 2\"\nauthor: \"Donny Snyder\"\ndesription: \"Homework 2 Submission\"\ndate: \"10/17/2022\"\nformat:\n  html:\n    toc: true\n    code-fold: true\n    code-copy: true\n    code-tools: true\ncategories:\n  - hw2\n  - regression\n---\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(tidyverse)\n```\n\n::: {.cell-output .cell-output-stderr}\n```\n── Attaching packages ─────────────────────────────────────── tidyverse 1.3.2 ──\n✔ ggplot2 3.3.6      ✔ purrr   0.3.5 \n✔ tibble  3.1.8      ✔ dplyr   1.0.10\n✔ tidyr   1.2.1      ✔ stringr 1.4.1 \n✔ readr   2.1.3      ✔ forcats 0.5.2 \n── Conflicts ────────────────────────────────────────── tidyverse_conflicts() ──\n✖ dplyr::filter() masks stats::filter()\n✖ dplyr::lag()    masks stats::lag()\n```\n:::\n\n```{.r .cell-code}\nlibrary(dplyr)\n```\n:::\n\n\n# Question 1\n\n\n::: {.cell}\n\n```{.r .cell-code}\nbyPassConfInt <- NA\nbyPassConfInt[1] <- 19 + .9*(10/(sqrt(539)))\nbyPassConfInt[2] <- 19 - .9*(10/(sqrt(539)))\n\nangConfInt <- NA\nangConfInt[1] <- 18 + .9*(9/(sqrt(847)))\nangConfInt[2] <- 18 - .9*(9/(sqrt(847)))\n\nprint(byPassConfInt)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 19.38766 18.61234\n```\n:::\n\n```{.r .cell-code}\nprint(angConfInt)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 18.27832 17.72168\n```\n:::\n:::\n\nThe confidence interval is narrower than for angiography than for bypass surgery.\n\n# Question 2\n\n\n::: {.cell}\n\n```{.r .cell-code}\npointEstData <- NA\npointEstData[1:567] <- 1\npointEstData[568:1031] <- 0\npointSD <- sd(pointEstData)\npointEst <- 567/1031\npointConfInt <- NA\npointConfInt[1] <- pointEst + .95*(pointSD/(sqrt(1031)))\npointConfInt[2] <- pointEst - .95*(pointSD/(sqrt(1031)))\nprint(pointConfInt)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 0.5646779 0.5352251\n```\n:::\n:::\n\nThe confidence interval here suggests that we can assume with 95% confidence that between 56.5% of adult Americans and 53.5% believe that college education is essential for success.\n\n# Question 3\n\n\n::: {.cell}\n\n```{.r .cell-code}\npopSD <- (200 - 30)/4\ncriticalVal <- 1.96\nsampSize <- ((popSD * criticalVal)/5)^2\nprint(sampSize)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 277.5556\n```\n:::\n:::\n\nThe size of the sample should be 278.\n\n# Question 4a\n\nNull hypothesis: Womens income does not deviate from the mean income of senior-level workers.\n\nAlternative hypothesis: Womens income does deviate from the mean income of senior-level workers.\n\n\n::: {.cell}\n\n```{.r .cell-code}\ntStat <- (410 - 500)/(90/(sqrt(9)))\ndegreeFree <- 9-1\n2*pt(-tStat, degreeFree, lower.tail = FALSE)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 0.01707168\n```\n:::\n\n```{.r .cell-code}\npt(-tStat, degreeFree, lower.tail = FALSE)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 0.008535841\n```\n:::\n\n```{.r .cell-code}\npt(tStat, degreeFree, lower.tail = FALSE)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 0.9914642\n```\n:::\n:::\n\nThe p value of this test statistic and degrees of freedom is 0.017.\n\n#4b\nThe p-value for the one-tailed test h0 < 500 is 0.0085. This is half because it is only measuring half of the distribution.\n\n#4c\nThe p-value for the one-tailed test h0 > 500 is 0.9915. This is because this is measuring in the opposite direction of the actual mean.\n\n#Question 5\n\n::: {.cell}\n\n```{.r .cell-code}\ntStatJones <- (519.5 - 500)/(10)\ntStatSmith <- (519.7 - 500)/(10)\ndegreeFree <- 1000-1\n\n2*pt(tStatJones,degreeFree, lower.tail = FALSE)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 0.05145555\n```\n:::\n\n```{.r .cell-code}\n2*pt(tStatSmith,degreeFree, lower.tail = FALSE)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 0.04911426\n```\n:::\n:::\n\n#Question 5b\nAs you can see from the printed values, the Smith study is statistically significant while the Jones study is not.\n\n#Question 5c\nIf you do not report the p-value, you cannot tell how close the p-value is to being significant, so it can get rid of the value of running the study to not report it.\n\n#Question 6\n\n::: {.cell}\n\n```{.r .cell-code}\ngas_taxes <- c(51.27, 47.43, 38.89, 41.95, 28.61, 41.29, 52.19, 49.48, 35.02, 48.13, 39.28, 54.41, 41.66, 30.28, 18.49, 38.72, 33.41, 45.02)\n\ntStatGas <- (mean(gas_taxes) - 45)/(sqrt(sd(gas_taxes)/length(gas_taxes)))\ndegreeFree <- length(gas_taxes) - 1\n\n2*pt(-tStatGas,degreeFree, lower.tail = FALSE)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 2.341428e-05\n```\n:::\n:::\n\nYes there is enough evidence. The p-value is far below p = 0.05, at 0.0000234.",
    "supporting": [],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}