{
  "hash": "0fe5c7f89752fa10183750417d3f34b2",
  "result": {
    "markdown": "---\ntitle: \"Homework 2\"\nauthor: \"Saaradhaa M\"\ndate: \"10/10/2022\"\nformat: \n  html:\n    df-print: paged\n    toc: true\n    code-copy: true\n    code-tools: true\n    css: \"styles.css\"\ncategories:\n  - hw2\n---\n\n\n# Qn 1\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# calculate standard errors.\nSE_B <- 10/sqrt(539)\nSE_A <- 9/sqrt(847)\n\n# calculate t-values.\nCL <- 0.90  \nTA <- (1-CL)/2\ntvalue_b <- qt(p = 1-TA, df = 539-1)\ntvalue_a <- qt(p = 1-TA, df = 847-1)\n\n# calculate CI for bypass.\nCIB <- c(19 - tvalue_b * SE_B,\n        19 + tvalue_b * SE_B)\nCIB\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 18.29029 19.70971\n```\n:::\n\n```{.r .cell-code}\n# calculate CI range for bypass.\n(19 + tvalue_b * SE_B) - (19 - tvalue_b * SE_B)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 1.419421\n```\n:::\n\n```{.r .cell-code}\n# calculate CI for angiography.\nCIA <- c(18 - tvalue_a * SE_A,\n        18 + tvalue_a * SE_A)\nCIA\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 17.49078 18.50922\n```\n:::\n\n```{.r .cell-code}\n# calculate CI range for angiography.\n(18 + tvalue_a * SE_A) - (18 - tvalue_a * SE_A)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 1.018436\n```\n:::\n:::\n\n\nThe 90% CI is narrower for angiography.\n\n# Qn 2\n\n\n::: {.cell}\n\n```{.r .cell-code}\nset.seed(0)\nprop <- prop.test(x=567, n=1031)\nprop\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n\n\t1-sample proportions test with continuity correction\n\ndata:  567 out of 1031, null probability 0.5\nX-squared = 10.091, df = 1, p-value = 0.00149\nalternative hypothesis: true p is not equal to 0.5\n95 percent confidence interval:\n 0.5189682 0.5805580\nsample estimates:\n        p \n0.5499515 \n```\n:::\n:::\n\n\nThe 95% CI is \\[0.5189682, 0.580558\\], which includes the point estimate 0.5499515 and excludes 0.5. Hence, we can reject the null hypothesis that the true probability is 0.5 at the 5% significance level, *p* = 0.0014898.\n\n# Qn 3\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# calculate population SD.\nPSD <- (200-30)/4\n\n# calculate sample size.\nn <- round(((1.96*PSD)/5)^2)\n```\n:::\n\n\nThe minimum required sample size is 278.\n\n# Qn 4a\n\nAssumptions: H~0~ is true, observations are independent of one another, *y* is continuous and sample is approximately normally distributed. H~0~: μ = 500 H~a~: μ ≠ 500\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# calculate t-statistic.\nt <- (410-500)/(90/sqrt(9))\n\n# calculate p-value.\np <- 2*pt(q=abs(t), df=8, lower.tail=FALSE)\np\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 0.01707168\n```\n:::\n:::\n\n\nWe can reject the null hypothesis at the 5% significance level, *t*(8) = 3, *p* = 0.0170717. Female employees' mean income significantly differs from \\$500 per week.\n\n\\[I have a question - I am confused on whether I was right to use the absolute value here, and when we should use absolute values.\\]\n\n# Qn 4b\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# calculate p-value.\np2 <- pt(q=t, df=8, lower.tail=TRUE)\np2\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 0.008535841\n```\n:::\n:::\n\n\nWe can reject the null hypothesis at the 5% significance level, *t*(8)= -3, *p* = 0.0085358. Female employees' mean income is significantly less than \\$500 per week.\n\n# Qn 4c\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# calculate p-value.\np3 <- pt(q=t, df=8, lower.tail=FALSE)\np3\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 0.9914642\n```\n:::\n:::\n\n\nWe fail to reject the null hypothesis at the 5% significance level, *t*(8)= -3, *p* = 0.9914642. Female employees' mean income is [**not**]{.underline} significantly more than \\$500 per week.\n\n# Qn 5a\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# calculate SD for Jones and Smith.\nSD <- 10*sqrt(1000)\n\n# calculate t for Jones.\nt_j <- ((519.5-500)/SD) * sqrt(1000)\nt_j\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 1.95\n```\n:::\n\n```{.r .cell-code}\n# calculate p-value for Jones.\np_j <- 2*(pt(q=t_j, df=999, lower.tail=FALSE))\np_j\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 0.05145555\n```\n:::\n\n```{.r .cell-code}\n# calculate t for Smith.\nt_s <- ((519.7-500)/SD) * sqrt(1000)\nt_s\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 1.97\n```\n:::\n\n```{.r .cell-code}\n# calculate p-value for Smith.\np_s <- 2*(pt(q=t_s, df=999, lower.tail=FALSE))\np_s\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 0.04911426\n```\n:::\n:::\n\n\n# Qn 5b\n\nThe result is statistically significant for Smith, but not Jones.\n\n# Qn 5c\n\nIt is useful to report the exact p-value in cases like this, when the p-value is very close to alpha. It helps the reader to understand (1) why it was/was not rejected, and (2) how much evidence there is against the null hypothesis.\n\n# Qn 6\n\n\n::: {.cell}\n\n```{.r .cell-code}\n#create variable.\ngas_taxes <- c(51.27, 47.43, 38.89, 41.95, 28.61, 41.29, 52.19, 49.48, 35.02, 48.13, 39.28, 54.41, 41.66, 30.28, 18.49, 38.72, 33.41, 45.02)\n\n# do t-test.\ntax <- t.test(gas_taxes, alternative=\"less\",mu=45)\ntax\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n\n\tOne Sample t-test\n\ndata:  gas_taxes\nt = -1.8857, df = 17, p-value = 0.03827\nalternative hypothesis: true mean is less than 45\n95 percent confidence interval:\n     -Inf 44.67946\nsample estimates:\nmean of x \n 40.86278 \n```\n:::\n:::\n\n\nThe 95% CI is \\[-\\infty{}, 44.6794598\\], which includes the estimated mean 40.8627778 and excludes 45. Hence, we can reject the null hypothesis at the 5% significance level, *t*(17)= -1.8857058, *p* = 0.0382708. The average tax per gallon in the US in 2005 was significantly less than 45 cents.\n",
    "supporting": [],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {
      "include-in-header": [
        "<link href=\"../site_libs/pagedtable-1.1/css/pagedtable.css\" rel=\"stylesheet\" />\n<script src=\"../site_libs/pagedtable-1.1/js/pagedtable.js\"></script>\n"
      ]
    },
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}