{
  "hash": "462705616a3a2e5a20bb12c5833adaf1",
  "result": {
    "markdown": "---\ntitle: \"Homework 1\"\nauthor: \"Lindsay Jones\"\ndescription: The first homework on descriptive statistics and probability.\ndate: \"10/02/2022\"\nformat:\n  html:\n    toc: true\n    code-fold: true\n    code-copy: true\n    code-tools: true\ncategories:\n  - hw1\n  - desriptive statistics \n  - probability\n---\n\n\n# Homework 1\n\n## Setup\n\nFirst I'll load the libraries and read in the data.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(readr)\nlibrary(ggplot2)\nlibrary(dplyr)\n```\n\n::: {.cell-output .cell-output-stderr}\n```\n\nAttaching package: 'dplyr'\n```\n:::\n\n::: {.cell-output .cell-output-stderr}\n```\nThe following objects are masked from 'package:stats':\n\n    filter, lag\n```\n:::\n\n::: {.cell-output .cell-output-stderr}\n```\nThe following objects are masked from 'package:base':\n\n    intersect, setdiff, setequal, union\n```\n:::\n\n```{.r .cell-code}\nlibrary(readxl)\nlc <- read_excel(\"_data/LungCapData.xls\")\n```\n:::\n\n\n## 1) Use the LungCapData to answer the following questions.\n\n### a. What does the distribution of LungCap look like?\n\nThe distribution of lung capacity is as follows:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nhist(lc$LungCap)\n```\n\n::: {.cell-output-display}\n![](Homework-1-LJones_files/figure-html/unnamed-chunk-2-1.png){width=672}\n:::\n:::\n\n\nThe histogram appears close to the normal distribution.\n\n### b. Compare the probability distribution of the LungCap with respect to Males and Females\n\n\n::: {.cell}\n\n```{.r .cell-code}\nboxplot(LungCap~Gender, data=lc)\n```\n\n::: {.cell-output-display}\n![](Homework-1-LJones_files/figure-html/unnamed-chunk-3-1.png){width=672}\n:::\n:::\n\n\n### c. Compare the mean lung capacities for smokers and non-smokers. Does it make sense?\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlc %>%\n  group_by(Smoke) %>%\n  summarize(Mean = mean(LungCap))\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n# A tibble: 2 × 2\n  Smoke  Mean\n  <chr> <dbl>\n1 no     7.77\n2 yes    8.65\n```\n:::\n:::\n\n\nInterestingly, the mean lung capacity is higher for smokers than it is for non-smokers.\n\n### d. Examine the relationship between Smoking and Lung Capacity within age groups: \"less than or equal to 13\", \"14 to 15\", \"16 to 17\", and \"greater than or equal to 18\".\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlcbyagegrp <- lc %>% \n  mutate(age_group = case_when(\n    Age <=13 ~ \"13 and Under\",\n    Age >=14 & Age <=15 ~\"14-15\",\n    Age >=16 & Age <=17 ~\"16 - 17\",\n    Age >=18 ~\"18+\")) %>% \n  arrange(age_group, Age)\n\nggplot(lcbyagegrp, aes(x = LungCap)) +\n  geom_histogram() +\n  facet_grid(age_group ~ Smoke)\n```\n\n::: {.cell-output .cell-output-stderr}\n```\n`stat_bin()` using `bins = 30`. Pick better value with `binwidth`.\n```\n:::\n\n::: {.cell-output-display}\n![](Homework-1-LJones_files/figure-html/unnamed-chunk-5-1.png){width=672}\n:::\n:::\n\n\n### e. Compare the lung capacities for smokers and non-smokers within each age group.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlcbyagegrp %>%\n  group_by(age_group, Smoke) %>%\n  summarize(Mean = mean(LungCap))\n```\n\n::: {.cell-output .cell-output-stderr}\n```\n`summarise()` has grouped output by 'age_group'. You can override using the\n`.groups` argument.\n```\n:::\n\n::: {.cell-output .cell-output-stdout}\n```\n# A tibble: 8 × 3\n# Groups:   age_group [4]\n  age_group    Smoke  Mean\n  <chr>        <chr> <dbl>\n1 13 and Under no     6.36\n2 13 and Under yes    7.20\n3 14-15        no     9.14\n4 14-15        yes    8.39\n5 16 - 17      no    10.5 \n6 16 - 17      yes    9.38\n7 18+          no    11.1 \n8 18+          yes   10.5 \n```\n:::\n:::\n\n\n#### Is your answer different from the one in part d? What could possibly be going on here\n\nThe mean lung capacity for smokers aged 13 and under is higher than that of non-smokers in the same age group, which defies expectation. The rest of the age groups meet that expectation. There may be an error or extreme outlier in the data for smokers aged 13 and under.\n\n### f. Calculate the correlation and covariance between Lung Capacity and Age.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlc %>% cov(Age, LungCap)\n```\n\n::: {.cell-output .cell-output-error}\n```\nError in pmatch(use, c(\"all.obs\", \"complete.obs\", \"pairwise.complete.obs\", : object 'LungCap' not found\n```\n:::\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\n#correlation\ncor(lc$LungCap,lc$Age)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 0.8196749\n```\n:::\n\n```{.r .cell-code}\n#covariance\ncov(lc$LungCap, lc$Age)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 8.738289\n```\n:::\n:::\n\n\nThe correlation is very close to positive 1, indicating a strong positive correlation between between lung capacity and age. The covariance being a positive number indicates a positive relationship.\n\n## 2) Let X = number of prior convictions for prisoners at a state prison at which there are 810 prisoners.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nX <- c(0:4)\nFrequency <- c(128, 434, 160, 64, 24)\n\ndf <- data.frame(X, Frequency)\n\ndf\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n  X Frequency\n1 0       128\n2 1       434\n3 2       160\n4 3        64\n5 4        24\n```\n:::\n:::\n\n\n### a. What is the probability that a randomly selected inmate has exactly 2 prior convictions?\n\n\n::: {.cell}\n\n```{.r .cell-code}\ndf2 <- mutate(df, Probability = Frequency/sum(Frequency))\ndf2\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n  X Frequency Probability\n1 0       128  0.15802469\n2 1       434  0.53580247\n3 2       160  0.19753086\n4 3        64  0.07901235\n5 4        24  0.02962963\n```\n:::\n:::\n\n\nThe probability is about 19.75%.\n\n### b. What is the probability that a randomly selected inmate has fewer than 2 prior convictions?\n\n\n::: {.cell}\n\n```{.r .cell-code}\nb2 <- df2 %>% \n  filter(X < 2)\n\nsum(b2$Probability)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 0.6938272\n```\n:::\n:::\n\n\nThe probability is about 69%.\n\n### c. What is the probability that a randomly selected inmate has 2 or fewer prior convictions?\n\n\n::: {.cell}\n\n```{.r .cell-code}\nc2 <- df2 %>% \n  filter(X <= 2)\n\nsum(c2$Probability)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 0.891358\n```\n:::\n:::\n\n\nThe probability is about 89%.\n\n### d. What is the probability that a randomly selected inmate has more than 2 prior convictions?\n\n\n::: {.cell}\n\n```{.r .cell-code}\nd2 <- df2 %>% \n  filter(X > 2)\n\nsum(d2$Probability)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 0.108642\n```\n:::\n:::\n\n\nThe probability is about 10.9%.\n\n### e. What is the expected value for the number of prior convictions?\n\n\n::: {.cell}\n\n```{.r .cell-code}\ne <- weighted.mean(df2$X, df2$Probability)\ne\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 1.28642\n```\n:::\n:::\n\n\nThe expected number of prior convictions is about 1.286.\n\n### f. Calculate the variance and the standard deviation for the Prior Convictions.\n\n\n::: {.cell}\n\n```{.r .cell-code}\n#variance\nvariance <- (sum(Frequency*((X-e)^2)))/(sum(Frequency)-1)\nvariance\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 0.8572937\n```\n:::\n\n```{.r .cell-code}\n#standard deviation\nsd <- sqrt(variance)\nsd\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 0.9259016\n```\n:::\n:::\n\n\nThe variance of prior convictions is about 0.857, and the standard deviation (simply, the square root of the variance) is about 0.926.\n",
    "supporting": [
      "Homework-1-LJones_files"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}