{
  "hash": "746b2890b60d113a8f6cccaabb1351ea",
  "result": {
    "markdown": "---\ntitle: \"Duryea Homework 1\"\nauthor: \"Emily Duryea\"\ndescription: \"Homework 1 for DACSS 603\"\ndate: \"10/03/2022\"\nformat:\n  html: \n    toc: true\n    code-fold: true\n    code-copy: true\n    code-tools: true\ncategories:\n  - hw1\n  - descriptive statistics\n  - probability\n---\n\n\nQuestion 1\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(ggplot2)\nlibrary(dplyr)\n```\n\n::: {.cell-output .cell-output-stderr}\n```\n\nAttaching package: 'dplyr'\n```\n:::\n\n::: {.cell-output .cell-output-stderr}\n```\nThe following objects are masked from 'package:stats':\n\n    filter, lag\n```\n:::\n\n::: {.cell-output .cell-output-stderr}\n```\nThe following objects are masked from 'package:base':\n\n    intersect, setdiff, setequal, union\n```\n:::\n\n```{.r .cell-code}\nlibrary(readxl)\ndf <- read_excel(\"_data/LungCapData.xls\")  \n\nhist(df$LungCap)\n```\n\n::: {.cell-output-display}\n![](Emily-Duryea-Homework-1_files/figure-html/unnamed-chunk-1-1.png){width=672}\n:::\n:::\n\n\nPart A: Plotting probability density histogram\n\n\n::: {.cell}\n\n```{.r .cell-code}\nhist(df$LungCap, \n     col=\"yellow\",\n     border=\"black\",\n     prob = TRUE,\n     xlab = \"LungCap\",\n     main = \"Density Plot\")\n\nlines(density(df$LungCap),\n      lwd = 2,\n      col = \"chocolate3\")\n```\n\n::: {.cell-output-display}\n![](Emily-Duryea-Homework-1_files/figure-html/unnamed-chunk-2-1.png){width=672}\n:::\n:::\n\n\nPart B: Compare the probability distribution of the LungCap with respect to Males and Females\n\n\n::: {.cell}\n\n```{.r .cell-code}\nggplot(df, aes(y = dnorm(LungCap), color = Gender)) +\n  geom_boxplot() +\n  labs(title = \"LungCap Probability Distribution for Males and Females\", y = \"Probability density\")\n```\n\n::: {.cell-output-display}\n![](Emily-Duryea-Homework-1_files/figure-html/unnamed-chunk-3-1.png){width=672}\n:::\n:::\n\n\nPart C: Compare the mean lung capacities for smokers and non-smokers\n\n\n::: {.cell}\n\n```{.r .cell-code}\nmean_smoking <- df %>%\n  group_by(Smoke) %>%\n  summarise(mean = mean(LungCap))\nmean_smoking\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n# A tibble: 2 × 2\n  Smoke  mean\n  <chr> <dbl>\n1 no     7.77\n2 yes    8.65\n```\n:::\n:::\n\n\nThe means of smokers vs non smokers does not make sense since non smokers have a lower mean lung cap, when one would think it would be the other way around. However, limited data is provided on the sample, so there could be other factors in play.\n\nPart D: Examine the relationship between Smoking and Lung Capacity within age groups: \"less than or equal to 13\", \"14 to 15\", \"16 to 17\", and \"greater than or equal to 18\"\n\n\n::: {.cell}\n\n```{.r .cell-code}\ndf <- mutate(df, AgeGroup = case_when(Age <= 13 ~ \"less than or equal to 13\",\n                                    Age == 14 | Age == 15 ~ \"14 to 15\",\n                                    Age == 16 | Age == 17 ~ \"16 to 17\",\n                                    Age >= 18 ~ \"greater than or equal to 18\"))\n\ndf %>%\n  ggplot(aes(y = LungCap, color = Smoke)) +\n  geom_histogram(bins = 25) +\n  facet_wrap(vars(AgeGroup)) +\n  theme_classic() + \n  labs(title = \"LungCap and Smoke based on age groups\", y = \"Lung Capacity\", x = \"Frequency\")\n```\n\n::: {.cell-output-display}\n![](Emily-Duryea-Homework-1_files/figure-html/unnamed-chunk-5-1.png){width=672}\n:::\n:::\n\n\nBased on the histograms, Part D seems to contrast with Part C, since the plots seem to demonstrate non-smokers having higher lung capacity than smokers in all age groups. Additionally, lung capacity appears to decrease with age based on the graph.\n\nPart E: Compare the lung capacities for smokers and non-smokers within each age group\n\n\n::: {.cell}\n\n```{.r .cell-code}\ndf %>%\n  ggplot(aes(x = Age, y = LungCap, color = Smoke)) +\n  geom_line() +\n  facet_wrap(vars(Smoke)) +\n  labs(title = \"LungCap and Smoke based on age and smoker vs nonsmoker\", y = \"Lung Capacity\", x = \"Age\")\n```\n\n::: {.cell-output-display}\n![](Emily-Duryea-Homework-1_files/figure-html/unnamed-chunk-6-1.png){width=672}\n:::\n:::\n\n\nBased on information gained in Part D and Part E, it appears that lung capacity decreases with age, and, despite the means in Part C, lung capacity is higher for non-smokers.\n\nPart F: Calculate the correlation and covariance between Lung Capacity and Age\n\n\n::: {.cell}\n\n```{.r .cell-code}\nCov_lungcapage <- cov(df$LungCap, df$Age)\nCor_lungcapeage <- cor(df$LungCap, df$Age)\nCov_lungcapage\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 8.738289\n```\n:::\n\n```{.r .cell-code}\nCor_lungcapeage\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 0.8196749\n```\n:::\n:::\n\n\nBecause both the covariance and correlation are positive numbers, the relationship between lung capacity and age are positively related, meaning as one increases, the other also increases in a proportional manner.\n\nQuestion 2\n\n\n::: {.cell}\n\n```{.r .cell-code}\nPrior_Convictions <- c(0:4)\nInmate_Number <- c(128, 434, 160, 64, 24)\nip <- tibble(Prior_Convictions, Inmate_Number)\n\nip <- mutate(ip, Probability = Inmate_Number/sum(Inmate_Number))\nip\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n# A tibble: 5 × 3\n  Prior_Convictions Inmate_Number Probability\n              <int>         <dbl>       <dbl>\n1                 0           128      0.158 \n2                 1           434      0.536 \n3                 2           160      0.198 \n4                 3            64      0.0790\n5                 4            24      0.0296\n```\n:::\n:::\n\n\nPart A: What is the probability that a randomly selected inmate has exactly 2 prior convictions?\n\n\n::: {.cell}\n\n```{.r .cell-code}\nip %>%\n  filter(Prior_Convictions == 2) %>%\n  select(Probability)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n# A tibble: 1 × 1\n  Probability\n        <dbl>\n1       0.198\n```\n:::\n:::\n\n\nThe probability that a randomly selected inmate has exactly two prior convictions is 0.1975309.\n\nPart B: What is the probability that a randomly selected inmate has fewer than 2 prior convictions?\n\n\n::: {.cell}\n\n```{.r .cell-code}\npartb <- ip %>%\n  filter(Prior_Convictions < 2)\nsum(partb$Probability)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 0.6938272\n```\n:::\n:::\n\n\nThe probability that a randomly selected inmate has fewer than two prior convictions is 0.6938272.\n\nPart C: What is the probability that a randomly selected inmate has 2 or fewer prior convictions?\n\n\n::: {.cell}\n\n```{.r .cell-code}\npartc <- ip %>%\n  filter(Prior_Convictions <= 2)\nsum(partc$Probability)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 0.891358\n```\n:::\n:::\n\n\nThe probability that a randomly selected inmate has two or fewer prior convictions is 0.891358.\n\nPart D: What is the probability that a randomly selected inmate has more than 2 prior convictions?\n\n\n::: {.cell}\n\n```{.r .cell-code}\npartd <- ip %>%\n  filter(Prior_Convictions > 2)\nsum(partd$Probability)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 0.108642\n```\n:::\n:::\n\n\nThe probability that a randomly selected inmate has more than two prior convictions is 0.108642.\n\nPart E: What is the expected value for the number of prior convictions?\n\n\n::: {.cell}\n\n```{.r .cell-code}\nip <- mutate(ip, vl = Prior_Convictions*Probability)\nparte <- sum(ip$vl)\nparte\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 1.28642\n```\n:::\n:::\n\n\nThe expected value for the number of prior convictions is 1.28642.\n\nPart F: Calculate the variance and the standard deviation for the Prior Convictions\n\n\n::: {.cell}\n\n```{.r .cell-code}\nip_var <-sum(((ip$Prior_Convictions-parte)^2)*ip$Probability)\nip_var\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 0.8562353\n```\n:::\n\n```{.r .cell-code}\nsqrt(ip_var)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 0.9253298\n```\n:::\n:::\n\n\nThe variance for prior convictions is 0.8562353 and the standard deviation is 0.9253298.\n",
    "supporting": [
      "Emily-Duryea-Homework-1_files"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}