{
  "hash": "3efedd07d639eedb06f237d6c3199af9",
  "result": {
    "markdown": "---\ntitle: \"Homework 2\"\nauthor: \"Steve O'Neill\"\ndescription: \"Probability Distributions\"\ndate: \"09/20/2022\"\ndf-paged: true\nformat:\n  html:\n    toc: true\n    code-fold: true\n    code-copy: true\n    code-tools: true\ncategories:\n  - hw2\n---\n\n\n### Question 1.\n\n> \"The time between the date a patient was recommended for heart surgery and the surgery date for cardiac patients in Ontario was collected by the Cardiac Care Network (\"Wait Times Data Guide,\" Ministry of Health and Long-Term Care, Ontario, Canada, 2006). The sample mean and sample standard deviation for wait times (in days) of patients for two cardiac procedures are given in the accompanying table. Assume that the sample is representative of the Ontario population\"\n\n\n::: {.cell}\n\n```{.r .cell-code}\nbypass <- data.frame(sample_size = 539,\n                     mean_wait_time = 19,\n                     standard_dev = 10)\nbypass \n```\n\n::: {.cell-output .cell-output-stdout}\n```\n  sample_size mean_wait_time standard_dev\n1         539             19           10\n```\n:::\n\n```{.r .cell-code}\nangiography <- data.frame(sample_size = 847,\n                     mean_wait_time = 18,\n                     standard_dev = 9)\nangiography\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n  sample_size mean_wait_time standard_dev\n1         847             18            9\n```\n:::\n:::\n\n\n> Construct the 90% confidence interval to estimate the actual mean wait time for each of the two procedures. Is the confidence interval narrower for angiography or bypass surgery?\n\n### Bypass\n\nHere is a manual way of doing so:\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# standard error\nstandard_error <- bypass$standard_dev / sqrt(bypass$sample_size)\nstandard_error\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 0.4307305\n```\n:::\n\n```{.r .cell-code}\n#Specify a confidence level, calculate the area of the two tales:\nconfidence_level <- 0.90  \n# how much area should be in each tail of the distribution for 95% to be in the middle?\ntail_area <- (1-confidence_level)/2\ntail_area\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 0.05\n```\n:::\n\n```{.r .cell-code}\n# t-value\nt_score <- qt(p = 1-tail_area, df = bypass$sample_size-1)\nt_score\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 1.647691\n```\n:::\n\n```{.r .cell-code}\n# plug everything back in\n# computing above calculations in a formula to calculate confidence interval\nCI <- c(bypass$mean_wait_time - t_score * standard_error,\n        bypass$mean_wait_time + t_score * standard_error)\nprint(CI)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 18.29029 19.70971\n```\n:::\n\n```{.r .cell-code}\n#margin of error\nprint(t_score * standard_error)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 0.7097107\n```\n:::\n:::\n\n\nThe 90% confidence interval for `bypass` is `18.29029 19.70971`. So the estimated wait time is between those two values.\n\n### Angiography\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# standard error\nstandard_error <- angiography$standard_dev / sqrt(angiography$sample_size)\nstandard_error\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 0.3092437\n```\n:::\n\n```{.r .cell-code}\n#Specify a confidence level, calculate the area of the two tales:\nconfidence_level <- 0.90  \n# how much area should be in each tail of the distribution for 95% to be in the middle?\ntail_area <- (1-confidence_level)/2\ntail_area\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 0.05\n```\n:::\n\n```{.r .cell-code}\n# t-value\nt_score <- qt(p = 1-tail_area, df = angiography$sample_size-1)\nt_score\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 1.646657\n```\n:::\n\n```{.r .cell-code}\n# plug everything back in\n# computing above calculations in a formula to calculate confidence interval\nCI <- c(angiography$mean_wait_time - t_score * standard_error,\n        angiography$mean_wait_time + t_score * standard_error)\nprint(CI)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 17.49078 18.50922\n```\n:::\n\n```{.r .cell-code}\n#margin of error\nprint(t_score * standard_error)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 0.5092182\n```\n:::\n:::\n\n\nThe 90% confidence interval for `bypass` is `17.49078 18.50922`\n\nThe 90% confidence interval for angiography is narrower than that of bypass. Their margins of error are `0.5092182` and `0.7097107`, respectively.\n\n## Question 2\n\n> A survey of 1031 adult Americans was carried out by the National Center for Public Policy. Assume that the sample is representative of adult Americans. Among those surveyed, 567 believed that college education is essential for success. Find the point estimate, p, of the proportion of all adult Americans who believe that a college education is essential for success. Construct and interpret a 95% confidence interval for p.\n\n\n::: {.cell}\n\n```{.r .cell-code}\ncollege_n <- 1031\ncollege_k <- 567\ncollege_p <- college_k/college_n\ncollege_p\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 0.5499515\n```\n:::\n:::\n\n\nThe point estimate for the proportion of all adult Americans who believe that a college education is essential for success is simply `0.5499515`.\n\n\n::: {.cell}\n\n```{.r .cell-code}\ncollege_moe <- qnorm(0.975)*sqrt(college_p*(1-college_p)/college_n)\ncollege_moe\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 0.03036761\n```\n:::\n\n```{.r .cell-code}\ncollege_CI_low <- college_p - college_moe\ncollege_CI_high <- college_p + college_moe\ncollege_CI_low\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 0.5195839\n```\n:::\n\n```{.r .cell-code}\ncollege_CI_high\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 0.5803191\n```\n:::\n:::\n\n\nThe 95% confidence interval for the point estimate is \\[`0.5195839`, `0.5803191`\\].\n\n## Question 3\n\n> Suppose that the financial aid office of UMass Amherst seeks to estimate the mean cost of textbooks per semester for students. The estimate will be useful if it is within \\$5 of the true population mean (i.e. they want the confidence interval to have a length of \\$10 or less). The financial aid office is pretty sure that the amount spent on books varies widely, with most values between \\$30 and \\$200. They think that the population standard deviation is about a quarter of this range (in other words, you can assume they know the population standard deviation). Assuming the significance level to be 5%, what should be the size of the sample?\n\n\n::: {.cell}\n\n```{.r .cell-code}\n#The estimate will be useful if it is within $5 of the true population mean\nbooks_moe <- 5\n#The financial aid office is pretty sure that the amount spent on books varies widely, with most values between $30 and $200.\nbooks_range <- (200-30)\n#They think that the population standard deviation is about a quarter of this range\nbooks_sd <- books_range / 4\nbooks_sd\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 42.5\n```\n:::\n:::\n\n\nA 5% alpha means a 95% confidence level. Conventionally we know the 'critical value' for the 95% confidence interval is 1.96\n\nUnfortunately, I'm missing the equation that lets us find the sample size from these values!\n\n## Question 4\n\n> According to a union agreement, the mean income for all senior-level workers in a large service company equals \\$500 per week. A representative of a women's group decides to analyze whether the mean income μ for female employees matches this norm. For a random sample of nine female employees, ȳ = \\$410 and s = 90.Test whether the mean income of female employees differs from \\$500 per week. Include assumptions, hypotheses, test statistic, and P-value. Interpret the result.\n\n\n::: {.cell}\n\n```{.r .cell-code}\n#the mean income for all senior-level workers in a large service company equals $500 per week.\nunion_pop_mean = 500\n#For a random sample of nine female employees,\nunion_sample_size = 9\n# ȳ = $410\nunion_sample_mean = 410\n# and s = 90\nunion_sample_sd = 90\n```\n:::\n\n\n### T-statistic\n\nAssuming the sample is normally distributed, the formula for a t-statistic is: (sample mean - population mean) / (sample standard deviation / square root of sample size)\n\n\n::: {.cell}\n\n```{.r .cell-code}\ntstatistic <- (union_sample_mean - union_pop_mean) / (union_sample_sd / sqrt(union_sample_size))\ntstatistic\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] -3\n```\n:::\n:::\n\nThe t-statistic is -3.\n\n### Hypotheses\n\nIn this case, the null hypothesis is that the mean income for female employees matches \\$500/wk. The alternate hypothesis is that it does not equal \\$500/wk.\n\n`pt` takes the T-statistic and degrees of freedom and returns the p-value to the left. If we multiply it by two, it becomes 'two-tailed':\n\n\n::: {.cell}\n\n```{.r .cell-code}\n2 * pt(-3, (union_sample_size - 1))\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 0.01707168\n```\n:::\n:::\n\n\nThis two-tailed test returns a p-value of `0.01707168` his is well under the significance level of 5%, meaning that there is only a 1.7 percent chance of receiving as extreme a result as this under the null hypothesis. Therefore the null hypothesis is said to be rejected.\n\n# Alernate hypothesis of μ \\< 500\n\n> Report the P-value for Ha : μ \\< 500. Interpret.\n\nThis is similar, except not multiplied by 2:\n\n\n::: {.cell}\n\n```{.r .cell-code}\npt(-3, (union_sample_size - 1))\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 0.008535841\n```\n:::\n:::\n\n\nThere is only a .8 percent probability that we would observe our values if the mean income was 500, so the null hypothesis is rejected.\n\n# H a of μ \\> 500\n\n> Report and interpret the P-value for H a: μ \\> 500\n\n\n::: {.cell}\n\n```{.r .cell-code}\npt(-3, (union_sample_size - 1), lower.tail = FALSE)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 0.9914642\n```\n:::\n:::\n\n\nIf the alternative hypothesis is that the sample mean is greater than 500, we would see values like those we collected over 99% of the time, and fail to reject the null hypothesis.\n\n## Question 5\n\n> Jones and Smith separately conduct studies to test H0: μ = 500 against Ha : μ ≠ 500, each with n = 1000. Jones gets ȳ = 519.5, with se = 10.0. Smith gets ȳ = 519.7, with se = 10.0\n\n\n::: {.cell}\n\n```{.r .cell-code}\njones_smith_pop_mean = 500\njones_smith_sample_size = 10000\n\njones_sample_mean = 519.5\nsmith_sample_mean = 519.7\n\njones_smith_se = 10\n```\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\njones_t_statistic <- (jones_sample_mean - jones_smith_pop_mean) / jones_smith_se\njones_t_statistic\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 1.95\n```\n:::\n\n```{.r .cell-code}\njones_p_value <- 2*pt(jones_t_statistic, (jones_smith_sample_size - 1), lower.tail = FALSE)\njones_p_value\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 0.05120403\n```\n:::\n\n```{.r .cell-code}\nsmith_t_statistic <- (smith_sample_mean - jones_smith_pop_mean) / jones_smith_se\nsmith_t_statistic\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 1.97\n```\n:::\n\n```{.r .cell-code}\nsmith_p_value <- 2*pt(smith_t_statistic, (jones_smith_sample_size - 1), lower.tail = FALSE)\nsmith_p_value\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 0.04886592\n```\n:::\n:::\n\n\n> Using α = 0.05, for each study indicate whether the result is \"statistically significant.\"\n\nUsing an alpha of .05, Jones' p value is not 'statistically significant', but Smith's is.\n\nBoth Jones and Smith's results should be presented with the P-values included so that knowledgeable people can see how borderline they are. Alternately, different significance levels could be adopted - or the sample size could be increased.\n\n## Question 6\n\nAre the taxes on gasoline very high in the United States? According to the American Petroleum Institute, the per gallon federal tax that was levied on gasoline was 18.4 cents per gallon. However, state and local taxes vary over the same period. The sample data of gasoline taxes for 18 large cities is given below in the variable called gas_taxes.\n\n\n::: {.cell}\n\n```{.r .cell-code}\ngas_taxes <- c(51.27, 47.43, 38.89, 41.95, 28.61, 41.29, 52.19, 49.48, 35.02, 48.13, 39.28, 54.41, 41.66, 30.28, 18.49, 38.72, 33.41, 45.02)\n```\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\ngas_mean <- gas_taxes %>% mean()\n```\n\n::: {.cell-output .cell-output-error}\n```\nError in gas_taxes %>% mean(): could not find function \"%>%\"\n```\n:::\n:::\n\n\n> Is there enough evidence to conclude at a 95% confidence level that the average tax per gallon of gas in the US in 2005 was less than 45 cents? Explain.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nt.test(gas_taxes, mu = gas_mean, alternative = 'less')\n```\n\n::: {.cell-output .cell-output-error}\n```\nError in t.test.default(gas_taxes, mu = gas_mean, alternative = \"less\"): object 'gas_mean' not found\n```\n:::\n:::\n\n\nWith the information we have, I am not sure if we have enough evidence to conclude about the average tax per gallon **in 2005**. Otherwise, the p-value is within bounds at .5 and yes, this would be statistically significant.\n",
    "supporting": [],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}