{
  "hash": "6121914dea1d03255f3b882637d3ccd3",
  "result": {
    "markdown": "---\ntitle: \"Homework 1\"\nauthor: \"Nick Boonstra\"\ndescription: \"The first homework on descriptive statistics and probability\"\ndate: Sys.Date()\nformat:\n  html:\n    toc: true\n    code-fold: true\n    code-copy: true\n    code-tools: true\ncategories:\n  - hw1\n  - desriptive statistics \n  - probability\n---\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(tidyverse)\n```\n\n::: {.cell-output .cell-output-stderr}\n```\n── Attaching packages ─────────────────────────────────────── tidyverse 1.3.2 ──\n✔ ggplot2 3.3.6     ✔ purrr   0.3.4\n✔ tibble  3.1.8     ✔ dplyr   1.0.9\n✔ tidyr   1.2.0     ✔ stringr 1.4.0\n✔ readr   2.1.2     ✔ forcats 0.5.1\n── Conflicts ────────────────────────────────────────── tidyverse_conflicts() ──\n✖ dplyr::filter() masks stats::filter()\n✖ dplyr::lag()    masks stats::lag()\n```\n:::\n\n```{.r .cell-code}\nlibrary(readxl)\n\nknitr::opts_chunk$set(echo = TRUE, warning=FALSE, message=FALSE)\n```\n:::\n\n\n# Question 1\n\n## a\n\nFirst, let's read in the data from the Excel file:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(readxl)\nlungcap <- read_excel(\"_data/LungCapData.xls\")\n```\n:::\n\n\nThe distribution of LungCap looks as follows:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nhist(lungcap$LungCap)\n```\n\n::: {.cell-output-display}\n![](hw1_boonstra_files/figure-html/hist-1.png){width=672}\n:::\n:::\n\n\nThe histogram suggests that the distribution is close to a normal distribution. Most of the observations are close to the mean. Very few observations are close to the margins (0 and 15).\n\n## b\n\nThese are the boxplots of the distributions for the lung capacity of males and females in the sample:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlungcap %>% \n  ggplot(aes(x=\"\",y=LungCap)) +\n  geom_boxplot() +\n  facet_wrap(vars(Gender)) +\n  labs(x=\"\",y=\"Lung Capacity\")\n```\n\n::: {.cell-output-display}\n![](hw1_boonstra_files/figure-html/boxplot-1.png){width=672}\n:::\n:::\n\n\nAccording to these boxplots, it appears that males and females have similar median lung capacities, but that males may be more likely to have a higher lung capacity than females.\n\n## c\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlungcap %>% \n  group_by(Smoke) %>% \n  summarise(mean_lungcap=mean(LungCap))\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n# A tibble: 2 × 2\n  Smoke mean_lungcap\n  <chr>        <dbl>\n1 no            7.77\n2 yes           8.65\n```\n:::\n:::\n\n\nAccording to this sample, it would appear that smokers have a higher lung capacity than non-smokers. This would appear to be counter-intuitive, as one would likely expect smoking to reduce lung functionality and, by extension, capacity.\n\n## d\n\nIn order to complete this examination by group, we must create a new nominal variable that groups observations by age; this can be accomplished fairly simply using the `mutate()` and `case_when()` functions:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlungcap_age <- lungcap %>% \n  mutate(age_group = case_when(\n    Age <= 13 ~ \"13 and under\",\n    Age == 14 | Age == 15 ~ \"14 to 15\",\n    Age == 16 | Age == 17 ~ \"16 to 17\",\n    Age >= 18 ~ \"18 and older\"\n  ))\n```\n:::\n\n\nWith this new dataframe, we can use the `group_by()` function to calculate mean lung capacity by age group and smoker status:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlungcap_age %>% \n  group_by(age_group,Smoke) %>% \n  summarise(mean(LungCap))\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n# A tibble: 8 × 3\n# Groups:   age_group [4]\n  age_group    Smoke `mean(LungCap)`\n  <chr>        <chr>           <dbl>\n1 13 and under no               6.36\n2 13 and under yes              7.20\n3 14 to 15     no               9.14\n4 14 to 15     yes              8.39\n5 16 to 17     no              10.5 \n6 16 to 17     yes              9.38\n7 18 and older no              11.1 \n8 18 and older yes             10.5 \n```\n:::\n:::\n\n\nAccording to these data, it appears that lung capacity generally increases with age. Interestingly, lung capacity is worse for smokers than it is for non-smokers in every age group except for \"13 and under\". This is surprising on the surface, given that, when the data are ungrouped, smokers have a higher lung capacity than non-smokers (see part c). However, this begins to make more sense when we see how much better the \"13 and under\" group is represented compared to the others in this dataset:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlungcap_age %>% \n  group_by(age_group) %>% \n  count()\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n# A tibble: 4 × 2\n# Groups:   age_group [4]\n  age_group        n\n  <chr>        <int>\n1 13 and under   428\n2 14 to 15       120\n3 16 to 17        97\n4 18 and older    80\n```\n:::\n:::\n\n\nThis high number of observations compared to other age groups likely plays a significant role in skewing the mean of the entire dataset.\n\n## e\n\nIt is not clear to me how this part is different from part d; from what I do understand, I believe the question being asked here is addressed in that part.\n\n## f\n\n\n::: {.cell}\n\n```{.r .cell-code}\ncov(lungcap$LungCap, lungcap$Age)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 8.738289\n```\n:::\n\n```{.r .cell-code}\ncor(lungcap$LungCap, lungcap$Age)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 0.8196749\n```\n:::\n:::\n\n\nIt would appear that lung capacity and age covary together positively, such that a higher age means a higher lung capacity. We can confirm this with a simple visualization:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlungcap %>% \n  ggplot(aes(x=Age,y=LungCap)) +\n  geom_point() +\n  geom_smooth()\n```\n\n::: {.cell-output-display}\n![](hw1_boonstra_files/figure-html/corr viz-1.png){width=672}\n:::\n:::\n\n\n# Question 2\n\nBefore we begin answering the parts of this question, we must create a dataframe in R that represents the necessary data.\n\n\n::: {.cell}\n\n```{.r .cell-code}\npriors <- c(0,1,2,3,4)\nfreq <- c(128,434,160,64,24)\nprisoners <- data.frame(priors,freq)\nprisoners\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n  priors freq\n1      0  128\n2      1  434\n3      2  160\n4      3   64\n5      4   24\n```\n:::\n:::\n\n\n## a\n\nThe probability that a randomly selected inmate has exactly 2 prior convictions is 160 / 810 = 0.1975309.\n\n## b\n\nThe probability that a randomly selected inmate has less than 2 prior convictions is (128+434) / 810 = 0.6938272.\n\n## c\n\nThe probability that a randomly selected inmate has 2 or fewer prior convictions is (128+434+160) / 810 = 0.891358.\n\n## d\n\nThe probability that a randomly selected inmate has more than 2 prior convictions is (64+24) / 810 = 0.108642.\n\n## e\n\nBefore calculating expected value, we should put together a probability mass function for the `prisoners` data.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nprisoners <- prisoners %>% \n  mutate(prob=freq/810) %>% \n  mutate(expect=prob*priors)\n\nprisoners %>% \n  summarise(sum(expect))\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n  sum(expect)\n1     1.28642\n```\n:::\n:::\n\n\nThe expected value for the number of prior convictions is about 1.29 priors.\n",
    "supporting": [
      "hw1_boonstra_files"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}