{
  "hash": "3fe7ee610cc391e40ab9178c5e7e16d9",
  "result": {
    "markdown": "---\ntitle: \"Homework 1\"\nauthor: \"Emma Rasmussen\"\ndescription: \"The first homework on descriptive statistics and probability\"\ndate: \"09/29/2022\"\nformat:\n  html:\n    toc: true\n    code-fold: true\n    code-copy: true\n    code-tools: true\ncategories:\n  - hw1\n  - desriptive statistics \n  - probability\n---\n\n::: {.cell}\n\n```{.r .cell-code}\nknitr::opts_chunk$set(echo = TRUE, warning=FALSE, message=FALSE)\n\nlibrary(readxl)\nlibrary(tidyverse)\nlibrary(ggplot2)\nlibrary(dplyr)\n```\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\nlungcap<-read_excel(\"_data/LungCapData.xls\")\nhead(lungcap)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n# A tibble: 6 × 6\n  LungCap   Age Height Smoke Gender Caesarean\n    <dbl> <dbl>  <dbl> <chr> <chr>  <chr>    \n1    6.48     6   62.1 no    male   no       \n2   10.1     18   74.7 yes   female no       \n3    9.55    16   69.7 no    female yes      \n4   11.1     14   71   no    male   no       \n5    4.8      5   56.9 no    male   no       \n6    6.22    11   58.7 no    female no       \n```\n:::\n\n```{.r .cell-code}\n#saving a copy of original dataset\nlungcap_orig<-lungcap\n\n#checking for missing values in LungCap\nwhich(is.na(lungcap$LungCap))\n```\n\n::: {.cell-output .cell-output-stdout}\n```\ninteger(0)\n```\n:::\n:::\n\n\n### 1a.\n\nThe distribution of LungCapData is plotted as a histogram below.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nggplot(lungcap, aes(x=LungCap))+geom_histogram()\n```\n\n::: {.cell-output-display}\n![](HW1_EmmaRasmussen_files/figure-html/unnamed-chunk-3-1.png){width=672}\n:::\n:::\n\n\nThe histogram looks approximately normally distributed\n\n### 1b.\n\nThe probability distribution of LungCap data for males and females is compared using the boxplots below:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nggplot(lungcap, aes(x=LungCap, y=Gender))+geom_boxplot()\n```\n\n::: {.cell-output-display}\n![](HW1_EmmaRasmussen_files/figure-html/unnamed-chunk-4-1.png){width=672}\n:::\n:::\n\n\nThe mean lung capacity of males appears slightly higher than that of females.\nThe IQR and range for males and females appears similarly spread with a higher average for males.\n\n### 1c.\n\nBelow the mean and standard deviation of smokers and non-smokers is compared.\nThey are also plotted as a boxplot to help visualize the distribution.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlungcap%>%\n  group_by(Smoke) %>% \n  summarize(Mean=mean(LungCap))\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n# A tibble: 2 × 2\n  Smoke  Mean\n  <chr> <dbl>\n1 no     7.77\n2 yes    8.65\n```\n:::\n\n```{.r .cell-code}\nlungcap%>%\n  group_by(Smoke) %>% \n  summarize(stdev=sd(LungCap))\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n# A tibble: 2 × 2\n  Smoke stdev\n  <chr> <dbl>\n1 no     2.73\n2 yes    1.88\n```\n:::\n\n```{.r .cell-code}\nggplot(lungcap, aes(x=LungCap, y=Smoke))+geom_boxplot()\n```\n\n::: {.cell-output-display}\n![](HW1_EmmaRasmussen_files/figure-html/unnamed-chunk-5-1.png){width=672}\n:::\n:::\n\n\nThe mean lung capacity for smokers (8.645) in this sample is higher than that of non-smokers (7.770).\nThis does not make sense.\nHowever, the standard deviation of non-smokers (2.726) is much higher than smokers (1.883) so there might be something else going on (see boxplot).\n\n### 1d.\n\nBelow, means are taken by age groups of smokers/non-smokers.\nI also created a new age category variable (\"AgeCat\") to plot the data by smoking status and age category.\n\n\n::: {.cell}\n\n```{.r .cell-code}\n#Mean under 13 and nonsmoker\nlungcap %>% \n  filter(Age<=13 & Smoke==\"no\") %>% \n  pull(LungCap) %>% \n  mean()\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 6.358746\n```\n:::\n\n```{.r .cell-code}\n#Mean under 13 and smoker\nlungcap %>% \n  filter(Age<=13 & Smoke==\"yes\") %>% \n  pull(LungCap) %>% \n  mean()\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 7.201852\n```\n:::\n\n```{.r .cell-code}\n#Mean 14-15 and nonsmoker\nlungcap %>% \n  filter(Age==14 | Age==15 & Smoke==\"no\") %>% \n  pull(LungCap) %>% \n  mean()\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 9.068018\n```\n:::\n\n```{.r .cell-code}\n#Mean 14-15 and smoker\nlungcap %>% \n  filter(Age==14 | Age==15 & Smoke==\"yes\") %>% \n  pull(LungCap) %>% \n  mean()\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 8.689231\n```\n:::\n\n```{.r .cell-code}\n#Mean 16-17 and nonsmoker\nlungcap %>% \n  filter(Age==16 | Age==17 & Smoke==\"no\") %>% \n  pull(LungCap) %>% \n  mean()\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 10.30523\n```\n:::\n\n```{.r .cell-code}\n#Mean 16-17 and smoker\nlungcap %>% \n  filter(Age==16 | Age==17 & Smoke==\"yes\") %>% \n  pull(LungCap) %>% \n  mean()\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 9.850385\n```\n:::\n\n```{.r .cell-code}\n#Mean over 18 and nonsmoker\nlungcap %>% \n  filter(Age>=18 & Smoke==\"no\") %>% \n  pull(LungCap) %>% \n  mean()\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 11.06885\n```\n:::\n\n```{.r .cell-code}\n#Mean over 18 and smoker\nlungcap %>% \n  filter(Age>=18 & Smoke==\"yes\") %>% \n  pull(LungCap) %>% \n  mean()\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 10.51333\n```\n:::\n\n```{.r .cell-code}\n#creating new variable AgeCat to create boxplots\nlungcap<-lungcap %>% \n  mutate(AgeCat= as.factor(case_when(Age <= 13 ~ \"13 and under\", \n                           Age == 14 |Age ==15 ~ \"14-15\", \n                           Age == 16 | Age==17 ~ \"16-17\",\n                           Age >= 18 ~ \"18 or over\"\n                           )))\n\n#new Category AgeCat is the last column\nlungcap\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n# A tibble: 725 × 7\n   LungCap   Age Height Smoke Gender Caesarean AgeCat      \n     <dbl> <dbl>  <dbl> <chr> <chr>  <chr>     <fct>       \n 1    6.48     6   62.1 no    male   no        13 and under\n 2   10.1     18   74.7 yes   female no        18 or over  \n 3    9.55    16   69.7 no    female yes       16-17       \n 4   11.1     14   71   no    male   no        14-15       \n 5    4.8      5   56.9 no    male   no        13 and under\n 6    6.22    11   58.7 no    female no        13 and under\n 7    4.95     8   63.3 no    male   yes       13 and under\n 8    7.32    11   70.4 no    male   no        13 and under\n 9    8.88    15   70.5 no    male   no        14-15       \n10    6.8     11   59.2 no    male   no        13 and under\n# … with 715 more rows\n```\n:::\n\n```{.r .cell-code}\nggplot(lungcap, aes(x=LungCap))+geom_boxplot()+facet_grid(Smoke ~ AgeCat)\n```\n\n::: {.cell-output-display}\n![](HW1_EmmaRasmussen_files/figure-html/unnamed-chunk-6-1.png){width=672}\n:::\n:::\n\n\n### 1e.\n\nComparing the lung capacities for smokers and non-smokers in different age categories:\n\nNow we can see that the mean lung capacity for smokers by age group is generally lower than that of nonsmokers.\nThis is true in all categories except for Under 13, which is likely because smokers in that category are going to be older than nonsmokers in that category (i.e. it is more likely that a 12 year old smokes than a 6 year old, and a 12 year old has a larger lung capacity than a 6 year old regardless of smoking status)\n\nThis explains the first calculation of mean by smoking status (before finding the mean by age categories).\nSmokers are generally going to be older than non-smokers for this sample (the oldest participant in the sample is 19- see code below), which explains why the mean for smokers versus non-smokers (not separated by age categories) makes it look like smokers have a higher average lung capacity.\n\n\n::: {.cell}\n\n```{.r .cell-code}\n#checking how old participants in the sample are\nlungcap %>% \n  summarize(range(Age))\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n# A tibble: 2 × 1\n  `range(Age)`\n         <dbl>\n1            3\n2           19\n```\n:::\n:::\n\n\n### 1f.\n\nCalculating the correlation and covariance between Lung Capacity and Age:\n\n\n::: {.cell}\n\n```{.r .cell-code}\n#Creating vectors of Age and Lung Capacity from df (lungcap) to apply cov() and cor() functions to\nx<-c(lungcap$Age)\ny<-c(lungcap$LungCap)\n\n\n#Calculating covariance\ncov(x, y)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 8.738289\n```\n:::\n\n```{.r .cell-code}\n#calculating correlation\ncor(x, y)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 0.8196749\n```\n:::\n:::\n\n\nThe covariance, 8.738 is fairly high and positive, meaning as age increases, so does lung capacity (i.e. age and lung capacity co-vary).\nThe correlation (0.82) is fairly close to one and positive, indicating they correlate fairly closely.\n\n### 2a-f.\n\nPrior Conviction Data\n\n\n::: {.cell}\n\n```{.r .cell-code}\n#creating a data frame\nX<-c(0, 1, 2, 3, 4)\nFrequency<-c(128, 434, 160, 64, 24)\nprison<- data.frame(X, Frequency)\nprison\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n  X Frequency\n1 0       128\n2 1       434\n3 2       160\n4 3        64\n5 4        24\n```\n:::\n\n```{.r .cell-code}\nprison<-rename(prison, PriorConvictions=X)\nprison\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n  PriorConvictions Frequency\n1                0       128\n2                1       434\n3                2       160\n4                3        64\n5                4        24\n```\n:::\n\n```{.r .cell-code}\n#visualizing df using bar chart\nggplot(prison, aes(x=PriorConvictions, y=Frequency))+geom_bar(stat=\"identity\")+geom_text(aes(label = Frequency), vjust = -.3)\n```\n\n::: {.cell-output-display}\n![](HW1_EmmaRasmussen_files/figure-html/unnamed-chunk-9-1.png){width=672}\n:::\n\n```{.r .cell-code}\n#There are 810 obs in df\nsum(Frequency)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 810\n```\n:::\n:::\n\n\nAnswering the Questions\n\n\n::: {.cell}\n\n```{.r .cell-code}\n#creating a vector of probabilities\nprobs<-Frequency/810\nprobs\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 0.15802469 0.53580247 0.19753086 0.07901235 0.02962963\n```\n:::\n\n```{.r .cell-code}\n#A\n# P(x=2)=160/810\n160/810\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 0.1975309\n```\n:::\n\n```{.r .cell-code}\n#B\n#P(x<2)=P(0)+P(1)\n(128+434)/810\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 0.6938272\n```\n:::\n\n```{.r .cell-code}\n#C\n#P(x<=2)=P(0)+P(1)+P(2)\n(128+434+160)/810\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 0.891358\n```\n:::\n\n```{.r .cell-code}\n#D\n#1-P(above)\n1-((128+434+160)/810)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 0.108642\n```\n:::\n\n```{.r .cell-code}\n#E\n#Expected value=sum of probabilities*each value (0, 1, 2, 3 or 4)\nweighted.mean(X, probs)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 1.28642\n```\n:::\n\n```{.r .cell-code}\n#F\n#Calculating the Variance using the formula for variance\n(sum(Frequency*((X-1.28642)^2)))/(sum(Frequency)-1)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 0.8572937\n```\n:::\n\n```{.r .cell-code}\n#Calculating the sample standard deviation from the variance\nsqrt(0.8572937)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 0.9259016\n```\n:::\n:::\n\n\na.  What is the probability that a randomly selected inmate has exactly 2 prior convictions? 19.75% probability (or 0.1975)\nb.  What is the probability that a randomly selected inmate has fewer than 2 prior convictions? 69.38% probability\nc.  What is the probability that a randomly selected inmate has 2 or fewer prior convictions? 89.14% probability\nd.  What is the probability that a randomly selected inmate has more than 2 prior convictions? 10.86% probability\ne.  What is the expected value for the number of prior convictions? 1.28642 prior convictions\nf.  Calculate the variance and the standard deviation for the Prior Convictions. variance: 0.8572937 standard deviation: 0.9259016 prior convictions\n",
    "supporting": [
      "HW1_EmmaRasmussen_files"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}