{
  "hash": "b376646761f05a4f7fc0f18261580b33",
  "result": {
    "markdown": "---\ntitle: \"Homework 2\"\nauthor: \"Kalimah Muhammad\"\ndesription: \"CI and Hypothesis Testing\"\ndate: \"10/17/2022\"\nformat:\n  html:\n    toc: true\n    code-fold: true\n    code-copy: true\n    code-tools: true\ncategories:\n  - hw2\n  - Kalimah Muhammad\n---\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(tidyr)\nknitr::opts_chunk$set(echo = TRUE)\n```\n:::\n\n\n## Questions\n\n### 1.Cardiac Care Network - Wait Times for Cardiac Surgeries\n*Prompt: The time between the date a patient was recommended for heart surgery and the surgery date for cardiac patients in Ontario was collected by the Cardiac Care Network (“Wait Times Data Guide,” Ministry of Health and Long-Term Care, Ontario, Canada, 2006). The sample mean and sample standard deviation for wait times (in days) of patients for two cardiac procedures are given in the accompanying table. Assume that the sample is representative of the Ontario population.*\n\n**Construct the 90% confidence interval to estimate the actual mean wait time for each of the two procedures.** \n\n#### Bypass Surgery Confidence Interval\n\n\n::: {.cell}\n\n```{.r .cell-code}\n#calculate confidence interval for bypass surgery\nmean<- 19 #mean wait time\nsd<-10 #standard deviation\nn <-539 #sample size\nbypass_se <- (sd/sqrt(n)) # calculate sample standard error \nconf_level <-0.9 #establish 90% confidence interval\ntail_area <- (1-conf_level)/2 #calculate tail area\nt_score<- qt(p=1-tail_area, df=n-1) #determine t-score\nbypass_CI <- c(mean - t_score* bypass_se,\n               mean + t_score* bypass_se) #calculate confidence interval\nprint(bypass_CI)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 18.29029 19.70971\n```\n:::\n:::\n\n\nThe confidence interval (CI) for the average wait time for bypass surgery is between 18.29 and 19.71 days. \n\n#### Angiography Confidence Interval\n\n\n::: {.cell}\n\n```{.r .cell-code}\n#Calculate cofidence interval for angiography\n#mean= 18, sd=9, n=847\nmean_ag<- 18 #mean wait time\nsd_ag<-9 #standard deviation\nn_ag <-847 #sample size\nag_se <- (sd_ag/sqrt(n)) # calculate sample standard error \nconf_level <-0.9 #establish 90% confidence interval\ntail_area <- (1-conf_level)/2 #calculate tail area\nt_score_ag<- qt(p=1-tail_area, df=n-1) #determine t-score\nag_CI <- c(mean_ag - t_score_ag* ag_se,\n               mean_ag + t_score_ag* ag_se) #calculate confidence interval\nprint(ag_CI)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 17.36126 18.63874\n```\n:::\n:::\n\n\nMeanwhile, the CI for the angiography mean wait time is between 17.36 and 18.63 days. \n\n#### Is the confidence interval narrower for angiography or bypass surgery?\n\n\n::: {.cell}\n\n```{.r .cell-code}\n19.70971-18.29029 #difference in bypass surgery CI range\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 1.41942\n```\n:::\n\n```{.r .cell-code}\n18.63874-17.36126 #difference in angiography CI range\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 1.27748\n```\n:::\n:::\n\n\nThe range in the confidence interval for angiography is 1.28 narrower than the bypass surgery, 1.42.\n\n***\n\n### 2. National Center for Public Policy - Is college essential for success?\n*Prompt: A survey of 1031 adult Americans was carried out by the National Center for Public Policy. Assume that the sample is representative of adult Americans. Among those surveyed, 567 believed that college education is essential for success.*\n**Find the point estimate, p, of the proportion of all adult Americans who believe that a college education is essential for success.Construct and interpret a 95% confidence interval for p.**\n\n\n::: {.cell}\n\n```{.r .cell-code}\n#proportion of US adults who believe college is essential for success\nprop.test(567,1031,conf.level = 0.95)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n\n\t1-sample proportions test with continuity correction\n\ndata:  567 out of 1031, null probability 0.5\nX-squared = 10.091, df = 1, p-value = 0.00149\nalternative hypothesis: true p is not equal to 0.5\n95 percent confidence interval:\n 0.5189682 0.5805580\nsample estimates:\n        p \n0.5499515 \n```\n:::\n:::\n\nThe point estimate of the proportion of all adult Americans who believe that a college education is essential for success is 0.55. The confidence interval set at 95% ranges between 0.52 and 0.58.\n\n***\n\n### 3. Student Sample Size\n*Prompt: Suppose that the financial aid office of UMass Amherst seeks to estimate the mean cost of textbooks per semester for students. The estimate will be useful if it is within 5 dollars of the true population mean (i.e. they want the confidence interval to have a length of 10 dollars or less). The financial aid office is pretty sure that the amount spent on books varies widely, with most values between 30 dollars and 200 dollars. They think that the population standard deviation is about a quarter of this range (in other words, you can assume they know the population standard deviation).* **Assuming the significance level to be 5%, what should be the size of the sample?**\n\n\n::: {.cell}\n\n```{.r .cell-code}\n#calculate the sample size\npop_sd<-(200-30)/4\ncritical_value<-1.96 #based off signigicance level of 5\nsample_size<- ((pop_sd*critical_value)/5)^2 \nprint(sample_size)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 277.5556\n```\n:::\n:::\n\nThe sample size should be 278 students to estimate the mean cost of textbooks per semester. \n\n***\n\n### 4. Income for Union Workers\n*Prompt: According to a union agreement, the mean income for all senior-level workers in a large service company equals 500 per week. A representative of a women’s group decides to analyze whether the mean income μ for female employees matches this norm. For a random sample of nine female employees, ȳ = $410 and s = 90.*\n\nTest whether the mean income of female employees differs from $500 per week. Include assumptions, hypotheses, test statistic, and P-value. Interpret the result.\nReport the P-value for Ha : μ < 500. Interpret.\nReport and interpret the P-value for H a: μ > 500.\n(Hint: The P-values for the two possible one-sided tests must sum to 1.)\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nsam_mean<-410\nmu<-500\nsam_sd<-90\nn<-9\n\nt_score<- (sam_mean-mu)/(sam_sd/(sqrt(n)))\nprint(t_score)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] -3\n```\n:::\n\n```{.r .cell-code}\nupper_tail<- pt(t_score, df=n-1, lower.tail = FALSE)\nprint(upper_tail)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 0.9914642\n```\n:::\n\n```{.r .cell-code}\nlower_tail<- pt(t_score, df=n-1, lower.tail = TRUE)\nprint(lower_tail)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 0.008535841\n```\n:::\n\n```{.r .cell-code}\np_value<- upper_tail + lower_tail\nprint(p_value)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 1\n```\n:::\n:::\n\n\n***\n\n### 5. Jones and Smith\n*Prompt: Jones and Smith separately conduct studies to test H0: μ = 500 against Ha : μ ≠ 500, each with n = 1000. Jones gets ȳ = 519.5, with se = 10.0. Smith gets ȳ = 519.7 with se = 10.0.*\n\n\n::: {.cell}\n\n```{.r .cell-code}\nmu<- 500 #hypothesized population mean\nj_mean<-519.5 #Jones's mean\ns_mean<-519.7 #Smith's mean\nn=1000 #sample size\nse<-10 #standard error\n```\n:::\n\n\nShow that t = 1.95 and P-value = 0.051 for Jones. \n\n::: {.cell}\n\n```{.r .cell-code}\n#calculate the t-score for Jones\nj_tscore<-(j_mean - mu)/se\nprint(j_tscore)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 1.95\n```\n:::\n\n```{.r .cell-code}\n#calculate p-value for Jones\nj_pvalue<- pt(j_tscore, df=n-1, lower.tail = FALSE) *2\nprint(j_pvalue)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 0.05145555\n```\n:::\n:::\n\n\nShow that t = 1.97 and P-value = 0.049 for Smith.\n\n::: {.cell}\n\n```{.r .cell-code}\n#calculate the t-score for Smith\ns_tscore<-(s_mean - mu)/se\nprint(s_tscore)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 1.97\n```\n:::\n\n```{.r .cell-code}\n#calculate p-value for Smith\ns_pvalue<- pt(s_tscore, df=n-1, lower.tail = FALSE) *2\nprint(s_pvalue)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 0.04911426\n```\n:::\n:::\n\n\n**Using α = 0.05, for each study indicate whether the result is “statistically significant.” Using this example, explain the misleading aspects of reporting the result of a test as “P ≤ 0.05” versus “P > 0.05,” or as “reject H0” versus “Do not reject H0 ,” without reporting the actual P-value.**\n\nIn Smith's test, the p-value of .049, less than 0.05, coupled with the significance level of 0.05 indicate a statistically significant result to reject the null hypothesis. However, the results from the Jones's test with a p-value of 0.052, greater than 0.05, indicates the results were not statistically significant and the null was retained. \n\nTheses results can be misleading as the significance level impacts  how the p-values are referenced when under 0.05. P-values over 0.05 will typically retain the null, however p-values under 0.05 are influenced by the significance level to determine whether results are statistically significant to reject the null hypothesis.\n\n***\n\n### 6. US Gas Tax\n*Prompt:Are the taxes on gasoline very high in the United States? According to the American Petroleum Institute, the per gallon federal tax that was levied on gasoline was 18.4 cents per gallon. However, state and local taxes vary over the same period. The sample data of gasoline taxes for 18 large cities is given below in the variable called gas_taxes.*\n\ngas_taxes <- c(51.27, 47.43, 38.89, 41.95, 28.61, 41.29, 52.19, 49.48, 35.02, 48.13, 39.28, 54.41, 41.66, 30.28, 18.49, 38.72, 33.41, 45.02)\n\n**Is there enough evidence to conclude at a 95% confidence level that the average tax per gallon of gas in the US in 2005 was less than 45 cents? Explain.**\n\n\n::: {.cell}\n\n```{.r .cell-code}\ngas_taxes <- c(51.27, 47.43, 38.89, 41.95, 28.61, 41.29, 52.19, 49.48, 35.02, 48.13, 39.28, 54.41, 41.66, 30.28, 18.49, 38.72, 33.41, 45.02)\n\n#t-test of average gas taxes from sample cities\nt.test(gas_taxes, alternative = c(\"less\"), mu=45, conf.level = 0.95)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n\n\tOne Sample t-test\n\ndata:  gas_taxes\nt = -1.8857, df = 17, p-value = 0.03827\nalternative hypothesis: true mean is less than 45\n95 percent confidence interval:\n     -Inf 44.67946\nsample estimates:\nmean of x \n 40.86278 \n```\n:::\n:::\n\nYes, using the t-test to compare the sample mean (40.86) to the hypothesized population mean (45) at the confidence level of 95% resulted in a favorable conclusion that the sample average was less than 45 cents. ",
    "supporting": [],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}