{
  "hash": "2582e1ea68bac7c659e3772b27adf4b7",
  "result": {
    "markdown": "---\ntitle: \"HW4\"\nauthor: \"Steph Roberts\"\ndesription: \"Homework 4\"\ndate: \"11/14/2022\"\nformat:\n  html:\n    toc: true\n    code-fold: true\n    code-copy: true\n    code-tools: true\ncategories:\n  - hw4\n  - Steph Roberts\n---\n\n\n### Homework 4\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(tidyverse)\nlibrary(alr4)\nlibrary(smss)\n\nknitr::opts_chunk$set(echo = TRUE)\n```\n:::\n\n\n## Question 1\n\nFor recent data in Jacksonville, Florida, on y = selling price of home (in dollars), x1 = size of home (in square feet), and x2 = lot size (in square feet), the prediction equation is \nŷ = −10,536 + 53.8x1 + 2.84x2.\n\n### 1A\n\nA particular home of 1240 square feet on a lot of 18,000 square feet sold for $145,000. Find the predicted selling price and the residual, and interpret.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nest <- (53.8*1240) + (2.84*18000)-10536\nprint(paste(\"The predicted selling price is\", est))\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] \"The predicted selling price is 107296\"\n```\n:::\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\nres <- 145000 - est\nprint(paste(\"The residual is\", res))\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] \"The residual is 37704\"\n```\n:::\n:::\n\n\n### 1B\nFor fixed lot size, how much is the house selling price predicted to increase for each square-foot increase in home size? Why?\n\nThe coefficient of the square-footage variable is 53.8, which indicates that is how much the selling price will increase for every increase in square-foot. \n\n### 1C\nAccording to this prediction equation, for fixed home size, how much would lot size need to increase to have the same impact as a one-square-foot increase in home size?\n\n\n::: {.cell}\n\n```{.r .cell-code}\nsfcoef <- 53.8\nlotcoef<- 2.84\n\nlotinc<-sfcoef/lotcoef\nprint(paste(\"The lot size would need to increase\", lotinc, \"for every 1 square foot increasenin home size\"))\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] \"The lot size would need to increase 18.943661971831 for every 1 square foot increasenin home size\"\n```\n:::\n:::\n\n\n## Question 2\n\n(Data file: salary in alr4 R package). The data file concerns salary and other characteristics of all faculty in a small Midwestern college collected in the early 1980s for presentation in legal proceedings for which discrimination against women in salary was at issue. All persons in the data hold tenured or tenure track positions; temporary faculty are not included. The variables include degree, a factor with levels PhD and MS; rank, a factor with levels Asst, Assoc, and Prof; sex, a factor with levels Male and Female; Year, years in current rank; ysdeg, years since highest degree, and salary, academic year salary in dollars.\n\n### 2A \nTest the hypothesis that the mean salary for men and women is the same, without regard to any other variable but sex. Explain your findings.\n\n\n::: {.cell}\n\n```{.r .cell-code}\ndata(\"salary\")\ndim(salary)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 52  6\n```\n:::\n\n```{.r .cell-code}\nhead(salary)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n   degree rank    sex year ysdeg salary\n1 Masters Prof   Male   25    35  36350\n2 Masters Prof   Male   13    22  35350\n3 Masters Prof   Male   10    23  28200\n4 Masters Prof Female    7    27  26775\n5     PhD Prof   Male   19    30  33696\n6 Masters Prof   Male   16    21  28516\n```\n:::\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\nt.test(salary ~ sex, data=salary)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n\n\tWelch Two Sample t-test\n\ndata:  salary by sex\nt = 1.7744, df = 21.591, p-value = 0.09009\nalternative hypothesis: true difference in means between group Male and group Female is not equal to 0\n95 percent confidence interval:\n -567.8539 7247.1471\nsample estimates:\n  mean in group Male mean in group Female \n            24696.79             21357.14 \n```\n:::\n:::\n\nThe null hypothesis would be that male and females have the same mean salary. With a p-value of 0.09 we fail to reject the null hypothesis at the usual significance level of alpha = 0.05. Based on the data, we can conclude there is not enough evidence of a difference between the true average of the two groups.  \n\n### 2B\nRun a multiple linear regression with salary as the outcome variable and everything else as predictors, including sex. Assuming no interactions between sex and the other predictors, obtain a 95% confidence interval for the difference in salary between males and females.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nallvar <- lm(salary ~ ., data = salary)\nsummary(allvar)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n\nCall:\nlm(formula = salary ~ ., data = salary)\n\nResiduals:\n    Min      1Q  Median      3Q     Max \n-4045.2 -1094.7  -361.5   813.2  9193.1 \n\nCoefficients:\n            Estimate Std. Error t value Pr(>|t|)    \n(Intercept) 15746.05     800.18  19.678  < 2e-16 ***\ndegreePhD    1388.61    1018.75   1.363    0.180    \nrankAssoc    5292.36    1145.40   4.621 3.22e-05 ***\nrankProf    11118.76    1351.77   8.225 1.62e-10 ***\nsexFemale    1166.37     925.57   1.260    0.214    \nyear          476.31      94.91   5.018 8.65e-06 ***\nysdeg        -124.57      77.49  -1.608    0.115    \n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n\nResidual standard error: 2398 on 45 degrees of freedom\nMultiple R-squared:  0.855,\tAdjusted R-squared:  0.8357 \nF-statistic: 44.24 on 6 and 45 DF,  p-value: < 2.2e-16\n```\n:::\n:::\n\nAs discovered earlier, sex does not have a large impact on salary when other variables are involved. \n\n\n::: {.cell}\n\n```{.r .cell-code}\nconfint(allvar)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n                 2.5 %      97.5 %\n(Intercept) 14134.4059 17357.68946\ndegreePhD    -663.2482  3440.47485\nrankAssoc    2985.4107  7599.31080\nrankProf     8396.1546 13841.37340\nsexFemale    -697.8183  3030.56452\nyear          285.1433   667.47476\nysdeg        -280.6397    31.49105\n```\n:::\n:::\n\nThe confidence interval for the difference between male and female salary is between -$697.81 and $3,030.57. Because this range includes negative numbers, it shows that females can make more of less than males even when all factors are accounted for.\n\n### 2C \nInterpret your finding for each predictor variable; discuss (a) statistical significance, (b) interpretation of the coefficient / slope in relation to the outcome variable and other variables\n\nConsidering an alpha = 0.05, we can interpret the statistical significance of the predictor variables.\n\n**Degree:** not significant and has a coefficient of 1388, meaning those with PhDs make an average of $1,388 more. \n**Ranking Associate:**  IS significant and has a coefficient of 5292.36, meaning a rank change from assistant to Associate impacts the salary an average of $5,292.36.\n**Ranking Professor:** IS significant and has a coefficient of 11118.76, meaning one unit of rank from assistant to Professor impacts the salary an average of $11,118.76.\n**Sex:** not significant and has a coefficient of 1166.37, meaning a change in the sex of an observation changes the salary an average of $1,166.37, in favor of the females. \n**Year:** IS significant and has a coefficient of 476.31, meaning one more year in rank impacts the salary an average of $476.31.\n**Year since degree:** not significant and has a coefficient of -124.57, meaning every additional year since degree negatively impacts salary by $124.57.\n\n### 2D\nChange the baseline category for the rank variable. Interpret the coefficients related to rank again.\n\n\n::: {.cell}\n\n```{.r .cell-code}\ntable(salary$rank)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n\n Asst Assoc  Prof \n   18    14    20 \n```\n:::\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\nsalary$rank <- relevel(salary$rank, ref = \"Assoc\")\nmod_rank <- lm(salary ~ ., data = salary)\nsummary(mod_rank)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n\nCall:\nlm(formula = salary ~ ., data = salary)\n\nResiduals:\n    Min      1Q  Median      3Q     Max \n-4045.2 -1094.7  -361.5   813.2  9193.1 \n\nCoefficients:\n            Estimate Std. Error t value Pr(>|t|)    \n(Intercept) 21038.41    1109.12  18.969  < 2e-16 ***\ndegreePhD    1388.61    1018.75   1.363    0.180    \nrankAsst    -5292.36    1145.40  -4.621 3.22e-05 ***\nrankProf     5826.40    1012.93   5.752 7.28e-07 ***\nsexFemale    1166.37     925.57   1.260    0.214    \nyear          476.31      94.91   5.018 8.65e-06 ***\nysdeg        -124.57      77.49  -1.608    0.115    \n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n\nResidual standard error: 2398 on 45 degrees of freedom\nMultiple R-squared:  0.855,\tAdjusted R-squared:  0.8357 \nF-statistic: 44.24 on 6 and 45 DF,  p-value: < 2.2e-16\n```\n:::\n:::\n\nChanging the baseline of the rank variable changes the output because out input is asking a different question. Here, we see that a \"unit change\" is now based on the associate rank as a baseline, instead of assistant, as defaulted before. This tells us that a change in unit from associate to assistant impacts salary by an average of - $5,292.36 and a change to professor impacts salary an average of $5,826.40.\n\n### 2E\nFinkelstein (1980), in a discussion of the use of regression in discrimination cases, wrote, “[a] variable may reflect a position or status bestowed by the employer, in which case if there is discrimination in the award of the position or status, the variable may be ‘tainted.’ ” Thus, for example, if discrimination is at work in promotion of faculty to higher ranks, using rank to adjust salaries before comparing the sexes may not be acceptable to the courts. Exclude the variable rank, refit, and summarize how your findings changed, if they did.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nno_rank <- lm(salary ~ degree  + sex + year + ysdeg, data = salary)\nsummary(no_rank)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n\nCall:\nlm(formula = salary ~ degree + sex + year + ysdeg, data = salary)\n\nResiduals:\n    Min      1Q  Median      3Q     Max \n-8146.9 -2186.9  -491.5  2279.1 11186.6 \n\nCoefficients:\n            Estimate Std. Error t value Pr(>|t|)    \n(Intercept) 17183.57    1147.94  14.969  < 2e-16 ***\ndegreePhD   -3299.35    1302.52  -2.533 0.014704 *  \nsexFemale   -1286.54    1313.09  -0.980 0.332209    \nyear          351.97     142.48   2.470 0.017185 *  \nysdeg         339.40      80.62   4.210 0.000114 ***\n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n\nResidual standard error: 3744 on 47 degrees of freedom\nMultiple R-squared:  0.6312,\tAdjusted R-squared:  0.5998 \nF-statistic: 20.11 on 4 and 47 DF,  p-value: 1.048e-09\n```\n:::\n:::\n\nExcluding rank changes things a bit. Now, having a PhD degree impacts salary -$3,299 compared with masters. Also, removing rank affects the differences in the sex variable. It is still not significant, but with a coefficient of -1286.54, it suggests females make less when rank is controlled for. Years in rank is less significant and years since degree is more significant.\n\nHowever, with an R-squared of 0.63 compared with the earlier 0.86, this model is a worse fit for the data. \n\n### 2F\nEveryone in this dataset was hired the year they earned their highest degree. It is also known that a new Dean was appointed 15 years ago, and everyone in the dataset who earned their highest degree 15 years ago or less than that has been hired by the new Dean. Some people have argued that the new Dean has been making offers that are a lot more generous to newly hired faculty than the previous one and that this might explain some of the variation in Salary. Create a new variable that would allow you to test this hypothesis and run another multiple regression model to test this. Select variables carefully to make sure there is no multicollinearity. Explain why multicollinearity would be a concern in this case and how you avoided it. Do you find support for the hypothesis that the people hired by the new Dean are making higher than those that were not?\n\n\n::: {.cell}\n\n```{.r .cell-code}\n#Create new variable\nsalary <- salary %>%\n  mutate(new = case_when(ysdeg> 15 ~ 'no',\n                         ysdeg <= 15 ~ 'yes'))\n\nnew_hire <- lm(salary ~ degree + sex + rank + year + new, data = salary)\nsummary(new_hire)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n\nCall:\nlm(formula = salary ~ degree + sex + rank + year + new, data = salary)\n\nResiduals:\n    Min      1Q  Median      3Q     Max \n-3403.3 -1387.0  -167.0   528.2  9233.8 \n\nCoefficients:\n            Estimate Std. Error t value Pr(>|t|)    \n(Intercept) 18301.04    1301.36  14.063  < 2e-16 ***\ndegreePhD     818.93     797.48   1.027   0.3100    \nsexFemale     907.14     840.54   1.079   0.2862    \nrankAsst    -4972.66     997.17  -4.987 9.61e-06 ***\nrankProf     6124.28    1028.58   5.954 3.65e-07 ***\nyear          434.85      78.89   5.512 1.65e-06 ***\nnewyes       2163.46    1072.04   2.018   0.0496 *  \n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n\nResidual standard error: 2362 on 45 degrees of freedom\nMultiple R-squared:  0.8594,\tAdjusted R-squared:  0.8407 \nF-statistic: 45.86 on 6 and 45 DF,  p-value: < 2.2e-16\n```\n:::\n:::\n\nConsidering the concept of multicollinearity, I excluded ysdeg as the \"new\" variable accounts for the same data. With this modification, our R-squared is still high at 0.86. Rank and years in rank are still significant. Interestingly, \"new\" is also significant, with a coefficient of 2163.46 suggests being a new hire impacts salary an average of $2,163.46. This supports the hypothesis that those hired by the new dean are getting better offers. \n\n## Question 3\n\n(Data file: house.selling.price in smss R package) \n\n### 3A\nUsing the house.selling.price data, run and report regression results modeling y = selling price (in dollars) in terms of size of home (in square feet) and whether the home is new (1 = yes; 0 = no). In particular, for each variable; discuss statistical significance and interpret the meaning of the coefficient.\n\n\n::: {.cell}\n\n```{.r .cell-code}\ndata(\"house.selling.price\") \nhouse <- house.selling.price\nhead(house)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n  case Taxes Beds Baths New  Price Size\n1    1  3104    4     2   0 279900 2048\n2    2  1173    2     1   0 146500  912\n3    3  3076    4     2   0 237700 1654\n4    4  1608    3     2   0 200000 2068\n5    5  1454    3     3   0 159900 1477\n6    6  2997    3     2   1 499900 3153\n```\n:::\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\nsize_new <- lm(Price ~ Size + New, data = house)\nsummary(size_new)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n\nCall:\nlm(formula = Price ~ Size + New, data = house)\n\nResiduals:\n    Min      1Q  Median      3Q     Max \n-205102  -34374   -5778   18929  163866 \n\nCoefficients:\n              Estimate Std. Error t value Pr(>|t|)    \n(Intercept) -40230.867  14696.140  -2.738  0.00737 ** \nSize           116.132      8.795  13.204  < 2e-16 ***\nNew          57736.283  18653.041   3.095  0.00257 ** \n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n\nResidual standard error: 53880 on 97 degrees of freedom\nMultiple R-squared:  0.7226,\tAdjusted R-squared:  0.7169 \nF-statistic: 126.3 on 2 and 97 DF,  p-value: < 2.2e-16\n```\n:::\n:::\n\nBoth the size of the house and whether it is new are statistically significant factors in the selling price of these homes. For each square foot increase of house size, the price is impacted by $116.13. A home being new is worth $57,736.28 more on average than homes that are not.\n\n### 3B\nReport and interpret the prediction equation, and form separate equations relating selling price to size for new and for not new homes.\n\nThe prediction equation for the size_new model is y= -40230.867 +116.132x1 +57736.283x2, where x1 = size and x2 = new. \n\nThe prediction for new homes is y= -40230.867 +116.132x1 +57736.283x2\nThe prediction for old homes is y= -40230.867 +116.132x1\n\n### 3C \nFind the predicted selling price for a home of 3000 square feet that is (i) new, (ii) not new.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nprint(paste(\"The predicted selling price for a home of 3000 square feet that is NEW is $\",-40230.867 +116.132*3000 +57736.283))\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] \"The predicted selling price for a home of 3000 square feet that is NEW is $ 365901.416\"\n```\n:::\n\n```{.r .cell-code}\nprint(paste(\"The predicted selling price for a home of 3000 square feet that is NOT NEW is $\",-40230.867 +116.132*3000))\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] \"The predicted selling price for a home of 3000 square feet that is NOT NEW is $ 308165.133\"\n```\n:::\n:::\n\n\n### 3D\nFit another model, this time with an interaction term allowing interaction between size and new, and report the regression results\n\n\n::: {.cell}\n\n```{.r .cell-code}\nia <- lm(Price ~ Size*New, data = house)\nsummary(ia)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n\nCall:\nlm(formula = Price ~ Size * New, data = house)\n\nResiduals:\n    Min      1Q  Median      3Q     Max \n-175748  -28979   -6260   14693  192519 \n\nCoefficients:\n              Estimate Std. Error t value Pr(>|t|)    \n(Intercept) -22227.808  15521.110  -1.432  0.15536    \nSize           104.438      9.424  11.082  < 2e-16 ***\nNew         -78527.502  51007.642  -1.540  0.12697    \nSize:New        61.916     21.686   2.855  0.00527 ** \n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n\nResidual standard error: 52000 on 96 degrees of freedom\nMultiple R-squared:  0.7443,\tAdjusted R-squared:  0.7363 \nF-statistic: 93.15 on 3 and 96 DF,  p-value: < 2.2e-16\n```\n:::\n:::\n\nThe R-squared of the interaction model is slightly better than the previous, suggesting it may be a better fit. The interaction between size and \"newness\" of a house is significant.The effect of size when a house is new increases price by $61.916 per square foot.\n\n### 3E\nReport the lines relating the predicted selling price to the size for homes that are (i) new, (ii) not new.\n\nThe prediction equation would be y = -22,2227.808 + 104.438x1 - 78,527.502x2 + 61.916x1x2, where x1 = size and x2 = new.\n\nThe equation for predicting a new house with this model is y = -22,2227.808 + 104.438x1 - 78,527.502 + 61.916x1\nThe equation for predicting a NOT new house with this model y = -22,2227.808 + 104.438x1\n\n### 3F\nFind the predicted selling price for a home of 3000 square feet that is (i) new, (ii) not new.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nprint(paste(\"The predicted selling price for a home of 3000 square feet that is NEW is $\", -22227.808 + (104.438 * 3000) - (78527.502 * 1) + (61.916 * 3000 * 1)))\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] \"The predicted selling price for a home of 3000 square feet that is NEW is $ 398306.69\"\n```\n:::\n\n```{.r .cell-code}\nprint(paste(\"The predicted selling price for a home of 3000 square feet that is NOT NEW is $\",-22227.808 + (104.438 * 3000)))\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] \"The predicted selling price for a home of 3000 square feet that is NOT NEW is $ 291086.192\"\n```\n:::\n:::\n\n\n### 3G\nFind the predicted selling price for a home of 1500 square feet that is (i) new, (ii) not new. Comparing to (F), explain how the difference in predicted selling prices changes as the size of home increases.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nprint(paste(\"The predicted selling price for a home of 1500 square feet that is NEW is $\", -22227.808 + (104.438 * 1500) - (78527.502 * 1) + (61.916 * 1500 * 1)))\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] \"The predicted selling price for a home of 1500 square feet that is NEW is $ 148775.69\"\n```\n:::\n\n```{.r .cell-code}\nprint(paste(\"The predicted selling price for a home of 1500 square feet that is NOT NEW is $\",-22227.808 + (104.438 * 1500)))\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] \"The predicted selling price for a home of 1500 square feet that is NOT NEW is $ 134429.192\"\n```\n:::\n:::\n\nThere is less of a difference when size is smaller because there are 2 coefficients that increase price as size increases. So that bigger the house, the more impact \"new\" has to the price.\n\n### 3H\nDo you think the model with interaction or the one without it represents the relationship of size and new to the outcome price? What makes you prefer one model over another?\n\nI think the model with the interaction represents the relationship of size and new to the price of a house because of a couple of things. First, the fit of the model, seen in the higher R-squared, is slightly favorable than the non-interaction model. Also, logically, it makes sense that a bigger house with more new materials (lumber, counters, lights) would increase the price. \n\n",
    "supporting": [],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}