{
  "hash": "90083ea2c3f5edbe3ab30c2b54c38cc6",
  "result": {
    "markdown": "---\ntitle: \"Homework 4\"\nauthor: \"Niharika Pola\"\ndescription: \"homework-4\"\ndate: \"11/27/2022\"\nformat:\n  html:\n    df-print: paged\n    css: styles.css\n    toc: true\n    code-fold: true\n    code-copy: true\n    code-tools: true\ncategories:\n  - hw4\n---\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(tidyverse)\nlibrary(ggplot2)\nlibrary(stats)\nlibrary(alr4)\nlibrary(smss)\n\nknitr::opts_chunk$set(echo = TRUE)\n```\n:::\n\n\n## Question 1\n\n## A\n\n\n::: {.cell}\n\n```{.r .cell-code}\nPredicted_selling_price <-  -10536 + 53.8 * 1240 + 2.84 * 18000\nPredicted_selling_price\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 107296\n```\n:::\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\nResidual <- Predicted_selling_price - 145000\nResidual\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] -37704\n```\n:::\n:::\n\n\nFrom the above result, we can say that the house was sold for 37704 dollars greater than predicted.\n\n## B\n\nUsing the prediction equation ŷ = -10536 + 53.8x1 + 2.84x2, where x2 equals lot size, the house selling price is expected to increase by 53.8 dollars per each square-foot increase in home size given the lot sized is fixed. This is because a fixed lot size would make 2.84x2 a set number in the prediction equation. Therefore, we would not need to factor in a change in the output based on any input. Then, we are left with the coefficient for the home size variable, which is 53.8. For x1 = 1, representing one square-foot of home size, the output would increase by 53.8 \\* 1 = 53.8.\n\n## C\n\nFor fixed home size,\n\n53.8 \\* 1 = 2.84x2\n\n\n::: {.cell}\n\n```{.r .cell-code}\nx2 <- 53.8/2.84\nx2\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 18.94366\n```\n:::\n:::\n\n\nAn increase in lot size of about 18.94 square-feet would have the same impact as an increase of 1 square-foot in home size on the predicted selling price.\n\n## Question 2\n\n\n::: {.cell}\n\n```{.r .cell-code}\ndata(\"salary\")\nsalary\n```\n\n::: {.cell-output-display}\n`````{=html}\n<div data-pagedtable=\"false\">\n  <script data-pagedtable-source type=\"application/json\">\n{\"columns\":[{\"label\":[\"degree\"],\"name\":[1],\"type\":[\"fct\"],\"align\":[\"left\"]},{\"label\":[\"rank\"],\"name\":[2],\"type\":[\"fct\"],\"align\":[\"left\"]},{\"label\":[\"sex\"],\"name\":[3],\"type\":[\"fct\"],\"align\":[\"left\"]},{\"label\":[\"year\"],\"name\":[4],\"type\":[\"int\"],\"align\":[\"right\"]},{\"label\":[\"ysdeg\"],\"name\":[5],\"type\":[\"int\"],\"align\":[\"right\"]},{\"label\":[\"salary\"],\"name\":[6],\"type\":[\"int\"],\"align\":[\"right\"]}],\"data\":[{\"1\":\"Masters\",\"2\":\"Prof\",\"3\":\"Male\",\"4\":\"25\",\"5\":\"35\",\"6\":\"36350\"},{\"1\":\"Masters\",\"2\":\"Prof\",\"3\":\"Male\",\"4\":\"13\",\"5\":\"22\",\"6\":\"35350\"},{\"1\":\"Masters\",\"2\":\"Prof\",\"3\":\"Male\",\"4\":\"10\",\"5\":\"23\",\"6\":\"28200\"},{\"1\":\"Masters\",\"2\":\"Prof\",\"3\":\"Female\",\"4\":\"7\",\"5\":\"27\",\"6\":\"26775\"},{\"1\":\"PhD\",\"2\":\"Prof\",\"3\":\"Male\",\"4\":\"19\",\"5\":\"30\",\"6\":\"33696\"},{\"1\":\"Masters\",\"2\":\"Prof\",\"3\":\"Male\",\"4\":\"16\",\"5\":\"21\",\"6\":\"28516\"},{\"1\":\"PhD\",\"2\":\"Prof\",\"3\":\"Female\",\"4\":\"0\",\"5\":\"32\",\"6\":\"24900\"},{\"1\":\"Masters\",\"2\":\"Prof\",\"3\":\"Male\",\"4\":\"16\",\"5\":\"18\",\"6\":\"31909\"},{\"1\":\"PhD\",\"2\":\"Prof\",\"3\":\"Male\",\"4\":\"13\",\"5\":\"30\",\"6\":\"31850\"},{\"1\":\"PhD\",\"2\":\"Prof\",\"3\":\"Male\",\"4\":\"13\",\"5\":\"31\",\"6\":\"32850\"},{\"1\":\"Masters\",\"2\":\"Prof\",\"3\":\"Male\",\"4\":\"12\",\"5\":\"22\",\"6\":\"27025\"},{\"1\":\"Masters\",\"2\":\"Assoc\",\"3\":\"Male\",\"4\":\"15\",\"5\":\"19\",\"6\":\"24750\"},{\"1\":\"Masters\",\"2\":\"Prof\",\"3\":\"Male\",\"4\":\"9\",\"5\":\"17\",\"6\":\"28200\"},{\"1\":\"PhD\",\"2\":\"Assoc\",\"3\":\"Male\",\"4\":\"9\",\"5\":\"27\",\"6\":\"23712\"},{\"1\":\"Masters\",\"2\":\"Prof\",\"3\":\"Male\",\"4\":\"9\",\"5\":\"24\",\"6\":\"25748\"},{\"1\":\"Masters\",\"2\":\"Prof\",\"3\":\"Male\",\"4\":\"7\",\"5\":\"15\",\"6\":\"29342\"},{\"1\":\"Masters\",\"2\":\"Prof\",\"3\":\"Male\",\"4\":\"13\",\"5\":\"20\",\"6\":\"31114\"},{\"1\":\"PhD\",\"2\":\"Assoc\",\"3\":\"Male\",\"4\":\"11\",\"5\":\"14\",\"6\":\"24742\"},{\"1\":\"PhD\",\"2\":\"Assoc\",\"3\":\"Male\",\"4\":\"10\",\"5\":\"15\",\"6\":\"22906\"},{\"1\":\"PhD\",\"2\":\"Prof\",\"3\":\"Male\",\"4\":\"6\",\"5\":\"21\",\"6\":\"24450\"},{\"1\":\"PhD\",\"2\":\"Asst\",\"3\":\"Male\",\"4\":\"16\",\"5\":\"23\",\"6\":\"19175\"},{\"1\":\"PhD\",\"2\":\"Assoc\",\"3\":\"Male\",\"4\":\"8\",\"5\":\"31\",\"6\":\"20525\"},{\"1\":\"Masters\",\"2\":\"Prof\",\"3\":\"Male\",\"4\":\"7\",\"5\":\"13\",\"6\":\"27959\"},{\"1\":\"Masters\",\"2\":\"Prof\",\"3\":\"Female\",\"4\":\"8\",\"5\":\"24\",\"6\":\"38045\"},{\"1\":\"Masters\",\"2\":\"Assoc\",\"3\":\"Male\",\"4\":\"9\",\"5\":\"12\",\"6\":\"24832\"},{\"1\":\"Masters\",\"2\":\"Prof\",\"3\":\"Male\",\"4\":\"5\",\"5\":\"18\",\"6\":\"25400\"},{\"1\":\"Masters\",\"2\":\"Assoc\",\"3\":\"Male\",\"4\":\"11\",\"5\":\"14\",\"6\":\"24800\"},{\"1\":\"Masters\",\"2\":\"Prof\",\"3\":\"Female\",\"4\":\"5\",\"5\":\"16\",\"6\":\"25500\"},{\"1\":\"PhD\",\"2\":\"Assoc\",\"3\":\"Male\",\"4\":\"3\",\"5\":\"7\",\"6\":\"26182\"},{\"1\":\"PhD\",\"2\":\"Assoc\",\"3\":\"Male\",\"4\":\"3\",\"5\":\"17\",\"6\":\"23725\"},{\"1\":\"PhD\",\"2\":\"Asst\",\"3\":\"Female\",\"4\":\"10\",\"5\":\"15\",\"6\":\"21600\"},{\"1\":\"PhD\",\"2\":\"Assoc\",\"3\":\"Male\",\"4\":\"11\",\"5\":\"31\",\"6\":\"23300\"},{\"1\":\"PhD\",\"2\":\"Asst\",\"3\":\"Male\",\"4\":\"9\",\"5\":\"14\",\"6\":\"23713\"},{\"1\":\"PhD\",\"2\":\"Assoc\",\"3\":\"Female\",\"4\":\"4\",\"5\":\"33\",\"6\":\"20690\"},{\"1\":\"PhD\",\"2\":\"Assoc\",\"3\":\"Female\",\"4\":\"6\",\"5\":\"29\",\"6\":\"22450\"},{\"1\":\"Masters\",\"2\":\"Assoc\",\"3\":\"Male\",\"4\":\"1\",\"5\":\"9\",\"6\":\"20850\"},{\"1\":\"Masters\",\"2\":\"Asst\",\"3\":\"Female\",\"4\":\"8\",\"5\":\"14\",\"6\":\"18304\"},{\"1\":\"Masters\",\"2\":\"Asst\",\"3\":\"Male\",\"4\":\"4\",\"5\":\"4\",\"6\":\"17095\"},{\"1\":\"Masters\",\"2\":\"Asst\",\"3\":\"Male\",\"4\":\"4\",\"5\":\"5\",\"6\":\"16700\"},{\"1\":\"Masters\",\"2\":\"Asst\",\"3\":\"Male\",\"4\":\"4\",\"5\":\"4\",\"6\":\"17600\"},{\"1\":\"Masters\",\"2\":\"Asst\",\"3\":\"Male\",\"4\":\"3\",\"5\":\"4\",\"6\":\"18075\"},{\"1\":\"PhD\",\"2\":\"Asst\",\"3\":\"Male\",\"4\":\"3\",\"5\":\"11\",\"6\":\"18000\"},{\"1\":\"Masters\",\"2\":\"Assoc\",\"3\":\"Male\",\"4\":\"0\",\"5\":\"7\",\"6\":\"20999\"},{\"1\":\"Masters\",\"2\":\"Asst\",\"3\":\"Female\",\"4\":\"3\",\"5\":\"3\",\"6\":\"17250\"},{\"1\":\"Masters\",\"2\":\"Asst\",\"3\":\"Male\",\"4\":\"2\",\"5\":\"3\",\"6\":\"16500\"},{\"1\":\"Masters\",\"2\":\"Asst\",\"3\":\"Male\",\"4\":\"2\",\"5\":\"1\",\"6\":\"16094\"},{\"1\":\"Masters\",\"2\":\"Asst\",\"3\":\"Female\",\"4\":\"2\",\"5\":\"6\",\"6\":\"16150\"},{\"1\":\"Masters\",\"2\":\"Asst\",\"3\":\"Female\",\"4\":\"2\",\"5\":\"2\",\"6\":\"15350\"},{\"1\":\"Masters\",\"2\":\"Asst\",\"3\":\"Male\",\"4\":\"1\",\"5\":\"1\",\"6\":\"16244\"},{\"1\":\"Masters\",\"2\":\"Asst\",\"3\":\"Female\",\"4\":\"1\",\"5\":\"1\",\"6\":\"16686\"},{\"1\":\"Masters\",\"2\":\"Asst\",\"3\":\"Female\",\"4\":\"1\",\"5\":\"1\",\"6\":\"15000\"},{\"1\":\"Masters\",\"2\":\"Asst\",\"3\":\"Female\",\"4\":\"0\",\"5\":\"2\",\"6\":\"20300\"}],\"options\":{\"columns\":{\"min\":{},\"max\":[10]},\"rows\":{\"min\":[10],\"max\":[10]},\"pages\":{}}}\n  </script>\n</div>\n`````\n:::\n:::\n\n\n## A\n\n\n::: {.cell}\n\n```{.r .cell-code}\nsummary(lm(salary ~ sex, data = salary))\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n\nCall:\nlm(formula = salary ~ sex, data = salary)\n\nResiduals:\n    Min      1Q  Median      3Q     Max \n-8602.8 -4296.6  -100.8  3513.1 16687.9 \n\nCoefficients:\n            Estimate Std. Error t value Pr(>|t|)    \n(Intercept)    24697        938  26.330   <2e-16 ***\nsexFemale      -3340       1808  -1.847   0.0706 .  \n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n\nResidual standard error: 5782 on 50 degrees of freedom\nMultiple R-squared:  0.0639,\tAdjusted R-squared:  0.04518 \nF-statistic: 3.413 on 1 and 50 DF,  p-value: 0.0706\n```\n:::\n:::\n\n\nThe null hypothesis would be that mean salary for men and mean salary for women are equal, and the alternative hypothesis would be that the salaries are not equal. I ran a regression with sex as the explanatory variable and salary as the outcome variable. The female coefficient is -3340, which means that women do make less than men not considering any other variables. However, if we consider the other variables and also there is a significance level of 0.07, so we fail to reject the null hypothesis and therefore cannot conclude that there is a difference between mean salaries for men and women.\n\n## B\n\n\n::: {.cell}\n\n```{.r .cell-code}\nmodel <- lm(salary ~ ., data = salary)\nsummary(model)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n\nCall:\nlm(formula = salary ~ ., data = salary)\n\nResiduals:\n    Min      1Q  Median      3Q     Max \n-4045.2 -1094.7  -361.5   813.2  9193.1 \n\nCoefficients:\n            Estimate Std. Error t value Pr(>|t|)    \n(Intercept) 15746.05     800.18  19.678  < 2e-16 ***\ndegreePhD    1388.61    1018.75   1.363    0.180    \nrankAssoc    5292.36    1145.40   4.621 3.22e-05 ***\nrankProf    11118.76    1351.77   8.225 1.62e-10 ***\nsexFemale    1166.37     925.57   1.260    0.214    \nyear          476.31      94.91   5.018 8.65e-06 ***\nysdeg        -124.57      77.49  -1.608    0.115    \n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n\nResidual standard error: 2398 on 45 degrees of freedom\nMultiple R-squared:  0.855,\tAdjusted R-squared:  0.8357 \nF-statistic: 44.24 on 6 and 45 DF,  p-value: < 2.2e-16\n```\n:::\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\nconfint(model)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n                 2.5 %      97.5 %\n(Intercept) 14134.4059 17357.68946\ndegreePhD    -663.2482  3440.47485\nrankAssoc    2985.4107  7599.31080\nrankProf     8396.1546 13841.37340\nsexFemale    -697.8183  3030.56452\nyear          285.1433   667.47476\nysdeg        -280.6397    31.49105\n```\n:::\n:::\n\n\nAssuming there is no interaction between sex and other predictors, we can be 95% confident that the difference in salary of women compared to men falls between -697.8183 dollars and 3030.56452 dollars.\n\n## C\n\nFor degree as the predictor, a PHD would be expected to increase salary by 1388.61 dollars in reference to a Masters degree salary. However, at a significance level of 0.18, we cannot conclude that degree level has a statistically significant impact on salary.\n\nFor the rank variable, an Associate can expect a 5292.36 dollar increase in salary compared to Assistant, while a Professor can expect a 11118.76 dollar salary increase compared to Assistant. Both ranks have significance levels well below 0.05 and we can determine that rank does have a statistically significant impact on salary.\n\nFor the variable of sex, a Female can expect a salary increase of 1166.37 dollars in comparison to Male salary, but the significance level is 0.214, so this is not a statistically significant relationship.\n\nFor year, a faculty member can expect a salary increase of 476.31 dollars for an increase in 1 year of employment in his/her/their position. Additionally, the level of significance is less than 0.01 so the relationship between year and salary appears to be significant.\n\nFor the ysdeg variable, an increase in years since earning highest degree can expect a decrease in salary, with a coefficient of -124.57. However, with a 0.115 level of significance, this relationship cannot be found to be statistically significant.\n\n## D\n\n\n::: {.cell}\n\n```{.r .cell-code}\nsalary$rank <- relevel(salary$rank, ref = \"Prof\")\nsummary(lm(salary ~ rank, salary))\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n\nCall:\nlm(formula = salary ~ rank, data = salary)\n\nResiduals:\n    Min      1Q  Median      3Q     Max \n-5209.0 -1819.2  -417.8  1586.6  8386.0 \n\nCoefficients:\n            Estimate Std. Error t value Pr(>|t|)    \n(Intercept)  29659.0      669.3  44.316  < 2e-16 ***\nrankAsst    -11890.3      972.4 -12.228  < 2e-16 ***\nrankAssoc    -6483.0     1043.0  -6.216 1.09e-07 ***\n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n\nResidual standard error: 2993 on 49 degrees of freedom\nMultiple R-squared:  0.7542,\tAdjusted R-squared:  0.7442 \nF-statistic: 75.17 on 2 and 49 DF,  p-value: 1.174e-15\n```\n:::\n:::\n\n\nAfter changing the baseline category for the rank variable, an Associate can expect a 6483.0 dollar decrease in salary compared to Professor, while a Assistant can expect a 11890.3 dollar salary decrease compared to Professor. Both ranks have significance levels well below 0.05 and we can determine that rank does have a statistically significant impact on salary.\n\n## E\n\n\n::: {.cell}\n\n```{.r .cell-code}\nsummary(lm(salary ~ degree + sex + year + ysdeg, salary))\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n\nCall:\nlm(formula = salary ~ degree + sex + year + ysdeg, data = salary)\n\nResiduals:\n    Min      1Q  Median      3Q     Max \n-8146.9 -2186.9  -491.5  2279.1 11186.6 \n\nCoefficients:\n            Estimate Std. Error t value Pr(>|t|)    \n(Intercept) 17183.57    1147.94  14.969  < 2e-16 ***\ndegreePhD   -3299.35    1302.52  -2.533 0.014704 *  \nsexFemale   -1286.54    1313.09  -0.980 0.332209    \nyear          351.97     142.48   2.470 0.017185 *  \nysdeg         339.40      80.62   4.210 0.000114 ***\n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n\nResidual standard error: 3744 on 47 degrees of freedom\nMultiple R-squared:  0.6312,\tAdjusted R-squared:  0.5998 \nF-statistic: 20.11 on 4 and 47 DF,  p-value: 1.048e-09\n```\n:::\n:::\n\n\nWhen removing the variable \"rank\", the coefficient for sex is -1286.54 compared to the above regression that included rank with a coefficient for sex at 1166.37. The new coefficient predicts that a female salary would be 1286.54 less than a male salary, when excluding the variable of rank. However, the significance level is 0.332, which is very high and therefore the results cannot be found to be statistically significant. While the change of the coefficient to negative upon removal of rank is interesting, the significance level would likely prevent these results from holding up in court as an indication of discrimination on the basis of sex.\n\n## F\n\n\n::: {.cell}\n\n```{.r .cell-code}\nsalary <- salary %>%\n  mutate(hired = case_when(ysdeg <= 15 ~ \"1\", ysdeg > 15 ~ \"0\"))\nsummary(lm(salary ~ hired, data = salary))\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n\nCall:\nlm(formula = salary ~ hired, data = salary)\n\nResiduals:\n   Min     1Q Median     3Q    Max \n -8294  -3486  -1772   3829  10576 \n\nCoefficients:\n            Estimate Std. Error t value Pr(>|t|)    \n(Intercept)  27469.4      913.4  30.073  < 2e-16 ***\nhired1       -7343.5     1291.8  -5.685 6.73e-07 ***\n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n\nResidual standard error: 4658 on 50 degrees of freedom\nMultiple R-squared:  0.3926,\tAdjusted R-squared:  0.3804 \nF-statistic: 32.32 on 1 and 50 DF,  p-value: 6.734e-07\n```\n:::\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\nsummary(lm(salary ~ sex + rank + degree + hired, data = salary))\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n\nCall:\nlm(formula = salary ~ sex + rank + degree + hired, data = salary)\n\nResiduals:\n    Min      1Q  Median      3Q     Max \n-6187.5 -1750.9  -438.9  1719.5  9362.9 \n\nCoefficients:\n            Estimate Std. Error t value Pr(>|t|)    \n(Intercept)  29511.3      784.0  37.640  < 2e-16 ***\nsexFemale     -829.2      997.6  -0.831    0.410    \nrankAsst    -11925.7     1512.4  -7.885 4.37e-10 ***\nrankAssoc    -7100.4     1297.0  -5.474 1.76e-06 ***\ndegreePhD     1126.2     1018.4   1.106    0.275    \nhired1         319.0     1303.8   0.245    0.808    \n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n\nResidual standard error: 3023 on 46 degrees of freedom\nMultiple R-squared:  0.7645,\tAdjusted R-squared:  0.7389 \nF-statistic: 29.87 on 5 and 46 DF,  p-value: 2.192e-13\n```\n:::\n:::\n\n\nI created a dummy variable called \"hired\" which coded those employed for 15 years or less (thus hired by the new Dean) as 1 and those who have been employed for over 15 years as 0. Then, I fit a new regression model and decided to include the variables of sex, rank, degree, and hired. I omitted the year and ysdeg variables to prevent overlapping or multicollinearity. Multicollinearity can be a concern when variables are highly correlated or related in some way. The idea of regression is to observe how each variable partially effects the output while holding the other variables fixed. We cannot reasonably change the year or ysdeg or hired variables individually while holding the other two fixed since they tend to \"grow\" in similar manners. Since the variable hired is a product of the ysdeg variable, we could not include both.\n\nBased on the regression model, those hired by the current Dean are predicted to make 319 dollars more than those not hired by the Dean. When it comes to salary, this is a rather insignificant number. Furthermore, the level of significance for the hired variable is .81, which is astronomical and indicates that the relationship between hired and salary is not statistically significant. Based on these factors, I would state that findings do not indicate any favorable treatment by the Dean toward faculty that the Dean specifically hired.\n\n## Question 3\n\n\n::: {.cell}\n\n```{.r .cell-code}\ndata(\"house.selling.price\")\nhouse.selling.price\n```\n\n::: {.cell-output-display}\n`````{=html}\n<div data-pagedtable=\"false\">\n  <script data-pagedtable-source type=\"application/json\">\n{\"columns\":[{\"label\":[\"case\"],\"name\":[1],\"type\":[\"int\"],\"align\":[\"right\"]},{\"label\":[\"Taxes\"],\"name\":[2],\"type\":[\"int\"],\"align\":[\"right\"]},{\"label\":[\"Beds\"],\"name\":[3],\"type\":[\"int\"],\"align\":[\"right\"]},{\"label\":[\"Baths\"],\"name\":[4],\"type\":[\"int\"],\"align\":[\"right\"]},{\"label\":[\"New\"],\"name\":[5],\"type\":[\"int\"],\"align\":[\"right\"]},{\"label\":[\"Price\"],\"name\":[6],\"type\":[\"int\"],\"align\":[\"right\"]},{\"label\":[\"Size\"],\"name\":[7],\"type\":[\"int\"],\"align\":[\"right\"]}],\"data\":[{\"1\":\"1\",\"2\":\"3104\",\"3\":\"4\",\"4\":\"2\",\"5\":\"0\",\"6\":\"279900\",\"7\":\"2048\"},{\"1\":\"2\",\"2\":\"1173\",\"3\":\"2\",\"4\":\"1\",\"5\":\"0\",\"6\":\"146500\",\"7\":\"912\"},{\"1\":\"3\",\"2\":\"3076\",\"3\":\"4\",\"4\":\"2\",\"5\":\"0\",\"6\":\"237700\",\"7\":\"1654\"},{\"1\":\"4\",\"2\":\"1608\",\"3\":\"3\",\"4\":\"2\",\"5\":\"0\",\"6\":\"200000\",\"7\":\"2068\"},{\"1\":\"5\",\"2\":\"1454\",\"3\":\"3\",\"4\":\"3\",\"5\":\"0\",\"6\":\"159900\",\"7\":\"1477\"},{\"1\":\"6\",\"2\":\"2997\",\"3\":\"3\",\"4\":\"2\",\"5\":\"1\",\"6\":\"499900\",\"7\":\"3153\"},{\"1\":\"7\",\"2\":\"4054\",\"3\":\"3\",\"4\":\"2\",\"5\":\"0\",\"6\":\"265500\",\"7\":\"1355\"},{\"1\":\"8\",\"2\":\"3002\",\"3\":\"3\",\"4\":\"2\",\"5\":\"1\",\"6\":\"289900\",\"7\":\"2075\"},{\"1\":\"9\",\"2\":\"6627\",\"3\":\"5\",\"4\":\"4\",\"5\":\"0\",\"6\":\"587000\",\"7\":\"3990\"},{\"1\":\"10\",\"2\":\"320\",\"3\":\"3\",\"4\":\"2\",\"5\":\"0\",\"6\":\"70000\",\"7\":\"1160\"},{\"1\":\"11\",\"2\":\"630\",\"3\":\"3\",\"4\":\"2\",\"5\":\"0\",\"6\":\"64500\",\"7\":\"1220\"},{\"1\":\"12\",\"2\":\"1780\",\"3\":\"3\",\"4\":\"2\",\"5\":\"0\",\"6\":\"167000\",\"7\":\"1690\"},{\"1\":\"13\",\"2\":\"1630\",\"3\":\"3\",\"4\":\"2\",\"5\":\"0\",\"6\":\"114600\",\"7\":\"1380\"},{\"1\":\"14\",\"2\":\"1530\",\"3\":\"3\",\"4\":\"2\",\"5\":\"0\",\"6\":\"103000\",\"7\":\"1590\"},{\"1\":\"15\",\"2\":\"930\",\"3\":\"3\",\"4\":\"1\",\"5\":\"0\",\"6\":\"101000\",\"7\":\"1050\"},{\"1\":\"16\",\"2\":\"590\",\"3\":\"2\",\"4\":\"1\",\"5\":\"0\",\"6\":\"70000\",\"7\":\"770\"},{\"1\":\"17\",\"2\":\"1050\",\"3\":\"3\",\"4\":\"2\",\"5\":\"0\",\"6\":\"85000\",\"7\":\"1410\"},{\"1\":\"18\",\"2\":\"20\",\"3\":\"3\",\"4\":\"1\",\"5\":\"0\",\"6\":\"22500\",\"7\":\"1060\"},{\"1\":\"19\",\"2\":\"870\",\"3\":\"2\",\"4\":\"2\",\"5\":\"0\",\"6\":\"90000\",\"7\":\"1300\"},{\"1\":\"20\",\"2\":\"1320\",\"3\":\"3\",\"4\":\"2\",\"5\":\"0\",\"6\":\"133000\",\"7\":\"1500\"},{\"1\":\"21\",\"2\":\"1350\",\"3\":\"2\",\"4\":\"1\",\"5\":\"0\",\"6\":\"90500\",\"7\":\"820\"},{\"1\":\"22\",\"2\":\"5616\",\"3\":\"4\",\"4\":\"3\",\"5\":\"1\",\"6\":\"577500\",\"7\":\"3949\"},{\"1\":\"23\",\"2\":\"680\",\"3\":\"2\",\"4\":\"1\",\"5\":\"0\",\"6\":\"142500\",\"7\":\"1170\"},{\"1\":\"24\",\"2\":\"1840\",\"3\":\"3\",\"4\":\"2\",\"5\":\"0\",\"6\":\"160000\",\"7\":\"1500\"},{\"1\":\"25\",\"2\":\"3680\",\"3\":\"4\",\"4\":\"2\",\"5\":\"0\",\"6\":\"240000\",\"7\":\"2790\"},{\"1\":\"26\",\"2\":\"1660\",\"3\":\"3\",\"4\":\"1\",\"5\":\"0\",\"6\":\"87000\",\"7\":\"1030\"},{\"1\":\"27\",\"2\":\"1620\",\"3\":\"3\",\"4\":\"2\",\"5\":\"0\",\"6\":\"118600\",\"7\":\"1250\"},{\"1\":\"28\",\"2\":\"3100\",\"3\":\"3\",\"4\":\"2\",\"5\":\"0\",\"6\":\"140000\",\"7\":\"1760\"},{\"1\":\"29\",\"2\":\"2070\",\"3\":\"2\",\"4\":\"3\",\"5\":\"0\",\"6\":\"148000\",\"7\":\"1550\"},{\"1\":\"30\",\"2\":\"830\",\"3\":\"3\",\"4\":\"2\",\"5\":\"0\",\"6\":\"69000\",\"7\":\"1120\"},{\"1\":\"31\",\"2\":\"2260\",\"3\":\"4\",\"4\":\"2\",\"5\":\"0\",\"6\":\"176000\",\"7\":\"2000\"},{\"1\":\"32\",\"2\":\"1760\",\"3\":\"3\",\"4\":\"1\",\"5\":\"0\",\"6\":\"86500\",\"7\":\"1350\"},{\"1\":\"33\",\"2\":\"2750\",\"3\":\"3\",\"4\":\"2\",\"5\":\"1\",\"6\":\"180000\",\"7\":\"1840\"},{\"1\":\"34\",\"2\":\"2020\",\"3\":\"4\",\"4\":\"2\",\"5\":\"0\",\"6\":\"179000\",\"7\":\"2510\"},{\"1\":\"35\",\"2\":\"4900\",\"3\":\"3\",\"4\":\"3\",\"5\":\"1\",\"6\":\"338000\",\"7\":\"3110\"},{\"1\":\"36\",\"2\":\"1180\",\"3\":\"4\",\"4\":\"2\",\"5\":\"0\",\"6\":\"130000\",\"7\":\"1760\"},{\"1\":\"37\",\"2\":\"2150\",\"3\":\"3\",\"4\":\"2\",\"5\":\"0\",\"6\":\"163000\",\"7\":\"1710\"},{\"1\":\"38\",\"2\":\"1600\",\"3\":\"2\",\"4\":\"1\",\"5\":\"0\",\"6\":\"125000\",\"7\":\"1110\"},{\"1\":\"39\",\"2\":\"1970\",\"3\":\"3\",\"4\":\"2\",\"5\":\"0\",\"6\":\"100000\",\"7\":\"1360\"},{\"1\":\"40\",\"2\":\"2060\",\"3\":\"3\",\"4\":\"1\",\"5\":\"0\",\"6\":\"100000\",\"7\":\"1250\"},{\"1\":\"41\",\"2\":\"1980\",\"3\":\"3\",\"4\":\"1\",\"5\":\"0\",\"6\":\"100000\",\"7\":\"1250\"},{\"1\":\"42\",\"2\":\"1510\",\"3\":\"3\",\"4\":\"2\",\"5\":\"0\",\"6\":\"146500\",\"7\":\"1480\"},{\"1\":\"43\",\"2\":\"1710\",\"3\":\"3\",\"4\":\"2\",\"5\":\"0\",\"6\":\"144900\",\"7\":\"1520\"},{\"1\":\"44\",\"2\":\"1590\",\"3\":\"3\",\"4\":\"2\",\"5\":\"0\",\"6\":\"183000\",\"7\":\"2020\"},{\"1\":\"45\",\"2\":\"1230\",\"3\":\"3\",\"4\":\"2\",\"5\":\"0\",\"6\":\"69900\",\"7\":\"1010\"},{\"1\":\"46\",\"2\":\"1510\",\"3\":\"2\",\"4\":\"2\",\"5\":\"0\",\"6\":\"60000\",\"7\":\"1640\"},{\"1\":\"47\",\"2\":\"1450\",\"3\":\"2\",\"4\":\"2\",\"5\":\"0\",\"6\":\"127000\",\"7\":\"940\"},{\"1\":\"48\",\"2\":\"970\",\"3\":\"3\",\"4\":\"2\",\"5\":\"0\",\"6\":\"86000\",\"7\":\"1580\"},{\"1\":\"49\",\"2\":\"150\",\"3\":\"2\",\"4\":\"2\",\"5\":\"0\",\"6\":\"50000\",\"7\":\"860\"},{\"1\":\"50\",\"2\":\"1470\",\"3\":\"3\",\"4\":\"2\",\"5\":\"0\",\"6\":\"137000\",\"7\":\"1420\"},{\"1\":\"51\",\"2\":\"1850\",\"3\":\"3\",\"4\":\"2\",\"5\":\"0\",\"6\":\"121300\",\"7\":\"1270\"},{\"1\":\"52\",\"2\":\"820\",\"3\":\"2\",\"4\":\"1\",\"5\":\"0\",\"6\":\"81000\",\"7\":\"980\"},{\"1\":\"53\",\"2\":\"2050\",\"3\":\"4\",\"4\":\"2\",\"5\":\"0\",\"6\":\"188000\",\"7\":\"2300\"},{\"1\":\"54\",\"2\":\"710\",\"3\":\"3\",\"4\":\"2\",\"5\":\"0\",\"6\":\"85000\",\"7\":\"1430\"},{\"1\":\"55\",\"2\":\"1280\",\"3\":\"3\",\"4\":\"2\",\"5\":\"0\",\"6\":\"137000\",\"7\":\"1380\"},{\"1\":\"56\",\"2\":\"1360\",\"3\":\"3\",\"4\":\"2\",\"5\":\"0\",\"6\":\"145000\",\"7\":\"1240\"},{\"1\":\"57\",\"2\":\"830\",\"3\":\"3\",\"4\":\"2\",\"5\":\"0\",\"6\":\"69000\",\"7\":\"1120\"},{\"1\":\"58\",\"2\":\"800\",\"3\":\"3\",\"4\":\"2\",\"5\":\"0\",\"6\":\"109300\",\"7\":\"1120\"},{\"1\":\"59\",\"2\":\"1220\",\"3\":\"3\",\"4\":\"2\",\"5\":\"0\",\"6\":\"131500\",\"7\":\"1900\"},{\"1\":\"60\",\"2\":\"3360\",\"3\":\"4\",\"4\":\"3\",\"5\":\"0\",\"6\":\"200000\",\"7\":\"2430\"},{\"1\":\"61\",\"2\":\"210\",\"3\":\"3\",\"4\":\"2\",\"5\":\"0\",\"6\":\"81900\",\"7\":\"1080\"},{\"1\":\"62\",\"2\":\"380\",\"3\":\"2\",\"4\":\"1\",\"5\":\"0\",\"6\":\"91200\",\"7\":\"1350\"},{\"1\":\"63\",\"2\":\"1920\",\"3\":\"4\",\"4\":\"3\",\"5\":\"0\",\"6\":\"124500\",\"7\":\"1720\"},{\"1\":\"64\",\"2\":\"4350\",\"3\":\"3\",\"4\":\"3\",\"5\":\"0\",\"6\":\"225000\",\"7\":\"4050\"},{\"1\":\"65\",\"2\":\"1510\",\"3\":\"3\",\"4\":\"2\",\"5\":\"0\",\"6\":\"136500\",\"7\":\"1500\"},{\"1\":\"66\",\"2\":\"4154\",\"3\":\"3\",\"4\":\"3\",\"5\":\"0\",\"6\":\"381000\",\"7\":\"2581\"},{\"1\":\"67\",\"2\":\"1976\",\"3\":\"3\",\"4\":\"2\",\"5\":\"1\",\"6\":\"250000\",\"7\":\"2120\"},{\"1\":\"68\",\"2\":\"3605\",\"3\":\"3\",\"4\":\"3\",\"5\":\"1\",\"6\":\"354900\",\"7\":\"2745\"},{\"1\":\"69\",\"2\":\"1400\",\"3\":\"3\",\"4\":\"2\",\"5\":\"0\",\"6\":\"140000\",\"7\":\"1520\"},{\"1\":\"70\",\"2\":\"790\",\"3\":\"2\",\"4\":\"2\",\"5\":\"0\",\"6\":\"89900\",\"7\":\"1280\"},{\"1\":\"71\",\"2\":\"1210\",\"3\":\"3\",\"4\":\"2\",\"5\":\"0\",\"6\":\"137000\",\"7\":\"1620\"},{\"1\":\"72\",\"2\":\"1550\",\"3\":\"3\",\"4\":\"2\",\"5\":\"0\",\"6\":\"103000\",\"7\":\"1520\"},{\"1\":\"73\",\"2\":\"2800\",\"3\":\"3\",\"4\":\"2\",\"5\":\"0\",\"6\":\"183000\",\"7\":\"2030\"},{\"1\":\"74\",\"2\":\"2560\",\"3\":\"3\",\"4\":\"2\",\"5\":\"0\",\"6\":\"140000\",\"7\":\"1390\"},{\"1\":\"75\",\"2\":\"1390\",\"3\":\"4\",\"4\":\"2\",\"5\":\"0\",\"6\":\"160000\",\"7\":\"1880\"},{\"1\":\"76\",\"2\":\"5443\",\"3\":\"3\",\"4\":\"2\",\"5\":\"0\",\"6\":\"434000\",\"7\":\"2891\"},{\"1\":\"77\",\"2\":\"2850\",\"3\":\"2\",\"4\":\"1\",\"5\":\"0\",\"6\":\"130000\",\"7\":\"1340\"},{\"1\":\"78\",\"2\":\"2230\",\"3\":\"2\",\"4\":\"2\",\"5\":\"0\",\"6\":\"123000\",\"7\":\"940\"},{\"1\":\"79\",\"2\":\"20\",\"3\":\"2\",\"4\":\"1\",\"5\":\"0\",\"6\":\"21000\",\"7\":\"580\"},{\"1\":\"80\",\"2\":\"1510\",\"3\":\"4\",\"4\":\"2\",\"5\":\"0\",\"6\":\"85000\",\"7\":\"1410\"},{\"1\":\"81\",\"2\":\"710\",\"3\":\"3\",\"4\":\"2\",\"5\":\"0\",\"6\":\"69900\",\"7\":\"1150\"},{\"1\":\"82\",\"2\":\"1540\",\"3\":\"3\",\"4\":\"2\",\"5\":\"0\",\"6\":\"125000\",\"7\":\"1380\"},{\"1\":\"83\",\"2\":\"1780\",\"3\":\"3\",\"4\":\"2\",\"5\":\"1\",\"6\":\"162600\",\"7\":\"1470\"},{\"1\":\"84\",\"2\":\"2920\",\"3\":\"2\",\"4\":\"2\",\"5\":\"1\",\"6\":\"156900\",\"7\":\"1590\"},{\"1\":\"85\",\"2\":\"1710\",\"3\":\"3\",\"4\":\"2\",\"5\":\"1\",\"6\":\"105900\",\"7\":\"1200\"},{\"1\":\"86\",\"2\":\"1880\",\"3\":\"3\",\"4\":\"2\",\"5\":\"0\",\"6\":\"167500\",\"7\":\"1920\"},{\"1\":\"87\",\"2\":\"1680\",\"3\":\"3\",\"4\":\"2\",\"5\":\"0\",\"6\":\"151800\",\"7\":\"2150\"},{\"1\":\"88\",\"2\":\"3690\",\"3\":\"5\",\"4\":\"3\",\"5\":\"0\",\"6\":\"118300\",\"7\":\"2200\"},{\"1\":\"89\",\"2\":\"900\",\"3\":\"2\",\"4\":\"2\",\"5\":\"0\",\"6\":\"94300\",\"7\":\"860\"},{\"1\":\"90\",\"2\":\"560\",\"3\":\"3\",\"4\":\"1\",\"5\":\"0\",\"6\":\"93900\",\"7\":\"1230\"},{\"1\":\"91\",\"2\":\"2040\",\"3\":\"4\",\"4\":\"2\",\"5\":\"0\",\"6\":\"165000\",\"7\":\"1140\"},{\"1\":\"92\",\"2\":\"4390\",\"3\":\"4\",\"4\":\"3\",\"5\":\"1\",\"6\":\"285000\",\"7\":\"2650\"},{\"1\":\"93\",\"2\":\"690\",\"3\":\"3\",\"4\":\"1\",\"5\":\"0\",\"6\":\"45000\",\"7\":\"1060\"},{\"1\":\"94\",\"2\":\"2100\",\"3\":\"3\",\"4\":\"2\",\"5\":\"0\",\"6\":\"124900\",\"7\":\"1770\"},{\"1\":\"95\",\"2\":\"2880\",\"3\":\"4\",\"4\":\"2\",\"5\":\"0\",\"6\":\"147000\",\"7\":\"1860\"},{\"1\":\"96\",\"2\":\"990\",\"3\":\"2\",\"4\":\"2\",\"5\":\"0\",\"6\":\"176000\",\"7\":\"1060\"},{\"1\":\"97\",\"2\":\"3030\",\"3\":\"3\",\"4\":\"2\",\"5\":\"0\",\"6\":\"196500\",\"7\":\"1730\"},{\"1\":\"98\",\"2\":\"1580\",\"3\":\"3\",\"4\":\"2\",\"5\":\"0\",\"6\":\"132200\",\"7\":\"1370\"},{\"1\":\"99\",\"2\":\"1770\",\"3\":\"3\",\"4\":\"2\",\"5\":\"0\",\"6\":\"88400\",\"7\":\"1560\"},{\"1\":\"100\",\"2\":\"1430\",\"3\":\"3\",\"4\":\"2\",\"5\":\"0\",\"6\":\"127200\",\"7\":\"1340\"}],\"options\":{\"columns\":{\"min\":{},\"max\":[10]},\"rows\":{\"min\":[10],\"max\":[10]},\"pages\":{}}}\n  </script>\n</div>\n`````\n:::\n:::\n\n\n## A\n\n\n::: {.cell}\n\n```{.r .cell-code}\nsummary(lm(Price ~ Size + New, house.selling.price))\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n\nCall:\nlm(formula = Price ~ Size + New, data = house.selling.price)\n\nResiduals:\n    Min      1Q  Median      3Q     Max \n-205102  -34374   -5778   18929  163866 \n\nCoefficients:\n              Estimate Std. Error t value Pr(>|t|)    \n(Intercept) -40230.867  14696.140  -2.738  0.00737 ** \nSize           116.132      8.795  13.204  < 2e-16 ***\nNew          57736.283  18653.041   3.095  0.00257 ** \n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n\nResidual standard error: 53880 on 97 degrees of freedom\nMultiple R-squared:  0.7226,\tAdjusted R-squared:  0.7169 \nF-statistic: 126.3 on 2 and 97 DF,  p-value: < 2.2e-16\n```\n:::\n:::\n\n\nBoth Size and New significantly positively predict selling price. As each predictor goes up by 1 unit, selling price rises by 116.132 dollars and 57736.283 dollars respectively.\n\n## B\n\n\n::: {.cell}\n\n```{.r .cell-code}\nnew <- house.selling.price %>% \n  filter(New == 1)\nsummary(lm(Price ~ Size, data = new))\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n\nCall:\nlm(formula = Price ~ Size, data = new)\n\nResiduals:\n   Min     1Q Median     3Q    Max \n-78606 -16092   -987  20068  76140 \n\nCoefficients:\n              Estimate Std. Error t value Pr(>|t|)    \n(Intercept) -100755.31   42513.73  -2.370   0.0419 *  \nSize            166.35      17.09   9.735 4.47e-06 ***\n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n\nResidual standard error: 45500 on 9 degrees of freedom\nMultiple R-squared:  0.9133,\tAdjusted R-squared:  0.9036 \nF-statistic: 94.76 on 1 and 9 DF,  p-value: 4.474e-06\n```\n:::\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\nold <- house.selling.price %>% \n  filter(New == 0)\nsummary(lm(Price ~ Size, data = old))\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n\nCall:\nlm(formula = Price ~ Size, data = old)\n\nResiduals:\n    Min      1Q  Median      3Q     Max \n-175748  -29155   -7297   14159  192519 \n\nCoefficients:\n              Estimate Std. Error t value Pr(>|t|)    \n(Intercept) -22227.808  15708.186  -1.415    0.161    \nSize           104.438      9.538  10.950   <2e-16 ***\n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n\nResidual standard error: 52620 on 87 degrees of freedom\nMultiple R-squared:  0.5795,\tAdjusted R-squared:  0.5747 \nF-statistic: 119.9 on 1 and 87 DF,  p-value: < 2.2e-16\n```\n:::\n:::\n\n\nSize significantly positively predicts price for both new and old houses, but by a greater magnitude for new houses. Adjusted R-squared for the model is also much higher (0.91 vs. 0.58).\n\nNew_Price = 166 \\* Size - 100755.31\n\nOld_Price = 104 \\* Size - 22227.808\n\n## C\n\n\n::: {.cell}\n\n```{.r .cell-code}\nSize <- 3000\nNew_Price = 166 * Size - 100755.31\nOld_Price = 104 * Size - 22227.808\nNew_Price\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 397244.7\n```\n:::\n\n```{.r .cell-code}\nOld_Price\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 289772.2\n```\n:::\n:::\n\n\n## D\n\n\n::: {.cell}\n\n```{.r .cell-code}\nsummary(lm(Price ~ Size*New, data = house.selling.price))\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n\nCall:\nlm(formula = Price ~ Size * New, data = house.selling.price)\n\nResiduals:\n    Min      1Q  Median      3Q     Max \n-175748  -28979   -6260   14693  192519 \n\nCoefficients:\n              Estimate Std. Error t value Pr(>|t|)    \n(Intercept) -22227.808  15521.110  -1.432  0.15536    \nSize           104.438      9.424  11.082  < 2e-16 ***\nNew         -78527.502  51007.642  -1.540  0.12697    \nSize:New        61.916     21.686   2.855  0.00527 ** \n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n\nResidual standard error: 52000 on 96 degrees of freedom\nMultiple R-squared:  0.7443,\tAdjusted R-squared:  0.7363 \nF-statistic: 93.15 on 3 and 96 DF,  p-value: < 2.2e-16\n```\n:::\n:::\n\n\n## E\n\nThe predicted selling price, based on the new regression that includes interaction between Size and Newness, would look like:\n\nNew_Price = -22227.81 + 104.44 \\* Size - 78527.50 \\* 1 + 61.92 \\* Size \\* 1\n\nOld_Price = -22227.81 + 104.44 \\* Size\n\n## F\n\n\n::: {.cell}\n\n```{.r .cell-code}\nSize <- 3000\nNew_Price = -22227.81 + 104.44 * Size - 78527.50 * 1 + 61.92 * Size * 1\nOld_Price = -22227.81 + 104.44 * Size\nNew_Price\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 398324.7\n```\n:::\n\n```{.r .cell-code}\nOld_Price\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 291092.2\n```\n:::\n:::\n\n\n## G\n\n\n::: {.cell}\n\n```{.r .cell-code}\nSize <- 1500\nNew_Price = -22227.81 + 104.44 * Size - 78527.50 * 1 + 61.92 * Size * 1\nOld_Price = -22227.81 + 104.44 * Size\nNew_Price\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 148784.7\n```\n:::\n\n```{.r .cell-code}\nOld_Price\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 134432.2\n```\n:::\n:::\n\n\nAs size of home goes up, the difference in predicted selling prices between old and new homes becomes larger.\n\n## H\n\nThe prediction model with interaction has a significantly large negative coefficient for the New variable. The adjusted r-squared for the model with interaction is 0.7363 and the adjusted r-squared for the first model without interaction is 0.7169. The increase in the adjusted r-squared with the interaction model could be due to an additional variable or could indicate a slightly better fit for the prediction of the data. Since the models do have similar adjusted r-squared values, I would prefer the model with interaction because the regression indicates that the interaction term is statistically significant to selling price prediction, so I feel it is necessary to utilize an equation that factors for this.\n",
    "supporting": [],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {
      "include-in-header": [
        "<link href=\"../site_libs/pagedtable-1.1/css/pagedtable.css\" rel=\"stylesheet\" />\r\n<script src=\"../site_libs/pagedtable-1.1/js/pagedtable.js\"></script>\r\n"
      ]
    },
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}