{
  "hash": "b2ff64fe4700f466487a608031633cbd",
  "result": {
    "markdown": "---\ntitle: \"Homework 4\"\nauthor: \"Nick Boonstra\"\ndate: \"November 16, 2022\"\nformat:\n  html:\n    code-fold: true\n---\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(tidyverse)\n```\n\n::: {.cell-output .cell-output-stderr}\n```\n── Attaching packages ─────────────────────────────────────── tidyverse 1.3.2 ──\n✔ ggplot2 3.3.6      ✔ purrr   0.3.5 \n✔ tibble  3.1.8      ✔ dplyr   1.0.10\n✔ tidyr   1.2.1      ✔ stringr 1.4.1 \n✔ readr   2.1.3      ✔ forcats 0.5.2 \n── Conflicts ────────────────────────────────────────── tidyverse_conflicts() ──\n✖ dplyr::filter() masks stats::filter()\n✖ dplyr::lag()    masks stats::lag()\n```\n:::\n\n```{.r .cell-code}\nlibrary(alr4)\n```\n\n::: {.cell-output .cell-output-stderr}\n```\nLoading required package: car\nLoading required package: carData\n\nAttaching package: 'car'\n\nThe following object is masked from 'package:dplyr':\n\n    recode\n\nThe following object is masked from 'package:purrr':\n\n    some\n\nLoading required package: effects\nlattice theme set by effectsTheme()\nSee ?effectsTheme for details.\n```\n:::\n\n```{.r .cell-code}\nlibrary(smss)\n```\n\n::: {.cell-output .cell-output-stderr}\n```\nWarning: package 'smss' was built under R version 4.2.2\n```\n:::\n:::\n\n\n# Question 1\n\nThe prediction equation for selling price of homes in Jacksonville, FL ($y$) is given as:\n\n$\\hat{y} = -10,536 + 53.8x_1 + 2.84x_2$\n\nwhere $x_1$ is the size of the home and $x_2$ is the size of the lot (both in square feet).\n\n## Part A\n\n\n::: {.cell}\n\n```{.r .cell-code}\nq1_a_price <- 145000\nq1_a_predict <- (53.8*1240) + (2.84*18000)\nprint(c(\"Predicted price = \",q1_a_predict))\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] \"Predicted price = \" \"117832\"            \n```\n:::\n\n```{.r .cell-code}\nresidual <- q1_a_price - q1_a_predict\nprint(c(\"Residual = \",residual))\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] \"Residual = \" \"27168\"      \n```\n:::\n:::\n\n\nAccording to the model, predicted selling price was roughly 118000 USD. The residual of roughly 28000 means that the model underpredicted the selling price by roughly 28000 USD.\n\n## Part B\n\nFor fixed lot size, the house price is expected to increase by 53.8 USD as the square footage of the house itself increases in 1. This is because the coefficient for the home size square footage is 53.8.\n\n## Part C\n\nLot size would need to increase by 18.943662 to have the same impact as a one-square-foot increase in home size.\n\n\n# Question 2\n\n\n::: {.cell}\n\n```{.r .cell-code}\ndata(salary)\nsalary\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n    degree  rank    sex year ysdeg salary\n1  Masters  Prof   Male   25    35  36350\n2  Masters  Prof   Male   13    22  35350\n3  Masters  Prof   Male   10    23  28200\n4  Masters  Prof Female    7    27  26775\n5      PhD  Prof   Male   19    30  33696\n6  Masters  Prof   Male   16    21  28516\n7      PhD  Prof Female    0    32  24900\n8  Masters  Prof   Male   16    18  31909\n9      PhD  Prof   Male   13    30  31850\n10     PhD  Prof   Male   13    31  32850\n11 Masters  Prof   Male   12    22  27025\n12 Masters Assoc   Male   15    19  24750\n13 Masters  Prof   Male    9    17  28200\n14     PhD Assoc   Male    9    27  23712\n15 Masters  Prof   Male    9    24  25748\n16 Masters  Prof   Male    7    15  29342\n17 Masters  Prof   Male   13    20  31114\n18     PhD Assoc   Male   11    14  24742\n19     PhD Assoc   Male   10    15  22906\n20     PhD  Prof   Male    6    21  24450\n21     PhD  Asst   Male   16    23  19175\n22     PhD Assoc   Male    8    31  20525\n23 Masters  Prof   Male    7    13  27959\n24 Masters  Prof Female    8    24  38045\n25 Masters Assoc   Male    9    12  24832\n26 Masters  Prof   Male    5    18  25400\n27 Masters Assoc   Male   11    14  24800\n28 Masters  Prof Female    5    16  25500\n29     PhD Assoc   Male    3     7  26182\n30     PhD Assoc   Male    3    17  23725\n31     PhD  Asst Female   10    15  21600\n32     PhD Assoc   Male   11    31  23300\n33     PhD  Asst   Male    9    14  23713\n34     PhD Assoc Female    4    33  20690\n35     PhD Assoc Female    6    29  22450\n36 Masters Assoc   Male    1     9  20850\n37 Masters  Asst Female    8    14  18304\n38 Masters  Asst   Male    4     4  17095\n39 Masters  Asst   Male    4     5  16700\n40 Masters  Asst   Male    4     4  17600\n41 Masters  Asst   Male    3     4  18075\n42     PhD  Asst   Male    3    11  18000\n43 Masters Assoc   Male    0     7  20999\n44 Masters  Asst Female    3     3  17250\n45 Masters  Asst   Male    2     3  16500\n46 Masters  Asst   Male    2     1  16094\n47 Masters  Asst Female    2     6  16150\n48 Masters  Asst Female    2     2  15350\n49 Masters  Asst   Male    1     1  16244\n50 Masters  Asst Female    1     1  16686\n51 Masters  Asst Female    1     1  15000\n52 Masters  Asst Female    0     2  20300\n```\n:::\n:::\n\n\n## Part A\n\n\n::: {.cell}\n\n```{.r .cell-code}\nsalary_men <- salary %>% \n  filter(sex == \"Male\")\nsalary_women <- salary %>% \n  filter(sex == \"Female\")\n\nt.test(salary_men$salary,salary_women$salary)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n\n\tWelch Two Sample t-test\n\ndata:  salary_men$salary and salary_women$salary\nt = 1.7744, df = 21.591, p-value = 0.09009\nalternative hypothesis: true difference in means is not equal to 0\n95 percent confidence interval:\n -567.8539 7247.1471\nsample estimates:\nmean of x mean of y \n 24696.79  21357.14 \n```\n:::\n:::\n\n\nThe findings of a two-sample Welch's t-test comparing salary by sex are inconclusive; the difference in means is not significant at a 95% confidence level, but is significant at a 90% confidence level, suggesting that further investigation (i.e. multiple regression) could yield significant results.\n\n## Part B\n\n\n::: {.cell}\n\n```{.r .cell-code}\nq2_lm <- lm(\n  salary ~\n    .,\n  data = salary\n)\nsummary(q2_lm)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n\nCall:\nlm(formula = salary ~ ., data = salary)\n\nResiduals:\n    Min      1Q  Median      3Q     Max \n-4045.2 -1094.7  -361.5   813.2  9193.1 \n\nCoefficients:\n            Estimate Std. Error t value Pr(>|t|)    \n(Intercept) 15746.05     800.18  19.678  < 2e-16 ***\ndegreePhD    1388.61    1018.75   1.363    0.180    \nrankAssoc    5292.36    1145.40   4.621 3.22e-05 ***\nrankProf    11118.76    1351.77   8.225 1.62e-10 ***\nsexFemale    1166.37     925.57   1.260    0.214    \nyear          476.31      94.91   5.018 8.65e-06 ***\nysdeg        -124.57      77.49  -1.608    0.115    \n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n\nResidual standard error: 2398 on 45 degrees of freedom\nMultiple R-squared:  0.855,\tAdjusted R-squared:  0.8357 \nF-statistic: 44.24 on 6 and 45 DF,  p-value: < 2.2e-16\n```\n:::\n:::\n\n\nThe 95% confidence interval for the coefficient of `sexFemale` is the range between -481.0138205 on the low end and 2813.7538205 on the high end. Because this range of values passes from negative to positive (i.e. crosses 0), we say that the result is insignificant at a 95% confidence level.\n\n## Part C\n\n1.5746048\\times 10^{4} -- All other things being equal, a professor at this university could be expected to earn \\$15746.05. This coefficient is significant beyond a 99% confidence level.\n\n1388.6133186 -- A professor with a PhD would be expected to make \\$1,388.61 more than one with a Master's degree. However, this coefficient is not significant at a 95% confidence level.\n\n5292.3607713 -- An Associate Professor would be expected to make \\$5292.36 more than an Assistant Professor. This coefficient is significant at a 95% confidence level.\n\n1.1118764\\times 10^{4} -- A Full Professor would be expected to make \\$11118.76 more than an Assistant Professor. This coefficient is significant at a 95% confidence level.\n\n1166.373101 -- A female professor would be expected to make \\$1166.37 more than a male professor based on this model. However, the coefficient is not significant at a 95% confidence level. The direction of the sign, and the lack of significance, would both help to discredit the notion that female professors earn less than male professors at this university systemically.\n\n476.3090151 -- Each additional year of experience in one's current rank would be expected to earn a professor an additional \\$476.31 per year. This coefficient is significant at a 95% confidence level.\n\n-124.5743208 -- A professor would be expected to earn \\$124.57 less per year based on each year since they earned their highest degree according to this model. However, this coefficient is not significant at a 95% confidence level, which is good, because this effect wouldn't make much sense when considering the real-world meaning of the coefficient.\n\n## Part D\n\n::: {.cell}\n\n```{.r .cell-code}\nsalary$rank <- factor(salary$rank, levels = c(\"Prof\",\"Asst\",\"Assoc\"))\n\nsummary(lm(\n  salary ~\n    .,\n  data = salary\n))\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n\nCall:\nlm(formula = salary ~ ., data = salary)\n\nResiduals:\n    Min      1Q  Median      3Q     Max \n-4045.2 -1094.7  -361.5   813.2  9193.1 \n\nCoefficients:\n             Estimate Std. Error t value Pr(>|t|)    \n(Intercept)  26864.81    1375.29  19.534  < 2e-16 ***\ndegreePhD     1388.61    1018.75   1.363    0.180    \nrankAsst    -11118.76    1351.77  -8.225 1.62e-10 ***\nrankAssoc    -5826.40    1012.93  -5.752 7.28e-07 ***\nsexFemale     1166.37     925.57   1.260    0.214    \nyear           476.31      94.91   5.018 8.65e-06 ***\nysdeg         -124.57      77.49  -1.608    0.115    \n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n\nResidual standard error: 2398 on 45 degrees of freedom\nMultiple R-squared:  0.855,\tAdjusted R-squared:  0.8357 \nF-statistic: 44.24 on 6 and 45 DF,  p-value: < 2.2e-16\n```\n:::\n:::\n\n\nReordering the `rank` variable to put the \"Prof\" level first yields the above regression table. As in the first regression, Assistant Professors are here expected to make \\$11118.76 less per year than Full Professors. Associate Professors are expected to make \\$5826.40 less per year than Full Professors. Both of these coefficients are significant at a 95% confidence level.\n\n## Part E\n\n\n::: {.cell}\n\n```{.r .cell-code}\nsummary(lm(\n  salary ~\n    . - rank,\n  data = salary\n))\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n\nCall:\nlm(formula = salary ~ . - rank, data = salary)\n\nResiduals:\n    Min      1Q  Median      3Q     Max \n-8146.9 -2186.9  -491.5  2279.1 11186.6 \n\nCoefficients:\n            Estimate Std. Error t value Pr(>|t|)    \n(Intercept) 17183.57    1147.94  14.969  < 2e-16 ***\ndegreePhD   -3299.35    1302.52  -2.533 0.014704 *  \nsexFemale   -1286.54    1313.09  -0.980 0.332209    \nyear          351.97     142.48   2.470 0.017185 *  \nysdeg         339.40      80.62   4.210 0.000114 ***\n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n\nResidual standard error: 3744 on 47 degrees of freedom\nMultiple R-squared:  0.6312,\tAdjusted R-squared:  0.5998 \nF-statistic: 20.11 on 4 and 47 DF,  p-value: 1.048e-09\n```\n:::\n:::\n\n\nWith `rank` excluded, `ysdeg` becomes positive and significant. The coefficient for `sexFemale` is now negative, but is still not significant.\n\n## Part F\n\n\n::: {.cell}\n\n```{.r .cell-code}\nsalary_dean <- salary %>% \n  mutate(dean = case_when(\n    ysdeg <= 15 ~ 1,\n    T ~ 0\n  ))\n\nsummary(lm(\n  salary ~\n    . - ysdeg,\n  data = salary_dean\n))\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n\nCall:\nlm(formula = salary ~ . - ysdeg, data = salary_dean)\n\nResiduals:\n    Min      1Q  Median      3Q     Max \n-3403.3 -1387.0  -167.0   528.2  9233.8 \n\nCoefficients:\n             Estimate Std. Error t value Pr(>|t|)    \n(Intercept)  24425.32    1107.52  22.054  < 2e-16 ***\ndegreePhD      818.93     797.48   1.027   0.3100    \nrankAsst    -11096.95    1191.00  -9.317 4.54e-12 ***\nrankAssoc    -6124.28    1028.58  -5.954 3.65e-07 ***\nsexFemale      907.14     840.54   1.079   0.2862    \nyear           434.85      78.89   5.512 1.65e-06 ***\ndean          2163.46    1072.04   2.018   0.0496 *  \n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n\nResidual standard error: 2362 on 45 degrees of freedom\nMultiple R-squared:  0.8594,\tAdjusted R-squared:  0.8407 \nF-statistic: 45.86 on 6 and 45 DF,  p-value: < 2.2e-16\n```\n:::\n:::\n\n\nBecause `dean` is based on `ysdeg`, and because `year` and `ysdeg` measure overlapping lengths of time, I excluded `ysdeg` for this model. The results are similar to those above, most notably in the lack of significance for the coefficient of `sexFemale`.\n\n# Question 3\n\n\n::: {.cell}\n\n```{.r .cell-code}\ndata(house.selling.price)\nhouse.selling.price\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n    case Taxes Beds Baths New  Price Size\n1      1  3104    4     2   0 279900 2048\n2      2  1173    2     1   0 146500  912\n3      3  3076    4     2   0 237700 1654\n4      4  1608    3     2   0 200000 2068\n5      5  1454    3     3   0 159900 1477\n6      6  2997    3     2   1 499900 3153\n7      7  4054    3     2   0 265500 1355\n8      8  3002    3     2   1 289900 2075\n9      9  6627    5     4   0 587000 3990\n10    10   320    3     2   0  70000 1160\n11    11   630    3     2   0  64500 1220\n12    12  1780    3     2   0 167000 1690\n13    13  1630    3     2   0 114600 1380\n14    14  1530    3     2   0 103000 1590\n15    15   930    3     1   0 101000 1050\n16    16   590    2     1   0  70000  770\n17    17  1050    3     2   0  85000 1410\n18    18    20    3     1   0  22500 1060\n19    19   870    2     2   0  90000 1300\n20    20  1320    3     2   0 133000 1500\n21    21  1350    2     1   0  90500  820\n22    22  5616    4     3   1 577500 3949\n23    23   680    2     1   0 142500 1170\n24    24  1840    3     2   0 160000 1500\n25    25  3680    4     2   0 240000 2790\n26    26  1660    3     1   0  87000 1030\n27    27  1620    3     2   0 118600 1250\n28    28  3100    3     2   0 140000 1760\n29    29  2070    2     3   0 148000 1550\n30    30   830    3     2   0  69000 1120\n31    31  2260    4     2   0 176000 2000\n32    32  1760    3     1   0  86500 1350\n33    33  2750    3     2   1 180000 1840\n34    34  2020    4     2   0 179000 2510\n35    35  4900    3     3   1 338000 3110\n36    36  1180    4     2   0 130000 1760\n37    37  2150    3     2   0 163000 1710\n38    38  1600    2     1   0 125000 1110\n39    39  1970    3     2   0 100000 1360\n40    40  2060    3     1   0 100000 1250\n41    41  1980    3     1   0 100000 1250\n42    42  1510    3     2   0 146500 1480\n43    43  1710    3     2   0 144900 1520\n44    44  1590    3     2   0 183000 2020\n45    45  1230    3     2   0  69900 1010\n46    46  1510    2     2   0  60000 1640\n47    47  1450    2     2   0 127000  940\n48    48   970    3     2   0  86000 1580\n49    49   150    2     2   0  50000  860\n50    50  1470    3     2   0 137000 1420\n51    51  1850    3     2   0 121300 1270\n52    52   820    2     1   0  81000  980\n53    53  2050    4     2   0 188000 2300\n54    54   710    3     2   0  85000 1430\n55    55  1280    3     2   0 137000 1380\n56    56  1360    3     2   0 145000 1240\n57    57   830    3     2   0  69000 1120\n58    58   800    3     2   0 109300 1120\n59    59  1220    3     2   0 131500 1900\n60    60  3360    4     3   0 200000 2430\n61    61   210    3     2   0  81900 1080\n62    62   380    2     1   0  91200 1350\n63    63  1920    4     3   0 124500 1720\n64    64  4350    3     3   0 225000 4050\n65    65  1510    3     2   0 136500 1500\n66    66  4154    3     3   0 381000 2581\n67    67  1976    3     2   1 250000 2120\n68    68  3605    3     3   1 354900 2745\n69    69  1400    3     2   0 140000 1520\n70    70   790    2     2   0  89900 1280\n71    71  1210    3     2   0 137000 1620\n72    72  1550    3     2   0 103000 1520\n73    73  2800    3     2   0 183000 2030\n74    74  2560    3     2   0 140000 1390\n75    75  1390    4     2   0 160000 1880\n76    76  5443    3     2   0 434000 2891\n77    77  2850    2     1   0 130000 1340\n78    78  2230    2     2   0 123000  940\n79    79    20    2     1   0  21000  580\n80    80  1510    4     2   0  85000 1410\n81    81   710    3     2   0  69900 1150\n82    82  1540    3     2   0 125000 1380\n83    83  1780    3     2   1 162600 1470\n84    84  2920    2     2   1 156900 1590\n85    85  1710    3     2   1 105900 1200\n86    86  1880    3     2   0 167500 1920\n87    87  1680    3     2   0 151800 2150\n88    88  3690    5     3   0 118300 2200\n89    89   900    2     2   0  94300  860\n90    90   560    3     1   0  93900 1230\n91    91  2040    4     2   0 165000 1140\n92    92  4390    4     3   1 285000 2650\n93    93   690    3     1   0  45000 1060\n94    94  2100    3     2   0 124900 1770\n95    95  2880    4     2   0 147000 1860\n96    96   990    2     2   0 176000 1060\n97    97  3030    3     2   0 196500 1730\n98    98  1580    3     2   0 132200 1370\n99    99  1770    3     2   0  88400 1560\n100  100  1430    3     2   0 127200 1340\n```\n:::\n:::\n\n\n## Part A\n\n\n::: {.cell}\n\n```{.r .cell-code}\nq3_lm <- lm(\n  Price ~ \n    Size + New,\n  data = house.selling.price\n)\nsummary(q3_lm)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n\nCall:\nlm(formula = Price ~ Size + New, data = house.selling.price)\n\nResiduals:\n    Min      1Q  Median      3Q     Max \n-205102  -34374   -5778   18929  163866 \n\nCoefficients:\n              Estimate Std. Error t value Pr(>|t|)    \n(Intercept) -40230.867  14696.140  -2.738  0.00737 ** \nSize           116.132      8.795  13.204  < 2e-16 ***\nNew          57736.283  18653.041   3.095  0.00257 ** \n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n\nResidual standard error: 53880 on 97 degrees of freedom\nMultiple R-squared:  0.7226,\tAdjusted R-squared:  0.7169 \nF-statistic: 126.3 on 2 and 97 DF,  p-value: < 2.2e-16\n```\n:::\n:::\n\n\nAll coefficients are significant. The intercept (i.e. a theoretical house of no size that is not new) is -\\$42390.87. Each square foot increases house price by \\$116.13. A new house would be expected to sell for \\$57736.28 more than an old house of equal size.\n\n## Part B\n\n$y$ is equal to predicted selling price in USD, and $x$ is equal to house size in square feet.\n\nNew home:\n\n$y = 17505.42 + 116.13x$\n\nOld home:\n\n$y = -40230.87 + 116.132x$\n\n## Part C\n\n\n::: {.cell}\n\n```{.r .cell-code}\nq3_predict <- data.frame(\n  Size = c(3000,3000),\n  New = c(1,0)\n)\npredict(q3_lm,newdata=q3_predict)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n       1        2 \n365900.2 308163.9 \n```\n:::\n:::\n\n\nThe new house would be expected to sell for \\$365900, while the not-new house would be expected to sell for about \\$308000.\n\n## Part D\n\n\n::: {.cell}\n\n```{.r .cell-code}\nq3_lm_interact <- lm(\n  Price ~ \n    Size * New,\n  data = house.selling.price\n)\nsummary(q3_lm_interact)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n\nCall:\nlm(formula = Price ~ Size * New, data = house.selling.price)\n\nResiduals:\n    Min      1Q  Median      3Q     Max \n-175748  -28979   -6260   14693  192519 \n\nCoefficients:\n              Estimate Std. Error t value Pr(>|t|)    \n(Intercept) -22227.808  15521.110  -1.432  0.15536    \nSize           104.438      9.424  11.082  < 2e-16 ***\nNew         -78527.502  51007.642  -1.540  0.12697    \nSize:New        61.916     21.686   2.855  0.00527 ** \n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n\nResidual standard error: 52000 on 96 degrees of freedom\nMultiple R-squared:  0.7443,\tAdjusted R-squared:  0.7363 \nF-statistic: 93.15 on 3 and 96 DF,  p-value: < 2.2e-16\n```\n:::\n:::\n\n\nThe intercept and `New` values are no longer significant. Selling price is expected to increase by \\$104 per square foot for all houses, and an additional \\$62 per square foot for new houses.\n\n\n\n",
    "supporting": [],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}