{
  "hash": "b5275099bbbb380a6a876dce06e979a9",
  "result": {
    "markdown": "---\ntitle: \"Homework 2\"\nauthor: \"Ethan Campbell\"\ndescription: \"The second homework\"\ndate: \"10/15/2022\"\nformat:\n  html:\n    toc: true\n    code-fold: true\n    code-copy: true\n    code-tools: true\ncategories:\n  - hw2\n---\n\n\n# Question 1\n\n\nFirst, let's read in the data from the Excel file:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(readxl)\n```\n\n::: {.cell-output .cell-output-stderr}\n```\nWarning: package 'readxl' was built under R version 4.1.3\n```\n:::\n\n```{.r .cell-code}\nlibrary(tidyverse)\n```\n\n::: {.cell-output .cell-output-stderr}\n```\nWarning: package 'tidyverse' was built under R version 4.1.3\n```\n:::\n\n::: {.cell-output .cell-output-stderr}\n```\n-- Attaching packages --------------------------------------- tidyverse 1.3.2 --\nv ggplot2 3.3.6     v purrr   0.3.4\nv tibble  3.1.8     v dplyr   1.0.9\nv tidyr   1.2.0     v stringr 1.4.1\nv readr   2.1.2     v forcats 0.5.2\n```\n:::\n\n::: {.cell-output .cell-output-stderr}\n```\nWarning: package 'ggplot2' was built under R version 4.1.3\n```\n:::\n\n::: {.cell-output .cell-output-stderr}\n```\nWarning: package 'tibble' was built under R version 4.1.3\n```\n:::\n\n::: {.cell-output .cell-output-stderr}\n```\nWarning: package 'tidyr' was built under R version 4.1.3\n```\n:::\n\n::: {.cell-output .cell-output-stderr}\n```\nWarning: package 'readr' was built under R version 4.1.3\n```\n:::\n\n::: {.cell-output .cell-output-stderr}\n```\nWarning: package 'dplyr' was built under R version 4.1.3\n```\n:::\n\n::: {.cell-output .cell-output-stderr}\n```\nWarning: package 'stringr' was built under R version 4.1.3\n```\n:::\n\n::: {.cell-output .cell-output-stderr}\n```\nWarning: package 'forcats' was built under R version 4.1.3\n```\n:::\n\n::: {.cell-output .cell-output-stderr}\n```\n-- Conflicts ------------------------------------------ tidyverse_conflicts() --\nx dplyr::filter() masks stats::filter()\nx dplyr::lag()    masks stats::lag()\n```\n:::\n\n```{.r .cell-code}\nlibrary(dplyr)\n```\n:::\n\n\n\n# Question 1\n\nConstruct the 90% confidence interval to estimate the actual mean wait time for each of the two procedures. Is the confidence interval narrower for angiography or bypass surgery?\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# getting the values set up\n\nbypass_n = 539\nbypass_mean = 19\nbypass_sd = 10\n\nangio_n = 847\nangio_mean = 18\nangio_sd = 9\n\n# Creating the degree of freedom(-1 from sample size)\n\nbypass_n = bypass_n -1\nangio_n = angio_n - 1\n\n# t-score with a 90% CI\nbypass_Tscore <- qt(p=.90, df = bypass_n)\nangio_Tscore <- qt(p=.90, df = angio_n)\n\n\n# Calculate the standard error (standard deviation/square root of sample size)\n\nbypass_standarderror = bypass_sd/sqrt(bypass_n)\nangio_standarderror = angio_sd/sqrt(angio_n)\n\n# Calculate the margin of error(T-score times standard error)\n\nbypass_Me = bypass_Tscore*bypass_standarderror\nangio_Me = angio_Tscore*angio_standarderror\n\n# calculate the range (lower and upper by adding and subtracting the margin of error to the mean to get the range)\n\nBypass_lower = bypass_mean - bypass_Me\nBypass_upper = bypass_mean + bypass_Me\nbypass <- c(Bypass_lower, Bypass_upper)\n\nangio_lower = angio_mean - angio_Me\nangio_upper = angio_mean + angio_Me\nangio <- c(angio_lower, angio_upper)\n\n\n# Looking at the two ranges with 90 CI\nbypass\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 18.4468 19.5532\n```\n:::\n\n```{.r .cell-code}\ndiff(bypass)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 1.106391\n```\n:::\n\n```{.r .cell-code}\nangio\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 17.60314 18.39686\n```\n:::\n\n```{.r .cell-code}\ndiff(angio)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 0.7937115\n```\n:::\n:::\n\nThe confidence interval is narrower for Angiograpy as it is only .79 while the bypass is 1.1 meanidng that patients who show up for the angiography surgery are more likely to get in faster. \n\n# Question 2\n\nA survey of 1031 adult Americans was carried out by the National Center for Public Policy. Assume that the sample is representative of adult Americans. Among those surveyed, 567 believed that college education is essential for success. Find the point estimate, p, of the proportion of all adult Americans who believe that a college education is essential for success. Construct and interpret a 95% confidence interval for p.\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# to calculate the point estimate it is S/T\nS = 567\nT = 1031\n\nPoint_estimate = S/T\n\n# For the confidence interval the prop.test function will return the range for the point estimate at 95% CI. Here we can also pull P\nprop.test(S, T, Point_estimate)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n\n\t1-sample proportions test without continuity correction\n\ndata:  S out of T, null probability Point_estimate\nX-squared = 6.9637e-30, df = 1, p-value = 1\nalternative hypothesis: true p is not equal to 0.5499515\n95 percent confidence interval:\n 0.5194543 0.5800778\nsample estimates:\n        p \n0.5499515 \n```\n:::\n:::\n\n\nAfter running this we can see that we have a confidence interval of 95 percent confidence interval which equals, 0.5194543-0.5800778 and a\nsample estimates: p that equals, 0.5499515. \n\n# Question 3\n\nSuppose that the financial aid office of UMass Amherst seeks to estimate the mean cost of textbooks per semester for students. The estimate will be useful if it is within 5 of the true population mean (i.e. they want the confidence interval to have a length of 10 or less). The financial aid office is pretty sure that the amount spent on books varies widely, with most values between 30 and 200. They think that the population standard deviation is about a quarter of this range (in other words, you can assume they know the population standard deviation). Assuming the significance level to be 5%, what should be the size of the sample?\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Obtaining the standard deviation based on question\nUmass_sd = (200-30)*.25\nUmass_sd\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 42.5\n```\n:::\n\n```{.r .cell-code}\n# Since we know that the CI is 95% we can get the z-score to calculate the sample size\n\nzscore = qnorm(.95)\nzscore\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 1.644854\n```\n:::\n\n```{.r .cell-code}\n# calculating the sample size needed, using 5 with z score since the estimate will be useful if its within $5 of true pop mean.\n\nsample = Umass_sd^2 * (zscore/5)^2\n\nsample\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 195.4755\n```\n:::\n:::\n\n\nUmass financial aid office would need a sample size of roughly 195.\n\n# Question 4\n\nAccording to a union agreement, the mean income for all senior-level workers in a large service company equals 500 per week. A representative of a women’s group decides to analyze whether the mean income μ for female employees matches this norm. For a random sample of nine female employees, ȳ = $410 and s = 90.\n\n## A \n\nTest whether the mean income of female employees differs from $500 per week. Include assumptions, hypotheses, test statistic, and P-value. Interpret the result.\n\nHere we can get the t statistic since it will show us the difference in two means\n\nNull hypothesis mean = 500\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Calculating the t statistic\nT_statistic = (410-500)/(90/(sqrt(9)))\nT_statistic\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] -3\n```\n:::\n\n```{.r .cell-code}\n# calculating the p value\n\npvalue = 2* pt(T_statistic, df=8)\n\npvalue\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 0.01707168\n```\n:::\n\n```{.r .cell-code}\n# the p value is showing evidence that we would reject the null hypothesis here since it is < .05.\n```\n:::\n\n\n\n## B\n\nTesting to see p value of it being less than 500\n\n\n::: {.cell}\n\n```{.r .cell-code}\npvalue_left <- pt(T_statistic, df = 8, lower.tail = TRUE)\npvalue_left\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 0.008535841\n```\n:::\n\n```{.r .cell-code}\n# this is also showing a value smaller than the 5% given which means it is more evidence to reject the null hypothesis \n```\n:::\n\n\n## C\n\nTesting to see the p value greater than 500\n\n\n::: {.cell}\n\n```{.r .cell-code}\npvalue_right <- pt(T_statistic, df = 8, lower.tail = FALSE)\n\npvalue_right\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 0.9914642\n```\n:::\n\n```{.r .cell-code}\n# Making sure the two values equal 1\nsum(pvalue_left, pvalue_right)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 1\n```\n:::\n:::\n\n\nthis is showing a 99.14% chance of observing if the population mean was less than that 500 mark. This is interesting and we would fail to reject the null hypothesis here since it exceeds the amount specified. This would indicate that they are not getting paid the same amount.\n\n\n# Question 5 \n\nJones and Smith separately conduct studies to test H0: μ = 500 against Ha : μ ≠ 500, each with n = 1000. Jones gets ȳ = 519.5, with se = 10.0. Smith gets ȳ = 519.7,\nwith se = 10.0.\n\n\n## A\n\nShow that t = 1.95 and P-value = 0.051 for Jones. Show that t = 1.97 and P-value = 0.049 for Smith.\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Lets run the test and see whats going on\n\nJones <- (519.5-500)/(10)\nSmith= (519.7-500)/(10)\n\n# Here we can see the t stat they are both getting so looking good so far\nJones\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 1.95\n```\n:::\n\n```{.r .cell-code}\nSmith\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 1.97\n```\n:::\n\n```{.r .cell-code}\n# Now to get the P-value\n\nJones_p <- 2*pt(Jones, df= 999, lower.tail = FALSE)\nSmith_p <- 2*pt(Smith, df= 999, lower.tail = FALSE)\n\n# Observing the p values\n\nJones_p\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 0.05145555\n```\n:::\n\n```{.r .cell-code}\nSmith_p\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 0.04911426\n```\n:::\n:::\n\n\n## B\n\nUsing this example, explain the misleading aspects of reporting the result of a test as “P ≤ 0.05” versus “P > 0.05,” or as “reject H0” versus “Do not reject H0 ,” without reporting the actual P-value.\n\nBased on the basic test of this with a CI of 95% we could say that Jones would be unable to reject the null hypothesis since his exceeds .05. Smith on the other hand would barley be able to reject the null hypothesis with his equalling .049. \n\n## C.\n\nUsing this example, explain the misleading aspects of reporting the result of a test as “P ≤ 0.05” versus “P > 0.05,” or as “reject H0” versus “Do not reject H0 ,” without reporting the actual P-value.\n\nBoth of these p values were extremely close to the actual cut off point which shows including them is important. If I would have saw these p scores I would have had doubts or questions regarding the data and would have ran my own test to validate the claims. I think that is reason it would be important to include them to allow other people to see how close the study was. \n\n# Question 6\n\nAre the taxes on gasoline very high in the United States? According to the American Petroleum Institute, the per gallon federal tax that was levied on gasoline was 18.4 cents per gallon. However, state and local taxes vary over the same period. The sample data of gasoline taxes for 18 large cities is given below in the variable called gas_taxes.\n\ngas_taxes <- c(51.27, 47.43, 38.89, 41.95, 28.61, 41.29, 52.19, 49.48, 35.02, 48.13, 39.28, 54.41, 41.66, 30.28, 18.49, 38.72, 33.41, 45.02)\n\nIs there enough evidence to conclude at a 95% confidence level that the average tax per gallon of gas in the US in 2005 was less than 45 cents? Explain.\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Generating the vector\nTaxes <- gas_taxes <- c(51.27, 47.43, 38.89, 41.95, 28.61, 41.29, 52.19, 49.48, 35.02, 48.13, 39.28, 54.41, 41.66, 30.28, 18.49, 38.72, 33.41, 45.02)\n\nMean_taxes <- mean(Taxes)\n\n# The mean gas price is 40.86 cents\n\nt.test(Taxes, mu = 45, alternative = 'less')\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n\n\tOne Sample t-test\n\ndata:  Taxes\nt = -1.8857, df = 17, p-value = 0.03827\nalternative hypothesis: true mean is less than 45\n95 percent confidence interval:\n     -Inf 44.67946\nsample estimates:\nmean of x \n 40.86278 \n```\n:::\n:::\n\n\nHere we can see that the p value for this is .038 which means we can reject the null hypothesis that gas prices are equal to or greater than 45 cents. The mean sample that came up was also within the range of the confidence interval.\n",
    "supporting": [],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}