{
  "hash": "81b6665d610bb6597646370d83c32d31",
  "result": {
    "markdown": "---\ntitle: \"Homework 1\"\nauthor: \"Steve O'Neill\"\ndescription: \"The first homework on descriptive statistics and probability\"\ndate: \"09/20/2022\"\nformat:\n  html:\n    toc: true\n    code-fold: true\n    code-copy: true\n    code-tools: true\ncategories:\n  - hw1\n  - desriptive statistics \n  - probability\n---\n\n\n# Question 1: Lung Capacity\n\nThis exercise focuses on lung capacity data (`LungCapData.xls`). First, the data must be \"read into\" R:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(readxl)\nlibrary(tidyverse)\n```\n\n::: {.cell-output .cell-output-stderr}\n```\n── Attaching packages ─────────────────────────────────────── tidyverse 1.3.2 ──\n✔ ggplot2 3.3.6     ✔ purrr   0.3.4\n✔ tibble  3.1.8     ✔ dplyr   1.0.9\n✔ tidyr   1.2.0     ✔ stringr 1.4.0\n✔ readr   2.1.2     ✔ forcats 0.5.1\n── Conflicts ────────────────────────────────────────── tidyverse_conflicts() ──\n✖ dplyr::filter() masks stats::filter()\n✖ dplyr::lag()    masks stats::lag()\n```\n:::\n\n```{.r .cell-code}\ndf <- read_excel(\"_data/LungCapData.xls\")\ndf\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n# A tibble: 725 × 6\n   LungCap   Age Height Smoke Gender Caesarean\n     <dbl> <dbl>  <dbl> <chr> <chr>  <chr>    \n 1    6.48     6   62.1 no    male   no       \n 2   10.1     18   74.7 yes   female no       \n 3    9.55    16   69.7 no    female yes      \n 4   11.1     14   71   no    male   no       \n 5    4.8      5   56.9 no    male   no       \n 6    6.22    11   58.7 no    female no       \n 7    4.95     8   63.3 no    male   yes      \n 8    7.32    11   70.4 no    male   no       \n 9    8.88    15   70.5 no    male   no       \n10    6.8     11   59.2 no    male   no       \n# … with 715 more rows\n# ℹ Use `print(n = ...)` to see more rows\n```\n:::\n:::\n\n\n### 1a.: What does the distribution look like?\n\nHere is the distribution of `LungCap` with probability density on the y-axis (instead of frequency, the default):\n\n\n::: {.cell}\n\n```{.r .cell-code}\nhist(df$LungCap, freq = FALSE)\n```\n\n::: {.cell-output-display}\n![](HW1_SteveONeill_files/figure-html/unnamed-chunk-2-1.png){width=672}\n:::\n:::\n\n\nIt looks to approach a normal distribution.\n\n### 1b. Comparing Males and Females\n\nMales seem to have a higher `LungCap` in general:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nboxplot(df$LungCap ~ df$Gender)\n```\n\n::: {.cell-output-display}\n![](HW1_SteveONeill_files/figure-html/unnamed-chunk-3-1.png){width=672}\n:::\n:::\n\n### 1c. Smokers\n\nSurprisingly, smokers in this dataset overall are shown to have a higher average lung capacity. This is not what I expected so there might be other factors at play.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nboxplot(df$LungCap ~ df$Smoke)\n```\n\n::: {.cell-output-display}\n![](HW1_SteveONeill_files/figure-html/unnamed-chunk-4-1.png){width=672}\n:::\n:::\n\n### 1d. & 1e.: Smoking, Lung Capacity, and Age\n\nI am approaching this as a compound question. I think a clustered bar chart does the best job of representing the relationship between smoking, lung capacity, and age:\n\n\n::: {.cell}\n\n```{.r .cell-code}\ngrouped_df <- df %>% \n  mutate(group = case_when(\n    between(Age, 0, 13) ~ \"age_13_or_under\",\n    between(Age, 14, 15) ~ \"age_14_to_15\",\n    between(Age, 16, 17) ~ \"age_16_to_17\",\n    Age >= '18' ~ \"age_18_to_older\",\n    TRUE ~ NA_character_\n  ))\n\ngrouped_df %>% ggplot(aes(fill=Smoke, y=LungCap, x=group)) + \n    geom_bar(position=\"dodge\", stat=\"identity\")\n```\n\n::: {.cell-output-display}\n![](HW1_SteveONeill_files/figure-html/unnamed-chunk-5-1.png){width=672}\n:::\n:::\n\nAs we see, it looks like older individuals tend to have higher lung capacities regardless of whether they smoke or not. Age seems to be the bigger determiner of lung capacity than smoking status.\n\nHere is a 100% stacked bar chart which shows that those over 18 also smoke more than other cohorts (which is expected):\n\n\n::: {.cell}\n\n```{.r .cell-code}\ngrouped_df %>% ggplot(aes(x=group, fill = Smoke)) +\n  geom_bar(position = \"fill\")\n```\n\n::: {.cell-output-display}\n![](HW1_SteveONeill_files/figure-html/unnamed-chunk-6-1.png){width=672}\n:::\n:::\n\nIt seems that because the percentage of smokers queried are more likely to be older, they will naturally have larger lung capacities than others.\n\nPerhaps more importantly, this dataset focuses significantly more on young people - so smaller lung capacities make up much more of the overall sample: \n\n\n::: {.cell}\n\n```{.r .cell-code}\ngrouped_df %>% ggplot(aes(x=group, fill = Smoke)) +\n  geom_bar()\n```\n\n::: {.cell-output-display}\n![](HW1_SteveONeill_files/figure-html/unnamed-chunk-7-1.png){width=672}\n:::\n:::\n\n\n### 1f.: Correlation & Covariance\n\n::: {.cell}\n\n```{.r .cell-code}\ncor(grouped_df$LungCap, grouped_df$Age)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 0.8196749\n```\n:::\n\n```{.r .cell-code}\ncov(grouped_df$LungCap, grouped_df$Age)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 8.738289\n```\n:::\n:::\n\n\nIn this case, the Pearson's correlation value is `.81`. Generally two variables are considered strong when their r-value is larger than `.7`, so I will say that age and lung capacity are strongly correlated.\n\nTheir covariance is also positive, so an increase in one results in an increase in the other. That means lung capacity goes up with age rather than the other way around.\n\n# Question 2\n\nI will make a dataframe from the values provided:\n\n::: {.cell}\n\n```{.r .cell-code}\nprior_convictions=c(0,1,2,3,4)\nfreq=c(128, 434, 160, 64, 24)\nprisondata <- data.frame(prior_convictions, freq)\nprisondata\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n  prior_convictions freq\n1                 0  128\n2                 1  434\n3                 2  160\n4                 3   64\n5                 4   24\n```\n:::\n:::\n\nAnd add a probability column:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nprison_prob <- prisondata %>% mutate(prob = freq/sum(freq))\nprison_prob\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n  prior_convictions freq       prob\n1                 0  128 0.15802469\n2                 1  434 0.53580247\n3                 2  160 0.19753086\n4                 3   64 0.07901235\n5                 4   24 0.02962963\n```\n:::\n:::\n\n\n### 2a.\n\n*What is the probability that a randomly selected inmate has exactly 2 prior convictions?*\n\nFrom the table above, the probability is `0.19753086`, nearly 20 percent.\n\n\n### 2b.\n\n*What is the probability that a randomly selected inmate has fewer than 2 prior convictions?*\n\n\n::: {.cell}\n\n```{.r .cell-code}\nhead(prison_prob,2) %>% summarise(sum(prob))\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n  sum(prob)\n1 0.6938272\n```\n:::\n:::\n\n\nThe probability a randomly selected inmate has has fewer than 2 prior convictions is ~69%.\n\n### 2c.\n\n*What is the probability that a randomly selected inmate has 2 or fewer prior convictions?*\n\n\n::: {.cell}\n\n```{.r .cell-code}\nhead(prison_prob,3) %>% summarise(sum(prob))\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n  sum(prob)\n1  0.891358\n```\n:::\n:::\n\n\nThe probability a randomly selected inmate has 2 or fewer convictions is ~89%\n\n### 2d.\n\n*What is the probability that a randomly selected inmate has more than 2 prior convictions?*\n\n\n::: {.cell}\n\n```{.r .cell-code}\ntail(prison_prob,3) %>% summarise(sum(prob))\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n  sum(prob)\n1 0.3061728\n```\n:::\n:::\n\n\nThe probability a randomly selected inmate has more than 2 prior convictions is ~30.6%\n\n### 2e.\n\nWhat is the expected value of the number of prior convictions?\n\n\n::: {.cell}\n\n```{.r .cell-code}\nsum(prison_prob$prior_convictions*prison_prob$prob)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 1.28642\n```\n:::\n\n```{.r .cell-code}\n#Or another way,\n\nweighted.mean(prison_prob$prior_convictions,prison_prob$prob)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 1.28642\n```\n:::\n:::\n\nThe expected value of prior convictions is 1.28642 \n\n### 2f\n\n\n::: {.cell}\n\n```{.r .cell-code}\nprison_prob\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n  prior_convictions freq       prob\n1                 0  128 0.15802469\n2                 1  434 0.53580247\n3                 2  160 0.19753086\n4                 3   64 0.07901235\n5                 4   24 0.02962963\n```\n:::\n\n```{.r .cell-code}\nvar(prison_prob$freq)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 25948\n```\n:::\n\n```{.r .cell-code}\nsd(prison_prob$freq)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 161.0838\n```\n:::\n:::\n\nThe variance among all prior convictions is 25948. The standard deviation among all prior convictions is 161.0838.",
    "supporting": [
      "HW1_SteveONeill_files"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}