{
  "hash": "9e2a946bf3721f722612c6787dbb45a1",
  "result": {
    "markdown": "---\ntitle: \"Homework 1\"\nauthor: \"Kaushika Potluri\"\ndesription: \"Something to describe what I did\"\ndate: \"08/02/2022\"\nformat:\n  html:\n    toc: true\n    code-fold: true\n    code-copy: true\n    code-tools: true\ncategories:\n  - hw1\n  - challenge1\n  - my name\n  - dataset\n  - ggplot2\n---\n\n::: {.cell}\n\n```{.r .cell-code}\nknitr::opts_chunk$set(echo = TRUE)\n```\n:::\n\n\n### Loading in packages:\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(readr)\nlibrary(ggplot2)\nlibrary(dplyr)\n```\n\n::: {.cell-output .cell-output-stderr}\n```\n\nAttaching package: 'dplyr'\n```\n:::\n\n::: {.cell-output .cell-output-stderr}\n```\nThe following objects are masked from 'package:stats':\n\n    filter, lag\n```\n:::\n\n::: {.cell-output .cell-output-stderr}\n```\nThe following objects are masked from 'package:base':\n\n    intersect, setdiff, setequal, union\n```\n:::\n\n```{.r .cell-code}\nlibrary(readxl)\n```\n:::\n\n\n### Reading in Data:\n\n::: {.cell}\n\n```{.r .cell-code}\ndf <- read_excel('_data/LungCapData.xls')\ndf\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n# A tibble: 725 × 6\n   LungCap   Age Height Smoke Gender Caesarean\n     <dbl> <dbl>  <dbl> <chr> <chr>  <chr>    \n 1    6.48     6   62.1 no    male   no       \n 2   10.1     18   74.7 yes   female no       \n 3    9.55    16   69.7 no    female yes      \n 4   11.1     14   71   no    male   no       \n 5    4.8      5   56.9 no    male   no       \n 6    6.22    11   58.7 no    female no       \n 7    4.95     8   63.3 no    male   yes      \n 8    7.32    11   70.4 no    male   no       \n 9    8.88    15   70.5 no    male   no       \n10    6.8     11   59.2 no    male   no       \n# … with 715 more rows\n```\n:::\n:::\n\n\n## 1(a) Distribution of LungCap:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nhist(df$LungCap)\n```\n\n::: {.cell-output-display}\n![](Blog-Post-2_Kaushika-Potluri_files/figure-html/unnamed-chunk-4-1.png){width=672}\n:::\n:::\n\nThe distribution appears to be very similar to a normal distribution, according to the histogram.\n\n## 1(b)\nThe boxplots below show the probability distributions grouped by Gender.\n\n::: {.cell}\n\n```{.r .cell-code}\nboxplot(LungCap~Gender, data=df)\n```\n\n::: {.cell-output-display}\n![](Blog-Post-2_Kaushika-Potluri_files/figure-html/unnamed-chunk-5-1.png){width=672}\n:::\n:::\n\nLooks like males have a slightly higher lung capacity than females.\n\n## 1 (c)\n\n\n::: {.cell}\n\n```{.r .cell-code}\ndf %>%\n  group_by(Smoke) %>%\n  summarize(Mean = mean(LungCap))\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n# A tibble: 2 × 2\n  Smoke  Mean\n  <chr> <dbl>\n1 no     7.77\n2 yes    8.65\n```\n:::\n:::\n\n\nSurprisingly, the mean lung capacity is higher for smokers than it is for non-smokers.\n\n## 1 (d)\n\n::: {.cell}\n\n```{.r .cell-code}\n# convert Age to categorical variable.\ndf <- mutate(df, AgeGroup = case_when(Age <= 13 ~ \"13 and lower\", Age == 14 | Age == 15 ~ \"14-15\", Age == 16 | Age == 17 ~ \"16-17\", Age >= 18 ~ \"18 and above\"))\narrange(df, Age)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n# A tibble: 725 × 7\n   LungCap   Age Height Smoke Gender Caesarean AgeGroup    \n     <dbl> <dbl>  <dbl> <chr> <chr>  <chr>     <chr>       \n 1   5.88      3   55.9 no    male   no        13 and lower\n 2   0.507     3   51.6 no    female yes       13 and lower\n 3   1.18      3   51.9 no    male   no        13 and lower\n 4   4.7       3   52.7 no    male   no        13 and lower\n 5   5.48      3   52.9 no    male   no        13 and lower\n 6   1.02      3   47   no    female no        13 and lower\n 7   2         3   51   no    female no        13 and lower\n 8   1.68      3   51.9 no    male   no        13 and lower\n 9   4.08      3   53.6 no    male   yes       13 and lower\n10   1.45      3   45.3 no    female no        13 and lower\n# … with 715 more rows\n```\n:::\n\n```{.r .cell-code}\n# construct histogram.\nggplot(df, aes(x = LungCap)) +\n  geom_histogram() +\n  facet_grid(AgeGroup~Smoke)\n```\n\n::: {.cell-output .cell-output-stderr}\n```\n`stat_bin()` using `bins = 30`. Pick better value with `binwidth`.\n```\n:::\n\n::: {.cell-output-display}\n![](Blog-Post-2_Kaushika-Potluri_files/figure-html/unnamed-chunk-7-1.png){width=672}\n:::\n:::\n\n\nMajority seem to be non-smokers, and looks like non-smokers seem to have higher lung capacity.\n\n## 1 (e)\n\n\n::: {.cell}\n\n```{.r .cell-code}\nclass(df$AgeGroup)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] \"character\"\n```\n:::\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\ndf$AgeGroup <- as.factor(df$AgeGroup) #converting to factor\n\n# construct table.\ndf %>% select(Smoke, LungCap, AgeGroup) %>% group_by(AgeGroup, Smoke) %>% summarise(mean(LungCap))\n```\n\n::: {.cell-output .cell-output-stderr}\n```\n`summarise()` has grouped output by 'AgeGroup'. You can override using the\n`.groups` argument.\n```\n:::\n\n::: {.cell-output .cell-output-stdout}\n```\n# A tibble: 8 × 3\n# Groups:   AgeGroup [4]\n  AgeGroup     Smoke `mean(LungCap)`\n  <fct>        <chr>           <dbl>\n1 13 and lower no               6.36\n2 13 and lower yes              7.20\n3 14-15        no               9.14\n4 14-15        yes              8.39\n5 16-17        no              10.5 \n6 16-17        yes              9.38\n7 18 and above no              11.1 \n8 18 and above yes             10.5 \n```\n:::\n:::\n\nThe mean lung capacity for smokers aged 13 and under is greater than that of non-smokers in the same age group which is different from expectation. Non-smokers have higher mean lung capacity for ages 14-15, 16-17 and 18 and above.\nEither there may be an error or extreme outlier in the data for smokers aged 13 and under.\n\n## 1 (f)\n\n\n::: {.cell}\n\n```{.r .cell-code}\ncor(df$LungCap,df$Age)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 0.8196749\n```\n:::\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\ncov(df$LungCap,df$Age)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 8.738289\n```\n:::\n:::\n\n\nLung capacity and age have a high positive correlation of 0.82, meaning that as age increases, lung capacity also does. The covariance is a little more challenging to interpret; the positive number indicates a positive association between lung capacity and age, but because covariance varies from negative infinity to infinity, it is difficult to judge the strength of the relationship. In most situations, I would choose to employ correlation.\n\n## 2\n\n::: {.cell}\n\n```{.r .cell-code}\ndf1 <- c(0:4)\nInmate_count <- c(128, 434, 160, 64, 24)\nIP<- data_frame(df1, Inmate_count)\n```\n\n::: {.cell-output .cell-output-stderr}\n```\nWarning: `data_frame()` was deprecated in tibble 1.1.0.\nℹ Please use `tibble()` instead.\n```\n:::\n:::\n\n\n## 2(a)\n\n::: {.cell}\n\n```{.r .cell-code}\nIP <- mutate(IP, Probability = Inmate_count/sum(Inmate_count))\nIP\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n# A tibble: 5 × 3\n    df1 Inmate_count Probability\n  <int>        <dbl>       <dbl>\n1     0          128      0.158 \n2     1          434      0.536 \n3     2          160      0.198 \n4     3           64      0.0790\n5     4           24      0.0296\n```\n:::\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\nIP %>%\n  filter(df1 == 2) %>%\n  select(Probability)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n# A tibble: 1 × 1\n  Probability\n        <dbl>\n1       0.198\n```\n:::\n:::\n\n\nThe probability is about 19.75%.\n\n## (b)\n\n::: {.cell}\n\n```{.r .cell-code}\ndf2 <- IP %>%\n  filter(df1 < 2)\nsum(df2$Probability)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 0.6938272\n```\n:::\n:::\n\n\nThe probability that a randomly selected inmate has fewer than 2 prior convictions is 0.6938272\n\n## 2(c)\n\n\n::: {.cell}\n\n```{.r .cell-code}\ndf3 <- IP %>%\n  filter(df1 <= 2)\nsum(df3$Probability)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 0.891358\n```\n:::\n:::\n\n\nThe probability that a randomly selected inmate has 2 or fewer prior convictions is 0.891358.\n\n## 2(d)\n\n::: {.cell}\n\n```{.r .cell-code}\ndf4 <- IP %>%\n  filter(df1 > 2)\nsum(df4$Probability)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 0.108642\n```\n:::\n:::\n\nThe probability that a randomly selected inmate has more than 2 prior convictions is 0.108642.\n\n## 2(e)\n\n::: {.cell}\n\n```{.r .cell-code}\nIP <- mutate(IP, X = df1*Probability)\nexpectedvalue<- sum(IP$X)\nexpectedvalue\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 1.28642\n```\n:::\n:::\n\n\nThe expected value for the number of prior convictions is 1.2864198. \nWe can round this to 1.\n\n## 2(f)\n\n::: {.cell}\n\n```{.r .cell-code}\nvar1 <-sum(((IP$df1-expectedvalue)^2)*IP$Probability)\nvar1\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 0.8562353\n```\n:::\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\nsqrt(var1)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 0.9253298\n```\n:::\n:::\n\n\nThe variance and the standard deviation for prior convictions are 0.8562353 and 0.9253298 respectively.",
    "supporting": [
      "Blog-Post-2_Kaushika-Potluri_files"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}