{
  "hash": "423ff0acf318163d9b4df9508c24a1c6",
  "result": {
    "markdown": "---\ntitle: \"Homework 4\"\nauthor: \"Donny Snyder\"\ndesription: \"Homework 4 Submission\"\ndate: \"11/14/2022\"\nformat:\n  html:\n    toc: true\n    code-fold: true\n    code-copy: true\n    code-tools: true\ncategories:\n  - hw4\n  - regression\n---\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(tidyverse)\n```\n\n::: {.cell-output .cell-output-stderr}\n```\n── Attaching packages ─────────────────────────────────────── tidyverse 1.3.2 ──\n✔ ggplot2 3.3.6      ✔ purrr   0.3.5 \n✔ tibble  3.1.8      ✔ dplyr   1.0.10\n✔ tidyr   1.2.1      ✔ stringr 1.4.1 \n✔ readr   2.1.3      ✔ forcats 0.5.2 \n── Conflicts ────────────────────────────────────────── tidyverse_conflicts() ──\n✖ dplyr::filter() masks stats::filter()\n✖ dplyr::lag()    masks stats::lag()\n```\n:::\n\n```{.r .cell-code}\nlibrary(alr4)\n```\n\n::: {.cell-output .cell-output-stderr}\n```\nLoading required package: car\nLoading required package: carData\n\nAttaching package: 'car'\n\nThe following object is masked from 'package:dplyr':\n\n    recode\n\nThe following object is masked from 'package:purrr':\n\n    some\n\nLoading required package: effects\nlattice theme set by effectsTheme()\nSee ?effectsTheme for details.\n```\n:::\n\n```{.r .cell-code}\nlibrary(smss)\n```\n\n::: {.cell-output .cell-output-stderr}\n```\nWarning: package 'smss' was built under R version 4.2.2\n```\n:::\n\n```{.r .cell-code}\nlibrary(dplyr)\nlibrary(ggplot2)\nlibrary(GGally)\n```\n\n::: {.cell-output .cell-output-error}\n```\nError in library(GGally): there is no package called 'GGally'\n```\n:::\n:::\n\n\n# Question 1\n\n\n::: {.cell}\n\n```{.r .cell-code}\npredictSell <- -10536 + (53.8 * 1240) + (2.84 * 18000)\nrealSell <- 145000\nresidual <- realSell - predictSell\nratioLottoHome <- 53.8/2.84\n```\n:::\n\n\n#Question 1A\nThe predicted selling price is 107,296 dollars, the residual is 37,704 dollars. The predicted selling price undershot the actual selling price. \n\n#Question 1B\nWith a fixed lot size, the house selling price will increase by 53.8 for each square foot. This is because as the house is getting bigger, the house is selling for more, because the house is more valuable than the empty lot space.\n\n#Question 1C\nThe lot would have to increase ~18.94 square feet to have the same impact as a one square foot increase size in the home.\n\n\n#Question 2\n\n::: {.cell}\n\n```{.r .cell-code}\ndata <- salary\n\nmodel1 <- lm(salary~sex, data = data)\nsummary(model1)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n\nCall:\nlm(formula = salary ~ sex, data = data)\n\nResiduals:\n    Min      1Q  Median      3Q     Max \n-8602.8 -4296.6  -100.8  3513.1 16687.9 \n\nCoefficients:\n            Estimate Std. Error t value Pr(>|t|)    \n(Intercept)    24697        938  26.330   <2e-16 ***\nsexFemale      -3340       1808  -1.847   0.0706 .  \n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n\nResidual standard error: 5782 on 50 degrees of freedom\nMultiple R-squared:  0.0639,\tAdjusted R-squared:  0.04518 \nF-statistic: 3.413 on 1 and 50 DF,  p-value: 0.0706\n```\n:::\n\n```{.r .cell-code}\nmodel2 <- lm(salary~degree+rank+sex+year+ysdeg, data = data)\nsummary(model2)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n\nCall:\nlm(formula = salary ~ degree + rank + sex + year + ysdeg, data = data)\n\nResiduals:\n    Min      1Q  Median      3Q     Max \n-4045.2 -1094.7  -361.5   813.2  9193.1 \n\nCoefficients:\n            Estimate Std. Error t value Pr(>|t|)    \n(Intercept) 15746.05     800.18  19.678  < 2e-16 ***\ndegreePhD    1388.61    1018.75   1.363    0.180    \nrankAssoc    5292.36    1145.40   4.621 3.22e-05 ***\nrankProf    11118.76    1351.77   8.225 1.62e-10 ***\nsexFemale    1166.37     925.57   1.260    0.214    \nyear          476.31      94.91   5.018 8.65e-06 ***\nysdeg        -124.57      77.49  -1.608    0.115    \n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n\nResidual standard error: 2398 on 45 degrees of freedom\nMultiple R-squared:  0.855,\tAdjusted R-squared:  0.8357 \nF-statistic: 44.24 on 6 and 45 DF,  p-value: < 2.2e-16\n```\n:::\n\n```{.r .cell-code}\nconfint(model2)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n                 2.5 %      97.5 %\n(Intercept) 14134.4059 17357.68946\ndegreePhD    -663.2482  3440.47485\nrankAssoc    2985.4107  7599.31080\nrankProf     8396.1546 13841.37340\nsexFemale    -697.8183  3030.56452\nyear          285.1433   667.47476\nysdeg        -280.6397    31.49105\n```\n:::\n\n```{.r .cell-code}\ndata$rank <- factor(data$rank, levels = c(\"Prof\", \"Assoc\", \"Asst\"))\n\nmodel3 <- lm(salary~degree+rank+sex+year+ysdeg, data = data)\nsummary(model3)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n\nCall:\nlm(formula = salary ~ degree + rank + sex + year + ysdeg, data = data)\n\nResiduals:\n    Min      1Q  Median      3Q     Max \n-4045.2 -1094.7  -361.5   813.2  9193.1 \n\nCoefficients:\n             Estimate Std. Error t value Pr(>|t|)    \n(Intercept)  26864.81    1375.29  19.534  < 2e-16 ***\ndegreePhD     1388.61    1018.75   1.363    0.180    \nrankAssoc    -5826.40    1012.93  -5.752 7.28e-07 ***\nrankAsst    -11118.76    1351.77  -8.225 1.62e-10 ***\nsexFemale     1166.37     925.57   1.260    0.214    \nyear           476.31      94.91   5.018 8.65e-06 ***\nysdeg         -124.57      77.49  -1.608    0.115    \n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n\nResidual standard error: 2398 on 45 degrees of freedom\nMultiple R-squared:  0.855,\tAdjusted R-squared:  0.8357 \nF-statistic: 44.24 on 6 and 45 DF,  p-value: < 2.2e-16\n```\n:::\n\n```{.r .cell-code}\nmodel4 <- lm(salary~degree+sex+year+ysdeg, data = data)\nsummary(model4)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n\nCall:\nlm(formula = salary ~ degree + sex + year + ysdeg, data = data)\n\nResiduals:\n    Min      1Q  Median      3Q     Max \n-8146.9 -2186.9  -491.5  2279.1 11186.6 \n\nCoefficients:\n            Estimate Std. Error t value Pr(>|t|)    \n(Intercept) 17183.57    1147.94  14.969  < 2e-16 ***\ndegreePhD   -3299.35    1302.52  -2.533 0.014704 *  \nsexFemale   -1286.54    1313.09  -0.980 0.332209    \nyear          351.97     142.48   2.470 0.017185 *  \nysdeg         339.40      80.62   4.210 0.000114 ***\n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n\nResidual standard error: 3744 on 47 degrees of freedom\nMultiple R-squared:  0.6312,\tAdjusted R-squared:  0.5998 \nF-statistic: 20.11 on 4 and 47 DF,  p-value: 1.048e-09\n```\n:::\n\n```{.r .cell-code}\ndata$dean <- NA\n\nx = 1\nwhile(x < 53){\n  if(data$ysdeg[x] > 15){\n    data$dean[x] = 0\n  }\n  else{\n    data$dean[x] = 1\n  }\n x = x + 1   \n}\n\nmodel5 <- lm(data = data, salary~sex+year+dean+degree)\nsummary(model5)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n\nCall:\nlm(formula = salary ~ sex + year + dean + degree, data = data)\n\nResiduals:\n     Min       1Q   Median       3Q      Max \n-10740.1  -2550.1     -3.3   1942.4  11718.3 \n\nCoefficients:\n            Estimate Std. Error t value Pr(>|t|)    \n(Intercept)  22598.7     1792.1  12.610  < 2e-16 ***\nsexFemale     -523.5     1355.1  -0.386 0.701017    \nyear           531.4      130.2   4.082 0.000172 ***\ndean         -4449.8     1347.2  -3.303 0.001834 ** \ndegreePhD    -1186.6     1191.2  -0.996 0.324267    \n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n\nResidual standard error: 3958 on 47 degrees of freedom\nMultiple R-squared:  0.5878,\tAdjusted R-squared:  0.5527 \nF-statistic: 16.75 on 4 and 47 DF,  p-value: 1.338e-08\n```\n:::\n:::\n\n\n# Question 2A\nAs shown in model1, it seems like the mean salary is the same, as the null hypothesis that there is no difference cannot be rejected with the p-value of 0.0706.\n\n# Question 2B\nThe 95% confidence interval for pay differences between males and females is between -697.8183 and 3030.56452.\n\n# Question 2C\nThere is demonstrated statistically significant evidence that rank and years in current rank show significant results on an increase in salary. Rank as a professor shows the strongest effect, with rank as an associate professor also showing a high effect, as well as years in current rank. Rank has the highest slope for statistically significantly raising salary, particularly among full professors. All other relationships are not statistically significant.\n\n# Question 2D\nChanging the baseline changes the direction of the relationship for associate and assistant professors. It shows that relative to full professors, associate, and assistant professors receive less.\n\n# Question 2E\nExcluding rank makes the degreePhD and years after degree variables more important, as rank was likely previously explaining their variance. Without being able to rely on rank, these serve as proxies for professors receiving more money due to being a higher rank. however, there is also no statistically significant of discrimination based on sex.\n\n# Question 2F\nThere is actually some evidence that the dean has been making less generous offers than previously, per model 5. Multicollinearity can make it harder to make inferences. I avoided it by excluding degree and years after degree variables, as rank explains salary better than those.\n\n# Question 3\n\n\n::: {.cell}\n\n```{.r .cell-code}\nsummary(house.selling.price)\n```\n\n::: {.cell-output .cell-output-error}\n```\nError in summary(house.selling.price): object 'house.selling.price' not found\n```\n:::\n\n```{.r .cell-code}\ndata2 <- house.selling.price\n```\n\n::: {.cell-output .cell-output-error}\n```\nError in eval(expr, envir, enclos): object 'house.selling.price' not found\n```\n:::\n\n```{.r .cell-code}\nmodel1 <- lm(data = data2, Price~Size+New)\n```\n\n::: {.cell-output .cell-output-error}\n```\nError in is.data.frame(data): object 'data2' not found\n```\n:::\n\n```{.r .cell-code}\nsummary(model1)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n\nCall:\nlm(formula = salary ~ sex, data = data)\n\nResiduals:\n    Min      1Q  Median      3Q     Max \n-8602.8 -4296.6  -100.8  3513.1 16687.9 \n\nCoefficients:\n            Estimate Std. Error t value Pr(>|t|)    \n(Intercept)    24697        938  26.330   <2e-16 ***\nsexFemale      -3340       1808  -1.847   0.0706 .  \n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n\nResidual standard error: 5782 on 50 degrees of freedom\nMultiple R-squared:  0.0639,\tAdjusted R-squared:  0.04518 \nF-statistic: 3.413 on 1 and 50 DF,  p-value: 0.0706\n```\n:::\n\n```{.r .cell-code}\npredictNew <- (116.132*3000) + 57736.283*1 - 40230.867\n\npredictNotNew <- (116.132*3000) + 57736.283*0 - 40230.867\n\nmodel2 <- lm(data = data2, Price~Size+New+Size*New)\n```\n\n::: {.cell-output .cell-output-error}\n```\nError in is.data.frame(data): object 'data2' not found\n```\n:::\n\n```{.r .cell-code}\nsummary(model2)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n\nCall:\nlm(formula = salary ~ degree + rank + sex + year + ysdeg, data = data)\n\nResiduals:\n    Min      1Q  Median      3Q     Max \n-4045.2 -1094.7  -361.5   813.2  9193.1 \n\nCoefficients:\n            Estimate Std. Error t value Pr(>|t|)    \n(Intercept) 15746.05     800.18  19.678  < 2e-16 ***\ndegreePhD    1388.61    1018.75   1.363    0.180    \nrankAssoc    5292.36    1145.40   4.621 3.22e-05 ***\nrankProf    11118.76    1351.77   8.225 1.62e-10 ***\nsexFemale    1166.37     925.57   1.260    0.214    \nyear          476.31      94.91   5.018 8.65e-06 ***\nysdeg        -124.57      77.49  -1.608    0.115    \n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n\nResidual standard error: 2398 on 45 degrees of freedom\nMultiple R-squared:  0.855,\tAdjusted R-squared:  0.8357 \nF-statistic: 44.24 on 6 and 45 DF,  p-value: < 2.2e-16\n```\n:::\n\n```{.r .cell-code}\npredictNew2 <- 104.438*3000 - 78527.502 + 61.916*3000 - 22227.808\n\npredictNotNew2 <- 104.438*3000 - 22227.808\n\npredictNew3 <- 104.438*1500 - 78527.502 + 61.916*1500 - 22227.808\n\npredictNotNew3 <- 104.438*1500 - 22227.808\n```\n:::\n\n\n# Question 3A\nSize of home and how new the home is both statistically significantly increase the selling prices of homes. \n\n# Question 3B\nNew Home Price = 116.132(size in square feet) + 57736.283(if New) - 40230.867\n\nNot New Home Price = 116.132(size in square feet) - 40230.867\n\n# Question 3C\nNew Home Prediction = 365901.416\nNo New Home Prediction = 308165.133\n\n# Question 3D\nIt seems like Size and New have a positive interaction effect. Being a new home and being larger are interrelated. This also removes the statistical significance of being new.\n\n# Question 3E\nNew home Prediction = 104.438(size in square feet) - 78527.502(if new) + 61.916(new times size) - 22227.808\n\nNot new home Prediction = 104.438(size in square feet) + 22227.808\n\n# Question 3F\nNew Home Prediction = 398306.69\n\nNo New Home Prediction = 291086.192\n\n# Question 3G\nNew Home Prediction = \n148775.69\n\nNo New Home Prediction = 134429.192\n\nAs size of home gets smaller, newness tends to matter less towards increasing the predicted selling price, so the disparity between new and not new homes tends to decrease.\n\n# Question 3H\nI think that I prefer the interaction model. It is more responsive to size than just merely adding over 50k for being either new or not new, in a binary. It's good to have more of a gradient measure like this interaction provides in multiple ways.",
    "supporting": [],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}