{
  "hash": "eacef3195b76a441928464fbc63379d5",
  "result": {
    "markdown": "---\ntitle: \"HW 4\"\nauthor: \"Karen Detter\"\ndesription: \"HW 4 - Modeling\"\ndate: \"08/02/2022\"\nformat:\n  html:\n    toc: true\n    code-fold: true\n    code-copy: true\n    code-tools: true\ncategories:\n  - hw4\n---\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(tidyverse)\nlibrary(alr4)\nlibrary(smss)\n\nknitr::opts_chunk$set(echo = TRUE)\n```\n:::\n\n\n## Question 1\n\n### A.\n\n$\\hat{y}$ (predicted selling price) =\n\n::: {.cell}\n\n```{.r .cell-code}\nyhat <- (-10536 + (53.8*1240) + (2.84*18000))\nyhat\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 107296\n```\n:::\n:::\n\n\nresidual = observed - predicted\n\n::: {.cell}\n\n```{.r .cell-code}\nres <- 145000 - 107296\nres\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 37704\n```\n:::\n:::\n\n\nThe home in question sold for $37,704 more than the equation predicted, indicating that other variables that were not included in the equation have an impact on selling price.\n\n### B.\n\nFor fixed lot size, the house selling price is predicted to increase 53.8 for each square foot in home size. When lot size is fixed, that variable is disregarded, leaving $\\hat{y}$ = 53.8$x_{1}$, which means that for each unit of x, the predicted value of y will increase by 53.8.\n\n### C.\n\n::: {.cell}\n\n```{.r .cell-code}\nincr <- 53.8 / 2.84\nincr\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 18.94366\n```\n:::\n:::\n\n\nLot size ($x_{2}$) would need to increase by 18.94 units to have the same impact as a one unit increase in home size ($x_{1}$).\n\n## Question 2\n\n### A.\n\n::: {.cell}\n\n```{.r .cell-code}\n#test hypothesis with two sample t-test\n\ndata(\"salary\")\nt.test(salary ~ sex, data = salary)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n\n\tWelch Two Sample t-test\n\ndata:  salary by sex\nt = 1.7744, df = 21.591, p-value = 0.09009\nalternative hypothesis: true difference in means between group Male and group Female is not equal to 0\n95 percent confidence interval:\n -567.8539 7247.1471\nsample estimates:\n  mean in group Male mean in group Female \n            24696.79             21357.14 \n```\n:::\n:::\n\n\nAlthough the sample estimate means show a difference in salary between men and women, the null hypothesis that there is no difference between the two groups cannot be rejected on the basis of this test alone, due to the p-value of .09 being higher than the threshhold of .05.\n\n### B.\n\n::: {.cell}\n\n```{.r .cell-code}\n#run a multiple linear regression with all variables explaining salary\n\nmodel <- lm(salary ~ ., data = salary)\nsummary(model)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n\nCall:\nlm(formula = salary ~ ., data = salary)\n\nResiduals:\n    Min      1Q  Median      3Q     Max \n-4045.2 -1094.7  -361.5   813.2  9193.1 \n\nCoefficients:\n            Estimate Std. Error t value Pr(>|t|)    \n(Intercept) 15746.05     800.18  19.678  < 2e-16 ***\ndegreePhD    1388.61    1018.75   1.363    0.180    \nrankAssoc    5292.36    1145.40   4.621 3.22e-05 ***\nrankProf    11118.76    1351.77   8.225 1.62e-10 ***\nsexFemale    1166.37     925.57   1.260    0.214    \nyear          476.31      94.91   5.018 8.65e-06 ***\nysdeg        -124.57      77.49  -1.608    0.115    \n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n\nResidual standard error: 2398 on 45 degrees of freedom\nMultiple R-squared:  0.855,\tAdjusted R-squared:  0.8357 \nF-statistic: 44.24 on 6 and 45 DF,  p-value: < 2.2e-16\n```\n:::\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\n#obtain a 95% confidence interval for difference in salary by sex\n\nconfint(model, 'sexFemale')\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n              2.5 %   97.5 %\nsexFemale -697.8183 3030.565\n```\n:::\n:::\n\n\nBecause the confidence interval includes 0, it was correct to reject the null hypothesis.\n\n### C.\n\nIn this model, the **intercept** shows a base expected salary of 15746 for all observations in the data set, without consideration of any other variables. **Rank** and **years in current rank** show statistically significant effects on **salary**. \n\nGaining a level of **degree** (from Masters to PhD) is associated with a salary increase of 1389, but not within the statistically significant threshhold. \n\nMoving from **rankAsst** to **rankAssoc** corresponds to an increase in salary of 5292, and moving from **rankAsst** to **rankProf** yields a salary increase of 11119. \n\nEach unit of **years in current rank** corresponds to a salary increase of 476, while each unit of **years since highest degree** is associated with a *decrease* in salary of 125, although this association is not statistically significant.\n\nBeing **female** is associated with an increase in salary of 1166, but the relationship is not at the level of statistical significance.\n\n### D.\n\n::: {.cell}\n\n```{.r .cell-code}\n#change baseline for rank category\nsalary$rank <- relevel(salary$rank, ref = 'Prof')\n\nsummary(lm(salary ~ ., data = salary))\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n\nCall:\nlm(formula = salary ~ ., data = salary)\n\nResiduals:\n    Min      1Q  Median      3Q     Max \n-4045.2 -1094.7  -361.5   813.2  9193.1 \n\nCoefficients:\n             Estimate Std. Error t value Pr(>|t|)    \n(Intercept)  26864.81    1375.29  19.534  < 2e-16 ***\ndegreePhD     1388.61    1018.75   1.363    0.180    \nrankAsst    -11118.76    1351.77  -8.225 1.62e-10 ***\nrankAssoc    -5826.40    1012.93  -5.752 7.28e-07 ***\nsexFemale     1166.37     925.57   1.260    0.214    \nyear           476.31      94.91   5.018 8.65e-06 ***\nysdeg         -124.57      77.49  -1.608    0.115    \n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n\nResidual standard error: 2398 on 45 degrees of freedom\nMultiple R-squared:  0.855,\tAdjusted R-squared:  0.8357 \nF-statistic: 44.24 on 6 and 45 DF,  p-value: < 2.2e-16\n```\n:::\n:::\n\n\nHaving the rank of Associate correlates to a salary of 5826 less than the salary correlated to the rank of Professor, and the rank of Assistant correlates to a salary of 11119 less than that of the Professor rank.\n\n### E.\n\n::: {.cell}\n\n```{.r .cell-code}\n#refit model excluding the rank variable\nmodel_alt <- lm(salary ~ degree + sex + year + ysdeg, data = salary)\nsummary(model_alt)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n\nCall:\nlm(formula = salary ~ degree + sex + year + ysdeg, data = salary)\n\nResiduals:\n    Min      1Q  Median      3Q     Max \n-8146.9 -2186.9  -491.5  2279.1 11186.6 \n\nCoefficients:\n            Estimate Std. Error t value Pr(>|t|)    \n(Intercept) 17183.57    1147.94  14.969  < 2e-16 ***\ndegreePhD   -3299.35    1302.52  -2.533 0.014704 *  \nsexFemale   -1286.54    1313.09  -0.980 0.332209    \nyear          351.97     142.48   2.470 0.017185 *  \nysdeg         339.40      80.62   4.210 0.000114 ***\n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n\nResidual standard error: 3744 on 47 degrees of freedom\nMultiple R-squared:  0.6312,\tAdjusted R-squared:  0.5998 \nF-statistic: 20.11 on 4 and 47 DF,  p-value: 1.048e-09\n```\n:::\n:::\n\n\nIn this model, being female is associated with a salary decrease of 1287, but the effect is, again, well outside the acceptable range of statistical significance.\n\n### F.\n\n::: {.cell}\n\n```{.r .cell-code}\n#create new variable for hiring dean\nhiring_dean <- salary %>%\n              mutate(dean = \n                       case_when(`ysdeg` > 15 ~ 'prev',\n                                 `ysdeg` <= 15 ~ 'new'))\n\n#fit new model to test hypothesis while avoiding multicollinearity\ndean_model <- lm(salary ~ . - ysdeg, data = hiring_dean)\nsummary(dean_model)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n\nCall:\nlm(formula = salary ~ . - ysdeg, data = hiring_dean)\n\nResiduals:\n    Min      1Q  Median      3Q     Max \n-3403.3 -1387.0  -167.0   528.2  9233.8 \n\nCoefficients:\n             Estimate Std. Error t value Pr(>|t|)    \n(Intercept)  26588.79    1168.06  22.763  < 2e-16 ***\ndegreePhD      818.93     797.48   1.027   0.3100    \nrankAsst    -11096.95    1191.00  -9.317 4.54e-12 ***\nrankAssoc    -6124.28    1028.58  -5.954 3.65e-07 ***\nsexFemale      907.14     840.54   1.079   0.2862    \nyear           434.85      78.89   5.512 1.65e-06 ***\ndeanprev     -2163.46    1072.04  -2.018   0.0496 *  \n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n\nResidual standard error: 2362 on 45 degrees of freedom\nMultiple R-squared:  0.8594,\tAdjusted R-squared:  0.8407 \nF-statistic: 45.86 on 6 and 45 DF,  p-value: < 2.2e-16\n```\n:::\n:::\n\n\nBecause the variable *ysdeg* would, by nature, be highly correlated to the variable *dean*, *ysdeg* was omitted in the model examining the effect of *dean* on salary.\n\nThe resulting model shows a statistically significant (p = .05) effect of hiring dean on salary, with hiring by the previous dean correlating to a decrease in salary of 2163.\n\n## Question 3\n\n### A.\n\n::: {.cell}\n\n```{.r .cell-code}\ndata(\"house.selling.price\")\nsummary(lm(Price ~ Size + New, data = house.selling.price))\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n\nCall:\nlm(formula = Price ~ Size + New, data = house.selling.price)\n\nResiduals:\n    Min      1Q  Median      3Q     Max \n-205102  -34374   -5778   18929  163866 \n\nCoefficients:\n              Estimate Std. Error t value Pr(>|t|)    \n(Intercept) -40230.867  14696.140  -2.738  0.00737 ** \nSize           116.132      8.795  13.204  < 2e-16 ***\nNew          57736.283  18653.041   3.095  0.00257 ** \n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n\nResidual standard error: 53880 on 97 degrees of freedom\nMultiple R-squared:  0.7226,\tAdjusted R-squared:  0.7169 \nF-statistic: 126.3 on 2 and 97 DF,  p-value: < 2.2e-16\n```\n:::\n:::\n\n\nSize and whether a house is new each have a statistically significant effect on house price, both with p-values well below the significance threshhold of .05.\n\nEach unit of size is associated with an increase in price of 116, and new houses are associated with a price increase of 57736.\n\n### B.\n\n**prediction equation:**\n\n$\\hat{y}$ = -40231 + 116$x_{1}$ + 57736$x_{2}$\n\n**where** y = house selling price, $x_{1}$ = house size (in sq ft), $x_{2}$ = house is new\n\n**alternative prediction equation:**\n\n$\\hat{y}$ = -40231 + 116$x_{1}$ + 0$x_{2}$\n\n**where** y = house selling price, $x_{1}$ = house size (in sq ft), $x_{2}$ = house is not new\n\n### C.\n\n*(i)*\n\n**3000 sq ft, new house:**\n\n$\\hat{y}$ = -40231 + 116(3000) + 57736\n          = -40231 + 348000 + 57736\n          = -40231 + 405736\n          = $365,505\n\n*(ii)*\n\n**3000 sq ft, not new house:**\n\n$\\hat{y}$ = -40231 + 116(3000) + 0\n          = -40231 + 348000\n          = $307,769\n\n### D.\n\n::: {.cell}\n\n```{.r .cell-code}\n#fit model with an interaction term between variables\n\nsummary(lm(Price ~ Size + New + Size*New, data = house.selling.price))\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n\nCall:\nlm(formula = Price ~ Size + New + Size * New, data = house.selling.price)\n\nResiduals:\n    Min      1Q  Median      3Q     Max \n-175748  -28979   -6260   14693  192519 \n\nCoefficients:\n              Estimate Std. Error t value Pr(>|t|)    \n(Intercept) -22227.808  15521.110  -1.432  0.15536    \nSize           104.438      9.424  11.082  < 2e-16 ***\nNew         -78527.502  51007.642  -1.540  0.12697    \nSize:New        61.916     21.686   2.855  0.00527 ** \n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n\nResidual standard error: 52000 on 96 degrees of freedom\nMultiple R-squared:  0.7443,\tAdjusted R-squared:  0.7363 \nF-statistic: 93.15 on 3 and 96 DF,  p-value: < 2.2e-16\n```\n:::\n:::\n\n\n### E.\n\nThe prediction equations generated from this model are:\n\n**(i) New**\n\nPrice = -22228 + 104(Size) - 78528 + 62(Size)\n\n**(ii) Not New**\n\nPrice = -22228 + 104(Size)\n\nTherefore, new houses are associated with an additional price increase of 62 per unit of size increase.\n\n### F.\n\n*Predicted Prices:*\n\n**(i) 3000 sq ft New House**\n\nPrice = -22228 + 104(3000) - 78528 + 62(3000)\n      = $397,244\n\n**(ii) 3000 sq ft Not New House**\n\nPrice = -22228 + 104(3000)\n      = $289,772\n\n### G.\n\n*Predicted Prices:*\n\n**(i) 1500 sq ft New House**\n\nPrice = -22228 + 104(1500) - 78528 + 62(1500)\n      = $148,244\n\n**(ii) 1500 sq ft Not New House**\n\nPrice = -22228 + 104(1500)\n      = $133,772\n\nThe ratio between the predicted selling prices of the new and not new, 1500 sq ft house is 1.108.\nThe ratio between the predicted selling prices of the new and not new, 3000 sq ft house is 1.371.\n\nAs size increases, the price difference between new and not new houses also increases, indicating that there *is* an interaction between *Size* and *New*.\n\n### H.\n\nThe model with the interaction term between *Size* and *New* seems to better represent the relationship between these variables and *Price*. Also, the Adjusted $R^{2}$ for this model is a bit higher, indicating that it explains a higher portion of the variance than the original model.\n",
    "supporting": [],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}