{
  "hash": "cb79194e1c841b83631e5e5d02c2405e",
  "result": {
    "markdown": "---\ntitle: \"HW4\"\nauthor: \"Ken Docekal\"\ndesription: \"Homework 4\"\ndate: \"11/14/2022\"\nformat:\n  html:\n    toc: true\n    code-fold: true\n    code-copy: true\n    code-tools: true\ncategories:\n  - hw4\n  - Ken Docekal\n\n---\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(tidyverse)\nlibrary(AER)\n```\n\n::: {.cell-output .cell-output-error}\n```\nError in library(AER): there is no package called 'AER'\n```\n:::\n\n```{.r .cell-code}\nlibrary(stargazer)\n```\n\n::: {.cell-output .cell-output-error}\n```\nError in library(stargazer): there is no package called 'stargazer'\n```\n:::\n\n```{.r .cell-code}\nknitr::opts_chunk$set(echo = TRUE)\n```\n:::\n\n\n\n\n## Q1\n\n\n# A\n\n\n::: {.cell}\n\n```{.r .cell-code}\na <- 1240\n\nb <- 18000\n\nc <- -10536 + 53.8*a + 2.84*b \n\nc\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 107296\n```\n:::\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\n145000 - 107296\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 37704\n```\n:::\n:::\n\n\nThe predicted selling price is 107296 which makes the residual 37704. This means that our model's estimated sale price of $107296, for a house size of 1240 square feet and lot size  of 18000 square feet, is off from the actual observed price by $37704. \n\n\n\n# B\n\nWith fixed lot size each square-foot increase in home size increases price by $53.80. This is because the variable's coefficient is  53.8 and will therefore only increase by this amount if no factors other than home size are considered by the model.  \n\n\n\n# C\n\n\n::: {.cell}\n\n```{.r .cell-code}\n53.8/ 2.84\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 18.94366\n```\n:::\n:::\n\n\nIf we fix home size, lot size need to increase by 18.94 feet to have the equivalent impact as a one square foot increase in home size. \n\n\n\n## Q2\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(alr4) \n```\n\n::: {.cell-output .cell-output-stderr}\n```\nLoading required package: car\n```\n:::\n\n::: {.cell-output .cell-output-stderr}\n```\nLoading required package: carData\n```\n:::\n\n::: {.cell-output .cell-output-stderr}\n```\n\nAttaching package: 'car'\n```\n:::\n\n::: {.cell-output .cell-output-stderr}\n```\nThe following object is masked from 'package:dplyr':\n\n    recode\n```\n:::\n\n::: {.cell-output .cell-output-stderr}\n```\nThe following object is masked from 'package:purrr':\n\n    some\n```\n:::\n\n::: {.cell-output .cell-output-stderr}\n```\nLoading required package: effects\n```\n:::\n\n::: {.cell-output .cell-output-stderr}\n```\nlattice theme set by effectsTheme()\nSee ?effectsTheme for details.\n```\n:::\n\n```{.r .cell-code}\ndata('salary', package = 'alr4')\n```\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\nsummary(salary)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n     degree      rank        sex          year            ysdeg      \n Masters:34   Asst :18   Male  :38   Min.   : 0.000   Min.   : 1.00  \n PhD    :18   Assoc:14   Female:14   1st Qu.: 3.000   1st Qu.: 6.75  \n              Prof :20               Median : 7.000   Median :15.50  \n                                     Mean   : 7.481   Mean   :16.12  \n                                     3rd Qu.:11.000   3rd Qu.:23.25  \n                                     Max.   :25.000   Max.   :35.00  \n     salary     \n Min.   :15000  \n 1st Qu.:18247  \n Median :23719  \n Mean   :23798  \n 3rd Qu.:27259  \n Max.   :38045  \n```\n:::\n\n```{.r .cell-code}\ntibble(salary)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n# A tibble: 52 × 6\n   degree  rank  sex     year ysdeg salary\n   <fct>   <fct> <fct>  <int> <int>  <int>\n 1 Masters Prof  Male      25    35  36350\n 2 Masters Prof  Male      13    22  35350\n 3 Masters Prof  Male      10    23  28200\n 4 Masters Prof  Female     7    27  26775\n 5 PhD     Prof  Male      19    30  33696\n 6 Masters Prof  Male      16    21  28516\n 7 PhD     Prof  Female     0    32  24900\n 8 Masters Prof  Male      16    18  31909\n 9 PhD     Prof  Male      13    30  31850\n10 PhD     Prof  Male      13    31  32850\n# … with 42 more rows\n```\n:::\n:::\n\n\n\n\n# A\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlm(salary ~ sex, data = salary) |> summary()\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n\nCall:\nlm(formula = salary ~ sex, data = salary)\n\nResiduals:\n    Min      1Q  Median      3Q     Max \n-8602.8 -4296.6  -100.8  3513.1 16687.9 \n\nCoefficients:\n            Estimate Std. Error t value Pr(>|t|)    \n(Intercept)    24697        938  26.330   <2e-16 ***\nsexFemale      -3340       1808  -1.847   0.0706 .  \n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n\nResidual standard error: 5782 on 50 degrees of freedom\nMultiple R-squared:  0.0639,\tAdjusted R-squared:  0.04518 \nF-statistic: 3.413 on 1 and 50 DF,  p-value: 0.0706\n```\n:::\n:::\n\n\nFindings indicate a negative relationship of $3340 for females however this result is not significant at the 95% confidence level and the model has low predictive ability as adjusted R-squared is only .05. This is confirmed as p-value is the same because there is only one explanatory variable.\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nmodel <- lm(salary ~ sex, data = salary)\ncoeftest(model, vcov. = vcovHC, type = \"HC1\")\n```\n\n::: {.cell-output .cell-output-error}\n```\nError in coeftest(model, vcov. = vcovHC, type = \"HC1\"): could not find function \"coeftest\"\n```\n:::\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\nmodel <- lm(salary ~ sex, data = salary)\nconfint(model)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n               2.5 %    97.5 %\n(Intercept) 22812.81 26580.773\nsexFemale   -6970.55   291.257\n```\n:::\n:::\n\n\n\n\n# B\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nmodel <- lm(salary ~ sex + degree + rank + year + ysdeg, data = salary)\n\nconfint(model)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n                 2.5 %      97.5 %\n(Intercept) 14134.4059 17357.68946\nsexFemale    -697.8183  3030.56452\ndegreePhD    -663.2482  3440.47485\nrankAssoc    2985.4107  7599.31080\nrankProf     8396.1546 13841.37340\nyear          285.1433   667.47476\nysdeg        -280.6397    31.49105\n```\n:::\n:::\n\n\n95% confidence interval for sex controlling for other variables: \n\n-697.81 to 3030.564\n\n\n\n# C\n\n\n::: {.cell}\n\n```{.r .cell-code}\n lm(salary ~ sex + degree + rank + year + ysdeg, data = salary) |> summary()\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n\nCall:\nlm(formula = salary ~ sex + degree + rank + year + ysdeg, data = salary)\n\nResiduals:\n    Min      1Q  Median      3Q     Max \n-4045.2 -1094.7  -361.5   813.2  9193.1 \n\nCoefficients:\n            Estimate Std. Error t value Pr(>|t|)    \n(Intercept) 15746.05     800.18  19.678  < 2e-16 ***\nsexFemale    1166.37     925.57   1.260    0.214    \ndegreePhD    1388.61    1018.75   1.363    0.180    \nrankAssoc    5292.36    1145.40   4.621 3.22e-05 ***\nrankProf    11118.76    1351.77   8.225 1.62e-10 ***\nyear          476.31      94.91   5.018 8.65e-06 ***\nysdeg        -124.57      77.49  -1.608    0.115    \n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n\nResidual standard error: 2398 on 45 degrees of freedom\nMultiple R-squared:  0.855,\tAdjusted R-squared:  0.8357 \nF-statistic: 44.24 on 6 and 45 DF,  p-value: < 2.2e-16\n```\n:::\n:::\n\n\n\nsex \nThe p-value of 0.214 indicates the effect of sex is insignificant at the 95% confidence interval; with all other variables held equal the coefficient indicates an increase of $1166.37 in salary for female sex with a positive slope. \n\ndegreePhD\nThe p-value of 0.18 indicates the effect of a PhD degree is insignificant at the 95% confidence interval; with all other variables held equal the coefficient indicates an increase of $1388.61 in salary for PhD holders compared to Masters degree holders with a positive slope.\n\nrank\nRank values are in relation to the baseline of rankAsst. The p-values of both rankAssoc and rankProf are low enough to indicate significance at the 95% confidence interval; with all other variables held equal the coefficients indicate positive slopes with a salary increase of $5292.36 and $11,118.76 for Associate and Full Professors respectively compared to Assistant Professor salary.\n\nyear \nThe p-value of less than .05 indicates the effect of years in current rank is significant at the 95% confidence interval; with all other variables held equal the coefficient indicates a positive slope with an increase of $476.31 in salary per increase in year.\n\nysdeg \nThe p-value of 0.115 indicates the effect of ysdeg is insignificant at the 95% confidence interval; with all other variables held equal the coefficient indicates an decrease of $124.57 in salary per year since highest degree with a negative slope. \n\n\n\n# D\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nsalary$rank <- relevel(salary$rank, ref = \"Assoc\")\nsummary(lm(salary ~ sex + degree + rank + year + ysdeg, data = salary))\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n\nCall:\nlm(formula = salary ~ sex + degree + rank + year + ysdeg, data = salary)\n\nResiduals:\n    Min      1Q  Median      3Q     Max \n-4045.2 -1094.7  -361.5   813.2  9193.1 \n\nCoefficients:\n            Estimate Std. Error t value Pr(>|t|)    \n(Intercept) 21038.41    1109.12  18.969  < 2e-16 ***\nsexFemale    1166.37     925.57   1.260    0.214    \ndegreePhD    1388.61    1018.75   1.363    0.180    \nrankAsst    -5292.36    1145.40  -4.621 3.22e-05 ***\nrankProf     5826.40    1012.93   5.752 7.28e-07 ***\nyear          476.31      94.91   5.018 8.65e-06 ***\nysdeg        -124.57      77.49  -1.608    0.115    \n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n\nResidual standard error: 2398 on 45 degrees of freedom\nMultiple R-squared:  0.855,\tAdjusted R-squared:  0.8357 \nF-statistic: 44.24 on 6 and 45 DF,  p-value: < 2.2e-16\n```\n:::\n:::\n\n\nWhen rank's baseline is changed to Assc we are able to see the values for rankAsst. The coefficient of  -5292.36 indicates a negative relationship with p-value indicating significance at the 95% confidence interval.\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nsalary$rank <- relevel(salary$rank, ref = \"Prof\")\nsummary(lm(salary ~ sex + degree + rank + year + ysdeg, data = salary))\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n\nCall:\nlm(formula = salary ~ sex + degree + rank + year + ysdeg, data = salary)\n\nResiduals:\n    Min      1Q  Median      3Q     Max \n-4045.2 -1094.7  -361.5   813.2  9193.1 \n\nCoefficients:\n             Estimate Std. Error t value Pr(>|t|)    \n(Intercept)  26864.81    1375.29  19.534  < 2e-16 ***\nsexFemale     1166.37     925.57   1.260    0.214    \ndegreePhD     1388.61    1018.75   1.363    0.180    \nrankAssoc    -5826.40    1012.93  -5.752 7.28e-07 ***\nrankAsst    -11118.76    1351.77  -8.225 1.62e-10 ***\nyear           476.31      94.91   5.018 8.65e-06 ***\nysdeg         -124.57      77.49  -1.608    0.115    \n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n\nResidual standard error: 2398 on 45 degrees of freedom\nMultiple R-squared:  0.855,\tAdjusted R-squared:  0.8357 \nF-statistic: 44.24 on 6 and 45 DF,  p-value: < 2.2e-16\n```\n:::\n:::\n\n\nWhen we change the baseline to Prof the model tells us that with other variables equal professor with rank Asst would receive $11,118.76 less salary and a professor with rank Assoc would receive $5826.40 less salary. Both these results are significant at the 95% confidence interval. \n\n\n\n# E\n\nRank would be a biased estimator?? multicollinear? \n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlm(salary ~ sex + degree + year + ysdeg, data = salary) |> summary()\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n\nCall:\nlm(formula = salary ~ sex + degree + year + ysdeg, data = salary)\n\nResiduals:\n    Min      1Q  Median      3Q     Max \n-8146.9 -2186.9  -491.5  2279.1 11186.6 \n\nCoefficients:\n            Estimate Std. Error t value Pr(>|t|)    \n(Intercept) 17183.57    1147.94  14.969  < 2e-16 ***\nsexFemale   -1286.54    1313.09  -0.980 0.332209    \ndegreePhD   -3299.35    1302.52  -2.533 0.014704 *  \nyear          351.97     142.48   2.470 0.017185 *  \nysdeg         339.40      80.62   4.210 0.000114 ***\n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n\nResidual standard error: 3744 on 47 degrees of freedom\nMultiple R-squared:  0.6312,\tAdjusted R-squared:  0.5998 \nF-statistic: 20.11 on 4 and 47 DF,  p-value: 1.048e-09\n```\n:::\n:::\n\nComparing the rank excluded model with a non-excluded model we can see that rank is not multicollinear as each rank variable outcome is significant according to its individual p-value and adjusted R-squared decreases when rank is removed from the model. The rank-included model has relatively greater predictive power.\n\n\n\n\n# F\n\nWe can turn ysdeg into a dummy variable dean with 1 if hired after the dean, 0 if hired before the dean.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nsalary$dean <- ifelse(salary$ysdeg <=15, 1, 0)\ntibble(salary)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n# A tibble: 52 × 7\n   degree  rank  sex     year ysdeg salary  dean\n   <fct>   <fct> <fct>  <int> <int>  <int> <dbl>\n 1 Masters Prof  Male      25    35  36350     0\n 2 Masters Prof  Male      13    22  35350     0\n 3 Masters Prof  Male      10    23  28200     0\n 4 Masters Prof  Female     7    27  26775     0\n 5 PhD     Prof  Male      19    30  33696     0\n 6 Masters Prof  Male      16    21  28516     0\n 7 PhD     Prof  Female     0    32  24900     0\n 8 Masters Prof  Male      16    18  31909     0\n 9 PhD     Prof  Male      13    30  31850     0\n10 PhD     Prof  Male      13    31  32850     0\n# … with 42 more rows\n```\n:::\n:::\n\n\n\n\nMulticollinearity check:\n\n\n::: {.cell}\n\n```{.r .cell-code}\ncor(salary$ysdeg, salary$year)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 0.6387763\n```\n:::\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\ncor(salary$ysdeg, salary$dean)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] -0.8434239\n```\n:::\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\ncor(salary$year, salary$dean)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] -0.5394452\n```\n:::\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\nlm(salary ~ sex + degree + year + rank + ysdeg + dean, data = salary) |> summary()\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n\nCall:\nlm(formula = salary ~ sex + degree + year + rank + ysdeg + dean, \n    data = salary)\n\nResiduals:\n    Min      1Q  Median      3Q     Max \n-3621.2 -1336.8  -271.6   530.1  9247.6 \n\nCoefficients:\n             Estimate Std. Error t value Pr(>|t|)    \n(Intercept)  25179.14    1901.59  13.241  < 2e-16 ***\nsexFemale     1084.09     921.49   1.176    0.246    \ndegreePhD     1135.00    1031.16   1.101    0.277    \nyear           460.35      95.09   4.841 1.63e-05 ***\nrankAssoc    -6177.44    1043.04  -5.923 4.39e-07 ***\nrankAsst    -11411.45    1362.02  -8.378 1.16e-10 ***\nysdeg          -47.86      97.71  -0.490    0.627    \ndean          1749.09    1372.83   1.274    0.209    \n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n\nResidual standard error: 2382 on 44 degrees of freedom\nMultiple R-squared:  0.8602,\tAdjusted R-squared:  0.838 \nF-statistic: 38.68 on 7 and 44 DF,  p-value: < 2.2e-16\n```\n:::\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\nlm(salary ~ sex + degree + rank + dean, data = salary) |> summary()\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n\nCall:\nlm(formula = salary ~ sex + degree + rank + dean, data = salary)\n\nResiduals:\n    Min      1Q  Median      3Q     Max \n-6187.5 -1750.9  -438.9  1719.5  9362.9 \n\nCoefficients:\n            Estimate Std. Error t value Pr(>|t|)    \n(Intercept)  29511.3      784.0  37.640  < 2e-16 ***\nsexFemale     -829.2      997.6  -0.831    0.410    \ndegreePhD     1126.2     1018.4   1.106    0.275    \nrankAssoc    -7100.4     1297.0  -5.474 1.76e-06 ***\nrankAsst    -11925.7     1512.4  -7.885 4.37e-10 ***\ndean           319.0     1303.8   0.245    0.808    \n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n\nResidual standard error: 3023 on 46 degrees of freedom\nMultiple R-squared:  0.7645,\tAdjusted R-squared:  0.7389 \nF-statistic: 29.87 on 5 and 46 DF,  p-value: 2.192e-13\n```\n:::\n:::\n\n\n\n\nSelected model excluding ysdeg:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlm(salary ~ sex + degree + year + rank + dean, data = salary) |> summary()\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n\nCall:\nlm(formula = salary ~ sex + degree + year + rank + dean, data = salary)\n\nResiduals:\n    Min      1Q  Median      3Q     Max \n-3403.3 -1387.0  -167.0   528.2  9233.8 \n\nCoefficients:\n             Estimate Std. Error t value Pr(>|t|)    \n(Intercept)  24425.32    1107.52  22.054  < 2e-16 ***\nsexFemale      907.14     840.54   1.079   0.2862    \ndegreePhD      818.93     797.48   1.027   0.3100    \nyear           434.85      78.89   5.512 1.65e-06 ***\nrankAssoc    -6124.28    1028.58  -5.954 3.65e-07 ***\nrankAsst    -11096.95    1191.00  -9.317 4.54e-12 ***\ndean          2163.46    1072.04   2.018   0.0496 *  \n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n\nResidual standard error: 2362 on 45 degrees of freedom\nMultiple R-squared:  0.8594,\tAdjusted R-squared:  0.8407 \nF-statistic: 45.86 on 6 and 45 DF,  p-value: < 2.2e-16\n```\n:::\n:::\n\n\n\nThe new variable dummy dean is derived from ysdeg so we exclude ysdeg from the model. Controlling for all other variables, dean's coefficient of 2163.46 represents a positive relationship between dean hiring and salary however this relationship is not statistically significant. Based on the selected model we are not able to reject the null hypothesis that people hired by the new Dean are making a higher salary at the 95% confidence level due to the p-value of .05. \n\n\n\n## Q3\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(smss) \n```\n\n::: {.cell-output .cell-output-stderr}\n```\nWarning: package 'smss' was built under R version 4.2.2\n```\n:::\n\n```{.r .cell-code}\ndata('house.selling.price', package = 'smss')\n```\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\nsummary(house.selling.price)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n      case            Taxes           Beds       Baths           New      \n Min.   :  1.00   Min.   :  20   Min.   :2   Min.   :1.00   Min.   :0.00  \n 1st Qu.: 25.75   1st Qu.:1178   1st Qu.:3   1st Qu.:2.00   1st Qu.:0.00  \n Median : 50.50   Median :1614   Median :3   Median :2.00   Median :0.00  \n Mean   : 50.50   Mean   :1908   Mean   :3   Mean   :1.96   Mean   :0.11  \n 3rd Qu.: 75.25   3rd Qu.:2238   3rd Qu.:3   3rd Qu.:2.00   3rd Qu.:0.00  \n Max.   :100.00   Max.   :6627   Max.   :5   Max.   :4.00   Max.   :1.00  \n     Price             Size     \n Min.   : 21000   Min.   : 580  \n 1st Qu.: 93225   1st Qu.:1215  \n Median :132600   Median :1474  \n Mean   :155331   Mean   :1629  \n 3rd Qu.:169625   3rd Qu.:1865  \n Max.   :587000   Max.   :4050  \n```\n:::\n\n```{.r .cell-code}\ntibble(house.selling.price)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n# A tibble: 100 × 7\n    case Taxes  Beds Baths   New  Price  Size\n   <int> <int> <int> <int> <int>  <int> <int>\n 1     1  3104     4     2     0 279900  2048\n 2     2  1173     2     1     0 146500   912\n 3     3  3076     4     2     0 237700  1654\n 4     4  1608     3     2     0 200000  2068\n 5     5  1454     3     3     0 159900  1477\n 6     6  2997     3     2     1 499900  3153\n 7     7  4054     3     2     0 265500  1355\n 8     8  3002     3     2     1 289900  2075\n 9     9  6627     5     4     0 587000  3990\n10    10   320     3     2     0  70000  1160\n# … with 90 more rows\n```\n:::\n:::\n\n\n\n\n# A\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlm(Price ~ Size + New, data = house.selling.price) |> summary()\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n\nCall:\nlm(formula = Price ~ Size + New, data = house.selling.price)\n\nResiduals:\n    Min      1Q  Median      3Q     Max \n-205102  -34374   -5778   18929  163866 \n\nCoefficients:\n              Estimate Std. Error t value Pr(>|t|)    \n(Intercept) -40230.867  14696.140  -2.738  0.00737 ** \nSize           116.132      8.795  13.204  < 2e-16 ***\nNew          57736.283  18653.041   3.095  0.00257 ** \n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n\nResidual standard error: 53880 on 97 degrees of freedom\nMultiple R-squared:  0.7226,\tAdjusted R-squared:  0.7169 \nF-statistic: 126.3 on 2 and 97 DF,  p-value: < 2.2e-16\n```\n:::\n:::\n\n\nThe model prediciting home selling price in terms of size and newness is statistically significant overall and accounts for .72 of observed prices. Individually, both Size and New variables are significant at the 95% confidence interval; the Size coefficient indicates an of $116.13 per additional square feet while the New coefficient indicates new homes sell for $57,736.28 more than old homes.\n\n\n\n# B\n\n\nLooking only at new homes, the mean selling price for new homes is predicted to be $290964. \n\n::: {.cell}\n\n```{.r .cell-code}\nprediction1 <- predict(lm(Price ~ Size + New, data = subset(house.selling.price, New==\"1\"))) \n\nsummary(prediction1)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n   Min. 1st Qu.  Median    Mean 3rd Qu.    Max. \n  98870  184542  251916  290964  386247  556178 \n```\n:::\n:::\n\n\n\n\nLooking only at non-new homes, the mean selling price for non-new homes is predicted to be $138,567. \n\n::: {.cell}\n\n```{.r .cell-code}\nprediction0 <- predict(lm(Price ~ Size + New, data = subset(house.selling.price, New==\"0\"))) \n\nsummary(prediction0)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n   Min. 1st Qu.  Median    Mean 3rd Qu.    Max. \n  38347   98921  125030  138567  158451  400748 \n```\n:::\n:::\n\n\n\n\n\n# C\n\n\n::: {.cell}\n\n```{.r .cell-code}\nn <- lm(Price ~ Size + New, data = house.selling.price)\n```\n:::\n\n\n\nThe predicted selling price for a new home of 3000 square feet is $366,016.30\n\n\n::: {.cell}\n\n```{.r .cell-code}\npredict(n, data.frame(Size = 3000) + (New = 1))\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n       1 \n366016.3 \n```\n:::\n:::\n\n\n\nThe predicted selling price for a non-new home of 3000 square feet is $308,163.90\n\n\n::: {.cell}\n\n```{.r .cell-code}\npredict(n, data.frame(Size = 3000) + (New = 0))\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n       1 \n308163.9 \n```\n:::\n:::\n\n\n\n\n\n# D\n\nThe model with an interaction term between size and new indicates overall model significance at the 95% confidence interval due to the low model p-value. With other variables held equal however, the variable New is no longer statistically significant. \n\n\n::: {.cell}\n\n```{.r .cell-code}\nlm(Price ~ Size + New + Size*New, data = house.selling.price) |> summary()\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n\nCall:\nlm(formula = Price ~ Size + New + Size * New, data = house.selling.price)\n\nResiduals:\n    Min      1Q  Median      3Q     Max \n-175748  -28979   -6260   14693  192519 \n\nCoefficients:\n              Estimate Std. Error t value Pr(>|t|)    \n(Intercept) -22227.808  15521.110  -1.432  0.15536    \nSize           104.438      9.424  11.082  < 2e-16 ***\nNew         -78527.502  51007.642  -1.540  0.12697    \nSize:New        61.916     21.686   2.855  0.00527 ** \n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n\nResidual standard error: 52000 on 96 degrees of freedom\nMultiple R-squared:  0.7443,\tAdjusted R-squared:  0.7363 \nF-statistic: 93.15 on 3 and 96 DF,  p-value: < 2.2e-16\n```\n:::\n:::\n\n\n\n\n# E\n\nThe regression line for homes hat are new and not new show the same positive linear relationship and a very similar slope. This indicates that the degree of newness' effect on selling price is similar for new and not new homes. \n\n\n::: {.cell}\n\n```{.r .cell-code}\nnew0 <- subset(house.selling.price, New==\"0\")\n\nggplot(new0, aes(y=Size, x=Price)) + \n  geom_point(colour = \"red\") + \n   geom_smooth(method = \"lm\", se=FALSE) \n```\n\n::: {.cell-output .cell-output-stderr}\n```\n`geom_smooth()` using formula 'y ~ x'\n```\n:::\n\n::: {.cell-output-display}\n![](KenDocekal_HW4_files/figure-html/unnamed-chunk-31-1.png){width=672}\n:::\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\nnew1 <- subset(house.selling.price, New==\"1\")\n\nggplot(new1, aes(y=Size, x=Price)) + \n  geom_point(colour = \"blue\") + \n   geom_smooth(method = \"lm\", se=FALSE) \n```\n\n::: {.cell-output .cell-output-stderr}\n```\n`geom_smooth()` using formula 'y ~ x'\n```\n:::\n\n::: {.cell-output-display}\n![](KenDocekal_HW4_files/figure-html/unnamed-chunk-32-1.png){width=672}\n:::\n:::\n\n\n\n\n\n# F\n\nThe predicted selling price with Size*New\n\n\n::: {.cell}\n\n```{.r .cell-code}\nnI <- lm(Price ~ Size + New + Size*New, data = house.selling.price)\n```\n:::\n\n\n\nThe predicted selling price for a new home of 3000 square feet is $398,473.90.\n\n\n::: {.cell}\n\n```{.r .cell-code}\npredict(nI, data.frame(Size = 3000) + (New = 1))\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n       1 \n398473.9 \n```\n:::\n:::\n\n\n\nThe predicted selling price for a non-new home of 3000 square feet is $291,087.40.\n\n\n::: {.cell}\n\n```{.r .cell-code}\npredict(nI, data.frame(Size = 3000) + (New = 0))\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n       1 \n291087.4 \n```\n:::\n:::\n\n\n\n\n# G\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\npredict(nI, data.frame(Size = 1500) + (New = 1))\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n       1 \n148942.5 \n```\n:::\n\n```{.r .cell-code}\npredict(nI, data.frame(Size = 1500) + (New = 0))\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n       1 \n134429.8 \n```\n:::\n:::\n\n\nAs house size increase the difference in selling price also increases as for a home of 1500 square feet the different between new and non-new is predicted to be $14,512.70, compared to a difference of $107,386.50 for a 3000 square foot home.  \n\n\n# H\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlm(Price ~ Size + New, data = house.selling.price) |> summary()\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n\nCall:\nlm(formula = Price ~ Size + New, data = house.selling.price)\n\nResiduals:\n    Min      1Q  Median      3Q     Max \n-205102  -34374   -5778   18929  163866 \n\nCoefficients:\n              Estimate Std. Error t value Pr(>|t|)    \n(Intercept) -40230.867  14696.140  -2.738  0.00737 ** \nSize           116.132      8.795  13.204  < 2e-16 ***\nNew          57736.283  18653.041   3.095  0.00257 ** \n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n\nResidual standard error: 53880 on 97 degrees of freedom\nMultiple R-squared:  0.7226,\tAdjusted R-squared:  0.7169 \nF-statistic: 126.3 on 2 and 97 DF,  p-value: < 2.2e-16\n```\n:::\n\n```{.r .cell-code}\nlm(Price ~ Size + New + Size*New, data = house.selling.price) |> summary()\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n\nCall:\nlm(formula = Price ~ Size + New + Size * New, data = house.selling.price)\n\nResiduals:\n    Min      1Q  Median      3Q     Max \n-175748  -28979   -6260   14693  192519 \n\nCoefficients:\n              Estimate Std. Error t value Pr(>|t|)    \n(Intercept) -22227.808  15521.110  -1.432  0.15536    \nSize           104.438      9.424  11.082  < 2e-16 ***\nNew         -78527.502  51007.642  -1.540  0.12697    \nSize:New        61.916     21.686   2.855  0.00527 ** \n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n\nResidual standard error: 52000 on 96 degrees of freedom\nMultiple R-squared:  0.7443,\tAdjusted R-squared:  0.7363 \nF-statistic: 93.15 on 3 and 96 DF,  p-value: < 2.2e-16\n```\n:::\n:::\n\n\nThe model with the interaction term is preferable compared to without the interaction term as the adjusted R-squared value is higher while both models are statistically significant indicating that model is more representative of the relationship of Size and New to Price.\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n",
    "supporting": [
      "KenDocekal_HW4_files"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}