{
  "hash": "6474824c6ff21eda7fc6d2d151be0afb",
  "result": {
    "markdown": "---\ntitle: \"Homework 2\"\nauthor: \"Niyati Sharma\"\ndescription: \"The first homework on descriptive statistics and probability\"\ndate: \"10/17/2022\"\nformat:\n  html:\n    toc: true\n    code-fold: true\n    code-copy: true\n    code-tools: true\ncategories:\n  - hw2\n  - desriptive statistics \n  - probability\n---\n\n::: {.cell}\n\n```{.r .cell-code}\n#| label: setup\n#| warning: false\n#| message: false\n \nknitr::opts_chunk$set(echo = TRUE, warning=FALSE, message=FALSE)\n\nlibrary(readxl)\nlibrary(tidyverse)\n```\n\n::: {.cell-output .cell-output-stderr}\n```\n── Attaching packages ─────────────────────────────────────── tidyverse 1.3.2 ──\n✔ ggplot2 3.3.6      ✔ purrr   0.3.4 \n✔ tibble  3.1.8      ✔ dplyr   1.0.10\n✔ tidyr   1.2.1      ✔ stringr 1.4.1 \n✔ readr   2.1.2      ✔ forcats 0.5.2 \n── Conflicts ────────────────────────────────────────── tidyverse_conflicts() ──\n✖ dplyr::filter() masks stats::filter()\n✖ dplyr::lag()    masks stats::lag()\n```\n:::\n\n```{.r .cell-code}\nlibrary(ggplot2)\nlibrary(dplyr)\n```\n:::\n\n\n## 1\nCreating the table with the given data.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nSP <- c('Bypass', 'Angiography')\nSS <- c(539, 847)\nMW <- c(19, 18)\nSD <- c(10, 9)\n\nServeyData <- data.frame(SP, SS, MW, SD)\nServeyData\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n           SP  SS MW SD\n1      Bypass 539 19 10\n2 Angiography 847 18  9\n```\n:::\n:::\n\nCalculate Standard error\n\n::: {.cell}\n\n```{.r .cell-code}\nSE <- SD / sqrt(SS)\nSE\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 0.4307305 0.3092437\n```\n:::\n:::\n\ncalculate the area of the two tails\n\n::: {.cell}\n\n```{.r .cell-code}\nCL <- 0.90  \n#area in each tail of the distribution for 90%\ntail_area <- (1-CL)/2\ntail_area\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 0.05\n```\n:::\n:::\n\n\ncalculate t-values by using the qt() function\n\n::: {.cell}\n\n```{.r .cell-code}\nt_score <- qt(p = 1-tail_area, df = SS-1)\nt_score\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 1.647691 1.646657\n```\n:::\n:::\n\ncalculate the confidence interval\n\n::: {.cell}\n\n```{.r .cell-code}\nCI <- c(MW - t_score * SE,\n        MW + t_score * SE)\nprint(CI)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 18.29029 17.49078 19.70971 18.50922\n```\n:::\n:::\n\nThe 90% confidence interval for bypass is [18.29, 19.71] days and for angiography it is [17.49, 18.51] days. The confidence interval for angiography is narrower. \n\n## 2\nUsing prop.test() to calculate p and the 95% confidence interval.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nset.seed(0)\nprop.test(567, 1031, conf.level = .95)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n\n\t1-sample proportions test with continuity correction\n\ndata:  567 out of 1031, null probability 0.5\nX-squared = 10.091, df = 1, p-value = 0.00149\nalternative hypothesis: true p is not equal to 0.5\n95 percent confidence interval:\n 0.5189682 0.5805580\nsample estimates:\n        p \n0.5499515 \n```\n:::\n:::\n\nThe 95% confidence interval for the point estimate is 0.5195839 - 0.5803191.The point estimate for the proportion of all adult Americans who believe that a college education is essential for success is 0.55.\n\n## 3\nCalculate the min sample size\n\n::: {.cell}\n\n```{.r .cell-code}\n# calculate population SD.\nSD <- (200-30)/4\n#margin of error\nME <- (10/2)\n# calculate sample size.\nsamplesize <- ((1.96*SD)/ME)^2\nsamplesize\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 277.5556\n```\n:::\n:::\n\nthe size of the sample should be 278\n\n## 4 \n\n## a\n\ncalculate t statistic since it will show us the difference in two means\n\nNull hypothesis mean = 500\n\n::: {.cell}\n\n```{.r .cell-code}\nt_stats <- (410-500)/(90/sqrt(9))\nt_stats\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] -3\n```\n:::\n:::\n\nCalculate P value\n\n\n::: {.cell}\n\n```{.r .cell-code}\np_value <- 2* pt(t_stats, df=8)\np_value\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 0.01707168\n```\n:::\n:::\n\nThe test statistic is -3 and the p-value is 0.01707168.The p-value is substantially less than .05 is the evidence that we can reject the null hypothesis. There is strong evidence that the mean income of female employees is not equal to $500.\n\n## b\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nPL <- pt(t_stats, df = 8, lower.tail = TRUE)\nPL\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 0.008535841\n```\n:::\n:::\n\nSince  p-value is 0.0085 is less than the alpha level of 0.05, we can reject the null hypothesis. There is evidence that the mean income of female employees is less than $500.\n\n## c\n\n\n::: {.cell}\n\n```{.r .cell-code}\nPL <- pt(t_stats, df = 8, lower.tail = FALSE)\nPL\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 0.9914642\n```\n:::\n:::\n\nSince  p-value is 0.991 is more than the alpha level of 0.05, we cannot reject the null hypothesis. There is evidence that the mean income of female employees is more than $500.\n\n## 5\n\n## a\n\n::: {.cell}\n\n```{.r .cell-code}\n# calculate standard deviation \nStd_Dev <- 10*sqrt(1000)\n\n# calculate t for Jones.\nt_jones <- ((519.5-500)/Std_Dev) * sqrt(1000)\nt_jones\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 1.95\n```\n:::\n\n```{.r .cell-code}\n# calculate p-value for Jones.\np_jones <- 2*(pt(q=t_jones, df=999, lower.tail=FALSE))\np_jones\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 0.05145555\n```\n:::\n\n```{.r .cell-code}\n# calculate t for Smith.\nt_smith <- ((519.7-500)/Std_Dev) * sqrt(1000)\nt_smith\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 1.97\n```\n:::\n\n```{.r .cell-code}\n# calculate p-value for Smith.\np_smith <- 2*(pt(q=t_smith, df=999, lower.tail=FALSE))\np_smith\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 0.04911426\n```\n:::\n:::\n\n## b\nAt the .05 significance level, we could say that Jones would be unable to reject the null hypothesis since his exceeds .05. Smith on the other hand would barley be able to reject the null hypothesis with his equalling .049. \n\n## c\nBoth of these p values were extremely close to the actual cut off point which shows including them is important. If I would have saw these p scores I would have had doubts or questions regarding the data and would have ran my own test to validate the claims. I think that is reason it would be important to include them to allow other people to see how close the study was. \n\n## 6 \n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\ngas_taxes <- c(51.27, 47.43, 38.89, 41.95, 28.61, 41.29, 52.19, 49.48, 35.02, 48.13, 39.28, 54.41, 41.66, 30.28, 18.49, 38.72, 33.41, 45.02)\nt.test(gas_taxes, mu = 45, alternative = 'less')\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n\n\tOne Sample t-test\n\ndata:  gas_taxes\nt = -1.8857, df = 17, p-value = 0.03827\nalternative hypothesis: true mean is less than 45\n95 percent confidence interval:\n     -Inf 44.67946\nsample estimates:\nmean of x \n 40.86278 \n```\n:::\n:::\n\nHere we can see that the p value for this is .038 which means we can reject the null hypothesis that gas prices are equal to or greater than 45 cents. The mean sample that came up was also within the range of the confidence interval.\n\n\n\n",
    "supporting": [],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}