{
  "hash": "46666624ecf8bf40d95fae261b13b3f7",
  "result": {
    "markdown": "---\ntitle: \"Homework 4\"\nauthor: \"Kaushika Potluri\"\ndesription: \"Homework 4\"\ndate: \"14/11/2022\"\nformat:\n  html:\n    toc: true\n    code-fold: true\n    code-copy: true\n    code-tools: true\neditor: \n  markdown: \n    wrap: sentence\n---\n\n\n## Loading Libraries:\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(readxl)\nlibrary(tidyverse)\n```\n\n::: {.cell-output .cell-output-stderr}\n```\n── Attaching packages ─────────────────────────────────────── tidyverse 1.3.2 ──\n✔ ggplot2 3.4.0      ✔ purrr   0.3.5 \n✔ tibble  3.1.8      ✔ dplyr   1.0.10\n✔ tidyr   1.2.1      ✔ stringr 1.4.1 \n✔ readr   2.1.3      ✔ forcats 0.5.2 \n── Conflicts ────────────────────────────────────────── tidyverse_conflicts() ──\n✖ dplyr::filter() masks stats::filter()\n✖ dplyr::lag()    masks stats::lag()\n```\n:::\n\n```{.r .cell-code}\nlibrary(ggplot2)\nlibrary(dplyr)\nlibrary(stringr)\nlibrary(alr4)\n```\n\n::: {.cell-output .cell-output-stderr}\n```\nLoading required package: car\nLoading required package: carData\n\nAttaching package: 'car'\n\nThe following object is masked from 'package:dplyr':\n\n    recode\n\nThe following object is masked from 'package:purrr':\n\n    some\n\nLoading required package: effects\nlattice theme set by effectsTheme()\nSee ?effectsTheme for details.\n```\n:::\n\n```{.r .cell-code}\nlibrary(smss)\n```\n:::\n\n#1(a)\nPrediction equation: ŷ = −10,536 + 53.8x1 + 2.84x2.\n\n::: {.cell}\n\n```{.r .cell-code}\n#Plugging in the values of home and lot size into prediction equation\npredicted_sellingprice <- -10536 + 53.8*1240 + 2.84*18000\npredicted_sellingprice\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 107296\n```\n:::\n:::\n\n\n$107,297 is the predicticted selling price\n\n\n::: {.cell}\n\n```{.r .cell-code}\n#Residual = Actual-predicted\nresidual <- 145000-107296\nresidual\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 37704\n```\n:::\n:::\n\n\nTherfore, the Residual is $37,704.\n\n#1(b)\n\nThe prediction equation is ŷ = -10536 + 53.8x1 + 2.84x2. Using this, where x2= lot size, the house selling price is expected to increase by 53.8 dollars per each square-foot increase in home size given the lot sized is fixed. This is due to a fixed lot size would make 2.84x2 a set number in the prediction equation. Which means in the prediction equation y = -10356 + 53.8x1 + 2.84x2 x1 would have input values making it increase.\n\n#1(c)\nFor fixed home size, 53.8 * 1 = 2.84x2\n\n::: {.cell}\n\n```{.r .cell-code}\nx2 <- 53.8/2.84\nx2\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 18.94366\n```\n:::\n:::\n\n\nAn increase in lot size of about 18.94 square-feet would have the same impact as an increase of 1 square-foot in home size on the predicted selling price.\n\n#2\n\n::: {.cell}\n\n```{.r .cell-code}\ndata(\"salary\")\nsalary\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n    degree  rank    sex year ysdeg salary\n1  Masters  Prof   Male   25    35  36350\n2  Masters  Prof   Male   13    22  35350\n3  Masters  Prof   Male   10    23  28200\n4  Masters  Prof Female    7    27  26775\n5      PhD  Prof   Male   19    30  33696\n6  Masters  Prof   Male   16    21  28516\n7      PhD  Prof Female    0    32  24900\n8  Masters  Prof   Male   16    18  31909\n9      PhD  Prof   Male   13    30  31850\n10     PhD  Prof   Male   13    31  32850\n11 Masters  Prof   Male   12    22  27025\n12 Masters Assoc   Male   15    19  24750\n13 Masters  Prof   Male    9    17  28200\n14     PhD Assoc   Male    9    27  23712\n15 Masters  Prof   Male    9    24  25748\n16 Masters  Prof   Male    7    15  29342\n17 Masters  Prof   Male   13    20  31114\n18     PhD Assoc   Male   11    14  24742\n19     PhD Assoc   Male   10    15  22906\n20     PhD  Prof   Male    6    21  24450\n21     PhD  Asst   Male   16    23  19175\n22     PhD Assoc   Male    8    31  20525\n23 Masters  Prof   Male    7    13  27959\n24 Masters  Prof Female    8    24  38045\n25 Masters Assoc   Male    9    12  24832\n26 Masters  Prof   Male    5    18  25400\n27 Masters Assoc   Male   11    14  24800\n28 Masters  Prof Female    5    16  25500\n29     PhD Assoc   Male    3     7  26182\n30     PhD Assoc   Male    3    17  23725\n31     PhD  Asst Female   10    15  21600\n32     PhD Assoc   Male   11    31  23300\n33     PhD  Asst   Male    9    14  23713\n34     PhD Assoc Female    4    33  20690\n35     PhD Assoc Female    6    29  22450\n36 Masters Assoc   Male    1     9  20850\n37 Masters  Asst Female    8    14  18304\n38 Masters  Asst   Male    4     4  17095\n39 Masters  Asst   Male    4     5  16700\n40 Masters  Asst   Male    4     4  17600\n41 Masters  Asst   Male    3     4  18075\n42     PhD  Asst   Male    3    11  18000\n43 Masters Assoc   Male    0     7  20999\n44 Masters  Asst Female    3     3  17250\n45 Masters  Asst   Male    2     3  16500\n46 Masters  Asst   Male    2     1  16094\n47 Masters  Asst Female    2     6  16150\n48 Masters  Asst Female    2     2  15350\n49 Masters  Asst   Male    1     1  16244\n50 Masters  Asst Female    1     1  16686\n51 Masters  Asst Female    1     1  15000\n52 Masters  Asst Female    0     2  20300\n```\n:::\n:::\n\n\n#2(a)\n\n::: {.cell}\n\n```{.r .cell-code}\nsummary(lm(salary ~ sex, data = salary))\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n\nCall:\nlm(formula = salary ~ sex, data = salary)\n\nResiduals:\n    Min      1Q  Median      3Q     Max \n-8602.8 -4296.6  -100.8  3513.1 16687.9 \n\nCoefficients:\n            Estimate Std. Error t value Pr(>|t|)    \n(Intercept)    24697        938  26.330   <2e-16 ***\nsexFemale      -3340       1808  -1.847   0.0706 .  \n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n\nResidual standard error: 5782 on 50 degrees of freedom\nMultiple R-squared:  0.0639,\tAdjusted R-squared:  0.04518 \nF-statistic: 3.413 on 1 and 50 DF,  p-value: 0.0706\n```\n:::\n:::\n\n\nHere the null hypothesis would be: mean salary for men and women are equal\nThe Alternative hypothesis would be: the salaries are not equal for men and women.\nHere, the female coefficient is -3340, which can imply that women do make less than men not considering any other variables. However, if we consider the other variables and also there is a significance level of 0.07, hence we fail to reject the null hypothesis.\nTherefore, we cannot conclude that there is a difference between mean salaries for men and women.\n\n#2(b)\n\n::: {.cell}\n\n```{.r .cell-code}\nmodel <- lm(salary ~ ., data = salary)\nsummary(model)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n\nCall:\nlm(formula = salary ~ ., data = salary)\n\nResiduals:\n    Min      1Q  Median      3Q     Max \n-4045.2 -1094.7  -361.5   813.2  9193.1 \n\nCoefficients:\n            Estimate Std. Error t value Pr(>|t|)    \n(Intercept) 15746.05     800.18  19.678  < 2e-16 ***\ndegreePhD    1388.61    1018.75   1.363    0.180    \nrankAssoc    5292.36    1145.40   4.621 3.22e-05 ***\nrankProf    11118.76    1351.77   8.225 1.62e-10 ***\nsexFemale    1166.37     925.57   1.260    0.214    \nyear          476.31      94.91   5.018 8.65e-06 ***\nysdeg        -124.57      77.49  -1.608    0.115    \n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n\nResidual standard error: 2398 on 45 degrees of freedom\nMultiple R-squared:  0.855,\tAdjusted R-squared:  0.8357 \nF-statistic: 44.24 on 6 and 45 DF,  p-value: < 2.2e-16\n```\n:::\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\nconfint(model)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n                 2.5 %      97.5 %\n(Intercept) 14134.4059 17357.68946\ndegreePhD    -663.2482  3440.47485\nrankAssoc    2985.4107  7599.31080\nrankProf     8396.1546 13841.37340\nsexFemale    -697.8183  3030.56452\nyear          285.1433   667.47476\nysdeg        -280.6397    31.49105\n```\n:::\n:::\n\n\nThe 95% confidence interval for the difference in salary between male and females is -697.82 and 3030.56.\n\n#2(d)\n\nDegreeePhD: For a faculty member that has a PhD degree their predicted salary is $1388.61 than other faculty members who don’t have a PhD degree. \n\nRank: The baseline category is asst prof.For an associate professor their predicted salary is $5,292.36. For a professor their predicted salary is $11,118.76.\nThese salary differences are statistically significant at the 0.0001 alpha level for both Asst and Professor rank.\n\n\nSex: For a faculty member who is female their predicted salary is $1166.37 more than a male. However, his coefficient is not statistically significant at any alpha level.\n\nYear: Every year a faculty member’s salary is expected to increase by $478.31.The coeffiticent is significant at the 0.0001 alpha level.\n\nysdegree: For every year after degree completion they can expect to have their slary decrese by $124.57. However this coefficient is not significant at any alpha level.\n\n#2(d)\n\n::: {.cell}\n\n```{.r .cell-code}\nsalary$rank<- relevel(salary$rank, ref = 'Assoc')\nsummary(lm(salary ~ degree + rank + sex + year + ysdeg, data=salary))\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n\nCall:\nlm(formula = salary ~ degree + rank + sex + year + ysdeg, data = salary)\n\nResiduals:\n    Min      1Q  Median      3Q     Max \n-4045.2 -1094.7  -361.5   813.2  9193.1 \n\nCoefficients:\n            Estimate Std. Error t value Pr(>|t|)    \n(Intercept) 21038.41    1109.12  18.969  < 2e-16 ***\ndegreePhD    1388.61    1018.75   1.363    0.180    \nrankAsst    -5292.36    1145.40  -4.621 3.22e-05 ***\nrankProf     5826.40    1012.93   5.752 7.28e-07 ***\nsexFemale    1166.37     925.57   1.260    0.214    \nyear          476.31      94.91   5.018 8.65e-06 ***\nysdeg        -124.57      77.49  -1.608    0.115    \n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n\nResidual standard error: 2398 on 45 degrees of freedom\nMultiple R-squared:  0.855,\tAdjusted R-squared:  0.8357 \nF-statistic: 44.24 on 6 and 45 DF,  p-value: < 2.2e-16\n```\n:::\n:::\n\nThe baseline category is now Assoc. According to these coefficients, faculty of rank asst are expected to make $5292.36 less than Associate professors. Faculty of rank Professor are expected to make $5826.40 more than Associate professors.\n\n#2(e)\n\n::: {.cell}\n\n```{.r .cell-code}\nsummary(lm(salary ~ degree + sex + year + ysdeg, data=salary))\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n\nCall:\nlm(formula = salary ~ degree + sex + year + ysdeg, data = salary)\n\nResiduals:\n    Min      1Q  Median      3Q     Max \n-8146.9 -2186.9  -491.5  2279.1 11186.6 \n\nCoefficients:\n            Estimate Std. Error t value Pr(>|t|)    \n(Intercept) 17183.57    1147.94  14.969  < 2e-16 ***\ndegreePhD   -3299.35    1302.52  -2.533 0.014704 *  \nsexFemale   -1286.54    1313.09  -0.980 0.332209    \nyear          351.97     142.48   2.470 0.017185 *  \nysdeg         339.40      80.62   4.210 0.000114 ***\n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n\nResidual standard error: 3744 on 47 degrees of freedom\nMultiple R-squared:  0.6312,\tAdjusted R-squared:  0.5998 \nF-statistic: 20.11 on 4 and 47 DF,  p-value: 1.048e-09\n```\n:::\n:::\n\n\nRemoving the rank variable reveals a difference between male and female salaries with females making $1286.54 less than men. However, this difference is not signficant at any standard alpha levels.\n\n#2(f)\n\n\n::: {.cell}\n\n```{.r .cell-code}\nsalary<-mutate(salary, hired= case_when(ysdeg<15 ~ \"new\", ysdeg>=15 ~ \"old\"))\nsummary(lm( salary ~ degree + sex + rank +  hired + year, data = salary))\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n\nCall:\nlm(formula = salary ~ degree + sex + rank + hired + year, data = salary)\n\nResiduals:\n    Min      1Q  Median      3Q     Max \n-3588.0 -1532.2  -232.2   565.7  9132.5 \n\nCoefficients:\n            Estimate Std. Error t value Pr(>|t|)    \n(Intercept)  20468.7      951.7  21.507  < 2e-16 ***\ndegreePhD     1073.5      843.3   1.273   0.2096    \nsexFemale     1046.7      858.0   1.220   0.2289    \nrankAsst     -5012.5     1002.3  -5.001 9.16e-06 ***\nrankProf      6213.3     1045.0   5.946 3.76e-07 ***\nhiredold     -2421.6     1187.9  -2.038   0.0474 *  \nyear           450.7       81.5   5.530 1.55e-06 ***\n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n\nResidual standard error: 2360 on 45 degrees of freedom\nMultiple R-squared:  0.8597,\tAdjusted R-squared:  0.841 \nF-statistic: 45.95 on 6 and 45 DF,  p-value: < 2.2e-16\n```\n:::\n:::\n\nAccording to this equation, faculty hired by the old dean make $2421.60 less than new faculty when we control for other factors. This is significant at the 0.05 alpha level.\nExcluded ysdegree after creating the new variable to avoid multicollinearity.\n\n#3(a)\n\n::: {.cell}\n\n```{.r .cell-code}\ndata(house.selling.price)\nhouse.selling.price\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n    case Taxes Beds Baths New  Price Size\n1      1  3104    4     2   0 279900 2048\n2      2  1173    2     1   0 146500  912\n3      3  3076    4     2   0 237700 1654\n4      4  1608    3     2   0 200000 2068\n5      5  1454    3     3   0 159900 1477\n6      6  2997    3     2   1 499900 3153\n7      7  4054    3     2   0 265500 1355\n8      8  3002    3     2   1 289900 2075\n9      9  6627    5     4   0 587000 3990\n10    10   320    3     2   0  70000 1160\n11    11   630    3     2   0  64500 1220\n12    12  1780    3     2   0 167000 1690\n13    13  1630    3     2   0 114600 1380\n14    14  1530    3     2   0 103000 1590\n15    15   930    3     1   0 101000 1050\n16    16   590    2     1   0  70000  770\n17    17  1050    3     2   0  85000 1410\n18    18    20    3     1   0  22500 1060\n19    19   870    2     2   0  90000 1300\n20    20  1320    3     2   0 133000 1500\n21    21  1350    2     1   0  90500  820\n22    22  5616    4     3   1 577500 3949\n23    23   680    2     1   0 142500 1170\n24    24  1840    3     2   0 160000 1500\n25    25  3680    4     2   0 240000 2790\n26    26  1660    3     1   0  87000 1030\n27    27  1620    3     2   0 118600 1250\n28    28  3100    3     2   0 140000 1760\n29    29  2070    2     3   0 148000 1550\n30    30   830    3     2   0  69000 1120\n31    31  2260    4     2   0 176000 2000\n32    32  1760    3     1   0  86500 1350\n33    33  2750    3     2   1 180000 1840\n34    34  2020    4     2   0 179000 2510\n35    35  4900    3     3   1 338000 3110\n36    36  1180    4     2   0 130000 1760\n37    37  2150    3     2   0 163000 1710\n38    38  1600    2     1   0 125000 1110\n39    39  1970    3     2   0 100000 1360\n40    40  2060    3     1   0 100000 1250\n41    41  1980    3     1   0 100000 1250\n42    42  1510    3     2   0 146500 1480\n43    43  1710    3     2   0 144900 1520\n44    44  1590    3     2   0 183000 2020\n45    45  1230    3     2   0  69900 1010\n46    46  1510    2     2   0  60000 1640\n47    47  1450    2     2   0 127000  940\n48    48   970    3     2   0  86000 1580\n49    49   150    2     2   0  50000  860\n50    50  1470    3     2   0 137000 1420\n51    51  1850    3     2   0 121300 1270\n52    52   820    2     1   0  81000  980\n53    53  2050    4     2   0 188000 2300\n54    54   710    3     2   0  85000 1430\n55    55  1280    3     2   0 137000 1380\n56    56  1360    3     2   0 145000 1240\n57    57   830    3     2   0  69000 1120\n58    58   800    3     2   0 109300 1120\n59    59  1220    3     2   0 131500 1900\n60    60  3360    4     3   0 200000 2430\n61    61   210    3     2   0  81900 1080\n62    62   380    2     1   0  91200 1350\n63    63  1920    4     3   0 124500 1720\n64    64  4350    3     3   0 225000 4050\n65    65  1510    3     2   0 136500 1500\n66    66  4154    3     3   0 381000 2581\n67    67  1976    3     2   1 250000 2120\n68    68  3605    3     3   1 354900 2745\n69    69  1400    3     2   0 140000 1520\n70    70   790    2     2   0  89900 1280\n71    71  1210    3     2   0 137000 1620\n72    72  1550    3     2   0 103000 1520\n73    73  2800    3     2   0 183000 2030\n74    74  2560    3     2   0 140000 1390\n75    75  1390    4     2   0 160000 1880\n76    76  5443    3     2   0 434000 2891\n77    77  2850    2     1   0 130000 1340\n78    78  2230    2     2   0 123000  940\n79    79    20    2     1   0  21000  580\n80    80  1510    4     2   0  85000 1410\n81    81   710    3     2   0  69900 1150\n82    82  1540    3     2   0 125000 1380\n83    83  1780    3     2   1 162600 1470\n84    84  2920    2     2   1 156900 1590\n85    85  1710    3     2   1 105900 1200\n86    86  1880    3     2   0 167500 1920\n87    87  1680    3     2   0 151800 2150\n88    88  3690    5     3   0 118300 2200\n89    89   900    2     2   0  94300  860\n90    90   560    3     1   0  93900 1230\n91    91  2040    4     2   0 165000 1140\n92    92  4390    4     3   1 285000 2650\n93    93   690    3     1   0  45000 1060\n94    94  2100    3     2   0 124900 1770\n95    95  2880    4     2   0 147000 1860\n96    96   990    2     2   0 176000 1060\n97    97  3030    3     2   0 196500 1730\n98    98  1580    3     2   0 132200 1370\n99    99  1770    3     2   0  88400 1560\n100  100  1430    3     2   0 127200 1340\n```\n:::\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\nsummary(lm(Price ~ Size + New, data= house.selling.price))\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n\nCall:\nlm(formula = Price ~ Size + New, data = house.selling.price)\n\nResiduals:\n    Min      1Q  Median      3Q     Max \n-205102  -34374   -5778   18929  163866 \n\nCoefficients:\n              Estimate Std. Error t value Pr(>|t|)    \n(Intercept) -40230.867  14696.140  -2.738  0.00737 ** \nSize           116.132      8.795  13.204  < 2e-16 ***\nNew          57736.283  18653.041   3.095  0.00257 ** \n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n\nResidual standard error: 53880 on 97 degrees of freedom\nMultiple R-squared:  0.7226,\tAdjusted R-squared:  0.7169 \nF-statistic: 126.3 on 2 and 97 DF,  p-value: < 2.2e-16\n```\n:::\n:::\n\n\nAccording to the coefficient for size, the price of a house is expected to increase by $116.132 for each square foot increase in size. The coefficient is significant at the 0.0001 alpha level, meaning there is a strong correlation between size and price when the age status (new/old) is held fixed.\n\nAccording to the coefficient for new, a new house is expected to cost $57,736.283 more than an old house. This variable is significant at the 0.001 level, meaning that whether a house is old or new has a strong positive impact on price of the house.\n\n#3(b)\n\nY = -40230.867 + 116.132(X1) + 57736.283 (X2) where X1 represents size and X2 represents new/old.\n\nFor a new house: Y = -40230.867 + 116.132(size) + 57736.283\n\nFor an old house: Y = -40230.867 + 116.132(size)\n\n#3(c)\n\n::: {.cell}\n\n```{.r .cell-code}\nsize<- 3000\n-40230.867 + (116.132 * size) + 57736.283 \n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 365901.4\n```\n:::\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\nsize<- 3000\n-40230.867 + (116.132 *size)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 308165.1\n```\n:::\n:::\n\n\n#3(d)\n\n::: {.cell}\n\n```{.r .cell-code}\nsummary(lm( Price~ Size*New, data = house.selling.price))\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n\nCall:\nlm(formula = Price ~ Size * New, data = house.selling.price)\n\nResiduals:\n    Min      1Q  Median      3Q     Max \n-175748  -28979   -6260   14693  192519 \n\nCoefficients:\n              Estimate Std. Error t value Pr(>|t|)    \n(Intercept) -22227.808  15521.110  -1.432  0.15536    \nSize           104.438      9.424  11.082  < 2e-16 ***\nNew         -78527.502  51007.642  -1.540  0.12697    \nSize:New        61.916     21.686   2.855  0.00527 ** \n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n\nResidual standard error: 52000 on 96 degrees of freedom\nMultiple R-squared:  0.7443,\tAdjusted R-squared:  0.7363 \nF-statistic: 93.15 on 3 and 96 DF,  p-value: < 2.2e-16\n```\n:::\n:::\n\n\n#3(e)\nThe predicted selling price, based on the new regression that includes interaction between Size and Newness, would look like:\n\nFor a new house: Y = -22227.81 + 104.44 * Size - 78527.50 * 1 + 61.92 * Size * 1\n\nOld: Y = -22227.81 + 104.44 * Size\n\n#3(f)\n\n::: {.cell}\n\n```{.r .cell-code}\n#new: \n-2227.808 + 166.354*3000 - 78527.502\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 418306.7\n```\n:::\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\n#not new:\n-2227.808 + 104.438*3000\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 311086.2\n```\n:::\n:::\n\n\nNew: $418,306.70 Not new: $311,086.20\n\n#3(g)\n\n::: {.cell}\n\n```{.r .cell-code}\n#new: \n-2227.808 + 166.354*1500 - 78527.502\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 168775.7\n```\n:::\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\nSize <- 1500\nNew_Price = -22227.81 + 104.44 * Size - 78527.50 * 1 + 61.92 * Size * 1\nOld_Price = -22227.81 + 104.44 * Size\nNew_Price\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 148784.7\n```\n:::\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\nOld_Price\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 134432.2\n```\n:::\n:::\n\n\nAs size of home goes up, the difference in predicted selling prices between old and new homes becomes larger.\nHouses that are larger are much greater in price, especially when comparing new large houses to small new houses.\n\n#3(h)\n\nI prefer the second model with the interaction term which provides a clearer picture of how increased square footage makes a larger difference in bigger sized houses. The model with the interaction term also has a larger adjusted R squared.\n\n\n::: {.cell}\n\n```{.r .cell-code}\n#for a 1000 sq foot home:\n#New:\n-2227.808 + 166.354*1000 - 78527.502\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 85598.69\n```\n:::\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\n#Not new:\n-2227.808 + 104.438*1000\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 102210.2\n```\n:::\n:::\n\n\nI wouldn't use this model for small homes: for a home that is 1000 square feet, the predicted price for a new house is greater than for an old house. \nSo I dont think this model would be good at predicting tiny house prices.\n",
    "supporting": [],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}