{
  "hash": "6ad06393a4253c7bddd01fcd664903ce",
  "result": {
    "markdown": "---\ntitle: \"Final Project\"\nauthor: \"Niharika Pola\"\ndescription: \"Final Project\"\ndate: \"12/13/2022\"\nformat:\n  html:\n    df-print: paged\n    css: styles.css\n    toc: true\n    code-fold: true\n    code-copy: true\n    code-tools: true\ncategories:\n  - Final Project\n---\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(tidyverse)\nlibrary(ggplot2)\nlibrary(readr)\nlibrary(corrplot)\nlibrary(reshape2)\nlibrary(corrgram)\nlibrary(ggpubr)\nlibrary(caTools)\nlibrary(GGally)\nlibrary(stats)\nlibrary(ggsci)\n```\n:::\n\n\n# Happiness Explained: Through Multiple Linear Regression.\n\n## Background/Motivation\n\nWhat is takes for a country or a continent to be happy or sad? Is it the higher GDP per capita, lower Population growth, lower Suicide rate or Urbanization? What are the factors that affect a country's or continents overall happiness? Can we predict the happiness score? The curiosity to find answers to these questions made me explore the world happiness scores and world data by country.\n\nThe World Happiness Report is a landmark survey of the state of global happiness . The report continues to gain global recognition as governments, organizations and civil society increasingly use happiness indicators to inform their policy-making decisions. Leading experts across fields -- economics, psychology, survey analysis, national statistics, health, public policy and more -- describe how measurements of well-being can be used effectively to assess the progress of nations. The reports review the state of happiness in the world today and show how the new science of happiness explains personal and national variations in happiness.\n\nThe data sets that are used in this analysis are 1) [world happiness report 2021](https://www.kaggle.com/datasets/ajaypalsinghlo/world-happiness-report-2021) and 2) kaggle's [world data by country 2020](https://www.kaggle.com/datasets/daniboy370/world-data-by-country-2020). Happiness scores from first data set and few variables from the second data set are being used to analyse the following research question.\n\n## Research Question\n\n1.  What are the variables or factors that are affecting a country's happiness?\n2.  To find out which model fits/accurately predicts the happiness score.\n\n## Hypothesis\n\nI wish to test the following hypothesis,\n\n1.  Higher/Better GDP per capital leads to a country's happiness.\n2.  Urbanization leads to a country's happiness.\n3.  Higher Life Expectancy leads to country's happiness.\n\nThis study aims to test the above hypothesis while comparing the GDP per capital and Urbanization with other variables including: Population growth, Life Expectancy, Sex-Ratio and Suicide Rate.\n\n### Reading & Preparing the data sets\n\n\n::: {.cell}\n\n```{.r .cell-code}\n#dataset-1\nhappiness <- read_csv(\"project datasets/world-happiness-report-2021.csv\")\n```\n\n::: {.cell-output .cell-output-stderr}\n```\nRows: 149 Columns: 20\n── Column specification ────────────────────────────────────────────────────────\nDelimiter: \",\"\nchr  (2): Country name, Regional indicator\ndbl (18): Ladder score, Standard error of ladder score, upperwhisker, lowerw...\n\nℹ Use `spec()` to retrieve the full column specification for this data.\nℹ Specify the column types or set `show_col_types = FALSE` to quiet this message.\n```\n:::\n\n```{.r .cell-code}\nhap_sc <- select(happiness, \"Country name\", \"Ladder score\")\nhap_sc <- rename(hap_sc, \"Country\"=\"Country name\", \"Happiness\"=\"Ladder score\")\ncolnames(hap_sc)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] \"Country\"   \"Happiness\"\n```\n:::\n\n```{.r .cell-code}\n#datasets from world data by country\nGDP_per_capita <- read_csv(\"project datasets/GDP per capita.csv\")\n```\n\n::: {.cell-output .cell-output-stderr}\n```\nRows: 191 Columns: 3\n── Column specification ────────────────────────────────────────────────────────\nDelimiter: \",\"\nchr (2): Country, ISO-code\ndbl (1): GDP per capita\n\nℹ Use `spec()` to retrieve the full column specification for this data.\nℹ Specify the column types or set `show_col_types = FALSE` to quiet this message.\n```\n:::\n\n```{.r .cell-code}\nUrbanization_rate <- read_csv(\"project datasets/Urbanization rate.csv\")\n```\n\n::: {.cell-output .cell-output-stderr}\n```\nRows: 218 Columns: 3\n── Column specification ────────────────────────────────────────────────────────\nDelimiter: \",\"\nchr (2): Country, ISO-code\ndbl (1): Urbanization rate\n\nℹ Use `spec()` to retrieve the full column specification for this data.\nℹ Specify the column types or set `show_col_types = FALSE` to quiet this message.\n```\n:::\n\n```{.r .cell-code}\nPopulation_growth <- read_csv(\"project datasets/Population growth.csv\")\n```\n\n::: {.cell-output .cell-output-stderr}\n```\nRows: 207 Columns: 3\n── Column specification ────────────────────────────────────────────────────────\nDelimiter: \",\"\nchr (2): Country, ISO-code\ndbl (1): Population growth\n\nℹ Use `spec()` to retrieve the full column specification for this data.\nℹ Specify the column types or set `show_col_types = FALSE` to quiet this message.\n```\n:::\n\n```{.r .cell-code}\nLife_expectancy <- read_csv(\"project datasets/Life expectancy.csv\")\n```\n\n::: {.cell-output .cell-output-stderr}\n```\nRows: 185 Columns: 3\n── Column specification ────────────────────────────────────────────────────────\nDelimiter: \",\"\nchr (2): Country, ISO-code\ndbl (1): Life expectancy\n\nℹ Use `spec()` to retrieve the full column specification for this data.\nℹ Specify the column types or set `show_col_types = FALSE` to quiet this message.\n```\n:::\n\n```{.r .cell-code}\nSuicide_rate <- read_csv(\"project datasets/Suicide rate.csv\")\n```\n\n::: {.cell-output .cell-output-stderr}\n```\nRows: 182 Columns: 3\n── Column specification ────────────────────────────────────────────────────────\nDelimiter: \",\"\nchr (2): Country, ISO-code\ndbl (1): Suicide rate\n\nℹ Use `spec()` to retrieve the full column specification for this data.\nℹ Specify the column types or set `show_col_types = FALSE` to quiet this message.\n```\n:::\n\n```{.r .cell-code}\nSex_ratio <- read_csv(\"project datasets/Sex-ratio.csv\")\n```\n\n::: {.cell-output .cell-output-stderr}\n```\nRows: 226 Columns: 3\n── Column specification ────────────────────────────────────────────────────────\nDelimiter: \",\"\nchr (2): Country, ISO-code\ndbl (1): Sex-ratio\n\nℹ Use `spec()` to retrieve the full column specification for this data.\nℹ Specify the column types or set `show_col_types = FALSE` to quiet this message.\n```\n:::\n\n```{.r .cell-code}\n#merging the above datasets by country and iso code\n\nworld_data <- merge(GDP_per_capita, Urbanization_rate)\nworld_data <- merge(world_data, Population_growth)\nworld_data <- merge(world_data, Life_expectancy)\nworld_data <- merge(world_data, Suicide_rate)\nworld_data <- merge(world_data, Sex_ratio)\n\n\n\n#merging happiness scores and world data\nhappy <- merge(world_data, hap_sc)\nhappy <- rename(happy, \"GDP.per.capita\"=\"GDP per capita\", \"urbanization.rate\"=\"Urbanization rate\", \"Population.growth\"=\"Population growth\", \"Life.expectancy\"=\"Life expectancy\", \"Suicide.rate\"=\"Suicide rate\", \"Sex.ratio\"=\"Sex-ratio\")\nstr(happy)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n'data.frame':\t199 obs. of  9 variables:\n $ Country          : chr  \"Afghanistan\" \"Algeria\" \"Argentina\" \"Armenia\" ...\n $ ISO-code         : chr  \"AFG\" \"DZA\" \"ARG\" \"ARM\" ...\n $ GDP.per.capita   : num  2182 16091 19971 11845 54799 ...\n $ urbanization.rate: num  26 73.7 92.1 63.3 86.2 58.7 56.4 89.5 38.2 79.5 ...\n $ Population.growth: num  2.41 1.89 0.88 0.17 1.6 0.46 1.35 1.92 1.19 -0.1 ...\n $ Life.expectancy  : num  64.5 76.7 76.5 74.9 83.3 81.4 72.9 77.2 72.3 74.6 ...\n $ Suicide.rate     : num  6.4 3.3 9.1 5.7 11.7 11.4 2.6 5.7 6.1 21.4 ...\n $ Sex.ratio        : num  1.03 1.03 0.98 0.95 0.99 0.96 0.98 1.53 0.97 0.87 ...\n $ Happiness        : num  2.52 4.89 5.93 5.28 7.18 ...\n```\n:::\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\n#adding continents data to final dataset\nhappy$Continent <- NA\n\nhappy$Continent[which(happy$Country %in% c(\"Israel\", \"United Arab Emirates\", \"Singapore\", \"Thailand\", \"Taiwan Province of China\",\n                                   \"Qatar\", \"Saudi Arabia\", \"Kuwait\", \"Bahrain\", \"Malaysia\", \"Uzbekistan\", \"Japan\",\n                                   \"South Korea\", \"Turkmenistan\", \"Kazakhstan\", \"Turkey\", \"Hong Kong S.A.R., China\", \"Philippines\",\n                                   \"Jordan\", \"China\", \"Pakistan\", \"Indonesia\", \"Azerbaijan\", \"Lebanon\", \"Vietnam\",\n                                   \"Tajikistan\", \"Bhutan\", \"Kyrgyzstan\", \"Nepal\", \"Mongolia\", \"Palestinian Territories\",\n                                   \"Iran\", \"Bangladesh\", \"Myanmar\", \"Iraq\", \"Sri Lanka\", \"Armenia\", \"India\", \"Georgia\",\n                                   \"Cambodia\", \"Afghanistan\", \"Yemen\", \"Syria\"))] <- \"Asia\"\nhappy$Continent[which(happy$Country %in% c(\"Norway\", \"Denmark\", \"Iceland\", \"Switzerland\", \"Finland\",\n                                   \"Netherlands\", \"Sweden\", \"Austria\", \"Ireland\", \"Germany\",\n                                   \"Belgium\", \"Luxembourg\", \"United Kingdom\", \"Czech Republic\",\n                                   \"Malta\", \"France\", \"Spain\", \"Slovakia\", \"Poland\", \"Italy\",\n                                   \"Russia\", \"Lithuania\", \"Latvia\", \"Moldova\", \"Romania\",\n                                   \"Slovenia\", \"North Cyprus\", \"Cyprus\", \"Estonia\", \"Belarus\",\n                                   \"Serbia\", \"Hungary\", \"Croatia\", \"Kosovo\", \"Montenegro\",\n                                   \"Greece\", \"Portugal\", \"Bosnia and Herzegovina\", \"Macedonia\",\n                                   \"Bulgaria\", \"Albania\", \"Ukraine\"))] <- \"Europe\"\nhappy$Continent[which(happy$Country %in% c(\"Canada\", \"Costa Rica\", \"United States\", \"Mexico\",  \n                                   \"Panama\",\"Trinidad and Tobago\", \"El Salvador\", \"Belize\", \"Guatemala\",\n                                   \"Jamaica\", \"Nicaragua\", \"Dominican Republic\", \"Honduras\",\n                                   \"Haiti\"))] <- \"North America\"\nhappy$Continent[which(happy$Country %in% c(\"Chile\", \"Brazil\", \"Argentina\", \"Uruguay\",\n                                   \"Colombia\", \"Ecuador\", \"Bolivia\", \"Peru\",\n                                   \"Paraguay\", \"Venezuela\"))] <- \"South America\"\nhappy$Continent[which(happy$Country %in% c(\"New Zealand\", \"Australia\"))] <- \"Australia\"\nhappy$Continent[which(is.na(happy$Continent))] <- \"Africa\"\n\n# Moving the continent column's position in the dataset to the second column\n\nhappy <- happy %>% select(Country,Continent, everything())\nhappy <- happy[!duplicated(happy), ]\n\n#Renaming the final dataframe to happy\nview(happy)\nhappy <- happy[-(48:110), ]\nstr(happy)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n'data.frame':\t136 obs. of  10 variables:\n $ Country          : chr  \"Afghanistan\" \"Algeria\" \"Argentina\" \"Armenia\" ...\n $ Continent        : chr  \"Asia\" \"Africa\" \"South America\" \"Asia\" ...\n $ ISO-code         : chr  \"AFG\" \"DZA\" \"ARG\" \"ARM\" ...\n $ GDP.per.capita   : num  2182 16091 19971 11845 54799 ...\n $ urbanization.rate: num  26 73.7 92.1 63.3 86.2 58.7 56.4 89.5 38.2 79.5 ...\n $ Population.growth: num  2.41 1.89 0.88 0.17 1.6 0.46 1.35 1.92 1.19 -0.1 ...\n $ Life.expectancy  : num  64.5 76.7 76.5 74.9 83.3 81.4 72.9 77.2 72.3 74.6 ...\n $ Suicide.rate     : num  6.4 3.3 9.1 5.7 11.7 11.4 2.6 5.7 6.1 21.4 ...\n $ Sex.ratio        : num  1.03 1.03 0.98 0.95 0.99 0.96 0.98 1.53 0.97 0.87 ...\n $ Happiness        : num  2.52 4.89 5.93 5.28 7.18 ...\n```\n:::\n:::\n\n\nThe final data set \"happy\" consists of 12 variables and 136 observations. We can start the analysis now.\n\n# Exploratory Data Analysis\n\n## Understanding the correlation between happiness scores and other variables.\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Create a correlation plot\nggcorr(happy, label = TRUE, label_round = 2, label_size = 3.5, size = 4, hjust = .85) +\n  ggtitle(\"Plot- 1: Correlation Heatmap\") +\n  theme(plot.title = element_text(hjust = 0.5))\n```\n\n::: {.cell-output .cell-output-stderr}\n```\nWarning in ggcorr(happy, label = TRUE, label_round = 2, label_size = 3.5, : data\nin column(s) 'Country', 'Continent', 'ISO-code' are not numeric and were ignored\n```\n:::\n\n::: {.cell-output-display}\n![](Final-Project_World-Happiness_files/figure-html/unnamed-chunk-4-1.png){width=672}\n:::\n:::\n\n\nObservations from the correlation plot:\n\nThe happiness score is,\n\n-   Strongly correlating with GDP per capita, Urbanization rate and Life expectancy.\n\n-   Inversely correlated with suicidal rate and population growth.\n\n-   No correlation with sex ratio.\n\n\n::: {.cell}\n\n```{.r .cell-code}\n#plotting the happiness data on world map\n\nplot_2 <- select(happy, \"Continent\", \"Country\", \"Happiness\")\n\nlibrary(maps)\n```\n\n::: {.cell-output .cell-output-stderr}\n```\n\nAttaching package: 'maps'\n```\n:::\n\n::: {.cell-output .cell-output-stderr}\n```\nThe following object is masked from 'package:purrr':\n\n    map\n```\n:::\n\n```{.r .cell-code}\nworld.data <- map_data(\"world\")\nmap.world_joined <- left_join(world.data, plot_2, by = c('region'='Country'))\n\nmap1 <- ggplot(map.world_joined, aes(x=long, y=lat, group=group)) +\n  geom_polygon(aes(fill=Happiness), color=\"black\")\n\nmap2 <- map1 + scale_fill_gradient(name = \"Happiness Score\", low = \"yellow\", high = \"red\", na.value = \"grey50\") +\n  theme(axis.text.x = element_blank(), \n        axis.text.y = element_blank(),\n        axis.ticks = element_blank(),\n        axis.title.y = element_blank(),\n        axis.title.x = element_blank(),\n        rect = element_blank())\nmap2\n```\n\n::: {.cell-output-display}\n![](Final-Project_World-Happiness_files/figure-html/unnamed-chunk-5-1.png){width=672}\n:::\n:::\n\n\nNorth America, Europe and Australia appear to be the happiest.\n\nSouth America, North Asia, Western Africa and countries/islands in the indian ocean appear to be happy on average.\n\nSouth Africa, India are unhappy and of course Afghanistan is the unhappiest country in the world.\n\n### Happiness score comparison on different continents\n\n\n::: {.cell}\n\n```{.r .cell-code}\n####### Happiness score for each continent\n\ngg1 <- ggplot(happy,\n              aes(x=Continent,\n                  y=Happiness,\n                  color=Continent))+\n  geom_point() + theme_bw() +\n  theme(axis.title = element_text(family = \"Helvetica\", size = (8)))\n\ngg2 <- ggplot(happy , aes(x = Continent, y = Happiness)) +\n  geom_boxplot(aes(fill=Continent)) + theme_bw() +\n  theme(axis.title = element_text(family = \"Helvetica\", size = (8)))\n\ngg3 <- ggplot(happy,aes(x=Continent,y=Happiness))+\n  geom_violin(aes(fill=Continent),alpha=0.7)+ theme_bw() +\n  theme(axis.title = element_text(family = \"Helvetica\", size = (8)))\n\n# Compute descriptive statistics by groups\nstable <- desc_statby(happy, measure.var = \"Happiness\",\n                      grps = \"Continent\")\nstable <- stable[, c(\"Continent\",\"mean\",\"median\")]\nnames(stable) <- c(\"Continent\", \"Mean of happiness score\",\"Median of happiness score\")\n# Summary table plot\nstable.p <- ggtexttable(stable,rows = NULL, \n                         theme = ttheme(\"classic\"))\n\n\nggarrange(gg1, gg2, ncol = 1, nrow = 2)\n```\n\n::: {.cell-output-display}\n![](Final-Project_World-Happiness_files/figure-html/unnamed-chunk-6-1.png){width=672}\n:::\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\nggarrange(gg3, stable.p, ncol = 1, nrow = 2)\n```\n\n::: {.cell-output-display}\n![](Final-Project_World-Happiness_files/figure-html/unnamed-chunk-7-1.png){width=672}\n:::\n:::\n\n\nAs we have seen before, Australia has the highest median happiness score. Europe, South America, and North America are in the second place regarding median happiness score. Asia has the lowest median after Africa. We can see the range of happiness score for different continents, and also the concentration of happiness score.\n\nLet's see the correlation between happiness score and 3 major factors in the happiness data set that are GDP per capita, Life Expectancy, Urbanization rate to understand how they are varying.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nggplot(subset(happy, happy$Continent != \"Australia\"), aes(x =  GDP.per.capita, y = Happiness)) + \n  geom_point(aes(color=Continent), size = 3, alpha = 0.8) +  \n  geom_smooth(aes(color = Continent, fill = Continent), \n              method = \"lm\", fullrange = TRUE) +\n  facet_wrap(~Continent) +\n  theme_bw() + labs(title = \"Scatter plot with regression line Happiness vs GDP per capita\")\n```\n\n::: {.cell-output .cell-output-stderr}\n```\n`geom_smooth()` using formula = 'y ~ x'\n```\n:::\n\n::: {.cell-output-display}\n![](Final-Project_World-Happiness_files/figure-html/unnamed-chunk-8-1.png){width=672}\n:::\n:::\n\n\nThe correlation between GDP per capita and happiness score in Europe, North America, and Asia is more significant than the other continents. Worth mentioning that we will not take Australia into account because there are just two countries in Australia and creating scatter plot with the regression line for this continent will not give us any insight.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nggplot(subset(happy, happy$Continent != \"Australia\"), aes(x =  urbanization.rate, y = Happiness)) + \n  geom_point(aes(color=Continent), size = 3, alpha = 0.8) +  \n  geom_smooth(aes(color = Continent, fill = Continent), \n              method = \"lm\", fullrange = TRUE) +\n  facet_wrap(~Continent) +\n  theme_bw() + labs(title = \"Scatter plot with regression line Happiness vs Urbanization rate\")\n```\n\n::: {.cell-output .cell-output-stderr}\n```\n`geom_smooth()` using formula = 'y ~ x'\n```\n:::\n\n::: {.cell-output-display}\n![](Final-Project_World-Happiness_files/figure-html/unnamed-chunk-9-1.png){width=672}\n:::\n:::\n\n\nThe relationship between happiness score and urbanization rate is very significant in Asia, Africa and Europe followed by North america and south america.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nggplot(subset(happy, happy$Continent != \"Australia\"), aes(x =  Life.expectancy, y = Happiness)) + \n  geom_point(aes(color=Continent), size = 3, alpha = 0.8) +  \n  geom_smooth(aes(color = Continent, fill = Continent), \n              method = \"lm\", fullrange = TRUE) +\n  facet_wrap(~Continent) +\n  theme_bw() + labs(title = \"Scatter plot with regression line Happiness vs Life Expectancy\")\n```\n\n::: {.cell-output .cell-output-stderr}\n```\n`geom_smooth()` using formula = 'y ~ x'\n```\n:::\n\n::: {.cell-output-display}\n![](Final-Project_World-Happiness_files/figure-html/unnamed-chunk-10-1.png){width=672}\n:::\n:::\n\n\nThe relationship between happiness score and life expectancy is very significant in Asia, Europe and Africa followed by North america and south america.\n\n## Modeling & Hypothesis testing\n\nFrom the above visualizations and analysis, we have found that GDP per capita, Urbanization and Life Expectancy play major role in the happiness score. Whereas suicide rate and population growth has an inverse relationship. Let's build a model for estimating happiness scores based on these control variables and see which of these has effect on the overall happiness scores.\n\n### Model-1\n\n\n::: {.cell}\n\n```{.r .cell-code}\n#Model-1\nmodel1 <- lm(Happiness ~ GDP.per.capita + urbanization.rate + Life.expectancy, data = happy)\nsummary(model1)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n\nCall:\nlm(formula = Happiness ~ GDP.per.capita + urbanization.rate + \n    Life.expectancy, data = happy)\n\nResiduals:\n     Min       1Q   Median       3Q      Max \n-1.89896 -0.37351  0.07498  0.48488  1.15628 \n\nCoefficients:\n                   Estimate Std. Error t value Pr(>|t|)    \n(Intercept)       4.510e-01  7.280e-01   0.620   0.5366    \nGDP.per.capita    1.790e-05  3.867e-06   4.628 8.72e-06 ***\nurbanization.rate 6.992e-03  3.646e-03   1.918   0.0573 .  \nLife.expectancy   5.814e-02  1.156e-02   5.030 1.57e-06 ***\n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n\nResidual standard error: 0.6355 on 132 degrees of freedom\nMultiple R-squared:  0.6693,\tAdjusted R-squared:  0.6618 \nF-statistic: 89.07 on 3 and 132 DF,  p-value: < 2.2e-16\n```\n:::\n:::\n\n\nIt can be seen that p-value of the F-statistic is \\< 2.2e-16, which is highly significant. This means that, at least, one of the predictor/control variables ( GDP per capita, Urbanization rare and Life Expectancy) is significantly related to the outcome variable (Happiness score).\n\nIt can be seen that, changing in GDP per capita and Life expectancy are significantly associated to changes in happiness scores while changes in urbanization rate is not significantly associated with sales.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nsummary(model1)$coefficient\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n                      Estimate   Std. Error   t value     Pr(>|t|)\n(Intercept)       4.510470e-01 7.280370e-01 0.6195386 5.366295e-01\nGDP.per.capita    1.789683e-05 3.867139e-06 4.6279250 8.717287e-06\nurbanization.rate 6.992347e-03 3.645755e-03 1.9179423 5.727811e-02\nLife.expectancy   5.814042e-02 1.155817e-02 5.0302459 1.567648e-06\n```\n:::\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\nconfint(model1)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n                          2.5 %       97.5 %\n(Intercept)       -9.890821e-01 1.891176e+00\nGDP.per.capita     1.024724e-05 2.554641e-05\nurbanization.rate -2.193158e-04 1.420401e-02\nLife.expectancy    3.527723e-02 8.100362e-02\n```\n:::\n:::\n\n\nLets see how this model behaves if we apply log on the variables\n\n\n::: {.cell}\n\n```{.r .cell-code}\n#Model-1 with log\nmodel1_log <- lm(Happiness ~ log(GDP.per.capita + urbanization.rate + Life.expectancy), data = happy)\nsummary(model1_log)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n\nCall:\nlm(formula = Happiness ~ log(GDP.per.capita + urbanization.rate + \n    Life.expectancy), data = happy)\n\nResiduals:\n     Min       1Q   Median       3Q      Max \n-2.32889 -0.48506  0.05291  0.51078  1.36460 \n\nCoefficients:\n                                                          Estimate Std. Error\n(Intercept)                                               -1.66107    0.49628\nlog(GDP.per.capita + urbanization.rate + Life.expectancy)  0.75478    0.05177\n                                                          t value Pr(>|t|)    \n(Intercept)                                                -3.347  0.00106 ** \nlog(GDP.per.capita + urbanization.rate + Life.expectancy)  14.581  < 2e-16 ***\n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n\nResidual standard error: 0.682 on 134 degrees of freedom\nMultiple R-squared:  0.6134,\tAdjusted R-squared:  0.6105 \nF-statistic: 212.6 on 1 and 134 DF,  p-value: < 2.2e-16\n```\n:::\n:::\n\n\nThe R-Squared value drops from 0.6693 to 0.6134 by applying log for model-1.\n\n### Model-2\n\n\n::: {.cell}\n\n```{.r .cell-code}\n#Model-2\nmodel2  <- lm(Happiness ~ GDP.per.capita + Life.expectancy, data = happy)\nsummary(model2)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n\nCall:\nlm(formula = Happiness ~ GDP.per.capita + Life.expectancy, data = happy)\n\nResiduals:\n     Min       1Q   Median       3Q      Max \n-2.01976 -0.39026  0.09436  0.49252  1.18774 \n\nCoefficients:\n                 Estimate Std. Error t value Pr(>|t|)    \n(Intercept)     1.683e-01  7.201e-01   0.234    0.816    \nGDP.per.capita  2.028e-05  3.699e-06   5.481 2.05e-07 ***\nLife.expectancy 6.713e-02  1.067e-02   6.292 4.20e-09 ***\n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n\nResidual standard error: 0.6418 on 133 degrees of freedom\nMultiple R-squared:  0.6601,\tAdjusted R-squared:  0.655 \nF-statistic: 129.2 on 2 and 133 DF,  p-value: < 2.2e-16\n```\n:::\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\nsummary(model2)$coefficient\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n                    Estimate   Std. Error   t value     Pr(>|t|)\n(Intercept)     1.683136e-01 7.200997e-01 0.2337366 8.155489e-01\nGDP.per.capita  2.027701e-05 3.699299e-06 5.4813121 2.046209e-07\nLife.expectancy 6.713497e-02 1.066984e-02 6.2920307 4.201007e-09\n```\n:::\n:::\n\n\nIt turns out Life Expectancy is strongly associated with happiness scores and GDP per capita follows life expectancy.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nconfint(model2)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n                        2.5 %       97.5 %\n(Intercept)     -1.256016e+00 1.592643e+00\nGDP.per.capita   1.295994e-05 2.759408e-05\nLife.expectancy  4.603044e-02 8.823951e-02\n```\n:::\n:::\n\n\nHowever the R-squared values of Model-1 and Model-2 are approximately around 65-66%. Hence we cannot say which model is best fit to predict the happiness scores.\n\nLets consider all the 5 control variables and see the results.\n\nLets see how model-2 behaves if we apply log on the variables\n\n\n::: {.cell}\n\n```{.r .cell-code}\n#Model-2 with log\nmodel2_log  <- lm(Happiness ~ log(GDP.per.capita + Life.expectancy), data = happy)\nsummary(model2_log)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n\nCall:\nlm(formula = Happiness ~ log(GDP.per.capita + Life.expectancy), \n    data = happy)\n\nResiduals:\n     Min       1Q   Median       3Q      Max \n-2.32936 -0.47756  0.04899  0.51212  1.36194 \n\nCoefficients:\n                                      Estimate Std. Error t value Pr(>|t|)    \n(Intercept)                           -1.62336    0.49427  -3.284   0.0013 ** \nlog(GDP.per.capita + Life.expectancy)  0.75129    0.05158  14.565   <2e-16 ***\n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n\nResidual standard error: 0.6824 on 134 degrees of freedom\nMultiple R-squared:  0.6129,\tAdjusted R-squared:   0.61 \nF-statistic: 212.1 on 1 and 134 DF,  p-value: < 2.2e-16\n```\n:::\n:::\n\n\nThe R-Squared value drops from 0.66 to 0.61 by applying log for model-2.\n\n### Model-3\n\n\n::: {.cell}\n\n```{.r .cell-code}\n#Model-3\nmodel3 <- lm(Happiness ~ GDP.per.capita + urbanization.rate + Life.expectancy + Suicide.rate + Population.growth , data = happy)\nsummary(model3)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n\nCall:\nlm(formula = Happiness ~ GDP.per.capita + urbanization.rate + \n    Life.expectancy + Suicide.rate + Population.growth, data = happy)\n\nResiduals:\n     Min       1Q   Median       3Q      Max \n-1.87156 -0.39252  0.05248  0.45831  1.25675 \n\nCoefficients:\n                    Estimate Std. Error t value Pr(>|t|)    \n(Intercept)       -2.712e-02  1.268e+00  -0.021 0.982977    \nGDP.per.capita     1.646e-05  4.281e-06   3.845 0.000188 ***\nurbanization.rate  6.826e-03  3.647e-03   1.872 0.063456 .  \nLife.expectancy    6.341e-02  1.667e-02   3.804 0.000218 ***\nSuicide.rate       1.586e-02  1.317e-02   1.204 0.230615    \nPopulation.growth -1.622e-02  7.576e-02  -0.214 0.830844    \n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n\nResidual standard error: 0.6348 on 130 degrees of freedom\nMultiple R-squared:  0.6751,\tAdjusted R-squared:  0.6626 \nF-statistic: 54.01 on 5 and 130 DF,  p-value: < 2.2e-16\n```\n:::\n:::\n\n\nThe R-squared remains same after adding additional two control variables. So far, the second model fits the happiness scores.\n\nLets see how model-3 behaves if we apply log on the control variables\n\n\n::: {.cell}\n\n```{.r .cell-code}\n#Model-3 with log\nmodel3_log <- lm(Happiness ~ log(GDP.per.capita + urbanization.rate + Life.expectancy + Suicide.rate + Population.growth) , data = happy)\nsummary(model3_log)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n\nCall:\nlm(formula = Happiness ~ log(GDP.per.capita + urbanization.rate + \n    Life.expectancy + Suicide.rate + Population.growth), data = happy)\n\nResiduals:\n     Min       1Q   Median       3Q      Max \n-2.32855 -0.48525  0.05338  0.51003  1.36226 \n\nCoefficients:\n                                                                                             Estimate\n(Intercept)                                                                                  -1.67866\nlog(GDP.per.capita + urbanization.rate + Life.expectancy + Suicide.rate + Population.growth)  0.75648\n                                                                                             Std. Error\n(Intercept)                                                                                     0.49727\nlog(GDP.per.capita + urbanization.rate + Life.expectancy + Suicide.rate + Population.growth)    0.05186\n                                                                                             t value\n(Intercept)                                                                                   -3.376\nlog(GDP.per.capita + urbanization.rate + Life.expectancy + Suicide.rate + Population.growth)  14.587\n                                                                                             Pr(>|t|)\n(Intercept)                                                                                  0.000963\nlog(GDP.per.capita + urbanization.rate + Life.expectancy + Suicide.rate + Population.growth)  < 2e-16\n                                                                                                \n(Intercept)                                                                                  ***\nlog(GDP.per.capita + urbanization.rate + Life.expectancy + Suicide.rate + Population.growth) ***\n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n\nResidual standard error: 0.6818 on 134 degrees of freedom\nMultiple R-squared:  0.6136,\tAdjusted R-squared:  0.6107 \nF-statistic: 212.8 on 1 and 134 DF,  p-value: < 2.2e-16\n```\n:::\n:::\n\n\nThe R-squared values drops from 0.66 to 0.61 by application of log.\n\n## Model comprision\n\n+-----------------------------------------------------------------------------------------------------+---------------------+--------------------+-----------------------------------+\n| Models                                                                                              | Multiple R-squared  | Adjusted R-squared | Significant Variables             |\n+=====================================================================================================+=====================+====================+===================================+\n| Model-1 (GDP per capita+Urbanization rate+Life expectancy)                                          | 0.6693              | 0.6618             | GDP per capita & Life Expectancy  |\n+-----------------------------------------------------------------------------------------------------+---------------------+--------------------+-----------------------------------+\n| Model-1 (Log(GDP per capita+Urbanization rate+Life expectancy))                                     | 0.6134              | 0.6105             | \\-                                |\n+-----------------------------------------------------------------------------------------------------+---------------------+--------------------+-----------------------------------+\n| Model-2 (GDP per capita+Life expectancy)                                                            | 0.6601              | 0.655              | GDP per capita & Life Expectancy. |\n|                                                                                                     |                     |                    |                                   |\n|                                                                                                     |                     |                    | Life expectancy \\> GDP per capita |\n+-----------------------------------------------------------------------------------------------------+---------------------+--------------------+-----------------------------------+\n| Model-2 (Log(GDP per capita+Life expectancy))                                                       | 0.6129              | 0.61               | \\-                                |\n+-----------------------------------------------------------------------------------------------------+---------------------+--------------------+-----------------------------------+\n| Model-3 (GDP per capita+Urbanization rate +Life expectancy + Suicide rate + population growth)      | 0.6601              | 0.655              | GDP per capita & Life Expectancy  |\n+-----------------------------------------------------------------------------------------------------+---------------------+--------------------+-----------------------------------+\n| Model-3 (Log(GDP per capita+Urbanization rate +Life expectancy + Suicide rate + population growth)) | 0.6136              | 0.6107             | GDP per capita & Life Expectancy. |\n|                                                                                                     |                     |                    |                                   |\n|                                                                                                     |                     |                    | Life expectancy \\> GDP per capita |\n+-----------------------------------------------------------------------------------------------------+---------------------+--------------------+-----------------------------------+\n\n-   It can be derived from the above table that the adjusted R-Squared for Model-2 is better than other two models, hence it can be said that Model-2 is a good fit.\n\n-   Application of Logarithm on the control variables reduced the R-squared values in all the 3 models.\n\n-   **Hypothesis testing conclusion:**\n\n    Turns out we have evidence for all the 3 hypothesis but,\n\n    -   We have a strong evidence for hypothesis-3 i.e. Higher Life Expectancy leads to country's happiness.\n\n\\-\\-\\-\\-\\--\n\nAs we have concluded that Model-2 is a goof fit, Lets divide the happy dataset into training and test and plot the predicted happiness scores for Model-2.\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Splitting the dataset into the Training set and Test set\nset.seed(123)\ndataset <- happy[4:10]\nsplit = sample.split(dataset$Happiness, SplitRatio = 0.8)\ntraining_set = subset(dataset, split == TRUE)\ntest_set = subset(dataset, split == FALSE)\n```\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\n# Fitting Multiple Linear Regression to the Training set on Model-2\nregressor_lm = lm(formula = Happiness ~ GDP.per.capita + Life.expectancy,\n               data = training_set)\n\nsummary(regressor_lm)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n\nCall:\nlm(formula = Happiness ~ GDP.per.capita + Life.expectancy, data = training_set)\n\nResiduals:\n    Min      1Q  Median      3Q     Max \n-1.9617 -0.4055  0.0248  0.4922  1.1547 \n\nCoefficients:\n                  Estimate Std. Error t value Pr(>|t|)    \n(Intercept)     -6.041e-02  7.946e-01  -0.076     0.94    \nGDP.per.capita   2.117e-05  4.330e-06   4.889 3.65e-06 ***\nLife.expectancy  6.975e-02  1.184e-02   5.892 4.65e-08 ***\n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n\nResidual standard error: 0.6397 on 105 degrees of freedom\nMultiple R-squared:  0.6834,\tAdjusted R-squared:  0.6774 \nF-statistic: 113.3 on 2 and 105 DF,  p-value: < 2.2e-16\n```\n:::\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\ny_pred_lm = predict(regressor_lm, newdata = test_set)\n\nPred_Actual_lm <- as.data.frame(cbind(Prediction = y_pred_lm, Actual = test_set$Happiness))\n\ngg.lm <- ggplot(Pred_Actual_lm, aes(Actual, Prediction )) +\n  geom_point() + theme_bw() + geom_abline() +\n  labs(title = \"Multiple Linear Regression\", x = \"Actual happiness score\",\n       y = \"Predicted happiness score\") +\n  theme(plot.title = element_text(family = \"Helvetica\", face = \"bold\", size = (15)), \n        axis.title = element_text(family = \"Helvetica\", size = (10)))\ngg.lm\n```\n\n::: {.cell-output-display}\n![](Final-Project_World-Happiness_files/figure-html/unnamed-chunk-23-1.png){width=672}\n:::\n:::\n\n\n**The Model shows 67% accuracy on the test data.**\n\n## Regression Diagnostics\n\n### Model-1\n\n\n::: {.cell}\n\n```{.r .cell-code}\n#Model-1\npar(mfrow = c(2,3)); plot(model1, which = 1:6)\n```\n\n::: {.cell-output-display}\n![](Final-Project_World-Happiness_files/figure-html/unnamed-chunk-24-1.png){width=672}\n:::\n:::\n\n\n**Model-1 Diagnostics:**\n\nResiduals vs Fitted: The Linearity assumption is met and there is a constant variance of residuals along the line. Overall the plot looks good.\n\nNormal Q-Q: The points are falling along the theoretical quantiles, hence the normality assumption is met.\n\nScale-Location: The line is approximately horizontal, so I can say that the constant variance assumption is met.\n\nCook's distance: No observation is greater than 1. The maximum cook's distance is \\<0.3. 174th observation is the influential.\n\nResiduals vs Leverage: No observations are beyond the cook's distance and the leverage is low.\n\nBut the influential observation 174 is not at the same place in all graphs which is odd.\n\n### Model-2\n\n\n::: {.cell}\n\n```{.r .cell-code}\n#Model-2\npar(mfrow = c(2,3)); plot(model2, which = 1:6)\n```\n\n::: {.cell-output-display}\n![](Final-Project_World-Happiness_files/figure-html/unnamed-chunk-25-1.png){width=672}\n:::\n:::\n\n\n**Model-2 Diagnostics:**\n\nResiduals vs Fitted: I would say the linearity assumption is violated here but the constant variance of residuals is present.\n\nNormal Q-Q: The points are falling along the theoretical quantiles, hence the normality assumption is met.\n\nScale-Location: Compared to model-1, the line is almost horizontal. This one looks good.\n\nCook's distance: No observation is greater than 1. The maximum cook's distance is 0.9 (approximately). The 156th observation is very influential.\n\nResiduals vs Leverage: No observations are beyond the cook's distance and the leverage is high as compared to model-1 which is good.\n\n**I can say that the regression diagnostics of Model-2 look much better than Model-1 because of the larger cook's distance and leverage.**\n\n### Model-3\n\n\n::: {.cell}\n\n```{.r .cell-code}\n#Model-3\npar(mfrow = c(2,3)); plot(model3, which = 1:6)\n```\n\n::: {.cell-output-display}\n![](Final-Project_World-Happiness_files/figure-html/unnamed-chunk-26-1.png){width=672}\n:::\n:::\n\n\nResiduals vs Fitted: The Linearity assumption is met and there is a constant variance of residuals along the line. Overall the plot looks good.\n\nNormal Q-Q: The points are falling along the theoretical quantiles, hence the normality assumption is met.\n\nScale-Location: Compared to model-1 & 2, the line is not horizontal.\n\nCook's distance: No observation is greater than 1. The maximum cook's distance is \\< 0.3 (approximately). Again as similar to model-1, the 174th observation is very influential.\n\nResiduals vs Leverage: No observations are beyond the cook's distance and the leverage is low.\n\nBut the influential observation 174 is not at the same place in all graphs which is odd.\n\n## Conclusion\n\nThe aim of this study is to find out which factors significantly effect world happiness scores and to find out a model that fits/predicts the happiness scores. The following is the summary of this study.\n\n-   GDP per capita, Urbanization rate and Life expectancy are the factors that are significantly associated with Happiness scores.\n\n-   North America, Europe and Australia appear to be the happiest.\n\n-   South America, North Asia, Western Africa and countries/islands in the indian ocean appear to be happy on average.\n\n-   South Africa, India are unhappy and of course Afghanistan is the unhappiest country in the world.\n\n-   Australia has the highest median happiness score. Europe, South America, and North America are in the second place regarding median happiness score. Asia has the lowest median after Africa. We can see the range of happiness score for different continents, and also the concentration of happiness score.\n\n-   The correlation between GDP per capita and happiness score in Europe, North America, and Asia is more significant than the other continents.\n\n-   The relationship between happiness score and urbanization rate is very significant in Asia, Africa and Europe followed by North america and south america.\n\n-   The relationship between happiness score and life expectancy is very significant in Asia, Europe and Africa followed by North america and south america.\n\nWhen it comes to modeling and hypothesis testing,\n\n-   Model-1 concluded that GDP per capita and Life Expectancy are strongly associated with the happiness scores.\n\n-   Model-2 concluded that Life Expectancy is more strongly associated with the happiness scores, giving evidence to the third hypothesis.\n\n-   Regression diagnostics of model-2 showed larger cook distance and leverage.\n\n## References\n\n1.  <https://www.kaggle.com/code/noobiedatascientist/explaining-happiness/data>\n\n2.  <https://worldhappiness.report/ed/2021/>\n\n3.  <http://www.sthda.com/english/articles/40-regression-analysis/168-multiple-linear-regression-in-r/#building-model>\n\n4.  [https://www.guru99.com/r-simple-multiple-linear-regression.html](https://www.guru99.com/r-simple-multiple-linear-regression.htmlhttps://www.guru99.com/r-simple-multiple-linear-regression.html)\n",
    "supporting": [
      "Final-Project_World-Happiness_files"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {
      "include-in-header": [
        "<link href=\"../site_libs/pagedtable-1.1/css/pagedtable.css\" rel=\"stylesheet\" />\r\n<script src=\"../site_libs/pagedtable-1.1/js/pagedtable.js\"></script>\r\n"
      ]
    },
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}