{
  "hash": "2a914423e2c8e4db467b8f0340984fd8",
  "result": {
    "markdown": "---\ntitle: \"Homework 2\"\nauthor: \"Roy Yoon\"\ndesription: \"DACSS 603 Home Work 2\"\ndate: \"10/18/2022\"\nformat:\n  html:\n    toc: true\n    code-fold: true\n    code-copy: true\n    code-tools: true\ncategories:\n  - hw2\n  - Roy Yoon\n  - dataset\n  - ggplot2\n---\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(tidyverse)\n\nknitr::opts_chunk$set(echo = TRUE)\n```\n:::\n\n\n# Question 1\n\nConstruct the 90% confidence interval to estimate the actual mean wait time for each of the two procedures. Is the confidence interval narrower for angiography or bypass surgery?\n\n## Bypass Sample Size, Mean Wait Time, Standard Deviation\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Bypass information\nbypass_sample_size <- 539\nbypass_mean <- 19\nbypass_sd <- 10\n```\n:::\n\n\n## Standard Error for Bypass\n\n\n::: {.cell}\n\n```{.r .cell-code}\nbypass_standard_error <- bypass_sd / sqrt(bypass_sample_size)\n\nbypass_standard_error\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 0.4307305\n```\n:::\n:::\n\n\n## T-Value Steps for Bypass\n\n\n::: {.cell}\n\n```{.r .cell-code}\nbypass_confidence_level <- 0.90\nbypass_tail_area <- (1 - bypass_confidence_level)/2\n\nbypass_tail_area\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 0.05\n```\n:::\n\n```{.r .cell-code}\nbypass_t_score <- qt(p = 1 - bypass_tail_area, df = bypass_sample_size - 1)\n\nbypass_t_score\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 1.647691\n```\n:::\n:::\n\n\n## Calculate Bypass Confidence Interval\n\n\n::: {.cell}\n\n```{.r .cell-code}\nbypass_confidence_interval <- c(bypass_mean - (bypass_t_score * bypass_standard_error),\n                                bypass_mean + (bypass_t_score * bypass_standard_error))\n\nbypass_confidence_interval\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 18.29029 19.70971\n```\n:::\n:::\n\n\n## Margin of Error for bypass\n\n\n::: {.cell}\n\n```{.r .cell-code}\nbypass_margin_of_error <- bypass_t_score * bypass_standard_error\n\nbypass_margin_of_error\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 0.7097107\n```\n:::\n:::\n\n\n## Angiography Sample Size, Mean Wait Time, Standard Deviation\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Bypass information\nangiography_sample_size <- 847\nangiography_mean <- 18\nangiography_sd <- 9\n```\n:::\n\n\n## Standard Error for Angiography\n\n\n::: {.cell}\n\n```{.r .cell-code}\nangiography_standard_error <- angiography_sd / sqrt(angiography_sample_size)\n\nangiography_standard_error\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 0.3092437\n```\n:::\n:::\n\n\n## T-Value Steps for Angiography\n\n\n::: {.cell}\n\n```{.r .cell-code}\nangiography_confidence_level <- 0.90\nangiography_tail_area <- (1 - angiography_confidence_level)/2\n\nangiography_tail_area\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 0.05\n```\n:::\n\n```{.r .cell-code}\nangiography_t_score <- qt(p = 1 - angiography_tail_area, df = angiography_sample_size - 1)\n\nangiography_t_score\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 1.646657\n```\n:::\n:::\n\n\n## Calculate Angiography Confidence Interval\n\n\n::: {.cell}\n\n```{.r .cell-code}\nangiography_confidence_interval <- c(angiography_mean - (angiography_t_score * angiography_standard_error),\n                                angiography_mean + (angiography_t_score * angiography_standard_error))\n\nangiography_confidence_interval\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 17.49078 18.50922\n```\n:::\n:::\n\n\n## Margin of Error for Angiography\n\n\n::: {.cell}\n\n```{.r .cell-code}\nangiography_margin_of_error <- angiography_t_score * angiography_standard_error\n\nangiography_margin_of_error\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 0.5092182\n```\n:::\n:::\n\n\n## Comparing Bypass and Angiogrpahy Confidence Intervals\n\n\n::: {.cell}\n\n```{.r .cell-code}\nangiography_confidence_interval\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 17.49078 18.50922\n```\n:::\n\n```{.r .cell-code}\n18.50922 - 17.49078\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 1.01844\n```\n:::\n\n```{.r .cell-code}\nbypass_confidence_interval\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 18.29029 19.70971\n```\n:::\n\n```{.r .cell-code}\n19.70971 - 18.29029\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 1.41942\n```\n:::\n:::\n\n\nAngiography has a more narrow confidence interval\n\n# Question 2\n\nA survey of 1031 adult Americans was carried out by the National Center for Public Policy. Assume that the sample is representative of adult Americans. Among those surveyed, 567 believed that college education is essential for success. Find the point estimate, p, of the proportion of all adult Americans who believe that a college education is essential for success. Construct and interpret a 95% confidence interval for p.\n\n## Point Estimate\n\n\n::: {.cell}\n\n```{.r .cell-code}\nsample_size <- 1031\n\neducation_essential <- 567\n\npoint_estimate <- education_essential / sample_size\n\npoint_estimate \n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 0.5499515\n```\n:::\n\n```{.r .cell-code}\nprop.test(education_essential, sample_size)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n\n\t1-sample proportions test with continuity correction\n\ndata:  education_essential out of sample_size, null probability 0.5\nX-squared = 10.091, df = 1, p-value = 0.00149\nalternative hypothesis: true p is not equal to 0.5\n95 percent confidence interval:\n 0.5189682 0.5805580\nsample estimates:\n        p \n0.5499515 \n```\n:::\n:::\n\n\nThe point estimate for adult Americans who believe college education is essential is 0.5499515. The 95 percent confidence interval is 0.5189682, 0.5805580. 95% of confidence intervals calculated with this procedure would contain the true mean. With the sampling method repeated, about 95% of the intervals would contain the true mean.\n\n# Question 3\n\nSuppose that the financial aid office of UMass Amherst seeks to estimate the mean cost of textbooks per semester for students. The estimate will be useful if it is within \\$5 of the true population mean (i.e. they want the confidence interval to have a length of \\$10 or less). The financial aid office is pretty sure that the amount spent on books varies widely, with most values between \\$30 and \\$200. They think that the population standard deviation is about a quarter of this range (in other words, you can assume they know the population standard deviation). Assuming the significance level to be 5%, what should be the size of the sample?\n\n\n::: {.cell}\n\n```{.r .cell-code}\nstandard_dev <- (200 - 30)/4\nstandard_dev\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 42.5\n```\n:::\n:::\n\n\nThe standard deviation from the data is 42.5. Now knowing the standard deviation we can look for the size of the sample by ways of the confidence interval.\n\nSolving for n, by ways of confidence interval.\n\n1.  5 = 1.96(42.5/sqrt(n))\n\n2.  5 = 83.3/sqrt(n)\n\n3.  5 \\* sqrt(n) = 83.3\n\n4.  sqrt(n) = 83.3 / 5\n\n5.  n = (83.3/5)\\^2\n\n6.  n = 278. 89\n\n# Question 4\n\nAccording to a union agreement, the mean income for all senior-level workers in a large service company equals \\$500 per week. A representative of a women's group decides to analyze whether the mean income μ for female employees matches this norm. For a random sample of nine female employees, ȳ = \\$410 and s = 90.\n\n## A.\n\nTest whether the mean income of female employees differs from \\$500 per week. Include assumptions, hypotheses, test statistic, and P-value. Interpret the result.\n\nAssumptions:\n\n-   Data is normally distributed; significance level is 5%\n\n-   Null Hypothesis (H0): μ = 500\n\n-   Alternative Hypothesis(H1): μ \\< 500, μ \\> 500\n\n## A: Standard Error\n\n\n::: {.cell}\n\n```{.r .cell-code}\nfemale_standard_dev <- 90\nfemale_sample_size <- 9\nfemale_sample_mean <- 410 \nnull_hypothesis_mean <- 500\n\nfemale_standard_error <- female_standard_dev / sqrt(female_sample_size)\n\nfemale_standard_error\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 30\n```\n:::\n:::\n\n\n## A: t-test\n\n\n::: {.cell}\n\n```{.r .cell-code}\nt_stat <- (female_sample_mean - null_hypothesis_mean) / female_standard_error\n\nt_stat\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] -3\n```\n:::\n:::\n\n\n## A: p-value\n\n\n::: {.cell}\n\n```{.r .cell-code}\np_value <- (pt(t_stat, df = 8)) * 2\n\np_value\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 0.01707168\n```\n:::\n:::\n\n\np-value (0.01707168) is smaller than the 5% significance level, so we are able to reject the null hypothesis and favor the alternative hypothesis.\n\n## B. Report the P-value for Ha : μ \\< 500. Interpret.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlow_p_value <- (pt(t_stat, df = 8, lower.tail = TRUE))\nlow_p_value\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 0.008535841\n```\n:::\n:::\n\n\n## C. Report and interpret the P-value for H a: μ \\> 500. (Hint: The P-values for the two possible one-sided tests must sum to 1.)\n\n\n::: {.cell}\n\n```{.r .cell-code}\nup_p_value <- (pt(t_stat, df = 8, lower.tail = FALSE))\nup_p_value\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 0.9914642\n```\n:::\n\n```{.r .cell-code}\n#sanity check from hint: The P-values for the two possible one-sided tests must sum to 1\nlow_p_value + up_p_value\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 1\n```\n:::\n:::\n\n\n# Question 5\n\nJones and Smith separately conduct studies to test H0: μ = 500 against Ha : μ ≠ 500, each with n = 1000. Jones gets ȳ = 519.5, with se = 10.0. Smith gets ȳ = 519.7, with se = 10.0.\n\n\n::: {.cell}\n\n```{.r .cell-code}\njones_sample_mean <- 519.5\njones_standard_error <- 10\nsmith_sample_mean <- 519.7\nsmith_standard_error <- 10\nh0_mean <- 500\n```\n:::\n\n\n## A\n\nShow that t = 1.95 and P-value = 0.051 for Jones. Show that t = 1.97 and P-value = 0.049 for Smith.\n\n\n::: {.cell}\n\n```{.r .cell-code}\n#Jones\n\njones_t_stat <- (jones_sample_mean - h0_mean) / jones_standard_error\n\njones_t_stat\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 1.95\n```\n:::\n\n```{.r .cell-code}\njones_p_value <- (pt(jones_t_stat, df = 999, lower.tail=FALSE)) * 2\n\njones_p_value\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 0.05145555\n```\n:::\n\n```{.r .cell-code}\n#Smith\n\nsmith_t_stat <- (smith_sample_mean - h0_mean) / smith_standard_error\n\nsmith_t_stat\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 1.97\n```\n:::\n\n```{.r .cell-code}\nsmith_p_value <- (pt(smith_t_stat, df = 999, lower.tail=FALSE) ) * 2\n\nsmith_p_value\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 0.04911426\n```\n:::\n:::\n\n\n## B\n\nUsing α = 0.05, for each study indicate whether the result is \"statistically significant.\"\n\nif the p value is less than the significance level, the null hypothesis is rejected.\n\nsignificance level: α = 0.05\n\nJones p-value: 0.05145555; Jones p-value \\> significance level, so the study is not statistically significant\n\nsmith p-value: 0.04911426; Smith p-value \\< significance level, so the study is statistically significant\n\n## C\n\nUsing this example, explain the misleading aspects of reporting the result of a test as \"P ≤ 0.05\" versus \"P \\> 0.05,\" or as \"reject H0\" versus \"Do not reject H0 ,\" without reporting the actual P-value.\n\nIf the p value is less than the significance level, the null hypothesis is rejected and we can consider the finding/result statistically insignificant. So blanketing Jone's study as not statistically significant and and Smith's study as significant may make sense. However, when you look at the sample means from Jones and Smith, there is not an outstanding difference between them. By the way the mathematics of calculating the p-value worked out, it can seem as though there is a great difference between the numbers reported by Jones and Smith, when their reported numbers are actually very narrow to each other.\n\n## Question 6\n\nAre the taxes on gasoline very high in the United States? According to the American Petroleum Institute, the per gallon federal tax that was levied on gasoline was 18.4 cents per gallon. However, state and local taxes vary over the same period. The sample data of gasoline taxes for 18 large cities is given below in the variable called gas_taxes.\n\ngas_taxes \\<- c(51.27, 47.43, 38.89, 41.95, 28.61, 41.29, 52.19, 49.48, 35.02, 48.13, 39.28, 54.41, 41.66, 30.28, 18.49, 38.72, 33.41, 45.02)\n\nIs there enough evidence to conclude at a 95% confidence level that the average tax per gallon of gas in the US in 2005 was less than 45 cents? Explain.\n\n\n::: {.cell}\n\n```{.r .cell-code}\ngas_taxes <- c(51.27, 47.43, 38.89, 41.95, 28.61, 41.29, 52.19, 49.48, 35.02, 48.13, 39.28, 54.41, 41.66, 30.28, 18.49, 38.72, 33.41, 45.02)\n\nt.test(gas_taxes, mu = 45, alternative = 'less')\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n\n\tOne Sample t-test\n\ndata:  gas_taxes\nt = -1.8857, df = 17, p-value = 0.03827\nalternative hypothesis: true mean is less than 45\n95 percent confidence interval:\n     -Inf 44.67946\nsample estimates:\nmean of x \n 40.86278 \n```\n:::\n:::\n\n\nWith a sample mean of 40.86278 and a p-value of 0.03827 which is less than the assumes 0.05 significance level, the null hypothesis is rejected and the alternative hypothesis is favored.\n\nThus, there is enough evidence to conclude at a 95% confidence level that the average tax per gallon of gas in the US in 2005 was less than 45 cents.\n",
    "supporting": [],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}