{
  "hash": "3dccd31aee0abf33d9344c0aba443732",
  "result": {
    "markdown": "---\ntitle: \"Kimble HW 2\"\nauthor: \"Karen Kimble\"\ndesription: \"Homework 2 for DACSS 603\"\ndate: \"10/17/2022\"\nformat:\n  html:\n    toc: true\n    code-fold: true\n    code-copy: true\n    code-tools: true\ncategories:\n  - hw2\n  - karen\n---\n\n::: {.cell}\n\n```{.r .cell-code}\n# Setup\n\nlibrary(tidyverse)\n```\n\n::: {.cell-output .cell-output-stderr}\n```\n── Attaching packages ─────────────────────────────────────── tidyverse 1.3.2 ──\n✔ ggplot2 3.3.6      ✔ purrr   0.3.5 \n✔ tibble  3.1.8      ✔ dplyr   1.0.10\n✔ tidyr   1.2.1      ✔ stringr 1.4.1 \n✔ readr   2.1.3      ✔ forcats 0.5.2 \n── Conflicts ────────────────────────────────────────── tidyverse_conflicts() ──\n✖ dplyr::filter() masks stats::filter()\n✖ dplyr::lag()    masks stats::lag()\n```\n:::\n\n```{.r .cell-code}\nlibrary(stats)\nknitr::opts_chunk$set(echo = TRUE)\n```\n:::\n\n\n## Question 1\n\n### Angiography\n\n\n::: {.cell}\n\n```{.r .cell-code}\nconfidence_level <- 0.90\n\ntail_area <- (1-confidence_level)/2\n\nstandard_error <- 9 / sqrt(847)\n\nt_score <- qt(p = 1-tail_area, df = 846)\n\nCI_1 <- c(18 - t_score * standard_error, 18 + t_score * standard_error)\n\nprint(CI_1)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 17.49078 18.50922\n```\n:::\n:::\n\n\n### Bypass Surgery\n\n\n::: {.cell}\n\n```{.r .cell-code}\nconfidence_level <- 0.90\n\ntail_area <- (1-confidence_level)/2\n\nstandard_error <- 10 / sqrt(539)\n\nt_score <- qt(p = 1-tail_area, df = 538)\n\nCI_2 <- c(19 - t_score * standard_error, 19 + t_score * standard_error)\n\nprint(CI_2)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 18.29029 19.70971\n```\n:::\n:::\n\n\nThe confidence interval for angiography (range of about 1.1) is smaller than the confidence interval for bypass surgery (range of about 1.5) at a confidence level of 90%.\n\n## Question 2\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Point estimate\n\np <- 567/1031\n\np\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 0.5499515\n```\n:::\n:::\n\n\nThe point estimate p for the proportion of all adult Americans who believe that a college education is essential for success.\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Confidence Interval\n\nconfidence_level <- 0.95\n\ntail_area <- (1-confidence_level)/2\n\nstandard_deviation <- sqrt((p * (1-p))/1031)\n\nstandard_error <- standard_deviation / sqrt(1031)\n\nt_score <- qt(p = 1-tail_area, df = 1030)\n\nCI_3 <- c(p - t_score * standard_error, p + t_score * standard_error)\n\nprint(CI_3)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 0.5490046 0.5508984\n```\n:::\n:::\n\n\nThrough this test, I am 95% confident that the true proportion of all adult Americans who believe a college education is essential for success lies between 0.549 and 0.551.\n\n## Question 3\n\n\n::: {.cell}\n\n```{.r .cell-code}\nsd <- (200-30)/4\n\nx <- 5/(2.26 * sd)\n\nsample_size = (1/x)^2\n\nsample_size\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 369.0241\n```\n:::\n:::\n\n\nThe size of the sample should be at least 370 people. Since they want a confidence interval within 5 dollars and they assume the standard deviation is a quarter of the range of 30 dollars to 200 dollars, I was able to use the confidence interval equation to find the missing variable of sample size. The confidence level is 95%, meaning that with a large sample size, the t-score would be around 2.26, allowing me to use the equation and isolate the sample size.\n\n## Question 4\n\n### Part A\n\nHo: The true mean income of female employees is \\$500/week\n\nHa: The true mean income of female employees is not \\$500/week\n\n\n::: {.cell}\n\n```{.r .cell-code}\nconfidence_level <- 0.95\n\ntail_area <- (1-confidence_level)/2\n\nstandard_error <- 90 / sqrt(9)\n\nt_score <- qt(p = 1-tail_area, df = 8)\n\nCI_4A <- c(410 - t_score * standard_error, 410 + t_score * standard_error)\n\np_value = 2 * pt(q = t_score, df = 8, lower.tail = FALSE)\n\np_value\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 0.05\n```\n:::\n\n```{.r .cell-code}\nprint(CI_4A)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 340.8199 479.1801\n```\n:::\n:::\n\n\nThe p-value is exactly 0.05, meaning it is not smaller than the alpha value of 0.05 and thus is not statistically significant. We do not have enough evidence to reject the null hypothesis. The confidence interval shows that we are 95% confident the true mean income of female employees lies between 340.82 dollars/week and 479.18 dollars/week.\n\n### Part B\n\n\n::: {.cell}\n\n```{.r .cell-code}\np_value = pt(q = t_score, df = 8, lower.tail = TRUE)\n\np_value\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 0.975\n```\n:::\n:::\n\n\nThe p-value for the alternate hypothesis that the true mean income of female employees is greater than 500 dollars/week is 0.975. This value is extremely large and greater than the 0.05 alpha level, meaning there is not statistically significant evidence and thus do not reject the null hypothesis.\n\n### Part C\n\n\n::: {.cell}\n\n```{.r .cell-code}\np_value = pt(q = t_score, df = 8, lower.tail = FALSE)\n\np_value\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 0.025\n```\n:::\n:::\n\n\nThe p-value for the alternative hypothesis that the true mean income of female employees is less than 500 dollars/week is 0.025. This value is less than the alpha value of 0.05, meaning it is statistically significant and we can reject the null hypothesis. The true mean income of female employees is likely less than 500 dollars/week.\n\n## Question 5\n\n### Part A\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Jones\n\nt_score <- (519.5-500)/(10)\n\nt_score\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 1.95\n```\n:::\n\n```{.r .cell-code}\np_value <- 2 * pt(q = t_score, df = 999, lower.tail = FALSE)\n\np_value\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 0.05145555\n```\n:::\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\n# Smith\n\nt_score <- (519.7-500)/(10)\n\nt_score\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 1.97\n```\n:::\n\n```{.r .cell-code}\np_value <- 2 * pt(q = t_score, df = 999, lower.tail = FALSE)\n\np_value\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 0.04911426\n```\n:::\n:::\n\n\n### Part B\n\nFor Jones's study, the results were not statistically significant because the p-value of 0.51 is greater than the alpha value of 0.05. For Smith's study, the results were statistically signficiant because the p-value of 0.49 is less than the alpha value of 0.05.\n\n### Part C\n\nReporting the result of a test as P being greater or less than the alpha value can be misleading if the p value is not reported. In both studies, the p-value was .01 away from 0.05, yet in only one study was the result statistically significant. A small p-value may still be meaningful to report because it still shows that there was a relatively small probability of getting the result that one did. Not reporting the p-value when reporting the result and whether or not a hypothesis is rejected leaves an important part of the study out. Someone simply reading that a hypothesis was not rejected without knowing the p-value may assume the p-value was very large even when it was small (such as in the case of Smith vs. Jones), thus leaving out a major aspect of the study.\n\n## Question 6\n\n\n::: {.cell}\n\n```{.r .cell-code}\ngas_taxes <- c(51.27, 47.43, 38.89, 41.95, 28.61, 41.29, 52.19, 49.48, 35.02, 48.13, 39.28, 54.41, 41.66, 30.28, 18.49, 38.72, 33.41, 45.02)\n\nt.test(gas_taxes, alternative = c(\"less\"), mu = 45)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n\n\tOne Sample t-test\n\ndata:  gas_taxes\nt = -1.8857, df = 17, p-value = 0.03827\nalternative hypothesis: true mean is less than 45\n95 percent confidence interval:\n     -Inf 44.67946\nsample estimates:\nmean of x \n 40.86278 \n```\n:::\n:::\n\n\nThe p-value of this test is 0.038, which is less than the alpha value of 0.05. This means that there is statistically significant evidence and we can reject the null hypothesis, that the true average gas tax per gallon in the United States is 45 cents. There is significant evidence to suggest that the true average gas tax per gallon in the United States is less than 45 cents.\n",
    "supporting": [],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}