{
  "hash": "df3ff1acd01bcafb6efb69e2f862aac4",
  "result": {
    "markdown": "---\ntitle: \"Homework 3\"\nauthor: \"Steve O'Neill\"\ndescription: \"Homework 3\"\ndate: \"10/29/2022\"\ndf-paged: true\nformat:\n  html:\n    toc: true\n    code-fold: true\n    code-copy: true\n    code-tools: true\ncategories:\n  - hw3\n---\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(tidyverse)\n```\n\n::: {.cell-output .cell-output-stderr}\n```\n── Attaching packages ─────────────────────────────────────── tidyverse 1.3.2 ──\n✔ ggplot2 3.3.6     ✔ purrr   0.3.4\n✔ tibble  3.1.8     ✔ dplyr   1.0.9\n✔ tidyr   1.2.0     ✔ stringr 1.4.0\n✔ readr   2.1.2     ✔ forcats 0.5.1\n── Conflicts ────────────────────────────────────────── tidyverse_conflicts() ──\n✖ dplyr::filter() masks stats::filter()\n✖ dplyr::lag()    masks stats::lag()\n```\n:::\n\n```{.r .cell-code}\nlibrary(alr4)\n```\n\n::: {.cell-output .cell-output-stderr}\n```\nLoading required package: car\nLoading required package: carData\n\nAttaching package: 'car'\n\nThe following object is masked from 'package:dplyr':\n\n    recode\n\nThe following object is masked from 'package:purrr':\n\n    some\n\nLoading required package: effects\nlattice theme set by effectsTheme()\nSee ?effectsTheme for details.\n```\n:::\n\n```{.r .cell-code}\nlibrary(smss)\ndata(\"UN11\")\ndata(\"water\")\ndata(\"Rateprof\")\ndata(\"student.survey\")\n```\n:::\n\n\nSome of the questions use data from the alr4 and smss R packages. For the ALR book, the package is. You would need to install those packages in R (no need for an install.packages() call in your .qmd file, though---just use library()) and load the data using the data() function.\n\nQuestions:\n\n## Question 1\n\n> United Nations (Data file: UN11in alr4) The data in the file UN11 contains several variables, including ppgdp, the gross national product per person in U.S. dollars, and fertility, the birth rate per 1000 females, both from the year 2009. The data are for 199 localities, mostly UN member countries, but also other areas such as Hong Kong that are not independent countries. The data were collected from the United Nations (2011). We will study the dependence of fertility on ppgdp.\n\n1.1.1. Identify the predictor and the response.\n\nThe independent (predictor) variable is `ppgdp`. The response (dependent) variable is `fertility`.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nhead(UN11)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n                region  group fertility   ppgdp lifeExpF pctUrban\nAfghanistan       Asia  other     5.968   499.0    49.49       23\nAlbania         Europe  other     1.525  3677.2    80.40       53\nAlgeria         Africa africa     2.142  4473.0    75.00       67\nAngola          Africa africa     5.135  4321.9    53.17       59\nAnguilla     Caribbean  other     2.000 13750.1    81.10      100\nArgentina   Latin Amer  other     2.172  9162.1    79.89       93\n```\n:::\n:::\n\n\n> 1.1.2 Draw the scatterplot of fertility on the vertical axis versus ppgdp on the horizontal axis and summarize the information in this graph. Does a straight-line mean function seem to be plausible for a summary of this graph?\n\nThis data looks curvilinear. A straight-line mean function is not favored.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(ggplot2)\nggplot(data = UN11, aes(x = ppgdp, y = fertility)) +\n  geom_point()\n```\n\n::: {.cell-output-display}\n![](HW3_SteveONeill_files/figure-html/unnamed-chunk-3-1.png){width=672}\n:::\n:::\n\n\n> 1.1.3 Draw the scatterplot of log(fertility) versus log(ppgdp) using natural logarithms. Does the simple linear regression model seem plausible for a summary of this graph? If you use a different base of logarithms, the shape of the graph won't change, but the values on the axes will change.\n\nYes, in the Log-Log model, linear regression seems more likely to work.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(ggplot2)\nggplot(data = UN11, aes(x = log(ppgdp), y = log(fertility))) +\n  geom_point() +\n  ggtitle(\"Log-Log\") +\n  geom_smooth(method = 'lm', se = F)\n```\n\n::: {.cell-output .cell-output-stderr}\n```\n`geom_smooth()` using formula 'y ~ x'\n```\n:::\n\n::: {.cell-output-display}\n![](HW3_SteveONeill_files/figure-html/unnamed-chunk-4-1.png){width=672}\n:::\n:::\n\n\n## Question 2\n\n> Annual income, in dollars, is an explanatory variable in a regression analysis. For a British version of the report on the analysis, all responses are converted to British pounds sterling (1 pound equals about 1.33 dollars, as of 2016).\n\n> (a) How, if at all, does the slope of the prediction equation change?\n\nI assume \"responses\" mean responses to a survey. I have created fake survey data to understand the question:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nsatisfaction <- c(1,2,3,4,5)\nus_income <- c(20010,30450,40000,51000,75000)\nuk_income <- c(us_income / 1.33) \n\nmod_us <- lm(satisfaction ~ us_income)\nsummary(mod_us)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n\nCall:\nlm(formula = satisfaction ~ us_income)\n\nResiduals:\n       1        2        3        4        5 \n-0.29520 -0.05966  0.24105  0.43559 -0.32178 \n\nCoefficients:\n              Estimate Std. Error t value Pr(>|t|)   \n(Intercept) -1.700e-01  4.294e-01  -0.396    0.719   \nus_income    7.322e-05  9.092e-06   8.054    0.004 **\n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n\nResidual standard error: 0.3839 on 3 degrees of freedom\nMultiple R-squared:  0.9558,\tAdjusted R-squared:  0.9411 \nF-statistic: 64.86 on 1 and 3 DF,  p-value: 0.003999\n```\n:::\n\n```{.r .cell-code}\nmod_uk <- lm(satisfaction ~ uk_income)\nsummary(mod_uk)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n\nCall:\nlm(formula = satisfaction ~ uk_income)\n\nResiduals:\n       1        2        3        4        5 \n-0.29520 -0.05966  0.24105  0.43559 -0.32178 \n\nCoefficients:\n              Estimate Std. Error t value Pr(>|t|)   \n(Intercept) -1.700e-01  4.294e-01  -0.396    0.719   \nuk_income    9.739e-05  1.209e-05   8.054    0.004 **\n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n\nResidual standard error: 0.3839 on 3 degrees of freedom\nMultiple R-squared:  0.9558,\tAdjusted R-squared:  0.9411 \nF-statistic: 64.86 on 1 and 3 DF,  p-value: 0.003999\n```\n:::\n:::\n\n\nIn the UK version, the slope is multiplied by 1.33.\n\n> (b) How, if at all, does the correlation change?\n\nSince only the units are changing, the correlation does not change. See:\n\n\n::: {.cell}\n\n```{.r .cell-code}\ncor(satisfaction,us_income)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 0.9776455\n```\n:::\n\n```{.r .cell-code}\ncor(satisfaction,uk_income)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 0.9776455\n```\n:::\n:::\n\n\n## Question 3\n\nWater runoff in the Sierras (Data file: water in alr4) Can Southern California's water supply in future years be predicted from past data? One factor affecting water availability is stream runoff. If runoff could be predicted, engineers, planners, and policy makers could do their jobs more efficiently. The data file contains 43 years' worth of precipitation measurements taken at six sites in the Sierra Nevada mountains (labeled APMAM, APSAB, APSLAKE, OPBPC, OPRC, and OPSLAKE) and stream runoff volume at a site near Bishop, California, labeled BSAAM. Draw the scatterplot matrix for these data and summarize the information available from these plots. (Hint: Use the pairs() function.)\n\n\n::: {.cell}\n\n```{.r .cell-code}\npairs(water)\n```\n\n::: {.cell-output-display}\n![](HW3_SteveONeill_files/figure-html/unnamed-chunk-7-1.png){width=672}\n:::\n:::\n\n\n`pair()` shows pairwise correlations. It looks like OPBC, OPRC, OPSLAKE, and BSAAM are very similar to each other. Likewise, APSLAK, APSAB, and APMAM are similar to each other. Taken separately, the two groups are not similar to each other. There is no pattern in the year of observation. I would be comfortable making predictions within the groups individually, but not based off the year. \n\n## Question 4\n\n>Professor ratings (Data file: Rateprof in alr4) In the website and online forum RateMyProfessors.com, students rate and comment on their instructors. Launched in 1999, the site includes millions of ratings on thousands of instructors. The data file includes the summaries of the ratings of 364 instructors at a large campus in the Midwest (Bleske-Rechek and Fritsch, 2011). Each instructor included in the data had at least 10 ratings over a several year period. Students provided ratings of 1--5 on quality, helpfulness, clarity, easiness of instructor's courses, and raterInterest in the subject matter covered in the instructor's courses. The data file provides the averages of these five ratings. Create a scatterplot matrix of these five variables. Provide a brief description of the relationships between the five ratings.\n\nQuality, helpfulness, and clarity are all highly correlated. This tells me that perceptions of quality really hinge on helpfulness and clarity from the professor. However, classes which are high quality, helpful, and clear are not always easy (although there is some kind of positive correlation).\n\nTo some degree, it does look like each pairwise combination is positively correlated, with the possible exception of raterInterest and easiness.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nratings <- Rateprof %>% select(quality, helpfulness, clarity, easiness, raterInterest)\npairs(ratings)\n```\n\n::: {.cell-output-display}\n![](HW3_SteveONeill_files/figure-html/unnamed-chunk-8-1.png){width=672}\n:::\n:::\n\n\n## Question 5\n\n>For the student.survey data file in the smss package, conduct regression analyses relating (by convention, y denotes the outcome variable, x denotes the explanatory variable) (i) y = political ideology and x = religiosity, (ii) y = high school GPA and x = hours of TV watching.\n\n\n::: {.cell}\n\n```{.r .cell-code}\n#Levels look to be correct already:\n#as.factor(student.survey$pi)\n\nsummary(lm(as.numeric(student.survey$pi) ~ as.numeric(student.survey$re)))\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n\nCall:\nlm(formula = as.numeric(student.survey$pi) ~ as.numeric(student.survey$re))\n\nResiduals:\n     Min       1Q   Median       3Q      Max \n-2.81243 -0.87160  0.09882  1.12840  3.09882 \n\nCoefficients:\n                              Estimate Std. Error t value Pr(>|t|)    \n(Intercept)                     0.9308     0.4252   2.189   0.0327 *  \nas.numeric(student.survey$re)   0.9704     0.1792   5.416 1.22e-06 ***\n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n\nResidual standard error: 1.345 on 58 degrees of freedom\nMultiple R-squared:  0.3359,\tAdjusted R-squared:  0.3244 \nF-statistic: 29.34 on 1 and 58 DF,  p-value: 1.221e-06\n```\n:::\n\n```{.r .cell-code}\nsummary(lm(as.numeric(student.survey$hi) ~ as.numeric(student.survey$tv)))\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n\nCall:\nlm(formula = as.numeric(student.survey$hi) ~ as.numeric(student.survey$tv))\n\nResiduals:\n    Min      1Q  Median      3Q     Max \n-1.2583 -0.2456  0.0417  0.3368  0.7051 \n\nCoefficients:\n                               Estimate Std. Error t value Pr(>|t|)    \n(Intercept)                    3.441353   0.085345  40.323   <2e-16 ***\nas.numeric(student.survey$tv) -0.018305   0.008658  -2.114   0.0388 *  \n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n\nResidual standard error: 0.4467 on 58 degrees of freedom\nMultiple R-squared:  0.07156,\tAdjusted R-squared:  0.05555 \nF-statistic: 4.471 on 1 and 58 DF,  p-value: 0.03879\n```\n:::\n:::\n\n\n>(a)Graphically portray how the explanatory variable relates to the outcome variable in each of the two cases \n\n\n::: {.cell}\n\n```{.r .cell-code}\n#as.numeric(student.survey$pi)\n\n#  (i) y = political ideology and x = religiosity\n\nlibrary(ggplot2)\nggplot(data = student.survey, aes(x = re, y = pi)) +\n  geom_point()\n```\n\n::: {.cell-output-display}\n![](HW3_SteveONeill_files/figure-html/unnamed-chunk-10-1.png){width=672}\n:::\n\n```{.r .cell-code}\npi_re <- student.survey %>% select(pi, re)\npairs(pi_re)\n```\n\n::: {.cell-output-display}\n![](HW3_SteveONeill_files/figure-html/unnamed-chunk-10-2.png){width=672}\n:::\n\n```{.r .cell-code}\n#Alternate way:\nlibrary(ggplot2)\nggplot(data = student.survey, aes(x = re, y = pi)) +\n  geom_point() +\n  geom_smooth(method = 'lm', se = F) +\n  ggtitle (\"Religiosity and Political Ideology\")\n```\n\n::: {.cell-output .cell-output-stderr}\n```\n`geom_smooth()` using formula 'y ~ x'\n```\n:::\n\n::: {.cell-output-display}\n![](HW3_SteveONeill_files/figure-html/unnamed-chunk-10-3.png){width=672}\n:::\n\n```{.r .cell-code}\n#(ii) y = high school GPA and x = hours of TV watching\n\nlibrary(ggplot2)\nggplot(data = student.survey, aes(x = hi, y = tv)) +\n  geom_point() +\n  geom_smooth(method = 'lm', se = F) +\n  ggtitle (\"High School GPA and TV watched (in hours)\")\n```\n\n::: {.cell-output .cell-output-stderr}\n```\n`geom_smooth()` using formula 'y ~ x'\n```\n:::\n\n::: {.cell-output-display}\n![](HW3_SteveONeill_files/figure-html/unnamed-chunk-10-4.png){width=672}\n:::\n\n```{.r .cell-code}\n#Alternate way:\n\nhi_tv  <- student.survey %>% select(hi, tv)\npairs(hi_tv)\n```\n\n::: {.cell-output-display}\n![](HW3_SteveONeill_files/figure-html/unnamed-chunk-10-5.png){width=672}\n:::\n:::\n\n\n\n>(b) Summarize and interpret results of inferential analyses.\n\n### Political Ideology ~ Religiosity\n\nPolitical ideology is slightly correlated with religiosity with an R-squared of 0.3359. The results are statistically significant. However, I would not say this is quite enough for predictive purposes because of that low R-squared value.\n\n### High School GPA ~ TV Watched\n\nLooking at the scatterplot makes it appear that this data is all over the place with outliers. It does seem the higher GPA students do watch the least TV, and the linear regression is technically statistically significant with a p-value of 0.0388. However, the R-squared value is a very low 0.07156. I would not make any inferences about GPA's causal effect on TV.\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n",
    "supporting": [
      "HW3_SteveONeill_files"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}