{
  "hash": "01376a63ab25998c316f17476068e18f",
  "result": {
    "markdown": "---\ntitle: \"Homework 2 Solution\"\nauthor: \"Dane Shelton\"\ndesription: \"Confidence Intervals and Hypothesis Testing\"\ndate: \"10/16/2022\"\nformat:\n  html:\n    df-print: paged\n    callout-appearance: \"simple\"\n    callout-icon: FALSE\n    toc: true\n    code-fold: true\n    code-copy: true\n    code-tools: true\ncategories:\n  - hw2\n  - shelton\n---\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(tidyverse)\n\nknitr::opts_chunk$set(warning= FALSE, message=FALSE)\n```\n:::\n\n\n## Homework 2\n\n::: panel-tabset\n## Q1\n\n### 90% Confidence Intervals\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Bypass\nn_bp <- 539\nmean_bp <- 19\nsd_bp <- 10\nt_90 <- qt(.05, (n_bp-1), lower.tail=F)\n\n#CI\nupper_bp <- mean_bp + ((sd_bp/sqrt(539))*t_90)\nlower_bp <- mean_bp - ((sd_bp/sqrt(539))*t_90)\n\nci90_bp <- c(lower_bp,upper_bp)\nprint(c(\"90% CI For Mean Bypass Wait\", ci90_bp))\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] \"90% CI For Mean Bypass Wait\" \"18.2902893200424\"           \n[3] \"19.7097106799576\"           \n```\n:::\n\n```{.r .cell-code}\n# Angiography\nn_ag <- 847\nmean_ag <- 18\nsd_ag <- 9\nt_90 <- qt(.05, (n_ag-1), lower.tail=F)\n\n#CI\nupper_ag <- mean_ag + (sd_ag/sqrt(539)*t_90)\nlower_ag <- mean_ag - (sd_ag/sqrt(539)*t_90)\n\nci90_ag <- c(lower_ag,upper_ag)\n\nprint(c(\"90% CI For Angiography Wait\", ci90_ag))\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] \"90% CI For Angiography Wait\" \"17.3616612514732\"           \n[3] \"18.6383387485268\"           \n```\n:::\n\n```{.r .cell-code}\nprint(c(\"Width Bypass\", upper_bp-lower_bp))\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] \"Width Bypass\"     \"1.41942135991513\"\n```\n:::\n\n```{.r .cell-code}\nprint(c(\"Width Angiography\", upper_ag-lower_ag))\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] \"Width Angiography\" \"1.27667749705367\" \n```\n:::\n:::\n\n\nThe 90% Confidence interval is narrower for the mean Angiography wait time (days) than mean Bypass wait due to the larger sample and smaller standard deviation.\n\n## Q2\n\n### One Prop Confidence Interval\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# College 95% CI\nprop.test(567,1031,conf.level = .95)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n\n\t1-sample proportions test with continuity correction\n\ndata:  567 out of 1031, null probability 0.5\nX-squared = 10.091, df = 1, p-value = 0.00149\nalternative hypothesis: true p is not equal to 0.5\n95 percent confidence interval:\n 0.5189682 0.5805580\nsample estimates:\n        p \n0.5499515 \n```\n:::\n:::\n\n\nThe 95% confidence interval for the true proportion of Americans who believe a college education is essential for success is (0.52,0.58). 95% confidence is not a comment on the proportion itself, rather our method. If we took several samples and created a confidence interval for proportion `p`, 95% of the intervals would contain the true population proportion.\n\nBecause our confidence interval does not include .5, we can conclude that at .05 significance, the majority (\\>0.5) of Americans believe that a college educcation is essential for success.\n\n## Q3\n\n### Margin of Error Calculation\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Margin of Error Calculation\n\nci_95 <- qnorm(.025, lower.tail=F)\n\n# 5 = (170*.25)/sqrt(x)*1.96\n\n(x <- ((170*.25)/5)*ci_95)^2\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 277.5454\n```\n:::\n:::\n\n\nTo estimate mean textbook cost per semester within \\$5 of true value at .05 significance level the financial aid office would need 278 students in their sample.\n\n## Q4\n\n### One Sample T-Test\n\n::: callout-note\n## a \n**H~0~:** mean income of female employees = \\$500/wk \n**H~1~:** mean income of female employees != \\$500/wk\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# womens data\nw_xbar <- 410\nw_n <- 9\nw_sd <- 90\nw_se <- 90/sqrt(w_n)\ntest_stat <- (w_xbar-500)/w_se\ncrit_2sided <- abs(qt(.025,w_n-1))\ncrit_less <- qt(.05, w_n-1,lower.tail=T)\ncrit_greater <- qt(.95,w_n-1,lower.tail=T)\np_value <- pt(test_stat, df=w_n-1, lower.tail=T)\npval_greater <- pt(test_stat, df=w_n-1, lower.tail=F)\n\n# Two Sided 2 Test\nprint('Two-Sided T-Test')\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] \"Two-Sided T-Test\"\n```\n:::\n\n```{.r .cell-code}\nprint(c('test-statistic (use absolute value):', test_stat))\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] \"test-statistic (use absolute value):\"\n[2] \"-3\"                                  \n```\n:::\n\n```{.r .cell-code}\nprint(c('rejection-region:', crit_2sided))\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] \"rejection-region:\" \"2.30600413520417\" \n```\n:::\n\n```{.r .cell-code}\nprint(c('p-value', 2*p_value))\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] \"p-value\"            \"0.0170716812337826\"\n```\n:::\n:::\n\n\np-value = .017; Reject the null, at alpha=.05 we have sufficient evidence to conclude female employees' wages differ from \\$500/week. If female weekly income was equal to 500, we would expect 1.7% of samples to produce a sample mean of 410\\$ or more extreme.\n:::\n\n::: callout-note\n## b\n\n**H~0~:** mean income of female employees = \\$500/wk \n**H~1~:** mean income of female employees is less than \\$500/wk\n\n\n::: {.cell}\n\n```{.r .cell-code}\nprint('Left-Sided T-Test')\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] \"Left-Sided T-Test\"\n```\n:::\n\n```{.r .cell-code}\nprint(c('test-statistic:', test_stat))\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] \"test-statistic:\" \"-3\"             \n```\n:::\n\n```{.r .cell-code}\nprint(c('rejection-region:',crit_less))\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] \"rejection-region:\" \"-1.8595480375309\" \n```\n:::\n\n```{.r .cell-code}\nprint(c('p-value',p_value))\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] \"p-value\"             \"0.00853584061689132\"\n```\n:::\n:::\n\n\np-value = .009; Reject the null, at alpha=.05 we have sufficient evidence to conclude female employees' wages are less than \\$500/week. If mean female weekly income was equal to 500 , we would expect less than one percent of samples to produce a mean equal to or more extreme (less) than 410.\n:::\n\n::: callout-note\n## c\n\n**H~0~:** mean income of female employees = \\$500/wk \n**H~1~:** mean income of female employees is greater than \\$500/wk\n\n\n::: {.cell}\n\n```{.r .cell-code}\nprint('Right-Sided T-Test')\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] \"Right-Sided T-Test\"\n```\n:::\n\n```{.r .cell-code}\nprint(c('test-statistic:', test_stat))\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] \"test-statistic:\" \"-3\"             \n```\n:::\n\n```{.r .cell-code}\nprint(c('rejection-region:',crit_greater))\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] \"rejection-region:\" \"1.8595480375309\"  \n```\n:::\n\n```{.r .cell-code}\nprint(c('p-value',pval_greater))\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] \"p-value\"           \"0.991464159383109\"\n```\n:::\n:::\n\n\np-value = .991; Fail to reject the null, at alpha=.05 we do **not**have sufficient evidence to conclude female employees' wages are greater than \\$500/week. If female weekly income was equal to 500, we would expect 99 percent of samples to produce a mean equal to or greater than 410.\n:::\n\n## Q5\n\n::: callout-note\n## a & b \n\n\n::: {.cell}\n\n```{.r .cell-code}\n# jones data\nj_xbar <- 519.5\nj_n <- 1000\nj_se <- 10\nj_test_stat <- (j_xbar-500)/j_se\ncrit_2sided <- abs(qt(.025,j_n-1))\nj_p_value <- pt(j_test_stat, df=j_n-1, lower.tail=F)\n\n\n# Jones Two Sided 2 Test\nprint('Jones Two-Sided T-Test')\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] \"Jones Two-Sided T-Test\"\n```\n:::\n\n```{.r .cell-code}\nprint(c('test-statistic (use absolute value):', j_test_stat))\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] \"test-statistic (use absolute value):\"\n[2] \"1.95\"                                \n```\n:::\n\n```{.r .cell-code}\nprint(c('rejection-region:', crit_2sided))\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] \"rejection-region:\" \"1.96234146113345\" \n```\n:::\n\n```{.r .cell-code}\nprint(c('p-value', 2*j_p_value))\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] \"p-value\"            \"0.0514555476459477\"\n```\n:::\n\n```{.r .cell-code}\nprint(c('insignificant at alpha = 0.05'))\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] \"insignificant at alpha = 0.05\"\n```\n:::\n\n```{.r .cell-code}\n# smith data\ns_xbar <- 519.7\ns_n <- 1000\ns_se <- 10\ns_test_stat <- (s_xbar-500)/s_se\ncrit_2sided <- abs(qt(.025,j_n-1))\ns_p_value <- pt(s_test_stat, df=s_n-1, lower.tail=F)\n\n\n# Smith Two Sided 2 Test\nprint('Smith Two-Sided T-Test')\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] \"Smith Two-Sided T-Test\"\n```\n:::\n\n```{.r .cell-code}\nprint(c('test-statistic (use absolute value):', s_test_stat))\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] \"test-statistic (use absolute value):\"\n[2] \"1.97\"                                \n```\n:::\n\n```{.r .cell-code}\nprint(c('rejection-region:', crit_2sided))\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] \"rejection-region:\" \"1.96234146113345\" \n```\n:::\n\n```{.r .cell-code}\nprint(c('p-value', 2*s_p_value))\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] \"p-value\"            \"0.0491142565416521\"\n```\n:::\n\n```{.r .cell-code}\nprint(c('significant at alpha = 0.05'))\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] \"significant at alpha = 0.05\"\n```\n:::\n:::\n\n:::\n\n:::callout-note\n## c\n\nBy not reporting the p-value, we do not understand the strength of the test - *how* extreme are the findings? In in an example like this, we see nearly identical results produce opposite significance results; language like \"statistically significant\" can get especially dangerous here to someone who is unfamiliar with basic statistical theory.\n:::\n\n## Q6\n\n\n::: {.cell}\n\n```{.r .cell-code}\ngas_taxes <- c(51.27, 47.43, 38.89, \n               41.95, 28.61, 41.29, \n               52.19, 49.48, 35.02, \n               48.13, 39.28, 54.41, \n               41.66, 30.28, 18.49, \n               38.72, 33.41, 45.02)\nt.test(gas_taxes, mu=45, alternative = 'less')\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n\n\tOne Sample t-test\n\ndata:  gas_taxes\nt = -1.8857, df = 17, p-value = 0.03827\nalternative hypothesis: true mean is less than 45\n95 percent confidence interval:\n     -Inf 44.67946\nsample estimates:\nmean of x \n 40.86278 \n```\n:::\n:::\n\n\nYes; at the 95% confidence level, we have sufficient evidence to reject the null hypothesis mu=45. 45 is not included in our left sided confidence interval, favoring the alternative hypothesis that the average tax on gas in the United States in 2005 was less than 45 cents per gallon.\n:::\n\n\n",
    "supporting": [],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {
      "include-in-header": [
        "<link href=\"../site_libs/pagedtable-1.1/css/pagedtable.css\" rel=\"stylesheet\" />\r\n<script src=\"../site_libs/pagedtable-1.1/js/pagedtable.js\"></script>\r\n"
      ]
    },
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}