{
  "hash": "fbed5296a9dcde7c7d774e50ebe0714c",
  "result": {
    "markdown": "---\ntitle: \"HW1\"\nauthor: \"Niyati Sharma\"\ndesription: \"The first homework on descriptive statistics and probability\"\ndate: \"10/03/2022\"\nformat:\n  html:\n    toc: true\n    code-fold: true\n    code-copy: true\n    code-tools: true\ncategories:\n  - hw1\n  - Niyati Sharma\n  - desriptive statistics \n  - probability\n---\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(tidyverse)\nlibrary(readxl)\nlibrary(ggplot2)\nlibrary(stats)\n\n\n\nknitr::opts_chunk$set(echo = TRUE)\n```\n:::\n\n\n## Question 1\n\n## Read the data from xls file\n\n::: {.cell}\n\n```{.r .cell-code}\nRE <- read_excel(\"_data/LungCapData.xls\")\nRE\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n# A tibble: 725 × 6\n   LungCap   Age Height Smoke Gender Caesarean\n     <dbl> <dbl>  <dbl> <chr> <chr>  <chr>    \n 1    6.48     6   62.1 no    male   no       \n 2   10.1     18   74.7 yes   female no       \n 3    9.55    16   69.7 no    female yes      \n 4   11.1     14   71   no    male   no       \n 5    4.8      5   56.9 no    male   no       \n 6    6.22    11   58.7 no    female no       \n 7    4.95     8   63.3 no    male   yes      \n 8    7.32    11   70.4 no    male   no       \n 9    8.88    15   70.5 no    male   no       \n10    6.8     11   59.2 no    male   no       \n# … with 715 more rows\n```\n:::\n:::\n\n\n##A\n\n\n::: {.cell}\n\n```{.r .cell-code}\nRE %>% \n  ggplot(aes(LungCap))+\n  geom_histogram(bins=20)\n```\n\n::: {.cell-output-display}\n![](NiyatiSharma_HW1_files/figure-html/unnamed-chunk-3-1.png){width=672}\n:::\n:::\n\n\nThe histogram looks close to normal distributed.\n\n\n## B\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nRE %>%\n  ggplot(aes (LungCap, color=Gender)) +\n  geom_boxplot() +\n  theme_classic() \n```\n\n::: {.cell-output-display}\n![](NiyatiSharma_HW1_files/figure-html/unnamed-chunk-4-1.png){width=672}\n:::\n:::\n\n  The probability density of the female is higher than the males.\n\n\n## C\n\n\n::: {.cell}\n\n```{.r .cell-code}\nMean_Smoker <- RE %>%\n  group_by(Smoke) %>%\n  summarise(mean = mean(LungCap))\nMean_Smoker\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n# A tibble: 2 × 2\n  Smoke  mean\n  <chr> <dbl>\n1 no     7.77\n2 yes    8.65\n```\n:::\n\n```{.r .cell-code}\nggplot(RE, aes(LungCap,Smoke))+\n  geom_boxplot()\n```\n\n::: {.cell-output-display}\n![](NiyatiSharma_HW1_files/figure-html/unnamed-chunk-5-1.png){width=672}\n:::\n:::\n\nFrom this sample, it appears that smokers have a higher mean lung capacity than non-smokers. \n\n## D\n\n\n::: {.cell}\n\n```{.r .cell-code}\nRE<-RE %>% \n  mutate(Category = as.factor(case_when(Age <= 13 ~ \"13 and under\", \n                           Age == 14 |Age ==15 ~ \"14-15\", \n                           Age == 16 | Age==17 ~ \"16-17\",\n                           Age >= 18 ~ \"18 or over\"\n                           )))\nRE\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n# A tibble: 725 × 7\n   LungCap   Age Height Smoke Gender Caesarean Category    \n     <dbl> <dbl>  <dbl> <chr> <chr>  <chr>     <fct>       \n 1    6.48     6   62.1 no    male   no        13 and under\n 2   10.1     18   74.7 yes   female no        18 or over  \n 3    9.55    16   69.7 no    female yes       16-17       \n 4   11.1     14   71   no    male   no        14-15       \n 5    4.8      5   56.9 no    male   no        13 and under\n 6    6.22    11   58.7 no    female no        13 and under\n 7    4.95     8   63.3 no    male   yes       13 and under\n 8    7.32    11   70.4 no    male   no        13 and under\n 9    8.88    15   70.5 no    male   no        14-15       \n10    6.8     11   59.2 no    male   no        13 and under\n# … with 715 more rows\n```\n:::\n\n```{.r .cell-code}\nRE %>%\n  ggplot(aes( LungCap, color = Smoke)) +\n  geom_histogram()+\n  facet_grid(Smoke ~ Category)\n```\n\n::: {.cell-output .cell-output-stderr}\n```\n`stat_bin()` using `bins = 30`. Pick better value with `binwidth`.\n```\n:::\n\n::: {.cell-output-display}\n![](NiyatiSharma_HW1_files/figure-html/unnamed-chunk-6-1.png){width=672}\n:::\n:::\n\nThe people who smoke are few in age group of \"less than or equal to 13\".\nFrom the result we can say  age is inversely proportional to the lung capacity.\n\n\n\n## E\nForm the above data we can say the output are pretty similar that smokers have a lower lung capacity compared to non-smokers\n\n## F\ncorrelation and covariance between lung capacity and age\n\n::: {.cell}\n\n```{.r .cell-code}\ncov(RE$LungCap,RE$Age)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 8.738289\n```\n:::\n\n```{.r .cell-code}\ncor(RE$LungCap,RE$Age)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 0.8196749\n```\n:::\n:::\n\nCovariance is positive and indicates that age and lung capacity are directly related.\nCorrelation is also positive,from these results we can conclude that the lung capacity increases with age. \n\n\n## Question 2\n\n\n::: {.cell}\n\n```{.r .cell-code}\nx <- c(0:4)\nfreq <- c(128, 434, 160, 64, 24)\nconvictions <- data_frame(x, freq)\n```\n\n::: {.cell-output .cell-output-stderr}\n```\nWarning: `data_frame()` was deprecated in tibble 1.1.0.\nPlease use `tibble()` instead.\n```\n:::\n\n```{.r .cell-code}\nconvictions\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n# A tibble: 5 × 2\n      x  freq\n  <int> <dbl>\n1     0   128\n2     1   434\n3     2   160\n4     3    64\n5     4    24\n```\n:::\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\nconvictions <- convictions %>% mutate(probability = freq/sum(freq))\nconvictions\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n# A tibble: 5 × 3\n      x  freq probability\n  <int> <dbl>       <dbl>\n1     0   128      0.158 \n2     1   434      0.536 \n3     2   160      0.198 \n4     3    64      0.0790\n5     4    24      0.0296\n```\n:::\n:::\n\n\n\n## A\nProbability of exactly 2 is 19.75%\n\n## B\n\n::: {.cell}\n\n```{.r .cell-code}\na <-head(convictions,2)\nsum(a$probability)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 0.6938272\n```\n:::\n:::\n\nProbability that a randomly selected inmate has fewer than 2 prior\nconvictions : 69.38%\n\n## C \n\n\n::: {.cell}\n\n```{.r .cell-code}\na <-head(convictions,3)\nsum(a$probability)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 0.891358\n```\n:::\n:::\n\nThe probability that a randomly selected inmate has 2 or fewer prior\nconvictions : 89.13%\n\n## D\n\n\n::: {.cell}\n\n```{.r .cell-code}\na <-tail(convictions,2)\nsum(a$probability)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 0.108642\n```\n:::\n:::\n\nThe probability that a randomly selected inmate has more than 2 prior\nconvictions? : 10.86%\n\n\n## E\n\n::: {.cell}\n\n```{.r .cell-code}\nWE <- weighted.mean(convictions$x,convictions$probability)\nWE\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 1.28642\n```\n:::\n:::\n\nThe expected value for the number of prior convictions : 1.28\n\n## F\nThe variance is 0.857 and the standard deviation is 0.925\n\n::: {.cell}\n\n```{.r .cell-code}\nAB <- (sum(freq*((x-WE)^2)))/(sum(freq)-1)\nAB\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 0.8572937\n```\n:::\n\n```{.r .cell-code}\nsqrt(AB)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 0.9259016\n```\n:::\n:::",
    "supporting": [
      "NiyatiSharma_HW1_files"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}