{
  "hash": "48a88f68f818ca1b27fced0dec28d41c",
  "result": {
    "markdown": "---\ntitle: \"HW2\"\nauthor: \"Ken Docekal\"\ndesription: \"Homework 2\"\ndate: \"10/17/2022\"\nformat:\n  html:\n    toc: true\n    code-fold: true\n    code-copy: true\n    code-tools: true\ncategories:\n  - hw2\n  - Ken Docekal\n\n---\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(tidyverse)\n\nknitr::opts_chunk$set(echo = TRUE)\n```\n:::\n\n\n\n\n## Q1\n\n\n90% Confidence Interval for Bypass:\n\n18.29 - 19.71\n\n\n::: {.cell}\n\n```{.r .cell-code}\nn <- 539\nxbar <- 19 \ns <- 10\n\nmargin <- qt(0.95,df=n-1)*s/sqrt(n)\n\nlow <- xbar - margin\nlow\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 18.29029\n```\n:::\n\n```{.r .cell-code}\nhigh <- xbar + margin\nhigh\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 19.70971\n```\n:::\n:::\n\n\n\n90% Confidence Interval for Angiography:\n\n17.49 - 18.51\n\n\n::: {.cell}\n\n```{.r .cell-code}\nn <- 847\nxbar <- 18 \ns <- 9\n\nmargin <- qt(0.95,df=n-1)*s/sqrt(n)\n\nlow <- xbar - margin\nlow\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 17.49078\n```\n:::\n\n```{.r .cell-code}\nhigh <- xbar + margin\nhigh\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 18.50922\n```\n:::\n:::\n\nThe confidence interval is narrower for Angiography - 1.02 difference, compared to Bypass - 1.42 difference. \n\n\n\n## Q2\n\n\nThe proportion point estimate for adult Americans who believe that a college education is essential for success is .55, based on 567 out of the representative sample of 1031 adult Americans surveyed. \n\nA 95% confidence interval shows that in 95% of cases the observed mean proportion of adult Americans who believe that a college education is essential for success will be between 52% and 58%. \n\n\n::: {.cell}\n\n```{.r .cell-code}\nprop.test(567,1031)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n\n\t1-sample proportions test with continuity correction\n\ndata:  567 out of 1031, null probability 0.5\nX-squared = 10.091, df = 1, p-value = 0.00149\nalternative hypothesis: true p is not equal to 0.5\n95 percent confidence interval:\n 0.5189682 0.5805580\nsample estimates:\n        p \n0.5499515 \n```\n:::\n:::\n\n\n\n\n## Q3\n\n\nBased on the range of 30 to 200 we can determine the standard deviation using s = (Maximum – Minimum)/4 resulting in s=42.5.With a 95% significance level we will use 1.96 for the z score. To find the minimum sample size needed - n, we solve for (Zscore*s/margin of error)^2. Our sample size needs to be at least 277.56. \n\n\n::: {.cell}\n\n```{.r .cell-code}\nn <- ((1.96)*(42.5)/5)^2\n\nn\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 277.5556\n```\n:::\n:::\n\n\n\n\n## Q4\n\n\n# A\n\n\nCreate random normal distribution sample as a tibble for female employee wages using mean - 410, standard deviation - 90, and n - 9. Name column as \"wage\".\n\n\n::: {.cell}\n\n```{.r .cell-code}\nset.seed(24)\nfemale <-tibble(\n  value=rnorm(n=9,mean=410,sd=90))\n\n\nnames(female) <- c(\"wage\")\n\n                   \nsummary(female) \n```\n\n::: {.cell-output .cell-output-stdout}\n```\n      wage      \n Min.   :333.6  \n 1st Qu.:360.9  \n Median :433.9  \n Mean   :410.7  \n 3rd Qu.:450.0  \n Max.   :486.3  \n```\n:::\n:::\n\n\n\nUsing a one sample t-test we observe a p-value of .001 meaning we can reject the null hypothesis where mean income equals 500 at the 95% confidence level. In this test Wages are assumed to be normally distributed; we observe the test statistic of -4.84, which measures how close our data matches the null hypothesis' expected distribution and informs the p-value.\n\nResults indicate that 95% of cases will not show an employee with 500 in wages. Furthermore, the mean of 410.70 and 95% confidence interval of 368.15 to 453.25 indicate wages will not be greater than 471 at most for most female employees.  \n\n\n::: {.cell}\n\n```{.r .cell-code}\nt.test(female$wage, mu = 500)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n\n\tOne Sample t-test\n\ndata:  female$wage\nt = -4.84, df = 8, p-value = 0.001288\nalternative hypothesis: true mean is not equal to 500\n95 percent confidence interval:\n 368.1516 453.2464\nsample estimates:\nmean of x \n  410.699 \n```\n:::\n:::\n\n\n\n# B\n\n\nDue to the small p-value of 0.0006 we are confident that the true mean must be less than 500, even at the 99% confidence level. \n\n\n::: {.cell}\n\n```{.r .cell-code}\nt.test(female$wage, mu = 500, alternative = 'less')\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n\n\tOne Sample t-test\n\ndata:  female$wage\nt = -4.84, df = 8, p-value = 0.0006441\nalternative hypothesis: true mean is less than 500\n95 percent confidence interval:\n    -Inf 445.009\nsample estimates:\nmean of x \n  410.699 \n```\n:::\n:::\n\n\n\n# C\n\n\nThe opposite is true when looking at the p-value of .999 for when the true mean is greater than 500. This indicates that 99.9% of cases observed will not have a mean greater than 500. All results indicate strong likelihood that mean wage will be less than 500 for female employees.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nt.test(female$wage, mu = 500, alternative = 'greater')\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n\n\tOne Sample t-test\n\ndata:  female$wage\nt = -4.84, df = 8, p-value = 0.9994\nalternative hypothesis: true mean is greater than 500\n95 percent confidence interval:\n 376.389     Inf\nsample estimates:\nmean of x \n  410.699 \n```\n:::\n:::\n\n\n\n\n\n## Q5\n\n\n# A\n\n\nFirst obtain standard deviation using standard error times square root of sample size.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nsd <- 10*(sqrt(1000))\n\nsd\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 316.2278\n```\n:::\n:::\n\n\n\nWe can then create samples as tibbles for Jones and Smith using respective means - 519.7 and 519.5, standard deviation - 316.23, and n - 1000.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nset.seed(65)\njones <-tibble(\n  value= rnorm(n=1000,mean=519.7,sd=316.23))\n```\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\nset.seed(32)\nsmith <-tibble(\n  value= rnorm(n=1000,mean=519.5,sd=316.23))\n```\n:::\n\n\n\nWith two one sample t-tests we observe a t and p values of 1.859 and .063 for Jones and 2.015 and .044 for Smith. As the data set was randomly generated based on provided parameters results did not exactly match those in the prompt. \n\n\n::: {.cell}\n\n```{.r .cell-code}\nt.test(jones$value, mu = 500)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n\n\tOne Sample t-test\n\ndata:  jones$value\nt = 1.8587, df = 999, p-value = 0.06336\nalternative hypothesis: true mean is not equal to 500\n95 percent confidence interval:\n 498.9088 540.2335\nsample estimates:\nmean of x \n 519.5711 \n```\n:::\n\n```{.r .cell-code}\nt.test(smith$value, mu = 500)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n\n\tOne Sample t-test\n\ndata:  smith$value\nt = 2.0152, df = 999, p-value = 0.04415\nalternative hypothesis: true mean is not equal to 500\n95 percent confidence interval:\n 500.5197 539.1257\nsample estimates:\nmean of x \n 519.8227 \n```\n:::\n:::\n\n\n\n# B\n\n\nUsing a 95% confidence interval, p-values indicate that Jones' test is not statistically significant while Smith's test is significant. This is because Jones' p-value is .013 over the acceptable p-value score for results to be acceptable at the 95% confidence level. Smith's score is .006 under the same threshold and therefore still considered statistically significant. \n\n\n# C\n\n\nThis example illustrates the importance of reporting actual p-values as sometimes the margin of difference between p-values can be minor but still have a major impact on whether results are considered statistically significant. This can mislead readers as test results may be improperly discounted, due to the impact of minor differences in data, although results may otherwise be almost identical to a test done using a different comparable but non-identical sample. View the actual p-value allows readers to better understand the data studied by view the degree of difference results show from the confidence level used. \n\n\n\n\n## Q6\n\n\nCreate a data frame with a column for tax values.\n\n\n::: {.cell}\n\n```{.r .cell-code}\ngas_taxes <-  data.frame (first_column  = c(51.27, 47.43, 38.89, 41.95, 28.61, 41.29, 52.19, 49.48, 35.02, 48.13, 39.28, 54.41, 41.66, 30.28, 18.49, 38.72, 33.41, 45.02)) \n```\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\ngas_taxes\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n   first_column\n1         51.27\n2         47.43\n3         38.89\n4         41.95\n5         28.61\n6         41.29\n7         52.19\n8         49.48\n9         35.02\n10        48.13\n11        39.28\n12        54.41\n13        41.66\n14        30.28\n15        18.49\n16        38.72\n17        33.41\n18        45.02\n```\n:::\n\n```{.r .cell-code}\nnames(gas_taxes) <- c(\"tax\")\n```\n:::\n\n\n\nUsing a one sample t-test where null hypothesis is mean tax is 45 and alternative hypothesis is true mean is less than 45 we are able to reject the null hypothesis at the 95% confidence level. Results indicate that mean tax was 40.86 and 95% of all observations will find a mean tax less than 44.68; therefore, while a few cities at the upper end of the range had prices near 45 cents per gallon, this was not usual and the average tax per gallon of gas in the US in 2005 was less than 45 cents. \n\n\n::: {.cell}\n\n```{.r .cell-code}\nt.test(gas_taxes$tax, mu = 45, alternative = 'less')\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n\n\tOne Sample t-test\n\ndata:  gas_taxes$tax\nt = -1.8857, df = 17, p-value = 0.03827\nalternative hypothesis: true mean is less than 45\n95 percent confidence interval:\n     -Inf 44.67946\nsample estimates:\nmean of x \n 40.86278 \n```\n:::\n:::\n",
    "supporting": [],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}