{
  "hash": "b95105af8a4cfe57801b9b838f9379ca",
  "result": {
    "markdown": "---\ntitle: 'Resubmission: Homework #1'\nauthor: \"Kalimah Muhammad\"\ndate: \"10/03/2022\"\ndesription: \"Descriptive Statistics\"\nformat:\n  html:\n    toc: true\n    code-fold: true\n    code-copy: true\n    code-tools: true\ncategories: \n  - hw1\n  - Kalimah Muhammad\n---\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(tidyverse)\nlibrary(dplyr)\nlibrary(readxl)\nlibrary (ggplot2)\nlungcap<- read_excel(\"_data/LungCapData.xls\")\nknitr::opts_chunk$set(echo = TRUE)\n```\n:::\n\n\n## LungCapData\n\n### 1a. What does the distribution of LungCap look like?  \n\n::: {.cell}\n\n```{.r .cell-code}\nggplot(lungcap, aes(x=LungCap))+ geom_histogram()\n```\n\n::: {.cell-output .cell-output-stderr}\n```\n`stat_bin()` using `bins = 30`. Pick better value with `binwidth`.\n```\n:::\n\n::: {.cell-output-display}\n![](KalimahMuhammad_hw1_files/figure-html/unnamed-chunk-2-1.png){width=672}\n:::\n:::\n\n\nThis is not normally distributed as there are far more observations of lower lung capacity than higher suggesting the distribution is negatively skewed.\n\n\n### 1b. Compare the probability distribution of the LungCap with respect to Males and Females? \n\n\n::: {.cell}\n\n```{.r .cell-code}\nlungcap %>%\ngroup_by(Gender)%>%\nsummarise(mean(LungCap))\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n# A tibble: 2 × 2\n  Gender `mean(LungCap)`\n  <chr>            <dbl>\n1 female            7.41\n2 male              8.31\n```\n:::\n:::\n\n\nThe average lung capacity for females is 7.41, lower than the average for males at 8.31. \n\n### 1c. Compare the mean lung capacities for smokers and non-smokers. Does it make sense?\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlungcap %>%\ngroup_by(Smoke)%>%\nsummarise(mean(LungCap))\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n# A tibble: 2 × 2\n  Smoke `mean(LungCap)`\n  <chr>           <dbl>\n1 no               7.77\n2 yes              8.65\n```\n:::\n:::\n\n\nThe mean lung capacity for non-smokers is 7.77, lower than the mean for smokers at 8.65. At first glance, this seems contradictory as one would guess smokers to have a lower lung capacity than non-smokers.The following grid displays non-smokers as having overall higher lung capacity, conflicting with the mean above.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nggplot(lungcap, aes(x = LungCap)) +\nfacet_grid(Gender ~ Smoke)+\n  geom_histogram()\n```\n\n::: {.cell-output .cell-output-stderr}\n```\n`stat_bin()` using `bins = 30`. Pick better value with `binwidth`.\n```\n:::\n\n::: {.cell-output-display}\n![](KalimahMuhammad_hw1_files/figure-html/unnamed-chunk-5-1.png){width=672}\n:::\n:::\n\n\n### 1d. Examine the relationship between Smoking and Lung Capacity within age groups: “less than or equal to 13”, “14 to 15”, “16 to 17”, and “greater than or equal to 18”.   \n\n\n::: {.cell}\n\n```{.r .cell-code}\n#Lung capacity for those age 13 and under\nlungcap %>%\nfilter(Age <= 13)%>%\ngroup_by(Smoke)%>%\nsummarise(LungCap = mean(LungCap))\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n# A tibble: 2 × 2\n  Smoke LungCap\n  <chr>   <dbl>\n1 no       6.36\n2 yes      7.20\n```\n:::\n\n```{.r .cell-code}\n#Lung capacity for those between the age of 14 to 15\nlungcap%>%\nfilter(Age== 14 | Age ==15)%>%\ngroup_by(Smoke)%>%\nsummarise(mean(LungCap))\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n# A tibble: 2 × 2\n  Smoke `mean(LungCap)`\n  <chr>           <dbl>\n1 no               9.14\n2 yes              8.39\n```\n:::\n\n```{.r .cell-code}\n#Lung capacity for those between the age of 16 to 17\nlungcap%>%\nfilter(Age==16 |Age==16)%>%\ngroup_by(Smoke)%>%\nsummarise(mean(LungCap))\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n# A tibble: 2 × 2\n  Smoke `mean(LungCap)`\n  <chr>           <dbl>\n1 no              10.1 \n2 yes              8.90\n```\n:::\n\n```{.r .cell-code}\n#Lung capacity for those 18 and older\nlungcap%>%\nfilter(Age>=18)%>%\ngroup_by(Smoke)%>%\nsummarise(mean(LungCap))\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n# A tibble: 2 × 2\n  Smoke `mean(LungCap)`\n  <chr>           <dbl>\n1 no               11.1\n2 yes              10.5\n```\n:::\n:::\n\n\n### 1e. Compare the lung capacities for smokers and non-smokers within each age group.  \nWith the exception of those age 13 years old and under, all non-smokers had a greater lung capacity than smokers. For those over the age of 18, the difference of the average in lung capacity for non-smokers to smokers was 0.55. For 16-17 year olds, the difference was the greatest at 1.16. The difference for 14-15 year olds was 0.74 and for those 13 years old and under, the difference was -0.843.\n\n### Is your answer different from the one in part c? What could possibly be going on here?\nHere the average lung capacity for non-smokers is higher than for smokers. This differs from the results of question 1c. Overall, we see lung capacity increase with age irrespective of smoking so this may contribute to the change in results. \n\n### 1f. Calculate the correlation and covariance between Lung Capacity and Age. (use the cov() and cor() functions in R). Interpret results.  \n\n\n::: {.cell}\n\n```{.r .cell-code}\ncov(lungcap$LungCap, lungcap$Age)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 8.738289\n```\n:::\n\n```{.r .cell-code}\ncor(lungcap$LungCap, lungcap$Age)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 0.8196749\n```\n:::\n:::\n\n\nThe covariance between lung capacity and age is 8.74 suggesting a positive relationship in which both variables move in the same direction (i.e. for this data set an increase in lung capacity would suggest an increase in age as well).\n\nThe correlation between lung capacity and age is 0.82 suggesting a strong positive correlation (0.82 of a potential -1 to +1).\n\n## Inmate Data\n\n\n::: {.cell}\n\n```{.r .cell-code}\npriors<- c(0, 1, 2, 3, 4)\nfrequency<- c(128, 434, 160, 64, 24)\nprison <-data.frame(priors,frequency)\nView(prison)\n```\n:::\n\n\n2a. What is the probability that a randomly selected inmate has exactly 2 prior convictions?  20%   \n\n2b. What is the probability that a randomly selected inmate has fewer than 2 prior convictions?  69%  \n\n2c. What is the probability that a randomly selected inmate has 2 or fewer prior convictions?  89%\n\n2d. What is the probability that a randomly selected inmate has more than 2 prior convictions?  11%\n\n2e. What is the expected value for the number of prior convictions? \n\n::: {.cell}\n\n```{.r .cell-code}\n((128*0)+(434*1)+(160*2)+(64*3)+(24*4))/sum(frequency)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 1.28642\n```\n:::\n:::\n\n\n2f. Calculate the variance and the standard deviation for the Prior Convictions.  \n\n\n::: {.cell}\n\n```{.r .cell-code}\nvar(prison$priors)*((810-1)/810)#calculate population variance\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 2.496914\n```\n:::\n\n```{.r .cell-code}\nsd(prison$priors)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 1.581139\n```\n:::\n:::\n",
    "supporting": [
      "KalimahMuhammad_hw1_files"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}