---
title: "finalpart1"
editor: visual
date: "10/11/22"
author: "Shoshana Buck & Roy Yoon"
tags: 
  - final project part 1
---

## Research Question

we are going to be using the [National Longitudinal Study of Adolescent to Adult Health, 1994-2018](https://www.icpsr.umich.edu/web/ICPSR/studies/21600.) we are interested in exploring the relation between education levels and health.

#Some of our research questions are:

What is the correlation and relationship between someone's education and health? Does the type and duration of education matter? Are there fields that may be "more healthy"? How does the relationship between education and health differ among the education levels/ is there a difference?

What does this data set have to say to a possible causal link between education and health? Does the data set provide apt data to establish a causal link?

## Hypothesis

We are going to be using the hypothesis from researchers **Eric R. Ride** and **Mark H. Showalter**, but using the data from the *National Longitudinal Study*

There hypothesis was: 'The empirical link between education and health is firmly established. Numerous studies document that higher levels of education are positively associated with longer life and better health throughout the lifespan...But measuring the causal links between education and health is a more challenging task." [Estimating the relation between health and education: what do we know and what do we need to know?](linkhttps://www.sciencedirect.com/science/article/pii/S0272775711000525)

We are hypothesizing that a positive correlation exists between education and health; the more education an individual receives, the better health the individual may have.

We want to look at the *National Longitudinal Study of Adolescent to Adult Health 1992-2018* and observe what other factors beyond education there is that can affect the correlation to health. What are the potential moderating or mediating variables?

## Descriptive Statistics

This is an overview of the entire data set we are still determining which specific sections we want to analyze for our final project.

According to [ICPSR](https://www.icpsr.umich.edu/web/ICPSR/studies/21600.):

**Study Purpose**: Add Health was developed in response to a mandate from the U.S. Congress to fund a study of adolescent health. Waves I and II focused on the forces that may influence adolescents' health and risk behaviors, including personal traits, families, friendships, romantic relationships, peer groups, schools, neighborhoods, and communities. As participants aged into adulthood, the scientific goals of the study expanded and evolved. Wave III explored adolescent experiences and behaviors related to decisions, behavior, and health outcomes in the transition to adulthood. Wave IV expanded to examine developmental and health trajectories across the life course of adolescence into young adulthood, using an integrative study design which combined social, behavioral, and biomedical measures data collection. Wave V aimed to track the emergence of chronic disease as the cohort aged into their 30s and early 40s.

**Study Design:** Add health is a school-based longitudinal study of a nationally-representative sample of adolescents in grates 7-12 in the United States in 1945-45. Over more than 20 years of data collection, data have been collected from adolescents, their fellow students, school administrators, parents, siblings, friends, and romantic partners through multiple data collection components. In addition, existing databases with information about respondents' neighborhoods and communities have been merged with Add Health data, including variables on income poverty, unemployment, availability and utilization of health services, crime, church membership, and social programs and policies.

**Sample:**

-   **Wave I:** The **Stage 1** in-school sample was a stratified, random sample of all high schools in the United States. A school was eligible for the sample if it included an 11th grade and had a minimum enrollment of 30 students. A feeder school -- a school that sent graduates to the high school and that included a 7th grade -- was also recruited from the community. The in-school questionnaire was administered to more than 90,000 students in grades 7 through 12. The Stage 2 in-home sample of 27,000 adolescents consisted of a core sample from each community, plus selected special over samples. Eligibility for over samples was determined by an adolescent's responses on the in-school questionnaire. Adolescents could qualify for more than one sample.

-   **Wave II**: The Wave II in-home interview surveyed almost 15,000 of the same students one year after Wave I.

-   **Wave III**: The in-home Wave III sample consists of over 15,000 Wave I respondents who could be located and re-interviewed six years later.

-   **Wave IV**: All original Wave I in-home respondents were eligible for in-home interviews at Wave IV. At Wave IV, the Add Health sample was dispersed across the nation with respondents living in all 50 states. Administrators were able to locate 92.5% of the Wave IV sample and interviewed 80.3% of eligible sample members.

-   **Wave V:** All Wave I respondents who were still living were eligible at Wave V, yielding a pool of 19,828 persons. This pool was split into three stratified random samples for the purposes of survey design testing.

-   **Time Method:** Longitudinal:Panel

-   **Universe:** Adolescents in grades 7 through 12 during the 1994-1995 school year. Respondents were geographically located in the United States.

-   **Units of Observation**: Individual

-   **Data Types:** Survey Data

-   **Time periods**: 1994 - 2018

-   **Date of Collections:** Wave 1(1994-01 - 1995-12), Wave II(1996-04 - 1996-09), Wave III(2001-04 - 2002 -04), Wave IV(2007-04 - 2009-01), Wave V(2016-03 - 2018-11)

-   **Response Rates:** Wave 1(79%), Wave 2(88.6%), Wave III(77.4%), Wave IV(80.3%), Wave V(71.8%).
