<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.2.280">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">

<meta name="author" content="Niharika Pola">
<meta name="dcterms.date" content="2022-12-13">
<meta name="description" content="Final Project">

<title>Final Project</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1.6em;
  vertical-align: middle;
}
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
    color: #aaaaaa;
  }
pre.numberSource { margin-left: 3em; border-left: 1px solid #aaaaaa;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
code span.al { color: #ff0000; font-weight: bold; } /* Alert */
code span.an { color: #60a0b0; font-weight: bold; font-style: italic; } /* Annotation */
code span.at { color: #7d9029; } /* Attribute */
code span.bn { color: #40a070; } /* BaseN */
code span.bu { color: #008000; } /* BuiltIn */
code span.cf { color: #007020; font-weight: bold; } /* ControlFlow */
code span.ch { color: #4070a0; } /* Char */
code span.cn { color: #880000; } /* Constant */
code span.co { color: #60a0b0; font-style: italic; } /* Comment */
code span.cv { color: #60a0b0; font-weight: bold; font-style: italic; } /* CommentVar */
code span.do { color: #ba2121; font-style: italic; } /* Documentation */
code span.dt { color: #902000; } /* DataType */
code span.dv { color: #40a070; } /* DecVal */
code span.er { color: #ff0000; font-weight: bold; } /* Error */
code span.ex { } /* Extension */
code span.fl { color: #40a070; } /* Float */
code span.fu { color: #06287e; } /* Function */
code span.im { color: #008000; font-weight: bold; } /* Import */
code span.in { color: #60a0b0; font-weight: bold; font-style: italic; } /* Information */
code span.kw { color: #007020; font-weight: bold; } /* Keyword */
code span.op { color: #666666; } /* Operator */
code span.ot { color: #007020; } /* Other */
code span.pp { color: #bc7a00; } /* Preprocessor */
code span.sc { color: #4070a0; } /* SpecialChar */
code span.ss { color: #bb6688; } /* SpecialString */
code span.st { color: #4070a0; } /* String */
code span.va { color: #19177c; } /* Variable */
code span.vs { color: #4070a0; } /* VerbatimString */
code span.wa { color: #60a0b0; font-weight: bold; font-style: italic; } /* Warning */
</style>


<script src="../site_libs/quarto-nav/quarto-nav.js"></script>
<script src="../site_libs/quarto-nav/headroom.min.js"></script>
<script src="../site_libs/clipboard/clipboard.min.js"></script>
<script src="../site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="../site_libs/quarto-search/fuse.min.js"></script>
<script src="../site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="../">
<link href="../images/DACSS_Round_Network.png" rel="icon" type="image/png">
<script src="../site_libs/quarto-html/quarto.js"></script>
<script src="../site_libs/quarto-html/popper.min.js"></script>
<script src="../site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="../site_libs/quarto-html/anchor.min.js"></script>
<link href="../site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="../site_libs/quarto-html/quarto-syntax-highlighting.css" rel="stylesheet" class="quarto-color-scheme" id="quarto-text-highlighting-styles">
<link href="../site_libs/quarto-html/quarto-syntax-highlighting-dark.css" rel="prefetch" class="quarto-color-scheme quarto-color-alternate" id="quarto-text-highlighting-styles">
<script src="../site_libs/bootstrap/bootstrap.min.js"></script>
<link href="../site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="../site_libs/bootstrap/bootstrap.min.css" rel="stylesheet" class="quarto-color-scheme" id="quarto-bootstrap" data-mode="light">
<link href="../site_libs/bootstrap/bootstrap-dark.min.css" rel="prefetch" class="quarto-color-scheme quarto-color-alternate" id="quarto-bootstrap" data-mode="dark">
<script id="quarto-search-options" type="application/json">{
  "location": "navbar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "end",
  "type": "overlay",
  "limit": 20,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit"
  }
}</script>

<link href="../site_libs/pagedtable-1.1/css/pagedtable.css" rel="stylesheet">
<script src="../site_libs/pagedtable-1.1/js/pagedtable.js"></script>


<link rel="stylesheet" href="styles.css">
<meta name="twitter:title" content="Final Project">
<meta name="twitter:description" content="Final Project">
<meta name="twitter:creator" content="@UMassDACSS">
<meta name="twitter:site" content="@UMassDACSS">
<meta name="twitter:card" content="summary">
</head>

<body class="nav-fixed">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
    <nav class="navbar navbar-expand-lg navbar-dark ">
      <div class="navbar-container container-fluid">
      <div class="navbar-brand-container">
    <a href="../index.html" class="navbar-brand navbar-brand-logo">
    <img src="../images/UMass White Wordmark Horiz.png" alt="" class="navbar-logo">
    </a>
  </div>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse" aria-controls="navbarCollapse" aria-expanded="false" aria-label="Toggle navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
  <span class="navbar-toggler-icon"></span>
</button>
          <div class="collapse navbar-collapse" id="navbarCollapse">
            <ul class="navbar-nav navbar-nav-scroll ms-auto">
  <li class="nav-item">
    <a class="nav-link" href="https://dacss.github.io/603_Fall_2022/">
 <span class="menu-text">Fall 2022 Posts</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="../about.html">
 <span class="menu-text">Contributors</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="https://umass.edu/sbs/dacss">
 <span class="menu-text">DACSS</span></a>
  </li>  
  <li class="nav-item compact">
    <a class="nav-link" href="https://github.com/DACSS/603_Fall_2022"><i class="bi bi-github" role="img" aria-label="GitHub">
</i> 
 <span class="menu-text"></span></a>
  </li>  
</ul>
              <div class="quarto-toggle-container">
                  <a href="" class="quarto-color-scheme-toggle nav-link" onclick="window.quartoToggleColorScheme(); return false;" title="Toggle dark mode"><i class="bi"></i></a>
              </div>
              <div id="quarto-search" class="" title="Search"></div>
          </div> <!-- /navcollapse -->
      </div> <!-- /container-fluid -->
    </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article page-navbar">
<!-- sidebar -->
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">On this page</h2>
   
  <ul>
  <li><a href="#happiness-explained-through-multiple-linear-regression." id="toc-happiness-explained-through-multiple-linear-regression." class="nav-link active" data-scroll-target="#happiness-explained-through-multiple-linear-regression.">Happiness Explained: Through Multiple Linear Regression.</a>
  <ul class="collapse">
  <li><a href="#backgroundmotivation" id="toc-backgroundmotivation" class="nav-link" data-scroll-target="#backgroundmotivation">Background/Motivation</a></li>
  <li><a href="#research-question" id="toc-research-question" class="nav-link" data-scroll-target="#research-question">Research Question</a></li>
  <li><a href="#hypothesis" id="toc-hypothesis" class="nav-link" data-scroll-target="#hypothesis">Hypothesis</a>
  <ul class="collapse">
  <li><a href="#reading-preparing-the-data-sets" id="toc-reading-preparing-the-data-sets" class="nav-link" data-scroll-target="#reading-preparing-the-data-sets">Reading &amp; Preparing the data sets</a></li>
  </ul></li>
  </ul></li>
  <li><a href="#exploratory-data-analysis" id="toc-exploratory-data-analysis" class="nav-link" data-scroll-target="#exploratory-data-analysis">Exploratory Data Analysis</a>
  <ul class="collapse">
  <li><a href="#understanding-the-correlation-between-happiness-scores-and-other-variables." id="toc-understanding-the-correlation-between-happiness-scores-and-other-variables." class="nav-link" data-scroll-target="#understanding-the-correlation-between-happiness-scores-and-other-variables.">Understanding the correlation between happiness scores and other variables.</a>
  <ul class="collapse">
  <li><a href="#happiness-score-comparison-on-different-continents" id="toc-happiness-score-comparison-on-different-continents" class="nav-link" data-scroll-target="#happiness-score-comparison-on-different-continents">Happiness score comparison on different continents</a></li>
  </ul></li>
  <li><a href="#modeling-hypothesis-testing" id="toc-modeling-hypothesis-testing" class="nav-link" data-scroll-target="#modeling-hypothesis-testing">Modeling &amp; Hypothesis testing</a>
  <ul class="collapse">
  <li><a href="#model-1" id="toc-model-1" class="nav-link" data-scroll-target="#model-1">Model-1</a></li>
  <li><a href="#model-2" id="toc-model-2" class="nav-link" data-scroll-target="#model-2">Model-2</a></li>
  <li><a href="#model-3" id="toc-model-3" class="nav-link" data-scroll-target="#model-3">Model-3</a></li>
  </ul></li>
  <li><a href="#model-comprision" id="toc-model-comprision" class="nav-link" data-scroll-target="#model-comprision">Model comprision</a></li>
  <li><a href="#regression-diagnostics" id="toc-regression-diagnostics" class="nav-link" data-scroll-target="#regression-diagnostics">Regression Diagnostics</a>
  <ul class="collapse">
  <li><a href="#model-1-1" id="toc-model-1-1" class="nav-link" data-scroll-target="#model-1-1">Model-1</a></li>
  <li><a href="#model-2-1" id="toc-model-2-1" class="nav-link" data-scroll-target="#model-2-1">Model-2</a></li>
  <li><a href="#model-3-1" id="toc-model-3-1" class="nav-link" data-scroll-target="#model-3-1">Model-3</a></li>
  </ul></li>
  <li><a href="#conclusion" id="toc-conclusion" class="nav-link" data-scroll-target="#conclusion">Conclusion</a></li>
  <li><a href="#references" id="toc-references" class="nav-link" data-scroll-target="#references">References</a></li>
  </ul></li>
  </ul>
</nav>
    </div>
<!-- main -->
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<div class="quarto-title-block"><div><h1 class="title">Final Project</h1><button type="button" class="btn code-tools-button dropdown-toggle" id="quarto-code-tools-menu" data-bs-toggle="dropdown" aria-expanded="false"><i class="bi"></i> Code</button><ul class="dropdown-menu dropdown-menu-end" aria-labelelledby="quarto-code-tools-menu"><li><a id="quarto-show-all-code" class="dropdown-item" href="javascript:void(0)" role="button">Show All Code</a></li><li><a id="quarto-hide-all-code" class="dropdown-item" href="javascript:void(0)" role="button">Hide All Code</a></li><li><hr class="dropdown-divider"></li><li><a id="quarto-view-source" class="dropdown-item" href="javascript:void(0)" role="button">View Source</a></li></ul></div></div>
  <div class="quarto-categories">
    <div class="quarto-category">Final Project</div>
  </div>
  </div>

<div>
  <div class="description">
    Final Project
  </div>
</div>


<div class="quarto-title-meta">

    <div>
    <div class="quarto-title-meta-heading">Author</div>
    <div class="quarto-title-meta-contents">
             <p>Niharika Pola </p>
          </div>
  </div>
    
    <div>
    <div class="quarto-title-meta-heading">Published</div>
    <div class="quarto-title-meta-contents">
      <p class="date">December 13, 2022</p>
    </div>
  </div>
  
    
  </div>
  

</header>

<div class="cell">
<details>
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb1"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(tidyverse)</span>
<span id="cb1-2"><a href="#cb1-2" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(ggplot2)</span>
<span id="cb1-3"><a href="#cb1-3" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(readr)</span>
<span id="cb1-4"><a href="#cb1-4" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(corrplot)</span>
<span id="cb1-5"><a href="#cb1-5" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(reshape2)</span>
<span id="cb1-6"><a href="#cb1-6" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(corrgram)</span>
<span id="cb1-7"><a href="#cb1-7" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(ggpubr)</span>
<span id="cb1-8"><a href="#cb1-8" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(caTools)</span>
<span id="cb1-9"><a href="#cb1-9" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(GGally)</span>
<span id="cb1-10"><a href="#cb1-10" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(stats)</span>
<span id="cb1-11"><a href="#cb1-11" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(ggsci)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
</div>
<section id="happiness-explained-through-multiple-linear-regression." class="level1">
<h1>Happiness Explained: Through Multiple Linear Regression.</h1>
<section id="backgroundmotivation" class="level2">
<h2 class="anchored" data-anchor-id="backgroundmotivation">Background/Motivation</h2>
<p>What is takes for a country or a continent to be happy or sad? Is it the higher GDP per capita, lower Population growth, lower Suicide rate or Urbanization? What are the factors that affect a country’s or continents overall happiness? Can we predict the happiness score? The curiosity to find answers to these questions made me explore the world happiness scores and world data by country.</p>
<p>The World Happiness Report is a landmark survey of the state of global happiness . The report continues to gain global recognition as governments, organizations and civil society increasingly use happiness indicators to inform their policy-making decisions. Leading experts across fields – economics, psychology, survey analysis, national statistics, health, public policy and more – describe how measurements of well-being can be used effectively to assess the progress of nations. The reports review the state of happiness in the world today and show how the new science of happiness explains personal and national variations in happiness.</p>
<p>The data sets that are used in this analysis are 1) <a href="https://www.kaggle.com/datasets/ajaypalsinghlo/world-happiness-report-2021">world happiness report 2021</a> and 2) kaggle’s <a href="https://www.kaggle.com/datasets/daniboy370/world-data-by-country-2020">world data by country 2020</a>. Happiness scores from first data set and few variables from the second data set are being used to analyse the following research question.</p>
</section>
<section id="research-question" class="level2">
<h2 class="anchored" data-anchor-id="research-question">Research Question</h2>
<ol type="1">
<li>What are the variables or factors that are affecting a country’s happiness?</li>
<li>To find out which model fits/accurately predicts the happiness score.</li>
</ol>
</section>
<section id="hypothesis" class="level2">
<h2 class="anchored" data-anchor-id="hypothesis">Hypothesis</h2>
<p>I wish to test the following hypothesis,</p>
<ol type="1">
<li>Higher/Better GDP per capital leads to a country’s happiness.</li>
<li>Urbanization leads to a country’s happiness.</li>
<li>Higher Life Expectancy leads to country’s happiness.</li>
</ol>
<p>This study aims to test the above hypothesis while comparing the GDP per capital and Urbanization with other variables including: Population growth, Life Expectancy, Sex-Ratio and Suicide Rate.</p>
<section id="reading-preparing-the-data-sets" class="level3">
<h3 class="anchored" data-anchor-id="reading-preparing-the-data-sets">Reading &amp; Preparing the data sets</h3>
<div class="cell">
<details>
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb2"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb2-1"><a href="#cb2-1" aria-hidden="true" tabindex="-1"></a><span class="co">#dataset-1</span></span>
<span id="cb2-2"><a href="#cb2-2" aria-hidden="true" tabindex="-1"></a>happiness <span class="ot">&lt;-</span> <span class="fu">read_csv</span>(<span class="st">"project datasets/world-happiness-report-2021.csv"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stderr">
<pre><code>Rows: 149 Columns: 20
── Column specification ────────────────────────────────────────────────────────
Delimiter: ","
chr  (2): Country name, Regional indicator
dbl (18): Ladder score, Standard error of ladder score, upperwhisker, lowerw...

ℹ Use `spec()` to retrieve the full column specification for this data.
ℹ Specify the column types or set `show_col_types = FALSE` to quiet this message.</code></pre>
</div>
<details>
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb4"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb4-1"><a href="#cb4-1" aria-hidden="true" tabindex="-1"></a>hap_sc <span class="ot">&lt;-</span> <span class="fu">select</span>(happiness, <span class="st">"Country name"</span>, <span class="st">"Ladder score"</span>)</span>
<span id="cb4-2"><a href="#cb4-2" aria-hidden="true" tabindex="-1"></a>hap_sc <span class="ot">&lt;-</span> <span class="fu">rename</span>(hap_sc, <span class="st">"Country"</span><span class="ot">=</span><span class="st">"Country name"</span>, <span class="st">"Happiness"</span><span class="ot">=</span><span class="st">"Ladder score"</span>)</span>
<span id="cb4-3"><a href="#cb4-3" aria-hidden="true" tabindex="-1"></a><span class="fu">colnames</span>(hap_sc)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>[1] "Country"   "Happiness"</code></pre>
</div>
<details>
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb6"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb6-1"><a href="#cb6-1" aria-hidden="true" tabindex="-1"></a><span class="co">#datasets from world data by country</span></span>
<span id="cb6-2"><a href="#cb6-2" aria-hidden="true" tabindex="-1"></a>GDP_per_capita <span class="ot">&lt;-</span> <span class="fu">read_csv</span>(<span class="st">"project datasets/GDP per capita.csv"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stderr">
<pre><code>Rows: 191 Columns: 3
── Column specification ────────────────────────────────────────────────────────
Delimiter: ","
chr (2): Country, ISO-code
dbl (1): GDP per capita

ℹ Use `spec()` to retrieve the full column specification for this data.
ℹ Specify the column types or set `show_col_types = FALSE` to quiet this message.</code></pre>
</div>
<details>
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb8"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb8-1"><a href="#cb8-1" aria-hidden="true" tabindex="-1"></a>Urbanization_rate <span class="ot">&lt;-</span> <span class="fu">read_csv</span>(<span class="st">"project datasets/Urbanization rate.csv"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stderr">
<pre><code>Rows: 218 Columns: 3
── Column specification ────────────────────────────────────────────────────────
Delimiter: ","
chr (2): Country, ISO-code
dbl (1): Urbanization rate

ℹ Use `spec()` to retrieve the full column specification for this data.
ℹ Specify the column types or set `show_col_types = FALSE` to quiet this message.</code></pre>
</div>
<details>
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb10"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb10-1"><a href="#cb10-1" aria-hidden="true" tabindex="-1"></a>Population_growth <span class="ot">&lt;-</span> <span class="fu">read_csv</span>(<span class="st">"project datasets/Population growth.csv"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stderr">
<pre><code>Rows: 207 Columns: 3
── Column specification ────────────────────────────────────────────────────────
Delimiter: ","
chr (2): Country, ISO-code
dbl (1): Population growth

ℹ Use `spec()` to retrieve the full column specification for this data.
ℹ Specify the column types or set `show_col_types = FALSE` to quiet this message.</code></pre>
</div>
<details>
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb12"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb12-1"><a href="#cb12-1" aria-hidden="true" tabindex="-1"></a>Life_expectancy <span class="ot">&lt;-</span> <span class="fu">read_csv</span>(<span class="st">"project datasets/Life expectancy.csv"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stderr">
<pre><code>Rows: 185 Columns: 3
── Column specification ────────────────────────────────────────────────────────
Delimiter: ","
chr (2): Country, ISO-code
dbl (1): Life expectancy

ℹ Use `spec()` to retrieve the full column specification for this data.
ℹ Specify the column types or set `show_col_types = FALSE` to quiet this message.</code></pre>
</div>
<details>
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb14"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb14-1"><a href="#cb14-1" aria-hidden="true" tabindex="-1"></a>Suicide_rate <span class="ot">&lt;-</span> <span class="fu">read_csv</span>(<span class="st">"project datasets/Suicide rate.csv"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stderr">
<pre><code>Rows: 182 Columns: 3
── Column specification ────────────────────────────────────────────────────────
Delimiter: ","
chr (2): Country, ISO-code
dbl (1): Suicide rate

ℹ Use `spec()` to retrieve the full column specification for this data.
ℹ Specify the column types or set `show_col_types = FALSE` to quiet this message.</code></pre>
</div>
<details>
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb16"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb16-1"><a href="#cb16-1" aria-hidden="true" tabindex="-1"></a>Sex_ratio <span class="ot">&lt;-</span> <span class="fu">read_csv</span>(<span class="st">"project datasets/Sex-ratio.csv"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stderr">
<pre><code>Rows: 226 Columns: 3
── Column specification ────────────────────────────────────────────────────────
Delimiter: ","
chr (2): Country, ISO-code
dbl (1): Sex-ratio

ℹ Use `spec()` to retrieve the full column specification for this data.
ℹ Specify the column types or set `show_col_types = FALSE` to quiet this message.</code></pre>
</div>
<details>
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb18"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb18-1"><a href="#cb18-1" aria-hidden="true" tabindex="-1"></a><span class="co">#merging the above datasets by country and iso code</span></span>
<span id="cb18-2"><a href="#cb18-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb18-3"><a href="#cb18-3" aria-hidden="true" tabindex="-1"></a>world_data <span class="ot">&lt;-</span> <span class="fu">merge</span>(GDP_per_capita, Urbanization_rate)</span>
<span id="cb18-4"><a href="#cb18-4" aria-hidden="true" tabindex="-1"></a>world_data <span class="ot">&lt;-</span> <span class="fu">merge</span>(world_data, Population_growth)</span>
<span id="cb18-5"><a href="#cb18-5" aria-hidden="true" tabindex="-1"></a>world_data <span class="ot">&lt;-</span> <span class="fu">merge</span>(world_data, Life_expectancy)</span>
<span id="cb18-6"><a href="#cb18-6" aria-hidden="true" tabindex="-1"></a>world_data <span class="ot">&lt;-</span> <span class="fu">merge</span>(world_data, Suicide_rate)</span>
<span id="cb18-7"><a href="#cb18-7" aria-hidden="true" tabindex="-1"></a>world_data <span class="ot">&lt;-</span> <span class="fu">merge</span>(world_data, Sex_ratio)</span>
<span id="cb18-8"><a href="#cb18-8" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb18-9"><a href="#cb18-9" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb18-10"><a href="#cb18-10" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb18-11"><a href="#cb18-11" aria-hidden="true" tabindex="-1"></a><span class="co">#merging happiness scores and world data</span></span>
<span id="cb18-12"><a href="#cb18-12" aria-hidden="true" tabindex="-1"></a>happy <span class="ot">&lt;-</span> <span class="fu">merge</span>(world_data, hap_sc)</span>
<span id="cb18-13"><a href="#cb18-13" aria-hidden="true" tabindex="-1"></a>happy <span class="ot">&lt;-</span> <span class="fu">rename</span>(happy, <span class="st">"GDP.per.capita"</span><span class="ot">=</span><span class="st">"GDP per capita"</span>, <span class="st">"urbanization.rate"</span><span class="ot">=</span><span class="st">"Urbanization rate"</span>, <span class="st">"Population.growth"</span><span class="ot">=</span><span class="st">"Population growth"</span>, <span class="st">"Life.expectancy"</span><span class="ot">=</span><span class="st">"Life expectancy"</span>, <span class="st">"Suicide.rate"</span><span class="ot">=</span><span class="st">"Suicide rate"</span>, <span class="st">"Sex.ratio"</span><span class="ot">=</span><span class="st">"Sex-ratio"</span>)</span>
<span id="cb18-14"><a href="#cb18-14" aria-hidden="true" tabindex="-1"></a><span class="fu">str</span>(happy)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>'data.frame':   199 obs. of  9 variables:
 $ Country          : chr  "Afghanistan" "Algeria" "Argentina" "Armenia" ...
 $ ISO-code         : chr  "AFG" "DZA" "ARG" "ARM" ...
 $ GDP.per.capita   : num  2182 16091 19971 11845 54799 ...
 $ urbanization.rate: num  26 73.7 92.1 63.3 86.2 58.7 56.4 89.5 38.2 79.5 ...
 $ Population.growth: num  2.41 1.89 0.88 0.17 1.6 0.46 1.35 1.92 1.19 -0.1 ...
 $ Life.expectancy  : num  64.5 76.7 76.5 74.9 83.3 81.4 72.9 77.2 72.3 74.6 ...
 $ Suicide.rate     : num  6.4 3.3 9.1 5.7 11.7 11.4 2.6 5.7 6.1 21.4 ...
 $ Sex.ratio        : num  1.03 1.03 0.98 0.95 0.99 0.96 0.98 1.53 0.97 0.87 ...
 $ Happiness        : num  2.52 4.89 5.93 5.28 7.18 ...</code></pre>
</div>
</div>
<div class="cell">
<details>
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb20"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb20-1"><a href="#cb20-1" aria-hidden="true" tabindex="-1"></a><span class="co">#adding continents data to final dataset</span></span>
<span id="cb20-2"><a href="#cb20-2" aria-hidden="true" tabindex="-1"></a>happy<span class="sc">$</span>Continent <span class="ot">&lt;-</span> <span class="cn">NA</span></span>
<span id="cb20-3"><a href="#cb20-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb20-4"><a href="#cb20-4" aria-hidden="true" tabindex="-1"></a>happy<span class="sc">$</span>Continent[<span class="fu">which</span>(happy<span class="sc">$</span>Country <span class="sc">%in%</span> <span class="fu">c</span>(<span class="st">"Israel"</span>, <span class="st">"United Arab Emirates"</span>, <span class="st">"Singapore"</span>, <span class="st">"Thailand"</span>, <span class="st">"Taiwan Province of China"</span>,</span>
<span id="cb20-5"><a href="#cb20-5" aria-hidden="true" tabindex="-1"></a>                                   <span class="st">"Qatar"</span>, <span class="st">"Saudi Arabia"</span>, <span class="st">"Kuwait"</span>, <span class="st">"Bahrain"</span>, <span class="st">"Malaysia"</span>, <span class="st">"Uzbekistan"</span>, <span class="st">"Japan"</span>,</span>
<span id="cb20-6"><a href="#cb20-6" aria-hidden="true" tabindex="-1"></a>                                   <span class="st">"South Korea"</span>, <span class="st">"Turkmenistan"</span>, <span class="st">"Kazakhstan"</span>, <span class="st">"Turkey"</span>, <span class="st">"Hong Kong S.A.R., China"</span>, <span class="st">"Philippines"</span>,</span>
<span id="cb20-7"><a href="#cb20-7" aria-hidden="true" tabindex="-1"></a>                                   <span class="st">"Jordan"</span>, <span class="st">"China"</span>, <span class="st">"Pakistan"</span>, <span class="st">"Indonesia"</span>, <span class="st">"Azerbaijan"</span>, <span class="st">"Lebanon"</span>, <span class="st">"Vietnam"</span>,</span>
<span id="cb20-8"><a href="#cb20-8" aria-hidden="true" tabindex="-1"></a>                                   <span class="st">"Tajikistan"</span>, <span class="st">"Bhutan"</span>, <span class="st">"Kyrgyzstan"</span>, <span class="st">"Nepal"</span>, <span class="st">"Mongolia"</span>, <span class="st">"Palestinian Territories"</span>,</span>
<span id="cb20-9"><a href="#cb20-9" aria-hidden="true" tabindex="-1"></a>                                   <span class="st">"Iran"</span>, <span class="st">"Bangladesh"</span>, <span class="st">"Myanmar"</span>, <span class="st">"Iraq"</span>, <span class="st">"Sri Lanka"</span>, <span class="st">"Armenia"</span>, <span class="st">"India"</span>, <span class="st">"Georgia"</span>,</span>
<span id="cb20-10"><a href="#cb20-10" aria-hidden="true" tabindex="-1"></a>                                   <span class="st">"Cambodia"</span>, <span class="st">"Afghanistan"</span>, <span class="st">"Yemen"</span>, <span class="st">"Syria"</span>))] <span class="ot">&lt;-</span> <span class="st">"Asia"</span></span>
<span id="cb20-11"><a href="#cb20-11" aria-hidden="true" tabindex="-1"></a>happy<span class="sc">$</span>Continent[<span class="fu">which</span>(happy<span class="sc">$</span>Country <span class="sc">%in%</span> <span class="fu">c</span>(<span class="st">"Norway"</span>, <span class="st">"Denmark"</span>, <span class="st">"Iceland"</span>, <span class="st">"Switzerland"</span>, <span class="st">"Finland"</span>,</span>
<span id="cb20-12"><a href="#cb20-12" aria-hidden="true" tabindex="-1"></a>                                   <span class="st">"Netherlands"</span>, <span class="st">"Sweden"</span>, <span class="st">"Austria"</span>, <span class="st">"Ireland"</span>, <span class="st">"Germany"</span>,</span>
<span id="cb20-13"><a href="#cb20-13" aria-hidden="true" tabindex="-1"></a>                                   <span class="st">"Belgium"</span>, <span class="st">"Luxembourg"</span>, <span class="st">"United Kingdom"</span>, <span class="st">"Czech Republic"</span>,</span>
<span id="cb20-14"><a href="#cb20-14" aria-hidden="true" tabindex="-1"></a>                                   <span class="st">"Malta"</span>, <span class="st">"France"</span>, <span class="st">"Spain"</span>, <span class="st">"Slovakia"</span>, <span class="st">"Poland"</span>, <span class="st">"Italy"</span>,</span>
<span id="cb20-15"><a href="#cb20-15" aria-hidden="true" tabindex="-1"></a>                                   <span class="st">"Russia"</span>, <span class="st">"Lithuania"</span>, <span class="st">"Latvia"</span>, <span class="st">"Moldova"</span>, <span class="st">"Romania"</span>,</span>
<span id="cb20-16"><a href="#cb20-16" aria-hidden="true" tabindex="-1"></a>                                   <span class="st">"Slovenia"</span>, <span class="st">"North Cyprus"</span>, <span class="st">"Cyprus"</span>, <span class="st">"Estonia"</span>, <span class="st">"Belarus"</span>,</span>
<span id="cb20-17"><a href="#cb20-17" aria-hidden="true" tabindex="-1"></a>                                   <span class="st">"Serbia"</span>, <span class="st">"Hungary"</span>, <span class="st">"Croatia"</span>, <span class="st">"Kosovo"</span>, <span class="st">"Montenegro"</span>,</span>
<span id="cb20-18"><a href="#cb20-18" aria-hidden="true" tabindex="-1"></a>                                   <span class="st">"Greece"</span>, <span class="st">"Portugal"</span>, <span class="st">"Bosnia and Herzegovina"</span>, <span class="st">"Macedonia"</span>,</span>
<span id="cb20-19"><a href="#cb20-19" aria-hidden="true" tabindex="-1"></a>                                   <span class="st">"Bulgaria"</span>, <span class="st">"Albania"</span>, <span class="st">"Ukraine"</span>))] <span class="ot">&lt;-</span> <span class="st">"Europe"</span></span>
<span id="cb20-20"><a href="#cb20-20" aria-hidden="true" tabindex="-1"></a>happy<span class="sc">$</span>Continent[<span class="fu">which</span>(happy<span class="sc">$</span>Country <span class="sc">%in%</span> <span class="fu">c</span>(<span class="st">"Canada"</span>, <span class="st">"Costa Rica"</span>, <span class="st">"United States"</span>, <span class="st">"Mexico"</span>,  </span>
<span id="cb20-21"><a href="#cb20-21" aria-hidden="true" tabindex="-1"></a>                                   <span class="st">"Panama"</span>,<span class="st">"Trinidad and Tobago"</span>, <span class="st">"El Salvador"</span>, <span class="st">"Belize"</span>, <span class="st">"Guatemala"</span>,</span>
<span id="cb20-22"><a href="#cb20-22" aria-hidden="true" tabindex="-1"></a>                                   <span class="st">"Jamaica"</span>, <span class="st">"Nicaragua"</span>, <span class="st">"Dominican Republic"</span>, <span class="st">"Honduras"</span>,</span>
<span id="cb20-23"><a href="#cb20-23" aria-hidden="true" tabindex="-1"></a>                                   <span class="st">"Haiti"</span>))] <span class="ot">&lt;-</span> <span class="st">"North America"</span></span>
<span id="cb20-24"><a href="#cb20-24" aria-hidden="true" tabindex="-1"></a>happy<span class="sc">$</span>Continent[<span class="fu">which</span>(happy<span class="sc">$</span>Country <span class="sc">%in%</span> <span class="fu">c</span>(<span class="st">"Chile"</span>, <span class="st">"Brazil"</span>, <span class="st">"Argentina"</span>, <span class="st">"Uruguay"</span>,</span>
<span id="cb20-25"><a href="#cb20-25" aria-hidden="true" tabindex="-1"></a>                                   <span class="st">"Colombia"</span>, <span class="st">"Ecuador"</span>, <span class="st">"Bolivia"</span>, <span class="st">"Peru"</span>,</span>
<span id="cb20-26"><a href="#cb20-26" aria-hidden="true" tabindex="-1"></a>                                   <span class="st">"Paraguay"</span>, <span class="st">"Venezuela"</span>))] <span class="ot">&lt;-</span> <span class="st">"South America"</span></span>
<span id="cb20-27"><a href="#cb20-27" aria-hidden="true" tabindex="-1"></a>happy<span class="sc">$</span>Continent[<span class="fu">which</span>(happy<span class="sc">$</span>Country <span class="sc">%in%</span> <span class="fu">c</span>(<span class="st">"New Zealand"</span>, <span class="st">"Australia"</span>))] <span class="ot">&lt;-</span> <span class="st">"Australia"</span></span>
<span id="cb20-28"><a href="#cb20-28" aria-hidden="true" tabindex="-1"></a>happy<span class="sc">$</span>Continent[<span class="fu">which</span>(<span class="fu">is.na</span>(happy<span class="sc">$</span>Continent))] <span class="ot">&lt;-</span> <span class="st">"Africa"</span></span>
<span id="cb20-29"><a href="#cb20-29" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb20-30"><a href="#cb20-30" aria-hidden="true" tabindex="-1"></a><span class="co"># Moving the continent column's position in the dataset to the second column</span></span>
<span id="cb20-31"><a href="#cb20-31" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb20-32"><a href="#cb20-32" aria-hidden="true" tabindex="-1"></a>happy <span class="ot">&lt;-</span> happy <span class="sc">%&gt;%</span> <span class="fu">select</span>(Country,Continent, <span class="fu">everything</span>())</span>
<span id="cb20-33"><a href="#cb20-33" aria-hidden="true" tabindex="-1"></a>happy <span class="ot">&lt;-</span> happy[<span class="sc">!</span><span class="fu">duplicated</span>(happy), ]</span>
<span id="cb20-34"><a href="#cb20-34" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb20-35"><a href="#cb20-35" aria-hidden="true" tabindex="-1"></a><span class="co">#Renaming the final dataframe to happy</span></span>
<span id="cb20-36"><a href="#cb20-36" aria-hidden="true" tabindex="-1"></a><span class="fu">view</span>(happy)</span>
<span id="cb20-37"><a href="#cb20-37" aria-hidden="true" tabindex="-1"></a>happy <span class="ot">&lt;-</span> happy[<span class="sc">-</span>(<span class="dv">48</span><span class="sc">:</span><span class="dv">110</span>), ]</span>
<span id="cb20-38"><a href="#cb20-38" aria-hidden="true" tabindex="-1"></a><span class="fu">str</span>(happy)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>'data.frame':   136 obs. of  10 variables:
 $ Country          : chr  "Afghanistan" "Algeria" "Argentina" "Armenia" ...
 $ Continent        : chr  "Asia" "Africa" "South America" "Asia" ...
 $ ISO-code         : chr  "AFG" "DZA" "ARG" "ARM" ...
 $ GDP.per.capita   : num  2182 16091 19971 11845 54799 ...
 $ urbanization.rate: num  26 73.7 92.1 63.3 86.2 58.7 56.4 89.5 38.2 79.5 ...
 $ Population.growth: num  2.41 1.89 0.88 0.17 1.6 0.46 1.35 1.92 1.19 -0.1 ...
 $ Life.expectancy  : num  64.5 76.7 76.5 74.9 83.3 81.4 72.9 77.2 72.3 74.6 ...
 $ Suicide.rate     : num  6.4 3.3 9.1 5.7 11.7 11.4 2.6 5.7 6.1 21.4 ...
 $ Sex.ratio        : num  1.03 1.03 0.98 0.95 0.99 0.96 0.98 1.53 0.97 0.87 ...
 $ Happiness        : num  2.52 4.89 5.93 5.28 7.18 ...</code></pre>
</div>
</div>
<p>The final data set “happy” consists of 12 variables and 136 observations. We can start the analysis now.</p>
</section>
</section>
</section>
<section id="exploratory-data-analysis" class="level1">
<h1>Exploratory Data Analysis</h1>
<section id="understanding-the-correlation-between-happiness-scores-and-other-variables." class="level2">
<h2 class="anchored" data-anchor-id="understanding-the-correlation-between-happiness-scores-and-other-variables.">Understanding the correlation between happiness scores and other variables.</h2>
<div class="cell">
<details>
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb22"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb22-1"><a href="#cb22-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Create a correlation plot</span></span>
<span id="cb22-2"><a href="#cb22-2" aria-hidden="true" tabindex="-1"></a><span class="fu">ggcorr</span>(happy, <span class="at">label =</span> <span class="cn">TRUE</span>, <span class="at">label_round =</span> <span class="dv">2</span>, <span class="at">label_size =</span> <span class="fl">3.5</span>, <span class="at">size =</span> <span class="dv">4</span>, <span class="at">hjust =</span> .<span class="dv">85</span>) <span class="sc">+</span></span>
<span id="cb22-3"><a href="#cb22-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ggtitle</span>(<span class="st">"Plot- 1: Correlation Heatmap"</span>) <span class="sc">+</span></span>
<span id="cb22-4"><a href="#cb22-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme</span>(<span class="at">plot.title =</span> <span class="fu">element_text</span>(<span class="at">hjust =</span> <span class="fl">0.5</span>))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stderr">
<pre><code>Warning in ggcorr(happy, label = TRUE, label_round = 2, label_size = 3.5, : data
in column(s) 'Country', 'Continent', 'ISO-code' are not numeric and were ignored</code></pre>
</div>
<div class="cell-output-display">
<p><img src="Final-Project_World-Happiness_files/figure-html/unnamed-chunk-4-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<p>Observations from the correlation plot:</p>
<p>The happiness score is,</p>
<ul>
<li><p>Strongly correlating with GDP per capita, Urbanization rate and Life expectancy.</p></li>
<li><p>Inversely correlated with suicidal rate and population growth.</p></li>
<li><p>No correlation with sex ratio.</p></li>
</ul>
<div class="cell">
<details>
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb24"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb24-1"><a href="#cb24-1" aria-hidden="true" tabindex="-1"></a><span class="co">#plotting the happiness data on world map</span></span>
<span id="cb24-2"><a href="#cb24-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb24-3"><a href="#cb24-3" aria-hidden="true" tabindex="-1"></a>plot_2 <span class="ot">&lt;-</span> <span class="fu">select</span>(happy, <span class="st">"Continent"</span>, <span class="st">"Country"</span>, <span class="st">"Happiness"</span>)</span>
<span id="cb24-4"><a href="#cb24-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb24-5"><a href="#cb24-5" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(maps)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stderr">
<pre><code>
Attaching package: 'maps'</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>The following object is masked from 'package:purrr':

    map</code></pre>
</div>
<details>
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb27"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb27-1"><a href="#cb27-1" aria-hidden="true" tabindex="-1"></a>world.data <span class="ot">&lt;-</span> <span class="fu">map_data</span>(<span class="st">"world"</span>)</span>
<span id="cb27-2"><a href="#cb27-2" aria-hidden="true" tabindex="-1"></a>map.world_joined <span class="ot">&lt;-</span> <span class="fu">left_join</span>(world.data, plot_2, <span class="at">by =</span> <span class="fu">c</span>(<span class="st">'region'</span><span class="ot">=</span><span class="st">'Country'</span>))</span>
<span id="cb27-3"><a href="#cb27-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb27-4"><a href="#cb27-4" aria-hidden="true" tabindex="-1"></a>map1 <span class="ot">&lt;-</span> <span class="fu">ggplot</span>(map.world_joined, <span class="fu">aes</span>(<span class="at">x=</span>long, <span class="at">y=</span>lat, <span class="at">group=</span>group)) <span class="sc">+</span></span>
<span id="cb27-5"><a href="#cb27-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_polygon</span>(<span class="fu">aes</span>(<span class="at">fill=</span>Happiness), <span class="at">color=</span><span class="st">"black"</span>)</span>
<span id="cb27-6"><a href="#cb27-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb27-7"><a href="#cb27-7" aria-hidden="true" tabindex="-1"></a>map2 <span class="ot">&lt;-</span> map1 <span class="sc">+</span> <span class="fu">scale_fill_gradient</span>(<span class="at">name =</span> <span class="st">"Happiness Score"</span>, <span class="at">low =</span> <span class="st">"yellow"</span>, <span class="at">high =</span> <span class="st">"red"</span>, <span class="at">na.value =</span> <span class="st">"grey50"</span>) <span class="sc">+</span></span>
<span id="cb27-8"><a href="#cb27-8" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme</span>(<span class="at">axis.text.x =</span> <span class="fu">element_blank</span>(), </span>
<span id="cb27-9"><a href="#cb27-9" aria-hidden="true" tabindex="-1"></a>        <span class="at">axis.text.y =</span> <span class="fu">element_blank</span>(),</span>
<span id="cb27-10"><a href="#cb27-10" aria-hidden="true" tabindex="-1"></a>        <span class="at">axis.ticks =</span> <span class="fu">element_blank</span>(),</span>
<span id="cb27-11"><a href="#cb27-11" aria-hidden="true" tabindex="-1"></a>        <span class="at">axis.title.y =</span> <span class="fu">element_blank</span>(),</span>
<span id="cb27-12"><a href="#cb27-12" aria-hidden="true" tabindex="-1"></a>        <span class="at">axis.title.x =</span> <span class="fu">element_blank</span>(),</span>
<span id="cb27-13"><a href="#cb27-13" aria-hidden="true" tabindex="-1"></a>        <span class="at">rect =</span> <span class="fu">element_blank</span>())</span>
<span id="cb27-14"><a href="#cb27-14" aria-hidden="true" tabindex="-1"></a>map2</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output-display">
<p><img src="Final-Project_World-Happiness_files/figure-html/unnamed-chunk-5-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<p>North America, Europe and Australia appear to be the happiest.</p>
<p>South America, North Asia, Western Africa and countries/islands in the indian ocean appear to be happy on average.</p>
<p>South Africa, India are unhappy and of course Afghanistan is the unhappiest country in the world.</p>
<section id="happiness-score-comparison-on-different-continents" class="level3">
<h3 class="anchored" data-anchor-id="happiness-score-comparison-on-different-continents">Happiness score comparison on different continents</h3>
<div class="cell">
<details>
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb28"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb28-1"><a href="#cb28-1" aria-hidden="true" tabindex="-1"></a><span class="do">####### Happiness score for each continent</span></span>
<span id="cb28-2"><a href="#cb28-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb28-3"><a href="#cb28-3" aria-hidden="true" tabindex="-1"></a>gg1 <span class="ot">&lt;-</span> <span class="fu">ggplot</span>(happy,</span>
<span id="cb28-4"><a href="#cb28-4" aria-hidden="true" tabindex="-1"></a>              <span class="fu">aes</span>(<span class="at">x=</span>Continent,</span>
<span id="cb28-5"><a href="#cb28-5" aria-hidden="true" tabindex="-1"></a>                  <span class="at">y=</span>Happiness,</span>
<span id="cb28-6"><a href="#cb28-6" aria-hidden="true" tabindex="-1"></a>                  <span class="at">color=</span>Continent))<span class="sc">+</span></span>
<span id="cb28-7"><a href="#cb28-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_point</span>() <span class="sc">+</span> <span class="fu">theme_bw</span>() <span class="sc">+</span></span>
<span id="cb28-8"><a href="#cb28-8" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme</span>(<span class="at">axis.title =</span> <span class="fu">element_text</span>(<span class="at">family =</span> <span class="st">"Helvetica"</span>, <span class="at">size =</span> (<span class="dv">8</span>)))</span>
<span id="cb28-9"><a href="#cb28-9" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb28-10"><a href="#cb28-10" aria-hidden="true" tabindex="-1"></a>gg2 <span class="ot">&lt;-</span> <span class="fu">ggplot</span>(happy , <span class="fu">aes</span>(<span class="at">x =</span> Continent, <span class="at">y =</span> Happiness)) <span class="sc">+</span></span>
<span id="cb28-11"><a href="#cb28-11" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_boxplot</span>(<span class="fu">aes</span>(<span class="at">fill=</span>Continent)) <span class="sc">+</span> <span class="fu">theme_bw</span>() <span class="sc">+</span></span>
<span id="cb28-12"><a href="#cb28-12" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme</span>(<span class="at">axis.title =</span> <span class="fu">element_text</span>(<span class="at">family =</span> <span class="st">"Helvetica"</span>, <span class="at">size =</span> (<span class="dv">8</span>)))</span>
<span id="cb28-13"><a href="#cb28-13" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb28-14"><a href="#cb28-14" aria-hidden="true" tabindex="-1"></a>gg3 <span class="ot">&lt;-</span> <span class="fu">ggplot</span>(happy,<span class="fu">aes</span>(<span class="at">x=</span>Continent,<span class="at">y=</span>Happiness))<span class="sc">+</span></span>
<span id="cb28-15"><a href="#cb28-15" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_violin</span>(<span class="fu">aes</span>(<span class="at">fill=</span>Continent),<span class="at">alpha=</span><span class="fl">0.7</span>)<span class="sc">+</span> <span class="fu">theme_bw</span>() <span class="sc">+</span></span>
<span id="cb28-16"><a href="#cb28-16" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme</span>(<span class="at">axis.title =</span> <span class="fu">element_text</span>(<span class="at">family =</span> <span class="st">"Helvetica"</span>, <span class="at">size =</span> (<span class="dv">8</span>)))</span>
<span id="cb28-17"><a href="#cb28-17" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb28-18"><a href="#cb28-18" aria-hidden="true" tabindex="-1"></a><span class="co"># Compute descriptive statistics by groups</span></span>
<span id="cb28-19"><a href="#cb28-19" aria-hidden="true" tabindex="-1"></a>stable <span class="ot">&lt;-</span> <span class="fu">desc_statby</span>(happy, <span class="at">measure.var =</span> <span class="st">"Happiness"</span>,</span>
<span id="cb28-20"><a href="#cb28-20" aria-hidden="true" tabindex="-1"></a>                      <span class="at">grps =</span> <span class="st">"Continent"</span>)</span>
<span id="cb28-21"><a href="#cb28-21" aria-hidden="true" tabindex="-1"></a>stable <span class="ot">&lt;-</span> stable[, <span class="fu">c</span>(<span class="st">"Continent"</span>,<span class="st">"mean"</span>,<span class="st">"median"</span>)]</span>
<span id="cb28-22"><a href="#cb28-22" aria-hidden="true" tabindex="-1"></a><span class="fu">names</span>(stable) <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="st">"Continent"</span>, <span class="st">"Mean of happiness score"</span>,<span class="st">"Median of happiness score"</span>)</span>
<span id="cb28-23"><a href="#cb28-23" aria-hidden="true" tabindex="-1"></a><span class="co"># Summary table plot</span></span>
<span id="cb28-24"><a href="#cb28-24" aria-hidden="true" tabindex="-1"></a>stable.p <span class="ot">&lt;-</span> <span class="fu">ggtexttable</span>(stable,<span class="at">rows =</span> <span class="cn">NULL</span>, </span>
<span id="cb28-25"><a href="#cb28-25" aria-hidden="true" tabindex="-1"></a>                         <span class="at">theme =</span> <span class="fu">ttheme</span>(<span class="st">"classic"</span>))</span>
<span id="cb28-26"><a href="#cb28-26" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb28-27"><a href="#cb28-27" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb28-28"><a href="#cb28-28" aria-hidden="true" tabindex="-1"></a><span class="fu">ggarrange</span>(gg1, gg2, <span class="at">ncol =</span> <span class="dv">1</span>, <span class="at">nrow =</span> <span class="dv">2</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output-display">
<p><img src="Final-Project_World-Happiness_files/figure-html/unnamed-chunk-6-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<div class="cell">
<details>
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb29"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb29-1"><a href="#cb29-1" aria-hidden="true" tabindex="-1"></a><span class="fu">ggarrange</span>(gg3, stable.p, <span class="at">ncol =</span> <span class="dv">1</span>, <span class="at">nrow =</span> <span class="dv">2</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output-display">
<p><img src="Final-Project_World-Happiness_files/figure-html/unnamed-chunk-7-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<p>As we have seen before, Australia has the highest median happiness score. Europe, South America, and North America are in the second place regarding median happiness score. Asia has the lowest median after Africa. We can see the range of happiness score for different continents, and also the concentration of happiness score.</p>
<p>Let’s see the correlation between happiness score and 3 major factors in the happiness data set that are GDP per capita, Life Expectancy, Urbanization rate to understand how they are varying.</p>
<div class="cell">
<details>
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb30"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb30-1"><a href="#cb30-1" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(<span class="fu">subset</span>(happy, happy<span class="sc">$</span>Continent <span class="sc">!=</span> <span class="st">"Australia"</span>), <span class="fu">aes</span>(<span class="at">x =</span>  GDP.per.capita, <span class="at">y =</span> Happiness)) <span class="sc">+</span> </span>
<span id="cb30-2"><a href="#cb30-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_point</span>(<span class="fu">aes</span>(<span class="at">color=</span>Continent), <span class="at">size =</span> <span class="dv">3</span>, <span class="at">alpha =</span> <span class="fl">0.8</span>) <span class="sc">+</span>  </span>
<span id="cb30-3"><a href="#cb30-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_smooth</span>(<span class="fu">aes</span>(<span class="at">color =</span> Continent, <span class="at">fill =</span> Continent), </span>
<span id="cb30-4"><a href="#cb30-4" aria-hidden="true" tabindex="-1"></a>              <span class="at">method =</span> <span class="st">"lm"</span>, <span class="at">fullrange =</span> <span class="cn">TRUE</span>) <span class="sc">+</span></span>
<span id="cb30-5"><a href="#cb30-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">facet_wrap</span>(<span class="sc">~</span>Continent) <span class="sc">+</span></span>
<span id="cb30-6"><a href="#cb30-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_bw</span>() <span class="sc">+</span> <span class="fu">labs</span>(<span class="at">title =</span> <span class="st">"Scatter plot with regression line Happiness vs GDP per capita"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stderr">
<pre><code>`geom_smooth()` using formula = 'y ~ x'</code></pre>
</div>
<div class="cell-output-display">
<p><img src="Final-Project_World-Happiness_files/figure-html/unnamed-chunk-8-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<p>The correlation between GDP per capita and happiness score in Europe, North America, and Asia is more significant than the other continents. Worth mentioning that we will not take Australia into account because there are just two countries in Australia and creating scatter plot with the regression line for this continent will not give us any insight.</p>
<div class="cell">
<details>
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb32"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb32-1"><a href="#cb32-1" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(<span class="fu">subset</span>(happy, happy<span class="sc">$</span>Continent <span class="sc">!=</span> <span class="st">"Australia"</span>), <span class="fu">aes</span>(<span class="at">x =</span>  urbanization.rate, <span class="at">y =</span> Happiness)) <span class="sc">+</span> </span>
<span id="cb32-2"><a href="#cb32-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_point</span>(<span class="fu">aes</span>(<span class="at">color=</span>Continent), <span class="at">size =</span> <span class="dv">3</span>, <span class="at">alpha =</span> <span class="fl">0.8</span>) <span class="sc">+</span>  </span>
<span id="cb32-3"><a href="#cb32-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_smooth</span>(<span class="fu">aes</span>(<span class="at">color =</span> Continent, <span class="at">fill =</span> Continent), </span>
<span id="cb32-4"><a href="#cb32-4" aria-hidden="true" tabindex="-1"></a>              <span class="at">method =</span> <span class="st">"lm"</span>, <span class="at">fullrange =</span> <span class="cn">TRUE</span>) <span class="sc">+</span></span>
<span id="cb32-5"><a href="#cb32-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">facet_wrap</span>(<span class="sc">~</span>Continent) <span class="sc">+</span></span>
<span id="cb32-6"><a href="#cb32-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_bw</span>() <span class="sc">+</span> <span class="fu">labs</span>(<span class="at">title =</span> <span class="st">"Scatter plot with regression line Happiness vs Urbanization rate"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stderr">
<pre><code>`geom_smooth()` using formula = 'y ~ x'</code></pre>
</div>
<div class="cell-output-display">
<p><img src="Final-Project_World-Happiness_files/figure-html/unnamed-chunk-9-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<p>The relationship between happiness score and urbanization rate is very significant in Asia, Africa and Europe followed by North america and south america.</p>
<div class="cell">
<details>
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb34"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb34-1"><a href="#cb34-1" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(<span class="fu">subset</span>(happy, happy<span class="sc">$</span>Continent <span class="sc">!=</span> <span class="st">"Australia"</span>), <span class="fu">aes</span>(<span class="at">x =</span>  Life.expectancy, <span class="at">y =</span> Happiness)) <span class="sc">+</span> </span>
<span id="cb34-2"><a href="#cb34-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_point</span>(<span class="fu">aes</span>(<span class="at">color=</span>Continent), <span class="at">size =</span> <span class="dv">3</span>, <span class="at">alpha =</span> <span class="fl">0.8</span>) <span class="sc">+</span>  </span>
<span id="cb34-3"><a href="#cb34-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_smooth</span>(<span class="fu">aes</span>(<span class="at">color =</span> Continent, <span class="at">fill =</span> Continent), </span>
<span id="cb34-4"><a href="#cb34-4" aria-hidden="true" tabindex="-1"></a>              <span class="at">method =</span> <span class="st">"lm"</span>, <span class="at">fullrange =</span> <span class="cn">TRUE</span>) <span class="sc">+</span></span>
<span id="cb34-5"><a href="#cb34-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">facet_wrap</span>(<span class="sc">~</span>Continent) <span class="sc">+</span></span>
<span id="cb34-6"><a href="#cb34-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_bw</span>() <span class="sc">+</span> <span class="fu">labs</span>(<span class="at">title =</span> <span class="st">"Scatter plot with regression line Happiness vs Life Expectancy"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stderr">
<pre><code>`geom_smooth()` using formula = 'y ~ x'</code></pre>
</div>
<div class="cell-output-display">
<p><img src="Final-Project_World-Happiness_files/figure-html/unnamed-chunk-10-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<p>The relationship between happiness score and life expectancy is very significant in Asia, Europe and Africa followed by North america and south america.</p>
</section>
</section>
<section id="modeling-hypothesis-testing" class="level2">
<h2 class="anchored" data-anchor-id="modeling-hypothesis-testing">Modeling &amp; Hypothesis testing</h2>
<p>From the above visualizations and analysis, we have found that GDP per capita, Urbanization and Life Expectancy play major role in the happiness score. Whereas suicide rate and population growth has an inverse relationship. Let’s build a model for estimating happiness scores based on these control variables and see which of these has effect on the overall happiness scores.</p>
<section id="model-1" class="level3">
<h3 class="anchored" data-anchor-id="model-1">Model-1</h3>
<div class="cell">
<details>
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb36"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb36-1"><a href="#cb36-1" aria-hidden="true" tabindex="-1"></a><span class="co">#Model-1</span></span>
<span id="cb36-2"><a href="#cb36-2" aria-hidden="true" tabindex="-1"></a>model1 <span class="ot">&lt;-</span> <span class="fu">lm</span>(Happiness <span class="sc">~</span> GDP.per.capita <span class="sc">+</span> urbanization.rate <span class="sc">+</span> Life.expectancy, <span class="at">data =</span> happy)</span>
<span id="cb36-3"><a href="#cb36-3" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(model1)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = Happiness ~ GDP.per.capita + urbanization.rate + 
    Life.expectancy, data = happy)

Residuals:
     Min       1Q   Median       3Q      Max 
-1.89896 -0.37351  0.07498  0.48488  1.15628 

Coefficients:
                   Estimate Std. Error t value Pr(&gt;|t|)    
(Intercept)       4.510e-01  7.280e-01   0.620   0.5366    
GDP.per.capita    1.790e-05  3.867e-06   4.628 8.72e-06 ***
urbanization.rate 6.992e-03  3.646e-03   1.918   0.0573 .  
Life.expectancy   5.814e-02  1.156e-02   5.030 1.57e-06 ***
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 0.6355 on 132 degrees of freedom
Multiple R-squared:  0.6693,    Adjusted R-squared:  0.6618 
F-statistic: 89.07 on 3 and 132 DF,  p-value: &lt; 2.2e-16</code></pre>
</div>
</div>
<p>It can be seen that p-value of the F-statistic is &lt; 2.2e-16, which is highly significant. This means that, at least, one of the predictor/control variables ( GDP per capita, Urbanization rare and Life Expectancy) is significantly related to the outcome variable (Happiness score).</p>
<p>It can be seen that, changing in GDP per capita and Life expectancy are significantly associated to changes in happiness scores while changes in urbanization rate is not significantly associated with sales.</p>
<div class="cell">
<details>
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb38"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb38-1"><a href="#cb38-1" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(model1)<span class="sc">$</span>coefficient</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>                      Estimate   Std. Error   t value     Pr(&gt;|t|)
(Intercept)       4.510470e-01 7.280370e-01 0.6195386 5.366295e-01
GDP.per.capita    1.789683e-05 3.867139e-06 4.6279250 8.717287e-06
urbanization.rate 6.992347e-03 3.645755e-03 1.9179423 5.727811e-02
Life.expectancy   5.814042e-02 1.155817e-02 5.0302459 1.567648e-06</code></pre>
</div>
</div>
<div class="cell">
<details>
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb40"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb40-1"><a href="#cb40-1" aria-hidden="true" tabindex="-1"></a><span class="fu">confint</span>(model1)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>                          2.5 %       97.5 %
(Intercept)       -9.890821e-01 1.891176e+00
GDP.per.capita     1.024724e-05 2.554641e-05
urbanization.rate -2.193158e-04 1.420401e-02
Life.expectancy    3.527723e-02 8.100362e-02</code></pre>
</div>
</div>
<p>Lets see how this model behaves if we apply log on the variables</p>
<div class="cell">
<details>
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb42"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb42-1"><a href="#cb42-1" aria-hidden="true" tabindex="-1"></a><span class="co">#Model-1 with log</span></span>
<span id="cb42-2"><a href="#cb42-2" aria-hidden="true" tabindex="-1"></a>model1_log <span class="ot">&lt;-</span> <span class="fu">lm</span>(Happiness <span class="sc">~</span> <span class="fu">log</span>(GDP.per.capita <span class="sc">+</span> urbanization.rate <span class="sc">+</span> Life.expectancy), <span class="at">data =</span> happy)</span>
<span id="cb42-3"><a href="#cb42-3" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(model1_log)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = Happiness ~ log(GDP.per.capita + urbanization.rate + 
    Life.expectancy), data = happy)

Residuals:
     Min       1Q   Median       3Q      Max 
-2.32889 -0.48506  0.05291  0.51078  1.36460 

Coefficients:
                                                          Estimate Std. Error
(Intercept)                                               -1.66107    0.49628
log(GDP.per.capita + urbanization.rate + Life.expectancy)  0.75478    0.05177
                                                          t value Pr(&gt;|t|)    
(Intercept)                                                -3.347  0.00106 ** 
log(GDP.per.capita + urbanization.rate + Life.expectancy)  14.581  &lt; 2e-16 ***
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 0.682 on 134 degrees of freedom
Multiple R-squared:  0.6134,    Adjusted R-squared:  0.6105 
F-statistic: 212.6 on 1 and 134 DF,  p-value: &lt; 2.2e-16</code></pre>
</div>
</div>
<p>The R-Squared value drops from 0.6693 to 0.6134 by applying log for model-1.</p>
</section>
<section id="model-2" class="level3">
<h3 class="anchored" data-anchor-id="model-2">Model-2</h3>
<div class="cell">
<details>
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb44"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb44-1"><a href="#cb44-1" aria-hidden="true" tabindex="-1"></a><span class="co">#Model-2</span></span>
<span id="cb44-2"><a href="#cb44-2" aria-hidden="true" tabindex="-1"></a>model2  <span class="ot">&lt;-</span> <span class="fu">lm</span>(Happiness <span class="sc">~</span> GDP.per.capita <span class="sc">+</span> Life.expectancy, <span class="at">data =</span> happy)</span>
<span id="cb44-3"><a href="#cb44-3" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(model2)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = Happiness ~ GDP.per.capita + Life.expectancy, data = happy)

Residuals:
     Min       1Q   Median       3Q      Max 
-2.01976 -0.39026  0.09436  0.49252  1.18774 

Coefficients:
                 Estimate Std. Error t value Pr(&gt;|t|)    
(Intercept)     1.683e-01  7.201e-01   0.234    0.816    
GDP.per.capita  2.028e-05  3.699e-06   5.481 2.05e-07 ***
Life.expectancy 6.713e-02  1.067e-02   6.292 4.20e-09 ***
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 0.6418 on 133 degrees of freedom
Multiple R-squared:  0.6601,    Adjusted R-squared:  0.655 
F-statistic: 129.2 on 2 and 133 DF,  p-value: &lt; 2.2e-16</code></pre>
</div>
</div>
<div class="cell">
<details>
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb46"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb46-1"><a href="#cb46-1" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(model2)<span class="sc">$</span>coefficient</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>                    Estimate   Std. Error   t value     Pr(&gt;|t|)
(Intercept)     1.683136e-01 7.200997e-01 0.2337366 8.155489e-01
GDP.per.capita  2.027701e-05 3.699299e-06 5.4813121 2.046209e-07
Life.expectancy 6.713497e-02 1.066984e-02 6.2920307 4.201007e-09</code></pre>
</div>
</div>
<p>It turns out Life Expectancy is strongly associated with happiness scores and GDP per capita follows life expectancy.</p>
<div class="cell">
<details>
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb48"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb48-1"><a href="#cb48-1" aria-hidden="true" tabindex="-1"></a><span class="fu">confint</span>(model2)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>                        2.5 %       97.5 %
(Intercept)     -1.256016e+00 1.592643e+00
GDP.per.capita   1.295994e-05 2.759408e-05
Life.expectancy  4.603044e-02 8.823951e-02</code></pre>
</div>
</div>
<p>However the R-squared values of Model-1 and Model-2 are approximately around 65-66%. Hence we cannot say which model is best fit to predict the happiness scores.</p>
<p>Lets consider all the 5 control variables and see the results.</p>
<p>Lets see how model-2 behaves if we apply log on the variables</p>
<div class="cell">
<details>
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb50"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb50-1"><a href="#cb50-1" aria-hidden="true" tabindex="-1"></a><span class="co">#Model-2 with log</span></span>
<span id="cb50-2"><a href="#cb50-2" aria-hidden="true" tabindex="-1"></a>model2_log  <span class="ot">&lt;-</span> <span class="fu">lm</span>(Happiness <span class="sc">~</span> <span class="fu">log</span>(GDP.per.capita <span class="sc">+</span> Life.expectancy), <span class="at">data =</span> happy)</span>
<span id="cb50-3"><a href="#cb50-3" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(model2_log)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = Happiness ~ log(GDP.per.capita + Life.expectancy), 
    data = happy)

Residuals:
     Min       1Q   Median       3Q      Max 
-2.32936 -0.47756  0.04899  0.51212  1.36194 

Coefficients:
                                      Estimate Std. Error t value Pr(&gt;|t|)    
(Intercept)                           -1.62336    0.49427  -3.284   0.0013 ** 
log(GDP.per.capita + Life.expectancy)  0.75129    0.05158  14.565   &lt;2e-16 ***
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 0.6824 on 134 degrees of freedom
Multiple R-squared:  0.6129,    Adjusted R-squared:   0.61 
F-statistic: 212.1 on 1 and 134 DF,  p-value: &lt; 2.2e-16</code></pre>
</div>
</div>
<p>The R-Squared value drops from 0.66 to 0.61 by applying log for model-2.</p>
</section>
<section id="model-3" class="level3">
<h3 class="anchored" data-anchor-id="model-3">Model-3</h3>
<div class="cell">
<details>
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb52"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb52-1"><a href="#cb52-1" aria-hidden="true" tabindex="-1"></a><span class="co">#Model-3</span></span>
<span id="cb52-2"><a href="#cb52-2" aria-hidden="true" tabindex="-1"></a>model3 <span class="ot">&lt;-</span> <span class="fu">lm</span>(Happiness <span class="sc">~</span> GDP.per.capita <span class="sc">+</span> urbanization.rate <span class="sc">+</span> Life.expectancy <span class="sc">+</span> Suicide.rate <span class="sc">+</span> Population.growth , <span class="at">data =</span> happy)</span>
<span id="cb52-3"><a href="#cb52-3" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(model3)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = Happiness ~ GDP.per.capita + urbanization.rate + 
    Life.expectancy + Suicide.rate + Population.growth, data = happy)

Residuals:
     Min       1Q   Median       3Q      Max 
-1.87156 -0.39252  0.05248  0.45831  1.25675 

Coefficients:
                    Estimate Std. Error t value Pr(&gt;|t|)    
(Intercept)       -2.712e-02  1.268e+00  -0.021 0.982977    
GDP.per.capita     1.646e-05  4.281e-06   3.845 0.000188 ***
urbanization.rate  6.826e-03  3.647e-03   1.872 0.063456 .  
Life.expectancy    6.341e-02  1.667e-02   3.804 0.000218 ***
Suicide.rate       1.586e-02  1.317e-02   1.204 0.230615    
Population.growth -1.622e-02  7.576e-02  -0.214 0.830844    
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 0.6348 on 130 degrees of freedom
Multiple R-squared:  0.6751,    Adjusted R-squared:  0.6626 
F-statistic: 54.01 on 5 and 130 DF,  p-value: &lt; 2.2e-16</code></pre>
</div>
</div>
<p>The R-squared remains same after adding additional two control variables. So far, the second model fits the happiness scores.</p>
<p>Lets see how model-3 behaves if we apply log on the control variables</p>
<div class="cell">
<details>
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb54"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb54-1"><a href="#cb54-1" aria-hidden="true" tabindex="-1"></a><span class="co">#Model-3 with log</span></span>
<span id="cb54-2"><a href="#cb54-2" aria-hidden="true" tabindex="-1"></a>model3_log <span class="ot">&lt;-</span> <span class="fu">lm</span>(Happiness <span class="sc">~</span> <span class="fu">log</span>(GDP.per.capita <span class="sc">+</span> urbanization.rate <span class="sc">+</span> Life.expectancy <span class="sc">+</span> Suicide.rate <span class="sc">+</span> Population.growth) , <span class="at">data =</span> happy)</span>
<span id="cb54-3"><a href="#cb54-3" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(model3_log)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = Happiness ~ log(GDP.per.capita + urbanization.rate + 
    Life.expectancy + Suicide.rate + Population.growth), data = happy)

Residuals:
     Min       1Q   Median       3Q      Max 
-2.32855 -0.48525  0.05338  0.51003  1.36226 

Coefficients:
                                                                                             Estimate
(Intercept)                                                                                  -1.67866
log(GDP.per.capita + urbanization.rate + Life.expectancy + Suicide.rate + Population.growth)  0.75648
                                                                                             Std. Error
(Intercept)                                                                                     0.49727
log(GDP.per.capita + urbanization.rate + Life.expectancy + Suicide.rate + Population.growth)    0.05186
                                                                                             t value
(Intercept)                                                                                   -3.376
log(GDP.per.capita + urbanization.rate + Life.expectancy + Suicide.rate + Population.growth)  14.587
                                                                                             Pr(&gt;|t|)
(Intercept)                                                                                  0.000963
log(GDP.per.capita + urbanization.rate + Life.expectancy + Suicide.rate + Population.growth)  &lt; 2e-16
                                                                                                
(Intercept)                                                                                  ***
log(GDP.per.capita + urbanization.rate + Life.expectancy + Suicide.rate + Population.growth) ***
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 0.6818 on 134 degrees of freedom
Multiple R-squared:  0.6136,    Adjusted R-squared:  0.6107 
F-statistic: 212.8 on 1 and 134 DF,  p-value: &lt; 2.2e-16</code></pre>
</div>
</div>
<p>The R-squared values drops from 0.66 to 0.61 by application of log.</p>
</section>
</section>
<section id="model-comprision" class="level2">
<h2 class="anchored" data-anchor-id="model-comprision">Model comprision</h2>
<table class="table">
<colgroup>
<col style="width: 55%">
<col style="width: 12%">
<col style="width: 11%">
<col style="width: 19%">
</colgroup>
<thead>
<tr class="header">
<th>Models</th>
<th>Multiple R-squared</th>
<th>Adjusted R-squared</th>
<th>Significant Variables</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Model-1 (GDP per capita+Urbanization rate+Life expectancy)</td>
<td>0.6693</td>
<td>0.6618</td>
<td>GDP per capita &amp; Life Expectancy</td>
</tr>
<tr class="even">
<td>Model-1 (Log(GDP per capita+Urbanization rate+Life expectancy))</td>
<td>0.6134</td>
<td>0.6105</td>
<td>-</td>
</tr>
<tr class="odd">
<td>Model-2 (GDP per capita+Life expectancy)</td>
<td>0.6601</td>
<td>0.655</td>
<td><p>GDP per capita &amp; Life Expectancy.</p>
<p>Life expectancy &gt; GDP per capita</p></td>
</tr>
<tr class="even">
<td>Model-2 (Log(GDP per capita+Life expectancy))</td>
<td>0.6129</td>
<td>0.61</td>
<td>-</td>
</tr>
<tr class="odd">
<td>Model-3 (GDP per capita+Urbanization rate +Life expectancy + Suicide rate + population growth)</td>
<td>0.6601</td>
<td>0.655</td>
<td>GDP per capita &amp; Life Expectancy</td>
</tr>
<tr class="even">
<td>Model-3 (Log(GDP per capita+Urbanization rate +Life expectancy + Suicide rate + population growth))</td>
<td>0.6136</td>
<td>0.6107</td>
<td><p>GDP per capita &amp; Life Expectancy.</p>
<p>Life expectancy &gt; GDP per capita</p></td>
</tr>
</tbody>
</table>
<ul>
<li><p>It can be derived from the above table that the adjusted R-Squared for Model-2 is better than other two models, hence it can be said that Model-2 is a good fit.</p></li>
<li><p>Application of Logarithm on the control variables reduced the R-squared values in all the 3 models.</p></li>
<li><p><strong>Hypothesis testing conclusion:</strong></p>
<p>Turns out we have evidence for all the 3 hypothesis but,</p>
<ul>
<li>We have a strong evidence for hypothesis-3 i.e.&nbsp;Higher Life Expectancy leads to country’s happiness.</li>
</ul></li>
</ul>
<p>------</p>
<p>As we have concluded that Model-2 is a goof fit, Lets divide the happy dataset into training and test and plot the predicted happiness scores for Model-2.</p>
<div class="cell">
<details>
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb56"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb56-1"><a href="#cb56-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Splitting the dataset into the Training set and Test set</span></span>
<span id="cb56-2"><a href="#cb56-2" aria-hidden="true" tabindex="-1"></a><span class="fu">set.seed</span>(<span class="dv">123</span>)</span>
<span id="cb56-3"><a href="#cb56-3" aria-hidden="true" tabindex="-1"></a>dataset <span class="ot">&lt;-</span> happy[<span class="dv">4</span><span class="sc">:</span><span class="dv">10</span>]</span>
<span id="cb56-4"><a href="#cb56-4" aria-hidden="true" tabindex="-1"></a>split <span class="ot">=</span> <span class="fu">sample.split</span>(dataset<span class="sc">$</span>Happiness, <span class="at">SplitRatio =</span> <span class="fl">0.8</span>)</span>
<span id="cb56-5"><a href="#cb56-5" aria-hidden="true" tabindex="-1"></a>training_set <span class="ot">=</span> <span class="fu">subset</span>(dataset, split <span class="sc">==</span> <span class="cn">TRUE</span>)</span>
<span id="cb56-6"><a href="#cb56-6" aria-hidden="true" tabindex="-1"></a>test_set <span class="ot">=</span> <span class="fu">subset</span>(dataset, split <span class="sc">==</span> <span class="cn">FALSE</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
</div>
<div class="cell">
<details>
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb57"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb57-1"><a href="#cb57-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Fitting Multiple Linear Regression to the Training set on Model-2</span></span>
<span id="cb57-2"><a href="#cb57-2" aria-hidden="true" tabindex="-1"></a>regressor_lm <span class="ot">=</span> <span class="fu">lm</span>(<span class="at">formula =</span> Happiness <span class="sc">~</span> GDP.per.capita <span class="sc">+</span> Life.expectancy,</span>
<span id="cb57-3"><a href="#cb57-3" aria-hidden="true" tabindex="-1"></a>               <span class="at">data =</span> training_set)</span>
<span id="cb57-4"><a href="#cb57-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb57-5"><a href="#cb57-5" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(regressor_lm)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = Happiness ~ GDP.per.capita + Life.expectancy, data = training_set)

Residuals:
    Min      1Q  Median      3Q     Max 
-1.9617 -0.4055  0.0248  0.4922  1.1547 

Coefficients:
                  Estimate Std. Error t value Pr(&gt;|t|)    
(Intercept)     -6.041e-02  7.946e-01  -0.076     0.94    
GDP.per.capita   2.117e-05  4.330e-06   4.889 3.65e-06 ***
Life.expectancy  6.975e-02  1.184e-02   5.892 4.65e-08 ***
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 0.6397 on 105 degrees of freedom
Multiple R-squared:  0.6834,    Adjusted R-squared:  0.6774 
F-statistic: 113.3 on 2 and 105 DF,  p-value: &lt; 2.2e-16</code></pre>
</div>
</div>
<div class="cell">
<details>
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb59"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb59-1"><a href="#cb59-1" aria-hidden="true" tabindex="-1"></a>y_pred_lm <span class="ot">=</span> <span class="fu">predict</span>(regressor_lm, <span class="at">newdata =</span> test_set)</span>
<span id="cb59-2"><a href="#cb59-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb59-3"><a href="#cb59-3" aria-hidden="true" tabindex="-1"></a>Pred_Actual_lm <span class="ot">&lt;-</span> <span class="fu">as.data.frame</span>(<span class="fu">cbind</span>(<span class="at">Prediction =</span> y_pred_lm, <span class="at">Actual =</span> test_set<span class="sc">$</span>Happiness))</span>
<span id="cb59-4"><a href="#cb59-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb59-5"><a href="#cb59-5" aria-hidden="true" tabindex="-1"></a>gg.lm <span class="ot">&lt;-</span> <span class="fu">ggplot</span>(Pred_Actual_lm, <span class="fu">aes</span>(Actual, Prediction )) <span class="sc">+</span></span>
<span id="cb59-6"><a href="#cb59-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_point</span>() <span class="sc">+</span> <span class="fu">theme_bw</span>() <span class="sc">+</span> <span class="fu">geom_abline</span>() <span class="sc">+</span></span>
<span id="cb59-7"><a href="#cb59-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">title =</span> <span class="st">"Multiple Linear Regression"</span>, <span class="at">x =</span> <span class="st">"Actual happiness score"</span>,</span>
<span id="cb59-8"><a href="#cb59-8" aria-hidden="true" tabindex="-1"></a>       <span class="at">y =</span> <span class="st">"Predicted happiness score"</span>) <span class="sc">+</span></span>
<span id="cb59-9"><a href="#cb59-9" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme</span>(<span class="at">plot.title =</span> <span class="fu">element_text</span>(<span class="at">family =</span> <span class="st">"Helvetica"</span>, <span class="at">face =</span> <span class="st">"bold"</span>, <span class="at">size =</span> (<span class="dv">15</span>)), </span>
<span id="cb59-10"><a href="#cb59-10" aria-hidden="true" tabindex="-1"></a>        <span class="at">axis.title =</span> <span class="fu">element_text</span>(<span class="at">family =</span> <span class="st">"Helvetica"</span>, <span class="at">size =</span> (<span class="dv">10</span>)))</span>
<span id="cb59-11"><a href="#cb59-11" aria-hidden="true" tabindex="-1"></a>gg.lm</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output-display">
<p><img src="Final-Project_World-Happiness_files/figure-html/unnamed-chunk-23-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<p><strong>The Model shows 67% accuracy on the test data.</strong></p>
</section>
<section id="regression-diagnostics" class="level2">
<h2 class="anchored" data-anchor-id="regression-diagnostics">Regression Diagnostics</h2>
<section id="model-1-1" class="level3">
<h3 class="anchored" data-anchor-id="model-1-1">Model-1</h3>
<div class="cell">
<details>
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb60"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb60-1"><a href="#cb60-1" aria-hidden="true" tabindex="-1"></a><span class="co">#Model-1</span></span>
<span id="cb60-2"><a href="#cb60-2" aria-hidden="true" tabindex="-1"></a><span class="fu">par</span>(<span class="at">mfrow =</span> <span class="fu">c</span>(<span class="dv">2</span>,<span class="dv">3</span>)); <span class="fu">plot</span>(model1, <span class="at">which =</span> <span class="dv">1</span><span class="sc">:</span><span class="dv">6</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output-display">
<p><img src="Final-Project_World-Happiness_files/figure-html/unnamed-chunk-24-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<p><strong>Model-1 Diagnostics:</strong></p>
<p>Residuals vs Fitted: The Linearity assumption is met and there is a constant variance of residuals along the line. Overall the plot looks good.</p>
<p>Normal Q-Q: The points are falling along the theoretical quantiles, hence the normality assumption is met.</p>
<p>Scale-Location: The line is approximately horizontal, so I can say that the constant variance assumption is met.</p>
<p>Cook’s distance: No observation is greater than 1. The maximum cook’s distance is &lt;0.3. 174th observation is the influential.</p>
<p>Residuals vs Leverage: No observations are beyond the cook’s distance and the leverage is low.</p>
<p>But the influential observation 174 is not at the same place in all graphs which is odd.</p>
</section>
<section id="model-2-1" class="level3">
<h3 class="anchored" data-anchor-id="model-2-1">Model-2</h3>
<div class="cell">
<details>
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb61"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb61-1"><a href="#cb61-1" aria-hidden="true" tabindex="-1"></a><span class="co">#Model-2</span></span>
<span id="cb61-2"><a href="#cb61-2" aria-hidden="true" tabindex="-1"></a><span class="fu">par</span>(<span class="at">mfrow =</span> <span class="fu">c</span>(<span class="dv">2</span>,<span class="dv">3</span>)); <span class="fu">plot</span>(model2, <span class="at">which =</span> <span class="dv">1</span><span class="sc">:</span><span class="dv">6</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output-display">
<p><img src="Final-Project_World-Happiness_files/figure-html/unnamed-chunk-25-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<p><strong>Model-2 Diagnostics:</strong></p>
<p>Residuals vs Fitted: I would say the linearity assumption is violated here but the constant variance of residuals is present.</p>
<p>Normal Q-Q: The points are falling along the theoretical quantiles, hence the normality assumption is met.</p>
<p>Scale-Location: Compared to model-1, the line is almost horizontal. This one looks good.</p>
<p>Cook’s distance: No observation is greater than 1. The maximum cook’s distance is 0.9 (approximately). The 156th observation is very influential.</p>
<p>Residuals vs Leverage: No observations are beyond the cook’s distance and the leverage is high as compared to model-1 which is good.</p>
<p><strong>I can say that the regression diagnostics of Model-2 look much better than Model-1 because of the larger cook’s distance and leverage.</strong></p>
</section>
<section id="model-3-1" class="level3">
<h3 class="anchored" data-anchor-id="model-3-1">Model-3</h3>
<div class="cell">
<details>
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb62"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb62-1"><a href="#cb62-1" aria-hidden="true" tabindex="-1"></a><span class="co">#Model-3</span></span>
<span id="cb62-2"><a href="#cb62-2" aria-hidden="true" tabindex="-1"></a><span class="fu">par</span>(<span class="at">mfrow =</span> <span class="fu">c</span>(<span class="dv">2</span>,<span class="dv">3</span>)); <span class="fu">plot</span>(model3, <span class="at">which =</span> <span class="dv">1</span><span class="sc">:</span><span class="dv">6</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output-display">
<p><img src="Final-Project_World-Happiness_files/figure-html/unnamed-chunk-26-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<p>Residuals vs Fitted: The Linearity assumption is met and there is a constant variance of residuals along the line. Overall the plot looks good.</p>
<p>Normal Q-Q: The points are falling along the theoretical quantiles, hence the normality assumption is met.</p>
<p>Scale-Location: Compared to model-1 &amp; 2, the line is not horizontal.</p>
<p>Cook’s distance: No observation is greater than 1. The maximum cook’s distance is &lt; 0.3 (approximately). Again as similar to model-1, the 174th observation is very influential.</p>
<p>Residuals vs Leverage: No observations are beyond the cook’s distance and the leverage is low.</p>
<p>But the influential observation 174 is not at the same place in all graphs which is odd.</p>
</section>
</section>
<section id="conclusion" class="level2">
<h2 class="anchored" data-anchor-id="conclusion">Conclusion</h2>
<p>The aim of this study is to find out which factors significantly effect world happiness scores and to find out a model that fits/predicts the happiness scores. The following is the summary of this study.</p>
<ul>
<li><p>GDP per capita, Urbanization rate and Life expectancy are the factors that are significantly associated with Happiness scores.</p></li>
<li><p>North America, Europe and Australia appear to be the happiest.</p></li>
<li><p>South America, North Asia, Western Africa and countries/islands in the indian ocean appear to be happy on average.</p></li>
<li><p>South Africa, India are unhappy and of course Afghanistan is the unhappiest country in the world.</p></li>
<li><p>Australia has the highest median happiness score. Europe, South America, and North America are in the second place regarding median happiness score. Asia has the lowest median after Africa. We can see the range of happiness score for different continents, and also the concentration of happiness score.</p></li>
<li><p>The correlation between GDP per capita and happiness score in Europe, North America, and Asia is more significant than the other continents.</p></li>
<li><p>The relationship between happiness score and urbanization rate is very significant in Asia, Africa and Europe followed by North america and south america.</p></li>
<li><p>The relationship between happiness score and life expectancy is very significant in Asia, Europe and Africa followed by North america and south america.</p></li>
</ul>
<p>When it comes to modeling and hypothesis testing,</p>
<ul>
<li><p>Model-1 concluded that GDP per capita and Life Expectancy are strongly associated with the happiness scores.</p></li>
<li><p>Model-2 concluded that Life Expectancy is more strongly associated with the happiness scores, giving evidence to the third hypothesis.</p></li>
<li><p>Regression diagnostics of model-2 showed larger cook distance and leverage.</p></li>
</ul>
</section>
<section id="references" class="level2">
<h2 class="anchored" data-anchor-id="references">References</h2>
<ol type="1">
<li><p><a href="https://www.kaggle.com/code/noobiedatascientist/explaining-happiness/data" class="uri">https://www.kaggle.com/code/noobiedatascientist/explaining-happiness/data</a></p></li>
<li><p><a href="https://worldhappiness.report/ed/2021/" class="uri">https://worldhappiness.report/ed/2021/</a></p></li>
<li><p><a href="http://www.sthda.com/english/articles/40-regression-analysis/168-multiple-linear-regression-in-r/#building-model" class="uri">http://www.sthda.com/english/articles/40-regression-analysis/168-multiple-linear-regression-in-r/#building-model</a></p></li>
<li><p><a href="https://www.guru99.com/r-simple-multiple-linear-regression.htmlhttps://www.guru99.com/r-simple-multiple-linear-regression.html">https://www.guru99.com/r-simple-multiple-linear-regression.html</a></p></li>
</ol>


<!-- -->

</section>
</section>

</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const disableStylesheet = (stylesheets) => {
    for (let i=0; i < stylesheets.length; i++) {
      const stylesheet = stylesheets[i];
      stylesheet.rel = 'prefetch';
    }
  }
  const enableStylesheet = (stylesheets) => {
    for (let i=0; i < stylesheets.length; i++) {
      const stylesheet = stylesheets[i];
      stylesheet.rel = 'stylesheet';
    }
  }
  const manageTransitions = (selector, allowTransitions) => {
    const els = window.document.querySelectorAll(selector);
    for (let i=0; i < els.length; i++) {
      const el = els[i];
      if (allowTransitions) {
        el.classList.remove('notransition');
      } else {
        el.classList.add('notransition');
      }
    }
  }
  const toggleColorMode = (alternate) => {
    // Switch the stylesheets
    const alternateStylesheets = window.document.querySelectorAll('link.quarto-color-scheme.quarto-color-alternate');
    manageTransitions('#quarto-margin-sidebar .nav-link', false);
    if (alternate) {
      enableStylesheet(alternateStylesheets);
      for (const sheetNode of alternateStylesheets) {
        if (sheetNode.id === "quarto-bootstrap") {
          toggleBodyColorMode(sheetNode);
        }
      }
    } else {
      disableStylesheet(alternateStylesheets);
      toggleBodyColorPrimary();
    }
    manageTransitions('#quarto-margin-sidebar .nav-link', true);
    // Switch the toggles
    const toggles = window.document.querySelectorAll('.quarto-color-scheme-toggle');
    for (let i=0; i < toggles.length; i++) {
      const toggle = toggles[i];
      if (toggle) {
        if (alternate) {
          toggle.classList.add("alternate");     
        } else {
          toggle.classList.remove("alternate");
        }
      }
    }
    // Hack to workaround the fact that safari doesn't
    // properly recolor the scrollbar when toggling (#1455)
    if (navigator.userAgent.indexOf('Safari') > 0 && navigator.userAgent.indexOf('Chrome') == -1) {
      manageTransitions("body", false);
      window.scrollTo(0, 1);
      setTimeout(() => {
        window.scrollTo(0, 0);
        manageTransitions("body", true);
      }, 40);  
    }
  }
  const isFileUrl = () => { 
    return window.location.protocol === 'file:';
  }
  const hasAlternateSentinel = () => {  
    let styleSentinel = getColorSchemeSentinel();
    if (styleSentinel !== null) {
      return styleSentinel === "alternate";
    } else {
      return false;
    }
  }
  const setStyleSentinel = (alternate) => {
    const value = alternate ? "alternate" : "default";
    if (!isFileUrl()) {
      window.localStorage.setItem("quarto-color-scheme", value);
    } else {
      localAlternateSentinel = value;
    }
  }
  const getColorSchemeSentinel = () => {
    if (!isFileUrl()) {
      const storageValue = window.localStorage.getItem("quarto-color-scheme");
      return storageValue != null ? storageValue : localAlternateSentinel;
    } else {
      return localAlternateSentinel;
    }
  }
  let localAlternateSentinel = 'default';
  // Dark / light mode switch
  window.quartoToggleColorScheme = () => {
    // Read the current dark / light value 
    let toAlternate = !hasAlternateSentinel();
    toggleColorMode(toAlternate);
    setStyleSentinel(toAlternate);
  };
  // Ensure there is a toggle, if there isn't float one in the top right
  if (window.document.querySelector('.quarto-color-scheme-toggle') === null) {
    const a = window.document.createElement('a');
    a.classList.add('top-right');
    a.classList.add('quarto-color-scheme-toggle');
    a.href = "";
    a.onclick = function() { try { window.quartoToggleColorScheme(); } catch {} return false; };
    const i = window.document.createElement("i");
    i.classList.add('bi');
    a.appendChild(i);
    window.document.body.appendChild(a);
  }
  // Switch to dark mode if need be
  if (hasAlternateSentinel()) {
    toggleColorMode(true);
  } else {
    toggleColorMode(false);
  }
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const clipboard = new window.ClipboardJS('.code-copy-button', {
    target: function(trigger) {
      return trigger.previousElementSibling;
    }
  });
  clipboard.on('success', function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copied!");
    let tooltip;
    if (window.bootstrap) {
      button.setAttribute("data-bs-toggle", "tooltip");
      button.setAttribute("data-bs-placement", "left");
      button.setAttribute("data-bs-title", "Copied!");
      tooltip = new bootstrap.Tooltip(button, 
        { trigger: "manual", 
          customClass: "code-copy-button-tooltip",
          offset: [0, -8]});
      tooltip.show();    
    }
    setTimeout(function() {
      if (tooltip) {
        tooltip.hide();
        button.removeAttribute("data-bs-title");
        button.removeAttribute("data-bs-toggle");
        button.removeAttribute("data-bs-placement");
      }
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  });
  const viewSource = window.document.getElementById('quarto-view-source') ||
                     window.document.getElementById('quarto-code-tools-source');
  if (viewSource) {
    const sourceUrl = viewSource.getAttribute("data-quarto-source-url");
    viewSource.addEventListener("click", function(e) {
      if (sourceUrl) {
        // rstudio viewer pane
        if (/\bcapabilities=\b/.test(window.location)) {
          window.open(sourceUrl);
        } else {
          window.location.href = sourceUrl;
        }
      } else {
        const modal = new bootstrap.Modal(document.getElementById('quarto-embedded-source-code-modal'));
        modal.show();
      }
      return false;
    });
  }
  function toggleCodeHandler(show) {
    return function(e) {
      const detailsSrc = window.document.querySelectorAll(".cell > details > .sourceCode");
      for (let i=0; i<detailsSrc.length; i++) {
        const details = detailsSrc[i].parentElement;
        if (show) {
          details.open = true;
        } else {
          details.removeAttribute("open");
        }
      }
      const cellCodeDivs = window.document.querySelectorAll(".cell > .sourceCode");
      const fromCls = show ? "hidden" : "unhidden";
      const toCls = show ? "unhidden" : "hidden";
      for (let i=0; i<cellCodeDivs.length; i++) {
        const codeDiv = cellCodeDivs[i];
        if (codeDiv.classList.contains(fromCls)) {
          codeDiv.classList.remove(fromCls);
          codeDiv.classList.add(toCls);
        } 
      }
      return false;
    }
  }
  const hideAllCode = window.document.getElementById("quarto-hide-all-code");
  if (hideAllCode) {
    hideAllCode.addEventListener("click", toggleCodeHandler(false));
  }
  const showAllCode = window.document.getElementById("quarto-show-all-code");
  if (showAllCode) {
    showAllCode.addEventListener("click", toggleCodeHandler(true));
  }
  function tippyHover(el, contentFn) {
    const config = {
      allowHTML: true,
      content: contentFn,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start'
    };
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      return note.innerHTML;
    });
  }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
});
</script>
<script src="https://giscus.app/client.js" data-repo="DACSS/603_Fall_2022" data-repo-id="R_kgDOH568kA" data-category="Announcements" data-category-id="" data-mapping="title" data-reactions-enabled="1" data-emit-metadata="0" data-input-position="top" data-theme="light" data-lang="en" crossorigin="anonymous" async="">
</script><div class="modal fade" id="quarto-embedded-source-code-modal" tabindex="-1" aria-labelledby="quarto-embedded-source-code-modal-label" aria-hidden="true"><div class="modal-dialog modal-dialog-scrollable"><div class="modal-content"><div class="modal-header"><h5 class="modal-title" id="quarto-embedded-source-code-modal-label">Source Code</h5><button class="btn-close" data-bs-dismiss="modal"></button></div><div class="modal-body"><div class="">
<div class="sourceCode" id="cb63" data-shortcodes="false"><pre class="sourceCode markdown code-with-copy"><code class="sourceCode markdown"><span id="cb63-1"><a href="#cb63-1" aria-hidden="true" tabindex="-1"></a><span class="co">---</span></span>
<span id="cb63-2"><a href="#cb63-2" aria-hidden="true" tabindex="-1"></a><span class="an">title:</span><span class="co"> "Final Project"</span></span>
<span id="cb63-3"><a href="#cb63-3" aria-hidden="true" tabindex="-1"></a><span class="an">author:</span><span class="co"> "Niharika Pola"</span></span>
<span id="cb63-4"><a href="#cb63-4" aria-hidden="true" tabindex="-1"></a><span class="an">description:</span><span class="co"> "Final Project"</span></span>
<span id="cb63-5"><a href="#cb63-5" aria-hidden="true" tabindex="-1"></a><span class="an">date:</span><span class="co"> "12/13/2022"</span></span>
<span id="cb63-6"><a href="#cb63-6" aria-hidden="true" tabindex="-1"></a><span class="an">format:</span></span>
<span id="cb63-7"><a href="#cb63-7" aria-hidden="true" tabindex="-1"></a><span class="co">  html:</span></span>
<span id="cb63-8"><a href="#cb63-8" aria-hidden="true" tabindex="-1"></a><span class="co">    df-print: paged</span></span>
<span id="cb63-9"><a href="#cb63-9" aria-hidden="true" tabindex="-1"></a><span class="co">    css: styles.css</span></span>
<span id="cb63-10"><a href="#cb63-10" aria-hidden="true" tabindex="-1"></a><span class="co">    toc: true</span></span>
<span id="cb63-11"><a href="#cb63-11" aria-hidden="true" tabindex="-1"></a><span class="co">    code-fold: true</span></span>
<span id="cb63-12"><a href="#cb63-12" aria-hidden="true" tabindex="-1"></a><span class="co">    code-copy: true</span></span>
<span id="cb63-13"><a href="#cb63-13" aria-hidden="true" tabindex="-1"></a><span class="co">    code-tools: true</span></span>
<span id="cb63-14"><a href="#cb63-14" aria-hidden="true" tabindex="-1"></a><span class="an">categories:</span></span>
<span id="cb63-15"><a href="#cb63-15" aria-hidden="true" tabindex="-1"></a><span class="co">  - Final Project</span></span>
<span id="cb63-16"><a href="#cb63-16" aria-hidden="true" tabindex="-1"></a><span class="co">---</span></span>
<span id="cb63-17"><a href="#cb63-17" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb63-18"><a href="#cb63-18" aria-hidden="true" tabindex="-1"></a><span class="in">```{r message=FALSE, warning=FALSE}</span></span>
<span id="cb63-19"><a href="#cb63-19" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(tidyverse)</span>
<span id="cb63-20"><a href="#cb63-20" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(ggplot2)</span>
<span id="cb63-21"><a href="#cb63-21" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(readr)</span>
<span id="cb63-22"><a href="#cb63-22" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(corrplot)</span>
<span id="cb63-23"><a href="#cb63-23" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(reshape2)</span>
<span id="cb63-24"><a href="#cb63-24" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(corrgram)</span>
<span id="cb63-25"><a href="#cb63-25" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(ggpubr)</span>
<span id="cb63-26"><a href="#cb63-26" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(caTools)</span>
<span id="cb63-27"><a href="#cb63-27" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(GGally)</span>
<span id="cb63-28"><a href="#cb63-28" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(stats)</span>
<span id="cb63-29"><a href="#cb63-29" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(ggsci)</span>
<span id="cb63-30"><a href="#cb63-30" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb63-31"><a href="#cb63-31" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb63-32"><a href="#cb63-32" aria-hidden="true" tabindex="-1"></a><span class="fu"># Happiness Explained: Through Multiple Linear Regression.</span></span>
<span id="cb63-33"><a href="#cb63-33" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb63-34"><a href="#cb63-34" aria-hidden="true" tabindex="-1"></a><span class="fu">## Background/Motivation</span></span>
<span id="cb63-35"><a href="#cb63-35" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb63-36"><a href="#cb63-36" aria-hidden="true" tabindex="-1"></a>What is takes for a country or a continent to be happy or sad? Is it the higher GDP per capita, lower Population growth, lower Suicide rate or Urbanization? What are the factors that affect a country's or continents overall happiness? Can we predict the happiness score? The curiosity to find answers to these questions made me explore the world happiness scores and world data by country.</span>
<span id="cb63-37"><a href="#cb63-37" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb63-38"><a href="#cb63-38" aria-hidden="true" tabindex="-1"></a>The World Happiness Report is a landmark survey of the state of global happiness . The report continues to gain global recognition as governments, organizations and civil society increasingly use happiness indicators to inform their policy-making decisions. Leading experts across fields -- economics, psychology, survey analysis, national statistics, health, public policy and more -- describe how measurements of well-being can be used effectively to assess the progress of nations. The reports review the state of happiness in the world today and show how the new science of happiness explains personal and national variations in happiness.</span>
<span id="cb63-39"><a href="#cb63-39" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb63-40"><a href="#cb63-40" aria-hidden="true" tabindex="-1"></a>The data sets that are used in this analysis are 1) <span class="co">[</span><span class="ot">world happiness report 2021</span><span class="co">](https://www.kaggle.com/datasets/ajaypalsinghlo/world-happiness-report-2021)</span> and 2) kaggle's <span class="co">[</span><span class="ot">world data by country 2020</span><span class="co">](https://www.kaggle.com/datasets/daniboy370/world-data-by-country-2020)</span>. Happiness scores from first data set and few variables from the second data set are being used to analyse the following research question.</span>
<span id="cb63-41"><a href="#cb63-41" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb63-42"><a href="#cb63-42" aria-hidden="true" tabindex="-1"></a><span class="fu">## Research Question</span></span>
<span id="cb63-43"><a href="#cb63-43" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb63-44"><a href="#cb63-44" aria-hidden="true" tabindex="-1"></a><span class="ss">1.  </span>What are the variables or factors that are affecting a country's happiness?</span>
<span id="cb63-45"><a href="#cb63-45" aria-hidden="true" tabindex="-1"></a><span class="ss">2.  </span>To find out which model fits/accurately predicts the happiness score.</span>
<span id="cb63-46"><a href="#cb63-46" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb63-47"><a href="#cb63-47" aria-hidden="true" tabindex="-1"></a><span class="fu">## Hypothesis</span></span>
<span id="cb63-48"><a href="#cb63-48" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb63-49"><a href="#cb63-49" aria-hidden="true" tabindex="-1"></a>I wish to test the following hypothesis,</span>
<span id="cb63-50"><a href="#cb63-50" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb63-51"><a href="#cb63-51" aria-hidden="true" tabindex="-1"></a><span class="ss">1.  </span>Higher/Better GDP per capital leads to a country's happiness.</span>
<span id="cb63-52"><a href="#cb63-52" aria-hidden="true" tabindex="-1"></a><span class="ss">2.  </span>Urbanization leads to a country's happiness.</span>
<span id="cb63-53"><a href="#cb63-53" aria-hidden="true" tabindex="-1"></a><span class="ss">3.  </span>Higher Life Expectancy leads to country's happiness.</span>
<span id="cb63-54"><a href="#cb63-54" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb63-55"><a href="#cb63-55" aria-hidden="true" tabindex="-1"></a>This study aims to test the above hypothesis while comparing the GDP per capital and Urbanization with other variables including: Population growth, Life Expectancy, Sex-Ratio and Suicide Rate.</span>
<span id="cb63-56"><a href="#cb63-56" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb63-57"><a href="#cb63-57" aria-hidden="true" tabindex="-1"></a><span class="fu">### Reading &amp; Preparing the data sets</span></span>
<span id="cb63-58"><a href="#cb63-58" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb63-61"><a href="#cb63-61" aria-hidden="true" tabindex="-1"></a><span class="in">```{r}</span></span>
<span id="cb63-62"><a href="#cb63-62" aria-hidden="true" tabindex="-1"></a><span class="co">#dataset-1</span></span>
<span id="cb63-63"><a href="#cb63-63" aria-hidden="true" tabindex="-1"></a>happiness <span class="ot">&lt;-</span> <span class="fu">read_csv</span>(<span class="st">"project datasets/world-happiness-report-2021.csv"</span>)</span>
<span id="cb63-64"><a href="#cb63-64" aria-hidden="true" tabindex="-1"></a>hap_sc <span class="ot">&lt;-</span> <span class="fu">select</span>(happiness, <span class="st">"Country name"</span>, <span class="st">"Ladder score"</span>)</span>
<span id="cb63-65"><a href="#cb63-65" aria-hidden="true" tabindex="-1"></a>hap_sc <span class="ot">&lt;-</span> <span class="fu">rename</span>(hap_sc, <span class="st">"Country"</span><span class="ot">=</span><span class="st">"Country name"</span>, <span class="st">"Happiness"</span><span class="ot">=</span><span class="st">"Ladder score"</span>)</span>
<span id="cb63-66"><a href="#cb63-66" aria-hidden="true" tabindex="-1"></a><span class="fu">colnames</span>(hap_sc)</span>
<span id="cb63-67"><a href="#cb63-67" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb63-68"><a href="#cb63-68" aria-hidden="true" tabindex="-1"></a><span class="co">#datasets from world data by country</span></span>
<span id="cb63-69"><a href="#cb63-69" aria-hidden="true" tabindex="-1"></a>GDP_per_capita <span class="ot">&lt;-</span> <span class="fu">read_csv</span>(<span class="st">"project datasets/GDP per capita.csv"</span>)</span>
<span id="cb63-70"><a href="#cb63-70" aria-hidden="true" tabindex="-1"></a>Urbanization_rate <span class="ot">&lt;-</span> <span class="fu">read_csv</span>(<span class="st">"project datasets/Urbanization rate.csv"</span>)</span>
<span id="cb63-71"><a href="#cb63-71" aria-hidden="true" tabindex="-1"></a>Population_growth <span class="ot">&lt;-</span> <span class="fu">read_csv</span>(<span class="st">"project datasets/Population growth.csv"</span>)</span>
<span id="cb63-72"><a href="#cb63-72" aria-hidden="true" tabindex="-1"></a>Life_expectancy <span class="ot">&lt;-</span> <span class="fu">read_csv</span>(<span class="st">"project datasets/Life expectancy.csv"</span>)</span>
<span id="cb63-73"><a href="#cb63-73" aria-hidden="true" tabindex="-1"></a>Suicide_rate <span class="ot">&lt;-</span> <span class="fu">read_csv</span>(<span class="st">"project datasets/Suicide rate.csv"</span>)</span>
<span id="cb63-74"><a href="#cb63-74" aria-hidden="true" tabindex="-1"></a>Sex_ratio <span class="ot">&lt;-</span> <span class="fu">read_csv</span>(<span class="st">"project datasets/Sex-ratio.csv"</span>)</span>
<span id="cb63-75"><a href="#cb63-75" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb63-76"><a href="#cb63-76" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb63-77"><a href="#cb63-77" aria-hidden="true" tabindex="-1"></a><span class="co">#merging the above datasets by country and iso code</span></span>
<span id="cb63-78"><a href="#cb63-78" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb63-79"><a href="#cb63-79" aria-hidden="true" tabindex="-1"></a>world_data <span class="ot">&lt;-</span> <span class="fu">merge</span>(GDP_per_capita, Urbanization_rate)</span>
<span id="cb63-80"><a href="#cb63-80" aria-hidden="true" tabindex="-1"></a>world_data <span class="ot">&lt;-</span> <span class="fu">merge</span>(world_data, Population_growth)</span>
<span id="cb63-81"><a href="#cb63-81" aria-hidden="true" tabindex="-1"></a>world_data <span class="ot">&lt;-</span> <span class="fu">merge</span>(world_data, Life_expectancy)</span>
<span id="cb63-82"><a href="#cb63-82" aria-hidden="true" tabindex="-1"></a>world_data <span class="ot">&lt;-</span> <span class="fu">merge</span>(world_data, Suicide_rate)</span>
<span id="cb63-83"><a href="#cb63-83" aria-hidden="true" tabindex="-1"></a>world_data <span class="ot">&lt;-</span> <span class="fu">merge</span>(world_data, Sex_ratio)</span>
<span id="cb63-84"><a href="#cb63-84" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb63-85"><a href="#cb63-85" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb63-86"><a href="#cb63-86" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb63-87"><a href="#cb63-87" aria-hidden="true" tabindex="-1"></a><span class="co">#merging happiness scores and world data</span></span>
<span id="cb63-88"><a href="#cb63-88" aria-hidden="true" tabindex="-1"></a>happy <span class="ot">&lt;-</span> <span class="fu">merge</span>(world_data, hap_sc)</span>
<span id="cb63-89"><a href="#cb63-89" aria-hidden="true" tabindex="-1"></a>happy <span class="ot">&lt;-</span> <span class="fu">rename</span>(happy, <span class="st">"GDP.per.capita"</span><span class="ot">=</span><span class="st">"GDP per capita"</span>, <span class="st">"urbanization.rate"</span><span class="ot">=</span><span class="st">"Urbanization rate"</span>, <span class="st">"Population.growth"</span><span class="ot">=</span><span class="st">"Population growth"</span>, <span class="st">"Life.expectancy"</span><span class="ot">=</span><span class="st">"Life expectancy"</span>, <span class="st">"Suicide.rate"</span><span class="ot">=</span><span class="st">"Suicide rate"</span>, <span class="st">"Sex.ratio"</span><span class="ot">=</span><span class="st">"Sex-ratio"</span>)</span>
<span id="cb63-90"><a href="#cb63-90" aria-hidden="true" tabindex="-1"></a><span class="fu">str</span>(happy)</span>
<span id="cb63-91"><a href="#cb63-91" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb63-92"><a href="#cb63-92" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb63-95"><a href="#cb63-95" aria-hidden="true" tabindex="-1"></a><span class="in">```{r}</span></span>
<span id="cb63-96"><a href="#cb63-96" aria-hidden="true" tabindex="-1"></a><span class="co">#adding continents data to final dataset</span></span>
<span id="cb63-97"><a href="#cb63-97" aria-hidden="true" tabindex="-1"></a>happy<span class="sc">$</span>Continent <span class="ot">&lt;-</span> <span class="cn">NA</span></span>
<span id="cb63-98"><a href="#cb63-98" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb63-99"><a href="#cb63-99" aria-hidden="true" tabindex="-1"></a>happy<span class="sc">$</span>Continent[<span class="fu">which</span>(happy<span class="sc">$</span>Country <span class="sc">%in%</span> <span class="fu">c</span>(<span class="st">"Israel"</span>, <span class="st">"United Arab Emirates"</span>, <span class="st">"Singapore"</span>, <span class="st">"Thailand"</span>, <span class="st">"Taiwan Province of China"</span>,</span>
<span id="cb63-100"><a href="#cb63-100" aria-hidden="true" tabindex="-1"></a>                                   <span class="st">"Qatar"</span>, <span class="st">"Saudi Arabia"</span>, <span class="st">"Kuwait"</span>, <span class="st">"Bahrain"</span>, <span class="st">"Malaysia"</span>, <span class="st">"Uzbekistan"</span>, <span class="st">"Japan"</span>,</span>
<span id="cb63-101"><a href="#cb63-101" aria-hidden="true" tabindex="-1"></a>                                   <span class="st">"South Korea"</span>, <span class="st">"Turkmenistan"</span>, <span class="st">"Kazakhstan"</span>, <span class="st">"Turkey"</span>, <span class="st">"Hong Kong S.A.R., China"</span>, <span class="st">"Philippines"</span>,</span>
<span id="cb63-102"><a href="#cb63-102" aria-hidden="true" tabindex="-1"></a>                                   <span class="st">"Jordan"</span>, <span class="st">"China"</span>, <span class="st">"Pakistan"</span>, <span class="st">"Indonesia"</span>, <span class="st">"Azerbaijan"</span>, <span class="st">"Lebanon"</span>, <span class="st">"Vietnam"</span>,</span>
<span id="cb63-103"><a href="#cb63-103" aria-hidden="true" tabindex="-1"></a>                                   <span class="st">"Tajikistan"</span>, <span class="st">"Bhutan"</span>, <span class="st">"Kyrgyzstan"</span>, <span class="st">"Nepal"</span>, <span class="st">"Mongolia"</span>, <span class="st">"Palestinian Territories"</span>,</span>
<span id="cb63-104"><a href="#cb63-104" aria-hidden="true" tabindex="-1"></a>                                   <span class="st">"Iran"</span>, <span class="st">"Bangladesh"</span>, <span class="st">"Myanmar"</span>, <span class="st">"Iraq"</span>, <span class="st">"Sri Lanka"</span>, <span class="st">"Armenia"</span>, <span class="st">"India"</span>, <span class="st">"Georgia"</span>,</span>
<span id="cb63-105"><a href="#cb63-105" aria-hidden="true" tabindex="-1"></a>                                   <span class="st">"Cambodia"</span>, <span class="st">"Afghanistan"</span>, <span class="st">"Yemen"</span>, <span class="st">"Syria"</span>))] <span class="ot">&lt;-</span> <span class="st">"Asia"</span></span>
<span id="cb63-106"><a href="#cb63-106" aria-hidden="true" tabindex="-1"></a>happy<span class="sc">$</span>Continent[<span class="fu">which</span>(happy<span class="sc">$</span>Country <span class="sc">%in%</span> <span class="fu">c</span>(<span class="st">"Norway"</span>, <span class="st">"Denmark"</span>, <span class="st">"Iceland"</span>, <span class="st">"Switzerland"</span>, <span class="st">"Finland"</span>,</span>
<span id="cb63-107"><a href="#cb63-107" aria-hidden="true" tabindex="-1"></a>                                   <span class="st">"Netherlands"</span>, <span class="st">"Sweden"</span>, <span class="st">"Austria"</span>, <span class="st">"Ireland"</span>, <span class="st">"Germany"</span>,</span>
<span id="cb63-108"><a href="#cb63-108" aria-hidden="true" tabindex="-1"></a>                                   <span class="st">"Belgium"</span>, <span class="st">"Luxembourg"</span>, <span class="st">"United Kingdom"</span>, <span class="st">"Czech Republic"</span>,</span>
<span id="cb63-109"><a href="#cb63-109" aria-hidden="true" tabindex="-1"></a>                                   <span class="st">"Malta"</span>, <span class="st">"France"</span>, <span class="st">"Spain"</span>, <span class="st">"Slovakia"</span>, <span class="st">"Poland"</span>, <span class="st">"Italy"</span>,</span>
<span id="cb63-110"><a href="#cb63-110" aria-hidden="true" tabindex="-1"></a>                                   <span class="st">"Russia"</span>, <span class="st">"Lithuania"</span>, <span class="st">"Latvia"</span>, <span class="st">"Moldova"</span>, <span class="st">"Romania"</span>,</span>
<span id="cb63-111"><a href="#cb63-111" aria-hidden="true" tabindex="-1"></a>                                   <span class="st">"Slovenia"</span>, <span class="st">"North Cyprus"</span>, <span class="st">"Cyprus"</span>, <span class="st">"Estonia"</span>, <span class="st">"Belarus"</span>,</span>
<span id="cb63-112"><a href="#cb63-112" aria-hidden="true" tabindex="-1"></a>                                   <span class="st">"Serbia"</span>, <span class="st">"Hungary"</span>, <span class="st">"Croatia"</span>, <span class="st">"Kosovo"</span>, <span class="st">"Montenegro"</span>,</span>
<span id="cb63-113"><a href="#cb63-113" aria-hidden="true" tabindex="-1"></a>                                   <span class="st">"Greece"</span>, <span class="st">"Portugal"</span>, <span class="st">"Bosnia and Herzegovina"</span>, <span class="st">"Macedonia"</span>,</span>
<span id="cb63-114"><a href="#cb63-114" aria-hidden="true" tabindex="-1"></a>                                   <span class="st">"Bulgaria"</span>, <span class="st">"Albania"</span>, <span class="st">"Ukraine"</span>))] <span class="ot">&lt;-</span> <span class="st">"Europe"</span></span>
<span id="cb63-115"><a href="#cb63-115" aria-hidden="true" tabindex="-1"></a>happy<span class="sc">$</span>Continent[<span class="fu">which</span>(happy<span class="sc">$</span>Country <span class="sc">%in%</span> <span class="fu">c</span>(<span class="st">"Canada"</span>, <span class="st">"Costa Rica"</span>, <span class="st">"United States"</span>, <span class="st">"Mexico"</span>,  </span>
<span id="cb63-116"><a href="#cb63-116" aria-hidden="true" tabindex="-1"></a>                                   <span class="st">"Panama"</span>,<span class="st">"Trinidad and Tobago"</span>, <span class="st">"El Salvador"</span>, <span class="st">"Belize"</span>, <span class="st">"Guatemala"</span>,</span>
<span id="cb63-117"><a href="#cb63-117" aria-hidden="true" tabindex="-1"></a>                                   <span class="st">"Jamaica"</span>, <span class="st">"Nicaragua"</span>, <span class="st">"Dominican Republic"</span>, <span class="st">"Honduras"</span>,</span>
<span id="cb63-118"><a href="#cb63-118" aria-hidden="true" tabindex="-1"></a>                                   <span class="st">"Haiti"</span>))] <span class="ot">&lt;-</span> <span class="st">"North America"</span></span>
<span id="cb63-119"><a href="#cb63-119" aria-hidden="true" tabindex="-1"></a>happy<span class="sc">$</span>Continent[<span class="fu">which</span>(happy<span class="sc">$</span>Country <span class="sc">%in%</span> <span class="fu">c</span>(<span class="st">"Chile"</span>, <span class="st">"Brazil"</span>, <span class="st">"Argentina"</span>, <span class="st">"Uruguay"</span>,</span>
<span id="cb63-120"><a href="#cb63-120" aria-hidden="true" tabindex="-1"></a>                                   <span class="st">"Colombia"</span>, <span class="st">"Ecuador"</span>, <span class="st">"Bolivia"</span>, <span class="st">"Peru"</span>,</span>
<span id="cb63-121"><a href="#cb63-121" aria-hidden="true" tabindex="-1"></a>                                   <span class="st">"Paraguay"</span>, <span class="st">"Venezuela"</span>))] <span class="ot">&lt;-</span> <span class="st">"South America"</span></span>
<span id="cb63-122"><a href="#cb63-122" aria-hidden="true" tabindex="-1"></a>happy<span class="sc">$</span>Continent[<span class="fu">which</span>(happy<span class="sc">$</span>Country <span class="sc">%in%</span> <span class="fu">c</span>(<span class="st">"New Zealand"</span>, <span class="st">"Australia"</span>))] <span class="ot">&lt;-</span> <span class="st">"Australia"</span></span>
<span id="cb63-123"><a href="#cb63-123" aria-hidden="true" tabindex="-1"></a>happy<span class="sc">$</span>Continent[<span class="fu">which</span>(<span class="fu">is.na</span>(happy<span class="sc">$</span>Continent))] <span class="ot">&lt;-</span> <span class="st">"Africa"</span></span>
<span id="cb63-124"><a href="#cb63-124" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb63-125"><a href="#cb63-125" aria-hidden="true" tabindex="-1"></a><span class="co"># Moving the continent column's position in the dataset to the second column</span></span>
<span id="cb63-126"><a href="#cb63-126" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb63-127"><a href="#cb63-127" aria-hidden="true" tabindex="-1"></a>happy <span class="ot">&lt;-</span> happy <span class="sc">%&gt;%</span> <span class="fu">select</span>(Country,Continent, <span class="fu">everything</span>())</span>
<span id="cb63-128"><a href="#cb63-128" aria-hidden="true" tabindex="-1"></a>happy <span class="ot">&lt;-</span> happy[<span class="sc">!</span><span class="fu">duplicated</span>(happy), ]</span>
<span id="cb63-129"><a href="#cb63-129" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb63-130"><a href="#cb63-130" aria-hidden="true" tabindex="-1"></a><span class="co">#Renaming the final dataframe to happy</span></span>
<span id="cb63-131"><a href="#cb63-131" aria-hidden="true" tabindex="-1"></a><span class="fu">view</span>(happy)</span>
<span id="cb63-132"><a href="#cb63-132" aria-hidden="true" tabindex="-1"></a>happy <span class="ot">&lt;-</span> happy[<span class="sc">-</span>(<span class="dv">48</span><span class="sc">:</span><span class="dv">110</span>), ]</span>
<span id="cb63-133"><a href="#cb63-133" aria-hidden="true" tabindex="-1"></a><span class="fu">str</span>(happy)</span>
<span id="cb63-134"><a href="#cb63-134" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb63-135"><a href="#cb63-135" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb63-136"><a href="#cb63-136" aria-hidden="true" tabindex="-1"></a>The final data set "happy" consists of 12 variables and 136 observations. We can start the analysis now.</span>
<span id="cb63-137"><a href="#cb63-137" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb63-138"><a href="#cb63-138" aria-hidden="true" tabindex="-1"></a><span class="fu"># Exploratory Data Analysis</span></span>
<span id="cb63-139"><a href="#cb63-139" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb63-140"><a href="#cb63-140" aria-hidden="true" tabindex="-1"></a><span class="fu">## Understanding the correlation between happiness scores and other variables.</span></span>
<span id="cb63-141"><a href="#cb63-141" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb63-144"><a href="#cb63-144" aria-hidden="true" tabindex="-1"></a><span class="in">```{r}</span></span>
<span id="cb63-145"><a href="#cb63-145" aria-hidden="true" tabindex="-1"></a><span class="co"># Create a correlation plot</span></span>
<span id="cb63-146"><a href="#cb63-146" aria-hidden="true" tabindex="-1"></a><span class="fu">ggcorr</span>(happy, <span class="at">label =</span> <span class="cn">TRUE</span>, <span class="at">label_round =</span> <span class="dv">2</span>, <span class="at">label_size =</span> <span class="fl">3.5</span>, <span class="at">size =</span> <span class="dv">4</span>, <span class="at">hjust =</span> .<span class="dv">85</span>) <span class="sc">+</span></span>
<span id="cb63-147"><a href="#cb63-147" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ggtitle</span>(<span class="st">"Plot- 1: Correlation Heatmap"</span>) <span class="sc">+</span></span>
<span id="cb63-148"><a href="#cb63-148" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme</span>(<span class="at">plot.title =</span> <span class="fu">element_text</span>(<span class="at">hjust =</span> <span class="fl">0.5</span>))</span>
<span id="cb63-149"><a href="#cb63-149" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb63-150"><a href="#cb63-150" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb63-151"><a href="#cb63-151" aria-hidden="true" tabindex="-1"></a>Observations from the correlation plot:</span>
<span id="cb63-152"><a href="#cb63-152" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb63-153"><a href="#cb63-153" aria-hidden="true" tabindex="-1"></a>The happiness score is,</span>
<span id="cb63-154"><a href="#cb63-154" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb63-155"><a href="#cb63-155" aria-hidden="true" tabindex="-1"></a><span class="ss">-   </span>Strongly correlating with GDP per capita, Urbanization rate and Life expectancy.</span>
<span id="cb63-156"><a href="#cb63-156" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb63-157"><a href="#cb63-157" aria-hidden="true" tabindex="-1"></a><span class="ss">-   </span>Inversely correlated with suicidal rate and population growth.</span>
<span id="cb63-158"><a href="#cb63-158" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb63-159"><a href="#cb63-159" aria-hidden="true" tabindex="-1"></a><span class="ss">-   </span>No correlation with sex ratio.</span>
<span id="cb63-160"><a href="#cb63-160" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb63-163"><a href="#cb63-163" aria-hidden="true" tabindex="-1"></a><span class="in">```{r}</span></span>
<span id="cb63-164"><a href="#cb63-164" aria-hidden="true" tabindex="-1"></a><span class="co">#plotting the happiness data on world map</span></span>
<span id="cb63-165"><a href="#cb63-165" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb63-166"><a href="#cb63-166" aria-hidden="true" tabindex="-1"></a>plot_2 <span class="ot">&lt;-</span> <span class="fu">select</span>(happy, <span class="st">"Continent"</span>, <span class="st">"Country"</span>, <span class="st">"Happiness"</span>)</span>
<span id="cb63-167"><a href="#cb63-167" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb63-168"><a href="#cb63-168" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(maps)</span>
<span id="cb63-169"><a href="#cb63-169" aria-hidden="true" tabindex="-1"></a>world.data <span class="ot">&lt;-</span> <span class="fu">map_data</span>(<span class="st">"world"</span>)</span>
<span id="cb63-170"><a href="#cb63-170" aria-hidden="true" tabindex="-1"></a>map.world_joined <span class="ot">&lt;-</span> <span class="fu">left_join</span>(world.data, plot_2, <span class="at">by =</span> <span class="fu">c</span>(<span class="st">'region'</span><span class="ot">=</span><span class="st">'Country'</span>))</span>
<span id="cb63-171"><a href="#cb63-171" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb63-172"><a href="#cb63-172" aria-hidden="true" tabindex="-1"></a>map1 <span class="ot">&lt;-</span> <span class="fu">ggplot</span>(map.world_joined, <span class="fu">aes</span>(<span class="at">x=</span>long, <span class="at">y=</span>lat, <span class="at">group=</span>group)) <span class="sc">+</span></span>
<span id="cb63-173"><a href="#cb63-173" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_polygon</span>(<span class="fu">aes</span>(<span class="at">fill=</span>Happiness), <span class="at">color=</span><span class="st">"black"</span>)</span>
<span id="cb63-174"><a href="#cb63-174" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb63-175"><a href="#cb63-175" aria-hidden="true" tabindex="-1"></a>map2 <span class="ot">&lt;-</span> map1 <span class="sc">+</span> <span class="fu">scale_fill_gradient</span>(<span class="at">name =</span> <span class="st">"Happiness Score"</span>, <span class="at">low =</span> <span class="st">"yellow"</span>, <span class="at">high =</span> <span class="st">"red"</span>, <span class="at">na.value =</span> <span class="st">"grey50"</span>) <span class="sc">+</span></span>
<span id="cb63-176"><a href="#cb63-176" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme</span>(<span class="at">axis.text.x =</span> <span class="fu">element_blank</span>(), </span>
<span id="cb63-177"><a href="#cb63-177" aria-hidden="true" tabindex="-1"></a>        <span class="at">axis.text.y =</span> <span class="fu">element_blank</span>(),</span>
<span id="cb63-178"><a href="#cb63-178" aria-hidden="true" tabindex="-1"></a>        <span class="at">axis.ticks =</span> <span class="fu">element_blank</span>(),</span>
<span id="cb63-179"><a href="#cb63-179" aria-hidden="true" tabindex="-1"></a>        <span class="at">axis.title.y =</span> <span class="fu">element_blank</span>(),</span>
<span id="cb63-180"><a href="#cb63-180" aria-hidden="true" tabindex="-1"></a>        <span class="at">axis.title.x =</span> <span class="fu">element_blank</span>(),</span>
<span id="cb63-181"><a href="#cb63-181" aria-hidden="true" tabindex="-1"></a>        <span class="at">rect =</span> <span class="fu">element_blank</span>())</span>
<span id="cb63-182"><a href="#cb63-182" aria-hidden="true" tabindex="-1"></a>map2</span>
<span id="cb63-183"><a href="#cb63-183" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb63-184"><a href="#cb63-184" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb63-185"><a href="#cb63-185" aria-hidden="true" tabindex="-1"></a>North America, Europe and Australia appear to be the happiest.</span>
<span id="cb63-186"><a href="#cb63-186" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb63-187"><a href="#cb63-187" aria-hidden="true" tabindex="-1"></a>South America, North Asia, Western Africa and countries/islands in the indian ocean appear to be happy on average.</span>
<span id="cb63-188"><a href="#cb63-188" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb63-189"><a href="#cb63-189" aria-hidden="true" tabindex="-1"></a>South Africa, India are unhappy and of course Afghanistan is the unhappiest country in the world.</span>
<span id="cb63-190"><a href="#cb63-190" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb63-191"><a href="#cb63-191" aria-hidden="true" tabindex="-1"></a><span class="fu">### Happiness score comparison on different continents</span></span>
<span id="cb63-192"><a href="#cb63-192" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb63-193"><a href="#cb63-193" aria-hidden="true" tabindex="-1"></a><span class="in">```{r message=FALSE, warning=FALSE, error=FALSE}</span></span>
<span id="cb63-194"><a href="#cb63-194" aria-hidden="true" tabindex="-1"></a><span class="do">####### Happiness score for each continent</span></span>
<span id="cb63-195"><a href="#cb63-195" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb63-196"><a href="#cb63-196" aria-hidden="true" tabindex="-1"></a>gg1 <span class="ot">&lt;-</span> <span class="fu">ggplot</span>(happy,</span>
<span id="cb63-197"><a href="#cb63-197" aria-hidden="true" tabindex="-1"></a>              <span class="fu">aes</span>(<span class="at">x=</span>Continent,</span>
<span id="cb63-198"><a href="#cb63-198" aria-hidden="true" tabindex="-1"></a>                  <span class="at">y=</span>Happiness,</span>
<span id="cb63-199"><a href="#cb63-199" aria-hidden="true" tabindex="-1"></a>                  <span class="at">color=</span>Continent))<span class="sc">+</span></span>
<span id="cb63-200"><a href="#cb63-200" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_point</span>() <span class="sc">+</span> <span class="fu">theme_bw</span>() <span class="sc">+</span></span>
<span id="cb63-201"><a href="#cb63-201" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme</span>(<span class="at">axis.title =</span> <span class="fu">element_text</span>(<span class="at">family =</span> <span class="st">"Helvetica"</span>, <span class="at">size =</span> (<span class="dv">8</span>)))</span>
<span id="cb63-202"><a href="#cb63-202" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb63-203"><a href="#cb63-203" aria-hidden="true" tabindex="-1"></a>gg2 <span class="ot">&lt;-</span> <span class="fu">ggplot</span>(happy , <span class="fu">aes</span>(<span class="at">x =</span> Continent, <span class="at">y =</span> Happiness)) <span class="sc">+</span></span>
<span id="cb63-204"><a href="#cb63-204" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_boxplot</span>(<span class="fu">aes</span>(<span class="at">fill=</span>Continent)) <span class="sc">+</span> <span class="fu">theme_bw</span>() <span class="sc">+</span></span>
<span id="cb63-205"><a href="#cb63-205" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme</span>(<span class="at">axis.title =</span> <span class="fu">element_text</span>(<span class="at">family =</span> <span class="st">"Helvetica"</span>, <span class="at">size =</span> (<span class="dv">8</span>)))</span>
<span id="cb63-206"><a href="#cb63-206" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb63-207"><a href="#cb63-207" aria-hidden="true" tabindex="-1"></a>gg3 <span class="ot">&lt;-</span> <span class="fu">ggplot</span>(happy,<span class="fu">aes</span>(<span class="at">x=</span>Continent,<span class="at">y=</span>Happiness))<span class="sc">+</span></span>
<span id="cb63-208"><a href="#cb63-208" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_violin</span>(<span class="fu">aes</span>(<span class="at">fill=</span>Continent),<span class="at">alpha=</span><span class="fl">0.7</span>)<span class="sc">+</span> <span class="fu">theme_bw</span>() <span class="sc">+</span></span>
<span id="cb63-209"><a href="#cb63-209" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme</span>(<span class="at">axis.title =</span> <span class="fu">element_text</span>(<span class="at">family =</span> <span class="st">"Helvetica"</span>, <span class="at">size =</span> (<span class="dv">8</span>)))</span>
<span id="cb63-210"><a href="#cb63-210" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb63-211"><a href="#cb63-211" aria-hidden="true" tabindex="-1"></a><span class="co"># Compute descriptive statistics by groups</span></span>
<span id="cb63-212"><a href="#cb63-212" aria-hidden="true" tabindex="-1"></a>stable <span class="ot">&lt;-</span> <span class="fu">desc_statby</span>(happy, <span class="at">measure.var =</span> <span class="st">"Happiness"</span>,</span>
<span id="cb63-213"><a href="#cb63-213" aria-hidden="true" tabindex="-1"></a>                      <span class="at">grps =</span> <span class="st">"Continent"</span>)</span>
<span id="cb63-214"><a href="#cb63-214" aria-hidden="true" tabindex="-1"></a>stable <span class="ot">&lt;-</span> stable[, <span class="fu">c</span>(<span class="st">"Continent"</span>,<span class="st">"mean"</span>,<span class="st">"median"</span>)]</span>
<span id="cb63-215"><a href="#cb63-215" aria-hidden="true" tabindex="-1"></a><span class="fu">names</span>(stable) <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="st">"Continent"</span>, <span class="st">"Mean of happiness score"</span>,<span class="st">"Median of happiness score"</span>)</span>
<span id="cb63-216"><a href="#cb63-216" aria-hidden="true" tabindex="-1"></a><span class="co"># Summary table plot</span></span>
<span id="cb63-217"><a href="#cb63-217" aria-hidden="true" tabindex="-1"></a>stable.p <span class="ot">&lt;-</span> <span class="fu">ggtexttable</span>(stable,<span class="at">rows =</span> <span class="cn">NULL</span>, </span>
<span id="cb63-218"><a href="#cb63-218" aria-hidden="true" tabindex="-1"></a>                         <span class="at">theme =</span> <span class="fu">ttheme</span>(<span class="st">"classic"</span>))</span>
<span id="cb63-219"><a href="#cb63-219" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb63-220"><a href="#cb63-220" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb63-221"><a href="#cb63-221" aria-hidden="true" tabindex="-1"></a><span class="fu">ggarrange</span>(gg1, gg2, <span class="at">ncol =</span> <span class="dv">1</span>, <span class="at">nrow =</span> <span class="dv">2</span>)</span>
<span id="cb63-222"><a href="#cb63-222" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb63-223"><a href="#cb63-223" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb63-224"><a href="#cb63-224" aria-hidden="true" tabindex="-1"></a><span class="in">```{r message=FALSE, warning=FALSE, error=FALSE}</span></span>
<span id="cb63-225"><a href="#cb63-225" aria-hidden="true" tabindex="-1"></a><span class="fu">ggarrange</span>(gg3, stable.p, <span class="at">ncol =</span> <span class="dv">1</span>, <span class="at">nrow =</span> <span class="dv">2</span>)</span>
<span id="cb63-226"><a href="#cb63-226" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb63-227"><a href="#cb63-227" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb63-228"><a href="#cb63-228" aria-hidden="true" tabindex="-1"></a>As we have seen before, Australia has the highest median happiness score. Europe, South America, and North America are in the second place regarding median happiness score. Asia has the lowest median after Africa. We can see the range of happiness score for different continents, and also the concentration of happiness score.</span>
<span id="cb63-229"><a href="#cb63-229" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb63-230"><a href="#cb63-230" aria-hidden="true" tabindex="-1"></a>Let's see the correlation between happiness score and 3 major factors in the happiness data set that are GDP per capita, Life Expectancy, Urbanization rate to understand how they are varying.</span>
<span id="cb63-231"><a href="#cb63-231" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb63-234"><a href="#cb63-234" aria-hidden="true" tabindex="-1"></a><span class="in">```{r}</span></span>
<span id="cb63-235"><a href="#cb63-235" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(<span class="fu">subset</span>(happy, happy<span class="sc">$</span>Continent <span class="sc">!=</span> <span class="st">"Australia"</span>), <span class="fu">aes</span>(<span class="at">x =</span>  GDP.per.capita, <span class="at">y =</span> Happiness)) <span class="sc">+</span> </span>
<span id="cb63-236"><a href="#cb63-236" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_point</span>(<span class="fu">aes</span>(<span class="at">color=</span>Continent), <span class="at">size =</span> <span class="dv">3</span>, <span class="at">alpha =</span> <span class="fl">0.8</span>) <span class="sc">+</span>  </span>
<span id="cb63-237"><a href="#cb63-237" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_smooth</span>(<span class="fu">aes</span>(<span class="at">color =</span> Continent, <span class="at">fill =</span> Continent), </span>
<span id="cb63-238"><a href="#cb63-238" aria-hidden="true" tabindex="-1"></a>              <span class="at">method =</span> <span class="st">"lm"</span>, <span class="at">fullrange =</span> <span class="cn">TRUE</span>) <span class="sc">+</span></span>
<span id="cb63-239"><a href="#cb63-239" aria-hidden="true" tabindex="-1"></a>  <span class="fu">facet_wrap</span>(<span class="sc">~</span>Continent) <span class="sc">+</span></span>
<span id="cb63-240"><a href="#cb63-240" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_bw</span>() <span class="sc">+</span> <span class="fu">labs</span>(<span class="at">title =</span> <span class="st">"Scatter plot with regression line Happiness vs GDP per capita"</span>)</span>
<span id="cb63-241"><a href="#cb63-241" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb63-242"><a href="#cb63-242" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb63-243"><a href="#cb63-243" aria-hidden="true" tabindex="-1"></a>The correlation between GDP per capita and happiness score in Europe, North America, and Asia is more significant than the other continents. Worth mentioning that we will not take Australia into account because there are just two countries in Australia and creating scatter plot with the regression line for this continent will not give us any insight.</span>
<span id="cb63-244"><a href="#cb63-244" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb63-247"><a href="#cb63-247" aria-hidden="true" tabindex="-1"></a><span class="in">```{r}</span></span>
<span id="cb63-248"><a href="#cb63-248" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(<span class="fu">subset</span>(happy, happy<span class="sc">$</span>Continent <span class="sc">!=</span> <span class="st">"Australia"</span>), <span class="fu">aes</span>(<span class="at">x =</span>  urbanization.rate, <span class="at">y =</span> Happiness)) <span class="sc">+</span> </span>
<span id="cb63-249"><a href="#cb63-249" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_point</span>(<span class="fu">aes</span>(<span class="at">color=</span>Continent), <span class="at">size =</span> <span class="dv">3</span>, <span class="at">alpha =</span> <span class="fl">0.8</span>) <span class="sc">+</span>  </span>
<span id="cb63-250"><a href="#cb63-250" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_smooth</span>(<span class="fu">aes</span>(<span class="at">color =</span> Continent, <span class="at">fill =</span> Continent), </span>
<span id="cb63-251"><a href="#cb63-251" aria-hidden="true" tabindex="-1"></a>              <span class="at">method =</span> <span class="st">"lm"</span>, <span class="at">fullrange =</span> <span class="cn">TRUE</span>) <span class="sc">+</span></span>
<span id="cb63-252"><a href="#cb63-252" aria-hidden="true" tabindex="-1"></a>  <span class="fu">facet_wrap</span>(<span class="sc">~</span>Continent) <span class="sc">+</span></span>
<span id="cb63-253"><a href="#cb63-253" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_bw</span>() <span class="sc">+</span> <span class="fu">labs</span>(<span class="at">title =</span> <span class="st">"Scatter plot with regression line Happiness vs Urbanization rate"</span>)</span>
<span id="cb63-254"><a href="#cb63-254" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb63-255"><a href="#cb63-255" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb63-256"><a href="#cb63-256" aria-hidden="true" tabindex="-1"></a>The relationship between happiness score and urbanization rate is very significant in Asia, Africa and Europe followed by North america and south america.</span>
<span id="cb63-257"><a href="#cb63-257" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb63-260"><a href="#cb63-260" aria-hidden="true" tabindex="-1"></a><span class="in">```{r}</span></span>
<span id="cb63-261"><a href="#cb63-261" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(<span class="fu">subset</span>(happy, happy<span class="sc">$</span>Continent <span class="sc">!=</span> <span class="st">"Australia"</span>), <span class="fu">aes</span>(<span class="at">x =</span>  Life.expectancy, <span class="at">y =</span> Happiness)) <span class="sc">+</span> </span>
<span id="cb63-262"><a href="#cb63-262" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_point</span>(<span class="fu">aes</span>(<span class="at">color=</span>Continent), <span class="at">size =</span> <span class="dv">3</span>, <span class="at">alpha =</span> <span class="fl">0.8</span>) <span class="sc">+</span>  </span>
<span id="cb63-263"><a href="#cb63-263" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_smooth</span>(<span class="fu">aes</span>(<span class="at">color =</span> Continent, <span class="at">fill =</span> Continent), </span>
<span id="cb63-264"><a href="#cb63-264" aria-hidden="true" tabindex="-1"></a>              <span class="at">method =</span> <span class="st">"lm"</span>, <span class="at">fullrange =</span> <span class="cn">TRUE</span>) <span class="sc">+</span></span>
<span id="cb63-265"><a href="#cb63-265" aria-hidden="true" tabindex="-1"></a>  <span class="fu">facet_wrap</span>(<span class="sc">~</span>Continent) <span class="sc">+</span></span>
<span id="cb63-266"><a href="#cb63-266" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_bw</span>() <span class="sc">+</span> <span class="fu">labs</span>(<span class="at">title =</span> <span class="st">"Scatter plot with regression line Happiness vs Life Expectancy"</span>)</span>
<span id="cb63-267"><a href="#cb63-267" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb63-268"><a href="#cb63-268" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb63-269"><a href="#cb63-269" aria-hidden="true" tabindex="-1"></a>The relationship between happiness score and life expectancy is very significant in Asia, Europe and Africa followed by North america and south america.</span>
<span id="cb63-270"><a href="#cb63-270" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb63-271"><a href="#cb63-271" aria-hidden="true" tabindex="-1"></a><span class="fu">## Modeling &amp; Hypothesis testing</span></span>
<span id="cb63-272"><a href="#cb63-272" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb63-273"><a href="#cb63-273" aria-hidden="true" tabindex="-1"></a>From the above visualizations and analysis, we have found that GDP per capita, Urbanization and Life Expectancy play major role in the happiness score. Whereas suicide rate and population growth has an inverse relationship. Let's build a model for estimating happiness scores based on these control variables and see which of these has effect on the overall happiness scores.</span>
<span id="cb63-274"><a href="#cb63-274" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb63-275"><a href="#cb63-275" aria-hidden="true" tabindex="-1"></a><span class="fu">### Model-1</span></span>
<span id="cb63-276"><a href="#cb63-276" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb63-279"><a href="#cb63-279" aria-hidden="true" tabindex="-1"></a><span class="in">```{r}</span></span>
<span id="cb63-280"><a href="#cb63-280" aria-hidden="true" tabindex="-1"></a><span class="co">#Model-1</span></span>
<span id="cb63-281"><a href="#cb63-281" aria-hidden="true" tabindex="-1"></a>model1 <span class="ot">&lt;-</span> <span class="fu">lm</span>(Happiness <span class="sc">~</span> GDP.per.capita <span class="sc">+</span> urbanization.rate <span class="sc">+</span> Life.expectancy, <span class="at">data =</span> happy)</span>
<span id="cb63-282"><a href="#cb63-282" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(model1)</span>
<span id="cb63-283"><a href="#cb63-283" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb63-284"><a href="#cb63-284" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb63-285"><a href="#cb63-285" aria-hidden="true" tabindex="-1"></a>It can be seen that p-value of the F-statistic is <span class="sc">\&lt;</span> 2.2e-16, which is highly significant. This means that, at least, one of the predictor/control variables ( GDP per capita, Urbanization rare and Life Expectancy) is significantly related to the outcome variable (Happiness score).</span>
<span id="cb63-286"><a href="#cb63-286" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb63-287"><a href="#cb63-287" aria-hidden="true" tabindex="-1"></a>It can be seen that, changing in GDP per capita and Life expectancy are significantly associated to changes in happiness scores while changes in urbanization rate is not significantly associated with sales.</span>
<span id="cb63-288"><a href="#cb63-288" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb63-291"><a href="#cb63-291" aria-hidden="true" tabindex="-1"></a><span class="in">```{r}</span></span>
<span id="cb63-292"><a href="#cb63-292" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(model1)<span class="sc">$</span>coefficient</span>
<span id="cb63-293"><a href="#cb63-293" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb63-294"><a href="#cb63-294" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb63-297"><a href="#cb63-297" aria-hidden="true" tabindex="-1"></a><span class="in">```{r}</span></span>
<span id="cb63-298"><a href="#cb63-298" aria-hidden="true" tabindex="-1"></a><span class="fu">confint</span>(model1)</span>
<span id="cb63-299"><a href="#cb63-299" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb63-300"><a href="#cb63-300" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb63-301"><a href="#cb63-301" aria-hidden="true" tabindex="-1"></a>Lets see how this model behaves if we apply log on the variables</span>
<span id="cb63-302"><a href="#cb63-302" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb63-305"><a href="#cb63-305" aria-hidden="true" tabindex="-1"></a><span class="in">```{r}</span></span>
<span id="cb63-306"><a href="#cb63-306" aria-hidden="true" tabindex="-1"></a><span class="co">#Model-1 with log</span></span>
<span id="cb63-307"><a href="#cb63-307" aria-hidden="true" tabindex="-1"></a>model1_log <span class="ot">&lt;-</span> <span class="fu">lm</span>(Happiness <span class="sc">~</span> <span class="fu">log</span>(GDP.per.capita <span class="sc">+</span> urbanization.rate <span class="sc">+</span> Life.expectancy), <span class="at">data =</span> happy)</span>
<span id="cb63-308"><a href="#cb63-308" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(model1_log)</span>
<span id="cb63-309"><a href="#cb63-309" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb63-310"><a href="#cb63-310" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb63-311"><a href="#cb63-311" aria-hidden="true" tabindex="-1"></a>The R-Squared value drops from 0.6693 to 0.6134 by applying log for model-1.</span>
<span id="cb63-312"><a href="#cb63-312" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb63-313"><a href="#cb63-313" aria-hidden="true" tabindex="-1"></a><span class="fu">### Model-2</span></span>
<span id="cb63-314"><a href="#cb63-314" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb63-317"><a href="#cb63-317" aria-hidden="true" tabindex="-1"></a><span class="in">```{r}</span></span>
<span id="cb63-318"><a href="#cb63-318" aria-hidden="true" tabindex="-1"></a><span class="co">#Model-2</span></span>
<span id="cb63-319"><a href="#cb63-319" aria-hidden="true" tabindex="-1"></a>model2  <span class="ot">&lt;-</span> <span class="fu">lm</span>(Happiness <span class="sc">~</span> GDP.per.capita <span class="sc">+</span> Life.expectancy, <span class="at">data =</span> happy)</span>
<span id="cb63-320"><a href="#cb63-320" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(model2)</span>
<span id="cb63-321"><a href="#cb63-321" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb63-322"><a href="#cb63-322" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb63-325"><a href="#cb63-325" aria-hidden="true" tabindex="-1"></a><span class="in">```{r}</span></span>
<span id="cb63-326"><a href="#cb63-326" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(model2)<span class="sc">$</span>coefficient</span>
<span id="cb63-327"><a href="#cb63-327" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb63-328"><a href="#cb63-328" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb63-329"><a href="#cb63-329" aria-hidden="true" tabindex="-1"></a>It turns out Life Expectancy is strongly associated with happiness scores and GDP per capita follows life expectancy.</span>
<span id="cb63-330"><a href="#cb63-330" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb63-333"><a href="#cb63-333" aria-hidden="true" tabindex="-1"></a><span class="in">```{r}</span></span>
<span id="cb63-334"><a href="#cb63-334" aria-hidden="true" tabindex="-1"></a><span class="fu">confint</span>(model2)</span>
<span id="cb63-335"><a href="#cb63-335" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb63-336"><a href="#cb63-336" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb63-337"><a href="#cb63-337" aria-hidden="true" tabindex="-1"></a>However the R-squared values of Model-1 and Model-2 are approximately around 65-66%. Hence we cannot say which model is best fit to predict the happiness scores.</span>
<span id="cb63-338"><a href="#cb63-338" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb63-339"><a href="#cb63-339" aria-hidden="true" tabindex="-1"></a>Lets consider all the 5 control variables and see the results.</span>
<span id="cb63-340"><a href="#cb63-340" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb63-341"><a href="#cb63-341" aria-hidden="true" tabindex="-1"></a>Lets see how model-2 behaves if we apply log on the variables</span>
<span id="cb63-342"><a href="#cb63-342" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb63-345"><a href="#cb63-345" aria-hidden="true" tabindex="-1"></a><span class="in">```{r}</span></span>
<span id="cb63-346"><a href="#cb63-346" aria-hidden="true" tabindex="-1"></a><span class="co">#Model-2 with log</span></span>
<span id="cb63-347"><a href="#cb63-347" aria-hidden="true" tabindex="-1"></a>model2_log  <span class="ot">&lt;-</span> <span class="fu">lm</span>(Happiness <span class="sc">~</span> <span class="fu">log</span>(GDP.per.capita <span class="sc">+</span> Life.expectancy), <span class="at">data =</span> happy)</span>
<span id="cb63-348"><a href="#cb63-348" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(model2_log)</span>
<span id="cb63-349"><a href="#cb63-349" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb63-350"><a href="#cb63-350" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb63-351"><a href="#cb63-351" aria-hidden="true" tabindex="-1"></a>The R-Squared value drops from 0.66 to 0.61 by applying log for model-2.</span>
<span id="cb63-352"><a href="#cb63-352" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb63-353"><a href="#cb63-353" aria-hidden="true" tabindex="-1"></a><span class="fu">### Model-3</span></span>
<span id="cb63-354"><a href="#cb63-354" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb63-357"><a href="#cb63-357" aria-hidden="true" tabindex="-1"></a><span class="in">```{r}</span></span>
<span id="cb63-358"><a href="#cb63-358" aria-hidden="true" tabindex="-1"></a><span class="co">#Model-3</span></span>
<span id="cb63-359"><a href="#cb63-359" aria-hidden="true" tabindex="-1"></a>model3 <span class="ot">&lt;-</span> <span class="fu">lm</span>(Happiness <span class="sc">~</span> GDP.per.capita <span class="sc">+</span> urbanization.rate <span class="sc">+</span> Life.expectancy <span class="sc">+</span> Suicide.rate <span class="sc">+</span> Population.growth , <span class="at">data =</span> happy)</span>
<span id="cb63-360"><a href="#cb63-360" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(model3)</span>
<span id="cb63-361"><a href="#cb63-361" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb63-362"><a href="#cb63-362" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb63-363"><a href="#cb63-363" aria-hidden="true" tabindex="-1"></a>The R-squared remains same after adding additional two control variables. So far, the second model fits the happiness scores.</span>
<span id="cb63-364"><a href="#cb63-364" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb63-365"><a href="#cb63-365" aria-hidden="true" tabindex="-1"></a>Lets see how model-3 behaves if we apply log on the control variables</span>
<span id="cb63-366"><a href="#cb63-366" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb63-369"><a href="#cb63-369" aria-hidden="true" tabindex="-1"></a><span class="in">```{r}</span></span>
<span id="cb63-370"><a href="#cb63-370" aria-hidden="true" tabindex="-1"></a><span class="co">#Model-3 with log</span></span>
<span id="cb63-371"><a href="#cb63-371" aria-hidden="true" tabindex="-1"></a>model3_log <span class="ot">&lt;-</span> <span class="fu">lm</span>(Happiness <span class="sc">~</span> <span class="fu">log</span>(GDP.per.capita <span class="sc">+</span> urbanization.rate <span class="sc">+</span> Life.expectancy <span class="sc">+</span> Suicide.rate <span class="sc">+</span> Population.growth) , <span class="at">data =</span> happy)</span>
<span id="cb63-372"><a href="#cb63-372" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(model3_log)</span>
<span id="cb63-373"><a href="#cb63-373" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb63-374"><a href="#cb63-374" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb63-375"><a href="#cb63-375" aria-hidden="true" tabindex="-1"></a>The R-squared values drops from 0.66 to 0.61 by application of log.</span>
<span id="cb63-376"><a href="#cb63-376" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb63-377"><a href="#cb63-377" aria-hidden="true" tabindex="-1"></a><span class="fu">## Model comprision</span></span>
<span id="cb63-378"><a href="#cb63-378" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb63-379"><a href="#cb63-379" aria-hidden="true" tabindex="-1"></a>+-----------------------------------------------------------------------------------------------------+---------------------+--------------------+-----------------------------------+</span>
<span id="cb63-380"><a href="#cb63-380" aria-hidden="true" tabindex="-1"></a>| Models                                                                                              | Multiple R-squared  | Adjusted R-squared | Significant Variables             |</span>
<span id="cb63-381"><a href="#cb63-381" aria-hidden="true" tabindex="-1"></a>+=====================================================================================================+=====================+====================+===================================+</span>
<span id="cb63-382"><a href="#cb63-382" aria-hidden="true" tabindex="-1"></a>| Model-1 (GDP per capita+Urbanization rate+Life expectancy)                                          | 0.6693              | 0.6618             | GDP per capita &amp; Life Expectancy  |</span>
<span id="cb63-383"><a href="#cb63-383" aria-hidden="true" tabindex="-1"></a>+-----------------------------------------------------------------------------------------------------+---------------------+--------------------+-----------------------------------+</span>
<span id="cb63-384"><a href="#cb63-384" aria-hidden="true" tabindex="-1"></a>| Model-1 (Log(GDP per capita+Urbanization rate+Life expectancy))                                     | 0.6134              | 0.6105             | <span class="sc">\-</span>                                |</span>
<span id="cb63-385"><a href="#cb63-385" aria-hidden="true" tabindex="-1"></a>+-----------------------------------------------------------------------------------------------------+---------------------+--------------------+-----------------------------------+</span>
<span id="cb63-386"><a href="#cb63-386" aria-hidden="true" tabindex="-1"></a>| Model-2 (GDP per capita+Life expectancy)                                                            | 0.6601              | 0.655              | GDP per capita &amp; Life Expectancy. |</span>
<span id="cb63-387"><a href="#cb63-387" aria-hidden="true" tabindex="-1"></a>|                                                                                                     |                     |                    |                                   |</span>
<span id="cb63-388"><a href="#cb63-388" aria-hidden="true" tabindex="-1"></a>|                                                                                                     |                     |                    | Life expectancy <span class="sc">\&gt;</span> GDP per capita |</span>
<span id="cb63-389"><a href="#cb63-389" aria-hidden="true" tabindex="-1"></a>+-----------------------------------------------------------------------------------------------------+---------------------+--------------------+-----------------------------------+</span>
<span id="cb63-390"><a href="#cb63-390" aria-hidden="true" tabindex="-1"></a>| Model-2 (Log(GDP per capita+Life expectancy))                                                       | 0.6129              | 0.61               | <span class="sc">\-</span>                                |</span>
<span id="cb63-391"><a href="#cb63-391" aria-hidden="true" tabindex="-1"></a>+-----------------------------------------------------------------------------------------------------+---------------------+--------------------+-----------------------------------+</span>
<span id="cb63-392"><a href="#cb63-392" aria-hidden="true" tabindex="-1"></a>| Model-3 (GDP per capita+Urbanization rate +Life expectancy + Suicide rate + population growth)      | 0.6601              | 0.655              | GDP per capita &amp; Life Expectancy  |</span>
<span id="cb63-393"><a href="#cb63-393" aria-hidden="true" tabindex="-1"></a>+-----------------------------------------------------------------------------------------------------+---------------------+--------------------+-----------------------------------+</span>
<span id="cb63-394"><a href="#cb63-394" aria-hidden="true" tabindex="-1"></a>| Model-3 (Log(GDP per capita+Urbanization rate +Life expectancy + Suicide rate + population growth)) | 0.6136              | 0.6107             | GDP per capita &amp; Life Expectancy. |</span>
<span id="cb63-395"><a href="#cb63-395" aria-hidden="true" tabindex="-1"></a>|                                                                                                     |                     |                    |                                   |</span>
<span id="cb63-396"><a href="#cb63-396" aria-hidden="true" tabindex="-1"></a>|                                                                                                     |                     |                    | Life expectancy <span class="sc">\&gt;</span> GDP per capita |</span>
<span id="cb63-397"><a href="#cb63-397" aria-hidden="true" tabindex="-1"></a>+-----------------------------------------------------------------------------------------------------+---------------------+--------------------+-----------------------------------+</span>
<span id="cb63-398"><a href="#cb63-398" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb63-399"><a href="#cb63-399" aria-hidden="true" tabindex="-1"></a><span class="ss">-   </span>It can be derived from the above table that the adjusted R-Squared for Model-2 is better than other two models, hence it can be said that Model-2 is a good fit.</span>
<span id="cb63-400"><a href="#cb63-400" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb63-401"><a href="#cb63-401" aria-hidden="true" tabindex="-1"></a><span class="ss">-   </span>Application of Logarithm on the control variables reduced the R-squared values in all the 3 models.</span>
<span id="cb63-402"><a href="#cb63-402" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb63-403"><a href="#cb63-403" aria-hidden="true" tabindex="-1"></a><span class="ss">-   </span>**Hypothesis testing conclusion:**</span>
<span id="cb63-404"><a href="#cb63-404" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb63-405"><a href="#cb63-405" aria-hidden="true" tabindex="-1"></a>    Turns out we have evidence for all the 3 hypothesis but,</span>
<span id="cb63-406"><a href="#cb63-406" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb63-407"><a href="#cb63-407" aria-hidden="true" tabindex="-1"></a><span class="ss">    -   </span>We have a strong evidence for hypothesis-3 i.e. Higher Life Expectancy leads to country's happiness.</span>
<span id="cb63-408"><a href="#cb63-408" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb63-409"><a href="#cb63-409" aria-hidden="true" tabindex="-1"></a><span class="sc">\-\-\-\-\-</span>-</span>
<span id="cb63-410"><a href="#cb63-410" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb63-411"><a href="#cb63-411" aria-hidden="true" tabindex="-1"></a>As we have concluded that Model-2 is a goof fit, Lets divide the happy dataset into training and test and plot the predicted happiness scores for Model-2.</span>
<span id="cb63-412"><a href="#cb63-412" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb63-415"><a href="#cb63-415" aria-hidden="true" tabindex="-1"></a><span class="in">```{r}</span></span>
<span id="cb63-416"><a href="#cb63-416" aria-hidden="true" tabindex="-1"></a><span class="co"># Splitting the dataset into the Training set and Test set</span></span>
<span id="cb63-417"><a href="#cb63-417" aria-hidden="true" tabindex="-1"></a><span class="fu">set.seed</span>(<span class="dv">123</span>)</span>
<span id="cb63-418"><a href="#cb63-418" aria-hidden="true" tabindex="-1"></a>dataset <span class="ot">&lt;-</span> happy[<span class="dv">4</span><span class="sc">:</span><span class="dv">10</span>]</span>
<span id="cb63-419"><a href="#cb63-419" aria-hidden="true" tabindex="-1"></a>split <span class="ot">=</span> <span class="fu">sample.split</span>(dataset<span class="sc">$</span>Happiness, <span class="at">SplitRatio =</span> <span class="fl">0.8</span>)</span>
<span id="cb63-420"><a href="#cb63-420" aria-hidden="true" tabindex="-1"></a>training_set <span class="ot">=</span> <span class="fu">subset</span>(dataset, split <span class="sc">==</span> <span class="cn">TRUE</span>)</span>
<span id="cb63-421"><a href="#cb63-421" aria-hidden="true" tabindex="-1"></a>test_set <span class="ot">=</span> <span class="fu">subset</span>(dataset, split <span class="sc">==</span> <span class="cn">FALSE</span>)</span>
<span id="cb63-422"><a href="#cb63-422" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb63-423"><a href="#cb63-423" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb63-426"><a href="#cb63-426" aria-hidden="true" tabindex="-1"></a><span class="in">```{r}</span></span>
<span id="cb63-427"><a href="#cb63-427" aria-hidden="true" tabindex="-1"></a><span class="co"># Fitting Multiple Linear Regression to the Training set on Model-2</span></span>
<span id="cb63-428"><a href="#cb63-428" aria-hidden="true" tabindex="-1"></a>regressor_lm <span class="ot">=</span> <span class="fu">lm</span>(<span class="at">formula =</span> Happiness <span class="sc">~</span> GDP.per.capita <span class="sc">+</span> Life.expectancy,</span>
<span id="cb63-429"><a href="#cb63-429" aria-hidden="true" tabindex="-1"></a>               <span class="at">data =</span> training_set)</span>
<span id="cb63-430"><a href="#cb63-430" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb63-431"><a href="#cb63-431" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(regressor_lm)</span>
<span id="cb63-432"><a href="#cb63-432" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb63-433"><a href="#cb63-433" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb63-434"><a href="#cb63-434" aria-hidden="true" tabindex="-1"></a><span class="in">```{r message=FALSE, warning=FALSE, error=FALSE}</span></span>
<span id="cb63-435"><a href="#cb63-435" aria-hidden="true" tabindex="-1"></a>y_pred_lm <span class="ot">=</span> <span class="fu">predict</span>(regressor_lm, <span class="at">newdata =</span> test_set)</span>
<span id="cb63-436"><a href="#cb63-436" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb63-437"><a href="#cb63-437" aria-hidden="true" tabindex="-1"></a>Pred_Actual_lm <span class="ot">&lt;-</span> <span class="fu">as.data.frame</span>(<span class="fu">cbind</span>(<span class="at">Prediction =</span> y_pred_lm, <span class="at">Actual =</span> test_set<span class="sc">$</span>Happiness))</span>
<span id="cb63-438"><a href="#cb63-438" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb63-439"><a href="#cb63-439" aria-hidden="true" tabindex="-1"></a>gg.lm <span class="ot">&lt;-</span> <span class="fu">ggplot</span>(Pred_Actual_lm, <span class="fu">aes</span>(Actual, Prediction )) <span class="sc">+</span></span>
<span id="cb63-440"><a href="#cb63-440" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_point</span>() <span class="sc">+</span> <span class="fu">theme_bw</span>() <span class="sc">+</span> <span class="fu">geom_abline</span>() <span class="sc">+</span></span>
<span id="cb63-441"><a href="#cb63-441" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">title =</span> <span class="st">"Multiple Linear Regression"</span>, <span class="at">x =</span> <span class="st">"Actual happiness score"</span>,</span>
<span id="cb63-442"><a href="#cb63-442" aria-hidden="true" tabindex="-1"></a>       <span class="at">y =</span> <span class="st">"Predicted happiness score"</span>) <span class="sc">+</span></span>
<span id="cb63-443"><a href="#cb63-443" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme</span>(<span class="at">plot.title =</span> <span class="fu">element_text</span>(<span class="at">family =</span> <span class="st">"Helvetica"</span>, <span class="at">face =</span> <span class="st">"bold"</span>, <span class="at">size =</span> (<span class="dv">15</span>)), </span>
<span id="cb63-444"><a href="#cb63-444" aria-hidden="true" tabindex="-1"></a>        <span class="at">axis.title =</span> <span class="fu">element_text</span>(<span class="at">family =</span> <span class="st">"Helvetica"</span>, <span class="at">size =</span> (<span class="dv">10</span>)))</span>
<span id="cb63-445"><a href="#cb63-445" aria-hidden="true" tabindex="-1"></a>gg.lm</span>
<span id="cb63-446"><a href="#cb63-446" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb63-447"><a href="#cb63-447" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb63-448"><a href="#cb63-448" aria-hidden="true" tabindex="-1"></a>**The Model shows 67% accuracy on the test data.**</span>
<span id="cb63-449"><a href="#cb63-449" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb63-450"><a href="#cb63-450" aria-hidden="true" tabindex="-1"></a><span class="fu">## Regression Diagnostics</span></span>
<span id="cb63-451"><a href="#cb63-451" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb63-452"><a href="#cb63-452" aria-hidden="true" tabindex="-1"></a><span class="fu">### Model-1</span></span>
<span id="cb63-453"><a href="#cb63-453" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb63-456"><a href="#cb63-456" aria-hidden="true" tabindex="-1"></a><span class="in">```{r}</span></span>
<span id="cb63-457"><a href="#cb63-457" aria-hidden="true" tabindex="-1"></a><span class="co">#Model-1</span></span>
<span id="cb63-458"><a href="#cb63-458" aria-hidden="true" tabindex="-1"></a><span class="fu">par</span>(<span class="at">mfrow =</span> <span class="fu">c</span>(<span class="dv">2</span>,<span class="dv">3</span>)); <span class="fu">plot</span>(model1, <span class="at">which =</span> <span class="dv">1</span><span class="sc">:</span><span class="dv">6</span>)</span>
<span id="cb63-459"><a href="#cb63-459" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb63-460"><a href="#cb63-460" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb63-461"><a href="#cb63-461" aria-hidden="true" tabindex="-1"></a>**Model-1 Diagnostics:**</span>
<span id="cb63-462"><a href="#cb63-462" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb63-463"><a href="#cb63-463" aria-hidden="true" tabindex="-1"></a>Residuals vs Fitted: The Linearity assumption is met and there is a constant variance of residuals along the line. Overall the plot looks good.</span>
<span id="cb63-464"><a href="#cb63-464" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb63-465"><a href="#cb63-465" aria-hidden="true" tabindex="-1"></a>Normal Q-Q: The points are falling along the theoretical quantiles, hence the normality assumption is met.</span>
<span id="cb63-466"><a href="#cb63-466" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb63-467"><a href="#cb63-467" aria-hidden="true" tabindex="-1"></a>Scale-Location: The line is approximately horizontal, so I can say that the constant variance assumption is met.</span>
<span id="cb63-468"><a href="#cb63-468" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb63-469"><a href="#cb63-469" aria-hidden="true" tabindex="-1"></a>Cook's distance: No observation is greater than 1. The maximum cook's distance is <span class="sc">\&lt;</span>0.3. 174th observation is the influential.</span>
<span id="cb63-470"><a href="#cb63-470" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb63-471"><a href="#cb63-471" aria-hidden="true" tabindex="-1"></a>Residuals vs Leverage: No observations are beyond the cook's distance and the leverage is low.</span>
<span id="cb63-472"><a href="#cb63-472" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb63-473"><a href="#cb63-473" aria-hidden="true" tabindex="-1"></a>But the influential observation 174 is not at the same place in all graphs which is odd.</span>
<span id="cb63-474"><a href="#cb63-474" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb63-475"><a href="#cb63-475" aria-hidden="true" tabindex="-1"></a><span class="fu">### Model-2</span></span>
<span id="cb63-476"><a href="#cb63-476" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb63-479"><a href="#cb63-479" aria-hidden="true" tabindex="-1"></a><span class="in">```{r}</span></span>
<span id="cb63-480"><a href="#cb63-480" aria-hidden="true" tabindex="-1"></a><span class="co">#Model-2</span></span>
<span id="cb63-481"><a href="#cb63-481" aria-hidden="true" tabindex="-1"></a><span class="fu">par</span>(<span class="at">mfrow =</span> <span class="fu">c</span>(<span class="dv">2</span>,<span class="dv">3</span>)); <span class="fu">plot</span>(model2, <span class="at">which =</span> <span class="dv">1</span><span class="sc">:</span><span class="dv">6</span>)</span>
<span id="cb63-482"><a href="#cb63-482" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb63-483"><a href="#cb63-483" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb63-484"><a href="#cb63-484" aria-hidden="true" tabindex="-1"></a>**Model-2 Diagnostics:**</span>
<span id="cb63-485"><a href="#cb63-485" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb63-486"><a href="#cb63-486" aria-hidden="true" tabindex="-1"></a>Residuals vs Fitted: I would say the linearity assumption is violated here but the constant variance of residuals is present.</span>
<span id="cb63-487"><a href="#cb63-487" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb63-488"><a href="#cb63-488" aria-hidden="true" tabindex="-1"></a>Normal Q-Q: The points are falling along the theoretical quantiles, hence the normality assumption is met.</span>
<span id="cb63-489"><a href="#cb63-489" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb63-490"><a href="#cb63-490" aria-hidden="true" tabindex="-1"></a>Scale-Location: Compared to model-1, the line is almost horizontal. This one looks good.</span>
<span id="cb63-491"><a href="#cb63-491" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb63-492"><a href="#cb63-492" aria-hidden="true" tabindex="-1"></a>Cook's distance: No observation is greater than 1. The maximum cook's distance is 0.9 (approximately). The 156th observation is very influential.</span>
<span id="cb63-493"><a href="#cb63-493" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb63-494"><a href="#cb63-494" aria-hidden="true" tabindex="-1"></a>Residuals vs Leverage: No observations are beyond the cook's distance and the leverage is high as compared to model-1 which is good.</span>
<span id="cb63-495"><a href="#cb63-495" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb63-496"><a href="#cb63-496" aria-hidden="true" tabindex="-1"></a>**I can say that the regression diagnostics of Model-2 look much better than Model-1 because of the larger cook's distance and leverage.**</span>
<span id="cb63-497"><a href="#cb63-497" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb63-498"><a href="#cb63-498" aria-hidden="true" tabindex="-1"></a><span class="fu">### Model-3</span></span>
<span id="cb63-499"><a href="#cb63-499" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb63-502"><a href="#cb63-502" aria-hidden="true" tabindex="-1"></a><span class="in">```{r}</span></span>
<span id="cb63-503"><a href="#cb63-503" aria-hidden="true" tabindex="-1"></a><span class="co">#Model-3</span></span>
<span id="cb63-504"><a href="#cb63-504" aria-hidden="true" tabindex="-1"></a><span class="fu">par</span>(<span class="at">mfrow =</span> <span class="fu">c</span>(<span class="dv">2</span>,<span class="dv">3</span>)); <span class="fu">plot</span>(model3, <span class="at">which =</span> <span class="dv">1</span><span class="sc">:</span><span class="dv">6</span>)</span>
<span id="cb63-505"><a href="#cb63-505" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb63-506"><a href="#cb63-506" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb63-507"><a href="#cb63-507" aria-hidden="true" tabindex="-1"></a>Residuals vs Fitted: The Linearity assumption is met and there is a constant variance of residuals along the line. Overall the plot looks good.</span>
<span id="cb63-508"><a href="#cb63-508" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb63-509"><a href="#cb63-509" aria-hidden="true" tabindex="-1"></a>Normal Q-Q: The points are falling along the theoretical quantiles, hence the normality assumption is met.</span>
<span id="cb63-510"><a href="#cb63-510" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb63-511"><a href="#cb63-511" aria-hidden="true" tabindex="-1"></a>Scale-Location: Compared to model-1 &amp; 2, the line is not horizontal.</span>
<span id="cb63-512"><a href="#cb63-512" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb63-513"><a href="#cb63-513" aria-hidden="true" tabindex="-1"></a>Cook's distance: No observation is greater than 1. The maximum cook's distance is <span class="sc">\&lt;</span> 0.3 (approximately). Again as similar to model-1, the 174th observation is very influential.</span>
<span id="cb63-514"><a href="#cb63-514" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb63-515"><a href="#cb63-515" aria-hidden="true" tabindex="-1"></a>Residuals vs Leverage: No observations are beyond the cook's distance and the leverage is low.</span>
<span id="cb63-516"><a href="#cb63-516" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb63-517"><a href="#cb63-517" aria-hidden="true" tabindex="-1"></a>But the influential observation 174 is not at the same place in all graphs which is odd.</span>
<span id="cb63-518"><a href="#cb63-518" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb63-519"><a href="#cb63-519" aria-hidden="true" tabindex="-1"></a><span class="fu">## Conclusion</span></span>
<span id="cb63-520"><a href="#cb63-520" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb63-521"><a href="#cb63-521" aria-hidden="true" tabindex="-1"></a>The aim of this study is to find out which factors significantly effect world happiness scores and to find out a model that fits/predicts the happiness scores. The following is the summary of this study.</span>
<span id="cb63-522"><a href="#cb63-522" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb63-523"><a href="#cb63-523" aria-hidden="true" tabindex="-1"></a><span class="ss">-   </span>GDP per capita, Urbanization rate and Life expectancy are the factors that are significantly associated with Happiness scores.</span>
<span id="cb63-524"><a href="#cb63-524" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb63-525"><a href="#cb63-525" aria-hidden="true" tabindex="-1"></a><span class="ss">-   </span>North America, Europe and Australia appear to be the happiest.</span>
<span id="cb63-526"><a href="#cb63-526" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb63-527"><a href="#cb63-527" aria-hidden="true" tabindex="-1"></a><span class="ss">-   </span>South America, North Asia, Western Africa and countries/islands in the indian ocean appear to be happy on average.</span>
<span id="cb63-528"><a href="#cb63-528" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb63-529"><a href="#cb63-529" aria-hidden="true" tabindex="-1"></a><span class="ss">-   </span>South Africa, India are unhappy and of course Afghanistan is the unhappiest country in the world.</span>
<span id="cb63-530"><a href="#cb63-530" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb63-531"><a href="#cb63-531" aria-hidden="true" tabindex="-1"></a><span class="ss">-   </span>Australia has the highest median happiness score. Europe, South America, and North America are in the second place regarding median happiness score. Asia has the lowest median after Africa. We can see the range of happiness score for different continents, and also the concentration of happiness score.</span>
<span id="cb63-532"><a href="#cb63-532" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb63-533"><a href="#cb63-533" aria-hidden="true" tabindex="-1"></a><span class="ss">-   </span>The correlation between GDP per capita and happiness score in Europe, North America, and Asia is more significant than the other continents.</span>
<span id="cb63-534"><a href="#cb63-534" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb63-535"><a href="#cb63-535" aria-hidden="true" tabindex="-1"></a><span class="ss">-   </span>The relationship between happiness score and urbanization rate is very significant in Asia, Africa and Europe followed by North america and south america.</span>
<span id="cb63-536"><a href="#cb63-536" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb63-537"><a href="#cb63-537" aria-hidden="true" tabindex="-1"></a><span class="ss">-   </span>The relationship between happiness score and life expectancy is very significant in Asia, Europe and Africa followed by North america and south america.</span>
<span id="cb63-538"><a href="#cb63-538" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb63-539"><a href="#cb63-539" aria-hidden="true" tabindex="-1"></a>When it comes to modeling and hypothesis testing,</span>
<span id="cb63-540"><a href="#cb63-540" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb63-541"><a href="#cb63-541" aria-hidden="true" tabindex="-1"></a><span class="ss">-   </span>Model-1 concluded that GDP per capita and Life Expectancy are strongly associated with the happiness scores.</span>
<span id="cb63-542"><a href="#cb63-542" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb63-543"><a href="#cb63-543" aria-hidden="true" tabindex="-1"></a><span class="ss">-   </span>Model-2 concluded that Life Expectancy is more strongly associated with the happiness scores, giving evidence to the third hypothesis.</span>
<span id="cb63-544"><a href="#cb63-544" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb63-545"><a href="#cb63-545" aria-hidden="true" tabindex="-1"></a><span class="ss">-   </span>Regression diagnostics of model-2 showed larger cook distance and leverage.</span>
<span id="cb63-546"><a href="#cb63-546" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb63-547"><a href="#cb63-547" aria-hidden="true" tabindex="-1"></a><span class="fu">## References</span></span>
<span id="cb63-548"><a href="#cb63-548" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb63-549"><a href="#cb63-549" aria-hidden="true" tabindex="-1"></a><span class="ss">1.  </span><span class="ot">&lt;https://www.kaggle.com/code/noobiedatascientist/explaining-happiness/data&gt;</span></span>
<span id="cb63-550"><a href="#cb63-550" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb63-551"><a href="#cb63-551" aria-hidden="true" tabindex="-1"></a><span class="ss">2.  </span><span class="ot">&lt;https://worldhappiness.report/ed/2021/&gt;</span></span>
<span id="cb63-552"><a href="#cb63-552" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb63-553"><a href="#cb63-553" aria-hidden="true" tabindex="-1"></a><span class="ss">3.  </span><span class="ot">&lt;http://www.sthda.com/english/articles/40-regression-analysis/168-multiple-linear-regression-in-r/#building-model&gt;</span></span>
<span id="cb63-554"><a href="#cb63-554" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb63-555"><a href="#cb63-555" aria-hidden="true" tabindex="-1"></a><span class="ss">4.  </span><span class="co">[</span><span class="ot">https://www.guru99.com/r-simple-multiple-linear-regression.html</span><span class="co">](https://www.guru99.com/r-simple-multiple-linear-regression.htmlhttps://www.guru99.com/r-simple-multiple-linear-regression.html)</span></span>
</code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div></div></div></div></div>
</div> <!-- /content -->



</body></html>