---
title: "Final Project Part 1"
author: "Quinn He"
desription: "Research Project: 603"
date: "08/02/2022"
format:
  html:
    toc: true
    code-fold: true
    code-copy: true
    code-tools: true
categories:
  - finalpart1
---

```{r}
#| label: setup
#| warning: false

library(tidyverse)

knitr::opts_chunk$set(echo = TRUE)
```

## Research Question 

I want to measure correlation between rise in temperature or sea level due to climate change and whether that causes a rise in housing prices and purchases based on the states political leanings. I'm curious to see if coastal red states, states you would imagine do not believe in climate change, are continuing to have an increase in housing prices even though there is rising sea level and devastation to the coastal lines. In contrast, are blue states that would normally believe climate change also having an increase in housing prices? My main research will be discovering if the effects of climate change have an impact on housing prices at all.

Some research has shown that homeowners sell to flippers who want to fix the house then sell it to someone, which, unbeknownst to them, has been through multiple floods. This could account for results showing an increase in prices and purchases.


# Articles/Research Papers

https://time.com/5953380/climate-housing-crisis/

## Hypothesis

Does the saying "location, location, location" really matter when it comes to housing prices in Miami or are there other factors as well that contribute to price? My hypothesis is a home close to the ocean specifically but also in proximity to the business center of Miami are the most expensive houses. 

## Descriptive Statistics