<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.2.269">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">

<meta name="author" content="Karen Kimble">
<meta name="dcterms.date" content="2022-11-14">

<title>DACSS 603 Final Project Pt 2</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1.6em;
  vertical-align: middle;
}
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
    color: #aaaaaa;
  }
pre.numberSource { margin-left: 3em; border-left: 1px solid #aaaaaa;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
code span.al { color: #ff0000; font-weight: bold; } /* Alert */
code span.an { color: #60a0b0; font-weight: bold; font-style: italic; } /* Annotation */
code span.at { color: #7d9029; } /* Attribute */
code span.bn { color: #40a070; } /* BaseN */
code span.bu { color: #008000; } /* BuiltIn */
code span.cf { color: #007020; font-weight: bold; } /* ControlFlow */
code span.ch { color: #4070a0; } /* Char */
code span.cn { color: #880000; } /* Constant */
code span.co { color: #60a0b0; font-style: italic; } /* Comment */
code span.cv { color: #60a0b0; font-weight: bold; font-style: italic; } /* CommentVar */
code span.do { color: #ba2121; font-style: italic; } /* Documentation */
code span.dt { color: #902000; } /* DataType */
code span.dv { color: #40a070; } /* DecVal */
code span.er { color: #ff0000; font-weight: bold; } /* Error */
code span.ex { } /* Extension */
code span.fl { color: #40a070; } /* Float */
code span.fu { color: #06287e; } /* Function */
code span.im { color: #008000; font-weight: bold; } /* Import */
code span.in { color: #60a0b0; font-weight: bold; font-style: italic; } /* Information */
code span.kw { color: #007020; font-weight: bold; } /* Keyword */
code span.op { color: #666666; } /* Operator */
code span.ot { color: #007020; } /* Other */
code span.pp { color: #bc7a00; } /* Preprocessor */
code span.sc { color: #4070a0; } /* SpecialChar */
code span.ss { color: #bb6688; } /* SpecialString */
code span.st { color: #4070a0; } /* String */
code span.va { color: #19177c; } /* Variable */
code span.vs { color: #4070a0; } /* VerbatimString */
code span.wa { color: #60a0b0; font-weight: bold; font-style: italic; } /* Warning */
</style>


<script src="../site_libs/quarto-nav/quarto-nav.js"></script>
<script src="../site_libs/quarto-nav/headroom.min.js"></script>
<script src="../site_libs/clipboard/clipboard.min.js"></script>
<script src="../site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="../site_libs/quarto-search/fuse.min.js"></script>
<script src="../site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="../">
<link href="../images/DACSS_Round_Network.png" rel="icon" type="image/png">
<script src="../site_libs/quarto-html/quarto.js"></script>
<script src="../site_libs/quarto-html/popper.min.js"></script>
<script src="../site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="../site_libs/quarto-html/anchor.min.js"></script>
<link href="../site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="../site_libs/quarto-html/quarto-syntax-highlighting.css" rel="stylesheet" class="quarto-color-scheme" id="quarto-text-highlighting-styles">
<link href="../site_libs/quarto-html/quarto-syntax-highlighting-dark.css" rel="prefetch" class="quarto-color-scheme quarto-color-alternate" id="quarto-text-highlighting-styles">
<script src="../site_libs/bootstrap/bootstrap.min.js"></script>
<link href="../site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="../site_libs/bootstrap/bootstrap.min.css" rel="stylesheet" class="quarto-color-scheme" id="quarto-bootstrap" data-mode="light">
<link href="../site_libs/bootstrap/bootstrap-dark.min.css" rel="prefetch" class="quarto-color-scheme quarto-color-alternate" id="quarto-bootstrap" data-mode="dark">
<script id="quarto-search-options" type="application/json">{
  "location": "navbar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "end",
  "type": "overlay",
  "limit": 20,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit"
  }
}</script>


<meta name="twitter:title" content="DACSS 603 Final Project Pt 2">
<meta name="twitter:description" content="The research question I want to explore is whether child poverty has increased in schools that are predominantly made up of non-white students from the 2014-2015 school year to the 2020-2021 school…">
<meta name="twitter:creator" content="@UMassDACSS">
<meta name="twitter:site" content="@UMassDACSS">
<meta name="twitter:card" content="summary">
</head>

<body class="nav-fixed">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
    <nav class="navbar navbar-expand-lg navbar-dark ">
      <div class="navbar-container container-fluid">
      <div class="navbar-brand-container">
    <a href="../index.html" class="navbar-brand navbar-brand-logo">
    <img src="../images/UMass White Wordmark Horiz.png" alt="" class="navbar-logo">
    </a>
  </div>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse" aria-controls="navbarCollapse" aria-expanded="false" aria-label="Toggle navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
  <span class="navbar-toggler-icon"></span>
</button>
          <div class="collapse navbar-collapse" id="navbarCollapse">
            <ul class="navbar-nav navbar-nav-scroll ms-auto">
  <li class="nav-item">
    <a class="nav-link" href="https://dacss.github.io/603_Fall_2022/">
 <span class="menu-text">Fall 2022 Posts</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="../about.html">
 <span class="menu-text">Contributors</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="https://umass.edu/sbs/dacss">
 <span class="menu-text">DACSS</span></a>
  </li>  
  <li class="nav-item compact">
    <a class="nav-link" href="https://github.com/DACSS/603_Fall_2022"><i class="bi bi-github" role="img" aria-label="GitHub">
</i> 
 <span class="menu-text"></span></a>
  </li>  
</ul>
              <div class="quarto-toggle-container">
                  <a href="" class="quarto-color-scheme-toggle nav-link" onclick="window.quartoToggleColorScheme(); return false;" title="Toggle dark mode"><i class="bi"></i></a>
              </div>
              <div id="quarto-search" class="" title="Search"></div>
          </div> <!-- /navcollapse -->
      </div> <!-- /container-fluid -->
    </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article page-navbar">
<!-- sidebar -->
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">On this page</h2>
   
  <ul>
  <li><a href="#setup" id="toc-setup" class="nav-link active" data-scroll-target="#setup">Setup</a></li>
  <li><a href="#research-question" id="toc-research-question" class="nav-link" data-scroll-target="#research-question">Research Question</a></li>
  <li><a href="#hypothesis" id="toc-hypothesis" class="nav-link" data-scroll-target="#hypothesis">Hypothesis</a></li>
  <li><a href="#descriptive-statistics" id="toc-descriptive-statistics" class="nav-link" data-scroll-target="#descriptive-statistics">Descriptive Statistics</a></li>
  <li><a href="#visualizations" id="toc-visualizations" class="nav-link" data-scroll-target="#visualizations">Visualizations</a></li>
  <li><a href="#hypothesis-testing" id="toc-hypothesis-testing" class="nav-link" data-scroll-target="#hypothesis-testing">Hypothesis Testing</a></li>
  <li><a href="#model-comparisons" id="toc-model-comparisons" class="nav-link" data-scroll-target="#model-comparisons">Model Comparisons</a></li>
  <li><a href="#diagnostics" id="toc-diagnostics" class="nav-link" data-scroll-target="#diagnostics">Diagnostics</a></li>
  <li><a href="#references" id="toc-references" class="nav-link" data-scroll-target="#references">References</a></li>
  </ul>
</nav>
    </div>
<!-- main -->
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<div class="quarto-title-block"><div><h1 class="title">DACSS 603 Final Project Pt 2</h1><button type="button" class="btn code-tools-button dropdown-toggle" id="quarto-code-tools-menu" data-bs-toggle="dropdown" aria-expanded="false"><i class="bi"></i> Code</button><ul class="dropdown-menu dropdown-menu-end" aria-labelelledby="quarto-code-tools-menu"><li><a id="quarto-show-all-code" class="dropdown-item" href="javascript:void(0)" role="button">Show All Code</a></li><li><a id="quarto-hide-all-code" class="dropdown-item" href="javascript:void(0)" role="button">Hide All Code</a></li><li><hr class="dropdown-divider"></li><li><a id="quarto-view-source" class="dropdown-item" href="javascript:void(0)" role="button">View Source</a></li></ul></div></div>
</div>



<div class="quarto-title-meta">

    <div>
    <div class="quarto-title-meta-heading">Author</div>
    <div class="quarto-title-meta-contents">
             <p>Karen Kimble </p>
          </div>
  </div>
    
    <div>
    <div class="quarto-title-meta-heading">Published</div>
    <div class="quarto-title-meta-contents">
      <p class="date">November 14, 2022</p>
    </div>
  </div>
  
    
  </div>
  

</header>

<section id="setup" class="level2">
<h2 class="anchored" data-anchor-id="setup">Setup</h2>
<div class="cell">
<details>
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb1"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(tidyverse)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stderr">
<pre><code>── Attaching packages ─────────────────────────────────────── tidyverse 1.3.2 ──
✔ ggplot2 3.4.0      ✔ purrr   0.3.5 
✔ tibble  3.1.8      ✔ dplyr   1.0.10
✔ tidyr   1.2.1      ✔ stringr 1.4.1 
✔ readr   2.1.3      ✔ forcats 0.5.2 
── Conflicts ────────────────────────────────────────── tidyverse_conflicts() ──
✖ dplyr::filter() masks stats::filter()
✖ dplyr::lag()    masks stats::lag()</code></pre>
</div>
<details>
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb3"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb3-1"><a href="#cb3-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(readr)</span>
<span id="cb3-2"><a href="#cb3-2" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(scales)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stderr">
<pre><code>
Attaching package: 'scales'

The following object is masked from 'package:purrr':

    discard

The following object is masked from 'package:readr':

    col_factor</code></pre>
</div>
<details>
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb5"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb5-1"><a href="#cb5-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(ggplot2)</span>
<span id="cb5-2"><a href="#cb5-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb5-3"><a href="#cb5-3" aria-hidden="true" tabindex="-1"></a><span class="co"># Importing datasets</span></span>
<span id="cb5-4"><a href="#cb5-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb5-5"><a href="#cb5-5" aria-hidden="true" tabindex="-1"></a>NYC_2019 <span class="ot">&lt;-</span> <span class="fu">read_csv</span>(<span class="st">"_data/2018-2019_School_Demographic_Snapshot.csv"</span>, <span class="at">col_types =</span> <span class="fu">cols</span>(<span class="st">`</span><span class="at">Grade PK (Half Day &amp; Full Day)</span><span class="st">`</span> <span class="ot">=</span> <span class="fu">col_skip</span>(), <span class="st">`</span><span class="at"># Multiple Race Categories Not Represented</span><span class="st">`</span> <span class="ot">=</span> <span class="fu">col_skip</span>(), <span class="st">`</span><span class="at">% Multiple Race Categories Not Represented</span><span class="st">`</span> <span class="ot">=</span> <span class="fu">col_skip</span>()))</span>
<span id="cb5-6"><a href="#cb5-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb5-7"><a href="#cb5-7" aria-hidden="true" tabindex="-1"></a>NYC_2019<span class="sc">$</span><span class="st">`</span><span class="at">% Poverty</span><span class="st">`</span> <span class="ot">&lt;-</span> <span class="fu">percent</span>(NYC_2019<span class="sc">$</span><span class="st">`</span><span class="at">% Poverty</span><span class="st">`</span>, <span class="at">accuracy=</span><span class="fl">0.1</span>)</span>
<span id="cb5-8"><a href="#cb5-8" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb5-9"><a href="#cb5-9" aria-hidden="true" tabindex="-1"></a>NYC_2021 <span class="ot">&lt;-</span> <span class="fu">read_csv</span>(<span class="st">"_data/2020-2021_Demographic_Snapshot_School.csv"</span>, <span class="at">col_types =</span> <span class="fu">cols</span>(<span class="st">`</span><span class="at">Grade 3K+PK (Half Day &amp; Full Day)</span><span class="st">`</span> <span class="ot">=</span> <span class="fu">col_skip</span>(), <span class="st">`</span><span class="at"># Multi-Racial</span><span class="st">`</span> <span class="ot">=</span> <span class="fu">col_skip</span>(), <span class="st">`</span><span class="at">% Multi-Racial</span><span class="st">`</span> <span class="ot">=</span> <span class="fu">col_skip</span>(), <span class="st">`</span><span class="at"># Native American</span><span class="st">`</span> <span class="ot">=</span> <span class="fu">col_skip</span>(), <span class="st">`</span><span class="at">% Native American</span><span class="st">`</span> <span class="ot">=</span> <span class="fu">col_skip</span>(), <span class="st">`</span><span class="at"># Missing Race/Ethnicity Data</span><span class="st">`</span> <span class="ot">=</span> <span class="fu">col_skip</span>(), <span class="st">`</span><span class="at">% Missing Race/Ethnicity Data</span><span class="st">`</span> <span class="ot">=</span> <span class="fu">col_skip</span>()))</span>
<span id="cb5-10"><a href="#cb5-10" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb5-11"><a href="#cb5-11" aria-hidden="true" tabindex="-1"></a><span class="co"># In order to bind the data, I had to remove columns that were not present in the other spreadsheet: Grade PK or 3K, Native American, the different multi-racial categories, and Missing Data</span></span>
<span id="cb5-12"><a href="#cb5-12" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb5-13"><a href="#cb5-13" aria-hidden="true" tabindex="-1"></a>school_data <span class="ot">&lt;-</span> <span class="fu">rbind</span>(NYC_2019, NYC_2021)</span>
<span id="cb5-14"><a href="#cb5-14" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb5-15"><a href="#cb5-15" aria-hidden="true" tabindex="-1"></a><span class="co"># Renaming some columns</span></span>
<span id="cb5-16"><a href="#cb5-16" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb5-17"><a href="#cb5-17" aria-hidden="true" tabindex="-1"></a>school_data<span class="sc">$</span>pct_white <span class="ot">&lt;-</span> school_data<span class="sc">$</span><span class="st">'% White'</span></span>
<span id="cb5-18"><a href="#cb5-18" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb5-19"><a href="#cb5-19" aria-hidden="true" tabindex="-1"></a><span class="co"># Making values coded as "above 95%" to equal 95% and "below 5%" to equal 5% for the purposes of this analysis</span></span>
<span id="cb5-20"><a href="#cb5-20" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb5-21"><a href="#cb5-21" aria-hidden="true" tabindex="-1"></a>school_data<span class="sc">$</span><span class="st">`</span><span class="at">% Poverty</span><span class="st">`</span> <span class="ot">&lt;-</span> <span class="fu">recode</span>(school_data<span class="sc">$</span><span class="st">`</span><span class="at">% Poverty</span><span class="st">`</span>, <span class="st">"Above 95%"</span> <span class="ot">=</span> <span class="st">"95%"</span>, <span class="st">"Below 5%"</span> <span class="ot">=</span> <span class="st">"5%"</span>)</span>
<span id="cb5-22"><a href="#cb5-22" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb5-23"><a href="#cb5-23" aria-hidden="true" tabindex="-1"></a><span class="co"># Re-coding variables as numeric</span></span>
<span id="cb5-24"><a href="#cb5-24" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb5-25"><a href="#cb5-25" aria-hidden="true" tabindex="-1"></a>school_data<span class="sc">$</span><span class="st">`</span><span class="at">% Poverty</span><span class="st">`</span> <span class="ot">&lt;-</span> <span class="fu">sapply</span>(school_data<span class="sc">$</span><span class="st">`</span><span class="at">% Poverty</span><span class="st">`</span>, <span class="cf">function</span>(x) <span class="fu">gsub</span>(<span class="st">"%"</span>, <span class="st">""</span>, x))</span>
<span id="cb5-26"><a href="#cb5-26" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb5-27"><a href="#cb5-27" aria-hidden="true" tabindex="-1"></a>school_data<span class="sc">$</span><span class="st">`</span><span class="at">% Poverty</span><span class="st">`</span> <span class="ot">&lt;-</span> <span class="fu">as.numeric</span>(school_data<span class="sc">$</span><span class="st">`</span><span class="at">% Poverty</span><span class="st">`</span>)</span>
<span id="cb5-28"><a href="#cb5-28" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb5-29"><a href="#cb5-29" aria-hidden="true" tabindex="-1"></a>school_data<span class="sc">$</span><span class="st">`</span><span class="at">Economic Need Index</span><span class="st">`</span> <span class="ot">&lt;-</span> <span class="fu">as.numeric</span>(school_data<span class="sc">$</span><span class="st">`</span><span class="at">Economic Need Index</span><span class="st">`</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stderr">
<pre><code>Warning: NAs introduced by coercion</code></pre>
</div>
<details>
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb7"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb7-1"><a href="#cb7-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Creating a new variable of post-Covid (1) and pre-Covid (0)</span></span>
<span id="cb7-2"><a href="#cb7-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb7-3"><a href="#cb7-3" aria-hidden="true" tabindex="-1"></a>school_data<span class="sc">$</span>Post_Covid <span class="ot">&lt;-</span> <span class="fu">ifelse</span>(school_data<span class="sc">$</span>Year <span class="sc">==</span> <span class="st">"2020-21"</span>, <span class="fu">c</span>(<span class="st">"1"</span>), <span class="fu">c</span>(<span class="st">"0"</span>))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
</div>
</section>
<section id="research-question" class="level2">
<h2 class="anchored" data-anchor-id="research-question">Research Question</h2>
<p>The research question I want to explore is whether child poverty has increased in schools that are predominantly made up of non-white students from the 2014-2015 school year to the 2020-2021 school year. I think this is extremely important to look at because of the pandemic’s impact on not only child learning but also families’ economic resources. According to the Columbia University Center on Poverty and Social Policy, “nearly a quarter of children ages 0-3 live in poverty and nearly half of the city’s young children live in lower-opportunity neighborhoods where the poverty rate is at least 20 percent” (“Poverty”). Unfortunately, research shows that poverty is disproportionately felt according to one’s race or ethnicity. In New York State, as of 2021, child poverty among children of color is almost 30%, with Black or African American children more than twice as likely to live in poverty than White, Non-Hispanic children (“New York State”, 2021). With this disproportionate level of economic need in children of color, it seems important to investigate if the poverty level within New York City schools that are predominately non-White has increased significantly compared to schools that are predominantly White. When searching the UMass Libraries databases and other sources, it was hard to find studies that used this data in this way. It is important to understand if there is increasing poverty levels within an already vulnerable group.</p>
</section>
<section id="hypothesis" class="level2">
<h2 class="anchored" data-anchor-id="hypothesis">Hypothesis</h2>
<p>I hypothesize that the poverty rate in NYC schools that are predominantly children of color will have increased more between pre- and post-Covid than the poverty rate in schools that are predominantly White. Since I have not found many previous studies on this, it is hard to know if this hypothesis was tested before. However, this data is fairly recent and also relates to the pandemic’s effects on economics, so I think it is still a significant contribution to test this hypothesis.</p>
</section>
<section id="descriptive-statistics" class="level2">
<h2 class="anchored" data-anchor-id="descriptive-statistics">Descriptive Statistics</h2>
<p>A description and summary of your data. How was your data collected by its original collectors? What are the important variables of interest for your research question? Use functions like glimpse() and summary() to present your data.</p>
<p>The data was collected by New York City and put on its Open Data source. The data covers NYC schools in the academic years 2014-2015 to 2020-2021. The important variables of interest included in the data are:</p>
<ul>
<li><p>Academic year, which I transformed into pre-Covid and post-Covid variables</p></li>
<li><p>Number and percentage of Asisan, Black, Hispanic, and White students</p></li>
<li><p>Number and percentage of students in poverty</p></li>
<li><p>Economic need index, which is the average of students’ “Economic Need Values”</p>
<ul>
<li>The Economic Need Index (ENI) estimates the percentage of students facing economic hardship</li>
</ul></li>
</ul>
<p>The other variables included are: DBN (district, borough, school number), school name, total enrollment, enrollment numbers for K-12, number and percentage of female and male students, number and percentage of students with disabilities, and number and percentage of English-Language Learner (ELL) students.</p>
<div class="cell">
<details>
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb8"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb8-1"><a href="#cb8-1" aria-hidden="true" tabindex="-1"></a><span class="fu">glimpse</span>(school_data)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>Rows: 18,142
Columns: 38
$ DBN                            &lt;chr&gt; "01M015", "01M015", "01M015", "01M015",…
$ `School Name`                  &lt;chr&gt; "P.S. 015 Roberto Clemente", "P.S. 015 …
$ Year                           &lt;chr&gt; "2014-15", "2015-16", "2016-17", "2017-…
$ `Total Enrollment`             &lt;dbl&gt; 183, 176, 178, 190, 174, 270, 270, 271,…
$ `Grade K`                      &lt;dbl&gt; 27, 32, 28, 28, 20, 44, 47, 37, 34, 30,…
$ `Grade 1`                      &lt;dbl&gt; 47, 33, 33, 32, 33, 40, 43, 46, 38, 39,…
$ `Grade 2`                      &lt;dbl&gt; 31, 39, 27, 33, 30, 39, 41, 47, 42, 43,…
$ `Grade 3`                      &lt;dbl&gt; 19, 23, 31, 23, 30, 35, 43, 40, 46, 41,…
$ `Grade 4`                      &lt;dbl&gt; 17, 17, 24, 31, 20, 40, 35, 43, 42, 44,…
$ `Grade 5`                      &lt;dbl&gt; 24, 18, 18, 26, 28, 42, 40, 34, 42, 42,…
$ `Grade 6`                      &lt;dbl&gt; 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, …
$ `Grade 7`                      &lt;dbl&gt; 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, …
$ `Grade 8`                      &lt;dbl&gt; 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, …
$ `Grade 9`                      &lt;dbl&gt; 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, …
$ `Grade 10`                     &lt;dbl&gt; 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, …
$ `Grade 11`                     &lt;dbl&gt; 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, …
$ `Grade 12`                     &lt;dbl&gt; 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, …
$ `# Female`                     &lt;dbl&gt; 84, 83, 83, 99, 85, 132, 125, 127, 114,…
$ `% Female`                     &lt;dbl&gt; 0.459, 0.472, 0.466, 0.521, 0.489, 0.48…
$ `# Male`                       &lt;dbl&gt; 99, 93, 95, 91, 89, 138, 145, 144, 143,…
$ `% Male`                       &lt;dbl&gt; 0.541, 0.528, 0.534, 0.479, 0.511, 0.51…
$ `# Asian`                      &lt;dbl&gt; 8, 9, 14, 20, 24, 30, 27, 24, 23, 14, 2…
$ `% Asian`                      &lt;dbl&gt; 0.044, 0.051, 0.079, 0.105, 0.138, 0.11…
$ `# Black`                      &lt;dbl&gt; 65, 57, 51, 52, 48, 47, 55, 51, 49, 52,…
$ `% Black`                      &lt;dbl&gt; 0.355, 0.324, 0.287, 0.274, 0.276, 0.17…
$ `# Hispanic`                   &lt;dbl&gt; 107, 105, 105, 110, 95, 158, 169, 180, …
$ `% Hispanic`                   &lt;dbl&gt; 0.585, 0.597, 0.590, 0.579, 0.546, 0.58…
$ `# White`                      &lt;dbl&gt; 2, 2, 4, 6, 6, 27, 16, 15, 16, 18, 25, …
$ `% White`                      &lt;dbl&gt; 0.011, 0.011, 0.022, 0.032, 0.034, 0.10…
$ `# Students with Disabilities` &lt;dbl&gt; 64, 60, 51, 49, 38, 82, 82, 88, 90, 92,…
$ `% Students with Disabilities` &lt;dbl&gt; 0.350, 0.341, 0.287, 0.258, 0.218, 0.30…
$ `# English Language Learners`  &lt;dbl&gt; 17, 16, 12, 8, 8, 18, 13, 9, 8, 8, 120,…
$ `% English Language Learners`  &lt;dbl&gt; 0.093, 0.091, 0.067, 0.042, 0.046, 0.06…
$ `# Poverty`                    &lt;chr&gt; "169", "149", "152", "161", "145", "200…
$ `% Poverty`                    &lt;dbl&gt; 92.3, 84.7, 85.4, 84.7, 83.3, 74.1, 80.…
$ `Economic Need Index`          &lt;dbl&gt; 0.930, 0.889, 0.882, 0.890, 0.880, 0.60…
$ pct_white                      &lt;dbl&gt; 0.011, 0.011, 0.022, 0.032, 0.034, 0.10…
$ Post_Covid                     &lt;chr&gt; "0", "0", "0", "0", "0", "0", "0", "0",…</code></pre>
</div>
</div>
<div class="cell">
<details>
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb10"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb10-1"><a href="#cb10-1" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(school_data)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>     DBN            School Name            Year           Total Enrollment
 Length:18142       Length:18142       Length:18142       Min.   :   7.0  
 Class :character   Class :character   Class :character   1st Qu.: 323.0  
 Mode  :character   Mode  :character   Mode  :character   Median : 477.0  
                                                          Mean   : 592.3  
                                                          3rd Qu.: 695.0  
                                                          Max.   :6040.0  
                                                                          
    Grade K          Grade 1          Grade 2          Grade 3      
 Min.   :  0.00   Min.   :  0.00   Min.   :  0.00   Min.   :  0.00  
 1st Qu.:  0.00   1st Qu.:  0.00   1st Qu.:  0.00   1st Qu.:  0.00  
 Median : 32.00   Median : 33.00   Median : 32.00   Median : 28.00  
 Mean   : 44.25   Mean   : 45.79   Mean   : 45.73   Mean   : 45.33  
 3rd Qu.: 78.00   3rd Qu.: 81.00   3rd Qu.: 82.00   3rd Qu.: 81.00  
 Max.   :393.00   Max.   :383.00   Max.   :349.00   Max.   :369.00  
                                                                    
    Grade 4         Grade 5          Grade 6          Grade 7      
 Min.   :  0.0   Min.   :  0.00   Min.   :  0.00   Min.   :  0.00  
 1st Qu.:  0.0   1st Qu.:  0.00   1st Qu.:  0.00   1st Qu.:  0.00  
 Median : 22.0   Median : 19.00   Median :  0.00   Median :  0.00  
 Mean   : 44.8   Mean   : 44.18   Mean   : 43.15   Mean   : 42.37  
 3rd Qu.: 80.0   3rd Qu.: 80.00   3rd Qu.: 64.00   3rd Qu.: 62.00  
 Max.   :376.0   Max.   :351.00   Max.   :771.00   Max.   :796.00  
                                                                   
    Grade 8          Grade 9           Grade 10         Grade 11      
 Min.   :  0.00   Min.   :   0.00   Min.   :   0.0   Min.   :   0.00  
 1st Qu.:  0.00   1st Qu.:   0.00   1st Qu.:   0.0   1st Qu.:   0.00  
 Median :  0.00   Median :   0.00   Median :   0.0   Median :   0.00  
 Mean   : 41.88   Mean   :  49.34   Mean   :  48.7   Mean   :  39.85  
 3rd Qu.: 60.00   3rd Qu.:  68.00   3rd Qu.:  69.0   3rd Qu.:  54.00  
 Max.   :784.00   Max.   :1555.00   Max.   :3832.0   Max.   :1529.00  
                                                                      
    Grade 12          # Female         % Female          # Male      
 Min.   :   0.00   Min.   :   0.0   Min.   :0.0000   Min.   :   0.0  
 1st Qu.:   0.00   1st Qu.: 146.0   1st Qu.:0.4620   1st Qu.: 163.0  
 Median :   0.00   Median : 232.0   Median :0.4880   Median : 248.0  
 Mean   :  39.58   Mean   : 287.4   Mean   :0.4827   Mean   : 304.9  
 3rd Qu.:  53.00   3rd Qu.: 347.0   3rd Qu.:0.5130   3rd Qu.: 364.0  
 Max.   :1566.00   Max.   :2405.0   Max.   :1.0000   Max.   :3635.0  
                                                                     
     % Male          # Asian           % Asian          # Black      
 Min.   :0.0000   Min.   :   0.00   Min.   :0.0000   Min.   :   0.0  
 1st Qu.:0.4870   1st Qu.:   5.00   1st Qu.:0.0130   1st Qu.:  42.0  
 Median :0.5120   Median :  17.00   Median :0.0400   Median : 105.0  
 Mean   :0.5173   Mean   :  95.38   Mean   :0.1136   Mean   : 154.1  
 3rd Qu.:0.5380   3rd Qu.:  79.00   3rd Qu.:0.1400   3rd Qu.: 198.0  
 Max.   :1.0000   Max.   :3671.00   Max.   :0.9470   Max.   :1493.0  
                                                                     
    % Black        # Hispanic     % Hispanic        # White       
 Min.   :0.000   Min.   :   1   Min.   :0.0060   Min.   :   0.00  
 1st Qu.:0.083   1st Qu.:  89   1st Qu.:0.1980   1st Qu.:   6.00  
 Median :0.251   Median : 180   Median :0.3990   Median :  15.00  
 Mean   :0.316   Mean   : 241   Mean   :0.4251   Mean   :  87.24  
 3rd Qu.:0.502   3rd Qu.: 313   3rd Qu.:0.6323   3rd Qu.:  78.00  
 Max.   :0.987   Max.   :2056   Max.   :1.0000   Max.   :3190.00  
                                                                  
    % White       # Students with Disabilities % Students with Disabilities
 Min.   :0.0000   Min.   :  0.0                Min.   :0.0000              
 1st Qu.:0.0140   1st Qu.: 66.0                1st Qu.:0.1570              
 Median :0.0330   Median : 98.0                Median :0.2030              
 Mean   :0.1205   Mean   :121.6                Mean   :0.2295              
 3rd Qu.:0.1440   3rd Qu.:146.0                3rd Qu.:0.2540              
 Max.   :0.9450   Max.   :925.0                Max.   :1.0000              
                                                                           
 # English Language Learners % English Language Learners  # Poverty        
 Min.   :   0.0              Min.   :0.0000              Length:18142      
 1st Qu.:  18.0              1st Qu.:0.0430              Class :character  
 Median :  43.0              Median :0.0950              Mode  :character  
 Mean   :  81.1              Mean   :0.1363                                
 3rd Qu.: 100.0              3rd Qu.:0.1800                                
 Max.   :1219.0              Max.   :1.0000                                
                                                                           
   % Poverty      Economic Need Index   pct_white       Post_Covid       
 Min.   :  2.90   Min.   :0.030       Min.   :0.0000   Length:18142      
 1st Qu.: 69.30   1st Qu.:0.579       1st Qu.:0.0140   Class :character  
 Median : 81.40   Median :0.743       Median :0.0330   Mode  :character  
 Mean   : 75.89   Mean   :0.691       Mean   :0.1205                     
 3rd Qu.: 89.90   3rd Qu.:0.846       3rd Qu.:0.1440                     
 Max.   :100.00   Max.   :0.998       Max.   :0.9450                     
                  NA's   :9169                                           </code></pre>
</div>
<details>
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb12"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb12-1"><a href="#cb12-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Note: the summary data for the enrollment numbers split by grade is somewhat off (especially minimums) because there is no variable listed for type of school (i.e., middle versus high school). So, for example, an elementary school would have an enrollment total of 0 for grade 12, which would show up as the minimum.</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
</div>
<p>As we can see from this summary, the median percent of poverty in NYC schools (81.4%) is higher than the mean percent (75.89%), indicating that there may be low outliers with very low percentages of poverty. The same holds true for the Economic Need Index, with the mean (0.691) lower than the median (0.743). It is troubling, however, that both the mean and median percentages of poverty in NYC schools overall is more than three-fourths of the population.</p>
</section>
<section id="visualizations" class="level2">
<h2 class="anchored" data-anchor-id="visualizations">Visualizations</h2>
<div class="cell">
<details>
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb13"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb13-1"><a href="#cb13-1" aria-hidden="true" tabindex="-1"></a>post_white <span class="ot">&lt;-</span> <span class="fu">filter</span>(school_data, pct_white <span class="sc">&gt;</span> <span class="fl">0.5</span> <span class="sc">&amp;</span> Post_Covid <span class="sc">==</span> <span class="st">"1"</span>)</span>
<span id="cb13-2"><a href="#cb13-2" aria-hidden="true" tabindex="-1"></a>post_nonwhite <span class="ot">&lt;-</span> <span class="fu">filter</span>(school_data, pct_white <span class="sc">&lt;=</span> <span class="fl">0.5</span> <span class="sc">&amp;</span> Post_Covid <span class="sc">==</span> <span class="st">"1"</span>)</span>
<span id="cb13-3"><a href="#cb13-3" aria-hidden="true" tabindex="-1"></a>pre_white <span class="ot">&lt;-</span> <span class="fu">filter</span>(school_data, pct_white <span class="sc">&gt;</span> <span class="fl">0.5</span> <span class="sc">&amp;</span> Post_Covid <span class="sc">==</span> <span class="st">"0"</span>)</span>
<span id="cb13-4"><a href="#cb13-4" aria-hidden="true" tabindex="-1"></a>pre_nonwhite <span class="ot">&lt;-</span> <span class="fu">filter</span>(school_data, pct_white <span class="sc">&lt;=</span> <span class="fl">0.5</span> <span class="sc">&amp;</span> Post_Covid <span class="sc">==</span> <span class="st">"0"</span>)</span>
<span id="cb13-5"><a href="#cb13-5" aria-hidden="true" tabindex="-1"></a>post <span class="ot">&lt;-</span> <span class="fu">filter</span>(school_data, Post_Covid <span class="sc">==</span> <span class="st">"1"</span>)</span>
<span id="cb13-6"><a href="#cb13-6" aria-hidden="true" tabindex="-1"></a>pre <span class="ot">&lt;-</span> <span class="fu">filter</span>(school_data, Post_Covid <span class="sc">==</span> <span class="st">"0"</span>)</span>
<span id="cb13-7"><a href="#cb13-7" aria-hidden="true" tabindex="-1"></a>white <span class="ot">&lt;-</span> <span class="fu">filter</span>(school_data, pct_white <span class="sc">&gt;</span> <span class="fl">0.5</span>)</span>
<span id="cb13-8"><a href="#cb13-8" aria-hidden="true" tabindex="-1"></a>nonwhite <span class="ot">&lt;-</span> <span class="fu">filter</span>(school_data, pct_white <span class="sc">&lt;=</span> <span class="fl">0.5</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
</div>
<div class="cell">
<details>
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb14"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb14-1"><a href="#cb14-1" aria-hidden="true" tabindex="-1"></a><span class="fu">boxplot</span>(school_data<span class="sc">$</span><span class="st">`</span><span class="at">% Poverty</span><span class="st">`</span> <span class="sc">~</span> school_data<span class="sc">$</span>Post_Covid,</span>
<span id="cb14-2"><a href="#cb14-2" aria-hidden="true" tabindex="-1"></a>        <span class="at">xlab =</span> <span class="st">"Pre-Covid (0) or Post-Covid (1)"</span>,</span>
<span id="cb14-3"><a href="#cb14-3" aria-hidden="true" tabindex="-1"></a>        <span class="at">ylab =</span> <span class="st">"Percent of Students in Poverty"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output-display">
<p><img src="FinalPt2_KarenKimble_files/figure-html/unnamed-chunk-5-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<p>From the box plot above, we can see that poverty levels between pre- and post-Covid did not change very dramatically for overall students. However, the maximum percentage of poverty did decrease from close to 100% to about 95%. Yet the median percentage level of poverty increased from pre- to post-Covid, though still remained under 90%. There are a large number of outliers below the minimum level of poverty, which is interesting–yet the minimum level of poverty increased between pre- and post-Covid.</p>
<div class="cell">
<details>
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb15"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb15-1"><a href="#cb15-1" aria-hidden="true" tabindex="-1"></a><span class="fu">boxplot</span>(white<span class="sc">$</span><span class="st">`</span><span class="at">% Poverty</span><span class="st">`</span> <span class="sc">~</span> white<span class="sc">$</span>Post_Covid,</span>
<span id="cb15-2"><a href="#cb15-2" aria-hidden="true" tabindex="-1"></a>        <span class="at">xlab =</span> <span class="st">"Pre-Covid (0) or Post-Covid (1)"</span>,</span>
<span id="cb15-3"><a href="#cb15-3" aria-hidden="true" tabindex="-1"></a>        <span class="at">ylab =</span> <span class="st">"Percent of Students in Majority White Districts in Poverty"</span>,</span>
<span id="cb15-4"><a href="#cb15-4" aria-hidden="true" tabindex="-1"></a>        <span class="at">cex.lab =</span> <span class="fl">0.75</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output-display">
<p><img src="FinalPt2_KarenKimble_files/figure-html/unnamed-chunk-6-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<p>The box plot showing majority white districts’ poverty levels pre- and post-Covid indicate that, while the median poverty level did not change dramatically, the maximum percentage and the third quartile percentage of poverty decreased between pre- and post-Covid. There was a high outlier pre-Covid, but this disappeared in the post-Covid box plot. The majority of observations for predominantly white schools fall in between about 15%-40% of students in poverty, for both pre- and post-Covid levels.</p>
<div class="cell">
<details>
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb16"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb16-1"><a href="#cb16-1" aria-hidden="true" tabindex="-1"></a><span class="fu">boxplot</span>(nonwhite<span class="sc">$</span><span class="st">`</span><span class="at">% Poverty</span><span class="st">`</span> <span class="sc">~</span> nonwhite<span class="sc">$</span>Post_Covid,</span>
<span id="cb16-2"><a href="#cb16-2" aria-hidden="true" tabindex="-1"></a>        <span class="at">xlab =</span> <span class="st">"Pre-Covid (0) or Post-Covid (1)"</span>,</span>
<span id="cb16-3"><a href="#cb16-3" aria-hidden="true" tabindex="-1"></a>        <span class="at">ylab =</span> <span class="st">"Percent of Students in Majority Non-White Districts in Poverty"</span>,</span>
<span id="cb16-4"><a href="#cb16-4" aria-hidden="true" tabindex="-1"></a>        <span class="at">cex.lab =</span> <span class="fl">0.75</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output-display">
<p><img src="FinalPt2_KarenKimble_files/figure-html/unnamed-chunk-7-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<p>The box plot for majority non-white districts’ poverty levels has a large number of outliers under the poverty level of 50%, similar to the plot for all school districts. The median level of poverty actually increased slightly between pre- and post-Covid years, along with the minimum level of poverty (both in the plot and in outliers). The maximum level of poverty, however, decreased more between these years. A majority of obersvations for both pre- and post-Covid are between 70%-90% of students in poverty for majority non-white districts.</p>
<div class="cell">
<details>
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb17"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb17-1"><a href="#cb17-1" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(school_data, <span class="fu">aes</span>(<span class="at">x=</span><span class="st">`</span><span class="at">% Poverty</span><span class="st">`</span>)) <span class="sc">+</span></span>
<span id="cb17-2"><a href="#cb17-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_histogram</span>(<span class="at">binwidth =</span> <span class="dv">5</span>, <span class="at">color=</span><span class="st">"black"</span>, <span class="at">fill=</span><span class="st">"white"</span>) <span class="sc">+</span></span>
<span id="cb17-3"><a href="#cb17-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_vline</span>(<span class="fu">aes</span>(<span class="at">xintercept=</span><span class="fu">mean</span>(<span class="st">`</span><span class="at">% Poverty</span><span class="st">`</span>)), <span class="at">color=</span><span class="st">"red"</span>, <span class="at">linetype=</span><span class="st">"dashed"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output-display">
<p><img src="FinalPt2_KarenKimble_files/figure-html/unnamed-chunk-8-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<p>From the histogram above, we can see that the mean percentage of poverty for all NYC school districts is just above 75%. Most observations are above the mean, with very few school districts below 50% poverty levels. This is most likely why there were so many outliers in the box plots for all school districts and majority non-white school districts.</p>
<div class="cell">
<details>
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb18"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb18-1"><a href="#cb18-1" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(pre, <span class="fu">aes</span>(<span class="at">x=</span><span class="st">`</span><span class="at">% Poverty</span><span class="st">`</span>)) <span class="sc">+</span></span>
<span id="cb18-2"><a href="#cb18-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_histogram</span>(<span class="at">binwidth =</span> <span class="dv">5</span>, <span class="at">color=</span><span class="st">"black"</span>, <span class="at">fill=</span><span class="st">"gray"</span>) <span class="sc">+</span></span>
<span id="cb18-3"><a href="#cb18-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">title=</span><span class="st">"School Districts Pre-Covid"</span>) <span class="sc">+</span></span>
<span id="cb18-4"><a href="#cb18-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_vline</span>(<span class="fu">aes</span>(<span class="at">xintercept=</span><span class="fu">mean</span>(<span class="st">`</span><span class="at">% Poverty</span><span class="st">`</span>)), <span class="at">color=</span><span class="st">"red"</span>, <span class="at">linetype=</span><span class="st">"dashed"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output-display">
<p><img src="FinalPt2_KarenKimble_files/figure-html/unnamed-chunk-9-1.png" class="img-fluid" width="672"></p>
</div>
<details>
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb19"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb19-1"><a href="#cb19-1" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(post, <span class="fu">aes</span>(<span class="at">x=</span><span class="st">`</span><span class="at">% Poverty</span><span class="st">`</span>)) <span class="sc">+</span></span>
<span id="cb19-2"><a href="#cb19-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_histogram</span>(<span class="at">binwidth =</span> <span class="dv">5</span>, <span class="at">color=</span><span class="st">"black"</span>, <span class="at">fill=</span><span class="st">"light gray"</span>) <span class="sc">+</span></span>
<span id="cb19-3"><a href="#cb19-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">title=</span><span class="st">"School Districts Post-Covid"</span>) <span class="sc">+</span></span>
<span id="cb19-4"><a href="#cb19-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_vline</span>(<span class="fu">aes</span>(<span class="at">xintercept=</span><span class="fu">mean</span>(<span class="st">`</span><span class="at">% Poverty</span><span class="st">`</span>)), <span class="at">color=</span><span class="st">"red"</span>, <span class="at">linetype=</span><span class="st">"dashed"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output-display">
<p><img src="FinalPt2_KarenKimble_files/figure-html/unnamed-chunk-9-2.png" class="img-fluid" width="672"></p>
</div>
</div>
<p>The two different plots above show that a alightly larger share of districts post-Covid had poverty levels above the mean. The observations are very skewed to the left in all three plots, however.</p>
</section>
<section id="hypothesis-testing" class="level2">
<h2 class="anchored" data-anchor-id="hypothesis-testing">Hypothesis Testing</h2>
<p>Response variables: Percentage of students in poverty</p>
<p>Explanatory variables: Post- or pre-Covid, whether the school is majority or minority white</p>
<p>I’m including the interaction term of school demographics because I think that this does play a major role in how Covid effects were mitigated or compounded. Schools with more white students may have received more support during Covid, whether directly to the school or to the students themselves.</p>
<p>Null Hypothesis: The percentage of students in poverty is the same both pre- and post-Covid for both majority and minority white school districts.</p>
<p>Alternative Hypothesis: The percentage of students in poverty is higher post-Covid than pre-Covid, and this effect will be more drastic in minority white school districts than in majority white school districts.</p>
<div class="cell">
<details>
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb20"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb20-1"><a href="#cb20-1" aria-hidden="true" tabindex="-1"></a><span class="fu">mean</span>(post_white<span class="sc">$</span><span class="st">'% Poverty'</span>) <span class="sc">-</span> <span class="fu">mean</span>(pre_white<span class="sc">$</span><span class="st">'% Poverty'</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>[1] -0.9168508</code></pre>
</div>
<details>
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb22"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb22-1"><a href="#cb22-1" aria-hidden="true" tabindex="-1"></a><span class="fu">mean</span>(post_nonwhite<span class="sc">$</span><span class="st">'% Poverty'</span>) <span class="sc">-</span> <span class="fu">mean</span>(pre_nonwhite<span class="sc">$</span><span class="st">'% Poverty'</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 0.4610488</code></pre>
</div>
<details>
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb24"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb24-1"><a href="#cb24-1" aria-hidden="true" tabindex="-1"></a><span class="fu">mean</span>(post<span class="sc">$</span><span class="st">'% Poverty'</span>) <span class="sc">-</span> <span class="fu">mean</span>(pre<span class="sc">$</span><span class="st">'% Poverty'</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 0.8529465</code></pre>
</div>
</div>
<p>Before conducting the hypothesis test, we already see that the differences between pre- and post-Covid poverty levels are very different for majority white and majorty nonwhite schools. Majority white schools actually had a decrease in poverty of 0.91% between pre-Covid and post-Covid school years. Yet majority nonwhite schools saw poverty increase between pre- and post-Covid by 0.46%. All school districts saw an overall 0.85% poverty increase in this time period. However, these numbers could be skewed since there is only one post-Covid year while there are a lot of years included in the data-set pre-Covid.</p>
<div class="cell">
<details>
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb26"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb26-1"><a href="#cb26-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Hypothesis Test</span></span>
<span id="cb26-2"><a href="#cb26-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb26-3"><a href="#cb26-3" aria-hidden="true" tabindex="-1"></a>model <span class="ot">&lt;-</span> <span class="fu">lm</span>(school_data<span class="sc">$</span><span class="st">'% Poverty'</span> <span class="sc">~</span> school_data<span class="sc">$</span>Post_Covid <span class="sc">+</span> school_data<span class="sc">$</span>pct_white <span class="sc">+</span> school_data<span class="sc">$</span>Post_Covid <span class="sc">*</span> school_data<span class="sc">$</span>pct_white)</span>
<span id="cb26-4"><a href="#cb26-4" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(model)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = school_data$"% Poverty" ~ school_data$Post_Covid + 
    school_data$pct_white + school_data$Post_Covid * school_data$pct_white)

Residuals:
    Min      1Q  Median      3Q     Max 
-53.760  -7.076   1.633   8.534  46.497 

Coefficients:
                                              Estimate Std. Error  t value
(Intercept)                                    86.0034     0.1154  745.344
school_data$Post_Covid1                         1.2192     0.3620    3.368
school_data$pct_white                         -84.3586     0.5311 -158.838
school_data$Post_Covid1:school_data$pct_white  -6.1271     1.7540   -3.493
                                              Pr(&gt;|t|)    
(Intercept)                                    &lt; 2e-16 ***
school_data$Post_Covid1                       0.000757 ***
school_data$pct_white                          &lt; 2e-16 ***
school_data$Post_Covid1:school_data$pct_white 0.000478 ***
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 12.22 on 18138 degrees of freedom
Multiple R-squared:  0.6083,    Adjusted R-squared:  0.6082 
F-statistic:  9389 on 3 and 18138 DF,  p-value: &lt; 2.2e-16</code></pre>
</div>
</div>
<p>As seen from the results above, the p-values for all three coefficients are smaller than the significance level of a = 0.05. The results for the coefficient for the varaible Post-Covid indicate that there is statistically significant evidence to reject the null hypothesis, that the percentage of students in poverty is the same both pre- and post-Covid.</p>
</section>
<section id="model-comparisons" class="level2">
<h2 class="anchored" data-anchor-id="model-comparisons">Model Comparisons</h2>
<div class="cell">
<details>
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb28"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb28-1"><a href="#cb28-1" aria-hidden="true" tabindex="-1"></a>model2 <span class="ot">&lt;-</span> <span class="fu">lm</span>(school_data<span class="sc">$</span><span class="st">'% Poverty'</span> <span class="sc">~</span> school_data<span class="sc">$</span>Post_Covid <span class="sc">+</span> school_data<span class="sc">$</span>pct_white)</span>
<span id="cb28-2"><a href="#cb28-2" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(model2)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = school_data$"% Poverty" ~ school_data$Post_Covid + 
    school_data$pct_white)

Residuals:
    Min      1Q  Median      3Q     Max 
-53.822  -7.128   1.638   8.595  46.731 

Coefficients:
                        Estimate Std. Error  t value Pr(&gt;|t|)    
(Intercept)              86.0713     0.1138  756.533   &lt;2e-16 ***
school_data$Post_Covid1   0.5011     0.2980    1.681   0.0927 .  
school_data$pct_white   -84.9203     0.5063 -167.720   &lt;2e-16 ***
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 12.23 on 18139 degrees of freedom
Multiple R-squared:  0.608, Adjusted R-squared:  0.608 
F-statistic: 1.407e+04 on 2 and 18139 DF,  p-value: &lt; 2.2e-16</code></pre>
</div>
</div>
<p>In this second model without the interaction term, the Covid variable has a much higher p-value of 0.9, larger than the 0.05 significance level. This means that in this model, there is not significant evidence to reject the hypothesis that the percentage of students in poverty is the same both pre- and post-Covid. However, the p-value for the variable of the percentage of white students remains much smaller than the 0.05 significance level. There is still significant evidence in this model to reject the hypothesis that the percentage of students in poverty is the same for all percentages of white students in the school.</p>
<p>Though this model could still work, I think the first model with the interaction term would still be more accurate. As stated before, the effects of Covid on poverty levels would be mitigated by how much support students in these school districts had, and there is ample evidence that majority white areas receive much more support or are generally more affluent than majority nonwhite areas.</p>
</section>
<section id="diagnostics" class="level2">
<h2 class="anchored" data-anchor-id="diagnostics">Diagnostics</h2>
<div class="cell">
<details>
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb30"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb30-1"><a href="#cb30-1" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(model)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output-display">
<p><img src="FinalPt2_KarenKimble_files/figure-html/unnamed-chunk-13-1.png" class="img-fluid" width="672"></p>
</div>
<div class="cell-output-display">
<p><img src="FinalPt2_KarenKimble_files/figure-html/unnamed-chunk-13-2.png" class="img-fluid" width="672"></p>
</div>
<div class="cell-output-display">
<p><img src="FinalPt2_KarenKimble_files/figure-html/unnamed-chunk-13-3.png" class="img-fluid" width="672"></p>
</div>
<div class="cell-output-display">
<p><img src="FinalPt2_KarenKimble_files/figure-html/unnamed-chunk-13-4.png" class="img-fluid" width="672"></p>
</div>
</div>
<p>In the Residuals vs Fitted plot, the Residuals seem to be random around the linear line, indicating that the assumption of a linear relationship is reasonable.</p>
<p>In the Normal Q-Q plot, the points generally fall along the line, supporting the assumption of normal residuals.</p>
<p>The Scale-Location plot does show a slight downward trend, but is approximately horizontal for most of the graph. This means that standardized residuals could be changing because of the fitted values and it’s possible that there is not constant variance.</p>
<p>There are no points outside of the proper distance in the Residuals vs.&nbsp;Leverage plot, showing that there is no single influential observation.</p>
</section>
<section id="references" class="level2">
<h2 class="anchored" data-anchor-id="references">References</h2>
<p>New York State Child Poverty Facts. Schuyler Center for Analysis and Advocacy. (2021, February 18). Retrieved from https://scaany.org/wp-content/uploads/2021/02/NYS-Child-Poverty-Facts_Feb2021.pdf</p>
<p>Poverty in New York City. Columbia University Center on Poverty and Social Policy. (n.d.). Retrieved from https://www.povertycenter.columbia.edu/poverty-in-new-york-city#:~:text=Children%20and%20Families%20in%20New%20York%20City&amp;text=Through%20surveys%2C%20we%20find%20that,is%20at%20least%2020%20percent.</p>


<!-- -->

</section>

</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const disableStylesheet = (stylesheets) => {
    for (let i=0; i < stylesheets.length; i++) {
      const stylesheet = stylesheets[i];
      stylesheet.rel = 'prefetch';
    }
  }
  const enableStylesheet = (stylesheets) => {
    for (let i=0; i < stylesheets.length; i++) {
      const stylesheet = stylesheets[i];
      stylesheet.rel = 'stylesheet';
    }
  }
  const manageTransitions = (selector, allowTransitions) => {
    const els = window.document.querySelectorAll(selector);
    for (let i=0; i < els.length; i++) {
      const el = els[i];
      if (allowTransitions) {
        el.classList.remove('notransition');
      } else {
        el.classList.add('notransition');
      }
    }
  }
  const toggleColorMode = (alternate) => {
    // Switch the stylesheets
    const alternateStylesheets = window.document.querySelectorAll('link.quarto-color-scheme.quarto-color-alternate');
    manageTransitions('#quarto-margin-sidebar .nav-link', false);
    if (alternate) {
      enableStylesheet(alternateStylesheets);
      for (const sheetNode of alternateStylesheets) {
        if (sheetNode.id === "quarto-bootstrap") {
          toggleBodyColorMode(sheetNode);
        }
      }
    } else {
      disableStylesheet(alternateStylesheets);
      toggleBodyColorPrimary();
    }
    manageTransitions('#quarto-margin-sidebar .nav-link', true);
    // Switch the toggles
    const toggles = window.document.querySelectorAll('.quarto-color-scheme-toggle');
    for (let i=0; i < toggles.length; i++) {
      const toggle = toggles[i];
      if (toggle) {
        if (alternate) {
          toggle.classList.add("alternate");     
        } else {
          toggle.classList.remove("alternate");
        }
      }
    }
    // Hack to workaround the fact that safari doesn't
    // properly recolor the scrollbar when toggling (#1455)
    if (navigator.userAgent.indexOf('Safari') > 0 && navigator.userAgent.indexOf('Chrome') == -1) {
      manageTransitions("body", false);
      window.scrollTo(0, 1);
      setTimeout(() => {
        window.scrollTo(0, 0);
        manageTransitions("body", true);
      }, 40);  
    }
  }
  const isFileUrl = () => { 
    return window.location.protocol === 'file:';
  }
  const hasAlternateSentinel = () => {  
    let styleSentinel = getColorSchemeSentinel();
    if (styleSentinel !== null) {
      return styleSentinel === "alternate";
    } else {
      return false;
    }
  }
  const setStyleSentinel = (alternate) => {
    const value = alternate ? "alternate" : "default";
    if (!isFileUrl()) {
      window.localStorage.setItem("quarto-color-scheme", value);
    } else {
      localAlternateSentinel = value;
    }
  }
  const getColorSchemeSentinel = () => {
    if (!isFileUrl()) {
      const storageValue = window.localStorage.getItem("quarto-color-scheme");
      return storageValue != null ? storageValue : localAlternateSentinel;
    } else {
      return localAlternateSentinel;
    }
  }
  let localAlternateSentinel = 'default';
  // Dark / light mode switch
  window.quartoToggleColorScheme = () => {
    // Read the current dark / light value 
    let toAlternate = !hasAlternateSentinel();
    toggleColorMode(toAlternate);
    setStyleSentinel(toAlternate);
  };
  // Ensure there is a toggle, if there isn't float one in the top right
  if (window.document.querySelector('.quarto-color-scheme-toggle') === null) {
    const a = window.document.createElement('a');
    a.classList.add('top-right');
    a.classList.add('quarto-color-scheme-toggle');
    a.href = "";
    a.onclick = function() { try { window.quartoToggleColorScheme(); } catch {} return false; };
    const i = window.document.createElement("i");
    i.classList.add('bi');
    a.appendChild(i);
    window.document.body.appendChild(a);
  }
  // Switch to dark mode if need be
  if (hasAlternateSentinel()) {
    toggleColorMode(true);
  } else {
    toggleColorMode(false);
  }
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const clipboard = new window.ClipboardJS('.code-copy-button', {
    target: function(trigger) {
      return trigger.previousElementSibling;
    }
  });
  clipboard.on('success', function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copied!");
    let tooltip;
    if (window.bootstrap) {
      button.setAttribute("data-bs-toggle", "tooltip");
      button.setAttribute("data-bs-placement", "left");
      button.setAttribute("data-bs-title", "Copied!");
      tooltip = new bootstrap.Tooltip(button, 
        { trigger: "manual", 
          customClass: "code-copy-button-tooltip",
          offset: [0, -8]});
      tooltip.show();    
    }
    setTimeout(function() {
      if (tooltip) {
        tooltip.hide();
        button.removeAttribute("data-bs-title");
        button.removeAttribute("data-bs-toggle");
        button.removeAttribute("data-bs-placement");
      }
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  });
  const viewSource = window.document.getElementById('quarto-view-source') ||
                     window.document.getElementById('quarto-code-tools-source');
  if (viewSource) {
    const sourceUrl = viewSource.getAttribute("data-quarto-source-url");
    viewSource.addEventListener("click", function(e) {
      if (sourceUrl) {
        // rstudio viewer pane
        if (/\bcapabilities=\b/.test(window.location)) {
          window.open(sourceUrl);
        } else {
          window.location.href = sourceUrl;
        }
      } else {
        const modal = new bootstrap.Modal(document.getElementById('quarto-embedded-source-code-modal'));
        modal.show();
      }
      return false;
    });
  }
  function toggleCodeHandler(show) {
    return function(e) {
      const detailsSrc = window.document.querySelectorAll(".cell > details > .sourceCode");
      for (let i=0; i<detailsSrc.length; i++) {
        const details = detailsSrc[i].parentElement;
        if (show) {
          details.open = true;
        } else {
          details.removeAttribute("open");
        }
      }
      const cellCodeDivs = window.document.querySelectorAll(".cell > .sourceCode");
      const fromCls = show ? "hidden" : "unhidden";
      const toCls = show ? "unhidden" : "hidden";
      for (let i=0; i<cellCodeDivs.length; i++) {
        const codeDiv = cellCodeDivs[i];
        if (codeDiv.classList.contains(fromCls)) {
          codeDiv.classList.remove(fromCls);
          codeDiv.classList.add(toCls);
        } 
      }
      return false;
    }
  }
  const hideAllCode = window.document.getElementById("quarto-hide-all-code");
  if (hideAllCode) {
    hideAllCode.addEventListener("click", toggleCodeHandler(false));
  }
  const showAllCode = window.document.getElementById("quarto-show-all-code");
  if (showAllCode) {
    showAllCode.addEventListener("click", toggleCodeHandler(true));
  }
  function tippyHover(el, contentFn) {
    const config = {
      allowHTML: true,
      content: contentFn,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start'
    };
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      return note.innerHTML;
    });
  }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
});
</script>
<script src="https://giscus.app/client.js" data-repo="DACSS/603_Fall_2022" data-repo-id="R_kgDOH568kA" data-category="Announcements" data-category-id="" data-mapping="title" data-reactions-enabled="1" data-emit-metadata="0" data-input-position="top" data-theme="light" data-lang="en" crossorigin="anonymous" async="">
</script><div class="modal fade" id="quarto-embedded-source-code-modal" tabindex="-1" aria-labelledby="quarto-embedded-source-code-modal-label" aria-hidden="true"><div class="modal-dialog modal-dialog-scrollable"><div class="modal-content"><div class="modal-header"><h5 class="modal-title" id="quarto-embedded-source-code-modal-label">Source Code</h5><button class="btn-close" data-bs-dismiss="modal"></button></div><div class="modal-body"><div class="">
<div class="sourceCode" id="cb31" data-shortcodes="false"><pre class="sourceCode markdown code-with-copy"><code class="sourceCode markdown"><span id="cb31-1"><a href="#cb31-1" aria-hidden="true" tabindex="-1"></a><span class="co">---</span></span>
<span id="cb31-2"><a href="#cb31-2" aria-hidden="true" tabindex="-1"></a><span class="an">title:</span><span class="co"> "DACSS 603 Final Project Pt 2"</span></span>
<span id="cb31-3"><a href="#cb31-3" aria-hidden="true" tabindex="-1"></a><span class="an">author:</span><span class="co"> "Karen Kimble"</span></span>
<span id="cb31-4"><a href="#cb31-4" aria-hidden="true" tabindex="-1"></a><span class="an">desription:</span><span class="co"> "Second part of final project"</span></span>
<span id="cb31-5"><a href="#cb31-5" aria-hidden="true" tabindex="-1"></a><span class="an">date:</span><span class="co"> "11/14/2022"</span></span>
<span id="cb31-6"><a href="#cb31-6" aria-hidden="true" tabindex="-1"></a><span class="an">format:</span></span>
<span id="cb31-7"><a href="#cb31-7" aria-hidden="true" tabindex="-1"></a><span class="co">  html:</span></span>
<span id="cb31-8"><a href="#cb31-8" aria-hidden="true" tabindex="-1"></a><span class="co">    toc: true</span></span>
<span id="cb31-9"><a href="#cb31-9" aria-hidden="true" tabindex="-1"></a><span class="co">    code-fold: true</span></span>
<span id="cb31-10"><a href="#cb31-10" aria-hidden="true" tabindex="-1"></a><span class="co">    code-copy: true</span></span>
<span id="cb31-11"><a href="#cb31-11" aria-hidden="true" tabindex="-1"></a><span class="co">    code-tools: true</span></span>
<span id="cb31-12"><a href="#cb31-12" aria-hidden="true" tabindex="-1"></a><span class="an">category:</span><span class="co"> finalpart2</span></span>
<span id="cb31-13"><a href="#cb31-13" aria-hidden="true" tabindex="-1"></a><span class="co">---</span></span>
<span id="cb31-14"><a href="#cb31-14" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb31-15"><a href="#cb31-15" aria-hidden="true" tabindex="-1"></a><span class="fu">## Setup</span></span>
<span id="cb31-16"><a href="#cb31-16" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb31-19"><a href="#cb31-19" aria-hidden="true" tabindex="-1"></a><span class="in">```{r}</span></span>
<span id="cb31-20"><a href="#cb31-20" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(tidyverse)</span>
<span id="cb31-21"><a href="#cb31-21" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(readr)</span>
<span id="cb31-22"><a href="#cb31-22" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(scales)</span>
<span id="cb31-23"><a href="#cb31-23" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(ggplot2)</span>
<span id="cb31-24"><a href="#cb31-24" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb31-25"><a href="#cb31-25" aria-hidden="true" tabindex="-1"></a><span class="co"># Importing datasets</span></span>
<span id="cb31-26"><a href="#cb31-26" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb31-27"><a href="#cb31-27" aria-hidden="true" tabindex="-1"></a>NYC_2019 <span class="ot">&lt;-</span> <span class="fu">read_csv</span>(<span class="st">"_data/2018-2019_School_Demographic_Snapshot.csv"</span>, <span class="at">col_types =</span> <span class="fu">cols</span>(<span class="st">`</span><span class="at">Grade PK (Half Day &amp; Full Day)</span><span class="st">`</span> <span class="ot">=</span> <span class="fu">col_skip</span>(), <span class="st">`</span><span class="at"># Multiple Race Categories Not Represented</span><span class="st">`</span> <span class="ot">=</span> <span class="fu">col_skip</span>(), <span class="st">`</span><span class="at">% Multiple Race Categories Not Represented</span><span class="st">`</span> <span class="ot">=</span> <span class="fu">col_skip</span>()))</span>
<span id="cb31-28"><a href="#cb31-28" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb31-29"><a href="#cb31-29" aria-hidden="true" tabindex="-1"></a>NYC_2019<span class="sc">$</span><span class="st">`</span><span class="at">% Poverty</span><span class="st">`</span> <span class="ot">&lt;-</span> <span class="fu">percent</span>(NYC_2019<span class="sc">$</span><span class="st">`</span><span class="at">% Poverty</span><span class="st">`</span>, <span class="at">accuracy=</span><span class="fl">0.1</span>)</span>
<span id="cb31-30"><a href="#cb31-30" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb31-31"><a href="#cb31-31" aria-hidden="true" tabindex="-1"></a>NYC_2021 <span class="ot">&lt;-</span> <span class="fu">read_csv</span>(<span class="st">"_data/2020-2021_Demographic_Snapshot_School.csv"</span>, <span class="at">col_types =</span> <span class="fu">cols</span>(<span class="st">`</span><span class="at">Grade 3K+PK (Half Day &amp; Full Day)</span><span class="st">`</span> <span class="ot">=</span> <span class="fu">col_skip</span>(), <span class="st">`</span><span class="at"># Multi-Racial</span><span class="st">`</span> <span class="ot">=</span> <span class="fu">col_skip</span>(), <span class="st">`</span><span class="at">% Multi-Racial</span><span class="st">`</span> <span class="ot">=</span> <span class="fu">col_skip</span>(), <span class="st">`</span><span class="at"># Native American</span><span class="st">`</span> <span class="ot">=</span> <span class="fu">col_skip</span>(), <span class="st">`</span><span class="at">% Native American</span><span class="st">`</span> <span class="ot">=</span> <span class="fu">col_skip</span>(), <span class="st">`</span><span class="at"># Missing Race/Ethnicity Data</span><span class="st">`</span> <span class="ot">=</span> <span class="fu">col_skip</span>(), <span class="st">`</span><span class="at">% Missing Race/Ethnicity Data</span><span class="st">`</span> <span class="ot">=</span> <span class="fu">col_skip</span>()))</span>
<span id="cb31-32"><a href="#cb31-32" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb31-33"><a href="#cb31-33" aria-hidden="true" tabindex="-1"></a><span class="co"># In order to bind the data, I had to remove columns that were not present in the other spreadsheet: Grade PK or 3K, Native American, the different multi-racial categories, and Missing Data</span></span>
<span id="cb31-34"><a href="#cb31-34" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb31-35"><a href="#cb31-35" aria-hidden="true" tabindex="-1"></a>school_data <span class="ot">&lt;-</span> <span class="fu">rbind</span>(NYC_2019, NYC_2021)</span>
<span id="cb31-36"><a href="#cb31-36" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb31-37"><a href="#cb31-37" aria-hidden="true" tabindex="-1"></a><span class="co"># Renaming some columns</span></span>
<span id="cb31-38"><a href="#cb31-38" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb31-39"><a href="#cb31-39" aria-hidden="true" tabindex="-1"></a>school_data<span class="sc">$</span>pct_white <span class="ot">&lt;-</span> school_data<span class="sc">$</span><span class="st">'% White'</span></span>
<span id="cb31-40"><a href="#cb31-40" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb31-41"><a href="#cb31-41" aria-hidden="true" tabindex="-1"></a><span class="co"># Making values coded as "above 95%" to equal 95% and "below 5%" to equal 5% for the purposes of this analysis</span></span>
<span id="cb31-42"><a href="#cb31-42" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb31-43"><a href="#cb31-43" aria-hidden="true" tabindex="-1"></a>school_data<span class="sc">$</span><span class="st">`</span><span class="at">% Poverty</span><span class="st">`</span> <span class="ot">&lt;-</span> <span class="fu">recode</span>(school_data<span class="sc">$</span><span class="st">`</span><span class="at">% Poverty</span><span class="st">`</span>, <span class="st">"Above 95%"</span> <span class="ot">=</span> <span class="st">"95%"</span>, <span class="st">"Below 5%"</span> <span class="ot">=</span> <span class="st">"5%"</span>)</span>
<span id="cb31-44"><a href="#cb31-44" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb31-45"><a href="#cb31-45" aria-hidden="true" tabindex="-1"></a><span class="co"># Re-coding variables as numeric</span></span>
<span id="cb31-46"><a href="#cb31-46" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb31-47"><a href="#cb31-47" aria-hidden="true" tabindex="-1"></a>school_data<span class="sc">$</span><span class="st">`</span><span class="at">% Poverty</span><span class="st">`</span> <span class="ot">&lt;-</span> <span class="fu">sapply</span>(school_data<span class="sc">$</span><span class="st">`</span><span class="at">% Poverty</span><span class="st">`</span>, <span class="cf">function</span>(x) <span class="fu">gsub</span>(<span class="st">"%"</span>, <span class="st">""</span>, x))</span>
<span id="cb31-48"><a href="#cb31-48" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb31-49"><a href="#cb31-49" aria-hidden="true" tabindex="-1"></a>school_data<span class="sc">$</span><span class="st">`</span><span class="at">% Poverty</span><span class="st">`</span> <span class="ot">&lt;-</span> <span class="fu">as.numeric</span>(school_data<span class="sc">$</span><span class="st">`</span><span class="at">% Poverty</span><span class="st">`</span>)</span>
<span id="cb31-50"><a href="#cb31-50" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb31-51"><a href="#cb31-51" aria-hidden="true" tabindex="-1"></a>school_data<span class="sc">$</span><span class="st">`</span><span class="at">Economic Need Index</span><span class="st">`</span> <span class="ot">&lt;-</span> <span class="fu">as.numeric</span>(school_data<span class="sc">$</span><span class="st">`</span><span class="at">Economic Need Index</span><span class="st">`</span>)</span>
<span id="cb31-52"><a href="#cb31-52" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb31-53"><a href="#cb31-53" aria-hidden="true" tabindex="-1"></a><span class="co"># Creating a new variable of post-Covid (1) and pre-Covid (0)</span></span>
<span id="cb31-54"><a href="#cb31-54" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb31-55"><a href="#cb31-55" aria-hidden="true" tabindex="-1"></a>school_data<span class="sc">$</span>Post_Covid <span class="ot">&lt;-</span> <span class="fu">ifelse</span>(school_data<span class="sc">$</span>Year <span class="sc">==</span> <span class="st">"2020-21"</span>, <span class="fu">c</span>(<span class="st">"1"</span>), <span class="fu">c</span>(<span class="st">"0"</span>))</span>
<span id="cb31-56"><a href="#cb31-56" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb31-57"><a href="#cb31-57" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb31-58"><a href="#cb31-58" aria-hidden="true" tabindex="-1"></a><span class="fu">## Research Question</span></span>
<span id="cb31-59"><a href="#cb31-59" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb31-60"><a href="#cb31-60" aria-hidden="true" tabindex="-1"></a>The research question I want to explore is whether child poverty has increased in schools that are predominantly made up of non-white students from the 2014-2015 school year to the 2020-2021 school year. I think this is extremely important to look at because of the pandemic's impact on not only child learning but also families' economic resources. According to the Columbia University Center on Poverty and Social Policy, "nearly a quarter of children ages 0-3 live in poverty and nearly half of the city's young children live in lower-opportunity neighborhoods where the poverty rate is at least 20 percent" ("Poverty"). Unfortunately, research shows that poverty is disproportionately felt according to one's race or ethnicity. In New York State, as of 2021, child poverty among children of color is almost 30%, with Black or African American children more than twice as likely to live in poverty than White, Non-Hispanic children ("New York State", 2021). With this disproportionate level of economic need in children of color, it seems important to investigate if the poverty level within New York City schools that are predominately non-White has increased significantly compared to schools that are predominantly White. When searching the UMass Libraries databases and other sources, it was hard to find studies that used this data in this way. It is important to understand if there is increasing poverty levels within an already vulnerable group.</span>
<span id="cb31-61"><a href="#cb31-61" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb31-62"><a href="#cb31-62" aria-hidden="true" tabindex="-1"></a><span class="fu">## Hypothesis</span></span>
<span id="cb31-63"><a href="#cb31-63" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb31-64"><a href="#cb31-64" aria-hidden="true" tabindex="-1"></a>I hypothesize that the poverty rate in NYC schools that are predominantly children of color will have increased more between pre- and post-Covid than the poverty rate in schools that are predominantly White. Since I have not found many previous studies on this, it is hard to know if this hypothesis was tested before. However, this data is fairly recent and also relates to the pandemic's effects on economics, so I think it is still a significant contribution to test this hypothesis.</span>
<span id="cb31-65"><a href="#cb31-65" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb31-66"><a href="#cb31-66" aria-hidden="true" tabindex="-1"></a><span class="fu">## Descriptive Statistics</span></span>
<span id="cb31-67"><a href="#cb31-67" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb31-68"><a href="#cb31-68" aria-hidden="true" tabindex="-1"></a>A description and summary of your data. How was your data collected by its original collectors? What are the important variables of interest for your research question? Use functions like glimpse() and summary() to present your data.</span>
<span id="cb31-69"><a href="#cb31-69" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb31-70"><a href="#cb31-70" aria-hidden="true" tabindex="-1"></a>The data was collected by New York City and put on its Open Data source. The data covers NYC schools in the academic years 2014-2015 to 2020-2021. The important variables of interest included in the data are:</span>
<span id="cb31-71"><a href="#cb31-71" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb31-72"><a href="#cb31-72" aria-hidden="true" tabindex="-1"></a><span class="ss">-   </span>Academic year, which I transformed into pre-Covid and post-Covid variables</span>
<span id="cb31-73"><a href="#cb31-73" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb31-74"><a href="#cb31-74" aria-hidden="true" tabindex="-1"></a><span class="ss">-   </span>Number and percentage of Asisan, Black, Hispanic, and White students</span>
<span id="cb31-75"><a href="#cb31-75" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb31-76"><a href="#cb31-76" aria-hidden="true" tabindex="-1"></a><span class="ss">-   </span>Number and percentage of students in poverty</span>
<span id="cb31-77"><a href="#cb31-77" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb31-78"><a href="#cb31-78" aria-hidden="true" tabindex="-1"></a><span class="ss">-   </span>Economic need index, which is the average of students' "Economic Need Values"</span>
<span id="cb31-79"><a href="#cb31-79" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb31-80"><a href="#cb31-80" aria-hidden="true" tabindex="-1"></a><span class="ss">    -   </span>The Economic Need Index (ENI) estimates the percentage of students facing economic hardship</span>
<span id="cb31-81"><a href="#cb31-81" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb31-82"><a href="#cb31-82" aria-hidden="true" tabindex="-1"></a>The other variables included are: DBN (district, borough, school number), school name, total enrollment, enrollment numbers for K-12, number and percentage of female and male students, number and percentage of students with disabilities, and number and percentage of English-Language Learner (ELL) students.</span>
<span id="cb31-83"><a href="#cb31-83" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb31-86"><a href="#cb31-86" aria-hidden="true" tabindex="-1"></a><span class="in">```{r}</span></span>
<span id="cb31-87"><a href="#cb31-87" aria-hidden="true" tabindex="-1"></a><span class="fu">glimpse</span>(school_data)</span>
<span id="cb31-88"><a href="#cb31-88" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb31-89"><a href="#cb31-89" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb31-92"><a href="#cb31-92" aria-hidden="true" tabindex="-1"></a><span class="in">```{r}</span></span>
<span id="cb31-93"><a href="#cb31-93" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(school_data)</span>
<span id="cb31-94"><a href="#cb31-94" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb31-95"><a href="#cb31-95" aria-hidden="true" tabindex="-1"></a><span class="co"># Note: the summary data for the enrollment numbers split by grade is somewhat off (especially minimums) because there is no variable listed for type of school (i.e., middle versus high school). So, for example, an elementary school would have an enrollment total of 0 for grade 12, which would show up as the minimum.</span></span>
<span id="cb31-96"><a href="#cb31-96" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb31-97"><a href="#cb31-97" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb31-98"><a href="#cb31-98" aria-hidden="true" tabindex="-1"></a>As we can see from this summary, the median percent of poverty in NYC schools (81.4%) is higher than the mean percent (75.89%), indicating that there may be low outliers with very low percentages of poverty. The same holds true for the Economic Need Index, with the mean (0.691) lower than the median (0.743). It is troubling, however, that both the mean and median percentages of poverty in NYC schools overall is more than three-fourths of the population.</span>
<span id="cb31-99"><a href="#cb31-99" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb31-100"><a href="#cb31-100" aria-hidden="true" tabindex="-1"></a><span class="fu">## Visualizations</span></span>
<span id="cb31-101"><a href="#cb31-101" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb31-104"><a href="#cb31-104" aria-hidden="true" tabindex="-1"></a><span class="in">```{r}</span></span>
<span id="cb31-105"><a href="#cb31-105" aria-hidden="true" tabindex="-1"></a>post_white <span class="ot">&lt;-</span> <span class="fu">filter</span>(school_data, pct_white <span class="sc">&gt;</span> <span class="fl">0.5</span> <span class="sc">&amp;</span> Post_Covid <span class="sc">==</span> <span class="st">"1"</span>)</span>
<span id="cb31-106"><a href="#cb31-106" aria-hidden="true" tabindex="-1"></a>post_nonwhite <span class="ot">&lt;-</span> <span class="fu">filter</span>(school_data, pct_white <span class="sc">&lt;=</span> <span class="fl">0.5</span> <span class="sc">&amp;</span> Post_Covid <span class="sc">==</span> <span class="st">"1"</span>)</span>
<span id="cb31-107"><a href="#cb31-107" aria-hidden="true" tabindex="-1"></a>pre_white <span class="ot">&lt;-</span> <span class="fu">filter</span>(school_data, pct_white <span class="sc">&gt;</span> <span class="fl">0.5</span> <span class="sc">&amp;</span> Post_Covid <span class="sc">==</span> <span class="st">"0"</span>)</span>
<span id="cb31-108"><a href="#cb31-108" aria-hidden="true" tabindex="-1"></a>pre_nonwhite <span class="ot">&lt;-</span> <span class="fu">filter</span>(school_data, pct_white <span class="sc">&lt;=</span> <span class="fl">0.5</span> <span class="sc">&amp;</span> Post_Covid <span class="sc">==</span> <span class="st">"0"</span>)</span>
<span id="cb31-109"><a href="#cb31-109" aria-hidden="true" tabindex="-1"></a>post <span class="ot">&lt;-</span> <span class="fu">filter</span>(school_data, Post_Covid <span class="sc">==</span> <span class="st">"1"</span>)</span>
<span id="cb31-110"><a href="#cb31-110" aria-hidden="true" tabindex="-1"></a>pre <span class="ot">&lt;-</span> <span class="fu">filter</span>(school_data, Post_Covid <span class="sc">==</span> <span class="st">"0"</span>)</span>
<span id="cb31-111"><a href="#cb31-111" aria-hidden="true" tabindex="-1"></a>white <span class="ot">&lt;-</span> <span class="fu">filter</span>(school_data, pct_white <span class="sc">&gt;</span> <span class="fl">0.5</span>)</span>
<span id="cb31-112"><a href="#cb31-112" aria-hidden="true" tabindex="-1"></a>nonwhite <span class="ot">&lt;-</span> <span class="fu">filter</span>(school_data, pct_white <span class="sc">&lt;=</span> <span class="fl">0.5</span>)</span>
<span id="cb31-113"><a href="#cb31-113" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb31-114"><a href="#cb31-114" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb31-117"><a href="#cb31-117" aria-hidden="true" tabindex="-1"></a><span class="in">```{r}</span></span>
<span id="cb31-118"><a href="#cb31-118" aria-hidden="true" tabindex="-1"></a><span class="fu">boxplot</span>(school_data<span class="sc">$</span><span class="st">`</span><span class="at">% Poverty</span><span class="st">`</span> <span class="sc">~</span> school_data<span class="sc">$</span>Post_Covid,</span>
<span id="cb31-119"><a href="#cb31-119" aria-hidden="true" tabindex="-1"></a>        <span class="at">xlab =</span> <span class="st">"Pre-Covid (0) or Post-Covid (1)"</span>,</span>
<span id="cb31-120"><a href="#cb31-120" aria-hidden="true" tabindex="-1"></a>        <span class="at">ylab =</span> <span class="st">"Percent of Students in Poverty"</span>)</span>
<span id="cb31-121"><a href="#cb31-121" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb31-122"><a href="#cb31-122" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb31-123"><a href="#cb31-123" aria-hidden="true" tabindex="-1"></a>From the box plot above, we can see that poverty levels between pre- and post-Covid did not change very dramatically for overall students. However, the maximum percentage of poverty did decrease from close to 100% to about 95%. Yet the median percentage level of poverty increased from pre- to post-Covid, though still remained under 90%. There are a large number of outliers below the minimum level of poverty, which is interesting--yet the minimum level of poverty increased between pre- and post-Covid.</span>
<span id="cb31-124"><a href="#cb31-124" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb31-127"><a href="#cb31-127" aria-hidden="true" tabindex="-1"></a><span class="in">```{r}</span></span>
<span id="cb31-128"><a href="#cb31-128" aria-hidden="true" tabindex="-1"></a><span class="fu">boxplot</span>(white<span class="sc">$</span><span class="st">`</span><span class="at">% Poverty</span><span class="st">`</span> <span class="sc">~</span> white<span class="sc">$</span>Post_Covid,</span>
<span id="cb31-129"><a href="#cb31-129" aria-hidden="true" tabindex="-1"></a>        <span class="at">xlab =</span> <span class="st">"Pre-Covid (0) or Post-Covid (1)"</span>,</span>
<span id="cb31-130"><a href="#cb31-130" aria-hidden="true" tabindex="-1"></a>        <span class="at">ylab =</span> <span class="st">"Percent of Students in Majority White Districts in Poverty"</span>,</span>
<span id="cb31-131"><a href="#cb31-131" aria-hidden="true" tabindex="-1"></a>        <span class="at">cex.lab =</span> <span class="fl">0.75</span>)</span>
<span id="cb31-132"><a href="#cb31-132" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb31-133"><a href="#cb31-133" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb31-134"><a href="#cb31-134" aria-hidden="true" tabindex="-1"></a>The box plot showing majority white districts' poverty levels pre- and post-Covid indicate that, while the median poverty level did not change dramatically, the maximum percentage and the third quartile percentage of poverty decreased between pre- and post-Covid. There was a high outlier pre-Covid, but this disappeared in the post-Covid box plot. The majority of observations for predominantly white schools fall in between about 15%-40% of students in poverty, for both pre- and post-Covid levels.</span>
<span id="cb31-135"><a href="#cb31-135" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb31-138"><a href="#cb31-138" aria-hidden="true" tabindex="-1"></a><span class="in">```{r}</span></span>
<span id="cb31-139"><a href="#cb31-139" aria-hidden="true" tabindex="-1"></a><span class="fu">boxplot</span>(nonwhite<span class="sc">$</span><span class="st">`</span><span class="at">% Poverty</span><span class="st">`</span> <span class="sc">~</span> nonwhite<span class="sc">$</span>Post_Covid,</span>
<span id="cb31-140"><a href="#cb31-140" aria-hidden="true" tabindex="-1"></a>        <span class="at">xlab =</span> <span class="st">"Pre-Covid (0) or Post-Covid (1)"</span>,</span>
<span id="cb31-141"><a href="#cb31-141" aria-hidden="true" tabindex="-1"></a>        <span class="at">ylab =</span> <span class="st">"Percent of Students in Majority Non-White Districts in Poverty"</span>,</span>
<span id="cb31-142"><a href="#cb31-142" aria-hidden="true" tabindex="-1"></a>        <span class="at">cex.lab =</span> <span class="fl">0.75</span>)</span>
<span id="cb31-143"><a href="#cb31-143" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb31-144"><a href="#cb31-144" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb31-145"><a href="#cb31-145" aria-hidden="true" tabindex="-1"></a>The box plot for majority non-white districts' poverty levels has a large number of outliers under the poverty level of 50%, similar to the plot for all school districts. The median level of poverty actually increased slightly between pre- and post-Covid years, along with the minimum level of poverty (both in the plot and in outliers). The maximum level of poverty, however, decreased more between these years. A majority of obersvations for both pre- and post-Covid are between 70%-90% of students in poverty for majority non-white districts.</span>
<span id="cb31-146"><a href="#cb31-146" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb31-149"><a href="#cb31-149" aria-hidden="true" tabindex="-1"></a><span class="in">```{r}</span></span>
<span id="cb31-150"><a href="#cb31-150" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(school_data, <span class="fu">aes</span>(<span class="at">x=</span><span class="st">`</span><span class="at">% Poverty</span><span class="st">`</span>)) <span class="sc">+</span></span>
<span id="cb31-151"><a href="#cb31-151" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_histogram</span>(<span class="at">binwidth =</span> <span class="dv">5</span>, <span class="at">color=</span><span class="st">"black"</span>, <span class="at">fill=</span><span class="st">"white"</span>) <span class="sc">+</span></span>
<span id="cb31-152"><a href="#cb31-152" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_vline</span>(<span class="fu">aes</span>(<span class="at">xintercept=</span><span class="fu">mean</span>(<span class="st">`</span><span class="at">% Poverty</span><span class="st">`</span>)), <span class="at">color=</span><span class="st">"red"</span>, <span class="at">linetype=</span><span class="st">"dashed"</span>)</span>
<span id="cb31-153"><a href="#cb31-153" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb31-154"><a href="#cb31-154" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb31-155"><a href="#cb31-155" aria-hidden="true" tabindex="-1"></a>From the histogram above, we can see that the mean percentage of poverty for all NYC school districts is just above 75%. Most observations are above the mean, with very few school districts below 50% poverty levels. This is most likely why there were so many outliers in the box plots for all school districts and majority non-white school districts.</span>
<span id="cb31-156"><a href="#cb31-156" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb31-159"><a href="#cb31-159" aria-hidden="true" tabindex="-1"></a><span class="in">```{r}</span></span>
<span id="cb31-160"><a href="#cb31-160" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(pre, <span class="fu">aes</span>(<span class="at">x=</span><span class="st">`</span><span class="at">% Poverty</span><span class="st">`</span>)) <span class="sc">+</span></span>
<span id="cb31-161"><a href="#cb31-161" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_histogram</span>(<span class="at">binwidth =</span> <span class="dv">5</span>, <span class="at">color=</span><span class="st">"black"</span>, <span class="at">fill=</span><span class="st">"gray"</span>) <span class="sc">+</span></span>
<span id="cb31-162"><a href="#cb31-162" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">title=</span><span class="st">"School Districts Pre-Covid"</span>) <span class="sc">+</span></span>
<span id="cb31-163"><a href="#cb31-163" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_vline</span>(<span class="fu">aes</span>(<span class="at">xintercept=</span><span class="fu">mean</span>(<span class="st">`</span><span class="at">% Poverty</span><span class="st">`</span>)), <span class="at">color=</span><span class="st">"red"</span>, <span class="at">linetype=</span><span class="st">"dashed"</span>)</span>
<span id="cb31-164"><a href="#cb31-164" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb31-165"><a href="#cb31-165" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(post, <span class="fu">aes</span>(<span class="at">x=</span><span class="st">`</span><span class="at">% Poverty</span><span class="st">`</span>)) <span class="sc">+</span></span>
<span id="cb31-166"><a href="#cb31-166" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_histogram</span>(<span class="at">binwidth =</span> <span class="dv">5</span>, <span class="at">color=</span><span class="st">"black"</span>, <span class="at">fill=</span><span class="st">"light gray"</span>) <span class="sc">+</span></span>
<span id="cb31-167"><a href="#cb31-167" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">title=</span><span class="st">"School Districts Post-Covid"</span>) <span class="sc">+</span></span>
<span id="cb31-168"><a href="#cb31-168" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_vline</span>(<span class="fu">aes</span>(<span class="at">xintercept=</span><span class="fu">mean</span>(<span class="st">`</span><span class="at">% Poverty</span><span class="st">`</span>)), <span class="at">color=</span><span class="st">"red"</span>, <span class="at">linetype=</span><span class="st">"dashed"</span>)</span>
<span id="cb31-169"><a href="#cb31-169" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb31-170"><a href="#cb31-170" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb31-171"><a href="#cb31-171" aria-hidden="true" tabindex="-1"></a>The two different plots above show that a alightly larger share of districts post-Covid had poverty levels above the mean. The observations are very skewed to the left in all three plots, however.</span>
<span id="cb31-172"><a href="#cb31-172" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb31-173"><a href="#cb31-173" aria-hidden="true" tabindex="-1"></a><span class="fu">## Hypothesis Testing</span></span>
<span id="cb31-174"><a href="#cb31-174" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb31-175"><a href="#cb31-175" aria-hidden="true" tabindex="-1"></a>Response variables: Percentage of students in poverty</span>
<span id="cb31-176"><a href="#cb31-176" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb31-177"><a href="#cb31-177" aria-hidden="true" tabindex="-1"></a>Explanatory variables: Post- or pre-Covid, whether the school is majority or minority white</span>
<span id="cb31-178"><a href="#cb31-178" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb31-179"><a href="#cb31-179" aria-hidden="true" tabindex="-1"></a>I'm including the interaction term of school demographics because I think that this does play a major role in how Covid effects were mitigated or compounded. Schools with more white students may have received more support during Covid, whether directly to the school or to the students themselves.</span>
<span id="cb31-180"><a href="#cb31-180" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb31-181"><a href="#cb31-181" aria-hidden="true" tabindex="-1"></a>Null Hypothesis: The percentage of students in poverty is the same both pre- and post-Covid for both majority and minority white school districts.</span>
<span id="cb31-182"><a href="#cb31-182" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb31-183"><a href="#cb31-183" aria-hidden="true" tabindex="-1"></a>Alternative Hypothesis: The percentage of students in poverty is higher post-Covid than pre-Covid, and this effect will be more drastic in minority white school districts than in majority white school districts.</span>
<span id="cb31-184"><a href="#cb31-184" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb31-187"><a href="#cb31-187" aria-hidden="true" tabindex="-1"></a><span class="in">```{r}</span></span>
<span id="cb31-188"><a href="#cb31-188" aria-hidden="true" tabindex="-1"></a><span class="fu">mean</span>(post_white<span class="sc">$</span><span class="st">'% Poverty'</span>) <span class="sc">-</span> <span class="fu">mean</span>(pre_white<span class="sc">$</span><span class="st">'% Poverty'</span>)</span>
<span id="cb31-189"><a href="#cb31-189" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb31-190"><a href="#cb31-190" aria-hidden="true" tabindex="-1"></a><span class="fu">mean</span>(post_nonwhite<span class="sc">$</span><span class="st">'% Poverty'</span>) <span class="sc">-</span> <span class="fu">mean</span>(pre_nonwhite<span class="sc">$</span><span class="st">'% Poverty'</span>)</span>
<span id="cb31-191"><a href="#cb31-191" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb31-192"><a href="#cb31-192" aria-hidden="true" tabindex="-1"></a><span class="fu">mean</span>(post<span class="sc">$</span><span class="st">'% Poverty'</span>) <span class="sc">-</span> <span class="fu">mean</span>(pre<span class="sc">$</span><span class="st">'% Poverty'</span>)</span>
<span id="cb31-193"><a href="#cb31-193" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb31-194"><a href="#cb31-194" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb31-195"><a href="#cb31-195" aria-hidden="true" tabindex="-1"></a>Before conducting the hypothesis test, we already see that the differences between pre- and post-Covid poverty levels are very different for majority white and majorty nonwhite schools. Majority white schools actually had a decrease in poverty of 0.91% between pre-Covid and post-Covid school years. Yet majority nonwhite schools saw poverty increase between pre- and post-Covid by 0.46%. All school districts saw an overall 0.85% poverty increase in this time period. However, these numbers could be skewed since there is only one post-Covid year while there are a lot of years included in the data-set pre-Covid.</span>
<span id="cb31-196"><a href="#cb31-196" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb31-199"><a href="#cb31-199" aria-hidden="true" tabindex="-1"></a><span class="in">```{r}</span></span>
<span id="cb31-200"><a href="#cb31-200" aria-hidden="true" tabindex="-1"></a><span class="co"># Hypothesis Test</span></span>
<span id="cb31-201"><a href="#cb31-201" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb31-202"><a href="#cb31-202" aria-hidden="true" tabindex="-1"></a>model <span class="ot">&lt;-</span> <span class="fu">lm</span>(school_data<span class="sc">$</span><span class="st">'% Poverty'</span> <span class="sc">~</span> school_data<span class="sc">$</span>Post_Covid <span class="sc">+</span> school_data<span class="sc">$</span>pct_white <span class="sc">+</span> school_data<span class="sc">$</span>Post_Covid <span class="sc">*</span> school_data<span class="sc">$</span>pct_white)</span>
<span id="cb31-203"><a href="#cb31-203" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(model)</span>
<span id="cb31-204"><a href="#cb31-204" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb31-205"><a href="#cb31-205" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb31-206"><a href="#cb31-206" aria-hidden="true" tabindex="-1"></a>As seen from the results above, the p-values for all three coefficients are smaller than the significance level of a = 0.05. The results for the coefficient for the varaible Post-Covid indicate that there is statistically significant evidence to reject the null hypothesis, that the percentage of students in poverty is the same both pre- and post-Covid. </span>
<span id="cb31-207"><a href="#cb31-207" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb31-208"><a href="#cb31-208" aria-hidden="true" tabindex="-1"></a><span class="fu">## Model Comparisons</span></span>
<span id="cb31-209"><a href="#cb31-209" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb31-212"><a href="#cb31-212" aria-hidden="true" tabindex="-1"></a><span class="in">```{r}</span></span>
<span id="cb31-213"><a href="#cb31-213" aria-hidden="true" tabindex="-1"></a>model2 <span class="ot">&lt;-</span> <span class="fu">lm</span>(school_data<span class="sc">$</span><span class="st">'% Poverty'</span> <span class="sc">~</span> school_data<span class="sc">$</span>Post_Covid <span class="sc">+</span> school_data<span class="sc">$</span>pct_white)</span>
<span id="cb31-214"><a href="#cb31-214" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(model2)</span>
<span id="cb31-215"><a href="#cb31-215" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb31-216"><a href="#cb31-216" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb31-217"><a href="#cb31-217" aria-hidden="true" tabindex="-1"></a>In this second model without the interaction term, the Covid variable has a much higher p-value of 0.9, larger than the 0.05 significance level. This means that in this model, there is not significant evidence to reject the hypothesis that the percentage of students in poverty is the same both pre- and post-Covid. However, the p-value for the variable of the percentage of white students remains much smaller than the 0.05 significance level. There is still significant evidence in this model to reject the hypothesis that the percentage of students in poverty is the same for all percentages of white students in the school.</span>
<span id="cb31-218"><a href="#cb31-218" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb31-219"><a href="#cb31-219" aria-hidden="true" tabindex="-1"></a>Though this model could still work, I think the first model with the interaction term would still be more accurate. As stated before, the effects of Covid on poverty levels would be mitigated by how much support students in these school districts had, and there is ample evidence that majority white areas receive much more support or are generally more affluent than majority nonwhite areas.</span>
<span id="cb31-220"><a href="#cb31-220" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb31-221"><a href="#cb31-221" aria-hidden="true" tabindex="-1"></a><span class="fu">## Diagnostics</span></span>
<span id="cb31-222"><a href="#cb31-222" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb31-225"><a href="#cb31-225" aria-hidden="true" tabindex="-1"></a><span class="in">```{r}</span></span>
<span id="cb31-226"><a href="#cb31-226" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(model)</span>
<span id="cb31-227"><a href="#cb31-227" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb31-228"><a href="#cb31-228" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb31-229"><a href="#cb31-229" aria-hidden="true" tabindex="-1"></a>In the Residuals vs Fitted plot, the Residuals seem to be random around the linear line, indicating that the assumption of a linear relationship is reasonable.</span>
<span id="cb31-230"><a href="#cb31-230" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb31-231"><a href="#cb31-231" aria-hidden="true" tabindex="-1"></a>In the Normal Q-Q plot, the points generally fall along the line, supporting the assumption of normal residuals.</span>
<span id="cb31-232"><a href="#cb31-232" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb31-233"><a href="#cb31-233" aria-hidden="true" tabindex="-1"></a>The Scale-Location plot does show a slight downward trend, but is approximately horizontal for most of the graph. This means that standardized residuals could be changing because of the fitted values and it's possible that there is not constant variance.</span>
<span id="cb31-234"><a href="#cb31-234" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb31-235"><a href="#cb31-235" aria-hidden="true" tabindex="-1"></a>There are no points outside of the proper distance in the Residuals vs. Leverage plot, showing that there is no single influential observation.</span>
<span id="cb31-236"><a href="#cb31-236" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb31-237"><a href="#cb31-237" aria-hidden="true" tabindex="-1"></a><span class="fu">## References</span></span>
<span id="cb31-238"><a href="#cb31-238" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb31-239"><a href="#cb31-239" aria-hidden="true" tabindex="-1"></a>New York State Child Poverty Facts. Schuyler Center for Analysis and Advocacy. (2021, February 18). Retrieved from https://scaany.org/wp-content/uploads/2021/02/NYS-Child-Poverty-Facts_Feb2021.pdf</span>
<span id="cb31-240"><a href="#cb31-240" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb31-241"><a href="#cb31-241" aria-hidden="true" tabindex="-1"></a>Poverty in New York City. Columbia University Center on Poverty and Social Policy. (n.d.). Retrieved from https://www.povertycenter.columbia.edu/poverty-in-new-york-city#:\~:text=Children%20and%20Families%20in%20New%20York%20City&amp;text=Through%20surveys%2C%20we%20find%20that,is%20at%20least%2020%20percent.</span>
</code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div></div></div></div></div>
</div> <!-- /content -->



</body></html>