<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.2.280">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">

<meta name="author" content="Caleb Hill">
<meta name="dcterms.date" content="2022-12-11">

<title>Final Part 3</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1.6em;
  vertical-align: middle;
}
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
    color: #aaaaaa;
  }
pre.numberSource { margin-left: 3em; border-left: 1px solid #aaaaaa;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
code span.al { color: #ff0000; font-weight: bold; } /* Alert */
code span.an { color: #60a0b0; font-weight: bold; font-style: italic; } /* Annotation */
code span.at { color: #7d9029; } /* Attribute */
code span.bn { color: #40a070; } /* BaseN */
code span.bu { color: #008000; } /* BuiltIn */
code span.cf { color: #007020; font-weight: bold; } /* ControlFlow */
code span.ch { color: #4070a0; } /* Char */
code span.cn { color: #880000; } /* Constant */
code span.co { color: #60a0b0; font-style: italic; } /* Comment */
code span.cv { color: #60a0b0; font-weight: bold; font-style: italic; } /* CommentVar */
code span.do { color: #ba2121; font-style: italic; } /* Documentation */
code span.dt { color: #902000; } /* DataType */
code span.dv { color: #40a070; } /* DecVal */
code span.er { color: #ff0000; font-weight: bold; } /* Error */
code span.ex { } /* Extension */
code span.fl { color: #40a070; } /* Float */
code span.fu { color: #06287e; } /* Function */
code span.im { color: #008000; font-weight: bold; } /* Import */
code span.in { color: #60a0b0; font-weight: bold; font-style: italic; } /* Information */
code span.kw { color: #007020; font-weight: bold; } /* Keyword */
code span.op { color: #666666; } /* Operator */
code span.ot { color: #007020; } /* Other */
code span.pp { color: #bc7a00; } /* Preprocessor */
code span.sc { color: #4070a0; } /* SpecialChar */
code span.ss { color: #bb6688; } /* SpecialString */
code span.st { color: #4070a0; } /* String */
code span.va { color: #19177c; } /* Variable */
code span.vs { color: #4070a0; } /* VerbatimString */
code span.wa { color: #60a0b0; font-weight: bold; font-style: italic; } /* Warning */
</style>


<script src="../site_libs/quarto-nav/quarto-nav.js"></script>
<script src="../site_libs/quarto-nav/headroom.min.js"></script>
<script src="../site_libs/clipboard/clipboard.min.js"></script>
<script src="../site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="../site_libs/quarto-search/fuse.min.js"></script>
<script src="../site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="../">
<link href="../images/DACSS_Round_Network.png" rel="icon" type="image/png">
<script src="../site_libs/quarto-html/quarto.js"></script>
<script src="../site_libs/quarto-html/popper.min.js"></script>
<script src="../site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="../site_libs/quarto-html/anchor.min.js"></script>
<link href="../site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="../site_libs/quarto-html/quarto-syntax-highlighting.css" rel="stylesheet" class="quarto-color-scheme" id="quarto-text-highlighting-styles">
<link href="../site_libs/quarto-html/quarto-syntax-highlighting-dark.css" rel="prefetch" class="quarto-color-scheme quarto-color-alternate" id="quarto-text-highlighting-styles">
<script src="../site_libs/bootstrap/bootstrap.min.js"></script>
<link href="../site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="../site_libs/bootstrap/bootstrap.min.css" rel="stylesheet" class="quarto-color-scheme" id="quarto-bootstrap" data-mode="light">
<link href="../site_libs/bootstrap/bootstrap-dark.min.css" rel="prefetch" class="quarto-color-scheme quarto-color-alternate" id="quarto-bootstrap" data-mode="dark">
<script id="quarto-search-options" type="application/json">{
  "location": "navbar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "end",
  "type": "overlay",
  "limit": 20,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit"
  }
}</script>


<meta name="twitter:title" content="Final Part 3">
<meta name="twitter:description" content="With climate change upsetting normal weather patterns, there has been exciting research into how precipitation shocks (flooding and drought events) impact health outcomes, (Rizmie, d.">
<meta name="twitter:creator" content="@UMassDACSS">
<meta name="twitter:site" content="@UMassDACSS">
<meta name="twitter:card" content="summary">
</head>

<body class="nav-fixed">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
    <nav class="navbar navbar-expand-lg navbar-dark ">
      <div class="navbar-container container-fluid">
      <div class="navbar-brand-container">
    <a href="../index.html" class="navbar-brand navbar-brand-logo">
    <img src="../images/UMass White Wordmark Horiz.png" alt="" class="navbar-logo">
    </a>
  </div>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse" aria-controls="navbarCollapse" aria-expanded="false" aria-label="Toggle navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
  <span class="navbar-toggler-icon"></span>
</button>
          <div class="collapse navbar-collapse" id="navbarCollapse">
            <ul class="navbar-nav navbar-nav-scroll ms-auto">
  <li class="nav-item">
    <a class="nav-link" href="https://dacss.github.io/603_Fall_2022/">
 <span class="menu-text">Fall 2022 Posts</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="../about.html">
 <span class="menu-text">Contributors</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="https://umass.edu/sbs/dacss">
 <span class="menu-text">DACSS</span></a>
  </li>  
  <li class="nav-item compact">
    <a class="nav-link" href="https://github.com/DACSS/603_Fall_2022"><i class="bi bi-github" role="img" aria-label="GitHub">
</i> 
 <span class="menu-text"></span></a>
  </li>  
</ul>
              <div class="quarto-toggle-container">
                  <a href="" class="quarto-color-scheme-toggle nav-link" onclick="window.quartoToggleColorScheme(); return false;" title="Toggle dark mode"><i class="bi"></i></a>
              </div>
              <div id="quarto-search" class="" title="Search"></div>
          </div> <!-- /navcollapse -->
      </div> <!-- /container-fluid -->
    </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article page-navbar">
<!-- sidebar -->
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">On this page</h2>
   
  <ul>
  <li><a href="#introduction" id="toc-introduction" class="nav-link active" data-scroll-target="#introduction">Introduction</a>
  <ul class="collapse">
  <li><a href="#research-question" id="toc-research-question" class="nav-link" data-scroll-target="#research-question">Research Question</a></li>
  <li><a href="#hypothesis" id="toc-hypothesis" class="nav-link" data-scroll-target="#hypothesis">Hypothesis</a></li>
  </ul></li>
  <li><a href="#descriptive-statistics" id="toc-descriptive-statistics" class="nav-link" data-scroll-target="#descriptive-statistics">Descriptive Statistics</a>
  <ul class="collapse">
  <li><a href="#average-yearly-precipitation" id="toc-average-yearly-precipitation" class="nav-link" data-scroll-target="#average-yearly-precipitation">Average Yearly Precipitation</a></li>
  <li><a href="#median-household-income" id="toc-median-household-income" class="nav-link" data-scroll-target="#median-household-income">Median Household Income</a></li>
  <li><a href="#percent-in-poverty" id="toc-percent-in-poverty" class="nav-link" data-scroll-target="#percent-in-poverty">Percent in Poverty</a></li>
  <li><a href="#percent-commuting-alone-over-60-minutes" id="toc-percent-commuting-alone-over-60-minutes" class="nav-link" data-scroll-target="#percent-commuting-alone-over-60-minutes">Percent Commuting Alone, Over 60 Minutes</a></li>
  <li><a href="#percent-renter-housing-costs-over-50-percent-of-income" id="toc-percent-renter-housing-costs-over-50-percent-of-income" class="nav-link" data-scroll-target="#percent-renter-housing-costs-over-50-percent-of-income">Percent Renter Housing Costs Over 50 Percent of Income</a></li>
  <li><a href="#re-hospitalization-rate" id="toc-re-hospitalization-rate" class="nav-link" data-scroll-target="#re-hospitalization-rate">Re-hospitalization Rate</a></li>
  </ul></li>
  <li><a href="#analysis" id="toc-analysis" class="nav-link" data-scroll-target="#analysis">Analysis</a>
  <ul class="collapse">
  <li><a href="#hypothesis-testing" id="toc-hypothesis-testing" class="nav-link" data-scroll-target="#hypothesis-testing">Hypothesis Testing</a></li>
  <li><a href="#model-comparisons" id="toc-model-comparisons" class="nav-link" data-scroll-target="#model-comparisons">Model Comparisons</a></li>
  <li><a href="#diagnostics" id="toc-diagnostics" class="nav-link" data-scroll-target="#diagnostics">Diagnostics</a></li>
  </ul></li>
  <li><a href="#conclusion" id="toc-conclusion" class="nav-link" data-scroll-target="#conclusion">Conclusion</a></li>
  <li><a href="#references" id="toc-references" class="nav-link" data-scroll-target="#references">References</a></li>
  </ul>
</nav>
    </div>
<!-- main -->
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<div class="quarto-title-block"><div><h1 class="title">Final Part 3</h1><button type="button" class="btn code-tools-button dropdown-toggle" id="quarto-code-tools-menu" data-bs-toggle="dropdown" aria-expanded="false"><i class="bi"></i> Code</button><ul class="dropdown-menu dropdown-menu-end" aria-labelelledby="quarto-code-tools-menu"><li><a id="quarto-show-all-code" class="dropdown-item" href="javascript:void(0)" role="button">Show All Code</a></li><li><a id="quarto-hide-all-code" class="dropdown-item" href="javascript:void(0)" role="button">Hide All Code</a></li><li><hr class="dropdown-divider"></li><li><a id="quarto-view-source" class="dropdown-item" href="javascript:void(0)" role="button">View Source</a></li></ul></div></div>
  <div class="quarto-categories">
    <div class="quarto-category">finalpart3</div>
    <div class="quarto-category">caleb.hill</div>
  </div>
  </div>



<div class="quarto-title-meta">

    <div>
    <div class="quarto-title-meta-heading">Author</div>
    <div class="quarto-title-meta-contents">
             <p>Caleb Hill </p>
          </div>
  </div>
    
    <div>
    <div class="quarto-title-meta-heading">Published</div>
    <div class="quarto-title-meta-contents">
      <p class="date">December 11, 2022</p>
    </div>
  </div>
  
    
  </div>
  

</header>

<section id="introduction" class="level2">
<h2 class="anchored" data-anchor-id="introduction">Introduction</h2>
<p>With climate change upsetting normal weather patterns, there has been exciting research into how precipitation shocks (flooding and drought events) impact health outcomes, (Rizmie, d., Preuz, L, Miraldo, M. &amp; Atun, R. (2022); Tapak, L., Maryanaji, Z., Hamidi, O., Abbasi, H. &amp; Najafi-Vosough, R. (2018); Trinh, T., Feeny, S. &amp; Posso, A. (2018)). Alongside this train of thought, multiple research reports state that there is a relationship between re-hospitalization rates and social characteristics, such as demographic and economic identifiers, (Barnett, Hsu &amp; McWilliams, 2015; Murray, Allen, Clark, Daly &amp; Jacobs, 2021). Specifically, racial characteristics play a large role in predicting re-hospitalization in a population (Li, Cai &amp; Glance, 2015). While some articles examine economic and health factors contributing to these disparities, very few dig deep into environmental factors that influence this phenomenon, (Spatz, Bernheim, Horwitz &amp; Herrin, 2020). With your zipcode affecting up to 60% of your health outcomes, this research is relevant to better improving one of our most costly health expenditures: hospitalization. Therefore, this research report aims to integrate these two concepts, testing if precipitation shocks have a positive relationship on not just hospital admissions but also re-admissions.</p>
<p>Re-hospitalization is a substantially costlier expenditure, as readmitting a patient further increases costs – especially if the diagnosis was untreated, poorly treated, or incorrectly treated. Most inpatient episodes characterized as a re-hospitalization when the patient is readmitted to the hospital 60 days after discharge. If the cause is different, sometimes that is counted as a re-hospitalization; other times, not so much, (Bhosale, K., Nath, R., Pandit, N., Agarwal, P., Khairnar, S., Yadav, B. &amp; Chandrakar, S., 2020).</p>
<section id="research-question" class="level3">
<h3 class="anchored" data-anchor-id="research-question">Research Question</h3>
<p>This paper aims to explore how precipitation shocks impact re-hospitalization rates on a county-by-county level. We will control for socio-demographic and economic variables. We will also stratify by rural/urban classification, to determine if counties above or below 250,000 population experience differences in re-hospitalization rates, dependent upon these explanatory variables. This is purely because literature shows that rural communities face more acute and poorer health outcomes.</p>
<p>The data-set chosen for this analysis is taken from the Agency for Healthcare Research and Quality, Social Determinants of Health (SDOH) Database. This data-set has over 1,400 variables to explore each SDOH domain: social context, economic context, education, healthcare, and the environment. We shall pull data from three of these five domains: social, economic, and environmental.</p>
<p>How re-hospitalization is measured is not clarified per this data-set’s codebook. However, the Center for Medicare and Medicaid (CMS) 30-day Risk-Standardized Readmission Rate (RSRR) measures re-hospitalization as an unplanned readmission to inpatient services. It does stratify and specify based upon diagnosis. As the AHRQ is a federal agency alongside CMS, it is likely that they are pulling from CMS for this measure and aggregating various diagnoses into one county rate.</p>
</section>
<section id="hypothesis" class="level3">
<h3 class="anchored" data-anchor-id="hypothesis">Hypothesis</h3>
<p>The hypothesis for this research report is:</p>
<ul>
<li>Precipitation has a positive impact on re-hospitalization rates within rural counties.</li>
</ul>
<p>Therefore, the null hypothesis is:</p>
<ul>
<li>Precipitation does not have a positive impact on re-hospitalization rates within rural counties.</li>
</ul>
<p>Various regression models shall be employed to determine the relationship – or lack thereof – between these variables.</p>
<p>First I’ll import the relevant librarie and set up a UMass color scheme for crimson and black.</p>
<p>Then I’ll import the dataset and view the first six rows.</p>
<div class="cell">
<details>
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb1"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a>df <span class="ot">&lt;-</span> SDOH_2020_COUNTY_1_0 <span class="ot">&lt;-</span> <span class="fu">read_excel</span>(<span class="st">"_data/SDOH_2020_COUNTY_1_0.xlsx"</span>, </span>
<span id="cb1-2"><a href="#cb1-2" aria-hidden="true" tabindex="-1"></a>                                         <span class="at">sheet =</span> <span class="st">"Data"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stderr">
<pre><code>Warning: Expecting logical in OA1673 / R1673C391: got '46123'</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning: Expecting logical in OA1765 / R1765C391: got '32510'</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning: Expecting logical in OB1765 / R1765C392: got '41025'</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning: Expecting logical in OC1765 / R1765C393: got '41037'</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning: Expecting logical in OA2799 / R2799C391: got '49017'</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning: Expecting logical in OB2799 / R2799C392: got '49019'</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning: Expecting logical in OC2799 / R2799C393: got '49025'</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning: Expecting logical in OD2799 / R2799C394: got '49055'</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning: Expecting logical in OA2844 / R2844C391: got '51760'</code></pre>
</div>
<details>
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb11"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb11-1"><a href="#cb11-1" aria-hidden="true" tabindex="-1"></a><span class="fu">head</span>(df)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 6 × 685
   YEAR COUNTYFIPS STATEFIPS STATE COUNTY REGION TERRI…¹ ACS_T…² ACS_T…³ ACS_T…⁴
  &lt;dbl&gt; &lt;chr&gt;      &lt;chr&gt;     &lt;chr&gt; &lt;chr&gt;  &lt;chr&gt;    &lt;dbl&gt;   &lt;dbl&gt;   &lt;dbl&gt;   &lt;dbl&gt;
1  2020 01001      01        Alab… Autau… South        0   55639   54929   52404
2  2020 01003      01        Alab… Baldw… South        0  218289  216518  206329
3  2020 01005      01        Alab… Barbo… South        0   25026   24792   23694
4  2020 01007      01        Alab… Bibb … South        0   22374   22073   21121
5  2020 01009      01        Alab… Bloun… South        0   57755   57164   54250
6  2020 01011      01        Alab… Bullo… South        0   10173   10143    9579
# … with 675 more variables: ACS_TOT_POP_ABOVE15 &lt;dbl&gt;,
#   ACS_TOT_POP_ABOVE16 &lt;dbl&gt;, ACS_TOT_POP_16_19 &lt;dbl&gt;,
#   ACS_TOT_POP_ABOVE25 &lt;dbl&gt;, ACS_TOT_CIVIL_POP_ABOVE18 &lt;dbl&gt;,
#   ACS_TOT_CIVIL_VET_POP_ABOVE25 &lt;dbl&gt;, ACS_TOT_OWN_CHILD_BELOW17 &lt;dbl&gt;,
#   ACS_TOT_WORKER_NWFH &lt;dbl&gt;, ACS_TOT_WORKER_HH &lt;dbl&gt;,
#   ACS_TOT_CIVILIAN_LABOR &lt;dbl&gt;, ACS_TOT_CIVIL_EMPLOY_POP &lt;dbl&gt;,
#   ACS_TOT_POP_POV &lt;dbl&gt;, ACS_TOT_CIVIL_NONINST_POP_POV &lt;dbl&gt;, …</code></pre>
</div>
</div>
<p>Next I want to verify the class is a dataframe. Otherwise, I’ll need to transform the data to make it easier to work with.</p>
<div class="cell">
<details>
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb13"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb13-1"><a href="#cb13-1" aria-hidden="true" tabindex="-1"></a><span class="fu">class</span>(df)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>[1] "tbl_df"     "tbl"        "data.frame"</code></pre>
</div>
</div>
<p>All good here.</p>
<p>Now on to data transformation. We will need to select only the relevant columns for this analysis.</p>
<div class="cell">
<details>
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb15"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb15-1"><a href="#cb15-1" aria-hidden="true" tabindex="-1"></a>df_new <span class="ot">&lt;-</span> df <span class="sc">%&gt;%</span></span>
<span id="cb15-2"><a href="#cb15-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">select</span>(COUNTYFIPS,</span>
<span id="cb15-3"><a href="#cb15-3" aria-hidden="true" tabindex="-1"></a>         STATE,</span>
<span id="cb15-4"><a href="#cb15-4" aria-hidden="true" tabindex="-1"></a>         COUNTY,</span>
<span id="cb15-5"><a href="#cb15-5" aria-hidden="true" tabindex="-1"></a>         AHRF_USDA_RUCC_2013,</span>
<span id="cb15-6"><a href="#cb15-6" aria-hidden="true" tabindex="-1"></a>         NOAAC_PRECIPITATION_AVG_YEARLY,</span>
<span id="cb15-7"><a href="#cb15-7" aria-hidden="true" tabindex="-1"></a>         ACS_PCT_MALE,</span>
<span id="cb15-8"><a href="#cb15-8" aria-hidden="true" tabindex="-1"></a>         ACS_PCT_FEMALE,</span>
<span id="cb15-9"><a href="#cb15-9" aria-hidden="true" tabindex="-1"></a>         ACS_PCT_AIAN,</span>
<span id="cb15-10"><a href="#cb15-10" aria-hidden="true" tabindex="-1"></a>         ACS_PCT_ASIAN,</span>
<span id="cb15-11"><a href="#cb15-11" aria-hidden="true" tabindex="-1"></a>         ACS_PCT_BLACK,</span>
<span id="cb15-12"><a href="#cb15-12" aria-hidden="true" tabindex="-1"></a>         ACS_PCT_HISPANIC,</span>
<span id="cb15-13"><a href="#cb15-13" aria-hidden="true" tabindex="-1"></a>         ACS_PCT_MULT_RACE,</span>
<span id="cb15-14"><a href="#cb15-14" aria-hidden="true" tabindex="-1"></a>         ACS_PCT_NHPI,</span>
<span id="cb15-15"><a href="#cb15-15" aria-hidden="true" tabindex="-1"></a>         ACS_PCT_OTHER_RACE,</span>
<span id="cb15-16"><a href="#cb15-16" aria-hidden="true" tabindex="-1"></a>         ACS_PCT_WHITE,</span>
<span id="cb15-17"><a href="#cb15-17" aria-hidden="true" tabindex="-1"></a>         SAIPE_MEDIAN_HH_INCOME,</span>
<span id="cb15-18"><a href="#cb15-18" aria-hidden="true" tabindex="-1"></a>         SAIPE_PCT_POV,</span>
<span id="cb15-19"><a href="#cb15-19" aria-hidden="true" tabindex="-1"></a>         ACS_PCT_COMMT_60MINUP,</span>
<span id="cb15-20"><a href="#cb15-20" aria-hidden="true" tabindex="-1"></a>         ACS_PCT_RENTER_HU_COST_50PCT,</span>
<span id="cb15-21"><a href="#cb15-21" aria-hidden="true" tabindex="-1"></a>         LTC_AVG_OBS_REHOSP_RATE) </span>
<span id="cb15-22"><a href="#cb15-22" aria-hidden="true" tabindex="-1"></a><span class="fu">nrow</span>(df_new)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 3229</code></pre>
</div>
<details>
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb17"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb17-1"><a href="#cb17-1" aria-hidden="true" tabindex="-1"></a><span class="fu">head</span>(df_new)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 6 × 20
  COUNTYF…¹ STATE COUNTY AHRF_…² NOAAC…³ ACS_P…⁴ ACS_P…⁵ ACS_P…⁶ ACS_P…⁷ ACS_P…⁸
  &lt;chr&gt;     &lt;chr&gt; &lt;chr&gt;  &lt;chr&gt;     &lt;dbl&gt;   &lt;dbl&gt;   &lt;dbl&gt;   &lt;dbl&gt;   &lt;dbl&gt;   &lt;dbl&gt;
1 01001     Alab… Autau… 2          5.72    48.6    51.4    0.28    1.17   19.5 
2 01003     Alab… Baldw… 3          5.27    48.5    51.5    0.69    0.93    8.77
3 01005     Alab… Barbo… 6          5.75    52.6    47.4    0.35    0.49   47.7 
4 01007     Alab… Bibb … 1          5.61    53.7    46.3    0.05    0.25   22.6 
5 01009     Alab… Bloun… 1          5.96    49.6    50.4    0.1     0.41    1.4 
6 01011     Alab… Bullo… 6          5.40    54.8    45.2    0       1.35   68.6 
# … with 10 more variables: ACS_PCT_HISPANIC &lt;dbl&gt;, ACS_PCT_MULT_RACE &lt;dbl&gt;,
#   ACS_PCT_NHPI &lt;dbl&gt;, ACS_PCT_OTHER_RACE &lt;dbl&gt;, ACS_PCT_WHITE &lt;dbl&gt;,
#   SAIPE_MEDIAN_HH_INCOME &lt;dbl&gt;, SAIPE_PCT_POV &lt;dbl&gt;,
#   ACS_PCT_COMMT_60MINUP &lt;dbl&gt;, ACS_PCT_RENTER_HU_COST_50PCT &lt;dbl&gt;,
#   LTC_AVG_OBS_REHOSP_RATE &lt;dbl&gt;, and abbreviated variable names ¹​COUNTYFIPS,
#   ²​AHRF_USDA_RUCC_2013, ³​NOAAC_PRECIPITATION_AVG_YEARLY, ⁴​ACS_PCT_MALE,
#   ⁵​ACS_PCT_FEMALE, ⁶​ACS_PCT_AIAN, ⁷​ACS_PCT_ASIAN, ⁸​ACS_PCT_BLACK</code></pre>
</div>
</div>
<p>Out of 1400+ variables, we’ve whittled them down to 20. Of those 20, we have four (4) that are unique identifiers (FIPS, State, County, and Rural-Urban Continuation Code), ten (10) socio-demographic, four (4) economic, one (1) for precipitation, and one (1) for re-hospitalization.</p>
<p>Before we launch into exploring these variables via descriptive statistics, first we need to determine where the NAs are and see if any of the variables will have a substantial amount of missing data.</p>
<div class="cell">
<details>
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb19"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb19-1"><a href="#cb19-1" aria-hidden="true" tabindex="-1"></a><span class="fu">kable</span>(<span class="fu">colSums</span>(<span class="fu">is.na</span>(df_new)))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output-display">
<table class="table table-sm table-striped">
<thead>
<tr class="header">
<th style="text-align: left;"></th>
<th style="text-align: right;">x</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">COUNTYFIPS</td>
<td style="text-align: right;">0</td>
</tr>
<tr class="even">
<td style="text-align: left;">STATE</td>
<td style="text-align: right;">0</td>
</tr>
<tr class="odd">
<td style="text-align: left;">COUNTY</td>
<td style="text-align: right;">0</td>
</tr>
<tr class="even">
<td style="text-align: left;">AHRF_USDA_RUCC_2013</td>
<td style="text-align: right;">9</td>
</tr>
<tr class="odd">
<td style="text-align: left;">NOAAC_PRECIPITATION_AVG_YEARLY</td>
<td style="text-align: right;">123</td>
</tr>
<tr class="even">
<td style="text-align: left;">ACS_PCT_MALE</td>
<td style="text-align: right;">8</td>
</tr>
<tr class="odd">
<td style="text-align: left;">ACS_PCT_FEMALE</td>
<td style="text-align: right;">8</td>
</tr>
<tr class="even">
<td style="text-align: left;">ACS_PCT_AIAN</td>
<td style="text-align: right;">8</td>
</tr>
<tr class="odd">
<td style="text-align: left;">ACS_PCT_ASIAN</td>
<td style="text-align: right;">8</td>
</tr>
<tr class="even">
<td style="text-align: left;">ACS_PCT_BLACK</td>
<td style="text-align: right;">8</td>
</tr>
<tr class="odd">
<td style="text-align: left;">ACS_PCT_HISPANIC</td>
<td style="text-align: right;">8</td>
</tr>
<tr class="even">
<td style="text-align: left;">ACS_PCT_MULT_RACE</td>
<td style="text-align: right;">8</td>
</tr>
<tr class="odd">
<td style="text-align: left;">ACS_PCT_NHPI</td>
<td style="text-align: right;">8</td>
</tr>
<tr class="even">
<td style="text-align: left;">ACS_PCT_OTHER_RACE</td>
<td style="text-align: right;">8</td>
</tr>
<tr class="odd">
<td style="text-align: left;">ACS_PCT_WHITE</td>
<td style="text-align: right;">8</td>
</tr>
<tr class="even">
<td style="text-align: left;">SAIPE_MEDIAN_HH_INCOME</td>
<td style="text-align: right;">87</td>
</tr>
<tr class="odd">
<td style="text-align: left;">SAIPE_PCT_POV</td>
<td style="text-align: right;">87</td>
</tr>
<tr class="even">
<td style="text-align: left;">ACS_PCT_COMMT_60MINUP</td>
<td style="text-align: right;">8</td>
</tr>
<tr class="odd">
<td style="text-align: left;">ACS_PCT_RENTER_HU_COST_50PCT</td>
<td style="text-align: right;">8</td>
</tr>
<tr class="even">
<td style="text-align: left;">LTC_AVG_OBS_REHOSP_RATE</td>
<td style="text-align: right;">410</td>
</tr>
</tbody>
</table>
</div>
</div>
<p>Plenty of variables with missing data. The most concerning is – of course – our outcome variable, Re-Hospitalization Rates. This is not ideal. However, 410 / 3229 (12.6%) is not bad. That still leaves us with plenty of counties to review.</p>
<div class="cell">
<details>
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb20"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb20-1"><a href="#cb20-1" aria-hidden="true" tabindex="-1"></a>df_new <span class="ot">&lt;-</span> df_new <span class="sc">%&gt;%</span></span>
<span id="cb20-2"><a href="#cb20-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">drop_na</span>() <span class="sc">%&gt;%</span></span>
<span id="cb20-3"><a href="#cb20-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">print</span>(<span class="fu">nrow</span>(df_new))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 2,814 × 20
   COUNTYFIPS STATE   COUNTY          AHRF_USDA_RUCC_2013
   &lt;chr&gt;      &lt;chr&gt;   &lt;chr&gt;           &lt;chr&gt;              
 1 01001      Alabama Autauga County  2                  
 2 01003      Alabama Baldwin County  3                  
 3 01005      Alabama Barbour County  6                  
 4 01007      Alabama Bibb County     1                  
 5 01009      Alabama Blount County   1                  
 6 01011      Alabama Bullock County  6                  
 7 01013      Alabama Butler County   6                  
 8 01015      Alabama Calhoun County  3                  
 9 01017      Alabama Chambers County 6                  
10 01019      Alabama Cherokee County 6                  
   NOAAC_PRECIPITATION_AVG_YEARLY ACS_PCT_MALE ACS_PCT_FEMALE ACS_PCT_AIAN
                            &lt;dbl&gt;        &lt;dbl&gt;          &lt;dbl&gt;        &lt;dbl&gt;
 1                           5.72         48.6           51.4         0.28
 2                           5.27         48.5           51.5         0.69
 3                           5.75         52.6           47.4         0.35
 4                           5.61         53.7           46.3         0.05
 5                           5.96         49.6           50.4         0.1 
 6                           5.40         54.8           45.2         0   
 7                           5.37         45.9           54.1         0.33
 8                           5.74         48.0           52.0         0.31
 9                           5.93         47.6           52.4         0.24
10                           5.85         49.4           50.6         0.58
   ACS_PCT_ASIAN ACS_PCT_BLACK ACS_PCT_HISPANIC ACS_PCT_MULT_RACE ACS_PCT_NHPI
           &lt;dbl&gt;         &lt;dbl&gt;            &lt;dbl&gt;             &lt;dbl&gt;        &lt;dbl&gt;
 1          1.17         19.5              2.88              2.55         0.04
 2          0.93          8.77             4.56              2.6          0   
 3          0.49         47.7              4.44              2.09         0   
 4          0.25         22.6              2.68              0.51         0   
 5          0.41          1.4              9.28              2.24         0.1 
 6          1.35         68.6              8.1               0.74         0   
 7          1.32         44.6              1.47              1.64         0   
 8          0.81         21.2              3.85              2.49         0.29
 9          1.1          40                2.52              0.95         0.03
10          0.1           4.8              1.66              1.64         0   
   ACS_PCT_OTHER_RACE ACS_PCT_WHITE SAIPE_MEDIAN_HH_INCOME SAIPE_PCT_POV
                &lt;dbl&gt;         &lt;dbl&gt;                  &lt;dbl&gt;         &lt;dbl&gt;
 1               0.67          75.8                  67565          11.2
 2               1.56          85.4                  71135           8.9
 3               3.1           46.3                  38866          25.5
 4               0.04          76.6                  50907          17.8
 5               1.8           94.0                  55203          13.1
 6               3.13          26.2                  33124          30.8
 7               0.5           51.6                  42268          20.6
 8               1.64          73.3                  50259          14.5
 9               0.79          56.9                  39318          16.3
10               0.81          92.1                  50388          14.7
   ACS_PCT_COMMT_60MINUP ACS_PCT_RENTER_HU_COST_50PCT LTC_AVG_OBS_REHOSP_RATE
                   &lt;dbl&gt;                        &lt;dbl&gt;                   &lt;dbl&gt;
 1                  6.06                         26.6                    0.14
 2                  7.53                         20.8                    0.14
 3                 11.8                          22.4                    0.22
 4                 10.4                          27.4                    0.16
 5                 18.6                          22.6                    0.14
 6                 12.7                          34                      0.05
 7                  9.14                         29.5                    0.11
 8                  7.21                         20.5                    0.13
 9                  5.93                         13.0                    0.15
10                 10.2                          12.2                    0.19
# … with 2,804 more rows</code></pre>
</div>
</div>
<p>2,814 x 20 is a good place to start.</p>
<p>This next step will conver the Rural-Urban Continuum Code to a binary Rural/Urban. If the county is coded as a four (4) or higher, then they are classified as rural, non-metro, having a population of less than 250,000 as defined by USDA as “Rural.”</p>
<div class="cell">
<details>
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb22"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb22-1"><a href="#cb22-1" aria-hidden="true" tabindex="-1"></a>df_new <span class="ot">&lt;-</span> df_new <span class="sc">%&gt;%</span></span>
<span id="cb22-2"><a href="#cb22-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">Rurality =</span> <span class="fu">if_else</span>(</span>
<span id="cb22-3"><a href="#cb22-3" aria-hidden="true" tabindex="-1"></a>    AHRF_USDA_RUCC_2013 <span class="sc">&gt;=</span> <span class="dv">4</span>, <span class="st">"Rural"</span>, <span class="st">"Urban"</span>)</span>
<span id="cb22-4"><a href="#cb22-4" aria-hidden="true" tabindex="-1"></a>    )</span>
<span id="cb22-5"><a href="#cb22-5" aria-hidden="true" tabindex="-1"></a><span class="fu">head</span>(df_new)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 6 × 21
  COUNTYF…¹ STATE COUNTY AHRF_…² NOAAC…³ ACS_P…⁴ ACS_P…⁵ ACS_P…⁶ ACS_P…⁷ ACS_P…⁸
  &lt;chr&gt;     &lt;chr&gt; &lt;chr&gt;  &lt;chr&gt;     &lt;dbl&gt;   &lt;dbl&gt;   &lt;dbl&gt;   &lt;dbl&gt;   &lt;dbl&gt;   &lt;dbl&gt;
1 01001     Alab… Autau… 2          5.72    48.6    51.4    0.28    1.17   19.5 
2 01003     Alab… Baldw… 3          5.27    48.5    51.5    0.69    0.93    8.77
3 01005     Alab… Barbo… 6          5.75    52.6    47.4    0.35    0.49   47.7 
4 01007     Alab… Bibb … 1          5.61    53.7    46.3    0.05    0.25   22.6 
5 01009     Alab… Bloun… 1          5.96    49.6    50.4    0.1     0.41    1.4 
6 01011     Alab… Bullo… 6          5.40    54.8    45.2    0       1.35   68.6 
# … with 11 more variables: ACS_PCT_HISPANIC &lt;dbl&gt;, ACS_PCT_MULT_RACE &lt;dbl&gt;,
#   ACS_PCT_NHPI &lt;dbl&gt;, ACS_PCT_OTHER_RACE &lt;dbl&gt;, ACS_PCT_WHITE &lt;dbl&gt;,
#   SAIPE_MEDIAN_HH_INCOME &lt;dbl&gt;, SAIPE_PCT_POV &lt;dbl&gt;,
#   ACS_PCT_COMMT_60MINUP &lt;dbl&gt;, ACS_PCT_RENTER_HU_COST_50PCT &lt;dbl&gt;,
#   LTC_AVG_OBS_REHOSP_RATE &lt;dbl&gt;, Rurality &lt;chr&gt;, and abbreviated variable
#   names ¹​COUNTYFIPS, ²​AHRF_USDA_RUCC_2013, ³​NOAAC_PRECIPITATION_AVG_YEARLY,
#   ⁴​ACS_PCT_MALE, ⁵​ACS_PCT_FEMALE, ⁶​ACS_PCT_AIAN, ⁷​ACS_PCT_ASIAN, …</code></pre>
</div>
</div>
</section>
</section>
<section id="descriptive-statistics" class="level2">
<h2 class="anchored" data-anchor-id="descriptive-statistics">Descriptive Statistics</h2>
<p>For our preliminary analysis, we’re going to provide summary statistics analyzing the variables relevant to our research question, excluding the socio-demographic control variables, and a visualization for each.</p>
<div class="cell">
<details>
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb24"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb24-1"><a href="#cb24-1" aria-hidden="true" tabindex="-1"></a><span class="fu">kable</span>(<span class="fu">describe</span>(df_new))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output-display">
<table class="table table-sm table-striped">
<colgroup>
<col style="width: 17%">
<col style="width: 2%">
<col style="width: 2%">
<col style="width: 7%">
<col style="width: 7%">
<col style="width: 6%">
<col style="width: 7%">
<col style="width: 7%">
<col style="width: 7%">
<col style="width: 6%">
<col style="width: 7%">
<col style="width: 6%">
<col style="width: 6%">
<col style="width: 6%">
</colgroup>
<thead>
<tr class="header">
<th style="text-align: left;"></th>
<th style="text-align: right;">vars</th>
<th style="text-align: right;">n</th>
<th style="text-align: right;">mean</th>
<th style="text-align: right;">sd</th>
<th style="text-align: right;">median</th>
<th style="text-align: right;">trimmed</th>
<th style="text-align: right;">mad</th>
<th style="text-align: right;">min</th>
<th style="text-align: right;">max</th>
<th style="text-align: right;">range</th>
<th style="text-align: right;">skew</th>
<th style="text-align: right;">kurtosis</th>
<th style="text-align: right;">se</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">COUNTYFIPS*</td>
<td style="text-align: right;">1</td>
<td style="text-align: right;">2814</td>
<td style="text-align: right;">1.407500e+03</td>
<td style="text-align: right;">8.124762e+02</td>
<td style="text-align: right;">1407.50000</td>
<td style="text-align: right;">1.407500e+03</td>
<td style="text-align: right;">1043.009100</td>
<td style="text-align: right;">1.000000e+00</td>
<td style="text-align: right;">2814.000</td>
<td style="text-align: right;">2.813000e+03</td>
<td style="text-align: right;">0.0000000</td>
<td style="text-align: right;">-1.2012794</td>
<td style="text-align: right;">15.3161135</td>
</tr>
<tr class="even">
<td style="text-align: left;">STATE*</td>
<td style="text-align: right;">2</td>
<td style="text-align: right;">2814</td>
<td style="text-align: right;">2.442928e+01</td>
<td style="text-align: right;">1.359471e+01</td>
<td style="text-align: right;">23.00000</td>
<td style="text-align: right;">2.441874e+01</td>
<td style="text-align: right;">16.308600</td>
<td style="text-align: right;">1.000000e+00</td>
<td style="text-align: right;">48.000</td>
<td style="text-align: right;">4.700000e+01</td>
<td style="text-align: right;">0.0584273</td>
<td style="text-align: right;">-1.2662366</td>
<td style="text-align: right;">0.2562759</td>
</tr>
<tr class="odd">
<td style="text-align: left;">COUNTY*</td>
<td style="text-align: right;">3</td>
<td style="text-align: right;">2814</td>
<td style="text-align: right;">8.369058e+02</td>
<td style="text-align: right;">4.694846e+02</td>
<td style="text-align: right;">831.50000</td>
<td style="text-align: right;">8.339405e+02</td>
<td style="text-align: right;">584.885700</td>
<td style="text-align: right;">1.000000e+00</td>
<td style="text-align: right;">1674.000</td>
<td style="text-align: right;">1.673000e+03</td>
<td style="text-align: right;">0.0526568</td>
<td style="text-align: right;">-1.1127220</td>
<td style="text-align: right;">8.8503264</td>
</tr>
<tr class="even">
<td style="text-align: left;">AHRF_USDA_RUCC_2013*</td>
<td style="text-align: right;">4</td>
<td style="text-align: right;">2814</td>
<td style="text-align: right;">4.772210e+00</td>
<td style="text-align: right;">2.619826e+00</td>
<td style="text-align: right;">6.00000</td>
<td style="text-align: right;">4.717140e+00</td>
<td style="text-align: right;">2.965200</td>
<td style="text-align: right;">1.000000e+00</td>
<td style="text-align: right;">9.000</td>
<td style="text-align: right;">8.000000e+00</td>
<td style="text-align: right;">0.0039932</td>
<td style="text-align: right;">-1.2985960</td>
<td style="text-align: right;">0.0493867</td>
</tr>
<tr class="odd">
<td style="text-align: left;">NOAAC_PRECIPITATION_AVG_YEARLY</td>
<td style="text-align: right;">5</td>
<td style="text-align: right;">2814</td>
<td style="text-align: right;">3.611196e+00</td>
<td style="text-align: right;">1.628908e+00</td>
<td style="text-align: right;">3.62375</td>
<td style="text-align: right;">3.638924e+00</td>
<td style="text-align: right;">1.887844</td>
<td style="text-align: right;">2.241667e-01</td>
<td style="text-align: right;">9.745</td>
<td style="text-align: right;">9.520833e+00</td>
<td style="text-align: right;">-0.0899446</td>
<td style="text-align: right;">-0.7490480</td>
<td style="text-align: right;">0.0307068</td>
</tr>
<tr class="even">
<td style="text-align: left;">ACS_PCT_MALE</td>
<td style="text-align: right;">6</td>
<td style="text-align: right;">2814</td>
<td style="text-align: right;">4.994695e+01</td>
<td style="text-align: right;">2.242017e+00</td>
<td style="text-align: right;">49.57000</td>
<td style="text-align: right;">4.966734e+01</td>
<td style="text-align: right;">1.171254</td>
<td style="text-align: right;">4.319000e+01</td>
<td style="text-align: right;">69.540</td>
<td style="text-align: right;">2.635000e+01</td>
<td style="text-align: right;">2.8174177</td>
<td style="text-align: right;">14.3096504</td>
<td style="text-align: right;">0.0422646</td>
</tr>
<tr class="odd">
<td style="text-align: left;">ACS_PCT_FEMALE</td>
<td style="text-align: right;">7</td>
<td style="text-align: right;">2814</td>
<td style="text-align: right;">5.005306e+01</td>
<td style="text-align: right;">2.242020e+00</td>
<td style="text-align: right;">50.43000</td>
<td style="text-align: right;">5.033267e+01</td>
<td style="text-align: right;">1.171254</td>
<td style="text-align: right;">3.046000e+01</td>
<td style="text-align: right;">56.810</td>
<td style="text-align: right;">2.635000e+01</td>
<td style="text-align: right;">-2.8174100</td>
<td style="text-align: right;">14.3095899</td>
<td style="text-align: right;">0.0422647</td>
</tr>
<tr class="even">
<td style="text-align: left;">ACS_PCT_AIAN</td>
<td style="text-align: right;">8</td>
<td style="text-align: right;">2814</td>
<td style="text-align: right;">1.396734e+00</td>
<td style="text-align: right;">5.115499e+00</td>
<td style="text-align: right;">0.32000</td>
<td style="text-align: right;">4.677753e-01</td>
<td style="text-align: right;">0.326172</td>
<td style="text-align: right;">0.000000e+00</td>
<td style="text-align: right;">76.740</td>
<td style="text-align: right;">7.674000e+01</td>
<td style="text-align: right;">9.0423583</td>
<td style="text-align: right;">99.6407741</td>
<td style="text-align: right;">0.0964331</td>
</tr>
<tr class="odd">
<td style="text-align: left;">ACS_PCT_ASIAN</td>
<td style="text-align: right;">9</td>
<td style="text-align: right;">2814</td>
<td style="text-align: right;">1.394538e+00</td>
<td style="text-align: right;">2.540860e+00</td>
<td style="text-align: right;">0.66000</td>
<td style="text-align: right;">8.754218e-01</td>
<td style="text-align: right;">0.652344</td>
<td style="text-align: right;">0.000000e+00</td>
<td style="text-align: right;">37.670</td>
<td style="text-align: right;">3.767000e+01</td>
<td style="text-align: right;">6.0286489</td>
<td style="text-align: right;">53.6120545</td>
<td style="text-align: right;">0.0478982</td>
</tr>
<tr class="even">
<td style="text-align: left;">ACS_PCT_BLACK</td>
<td style="text-align: right;">10</td>
<td style="text-align: right;">2814</td>
<td style="text-align: right;">9.453362e+00</td>
<td style="text-align: right;">1.460088e+01</td>
<td style="text-align: right;">2.63000</td>
<td style="text-align: right;">6.009964e+00</td>
<td style="text-align: right;">3.350676</td>
<td style="text-align: right;">0.000000e+00</td>
<td style="text-align: right;">87.790</td>
<td style="text-align: right;">8.779000e+01</td>
<td style="text-align: right;">2.2444231</td>
<td style="text-align: right;">5.0398860</td>
<td style="text-align: right;">0.2752434</td>
</tr>
<tr class="odd">
<td style="text-align: left;">ACS_PCT_HISPANIC</td>
<td style="text-align: right;">11</td>
<td style="text-align: right;">2814</td>
<td style="text-align: right;">9.176947e+00</td>
<td style="text-align: right;">1.321884e+01</td>
<td style="text-align: right;">4.27500</td>
<td style="text-align: right;">6.063504e+00</td>
<td style="text-align: right;">3.669435</td>
<td style="text-align: right;">0.000000e+00</td>
<td style="text-align: right;">98.900</td>
<td style="text-align: right;">9.890000e+01</td>
<td style="text-align: right;">3.1611507</td>
<td style="text-align: right;">11.8393833</td>
<td style="text-align: right;">0.2491905</td>
</tr>
<tr class="even">
<td style="text-align: left;">ACS_PCT_MULT_RACE</td>
<td style="text-align: right;">12</td>
<td style="text-align: right;">2814</td>
<td style="text-align: right;">3.413696e+00</td>
<td style="text-align: right;">2.268010e+00</td>
<td style="text-align: right;">2.85500</td>
<td style="text-align: right;">3.082020e+00</td>
<td style="text-align: right;">1.638273</td>
<td style="text-align: right;">0.000000e+00</td>
<td style="text-align: right;">18.860</td>
<td style="text-align: right;">1.886000e+01</td>
<td style="text-align: right;">1.7825475</td>
<td style="text-align: right;">4.7682557</td>
<td style="text-align: right;">0.0427546</td>
</tr>
<tr class="odd">
<td style="text-align: left;">ACS_PCT_NHPI</td>
<td style="text-align: right;">13</td>
<td style="text-align: right;">2814</td>
<td style="text-align: right;">7.894460e-02</td>
<td style="text-align: right;">1.933154e-01</td>
<td style="text-align: right;">0.02000</td>
<td style="text-align: right;">3.630110e-02</td>
<td style="text-align: right;">0.029652</td>
<td style="text-align: right;">0.000000e+00</td>
<td style="text-align: right;">3.820</td>
<td style="text-align: right;">3.820000e+00</td>
<td style="text-align: right;">7.0468064</td>
<td style="text-align: right;">84.3573375</td>
<td style="text-align: right;">0.0036442</td>
</tr>
<tr class="even">
<td style="text-align: left;">ACS_PCT_OTHER_RACE</td>
<td style="text-align: right;">14</td>
<td style="text-align: right;">2814</td>
<td style="text-align: right;">2.127616e+00</td>
<td style="text-align: right;">3.404236e+00</td>
<td style="text-align: right;">1.05000</td>
<td style="text-align: right;">1.416137e+00</td>
<td style="text-align: right;">1.156428</td>
<td style="text-align: right;">0.000000e+00</td>
<td style="text-align: right;">43.910</td>
<td style="text-align: right;">4.391000e+01</td>
<td style="text-align: right;">4.7889038</td>
<td style="text-align: right;">34.3014627</td>
<td style="text-align: right;">0.0641738</td>
</tr>
<tr class="odd">
<td style="text-align: left;">ACS_PCT_WHITE</td>
<td style="text-align: right;">15</td>
<td style="text-align: right;">2814</td>
<td style="text-align: right;">8.213514e+01</td>
<td style="text-align: right;">1.606041e+01</td>
<td style="text-align: right;">88.06500</td>
<td style="text-align: right;">8.489697e+01</td>
<td style="text-align: right;">11.052783</td>
<td style="text-align: right;">1.114000e+01</td>
<td style="text-align: right;">99.150</td>
<td style="text-align: right;">8.801000e+01</td>
<td style="text-align: right;">-1.5233572</td>
<td style="text-align: right;">2.1283704</td>
<td style="text-align: right;">0.3027572</td>
</tr>
<tr class="even">
<td style="text-align: left;">SAIPE_MEDIAN_HH_INCOME</td>
<td style="text-align: right;">16</td>
<td style="text-align: right;">2814</td>
<td style="text-align: right;">5.738628e+04</td>
<td style="text-align: right;">1.442985e+04</td>
<td style="text-align: right;">55107.00000</td>
<td style="text-align: right;">5.584910e+04</td>
<td style="text-align: right;">11735.520300</td>
<td style="text-align: right;">2.599700e+04</td>
<td style="text-align: right;">155362.000</td>
<td style="text-align: right;">1.293650e+05</td>
<td style="text-align: right;">1.4172637</td>
<td style="text-align: right;">3.6789671</td>
<td style="text-align: right;">272.0193680</td>
</tr>
<tr class="odd">
<td style="text-align: left;">SAIPE_PCT_POV</td>
<td style="text-align: right;">17</td>
<td style="text-align: right;">2814</td>
<td style="text-align: right;">1.371606e+01</td>
<td style="text-align: right;">5.320367e+00</td>
<td style="text-align: right;">12.80000</td>
<td style="text-align: right;">1.323637e+01</td>
<td style="text-align: right;">4.744320</td>
<td style="text-align: right;">3.000000e+00</td>
<td style="text-align: right;">39.600</td>
<td style="text-align: right;">3.660000e+01</td>
<td style="text-align: right;">1.0397109</td>
<td style="text-align: right;">1.6688697</td>
<td style="text-align: right;">0.1002951</td>
</tr>
<tr class="even">
<td style="text-align: left;">ACS_PCT_COMMT_60MINUP</td>
<td style="text-align: right;">18</td>
<td style="text-align: right;">2814</td>
<td style="text-align: right;">8.155924e+00</td>
<td style="text-align: right;">4.864799e+00</td>
<td style="text-align: right;">6.85500</td>
<td style="text-align: right;">7.487016e+00</td>
<td style="text-align: right;">3.810282</td>
<td style="text-align: right;">0.000000e+00</td>
<td style="text-align: right;">35.910</td>
<td style="text-align: right;">3.591000e+01</td>
<td style="text-align: right;">1.5015546</td>
<td style="text-align: right;">3.0016425</td>
<td style="text-align: right;">0.0917071</td>
</tr>
<tr class="odd">
<td style="text-align: left;">ACS_PCT_RENTER_HU_COST_50PCT</td>
<td style="text-align: right;">19</td>
<td style="text-align: right;">2814</td>
<td style="text-align: right;">2.060974e+01</td>
<td style="text-align: right;">6.649144e+00</td>
<td style="text-align: right;">20.78000</td>
<td style="text-align: right;">2.057608e+01</td>
<td style="text-align: right;">6.093486</td>
<td style="text-align: right;">0.000000e+00</td>
<td style="text-align: right;">49.260</td>
<td style="text-align: right;">4.926000e+01</td>
<td style="text-align: right;">0.1136840</td>
<td style="text-align: right;">0.5492796</td>
<td style="text-align: right;">0.1253440</td>
</tr>
<tr class="even">
<td style="text-align: left;">LTC_AVG_OBS_REHOSP_RATE</td>
<td style="text-align: right;">20</td>
<td style="text-align: right;">2814</td>
<td style="text-align: right;">1.449645e-01</td>
<td style="text-align: right;">8.432610e-02</td>
<td style="text-align: right;">0.14000</td>
<td style="text-align: right;">1.422425e-01</td>
<td style="text-align: right;">0.059304</td>
<td style="text-align: right;">0.000000e+00</td>
<td style="text-align: right;">1.000</td>
<td style="text-align: right;">1.000000e+00</td>
<td style="text-align: right;">1.6404370</td>
<td style="text-align: right;">12.5443704</td>
<td style="text-align: right;">0.0015896</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Rurality*</td>
<td style="text-align: right;">21</td>
<td style="text-align: right;">2814</td>
<td style="text-align: right;">1.393390e+00</td>
<td style="text-align: right;">4.885890e-01</td>
<td style="text-align: right;">1.00000</td>
<td style="text-align: right;">1.366785e+00</td>
<td style="text-align: right;">0.000000</td>
<td style="text-align: right;">1.000000e+00</td>
<td style="text-align: right;">2.000</td>
<td style="text-align: right;">1.000000e+00</td>
<td style="text-align: right;">0.4362437</td>
<td style="text-align: right;">-1.8103344</td>
<td style="text-align: right;">0.0092105</td>
</tr>
</tbody>
</table>
</div>
</div>
<p>Following this, we’re going to stratify each variable by rurality and determine either the difference in distribution (histogram) and/or central tendency (boxplot).</p>
<section id="average-yearly-precipitation" class="level3">
<h3 class="anchored" data-anchor-id="average-yearly-precipitation">Average Yearly Precipitation</h3>
<div class="cell">
<details>
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb25"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb25-1"><a href="#cb25-1" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(df_new, <span class="fu">aes</span>(<span class="at">x =</span> NOAAC_PRECIPITATION_AVG_YEARLY,</span>
<span id="cb25-2"><a href="#cb25-2" aria-hidden="true" tabindex="-1"></a>                   <span class="at">fill =</span> Rurality)) <span class="sc">+</span></span>
<span id="cb25-3"><a href="#cb25-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">scale_fill_manual</span>(<span class="at">values =</span> umass_colors) <span class="sc">+</span></span>
<span id="cb25-4"><a href="#cb25-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_histogram</span>() <span class="sc">+</span></span>
<span id="cb25-5"><a href="#cb25-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">xlab</span>(<span class="st">"Average Annual Precipitation"</span>) <span class="sc">+</span></span>
<span id="cb25-6"><a href="#cb25-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ylab</span>(<span class="st">"Count"</span>) <span class="sc">+</span></span>
<span id="cb25-7"><a href="#cb25-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_bw</span>()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stderr">
<pre><code>`stat_bin()` using `bins = 30`. Pick better value with `binwidth`.</code></pre>
</div>
<div class="cell-output-display">
<p><img src="FinalPart3_CalebHill_files/figure-html/unnamed-chunk-9-1.png" class="img-fluid" width="672"></p>
</div>
<details>
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb27"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb27-1"><a href="#cb27-1" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(df_new, <span class="fu">aes</span>(<span class="at">x =</span> NOAAC_PRECIPITATION_AVG_YEARLY,</span>
<span id="cb27-2"><a href="#cb27-2" aria-hidden="true" tabindex="-1"></a>                   <span class="at">fill =</span> Rurality)) <span class="sc">+</span></span>
<span id="cb27-3"><a href="#cb27-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">scale_fill_manual</span>(<span class="at">values =</span> umass_colors) <span class="sc">+</span></span>
<span id="cb27-4"><a href="#cb27-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_boxplot</span>() <span class="sc">+</span></span>
<span id="cb27-5"><a href="#cb27-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">xlab</span>(<span class="st">"Average Annual Precipitation"</span>) <span class="sc">+</span></span>
<span id="cb27-6"><a href="#cb27-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ylab</span>(<span class="st">"Count"</span>) <span class="sc">+</span></span>
<span id="cb27-7"><a href="#cb27-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_bw</span>()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output-display">
<p><img src="FinalPart3_CalebHill_files/figure-html/unnamed-chunk-9-2.png" class="img-fluid" width="672"></p>
</div>
</div>
<p>Average precipitation each month is fairly uniform, with the mean at 3.49 inches of rain, on average, each month. The mean does differ from Urban to Rural, with Rural counties being drier than their Urban counterparts, but not by much. This variable will most likely provide less variation in the analysis compared to others.</p>
</section>
<section id="median-household-income" class="level3">
<h3 class="anchored" data-anchor-id="median-household-income">Median Household Income</h3>
<div class="cell">
<details>
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb28"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb28-1"><a href="#cb28-1" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(df_new, <span class="fu">aes</span>(<span class="at">x =</span> SAIPE_MEDIAN_HH_INCOME,</span>
<span id="cb28-2"><a href="#cb28-2" aria-hidden="true" tabindex="-1"></a>                   <span class="at">fill =</span> Rurality)) <span class="sc">+</span></span>
<span id="cb28-3"><a href="#cb28-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">scale_fill_manual</span>(<span class="at">values =</span> umass_colors) <span class="sc">+</span></span>
<span id="cb28-4"><a href="#cb28-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_histogram</span>() <span class="sc">+</span></span>
<span id="cb28-5"><a href="#cb28-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">xlab</span>(<span class="st">"Median Household Income"</span>) <span class="sc">+</span></span>
<span id="cb28-6"><a href="#cb28-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ylab</span>(<span class="st">"Count"</span>) <span class="sc">+</span></span>
<span id="cb28-7"><a href="#cb28-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_bw</span>()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stderr">
<pre><code>`stat_bin()` using `bins = 30`. Pick better value with `binwidth`.</code></pre>
</div>
<div class="cell-output-display">
<p><img src="FinalPart3_CalebHill_files/figure-html/unnamed-chunk-10-1.png" class="img-fluid" width="672"></p>
</div>
<details>
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb30"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb30-1"><a href="#cb30-1" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(df_new, <span class="fu">aes</span>(<span class="at">x =</span> SAIPE_MEDIAN_HH_INCOME,</span>
<span id="cb30-2"><a href="#cb30-2" aria-hidden="true" tabindex="-1"></a>                   <span class="at">fill =</span> Rurality)) <span class="sc">+</span></span>
<span id="cb30-3"><a href="#cb30-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">scale_fill_manual</span>(<span class="at">values =</span> umass_colors) <span class="sc">+</span></span>
<span id="cb30-4"><a href="#cb30-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_boxplot</span>() <span class="sc">+</span></span>
<span id="cb30-5"><a href="#cb30-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">xlab</span>(<span class="st">"Median Household Income"</span>) <span class="sc">+</span></span>
<span id="cb30-6"><a href="#cb30-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ylab</span>(<span class="st">"Count"</span>) <span class="sc">+</span></span>
<span id="cb30-7"><a href="#cb30-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_bw</span>()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output-display">
<p><img src="FinalPart3_CalebHill_files/figure-html/unnamed-chunk-10-2.png" class="img-fluid" width="672"></p>
</div>
</div>
<p>Very close to a normal distribution, if barely left-skewed. A couple of high out-liers, hovering around $90,000+ in median household income, but the mean holds at $57,465.</p>
<p>Rural Counties have substantially lower median household income, by roughly $10,ooo to $20,000. Urban counties also make up the bulk of out-liers.</p>
</section>
<section id="percent-in-poverty" class="level3">
<h3 class="anchored" data-anchor-id="percent-in-poverty">Percent in Poverty</h3>
<div class="cell">
<details>
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb31"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb31-1"><a href="#cb31-1" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(df_new, <span class="fu">aes</span>(<span class="at">x =</span> SAIPE_PCT_POV,</span>
<span id="cb31-2"><a href="#cb31-2" aria-hidden="true" tabindex="-1"></a>                     <span class="at">fill =</span> Rurality)) <span class="sc">+</span></span>
<span id="cb31-3"><a href="#cb31-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_histogram</span>() <span class="sc">+</span></span>
<span id="cb31-4"><a href="#cb31-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">xlab</span>(<span class="st">"Percent Poverty"</span>) <span class="sc">+</span></span>
<span id="cb31-5"><a href="#cb31-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ylab</span>(<span class="st">"Count"</span>) <span class="sc">+</span></span>
<span id="cb31-6"><a href="#cb31-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">scale_fill_manual</span>(<span class="at">values =</span> umass_colors) <span class="sc">+</span></span>
<span id="cb31-7"><a href="#cb31-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_bw</span>()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stderr">
<pre><code>`stat_bin()` using `bins = 30`. Pick better value with `binwidth`.</code></pre>
</div>
<div class="cell-output-display">
<p><img src="FinalPart3_CalebHill_files/figure-html/unnamed-chunk-11-1.png" class="img-fluid" width="672"></p>
</div>
<details>
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb33"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb33-1"><a href="#cb33-1" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(df_new, <span class="fu">aes</span>(<span class="at">x =</span> SAIPE_PCT_POV,</span>
<span id="cb33-2"><a href="#cb33-2" aria-hidden="true" tabindex="-1"></a>                   <span class="at">fill =</span> Rurality)) <span class="sc">+</span></span>
<span id="cb33-3"><a href="#cb33-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">scale_fill_manual</span>(<span class="at">values =</span> umass_colors) <span class="sc">+</span></span>
<span id="cb33-4"><a href="#cb33-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_boxplot</span>() <span class="sc">+</span></span>
<span id="cb33-5"><a href="#cb33-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">xlab</span>(<span class="st">"Percent Poverty"</span>) <span class="sc">+</span></span>
<span id="cb33-6"><a href="#cb33-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ylab</span>(<span class="st">"Count"</span>) <span class="sc">+</span></span>
<span id="cb33-7"><a href="#cb33-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_bw</span>()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output-display">
<p><img src="FinalPart3_CalebHill_files/figure-html/unnamed-chunk-11-2.png" class="img-fluid" width="672"></p>
</div>
</div>
<p>Another close to normal distribution. Most counties have poverty rates ranging from 10% to 20%. There are of course out-liers, especially a good number below 10%, but those are rare.</p>
<p>Urbanized counties have substantially less percentage poverty compared to their rural counterparts, and rural counties make up the bulk of outliers post-30%. Only one Urban county has a poverty rate higher than 30%.</p>
</section>
<section id="percent-commuting-alone-over-60-minutes" class="level3">
<h3 class="anchored" data-anchor-id="percent-commuting-alone-over-60-minutes">Percent Commuting Alone, Over 60 Minutes</h3>
<div class="cell">
<details>
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb34"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb34-1"><a href="#cb34-1" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(df_new, <span class="fu">aes</span>(<span class="at">x =</span> ACS_PCT_COMMT_60MINUP,</span>
<span id="cb34-2"><a href="#cb34-2" aria-hidden="true" tabindex="-1"></a>                     <span class="at">fill =</span> Rurality)) <span class="sc">+</span></span>
<span id="cb34-3"><a href="#cb34-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_histogram</span>() <span class="sc">+</span></span>
<span id="cb34-4"><a href="#cb34-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">xlab</span>(<span class="st">"Percent Commuting Alone, Over 60 Minutes"</span>) <span class="sc">+</span></span>
<span id="cb34-5"><a href="#cb34-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ylab</span>(<span class="st">"Count"</span>) <span class="sc">+</span></span>
<span id="cb34-6"><a href="#cb34-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">scale_fill_manual</span>(<span class="at">values =</span> umass_colors) <span class="sc">+</span></span>
<span id="cb34-7"><a href="#cb34-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_bw</span>()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stderr">
<pre><code>`stat_bin()` using `bins = 30`. Pick better value with `binwidth`.</code></pre>
</div>
<div class="cell-output-display">
<p><img src="FinalPart3_CalebHill_files/figure-html/unnamed-chunk-12-1.png" class="img-fluid" width="672"></p>
</div>
<details>
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb36"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb36-1"><a href="#cb36-1" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(df_new, <span class="fu">aes</span>(<span class="at">x =</span> ACS_PCT_COMMT_60MINUP,</span>
<span id="cb36-2"><a href="#cb36-2" aria-hidden="true" tabindex="-1"></a>                   <span class="at">fill =</span> Rurality)) <span class="sc">+</span></span>
<span id="cb36-3"><a href="#cb36-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">scale_fill_manual</span>(<span class="at">values =</span> umass_colors) <span class="sc">+</span></span>
<span id="cb36-4"><a href="#cb36-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_boxplot</span>() <span class="sc">+</span></span>
<span id="cb36-5"><a href="#cb36-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">xlab</span>(<span class="st">"Percent Commuting Alone, Over 60 Minutes"</span>) <span class="sc">+</span></span>
<span id="cb36-6"><a href="#cb36-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ylab</span>(<span class="st">"Count"</span>) <span class="sc">+</span></span>
<span id="cb36-7"><a href="#cb36-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_bw</span>()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output-display">
<p><img src="FinalPart3_CalebHill_files/figure-html/unnamed-chunk-12-2.png" class="img-fluid" width="672"></p>
</div>
</div>
<p>The majority of counties fall below 10% of their population commuting up to and more than 60 minutes for work. Very little variation between urban and rural counties here, which is surprising considering population density would lead one to believe rural counties travel longer on average. Perhaps the inverse is correct, in that highly remote communities means commutes are more local.</p>
</section>
<section id="percent-renter-housing-costs-over-50-percent-of-income" class="level3">
<h3 class="anchored" data-anchor-id="percent-renter-housing-costs-over-50-percent-of-income">Percent Renter Housing Costs Over 50 Percent of Income</h3>
<div class="cell">
<details>
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb37"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb37-1"><a href="#cb37-1" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(df_new, <span class="fu">aes</span>(<span class="at">x =</span> ACS_PCT_RENTER_HU_COST_50PCT,</span>
<span id="cb37-2"><a href="#cb37-2" aria-hidden="true" tabindex="-1"></a>                     <span class="at">fill =</span> Rurality)) <span class="sc">+</span></span>
<span id="cb37-3"><a href="#cb37-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_histogram</span>() <span class="sc">+</span></span>
<span id="cb37-4"><a href="#cb37-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">xlab</span>(<span class="st">"Percent Renter Housing Costs Over 50 Percent of Income"</span>) <span class="sc">+</span></span>
<span id="cb37-5"><a href="#cb37-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ylab</span>(<span class="st">"Count"</span>) <span class="sc">+</span></span>
<span id="cb37-6"><a href="#cb37-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">scale_fill_manual</span>(<span class="at">values =</span> umass_colors) <span class="sc">+</span></span>
<span id="cb37-7"><a href="#cb37-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_bw</span>()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stderr">
<pre><code>`stat_bin()` using `bins = 30`. Pick better value with `binwidth`.</code></pre>
</div>
<div class="cell-output-display">
<p><img src="FinalPart3_CalebHill_files/figure-html/unnamed-chunk-13-1.png" class="img-fluid" width="672"></p>
</div>
<details>
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb39"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb39-1"><a href="#cb39-1" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(df_new, <span class="fu">aes</span>(<span class="at">x =</span> ACS_PCT_RENTER_HU_COST_50PCT,</span>
<span id="cb39-2"><a href="#cb39-2" aria-hidden="true" tabindex="-1"></a>                   <span class="at">fill =</span> Rurality)) <span class="sc">+</span></span>
<span id="cb39-3"><a href="#cb39-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">scale_fill_manual</span>(<span class="at">values =</span> umass_colors) <span class="sc">+</span></span>
<span id="cb39-4"><a href="#cb39-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_boxplot</span>() <span class="sc">+</span></span>
<span id="cb39-5"><a href="#cb39-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">xlab</span>(<span class="st">"Percent Renter Housing Costs Over 50 Percent of Income"</span>) <span class="sc">+</span></span>
<span id="cb39-6"><a href="#cb39-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ylab</span>(<span class="st">"Count"</span>) <span class="sc">+</span></span>
<span id="cb39-7"><a href="#cb39-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_bw</span>()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output-display">
<p><img src="FinalPart3_CalebHill_files/figure-html/unnamed-chunk-13-2.png" class="img-fluid" width="672"></p>
</div>
</div>
<p>This is a startling figure. On average, 20% of counties have renters where 50% or more of their income goes toward housing costs. These leaves little to no room for other expenses and drives economic instability. The data is normally distributed and barely left-skewed – but still an item to consider with further analysis.</p>
<p>Urban counties also have a higher renter housing burden on average, with rural counties having more out-liers.</p>
</section>
<section id="re-hospitalization-rate" class="level3">
<h3 class="anchored" data-anchor-id="re-hospitalization-rate">Re-hospitalization Rate</h3>
<div class="cell">
<details>
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb40"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb40-1"><a href="#cb40-1" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(df_new, <span class="fu">aes</span>(<span class="at">x =</span> LTC_AVG_OBS_REHOSP_RATE,</span>
<span id="cb40-2"><a href="#cb40-2" aria-hidden="true" tabindex="-1"></a>                   <span class="at">fill =</span> Rurality)) <span class="sc">+</span></span>
<span id="cb40-3"><a href="#cb40-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_histogram</span>() <span class="sc">+</span></span>
<span id="cb40-4"><a href="#cb40-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">xlab</span>(<span class="st">"Re-Hospitalization Rate"</span>) <span class="sc">+</span></span>
<span id="cb40-5"><a href="#cb40-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ylab</span>(<span class="st">"Count"</span>) <span class="sc">+</span></span>
<span id="cb40-6"><a href="#cb40-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">scale_fill_manual</span>(<span class="at">values =</span> umass_colors) <span class="sc">+</span></span>
<span id="cb40-7"><a href="#cb40-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_bw</span>()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stderr">
<pre><code>`stat_bin()` using `bins = 30`. Pick better value with `binwidth`.</code></pre>
</div>
<div class="cell-output-display">
<p><img src="FinalPart3_CalebHill_files/figure-html/unnamed-chunk-14-1.png" class="img-fluid" width="672"></p>
</div>
<details>
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb42"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb42-1"><a href="#cb42-1" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(df_new, <span class="fu">aes</span>(<span class="at">x =</span> LTC_AVG_OBS_REHOSP_RATE,</span>
<span id="cb42-2"><a href="#cb42-2" aria-hidden="true" tabindex="-1"></a>                   <span class="at">fill =</span> Rurality)) <span class="sc">+</span></span>
<span id="cb42-3"><a href="#cb42-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">scale_fill_manual</span>(<span class="at">values =</span> umass_colors) <span class="sc">+</span></span>
<span id="cb42-4"><a href="#cb42-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_boxplot</span>() <span class="sc">+</span></span>
<span id="cb42-5"><a href="#cb42-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">xlab</span>(<span class="st">"Re-Hospitalization Rate"</span>) <span class="sc">+</span></span>
<span id="cb42-6"><a href="#cb42-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ylab</span>(<span class="st">"Count"</span>) <span class="sc">+</span></span>
<span id="cb42-7"><a href="#cb42-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_bw</span>()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output-display">
<p><img src="FinalPart3_CalebHill_files/figure-html/unnamed-chunk-14-2.png" class="img-fluid" width="672"></p>
</div>
</div>
<p>Another right skewed variable. Lots of counties with 0.00 rates of re-hospitalization, and few, if any, above 0.50 per 100,000 people. The same can be said when comparing urban vs.&nbsp;rural, as there seems to be little variation. Rural counties do have more out-liers, as to be expected with low access to healthcare and quality healthcare services.From a health perspective, this is good news! From a research perspective, that’s going to make analysis a little trickier. However, the somewhat normal and/or bimodal distribution should be fairly easy to work with. While needing some transformation for a linear regression, we can test multiple models per each variable to determine which amendment provides the most robust inference.</p>
</section>
</section>
<section id="analysis" class="level2">
<h2 class="anchored" data-anchor-id="analysis">Analysis</h2>
<section id="hypothesis-testing" class="level3">
<h3 class="anchored" data-anchor-id="hypothesis-testing">Hypothesis Testing</h3>
<p>Remember that the hypothesis for this research report is:</p>
<ul>
<li>Precipitation has a positive impact on re-hospitalization rates within rural counties.</li>
</ul>
<p>We have fifteen (15) explanatory variables to work with, so we can run different regressions to determine what variables influence re-hospitalization rates the most – if at all – and how they interact with other variables.</p>
<p>Reminder that the fifteen (15) explanatory and control variables are broken down into three domains: the primary independent and dependent variables, socio-demographic variables, and economic variables.</p>
<p>Independent and Dependent variables:</p>
<ul>
<li><p>Average Annual Precipitation</p></li>
<li><p>Re-Hospitalization Rates</p></li>
</ul>
<p>Socio-demographic variables:</p>
<ul>
<li><p>Percent Male</p></li>
<li><p>Percent Female</p></li>
<li><p>Percent American Indian</p></li>
<li><p>Percent Asian</p></li>
<li><p>Percent Black</p></li>
<li><p>Percent Hispanic</p></li>
<li><p>Percent Multiple Races</p></li>
<li><p>Percent Other Race</p></li>
<li><p>Percent White</p></li>
</ul>
<p>Economic variables:</p>
<ul>
<li><p>Median Household Income</p></li>
<li><p>Percent Poverty</p></li>
<li><p>Percent Rental Housing Cost, over 50%</p></li>
<li><p>Percent Commuting Alone, over 60 minutes</p></li>
</ul>
<p>We will run four models to test the hypothesis. They shall examine each environmental variable’s impact on the dependent variable, re-hospitalization rates. The control variables will be the socio-demographic and economic variables, thirteen (13) in total.</p>
<p>Model 1 will take just the independent and dependent variables by themselves.</p>
<p>Model 2 will add socio-demographic variables as control.</p>
<p>Model 3 will add economic variables as control.</p>
<p>Model 4 will add both socio-demographic and economic variables as control.</p>
<div class="cell">
<details>
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb43"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb43-1"><a href="#cb43-1" aria-hidden="true" tabindex="-1"></a>df_new <span class="ot">&lt;-</span> df_new <span class="sc">%&gt;%</span></span>
<span id="cb43-2"><a href="#cb43-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">filter</span>(Rurality <span class="sc">==</span> <span class="st">"Rural"</span>) </span>
<span id="cb43-3"><a href="#cb43-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb43-4"><a href="#cb43-4" aria-hidden="true" tabindex="-1"></a>model1 <span class="ot">&lt;-</span> <span class="fu">lm</span>(LTC_AVG_OBS_REHOSP_RATE <span class="sc">~</span> </span>
<span id="cb43-5"><a href="#cb43-5" aria-hidden="true" tabindex="-1"></a>               NOAAC_PRECIPITATION_AVG_YEARLY,</span>
<span id="cb43-6"><a href="#cb43-6" aria-hidden="true" tabindex="-1"></a>             df_new)</span>
<span id="cb43-7"><a href="#cb43-7" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb43-8"><a href="#cb43-8" aria-hidden="true" tabindex="-1"></a>model2 <span class="ot">&lt;-</span> <span class="fu">lm</span>(LTC_AVG_OBS_REHOSP_RATE <span class="sc">~</span> </span>
<span id="cb43-9"><a href="#cb43-9" aria-hidden="true" tabindex="-1"></a>               NOAAC_PRECIPITATION_AVG_YEARLY <span class="sc">+</span></span>
<span id="cb43-10"><a href="#cb43-10" aria-hidden="true" tabindex="-1"></a>               ACS_PCT_MALE <span class="sc">+</span></span>
<span id="cb43-11"><a href="#cb43-11" aria-hidden="true" tabindex="-1"></a>               ACS_PCT_FEMALE <span class="sc">+</span></span>
<span id="cb43-12"><a href="#cb43-12" aria-hidden="true" tabindex="-1"></a>               ACS_PCT_AIAN <span class="sc">+</span></span>
<span id="cb43-13"><a href="#cb43-13" aria-hidden="true" tabindex="-1"></a>               ACS_PCT_ASIAN <span class="sc">+</span></span>
<span id="cb43-14"><a href="#cb43-14" aria-hidden="true" tabindex="-1"></a>               ACS_PCT_BLACK <span class="sc">+</span></span>
<span id="cb43-15"><a href="#cb43-15" aria-hidden="true" tabindex="-1"></a>               ACS_PCT_HISPANIC <span class="sc">+</span></span>
<span id="cb43-16"><a href="#cb43-16" aria-hidden="true" tabindex="-1"></a>               ACS_PCT_MULT_RACE <span class="sc">+</span></span>
<span id="cb43-17"><a href="#cb43-17" aria-hidden="true" tabindex="-1"></a>               ACS_PCT_NHPI <span class="sc">+</span></span>
<span id="cb43-18"><a href="#cb43-18" aria-hidden="true" tabindex="-1"></a>               ACS_PCT_OTHER_RACE <span class="sc">+</span></span>
<span id="cb43-19"><a href="#cb43-19" aria-hidden="true" tabindex="-1"></a>               ACS_PCT_WHITE,</span>
<span id="cb43-20"><a href="#cb43-20" aria-hidden="true" tabindex="-1"></a>             df_new)</span>
<span id="cb43-21"><a href="#cb43-21" aria-hidden="true" tabindex="-1"></a>  </span>
<span id="cb43-22"><a href="#cb43-22" aria-hidden="true" tabindex="-1"></a>model3 <span class="ot">&lt;-</span> <span class="fu">lm</span>(LTC_AVG_OBS_REHOSP_RATE <span class="sc">~</span> </span>
<span id="cb43-23"><a href="#cb43-23" aria-hidden="true" tabindex="-1"></a>               NOAAC_PRECIPITATION_AVG_YEARLY <span class="sc">+</span></span>
<span id="cb43-24"><a href="#cb43-24" aria-hidden="true" tabindex="-1"></a>               SAIPE_MEDIAN_HH_INCOME <span class="sc">+</span></span>
<span id="cb43-25"><a href="#cb43-25" aria-hidden="true" tabindex="-1"></a>               SAIPE_PCT_POV <span class="sc">+</span></span>
<span id="cb43-26"><a href="#cb43-26" aria-hidden="true" tabindex="-1"></a>               ACS_PCT_COMMT_60MINUP <span class="sc">+</span></span>
<span id="cb43-27"><a href="#cb43-27" aria-hidden="true" tabindex="-1"></a>               ACS_PCT_RENTER_HU_COST_50PCT,</span>
<span id="cb43-28"><a href="#cb43-28" aria-hidden="true" tabindex="-1"></a>             df_new)</span>
<span id="cb43-29"><a href="#cb43-29" aria-hidden="true" tabindex="-1"></a>  </span>
<span id="cb43-30"><a href="#cb43-30" aria-hidden="true" tabindex="-1"></a>model4 <span class="ot">&lt;-</span> <span class="fu">lm</span>(LTC_AVG_OBS_REHOSP_RATE <span class="sc">~</span> </span>
<span id="cb43-31"><a href="#cb43-31" aria-hidden="true" tabindex="-1"></a>               NOAAC_PRECIPITATION_AVG_YEARLY <span class="sc">+</span></span>
<span id="cb43-32"><a href="#cb43-32" aria-hidden="true" tabindex="-1"></a>               ACS_PCT_MALE <span class="sc">+</span></span>
<span id="cb43-33"><a href="#cb43-33" aria-hidden="true" tabindex="-1"></a>               ACS_PCT_FEMALE <span class="sc">+</span></span>
<span id="cb43-34"><a href="#cb43-34" aria-hidden="true" tabindex="-1"></a>               ACS_PCT_AIAN <span class="sc">+</span></span>
<span id="cb43-35"><a href="#cb43-35" aria-hidden="true" tabindex="-1"></a>               ACS_PCT_ASIAN <span class="sc">+</span></span>
<span id="cb43-36"><a href="#cb43-36" aria-hidden="true" tabindex="-1"></a>               ACS_PCT_BLACK <span class="sc">+</span></span>
<span id="cb43-37"><a href="#cb43-37" aria-hidden="true" tabindex="-1"></a>               ACS_PCT_HISPANIC <span class="sc">+</span></span>
<span id="cb43-38"><a href="#cb43-38" aria-hidden="true" tabindex="-1"></a>               ACS_PCT_MULT_RACE <span class="sc">+</span></span>
<span id="cb43-39"><a href="#cb43-39" aria-hidden="true" tabindex="-1"></a>               ACS_PCT_NHPI <span class="sc">+</span></span>
<span id="cb43-40"><a href="#cb43-40" aria-hidden="true" tabindex="-1"></a>               ACS_PCT_OTHER_RACE <span class="sc">+</span></span>
<span id="cb43-41"><a href="#cb43-41" aria-hidden="true" tabindex="-1"></a>               ACS_PCT_WHITE <span class="sc">+</span> </span>
<span id="cb43-42"><a href="#cb43-42" aria-hidden="true" tabindex="-1"></a>               SAIPE_MEDIAN_HH_INCOME <span class="sc">+</span></span>
<span id="cb43-43"><a href="#cb43-43" aria-hidden="true" tabindex="-1"></a>               SAIPE_PCT_POV <span class="sc">+</span></span>
<span id="cb43-44"><a href="#cb43-44" aria-hidden="true" tabindex="-1"></a>               ACS_PCT_COMMT_60MINUP <span class="sc">+</span></span>
<span id="cb43-45"><a href="#cb43-45" aria-hidden="true" tabindex="-1"></a>               ACS_PCT_RENTER_HU_COST_50PCT,</span>
<span id="cb43-46"><a href="#cb43-46" aria-hidden="true" tabindex="-1"></a>             df_new)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
</div>
<p>Let’s plot this regression. We will employ log transformations for re-hospitalization rates, as it is skewed.</p>
<div class="cell">
<details>
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb44"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb44-1"><a href="#cb44-1" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(df_new, <span class="fu">aes</span>(NOAAC_PRECIPITATION_AVG_YEARLY,</span>
<span id="cb44-2"><a href="#cb44-2" aria-hidden="true" tabindex="-1"></a>                   <span class="fu">log</span>(LTC_AVG_OBS_REHOSP_RATE))) <span class="sc">+</span></span>
<span id="cb44-3"><a href="#cb44-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_point</span>(<span class="at">color =</span> <span class="st">"#881c1c"</span>,</span>
<span id="cb44-4"><a href="#cb44-4" aria-hidden="true" tabindex="-1"></a>             <span class="at">alpha =</span> <span class="fl">0.3</span>) <span class="sc">+</span></span>
<span id="cb44-5"><a href="#cb44-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_smooth</span>(<span class="at">method =</span> lm,</span>
<span id="cb44-6"><a href="#cb44-6" aria-hidden="true" tabindex="-1"></a>              <span class="at">se =</span> <span class="cn">FALSE</span>,</span>
<span id="cb44-7"><a href="#cb44-7" aria-hidden="true" tabindex="-1"></a>              <span class="at">fullrange =</span> <span class="cn">TRUE</span>,</span>
<span id="cb44-8"><a href="#cb44-8" aria-hidden="true" tabindex="-1"></a>              <span class="at">color=</span> <span class="st">"#212721"</span>) <span class="sc">+</span></span>
<span id="cb44-9"><a href="#cb44-9" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">title =</span> <span class="st">"Simple Linear Regression Model, Precipitation Against Re-Hospitalization"</span>,</span>
<span id="cb44-10"><a href="#cb44-10" aria-hidden="true" tabindex="-1"></a>       <span class="at">x =</span> <span class="st">"Average Annual Precipitation"</span>,</span>
<span id="cb44-11"><a href="#cb44-11" aria-hidden="true" tabindex="-1"></a>       <span class="at">y =</span> <span class="st">"Re-Hospitalization Rates"</span>) <span class="sc">+</span></span>
<span id="cb44-12"><a href="#cb44-12" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_bw</span>()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stderr">
<pre><code>`geom_smooth()` using formula 'y ~ x'</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning: Removed 206 rows containing non-finite values (stat_smooth).</code></pre>
</div>
<div class="cell-output-display">
<p><img src="FinalPart3_CalebHill_files/figure-html/unnamed-chunk-16-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<p>We will reject the null hypothesis. While it looks like, at first glance, that there is little positive relationship, we can at least note that there is <em>some</em> positive relationship. In the next two sections, we will dig deeper into each model, examining the p-value, R-Squared value, and PRESS statistic to see what level of relationship is present.</p>
</section>
<section id="model-comparisons" class="level3">
<h3 class="anchored" data-anchor-id="model-comparisons">Model Comparisons</h3>
<p>Now we will compare the four (4) models in more depth.</p>
<div class="cell">
<details>
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb47"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb47-1"><a href="#cb47-1" aria-hidden="true" tabindex="-1"></a><span class="fu">stargazer</span>(model1,</span>
<span id="cb47-2"><a href="#cb47-2" aria-hidden="true" tabindex="-1"></a>          model2,</span>
<span id="cb47-3"><a href="#cb47-3" aria-hidden="true" tabindex="-1"></a>          model3,</span>
<span id="cb47-4"><a href="#cb47-4" aria-hidden="true" tabindex="-1"></a>          model4,</span>
<span id="cb47-5"><a href="#cb47-5" aria-hidden="true" tabindex="-1"></a>          <span class="at">type =</span> <span class="st">"pdf"</span>,</span>
<span id="cb47-6"><a href="#cb47-6" aria-hidden="true" tabindex="-1"></a>          <span class="at">title =</span> <span class="st">"Regression Results, Models 1 - 4"</span>,</span>
<span id="cb47-7"><a href="#cb47-7" aria-hidden="true" tabindex="-1"></a>          <span class="at">out =</span> <span class="st">"models.pdf"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>
% Error: 'style' must be either 'latex' (default), 'html' or 'text.'</code></pre>
</div>
<details>
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb49"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb49-1"><a href="#cb49-1" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(model1)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = LTC_AVG_OBS_REHOSP_RATE ~ NOAAC_PRECIPITATION_AVG_YEARLY, 
    data = df_new)

Residuals:
     Min       1Q   Median       3Q      Max 
-0.18242 -0.05750 -0.00742  0.04596  0.88653 

Coefficients:
                               Estimate Std. Error t value Pr(&gt;|t|)    
(Intercept)                    0.094490   0.005200   18.17   &lt;2e-16 ***
NOAAC_PRECIPITATION_AVG_YEARLY 0.013643   0.001348   10.12   &lt;2e-16 ***
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 0.09446 on 1705 degrees of freedom
Multiple R-squared:  0.05667,   Adjusted R-squared:  0.05612 
F-statistic: 102.4 on 1 and 1705 DF,  p-value: &lt; 2.2e-16</code></pre>
</div>
<details>
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb51"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb51-1"><a href="#cb51-1" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(model2)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = LTC_AVG_OBS_REHOSP_RATE ~ NOAAC_PRECIPITATION_AVG_YEARLY + 
    ACS_PCT_MALE + ACS_PCT_FEMALE + ACS_PCT_AIAN + ACS_PCT_ASIAN + 
    ACS_PCT_BLACK + ACS_PCT_HISPANIC + ACS_PCT_MULT_RACE + ACS_PCT_NHPI + 
    ACS_PCT_OTHER_RACE + ACS_PCT_WHITE, data = df_new)

Residuals:
     Min       1Q   Median       3Q      Max 
-0.19955 -0.05549 -0.00717  0.04516  0.86871 

Coefficients:
                                 Estimate Std. Error t value Pr(&gt;|t|)    
(Intercept)                    -6.269e+02  9.443e+02  -0.664  0.50686    
NOAAC_PRECIPITATION_AVG_YEARLY  1.336e-02  1.692e-03   7.893 5.27e-15 ***
ACS_PCT_MALE                    6.475e+00  9.448e+00   0.685  0.49324    
ACS_PCT_FEMALE                  6.476e+00  9.448e+00   0.685  0.49315    
ACS_PCT_AIAN                   -2.056e-01  3.140e-01  -0.655  0.51259    
ACS_PCT_ASIAN                  -2.062e-01  3.138e-01  -0.657  0.51126    
ACS_PCT_BLACK                  -2.056e-01  3.139e-01  -0.655  0.51254    
ACS_PCT_HISPANIC                7.863e-04  2.594e-04   3.031  0.00247 ** 
ACS_PCT_MULT_RACE              -2.057e-01  3.140e-01  -0.655  0.51244    
ACS_PCT_NHPI                   -2.157e-01  3.143e-01  -0.686  0.49253    
ACS_PCT_OTHER_RACE             -2.087e-01  3.140e-01  -0.665  0.50627    
ACS_PCT_WHITE                  -2.059e-01  3.139e-01  -0.656  0.51195    
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 0.09415 on 1695 degrees of freedom
Multiple R-squared:  0.06839,   Adjusted R-squared:  0.06234 
F-statistic: 11.31 on 11 and 1695 DF,  p-value: &lt; 2.2e-16</code></pre>
</div>
<details>
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb53"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb53-1"><a href="#cb53-1" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(model3)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = LTC_AVG_OBS_REHOSP_RATE ~ NOAAC_PRECIPITATION_AVG_YEARLY + 
    SAIPE_MEDIAN_HH_INCOME + SAIPE_PCT_POV + ACS_PCT_COMMT_60MINUP + 
    ACS_PCT_RENTER_HU_COST_50PCT, data = df_new)

Residuals:
     Min       1Q   Median       3Q      Max 
-0.24663 -0.05770 -0.00557  0.04577  0.86249 

Coefficients:
                                 Estimate Std. Error t value Pr(&gt;|t|)    
(Intercept)                     7.230e-02  3.187e-02   2.269  0.02342 *  
NOAAC_PRECIPITATION_AVG_YEARLY  1.045e-02  1.600e-03   6.531 8.62e-11 ***
SAIPE_MEDIAN_HH_INCOME         -5.292e-08  4.180e-07  -0.127  0.89929    
SAIPE_PCT_POV                   2.220e-03  7.671e-04   2.895  0.00384 ** 
ACS_PCT_COMMT_60MINUP          -1.130e-03  5.499e-04  -2.056  0.03996 *  
ACS_PCT_RENTER_HU_COST_50PCT    6.144e-04  3.443e-04   1.784  0.07456 .  
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 0.09366 on 1701 degrees of freedom
Multiple R-squared:  0.07482,   Adjusted R-squared:  0.0721 
F-statistic: 27.51 on 5 and 1701 DF,  p-value: &lt; 2.2e-16</code></pre>
</div>
<details>
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb55"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb55-1"><a href="#cb55-1" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(model4)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = LTC_AVG_OBS_REHOSP_RATE ~ NOAAC_PRECIPITATION_AVG_YEARLY + 
    ACS_PCT_MALE + ACS_PCT_FEMALE + ACS_PCT_AIAN + ACS_PCT_ASIAN + 
    ACS_PCT_BLACK + ACS_PCT_HISPANIC + ACS_PCT_MULT_RACE + ACS_PCT_NHPI + 
    ACS_PCT_OTHER_RACE + ACS_PCT_WHITE + SAIPE_MEDIAN_HH_INCOME + 
    SAIPE_PCT_POV + ACS_PCT_COMMT_60MINUP + ACS_PCT_RENTER_HU_COST_50PCT, 
    data = df_new)

Residuals:
     Min       1Q   Median       3Q      Max 
-0.23229 -0.05497 -0.00634  0.04535  0.87521 

Coefficients:
                                 Estimate Std. Error t value Pr(&gt;|t|)    
(Intercept)                    -6.595e+02  9.379e+02  -0.703 0.482070    
NOAAC_PRECIPITATION_AVG_YEARLY  1.051e-02  1.923e-03   5.466  5.3e-08 ***
ACS_PCT_MALE                    6.871e+00  9.384e+00   0.732 0.464161    
ACS_PCT_FEMALE                  6.873e+00  9.384e+00   0.732 0.464015    
ACS_PCT_AIAN                   -2.773e-01  3.125e-01  -0.888 0.374901    
ACS_PCT_ASIAN                  -2.771e-01  3.123e-01  -0.887 0.375049    
ACS_PCT_BLACK                  -2.772e-01  3.124e-01  -0.887 0.375121    
ACS_PCT_HISPANIC                4.957e-04  2.666e-04   1.859 0.063214 .  
ACS_PCT_MULT_RACE              -2.770e-01  3.125e-01  -0.886 0.375500    
ACS_PCT_NHPI                   -2.857e-01  3.128e-01  -0.913 0.361214    
ACS_PCT_OTHER_RACE             -2.792e-01  3.124e-01  -0.894 0.371696    
ACS_PCT_WHITE                  -2.769e-01  3.124e-01  -0.886 0.375604    
SAIPE_MEDIAN_HH_INCOME          2.885e-07  4.462e-07   0.646 0.518089    
SAIPE_PCT_POV                   3.312e-03  9.805e-04   3.378 0.000747 ***
ACS_PCT_COMMT_60MINUP          -1.156e-03  5.607e-04  -2.062 0.039362 *  
ACS_PCT_RENTER_HU_COST_50PCT    5.089e-04  3.520e-04   1.446 0.148414    
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 0.09347 on 1691 degrees of freedom
Multiple R-squared:  0.08393,   Adjusted R-squared:  0.07581 
F-statistic: 10.33 on 15 and 1691 DF,  p-value: &lt; 2.2e-16</code></pre>
</div>
</div>
<p>We want to look for two items in particular: 1) P-values that reach significant code of *** and 2) The highest Adjusted R-squared value.</p>
<p>Model 1’s <code>Precipitation</code> variable has the highest P-value compared to the other models, and the lowest Adjusted R-squared value.</p>
<p>Model 2’s significant variables are <code>Precipitation</code> and <code>Hispanic Rate.</code> However, the <code>Hispanic Rate</code> does not meet the significant code of ***. The Adjusted R-squared value is only slightly higher than Model 1.</p>
<p>Model 3’s significant variables are <code>Precipitation,</code> <code>Percent Poverty,</code> and <code>Commuting.</code> However, neither <code>Percent Poverty</code> nor <code>Commuting</code> meet ***. The Adjusted R-squared value is close to Model 4, so it appears that the economic variables have a higher impact over socio-demographic measures.</p>
<p>Model 4’s significant variables are <code>Precipitation,</code> <code>Percent Poverty,</code> and <code>Commuting.</code> <code>Precipitation</code> has the lowest P-value of the four models here, and <code>Percent Poverty</code> meets the significance threshold of ***. The Adjusted R-squared value is the highest here, though only at 0.076.</p>
<p>Finally, we’re going to calculate the PRESS statistic (Predicted Residual Sum of Squares) to best determine which model can predict the response variable based upon the explanatory variables.</p>
<div class="cell">
<details>
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb57"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb57-1"><a href="#cb57-1" aria-hidden="true" tabindex="-1"></a>PRESS <span class="ot">&lt;-</span> <span class="cf">function</span>(model) {</span>
<span id="cb57-2"><a href="#cb57-2" aria-hidden="true" tabindex="-1"></a>  i <span class="ot">&lt;-</span> <span class="fu">residuals</span>(model)<span class="sc">/</span>(<span class="dv">1</span> <span class="sc">-</span> <span class="fu">lm.influence</span>(model)<span class="sc">$</span>hat)</span>
<span id="cb57-3"><a href="#cb57-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">sum</span>(i<span class="sc">^</span><span class="dv">2</span>)</span>
<span id="cb57-4"><a href="#cb57-4" aria-hidden="true" tabindex="-1"></a>}</span>
<span id="cb57-5"><a href="#cb57-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb57-6"><a href="#cb57-6" aria-hidden="true" tabindex="-1"></a><span class="fu">PRESS</span>(model1)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 15.25297</code></pre>
</div>
<details>
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb59"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb59-1"><a href="#cb59-1" aria-hidden="true" tabindex="-1"></a><span class="fu">PRESS</span>(model2)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>[1] Inf</code></pre>
</div>
<details>
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb61"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb61-1"><a href="#cb61-1" aria-hidden="true" tabindex="-1"></a><span class="fu">PRESS</span>(model3)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 15.05951</code></pre>
</div>
<details>
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb63"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb63-1"><a href="#cb63-1" aria-hidden="true" tabindex="-1"></a><span class="fu">PRESS</span>(model4)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>[1] Inf</code></pre>
</div>
</div>
<p>Model 3 has the lowest PRESS score, though Model 4 is not being calculated for some reason. This is probably due to an error with a socio-demographic variable.</p>
<p>Due to a strong p-value, Adjusted R-squared value, and model fit compared to the other three models, Model 4 will be chosen as the final model for the diagnostic exploration.</p>
</section>
<section id="diagnostics" class="level3">
<h3 class="anchored" data-anchor-id="diagnostics">Diagnostics</h3>
<p>Finally, we’ll plot the diagnostics to best understand the model.</p>
<div class="cell">
<details>
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb65"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb65-1"><a href="#cb65-1" aria-hidden="true" tabindex="-1"></a><span class="fu">par</span>(<span class="at">mfrow =</span> <span class="fu">c</span>(<span class="dv">2</span>,<span class="dv">3</span>));</span>
<span id="cb65-2"><a href="#cb65-2" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(model4, </span>
<span id="cb65-3"><a href="#cb65-3" aria-hidden="true" tabindex="-1"></a>     <span class="at">which =</span> <span class="dv">1</span><span class="sc">:</span><span class="dv">6</span>) <span class="sc">+</span></span>
<span id="cb65-4"><a href="#cb65-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_bw</span>()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stderr">
<pre><code>Warning: not plotting observations with leverage one:
  44

Warning: not plotting observations with leverage one:
  44</code></pre>
</div>
<div class="cell-output-display">
<p><img src="FinalPart3_CalebHill_files/figure-html/unnamed-chunk-19-1.png" class="img-fluid" width="672"></p>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>NULL</code></pre>
</div>
<details>
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb68"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb68-1"><a href="#cb68-1" aria-hidden="true" tabindex="-1"></a><span class="fu">ggsave</span>(<span class="st">"diagnostics.pdf"</span>,</span>
<span id="cb68-2"><a href="#cb68-2" aria-hidden="true" tabindex="-1"></a>       <span class="at">device =</span> <span class="st">"pdf"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stderr">
<pre><code>Saving 7 x 5 in image</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>`geom_smooth()` using formula 'y ~ x'</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning: Removed 206 rows containing non-finite values (stat_smooth).</code></pre>
</div>
</div>
<p>Of the six plots, Cook’s distance is the most striking and relevant, as there are three out-liers: 683, 1345, and 1508.</p>
<div class="cell">
<details>
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb72"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb72-1"><a href="#cb72-1" aria-hidden="true" tabindex="-1"></a>df_new <span class="sc">%&gt;%</span></span>
<span id="cb72-2"><a href="#cb72-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">filter</span>(COUNTYFIPS <span class="sc">==</span> <span class="st">"26097"</span> <span class="sc">|</span> COUNTYFIPS <span class="sc">==</span> <span class="st">"46079"</span> <span class="sc">|</span> COUNTYFIPS <span class="sc">==</span> <span class="st">"48385"</span>) <span class="sc">%&gt;%</span></span>
<span id="cb72-3"><a href="#cb72-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">head</span>()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 3 × 21
  COUNTYF…¹ STATE COUNTY AHRF_…² NOAAC…³ ACS_P…⁴ ACS_P…⁵ ACS_P…⁶ ACS_P…⁷ ACS_P…⁸
  &lt;chr&gt;     &lt;chr&gt; &lt;chr&gt;  &lt;chr&gt;     &lt;dbl&gt;   &lt;dbl&gt;   &lt;dbl&gt;   &lt;dbl&gt;   &lt;dbl&gt;   &lt;dbl&gt;
1 26097     Mich… Macki… 7          3.13    51.2    48.8   16.4     0.73    3.46
2 46079     Sout… Lake … 6          1.46    52.0    48.0    2.12    0.05    0.39
3 48385     Texas Real … 9          1.81    44.9    55.1    0       0.06    1.17
# … with 11 more variables: ACS_PCT_HISPANIC &lt;dbl&gt;, ACS_PCT_MULT_RACE &lt;dbl&gt;,
#   ACS_PCT_NHPI &lt;dbl&gt;, ACS_PCT_OTHER_RACE &lt;dbl&gt;, ACS_PCT_WHITE &lt;dbl&gt;,
#   SAIPE_MEDIAN_HH_INCOME &lt;dbl&gt;, SAIPE_PCT_POV &lt;dbl&gt;,
#   ACS_PCT_COMMT_60MINUP &lt;dbl&gt;, ACS_PCT_RENTER_HU_COST_50PCT &lt;dbl&gt;,
#   LTC_AVG_OBS_REHOSP_RATE &lt;dbl&gt;, Rurality &lt;chr&gt;, and abbreviated variable
#   names ¹​COUNTYFIPS, ²​AHRF_USDA_RUCC_2013, ³​NOAAC_PRECIPITATION_AVG_YEARLY,
#   ⁴​ACS_PCT_MALE, ⁵​ACS_PCT_FEMALE, ⁶​ACS_PCT_AIAN, ⁷​ACS_PCT_ASIAN, …</code></pre>
</div>
</div>
<p>683 is Mackinac County, Michigan, one of the most remote areas in the Great Lakes, with a population of 10,906.</p>
<p>1345 is Mellette County, South Dakota, with a population of 1,908.</p>
<p>1508 is Real County, Texas, a county with only one incorporated area and a population of 2,826.</p>
<p>Otherwise, the plot looks good.</p>
<p>Normal Q-Q violates this test, as the points at the right tail of the plot do not generally fall along the line. This is very apparent for our three out-liers. Cook’s Distance vs.&nbsp;Leverage violates this test as well. The remaining plots do not violate their tested assumptions and further cement the model’s reliability.</p>
</section>
</section>
<section id="conclusion" class="level2">
<h2 class="anchored" data-anchor-id="conclusion">Conclusion</h2>
<p>This paper explored the relationship between re-hospitalization rates and precipitation, when controlling for common variables that regularly influence the dependent variable.</p>
<p>Four models were selected, one for each variable, to best determine which measure best impacted re-hospitalization rates. In all of the models, precipitation was statistically significant. While the adjusted R-squared value is negligible (0.076), there is a positive relationship that is statistically significant. Therein we see some form of an influence large amounts of annual precipitation has on re-hospitalization rates.</p>
</section>
<section id="references" class="level2">
<h2 class="anchored" data-anchor-id="references">References</h2>
<p>Barnett, M., Hsu, J. &amp; McWilliams, M. (2015). “Patient Characteristics and Differences in Hospital Readmission Rates.” JAMA Intern Med., 175(11): 1803-1812.</p>
<p>Bhosale KH, Nath RK, Pandit N, Agarwal P, Khairnar S, Yadav B, &amp; Chandrakar S. (2020). “Rate of Rehospitalization in 60 Days of Discharge and It’s Determinants in Patients with Heart Failure with Reduced Ejection Fraction in a Tertiary Care Centre in India.” Int J Heart Fail. 21;2(2):131-144.</p>
<p>Li, Y., Cai, X. &amp; Glance, L. (2015). “Disparities in 30-day rehospitalization rates among Medicare skilled nursing facility residents by race and site of care.” Med Care, 53(12): 1058-1065.</p>
<p>Murray, F., Allen, M., Clark, C., Daly, C. &amp; Jacobs, D. (2021). “Socio-demographic and -economic factors associated with 30-day readmission for conditions targeted by the hospital readmissions reduction program: a population-based study.” BMC Public Health, 21.</p>
<p>Rizmie, D., Preuz, L., Miraldo, M. &amp; Atun, R. (2022). “Impact of extreme temperatures on emergency hospital admissions by age and socio-economic deprivation in England.” Social Science &amp; Medicine, 308.</p>
<p>Tapak, L., Maryanaji, Z., Hamidi, O., Abbasi, H. &amp; Najafi-Vosough, R. (2018). “Investigating the effect of climatic parameters on mental disorder admissions.” International Journal of Biometerology, 62, 2109-2118.</p>
<p>Trinh, T., Feeny, S. &amp; Posso, A. (2018). “Rainfall shocks and child health: the role of parental mental health.” Climate and Development, 13(1), 34-48.</p>
<p>Spatz, E., Bernheim, S., Horwitz, L. &amp; Herrin, J. (2020). Community factors and hospital wide readmission rates: Does context matter? PLoS One, 15(10).</p>


<!-- -->

</section>

</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const disableStylesheet = (stylesheets) => {
    for (let i=0; i < stylesheets.length; i++) {
      const stylesheet = stylesheets[i];
      stylesheet.rel = 'prefetch';
    }
  }
  const enableStylesheet = (stylesheets) => {
    for (let i=0; i < stylesheets.length; i++) {
      const stylesheet = stylesheets[i];
      stylesheet.rel = 'stylesheet';
    }
  }
  const manageTransitions = (selector, allowTransitions) => {
    const els = window.document.querySelectorAll(selector);
    for (let i=0; i < els.length; i++) {
      const el = els[i];
      if (allowTransitions) {
        el.classList.remove('notransition');
      } else {
        el.classList.add('notransition');
      }
    }
  }
  const toggleColorMode = (alternate) => {
    // Switch the stylesheets
    const alternateStylesheets = window.document.querySelectorAll('link.quarto-color-scheme.quarto-color-alternate');
    manageTransitions('#quarto-margin-sidebar .nav-link', false);
    if (alternate) {
      enableStylesheet(alternateStylesheets);
      for (const sheetNode of alternateStylesheets) {
        if (sheetNode.id === "quarto-bootstrap") {
          toggleBodyColorMode(sheetNode);
        }
      }
    } else {
      disableStylesheet(alternateStylesheets);
      toggleBodyColorPrimary();
    }
    manageTransitions('#quarto-margin-sidebar .nav-link', true);
    // Switch the toggles
    const toggles = window.document.querySelectorAll('.quarto-color-scheme-toggle');
    for (let i=0; i < toggles.length; i++) {
      const toggle = toggles[i];
      if (toggle) {
        if (alternate) {
          toggle.classList.add("alternate");     
        } else {
          toggle.classList.remove("alternate");
        }
      }
    }
    // Hack to workaround the fact that safari doesn't
    // properly recolor the scrollbar when toggling (#1455)
    if (navigator.userAgent.indexOf('Safari') > 0 && navigator.userAgent.indexOf('Chrome') == -1) {
      manageTransitions("body", false);
      window.scrollTo(0, 1);
      setTimeout(() => {
        window.scrollTo(0, 0);
        manageTransitions("body", true);
      }, 40);  
    }
  }
  const isFileUrl = () => { 
    return window.location.protocol === 'file:';
  }
  const hasAlternateSentinel = () => {  
    let styleSentinel = getColorSchemeSentinel();
    if (styleSentinel !== null) {
      return styleSentinel === "alternate";
    } else {
      return false;
    }
  }
  const setStyleSentinel = (alternate) => {
    const value = alternate ? "alternate" : "default";
    if (!isFileUrl()) {
      window.localStorage.setItem("quarto-color-scheme", value);
    } else {
      localAlternateSentinel = value;
    }
  }
  const getColorSchemeSentinel = () => {
    if (!isFileUrl()) {
      const storageValue = window.localStorage.getItem("quarto-color-scheme");
      return storageValue != null ? storageValue : localAlternateSentinel;
    } else {
      return localAlternateSentinel;
    }
  }
  let localAlternateSentinel = 'default';
  // Dark / light mode switch
  window.quartoToggleColorScheme = () => {
    // Read the current dark / light value 
    let toAlternate = !hasAlternateSentinel();
    toggleColorMode(toAlternate);
    setStyleSentinel(toAlternate);
  };
  // Ensure there is a toggle, if there isn't float one in the top right
  if (window.document.querySelector('.quarto-color-scheme-toggle') === null) {
    const a = window.document.createElement('a');
    a.classList.add('top-right');
    a.classList.add('quarto-color-scheme-toggle');
    a.href = "";
    a.onclick = function() { try { window.quartoToggleColorScheme(); } catch {} return false; };
    const i = window.document.createElement("i");
    i.classList.add('bi');
    a.appendChild(i);
    window.document.body.appendChild(a);
  }
  // Switch to dark mode if need be
  if (hasAlternateSentinel()) {
    toggleColorMode(true);
  } else {
    toggleColorMode(false);
  }
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const clipboard = new window.ClipboardJS('.code-copy-button', {
    target: function(trigger) {
      return trigger.previousElementSibling;
    }
  });
  clipboard.on('success', function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copied!");
    let tooltip;
    if (window.bootstrap) {
      button.setAttribute("data-bs-toggle", "tooltip");
      button.setAttribute("data-bs-placement", "left");
      button.setAttribute("data-bs-title", "Copied!");
      tooltip = new bootstrap.Tooltip(button, 
        { trigger: "manual", 
          customClass: "code-copy-button-tooltip",
          offset: [0, -8]});
      tooltip.show();    
    }
    setTimeout(function() {
      if (tooltip) {
        tooltip.hide();
        button.removeAttribute("data-bs-title");
        button.removeAttribute("data-bs-toggle");
        button.removeAttribute("data-bs-placement");
      }
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  });
  const viewSource = window.document.getElementById('quarto-view-source') ||
                     window.document.getElementById('quarto-code-tools-source');
  if (viewSource) {
    const sourceUrl = viewSource.getAttribute("data-quarto-source-url");
    viewSource.addEventListener("click", function(e) {
      if (sourceUrl) {
        // rstudio viewer pane
        if (/\bcapabilities=\b/.test(window.location)) {
          window.open(sourceUrl);
        } else {
          window.location.href = sourceUrl;
        }
      } else {
        const modal = new bootstrap.Modal(document.getElementById('quarto-embedded-source-code-modal'));
        modal.show();
      }
      return false;
    });
  }
  function toggleCodeHandler(show) {
    return function(e) {
      const detailsSrc = window.document.querySelectorAll(".cell > details > .sourceCode");
      for (let i=0; i<detailsSrc.length; i++) {
        const details = detailsSrc[i].parentElement;
        if (show) {
          details.open = true;
        } else {
          details.removeAttribute("open");
        }
      }
      const cellCodeDivs = window.document.querySelectorAll(".cell > .sourceCode");
      const fromCls = show ? "hidden" : "unhidden";
      const toCls = show ? "unhidden" : "hidden";
      for (let i=0; i<cellCodeDivs.length; i++) {
        const codeDiv = cellCodeDivs[i];
        if (codeDiv.classList.contains(fromCls)) {
          codeDiv.classList.remove(fromCls);
          codeDiv.classList.add(toCls);
        } 
      }
      return false;
    }
  }
  const hideAllCode = window.document.getElementById("quarto-hide-all-code");
  if (hideAllCode) {
    hideAllCode.addEventListener("click", toggleCodeHandler(false));
  }
  const showAllCode = window.document.getElementById("quarto-show-all-code");
  if (showAllCode) {
    showAllCode.addEventListener("click", toggleCodeHandler(true));
  }
  function tippyHover(el, contentFn) {
    const config = {
      allowHTML: true,
      content: contentFn,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start'
    };
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      return note.innerHTML;
    });
  }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
});
</script>
<script src="https://giscus.app/client.js" data-repo="DACSS/603_Fall_2022" data-repo-id="R_kgDOH568kA" data-category="Announcements" data-category-id="" data-mapping="title" data-reactions-enabled="1" data-emit-metadata="0" data-input-position="top" data-theme="light" data-lang="en" crossorigin="anonymous" async="">
</script><div class="modal fade" id="quarto-embedded-source-code-modal" tabindex="-1" aria-labelledby="quarto-embedded-source-code-modal-label" aria-hidden="true"><div class="modal-dialog modal-dialog-scrollable"><div class="modal-content"><div class="modal-header"><h5 class="modal-title" id="quarto-embedded-source-code-modal-label">Source Code</h5><button class="btn-close" data-bs-dismiss="modal"></button></div><div class="modal-body"><div class="">
<div class="sourceCode" id="cb74" data-shortcodes="false"><pre class="sourceCode markdown code-with-copy"><code class="sourceCode markdown"><span id="cb74-1"><a href="#cb74-1" aria-hidden="true" tabindex="-1"></a><span class="co">---</span></span>
<span id="cb74-2"><a href="#cb74-2" aria-hidden="true" tabindex="-1"></a><span class="an">title:</span><span class="co"> "Final Part 3"</span></span>
<span id="cb74-3"><a href="#cb74-3" aria-hidden="true" tabindex="-1"></a><span class="an">author:</span><span class="co"> "Caleb Hill"</span></span>
<span id="cb74-4"><a href="#cb74-4" aria-hidden="true" tabindex="-1"></a><span class="an">desription:</span><span class="co"> "Part 3 of the Final Project"</span></span>
<span id="cb74-5"><a href="#cb74-5" aria-hidden="true" tabindex="-1"></a><span class="an">date:</span><span class="co"> "12/11/2022"</span></span>
<span id="cb74-6"><a href="#cb74-6" aria-hidden="true" tabindex="-1"></a><span class="an">format:</span></span>
<span id="cb74-7"><a href="#cb74-7" aria-hidden="true" tabindex="-1"></a><span class="co">  html:</span></span>
<span id="cb74-8"><a href="#cb74-8" aria-hidden="true" tabindex="-1"></a><span class="co">    toc: true</span></span>
<span id="cb74-9"><a href="#cb74-9" aria-hidden="true" tabindex="-1"></a><span class="co">    code-fold: true</span></span>
<span id="cb74-10"><a href="#cb74-10" aria-hidden="true" tabindex="-1"></a><span class="co">    code-copy: true</span></span>
<span id="cb74-11"><a href="#cb74-11" aria-hidden="true" tabindex="-1"></a><span class="co">    code-tools: true</span></span>
<span id="cb74-12"><a href="#cb74-12" aria-hidden="true" tabindex="-1"></a><span class="an">categories:</span></span>
<span id="cb74-13"><a href="#cb74-13" aria-hidden="true" tabindex="-1"></a><span class="co">  - finalpart3</span></span>
<span id="cb74-14"><a href="#cb74-14" aria-hidden="true" tabindex="-1"></a><span class="co">  - caleb.hill</span></span>
<span id="cb74-15"><a href="#cb74-15" aria-hidden="true" tabindex="-1"></a><span class="co">---</span></span>
<span id="cb74-16"><a href="#cb74-16" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb74-17"><a href="#cb74-17" aria-hidden="true" tabindex="-1"></a><span class="fu">## Introduction</span></span>
<span id="cb74-18"><a href="#cb74-18" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb74-19"><a href="#cb74-19" aria-hidden="true" tabindex="-1"></a>With climate change upsetting normal weather patterns, there has been exciting research into how precipitation shocks (flooding and drought events) impact health outcomes, (Rizmie, d., Preuz, L, Miraldo, M. &amp; Atun, R. (2022); Tapak, L., Maryanaji, Z., Hamidi, O., Abbasi, H. &amp; Najafi-Vosough, R. (2018); Trinh, T., Feeny, S. &amp; Posso, A. (2018)). Alongside this train of thought, multiple research reports state that there is a relationship between re-hospitalization rates and social characteristics, such as demographic and economic identifiers, (Barnett, Hsu &amp; McWilliams, 2015; Murray, Allen, Clark, Daly &amp; Jacobs, 2021). Specifically, racial characteristics play a large role in predicting re-hospitalization in a population (Li, Cai &amp; Glance, 2015). While some articles examine economic and health factors contributing to these disparities, very few dig deep into environmental factors that influence this phenomenon, (Spatz, Bernheim, Horwitz &amp; Herrin, 2020). With your zipcode affecting up to 60% of your health outcomes, this research is relevant to better improving one of our most costly health expenditures: hospitalization. Therefore, this research report aims to integrate these two concepts, testing if precipitation shocks have a positive relationship on not just hospital admissions but also re-admissions.</span>
<span id="cb74-20"><a href="#cb74-20" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb74-21"><a href="#cb74-21" aria-hidden="true" tabindex="-1"></a>Re-hospitalization is a substantially costlier expenditure, as readmitting a patient further increases costs -- especially if the diagnosis was untreated, poorly treated, or incorrectly treated. Most inpatient episodes characterized as a re-hospitalization when the patient is readmitted to the hospital 60 days after discharge. If the cause is different, sometimes that is counted as a re-hospitalization; other times, not so much, (Bhosale, K., Nath, R., Pandit, N., Agarwal, P., Khairnar, S., Yadav, B. &amp; Chandrakar, S., 2020).</span>
<span id="cb74-22"><a href="#cb74-22" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb74-23"><a href="#cb74-23" aria-hidden="true" tabindex="-1"></a><span class="fu">### Research Question</span></span>
<span id="cb74-24"><a href="#cb74-24" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb74-25"><a href="#cb74-25" aria-hidden="true" tabindex="-1"></a>This paper aims to explore how precipitation shocks impact re-hospitalization rates on a county-by-county level. We will control for socio-demographic and economic variables. We will also stratify by rural/urban classification, to determine if counties above or below 250,000 population experience differences in re-hospitalization rates, dependent upon these explanatory variables. This is purely because literature shows that rural communities face more acute and poorer health outcomes.</span>
<span id="cb74-26"><a href="#cb74-26" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb74-27"><a href="#cb74-27" aria-hidden="true" tabindex="-1"></a>The data-set chosen for this analysis is taken from the Agency for Healthcare Research and Quality, Social Determinants of Health (SDOH) Database. This data-set has over 1,400 variables to explore each SDOH domain: social context, economic context, education, healthcare, and the environment. We shall pull data from three of these five domains: social, economic, and environmental.</span>
<span id="cb74-28"><a href="#cb74-28" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb74-29"><a href="#cb74-29" aria-hidden="true" tabindex="-1"></a>How re-hospitalization is measured is not clarified per this data-set's codebook. However, the Center for Medicare and Medicaid (CMS) 30-day Risk-Standardized Readmission Rate (RSRR) measures re-hospitalization as an unplanned readmission to inpatient services. It does stratify and specify based upon diagnosis. As the AHRQ is a federal agency alongside CMS, it is likely that they are pulling from CMS for this measure and aggregating various diagnoses into one county rate.</span>
<span id="cb74-30"><a href="#cb74-30" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb74-31"><a href="#cb74-31" aria-hidden="true" tabindex="-1"></a><span class="fu">### Hypothesis</span></span>
<span id="cb74-32"><a href="#cb74-32" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb74-33"><a href="#cb74-33" aria-hidden="true" tabindex="-1"></a>The hypothesis for this research report is:</span>
<span id="cb74-34"><a href="#cb74-34" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb74-35"><a href="#cb74-35" aria-hidden="true" tabindex="-1"></a><span class="ss">-   </span>Precipitation has a positive impact on re-hospitalization rates within rural counties.</span>
<span id="cb74-36"><a href="#cb74-36" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb74-37"><a href="#cb74-37" aria-hidden="true" tabindex="-1"></a>Therefore, the null hypothesis is:</span>
<span id="cb74-38"><a href="#cb74-38" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb74-39"><a href="#cb74-39" aria-hidden="true" tabindex="-1"></a><span class="ss">-   </span>Precipitation does not have a positive impact on re-hospitalization rates within rural counties.</span>
<span id="cb74-40"><a href="#cb74-40" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb74-41"><a href="#cb74-41" aria-hidden="true" tabindex="-1"></a>Various regression models shall be employed to determine the relationship -- or lack thereof -- between these variables.</span>
<span id="cb74-42"><a href="#cb74-42" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb74-43"><a href="#cb74-43" aria-hidden="true" tabindex="-1"></a>First I'll import the relevant librarie and set up a UMass color scheme for crimson and black.</span>
<span id="cb74-44"><a href="#cb74-44" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb74-45"><a href="#cb74-45" aria-hidden="true" tabindex="-1"></a><span class="in">```{r, include = FALSE}</span></span>
<span id="cb74-46"><a href="#cb74-46" aria-hidden="true" tabindex="-1"></a><span class="co">#| label: setup</span></span>
<span id="cb74-47"><a href="#cb74-47" aria-hidden="true" tabindex="-1"></a><span class="co">#| warning: false</span></span>
<span id="cb74-48"><a href="#cb74-48" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb74-49"><a href="#cb74-49" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(tidyverse)</span>
<span id="cb74-50"><a href="#cb74-50" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(readxl)</span>
<span id="cb74-51"><a href="#cb74-51" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(psych)</span>
<span id="cb74-52"><a href="#cb74-52" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(knitr)</span>
<span id="cb74-53"><a href="#cb74-53" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(corrplot)</span>
<span id="cb74-54"><a href="#cb74-54" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(stargazer)</span>
<span id="cb74-55"><a href="#cb74-55" aria-hidden="true" tabindex="-1"></a><span class="fu">theme_bw</span>()</span>
<span id="cb74-56"><a href="#cb74-56" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb74-57"><a href="#cb74-57" aria-hidden="true" tabindex="-1"></a>umass_colors <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="st">"#881c1c"</span>, <span class="st">"#212721"</span>)</span>
<span id="cb74-58"><a href="#cb74-58" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb74-59"><a href="#cb74-59" aria-hidden="true" tabindex="-1"></a>knitr<span class="sc">::</span>opts_chunk<span class="sc">$</span><span class="fu">set</span>(<span class="at">echo =</span> <span class="cn">TRUE</span>)</span>
<span id="cb74-60"><a href="#cb74-60" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb74-61"><a href="#cb74-61" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb74-62"><a href="#cb74-62" aria-hidden="true" tabindex="-1"></a>Then I'll import the dataset and view the first six rows.</span>
<span id="cb74-63"><a href="#cb74-63" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb74-66"><a href="#cb74-66" aria-hidden="true" tabindex="-1"></a><span class="in">```{r}</span></span>
<span id="cb74-67"><a href="#cb74-67" aria-hidden="true" tabindex="-1"></a>df <span class="ot">&lt;-</span> SDOH_2020_COUNTY_1_0 <span class="ot">&lt;-</span> <span class="fu">read_excel</span>(<span class="st">"_data/SDOH_2020_COUNTY_1_0.xlsx"</span>, </span>
<span id="cb74-68"><a href="#cb74-68" aria-hidden="true" tabindex="-1"></a>                                         <span class="at">sheet =</span> <span class="st">"Data"</span>)</span>
<span id="cb74-69"><a href="#cb74-69" aria-hidden="true" tabindex="-1"></a><span class="fu">head</span>(df)</span>
<span id="cb74-70"><a href="#cb74-70" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb74-71"><a href="#cb74-71" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb74-72"><a href="#cb74-72" aria-hidden="true" tabindex="-1"></a>Next I want to verify the class is a dataframe. Otherwise, I'll need to transform the data to make it easier to work with.</span>
<span id="cb74-73"><a href="#cb74-73" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb74-76"><a href="#cb74-76" aria-hidden="true" tabindex="-1"></a><span class="in">```{r}</span></span>
<span id="cb74-77"><a href="#cb74-77" aria-hidden="true" tabindex="-1"></a><span class="fu">class</span>(df)</span>
<span id="cb74-78"><a href="#cb74-78" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb74-79"><a href="#cb74-79" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb74-80"><a href="#cb74-80" aria-hidden="true" tabindex="-1"></a>All good here.</span>
<span id="cb74-81"><a href="#cb74-81" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb74-82"><a href="#cb74-82" aria-hidden="true" tabindex="-1"></a>Now on to data transformation. We will need to select only the relevant columns for this analysis.</span>
<span id="cb74-83"><a href="#cb74-83" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb74-86"><a href="#cb74-86" aria-hidden="true" tabindex="-1"></a><span class="in">```{r}</span></span>
<span id="cb74-87"><a href="#cb74-87" aria-hidden="true" tabindex="-1"></a>df_new <span class="ot">&lt;-</span> df <span class="sc">%&gt;%</span></span>
<span id="cb74-88"><a href="#cb74-88" aria-hidden="true" tabindex="-1"></a>  <span class="fu">select</span>(COUNTYFIPS,</span>
<span id="cb74-89"><a href="#cb74-89" aria-hidden="true" tabindex="-1"></a>         STATE,</span>
<span id="cb74-90"><a href="#cb74-90" aria-hidden="true" tabindex="-1"></a>         COUNTY,</span>
<span id="cb74-91"><a href="#cb74-91" aria-hidden="true" tabindex="-1"></a>         AHRF_USDA_RUCC_2013,</span>
<span id="cb74-92"><a href="#cb74-92" aria-hidden="true" tabindex="-1"></a>         NOAAC_PRECIPITATION_AVG_YEARLY,</span>
<span id="cb74-93"><a href="#cb74-93" aria-hidden="true" tabindex="-1"></a>         ACS_PCT_MALE,</span>
<span id="cb74-94"><a href="#cb74-94" aria-hidden="true" tabindex="-1"></a>         ACS_PCT_FEMALE,</span>
<span id="cb74-95"><a href="#cb74-95" aria-hidden="true" tabindex="-1"></a>         ACS_PCT_AIAN,</span>
<span id="cb74-96"><a href="#cb74-96" aria-hidden="true" tabindex="-1"></a>         ACS_PCT_ASIAN,</span>
<span id="cb74-97"><a href="#cb74-97" aria-hidden="true" tabindex="-1"></a>         ACS_PCT_BLACK,</span>
<span id="cb74-98"><a href="#cb74-98" aria-hidden="true" tabindex="-1"></a>         ACS_PCT_HISPANIC,</span>
<span id="cb74-99"><a href="#cb74-99" aria-hidden="true" tabindex="-1"></a>         ACS_PCT_MULT_RACE,</span>
<span id="cb74-100"><a href="#cb74-100" aria-hidden="true" tabindex="-1"></a>         ACS_PCT_NHPI,</span>
<span id="cb74-101"><a href="#cb74-101" aria-hidden="true" tabindex="-1"></a>         ACS_PCT_OTHER_RACE,</span>
<span id="cb74-102"><a href="#cb74-102" aria-hidden="true" tabindex="-1"></a>         ACS_PCT_WHITE,</span>
<span id="cb74-103"><a href="#cb74-103" aria-hidden="true" tabindex="-1"></a>         SAIPE_MEDIAN_HH_INCOME,</span>
<span id="cb74-104"><a href="#cb74-104" aria-hidden="true" tabindex="-1"></a>         SAIPE_PCT_POV,</span>
<span id="cb74-105"><a href="#cb74-105" aria-hidden="true" tabindex="-1"></a>         ACS_PCT_COMMT_60MINUP,</span>
<span id="cb74-106"><a href="#cb74-106" aria-hidden="true" tabindex="-1"></a>         ACS_PCT_RENTER_HU_COST_50PCT,</span>
<span id="cb74-107"><a href="#cb74-107" aria-hidden="true" tabindex="-1"></a>         LTC_AVG_OBS_REHOSP_RATE) </span>
<span id="cb74-108"><a href="#cb74-108" aria-hidden="true" tabindex="-1"></a><span class="fu">nrow</span>(df_new)</span>
<span id="cb74-109"><a href="#cb74-109" aria-hidden="true" tabindex="-1"></a><span class="fu">head</span>(df_new)</span>
<span id="cb74-110"><a href="#cb74-110" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb74-111"><a href="#cb74-111" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb74-112"><a href="#cb74-112" aria-hidden="true" tabindex="-1"></a>Out of 1400+ variables, we've whittled them down to 20. Of those 20, we have four (4) that are unique identifiers (FIPS, State, County, and Rural-Urban Continuation Code), ten (10) socio-demographic, four (4) economic, one (1) for precipitation, and one (1) for re-hospitalization.</span>
<span id="cb74-113"><a href="#cb74-113" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb74-114"><a href="#cb74-114" aria-hidden="true" tabindex="-1"></a>Before we launch into exploring these variables via descriptive statistics, first we need to determine where the NAs are and see if any of the variables will have a substantial amount of missing data.</span>
<span id="cb74-115"><a href="#cb74-115" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb74-118"><a href="#cb74-118" aria-hidden="true" tabindex="-1"></a><span class="in">```{r}</span></span>
<span id="cb74-119"><a href="#cb74-119" aria-hidden="true" tabindex="-1"></a><span class="fu">kable</span>(<span class="fu">colSums</span>(<span class="fu">is.na</span>(df_new)))</span>
<span id="cb74-120"><a href="#cb74-120" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb74-121"><a href="#cb74-121" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb74-122"><a href="#cb74-122" aria-hidden="true" tabindex="-1"></a>Plenty of variables with missing data. The most concerning is -- of course -- our outcome variable, Re-Hospitalization Rates. This is not ideal. However, 410 / 3229 (12.6%) is not bad. That still leaves us with plenty of counties to review.</span>
<span id="cb74-123"><a href="#cb74-123" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb74-126"><a href="#cb74-126" aria-hidden="true" tabindex="-1"></a><span class="in">```{r}</span></span>
<span id="cb74-127"><a href="#cb74-127" aria-hidden="true" tabindex="-1"></a>df_new <span class="ot">&lt;-</span> df_new <span class="sc">%&gt;%</span></span>
<span id="cb74-128"><a href="#cb74-128" aria-hidden="true" tabindex="-1"></a>  <span class="fu">drop_na</span>() <span class="sc">%&gt;%</span></span>
<span id="cb74-129"><a href="#cb74-129" aria-hidden="true" tabindex="-1"></a>  <span class="fu">print</span>(<span class="fu">nrow</span>(df_new))</span>
<span id="cb74-130"><a href="#cb74-130" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb74-131"><a href="#cb74-131" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb74-132"><a href="#cb74-132" aria-hidden="true" tabindex="-1"></a>2,814 x 20 is a good place to start.</span>
<span id="cb74-133"><a href="#cb74-133" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb74-134"><a href="#cb74-134" aria-hidden="true" tabindex="-1"></a>This next step will conver the Rural-Urban Continuum Code to a binary Rural/Urban. If the county is coded as a four (4) or higher, then they are classified as rural, non-metro, having a population of less than 250,000 as defined by USDA as "Rural."</span>
<span id="cb74-135"><a href="#cb74-135" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb74-138"><a href="#cb74-138" aria-hidden="true" tabindex="-1"></a><span class="in">```{r}</span></span>
<span id="cb74-139"><a href="#cb74-139" aria-hidden="true" tabindex="-1"></a>df_new <span class="ot">&lt;-</span> df_new <span class="sc">%&gt;%</span></span>
<span id="cb74-140"><a href="#cb74-140" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">Rurality =</span> <span class="fu">if_else</span>(</span>
<span id="cb74-141"><a href="#cb74-141" aria-hidden="true" tabindex="-1"></a>    AHRF_USDA_RUCC_2013 <span class="sc">&gt;=</span> <span class="dv">4</span>, <span class="st">"Rural"</span>, <span class="st">"Urban"</span>)</span>
<span id="cb74-142"><a href="#cb74-142" aria-hidden="true" tabindex="-1"></a>    )</span>
<span id="cb74-143"><a href="#cb74-143" aria-hidden="true" tabindex="-1"></a><span class="fu">head</span>(df_new)</span>
<span id="cb74-144"><a href="#cb74-144" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb74-145"><a href="#cb74-145" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb74-146"><a href="#cb74-146" aria-hidden="true" tabindex="-1"></a><span class="fu">## Descriptive Statistics</span></span>
<span id="cb74-147"><a href="#cb74-147" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb74-148"><a href="#cb74-148" aria-hidden="true" tabindex="-1"></a>For our preliminary analysis, we're going to provide summary statistics analyzing the variables relevant to our research question, excluding the socio-demographic control variables, and a visualization for each.</span>
<span id="cb74-149"><a href="#cb74-149" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb74-152"><a href="#cb74-152" aria-hidden="true" tabindex="-1"></a><span class="in">```{r}</span></span>
<span id="cb74-153"><a href="#cb74-153" aria-hidden="true" tabindex="-1"></a><span class="fu">kable</span>(<span class="fu">describe</span>(df_new))</span>
<span id="cb74-154"><a href="#cb74-154" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb74-155"><a href="#cb74-155" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb74-156"><a href="#cb74-156" aria-hidden="true" tabindex="-1"></a>Following this, we're going to stratify each variable by rurality and determine either the difference in distribution (histogram) and/or central tendency (boxplot).</span>
<span id="cb74-157"><a href="#cb74-157" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb74-158"><a href="#cb74-158" aria-hidden="true" tabindex="-1"></a><span class="fu">### Average Yearly Precipitation</span></span>
<span id="cb74-159"><a href="#cb74-159" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb74-162"><a href="#cb74-162" aria-hidden="true" tabindex="-1"></a><span class="in">```{r}</span></span>
<span id="cb74-163"><a href="#cb74-163" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(df_new, <span class="fu">aes</span>(<span class="at">x =</span> NOAAC_PRECIPITATION_AVG_YEARLY,</span>
<span id="cb74-164"><a href="#cb74-164" aria-hidden="true" tabindex="-1"></a>                   <span class="at">fill =</span> Rurality)) <span class="sc">+</span></span>
<span id="cb74-165"><a href="#cb74-165" aria-hidden="true" tabindex="-1"></a>  <span class="fu">scale_fill_manual</span>(<span class="at">values =</span> umass_colors) <span class="sc">+</span></span>
<span id="cb74-166"><a href="#cb74-166" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_histogram</span>() <span class="sc">+</span></span>
<span id="cb74-167"><a href="#cb74-167" aria-hidden="true" tabindex="-1"></a>  <span class="fu">xlab</span>(<span class="st">"Average Annual Precipitation"</span>) <span class="sc">+</span></span>
<span id="cb74-168"><a href="#cb74-168" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ylab</span>(<span class="st">"Count"</span>) <span class="sc">+</span></span>
<span id="cb74-169"><a href="#cb74-169" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_bw</span>()</span>
<span id="cb74-170"><a href="#cb74-170" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb74-171"><a href="#cb74-171" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(df_new, <span class="fu">aes</span>(<span class="at">x =</span> NOAAC_PRECIPITATION_AVG_YEARLY,</span>
<span id="cb74-172"><a href="#cb74-172" aria-hidden="true" tabindex="-1"></a>                   <span class="at">fill =</span> Rurality)) <span class="sc">+</span></span>
<span id="cb74-173"><a href="#cb74-173" aria-hidden="true" tabindex="-1"></a>  <span class="fu">scale_fill_manual</span>(<span class="at">values =</span> umass_colors) <span class="sc">+</span></span>
<span id="cb74-174"><a href="#cb74-174" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_boxplot</span>() <span class="sc">+</span></span>
<span id="cb74-175"><a href="#cb74-175" aria-hidden="true" tabindex="-1"></a>  <span class="fu">xlab</span>(<span class="st">"Average Annual Precipitation"</span>) <span class="sc">+</span></span>
<span id="cb74-176"><a href="#cb74-176" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ylab</span>(<span class="st">"Count"</span>) <span class="sc">+</span></span>
<span id="cb74-177"><a href="#cb74-177" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_bw</span>()</span>
<span id="cb74-178"><a href="#cb74-178" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb74-179"><a href="#cb74-179" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb74-180"><a href="#cb74-180" aria-hidden="true" tabindex="-1"></a>Average precipitation each month is fairly uniform, with the mean at 3.49 inches of rain, on average, each month. The mean does differ from Urban to Rural, with Rural counties being drier than their Urban counterparts, but not by much. This variable will most likely provide less variation in the analysis compared to others. </span>
<span id="cb74-181"><a href="#cb74-181" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb74-182"><a href="#cb74-182" aria-hidden="true" tabindex="-1"></a><span class="fu">### Median Household Income</span></span>
<span id="cb74-183"><a href="#cb74-183" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb74-186"><a href="#cb74-186" aria-hidden="true" tabindex="-1"></a><span class="in">```{r}</span></span>
<span id="cb74-187"><a href="#cb74-187" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(df_new, <span class="fu">aes</span>(<span class="at">x =</span> SAIPE_MEDIAN_HH_INCOME,</span>
<span id="cb74-188"><a href="#cb74-188" aria-hidden="true" tabindex="-1"></a>                   <span class="at">fill =</span> Rurality)) <span class="sc">+</span></span>
<span id="cb74-189"><a href="#cb74-189" aria-hidden="true" tabindex="-1"></a>  <span class="fu">scale_fill_manual</span>(<span class="at">values =</span> umass_colors) <span class="sc">+</span></span>
<span id="cb74-190"><a href="#cb74-190" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_histogram</span>() <span class="sc">+</span></span>
<span id="cb74-191"><a href="#cb74-191" aria-hidden="true" tabindex="-1"></a>  <span class="fu">xlab</span>(<span class="st">"Median Household Income"</span>) <span class="sc">+</span></span>
<span id="cb74-192"><a href="#cb74-192" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ylab</span>(<span class="st">"Count"</span>) <span class="sc">+</span></span>
<span id="cb74-193"><a href="#cb74-193" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_bw</span>()</span>
<span id="cb74-194"><a href="#cb74-194" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb74-195"><a href="#cb74-195" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(df_new, <span class="fu">aes</span>(<span class="at">x =</span> SAIPE_MEDIAN_HH_INCOME,</span>
<span id="cb74-196"><a href="#cb74-196" aria-hidden="true" tabindex="-1"></a>                   <span class="at">fill =</span> Rurality)) <span class="sc">+</span></span>
<span id="cb74-197"><a href="#cb74-197" aria-hidden="true" tabindex="-1"></a>  <span class="fu">scale_fill_manual</span>(<span class="at">values =</span> umass_colors) <span class="sc">+</span></span>
<span id="cb74-198"><a href="#cb74-198" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_boxplot</span>() <span class="sc">+</span></span>
<span id="cb74-199"><a href="#cb74-199" aria-hidden="true" tabindex="-1"></a>  <span class="fu">xlab</span>(<span class="st">"Median Household Income"</span>) <span class="sc">+</span></span>
<span id="cb74-200"><a href="#cb74-200" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ylab</span>(<span class="st">"Count"</span>) <span class="sc">+</span></span>
<span id="cb74-201"><a href="#cb74-201" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_bw</span>()</span>
<span id="cb74-202"><a href="#cb74-202" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb74-203"><a href="#cb74-203" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb74-204"><a href="#cb74-204" aria-hidden="true" tabindex="-1"></a>Very close to a normal distribution, if barely left-skewed. A couple of high out-liers, hovering around \$90,000+ in median household income, but the mean holds at \$57,465.</span>
<span id="cb74-205"><a href="#cb74-205" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb74-206"><a href="#cb74-206" aria-hidden="true" tabindex="-1"></a>Rural Counties have substantially lower median household income, by roughly \$10,ooo to \$20,000. Urban counties also make up the bulk of out-liers.</span>
<span id="cb74-207"><a href="#cb74-207" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb74-208"><a href="#cb74-208" aria-hidden="true" tabindex="-1"></a><span class="fu">### Percent in Poverty</span></span>
<span id="cb74-209"><a href="#cb74-209" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb74-212"><a href="#cb74-212" aria-hidden="true" tabindex="-1"></a><span class="in">```{r}</span></span>
<span id="cb74-213"><a href="#cb74-213" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(df_new, <span class="fu">aes</span>(<span class="at">x =</span> SAIPE_PCT_POV,</span>
<span id="cb74-214"><a href="#cb74-214" aria-hidden="true" tabindex="-1"></a>                     <span class="at">fill =</span> Rurality)) <span class="sc">+</span></span>
<span id="cb74-215"><a href="#cb74-215" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_histogram</span>() <span class="sc">+</span></span>
<span id="cb74-216"><a href="#cb74-216" aria-hidden="true" tabindex="-1"></a>  <span class="fu">xlab</span>(<span class="st">"Percent Poverty"</span>) <span class="sc">+</span></span>
<span id="cb74-217"><a href="#cb74-217" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ylab</span>(<span class="st">"Count"</span>) <span class="sc">+</span></span>
<span id="cb74-218"><a href="#cb74-218" aria-hidden="true" tabindex="-1"></a>  <span class="fu">scale_fill_manual</span>(<span class="at">values =</span> umass_colors) <span class="sc">+</span></span>
<span id="cb74-219"><a href="#cb74-219" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_bw</span>()</span>
<span id="cb74-220"><a href="#cb74-220" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb74-221"><a href="#cb74-221" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(df_new, <span class="fu">aes</span>(<span class="at">x =</span> SAIPE_PCT_POV,</span>
<span id="cb74-222"><a href="#cb74-222" aria-hidden="true" tabindex="-1"></a>                   <span class="at">fill =</span> Rurality)) <span class="sc">+</span></span>
<span id="cb74-223"><a href="#cb74-223" aria-hidden="true" tabindex="-1"></a>  <span class="fu">scale_fill_manual</span>(<span class="at">values =</span> umass_colors) <span class="sc">+</span></span>
<span id="cb74-224"><a href="#cb74-224" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_boxplot</span>() <span class="sc">+</span></span>
<span id="cb74-225"><a href="#cb74-225" aria-hidden="true" tabindex="-1"></a>  <span class="fu">xlab</span>(<span class="st">"Percent Poverty"</span>) <span class="sc">+</span></span>
<span id="cb74-226"><a href="#cb74-226" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ylab</span>(<span class="st">"Count"</span>) <span class="sc">+</span></span>
<span id="cb74-227"><a href="#cb74-227" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_bw</span>()</span>
<span id="cb74-228"><a href="#cb74-228" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb74-229"><a href="#cb74-229" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb74-230"><a href="#cb74-230" aria-hidden="true" tabindex="-1"></a>Another close to normal distribution. Most counties have poverty rates ranging from 10% to 20%. There are of course out-liers, especially a good number below 10%, but those are rare.</span>
<span id="cb74-231"><a href="#cb74-231" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb74-232"><a href="#cb74-232" aria-hidden="true" tabindex="-1"></a>Urbanized counties have substantially less percentage poverty compared to their rural counterparts, and rural counties make up the bulk of outliers post-30%. Only one Urban county has a poverty rate higher than 30%.</span>
<span id="cb74-233"><a href="#cb74-233" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb74-234"><a href="#cb74-234" aria-hidden="true" tabindex="-1"></a><span class="fu">### Percent Commuting Alone, Over 60 Minutes</span></span>
<span id="cb74-235"><a href="#cb74-235" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb74-238"><a href="#cb74-238" aria-hidden="true" tabindex="-1"></a><span class="in">```{r}</span></span>
<span id="cb74-239"><a href="#cb74-239" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(df_new, <span class="fu">aes</span>(<span class="at">x =</span> ACS_PCT_COMMT_60MINUP,</span>
<span id="cb74-240"><a href="#cb74-240" aria-hidden="true" tabindex="-1"></a>                     <span class="at">fill =</span> Rurality)) <span class="sc">+</span></span>
<span id="cb74-241"><a href="#cb74-241" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_histogram</span>() <span class="sc">+</span></span>
<span id="cb74-242"><a href="#cb74-242" aria-hidden="true" tabindex="-1"></a>  <span class="fu">xlab</span>(<span class="st">"Percent Commuting Alone, Over 60 Minutes"</span>) <span class="sc">+</span></span>
<span id="cb74-243"><a href="#cb74-243" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ylab</span>(<span class="st">"Count"</span>) <span class="sc">+</span></span>
<span id="cb74-244"><a href="#cb74-244" aria-hidden="true" tabindex="-1"></a>  <span class="fu">scale_fill_manual</span>(<span class="at">values =</span> umass_colors) <span class="sc">+</span></span>
<span id="cb74-245"><a href="#cb74-245" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_bw</span>()</span>
<span id="cb74-246"><a href="#cb74-246" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb74-247"><a href="#cb74-247" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(df_new, <span class="fu">aes</span>(<span class="at">x =</span> ACS_PCT_COMMT_60MINUP,</span>
<span id="cb74-248"><a href="#cb74-248" aria-hidden="true" tabindex="-1"></a>                   <span class="at">fill =</span> Rurality)) <span class="sc">+</span></span>
<span id="cb74-249"><a href="#cb74-249" aria-hidden="true" tabindex="-1"></a>  <span class="fu">scale_fill_manual</span>(<span class="at">values =</span> umass_colors) <span class="sc">+</span></span>
<span id="cb74-250"><a href="#cb74-250" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_boxplot</span>() <span class="sc">+</span></span>
<span id="cb74-251"><a href="#cb74-251" aria-hidden="true" tabindex="-1"></a>  <span class="fu">xlab</span>(<span class="st">"Percent Commuting Alone, Over 60 Minutes"</span>) <span class="sc">+</span></span>
<span id="cb74-252"><a href="#cb74-252" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ylab</span>(<span class="st">"Count"</span>) <span class="sc">+</span></span>
<span id="cb74-253"><a href="#cb74-253" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_bw</span>()</span>
<span id="cb74-254"><a href="#cb74-254" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb74-255"><a href="#cb74-255" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb74-256"><a href="#cb74-256" aria-hidden="true" tabindex="-1"></a>The majority of counties fall below 10% of their population commuting up to and more than 60 minutes for work. Very little variation between urban and rural counties here, which is surprising considering population density would lead one to believe rural counties travel longer on average. Perhaps the inverse is correct, in that highly remote communities means commutes are more local.</span>
<span id="cb74-257"><a href="#cb74-257" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb74-258"><a href="#cb74-258" aria-hidden="true" tabindex="-1"></a><span class="fu">### Percent Renter Housing Costs Over 50 Percent of Income</span></span>
<span id="cb74-259"><a href="#cb74-259" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb74-262"><a href="#cb74-262" aria-hidden="true" tabindex="-1"></a><span class="in">```{r}</span></span>
<span id="cb74-263"><a href="#cb74-263" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(df_new, <span class="fu">aes</span>(<span class="at">x =</span> ACS_PCT_RENTER_HU_COST_50PCT,</span>
<span id="cb74-264"><a href="#cb74-264" aria-hidden="true" tabindex="-1"></a>                     <span class="at">fill =</span> Rurality)) <span class="sc">+</span></span>
<span id="cb74-265"><a href="#cb74-265" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_histogram</span>() <span class="sc">+</span></span>
<span id="cb74-266"><a href="#cb74-266" aria-hidden="true" tabindex="-1"></a>  <span class="fu">xlab</span>(<span class="st">"Percent Renter Housing Costs Over 50 Percent of Income"</span>) <span class="sc">+</span></span>
<span id="cb74-267"><a href="#cb74-267" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ylab</span>(<span class="st">"Count"</span>) <span class="sc">+</span></span>
<span id="cb74-268"><a href="#cb74-268" aria-hidden="true" tabindex="-1"></a>  <span class="fu">scale_fill_manual</span>(<span class="at">values =</span> umass_colors) <span class="sc">+</span></span>
<span id="cb74-269"><a href="#cb74-269" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_bw</span>()</span>
<span id="cb74-270"><a href="#cb74-270" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb74-271"><a href="#cb74-271" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(df_new, <span class="fu">aes</span>(<span class="at">x =</span> ACS_PCT_RENTER_HU_COST_50PCT,</span>
<span id="cb74-272"><a href="#cb74-272" aria-hidden="true" tabindex="-1"></a>                   <span class="at">fill =</span> Rurality)) <span class="sc">+</span></span>
<span id="cb74-273"><a href="#cb74-273" aria-hidden="true" tabindex="-1"></a>  <span class="fu">scale_fill_manual</span>(<span class="at">values =</span> umass_colors) <span class="sc">+</span></span>
<span id="cb74-274"><a href="#cb74-274" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_boxplot</span>() <span class="sc">+</span></span>
<span id="cb74-275"><a href="#cb74-275" aria-hidden="true" tabindex="-1"></a>  <span class="fu">xlab</span>(<span class="st">"Percent Renter Housing Costs Over 50 Percent of Income"</span>) <span class="sc">+</span></span>
<span id="cb74-276"><a href="#cb74-276" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ylab</span>(<span class="st">"Count"</span>) <span class="sc">+</span></span>
<span id="cb74-277"><a href="#cb74-277" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_bw</span>()</span>
<span id="cb74-278"><a href="#cb74-278" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb74-279"><a href="#cb74-279" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb74-280"><a href="#cb74-280" aria-hidden="true" tabindex="-1"></a>This is a startling figure. On average, 20% of counties have renters where 50% or more of their income goes toward housing costs. These leaves little to no room for other expenses and drives economic instability. The data is normally distributed and barely left-skewed -- but still an item to consider with further analysis. </span>
<span id="cb74-281"><a href="#cb74-281" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb74-282"><a href="#cb74-282" aria-hidden="true" tabindex="-1"></a>Urban counties also have a higher renter housing burden on average, with rural counties having more out-liers.</span>
<span id="cb74-283"><a href="#cb74-283" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb74-284"><a href="#cb74-284" aria-hidden="true" tabindex="-1"></a><span class="fu">### Re-hospitalization Rate</span></span>
<span id="cb74-285"><a href="#cb74-285" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb74-288"><a href="#cb74-288" aria-hidden="true" tabindex="-1"></a><span class="in">```{r}</span></span>
<span id="cb74-289"><a href="#cb74-289" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(df_new, <span class="fu">aes</span>(<span class="at">x =</span> LTC_AVG_OBS_REHOSP_RATE,</span>
<span id="cb74-290"><a href="#cb74-290" aria-hidden="true" tabindex="-1"></a>                   <span class="at">fill =</span> Rurality)) <span class="sc">+</span></span>
<span id="cb74-291"><a href="#cb74-291" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_histogram</span>() <span class="sc">+</span></span>
<span id="cb74-292"><a href="#cb74-292" aria-hidden="true" tabindex="-1"></a>  <span class="fu">xlab</span>(<span class="st">"Re-Hospitalization Rate"</span>) <span class="sc">+</span></span>
<span id="cb74-293"><a href="#cb74-293" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ylab</span>(<span class="st">"Count"</span>) <span class="sc">+</span></span>
<span id="cb74-294"><a href="#cb74-294" aria-hidden="true" tabindex="-1"></a>  <span class="fu">scale_fill_manual</span>(<span class="at">values =</span> umass_colors) <span class="sc">+</span></span>
<span id="cb74-295"><a href="#cb74-295" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_bw</span>()</span>
<span id="cb74-296"><a href="#cb74-296" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb74-297"><a href="#cb74-297" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(df_new, <span class="fu">aes</span>(<span class="at">x =</span> LTC_AVG_OBS_REHOSP_RATE,</span>
<span id="cb74-298"><a href="#cb74-298" aria-hidden="true" tabindex="-1"></a>                   <span class="at">fill =</span> Rurality)) <span class="sc">+</span></span>
<span id="cb74-299"><a href="#cb74-299" aria-hidden="true" tabindex="-1"></a>  <span class="fu">scale_fill_manual</span>(<span class="at">values =</span> umass_colors) <span class="sc">+</span></span>
<span id="cb74-300"><a href="#cb74-300" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_boxplot</span>() <span class="sc">+</span></span>
<span id="cb74-301"><a href="#cb74-301" aria-hidden="true" tabindex="-1"></a>  <span class="fu">xlab</span>(<span class="st">"Re-Hospitalization Rate"</span>) <span class="sc">+</span></span>
<span id="cb74-302"><a href="#cb74-302" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ylab</span>(<span class="st">"Count"</span>) <span class="sc">+</span></span>
<span id="cb74-303"><a href="#cb74-303" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_bw</span>()</span>
<span id="cb74-304"><a href="#cb74-304" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb74-305"><a href="#cb74-305" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb74-306"><a href="#cb74-306" aria-hidden="true" tabindex="-1"></a>Another right skewed variable. Lots of counties with 0.00 rates of re-hospitalization, and few, if any, above 0.50 per 100,000 people. The same can be said when comparing urban vs. rural, as there seems to be little variation. Rural counties do have more out-liers, as to be expected with low access to healthcare and quality healthcare services.From a health perspective, this is good news! From a research perspective, that's going to make analysis a little trickier. However, the somewhat normal and/or bimodal distribution should be fairly easy to work with. While needing some transformation for a linear regression, we can test multiple models per each variable to determine which amendment provides the most robust inference.</span>
<span id="cb74-307"><a href="#cb74-307" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb74-308"><a href="#cb74-308" aria-hidden="true" tabindex="-1"></a><span class="fu">## Analysis</span></span>
<span id="cb74-309"><a href="#cb74-309" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb74-310"><a href="#cb74-310" aria-hidden="true" tabindex="-1"></a><span class="fu">### Hypothesis Testing</span></span>
<span id="cb74-311"><a href="#cb74-311" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb74-312"><a href="#cb74-312" aria-hidden="true" tabindex="-1"></a>Remember that the hypothesis for this research report is:</span>
<span id="cb74-313"><a href="#cb74-313" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb74-314"><a href="#cb74-314" aria-hidden="true" tabindex="-1"></a><span class="ss">-   </span>Precipitation has a positive impact on re-hospitalization rates within rural counties.</span>
<span id="cb74-315"><a href="#cb74-315" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb74-316"><a href="#cb74-316" aria-hidden="true" tabindex="-1"></a>We have fifteen (15) explanatory variables to work with, so we can run different regressions to determine what variables influence re-hospitalization rates the most -- if at all -- and how they interact with other variables.</span>
<span id="cb74-317"><a href="#cb74-317" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb74-318"><a href="#cb74-318" aria-hidden="true" tabindex="-1"></a>Reminder that the fifteen (15) explanatory and control variables are broken down into three domains: the primary independent and dependent variables, socio-demographic variables, and economic variables.</span>
<span id="cb74-319"><a href="#cb74-319" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb74-320"><a href="#cb74-320" aria-hidden="true" tabindex="-1"></a>Independent and Dependent variables:</span>
<span id="cb74-321"><a href="#cb74-321" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb74-322"><a href="#cb74-322" aria-hidden="true" tabindex="-1"></a><span class="ss">-   </span>Average Annual Precipitation</span>
<span id="cb74-323"><a href="#cb74-323" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb74-324"><a href="#cb74-324" aria-hidden="true" tabindex="-1"></a><span class="ss">-   </span>Re-Hospitalization Rates</span>
<span id="cb74-325"><a href="#cb74-325" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb74-326"><a href="#cb74-326" aria-hidden="true" tabindex="-1"></a>Socio-demographic variables:</span>
<span id="cb74-327"><a href="#cb74-327" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb74-328"><a href="#cb74-328" aria-hidden="true" tabindex="-1"></a><span class="ss">-   </span>Percent Male</span>
<span id="cb74-329"><a href="#cb74-329" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb74-330"><a href="#cb74-330" aria-hidden="true" tabindex="-1"></a><span class="ss">-   </span>Percent Female</span>
<span id="cb74-331"><a href="#cb74-331" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb74-332"><a href="#cb74-332" aria-hidden="true" tabindex="-1"></a><span class="ss">-   </span>Percent American Indian</span>
<span id="cb74-333"><a href="#cb74-333" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb74-334"><a href="#cb74-334" aria-hidden="true" tabindex="-1"></a><span class="ss">-   </span>Percent Asian</span>
<span id="cb74-335"><a href="#cb74-335" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb74-336"><a href="#cb74-336" aria-hidden="true" tabindex="-1"></a><span class="ss">-   </span>Percent Black</span>
<span id="cb74-337"><a href="#cb74-337" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb74-338"><a href="#cb74-338" aria-hidden="true" tabindex="-1"></a><span class="ss">-   </span>Percent Hispanic</span>
<span id="cb74-339"><a href="#cb74-339" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb74-340"><a href="#cb74-340" aria-hidden="true" tabindex="-1"></a><span class="ss">-   </span>Percent Multiple Races</span>
<span id="cb74-341"><a href="#cb74-341" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb74-342"><a href="#cb74-342" aria-hidden="true" tabindex="-1"></a><span class="ss">-   </span>Percent Other Race</span>
<span id="cb74-343"><a href="#cb74-343" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb74-344"><a href="#cb74-344" aria-hidden="true" tabindex="-1"></a><span class="ss">-   </span>Percent White</span>
<span id="cb74-345"><a href="#cb74-345" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb74-346"><a href="#cb74-346" aria-hidden="true" tabindex="-1"></a>Economic variables:</span>
<span id="cb74-347"><a href="#cb74-347" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb74-348"><a href="#cb74-348" aria-hidden="true" tabindex="-1"></a><span class="ss">-   </span>Median Household Income</span>
<span id="cb74-349"><a href="#cb74-349" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb74-350"><a href="#cb74-350" aria-hidden="true" tabindex="-1"></a><span class="ss">-   </span>Percent Poverty</span>
<span id="cb74-351"><a href="#cb74-351" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb74-352"><a href="#cb74-352" aria-hidden="true" tabindex="-1"></a><span class="ss">-   </span>Percent Rental Housing Cost, over 50%</span>
<span id="cb74-353"><a href="#cb74-353" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb74-354"><a href="#cb74-354" aria-hidden="true" tabindex="-1"></a><span class="ss">-   </span>Percent Commuting Alone, over 60 minutes</span>
<span id="cb74-355"><a href="#cb74-355" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb74-356"><a href="#cb74-356" aria-hidden="true" tabindex="-1"></a>We will run four models to test the hypothesis. They shall examine each environmental variable's impact on the dependent variable, re-hospitalization rates. The control variables will be the socio-demographic and economic variables, thirteen (13) in total.</span>
<span id="cb74-357"><a href="#cb74-357" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb74-358"><a href="#cb74-358" aria-hidden="true" tabindex="-1"></a>Model 1 will take just the independent and dependent variables by themselves.</span>
<span id="cb74-359"><a href="#cb74-359" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb74-360"><a href="#cb74-360" aria-hidden="true" tabindex="-1"></a>Model 2 will add socio-demographic variables as control.</span>
<span id="cb74-361"><a href="#cb74-361" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb74-362"><a href="#cb74-362" aria-hidden="true" tabindex="-1"></a>Model 3 will add economic variables as control.</span>
<span id="cb74-363"><a href="#cb74-363" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb74-364"><a href="#cb74-364" aria-hidden="true" tabindex="-1"></a>Model 4 will add both socio-demographic and economic variables as control.</span>
<span id="cb74-365"><a href="#cb74-365" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb74-368"><a href="#cb74-368" aria-hidden="true" tabindex="-1"></a><span class="in">```{r}</span></span>
<span id="cb74-369"><a href="#cb74-369" aria-hidden="true" tabindex="-1"></a>df_new <span class="ot">&lt;-</span> df_new <span class="sc">%&gt;%</span></span>
<span id="cb74-370"><a href="#cb74-370" aria-hidden="true" tabindex="-1"></a>  <span class="fu">filter</span>(Rurality <span class="sc">==</span> <span class="st">"Rural"</span>) </span>
<span id="cb74-371"><a href="#cb74-371" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb74-372"><a href="#cb74-372" aria-hidden="true" tabindex="-1"></a>model1 <span class="ot">&lt;-</span> <span class="fu">lm</span>(LTC_AVG_OBS_REHOSP_RATE <span class="sc">~</span> </span>
<span id="cb74-373"><a href="#cb74-373" aria-hidden="true" tabindex="-1"></a>               NOAAC_PRECIPITATION_AVG_YEARLY,</span>
<span id="cb74-374"><a href="#cb74-374" aria-hidden="true" tabindex="-1"></a>             df_new)</span>
<span id="cb74-375"><a href="#cb74-375" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb74-376"><a href="#cb74-376" aria-hidden="true" tabindex="-1"></a>model2 <span class="ot">&lt;-</span> <span class="fu">lm</span>(LTC_AVG_OBS_REHOSP_RATE <span class="sc">~</span> </span>
<span id="cb74-377"><a href="#cb74-377" aria-hidden="true" tabindex="-1"></a>               NOAAC_PRECIPITATION_AVG_YEARLY <span class="sc">+</span></span>
<span id="cb74-378"><a href="#cb74-378" aria-hidden="true" tabindex="-1"></a>               ACS_PCT_MALE <span class="sc">+</span></span>
<span id="cb74-379"><a href="#cb74-379" aria-hidden="true" tabindex="-1"></a>               ACS_PCT_FEMALE <span class="sc">+</span></span>
<span id="cb74-380"><a href="#cb74-380" aria-hidden="true" tabindex="-1"></a>               ACS_PCT_AIAN <span class="sc">+</span></span>
<span id="cb74-381"><a href="#cb74-381" aria-hidden="true" tabindex="-1"></a>               ACS_PCT_ASIAN <span class="sc">+</span></span>
<span id="cb74-382"><a href="#cb74-382" aria-hidden="true" tabindex="-1"></a>               ACS_PCT_BLACK <span class="sc">+</span></span>
<span id="cb74-383"><a href="#cb74-383" aria-hidden="true" tabindex="-1"></a>               ACS_PCT_HISPANIC <span class="sc">+</span></span>
<span id="cb74-384"><a href="#cb74-384" aria-hidden="true" tabindex="-1"></a>               ACS_PCT_MULT_RACE <span class="sc">+</span></span>
<span id="cb74-385"><a href="#cb74-385" aria-hidden="true" tabindex="-1"></a>               ACS_PCT_NHPI <span class="sc">+</span></span>
<span id="cb74-386"><a href="#cb74-386" aria-hidden="true" tabindex="-1"></a>               ACS_PCT_OTHER_RACE <span class="sc">+</span></span>
<span id="cb74-387"><a href="#cb74-387" aria-hidden="true" tabindex="-1"></a>               ACS_PCT_WHITE,</span>
<span id="cb74-388"><a href="#cb74-388" aria-hidden="true" tabindex="-1"></a>             df_new)</span>
<span id="cb74-389"><a href="#cb74-389" aria-hidden="true" tabindex="-1"></a>  </span>
<span id="cb74-390"><a href="#cb74-390" aria-hidden="true" tabindex="-1"></a>model3 <span class="ot">&lt;-</span> <span class="fu">lm</span>(LTC_AVG_OBS_REHOSP_RATE <span class="sc">~</span> </span>
<span id="cb74-391"><a href="#cb74-391" aria-hidden="true" tabindex="-1"></a>               NOAAC_PRECIPITATION_AVG_YEARLY <span class="sc">+</span></span>
<span id="cb74-392"><a href="#cb74-392" aria-hidden="true" tabindex="-1"></a>               SAIPE_MEDIAN_HH_INCOME <span class="sc">+</span></span>
<span id="cb74-393"><a href="#cb74-393" aria-hidden="true" tabindex="-1"></a>               SAIPE_PCT_POV <span class="sc">+</span></span>
<span id="cb74-394"><a href="#cb74-394" aria-hidden="true" tabindex="-1"></a>               ACS_PCT_COMMT_60MINUP <span class="sc">+</span></span>
<span id="cb74-395"><a href="#cb74-395" aria-hidden="true" tabindex="-1"></a>               ACS_PCT_RENTER_HU_COST_50PCT,</span>
<span id="cb74-396"><a href="#cb74-396" aria-hidden="true" tabindex="-1"></a>             df_new)</span>
<span id="cb74-397"><a href="#cb74-397" aria-hidden="true" tabindex="-1"></a>  </span>
<span id="cb74-398"><a href="#cb74-398" aria-hidden="true" tabindex="-1"></a>model4 <span class="ot">&lt;-</span> <span class="fu">lm</span>(LTC_AVG_OBS_REHOSP_RATE <span class="sc">~</span> </span>
<span id="cb74-399"><a href="#cb74-399" aria-hidden="true" tabindex="-1"></a>               NOAAC_PRECIPITATION_AVG_YEARLY <span class="sc">+</span></span>
<span id="cb74-400"><a href="#cb74-400" aria-hidden="true" tabindex="-1"></a>               ACS_PCT_MALE <span class="sc">+</span></span>
<span id="cb74-401"><a href="#cb74-401" aria-hidden="true" tabindex="-1"></a>               ACS_PCT_FEMALE <span class="sc">+</span></span>
<span id="cb74-402"><a href="#cb74-402" aria-hidden="true" tabindex="-1"></a>               ACS_PCT_AIAN <span class="sc">+</span></span>
<span id="cb74-403"><a href="#cb74-403" aria-hidden="true" tabindex="-1"></a>               ACS_PCT_ASIAN <span class="sc">+</span></span>
<span id="cb74-404"><a href="#cb74-404" aria-hidden="true" tabindex="-1"></a>               ACS_PCT_BLACK <span class="sc">+</span></span>
<span id="cb74-405"><a href="#cb74-405" aria-hidden="true" tabindex="-1"></a>               ACS_PCT_HISPANIC <span class="sc">+</span></span>
<span id="cb74-406"><a href="#cb74-406" aria-hidden="true" tabindex="-1"></a>               ACS_PCT_MULT_RACE <span class="sc">+</span></span>
<span id="cb74-407"><a href="#cb74-407" aria-hidden="true" tabindex="-1"></a>               ACS_PCT_NHPI <span class="sc">+</span></span>
<span id="cb74-408"><a href="#cb74-408" aria-hidden="true" tabindex="-1"></a>               ACS_PCT_OTHER_RACE <span class="sc">+</span></span>
<span id="cb74-409"><a href="#cb74-409" aria-hidden="true" tabindex="-1"></a>               ACS_PCT_WHITE <span class="sc">+</span> </span>
<span id="cb74-410"><a href="#cb74-410" aria-hidden="true" tabindex="-1"></a>               SAIPE_MEDIAN_HH_INCOME <span class="sc">+</span></span>
<span id="cb74-411"><a href="#cb74-411" aria-hidden="true" tabindex="-1"></a>               SAIPE_PCT_POV <span class="sc">+</span></span>
<span id="cb74-412"><a href="#cb74-412" aria-hidden="true" tabindex="-1"></a>               ACS_PCT_COMMT_60MINUP <span class="sc">+</span></span>
<span id="cb74-413"><a href="#cb74-413" aria-hidden="true" tabindex="-1"></a>               ACS_PCT_RENTER_HU_COST_50PCT,</span>
<span id="cb74-414"><a href="#cb74-414" aria-hidden="true" tabindex="-1"></a>             df_new)</span>
<span id="cb74-415"><a href="#cb74-415" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb74-416"><a href="#cb74-416" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb74-417"><a href="#cb74-417" aria-hidden="true" tabindex="-1"></a>Let's plot this regression. We will employ log transformations for re-hospitalization rates, as it is skewed. </span>
<span id="cb74-418"><a href="#cb74-418" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb74-421"><a href="#cb74-421" aria-hidden="true" tabindex="-1"></a><span class="in">```{r}</span></span>
<span id="cb74-422"><a href="#cb74-422" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(df_new, <span class="fu">aes</span>(NOAAC_PRECIPITATION_AVG_YEARLY,</span>
<span id="cb74-423"><a href="#cb74-423" aria-hidden="true" tabindex="-1"></a>                   <span class="fu">log</span>(LTC_AVG_OBS_REHOSP_RATE))) <span class="sc">+</span></span>
<span id="cb74-424"><a href="#cb74-424" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_point</span>(<span class="at">color =</span> <span class="st">"#881c1c"</span>,</span>
<span id="cb74-425"><a href="#cb74-425" aria-hidden="true" tabindex="-1"></a>             <span class="at">alpha =</span> <span class="fl">0.3</span>) <span class="sc">+</span></span>
<span id="cb74-426"><a href="#cb74-426" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_smooth</span>(<span class="at">method =</span> lm,</span>
<span id="cb74-427"><a href="#cb74-427" aria-hidden="true" tabindex="-1"></a>              <span class="at">se =</span> <span class="cn">FALSE</span>,</span>
<span id="cb74-428"><a href="#cb74-428" aria-hidden="true" tabindex="-1"></a>              <span class="at">fullrange =</span> <span class="cn">TRUE</span>,</span>
<span id="cb74-429"><a href="#cb74-429" aria-hidden="true" tabindex="-1"></a>              <span class="at">color=</span> <span class="st">"#212721"</span>) <span class="sc">+</span></span>
<span id="cb74-430"><a href="#cb74-430" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">title =</span> <span class="st">"Simple Linear Regression Model, Precipitation Against Re-Hospitalization"</span>,</span>
<span id="cb74-431"><a href="#cb74-431" aria-hidden="true" tabindex="-1"></a>       <span class="at">x =</span> <span class="st">"Average Annual Precipitation"</span>,</span>
<span id="cb74-432"><a href="#cb74-432" aria-hidden="true" tabindex="-1"></a>       <span class="at">y =</span> <span class="st">"Re-Hospitalization Rates"</span>) <span class="sc">+</span></span>
<span id="cb74-433"><a href="#cb74-433" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_bw</span>()</span>
<span id="cb74-434"><a href="#cb74-434" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb74-435"><a href="#cb74-435" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb74-436"><a href="#cb74-436" aria-hidden="true" tabindex="-1"></a>We will reject the null hypothesis. While it looks like, at first glance, that there is little positive relationship, we can at least note that there is *some* positive relationship. In the next two sections, we will dig deeper into each model, examining the p-value, R-Squared value, and PRESS statistic to see what level of relationship is present.</span>
<span id="cb74-437"><a href="#cb74-437" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb74-438"><a href="#cb74-438" aria-hidden="true" tabindex="-1"></a><span class="fu">### Model Comparisons</span></span>
<span id="cb74-439"><a href="#cb74-439" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb74-440"><a href="#cb74-440" aria-hidden="true" tabindex="-1"></a>Now we will compare the four (4) models in more depth.</span>
<span id="cb74-441"><a href="#cb74-441" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb74-444"><a href="#cb74-444" aria-hidden="true" tabindex="-1"></a><span class="in">```{r}</span></span>
<span id="cb74-445"><a href="#cb74-445" aria-hidden="true" tabindex="-1"></a><span class="fu">stargazer</span>(model1,</span>
<span id="cb74-446"><a href="#cb74-446" aria-hidden="true" tabindex="-1"></a>          model2,</span>
<span id="cb74-447"><a href="#cb74-447" aria-hidden="true" tabindex="-1"></a>          model3,</span>
<span id="cb74-448"><a href="#cb74-448" aria-hidden="true" tabindex="-1"></a>          model4,</span>
<span id="cb74-449"><a href="#cb74-449" aria-hidden="true" tabindex="-1"></a>          <span class="at">type =</span> <span class="st">"pdf"</span>,</span>
<span id="cb74-450"><a href="#cb74-450" aria-hidden="true" tabindex="-1"></a>          <span class="at">title =</span> <span class="st">"Regression Results, Models 1 - 4"</span>,</span>
<span id="cb74-451"><a href="#cb74-451" aria-hidden="true" tabindex="-1"></a>          <span class="at">out =</span> <span class="st">"models.pdf"</span>)</span>
<span id="cb74-452"><a href="#cb74-452" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(model1)</span>
<span id="cb74-453"><a href="#cb74-453" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(model2)</span>
<span id="cb74-454"><a href="#cb74-454" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(model3)</span>
<span id="cb74-455"><a href="#cb74-455" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(model4)</span>
<span id="cb74-456"><a href="#cb74-456" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb74-457"><a href="#cb74-457" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb74-458"><a href="#cb74-458" aria-hidden="true" tabindex="-1"></a>We want to look for two items in particular: 1) P-values that reach significant code of *** and 2) The highest Adjusted R-squared value.</span>
<span id="cb74-459"><a href="#cb74-459" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb74-460"><a href="#cb74-460" aria-hidden="true" tabindex="-1"></a>Model 1's <span class="in">`Precipitation`</span> variable has the highest P-value compared to the other models, and the lowest Adjusted R-squared value.</span>
<span id="cb74-461"><a href="#cb74-461" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb74-462"><a href="#cb74-462" aria-hidden="true" tabindex="-1"></a>Model 2's significant variables are <span class="in">`Precipitation`</span> and <span class="in">`Hispanic Rate.`</span> However, the <span class="in">`Hispanic Rate`</span> does not meet the significant code of ***. The Adjusted R-squared value is only slightly higher than Model 1.</span>
<span id="cb74-463"><a href="#cb74-463" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb74-464"><a href="#cb74-464" aria-hidden="true" tabindex="-1"></a>Model 3's significant variables are <span class="in">`Precipitation,`</span> <span class="in">`Percent Poverty,`</span> and <span class="in">`Commuting.`</span> However, neither <span class="in">`Percent Poverty`</span> nor <span class="in">`Commuting`</span> meet ***. The Adjusted R-squared value is close to Model 4, so it appears that the economic variables have a higher impact over socio-demographic measures.</span>
<span id="cb74-465"><a href="#cb74-465" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb74-466"><a href="#cb74-466" aria-hidden="true" tabindex="-1"></a>Model 4's significant variables are <span class="in">`Precipitation,`</span> <span class="in">`Percent Poverty,`</span> and <span class="in">`Commuting.`</span> <span class="in">`Precipitation`</span> has the lowest P-value of the four models here, and <span class="in">`Percent Poverty`</span> meets the significance threshold of ***. The Adjusted R-squared value is the highest here, though only at 0.076.</span>
<span id="cb74-467"><a href="#cb74-467" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb74-468"><a href="#cb74-468" aria-hidden="true" tabindex="-1"></a>Finally, we're going to calculate the PRESS statistic (Predicted Residual Sum of Squares) to best determine which model can predict the response variable based upon the explanatory variables.</span>
<span id="cb74-469"><a href="#cb74-469" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb74-472"><a href="#cb74-472" aria-hidden="true" tabindex="-1"></a><span class="in">```{r}</span></span>
<span id="cb74-473"><a href="#cb74-473" aria-hidden="true" tabindex="-1"></a>PRESS <span class="ot">&lt;-</span> <span class="cf">function</span>(model) {</span>
<span id="cb74-474"><a href="#cb74-474" aria-hidden="true" tabindex="-1"></a>  i <span class="ot">&lt;-</span> <span class="fu">residuals</span>(model)<span class="sc">/</span>(<span class="dv">1</span> <span class="sc">-</span> <span class="fu">lm.influence</span>(model)<span class="sc">$</span>hat)</span>
<span id="cb74-475"><a href="#cb74-475" aria-hidden="true" tabindex="-1"></a>  <span class="fu">sum</span>(i<span class="sc">^</span><span class="dv">2</span>)</span>
<span id="cb74-476"><a href="#cb74-476" aria-hidden="true" tabindex="-1"></a>}</span>
<span id="cb74-477"><a href="#cb74-477" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb74-478"><a href="#cb74-478" aria-hidden="true" tabindex="-1"></a><span class="fu">PRESS</span>(model1)</span>
<span id="cb74-479"><a href="#cb74-479" aria-hidden="true" tabindex="-1"></a><span class="fu">PRESS</span>(model2)</span>
<span id="cb74-480"><a href="#cb74-480" aria-hidden="true" tabindex="-1"></a><span class="fu">PRESS</span>(model3)</span>
<span id="cb74-481"><a href="#cb74-481" aria-hidden="true" tabindex="-1"></a><span class="fu">PRESS</span>(model4)</span>
<span id="cb74-482"><a href="#cb74-482" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb74-483"><a href="#cb74-483" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb74-484"><a href="#cb74-484" aria-hidden="true" tabindex="-1"></a>Model 3 has the lowest PRESS score, though Model 4 is not being calculated for some reason. This is probably due to an error with a socio-demographic variable.</span>
<span id="cb74-485"><a href="#cb74-485" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb74-486"><a href="#cb74-486" aria-hidden="true" tabindex="-1"></a>Due to a strong p-value, Adjusted R-squared value, and model fit compared to the other three models, Model 4 will be chosen as the final model for the diagnostic exploration. </span>
<span id="cb74-487"><a href="#cb74-487" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb74-488"><a href="#cb74-488" aria-hidden="true" tabindex="-1"></a><span class="fu">### Diagnostics</span></span>
<span id="cb74-489"><a href="#cb74-489" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb74-490"><a href="#cb74-490" aria-hidden="true" tabindex="-1"></a>Finally, we'll plot the diagnostics to best understand the model.</span>
<span id="cb74-491"><a href="#cb74-491" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb74-494"><a href="#cb74-494" aria-hidden="true" tabindex="-1"></a><span class="in">```{r}</span></span>
<span id="cb74-495"><a href="#cb74-495" aria-hidden="true" tabindex="-1"></a><span class="fu">par</span>(<span class="at">mfrow =</span> <span class="fu">c</span>(<span class="dv">2</span>,<span class="dv">3</span>));</span>
<span id="cb74-496"><a href="#cb74-496" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(model4, </span>
<span id="cb74-497"><a href="#cb74-497" aria-hidden="true" tabindex="-1"></a>     <span class="at">which =</span> <span class="dv">1</span><span class="sc">:</span><span class="dv">6</span>) <span class="sc">+</span></span>
<span id="cb74-498"><a href="#cb74-498" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_bw</span>()</span>
<span id="cb74-499"><a href="#cb74-499" aria-hidden="true" tabindex="-1"></a><span class="fu">ggsave</span>(<span class="st">"diagnostics.pdf"</span>,</span>
<span id="cb74-500"><a href="#cb74-500" aria-hidden="true" tabindex="-1"></a>       <span class="at">device =</span> <span class="st">"pdf"</span>)</span>
<span id="cb74-501"><a href="#cb74-501" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb74-502"><a href="#cb74-502" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb74-503"><a href="#cb74-503" aria-hidden="true" tabindex="-1"></a>Of the six plots, Cook's distance is the most striking and relevant, as there are three out-liers: 683, 1345, and 1508.</span>
<span id="cb74-504"><a href="#cb74-504" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb74-507"><a href="#cb74-507" aria-hidden="true" tabindex="-1"></a><span class="in">```{r}</span></span>
<span id="cb74-508"><a href="#cb74-508" aria-hidden="true" tabindex="-1"></a>df_new <span class="sc">%&gt;%</span></span>
<span id="cb74-509"><a href="#cb74-509" aria-hidden="true" tabindex="-1"></a>  <span class="fu">filter</span>(COUNTYFIPS <span class="sc">==</span> <span class="st">"26097"</span> <span class="sc">|</span> COUNTYFIPS <span class="sc">==</span> <span class="st">"46079"</span> <span class="sc">|</span> COUNTYFIPS <span class="sc">==</span> <span class="st">"48385"</span>) <span class="sc">%&gt;%</span></span>
<span id="cb74-510"><a href="#cb74-510" aria-hidden="true" tabindex="-1"></a>  <span class="fu">head</span>()</span>
<span id="cb74-511"><a href="#cb74-511" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb74-512"><a href="#cb74-512" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb74-513"><a href="#cb74-513" aria-hidden="true" tabindex="-1"></a>683 is Mackinac County, Michigan, one of the most remote areas in the Great Lakes, with a population of 10,906.</span>
<span id="cb74-514"><a href="#cb74-514" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb74-515"><a href="#cb74-515" aria-hidden="true" tabindex="-1"></a>1345 is Mellette County, South Dakota, with a population of 1,908.</span>
<span id="cb74-516"><a href="#cb74-516" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb74-517"><a href="#cb74-517" aria-hidden="true" tabindex="-1"></a>1508 is Real County, Texas, a county with only one incorporated area and a population of 2,826.</span>
<span id="cb74-518"><a href="#cb74-518" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb74-519"><a href="#cb74-519" aria-hidden="true" tabindex="-1"></a>Otherwise, the plot looks good.</span>
<span id="cb74-520"><a href="#cb74-520" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb74-521"><a href="#cb74-521" aria-hidden="true" tabindex="-1"></a>Normal Q-Q violates this test, as the points at the right tail of the plot do not generally fall along the line. This is very apparent for our three out-liers. Cook's Distance vs. Leverage violates this test as well. The remaining plots do not violate their tested assumptions and further cement the model's reliability.</span>
<span id="cb74-522"><a href="#cb74-522" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb74-523"><a href="#cb74-523" aria-hidden="true" tabindex="-1"></a><span class="fu">## Conclusion</span></span>
<span id="cb74-524"><a href="#cb74-524" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb74-525"><a href="#cb74-525" aria-hidden="true" tabindex="-1"></a>This paper explored the relationship between re-hospitalization rates and precipitation, when controlling for common variables that regularly influence the dependent variable.</span>
<span id="cb74-526"><a href="#cb74-526" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb74-527"><a href="#cb74-527" aria-hidden="true" tabindex="-1"></a>Four models were selected, one for each variable, to best determine which measure best impacted re-hospitalization rates. In all of the models, precipitation was statistically significant. While the adjusted R-squared value is negligible (0.076), there is a positive relationship that is statistically significant. Therein we see some form of an influence large amounts of annual precipitation has on re-hospitalization rates.</span>
<span id="cb74-528"><a href="#cb74-528" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb74-529"><a href="#cb74-529" aria-hidden="true" tabindex="-1"></a><span class="fu">## References</span></span>
<span id="cb74-530"><a href="#cb74-530" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb74-531"><a href="#cb74-531" aria-hidden="true" tabindex="-1"></a>Barnett, M., Hsu, J. &amp; McWilliams, M. (2015). "Patient Characteristics and Differences in Hospital Readmission Rates." JAMA Intern Med., 175(11): 1803-1812.</span>
<span id="cb74-532"><a href="#cb74-532" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb74-533"><a href="#cb74-533" aria-hidden="true" tabindex="-1"></a>Bhosale KH, Nath RK, Pandit N, Agarwal P, Khairnar S, Yadav B, &amp; Chandrakar S. (2020). "Rate of Rehospitalization in 60 Days of Discharge and It's Determinants in Patients with Heart Failure with Reduced Ejection Fraction in a Tertiary Care Centre in India." Int J Heart Fail. 21;2(2):131-144.</span>
<span id="cb74-534"><a href="#cb74-534" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb74-535"><a href="#cb74-535" aria-hidden="true" tabindex="-1"></a>Li, Y., Cai, X. &amp; Glance, L. (2015). "Disparities in 30-day rehospitalization rates among Medicare skilled nursing facility residents by race and site of care." Med Care, 53(12): 1058-1065.</span>
<span id="cb74-536"><a href="#cb74-536" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb74-537"><a href="#cb74-537" aria-hidden="true" tabindex="-1"></a>Murray, F., Allen, M., Clark, C., Daly, C. &amp; Jacobs, D. (2021). "Socio-demographic and -economic factors associated with 30-day readmission for conditions targeted by the hospital readmissions reduction program: a population-based study." BMC Public Health, 21.</span>
<span id="cb74-538"><a href="#cb74-538" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb74-539"><a href="#cb74-539" aria-hidden="true" tabindex="-1"></a>Rizmie, D., Preuz, L., Miraldo, M. &amp; Atun, R. (2022). "Impact of extreme temperatures on emergency hospital admissions by age and socio-economic deprivation in England." Social Science &amp; Medicine, 308.</span>
<span id="cb74-540"><a href="#cb74-540" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb74-541"><a href="#cb74-541" aria-hidden="true" tabindex="-1"></a>Tapak, L., Maryanaji, Z., Hamidi, O., Abbasi, H. &amp; Najafi-Vosough, R. (2018). "Investigating the effect of climatic parameters on mental disorder admissions." International Journal of Biometerology, 62, 2109-2118.</span>
<span id="cb74-542"><a href="#cb74-542" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb74-543"><a href="#cb74-543" aria-hidden="true" tabindex="-1"></a>Trinh, T., Feeny, S. &amp; Posso, A. (2018). "Rainfall shocks and child health: the role of parental mental health." Climate and Development, 13(1), 34-48.</span>
<span id="cb74-544"><a href="#cb74-544" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb74-545"><a href="#cb74-545" aria-hidden="true" tabindex="-1"></a>Spatz, E., Bernheim, S., Horwitz, L. &amp; Herrin, J. (2020). Community factors and hospital wide readmission rates: Does context matter? PLoS One, 15(10).</span>
</code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div></div></div></div></div>
</div> <!-- /content -->



</body></html>