<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.0.37">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">

<meta name="author" content="Lindsay Jones">
<meta name="dcterms.date" content="2022-11-14">
<meta name="description" content="The fourth homework">

<title>- Homework 4</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
span.underline{text-decoration: underline;}
div.column{display: inline-block; vertical-align: top; width: 50%;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
    color: #aaaaaa;
  }
pre.numberSource { margin-left: 3em; border-left: 1px solid #aaaaaa;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
code span.al { color: #ff0000; font-weight: bold; } /* Alert */
code span.an { color: #60a0b0; font-weight: bold; font-style: italic; } /* Annotation */
code span.at { color: #7d9029; } /* Attribute */
code span.bn { color: #40a070; } /* BaseN */
code span.bu { } /* BuiltIn */
code span.cf { color: #007020; font-weight: bold; } /* ControlFlow */
code span.ch { color: #4070a0; } /* Char */
code span.cn { color: #880000; } /* Constant */
code span.co { color: #60a0b0; font-style: italic; } /* Comment */
code span.cv { color: #60a0b0; font-weight: bold; font-style: italic; } /* CommentVar */
code span.do { color: #ba2121; font-style: italic; } /* Documentation */
code span.dt { color: #902000; } /* DataType */
code span.dv { color: #40a070; } /* DecVal */
code span.er { color: #ff0000; font-weight: bold; } /* Error */
code span.ex { } /* Extension */
code span.fl { color: #40a070; } /* Float */
code span.fu { color: #06287e; } /* Function */
code span.im { } /* Import */
code span.in { color: #60a0b0; font-weight: bold; font-style: italic; } /* Information */
code span.kw { color: #007020; font-weight: bold; } /* Keyword */
code span.op { color: #666666; } /* Operator */
code span.ot { color: #007020; } /* Other */
code span.pp { color: #bc7a00; } /* Preprocessor */
code span.sc { color: #4070a0; } /* SpecialChar */
code span.ss { color: #bb6688; } /* SpecialString */
code span.st { color: #4070a0; } /* String */
code span.va { color: #19177c; } /* Variable */
code span.vs { color: #4070a0; } /* VerbatimString */
code span.wa { color: #60a0b0; font-weight: bold; font-style: italic; } /* Warning */
</style>


<script src="../site_libs/quarto-nav/quarto-nav.js"></script>
<script src="../site_libs/quarto-nav/headroom.min.js"></script>
<script src="../site_libs/clipboard/clipboard.min.js"></script>
<script src="../site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="../site_libs/quarto-search/fuse.min.js"></script>
<script src="../site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="../">
<link href="../images/DACSS_Round_Network.png" rel="icon" type="image/png">
<script src="../site_libs/quarto-html/quarto.js"></script>
<script src="../site_libs/quarto-html/popper.min.js"></script>
<script src="../site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="../site_libs/quarto-html/anchor.min.js"></script>
<link href="../site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="../site_libs/quarto-html/quarto-syntax-highlighting.css" rel="stylesheet" class="quarto-color-scheme" id="quarto-text-highlighting-styles">
<link href="../site_libs/quarto-html/quarto-syntax-highlighting-dark.css" rel="prefetch" class="quarto-color-scheme quarto-color-alternate" id="quarto-text-highlighting-styles">
<script src="../site_libs/bootstrap/bootstrap.min.js"></script>
<link href="../site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="../site_libs/bootstrap/bootstrap.min.css" rel="stylesheet" class="quarto-color-scheme" id="quarto-bootstrap" data-mode="light">
<link href="../site_libs/bootstrap/bootstrap-dark.min.css" rel="prefetch" class="quarto-color-scheme quarto-color-alternate" id="quarto-bootstrap" data-mode="dark">
<script id="quarto-search-options" type="application/json">{
  "location": "navbar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "end",
  "type": "overlay",
  "limit": 20,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit"
  }
}</script>


<meta name="twitter:title" content="- Homework 4">
<meta name="twitter:description" content="The fourth homework">
<meta name="twitter:creator" content="@UMassDACSS">
<meta name="twitter:card" content="summary">
</head>

<body class="nav-fixed">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
    <nav class="navbar navbar-expand-lg navbar-dark ">
      <div class="navbar-container container-fluid">
      <a class="navbar-brand" href="../index.html">
    <img src="../images/UMass White Wordmark Horiz.png" alt="">
  </a>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse" aria-controls="navbarCollapse" aria-expanded="false" aria-label="Toggle navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
  <span class="navbar-toggler-icon"></span>
</button>
          <div class="collapse navbar-collapse" id="navbarCollapse">
            <ul class="navbar-nav navbar-nav-scroll ms-auto">
  <li class="nav-item">
    <a class="nav-link" href="https://dacss.github.io/603_Fall_2022/">Fall 2022 Posts</a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="../about.html">Contributors</a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="https://umass.edu/sbs/dacss">DACSS</a>
  </li>  
  <li class="nav-item compact">
    <a class="nav-link" href="https://github.com/DACSS/603_Fall_2022"><i class="bi bi-github" role="img" aria-label="GitHub">
</i> 
 </a>
  </li>  
</ul>
              <div class="quarto-toggle-container">
                  <a href="" class="quarto-color-scheme-toggle nav-link" onclick="window.quartoToggleColorScheme(); return false;" title="Toggle dark mode"><i class="bi"></i></a>
              </div>
              <div id="quarto-search" class="" title="Search"></div>
          </div> <!-- /navcollapse -->
      </div> <!-- /container-fluid -->
    </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article page-navbar">
<!-- sidebar -->
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc">
    <h2 id="toc-title">On this page</h2>
   
  <ul>
  <li><a href="#homework-4" id="toc-homework-4" class="nav-link active" data-scroll-target="#homework-4">Homework 4</a>
  <ul class="collapse">
  <li><a href="#setup" id="toc-setup" class="nav-link" data-scroll-target="#setup">Setup</a></li>
  <li><a href="#question-1" id="toc-question-1" class="nav-link" data-scroll-target="#question-1">Question 1</a>
  <ul class="collapse">
  <li><a href="#a" id="toc-a" class="nav-link" data-scroll-target="#a">A</a></li>
  <li><a href="#b" id="toc-b" class="nav-link" data-scroll-target="#b">B</a></li>
  <li><a href="#c" id="toc-c" class="nav-link" data-scroll-target="#c">C</a></li>
  </ul></li>
  <li><a href="#question-2" id="toc-question-2" class="nav-link" data-scroll-target="#question-2">Question 2</a>
  <ul class="collapse">
  <li><a href="#a-1" id="toc-a-1" class="nav-link" data-scroll-target="#a-1">A</a></li>
  <li><a href="#b-1" id="toc-b-1" class="nav-link" data-scroll-target="#b-1">B</a></li>
  <li><a href="#c-1" id="toc-c-1" class="nav-link" data-scroll-target="#c-1">C</a></li>
  <li><a href="#d" id="toc-d" class="nav-link" data-scroll-target="#d">D</a></li>
  <li><a href="#e" id="toc-e" class="nav-link" data-scroll-target="#e">E</a></li>
  <li><a href="#f" id="toc-f" class="nav-link" data-scroll-target="#f">F</a></li>
  </ul></li>
  <li><a href="#question-3" id="toc-question-3" class="nav-link" data-scroll-target="#question-3">Question 3</a>
  <ul class="collapse">
  <li><a href="#a-2" id="toc-a-2" class="nav-link" data-scroll-target="#a-2">A</a></li>
  <li><a href="#b-2" id="toc-b-2" class="nav-link" data-scroll-target="#b-2">B</a></li>
  <li><a href="#c-2" id="toc-c-2" class="nav-link" data-scroll-target="#c-2">C</a></li>
  <li><a href="#d-1" id="toc-d-1" class="nav-link" data-scroll-target="#d-1">D</a></li>
  <li><a href="#e-1" id="toc-e-1" class="nav-link" data-scroll-target="#e-1">E</a></li>
  <li><a href="#f-1" id="toc-f-1" class="nav-link" data-scroll-target="#f-1">F</a></li>
  <li><a href="#g" id="toc-g" class="nav-link" data-scroll-target="#g">G</a></li>
  <li><a href="#h" id="toc-h" class="nav-link" data-scroll-target="#h">H</a></li>
  </ul></li>
  </ul></li>
  </ul>
</nav>
    </div>
<!-- main -->
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<div class="quarto-title-block"><div><h1 class="title">Homework 4</h1><button type="button" class="btn code-tools-button dropdown-toggle" id="quarto-code-tools-menu" data-bs-toggle="dropdown" aria-expanded="false"><i class="bi"></i> Code</button><ul class="dropdown-menu dropdown-menu-end" aria-labelelledby="quarto-code-tools-menu"><li><a id="quarto-show-all-code" class="dropdown-item" href="javascript:void(0)" role="button">Show All Code</a></li><li><a id="quarto-hide-all-code" class="dropdown-item" href="javascript:void(0)" role="button">Hide All Code</a></li><li><hr class="dropdown-divider"></li><li><a id="quarto-view-source" class="dropdown-item" href="javascript:void(0)" role="button">View Source</a></li></ul></div></div>
  <div class="quarto-categories">
    <div class="quarto-category">hw4</div>
  </div>
  </div>

<div>
  <div class="description">
    The fourth homework
  </div>
</div>


<div class="quarto-title-meta">

    <div>
    <div class="quarto-title-meta-heading">Author</div>
    <div class="quarto-title-meta-contents">
             <p>Lindsay Jones </p>
          </div>
  </div>
    
    <div>
    <div class="quarto-title-meta-heading">Published</div>
    <div class="quarto-title-meta-contents">
      <p class="date">November 14, 2022</p>
    </div>
  </div>
    
  </div>
  

</header>

<section id="homework-4" class="level1">
<h1>Homework 4</h1>
<section id="setup" class="level2">
<h2 class="anchored" data-anchor-id="setup">Setup</h2>
<div class="cell">
<details>
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb1"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(alr4)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stderr">
<pre><code>Loading required package: car</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Loading required package: carData</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Loading required package: effects</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>lattice theme set by effectsTheme()
See ?effectsTheme for details.</code></pre>
</div>
<details>
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb6"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb6-1"><a href="#cb6-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(smss)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
</div>
</section>
<section id="question-1" class="level2">
<h2 class="anchored" data-anchor-id="question-1">Question 1</h2>
<p>For recent data in Jacksonville, Florida, on y = selling price of home (in dollars), x₁ = size of home (in square feet), and x₂ = lot size (in square feet), the prediction equation is ŷ = −10,536 + 53.8x₁ + 2.84x₂.</p>
<section id="a" class="level3">
<h3 class="anchored" data-anchor-id="a">A</h3>
<p>A particular home of 1240 square feet on a lot of 18,000 square feet sold for $145,000. Find the predicted selling price and the residual, and interpret.</p>
<div class="cell">
<details>
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb7"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb7-1"><a href="#cb7-1" aria-hidden="true" tabindex="-1"></a><span class="co">#plug variables into equation</span></span>
<span id="cb7-2"><a href="#cb7-2" aria-hidden="true" tabindex="-1"></a>x1 <span class="ot">=</span> <span class="dv">1240</span></span>
<span id="cb7-3"><a href="#cb7-3" aria-hidden="true" tabindex="-1"></a>x2 <span class="ot">=</span> <span class="dv">18000</span></span>
<span id="cb7-4"><a href="#cb7-4" aria-hidden="true" tabindex="-1"></a>y <span class="ot">=</span> <span class="dv">145000</span></span>
<span id="cb7-5"><a href="#cb7-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb7-6"><a href="#cb7-6" aria-hidden="true" tabindex="-1"></a>ybar1 <span class="ot">&lt;-</span> (<span class="sc">-</span><span class="dv">10536</span>)<span class="sc">+</span>(<span class="fl">53.8</span><span class="sc">*</span>x1)<span class="sc">+</span>(<span class="fl">2.84</span><span class="sc">*</span>x2)</span>
<span id="cb7-7"><a href="#cb7-7" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb7-8"><a href="#cb7-8" aria-hidden="true" tabindex="-1"></a>ybar1</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 107296</code></pre>
</div>
</div>
<div class="cell">
<details>
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb9"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb9-1"><a href="#cb9-1" aria-hidden="true" tabindex="-1"></a><span class="co">#subtract predicted from actual to find residual</span></span>
<span id="cb9-2"><a href="#cb9-2" aria-hidden="true" tabindex="-1"></a>y <span class="sc">-</span> ybar1</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 37704</code></pre>
</div>
</div>
<p>The house sold for $37,704 greater than predicted.</p>
</section>
<section id="b" class="level3">
<h3 class="anchored" data-anchor-id="b">B</h3>
<p>For fixed lot size, how much is the house selling price predicted to increase for each square-foot increase in home size? Why?</p>
<div class="cell">
<details>
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb11"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb11-1"><a href="#cb11-1" aria-hidden="true" tabindex="-1"></a><span class="co">#plug variables into equation</span></span>
<span id="cb11-2"><a href="#cb11-2" aria-hidden="true" tabindex="-1"></a>x1f <span class="ot">=</span> <span class="dv">1241</span> <span class="co">#increased size by 1 square foot</span></span>
<span id="cb11-3"><a href="#cb11-3" aria-hidden="true" tabindex="-1"></a>x2f <span class="ot">=</span> <span class="dv">18000</span></span>
<span id="cb11-4"><a href="#cb11-4" aria-hidden="true" tabindex="-1"></a>yf <span class="ot">=</span> <span class="dv">145000</span></span>
<span id="cb11-5"><a href="#cb11-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb11-6"><a href="#cb11-6" aria-hidden="true" tabindex="-1"></a>ybar1f <span class="ot">&lt;-</span> (<span class="sc">-</span><span class="dv">10536</span>)<span class="sc">+</span>(<span class="fl">53.8</span><span class="sc">*</span>x1f)<span class="sc">+</span>(<span class="fl">2.84</span><span class="sc">*</span>x2f)</span>
<span id="cb11-7"><a href="#cb11-7" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb11-8"><a href="#cb11-8" aria-hidden="true" tabindex="-1"></a><span class="co">#subtract old predicted price from new predicted price</span></span>
<span id="cb11-9"><a href="#cb11-9" aria-hidden="true" tabindex="-1"></a>ybar1f<span class="sc">-</span>ybar1 </span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 53.8</code></pre>
</div>
</div>
<p>In the given equation ŷ = −10,536 + 53.8x₁ + 2.84x₂, the slope coefficient for x₁ (size of home) is 53.8, meaning for every 1-foot increase in square footage the house selling price increases by $53.80. In the code above I demonstrate this by taking my code from part A and increasing square footage by 1, then subtracting part A’s solution from the new solution.</p>
</section>
<section id="c" class="level3">
<h3 class="anchored" data-anchor-id="c">C</h3>
<p>According to this prediction equation, for fixed home size, how much would lot size need to increase to have the same impact as a one-square-foot increase in home size?</p>
<div class="cell">
<details>
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb13"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb13-1"><a href="#cb13-1" aria-hidden="true" tabindex="-1"></a><span class="fl">53.8</span><span class="sc">/</span><span class="fl">2.84</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 18.94366</code></pre>
</div>
</div>
<p>The slope coefficient for x₂ (lot size) is 2.84, meaning for every 1-foot increase in lot size the house selling price increases by $2.84. We can use the equation 2.84 * x₂ = 53.8 to calculate what increase in lot size is needed to have the same value increase in home size. We can simplify this equation as 53.8/2.84, which equals about 18.94 square feet.</p>
</section>
</section>
<section id="question-2" class="level2">
<h2 class="anchored" data-anchor-id="question-2">Question 2</h2>
<p>The data file concerns salary and other characteristics of all faculty in a small Midwestern college collected in the early 1980s for presentation in legal proceedings for which discrimination against women in salary was at issue. All persons in the data hold tenured or tenure track positions; temporary faculty are not included. The variables include degree, a factor with levels PhD and MS; rank, a factor with levels Asst, Assoc, and Prof; sex, a factor with levels Male and Female; Year, years in current rank; ysdeg, years since highest degree, and salary, academic year salary in dollars.</p>
<div class="cell">
<details>
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb15"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb15-1"><a href="#cb15-1" aria-hidden="true" tabindex="-1"></a><span class="fu">head</span>(salary)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>   degree rank    sex year ysdeg salary
1 Masters Prof   Male   25    35  36350
2 Masters Prof   Male   13    22  35350
3 Masters Prof   Male   10    23  28200
4 Masters Prof Female    7    27  26775
5     PhD Prof   Male   19    30  33696
6 Masters Prof   Male   16    21  28516</code></pre>
</div>
</div>
<section id="a-1" class="level3">
<h3 class="anchored" data-anchor-id="a-1">A</h3>
<p>Test the hypothesis that the mean salary for men and women is the same, without regard to any other variable but sex. Explain your findings.</p>
<p>The null hypothesis is that the mean salary for men is the same as the mean salary for women, controlling for other variables. The alternative hypothesis is that the mean salary for men is NOT the same as the mean salary for women, controlling for other variables.</p>
<div class="cell">
<details>
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb17"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb17-1"><a href="#cb17-1" aria-hidden="true" tabindex="-1"></a><span class="fu">t.test</span>(salary <span class="sc">~</span> sex, <span class="at">data =</span> salary, <span class="at">var.equal =</span> <span class="cn">TRUE</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>
    Two Sample t-test

data:  salary by sex
t = 1.8474, df = 50, p-value = 0.0706
alternative hypothesis: true difference in means between group Male and group Female is not equal to 0
95 percent confidence interval:
 -291.257 6970.550
sample estimates:
  mean in group Male mean in group Female 
            24696.79             21357.14 </code></pre>
</div>
</div>
<p>The t-test shows that the mean salaries for each sex are different, but since the p-value is greater than .05, we fail to reject the null hypothesis.</p>
</section>
<section id="b-1" class="level3">
<h3 class="anchored" data-anchor-id="b-1">B</h3>
<p>Run a multiple linear regression with salary as the outcome variable and everything else as predictors, including sex. Assuming no interactions between sex and the other predictors, obtain a 95% confidence interval for the difference in salary between males and females.</p>
<div class="cell">
<details>
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb19"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb19-1"><a href="#cb19-1" aria-hidden="true" tabindex="-1"></a><span class="co">#run multiple linear regression</span></span>
<span id="cb19-2"><a href="#cb19-2" aria-hidden="true" tabindex="-1"></a>fit <span class="ot">=</span> <span class="fu">lm</span>(<span class="at">formula =</span> salary <span class="sc">~</span> degree <span class="sc">+</span> rank <span class="sc">+</span> sex <span class="sc">+</span> year <span class="sc">+</span> ysdeg, <span class="at">data =</span> salary)</span>
<span id="cb19-3"><a href="#cb19-3" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(fit)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = salary ~ degree + rank + sex + year + ysdeg, data = salary)

Residuals:
    Min      1Q  Median      3Q     Max 
-4045.2 -1094.7  -361.5   813.2  9193.1 

Coefficients:
            Estimate Std. Error t value Pr(&gt;|t|)    
(Intercept) 15746.05     800.18  19.678  &lt; 2e-16 ***
degreePhD    1388.61    1018.75   1.363    0.180    
rankAssoc    5292.36    1145.40   4.621 3.22e-05 ***
rankProf    11118.76    1351.77   8.225 1.62e-10 ***
sexFemale    1166.37     925.57   1.260    0.214    
year          476.31      94.91   5.018 8.65e-06 ***
ysdeg        -124.57      77.49  -1.608    0.115    
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 2398 on 45 degrees of freedom
Multiple R-squared:  0.855, Adjusted R-squared:  0.8357 
F-statistic: 44.24 on 6 and 45 DF,  p-value: &lt; 2.2e-16</code></pre>
</div>
</div>
<div class="cell">
<details>
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb21"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb21-1"><a href="#cb21-1" aria-hidden="true" tabindex="-1"></a><span class="co">#obtain a 95% confidence interval</span></span>
<span id="cb21-2"><a href="#cb21-2" aria-hidden="true" tabindex="-1"></a><span class="fu">confint</span>(fit, <span class="st">"sexFemale"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>              2.5 %   97.5 %
sexFemale -697.8183 3030.565</code></pre>
</div>
</div>
<p>The above confidence interval suggests that a female professor may earn between approximately $697.82 less and $3030.57 more than a male professor.</p>
</section>
<section id="c-1" class="level3">
<h3 class="anchored" data-anchor-id="c-1">C</h3>
<p>Interpret your finding for each predictor variable; discuss (a) statistical significance, (b) interpretation of the coefficient / slope in relation to the outcome variable and other variables.</p>
<div class="cell">
<details>
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb23"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb23-1"><a href="#cb23-1" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(fit)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = salary ~ degree + rank + sex + year + ysdeg, data = salary)

Residuals:
    Min      1Q  Median      3Q     Max 
-4045.2 -1094.7  -361.5   813.2  9193.1 

Coefficients:
            Estimate Std. Error t value Pr(&gt;|t|)    
(Intercept) 15746.05     800.18  19.678  &lt; 2e-16 ***
degreePhD    1388.61    1018.75   1.363    0.180    
rankAssoc    5292.36    1145.40   4.621 3.22e-05 ***
rankProf    11118.76    1351.77   8.225 1.62e-10 ***
sexFemale    1166.37     925.57   1.260    0.214    
year          476.31      94.91   5.018 8.65e-06 ***
ysdeg        -124.57      77.49  -1.608    0.115    
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 2398 on 45 degrees of freedom
Multiple R-squared:  0.855, Adjusted R-squared:  0.8357 
F-statistic: 44.24 on 6 and 45 DF,  p-value: &lt; 2.2e-16</code></pre>
</div>
</div>
<p>We can see from the p-values that the only statistically significant predictors are rank (both associate and professor) and year. The estimator column gives us the coefficient/slope of each variable, so we see that all variables except years since last degree are associated with an increase in salary. Years since last degree is actually associated with a decrease in salary (but again, this value is not statistically significant).</p>
</section>
<section id="d" class="level3">
<h3 class="anchored" data-anchor-id="d">D</h3>
<p>Change the baseline category for the rank variable. Interpret the coefficients related to rank again.</p>
<div class="cell">
<details>
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb25"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb25-1"><a href="#cb25-1" aria-hidden="true" tabindex="-1"></a>rank2 <span class="ot">=</span> <span class="fu">relevel</span>(salary<span class="sc">$</span>rank, <span class="st">"Prof"</span>)</span>
<span id="cb25-2"><a href="#cb25-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb25-3"><a href="#cb25-3" aria-hidden="true" tabindex="-1"></a>fit2 <span class="ot">=</span> <span class="fu">lm</span>(<span class="at">formula =</span> salary <span class="sc">~</span> degree <span class="sc">+</span> rank2 <span class="sc">+</span> sex <span class="sc">+</span> year <span class="sc">+</span> ysdeg, <span class="at">data =</span> salary)</span>
<span id="cb25-4"><a href="#cb25-4" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(fit2)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = salary ~ degree + rank2 + sex + year + ysdeg, data = salary)

Residuals:
    Min      1Q  Median      3Q     Max 
-4045.2 -1094.7  -361.5   813.2  9193.1 

Coefficients:
             Estimate Std. Error t value Pr(&gt;|t|)    
(Intercept)  26864.81    1375.29  19.534  &lt; 2e-16 ***
degreePhD     1388.61    1018.75   1.363    0.180    
rank2Asst   -11118.76    1351.77  -8.225 1.62e-10 ***
rank2Assoc   -5826.40    1012.93  -5.752 7.28e-07 ***
sexFemale     1166.37     925.57   1.260    0.214    
year           476.31      94.91   5.018 8.65e-06 ***
ysdeg         -124.57      77.49  -1.608    0.115    
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 2398 on 45 degrees of freedom
Multiple R-squared:  0.855, Adjusted R-squared:  0.8357 
F-statistic: 44.24 on 6 and 45 DF,  p-value: &lt; 2.2e-16</code></pre>
</div>
</div>
<p>By changing the baseline category for the rank to “Prof,” I made the coefficients for the rank completely different- now rank is associated with a decrease in salary. This just means that if a professor were to become an assistant or associate professor, their salary would be expected to decrease.</p>
</section>
<section id="e" class="level3">
<h3 class="anchored" data-anchor-id="e">E</h3>
<p>Finkelstein (1980), in a discussion of the use of regression in discrimination cases, wrote, “<a href="#a-2">a</a> variable may reflect a position or status bestowed by the employer, in which case if there is discrimination in the award of the position or status, the variable may be ‘tainted.’” Thus, for example, if discrimination is at work in promotion of faculty to higher ranks, using rank to adjust salaries before comparing the sexes may not be acceptable to the courts.</p>
<p>Exclude the variable rank, refit, and summarize how your findings changed, if they did.</p>
<div class="cell">
<details>
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb27"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb27-1"><a href="#cb27-1" aria-hidden="true" tabindex="-1"></a>fit3 <span class="ot">=</span> <span class="fu">lm</span>(<span class="at">formula =</span> salary <span class="sc">~</span> degree <span class="sc">+</span> sex <span class="sc">+</span> year <span class="sc">+</span> ysdeg, <span class="at">data =</span> salary)</span>
<span id="cb27-2"><a href="#cb27-2" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(fit3)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = salary ~ degree + sex + year + ysdeg, data = salary)

Residuals:
    Min      1Q  Median      3Q     Max 
-8146.9 -2186.9  -491.5  2279.1 11186.6 

Coefficients:
            Estimate Std. Error t value Pr(&gt;|t|)    
(Intercept) 17183.57    1147.94  14.969  &lt; 2e-16 ***
degreePhD   -3299.35    1302.52  -2.533 0.014704 *  
sexFemale   -1286.54    1313.09  -0.980 0.332209    
year          351.97     142.48   2.470 0.017185 *  
ysdeg         339.40      80.62   4.210 0.000114 ***
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 3744 on 47 degrees of freedom
Multiple R-squared:  0.6312,    Adjusted R-squared:  0.5998 
F-statistic: 20.11 on 4 and 47 DF,  p-value: 1.048e-09</code></pre>
</div>
</div>
<p>Eliminating rank from the regression completely changes the direction for having a PhD, being female, and years since last degree.</p>
</section>
<section id="f" class="level3">
<h3 class="anchored" data-anchor-id="f">F</h3>
<p>Everyone in this dataset was hired the year they earned their highest degree. It is also known that a new Dean was appointed 15 years ago, and everyone in the dataset who earned their highest degree 15 years ago or less than that has been hired by the new Dean. Some people have argued that the new Dean has been making offers that are a lot more generous to newly hired faculty than the previous one and that this might explain some of the variation in Salary.</p>
<p>Create a new variable that would allow you to test this hypothesis and run another multiple regression model to test this. Select variables carefully to make sure there is no multicollinearity. Explain why multicollinearity would be a concern in this case and how you avoided it. Do you find support for the hypothesis that the people hired by the new Dean are making higher than those that were not?</p>
<div class="cell">
<details>
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb29"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb29-1"><a href="#cb29-1" aria-hidden="true" tabindex="-1"></a><span class="co">#create a dummy variable</span></span>
<span id="cb29-2"><a href="#cb29-2" aria-hidden="true" tabindex="-1"></a>salary<span class="sc">$</span>hired <span class="ot">&lt;-</span> <span class="fu">ifelse</span>(salary<span class="sc">$</span>ysdeg <span class="sc">&lt;=</span> <span class="dv">15</span>, <span class="dv">1</span>, <span class="dv">0</span>)</span>
<span id="cb29-3"><a href="#cb29-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb29-4"><a href="#cb29-4" aria-hidden="true" tabindex="-1"></a>dean <span class="ot">&lt;-</span> <span class="fu">lm</span>(salary <span class="sc">~</span> hired <span class="sc">+</span> rank <span class="sc">+</span> sex <span class="sc">+</span> degree, <span class="at">data =</span> salary)</span>
<span id="cb29-5"><a href="#cb29-5" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(dean)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = salary ~ hired + rank + sex + degree, data = salary)

Residuals:
    Min      1Q  Median      3Q     Max 
-6187.5 -1750.9  -438.9  1719.5  9362.9 

Coefficients:
            Estimate Std. Error t value Pr(&gt;|t|)    
(Intercept)  17585.6     1621.2  10.847 2.88e-14 ***
hired          319.0     1303.8   0.245 0.807777    
rankAssoc     4825.3     1276.0   3.781 0.000448 ***
rankProf     11925.7     1512.4   7.885 4.37e-10 ***
sexFemale     -829.2      997.6  -0.831 0.410113    
degreePhD     1126.2     1018.4   1.106 0.274532    
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 3023 on 46 degrees of freedom
Multiple R-squared:  0.7645,    Adjusted R-squared:  0.7389 
F-statistic: 29.87 on 5 and 46 DF,  p-value: 2.192e-13</code></pre>
</div>
</div>
<p>I removed the variable ysdegree since it would be highly correlated (collinear) with the dummy variable I created, which is based on those who earned their most recent degree in the last 15 years. In this model, those hired by the new dean make $319 more than those hired by the previous dean. This is only supported at the highest significance level, so I would not say that the evidence to support this theory is strong.</p>
</section>
</section>
<section id="question-3" class="level2">
<h2 class="anchored" data-anchor-id="question-3">Question 3</h2>
<section id="a-2" class="level3">
<h3 class="anchored" data-anchor-id="a-2">A</h3>
<p>Using the house.selling.price data, run and report regression results modeling y = selling price (in dollars) in terms of size of home (in square feet) and whether the home is new (1 = yes; 0 = no). In particular, for each variable; discuss statistical significance and interpret the meaning of the coefficient.</p>
<div class="cell">
<details>
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb31"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb31-1"><a href="#cb31-1" aria-hidden="true" tabindex="-1"></a><span class="fu">data</span>(<span class="st">"house.selling.price"</span>)</span>
<span id="cb31-2"><a href="#cb31-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb31-3"><a href="#cb31-3" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(<span class="fu">lm</span>(Price <span class="sc">~</span> Size <span class="sc">+</span> New, <span class="at">data =</span> house.selling.price))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = Price ~ Size + New, data = house.selling.price)

Residuals:
    Min      1Q  Median      3Q     Max 
-205102  -34374   -5778   18929  163866 

Coefficients:
              Estimate Std. Error t value Pr(&gt;|t|)    
(Intercept) -40230.867  14696.140  -2.738  0.00737 ** 
Size           116.132      8.795  13.204  &lt; 2e-16 ***
New          57736.283  18653.041   3.095  0.00257 ** 
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 53880 on 97 degrees of freedom
Multiple R-squared:  0.7226,    Adjusted R-squared:  0.7169 
F-statistic: 126.3 on 2 and 97 DF,  p-value: &lt; 2.2e-16</code></pre>
</div>
</div>
<p>Size and “newnesss” of the homes both seem to be a predictor, as they are both statistically significant at the given value. The coefficient for size indicates that the price is expected to increase by about $116.13 for every 1 foot increase in square footage. The coefficient for newness indicates that, controlling for everything else, a new home is expected to sell for about $57,736.28 more than an older home.</p>
</section>
<section id="b-2" class="level3">
<h3 class="anchored" data-anchor-id="b-2">B</h3>
<p>Report and interpret the prediction equation, and form separate equations relating selling price to size for new and for not new homes.</p>
<p>The prediction equation is ŷ = -40230.867 + 116.132x + 57736.283z, where x = the size of the home; and z = 1 if the home is new or z = 0 if the home is older.</p>
<p>Old: price = -40230.867 + 116.132x New: price = -40230.867 + 116.132 + 57736.283 or 17505.133 + 116.132x</p>
</section>
<section id="c-2" class="level3">
<h3 class="anchored" data-anchor-id="c-2">C</h3>
<p>Find the predicted selling price for a home of 3000 square feet that is (i) new, (ii) not new.</p>
<div class="cell">
<details>
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb33"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb33-1"><a href="#cb33-1" aria-hidden="true" tabindex="-1"></a><span class="co">#old</span></span>
<span id="cb33-2"><a href="#cb33-2" aria-hidden="true" tabindex="-1"></a><span class="sc">-</span><span class="fl">40230.867</span> <span class="sc">+</span> <span class="fl">116.132</span><span class="sc">*</span><span class="dv">3000</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 308165.1</code></pre>
</div>
<details>
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb35"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb35-1"><a href="#cb35-1" aria-hidden="true" tabindex="-1"></a><span class="co">#new</span></span>
<span id="cb35-2"><a href="#cb35-2" aria-hidden="true" tabindex="-1"></a><span class="fl">17505.133</span> <span class="sc">+</span> <span class="fl">116.132</span><span class="sc">*</span><span class="dv">3000</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 365901.1</code></pre>
</div>
</div>
</section>
<section id="d-1" class="level3">
<h3 class="anchored" data-anchor-id="d-1">D</h3>
<p>Fit another model, this time with an interaction term allowing interaction between size and new, and report the regression results</p>
<div class="cell">
<details>
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb37"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb37-1"><a href="#cb37-1" aria-hidden="true" tabindex="-1"></a>newfit <span class="ot">=</span> <span class="fu">lm</span>(Price <span class="sc">~</span> Size<span class="sc">*</span>New, <span class="at">data =</span> house.selling.price)</span>
<span id="cb37-2"><a href="#cb37-2" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(newfit)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = Price ~ Size * New, data = house.selling.price)

Residuals:
    Min      1Q  Median      3Q     Max 
-175748  -28979   -6260   14693  192519 

Coefficients:
              Estimate Std. Error t value Pr(&gt;|t|)    
(Intercept) -22227.808  15521.110  -1.432  0.15536    
Size           104.438      9.424  11.082  &lt; 2e-16 ***
New         -78527.502  51007.642  -1.540  0.12697    
Size:New        61.916     21.686   2.855  0.00527 ** 
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 52000 on 96 degrees of freedom
Multiple R-squared:  0.7443,    Adjusted R-squared:  0.7363 
F-statistic: 93.15 on 3 and 96 DF,  p-value: &lt; 2.2e-16</code></pre>
</div>
</div>
<p>The interaction between size and newness appears statistically significant.</p>
</section>
<section id="e-1" class="level3">
<h3 class="anchored" data-anchor-id="e-1">E</h3>
<p>Report the lines relating the predicted selling price to the size for homes that are (i) new, (ii) not new.</p>
<p>Old: ŷ = -22227.808 + 104.438x New: ŷ = -22227.808 + 104.438x + -78527.502 + 61.916xz</p>
</section>
<section id="f-1" class="level3">
<h3 class="anchored" data-anchor-id="f-1">F</h3>
<p>Find the predicted selling price for a home of 3000 square feet that is (i) new, (ii) not new.</p>
<section id="i" class="level4">
<h4 class="anchored" data-anchor-id="i">i</h4>
<div class="cell">
<details>
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb39"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb39-1"><a href="#cb39-1" aria-hidden="true" tabindex="-1"></a><span class="co">#new</span></span>
<span id="cb39-2"><a href="#cb39-2" aria-hidden="true" tabindex="-1"></a><span class="sc">-</span><span class="fl">22227.808</span> <span class="sc">+</span> <span class="fl">104.438</span><span class="sc">*</span><span class="dv">3000</span> <span class="sc">+</span> <span class="sc">-</span><span class="fl">78527.502</span> <span class="sc">+</span> <span class="fl">61.916</span><span class="sc">*</span><span class="dv">3000</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 398306.7</code></pre>
</div>
</div>
</section>
<section id="ii" class="level4">
<h4 class="anchored" data-anchor-id="ii">ii</h4>
<div class="cell">
<details>
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb41"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb41-1"><a href="#cb41-1" aria-hidden="true" tabindex="-1"></a><span class="co">#old</span></span>
<span id="cb41-2"><a href="#cb41-2" aria-hidden="true" tabindex="-1"></a><span class="sc">-</span><span class="fl">22227.808</span> <span class="sc">+</span> <span class="fl">104.438</span><span class="sc">*</span><span class="dv">3000</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 291086.2</code></pre>
</div>
</div>
</section>
</section>
<section id="g" class="level3">
<h3 class="anchored" data-anchor-id="g">G</h3>
<p>Find the predicted selling price for a home of 1500 square feet that is (i) new, (ii) not new. Comparing to (F), explain how the difference in predicted selling prices changes as the size of home increases.</p>
<div class="cell">
<details>
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb43"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb43-1"><a href="#cb43-1" aria-hidden="true" tabindex="-1"></a><span class="co">#new</span></span>
<span id="cb43-2"><a href="#cb43-2" aria-hidden="true" tabindex="-1"></a><span class="sc">-</span><span class="fl">22227.808</span> <span class="sc">+</span> <span class="fl">104.438</span><span class="sc">*</span><span class="dv">1500</span> <span class="sc">+</span> <span class="sc">-</span><span class="fl">78527.502</span> <span class="sc">+</span> <span class="fl">61.916</span><span class="sc">*</span><span class="dv">1500</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 148775.7</code></pre>
</div>
</div>
<section id="ii-1" class="level4">
<h4 class="anchored" data-anchor-id="ii-1">ii</h4>
<div class="cell">
<details>
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb45"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb45-1"><a href="#cb45-1" aria-hidden="true" tabindex="-1"></a><span class="co">#old</span></span>
<span id="cb45-2"><a href="#cb45-2" aria-hidden="true" tabindex="-1"></a><span class="sc">-</span><span class="fl">22227.808</span> <span class="sc">+</span> <span class="fl">104.438</span><span class="sc">*</span><span class="dv">1500</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 134429.2</code></pre>
</div>
</div>
<p>We can see that the price difference for larger homes differs much more dramatically based on age than for smaller homes.</p>
</section>
</section>
<section id="h" class="level3">
<h3 class="anchored" data-anchor-id="h">H</h3>
<p>Do you think the model with interaction or the one without it represents the relationship of size and new to the outcome price? What makes you prefer one model over another?</p>
<p>Based on the p-values and the R-squared for both models, I think the model with interaction is a slightly better fit.</p>


<!-- -->

</section>
</section>
</section>

</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const disableStylesheet = (stylesheets) => {
    for (let i=0; i < stylesheets.length; i++) {
      const stylesheet = stylesheets[i];
      stylesheet.rel = 'prefetch';
    }
  }
  const enableStylesheet = (stylesheets) => {
    for (let i=0; i < stylesheets.length; i++) {
      const stylesheet = stylesheets[i];
      stylesheet.rel = 'stylesheet';
    }
  }
  const manageTransitions = (selector, allowTransitions) => {
    const els = window.document.querySelectorAll(selector);
    for (let i=0; i < els.length; i++) {
      const el = els[i];
      if (allowTransitions) {
        el.classList.remove('notransition');
      } else {
        el.classList.add('notransition');
      }
    }
  }
  const toggleColorMode = (alternate) => {
    // Switch the stylesheets
    const alternateStylesheets = window.document.querySelectorAll('link.quarto-color-scheme.quarto-color-alternate');
    manageTransitions('#quarto-margin-sidebar .nav-link', false);
    if (alternate) {
      enableStylesheet(alternateStylesheets);
      for (const sheetNode of alternateStylesheets) {
        if (sheetNode.id === "quarto-bootstrap") {
          toggleBodyColorMode(sheetNode);
        }
      }
    } else {
      disableStylesheet(alternateStylesheets);
      toggleBodyColorPrimary();
    }
    manageTransitions('#quarto-margin-sidebar .nav-link', true);
    // Switch the toggles
    const toggles = window.document.querySelectorAll('.quarto-color-scheme-toggle');
    for (let i=0; i < toggles.length; i++) {
      const toggle = toggles[i];
      if (toggle) {
        if (alternate) {
          toggle.classList.add("alternate");     
        } else {
          toggle.classList.remove("alternate");
        }
      }
    }
  }
  const isFileUrl = () => { 
    return window.location.protocol === 'file:';
  }
  const hasAlternateSentinel = () => {  
    let styleSentinel = getColorSchemeSentinel();
    if (styleSentinel !== null) {
      return styleSentinel === "alternate";
    } else {
      return false;
    }
  }
  const setStyleSentinel = (alternate) => {
    const value = alternate ? "alternate" : "default";
    if (!isFileUrl()) {
      window.localStorage.setItem("quarto-color-scheme", value);
    } else {
      localAlternateSentinel = value;
    }
  }
  const getColorSchemeSentinel = () => {
    if (!isFileUrl()) {
      const storageValue = window.localStorage.getItem("quarto-color-scheme");
      return storageValue != null ? storageValue : localAlternateSentinel;
    } else {
      return localAlternateSentinel;
    }
  }
  let localAlternateSentinel = 'default';
  // Dark / light mode switch
  window.quartoToggleColorScheme = () => {
    // Read the current dark / light value 
    let toAlternate = !hasAlternateSentinel();
    toggleColorMode(toAlternate);
    setStyleSentinel(toAlternate);
  };
  // Ensure there is a toggle, if there isn't float one in the top right
  if (window.document.querySelector('.quarto-color-scheme-toggle') === null) {
    const a = window.document.createElement('a');
    a.classList.add('top-right');
    a.classList.add('quarto-color-scheme-toggle');
    a.href = "";
    a.onclick = function() { try { window.quartoToggleColorScheme(); } catch {} return false; };
    const i = window.document.createElement("i");
    i.classList.add('bi');
    a.appendChild(i);
    window.document.body.appendChild(a);
  }
  // Switch to dark mode if need be
  if (hasAlternateSentinel()) {
    toggleColorMode(true);
  } 
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const clipboard = new window.ClipboardJS('.code-copy-button', {
    target: function(trigger) {
      return trigger.previousElementSibling;
    }
  });
  clipboard.on('success', function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copied!");
    setTimeout(function() {
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  });
  const viewSource = window.document.getElementById('quarto-view-source') ||
                     window.document.getElementById('quarto-code-tools-source');
  if (viewSource) {
    const sourceUrl = viewSource.getAttribute("data-quarto-source-url");
    viewSource.addEventListener("click", function(e) {
      if (sourceUrl) {
        // rstudio viewer pane
        if (/\bcapabilities=\b/.test(window.location)) {
          window.open(sourceUrl);
        } else {
          window.location.href = sourceUrl;
        }
      } else {
        const modal = new bootstrap.Modal(document.getElementById('quarto-embedded-source-code-modal'));
        modal.show();
      }
      return false;
    });
  }
  function toggleCodeHandler(show) {
    return function(e) {
      const detailsSrc = window.document.querySelectorAll(".cell > details > .sourceCode");
      for (let i=0; i<detailsSrc.length; i++) {
        const details = detailsSrc[i].parentElement;
        if (show) {
          details.open = true;
        } else {
          details.removeAttribute("open");
        }
      }
      const cellCodeDivs = window.document.querySelectorAll(".cell > .sourceCode");
      const fromCls = show ? "hidden" : "unhidden";
      const toCls = show ? "unhidden" : "hidden";
      for (let i=0; i<cellCodeDivs.length; i++) {
        const codeDiv = cellCodeDivs[i];
        if (codeDiv.classList.contains(fromCls)) {
          codeDiv.classList.remove(fromCls);
          codeDiv.classList.add(toCls);
        } 
      }
      return false;
    }
  }
  const hideAllCode = window.document.getElementById("quarto-hide-all-code");
  if (hideAllCode) {
    hideAllCode.addEventListener("click", toggleCodeHandler(false));
  }
  const showAllCode = window.document.getElementById("quarto-show-all-code");
  if (showAllCode) {
    showAllCode.addEventListener("click", toggleCodeHandler(true));
  }
  function tippyHover(el, contentFn) {
    const config = {
      allowHTML: true,
      content: contentFn,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start'
    };
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      let href = ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      return note.innerHTML;
    });
  }
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const cites = ref.parentNode.getAttribute('data-cites').split(' ');
    tippyHover(ref, function() {
      var popup = window.document.createElement('div');
      cites.forEach(function(cite) {
        var citeDiv = window.document.createElement('div');
        citeDiv.classList.add('hanging-indent');
        citeDiv.classList.add('csl-entry');
        var biblioDiv = window.document.getElementById('ref-' + cite);
        if (biblioDiv) {
          citeDiv.innerHTML = biblioDiv.innerHTML;
        }
        popup.appendChild(citeDiv);
      });
      return popup.innerHTML;
    });
  }
});
</script>
<script src="https://giscus.app/client.js" data-repo="DACSS/603_Fall_2022" data-repo-id="R_kgDOH568kA" data-category="Announcements" data-category-id="" data-mapping="title" data-reactions-enabled="1" data-emit-metadata="0" data-input-position="top" data-theme="light" data-lang="en" crossorigin="anonymous" async="">
</script><div class="modal fade" id="quarto-embedded-source-code-modal" tabindex="-1" aria-labelledby="quarto-embedded-source-code-modal-label" aria-hidden="true"><div class="modal-dialog modal-dialog-scrollable"><div class="modal-content"><div class="modal-header"><h5 class="modal-title" id="quarto-embedded-source-code-modal-label">Source Code</h5><button class="btn-close" data-bs-dismiss="modal"></button></div><div class="modal-body"><div class="">
<div class="sourceCode" id="cb47" data-shortcodes="false"><pre class="sourceCode markdown code-with-copy"><code class="sourceCode markdown"><span id="cb47-1"><a href="#cb47-1" aria-hidden="true" tabindex="-1"></a><span class="co">---</span></span>
<span id="cb47-2"><a href="#cb47-2" aria-hidden="true" tabindex="-1"></a><span class="an">title:</span><span class="co"> "Homework 4"</span></span>
<span id="cb47-3"><a href="#cb47-3" aria-hidden="true" tabindex="-1"></a><span class="an">author:</span><span class="co"> "Lindsay Jones"</span></span>
<span id="cb47-4"><a href="#cb47-4" aria-hidden="true" tabindex="-1"></a><span class="an">description:</span><span class="co"> The fourth homework</span></span>
<span id="cb47-5"><a href="#cb47-5" aria-hidden="true" tabindex="-1"></a><span class="an">date:</span><span class="co"> "11/14/2022"</span></span>
<span id="cb47-6"><a href="#cb47-6" aria-hidden="true" tabindex="-1"></a><span class="an">format:</span></span>
<span id="cb47-7"><a href="#cb47-7" aria-hidden="true" tabindex="-1"></a><span class="co">  html:</span></span>
<span id="cb47-8"><a href="#cb47-8" aria-hidden="true" tabindex="-1"></a><span class="co">    toc: true</span></span>
<span id="cb47-9"><a href="#cb47-9" aria-hidden="true" tabindex="-1"></a><span class="co">    code-fold: true</span></span>
<span id="cb47-10"><a href="#cb47-10" aria-hidden="true" tabindex="-1"></a><span class="co">    code-copy: true</span></span>
<span id="cb47-11"><a href="#cb47-11" aria-hidden="true" tabindex="-1"></a><span class="co">    code-tools: true</span></span>
<span id="cb47-12"><a href="#cb47-12" aria-hidden="true" tabindex="-1"></a><span class="an">categories:</span></span>
<span id="cb47-13"><a href="#cb47-13" aria-hidden="true" tabindex="-1"></a><span class="co">  - hw4</span></span>
<span id="cb47-14"><a href="#cb47-14" aria-hidden="true" tabindex="-1"></a><span class="co">---</span></span>
<span id="cb47-15"><a href="#cb47-15" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb47-16"><a href="#cb47-16" aria-hidden="true" tabindex="-1"></a><span class="fu"># Homework 4</span></span>
<span id="cb47-17"><a href="#cb47-17" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb47-18"><a href="#cb47-18" aria-hidden="true" tabindex="-1"></a><span class="fu">## Setup</span></span>
<span id="cb47-19"><a href="#cb47-19" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb47-22"><a href="#cb47-22" aria-hidden="true" tabindex="-1"></a><span class="in">```{r}</span></span>
<span id="cb47-23"><a href="#cb47-23" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(alr4)</span>
<span id="cb47-24"><a href="#cb47-24" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(smss)</span>
<span id="cb47-25"><a href="#cb47-25" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb47-26"><a href="#cb47-26" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb47-27"><a href="#cb47-27" aria-hidden="true" tabindex="-1"></a><span class="fu">## Question 1</span></span>
<span id="cb47-28"><a href="#cb47-28" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb47-29"><a href="#cb47-29" aria-hidden="true" tabindex="-1"></a>For recent data in Jacksonville, Florida, on y = selling price of home (in dollars), x₁ = size of home (in square feet), and x₂ = lot size (in square feet), the prediction equation is ŷ = −10,536 + 53.8x₁ + 2.84x₂.</span>
<span id="cb47-30"><a href="#cb47-30" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb47-31"><a href="#cb47-31" aria-hidden="true" tabindex="-1"></a><span class="fu">### A</span></span>
<span id="cb47-32"><a href="#cb47-32" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb47-33"><a href="#cb47-33" aria-hidden="true" tabindex="-1"></a>A particular home of 1240 square feet on a lot of 18,000 square feet sold for \$145,000. Find the predicted selling price and the residual, and interpret.</span>
<span id="cb47-34"><a href="#cb47-34" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb47-37"><a href="#cb47-37" aria-hidden="true" tabindex="-1"></a><span class="in">```{r}</span></span>
<span id="cb47-38"><a href="#cb47-38" aria-hidden="true" tabindex="-1"></a><span class="co">#plug variables into equation</span></span>
<span id="cb47-39"><a href="#cb47-39" aria-hidden="true" tabindex="-1"></a>x1 <span class="ot">=</span> <span class="dv">1240</span></span>
<span id="cb47-40"><a href="#cb47-40" aria-hidden="true" tabindex="-1"></a>x2 <span class="ot">=</span> <span class="dv">18000</span></span>
<span id="cb47-41"><a href="#cb47-41" aria-hidden="true" tabindex="-1"></a>y <span class="ot">=</span> <span class="dv">145000</span></span>
<span id="cb47-42"><a href="#cb47-42" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb47-43"><a href="#cb47-43" aria-hidden="true" tabindex="-1"></a>ybar1 <span class="ot">&lt;-</span> (<span class="sc">-</span><span class="dv">10536</span>)<span class="sc">+</span>(<span class="fl">53.8</span><span class="sc">*</span>x1)<span class="sc">+</span>(<span class="fl">2.84</span><span class="sc">*</span>x2)</span>
<span id="cb47-44"><a href="#cb47-44" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb47-45"><a href="#cb47-45" aria-hidden="true" tabindex="-1"></a>ybar1</span>
<span id="cb47-46"><a href="#cb47-46" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb47-47"><a href="#cb47-47" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb47-50"><a href="#cb47-50" aria-hidden="true" tabindex="-1"></a><span class="in">```{r}</span></span>
<span id="cb47-51"><a href="#cb47-51" aria-hidden="true" tabindex="-1"></a><span class="co">#subtract predicted from actual to find residual</span></span>
<span id="cb47-52"><a href="#cb47-52" aria-hidden="true" tabindex="-1"></a>y <span class="sc">-</span> ybar1</span>
<span id="cb47-53"><a href="#cb47-53" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb47-54"><a href="#cb47-54" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb47-55"><a href="#cb47-55" aria-hidden="true" tabindex="-1"></a>The house sold for \$37,704 greater than predicted.</span>
<span id="cb47-56"><a href="#cb47-56" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb47-57"><a href="#cb47-57" aria-hidden="true" tabindex="-1"></a><span class="fu">### B</span></span>
<span id="cb47-58"><a href="#cb47-58" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb47-59"><a href="#cb47-59" aria-hidden="true" tabindex="-1"></a>For fixed lot size, how much is the house selling price predicted to increase for each square-foot increase in home size? Why?</span>
<span id="cb47-60"><a href="#cb47-60" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb47-63"><a href="#cb47-63" aria-hidden="true" tabindex="-1"></a><span class="in">```{r}</span></span>
<span id="cb47-64"><a href="#cb47-64" aria-hidden="true" tabindex="-1"></a><span class="co">#plug variables into equation</span></span>
<span id="cb47-65"><a href="#cb47-65" aria-hidden="true" tabindex="-1"></a>x1f <span class="ot">=</span> <span class="dv">1241</span> <span class="co">#increased size by 1 square foot</span></span>
<span id="cb47-66"><a href="#cb47-66" aria-hidden="true" tabindex="-1"></a>x2f <span class="ot">=</span> <span class="dv">18000</span></span>
<span id="cb47-67"><a href="#cb47-67" aria-hidden="true" tabindex="-1"></a>yf <span class="ot">=</span> <span class="dv">145000</span></span>
<span id="cb47-68"><a href="#cb47-68" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb47-69"><a href="#cb47-69" aria-hidden="true" tabindex="-1"></a>ybar1f <span class="ot">&lt;-</span> (<span class="sc">-</span><span class="dv">10536</span>)<span class="sc">+</span>(<span class="fl">53.8</span><span class="sc">*</span>x1f)<span class="sc">+</span>(<span class="fl">2.84</span><span class="sc">*</span>x2f)</span>
<span id="cb47-70"><a href="#cb47-70" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb47-71"><a href="#cb47-71" aria-hidden="true" tabindex="-1"></a><span class="co">#subtract old predicted price from new predicted price</span></span>
<span id="cb47-72"><a href="#cb47-72" aria-hidden="true" tabindex="-1"></a>ybar1f<span class="sc">-</span>ybar1 </span>
<span id="cb47-73"><a href="#cb47-73" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb47-74"><a href="#cb47-74" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb47-75"><a href="#cb47-75" aria-hidden="true" tabindex="-1"></a>In the given equation ŷ = −10,536 + 53.8x₁ + 2.84x₂, the slope coefficient for x₁ (size of home) is 53.8, meaning for every 1-foot increase in square footage the house selling price increases by \$53.80. In the code above I demonstrate this by taking my code from part A and increasing square footage by 1, then subtracting part A's solution from the new solution.</span>
<span id="cb47-76"><a href="#cb47-76" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb47-77"><a href="#cb47-77" aria-hidden="true" tabindex="-1"></a><span class="fu">### C</span></span>
<span id="cb47-78"><a href="#cb47-78" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb47-79"><a href="#cb47-79" aria-hidden="true" tabindex="-1"></a>According to this prediction equation, for fixed home size, how much would lot size need to increase to have the same impact as a one-square-foot increase in home size?</span>
<span id="cb47-80"><a href="#cb47-80" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb47-83"><a href="#cb47-83" aria-hidden="true" tabindex="-1"></a><span class="in">```{r}</span></span>
<span id="cb47-84"><a href="#cb47-84" aria-hidden="true" tabindex="-1"></a><span class="fl">53.8</span><span class="sc">/</span><span class="fl">2.84</span></span>
<span id="cb47-85"><a href="#cb47-85" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb47-86"><a href="#cb47-86" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb47-87"><a href="#cb47-87" aria-hidden="true" tabindex="-1"></a>The slope coefficient for x₂ (lot size) is 2.84, meaning for every 1-foot increase in lot size the house selling price increases by \$2.84. We can use the equation 2.84 <span class="sc">\*</span> x₂ = 53.8 to calculate what increase in lot size is needed to have the same value increase in home size. We can simplify this equation as 53.8/2.84, which equals about 18.94 square feet.</span>
<span id="cb47-88"><a href="#cb47-88" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb47-89"><a href="#cb47-89" aria-hidden="true" tabindex="-1"></a><span class="fu">## Question 2</span></span>
<span id="cb47-90"><a href="#cb47-90" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb47-91"><a href="#cb47-91" aria-hidden="true" tabindex="-1"></a>The data file concerns salary and other characteristics of all faculty in a small Midwestern college collected in the early 1980s for presentation in legal proceedings for which discrimination against women in salary was at issue. All persons in the data hold tenured or tenure track positions; temporary faculty are not included. The variables include degree, a factor with levels PhD and MS; rank, a factor with levels Asst, Assoc, and Prof; sex, a factor with levels Male and Female; Year, years in current rank; ysdeg, years since highest degree, and salary, academic year salary in dollars.</span>
<span id="cb47-92"><a href="#cb47-92" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb47-95"><a href="#cb47-95" aria-hidden="true" tabindex="-1"></a><span class="in">```{r}</span></span>
<span id="cb47-96"><a href="#cb47-96" aria-hidden="true" tabindex="-1"></a><span class="fu">head</span>(salary)</span>
<span id="cb47-97"><a href="#cb47-97" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb47-98"><a href="#cb47-98" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb47-99"><a href="#cb47-99" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb47-100"><a href="#cb47-100" aria-hidden="true" tabindex="-1"></a><span class="fu">### A</span></span>
<span id="cb47-101"><a href="#cb47-101" aria-hidden="true" tabindex="-1"></a>Test the hypothesis that the mean salary for men and women is the same, without regard to any other variable but sex. Explain your findings.</span>
<span id="cb47-102"><a href="#cb47-102" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb47-103"><a href="#cb47-103" aria-hidden="true" tabindex="-1"></a>The null hypothesis is that the mean salary for men is the same as the mean salary for women, controlling for other variables. The alternative hypothesis is that the mean salary for men is NOT the same as the mean salary for women, controlling for other variables.</span>
<span id="cb47-104"><a href="#cb47-104" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb47-107"><a href="#cb47-107" aria-hidden="true" tabindex="-1"></a><span class="in">```{r}</span></span>
<span id="cb47-108"><a href="#cb47-108" aria-hidden="true" tabindex="-1"></a><span class="fu">t.test</span>(salary <span class="sc">~</span> sex, <span class="at">data =</span> salary, <span class="at">var.equal =</span> <span class="cn">TRUE</span>)</span>
<span id="cb47-109"><a href="#cb47-109" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb47-110"><a href="#cb47-110" aria-hidden="true" tabindex="-1"></a>The t-test shows that the mean salaries for each sex are different, but since the p-value is greater than .05, we fail to reject the null hypothesis.</span>
<span id="cb47-111"><a href="#cb47-111" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb47-112"><a href="#cb47-112" aria-hidden="true" tabindex="-1"></a><span class="fu">### B</span></span>
<span id="cb47-113"><a href="#cb47-113" aria-hidden="true" tabindex="-1"></a>Run a multiple linear regression with salary as the outcome variable and everything else as predictors, including sex. Assuming no interactions between sex and the other predictors, obtain a 95% confidence interval for the difference in salary between males and females.</span>
<span id="cb47-114"><a href="#cb47-114" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb47-117"><a href="#cb47-117" aria-hidden="true" tabindex="-1"></a><span class="in">```{r}</span></span>
<span id="cb47-118"><a href="#cb47-118" aria-hidden="true" tabindex="-1"></a><span class="co">#run multiple linear regression</span></span>
<span id="cb47-119"><a href="#cb47-119" aria-hidden="true" tabindex="-1"></a>fit <span class="ot">=</span> <span class="fu">lm</span>(<span class="at">formula =</span> salary <span class="sc">~</span> degree <span class="sc">+</span> rank <span class="sc">+</span> sex <span class="sc">+</span> year <span class="sc">+</span> ysdeg, <span class="at">data =</span> salary)</span>
<span id="cb47-120"><a href="#cb47-120" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(fit)</span>
<span id="cb47-121"><a href="#cb47-121" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb47-124"><a href="#cb47-124" aria-hidden="true" tabindex="-1"></a><span class="in">```{r}</span></span>
<span id="cb47-125"><a href="#cb47-125" aria-hidden="true" tabindex="-1"></a><span class="co">#obtain a 95% confidence interval</span></span>
<span id="cb47-126"><a href="#cb47-126" aria-hidden="true" tabindex="-1"></a><span class="fu">confint</span>(fit, <span class="st">"sexFemale"</span>)</span>
<span id="cb47-127"><a href="#cb47-127" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb47-128"><a href="#cb47-128" aria-hidden="true" tabindex="-1"></a>The above confidence interval suggests that a female professor may earn between approximately \$697.82 less and \$3030.57 more than a male professor. </span>
<span id="cb47-129"><a href="#cb47-129" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb47-130"><a href="#cb47-130" aria-hidden="true" tabindex="-1"></a><span class="fu">### C</span></span>
<span id="cb47-131"><a href="#cb47-131" aria-hidden="true" tabindex="-1"></a>Interpret your finding for each predictor variable; discuss (a) statistical significance, (b) interpretation of the coefficient / slope in relation to the outcome variable and other variables. </span>
<span id="cb47-132"><a href="#cb47-132" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb47-135"><a href="#cb47-135" aria-hidden="true" tabindex="-1"></a><span class="in">```{r}</span></span>
<span id="cb47-136"><a href="#cb47-136" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(fit)</span>
<span id="cb47-137"><a href="#cb47-137" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb47-138"><a href="#cb47-138" aria-hidden="true" tabindex="-1"></a>We can see from the p-values that the only statistically significant predictors are rank (both associate and professor) and year. The estimator column gives us the coefficient/slope of each variable, so we see that all variables except years since last degree are associated with an increase in salary. Years since last degree is actually associated with a decrease in salary (but again, this value is not statistically significant). </span>
<span id="cb47-139"><a href="#cb47-139" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb47-140"><a href="#cb47-140" aria-hidden="true" tabindex="-1"></a><span class="fu">### D</span></span>
<span id="cb47-141"><a href="#cb47-141" aria-hidden="true" tabindex="-1"></a>Change the baseline category for the rank variable. Interpret the coefficients related to rank again.</span>
<span id="cb47-142"><a href="#cb47-142" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb47-145"><a href="#cb47-145" aria-hidden="true" tabindex="-1"></a><span class="in">```{r}</span></span>
<span id="cb47-146"><a href="#cb47-146" aria-hidden="true" tabindex="-1"></a>rank2 <span class="ot">=</span> <span class="fu">relevel</span>(salary<span class="sc">$</span>rank, <span class="st">"Prof"</span>)</span>
<span id="cb47-147"><a href="#cb47-147" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb47-148"><a href="#cb47-148" aria-hidden="true" tabindex="-1"></a>fit2 <span class="ot">=</span> <span class="fu">lm</span>(<span class="at">formula =</span> salary <span class="sc">~</span> degree <span class="sc">+</span> rank2 <span class="sc">+</span> sex <span class="sc">+</span> year <span class="sc">+</span> ysdeg, <span class="at">data =</span> salary)</span>
<span id="cb47-149"><a href="#cb47-149" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(fit2)</span>
<span id="cb47-150"><a href="#cb47-150" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb47-151"><a href="#cb47-151" aria-hidden="true" tabindex="-1"></a>By changing the baseline category for the rank to "Prof," I made the coefficients for the rank completely different- now rank is associated with a decrease in salary. This just means that if a professor were to become an assistant or associate professor, their salary would be expected to decrease. </span>
<span id="cb47-152"><a href="#cb47-152" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb47-153"><a href="#cb47-153" aria-hidden="true" tabindex="-1"></a><span class="fu">### E</span></span>
<span id="cb47-154"><a href="#cb47-154" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb47-155"><a href="#cb47-155" aria-hidden="true" tabindex="-1"></a>Finkelstein (1980), in a discussion of the use of regression in discrimination cases, wrote, “<span class="co">[</span><span class="ot">a</span><span class="co">]</span> variable may reflect a position or status bestowed by the employer, in which case if there is discrimination in the award of the position or status, the variable may be ‘tainted.’ ” Thus, for example, if discrimination is at work in promotion of faculty to higher ranks, using rank to adjust salaries before comparing the sexes may not be acceptable to the courts. </span>
<span id="cb47-156"><a href="#cb47-156" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb47-157"><a href="#cb47-157" aria-hidden="true" tabindex="-1"></a>Exclude the variable rank, refit, and summarize how your findings changed, if they did.</span>
<span id="cb47-158"><a href="#cb47-158" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb47-161"><a href="#cb47-161" aria-hidden="true" tabindex="-1"></a><span class="in">```{r}</span></span>
<span id="cb47-162"><a href="#cb47-162" aria-hidden="true" tabindex="-1"></a>fit3 <span class="ot">=</span> <span class="fu">lm</span>(<span class="at">formula =</span> salary <span class="sc">~</span> degree <span class="sc">+</span> sex <span class="sc">+</span> year <span class="sc">+</span> ysdeg, <span class="at">data =</span> salary)</span>
<span id="cb47-163"><a href="#cb47-163" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(fit3)</span>
<span id="cb47-164"><a href="#cb47-164" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb47-165"><a href="#cb47-165" aria-hidden="true" tabindex="-1"></a>Eliminating rank from the regression completely changes the direction for having a PhD, being female, and years since last degree. </span>
<span id="cb47-166"><a href="#cb47-166" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb47-167"><a href="#cb47-167" aria-hidden="true" tabindex="-1"></a><span class="fu">### F</span></span>
<span id="cb47-168"><a href="#cb47-168" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb47-169"><a href="#cb47-169" aria-hidden="true" tabindex="-1"></a>Everyone in this dataset was hired the year they earned their highest degree. It is also known that a new Dean was appointed 15 years ago, and everyone in the dataset who earned their highest degree 15 years ago or less than that has been hired by the new Dean. Some people have argued that the new Dean has been making offers that are a lot more generous to newly hired faculty than the previous one and that this might explain some of the variation in Salary.</span>
<span id="cb47-170"><a href="#cb47-170" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb47-171"><a href="#cb47-171" aria-hidden="true" tabindex="-1"></a>Create a new variable that would allow you to test this hypothesis and run another multiple regression model to test this. Select variables carefully to make sure there is no multicollinearity. Explain why multicollinearity would be a concern in this case and how you avoided it. Do you find support for the hypothesis that the people hired by the new Dean are making higher than those that were not?</span>
<span id="cb47-172"><a href="#cb47-172" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb47-175"><a href="#cb47-175" aria-hidden="true" tabindex="-1"></a><span class="in">```{r}</span></span>
<span id="cb47-176"><a href="#cb47-176" aria-hidden="true" tabindex="-1"></a><span class="co">#create a dummy variable</span></span>
<span id="cb47-177"><a href="#cb47-177" aria-hidden="true" tabindex="-1"></a>salary<span class="sc">$</span>hired <span class="ot">&lt;-</span> <span class="fu">ifelse</span>(salary<span class="sc">$</span>ysdeg <span class="sc">&lt;=</span> <span class="dv">15</span>, <span class="dv">1</span>, <span class="dv">0</span>)</span>
<span id="cb47-178"><a href="#cb47-178" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb47-179"><a href="#cb47-179" aria-hidden="true" tabindex="-1"></a>dean <span class="ot">&lt;-</span> <span class="fu">lm</span>(salary <span class="sc">~</span> hired <span class="sc">+</span> rank <span class="sc">+</span> sex <span class="sc">+</span> degree, <span class="at">data =</span> salary)</span>
<span id="cb47-180"><a href="#cb47-180" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(dean)</span>
<span id="cb47-181"><a href="#cb47-181" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb47-182"><a href="#cb47-182" aria-hidden="true" tabindex="-1"></a>I removed the variable ysdegree since it would be highly correlated (collinear) with the dummy variable I created, which is based on those who earned their most recent degree in the last 15 years. In this model, those hired by the new dean make $319 more than those hired by the previous dean. This is only supported at the highest significance level, so I would not say that the evidence to support this theory is strong. </span>
<span id="cb47-183"><a href="#cb47-183" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb47-184"><a href="#cb47-184" aria-hidden="true" tabindex="-1"></a><span class="fu">## Question 3</span></span>
<span id="cb47-185"><a href="#cb47-185" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb47-186"><a href="#cb47-186" aria-hidden="true" tabindex="-1"></a><span class="fu">### A</span></span>
<span id="cb47-187"><a href="#cb47-187" aria-hidden="true" tabindex="-1"></a>Using the house.selling.price data, run and report regression results modeling y = selling price (in dollars) in terms of size of home (in square feet) and whether the home is new (1 = yes; 0 = no). In particular, for each variable; discuss statistical significance and interpret the meaning of the coefficient.</span>
<span id="cb47-188"><a href="#cb47-188" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb47-191"><a href="#cb47-191" aria-hidden="true" tabindex="-1"></a><span class="in">```{r}</span></span>
<span id="cb47-192"><a href="#cb47-192" aria-hidden="true" tabindex="-1"></a><span class="fu">data</span>(<span class="st">"house.selling.price"</span>)</span>
<span id="cb47-193"><a href="#cb47-193" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb47-194"><a href="#cb47-194" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(<span class="fu">lm</span>(Price <span class="sc">~</span> Size <span class="sc">+</span> New, <span class="at">data =</span> house.selling.price))</span>
<span id="cb47-195"><a href="#cb47-195" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb47-196"><a href="#cb47-196" aria-hidden="true" tabindex="-1"></a>Size and "newnesss" of the homes both seem to be a predictor, as they are both statistically significant at the given value. The coefficient for size indicates that the price is expected to increase by about \$116.13 for every 1 foot increase in square footage. The coefficient for newness indicates that, controlling for everything else, a new home is expected to sell for about \$57,736.28 more than an older home. </span>
<span id="cb47-197"><a href="#cb47-197" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb47-198"><a href="#cb47-198" aria-hidden="true" tabindex="-1"></a><span class="fu">### B</span></span>
<span id="cb47-199"><a href="#cb47-199" aria-hidden="true" tabindex="-1"></a>Report and interpret the prediction equation, and form separate equations relating selling price to size for new and for not new homes.</span>
<span id="cb47-200"><a href="#cb47-200" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb47-201"><a href="#cb47-201" aria-hidden="true" tabindex="-1"></a>The prediction equation is ŷ = -40230.867 + 116.132x + 57736.283z, where x = the size of the home; and z = 1 if the home is new or z = 0 if the home is older.</span>
<span id="cb47-202"><a href="#cb47-202" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb47-203"><a href="#cb47-203" aria-hidden="true" tabindex="-1"></a>Old: price = -40230.867 + 116.132x</span>
<span id="cb47-204"><a href="#cb47-204" aria-hidden="true" tabindex="-1"></a>New: price = -40230.867 + 116.132 + 57736.283   or 17505.133 + 116.132x</span>
<span id="cb47-205"><a href="#cb47-205" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb47-206"><a href="#cb47-206" aria-hidden="true" tabindex="-1"></a><span class="fu">### C</span></span>
<span id="cb47-207"><a href="#cb47-207" aria-hidden="true" tabindex="-1"></a>Find the predicted selling price for a home of 3000 square feet that is (i) new, (ii) not new.</span>
<span id="cb47-208"><a href="#cb47-208" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb47-211"><a href="#cb47-211" aria-hidden="true" tabindex="-1"></a><span class="in">```{r}</span></span>
<span id="cb47-212"><a href="#cb47-212" aria-hidden="true" tabindex="-1"></a><span class="co">#old</span></span>
<span id="cb47-213"><a href="#cb47-213" aria-hidden="true" tabindex="-1"></a><span class="sc">-</span><span class="fl">40230.867</span> <span class="sc">+</span> <span class="fl">116.132</span><span class="sc">*</span><span class="dv">3000</span></span>
<span id="cb47-214"><a href="#cb47-214" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb47-215"><a href="#cb47-215" aria-hidden="true" tabindex="-1"></a><span class="co">#new</span></span>
<span id="cb47-216"><a href="#cb47-216" aria-hidden="true" tabindex="-1"></a><span class="fl">17505.133</span> <span class="sc">+</span> <span class="fl">116.132</span><span class="sc">*</span><span class="dv">3000</span></span>
<span id="cb47-217"><a href="#cb47-217" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb47-218"><a href="#cb47-218" aria-hidden="true" tabindex="-1"></a><span class="fu">### D</span></span>
<span id="cb47-219"><a href="#cb47-219" aria-hidden="true" tabindex="-1"></a>Fit another model, this time with an interaction term allowing interaction between size and new, and report the regression results</span>
<span id="cb47-222"><a href="#cb47-222" aria-hidden="true" tabindex="-1"></a><span class="in">```{r}</span></span>
<span id="cb47-223"><a href="#cb47-223" aria-hidden="true" tabindex="-1"></a>newfit <span class="ot">=</span> <span class="fu">lm</span>(Price <span class="sc">~</span> Size<span class="sc">*</span>New, <span class="at">data =</span> house.selling.price)</span>
<span id="cb47-224"><a href="#cb47-224" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(newfit)</span>
<span id="cb47-225"><a href="#cb47-225" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb47-226"><a href="#cb47-226" aria-hidden="true" tabindex="-1"></a>The interaction between size and newness appears statistically significant.</span>
<span id="cb47-227"><a href="#cb47-227" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb47-228"><a href="#cb47-228" aria-hidden="true" tabindex="-1"></a><span class="fu">### E</span></span>
<span id="cb47-229"><a href="#cb47-229" aria-hidden="true" tabindex="-1"></a>Report the lines relating the predicted selling price to the size for homes that are (i) new, (ii) not new.</span>
<span id="cb47-230"><a href="#cb47-230" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb47-231"><a href="#cb47-231" aria-hidden="true" tabindex="-1"></a>Old: ŷ = -22227.808 + 104.438x</span>
<span id="cb47-232"><a href="#cb47-232" aria-hidden="true" tabindex="-1"></a>New: ŷ = -22227.808 + 104.438x + -78527.502 + 61.916xz</span>
<span id="cb47-233"><a href="#cb47-233" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb47-234"><a href="#cb47-234" aria-hidden="true" tabindex="-1"></a><span class="fu">### F</span></span>
<span id="cb47-235"><a href="#cb47-235" aria-hidden="true" tabindex="-1"></a>Find the predicted selling price for a home of 3000 square feet that is (i) new, (ii) not new.</span>
<span id="cb47-236"><a href="#cb47-236" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb47-237"><a href="#cb47-237" aria-hidden="true" tabindex="-1"></a><span class="fu">#### i</span></span>
<span id="cb47-240"><a href="#cb47-240" aria-hidden="true" tabindex="-1"></a><span class="in">```{r}</span></span>
<span id="cb47-241"><a href="#cb47-241" aria-hidden="true" tabindex="-1"></a><span class="co">#new</span></span>
<span id="cb47-242"><a href="#cb47-242" aria-hidden="true" tabindex="-1"></a><span class="sc">-</span><span class="fl">22227.808</span> <span class="sc">+</span> <span class="fl">104.438</span><span class="sc">*</span><span class="dv">3000</span> <span class="sc">+</span> <span class="sc">-</span><span class="fl">78527.502</span> <span class="sc">+</span> <span class="fl">61.916</span><span class="sc">*</span><span class="dv">3000</span></span>
<span id="cb47-243"><a href="#cb47-243" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb47-244"><a href="#cb47-244" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb47-245"><a href="#cb47-245" aria-hidden="true" tabindex="-1"></a><span class="fu">#### ii</span></span>
<span id="cb47-248"><a href="#cb47-248" aria-hidden="true" tabindex="-1"></a><span class="in">```{r}</span></span>
<span id="cb47-249"><a href="#cb47-249" aria-hidden="true" tabindex="-1"></a><span class="co">#old</span></span>
<span id="cb47-250"><a href="#cb47-250" aria-hidden="true" tabindex="-1"></a><span class="sc">-</span><span class="fl">22227.808</span> <span class="sc">+</span> <span class="fl">104.438</span><span class="sc">*</span><span class="dv">3000</span></span>
<span id="cb47-251"><a href="#cb47-251" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb47-252"><a href="#cb47-252" aria-hidden="true" tabindex="-1"></a><span class="fu">### G</span></span>
<span id="cb47-253"><a href="#cb47-253" aria-hidden="true" tabindex="-1"></a>Find the predicted selling price for a home of 1500 square feet that is (i) new, (ii) not new. Comparing to (F), explain how the difference in predicted selling prices changes as the size of home increases.</span>
<span id="cb47-254"><a href="#cb47-254" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb47-257"><a href="#cb47-257" aria-hidden="true" tabindex="-1"></a><span class="in">```{r}</span></span>
<span id="cb47-258"><a href="#cb47-258" aria-hidden="true" tabindex="-1"></a><span class="co">#new</span></span>
<span id="cb47-259"><a href="#cb47-259" aria-hidden="true" tabindex="-1"></a><span class="sc">-</span><span class="fl">22227.808</span> <span class="sc">+</span> <span class="fl">104.438</span><span class="sc">*</span><span class="dv">1500</span> <span class="sc">+</span> <span class="sc">-</span><span class="fl">78527.502</span> <span class="sc">+</span> <span class="fl">61.916</span><span class="sc">*</span><span class="dv">1500</span></span>
<span id="cb47-260"><a href="#cb47-260" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb47-261"><a href="#cb47-261" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb47-262"><a href="#cb47-262" aria-hidden="true" tabindex="-1"></a><span class="fu">#### ii</span></span>
<span id="cb47-265"><a href="#cb47-265" aria-hidden="true" tabindex="-1"></a><span class="in">```{r}</span></span>
<span id="cb47-266"><a href="#cb47-266" aria-hidden="true" tabindex="-1"></a><span class="co">#old</span></span>
<span id="cb47-267"><a href="#cb47-267" aria-hidden="true" tabindex="-1"></a><span class="sc">-</span><span class="fl">22227.808</span> <span class="sc">+</span> <span class="fl">104.438</span><span class="sc">*</span><span class="dv">1500</span></span>
<span id="cb47-268"><a href="#cb47-268" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb47-269"><a href="#cb47-269" aria-hidden="true" tabindex="-1"></a>We can see that the price difference for larger homes differs much more dramatically based on age than for smaller homes. </span>
<span id="cb47-270"><a href="#cb47-270" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb47-271"><a href="#cb47-271" aria-hidden="true" tabindex="-1"></a><span class="fu">### H</span></span>
<span id="cb47-272"><a href="#cb47-272" aria-hidden="true" tabindex="-1"></a>Do you think the model with interaction or the one without it represents the relationship of size and new to the outcome price? What makes you prefer one model over another?</span>
<span id="cb47-273"><a href="#cb47-273" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb47-274"><a href="#cb47-274" aria-hidden="true" tabindex="-1"></a>Based on the p-values and the R-squared for both models, I think the model with interaction is a slightly better fit. </span>
</code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div></div></div></div></div>
</div> <!-- /content -->



</body></html>