<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.2.269">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">

<meta name="author" content="Emily Duryea">
<meta name="dcterms.date" content="2022-11-14">
<meta name="description" content="The fourth homework assignment for DACSS 603">

<title>Homework 4 - Emily Duryea</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1.6em;
  vertical-align: middle;
}
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
    color: #aaaaaa;
  }
pre.numberSource { margin-left: 3em; border-left: 1px solid #aaaaaa;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
code span.al { color: #ff0000; font-weight: bold; } /* Alert */
code span.an { color: #60a0b0; font-weight: bold; font-style: italic; } /* Annotation */
code span.at { color: #7d9029; } /* Attribute */
code span.bn { color: #40a070; } /* BaseN */
code span.bu { color: #008000; } /* BuiltIn */
code span.cf { color: #007020; font-weight: bold; } /* ControlFlow */
code span.ch { color: #4070a0; } /* Char */
code span.cn { color: #880000; } /* Constant */
code span.co { color: #60a0b0; font-style: italic; } /* Comment */
code span.cv { color: #60a0b0; font-weight: bold; font-style: italic; } /* CommentVar */
code span.do { color: #ba2121; font-style: italic; } /* Documentation */
code span.dt { color: #902000; } /* DataType */
code span.dv { color: #40a070; } /* DecVal */
code span.er { color: #ff0000; font-weight: bold; } /* Error */
code span.ex { } /* Extension */
code span.fl { color: #40a070; } /* Float */
code span.fu { color: #06287e; } /* Function */
code span.im { color: #008000; font-weight: bold; } /* Import */
code span.in { color: #60a0b0; font-weight: bold; font-style: italic; } /* Information */
code span.kw { color: #007020; font-weight: bold; } /* Keyword */
code span.op { color: #666666; } /* Operator */
code span.ot { color: #007020; } /* Other */
code span.pp { color: #bc7a00; } /* Preprocessor */
code span.sc { color: #4070a0; } /* SpecialChar */
code span.ss { color: #bb6688; } /* SpecialString */
code span.st { color: #4070a0; } /* String */
code span.va { color: #19177c; } /* Variable */
code span.vs { color: #4070a0; } /* VerbatimString */
code span.wa { color: #60a0b0; font-weight: bold; font-style: italic; } /* Warning */
</style>


<script src="../site_libs/quarto-nav/quarto-nav.js"></script>
<script src="../site_libs/quarto-nav/headroom.min.js"></script>
<script src="../site_libs/clipboard/clipboard.min.js"></script>
<script src="../site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="../site_libs/quarto-search/fuse.min.js"></script>
<script src="../site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="../">
<link href="../images/DACSS_Round_Network.png" rel="icon" type="image/png">
<script src="../site_libs/quarto-html/quarto.js"></script>
<script src="../site_libs/quarto-html/popper.min.js"></script>
<script src="../site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="../site_libs/quarto-html/anchor.min.js"></script>
<link href="../site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="../site_libs/quarto-html/quarto-syntax-highlighting.css" rel="stylesheet" class="quarto-color-scheme" id="quarto-text-highlighting-styles">
<link href="../site_libs/quarto-html/quarto-syntax-highlighting-dark.css" rel="prefetch" class="quarto-color-scheme quarto-color-alternate" id="quarto-text-highlighting-styles">
<script src="../site_libs/bootstrap/bootstrap.min.js"></script>
<link href="../site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="../site_libs/bootstrap/bootstrap.min.css" rel="stylesheet" class="quarto-color-scheme" id="quarto-bootstrap" data-mode="light">
<link href="../site_libs/bootstrap/bootstrap-dark.min.css" rel="prefetch" class="quarto-color-scheme quarto-color-alternate" id="quarto-bootstrap" data-mode="dark">
<script id="quarto-search-options" type="application/json">{
  "location": "navbar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "end",
  "type": "overlay",
  "limit": 20,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit"
  }
}</script>


<meta name="twitter:title" content="Homework 4 - Emily Duryea">
<meta name="twitter:description" content="The fourth homework assignment for DACSS 603">
<meta name="twitter:creator" content="@UMassDACSS">
<meta name="twitter:site" content="@UMassDACSS">
<meta name="twitter:card" content="summary">
</head>

<body class="nav-fixed">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
    <nav class="navbar navbar-expand-lg navbar-dark ">
      <div class="navbar-container container-fluid">
      <div class="navbar-brand-container">
    <a href="../index.html" class="navbar-brand navbar-brand-logo">
    <img src="../images/UMass White Wordmark Horiz.png" alt="" class="navbar-logo">
    </a>
  </div>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse" aria-controls="navbarCollapse" aria-expanded="false" aria-label="Toggle navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
  <span class="navbar-toggler-icon"></span>
</button>
          <div class="collapse navbar-collapse" id="navbarCollapse">
            <ul class="navbar-nav navbar-nav-scroll ms-auto">
  <li class="nav-item">
    <a class="nav-link" href="https://dacss.github.io/603_Fall_2022/">
 <span class="menu-text">Fall 2022 Posts</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="../about.html">
 <span class="menu-text">Contributors</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="https://umass.edu/sbs/dacss">
 <span class="menu-text">DACSS</span></a>
  </li>  
  <li class="nav-item compact">
    <a class="nav-link" href="https://github.com/DACSS/603_Fall_2022"><i class="bi bi-github" role="img" aria-label="GitHub">
</i> 
 <span class="menu-text"></span></a>
  </li>  
</ul>
              <div class="quarto-toggle-container">
                  <a href="" class="quarto-color-scheme-toggle nav-link" onclick="window.quartoToggleColorScheme(); return false;" title="Toggle dark mode"><i class="bi"></i></a>
              </div>
              <div id="quarto-search" class="" title="Search"></div>
          </div> <!-- /navcollapse -->
      </div> <!-- /container-fluid -->
    </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article page-navbar">
<!-- sidebar -->
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">On this page</h2>
   
  <ul>
  <li><a href="#homework-4" id="toc-homework-4" class="nav-link active" data-scroll-target="#homework-4">Homework 4</a>
  <ul class="collapse">
  <li><a href="#question-1" id="toc-question-1" class="nav-link" data-scroll-target="#question-1">Question 1</a>
  <ul class="collapse">
  <li><a href="#part-a" id="toc-part-a" class="nav-link" data-scroll-target="#part-a">Part A</a></li>
  <li><a href="#part-b" id="toc-part-b" class="nav-link" data-scroll-target="#part-b">Part B</a></li>
  <li><a href="#part-c" id="toc-part-c" class="nav-link" data-scroll-target="#part-c">Part C</a></li>
  </ul></li>
  <li><a href="#question-2" id="toc-question-2" class="nav-link" data-scroll-target="#question-2">Question 2</a>
  <ul class="collapse">
  <li><a href="#part-a-1" id="toc-part-a-1" class="nav-link" data-scroll-target="#part-a-1">Part A</a></li>
  <li><a href="#part-b-1" id="toc-part-b-1" class="nav-link" data-scroll-target="#part-b-1">Part B</a></li>
  <li><a href="#part-c-1" id="toc-part-c-1" class="nav-link" data-scroll-target="#part-c-1">Part C</a></li>
  <li><a href="#part-d" id="toc-part-d" class="nav-link" data-scroll-target="#part-d">Part D</a></li>
  <li><a href="#part-e" id="toc-part-e" class="nav-link" data-scroll-target="#part-e">Part E</a></li>
  <li><a href="#part-f" id="toc-part-f" class="nav-link" data-scroll-target="#part-f">Part F</a></li>
  </ul></li>
  <li><a href="#question-3" id="toc-question-3" class="nav-link" data-scroll-target="#question-3">Question 3</a>
  <ul class="collapse">
  <li><a href="#part-a-2" id="toc-part-a-2" class="nav-link" data-scroll-target="#part-a-2">Part A</a></li>
  <li><a href="#part-b-2" id="toc-part-b-2" class="nav-link" data-scroll-target="#part-b-2">Part B</a></li>
  <li><a href="#part-c-2" id="toc-part-c-2" class="nav-link" data-scroll-target="#part-c-2">Part C</a></li>
  <li><a href="#part-d-1" id="toc-part-d-1" class="nav-link" data-scroll-target="#part-d-1">Part D</a></li>
  <li><a href="#part-e-1" id="toc-part-e-1" class="nav-link" data-scroll-target="#part-e-1">Part E</a></li>
  <li><a href="#part-f-1" id="toc-part-f-1" class="nav-link" data-scroll-target="#part-f-1">Part F</a></li>
  <li><a href="#part-g" id="toc-part-g" class="nav-link" data-scroll-target="#part-g">Part G</a></li>
  <li><a href="#part-h" id="toc-part-h" class="nav-link" data-scroll-target="#part-h">Part H</a></li>
  </ul></li>
  </ul></li>
  </ul>
</nav>
    </div>
<!-- main -->
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<div class="quarto-title-block"><div><h1 class="title">Homework 4 - Emily Duryea</h1><button type="button" class="btn code-tools-button dropdown-toggle" id="quarto-code-tools-menu" data-bs-toggle="dropdown" aria-expanded="false"><i class="bi"></i> Code</button><ul class="dropdown-menu dropdown-menu-end" aria-labelelledby="quarto-code-tools-menu"><li><a id="quarto-show-all-code" class="dropdown-item" href="javascript:void(0)" role="button">Show All Code</a></li><li><a id="quarto-hide-all-code" class="dropdown-item" href="javascript:void(0)" role="button">Hide All Code</a></li><li><hr class="dropdown-divider"></li><li><a id="quarto-view-source" class="dropdown-item" href="javascript:void(0)" role="button">View Source</a></li></ul></div></div>
  <div class="quarto-categories">
    <div class="quarto-category">hw4</div>
    <div class="quarto-category">Emily Duryea</div>
  </div>
  </div>

<div>
  <div class="description">
    The fourth homework assignment for DACSS 603
  </div>
</div>


<div class="quarto-title-meta">

    <div>
    <div class="quarto-title-meta-heading">Author</div>
    <div class="quarto-title-meta-contents">
             <p>Emily Duryea </p>
          </div>
  </div>
    
    <div>
    <div class="quarto-title-meta-heading">Published</div>
    <div class="quarto-title-meta-contents">
      <p class="date">November 14, 2022</p>
    </div>
  </div>
  
    
  </div>
  

</header>

<section id="homework-4" class="level1">
<h1>Homework 4</h1>
<section id="question-1" class="level2">
<h2 class="anchored" data-anchor-id="question-1">Question 1</h2>
<p>For recent data in Jacksonville, Florida, on y = selling price of home (in dollars), x1 = size of home (in square feet), and x2 = lot size (in square feet), the prediction equation is&nbsp;</p>
<p>ŷ = −10,536 + 53.8x1 + 2.84x2.</p>
<div class="cell">
<details>
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb1"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Importing needed libraries</span></span>
<span id="cb1-2"><a href="#cb1-2" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(readxl)</span>
<span id="cb1-3"><a href="#cb1-3" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(tidyverse)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stderr">
<pre><code>── Attaching packages ─────────────────────────────────────── tidyverse 1.3.2 ──
✔ ggplot2 3.4.0      ✔ purrr   0.3.5 
✔ tibble  3.1.8      ✔ dplyr   1.0.10
✔ tidyr   1.2.1      ✔ stringr 1.4.1 
✔ readr   2.1.3      ✔ forcats 0.5.2 
── Conflicts ────────────────────────────────────────── tidyverse_conflicts() ──
✖ dplyr::filter() masks stats::filter()
✖ dplyr::lag()    masks stats::lag()</code></pre>
</div>
<details>
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb3"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb3-1"><a href="#cb3-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(ggplot2)</span>
<span id="cb3-2"><a href="#cb3-2" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(dplyr)</span>
<span id="cb3-3"><a href="#cb3-3" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(stringr)</span>
<span id="cb3-4"><a href="#cb3-4" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(alr4)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stderr">
<pre><code>Loading required package: car
Loading required package: carData

Attaching package: 'car'

The following object is masked from 'package:dplyr':

    recode

The following object is masked from 'package:purrr':

    some

Loading required package: effects
lattice theme set by effectsTheme()
See ?effectsTheme for details.</code></pre>
</div>
<details>
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb5"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb5-1"><a href="#cb5-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(smss)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
</div>
<section id="part-a" class="level3">
<h3 class="anchored" data-anchor-id="part-a">Part A</h3>
<p>A particular home of 1240 square feet on a lot of 18,000 square feet sold for $145,000. Find the predicted selling price and the residual, and interpret.</p>
<div class="cell">
<details>
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb6"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb6-1"><a href="#cb6-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Plugging given values into the equation to solve</span></span>
<span id="cb6-2"><a href="#cb6-2" aria-hidden="true" tabindex="-1"></a><span class="sc">-</span><span class="dv">10536</span> <span class="sc">+</span> <span class="fl">53.8</span><span class="sc">*</span><span class="dv">1240</span> <span class="sc">+</span> <span class="fl">2.84</span><span class="sc">*</span><span class="dv">18000</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 107296</code></pre>
</div>
<details>
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb8"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb8-1"><a href="#cb8-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Calculating the residual</span></span>
<span id="cb8-2"><a href="#cb8-2" aria-hidden="true" tabindex="-1"></a><span class="dv">145000-107296</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 37704</code></pre>
</div>
</div>
<p>The predicted selling price of the house would be $107,296, and the residual would be $37,704.</p>
</section>
<section id="part-b" class="level3">
<h3 class="anchored" data-anchor-id="part-b">Part B</h3>
<p>For fixed lot size, how much is the house selling price predicted to increase for each square-foot increase in home size? Why?</p>
<p>The house selling price predicted to increase for each square-foot increase is $53.80, based on the multiplier in the prediction equation.</p>
</section>
<section id="part-c" class="level3">
<h3 class="anchored" data-anchor-id="part-c">Part C</h3>
<p>According to this prediction equation, for fixed home size, how much would lot size need to increase to have the same impact as a one-square-foot increase in home size?</p>
<div class="cell">
<details>
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb10"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb10-1"><a href="#cb10-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Calculating using square foot home size multiplier and square foot lot size multipler</span></span>
<span id="cb10-2"><a href="#cb10-2" aria-hidden="true" tabindex="-1"></a><span class="fl">53.8</span><span class="sc">/</span><span class="fl">2.84</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 18.94366</code></pre>
</div>
</div>
<p>The lot size of a fixed size home would have to increase by 18.94366 feet to have the same impact as a one square foot increase in home size.</p>
</section>
</section>
<section id="question-2" class="level2">
<h2 class="anchored" data-anchor-id="question-2">Question 2</h2>
<p>(Data file: salary in <strong>alr4</strong> R package). The data file concerns salary and other characteristics of all faculty in a small Midwestern college collected in the early 1980s for presentation in legal proceedings for which discrimination against women in salary was at issue. All persons in the data hold tenured or tenure track positions; temporary faculty are not included. The variables include degree, a factor with levels PhD and MS; rank, a factor with levels Asst, Assoc, and Prof; sex, a factor with levels Male and Female; Year, years in current rank; ysdeg, years since highest degree, and salary, academic year salary in dollars.</p>
<section id="part-a-1" class="level3">
<h3 class="anchored" data-anchor-id="part-a-1">Part A</h3>
<p>Test the hypothesis that the mean salary for men and women is the same, without regard to any other variable but sex. Explain your findings.</p>
<div class="cell">
<details>
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb12"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb12-1"><a href="#cb12-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Importing the data</span></span>
<span id="cb12-2"><a href="#cb12-2" aria-hidden="true" tabindex="-1"></a><span class="fu">data</span>(salary)</span>
<span id="cb12-3"><a href="#cb12-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb12-4"><a href="#cb12-4" aria-hidden="true" tabindex="-1"></a><span class="co"># Conducting a t-test to test hypothesis</span></span>
<span id="cb12-5"><a href="#cb12-5" aria-hidden="true" tabindex="-1"></a><span class="fu">t.test</span>(salary <span class="sc">~</span> sex, <span class="at">data=</span>salary)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>
    Welch Two Sample t-test

data:  salary by sex
t = 1.7744, df = 21.591, p-value = 0.09009
alternative hypothesis: true difference in means between group Male and group Female is not equal to 0
95 percent confidence interval:
 -567.8539 7247.1471
sample estimates:
  mean in group Male mean in group Female 
            24696.79             21357.14 </code></pre>
</div>
</div>
<p>Based on the results of the t-test, there is no statistically significant difference in the salary of male and female professors. This is because the p-value (0.09009) is greater than 0.05.</p>
</section>
<section id="part-b-1" class="level3">
<h3 class="anchored" data-anchor-id="part-b-1">Part B</h3>
<p>Run a multiple linear regression with salary as the outcome variable and everything else as predictors, including sex. Assuming no interactions between sex and the other predictors, obtain a 95% confidence interval for the difference in salary between males and females.</p>
<div class="cell">
<details>
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb14"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb14-1"><a href="#cb14-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Creating the model</span></span>
<span id="cb14-2"><a href="#cb14-2" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(<span class="fu">lm</span>(salary <span class="sc">~</span> degree <span class="sc">+</span> rank <span class="sc">+</span> sex <span class="sc">+</span> year <span class="sc">+</span> ysdeg, <span class="at">data=</span>salary))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = salary ~ degree + rank + sex + year + ysdeg, data = salary)

Residuals:
    Min      1Q  Median      3Q     Max 
-4045.2 -1094.7  -361.5   813.2  9193.1 

Coefficients:
            Estimate Std. Error t value Pr(&gt;|t|)    
(Intercept) 15746.05     800.18  19.678  &lt; 2e-16 ***
degreePhD    1388.61    1018.75   1.363    0.180    
rankAssoc    5292.36    1145.40   4.621 3.22e-05 ***
rankProf    11118.76    1351.77   8.225 1.62e-10 ***
sexFemale    1166.37     925.57   1.260    0.214    
year          476.31      94.91   5.018 8.65e-06 ***
ysdeg        -124.57      77.49  -1.608    0.115    
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 2398 on 45 degrees of freedom
Multiple R-squared:  0.855, Adjusted R-squared:  0.8357 
F-statistic: 44.24 on 6 and 45 DF,  p-value: &lt; 2.2e-16</code></pre>
</div>
<details>
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb16"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb16-1"><a href="#cb16-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Putting model data into a variable</span></span>
<span id="cb16-2"><a href="#cb16-2" aria-hidden="true" tabindex="-1"></a>professor_salary <span class="ot">&lt;-</span> <span class="fu">lm</span>(salary <span class="sc">~</span> degree <span class="sc">+</span> rank <span class="sc">+</span> sex <span class="sc">+</span> year <span class="sc">+</span> ysdeg, <span class="at">data=</span>salary)</span>
<span id="cb16-3"><a href="#cb16-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb16-4"><a href="#cb16-4" aria-hidden="true" tabindex="-1"></a><span class="co">#Creating a confidence interval for the variables in the model</span></span>
<span id="cb16-5"><a href="#cb16-5" aria-hidden="true" tabindex="-1"></a><span class="fu">confint</span>(professor_salary)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>                 2.5 %      97.5 %
(Intercept) 14134.4059 17357.68946
degreePhD    -663.2482  3440.47485
rankAssoc    2985.4107  7599.31080
rankProf     8396.1546 13841.37340
sexFemale    -697.8183  3030.56452
year          285.1433   667.47476
ysdeg        -280.6397    31.49105</code></pre>
</div>
</div>
<p>The confidence interval for salary difference based on sex is between -697.8183 and 3,030.56452.</p>
</section>
<section id="part-c-1" class="level3">
<h3 class="anchored" data-anchor-id="part-c-1">Part C</h3>
<p>Interpret your finding for each predictor variable; discuss (a) statistical significance, (b) interpretation of the coefficient / slope in relation to the outcome variable and other variables</p>
<section id="degree" class="level4">
<h4 class="anchored" data-anchor-id="degree">Degree</h4>
<p>The p-value is not statistically significant, as the p-value is greater than 0.05. The results indicate that professors with a PhD make $1,388.61 than professors without a PhD.</p>
</section>
<section id="rankassoc" class="level4">
<h4 class="anchored" data-anchor-id="rankassoc">rankAssoc</h4>
<p>The p-value is statistically significant, as it is less than 0.05. The results indicate that associate professors make $5,292.36 than assistant professors.</p>
</section>
<section id="rankprof" class="level4">
<h4 class="anchored" data-anchor-id="rankprof">rankProf</h4>
<p>The p-value is statistically significant. The results indicate that faculty professors make $11,118.76 more than assistant professors.</p>
</section>
<section id="sex" class="level4">
<h4 class="anchored" data-anchor-id="sex">Sex</h4>
<p>The p-value is not statistically significant. The results indicate that female professors make $1,166.37 more than male professors.</p>
</section>
<section id="year" class="level4">
<h4 class="anchored" data-anchor-id="year">Year</h4>
<p>The p-value is statistically significant. The results indicate that with each year as a professor, there is a salary increase of $476.31.</p>
</section>
<section id="ysdeg" class="level4">
<h4 class="anchored" data-anchor-id="ysdeg">Ysdeg</h4>
<p>The p-value is not statistically significant. The results indicate that for each year after completing their highest degree, there is a salary decrease of $124.57.</p>
</section>
</section>
<section id="part-d" class="level3">
<h3 class="anchored" data-anchor-id="part-d">Part D</h3>
<p>Change the baseline category for the rank variable. Interpret the coefficients related to rank again.</p>
<div class="cell">
<details>
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb18"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb18-1"><a href="#cb18-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Changing the baseline category for the rank variable</span></span>
<span id="cb18-2"><a href="#cb18-2" aria-hidden="true" tabindex="-1"></a>salary<span class="sc">$</span>rank<span class="ot">&lt;-</span> <span class="fu">relevel</span>(salary<span class="sc">$</span>rank, <span class="at">ref =</span> <span class="st">'Assoc'</span>)</span>
<span id="cb18-3"><a href="#cb18-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb18-4"><a href="#cb18-4" aria-hidden="true" tabindex="-1"></a><span class="co"># Redoing the model from Part B</span></span>
<span id="cb18-5"><a href="#cb18-5" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(<span class="fu">lm</span>(salary <span class="sc">~</span> degree <span class="sc">+</span> rank <span class="sc">+</span> sex <span class="sc">+</span> year <span class="sc">+</span> ysdeg, <span class="at">data=</span>salary))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = salary ~ degree + rank + sex + year + ysdeg, data = salary)

Residuals:
    Min      1Q  Median      3Q     Max 
-4045.2 -1094.7  -361.5   813.2  9193.1 

Coefficients:
            Estimate Std. Error t value Pr(&gt;|t|)    
(Intercept) 21038.41    1109.12  18.969  &lt; 2e-16 ***
degreePhD    1388.61    1018.75   1.363    0.180    
rankAsst    -5292.36    1145.40  -4.621 3.22e-05 ***
rankProf     5826.40    1012.93   5.752 7.28e-07 ***
sexFemale    1166.37     925.57   1.260    0.214    
year          476.31      94.91   5.018 8.65e-06 ***
ysdeg        -124.57      77.49  -1.608    0.115    
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 2398 on 45 degrees of freedom
Multiple R-squared:  0.855, Adjusted R-squared:  0.8357 
F-statistic: 44.24 on 6 and 45 DF,  p-value: &lt; 2.2e-16</code></pre>
</div>
</div>
<p>The baseline category has been changed to “Assoc.” The results indicate that assistant professors make $5,292.36 less than Associate professors. Faculty professor are expected to make $5,826.40 more than Associate professors. These results are both still statistically significant (p-value &lt; 0.05).</p>
</section>
<section id="part-e" class="level3">
<h3 class="anchored" data-anchor-id="part-e">Part E</h3>
<p>Finkelstein (1980), in a discussion of the use of regression in discrimination cases, wrote, "[a] variable may reflect a position or status bestowed by the employer, in which case if there is discrimination in the award of the position or status, the variable may be 'tainted.' " Thus, for example, if discrimination is at work in promotion of faculty to higher ranks, using rank to adjust salaries before comparing the sexes may not be acceptable to the courts. Exclude the variable rank, refit, and summarize how your findings changed, if they did.</p>
<div class="cell">
<details>
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb20"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb20-1"><a href="#cb20-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Creating a model without rank</span></span>
<span id="cb20-2"><a href="#cb20-2" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(<span class="fu">lm</span>(salary <span class="sc">~</span> degree <span class="sc">+</span> sex <span class="sc">+</span> year <span class="sc">+</span> ysdeg, <span class="at">data=</span>salary))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = salary ~ degree + sex + year + ysdeg, data = salary)

Residuals:
    Min      1Q  Median      3Q     Max 
-8146.9 -2186.9  -491.5  2279.1 11186.6 

Coefficients:
            Estimate Std. Error t value Pr(&gt;|t|)    
(Intercept) 17183.57    1147.94  14.969  &lt; 2e-16 ***
degreePhD   -3299.35    1302.52  -2.533 0.014704 *  
sexFemale   -1286.54    1313.09  -0.980 0.332209    
year          351.97     142.48   2.470 0.017185 *  
ysdeg         339.40      80.62   4.210 0.000114 ***
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 3744 on 47 degrees of freedom
Multiple R-squared:  0.6312,    Adjusted R-squared:  0.5998 
F-statistic: 20.11 on 4 and 47 DF,  p-value: 1.048e-09</code></pre>
</div>
</div>
<p>After removing rank from the model, the results indicate that there is a difference between male and female salaries, with females making $1,286.54 less than men. However, this difference is not statistically significant.</p>
</section>
<section id="part-f" class="level3">
<h3 class="anchored" data-anchor-id="part-f">Part F</h3>
<p>Everyone in this dataset was hired the year they earned their highest degree. It is also known that a new Dean was appointed 15 years ago, and everyone in the dataset who earned their highest degree 15 years ago or less than that has been hired by the new Dean. Some people have argued that the new Dean has been making offers that are a lot more generous to newly hired faculty than the previous one and that this might explain some of the variation in Salary.</p>
<p>Create a new variable that would allow you to test this hypothesis and run another multiple regression model to test this. Select variables carefully to make sure there is no multicollinearity. Explain why multicollinearity would be a concern in this case and how you avoided it. Do you find support for the hypothesis that the people hired by the new Dean are making higher than those that were not?</p>
<div class="cell">
<details>
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb22"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb22-1"><a href="#cb22-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Creating a variable with categories "new" for less than 15 years, and "old" for 15 or more years</span></span>
<span id="cb22-2"><a href="#cb22-2" aria-hidden="true" tabindex="-1"></a><span class="co">#creating a dummy variable new and old dean</span></span>
<span id="cb22-3"><a href="#cb22-3" aria-hidden="true" tabindex="-1"></a>salary<span class="ot">&lt;-</span><span class="fu">mutate</span>(salary, <span class="at">dean=</span> <span class="fu">case_when</span>(ysdeg <span class="sc">&lt;</span> <span class="dv">15</span> <span class="sc">~</span><span class="st">"new"</span>,</span>
<span id="cb22-4"><a href="#cb22-4" aria-hidden="true" tabindex="-1"></a>                               ysdeg <span class="sc">&gt;=</span><span class="dv">15</span> <span class="sc">~</span><span class="st">"old"</span>))</span>
<span id="cb22-5"><a href="#cb22-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb22-6"><a href="#cb22-6" aria-hidden="true" tabindex="-1"></a><span class="co"># Rerunning the model with new variable</span></span>
<span id="cb22-7"><a href="#cb22-7" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(<span class="fu">lm</span>(salary <span class="sc">~</span> dean <span class="sc">+</span> degree <span class="sc">+</span> sex <span class="sc">+</span> rank <span class="sc">+</span>year, <span class="at">data=</span>salary))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = salary ~ dean + degree + sex + rank + year, data = salary)

Residuals:
    Min      1Q  Median      3Q     Max 
-3588.0 -1532.2  -232.2   565.7  9132.5 

Coefficients:
            Estimate Std. Error t value Pr(&gt;|t|)    
(Intercept)  20468.7      951.7  21.507  &lt; 2e-16 ***
deanold      -2421.6     1187.9  -2.038   0.0474 *  
degreePhD     1073.5      843.3   1.273   0.2096    
sexFemale     1046.7      858.0   1.220   0.2289    
rankAsst     -5012.5     1002.3  -5.001 9.16e-06 ***
rankProf      6213.3     1045.0   5.946 3.76e-07 ***
year           450.7       81.5   5.530 1.55e-06 ***
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 2360 on 45 degrees of freedom
Multiple R-squared:  0.8597,    Adjusted R-squared:  0.841 
F-statistic: 45.95 on 6 and 45 DF,  p-value: &lt; 2.2e-16</code></pre>
</div>
</div>
<p>Based on the new variable and controlling for other predictors, faculty hired by the old dean make $2,421.60 less than new faculty.</p>
</section>
</section>
<section id="question-3" class="level2">
<h2 class="anchored" data-anchor-id="question-3">Question 3</h2>
<p>(Data file: house.selling.price in <strong>smss</strong> R package)</p>
<section id="part-a-2" class="level3">
<h3 class="anchored" data-anchor-id="part-a-2">Part A</h3>
<p>Using the house.selling.price data, run and report regression results modeling y = selling price (in dollars) in terms of sizeof home (in square feet) and whether the home is new(1 = yes; 0 = no). In particular, for each variable; discuss statistical significance and interpret the meaning of the coefficient.</p>
<div class="cell">
<details>
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb24"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb24-1"><a href="#cb24-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Importing needed data</span></span>
<span id="cb24-2"><a href="#cb24-2" aria-hidden="true" tabindex="-1"></a><span class="fu">data</span>(house.selling.price)</span>
<span id="cb24-3"><a href="#cb24-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb24-4"><a href="#cb24-4" aria-hidden="true" tabindex="-1"></a><span class="co"># Creating model based on size and age status</span></span>
<span id="cb24-5"><a href="#cb24-5" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(<span class="fu">lm</span>(Price <span class="sc">~</span> Size <span class="sc">+</span> New, <span class="at">data=</span> house.selling.price))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = Price ~ Size + New, data = house.selling.price)

Residuals:
    Min      1Q  Median      3Q     Max 
-205102  -34374   -5778   18929  163866 

Coefficients:
              Estimate Std. Error t value Pr(&gt;|t|)    
(Intercept) -40230.867  14696.140  -2.738  0.00737 ** 
Size           116.132      8.795  13.204  &lt; 2e-16 ***
New          57736.283  18653.041   3.095  0.00257 ** 
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 53880 on 97 degrees of freedom
Multiple R-squared:  0.7226,    Adjusted R-squared:  0.7169 
F-statistic: 126.3 on 2 and 97 DF,  p-value: &lt; 2.2e-16</code></pre>
</div>
</div>
<p>Based on the size variable, the house price will increase by ~$116.132 for each square foot increase in size. This finding is statistically significant.</p>
<p>Based on the age of the house variable, a new house is projected to cost ~$57,736.283 more than an old house. This finding is also statistically significant.<br>
</p>
</section>
<section id="part-b-2" class="level3">
<h3 class="anchored" data-anchor-id="part-b-2">Part B</h3>
<p>Report and interpret the prediction equation, and form separate equations relating selling price to size for new and for not new homes.</p>
<p>Prediction equation:</p>
<p>y = -40230.867 + 116.13*x1 + 57736.283*x2</p>
<p>x1 = size</p>
<p>x2 = age of house (old vs.&nbsp;new)</p>
<p>Prediction equation for a new house:</p>
<p>y = -40230.867 + 116.132*x1 + 57736.283</p>
<p>Prediction equation for an old house:</p>
<p>y = -40230.867 + 116.132*x1</p>
</section>
<section id="part-c-2" class="level3">
<h3 class="anchored" data-anchor-id="part-c-2">Part C</h3>
<p>Find the predicted selling price for a home of 3000 square feet that is (i) new, (ii) not new.</p>
<div class="cell">
<details>
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb26"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb26-1"><a href="#cb26-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Using the prediction model to predict the cost of a new house</span></span>
<span id="cb26-2"><a href="#cb26-2" aria-hidden="true" tabindex="-1"></a><span class="sc">-</span><span class="fl">40230.867</span> <span class="sc">+</span> <span class="fl">116.132</span><span class="sc">*</span><span class="dv">3000</span> <span class="sc">+</span>  <span class="fl">57736.283</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 365901.4</code></pre>
</div>
<details>
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb28"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb28-1"><a href="#cb28-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Using the prediction model to predict the cost of an old house</span></span>
<span id="cb28-2"><a href="#cb28-2" aria-hidden="true" tabindex="-1"></a><span class="sc">-</span><span class="fl">40230.867</span> <span class="sc">+</span> <span class="fl">116.132</span><span class="sc">*</span><span class="dv">3000</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 308165.1</code></pre>
</div>
</div>
<p>Based on the prediction model, a new house of 3,000 square feet would cost $365,901.40, while an old house of the same size would cost $308,165.10.</p>
</section>
<section id="part-d-1" class="level3">
<h3 class="anchored" data-anchor-id="part-d-1">Part D</h3>
<p>Fit another model, this time with an interaction term allowing interaction between size and new, and report the regression results</p>
<div class="cell">
<details>
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb30"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb30-1"><a href="#cb30-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Creating a model for an interaction between size and new</span></span>
<span id="cb30-2"><a href="#cb30-2" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(<span class="fu">lm</span>(Price <span class="sc">~</span> Size <span class="sc">+</span> New <span class="sc">+</span> Size<span class="sc">*</span>New, <span class="at">data=</span>house.selling.price))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = Price ~ Size + New + Size * New, data = house.selling.price)

Residuals:
    Min      1Q  Median      3Q     Max 
-175748  -28979   -6260   14693  192519 

Coefficients:
              Estimate Std. Error t value Pr(&gt;|t|)    
(Intercept) -22227.808  15521.110  -1.432  0.15536    
Size           104.438      9.424  11.082  &lt; 2e-16 ***
New         -78527.502  51007.642  -1.540  0.12697    
Size:New        61.916     21.686   2.855  0.00527 ** 
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 52000 on 96 degrees of freedom
Multiple R-squared:  0.7443,    Adjusted R-squared:  0.7363 
F-statistic: 93.15 on 3 and 96 DF,  p-value: &lt; 2.2e-16</code></pre>
</div>
</div>
<p>Based on this model, the prediction equation would be y = -2227.808 + 104.438*x1 + 61.916*x2 -78527.502*x3, where x1 is the size of the house in square feet, x2 is the size and house age interaction variable, and x3 is the house age variable (old vs new). Both size and the interaction between size and house age are statistically significant. However, the house age variable is no longer statistically significant.</p>
</section>
<section id="part-e-1" class="level3">
<h3 class="anchored" data-anchor-id="part-e-1">Part E</h3>
<p>Report the lines relating the predicted selling price to the size for homes that are (i) new, (ii) not new.</p>
<p>Prediction equation for a new house:</p>
<p>y = -2227.808 + 166.354*x1 - 78527.502</p>
<p>Prediction equation for an old house:</p>
<p>y = -2227.808 + 104.438*x1</p>
</section>
<section id="part-f-1" class="level3">
<h3 class="anchored" data-anchor-id="part-f-1">Part F</h3>
<p>Find the predicted selling price for a home of 3000 square feet that is (i) new, (ii) not new.</p>
<div class="cell">
<details>
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb32"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb32-1"><a href="#cb32-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Using the prediction model to predict the cost of a new house</span></span>
<span id="cb32-2"><a href="#cb32-2" aria-hidden="true" tabindex="-1"></a><span class="sc">-</span><span class="fl">2227.808</span> <span class="sc">+</span> <span class="fl">166.354</span><span class="sc">*</span><span class="dv">3000</span> <span class="sc">-</span> <span class="fl">78527.502</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 418306.7</code></pre>
</div>
<details>
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb34"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb34-1"><a href="#cb34-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Using the prediction model to predict the cost of an old house</span></span>
<span id="cb34-2"><a href="#cb34-2" aria-hidden="true" tabindex="-1"></a><span class="sc">-</span><span class="fl">2227.808</span> <span class="sc">+</span> <span class="fl">104.438</span><span class="sc">*</span><span class="dv">3000</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 311086.2</code></pre>
</div>
</div>
<p>Based on the new prediction model, a new house of 3,000 square feet would cost $418,306.70, while an old house of the same size would cost $311,086.20.</p>
</section>
<section id="part-g" class="level3">
<h3 class="anchored" data-anchor-id="part-g">Part G</h3>
<p>Find the predicted selling price for a home of 1500 square feet that is (i) new, (ii) not new. Comparing to (F), explain how the difference in predicted selling prices changes as the size of home increases.</p>
<div class="cell">
<details>
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb36"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb36-1"><a href="#cb36-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Using the prediction model to predict the cost of a new house</span></span>
<span id="cb36-2"><a href="#cb36-2" aria-hidden="true" tabindex="-1"></a><span class="sc">-</span><span class="fl">2227.808</span> <span class="sc">+</span> <span class="fl">166.354</span><span class="sc">*</span><span class="dv">1500</span> <span class="sc">-</span> <span class="fl">78527.502</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 168775.7</code></pre>
</div>
<details>
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb38"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb38-1"><a href="#cb38-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Using the prediction model to predict the cost of an old house</span></span>
<span id="cb38-2"><a href="#cb38-2" aria-hidden="true" tabindex="-1"></a><span class="sc">-</span><span class="fl">2227.808</span> <span class="sc">+</span> <span class="fl">104.438</span><span class="sc">*</span><span class="dv">1500</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 154429.2</code></pre>
</div>
</div>
<p>Based on the new prediction model, a new house of 1,500 square feet would cost $168,775.70, while an old house of the same size would cost $154,429.20. This model demonstrates that small houses vary less in price, regardless of age, than larger houses, where new vs old houses makes much more of a difference.</p>
</section>
<section id="part-h" class="level3">
<h3 class="anchored" data-anchor-id="part-h">Part H</h3>
<p>Do you think the model with interaction or the one without it represents the relationship of size and new to the outcome price? What makes you prefer one model over another?</p>
<div class="cell">
<details>
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb40"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb40-1"><a href="#cb40-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Calculating predicted house cost of a large new house with first model</span></span>
<span id="cb40-2"><a href="#cb40-2" aria-hidden="true" tabindex="-1"></a><span class="sc">-</span><span class="fl">40230.867</span> <span class="sc">+</span> <span class="fl">116.132</span><span class="sc">*</span><span class="dv">5000</span> <span class="sc">+</span>  <span class="fl">57736.283</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 598165.4</code></pre>
</div>
<details>
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb42"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb42-1"><a href="#cb42-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Calculating predicted house cost of a large old house with first model</span></span>
<span id="cb42-2"><a href="#cb42-2" aria-hidden="true" tabindex="-1"></a><span class="sc">-</span><span class="fl">40230.867</span> <span class="sc">+</span> <span class="fl">116.132</span><span class="sc">*</span><span class="dv">5000</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 540429.1</code></pre>
</div>
<details>
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb44"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb44-1"><a href="#cb44-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Calculating predicted house cost of a small new house with first model</span></span>
<span id="cb44-2"><a href="#cb44-2" aria-hidden="true" tabindex="-1"></a><span class="sc">-</span><span class="fl">40230.867</span> <span class="sc">+</span> <span class="fl">116.132</span><span class="sc">*</span><span class="dv">1000</span> <span class="sc">+</span>  <span class="fl">57736.283</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 133637.4</code></pre>
</div>
<details>
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb46"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb46-1"><a href="#cb46-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Calculating predicted house cost of a small old house with the first model</span></span>
<span id="cb46-2"><a href="#cb46-2" aria-hidden="true" tabindex="-1"></a><span class="sc">-</span><span class="fl">40230.867</span> <span class="sc">+</span> <span class="fl">116.132</span><span class="sc">*</span><span class="dv">1000</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 75901.13</code></pre>
</div>
<details>
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb48"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb48-1"><a href="#cb48-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Calculating predicted house cost of a large new house with second model</span></span>
<span id="cb48-2"><a href="#cb48-2" aria-hidden="true" tabindex="-1"></a><span class="sc">-</span><span class="fl">2227.808</span> <span class="sc">+</span> <span class="fl">166.354</span><span class="sc">*</span><span class="dv">5000</span> <span class="sc">-</span> <span class="fl">78527.502</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 751014.7</code></pre>
</div>
<details>
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb50"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb50-1"><a href="#cb50-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Calculating predicted house cost of a large old house with second model</span></span>
<span id="cb50-2"><a href="#cb50-2" aria-hidden="true" tabindex="-1"></a><span class="sc">-</span><span class="fl">2227.808</span> <span class="sc">+</span> <span class="fl">104.438</span><span class="sc">*</span><span class="dv">5000</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 519962.2</code></pre>
</div>
<details>
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb52"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb52-1"><a href="#cb52-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Calculating predicted house cost of a small new house with second model</span></span>
<span id="cb52-2"><a href="#cb52-2" aria-hidden="true" tabindex="-1"></a><span class="sc">-</span><span class="fl">2227.808</span> <span class="sc">+</span> <span class="fl">166.354</span><span class="sc">*</span><span class="dv">1000</span> <span class="sc">-</span> <span class="fl">78527.502</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 85598.69</code></pre>
</div>
<details>
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb54"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb54-1"><a href="#cb54-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Calculating predicted house cost of a small old house with the second model</span></span>
<span id="cb54-2"><a href="#cb54-2" aria-hidden="true" tabindex="-1"></a><span class="sc">-</span><span class="fl">2227.808</span> <span class="sc">+</span> <span class="fl">104.438</span><span class="sc">*</span><span class="dv">1000</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 102210.2</code></pre>
</div>
</div>
<p>I think that it depends. For large houses, I would use the second model, because it shows the difference the price a new house vs an old house more greatly. However, for smaller houses, the second model is inaccurate, since it predicts that a new small house would be cheaper than an old small house. I think the first model would be a better predictor for small houses.</p>


<!-- -->

</section>
</section>
</section>

</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const disableStylesheet = (stylesheets) => {
    for (let i=0; i < stylesheets.length; i++) {
      const stylesheet = stylesheets[i];
      stylesheet.rel = 'prefetch';
    }
  }
  const enableStylesheet = (stylesheets) => {
    for (let i=0; i < stylesheets.length; i++) {
      const stylesheet = stylesheets[i];
      stylesheet.rel = 'stylesheet';
    }
  }
  const manageTransitions = (selector, allowTransitions) => {
    const els = window.document.querySelectorAll(selector);
    for (let i=0; i < els.length; i++) {
      const el = els[i];
      if (allowTransitions) {
        el.classList.remove('notransition');
      } else {
        el.classList.add('notransition');
      }
    }
  }
  const toggleColorMode = (alternate) => {
    // Switch the stylesheets
    const alternateStylesheets = window.document.querySelectorAll('link.quarto-color-scheme.quarto-color-alternate');
    manageTransitions('#quarto-margin-sidebar .nav-link', false);
    if (alternate) {
      enableStylesheet(alternateStylesheets);
      for (const sheetNode of alternateStylesheets) {
        if (sheetNode.id === "quarto-bootstrap") {
          toggleBodyColorMode(sheetNode);
        }
      }
    } else {
      disableStylesheet(alternateStylesheets);
      toggleBodyColorPrimary();
    }
    manageTransitions('#quarto-margin-sidebar .nav-link', true);
    // Switch the toggles
    const toggles = window.document.querySelectorAll('.quarto-color-scheme-toggle');
    for (let i=0; i < toggles.length; i++) {
      const toggle = toggles[i];
      if (toggle) {
        if (alternate) {
          toggle.classList.add("alternate");     
        } else {
          toggle.classList.remove("alternate");
        }
      }
    }
    // Hack to workaround the fact that safari doesn't
    // properly recolor the scrollbar when toggling (#1455)
    if (navigator.userAgent.indexOf('Safari') > 0 && navigator.userAgent.indexOf('Chrome') == -1) {
      manageTransitions("body", false);
      window.scrollTo(0, 1);
      setTimeout(() => {
        window.scrollTo(0, 0);
        manageTransitions("body", true);
      }, 40);  
    }
  }
  const isFileUrl = () => { 
    return window.location.protocol === 'file:';
  }
  const hasAlternateSentinel = () => {  
    let styleSentinel = getColorSchemeSentinel();
    if (styleSentinel !== null) {
      return styleSentinel === "alternate";
    } else {
      return false;
    }
  }
  const setStyleSentinel = (alternate) => {
    const value = alternate ? "alternate" : "default";
    if (!isFileUrl()) {
      window.localStorage.setItem("quarto-color-scheme", value);
    } else {
      localAlternateSentinel = value;
    }
  }
  const getColorSchemeSentinel = () => {
    if (!isFileUrl()) {
      const storageValue = window.localStorage.getItem("quarto-color-scheme");
      return storageValue != null ? storageValue : localAlternateSentinel;
    } else {
      return localAlternateSentinel;
    }
  }
  let localAlternateSentinel = 'default';
  // Dark / light mode switch
  window.quartoToggleColorScheme = () => {
    // Read the current dark / light value 
    let toAlternate = !hasAlternateSentinel();
    toggleColorMode(toAlternate);
    setStyleSentinel(toAlternate);
  };
  // Ensure there is a toggle, if there isn't float one in the top right
  if (window.document.querySelector('.quarto-color-scheme-toggle') === null) {
    const a = window.document.createElement('a');
    a.classList.add('top-right');
    a.classList.add('quarto-color-scheme-toggle');
    a.href = "";
    a.onclick = function() { try { window.quartoToggleColorScheme(); } catch {} return false; };
    const i = window.document.createElement("i");
    i.classList.add('bi');
    a.appendChild(i);
    window.document.body.appendChild(a);
  }
  // Switch to dark mode if need be
  if (hasAlternateSentinel()) {
    toggleColorMode(true);
  } else {
    toggleColorMode(false);
  }
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const clipboard = new window.ClipboardJS('.code-copy-button', {
    target: function(trigger) {
      return trigger.previousElementSibling;
    }
  });
  clipboard.on('success', function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copied!");
    let tooltip;
    if (window.bootstrap) {
      button.setAttribute("data-bs-toggle", "tooltip");
      button.setAttribute("data-bs-placement", "left");
      button.setAttribute("data-bs-title", "Copied!");
      tooltip = new bootstrap.Tooltip(button, 
        { trigger: "manual", 
          customClass: "code-copy-button-tooltip",
          offset: [0, -8]});
      tooltip.show();    
    }
    setTimeout(function() {
      if (tooltip) {
        tooltip.hide();
        button.removeAttribute("data-bs-title");
        button.removeAttribute("data-bs-toggle");
        button.removeAttribute("data-bs-placement");
      }
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  });
  const viewSource = window.document.getElementById('quarto-view-source') ||
                     window.document.getElementById('quarto-code-tools-source');
  if (viewSource) {
    const sourceUrl = viewSource.getAttribute("data-quarto-source-url");
    viewSource.addEventListener("click", function(e) {
      if (sourceUrl) {
        // rstudio viewer pane
        if (/\bcapabilities=\b/.test(window.location)) {
          window.open(sourceUrl);
        } else {
          window.location.href = sourceUrl;
        }
      } else {
        const modal = new bootstrap.Modal(document.getElementById('quarto-embedded-source-code-modal'));
        modal.show();
      }
      return false;
    });
  }
  function toggleCodeHandler(show) {
    return function(e) {
      const detailsSrc = window.document.querySelectorAll(".cell > details > .sourceCode");
      for (let i=0; i<detailsSrc.length; i++) {
        const details = detailsSrc[i].parentElement;
        if (show) {
          details.open = true;
        } else {
          details.removeAttribute("open");
        }
      }
      const cellCodeDivs = window.document.querySelectorAll(".cell > .sourceCode");
      const fromCls = show ? "hidden" : "unhidden";
      const toCls = show ? "unhidden" : "hidden";
      for (let i=0; i<cellCodeDivs.length; i++) {
        const codeDiv = cellCodeDivs[i];
        if (codeDiv.classList.contains(fromCls)) {
          codeDiv.classList.remove(fromCls);
          codeDiv.classList.add(toCls);
        } 
      }
      return false;
    }
  }
  const hideAllCode = window.document.getElementById("quarto-hide-all-code");
  if (hideAllCode) {
    hideAllCode.addEventListener("click", toggleCodeHandler(false));
  }
  const showAllCode = window.document.getElementById("quarto-show-all-code");
  if (showAllCode) {
    showAllCode.addEventListener("click", toggleCodeHandler(true));
  }
  function tippyHover(el, contentFn) {
    const config = {
      allowHTML: true,
      content: contentFn,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start'
    };
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      return note.innerHTML;
    });
  }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
});
</script>
<script src="https://giscus.app/client.js" data-repo="DACSS/603_Fall_2022" data-repo-id="R_kgDOH568kA" data-category="Announcements" data-category-id="" data-mapping="title" data-reactions-enabled="1" data-emit-metadata="0" data-input-position="top" data-theme="light" data-lang="en" crossorigin="anonymous" async="">
</script><div class="modal fade" id="quarto-embedded-source-code-modal" tabindex="-1" aria-labelledby="quarto-embedded-source-code-modal-label" aria-hidden="true"><div class="modal-dialog modal-dialog-scrollable"><div class="modal-content"><div class="modal-header"><h5 class="modal-title" id="quarto-embedded-source-code-modal-label">Source Code</h5><button class="btn-close" data-bs-dismiss="modal"></button></div><div class="modal-body"><div class="">
<div class="sourceCode" id="cb56" data-shortcodes="false"><pre class="sourceCode markdown code-with-copy"><code class="sourceCode markdown"><span id="cb56-1"><a href="#cb56-1" aria-hidden="true" tabindex="-1"></a><span class="co">---</span></span>
<span id="cb56-2"><a href="#cb56-2" aria-hidden="true" tabindex="-1"></a><span class="an">title:</span><span class="co"> "Homework 4 - Emily Duryea"</span></span>
<span id="cb56-3"><a href="#cb56-3" aria-hidden="true" tabindex="-1"></a><span class="an">author:</span><span class="co"> "Emily Duryea"</span></span>
<span id="cb56-4"><a href="#cb56-4" aria-hidden="true" tabindex="-1"></a><span class="an">description:</span><span class="co"> "The fourth homework assignment for DACSS 603"</span></span>
<span id="cb56-5"><a href="#cb56-5" aria-hidden="true" tabindex="-1"></a><span class="an">date:</span><span class="co"> "11/14/2022"</span></span>
<span id="cb56-6"><a href="#cb56-6" aria-hidden="true" tabindex="-1"></a><span class="an">format:</span></span>
<span id="cb56-7"><a href="#cb56-7" aria-hidden="true" tabindex="-1"></a><span class="co">  html:</span></span>
<span id="cb56-8"><a href="#cb56-8" aria-hidden="true" tabindex="-1"></a><span class="co">    toc: true</span></span>
<span id="cb56-9"><a href="#cb56-9" aria-hidden="true" tabindex="-1"></a><span class="co">    code-fold: true</span></span>
<span id="cb56-10"><a href="#cb56-10" aria-hidden="true" tabindex="-1"></a><span class="co">    code-copy: true</span></span>
<span id="cb56-11"><a href="#cb56-11" aria-hidden="true" tabindex="-1"></a><span class="co">    code-tools: true</span></span>
<span id="cb56-12"><a href="#cb56-12" aria-hidden="true" tabindex="-1"></a><span class="an">categories:</span></span>
<span id="cb56-13"><a href="#cb56-13" aria-hidden="true" tabindex="-1"></a><span class="co">  - hw4</span></span>
<span id="cb56-14"><a href="#cb56-14" aria-hidden="true" tabindex="-1"></a><span class="co">  - Emily Duryea</span></span>
<span id="cb56-15"><a href="#cb56-15" aria-hidden="true" tabindex="-1"></a><span class="co">---</span></span>
<span id="cb56-16"><a href="#cb56-16" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb56-17"><a href="#cb56-17" aria-hidden="true" tabindex="-1"></a><span class="fu"># Homework 4</span></span>
<span id="cb56-18"><a href="#cb56-18" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb56-19"><a href="#cb56-19" aria-hidden="true" tabindex="-1"></a><span class="fu">## Question 1</span></span>
<span id="cb56-20"><a href="#cb56-20" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb56-21"><a href="#cb56-21" aria-hidden="true" tabindex="-1"></a>For recent data in Jacksonville, Florida, on y = selling price of home (in dollars), x1 = size of home (in square feet), and x2 = lot size (in square feet), the prediction equation is&nbsp;</span>
<span id="cb56-22"><a href="#cb56-22" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb56-23"><a href="#cb56-23" aria-hidden="true" tabindex="-1"></a>ŷ = −10,536 + 53.8x1 + 2.84x2.</span>
<span id="cb56-24"><a href="#cb56-24" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb56-27"><a href="#cb56-27" aria-hidden="true" tabindex="-1"></a><span class="in">```{r}</span></span>
<span id="cb56-28"><a href="#cb56-28" aria-hidden="true" tabindex="-1"></a><span class="co"># Importing needed libraries</span></span>
<span id="cb56-29"><a href="#cb56-29" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(readxl)</span>
<span id="cb56-30"><a href="#cb56-30" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(tidyverse)</span>
<span id="cb56-31"><a href="#cb56-31" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(ggplot2)</span>
<span id="cb56-32"><a href="#cb56-32" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(dplyr)</span>
<span id="cb56-33"><a href="#cb56-33" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(stringr)</span>
<span id="cb56-34"><a href="#cb56-34" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(alr4)</span>
<span id="cb56-35"><a href="#cb56-35" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(smss)</span>
<span id="cb56-36"><a href="#cb56-36" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb56-37"><a href="#cb56-37" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb56-38"><a href="#cb56-38" aria-hidden="true" tabindex="-1"></a><span class="fu">### Part A</span></span>
<span id="cb56-39"><a href="#cb56-39" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb56-40"><a href="#cb56-40" aria-hidden="true" tabindex="-1"></a>A particular home of 1240 square feet on a lot of 18,000 square feet sold for \$145,000. Find the predicted selling price and the residual, and interpret.</span>
<span id="cb56-41"><a href="#cb56-41" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb56-44"><a href="#cb56-44" aria-hidden="true" tabindex="-1"></a><span class="in">```{r}</span></span>
<span id="cb56-45"><a href="#cb56-45" aria-hidden="true" tabindex="-1"></a><span class="co"># Plugging given values into the equation to solve</span></span>
<span id="cb56-46"><a href="#cb56-46" aria-hidden="true" tabindex="-1"></a><span class="sc">-</span><span class="dv">10536</span> <span class="sc">+</span> <span class="fl">53.8</span><span class="sc">*</span><span class="dv">1240</span> <span class="sc">+</span> <span class="fl">2.84</span><span class="sc">*</span><span class="dv">18000</span></span>
<span id="cb56-47"><a href="#cb56-47" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb56-48"><a href="#cb56-48" aria-hidden="true" tabindex="-1"></a><span class="co"># Calculating the residual</span></span>
<span id="cb56-49"><a href="#cb56-49" aria-hidden="true" tabindex="-1"></a><span class="dv">145000-107296</span></span>
<span id="cb56-50"><a href="#cb56-50" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb56-51"><a href="#cb56-51" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb56-52"><a href="#cb56-52" aria-hidden="true" tabindex="-1"></a>The predicted selling price of the house would be \$107,296, and the residual would be \$37,704.</span>
<span id="cb56-53"><a href="#cb56-53" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb56-54"><a href="#cb56-54" aria-hidden="true" tabindex="-1"></a><span class="fu">### Part B</span></span>
<span id="cb56-55"><a href="#cb56-55" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb56-56"><a href="#cb56-56" aria-hidden="true" tabindex="-1"></a>For fixed lot size, how much is the house selling price predicted to increase for each square-foot increase in home size? Why?</span>
<span id="cb56-57"><a href="#cb56-57" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb56-58"><a href="#cb56-58" aria-hidden="true" tabindex="-1"></a>The house selling price predicted to increase for each square-foot increase is \$53.80, based on the multiplier in the prediction equation.</span>
<span id="cb56-59"><a href="#cb56-59" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb56-60"><a href="#cb56-60" aria-hidden="true" tabindex="-1"></a><span class="fu">### Part C</span></span>
<span id="cb56-61"><a href="#cb56-61" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb56-62"><a href="#cb56-62" aria-hidden="true" tabindex="-1"></a>According to this prediction equation, for fixed home size, how much would lot size need to increase to have the same impact as a one-square-foot increase in home size?</span>
<span id="cb56-63"><a href="#cb56-63" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb56-66"><a href="#cb56-66" aria-hidden="true" tabindex="-1"></a><span class="in">```{r}</span></span>
<span id="cb56-67"><a href="#cb56-67" aria-hidden="true" tabindex="-1"></a><span class="co"># Calculating using square foot home size multiplier and square foot lot size multipler</span></span>
<span id="cb56-68"><a href="#cb56-68" aria-hidden="true" tabindex="-1"></a><span class="fl">53.8</span><span class="sc">/</span><span class="fl">2.84</span></span>
<span id="cb56-69"><a href="#cb56-69" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb56-70"><a href="#cb56-70" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb56-71"><a href="#cb56-71" aria-hidden="true" tabindex="-1"></a>The lot size of a fixed size home would have to increase by 18.94366 feet to have the same impact as a one square foot increase in home size.</span>
<span id="cb56-72"><a href="#cb56-72" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb56-73"><a href="#cb56-73" aria-hidden="true" tabindex="-1"></a><span class="fu">## Question 2</span></span>
<span id="cb56-74"><a href="#cb56-74" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb56-75"><a href="#cb56-75" aria-hidden="true" tabindex="-1"></a>(Data file: salary in **alr4** R package). The data file concerns salary and other characteristics of all faculty in a small Midwestern college collected in the early 1980s for presentation in legal proceedings for which discrimination against women in salary was at issue. All persons in the data hold tenured or tenure track positions; temporary faculty are not included. The variables include degree, a factor with levels PhD and MS; rank, a factor with levels Asst, Assoc, and Prof; sex, a factor with levels Male and Female; Year, years in current rank; ysdeg, years since highest degree, and salary, academic year salary in dollars.</span>
<span id="cb56-76"><a href="#cb56-76" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb56-77"><a href="#cb56-77" aria-hidden="true" tabindex="-1"></a><span class="fu">### Part A</span></span>
<span id="cb56-78"><a href="#cb56-78" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb56-79"><a href="#cb56-79" aria-hidden="true" tabindex="-1"></a>Test the hypothesis that the mean salary for men and women is the same, without regard to any other variable but sex. Explain your findings.</span>
<span id="cb56-80"><a href="#cb56-80" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb56-83"><a href="#cb56-83" aria-hidden="true" tabindex="-1"></a><span class="in">```{r}</span></span>
<span id="cb56-84"><a href="#cb56-84" aria-hidden="true" tabindex="-1"></a><span class="co"># Importing the data</span></span>
<span id="cb56-85"><a href="#cb56-85" aria-hidden="true" tabindex="-1"></a><span class="fu">data</span>(salary)</span>
<span id="cb56-86"><a href="#cb56-86" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb56-87"><a href="#cb56-87" aria-hidden="true" tabindex="-1"></a><span class="co"># Conducting a t-test to test hypothesis</span></span>
<span id="cb56-88"><a href="#cb56-88" aria-hidden="true" tabindex="-1"></a><span class="fu">t.test</span>(salary <span class="sc">~</span> sex, <span class="at">data=</span>salary)</span>
<span id="cb56-89"><a href="#cb56-89" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb56-90"><a href="#cb56-90" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb56-91"><a href="#cb56-91" aria-hidden="true" tabindex="-1"></a>Based on the results of the t-test, there is no statistically significant difference in the salary of male and female professors. This is because the p-value (0.09009) is greater than 0.05.</span>
<span id="cb56-92"><a href="#cb56-92" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb56-93"><a href="#cb56-93" aria-hidden="true" tabindex="-1"></a><span class="fu">### Part B</span></span>
<span id="cb56-94"><a href="#cb56-94" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb56-95"><a href="#cb56-95" aria-hidden="true" tabindex="-1"></a>Run a multiple linear regression with salary as the outcome variable and everything else as predictors, including sex. Assuming no interactions between sex and the other predictors, obtain a 95% confidence interval for the difference in salary between males and females.</span>
<span id="cb56-96"><a href="#cb56-96" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb56-99"><a href="#cb56-99" aria-hidden="true" tabindex="-1"></a><span class="in">```{r}</span></span>
<span id="cb56-100"><a href="#cb56-100" aria-hidden="true" tabindex="-1"></a><span class="co"># Creating the model</span></span>
<span id="cb56-101"><a href="#cb56-101" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(<span class="fu">lm</span>(salary <span class="sc">~</span> degree <span class="sc">+</span> rank <span class="sc">+</span> sex <span class="sc">+</span> year <span class="sc">+</span> ysdeg, <span class="at">data=</span>salary))</span>
<span id="cb56-102"><a href="#cb56-102" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb56-103"><a href="#cb56-103" aria-hidden="true" tabindex="-1"></a><span class="co"># Putting model data into a variable</span></span>
<span id="cb56-104"><a href="#cb56-104" aria-hidden="true" tabindex="-1"></a>professor_salary <span class="ot">&lt;-</span> <span class="fu">lm</span>(salary <span class="sc">~</span> degree <span class="sc">+</span> rank <span class="sc">+</span> sex <span class="sc">+</span> year <span class="sc">+</span> ysdeg, <span class="at">data=</span>salary)</span>
<span id="cb56-105"><a href="#cb56-105" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb56-106"><a href="#cb56-106" aria-hidden="true" tabindex="-1"></a><span class="co">#Creating a confidence interval for the variables in the model</span></span>
<span id="cb56-107"><a href="#cb56-107" aria-hidden="true" tabindex="-1"></a><span class="fu">confint</span>(professor_salary)</span>
<span id="cb56-108"><a href="#cb56-108" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb56-109"><a href="#cb56-109" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb56-110"><a href="#cb56-110" aria-hidden="true" tabindex="-1"></a>The confidence interval for salary difference based on sex is between -697.8183 and 3,030.56452.</span>
<span id="cb56-111"><a href="#cb56-111" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb56-112"><a href="#cb56-112" aria-hidden="true" tabindex="-1"></a><span class="fu">### Part C</span></span>
<span id="cb56-113"><a href="#cb56-113" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb56-114"><a href="#cb56-114" aria-hidden="true" tabindex="-1"></a>Interpret your finding for each predictor variable; discuss (a) statistical significance, (b) interpretation of the coefficient / slope in relation to the outcome variable and other variables</span>
<span id="cb56-115"><a href="#cb56-115" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb56-116"><a href="#cb56-116" aria-hidden="true" tabindex="-1"></a><span class="fu">#### Degree</span></span>
<span id="cb56-117"><a href="#cb56-117" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb56-118"><a href="#cb56-118" aria-hidden="true" tabindex="-1"></a>The p-value is not statistically significant, as the p-value is greater than 0.05. The results indicate that professors with a PhD make \$1,388.61 than professors without a PhD.</span>
<span id="cb56-119"><a href="#cb56-119" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb56-120"><a href="#cb56-120" aria-hidden="true" tabindex="-1"></a><span class="fu">#### rankAssoc</span></span>
<span id="cb56-121"><a href="#cb56-121" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb56-122"><a href="#cb56-122" aria-hidden="true" tabindex="-1"></a>The p-value is statistically significant, as it is less than 0.05. The results indicate that associate professors make \$5,292.36 than assistant professors.</span>
<span id="cb56-123"><a href="#cb56-123" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb56-124"><a href="#cb56-124" aria-hidden="true" tabindex="-1"></a><span class="fu">#### rankProf</span></span>
<span id="cb56-125"><a href="#cb56-125" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb56-126"><a href="#cb56-126" aria-hidden="true" tabindex="-1"></a>The p-value is statistically significant. The results indicate that faculty professors make \$11,118.76 more than assistant professors.</span>
<span id="cb56-127"><a href="#cb56-127" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb56-128"><a href="#cb56-128" aria-hidden="true" tabindex="-1"></a><span class="fu">#### Sex</span></span>
<span id="cb56-129"><a href="#cb56-129" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb56-130"><a href="#cb56-130" aria-hidden="true" tabindex="-1"></a>The p-value is not statistically significant. The results indicate that female professors make \$1,166.37 more than male professors.</span>
<span id="cb56-131"><a href="#cb56-131" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb56-132"><a href="#cb56-132" aria-hidden="true" tabindex="-1"></a><span class="fu">#### Year</span></span>
<span id="cb56-133"><a href="#cb56-133" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb56-134"><a href="#cb56-134" aria-hidden="true" tabindex="-1"></a>The p-value is statistically significant. The results indicate that with each year as a professor, there is a salary increase of \$476.31.</span>
<span id="cb56-135"><a href="#cb56-135" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb56-136"><a href="#cb56-136" aria-hidden="true" tabindex="-1"></a><span class="fu">#### Ysdeg</span></span>
<span id="cb56-137"><a href="#cb56-137" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb56-138"><a href="#cb56-138" aria-hidden="true" tabindex="-1"></a>The p-value is not statistically significant. The results indicate that for each year after completing their highest degree, there is a salary decrease of \$124.57.</span>
<span id="cb56-139"><a href="#cb56-139" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb56-140"><a href="#cb56-140" aria-hidden="true" tabindex="-1"></a><span class="fu">### Part D</span></span>
<span id="cb56-141"><a href="#cb56-141" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb56-142"><a href="#cb56-142" aria-hidden="true" tabindex="-1"></a>Change the baseline category for the rank variable. Interpret the coefficients related to rank again.</span>
<span id="cb56-143"><a href="#cb56-143" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb56-146"><a href="#cb56-146" aria-hidden="true" tabindex="-1"></a><span class="in">```{r}</span></span>
<span id="cb56-147"><a href="#cb56-147" aria-hidden="true" tabindex="-1"></a><span class="co"># Changing the baseline category for the rank variable</span></span>
<span id="cb56-148"><a href="#cb56-148" aria-hidden="true" tabindex="-1"></a>salary<span class="sc">$</span>rank<span class="ot">&lt;-</span> <span class="fu">relevel</span>(salary<span class="sc">$</span>rank, <span class="at">ref =</span> <span class="st">'Assoc'</span>)</span>
<span id="cb56-149"><a href="#cb56-149" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb56-150"><a href="#cb56-150" aria-hidden="true" tabindex="-1"></a><span class="co"># Redoing the model from Part B</span></span>
<span id="cb56-151"><a href="#cb56-151" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(<span class="fu">lm</span>(salary <span class="sc">~</span> degree <span class="sc">+</span> rank <span class="sc">+</span> sex <span class="sc">+</span> year <span class="sc">+</span> ysdeg, <span class="at">data=</span>salary))</span>
<span id="cb56-152"><a href="#cb56-152" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb56-153"><a href="#cb56-153" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb56-154"><a href="#cb56-154" aria-hidden="true" tabindex="-1"></a>The baseline category has been changed to "Assoc." The results indicate that assistant professors make \$5,292.36 less than Associate professors. Faculty professor are expected to make \$5,826.40 more than Associate professors. These results are both still statistically significant (p-value <span class="sc">\&lt;</span> 0.05).</span>
<span id="cb56-155"><a href="#cb56-155" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb56-156"><a href="#cb56-156" aria-hidden="true" tabindex="-1"></a><span class="fu">### Part E</span></span>
<span id="cb56-157"><a href="#cb56-157" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb56-158"><a href="#cb56-158" aria-hidden="true" tabindex="-1"></a>Finkelstein (1980), in a discussion of the use of regression in discrimination cases, wrote, \"<span class="sc">\[</span>a<span class="sc">\]</span> variable may reflect a position or status bestowed by the employer, in which case if there is discrimination in the award of the position or status, the variable may be \'tainted.\' \" Thus, for example, if discrimination is at work in promotion of faculty to higher ranks, using rank to adjust salaries before comparing the sexes may not be acceptable to the courts. Exclude the variable rank, refit, and summarize how your findings changed, if they did.</span>
<span id="cb56-159"><a href="#cb56-159" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb56-162"><a href="#cb56-162" aria-hidden="true" tabindex="-1"></a><span class="in">```{r}</span></span>
<span id="cb56-163"><a href="#cb56-163" aria-hidden="true" tabindex="-1"></a><span class="co"># Creating a model without rank</span></span>
<span id="cb56-164"><a href="#cb56-164" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(<span class="fu">lm</span>(salary <span class="sc">~</span> degree <span class="sc">+</span> sex <span class="sc">+</span> year <span class="sc">+</span> ysdeg, <span class="at">data=</span>salary))</span>
<span id="cb56-165"><a href="#cb56-165" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb56-166"><a href="#cb56-166" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb56-167"><a href="#cb56-167" aria-hidden="true" tabindex="-1"></a>After removing rank from the model, the results indicate that there is a difference between male and female salaries, with females making \$1,286.54 less than men. However, this difference is not statistically significant.</span>
<span id="cb56-168"><a href="#cb56-168" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb56-169"><a href="#cb56-169" aria-hidden="true" tabindex="-1"></a><span class="fu">### Part F</span></span>
<span id="cb56-170"><a href="#cb56-170" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb56-171"><a href="#cb56-171" aria-hidden="true" tabindex="-1"></a>Everyone in this dataset was hired the year they earned their highest degree. It is also known that a new Dean was appointed 15 years ago, and everyone in the dataset who earned their highest degree 15 years ago or less than that has been hired by the new Dean. Some people have argued that the new Dean has been making offers that are a lot more generous to newly hired faculty than the previous one and that this might explain some of the variation in Salary.</span>
<span id="cb56-172"><a href="#cb56-172" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb56-173"><a href="#cb56-173" aria-hidden="true" tabindex="-1"></a>Create a new variable that would allow you to test this hypothesis and run another multiple regression model to test this. Select variables carefully to make sure there is no multicollinearity. Explain why multicollinearity would be a concern in this case and how you avoided it. Do you find support for the hypothesis that the people hired by the new Dean are making higher than those that were not?</span>
<span id="cb56-174"><a href="#cb56-174" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb56-177"><a href="#cb56-177" aria-hidden="true" tabindex="-1"></a><span class="in">```{r}</span></span>
<span id="cb56-178"><a href="#cb56-178" aria-hidden="true" tabindex="-1"></a><span class="co"># Creating a variable with categories "new" for less than 15 years, and "old" for 15 or more years</span></span>
<span id="cb56-179"><a href="#cb56-179" aria-hidden="true" tabindex="-1"></a><span class="co">#creating a dummy variable new and old dean</span></span>
<span id="cb56-180"><a href="#cb56-180" aria-hidden="true" tabindex="-1"></a>salary<span class="ot">&lt;-</span><span class="fu">mutate</span>(salary, <span class="at">dean=</span> <span class="fu">case_when</span>(ysdeg <span class="sc">&lt;</span> <span class="dv">15</span> <span class="sc">~</span><span class="st">"new"</span>,</span>
<span id="cb56-181"><a href="#cb56-181" aria-hidden="true" tabindex="-1"></a>                               ysdeg <span class="sc">&gt;=</span><span class="dv">15</span> <span class="sc">~</span><span class="st">"old"</span>))</span>
<span id="cb56-182"><a href="#cb56-182" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb56-183"><a href="#cb56-183" aria-hidden="true" tabindex="-1"></a><span class="co"># Rerunning the model with new variable</span></span>
<span id="cb56-184"><a href="#cb56-184" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(<span class="fu">lm</span>(salary <span class="sc">~</span> dean <span class="sc">+</span> degree <span class="sc">+</span> sex <span class="sc">+</span> rank <span class="sc">+</span>year, <span class="at">data=</span>salary))</span>
<span id="cb56-185"><a href="#cb56-185" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb56-186"><a href="#cb56-186" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb56-187"><a href="#cb56-187" aria-hidden="true" tabindex="-1"></a>Based on the new variable and controlling for other predictors, faculty hired by the old dean make \$2,421.60 less than new faculty.</span>
<span id="cb56-188"><a href="#cb56-188" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb56-189"><a href="#cb56-189" aria-hidden="true" tabindex="-1"></a><span class="fu">## Question 3</span></span>
<span id="cb56-190"><a href="#cb56-190" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb56-191"><a href="#cb56-191" aria-hidden="true" tabindex="-1"></a>(Data file: house.selling.price in **smss** R package)</span>
<span id="cb56-192"><a href="#cb56-192" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb56-193"><a href="#cb56-193" aria-hidden="true" tabindex="-1"></a><span class="fu">### Part A</span></span>
<span id="cb56-194"><a href="#cb56-194" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb56-195"><a href="#cb56-195" aria-hidden="true" tabindex="-1"></a>Using the house.selling.price data, run and report regression results modeling y = selling price (in dollars) in terms of sizeof home (in square feet) and whether the home is new(1 = yes; 0 = no). In particular, for each variable; discuss statistical significance and interpret the meaning of the coefficient.</span>
<span id="cb56-196"><a href="#cb56-196" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb56-199"><a href="#cb56-199" aria-hidden="true" tabindex="-1"></a><span class="in">```{r}</span></span>
<span id="cb56-200"><a href="#cb56-200" aria-hidden="true" tabindex="-1"></a><span class="co"># Importing needed data</span></span>
<span id="cb56-201"><a href="#cb56-201" aria-hidden="true" tabindex="-1"></a><span class="fu">data</span>(house.selling.price)</span>
<span id="cb56-202"><a href="#cb56-202" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb56-203"><a href="#cb56-203" aria-hidden="true" tabindex="-1"></a><span class="co"># Creating model based on size and age status</span></span>
<span id="cb56-204"><a href="#cb56-204" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(<span class="fu">lm</span>(Price <span class="sc">~</span> Size <span class="sc">+</span> New, <span class="at">data=</span> house.selling.price))</span>
<span id="cb56-205"><a href="#cb56-205" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb56-206"><a href="#cb56-206" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb56-207"><a href="#cb56-207" aria-hidden="true" tabindex="-1"></a>Based on the size variable, the house price will increase by \~\$116.132 for each square foot increase in size. This finding is statistically significant.</span>
<span id="cb56-208"><a href="#cb56-208" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb56-209"><a href="#cb56-209" aria-hidden="true" tabindex="-1"></a>Based on the age of the house variable, a new house is projected to cost \~\$57,736.283 more than an old house. This finding is also statistically significant.\</span>
<span id="cb56-210"><a href="#cb56-210" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb56-211"><a href="#cb56-211" aria-hidden="true" tabindex="-1"></a><span class="fu">### Part B</span></span>
<span id="cb56-212"><a href="#cb56-212" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb56-213"><a href="#cb56-213" aria-hidden="true" tabindex="-1"></a>Report and interpret the prediction equation, and form separate equations relating selling price to size for new and for not new homes.</span>
<span id="cb56-214"><a href="#cb56-214" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb56-215"><a href="#cb56-215" aria-hidden="true" tabindex="-1"></a>Prediction equation:</span>
<span id="cb56-216"><a href="#cb56-216" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb56-217"><a href="#cb56-217" aria-hidden="true" tabindex="-1"></a>y = -40230.867 + 116.13<span class="sc">\*</span>x1 + 57736.283<span class="sc">\*</span>x2</span>
<span id="cb56-218"><a href="#cb56-218" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb56-219"><a href="#cb56-219" aria-hidden="true" tabindex="-1"></a>x1 = size</span>
<span id="cb56-220"><a href="#cb56-220" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb56-221"><a href="#cb56-221" aria-hidden="true" tabindex="-1"></a>x2 = age of house (old vs. new)</span>
<span id="cb56-222"><a href="#cb56-222" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb56-223"><a href="#cb56-223" aria-hidden="true" tabindex="-1"></a>Prediction equation for a new house:</span>
<span id="cb56-224"><a href="#cb56-224" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb56-225"><a href="#cb56-225" aria-hidden="true" tabindex="-1"></a>y = -40230.867 + 116.132<span class="sc">\*</span>x1 + 57736.283</span>
<span id="cb56-226"><a href="#cb56-226" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb56-227"><a href="#cb56-227" aria-hidden="true" tabindex="-1"></a>Prediction equation for an old house:</span>
<span id="cb56-228"><a href="#cb56-228" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb56-229"><a href="#cb56-229" aria-hidden="true" tabindex="-1"></a>y = -40230.867 + 116.132<span class="sc">\*</span>x1</span>
<span id="cb56-230"><a href="#cb56-230" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb56-231"><a href="#cb56-231" aria-hidden="true" tabindex="-1"></a><span class="fu">### Part C</span></span>
<span id="cb56-232"><a href="#cb56-232" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb56-233"><a href="#cb56-233" aria-hidden="true" tabindex="-1"></a>Find the predicted selling price for a home of 3000 square feet that is (i) new, (ii) not new.</span>
<span id="cb56-234"><a href="#cb56-234" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb56-237"><a href="#cb56-237" aria-hidden="true" tabindex="-1"></a><span class="in">```{r}</span></span>
<span id="cb56-238"><a href="#cb56-238" aria-hidden="true" tabindex="-1"></a><span class="co"># Using the prediction model to predict the cost of a new house</span></span>
<span id="cb56-239"><a href="#cb56-239" aria-hidden="true" tabindex="-1"></a><span class="sc">-</span><span class="fl">40230.867</span> <span class="sc">+</span> <span class="fl">116.132</span><span class="sc">*</span><span class="dv">3000</span> <span class="sc">+</span>  <span class="fl">57736.283</span></span>
<span id="cb56-240"><a href="#cb56-240" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb56-241"><a href="#cb56-241" aria-hidden="true" tabindex="-1"></a><span class="co"># Using the prediction model to predict the cost of an old house</span></span>
<span id="cb56-242"><a href="#cb56-242" aria-hidden="true" tabindex="-1"></a><span class="sc">-</span><span class="fl">40230.867</span> <span class="sc">+</span> <span class="fl">116.132</span><span class="sc">*</span><span class="dv">3000</span></span>
<span id="cb56-243"><a href="#cb56-243" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb56-244"><a href="#cb56-244" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb56-245"><a href="#cb56-245" aria-hidden="true" tabindex="-1"></a>Based on the prediction model, a new house of 3,000 square feet would cost \$365,901.40, while an old house of the same size would cost \$308,165.10.</span>
<span id="cb56-246"><a href="#cb56-246" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb56-247"><a href="#cb56-247" aria-hidden="true" tabindex="-1"></a><span class="fu">### Part D</span></span>
<span id="cb56-248"><a href="#cb56-248" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb56-249"><a href="#cb56-249" aria-hidden="true" tabindex="-1"></a>Fit another model, this time with an interaction term allowing interaction between size and new, and report the regression results</span>
<span id="cb56-250"><a href="#cb56-250" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb56-253"><a href="#cb56-253" aria-hidden="true" tabindex="-1"></a><span class="in">```{r}</span></span>
<span id="cb56-254"><a href="#cb56-254" aria-hidden="true" tabindex="-1"></a><span class="co"># Creating a model for an interaction between size and new</span></span>
<span id="cb56-255"><a href="#cb56-255" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(<span class="fu">lm</span>(Price <span class="sc">~</span> Size <span class="sc">+</span> New <span class="sc">+</span> Size<span class="sc">*</span>New, <span class="at">data=</span>house.selling.price))</span>
<span id="cb56-256"><a href="#cb56-256" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb56-257"><a href="#cb56-257" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb56-258"><a href="#cb56-258" aria-hidden="true" tabindex="-1"></a>Based on this model, the prediction equation would be y = -2227.808 + 104.438<span class="sc">\*</span>x1 + 61.916<span class="sc">\*</span>x2 -78527.502<span class="sc">\*</span>x3, where x1 is the size of the house in square feet, x2 is the size and house age interaction variable, and x3 is the house age variable (old vs new). Both size and the interaction between size and house age are statistically significant. However, the house age variable is no longer statistically significant.</span>
<span id="cb56-259"><a href="#cb56-259" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb56-260"><a href="#cb56-260" aria-hidden="true" tabindex="-1"></a><span class="fu">### Part E</span></span>
<span id="cb56-261"><a href="#cb56-261" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb56-262"><a href="#cb56-262" aria-hidden="true" tabindex="-1"></a>Report the lines relating the predicted selling price to the size for homes that are (i) new, (ii) not new.</span>
<span id="cb56-263"><a href="#cb56-263" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb56-264"><a href="#cb56-264" aria-hidden="true" tabindex="-1"></a>Prediction equation for a new house:</span>
<span id="cb56-265"><a href="#cb56-265" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb56-266"><a href="#cb56-266" aria-hidden="true" tabindex="-1"></a>y = -2227.808 + 166.354<span class="sc">\*</span>x1 - 78527.502</span>
<span id="cb56-267"><a href="#cb56-267" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb56-268"><a href="#cb56-268" aria-hidden="true" tabindex="-1"></a>Prediction equation for an old house:</span>
<span id="cb56-269"><a href="#cb56-269" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb56-270"><a href="#cb56-270" aria-hidden="true" tabindex="-1"></a>y = -2227.808 + 104.438<span class="sc">\*</span>x1</span>
<span id="cb56-271"><a href="#cb56-271" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb56-272"><a href="#cb56-272" aria-hidden="true" tabindex="-1"></a><span class="fu">### Part F</span></span>
<span id="cb56-273"><a href="#cb56-273" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb56-274"><a href="#cb56-274" aria-hidden="true" tabindex="-1"></a>Find the predicted selling price for a home of 3000 square feet that is (i) new, (ii) not new.</span>
<span id="cb56-275"><a href="#cb56-275" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb56-278"><a href="#cb56-278" aria-hidden="true" tabindex="-1"></a><span class="in">```{r}</span></span>
<span id="cb56-279"><a href="#cb56-279" aria-hidden="true" tabindex="-1"></a><span class="co"># Using the prediction model to predict the cost of a new house</span></span>
<span id="cb56-280"><a href="#cb56-280" aria-hidden="true" tabindex="-1"></a><span class="sc">-</span><span class="fl">2227.808</span> <span class="sc">+</span> <span class="fl">166.354</span><span class="sc">*</span><span class="dv">3000</span> <span class="sc">-</span> <span class="fl">78527.502</span></span>
<span id="cb56-281"><a href="#cb56-281" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb56-282"><a href="#cb56-282" aria-hidden="true" tabindex="-1"></a><span class="co"># Using the prediction model to predict the cost of an old house</span></span>
<span id="cb56-283"><a href="#cb56-283" aria-hidden="true" tabindex="-1"></a><span class="sc">-</span><span class="fl">2227.808</span> <span class="sc">+</span> <span class="fl">104.438</span><span class="sc">*</span><span class="dv">3000</span></span>
<span id="cb56-284"><a href="#cb56-284" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb56-285"><a href="#cb56-285" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb56-286"><a href="#cb56-286" aria-hidden="true" tabindex="-1"></a>Based on the new prediction model, a new house of 3,000 square feet would cost \$418,306.70, while an old house of the same size would cost \$311,086.20.</span>
<span id="cb56-287"><a href="#cb56-287" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb56-288"><a href="#cb56-288" aria-hidden="true" tabindex="-1"></a><span class="fu">### Part G</span></span>
<span id="cb56-289"><a href="#cb56-289" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb56-290"><a href="#cb56-290" aria-hidden="true" tabindex="-1"></a>Find the predicted selling price for a home of 1500 square feet that is (i) new, (ii) not new. Comparing to (F), explain how the difference in predicted selling prices changes as the size of home increases.</span>
<span id="cb56-291"><a href="#cb56-291" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb56-294"><a href="#cb56-294" aria-hidden="true" tabindex="-1"></a><span class="in">```{r}</span></span>
<span id="cb56-295"><a href="#cb56-295" aria-hidden="true" tabindex="-1"></a><span class="co"># Using the prediction model to predict the cost of a new house</span></span>
<span id="cb56-296"><a href="#cb56-296" aria-hidden="true" tabindex="-1"></a><span class="sc">-</span><span class="fl">2227.808</span> <span class="sc">+</span> <span class="fl">166.354</span><span class="sc">*</span><span class="dv">1500</span> <span class="sc">-</span> <span class="fl">78527.502</span></span>
<span id="cb56-297"><a href="#cb56-297" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb56-298"><a href="#cb56-298" aria-hidden="true" tabindex="-1"></a><span class="co"># Using the prediction model to predict the cost of an old house</span></span>
<span id="cb56-299"><a href="#cb56-299" aria-hidden="true" tabindex="-1"></a><span class="sc">-</span><span class="fl">2227.808</span> <span class="sc">+</span> <span class="fl">104.438</span><span class="sc">*</span><span class="dv">1500</span></span>
<span id="cb56-300"><a href="#cb56-300" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb56-301"><a href="#cb56-301" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb56-302"><a href="#cb56-302" aria-hidden="true" tabindex="-1"></a>Based on the new prediction model, a new house of 1,500 square feet would cost \$168,775.70, while an old house of the same size would cost \$154,429.20. This model demonstrates that small houses vary less in price, regardless of age, than larger houses, where new vs old houses makes much more of a difference.</span>
<span id="cb56-303"><a href="#cb56-303" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb56-304"><a href="#cb56-304" aria-hidden="true" tabindex="-1"></a><span class="fu">### Part H</span></span>
<span id="cb56-305"><a href="#cb56-305" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb56-306"><a href="#cb56-306" aria-hidden="true" tabindex="-1"></a>Do you think the model with interaction or the one without it represents the relationship of size and new to the outcome price? What makes you prefer one model over another?</span>
<span id="cb56-307"><a href="#cb56-307" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb56-310"><a href="#cb56-310" aria-hidden="true" tabindex="-1"></a><span class="in">```{r}</span></span>
<span id="cb56-311"><a href="#cb56-311" aria-hidden="true" tabindex="-1"></a><span class="co"># Calculating predicted house cost of a large new house with first model</span></span>
<span id="cb56-312"><a href="#cb56-312" aria-hidden="true" tabindex="-1"></a><span class="sc">-</span><span class="fl">40230.867</span> <span class="sc">+</span> <span class="fl">116.132</span><span class="sc">*</span><span class="dv">5000</span> <span class="sc">+</span>  <span class="fl">57736.283</span></span>
<span id="cb56-313"><a href="#cb56-313" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb56-314"><a href="#cb56-314" aria-hidden="true" tabindex="-1"></a><span class="co"># Calculating predicted house cost of a large old house with first model</span></span>
<span id="cb56-315"><a href="#cb56-315" aria-hidden="true" tabindex="-1"></a><span class="sc">-</span><span class="fl">40230.867</span> <span class="sc">+</span> <span class="fl">116.132</span><span class="sc">*</span><span class="dv">5000</span></span>
<span id="cb56-316"><a href="#cb56-316" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb56-317"><a href="#cb56-317" aria-hidden="true" tabindex="-1"></a><span class="co"># Calculating predicted house cost of a small new house with first model</span></span>
<span id="cb56-318"><a href="#cb56-318" aria-hidden="true" tabindex="-1"></a><span class="sc">-</span><span class="fl">40230.867</span> <span class="sc">+</span> <span class="fl">116.132</span><span class="sc">*</span><span class="dv">1000</span> <span class="sc">+</span>  <span class="fl">57736.283</span></span>
<span id="cb56-319"><a href="#cb56-319" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb56-320"><a href="#cb56-320" aria-hidden="true" tabindex="-1"></a><span class="co"># Calculating predicted house cost of a small old house with the first model</span></span>
<span id="cb56-321"><a href="#cb56-321" aria-hidden="true" tabindex="-1"></a><span class="sc">-</span><span class="fl">40230.867</span> <span class="sc">+</span> <span class="fl">116.132</span><span class="sc">*</span><span class="dv">1000</span></span>
<span id="cb56-322"><a href="#cb56-322" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb56-323"><a href="#cb56-323" aria-hidden="true" tabindex="-1"></a><span class="co"># Calculating predicted house cost of a large new house with second model</span></span>
<span id="cb56-324"><a href="#cb56-324" aria-hidden="true" tabindex="-1"></a><span class="sc">-</span><span class="fl">2227.808</span> <span class="sc">+</span> <span class="fl">166.354</span><span class="sc">*</span><span class="dv">5000</span> <span class="sc">-</span> <span class="fl">78527.502</span></span>
<span id="cb56-325"><a href="#cb56-325" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb56-326"><a href="#cb56-326" aria-hidden="true" tabindex="-1"></a><span class="co"># Calculating predicted house cost of a large old house with second model</span></span>
<span id="cb56-327"><a href="#cb56-327" aria-hidden="true" tabindex="-1"></a><span class="sc">-</span><span class="fl">2227.808</span> <span class="sc">+</span> <span class="fl">104.438</span><span class="sc">*</span><span class="dv">5000</span></span>
<span id="cb56-328"><a href="#cb56-328" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb56-329"><a href="#cb56-329" aria-hidden="true" tabindex="-1"></a><span class="co"># Calculating predicted house cost of a small new house with second model</span></span>
<span id="cb56-330"><a href="#cb56-330" aria-hidden="true" tabindex="-1"></a><span class="sc">-</span><span class="fl">2227.808</span> <span class="sc">+</span> <span class="fl">166.354</span><span class="sc">*</span><span class="dv">1000</span> <span class="sc">-</span> <span class="fl">78527.502</span></span>
<span id="cb56-331"><a href="#cb56-331" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb56-332"><a href="#cb56-332" aria-hidden="true" tabindex="-1"></a><span class="co"># Calculating predicted house cost of a small old house with the second model</span></span>
<span id="cb56-333"><a href="#cb56-333" aria-hidden="true" tabindex="-1"></a><span class="sc">-</span><span class="fl">2227.808</span> <span class="sc">+</span> <span class="fl">104.438</span><span class="sc">*</span><span class="dv">1000</span></span>
<span id="cb56-334"><a href="#cb56-334" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb56-335"><a href="#cb56-335" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb56-336"><a href="#cb56-336" aria-hidden="true" tabindex="-1"></a>I think that it depends. For large houses, I would use the second model, because it shows the difference the price a new house vs an old house more greatly. However, for smaller houses, the second model is inaccurate, since it predicts that a new small house would be cheaper than an old small house. I think the first model would be a better predictor for small houses.</span>
</code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div></div></div></div></div>
</div> <!-- /content -->



</body></html>