<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.2.280">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">

<meta name="author" content="Ethan Campbell">
<meta name="dcterms.date" content="2022-11-14">

<title>Homework 4</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1.6em;
  vertical-align: middle;
}
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
    color: #aaaaaa;
  }
pre.numberSource { margin-left: 3em; border-left: 1px solid #aaaaaa;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
code span.al { color: #ff0000; font-weight: bold; } /* Alert */
code span.an { color: #60a0b0; font-weight: bold; font-style: italic; } /* Annotation */
code span.at { color: #7d9029; } /* Attribute */
code span.bn { color: #40a070; } /* BaseN */
code span.bu { color: #008000; } /* BuiltIn */
code span.cf { color: #007020; font-weight: bold; } /* ControlFlow */
code span.ch { color: #4070a0; } /* Char */
code span.cn { color: #880000; } /* Constant */
code span.co { color: #60a0b0; font-style: italic; } /* Comment */
code span.cv { color: #60a0b0; font-weight: bold; font-style: italic; } /* CommentVar */
code span.do { color: #ba2121; font-style: italic; } /* Documentation */
code span.dt { color: #902000; } /* DataType */
code span.dv { color: #40a070; } /* DecVal */
code span.er { color: #ff0000; font-weight: bold; } /* Error */
code span.ex { } /* Extension */
code span.fl { color: #40a070; } /* Float */
code span.fu { color: #06287e; } /* Function */
code span.im { color: #008000; font-weight: bold; } /* Import */
code span.in { color: #60a0b0; font-weight: bold; font-style: italic; } /* Information */
code span.kw { color: #007020; font-weight: bold; } /* Keyword */
code span.op { color: #666666; } /* Operator */
code span.ot { color: #007020; } /* Other */
code span.pp { color: #bc7a00; } /* Preprocessor */
code span.sc { color: #4070a0; } /* SpecialChar */
code span.ss { color: #bb6688; } /* SpecialString */
code span.st { color: #4070a0; } /* String */
code span.va { color: #19177c; } /* Variable */
code span.vs { color: #4070a0; } /* VerbatimString */
code span.wa { color: #60a0b0; font-weight: bold; font-style: italic; } /* Warning */
</style>


<script src="../site_libs/quarto-nav/quarto-nav.js"></script>
<script src="../site_libs/quarto-nav/headroom.min.js"></script>
<script src="../site_libs/clipboard/clipboard.min.js"></script>
<script src="../site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="../site_libs/quarto-search/fuse.min.js"></script>
<script src="../site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="../">
<link href="../images/DACSS_Round_Network.png" rel="icon" type="image/png">
<script src="../site_libs/quarto-html/quarto.js"></script>
<script src="../site_libs/quarto-html/popper.min.js"></script>
<script src="../site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="../site_libs/quarto-html/anchor.min.js"></script>
<link href="../site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="../site_libs/quarto-html/quarto-syntax-highlighting.css" rel="stylesheet" class="quarto-color-scheme" id="quarto-text-highlighting-styles">
<link href="../site_libs/quarto-html/quarto-syntax-highlighting-dark.css" rel="prefetch" class="quarto-color-scheme quarto-color-alternate" id="quarto-text-highlighting-styles">
<script src="../site_libs/bootstrap/bootstrap.min.js"></script>
<link href="../site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="../site_libs/bootstrap/bootstrap.min.css" rel="stylesheet" class="quarto-color-scheme" id="quarto-bootstrap" data-mode="light">
<link href="../site_libs/bootstrap/bootstrap-dark.min.css" rel="prefetch" class="quarto-color-scheme quarto-color-alternate" id="quarto-bootstrap" data-mode="dark">
<script id="quarto-search-options" type="application/json">{
  "location": "navbar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "end",
  "type": "overlay",
  "limit": 20,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit"
  }
}</script>


<meta name="twitter:title" content="Homework 4">
<meta name="twitter:description" content="">
<meta name="twitter:creator" content="@UMassDACSS">
<meta name="twitter:site" content="@UMassDACSS">
<meta name="twitter:card" content="summary">
</head>

<body class="nav-fixed">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
    <nav class="navbar navbar-expand-lg navbar-dark ">
      <div class="navbar-container container-fluid">
      <div class="navbar-brand-container">
    <a href="../index.html" class="navbar-brand navbar-brand-logo">
    <img src="../images/UMass White Wordmark Horiz.png" alt="" class="navbar-logo">
    </a>
  </div>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse" aria-controls="navbarCollapse" aria-expanded="false" aria-label="Toggle navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
  <span class="navbar-toggler-icon"></span>
</button>
          <div class="collapse navbar-collapse" id="navbarCollapse">
            <ul class="navbar-nav navbar-nav-scroll ms-auto">
  <li class="nav-item">
    <a class="nav-link" href="https://dacss.github.io/603_Fall_2022/">
 <span class="menu-text">Fall 2022 Posts</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="../about.html">
 <span class="menu-text">Contributors</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="https://umass.edu/sbs/dacss">
 <span class="menu-text">DACSS</span></a>
  </li>  
  <li class="nav-item compact">
    <a class="nav-link" href="https://github.com/DACSS/603_Fall_2022"><i class="bi bi-github" role="img" aria-label="GitHub">
</i> 
 <span class="menu-text"></span></a>
  </li>  
</ul>
              <div class="quarto-toggle-container">
                  <a href="" class="quarto-color-scheme-toggle nav-link" onclick="window.quartoToggleColorScheme(); return false;" title="Toggle dark mode"><i class="bi"></i></a>
              </div>
              <div id="quarto-search" class="" title="Search"></div>
          </div> <!-- /navcollapse -->
      </div> <!-- /container-fluid -->
    </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article page-navbar">
<!-- sidebar -->
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">On this page</h2>
   
  <ul>
  <li><a href="#section" id="toc-section" class="nav-link active" data-scroll-target="#section"></a></li>
  <li><a href="#question-1" id="toc-question-1" class="nav-link" data-scroll-target="#question-1"><strong>Question 1</strong></a></li>
  <li><a href="#question-2" id="toc-question-2" class="nav-link" data-scroll-target="#question-2"><strong>Question 2</strong></a></li>
  <li><a href="#question-3" id="toc-question-3" class="nav-link" data-scroll-target="#question-3"><strong>Question 3</strong></a></li>
  </ul>
</nav>
    </div>
<!-- main -->
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<div class="quarto-title-block"><div><h1 class="title">Homework 4</h1><button type="button" class="btn code-tools-button dropdown-toggle" id="quarto-code-tools-menu" data-bs-toggle="dropdown" aria-expanded="false"><i class="bi"></i> Code</button><ul class="dropdown-menu dropdown-menu-end" aria-labelelledby="quarto-code-tools-menu"><li><a id="quarto-show-all-code" class="dropdown-item" href="javascript:void(0)" role="button">Show All Code</a></li><li><a id="quarto-hide-all-code" class="dropdown-item" href="javascript:void(0)" role="button">Hide All Code</a></li><li><hr class="dropdown-divider"></li><li><a id="quarto-view-source" class="dropdown-item" href="javascript:void(0)" role="button">View Source</a></li></ul></div></div>
  <div class="quarto-categories">
    <div class="quarto-category">hw4</div>
  </div>
  </div>



<div class="quarto-title-meta">

    <div>
    <div class="quarto-title-meta-heading">Author</div>
    <div class="quarto-title-meta-contents">
             <p>Ethan Campbell </p>
          </div>
  </div>
    
    <div>
    <div class="quarto-title-meta-heading">Published</div>
    <div class="quarto-title-meta-contents">
      <p class="date">November 14, 2022</p>
    </div>
  </div>
  
    
  </div>
  

</header>

<section id="section" class="level2">
<h2 class="anchored" data-anchor-id="section"></h2>
</section>
<section id="question-1" class="level1">
<h1><strong>Question 1</strong></h1>
<p><br>
</p>
<div class="cell">
<details>
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb1"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(alr4)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stderr">
<pre><code>Warning: package 'alr4' was built under R version 4.1.3</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Loading required package: car</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning: package 'car' was built under R version 4.1.3</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Loading required package: carData</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Loading required package: effects</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning: package 'effects' was built under R version 4.1.3</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>lattice theme set by effectsTheme()
See ?effectsTheme for details.</code></pre>
</div>
<details>
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb9"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb9-1"><a href="#cb9-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(smss)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stderr">
<pre><code>Warning: package 'smss' was built under R version 4.1.3</code></pre>
</div>
<details>
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb11"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb11-1"><a href="#cb11-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(tidyverse)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stderr">
<pre><code>Warning: package 'tidyverse' was built under R version 4.1.3</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>-- Attaching packages --------------------------------------- tidyverse 1.3.2 --</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>v ggplot2 3.3.6     v purrr   0.3.4
v tibble  3.1.8     v dplyr   1.0.9
v tidyr   1.2.0     v stringr 1.4.1
v readr   2.1.2     v forcats 0.5.2</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning: package 'ggplot2' was built under R version 4.1.3</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning: package 'tibble' was built under R version 4.1.3</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning: package 'tidyr' was built under R version 4.1.3</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning: package 'readr' was built under R version 4.1.3</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning: package 'dplyr' was built under R version 4.1.3</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning: package 'stringr' was built under R version 4.1.3</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning: package 'forcats' was built under R version 4.1.3</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>-- Conflicts ------------------------------------------ tidyverse_conflicts() --
x dplyr::filter() masks stats::filter()
x dplyr::lag()    masks stats::lag()
x dplyr::recode() masks car::recode()
x purrr::some()   masks car::some()</code></pre>
</div>
</div>
<p>For recent data in Jacksonville, Florida, on y = selling price of home (in dollars), x1 = size of home (in square feet), and x2 = lot size (in square feet), the prediction equation is</p>
<p>y^ = ???10,536 + 53.8x1 + 2.84x2.</p>
<p><br>
</p>
<ol type="1">
<li>A particular home of 1240 square feet on a lot of 18,000 square feet sold for $145,000. Find the predicted selling price and the residual, and interpret.</li>
</ol>
<div class="cell">
<details>
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb23"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb23-1"><a href="#cb23-1" aria-hidden="true" tabindex="-1"></a>Actual_price <span class="ot">&lt;-</span> <span class="dv">145000</span></span>
<span id="cb23-2"><a href="#cb23-2" aria-hidden="true" tabindex="-1"></a>Predicted <span class="ot">&lt;-</span> <span class="sc">-</span><span class="dv">10536</span> <span class="sc">+</span>(<span class="fl">53.8</span><span class="sc">*</span><span class="dv">1240</span>) <span class="sc">+</span> (<span class="fl">2.84</span><span class="sc">*</span><span class="dv">18000</span>)</span>
<span id="cb23-3"><a href="#cb23-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb23-4"><a href="#cb23-4" aria-hidden="true" tabindex="-1"></a>residual <span class="ot">&lt;-</span> Actual_price <span class="sc">-</span> Predicted</span>
<span id="cb23-5"><a href="#cb23-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb23-6"><a href="#cb23-6" aria-hidden="true" tabindex="-1"></a>Question_3 <span class="ot">&lt;-</span> <span class="fl">53.8</span><span class="sc">/</span><span class="fl">2.84</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
</div>
<p>Answer:</p>
<p>The predicted equation is above and with the given information for x1 and x2 and Y we are able to calculate by inputting the information. The residual is the difference between the actual and predicted here we test for the predicted which is with the information inputted and we test for what the cost should be. Afterward, we subtract that from the actual price and notice a difference of -37704. This means that our equation is underpredicting the value of homes and this could be due to either the lack of data or the lack of certain variables that could sway the outcome.</p>
<ol start="2" type="1">
<li>For fixed lot size, how much is the house selling price predicted to increase for each square-foot increase in home size? Why?</li>
</ol>
<p>Answer: If lot size is fixed then we can ignore x2 and focus on x1. x1 is in charge of home size per square foot and here it is at 53.8 dollar increase per square foot. When the prediction was run this was the coefficient thus we can use this to predict other values based on the same information.<br>
</p>
<ol start="3" type="1">
<li>According to this prediction equation, for fixed home size, how much would lot size need to increase to have the same impact as a one-square-foot increase in home size?</li>
</ol>
<p>Answer: For fixed home size to have the same impact as one square foot increase in home size we would need to increase by 18.94. This is calculated by dividing x1 by x2 and this shows the difference in each rate so for them to have the same impact we would need to multiply it by the above number.<br>
</p>
</section>
<section id="question-2" class="level1">
<h1><strong>Question 2</strong></h1>
<p><br>
</p>
<p>(Data file: salary in <strong>alr4</strong> R package). The data file concerns salary and other characteristics of all faculty in a small Midwestern college collected in the early 1980s for presentation in legal proceedings for which discrimination against women in salary was at issue. All persons in the data hold tenured or tenure track positions; temporary faculty are not included. The variables include degree, a factor with levels PhD and MS; rank, a factor with levels Asst, Assoc, and Prof; sex, a factor with levels Male and Female; Year, years in current rank; ysdeg, years since highest degree, and salary, academic year salary in dollars.</p>
<p><br>
</p>
<ol type="1">
<li>Test the hypothesis that the mean salary for men and women is the same, without regard to any other variable but sex. Explain your findings.</li>
</ol>
<div class="callout-tip callout callout-style-default callout-captioned">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-caption-container flex-fill">
H<sub>0A</sub>
</div>
</div>
<div class="callout-body-container callout-body">
<p>Mean salary for men and women is the same.</p>
</div>
</div>
<div class="callout-tip callout callout-style-default callout-captioned">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-caption-container flex-fill">
H<sub>1A</sub>
</div>
</div>
<div class="callout-body-container callout-body">
<p>Mean salary for men and women is not the same.</p>
</div>
</div>
<div class="cell">
<details>
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb24"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb24-1"><a href="#cb24-1" aria-hidden="true" tabindex="-1"></a>regression <span class="ot">&lt;-</span> <span class="fu">lm</span>(salary <span class="sc">~</span> sex, <span class="at">data =</span> salary)</span>
<span id="cb24-2"><a href="#cb24-2" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(regression)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = salary ~ sex, data = salary)

Residuals:
    Min      1Q  Median      3Q     Max 
-8602.8 -4296.6  -100.8  3513.1 16687.9 

Coefficients:
            Estimate Std. Error t value Pr(&gt;|t|)    
(Intercept)    24697        938  26.330   &lt;2e-16 ***
sexFemale      -3340       1808  -1.847   0.0706 .  
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 5782 on 50 degrees of freedom
Multiple R-squared:  0.0639,    Adjusted R-squared:  0.04518 
F-statistic: 3.413 on 1 and 50 DF,  p-value: 0.0706</code></pre>
</div>
</div>
<p>Answer: Based on this alone we do not have enough information to reject the null hypothesis as the p-value for salary by sex is .0706. This is not statistically significant and does not give me any evidence to reject the null. However, when looking into the coefficient based on sex we notice it is -3340 lower than its sex counterpart. Based on this information we can assume that there is something going on and that women may be getting paid less. More data and more testing would be needed to prove this and more variables would prove essential to proving this hypothesis.</p>
<ol start="2" type="1">
<li>Run a multiple linear regression with salary as the outcome variable and everything else as predictors, including sex. Assuming no interactions between sex and the other predictors, obtain a 95% confidence interval for the difference in salary between males and females.</li>
</ol>
<div class="cell">
<details>
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb26"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb26-1"><a href="#cb26-1" aria-hidden="true" tabindex="-1"></a>regression2 <span class="ot">&lt;-</span> <span class="fu">lm</span>(salary <span class="sc">~</span> ., <span class="at">data =</span> salary)</span>
<span id="cb26-2"><a href="#cb26-2" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(regression2)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = salary ~ ., data = salary)

Residuals:
    Min      1Q  Median      3Q     Max 
-4045.2 -1094.7  -361.5   813.2  9193.1 

Coefficients:
            Estimate Std. Error t value Pr(&gt;|t|)    
(Intercept) 15746.05     800.18  19.678  &lt; 2e-16 ***
degreePhD    1388.61    1018.75   1.363    0.180    
rankAssoc    5292.36    1145.40   4.621 3.22e-05 ***
rankProf    11118.76    1351.77   8.225 1.62e-10 ***
sexFemale    1166.37     925.57   1.260    0.214    
year          476.31      94.91   5.018 8.65e-06 ***
ysdeg        -124.57      77.49  -1.608    0.115    
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 2398 on 45 degrees of freedom
Multiple R-squared:  0.855, Adjusted R-squared:  0.8357 
F-statistic: 44.24 on 6 and 45 DF,  p-value: &lt; 2.2e-16</code></pre>
</div>
</div>
<p>When looking at the data here we notice that p value has grown more becoming harder to reject the null but we also notice a significant shift in the coefficient as it has grown by over 4000 and is now 1166.37. I am assuming this could be related to the other variables shifting this information.</p>
<ol start="3" type="1">
<li>Interpret your finding for each predictor variable; discuss (a) statistical significance, (b) interpretation of the coefficient/slope in relation to the outcome variable and other variables</li>
</ol>
<p><strong>degreePHd</strong> * p-value = .180 * interpretation = causes an increase in salary of 1388.61 this would make sense as having a higher education is known to lead to an increase in salary. However, it is not significant here which hints to why the number is not as high this could be due to them favoring years of service more than education.</p>
<p><strong>rankAssoc</strong> * p-value = 3.22e-05 * interpretation = This value is very significant and we are able to reject any null and say yes this value has an impact. This values causes salary to increase by 5292.36 which shows the importance of this value.</p>
<p><strong>rankProf</strong> * p-value = 1.62e-10 * interpretation = This value is significant and we can reject any null hypothesis and say yes it has an impact. This one has the largest impact out of all the variables it causes salary to increase by 11118.73 which is a major increase as it it greater than all the other variables combined.</p>
<p><strong>sexFemale</strong> * p-value = .214 * interpretation = This value is not significant and we would fail to reject the null hypothesis. This one has a coefficient of 1166.37 which is how much it would increase salary. This is saying that females have a higher salary by that amount if this was significant and included all other variables.</p>
<p><strong>year</strong> * p-value = 8.65e-06 *n interpretation = This is a significant value that would allow us to reject the null hypothesis. This means the more you work there the more your salary increases and this is saying that it would increase your salary by 476.31 each year you work there.</p>
<p><strong>ysdeg</strong>* p-value = .115 * interpretation = This value is not significant and would fail to reject the null. This value would causes a decrease in salary by 124.57.</p>
<ol start="4" type="1">
<li>Change the baseline category for the rank variable. Interpret the coefficients related to rank again.</li>
</ol>
<div class="cell">
<details>
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb28"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb28-1"><a href="#cb28-1" aria-hidden="true" tabindex="-1"></a>salary<span class="sc">$</span>rank <span class="ot">&lt;-</span> <span class="fu">relevel</span>(salary<span class="sc">$</span>rank, <span class="at">ref =</span><span class="st">'Assoc'</span>)</span>
<span id="cb28-2"><a href="#cb28-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb28-3"><a href="#cb28-3" aria-hidden="true" tabindex="-1"></a>regression3 <span class="ot">&lt;-</span> <span class="fu">lm</span>(salary <span class="sc">~</span> ., <span class="at">data =</span> salary)</span>
<span id="cb28-4"><a href="#cb28-4" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(regression3)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = salary ~ ., data = salary)

Residuals:
    Min      1Q  Median      3Q     Max 
-4045.2 -1094.7  -361.5   813.2  9193.1 

Coefficients:
            Estimate Std. Error t value Pr(&gt;|t|)    
(Intercept) 21038.41    1109.12  18.969  &lt; 2e-16 ***
degreePhD    1388.61    1018.75   1.363    0.180    
rankAsst    -5292.36    1145.40  -4.621 3.22e-05 ***
rankProf     5826.40    1012.93   5.752 7.28e-07 ***
sexFemale    1166.37     925.57   1.260    0.214    
year          476.31      94.91   5.018 8.65e-06 ***
ysdeg        -124.57      77.49  -1.608    0.115    
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 2398 on 45 degrees of freedom
Multiple R-squared:  0.855, Adjusted R-squared:  0.8357 
F-statistic: 44.24 on 6 and 45 DF,  p-value: &lt; 2.2e-16</code></pre>
</div>
</div>
<p>When changing the base value for rank we notice a large shift in the value. Being an asst. reduces the salary by 5292.36. This is noticed in the coefficients and comparing it to the professor’s salary. This has a p value of 3.22e-05 meaning we could reject the null and say it has an impact.</p>
<ol start="5" type="1">
<li>Finkelstein (1980), in a discussion of the use of regression in discrimination cases, wrote, “[a] variable may reflect a position or status bestowed by the employer, in which case if there is discrimination in the award of the position or status, the variable may be ‘tainted.’” Thus, for example, if discrimination is at work in the promotion of faculty to higher ranks, using rank to adjust salaries before comparing the sexes may not be acceptable to the courts.</li>
</ol>
<p><br>
</p>
<p>Exclude the variable rank, refit, and summarize how your findings changed, if they did.</p>
<div class="cell">
<details>
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb30"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb30-1"><a href="#cb30-1" aria-hidden="true" tabindex="-1"></a>regression4 <span class="ot">&lt;-</span> <span class="fu">lm</span>(salary <span class="sc">~</span> sex <span class="sc">+</span> year <span class="sc">+</span> degree <span class="sc">+</span> ysdeg, <span class="at">data =</span> salary)</span>
<span id="cb30-2"><a href="#cb30-2" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(regression4)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = salary ~ sex + year + degree + ysdeg, data = salary)

Residuals:
    Min      1Q  Median      3Q     Max 
-8146.9 -2186.9  -491.5  2279.1 11186.6 

Coefficients:
            Estimate Std. Error t value Pr(&gt;|t|)    
(Intercept) 17183.57    1147.94  14.969  &lt; 2e-16 ***
sexFemale   -1286.54    1313.09  -0.980 0.332209    
year          351.97     142.48   2.470 0.017185 *  
degreePhD   -3299.35    1302.52  -2.533 0.014704 *  
ysdeg         339.40      80.62   4.210 0.000114 ***
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 3744 on 47 degrees of freedom
Multiple R-squared:  0.6312,    Adjusted R-squared:  0.5998 
F-statistic: 20.11 on 4 and 47 DF,  p-value: 1.048e-09</code></pre>
</div>
</div>
<p>When analyzing the changes after removing rank from the equation notice major changes to the p-values of all variables and to their coefficients. We notice that sex female is back to being negative and the p value has increased to .332209. Year has decreased to 351.97 and is significant a 95% only. degreePHd is now hugely negative which was once positive. This is now -3299.35 and is significant at 95%. ysdeg is the only variable that has seen some growth and it is now 339.40 with a p-value of 0.000114. Very interesting to see how much impact the year had on all other variables in this equation.<br>
</p>
<ol start="6" type="1">
<li>Everyone in this dataset was hired the year they earned their highest degree. It is also known that a new Dean was appointed 15 years ago, and everyone in the dataset who earned their highest degree 15 years ago or less than that has been hired by the new Dean. Some people have argued that the new Dean has been making offers that are a lot more generous to newly hired faculty than the previous one and that this might explain some of the variations in Salary.</li>
</ol>
<div class="cell">
<details>
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb32"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb32-1"><a href="#cb32-1" aria-hidden="true" tabindex="-1"></a><span class="co"># we need to make a dummy variable for the dean</span></span>
<span id="cb32-2"><a href="#cb32-2" aria-hidden="true" tabindex="-1"></a>salary <span class="ot">&lt;-</span> salary <span class="sc">%&gt;%</span></span>
<span id="cb32-3"><a href="#cb32-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">new_dean =</span> <span class="fu">case_when</span>(</span>
<span id="cb32-4"><a href="#cb32-4" aria-hidden="true" tabindex="-1"></a>    ysdeg <span class="sc">&lt;=</span> <span class="dv">15</span> <span class="sc">~</span> <span class="dv">1</span>,</span>
<span id="cb32-5"><a href="#cb32-5" aria-hidden="true" tabindex="-1"></a>    ysdeg <span class="sc">&gt;</span> <span class="dv">15</span> <span class="sc">~</span> <span class="dv">0</span></span>
<span id="cb32-6"><a href="#cb32-6" aria-hidden="true" tabindex="-1"></a>  ))</span>
<span id="cb32-7"><a href="#cb32-7" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb32-8"><a href="#cb32-8" aria-hidden="true" tabindex="-1"></a><span class="co"># now that we have that we can run the regression using an interaction term here to look into the impact of the dean change</span></span>
<span id="cb32-9"><a href="#cb32-9" aria-hidden="true" tabindex="-1"></a>dean_regresion <span class="ot">&lt;-</span> <span class="fu">lm</span>(salary <span class="sc">~</span> year <span class="sc">+</span> degree <span class="sc">+</span> sex <span class="sc">+</span> rank <span class="sc">+</span> new_dean <span class="sc">+</span> new_dean<span class="sc">*</span>year, <span class="at">data =</span> salary)</span>
<span id="cb32-10"><a href="#cb32-10" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb32-11"><a href="#cb32-11" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(dean_regresion)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = salary ~ year + degree + sex + rank + new_dean + 
    new_dean * year, data = salary)

Residuals:
    Min      1Q  Median      3Q     Max 
-3309.8 -1102.5  -265.2   539.2  9339.4 

Coefficients:
              Estimate Std. Error t value Pr(&gt;|t|)    
(Intercept)   17427.11    1538.08  11.330 1.24e-14 ***
year            495.72      97.42   5.088 7.20e-06 ***
degreePhD      1161.63     859.23   1.352   0.1833    
sexFemale      1115.96     862.06   1.295   0.2022    
rankAsst      -5416.07    1079.72  -5.016 9.14e-06 ***
rankProf       6196.73    1029.38   6.020 3.16e-07 ***
new_dean       3789.08    1867.72   2.029   0.0486 *  
year:new_dean  -195.43     183.99  -1.062   0.2940    
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 2358 on 44 degrees of freedom
Multiple R-squared:  0.8629,    Adjusted R-squared:  0.8411 
F-statistic: 39.58 on 7 and 44 DF,  p-value: &lt; 2.2e-16</code></pre>
</div>
</div>
<p>To avoid some problems with similar information we made an interaction term so we can compare when the new dean came effectively. Now when reading this we notice that at the 95% confidence level the new_Dean which means that being hired by the new dean does result in some higher wages. The new dean variable by itself had an increase of 3789.08 however when we take into consideration the interaction term it brings that number down by 195.43.</p>
<p><br>
</p>
<p>Create a new variable that would allow you to test this hypothesis and run another multiple regression model to test this. Select variables carefully to make sure there is no multicollinearity. Explain why multicollinearity would be a concern in this case and how you avoided it. Do you find support for the hypothesis that the people hired by the new Dean are making higher than those that were not?</p>
<p><br>
</p>
</section>
<section id="question-3" class="level1">
<h1><strong>Question 3</strong></h1>
<p><br>
</p>
<p>(Data file: house.selling.price in <strong>smss</strong> R package)</p>
<p><br>
</p>
<ol type="1">
<li>Using the house.selling.price data, run and report regression results modeling y = selling price (in dollars) in terms of size of the home (in square feet) and whether the home is new(1 = yes; 0 = no). In particular, for each variable; discuss the statistical significance and interpret the meaning of the coefficient.</li>
</ol>
<div class="cell">
<details>
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb34"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb34-1"><a href="#cb34-1" aria-hidden="true" tabindex="-1"></a><span class="fu">data</span>(<span class="st">"house.selling.price"</span>)</span>
<span id="cb34-2"><a href="#cb34-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb34-3"><a href="#cb34-3" aria-hidden="true" tabindex="-1"></a>house <span class="ot">&lt;-</span> house.selling.price</span>
<span id="cb34-4"><a href="#cb34-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb34-5"><a href="#cb34-5" aria-hidden="true" tabindex="-1"></a>Reg1 <span class="ot">&lt;-</span> <span class="fu">lm</span>(Price <span class="sc">~</span> Size <span class="sc">+</span> New, <span class="at">data =</span> house)</span>
<span id="cb34-6"><a href="#cb34-6" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(Reg1)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = Price ~ Size + New, data = house)

Residuals:
    Min      1Q  Median      3Q     Max 
-205102  -34374   -5778   18929  163866 

Coefficients:
              Estimate Std. Error t value Pr(&gt;|t|)    
(Intercept) -40230.867  14696.140  -2.738  0.00737 ** 
Size           116.132      8.795  13.204  &lt; 2e-16 ***
New          57736.283  18653.041   3.095  0.00257 ** 
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 53880 on 97 degrees of freedom
Multiple R-squared:  0.7226,    Adjusted R-squared:  0.7169 
F-statistic: 126.3 on 2 and 97 DF,  p-value: &lt; 2.2e-16</code></pre>
</div>
</div>
<p>Here there are two variables to look at first is Size, this coefficient is at 116.132 meaning for every sqft that is added the price goes up by this. The other one is new which increases the price of the home by 57736.283 if the home is new. Size is very significant at &lt; 2e-16 while new is significant at 0.00257 both of these variables are significant to predicting house cost. With these two variables alone we see an R squared of .726 which is really good.<br>
</p>
<ol start="2" type="1">
<li>Report and interpret the prediction equation, and form separate equations relating selling price to size for new and for not new homes.</li>
</ol>
<p>Prediction equation is: Y = -40230.867 +116.132x1 +17505.41x2 This is where x1 = size and x2 = new when it is yes</p>
<p>Prediction equation is: Y = -40230.867 +116.132x1 +-40230.867x2</p>
<p>This is where x1 = size and x2 = new when it is no<br>
</p>
<ol start="3" type="1">
<li>Find the predicted selling price for a home of 3000 square feet that is (i) new, (ii) not new.</li>
</ol>
<!-- -->
<ol type="i">
<li>new &lt;- (116.132*3000) + 17505.41</li>
<li>old &lt;- (116.132*3000) -40320.867</li>
</ol>
<p>New is valued at 365,901.41 while old is valued at 308,075.133<br>
</p>
<ol start="4" type="1">
<li>Fit another model, this time with an interaction term allowing interaction between size and new, and report the regression results</li>
</ol>
<div class="cell">
<details>
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb36"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb36-1"><a href="#cb36-1" aria-hidden="true" tabindex="-1"></a>Reg2 <span class="ot">&lt;-</span> <span class="fu">lm</span>(Price <span class="sc">~</span> Size <span class="sc">+</span> New <span class="sc">+</span> New<span class="sc">*</span>Size, <span class="at">data =</span> house)</span>
<span id="cb36-2"><a href="#cb36-2" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(Reg2)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = Price ~ Size + New + New * Size, data = house)

Residuals:
    Min      1Q  Median      3Q     Max 
-175748  -28979   -6260   14693  192519 

Coefficients:
              Estimate Std. Error t value Pr(&gt;|t|)    
(Intercept) -22227.808  15521.110  -1.432  0.15536    
Size           104.438      9.424  11.082  &lt; 2e-16 ***
New         -78527.502  51007.642  -1.540  0.12697    
Size:New        61.916     21.686   2.855  0.00527 ** 
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 52000 on 96 degrees of freedom
Multiple R-squared:  0.7443,    Adjusted R-squared:  0.7363 
F-statistic: 93.15 on 3 and 96 DF,  p-value: &lt; 2.2e-16</code></pre>
</div>
</div>
<p>the regression results show that with size and the new the cost per sqft is 166.354 which is 61.916 higher compared to the not new version. This is the focus of this regression is to evaluate the interaction term</p>
<p><br>
</p>
<ol start="5" type="1">
<li>Report the lines relating the predicted selling price to the size for homes that are (i) new, (ii) not new.</li>
</ol>
<div class="cell">
<details>
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb38"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb38-1"><a href="#cb38-1" aria-hidden="true" tabindex="-1"></a><span class="co">#mod &lt;- -22227.81 + 104.44x1 -78527.50x2 + 61.92(x1*z)</span></span>
<span id="cb38-2"><a href="#cb38-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb38-3"><a href="#cb38-3" aria-hidden="true" tabindex="-1"></a><span class="co">#old1 &lt;- -22227.81 + (104.44*x1)</span></span>
<span id="cb38-4"><a href="#cb38-4" aria-hidden="true" tabindex="-1"></a><span class="co">#new1 &lt;- -100755.31 + (166.36x1)</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
</div>
<p><br>
</p>
<ol start="6" type="1">
<li>Find the predicted selling price for a home of 3000 square feet that is (i) new, (ii) not new.</li>
</ol>
<div class="cell">
<details>
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb39"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb39-1"><a href="#cb39-1" aria-hidden="true" tabindex="-1"></a>old1 <span class="ot">&lt;-</span> <span class="sc">-</span><span class="fl">22227.81</span> <span class="sc">+</span> (<span class="fl">104.44</span><span class="sc">*</span><span class="dv">3000</span>)</span>
<span id="cb39-2"><a href="#cb39-2" aria-hidden="true" tabindex="-1"></a>new1 <span class="ot">&lt;-</span> <span class="sc">-</span><span class="fl">100755.31</span> <span class="sc">+</span> (<span class="fl">166.36</span><span class="sc">*</span><span class="dv">3000</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
</div>
<p>For a new home with this interaction term, we see a price of 398324.69 and for an old we see 291092.19 which is a huge difference.</p>
<p><br>
</p>
<ol start="7" type="1">
<li>Find the predicted selling price for a home of 1500 square feet that is (i) new, (ii) not new. Comparing to (F), explain how the difference in predicted selling prices changes as the size of the home increases.</li>
</ol>
<div class="cell">
<details>
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb40"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb40-1"><a href="#cb40-1" aria-hidden="true" tabindex="-1"></a>old2 <span class="ot">&lt;-</span> <span class="sc">-</span><span class="fl">22227.81</span> <span class="sc">+</span> (<span class="fl">104.44</span><span class="sc">*</span><span class="dv">1500</span>)</span>
<span id="cb40-2"><a href="#cb40-2" aria-hidden="true" tabindex="-1"></a>new2 <span class="ot">&lt;-</span> <span class="sc">-</span><span class="fl">100755.31</span> <span class="sc">+</span> (<span class="fl">166.36</span><span class="sc">*</span><span class="dv">1500</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
</div>
<p>Here we see the price of a new home is 148,784.69 at 1500 sqft while an old one is 134,432.19. The difference between these values is much smaller than it was last time and that falls to the slope. There is a difference of 61.916 between the new and old so the larger the home the larger the difference will be between the two.<br>
</p>
<ol start="8" type="1">
<li>Do you think the model with interaction or the one without it represents the relationship of size and new to the outcome price? What makes you prefer one model over another?</li>
</ol>
<p>When analyzing these two regressions I would take the second one with the interaction term as it accounts for the new variable in each sqft compared to the other one that had one static number which does not seem realistic. Another point to note is the difference in the r squared between the two regressions as the one with the interaction term is higher by ~ 2%.</p>
<p><br>
</p>


<!-- -->

</section>

</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const disableStylesheet = (stylesheets) => {
    for (let i=0; i < stylesheets.length; i++) {
      const stylesheet = stylesheets[i];
      stylesheet.rel = 'prefetch';
    }
  }
  const enableStylesheet = (stylesheets) => {
    for (let i=0; i < stylesheets.length; i++) {
      const stylesheet = stylesheets[i];
      stylesheet.rel = 'stylesheet';
    }
  }
  const manageTransitions = (selector, allowTransitions) => {
    const els = window.document.querySelectorAll(selector);
    for (let i=0; i < els.length; i++) {
      const el = els[i];
      if (allowTransitions) {
        el.classList.remove('notransition');
      } else {
        el.classList.add('notransition');
      }
    }
  }
  const toggleColorMode = (alternate) => {
    // Switch the stylesheets
    const alternateStylesheets = window.document.querySelectorAll('link.quarto-color-scheme.quarto-color-alternate');
    manageTransitions('#quarto-margin-sidebar .nav-link', false);
    if (alternate) {
      enableStylesheet(alternateStylesheets);
      for (const sheetNode of alternateStylesheets) {
        if (sheetNode.id === "quarto-bootstrap") {
          toggleBodyColorMode(sheetNode);
        }
      }
    } else {
      disableStylesheet(alternateStylesheets);
      toggleBodyColorPrimary();
    }
    manageTransitions('#quarto-margin-sidebar .nav-link', true);
    // Switch the toggles
    const toggles = window.document.querySelectorAll('.quarto-color-scheme-toggle');
    for (let i=0; i < toggles.length; i++) {
      const toggle = toggles[i];
      if (toggle) {
        if (alternate) {
          toggle.classList.add("alternate");     
        } else {
          toggle.classList.remove("alternate");
        }
      }
    }
    // Hack to workaround the fact that safari doesn't
    // properly recolor the scrollbar when toggling (#1455)
    if (navigator.userAgent.indexOf('Safari') > 0 && navigator.userAgent.indexOf('Chrome') == -1) {
      manageTransitions("body", false);
      window.scrollTo(0, 1);
      setTimeout(() => {
        window.scrollTo(0, 0);
        manageTransitions("body", true);
      }, 40);  
    }
  }
  const isFileUrl = () => { 
    return window.location.protocol === 'file:';
  }
  const hasAlternateSentinel = () => {  
    let styleSentinel = getColorSchemeSentinel();
    if (styleSentinel !== null) {
      return styleSentinel === "alternate";
    } else {
      return false;
    }
  }
  const setStyleSentinel = (alternate) => {
    const value = alternate ? "alternate" : "default";
    if (!isFileUrl()) {
      window.localStorage.setItem("quarto-color-scheme", value);
    } else {
      localAlternateSentinel = value;
    }
  }
  const getColorSchemeSentinel = () => {
    if (!isFileUrl()) {
      const storageValue = window.localStorage.getItem("quarto-color-scheme");
      return storageValue != null ? storageValue : localAlternateSentinel;
    } else {
      return localAlternateSentinel;
    }
  }
  let localAlternateSentinel = 'default';
  // Dark / light mode switch
  window.quartoToggleColorScheme = () => {
    // Read the current dark / light value 
    let toAlternate = !hasAlternateSentinel();
    toggleColorMode(toAlternate);
    setStyleSentinel(toAlternate);
  };
  // Ensure there is a toggle, if there isn't float one in the top right
  if (window.document.querySelector('.quarto-color-scheme-toggle') === null) {
    const a = window.document.createElement('a');
    a.classList.add('top-right');
    a.classList.add('quarto-color-scheme-toggle');
    a.href = "";
    a.onclick = function() { try { window.quartoToggleColorScheme(); } catch {} return false; };
    const i = window.document.createElement("i");
    i.classList.add('bi');
    a.appendChild(i);
    window.document.body.appendChild(a);
  }
  // Switch to dark mode if need be
  if (hasAlternateSentinel()) {
    toggleColorMode(true);
  } else {
    toggleColorMode(false);
  }
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const clipboard = new window.ClipboardJS('.code-copy-button', {
    target: function(trigger) {
      return trigger.previousElementSibling;
    }
  });
  clipboard.on('success', function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copied!");
    let tooltip;
    if (window.bootstrap) {
      button.setAttribute("data-bs-toggle", "tooltip");
      button.setAttribute("data-bs-placement", "left");
      button.setAttribute("data-bs-title", "Copied!");
      tooltip = new bootstrap.Tooltip(button, 
        { trigger: "manual", 
          customClass: "code-copy-button-tooltip",
          offset: [0, -8]});
      tooltip.show();    
    }
    setTimeout(function() {
      if (tooltip) {
        tooltip.hide();
        button.removeAttribute("data-bs-title");
        button.removeAttribute("data-bs-toggle");
        button.removeAttribute("data-bs-placement");
      }
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  });
  const viewSource = window.document.getElementById('quarto-view-source') ||
                     window.document.getElementById('quarto-code-tools-source');
  if (viewSource) {
    const sourceUrl = viewSource.getAttribute("data-quarto-source-url");
    viewSource.addEventListener("click", function(e) {
      if (sourceUrl) {
        // rstudio viewer pane
        if (/\bcapabilities=\b/.test(window.location)) {
          window.open(sourceUrl);
        } else {
          window.location.href = sourceUrl;
        }
      } else {
        const modal = new bootstrap.Modal(document.getElementById('quarto-embedded-source-code-modal'));
        modal.show();
      }
      return false;
    });
  }
  function toggleCodeHandler(show) {
    return function(e) {
      const detailsSrc = window.document.querySelectorAll(".cell > details > .sourceCode");
      for (let i=0; i<detailsSrc.length; i++) {
        const details = detailsSrc[i].parentElement;
        if (show) {
          details.open = true;
        } else {
          details.removeAttribute("open");
        }
      }
      const cellCodeDivs = window.document.querySelectorAll(".cell > .sourceCode");
      const fromCls = show ? "hidden" : "unhidden";
      const toCls = show ? "unhidden" : "hidden";
      for (let i=0; i<cellCodeDivs.length; i++) {
        const codeDiv = cellCodeDivs[i];
        if (codeDiv.classList.contains(fromCls)) {
          codeDiv.classList.remove(fromCls);
          codeDiv.classList.add(toCls);
        } 
      }
      return false;
    }
  }
  const hideAllCode = window.document.getElementById("quarto-hide-all-code");
  if (hideAllCode) {
    hideAllCode.addEventListener("click", toggleCodeHandler(false));
  }
  const showAllCode = window.document.getElementById("quarto-show-all-code");
  if (showAllCode) {
    showAllCode.addEventListener("click", toggleCodeHandler(true));
  }
  function tippyHover(el, contentFn) {
    const config = {
      allowHTML: true,
      content: contentFn,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start'
    };
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      return note.innerHTML;
    });
  }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
});
</script>
<script src="https://giscus.app/client.js" data-repo="DACSS/603_Fall_2022" data-repo-id="R_kgDOH568kA" data-category="Announcements" data-category-id="" data-mapping="title" data-reactions-enabled="1" data-emit-metadata="0" data-input-position="top" data-theme="light" data-lang="en" crossorigin="anonymous" async="">
</script><div class="modal fade" id="quarto-embedded-source-code-modal" tabindex="-1" aria-labelledby="quarto-embedded-source-code-modal-label" aria-hidden="true"><div class="modal-dialog modal-dialog-scrollable"><div class="modal-content"><div class="modal-header"><h5 class="modal-title" id="quarto-embedded-source-code-modal-label">Source Code</h5><button class="btn-close" data-bs-dismiss="modal"></button></div><div class="modal-body"><div class="">
<div class="sourceCode" id="cb41" data-shortcodes="false"><pre class="sourceCode markdown code-with-copy"><code class="sourceCode markdown"><span id="cb41-1"><a href="#cb41-1" aria-hidden="true" tabindex="-1"></a><span class="co">---</span></span>
<span id="cb41-2"><a href="#cb41-2" aria-hidden="true" tabindex="-1"></a><span class="an">title:</span><span class="co"> "Homework 4"</span></span>
<span id="cb41-3"><a href="#cb41-3" aria-hidden="true" tabindex="-1"></a><span class="an">author:</span><span class="co"> "Ethan Campbell"</span></span>
<span id="cb41-4"><a href="#cb41-4" aria-hidden="true" tabindex="-1"></a><span class="an">desription:</span><span class="co"> "Homework 4"</span></span>
<span id="cb41-5"><a href="#cb41-5" aria-hidden="true" tabindex="-1"></a><span class="an">date:</span><span class="co"> "11/14/2022"</span></span>
<span id="cb41-6"><a href="#cb41-6" aria-hidden="true" tabindex="-1"></a><span class="an">format:</span></span>
<span id="cb41-7"><a href="#cb41-7" aria-hidden="true" tabindex="-1"></a><span class="co">  html:</span></span>
<span id="cb41-8"><a href="#cb41-8" aria-hidden="true" tabindex="-1"></a><span class="co">    toc: true</span></span>
<span id="cb41-9"><a href="#cb41-9" aria-hidden="true" tabindex="-1"></a><span class="co">    code-fold: true</span></span>
<span id="cb41-10"><a href="#cb41-10" aria-hidden="true" tabindex="-1"></a><span class="co">    code-copy: true</span></span>
<span id="cb41-11"><a href="#cb41-11" aria-hidden="true" tabindex="-1"></a><span class="co">    code-tools: true</span></span>
<span id="cb41-12"><a href="#cb41-12" aria-hidden="true" tabindex="-1"></a><span class="an">categories:</span></span>
<span id="cb41-13"><a href="#cb41-13" aria-hidden="true" tabindex="-1"></a><span class="co">  - hw4</span></span>
<span id="cb41-14"><a href="#cb41-14" aria-hidden="true" tabindex="-1"></a><span class="co">---</span></span>
<span id="cb41-15"><a href="#cb41-15" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb41-16"><a href="#cb41-16" aria-hidden="true" tabindex="-1"></a><span class="fu">## </span></span>
<span id="cb41-17"><a href="#cb41-17" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb41-18"><a href="#cb41-18" aria-hidden="true" tabindex="-1"></a><span class="fu"># **Question 1**</span></span>
<span id="cb41-19"><a href="#cb41-19" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb41-20"><a href="#cb41-20" aria-hidden="true" tabindex="-1"></a>\</span>
<span id="cb41-21"><a href="#cb41-21" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb41-24"><a href="#cb41-24" aria-hidden="true" tabindex="-1"></a><span class="in">```{r}</span></span>
<span id="cb41-25"><a href="#cb41-25" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(alr4)</span>
<span id="cb41-26"><a href="#cb41-26" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(smss)</span>
<span id="cb41-27"><a href="#cb41-27" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(tidyverse)</span>
<span id="cb41-28"><a href="#cb41-28" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb41-29"><a href="#cb41-29" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb41-30"><a href="#cb41-30" aria-hidden="true" tabindex="-1"></a>For recent data in Jacksonville, Florida, on y = selling price of home (in dollars), x1 = size of home (in square feet), and x2 = lot size (in square feet), the prediction equation is </span>
<span id="cb41-31"><a href="#cb41-31" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb41-32"><a href="#cb41-32" aria-hidden="true" tabindex="-1"></a>y^ = ???10,536 + 53.8x1 + 2.84x2.</span>
<span id="cb41-33"><a href="#cb41-33" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb41-34"><a href="#cb41-34" aria-hidden="true" tabindex="-1"></a>\</span>
<span id="cb41-35"><a href="#cb41-35" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb41-36"><a href="#cb41-36" aria-hidden="true" tabindex="-1"></a><span class="ss">1.  </span>A particular home of 1240 square feet on a lot of 18,000 square feet sold for \$145,000. Find the predicted selling price and the residual, and interpret.</span>
<span id="cb41-37"><a href="#cb41-37" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb41-40"><a href="#cb41-40" aria-hidden="true" tabindex="-1"></a><span class="in">```{r}</span></span>
<span id="cb41-41"><a href="#cb41-41" aria-hidden="true" tabindex="-1"></a>Actual_price <span class="ot">&lt;-</span> <span class="dv">145000</span></span>
<span id="cb41-42"><a href="#cb41-42" aria-hidden="true" tabindex="-1"></a>Predicted <span class="ot">&lt;-</span> <span class="sc">-</span><span class="dv">10536</span> <span class="sc">+</span>(<span class="fl">53.8</span><span class="sc">*</span><span class="dv">1240</span>) <span class="sc">+</span> (<span class="fl">2.84</span><span class="sc">*</span><span class="dv">18000</span>)</span>
<span id="cb41-43"><a href="#cb41-43" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb41-44"><a href="#cb41-44" aria-hidden="true" tabindex="-1"></a>residual <span class="ot">&lt;-</span> Actual_price <span class="sc">-</span> Predicted</span>
<span id="cb41-45"><a href="#cb41-45" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb41-46"><a href="#cb41-46" aria-hidden="true" tabindex="-1"></a>Question_3 <span class="ot">&lt;-</span> <span class="fl">53.8</span><span class="sc">/</span><span class="fl">2.84</span></span>
<span id="cb41-47"><a href="#cb41-47" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb41-48"><a href="#cb41-48" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb41-49"><a href="#cb41-49" aria-hidden="true" tabindex="-1"></a>Answer:</span>
<span id="cb41-50"><a href="#cb41-50" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb41-51"><a href="#cb41-51" aria-hidden="true" tabindex="-1"></a>The predicted equation is above and with the given information for x1 and x2 and Y we are able to calculate by inputting the information. The residual is the difference between the actual and predicted here we test for the predicted which is with the information inputted and we test for what the cost should be. Afterward, we subtract that from the actual price and notice a difference of -37704. This means that our equation is underpredicting the value of homes and this could be due to either the lack of data or the lack of certain variables that could sway the outcome.</span>
<span id="cb41-52"><a href="#cb41-52" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb41-53"><a href="#cb41-53" aria-hidden="true" tabindex="-1"></a><span class="ss">2.  </span>For fixed lot size, how much is the house selling price predicted to increase for each square-foot increase in home size? Why?</span>
<span id="cb41-54"><a href="#cb41-54" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb41-55"><a href="#cb41-55" aria-hidden="true" tabindex="-1"></a>Answer: If lot size is fixed then we can ignore x2 and focus on x1. x1 is in charge of home size per square foot and here it is at 53.8 dollar increase per square foot. When the prediction was run this was the coefficient thus we can use this to predict other values based on the same information.\</span>
<span id="cb41-56"><a href="#cb41-56" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb41-57"><a href="#cb41-57" aria-hidden="true" tabindex="-1"></a><span class="ss">3.  </span>According to this prediction equation, for fixed home size, how much would lot size need to increase to have the same impact as a one-square-foot increase in home size?</span>
<span id="cb41-58"><a href="#cb41-58" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb41-59"><a href="#cb41-59" aria-hidden="true" tabindex="-1"></a>Answer: For fixed home size to have the same impact as one square foot increase in home size we would need to increase by 18.94. This is calculated by dividing x1 by x2 and this shows the difference in each rate so for them to have the same impact we would need to multiply it by the above number.\</span>
<span id="cb41-60"><a href="#cb41-60" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb41-61"><a href="#cb41-61" aria-hidden="true" tabindex="-1"></a><span class="fu"># **Question 2**</span></span>
<span id="cb41-62"><a href="#cb41-62" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb41-63"><a href="#cb41-63" aria-hidden="true" tabindex="-1"></a>\</span>
<span id="cb41-64"><a href="#cb41-64" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb41-65"><a href="#cb41-65" aria-hidden="true" tabindex="-1"></a>(Data file: salary in **alr4** R package). The data file concerns salary and other characteristics of all faculty in a small Midwestern college collected in the early 1980s for presentation in legal proceedings for which discrimination against women in salary was at issue. All persons in the data hold tenured or tenure track positions; temporary faculty are not included. The variables include degree, a factor with levels PhD and MS; rank, a factor with levels Asst, Assoc, and Prof; sex, a factor with levels Male and Female; Year, years in current rank; ysdeg, years since highest degree, and salary, academic year salary in dollars.</span>
<span id="cb41-66"><a href="#cb41-66" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb41-67"><a href="#cb41-67" aria-hidden="true" tabindex="-1"></a>\</span>
<span id="cb41-68"><a href="#cb41-68" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb41-69"><a href="#cb41-69" aria-hidden="true" tabindex="-1"></a><span class="ss">1.  </span>Test the hypothesis that the mean salary for men and women is the same, without regard to any other variable but sex. Explain your findings.</span>
<span id="cb41-70"><a href="#cb41-70" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb41-71"><a href="#cb41-71" aria-hidden="true" tabindex="-1"></a>::: callout-tip</span>
<span id="cb41-72"><a href="#cb41-72" aria-hidden="true" tabindex="-1"></a><span class="fu">## H~0A~</span></span>
<span id="cb41-73"><a href="#cb41-73" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb41-74"><a href="#cb41-74" aria-hidden="true" tabindex="-1"></a>Mean salary for men and women is the same.</span>
<span id="cb41-75"><a href="#cb41-75" aria-hidden="true" tabindex="-1"></a>:::</span>
<span id="cb41-76"><a href="#cb41-76" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb41-77"><a href="#cb41-77" aria-hidden="true" tabindex="-1"></a>::: callout-tip</span>
<span id="cb41-78"><a href="#cb41-78" aria-hidden="true" tabindex="-1"></a><span class="fu">## H~1A~</span></span>
<span id="cb41-79"><a href="#cb41-79" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb41-80"><a href="#cb41-80" aria-hidden="true" tabindex="-1"></a>Mean salary for men and women is not the same.</span>
<span id="cb41-81"><a href="#cb41-81" aria-hidden="true" tabindex="-1"></a>:::</span>
<span id="cb41-82"><a href="#cb41-82" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb41-85"><a href="#cb41-85" aria-hidden="true" tabindex="-1"></a><span class="in">```{r}</span></span>
<span id="cb41-86"><a href="#cb41-86" aria-hidden="true" tabindex="-1"></a>regression <span class="ot">&lt;-</span> <span class="fu">lm</span>(salary <span class="sc">~</span> sex, <span class="at">data =</span> salary)</span>
<span id="cb41-87"><a href="#cb41-87" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(regression)</span>
<span id="cb41-88"><a href="#cb41-88" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb41-89"><a href="#cb41-89" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb41-90"><a href="#cb41-90" aria-hidden="true" tabindex="-1"></a>Answer: Based on this alone we do not have enough information to reject the null hypothesis as the p-value for salary by sex is .0706. This is not statistically significant and does not give me any evidence to reject the null. However, when looking into the coefficient based on sex we notice it is -3340 lower than its sex counterpart. Based on this information we can assume that there is something going on and that women may be getting paid less. More data and more testing would be needed to prove this and more variables would prove essential to proving this hypothesis.</span>
<span id="cb41-91"><a href="#cb41-91" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb41-92"><a href="#cb41-92" aria-hidden="true" tabindex="-1"></a><span class="ss">2.  </span>Run a multiple linear regression with salary as the outcome variable and everything else as predictors, including sex. Assuming no interactions between sex and the other predictors, obtain a 95% confidence interval for the difference in salary between males and females.</span>
<span id="cb41-93"><a href="#cb41-93" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb41-96"><a href="#cb41-96" aria-hidden="true" tabindex="-1"></a><span class="in">```{r}</span></span>
<span id="cb41-97"><a href="#cb41-97" aria-hidden="true" tabindex="-1"></a>regression2 <span class="ot">&lt;-</span> <span class="fu">lm</span>(salary <span class="sc">~</span> ., <span class="at">data =</span> salary)</span>
<span id="cb41-98"><a href="#cb41-98" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(regression2)</span>
<span id="cb41-99"><a href="#cb41-99" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb41-100"><a href="#cb41-100" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb41-101"><a href="#cb41-101" aria-hidden="true" tabindex="-1"></a>When looking at the data here we notice that p value has grown more becoming harder to reject the null but we also notice a significant shift in the coefficient as it has grown by over 4000 and is now 1166.37. I am assuming this could be related to the other variables shifting this information.</span>
<span id="cb41-102"><a href="#cb41-102" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb41-103"><a href="#cb41-103" aria-hidden="true" tabindex="-1"></a><span class="ss">3.  </span>Interpret your finding for each predictor variable; discuss (a) statistical significance, (b) interpretation of the coefficient/slope in relation to the outcome variable and other variables</span>
<span id="cb41-104"><a href="#cb41-104" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb41-105"><a href="#cb41-105" aria-hidden="true" tabindex="-1"></a>**degreePHd** <span class="sc">\*</span> p-value = .180 <span class="sc">\*</span> interpretation = causes an increase in salary of 1388.61 this would make sense as having a higher education is known to lead to an increase in salary. However, it is not significant here which hints to why the number is not as high this could be due to them favoring years of service more than education. </span>
<span id="cb41-106"><a href="#cb41-106" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb41-107"><a href="#cb41-107" aria-hidden="true" tabindex="-1"></a>**rankAssoc** <span class="sc">\*</span> p-value = 3.22e-05 <span class="sc">\*</span> interpretation = This value is very significant and we are able to reject any null and say yes this value has an impact. This values causes salary to increase by 5292.36 which shows the importance of this value. </span>
<span id="cb41-108"><a href="#cb41-108" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb41-109"><a href="#cb41-109" aria-hidden="true" tabindex="-1"></a>**rankProf** <span class="sc">\*</span> p-value = 1.62e-10 <span class="sc">\*</span> interpretation = This value is significant and we can reject any null hypothesis and say yes it has an impact. This one has the largest impact out of all the variables it causes salary to increase by 11118.73 which is a major increase as it it greater than all the other variables combined. </span>
<span id="cb41-110"><a href="#cb41-110" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb41-111"><a href="#cb41-111" aria-hidden="true" tabindex="-1"></a>**sexFemale** <span class="sc">\*</span> p-value = .214 <span class="sc">\*</span> interpretation = This value is not significant and we would fail to reject the null hypothesis. This one has a coefficient of 1166.37 which is how much it would increase salary. This is saying that females have a higher salary by that amount if this was significant and included all other variables.</span>
<span id="cb41-112"><a href="#cb41-112" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb41-113"><a href="#cb41-113" aria-hidden="true" tabindex="-1"></a>**year** <span class="sc">\*</span> p-value = 8.65e-06 *n interpretation = This is a significant value that would allow us to reject the null hypothesis. This means the more you work there the more your salary increases and this is saying that it would increase your salary by 476.31 each year you work there. </span>
<span id="cb41-114"><a href="#cb41-114" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb41-115"><a href="#cb41-115" aria-hidden="true" tabindex="-1"></a>**ysdeg*** p-value = .115 <span class="sc">\*</span> interpretation = This value is not significant and would fail to reject the null. This value would causes a decrease in salary by 124.57.</span>
<span id="cb41-116"><a href="#cb41-116" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb41-117"><a href="#cb41-117" aria-hidden="true" tabindex="-1"></a><span class="ss">4.  </span>Change the baseline category for the rank variable. Interpret the coefficients related to rank again.</span>
<span id="cb41-118"><a href="#cb41-118" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb41-121"><a href="#cb41-121" aria-hidden="true" tabindex="-1"></a><span class="in">```{r}</span></span>
<span id="cb41-122"><a href="#cb41-122" aria-hidden="true" tabindex="-1"></a>salary<span class="sc">$</span>rank <span class="ot">&lt;-</span> <span class="fu">relevel</span>(salary<span class="sc">$</span>rank, <span class="at">ref =</span><span class="st">'Assoc'</span>)</span>
<span id="cb41-123"><a href="#cb41-123" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb41-124"><a href="#cb41-124" aria-hidden="true" tabindex="-1"></a>regression3 <span class="ot">&lt;-</span> <span class="fu">lm</span>(salary <span class="sc">~</span> ., <span class="at">data =</span> salary)</span>
<span id="cb41-125"><a href="#cb41-125" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(regression3)</span>
<span id="cb41-126"><a href="#cb41-126" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb41-127"><a href="#cb41-127" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb41-128"><a href="#cb41-128" aria-hidden="true" tabindex="-1"></a>When changing the base value for rank we notice a large shift in the value. Being an asst. reduces the salary by 5292.36. This is noticed in the coefficients and comparing it to the professor's salary. This has a p value of 3.22e-05 meaning we could reject the null and say it has an impact.</span>
<span id="cb41-129"><a href="#cb41-129" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb41-130"><a href="#cb41-130" aria-hidden="true" tabindex="-1"></a><span class="ss">5.  </span>Finkelstein (1980), in a discussion of the use of regression in discrimination cases, wrote, "<span class="sc">\[</span>a<span class="sc">\]</span> variable may reflect a position or status bestowed by the employer, in which case if there is discrimination in the award of the position or status, the variable may be 'tainted.'" Thus, for example, if discrimination is at work in the promotion of faculty to higher ranks, using rank to adjust salaries before comparing the sexes may not be acceptable to the courts. </span>
<span id="cb41-131"><a href="#cb41-131" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb41-132"><a href="#cb41-132" aria-hidden="true" tabindex="-1"></a>\</span>
<span id="cb41-133"><a href="#cb41-133" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb41-134"><a href="#cb41-134" aria-hidden="true" tabindex="-1"></a>Exclude the variable rank, refit, and summarize how your findings changed, if they did.</span>
<span id="cb41-135"><a href="#cb41-135" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb41-138"><a href="#cb41-138" aria-hidden="true" tabindex="-1"></a><span class="in">```{r}</span></span>
<span id="cb41-139"><a href="#cb41-139" aria-hidden="true" tabindex="-1"></a>regression4 <span class="ot">&lt;-</span> <span class="fu">lm</span>(salary <span class="sc">~</span> sex <span class="sc">+</span> year <span class="sc">+</span> degree <span class="sc">+</span> ysdeg, <span class="at">data =</span> salary)</span>
<span id="cb41-140"><a href="#cb41-140" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(regression4)</span>
<span id="cb41-141"><a href="#cb41-141" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb41-142"><a href="#cb41-142" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb41-143"><a href="#cb41-143" aria-hidden="true" tabindex="-1"></a>When analyzing the changes after removing rank from the equation notice major changes to the p-values of all variables and to their coefficients. We notice that sex female is back to being negative and the p value has increased to .332209. Year has decreased to 351.97 and is significant a 95% only. degreePHd is now hugely negative which was once positive. This is now -3299.35 and is significant at 95%. ysdeg is the only variable that has seen some growth and it is now 339.40 with a p-value of 0.000114. Very interesting to see how much impact the year had on all other variables in this equation.\</span>
<span id="cb41-144"><a href="#cb41-144" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb41-145"><a href="#cb41-145" aria-hidden="true" tabindex="-1"></a><span class="ss">6.  </span>Everyone in this dataset was hired the year they earned their highest degree. It is also known that a new Dean was appointed 15 years ago, and everyone in the dataset who earned their highest degree 15 years ago or less than that has been hired by the new Dean. Some people have argued that the new Dean has been making offers that are a lot more generous to newly hired faculty than the previous one and that this might explain some of the variations in Salary.</span>
<span id="cb41-146"><a href="#cb41-146" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb41-149"><a href="#cb41-149" aria-hidden="true" tabindex="-1"></a><span class="in">```{r}</span></span>
<span id="cb41-150"><a href="#cb41-150" aria-hidden="true" tabindex="-1"></a><span class="co"># we need to make a dummy variable for the dean</span></span>
<span id="cb41-151"><a href="#cb41-151" aria-hidden="true" tabindex="-1"></a>salary <span class="ot">&lt;-</span> salary <span class="sc">%&gt;%</span></span>
<span id="cb41-152"><a href="#cb41-152" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">new_dean =</span> <span class="fu">case_when</span>(</span>
<span id="cb41-153"><a href="#cb41-153" aria-hidden="true" tabindex="-1"></a>    ysdeg <span class="sc">&lt;=</span> <span class="dv">15</span> <span class="sc">~</span> <span class="dv">1</span>,</span>
<span id="cb41-154"><a href="#cb41-154" aria-hidden="true" tabindex="-1"></a>    ysdeg <span class="sc">&gt;</span> <span class="dv">15</span> <span class="sc">~</span> <span class="dv">0</span></span>
<span id="cb41-155"><a href="#cb41-155" aria-hidden="true" tabindex="-1"></a>  ))</span>
<span id="cb41-156"><a href="#cb41-156" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb41-157"><a href="#cb41-157" aria-hidden="true" tabindex="-1"></a><span class="co"># now that we have that we can run the regression using an interaction term here to look into the impact of the dean change</span></span>
<span id="cb41-158"><a href="#cb41-158" aria-hidden="true" tabindex="-1"></a>dean_regresion <span class="ot">&lt;-</span> <span class="fu">lm</span>(salary <span class="sc">~</span> year <span class="sc">+</span> degree <span class="sc">+</span> sex <span class="sc">+</span> rank <span class="sc">+</span> new_dean <span class="sc">+</span> new_dean<span class="sc">*</span>year, <span class="at">data =</span> salary)</span>
<span id="cb41-159"><a href="#cb41-159" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb41-160"><a href="#cb41-160" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(dean_regresion)</span>
<span id="cb41-161"><a href="#cb41-161" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb41-162"><a href="#cb41-162" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb41-163"><a href="#cb41-163" aria-hidden="true" tabindex="-1"></a>To avoid some problems with similar information we made an interaction term so we can compare when the new dean came effectively. Now when reading this we notice that at the 95% confidence level the new_Dean which means that being hired by the new dean does result in some higher wages. The new dean variable by itself had an increase of 3789.08 however when we take into consideration the interaction term it brings that number down by 195.43.</span>
<span id="cb41-164"><a href="#cb41-164" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb41-165"><a href="#cb41-165" aria-hidden="true" tabindex="-1"></a>\</span>
<span id="cb41-166"><a href="#cb41-166" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb41-167"><a href="#cb41-167" aria-hidden="true" tabindex="-1"></a>Create a new variable that would allow you to test this hypothesis and run another multiple regression model to test this. Select variables carefully to make sure there is no multicollinearity. Explain why multicollinearity would be a concern in this case and how you avoided it. Do you find support for the hypothesis that the people hired by the new Dean are making higher than those that were not?</span>
<span id="cb41-168"><a href="#cb41-168" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb41-169"><a href="#cb41-169" aria-hidden="true" tabindex="-1"></a>\</span>
<span id="cb41-170"><a href="#cb41-170" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb41-171"><a href="#cb41-171" aria-hidden="true" tabindex="-1"></a><span class="fu"># **Question 3**</span></span>
<span id="cb41-172"><a href="#cb41-172" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb41-173"><a href="#cb41-173" aria-hidden="true" tabindex="-1"></a>\</span>
<span id="cb41-174"><a href="#cb41-174" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb41-175"><a href="#cb41-175" aria-hidden="true" tabindex="-1"></a>(Data file: house.selling.price in **smss** R package) </span>
<span id="cb41-176"><a href="#cb41-176" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb41-177"><a href="#cb41-177" aria-hidden="true" tabindex="-1"></a>\</span>
<span id="cb41-178"><a href="#cb41-178" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb41-179"><a href="#cb41-179" aria-hidden="true" tabindex="-1"></a><span class="ss">1.  </span>Using the house.selling.price data, run and report regression results modeling y = selling price (in dollars) in terms of size of the home (in square feet) and whether the home is new(1 = yes; 0 = no). In particular, for each variable; discuss the statistical significance and interpret the meaning of the coefficient.</span>
<span id="cb41-180"><a href="#cb41-180" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb41-183"><a href="#cb41-183" aria-hidden="true" tabindex="-1"></a><span class="in">```{r}</span></span>
<span id="cb41-184"><a href="#cb41-184" aria-hidden="true" tabindex="-1"></a><span class="fu">data</span>(<span class="st">"house.selling.price"</span>)</span>
<span id="cb41-185"><a href="#cb41-185" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb41-186"><a href="#cb41-186" aria-hidden="true" tabindex="-1"></a>house <span class="ot">&lt;-</span> house.selling.price</span>
<span id="cb41-187"><a href="#cb41-187" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb41-188"><a href="#cb41-188" aria-hidden="true" tabindex="-1"></a>Reg1 <span class="ot">&lt;-</span> <span class="fu">lm</span>(Price <span class="sc">~</span> Size <span class="sc">+</span> New, <span class="at">data =</span> house)</span>
<span id="cb41-189"><a href="#cb41-189" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(Reg1)</span>
<span id="cb41-190"><a href="#cb41-190" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb41-191"><a href="#cb41-191" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb41-192"><a href="#cb41-192" aria-hidden="true" tabindex="-1"></a>Here there are two variables to look at first is Size, this coefficient is at 116.132 meaning for every sqft that is added the price goes up by this. The other one is new which increases the price of the home by 57736.283 if the home is new. Size is very significant at <span class="sc">\&lt;</span> 2e-16 while new is significant at 0.00257 both of these variables are significant to predicting house cost. With these two variables alone we see an R squared of .726 which is really good.\</span>
<span id="cb41-193"><a href="#cb41-193" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb41-194"><a href="#cb41-194" aria-hidden="true" tabindex="-1"></a><span class="ss">2.  </span>Report and interpret the prediction equation, and form separate equations relating selling price to size for new and for not new homes.</span>
<span id="cb41-195"><a href="#cb41-195" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb41-196"><a href="#cb41-196" aria-hidden="true" tabindex="-1"></a>Prediction equation is: Y = -40230.867 +116.132x1 +17505.41x2 This is where x1 = size and x2 = new when it is yes</span>
<span id="cb41-197"><a href="#cb41-197" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb41-198"><a href="#cb41-198" aria-hidden="true" tabindex="-1"></a>Prediction equation is: Y = -40230.867 +116.132x1 +-40230.867x2</span>
<span id="cb41-199"><a href="#cb41-199" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb41-200"><a href="#cb41-200" aria-hidden="true" tabindex="-1"></a>This is where x1 = size and x2 = new when it is no\</span>
<span id="cb41-201"><a href="#cb41-201" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb41-202"><a href="#cb41-202" aria-hidden="true" tabindex="-1"></a><span class="ss">3.  </span>Find the predicted selling price for a home of 3000 square feet that is (i) new, (ii) not new.</span>
<span id="cb41-203"><a href="#cb41-203" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb41-204"><a href="#cb41-204" aria-hidden="true" tabindex="-1"></a><span class="in">```{=html}</span></span>
<span id="cb41-205"><a href="#cb41-205" aria-hidden="true" tabindex="-1"></a><span class="in">&lt;!-- --&gt;</span></span>
<span id="cb41-206"><a href="#cb41-206" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb41-207"><a href="#cb41-207" aria-hidden="true" tabindex="-1"></a>(i) new <span class="sc">\&lt;</span>- (116.132<span class="sc">\*</span>3000) + 17505.41</span>
<span id="cb41-208"><a href="#cb41-208" aria-hidden="true" tabindex="-1"></a>(ii) old <span class="sc">\&lt;</span>- (116.132<span class="sc">\*</span>3000) -40320.867</span>
<span id="cb41-209"><a href="#cb41-209" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb41-210"><a href="#cb41-210" aria-hidden="true" tabindex="-1"></a>New is valued at 365,901.41 while old is valued at 308,075.133\</span>
<span id="cb41-211"><a href="#cb41-211" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb41-212"><a href="#cb41-212" aria-hidden="true" tabindex="-1"></a><span class="ss">4.  </span>Fit another model, this time with an interaction term allowing interaction between size and new, and report the regression results</span>
<span id="cb41-213"><a href="#cb41-213" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb41-216"><a href="#cb41-216" aria-hidden="true" tabindex="-1"></a><span class="in">```{r}</span></span>
<span id="cb41-217"><a href="#cb41-217" aria-hidden="true" tabindex="-1"></a>Reg2 <span class="ot">&lt;-</span> <span class="fu">lm</span>(Price <span class="sc">~</span> Size <span class="sc">+</span> New <span class="sc">+</span> New<span class="sc">*</span>Size, <span class="at">data =</span> house)</span>
<span id="cb41-218"><a href="#cb41-218" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(Reg2)</span>
<span id="cb41-219"><a href="#cb41-219" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb41-220"><a href="#cb41-220" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb41-221"><a href="#cb41-221" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb41-222"><a href="#cb41-222" aria-hidden="true" tabindex="-1"></a>the regression results show that with size and the new the cost per sqft is 166.354 which is 61.916 higher compared to the not new version. This is the focus of this regression is to evaluate the interaction term</span>
<span id="cb41-223"><a href="#cb41-223" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb41-224"><a href="#cb41-224" aria-hidden="true" tabindex="-1"></a>\</span>
<span id="cb41-225"><a href="#cb41-225" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb41-226"><a href="#cb41-226" aria-hidden="true" tabindex="-1"></a><span class="ss">5.  </span>Report the lines relating the predicted selling price to the size for homes that are (i) new, (ii) not new.</span>
<span id="cb41-227"><a href="#cb41-227" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb41-230"><a href="#cb41-230" aria-hidden="true" tabindex="-1"></a><span class="in">```{r}</span></span>
<span id="cb41-231"><a href="#cb41-231" aria-hidden="true" tabindex="-1"></a><span class="co">#mod &lt;- -22227.81 + 104.44x1 -78527.50x2 + 61.92(x1*z)</span></span>
<span id="cb41-232"><a href="#cb41-232" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb41-233"><a href="#cb41-233" aria-hidden="true" tabindex="-1"></a><span class="co">#old1 &lt;- -22227.81 + (104.44*x1)</span></span>
<span id="cb41-234"><a href="#cb41-234" aria-hidden="true" tabindex="-1"></a><span class="co">#new1 &lt;- -100755.31 + (166.36x1)</span></span>
<span id="cb41-235"><a href="#cb41-235" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb41-236"><a href="#cb41-236" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb41-237"><a href="#cb41-237" aria-hidden="true" tabindex="-1"></a>\</span>
<span id="cb41-238"><a href="#cb41-238" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb41-239"><a href="#cb41-239" aria-hidden="true" tabindex="-1"></a><span class="ss">6.  </span>Find the predicted selling price for a home of 3000 square feet that is (i) new, (ii) not new.</span>
<span id="cb41-240"><a href="#cb41-240" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb41-243"><a href="#cb41-243" aria-hidden="true" tabindex="-1"></a><span class="in">```{r}</span></span>
<span id="cb41-244"><a href="#cb41-244" aria-hidden="true" tabindex="-1"></a>old1 <span class="ot">&lt;-</span> <span class="sc">-</span><span class="fl">22227.81</span> <span class="sc">+</span> (<span class="fl">104.44</span><span class="sc">*</span><span class="dv">3000</span>)</span>
<span id="cb41-245"><a href="#cb41-245" aria-hidden="true" tabindex="-1"></a>new1 <span class="ot">&lt;-</span> <span class="sc">-</span><span class="fl">100755.31</span> <span class="sc">+</span> (<span class="fl">166.36</span><span class="sc">*</span><span class="dv">3000</span>)</span>
<span id="cb41-246"><a href="#cb41-246" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb41-247"><a href="#cb41-247" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb41-248"><a href="#cb41-248" aria-hidden="true" tabindex="-1"></a>For a new home with this interaction term, we see a price of 398324.69 and for an old we see 291092.19 which is a huge difference.</span>
<span id="cb41-249"><a href="#cb41-249" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb41-250"><a href="#cb41-250" aria-hidden="true" tabindex="-1"></a>\</span>
<span id="cb41-251"><a href="#cb41-251" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb41-252"><a href="#cb41-252" aria-hidden="true" tabindex="-1"></a><span class="ss">7.  </span>Find the predicted selling price for a home of 1500 square feet that is (i) new, (ii) not new. Comparing to (F), explain how the difference in predicted selling prices changes as the size of the home increases.</span>
<span id="cb41-253"><a href="#cb41-253" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb41-256"><a href="#cb41-256" aria-hidden="true" tabindex="-1"></a><span class="in">```{r}</span></span>
<span id="cb41-257"><a href="#cb41-257" aria-hidden="true" tabindex="-1"></a>old2 <span class="ot">&lt;-</span> <span class="sc">-</span><span class="fl">22227.81</span> <span class="sc">+</span> (<span class="fl">104.44</span><span class="sc">*</span><span class="dv">1500</span>)</span>
<span id="cb41-258"><a href="#cb41-258" aria-hidden="true" tabindex="-1"></a>new2 <span class="ot">&lt;-</span> <span class="sc">-</span><span class="fl">100755.31</span> <span class="sc">+</span> (<span class="fl">166.36</span><span class="sc">*</span><span class="dv">1500</span>)</span>
<span id="cb41-259"><a href="#cb41-259" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb41-260"><a href="#cb41-260" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb41-261"><a href="#cb41-261" aria-hidden="true" tabindex="-1"></a>Here we see the price of a new home is 148,784.69 at 1500 sqft while an old one is 134,432.19. The difference between these values is much smaller than it was last time and that falls to the slope. There is a difference of 61.916 between the new and old so the larger the home the larger the difference will be between the two.\</span>
<span id="cb41-262"><a href="#cb41-262" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb41-263"><a href="#cb41-263" aria-hidden="true" tabindex="-1"></a><span class="ss">8.  </span>Do you think the model with interaction or the one without it represents the relationship of size and new to the outcome price? What makes you prefer one model over another?</span>
<span id="cb41-264"><a href="#cb41-264" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb41-265"><a href="#cb41-265" aria-hidden="true" tabindex="-1"></a>When analyzing these two regressions I would take the second one with the interaction term as it accounts for the new variable in each sqft compared to the other one that had one static number which does not seem realistic. Another point to note is the difference in the r squared between the two regressions as the one with the interaction term is higher by \~ 2%.</span>
<span id="cb41-266"><a href="#cb41-266" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb41-267"><a href="#cb41-267" aria-hidden="true" tabindex="-1"></a>\</span>
</code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div></div></div></div></div>
</div> <!-- /content -->



</body></html>