<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.0.37">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">

<meta name="author" content="Kalimah Muhammad">
<meta name="dcterms.date" content="2022-11-14">

<title>- Homework #4</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
span.underline{text-decoration: underline;}
div.column{display: inline-block; vertical-align: top; width: 50%;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
    color: #aaaaaa;
  }
pre.numberSource { margin-left: 3em; border-left: 1px solid #aaaaaa;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
code span.al { color: #ff0000; font-weight: bold; } /* Alert */
code span.an { color: #60a0b0; font-weight: bold; font-style: italic; } /* Annotation */
code span.at { color: #7d9029; } /* Attribute */
code span.bn { color: #40a070; } /* BaseN */
code span.bu { } /* BuiltIn */
code span.cf { color: #007020; font-weight: bold; } /* ControlFlow */
code span.ch { color: #4070a0; } /* Char */
code span.cn { color: #880000; } /* Constant */
code span.co { color: #60a0b0; font-style: italic; } /* Comment */
code span.cv { color: #60a0b0; font-weight: bold; font-style: italic; } /* CommentVar */
code span.do { color: #ba2121; font-style: italic; } /* Documentation */
code span.dt { color: #902000; } /* DataType */
code span.dv { color: #40a070; } /* DecVal */
code span.er { color: #ff0000; font-weight: bold; } /* Error */
code span.ex { } /* Extension */
code span.fl { color: #40a070; } /* Float */
code span.fu { color: #06287e; } /* Function */
code span.im { } /* Import */
code span.in { color: #60a0b0; font-weight: bold; font-style: italic; } /* Information */
code span.kw { color: #007020; font-weight: bold; } /* Keyword */
code span.op { color: #666666; } /* Operator */
code span.ot { color: #007020; } /* Other */
code span.pp { color: #bc7a00; } /* Preprocessor */
code span.sc { color: #4070a0; } /* SpecialChar */
code span.ss { color: #bb6688; } /* SpecialString */
code span.st { color: #4070a0; } /* String */
code span.va { color: #19177c; } /* Variable */
code span.vs { color: #4070a0; } /* VerbatimString */
code span.wa { color: #60a0b0; font-weight: bold; font-style: italic; } /* Warning */
</style>


<script src="../site_libs/quarto-nav/quarto-nav.js"></script>
<script src="../site_libs/quarto-nav/headroom.min.js"></script>
<script src="../site_libs/clipboard/clipboard.min.js"></script>
<script src="../site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="../site_libs/quarto-search/fuse.min.js"></script>
<script src="../site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="../">
<link href="../images/DACSS_Round_Network.png" rel="icon" type="image/png">
<script src="../site_libs/quarto-html/quarto.js"></script>
<script src="../site_libs/quarto-html/popper.min.js"></script>
<script src="../site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="../site_libs/quarto-html/anchor.min.js"></script>
<link href="../site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="../site_libs/quarto-html/quarto-syntax-highlighting.css" rel="stylesheet" class="quarto-color-scheme" id="quarto-text-highlighting-styles">
<link href="../site_libs/quarto-html/quarto-syntax-highlighting-dark.css" rel="prefetch" class="quarto-color-scheme quarto-color-alternate" id="quarto-text-highlighting-styles">
<script src="../site_libs/bootstrap/bootstrap.min.js"></script>
<link href="../site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="../site_libs/bootstrap/bootstrap.min.css" rel="stylesheet" class="quarto-color-scheme" id="quarto-bootstrap" data-mode="light">
<link href="../site_libs/bootstrap/bootstrap-dark.min.css" rel="prefetch" class="quarto-color-scheme quarto-color-alternate" id="quarto-bootstrap" data-mode="dark">
<script id="quarto-search-options" type="application/json">{
  "location": "navbar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "end",
  "type": "overlay",
  "limit": 20,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit"
  }
}</script>


<meta name="twitter:title" content="- Homework #4">
<meta name="twitter:description" content="For recent data in Jacksonville, Florida, on y = selling price of home (in dollars), x1 = size of home (in square feet), and x2 = lot size (in square feet), the prediction equation is ŷ = −10,536 +…">
<meta name="twitter:creator" content="@UMassDACSS">
<meta name="twitter:card" content="summary">
</head>

<body class="nav-fixed">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
    <nav class="navbar navbar-expand-lg navbar-dark ">
      <div class="navbar-container container-fluid">
      <a class="navbar-brand" href="../index.html">
    <img src="../images/UMass White Wordmark Horiz.png" alt="">
  </a>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse" aria-controls="navbarCollapse" aria-expanded="false" aria-label="Toggle navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
  <span class="navbar-toggler-icon"></span>
</button>
          <div class="collapse navbar-collapse" id="navbarCollapse">
            <ul class="navbar-nav navbar-nav-scroll ms-auto">
  <li class="nav-item">
    <a class="nav-link" href="https://dacss.github.io/603_Fall_2022/">Fall 2022 Posts</a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="../about.html">Contributors</a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="https://umass.edu/sbs/dacss">DACSS</a>
  </li>  
  <li class="nav-item compact">
    <a class="nav-link" href="https://github.com/DACSS/603_Fall_2022"><i class="bi bi-github" role="img" aria-label="GitHub">
</i> 
 </a>
  </li>  
</ul>
              <div class="quarto-toggle-container">
                  <a href="" class="quarto-color-scheme-toggle nav-link" onclick="window.quartoToggleColorScheme(); return false;" title="Toggle dark mode"><i class="bi"></i></a>
              </div>
              <div id="quarto-search" class="" title="Search"></div>
          </div> <!-- /navcollapse -->
      </div> <!-- /container-fluid -->
    </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article page-navbar">
<!-- sidebar -->
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc">
    <h2 id="toc-title">On this page</h2>
   
  <ul>
  <li><a href="#question-1" id="toc-question-1" class="nav-link active" data-scroll-target="#question-1">Question 1</a>
  <ul class="collapse">
  <li><a href="#a" id="toc-a" class="nav-link" data-scroll-target="#a">1.A</a></li>
  <li><a href="#b" id="toc-b" class="nav-link" data-scroll-target="#b">1.B</a></li>
  <li><a href="#c" id="toc-c" class="nav-link" data-scroll-target="#c">1.C</a></li>
  </ul></li>
  <li><a href="#question-2" id="toc-question-2" class="nav-link" data-scroll-target="#question-2">Question 2</a>
  <ul class="collapse">
  <li><a href="#a-1" id="toc-a-1" class="nav-link" data-scroll-target="#a-1">2.A</a></li>
  <li><a href="#b-1" id="toc-b-1" class="nav-link" data-scroll-target="#b-1">2.B</a></li>
  <li><a href="#c-1" id="toc-c-1" class="nav-link" data-scroll-target="#c-1">2.C</a></li>
  <li><a href="#d" id="toc-d" class="nav-link" data-scroll-target="#d">2.D</a></li>
  <li><a href="#e" id="toc-e" class="nav-link" data-scroll-target="#e">2.E</a></li>
  <li><a href="#f" id="toc-f" class="nav-link" data-scroll-target="#f">2.F</a></li>
  <li><a href="#a-2" id="toc-a-2" class="nav-link" data-scroll-target="#a-2">3.A</a></li>
  <li><a href="#b-2" id="toc-b-2" class="nav-link" data-scroll-target="#b-2">3.B</a></li>
  <li><a href="#c-2" id="toc-c-2" class="nav-link" data-scroll-target="#c-2">3.C</a></li>
  <li><a href="#d-1" id="toc-d-1" class="nav-link" data-scroll-target="#d-1">3.D</a></li>
  <li><a href="#e-1" id="toc-e-1" class="nav-link" data-scroll-target="#e-1">3.E</a></li>
  <li><a href="#f-1" id="toc-f-1" class="nav-link" data-scroll-target="#f-1">3.F</a></li>
  <li><a href="#g" id="toc-g" class="nav-link" data-scroll-target="#g">3.G</a></li>
  <li><a href="#h" id="toc-h" class="nav-link" data-scroll-target="#h">3.H</a></li>
  </ul></li>
  </ul>
</nav>
    </div>
<!-- main -->
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<div class="quarto-title-block"><div><h1 class="title">Homework #4</h1><button type="button" class="btn code-tools-button dropdown-toggle" id="quarto-code-tools-menu" data-bs-toggle="dropdown" aria-expanded="false"><i class="bi"></i> Code</button><ul class="dropdown-menu dropdown-menu-end" aria-labelelledby="quarto-code-tools-menu"><li><a id="quarto-show-all-code" class="dropdown-item" href="javascript:void(0)" role="button">Show All Code</a></li><li><a id="quarto-hide-all-code" class="dropdown-item" href="javascript:void(0)" role="button">Hide All Code</a></li><li><hr class="dropdown-divider"></li><li><a id="quarto-view-source" class="dropdown-item" href="javascript:void(0)" role="button">View Source</a></li></ul></div></div>
  <div class="quarto-categories">
    <div class="quarto-category">hw4</div>
    <div class="quarto-category">Kalimah Muhammad</div>
  </div>
  </div>



<div class="quarto-title-meta">

    <div>
    <div class="quarto-title-meta-heading">Author</div>
    <div class="quarto-title-meta-contents">
             <p>Kalimah Muhammad </p>
          </div>
  </div>
    
    <div>
    <div class="quarto-title-meta-heading">Published</div>
    <div class="quarto-title-meta-contents">
      <p class="date">November 14, 2022</p>
    </div>
  </div>
    
  </div>
  

</header>

<div class="cell">
<details>
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb1"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(tidyverse)</span>
<span id="cb1-2"><a href="#cb1-2" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(dplyr)</span>
<span id="cb1-3"><a href="#cb1-3" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(ggplot2)</span>
<span id="cb1-4"><a href="#cb1-4" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(alr4)</span>
<span id="cb1-5"><a href="#cb1-5" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(smss)</span>
<span id="cb1-6"><a href="#cb1-6" aria-hidden="true" tabindex="-1"></a>knitr<span class="sc">::</span>opts_chunk<span class="sc">$</span><span class="fu">set</span>(<span class="at">echo =</span> <span class="cn">TRUE</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
</div>
<section id="question-1" class="level2">
<h2 class="anchored" data-anchor-id="question-1">Question 1</h2>
<p>For recent data in Jacksonville, Florida, on y = selling price of home (in dollars), x1 = size of home (in square feet), and x2 = lot size (in square feet), the prediction equation is ŷ = −10,536 + 53.8x1 + 2.84x2.</p>
<section id="a" class="level3">
<h3 class="anchored" data-anchor-id="a">1.A</h3>
<p>A particular home of 1240 square feet on a lot of 18,000 square feet sold for $145,000. Find the predicted selling price and the residual, and interpret.</p>
<div class="cell">
<details>
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb2"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb2-1"><a href="#cb2-1" aria-hidden="true" tabindex="-1"></a>test <span class="ot">&lt;-</span> <span class="fu">data.frame</span>(<span class="at">sq=</span><span class="fu">c</span>(<span class="dv">1240</span>), <span class="at">lot=</span><span class="fu">c</span>(<span class="dv">18000</span>), <span class="at">price=</span><span class="fu">c</span>(<span class="dv">145000</span>))</span>
<span id="cb2-2"><a href="#cb2-2" aria-hidden="true" tabindex="-1"></a>test_fit <span class="ot">&lt;-</span> <span class="fu">lm</span>(price<span class="sc">~</span>sq<span class="sc">+</span>lot, <span class="at">data=</span>test)</span>
<span id="cb2-3"><a href="#cb2-3" aria-hidden="true" tabindex="-1"></a><span class="fu">predict</span>(test_fit)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>     1 
145000 </code></pre>
</div>
<details>
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb4"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb4-1"><a href="#cb4-1" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(test_fit)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = price ~ sq + lot, data = test)

Residuals:
ALL 1 residuals are 0: no residual degrees of freedom!

Coefficients: (2 not defined because of singularities)
            Estimate Std. Error t value Pr(&gt;|t|)
(Intercept)   145000        NaN     NaN      NaN
sq                NA         NA      NA       NA
lot               NA         NA      NA       NA

Residual standard error: NaN on 0 degrees of freedom</code></pre>
</div>
</div>
</section>
<section id="b" class="level3">
<h3 class="anchored" data-anchor-id="b">1.B</h3>
<p>For fixed lot size, how much is the house selling price predicted to increase for each square-foot increase in home size? Why? The selling price would increase by 2,374.01 for each sqaure foot.</p>
</section>
<section id="c" class="level3">
<h3 class="anchored" data-anchor-id="c">1.C</h3>
<p>According to this prediction equation, for fixed home size, how much would lot size need to increase to have the same impact as a one-square-foot increase in home size? 2.84.</p>
</section>
</section>
<section id="question-2" class="level2">
<h2 class="anchored" data-anchor-id="question-2">Question 2</h2>
<p>(Data file: salary in alr4 R package). The data file concerns salary and other characteristics of all faculty in a small Midwestern college collected in the early 1980s for presentation in legal proceedings for which discrimination against women in salary was at issue. All persons in the data hold tenured or tenure track positions; temporary faculty are not included. The variables include degree, a factor with levels PhD and MS; rank, a factor with levels Asst, Assoc, and Prof; sex, a factor with levels Male and Female; Year, years in current rank; ysdeg, years since highest degree, and salary, academic year salary in dollars.</p>
<div class="cell">
<details>
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb6"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb6-1"><a href="#cb6-1" aria-hidden="true" tabindex="-1"></a><span class="fu">data</span>(salary) <span class="co">#load salary data</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
</div>
<section id="a-1" class="level3">
<h3 class="anchored" data-anchor-id="a-1">2.A</h3>
<p>Test the hypothesis that the mean salary for men and women is the same, without regard to any other variable but sex. Explain your findings.</p>
<div class="cell">
<details>
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb7"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb7-1"><a href="#cb7-1" aria-hidden="true" tabindex="-1"></a><span class="fu">t.test</span>(salary <span class="sc">~</span> sex, <span class="at">data=</span>salary)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>
    Welch Two Sample t-test

data:  salary by sex
t = 1.7744, df = 21.591, p-value = 0.09009
alternative hypothesis: true difference in means between group Male and group Female is not equal to 0
95 percent confidence interval:
 -567.8539 7247.1471
sample estimates:
  mean in group Male mean in group Female 
            24696.79             21357.14 </code></pre>
</div>
</div>
<p>Based on the above t.test, the average male salary is higher than the average female salary, 24,696.79 to 21,357.14 respectively.</p>
</section>
<section id="b-1" class="level3">
<h3 class="anchored" data-anchor-id="b-1">2.B</h3>
<p>Run a multiple linear regression with salary as the outcome variable and everything else as predictors, including sex. Assuming no interactions between sex and the other predictors, obtain a 95% confidence interval for the difference in salary between males and females.</p>
<div class="cell">
<details>
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb9"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb9-1"><a href="#cb9-1" aria-hidden="true" tabindex="-1"></a>salaryfit<span class="ot">&lt;-</span><span class="fu">lm</span>(salary <span class="sc">~</span> degree <span class="sc">+</span> rank <span class="sc">+</span> sex <span class="sc">+</span> year <span class="sc">+</span> ysdeg, <span class="at">data=</span>salary)</span>
<span id="cb9-2"><a href="#cb9-2" aria-hidden="true" tabindex="-1"></a>salaryfit</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = salary ~ degree + rank + sex + year + ysdeg, data = salary)

Coefficients:
(Intercept)    degreePhD    rankAssoc     rankProf    sexFemale         year  
    15746.0       1388.6       5292.4      11118.8       1166.4        476.3  
      ysdeg  
     -124.6  </code></pre>
</div>
<details>
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb11"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb11-1"><a href="#cb11-1" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(salaryfit)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = salary ~ degree + rank + sex + year + ysdeg, data = salary)

Residuals:
    Min      1Q  Median      3Q     Max 
-4045.2 -1094.7  -361.5   813.2  9193.1 

Coefficients:
            Estimate Std. Error t value Pr(&gt;|t|)    
(Intercept) 15746.05     800.18  19.678  &lt; 2e-16 ***
degreePhD    1388.61    1018.75   1.363    0.180    
rankAssoc    5292.36    1145.40   4.621 3.22e-05 ***
rankProf    11118.76    1351.77   8.225 1.62e-10 ***
sexFemale    1166.37     925.57   1.260    0.214    
year          476.31      94.91   5.018 8.65e-06 ***
ysdeg        -124.57      77.49  -1.608    0.115    
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 2398 on 45 degrees of freedom
Multiple R-squared:  0.855, Adjusted R-squared:  0.8357 
F-statistic: 44.24 on 6 and 45 DF,  p-value: &lt; 2.2e-16</code></pre>
</div>
<details>
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb13"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb13-1"><a href="#cb13-1" aria-hidden="true" tabindex="-1"></a><span class="fu">pairs</span>(salary)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output-display">
<p><img src="KalimahMuhammad_hw4_files/figure-html/unnamed-chunk-5-1.png" class="img-fluid" width="672"></p>
</div>
</div>
</section>
<section id="c-1" class="level3">
<h3 class="anchored" data-anchor-id="c-1">2.C</h3>
<p>Interpret your finding for each predictor variable; discuss (a) statistical significance, (b) interpretation of the coefficient / slope in relation to the outcome variable and other variables.</p>
<p>-MS degree: baseline estimate<br>
-PHD degree: increase in estimate<br>
-Rank Asst.: significantly lowers estimate, statistically significant<br>
-Rank Assoc.: significantly lowers estimate, statistically significant<br>
-Rank Prof.: baseline estimate, statistically significant<br>
-Female: increase in estimate<br>
-Year: statistically significant<br>
-Year since degree: minimally lowers estimate</p>
<p>From the pairs graph, we also see an association between rank, year, years since degree, and salary.</p>
</section>
<section id="d" class="level3">
<h3 class="anchored" data-anchor-id="d">2.D</h3>
<p>Change the baseline category for the rank variable. Interpret the coefficients related to rank again.</p>
<div class="cell">
<details>
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb14"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb14-1"><a href="#cb14-1" aria-hidden="true" tabindex="-1"></a>salary<span class="sc">$</span>rank <span class="ot">&lt;-</span><span class="fu">relevel</span>(salary<span class="sc">$</span>rank, <span class="at">ref=</span><span class="st">"Prof"</span>)</span>
<span id="cb14-2"><a href="#cb14-2" aria-hidden="true" tabindex="-1"></a><span class="fu">lm</span>(salary <span class="sc">~</span> rank, <span class="at">data=</span>salary)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = salary ~ rank, data = salary)

Coefficients:
(Intercept)     rankAsst    rankAssoc  
      29659       -11890        -6483  </code></pre>
</div>
<details>
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb16"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb16-1"><a href="#cb16-1" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(<span class="fu">lm</span>(salary <span class="sc">~</span> rank, <span class="at">data=</span>salary))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = salary ~ rank, data = salary)

Residuals:
    Min      1Q  Median      3Q     Max 
-5209.0 -1819.2  -417.8  1586.6  8386.0 

Coefficients:
            Estimate Std. Error t value Pr(&gt;|t|)    
(Intercept)  29659.0      669.3  44.316  &lt; 2e-16 ***
rankAsst    -11890.3      972.4 -12.228  &lt; 2e-16 ***
rankAssoc    -6483.0     1043.0  -6.216 1.09e-07 ***
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 2993 on 49 degrees of freedom
Multiple R-squared:  0.7542,    Adjusted R-squared:  0.7442 
F-statistic: 75.17 on 2 and 49 DF,  p-value: 1.174e-15</code></pre>
</div>
</div>
<p>Here, we can see higher salary associated with higher ranking (Professor compared to Assistant and Associate Professor) based on the estimate and coefficient values.</p>
</section>
<section id="e" class="level3">
<h3 class="anchored" data-anchor-id="e">2.E</h3>
<p>Finkelstein (1980), in a discussion of the use of regression in discrimination cases, wrote, “[a] variable may reflect a position or status bestowed by the employer, in which case if there is discrimination in the award of the position or status, the variable may be ‘tainted.’” Thus, for example, if discrimination is at work in promotion of faculty to higher ranks, using rank to adjust salaries before comparing the sexes may not be acceptable to the courts.</p>
<p>Exclude the variable rank, refit, and summarize how your findings changed, if they did.</p>
<div class="cell">
<details>
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb18"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb18-1"><a href="#cb18-1" aria-hidden="true" tabindex="-1"></a>salaryfit2<span class="ot">&lt;-</span><span class="fu">lm</span>(salary <span class="sc">~</span> degree <span class="sc">+</span> sex <span class="sc">+</span> year <span class="sc">+</span> ysdeg, <span class="at">data=</span>salary)</span>
<span id="cb18-2"><a href="#cb18-2" aria-hidden="true" tabindex="-1"></a>salaryfit2</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = salary ~ degree + sex + year + ysdeg, data = salary)

Coefficients:
(Intercept)    degreePhD    sexFemale         year        ysdeg  
    17183.6      -3299.3      -1286.5        352.0        339.4  </code></pre>
</div>
<details>
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb20"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb20-1"><a href="#cb20-1" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(salaryfit2)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = salary ~ degree + sex + year + ysdeg, data = salary)

Residuals:
    Min      1Q  Median      3Q     Max 
-8146.9 -2186.9  -491.5  2279.1 11186.6 

Coefficients:
            Estimate Std. Error t value Pr(&gt;|t|)    
(Intercept) 17183.57    1147.94  14.969  &lt; 2e-16 ***
degreePhD   -3299.35    1302.52  -2.533 0.014704 *  
sexFemale   -1286.54    1313.09  -0.980 0.332209    
year          351.97     142.48   2.470 0.017185 *  
ysdeg         339.40      80.62   4.210 0.000114 ***
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 3744 on 47 degrees of freedom
Multiple R-squared:  0.6312,    Adjusted R-squared:  0.5998 
F-statistic: 20.11 on 4 and 47 DF,  p-value: 1.048e-09</code></pre>
</div>
</div>
<p>Excluding rank, variables for degree, year, and years since degree become more significant.</p>
</section>
<section id="f" class="level3">
<h3 class="anchored" data-anchor-id="f">2.F</h3>
<p>Everyone in this dataset was hired the year they earned their highest degree. It is also known that a new Dean was appointed 15 years ago, and everyone in the dataset who earned their highest degree 15 years ago or less than that has been hired by the new Dean. Some people have argued that the new Dean has been making offers that are a lot more generous to newly hired faculty than the previous one and that this might explain some of the variation in Salary.</p>
<p>Create a new variable that would allow you to test this hypothesis and run another multiple regression model to test this. Select variables carefully to make sure there is no multicollinearity. Explain why multicollinearity would be a concern in this case and how you avoided it. Do you find support for the hypothesis that the people hired by the new Dean are making higher than those that were not?</p>
<div class="cell">
<details>
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb22"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb22-1"><a href="#cb22-1" aria-hidden="true" tabindex="-1"></a>salary2 <span class="ot">&lt;-</span> salary<span class="sc">%&gt;%</span></span>
<span id="cb22-2"><a href="#cb22-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">new_dean=</span> year<span class="sc">&lt;</span><span class="st">'16'</span>) <span class="co">#create column determining if new dean present</span></span>
<span id="cb22-3"><a href="#cb22-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb22-4"><a href="#cb22-4" aria-hidden="true" tabindex="-1"></a><span class="fu">t.test</span>(salary <span class="sc">~</span> new_dean, <span class="at">data=</span>salary2)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>
    Welch Two Sample t-test

data:  salary by new_dean
t = -0.55774, df = 39.995, p-value = 0.5801
alternative hypothesis: true difference in means between group FALSE and group TRUE is not equal to 0
95 percent confidence interval:
 -4337.222  2461.145
sample estimates:
mean in group FALSE  mean in group TRUE 
           23454.91            24392.95 </code></pre>
</div>
<details>
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb24"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb24-1"><a href="#cb24-1" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(<span class="fu">lm</span>(salary <span class="sc">~</span> new_dean, <span class="at">data=</span>salary2))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = salary ~ new_dean, data = salary2)

Residuals:
    Min      1Q  Median      3Q     Max 
-9392.9 -5208.2   264.1  3441.8 14590.1 

Coefficients:
             Estimate Std. Error t value Pr(&gt;|t|)    
(Intercept)     23455       1037  22.613   &lt;2e-16 ***
new_deanTRUE      938       1716   0.547    0.587    
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 5958 on 50 degrees of freedom
Multiple R-squared:  0.005941,  Adjusted R-squared:  -0.01394 
F-statistic: 0.2988 on 1 and 50 DF,  p-value: 0.587</code></pre>
</div>
</div>
<p>Based on the two-sample t-test and regression model, faculty hired by the new dean 15 years ago have a slightly higher salary than those hired prior. This may be attributed to the rank or experience of those hired under the new dean’s tenure so we will perform another model using the interacting term rank and degree.</p>
<div class="cell">
<details>
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb26"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb26-1"><a href="#cb26-1" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(<span class="fu">lm</span>(salary <span class="sc">~</span> degree <span class="sc">+</span> rank <span class="sc">*</span>new_dean, <span class="at">data=</span>salary2))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = salary ~ degree + rank * new_dean, data = salary2)

Residuals:
    Min      1Q  Median      3Q     Max 
-5886.9 -1584.4  -499.6  1538.8  8831.1 

Coefficients:
                        Estimate Std. Error t value Pr(&gt;|t|)    
(Intercept)             29213.89     867.27  33.685  &lt; 2e-16 ***
degreePhD                1054.74    1020.26   1.034    0.307    
rankAsst               -11764.52    1208.79  -9.732 1.21e-12 ***
rankAssoc               -6958.52    1610.43  -4.321 8.47e-05 ***
new_deanTRUE              518.22    1468.73   0.353    0.726    
rankAsst:new_deanTRUE    -212.54    2189.70  -0.097    0.923    
rankAssoc:new_deanTRUE    -33.19    2301.23  -0.014    0.989    
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 3075 on 45 degrees of freedom
Multiple R-squared:  0.7617,    Adjusted R-squared:  0.7299 
F-statistic: 23.97 on 6 and 45 DF,  p-value: 1.663e-12</code></pre>
</div>
</div>
<p>Once controlled for the dean status, faculty hired as Assistant and Associate Professors during the prior dean’s tenure were estimated considerably less.</p>
</section>
<section id="a-2" class="level3">
<h3 class="anchored" data-anchor-id="a-2">3.A</h3>
<p>Using the house.selling.price data, run and report regression results modeling y = selling price (in dollars) in terms of size of home (in square feet) and whether the home is new (1 = yes; 0 = no). In particular, for each variable; discuss statistical significance and interpret the meaning of the coefficient.</p>
<div class="cell">
<details>
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb28"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb28-1"><a href="#cb28-1" aria-hidden="true" tabindex="-1"></a><span class="fu">data</span>(house.selling.price) <span class="co">#load data</span></span>
<span id="cb28-2"><a href="#cb28-2" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(<span class="fu">lm</span>(Price <span class="sc">~</span> Size <span class="sc">+</span> New, <span class="at">data=</span>house.selling.price))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = Price ~ Size + New, data = house.selling.price)

Residuals:
    Min      1Q  Median      3Q     Max 
-205102  -34374   -5778   18929  163866 

Coefficients:
              Estimate Std. Error t value Pr(&gt;|t|)    
(Intercept) -40230.867  14696.140  -2.738  0.00737 ** 
Size           116.132      8.795  13.204  &lt; 2e-16 ***
New          57736.283  18653.041   3.095  0.00257 ** 
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 53880 on 97 degrees of freedom
Multiple R-squared:  0.7226,    Adjusted R-squared:  0.7169 
F-statistic: 126.3 on 2 and 97 DF,  p-value: &lt; 2.2e-16</code></pre>
</div>
</div>
<p>Newness appears as the most statistically significant variable in determining price followed by size.</p>
</section>
<section id="b-2" class="level3">
<h3 class="anchored" data-anchor-id="b-2">3.B</h3>
<p>Report and interpret the prediction equation, and form separate equations relating selling price to size for new and for not new homes.</p>
<div class="cell">
<details>
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb30"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb30-1"><a href="#cb30-1" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(<span class="fu">lm</span>(Price <span class="sc">~</span> New<span class="sc">*</span>Size, <span class="at">data=</span>house.selling.price))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = Price ~ New * Size, data = house.selling.price)

Residuals:
    Min      1Q  Median      3Q     Max 
-175748  -28979   -6260   14693  192519 

Coefficients:
              Estimate Std. Error t value Pr(&gt;|t|)    
(Intercept) -22227.808  15521.110  -1.432  0.15536    
New         -78527.502  51007.642  -1.540  0.12697    
Size           104.438      9.424  11.082  &lt; 2e-16 ***
New:Size        61.916     21.686   2.855  0.00527 ** 
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 52000 on 96 degrees of freedom
Multiple R-squared:  0.7443,    Adjusted R-squared:  0.7363 
F-statistic: 93.15 on 3 and 96 DF,  p-value: &lt; 2.2e-16</code></pre>
</div>
</div>
<p>Older homes are estimated less than newer homes but the size of a newer home is the most statistically significant.</p>
</section>
<section id="c-2" class="level3">
<h3 class="anchored" data-anchor-id="c-2">3.C</h3>
<p>Find the predicted selling price for a home of 3000 square feet that is (i) new, (ii) not new.</p>
<div class="cell">
<details>
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb32"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb32-1"><a href="#cb32-1" aria-hidden="true" tabindex="-1"></a>old <span class="ot">&lt;-</span> <span class="fu">data.frame</span>(<span class="at">Size=</span><span class="fu">c</span>(<span class="dv">3000</span>), <span class="at">New =</span> <span class="dv">0</span>)</span>
<span id="cb32-2"><a href="#cb32-2" aria-hidden="true" tabindex="-1"></a><span class="fu">predict</span>((<span class="fu">lm</span>(Price<span class="sc">~</span>Size<span class="sc">+</span>New, <span class="at">data=</span>house.selling.price)), old)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>       1 
308163.9 </code></pre>
</div>
<details>
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb34"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb34-1"><a href="#cb34-1" aria-hidden="true" tabindex="-1"></a>new <span class="ot">&lt;-</span> <span class="fu">data.frame</span>(<span class="at">Size=</span><span class="fu">c</span>(<span class="dv">3000</span>), <span class="at">New =</span> <span class="dv">1</span>)</span>
<span id="cb34-2"><a href="#cb34-2" aria-hidden="true" tabindex="-1"></a><span class="fu">predict</span>((<span class="fu">lm</span>(Price<span class="sc">~</span>Size<span class="sc">+</span>New, <span class="at">data=</span>house.selling.price)), new)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>       1 
365900.2 </code></pre>
</div>
</div>
</section>
<section id="d-1" class="level3">
<h3 class="anchored" data-anchor-id="d-1">3.D</h3>
<p>Fit another model, this time with an interaction term allowing interaction between size and new, and report the regression results.</p>
<div class="cell">
<details>
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb36"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb36-1"><a href="#cb36-1" aria-hidden="true" tabindex="-1"></a>old <span class="ot">&lt;-</span> <span class="fu">data.frame</span>(<span class="at">Size=</span><span class="fu">c</span>(<span class="dv">3000</span>), <span class="at">New =</span> <span class="dv">0</span>)</span>
<span id="cb36-2"><a href="#cb36-2" aria-hidden="true" tabindex="-1"></a><span class="fu">predict</span>((<span class="fu">lm</span>(Price<span class="sc">~</span>Size<span class="sc">*</span>New, <span class="at">data=</span>house.selling.price)), old)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>       1 
291087.4 </code></pre>
</div>
<details>
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb38"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb38-1"><a href="#cb38-1" aria-hidden="true" tabindex="-1"></a>new <span class="ot">&lt;-</span> <span class="fu">data.frame</span>(<span class="at">Size=</span><span class="fu">c</span>(<span class="dv">3000</span>), <span class="at">New =</span> <span class="dv">1</span>)</span>
<span id="cb38-2"><a href="#cb38-2" aria-hidden="true" tabindex="-1"></a><span class="fu">predict</span>((<span class="fu">lm</span>(Price<span class="sc">~</span>Size<span class="sc">*</span>New, <span class="at">data=</span>house.selling.price)), new)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>       1 
398307.5 </code></pre>
</div>
</div>
</section>
<section id="e-1" class="level3">
<h3 class="anchored" data-anchor-id="e-1">3.E</h3>
<p>Report the lines relating the predicted selling price to the size for homes that are (i) new, (ii) not new.</p>
<p>When the interacting term is added both the price of the older home decreases and the price for the newer home increases. This creates a greater range in variability compared to the first model.</p>
</section>
<section id="f-1" class="level3">
<h3 class="anchored" data-anchor-id="f-1">3.F</h3>
<p>Find the predicted selling price for a home of 3000 square feet that is (i) new, (ii) not new.</p>
<div class="cell">
<details>
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb40"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb40-1"><a href="#cb40-1" aria-hidden="true" tabindex="-1"></a>old <span class="ot">&lt;-</span> <span class="fu">data.frame</span>(<span class="at">Size=</span><span class="fu">c</span>(<span class="dv">3000</span>), <span class="at">New =</span> <span class="dv">0</span>)</span>
<span id="cb40-2"><a href="#cb40-2" aria-hidden="true" tabindex="-1"></a><span class="fu">predict</span>((<span class="fu">lm</span>(Price<span class="sc">~</span>Size<span class="sc">+</span>New, <span class="at">data=</span>house.selling.price)), old)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>       1 
308163.9 </code></pre>
</div>
<details>
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb42"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb42-1"><a href="#cb42-1" aria-hidden="true" tabindex="-1"></a>new <span class="ot">&lt;-</span> <span class="fu">data.frame</span>(<span class="at">Size=</span><span class="fu">c</span>(<span class="dv">3000</span>), <span class="at">New =</span> <span class="dv">1</span>)</span>
<span id="cb42-2"><a href="#cb42-2" aria-hidden="true" tabindex="-1"></a><span class="fu">predict</span>((<span class="fu">lm</span>(Price<span class="sc">~</span>Size<span class="sc">+</span>New, <span class="at">data=</span>house.selling.price)), new)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>       1 
365900.2 </code></pre>
</div>
</div>
<p>For an older home, the price for a 3000sq home is predicted at 308,163.90. For a new home, the predicted price would be 365,900.20.</p>
</section>
<section id="g" class="level3">
<h3 class="anchored" data-anchor-id="g">3.G</h3>
<p>Find the predicted selling price for a home of 1500 square feet that is (i) new, (ii) not new. Comparing to (F), explain how the difference in predicted selling prices changes as the size of home increases.</p>
<div class="cell">
<details>
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb44"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb44-1"><a href="#cb44-1" aria-hidden="true" tabindex="-1"></a>old2 <span class="ot">&lt;-</span> <span class="fu">data.frame</span>(<span class="at">Size=</span><span class="fu">c</span>(<span class="dv">1500</span>), <span class="at">New =</span> <span class="dv">0</span>)</span>
<span id="cb44-2"><a href="#cb44-2" aria-hidden="true" tabindex="-1"></a><span class="fu">predict</span>((<span class="fu">lm</span>(Price<span class="sc">~</span> Size <span class="sc">+</span> New, <span class="at">data=</span>house.selling.price)), old2)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>       1 
133966.5 </code></pre>
</div>
<details>
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb46"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb46-1"><a href="#cb46-1" aria-hidden="true" tabindex="-1"></a>new2 <span class="ot">&lt;-</span> <span class="fu">data.frame</span>(<span class="at">Size=</span><span class="fu">c</span>(<span class="dv">1500</span>), <span class="at">New =</span> <span class="dv">1</span>)</span>
<span id="cb46-2"><a href="#cb46-2" aria-hidden="true" tabindex="-1"></a><span class="fu">predict</span>((<span class="fu">lm</span>(Price<span class="sc">~</span> Size <span class="sc">+</span> New, <span class="at">data=</span>house.selling.price)), new2)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>       1 
191702.8 </code></pre>
</div>
</div>
<p>For an older home, the price for a 1500sq home is predicted at 133,966.50. For a new home, the predicted price would be 191,702.80.</p>
<p>As the size of the home doubles, the predicted price of both the older and newer home increased by the same value of 174,197.40.</p>
</section>
<section id="h" class="level3">
<h3 class="anchored" data-anchor-id="h">3.H</h3>
<p>Do you think the model with interaction or the one without it represents the relationship of size and new to the outcome price? What makes you prefer one model over another? The model that adds whether the home is new rather than multiply by it, is a better model more reflective of the actual rates.</p>


<!-- -->

</section>
</section>

</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const disableStylesheet = (stylesheets) => {
    for (let i=0; i < stylesheets.length; i++) {
      const stylesheet = stylesheets[i];
      stylesheet.rel = 'prefetch';
    }
  }
  const enableStylesheet = (stylesheets) => {
    for (let i=0; i < stylesheets.length; i++) {
      const stylesheet = stylesheets[i];
      stylesheet.rel = 'stylesheet';
    }
  }
  const manageTransitions = (selector, allowTransitions) => {
    const els = window.document.querySelectorAll(selector);
    for (let i=0; i < els.length; i++) {
      const el = els[i];
      if (allowTransitions) {
        el.classList.remove('notransition');
      } else {
        el.classList.add('notransition');
      }
    }
  }
  const toggleColorMode = (alternate) => {
    // Switch the stylesheets
    const alternateStylesheets = window.document.querySelectorAll('link.quarto-color-scheme.quarto-color-alternate');
    manageTransitions('#quarto-margin-sidebar .nav-link', false);
    if (alternate) {
      enableStylesheet(alternateStylesheets);
      for (const sheetNode of alternateStylesheets) {
        if (sheetNode.id === "quarto-bootstrap") {
          toggleBodyColorMode(sheetNode);
        }
      }
    } else {
      disableStylesheet(alternateStylesheets);
      toggleBodyColorPrimary();
    }
    manageTransitions('#quarto-margin-sidebar .nav-link', true);
    // Switch the toggles
    const toggles = window.document.querySelectorAll('.quarto-color-scheme-toggle');
    for (let i=0; i < toggles.length; i++) {
      const toggle = toggles[i];
      if (toggle) {
        if (alternate) {
          toggle.classList.add("alternate");     
        } else {
          toggle.classList.remove("alternate");
        }
      }
    }
  }
  const isFileUrl = () => { 
    return window.location.protocol === 'file:';
  }
  const hasAlternateSentinel = () => {  
    let styleSentinel = getColorSchemeSentinel();
    if (styleSentinel !== null) {
      return styleSentinel === "alternate";
    } else {
      return false;
    }
  }
  const setStyleSentinel = (alternate) => {
    const value = alternate ? "alternate" : "default";
    if (!isFileUrl()) {
      window.localStorage.setItem("quarto-color-scheme", value);
    } else {
      localAlternateSentinel = value;
    }
  }
  const getColorSchemeSentinel = () => {
    if (!isFileUrl()) {
      const storageValue = window.localStorage.getItem("quarto-color-scheme");
      return storageValue != null ? storageValue : localAlternateSentinel;
    } else {
      return localAlternateSentinel;
    }
  }
  let localAlternateSentinel = 'default';
  // Dark / light mode switch
  window.quartoToggleColorScheme = () => {
    // Read the current dark / light value 
    let toAlternate = !hasAlternateSentinel();
    toggleColorMode(toAlternate);
    setStyleSentinel(toAlternate);
  };
  // Ensure there is a toggle, if there isn't float one in the top right
  if (window.document.querySelector('.quarto-color-scheme-toggle') === null) {
    const a = window.document.createElement('a');
    a.classList.add('top-right');
    a.classList.add('quarto-color-scheme-toggle');
    a.href = "";
    a.onclick = function() { try { window.quartoToggleColorScheme(); } catch {} return false; };
    const i = window.document.createElement("i");
    i.classList.add('bi');
    a.appendChild(i);
    window.document.body.appendChild(a);
  }
  // Switch to dark mode if need be
  if (hasAlternateSentinel()) {
    toggleColorMode(true);
  } 
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const clipboard = new window.ClipboardJS('.code-copy-button', {
    target: function(trigger) {
      return trigger.previousElementSibling;
    }
  });
  clipboard.on('success', function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copied!");
    setTimeout(function() {
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  });
  const viewSource = window.document.getElementById('quarto-view-source') ||
                     window.document.getElementById('quarto-code-tools-source');
  if (viewSource) {
    const sourceUrl = viewSource.getAttribute("data-quarto-source-url");
    viewSource.addEventListener("click", function(e) {
      if (sourceUrl) {
        // rstudio viewer pane
        if (/\bcapabilities=\b/.test(window.location)) {
          window.open(sourceUrl);
        } else {
          window.location.href = sourceUrl;
        }
      } else {
        const modal = new bootstrap.Modal(document.getElementById('quarto-embedded-source-code-modal'));
        modal.show();
      }
      return false;
    });
  }
  function toggleCodeHandler(show) {
    return function(e) {
      const detailsSrc = window.document.querySelectorAll(".cell > details > .sourceCode");
      for (let i=0; i<detailsSrc.length; i++) {
        const details = detailsSrc[i].parentElement;
        if (show) {
          details.open = true;
        } else {
          details.removeAttribute("open");
        }
      }
      const cellCodeDivs = window.document.querySelectorAll(".cell > .sourceCode");
      const fromCls = show ? "hidden" : "unhidden";
      const toCls = show ? "unhidden" : "hidden";
      for (let i=0; i<cellCodeDivs.length; i++) {
        const codeDiv = cellCodeDivs[i];
        if (codeDiv.classList.contains(fromCls)) {
          codeDiv.classList.remove(fromCls);
          codeDiv.classList.add(toCls);
        } 
      }
      return false;
    }
  }
  const hideAllCode = window.document.getElementById("quarto-hide-all-code");
  if (hideAllCode) {
    hideAllCode.addEventListener("click", toggleCodeHandler(false));
  }
  const showAllCode = window.document.getElementById("quarto-show-all-code");
  if (showAllCode) {
    showAllCode.addEventListener("click", toggleCodeHandler(true));
  }
  function tippyHover(el, contentFn) {
    const config = {
      allowHTML: true,
      content: contentFn,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start'
    };
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      let href = ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      return note.innerHTML;
    });
  }
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const cites = ref.parentNode.getAttribute('data-cites').split(' ');
    tippyHover(ref, function() {
      var popup = window.document.createElement('div');
      cites.forEach(function(cite) {
        var citeDiv = window.document.createElement('div');
        citeDiv.classList.add('hanging-indent');
        citeDiv.classList.add('csl-entry');
        var biblioDiv = window.document.getElementById('ref-' + cite);
        if (biblioDiv) {
          citeDiv.innerHTML = biblioDiv.innerHTML;
        }
        popup.appendChild(citeDiv);
      });
      return popup.innerHTML;
    });
  }
});
</script>
<script src="https://giscus.app/client.js" data-repo="DACSS/603_Fall_2022" data-repo-id="R_kgDOH568kA" data-category="Announcements" data-category-id="" data-mapping="title" data-reactions-enabled="1" data-emit-metadata="0" data-input-position="top" data-theme="light" data-lang="en" crossorigin="anonymous" async="">
</script><div class="modal fade" id="quarto-embedded-source-code-modal" tabindex="-1" aria-labelledby="quarto-embedded-source-code-modal-label" aria-hidden="true"><div class="modal-dialog modal-dialog-scrollable"><div class="modal-content"><div class="modal-header"><h5 class="modal-title" id="quarto-embedded-source-code-modal-label">Source Code</h5><button class="btn-close" data-bs-dismiss="modal"></button></div><div class="modal-body"><div class="">
<div class="sourceCode" id="cb48" data-shortcodes="false"><pre class="sourceCode markdown code-with-copy"><code class="sourceCode markdown"><span id="cb48-1"><a href="#cb48-1" aria-hidden="true" tabindex="-1"></a><span class="co">---</span></span>
<span id="cb48-2"><a href="#cb48-2" aria-hidden="true" tabindex="-1"></a><span class="an">title:</span><span class="co"> 'Homework #4'</span></span>
<span id="cb48-3"><a href="#cb48-3" aria-hidden="true" tabindex="-1"></a><span class="an">author:</span><span class="co"> "Kalimah Muhammad"</span></span>
<span id="cb48-4"><a href="#cb48-4" aria-hidden="true" tabindex="-1"></a><span class="an">date:</span><span class="co"> "11/14/2022"</span></span>
<span id="cb48-5"><a href="#cb48-5" aria-hidden="true" tabindex="-1"></a><span class="an">desription:</span><span class="co"> "Homework #4"</span></span>
<span id="cb48-6"><a href="#cb48-6" aria-hidden="true" tabindex="-1"></a><span class="an">format:</span></span>
<span id="cb48-7"><a href="#cb48-7" aria-hidden="true" tabindex="-1"></a><span class="co">  html:</span></span>
<span id="cb48-8"><a href="#cb48-8" aria-hidden="true" tabindex="-1"></a><span class="co">    toc: true</span></span>
<span id="cb48-9"><a href="#cb48-9" aria-hidden="true" tabindex="-1"></a><span class="co">    code-fold: true</span></span>
<span id="cb48-10"><a href="#cb48-10" aria-hidden="true" tabindex="-1"></a><span class="co">    code-copy: true</span></span>
<span id="cb48-11"><a href="#cb48-11" aria-hidden="true" tabindex="-1"></a><span class="co">    code-tools: true</span></span>
<span id="cb48-12"><a href="#cb48-12" aria-hidden="true" tabindex="-1"></a><span class="an">categories:</span><span class="co"> </span></span>
<span id="cb48-13"><a href="#cb48-13" aria-hidden="true" tabindex="-1"></a><span class="co">  - hw4</span></span>
<span id="cb48-14"><a href="#cb48-14" aria-hidden="true" tabindex="-1"></a><span class="co">  - Kalimah Muhammad</span></span>
<span id="cb48-15"><a href="#cb48-15" aria-hidden="true" tabindex="-1"></a><span class="co">---</span></span>
<span id="cb48-16"><a href="#cb48-16" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb48-19"><a href="#cb48-19" aria-hidden="true" tabindex="-1"></a><span class="in">```{r}</span></span>
<span id="cb48-20"><a href="#cb48-20" aria-hidden="true" tabindex="-1"></a><span class="co">#| label: setup</span></span>
<span id="cb48-21"><a href="#cb48-21" aria-hidden="true" tabindex="-1"></a><span class="co">#| warning: false</span></span>
<span id="cb48-22"><a href="#cb48-22" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb48-23"><a href="#cb48-23" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(tidyverse)</span>
<span id="cb48-24"><a href="#cb48-24" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(dplyr)</span>
<span id="cb48-25"><a href="#cb48-25" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(ggplot2)</span>
<span id="cb48-26"><a href="#cb48-26" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(alr4)</span>
<span id="cb48-27"><a href="#cb48-27" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(smss)</span>
<span id="cb48-28"><a href="#cb48-28" aria-hidden="true" tabindex="-1"></a>knitr<span class="sc">::</span>opts_chunk<span class="sc">$</span><span class="fu">set</span>(<span class="at">echo =</span> <span class="cn">TRUE</span>)</span>
<span id="cb48-29"><a href="#cb48-29" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb48-30"><a href="#cb48-30" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb48-31"><a href="#cb48-31" aria-hidden="true" tabindex="-1"></a><span class="fu">## Question 1</span></span>
<span id="cb48-32"><a href="#cb48-32" aria-hidden="true" tabindex="-1"></a>For recent data in Jacksonville, Florida, on y = selling price of home (in dollars), x1 = size of home (in square feet), and x2 = lot size (in square feet), the prediction equation is </span>
<span id="cb48-33"><a href="#cb48-33" aria-hidden="true" tabindex="-1"></a>ŷ = −10,536 + 53.8x1 + 2.84x2.</span>
<span id="cb48-34"><a href="#cb48-34" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb48-35"><a href="#cb48-35" aria-hidden="true" tabindex="-1"></a><span class="fu">### 1.A</span></span>
<span id="cb48-36"><a href="#cb48-36" aria-hidden="true" tabindex="-1"></a>A particular home of 1240 square feet on a lot of 18,000 square feet sold for $145,000. Find the predicted selling price and the residual, and interpret.</span>
<span id="cb48-37"><a href="#cb48-37" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb48-40"><a href="#cb48-40" aria-hidden="true" tabindex="-1"></a><span class="in">```{r}</span></span>
<span id="cb48-41"><a href="#cb48-41" aria-hidden="true" tabindex="-1"></a>test <span class="ot">&lt;-</span> <span class="fu">data.frame</span>(<span class="at">sq=</span><span class="fu">c</span>(<span class="dv">1240</span>), <span class="at">lot=</span><span class="fu">c</span>(<span class="dv">18000</span>), <span class="at">price=</span><span class="fu">c</span>(<span class="dv">145000</span>))</span>
<span id="cb48-42"><a href="#cb48-42" aria-hidden="true" tabindex="-1"></a>test_fit <span class="ot">&lt;-</span> <span class="fu">lm</span>(price<span class="sc">~</span>sq<span class="sc">+</span>lot, <span class="at">data=</span>test)</span>
<span id="cb48-43"><a href="#cb48-43" aria-hidden="true" tabindex="-1"></a><span class="fu">predict</span>(test_fit)</span>
<span id="cb48-44"><a href="#cb48-44" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(test_fit)</span>
<span id="cb48-45"><a href="#cb48-45" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb48-46"><a href="#cb48-46" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb48-47"><a href="#cb48-47" aria-hidden="true" tabindex="-1"></a><span class="fu">### 1.B</span></span>
<span id="cb48-48"><a href="#cb48-48" aria-hidden="true" tabindex="-1"></a>For fixed lot size, how much is the house selling price predicted to increase for each square-foot increase in home size? Why?  The selling price would increase by 2,374.01 for each sqaure foot.</span>
<span id="cb48-49"><a href="#cb48-49" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb48-50"><a href="#cb48-50" aria-hidden="true" tabindex="-1"></a><span class="fu">### 1.C</span></span>
<span id="cb48-51"><a href="#cb48-51" aria-hidden="true" tabindex="-1"></a>According to this prediction equation, for fixed home size, how much would lot size need to increase to have the same impact as a one-square-foot increase in home size? 2.84.</span>
<span id="cb48-52"><a href="#cb48-52" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb48-53"><a href="#cb48-53" aria-hidden="true" tabindex="-1"></a><span class="fu">## Question 2</span></span>
<span id="cb48-54"><a href="#cb48-54" aria-hidden="true" tabindex="-1"></a>(Data file: salary in alr4 R package). The data file concerns salary and other characteristics of all faculty in a small Midwestern college collected in the early 1980s for presentation in legal proceedings for which discrimination against women in salary was at issue. All persons in the data hold tenured or tenure track positions; temporary faculty are not included. The variables include degree, a factor with levels PhD and MS; rank, a factor with levels Asst, Assoc, and Prof; sex, a factor with levels Male and Female; Year, years in current rank; ysdeg, years since highest degree, and salary, academic year salary in dollars.</span>
<span id="cb48-55"><a href="#cb48-55" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb48-58"><a href="#cb48-58" aria-hidden="true" tabindex="-1"></a><span class="in">```{r}</span></span>
<span id="cb48-59"><a href="#cb48-59" aria-hidden="true" tabindex="-1"></a><span class="fu">data</span>(salary) <span class="co">#load salary data</span></span>
<span id="cb48-60"><a href="#cb48-60" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb48-61"><a href="#cb48-61" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb48-62"><a href="#cb48-62" aria-hidden="true" tabindex="-1"></a><span class="fu">### 2.A </span></span>
<span id="cb48-63"><a href="#cb48-63" aria-hidden="true" tabindex="-1"></a>Test the hypothesis that the mean salary for men and women is the same, without regard to any other variable but sex. Explain your findings.</span>
<span id="cb48-64"><a href="#cb48-64" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb48-67"><a href="#cb48-67" aria-hidden="true" tabindex="-1"></a><span class="in">```{r}</span></span>
<span id="cb48-68"><a href="#cb48-68" aria-hidden="true" tabindex="-1"></a><span class="fu">t.test</span>(salary <span class="sc">~</span> sex, <span class="at">data=</span>salary)</span>
<span id="cb48-69"><a href="#cb48-69" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb48-70"><a href="#cb48-70" aria-hidden="true" tabindex="-1"></a>Based on the above t.test, the average male salary is higher than the average female salary, 24,696.79 to 21,357.14 respectively. </span>
<span id="cb48-71"><a href="#cb48-71" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb48-72"><a href="#cb48-72" aria-hidden="true" tabindex="-1"></a><span class="fu">### 2.B</span></span>
<span id="cb48-73"><a href="#cb48-73" aria-hidden="true" tabindex="-1"></a>Run a multiple linear regression with salary as the outcome variable and everything else as predictors, including sex. Assuming no interactions between sex and the other predictors, obtain a 95% confidence interval for the difference in salary between males and females.</span>
<span id="cb48-74"><a href="#cb48-74" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb48-77"><a href="#cb48-77" aria-hidden="true" tabindex="-1"></a><span class="in">```{r}</span></span>
<span id="cb48-78"><a href="#cb48-78" aria-hidden="true" tabindex="-1"></a>salaryfit<span class="ot">&lt;-</span><span class="fu">lm</span>(salary <span class="sc">~</span> degree <span class="sc">+</span> rank <span class="sc">+</span> sex <span class="sc">+</span> year <span class="sc">+</span> ysdeg, <span class="at">data=</span>salary)</span>
<span id="cb48-79"><a href="#cb48-79" aria-hidden="true" tabindex="-1"></a>salaryfit</span>
<span id="cb48-80"><a href="#cb48-80" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(salaryfit)</span>
<span id="cb48-81"><a href="#cb48-81" aria-hidden="true" tabindex="-1"></a><span class="fu">pairs</span>(salary)</span>
<span id="cb48-82"><a href="#cb48-82" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb48-83"><a href="#cb48-83" aria-hidden="true" tabindex="-1"></a><span class="fu">### 2.C </span></span>
<span id="cb48-84"><a href="#cb48-84" aria-hidden="true" tabindex="-1"></a>Interpret your finding for each predictor variable; discuss (a) statistical significance, (b) interpretation of the coefficient / slope in relation to the outcome variable and other variables.</span>
<span id="cb48-85"><a href="#cb48-85" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb48-86"><a href="#cb48-86" aria-hidden="true" tabindex="-1"></a>-MS degree: baseline estimate   </span>
<span id="cb48-87"><a href="#cb48-87" aria-hidden="true" tabindex="-1"></a>-PHD degree: increase in estimate   </span>
<span id="cb48-88"><a href="#cb48-88" aria-hidden="true" tabindex="-1"></a>-Rank Asst.: significantly lowers estimate, statistically significant   </span>
<span id="cb48-89"><a href="#cb48-89" aria-hidden="true" tabindex="-1"></a>-Rank Assoc.: significantly lowers estimate, statistically significant  </span>
<span id="cb48-90"><a href="#cb48-90" aria-hidden="true" tabindex="-1"></a>-Rank Prof.: baseline estimate, statistically significant   </span>
<span id="cb48-91"><a href="#cb48-91" aria-hidden="true" tabindex="-1"></a>-Female: increase in estimate  </span>
<span id="cb48-92"><a href="#cb48-92" aria-hidden="true" tabindex="-1"></a>-Year: statistically significant  </span>
<span id="cb48-93"><a href="#cb48-93" aria-hidden="true" tabindex="-1"></a>-Year since degree: minimally lowers estimate  </span>
<span id="cb48-94"><a href="#cb48-94" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb48-95"><a href="#cb48-95" aria-hidden="true" tabindex="-1"></a>From the pairs graph, we also see an association between rank, year, years since degree, and salary.  </span>
<span id="cb48-96"><a href="#cb48-96" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb48-97"><a href="#cb48-97" aria-hidden="true" tabindex="-1"></a><span class="fu">### 2.D</span></span>
<span id="cb48-98"><a href="#cb48-98" aria-hidden="true" tabindex="-1"></a>Change the baseline category for the rank variable. Interpret the coefficients related to rank again.</span>
<span id="cb48-99"><a href="#cb48-99" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb48-102"><a href="#cb48-102" aria-hidden="true" tabindex="-1"></a><span class="in">```{r}</span></span>
<span id="cb48-103"><a href="#cb48-103" aria-hidden="true" tabindex="-1"></a>salary<span class="sc">$</span>rank <span class="ot">&lt;-</span><span class="fu">relevel</span>(salary<span class="sc">$</span>rank, <span class="at">ref=</span><span class="st">"Prof"</span>)</span>
<span id="cb48-104"><a href="#cb48-104" aria-hidden="true" tabindex="-1"></a><span class="fu">lm</span>(salary <span class="sc">~</span> rank, <span class="at">data=</span>salary)</span>
<span id="cb48-105"><a href="#cb48-105" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(<span class="fu">lm</span>(salary <span class="sc">~</span> rank, <span class="at">data=</span>salary))</span>
<span id="cb48-106"><a href="#cb48-106" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb48-107"><a href="#cb48-107" aria-hidden="true" tabindex="-1"></a>Here, we can see higher salary associated with higher ranking (Professor compared to Assistant and Associate Professor) based on the estimate and coefficient values.  </span>
<span id="cb48-108"><a href="#cb48-108" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb48-109"><a href="#cb48-109" aria-hidden="true" tabindex="-1"></a><span class="fu">### 2.E </span></span>
<span id="cb48-110"><a href="#cb48-110" aria-hidden="true" tabindex="-1"></a>Finkelstein (1980), in a discussion of the use of regression in discrimination cases, wrote, “<span class="co">[</span><span class="ot">a</span><span class="co">]</span> variable may reflect a position or status bestowed by the employer, in which case if there is discrimination in the award of the position or status, the variable may be ‘tainted.’ ” Thus, for example, if discrimination is at work in promotion of faculty to higher ranks, using rank to adjust salaries before comparing the sexes may not be acceptable to the courts. </span>
<span id="cb48-111"><a href="#cb48-111" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb48-112"><a href="#cb48-112" aria-hidden="true" tabindex="-1"></a>Exclude the variable rank, refit, and summarize how your findings changed, if they did.  </span>
<span id="cb48-113"><a href="#cb48-113" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb48-116"><a href="#cb48-116" aria-hidden="true" tabindex="-1"></a><span class="in">```{r}</span></span>
<span id="cb48-117"><a href="#cb48-117" aria-hidden="true" tabindex="-1"></a>salaryfit2<span class="ot">&lt;-</span><span class="fu">lm</span>(salary <span class="sc">~</span> degree <span class="sc">+</span> sex <span class="sc">+</span> year <span class="sc">+</span> ysdeg, <span class="at">data=</span>salary)</span>
<span id="cb48-118"><a href="#cb48-118" aria-hidden="true" tabindex="-1"></a>salaryfit2</span>
<span id="cb48-119"><a href="#cb48-119" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(salaryfit2)</span>
<span id="cb48-120"><a href="#cb48-120" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb48-121"><a href="#cb48-121" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb48-122"><a href="#cb48-122" aria-hidden="true" tabindex="-1"></a>Excluding rank, variables for degree, year, and years since degree become more significant. </span>
<span id="cb48-123"><a href="#cb48-123" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb48-124"><a href="#cb48-124" aria-hidden="true" tabindex="-1"></a><span class="fu">### 2.F</span></span>
<span id="cb48-125"><a href="#cb48-125" aria-hidden="true" tabindex="-1"></a>Everyone in this dataset was hired the year they earned their highest degree. It is also known that a new Dean was appointed 15 years ago, and everyone in the dataset who earned their highest degree 15 years ago or less than that has been hired by the new Dean. Some people have argued that the new Dean has been making offers that are a lot more generous to newly hired faculty than the previous one and that this might explain some of the variation in Salary.</span>
<span id="cb48-126"><a href="#cb48-126" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb48-127"><a href="#cb48-127" aria-hidden="true" tabindex="-1"></a>Create a new variable that would allow you to test this hypothesis and run another multiple regression model to test this. Select variables carefully to make sure there is no multicollinearity. Explain why multicollinearity would be a concern in this case and how you avoided it. Do you find support for the hypothesis that the people hired by the new Dean are making higher than those that were not?</span>
<span id="cb48-128"><a href="#cb48-128" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb48-131"><a href="#cb48-131" aria-hidden="true" tabindex="-1"></a><span class="in">```{r}</span></span>
<span id="cb48-132"><a href="#cb48-132" aria-hidden="true" tabindex="-1"></a>salary2 <span class="ot">&lt;-</span> salary<span class="sc">%&gt;%</span></span>
<span id="cb48-133"><a href="#cb48-133" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">new_dean=</span> year<span class="sc">&lt;</span><span class="st">'16'</span>) <span class="co">#create column determining if new dean present</span></span>
<span id="cb48-134"><a href="#cb48-134" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb48-135"><a href="#cb48-135" aria-hidden="true" tabindex="-1"></a><span class="fu">t.test</span>(salary <span class="sc">~</span> new_dean, <span class="at">data=</span>salary2)</span>
<span id="cb48-136"><a href="#cb48-136" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb48-137"><a href="#cb48-137" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(<span class="fu">lm</span>(salary <span class="sc">~</span> new_dean, <span class="at">data=</span>salary2))</span>
<span id="cb48-138"><a href="#cb48-138" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb48-139"><a href="#cb48-139" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb48-140"><a href="#cb48-140" aria-hidden="true" tabindex="-1"></a>Based on the two-sample t-test and regression model, faculty hired by the new dean 15 years ago have a slightly higher salary than those hired prior. This may be attributed to the rank or experience of those hired under the new dean's tenure so we will perform another model using the interacting term rank and degree.</span>
<span id="cb48-141"><a href="#cb48-141" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb48-144"><a href="#cb48-144" aria-hidden="true" tabindex="-1"></a><span class="in">```{r}</span></span>
<span id="cb48-145"><a href="#cb48-145" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(<span class="fu">lm</span>(salary <span class="sc">~</span> degree <span class="sc">+</span> rank <span class="sc">*</span>new_dean, <span class="at">data=</span>salary2))</span>
<span id="cb48-146"><a href="#cb48-146" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb48-147"><a href="#cb48-147" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb48-148"><a href="#cb48-148" aria-hidden="true" tabindex="-1"></a>Once controlled for the dean status, faculty hired as Assistant and Associate Professors during the prior dean's tenure were estimated considerably less.</span>
<span id="cb48-149"><a href="#cb48-149" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb48-150"><a href="#cb48-150" aria-hidden="true" tabindex="-1"></a><span class="fu">### 3.A</span></span>
<span id="cb48-151"><a href="#cb48-151" aria-hidden="true" tabindex="-1"></a>Using the house.selling.price data, run and report regression results modeling y = selling price (in dollars) in terms of size of home (in square feet) and whether the home is new (1 = yes; 0 = no). In particular, for each variable; discuss statistical significance and interpret the meaning of the coefficient.</span>
<span id="cb48-152"><a href="#cb48-152" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb48-155"><a href="#cb48-155" aria-hidden="true" tabindex="-1"></a><span class="in">```{r}</span></span>
<span id="cb48-156"><a href="#cb48-156" aria-hidden="true" tabindex="-1"></a><span class="fu">data</span>(house.selling.price) <span class="co">#load data</span></span>
<span id="cb48-157"><a href="#cb48-157" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(<span class="fu">lm</span>(Price <span class="sc">~</span> Size <span class="sc">+</span> New, <span class="at">data=</span>house.selling.price))</span>
<span id="cb48-158"><a href="#cb48-158" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb48-159"><a href="#cb48-159" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb48-160"><a href="#cb48-160" aria-hidden="true" tabindex="-1"></a>Newness appears as the most statistically significant variable in determining price followed by size.</span>
<span id="cb48-161"><a href="#cb48-161" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb48-162"><a href="#cb48-162" aria-hidden="true" tabindex="-1"></a><span class="fu">### 3.B</span></span>
<span id="cb48-163"><a href="#cb48-163" aria-hidden="true" tabindex="-1"></a>Report and interpret the prediction equation, and form separate equations relating selling price to size for new and for not new homes.</span>
<span id="cb48-164"><a href="#cb48-164" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb48-167"><a href="#cb48-167" aria-hidden="true" tabindex="-1"></a><span class="in">```{r}</span></span>
<span id="cb48-168"><a href="#cb48-168" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(<span class="fu">lm</span>(Price <span class="sc">~</span> New<span class="sc">*</span>Size, <span class="at">data=</span>house.selling.price))</span>
<span id="cb48-169"><a href="#cb48-169" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb48-170"><a href="#cb48-170" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb48-171"><a href="#cb48-171" aria-hidden="true" tabindex="-1"></a>Older homes are estimated less than newer homes but the size of a newer home is the most statistically significant. </span>
<span id="cb48-172"><a href="#cb48-172" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb48-173"><a href="#cb48-173" aria-hidden="true" tabindex="-1"></a><span class="fu">### 3.C</span></span>
<span id="cb48-174"><a href="#cb48-174" aria-hidden="true" tabindex="-1"></a>Find the predicted selling price for a home of 3000 square feet that is (i) new, (ii) not new.</span>
<span id="cb48-175"><a href="#cb48-175" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb48-178"><a href="#cb48-178" aria-hidden="true" tabindex="-1"></a><span class="in">```{r}</span></span>
<span id="cb48-179"><a href="#cb48-179" aria-hidden="true" tabindex="-1"></a>old <span class="ot">&lt;-</span> <span class="fu">data.frame</span>(<span class="at">Size=</span><span class="fu">c</span>(<span class="dv">3000</span>), <span class="at">New =</span> <span class="dv">0</span>)</span>
<span id="cb48-180"><a href="#cb48-180" aria-hidden="true" tabindex="-1"></a><span class="fu">predict</span>((<span class="fu">lm</span>(Price<span class="sc">~</span>Size<span class="sc">+</span>New, <span class="at">data=</span>house.selling.price)), old)</span>
<span id="cb48-181"><a href="#cb48-181" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb48-182"><a href="#cb48-182" aria-hidden="true" tabindex="-1"></a>new <span class="ot">&lt;-</span> <span class="fu">data.frame</span>(<span class="at">Size=</span><span class="fu">c</span>(<span class="dv">3000</span>), <span class="at">New =</span> <span class="dv">1</span>)</span>
<span id="cb48-183"><a href="#cb48-183" aria-hidden="true" tabindex="-1"></a><span class="fu">predict</span>((<span class="fu">lm</span>(Price<span class="sc">~</span>Size<span class="sc">+</span>New, <span class="at">data=</span>house.selling.price)), new)</span>
<span id="cb48-184"><a href="#cb48-184" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb48-185"><a href="#cb48-185" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb48-186"><a href="#cb48-186" aria-hidden="true" tabindex="-1"></a><span class="fu">### 3.D</span></span>
<span id="cb48-187"><a href="#cb48-187" aria-hidden="true" tabindex="-1"></a>Fit another model, this time with an interaction term allowing interaction between size and new, and report the regression results.</span>
<span id="cb48-188"><a href="#cb48-188" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb48-191"><a href="#cb48-191" aria-hidden="true" tabindex="-1"></a><span class="in">```{r}</span></span>
<span id="cb48-192"><a href="#cb48-192" aria-hidden="true" tabindex="-1"></a>old <span class="ot">&lt;-</span> <span class="fu">data.frame</span>(<span class="at">Size=</span><span class="fu">c</span>(<span class="dv">3000</span>), <span class="at">New =</span> <span class="dv">0</span>)</span>
<span id="cb48-193"><a href="#cb48-193" aria-hidden="true" tabindex="-1"></a><span class="fu">predict</span>((<span class="fu">lm</span>(Price<span class="sc">~</span>Size<span class="sc">*</span>New, <span class="at">data=</span>house.selling.price)), old)</span>
<span id="cb48-194"><a href="#cb48-194" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb48-195"><a href="#cb48-195" aria-hidden="true" tabindex="-1"></a>new <span class="ot">&lt;-</span> <span class="fu">data.frame</span>(<span class="at">Size=</span><span class="fu">c</span>(<span class="dv">3000</span>), <span class="at">New =</span> <span class="dv">1</span>)</span>
<span id="cb48-196"><a href="#cb48-196" aria-hidden="true" tabindex="-1"></a><span class="fu">predict</span>((<span class="fu">lm</span>(Price<span class="sc">~</span>Size<span class="sc">*</span>New, <span class="at">data=</span>house.selling.price)), new)</span>
<span id="cb48-197"><a href="#cb48-197" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb48-198"><a href="#cb48-198" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb48-199"><a href="#cb48-199" aria-hidden="true" tabindex="-1"></a><span class="fu">### 3.E</span></span>
<span id="cb48-200"><a href="#cb48-200" aria-hidden="true" tabindex="-1"></a>Report the lines relating the predicted selling price to the size for homes that are (i) new, (ii) not new.</span>
<span id="cb48-201"><a href="#cb48-201" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb48-202"><a href="#cb48-202" aria-hidden="true" tabindex="-1"></a>When the interacting term is added both the price of the older home decreases and the price for the newer home increases. This creates a greater range in variability compared to the first model. </span>
<span id="cb48-203"><a href="#cb48-203" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb48-204"><a href="#cb48-204" aria-hidden="true" tabindex="-1"></a><span class="fu">### 3.F</span></span>
<span id="cb48-205"><a href="#cb48-205" aria-hidden="true" tabindex="-1"></a>Find the predicted selling price for a home of 3000 square feet that is (i) new, (ii) not new.</span>
<span id="cb48-206"><a href="#cb48-206" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb48-209"><a href="#cb48-209" aria-hidden="true" tabindex="-1"></a><span class="in">```{r}</span></span>
<span id="cb48-210"><a href="#cb48-210" aria-hidden="true" tabindex="-1"></a>old <span class="ot">&lt;-</span> <span class="fu">data.frame</span>(<span class="at">Size=</span><span class="fu">c</span>(<span class="dv">3000</span>), <span class="at">New =</span> <span class="dv">0</span>)</span>
<span id="cb48-211"><a href="#cb48-211" aria-hidden="true" tabindex="-1"></a><span class="fu">predict</span>((<span class="fu">lm</span>(Price<span class="sc">~</span>Size<span class="sc">+</span>New, <span class="at">data=</span>house.selling.price)), old)</span>
<span id="cb48-212"><a href="#cb48-212" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb48-213"><a href="#cb48-213" aria-hidden="true" tabindex="-1"></a>new <span class="ot">&lt;-</span> <span class="fu">data.frame</span>(<span class="at">Size=</span><span class="fu">c</span>(<span class="dv">3000</span>), <span class="at">New =</span> <span class="dv">1</span>)</span>
<span id="cb48-214"><a href="#cb48-214" aria-hidden="true" tabindex="-1"></a><span class="fu">predict</span>((<span class="fu">lm</span>(Price<span class="sc">~</span>Size<span class="sc">+</span>New, <span class="at">data=</span>house.selling.price)), new)</span>
<span id="cb48-215"><a href="#cb48-215" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb48-216"><a href="#cb48-216" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb48-217"><a href="#cb48-217" aria-hidden="true" tabindex="-1"></a>For an older home, the price for a 3000sq home is predicted at 308,163.90. For a new home, the predicted price would be 365,900.20.</span>
<span id="cb48-218"><a href="#cb48-218" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb48-219"><a href="#cb48-219" aria-hidden="true" tabindex="-1"></a><span class="fu">### 3.G</span></span>
<span id="cb48-220"><a href="#cb48-220" aria-hidden="true" tabindex="-1"></a>Find the predicted selling price for a home of 1500 square feet that is (i) new, (ii) not new. Comparing to (F), explain how the difference in predicted selling prices changes as the size of home increases.</span>
<span id="cb48-221"><a href="#cb48-221" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb48-224"><a href="#cb48-224" aria-hidden="true" tabindex="-1"></a><span class="in">```{r}</span></span>
<span id="cb48-225"><a href="#cb48-225" aria-hidden="true" tabindex="-1"></a>old2 <span class="ot">&lt;-</span> <span class="fu">data.frame</span>(<span class="at">Size=</span><span class="fu">c</span>(<span class="dv">1500</span>), <span class="at">New =</span> <span class="dv">0</span>)</span>
<span id="cb48-226"><a href="#cb48-226" aria-hidden="true" tabindex="-1"></a><span class="fu">predict</span>((<span class="fu">lm</span>(Price<span class="sc">~</span> Size <span class="sc">+</span> New, <span class="at">data=</span>house.selling.price)), old2)</span>
<span id="cb48-227"><a href="#cb48-227" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb48-228"><a href="#cb48-228" aria-hidden="true" tabindex="-1"></a>new2 <span class="ot">&lt;-</span> <span class="fu">data.frame</span>(<span class="at">Size=</span><span class="fu">c</span>(<span class="dv">1500</span>), <span class="at">New =</span> <span class="dv">1</span>)</span>
<span id="cb48-229"><a href="#cb48-229" aria-hidden="true" tabindex="-1"></a><span class="fu">predict</span>((<span class="fu">lm</span>(Price<span class="sc">~</span> Size <span class="sc">+</span> New, <span class="at">data=</span>house.selling.price)), new2)</span>
<span id="cb48-230"><a href="#cb48-230" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb48-231"><a href="#cb48-231" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb48-232"><a href="#cb48-232" aria-hidden="true" tabindex="-1"></a>For an older home, the price for a 1500sq home is predicted at 133,966.50. For a new home, the predicted price would be 191,702.80.</span>
<span id="cb48-233"><a href="#cb48-233" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb48-234"><a href="#cb48-234" aria-hidden="true" tabindex="-1"></a>As the size of the home doubles, the predicted price of both the older and newer home increased by the same value of 174,197.40.</span>
<span id="cb48-235"><a href="#cb48-235" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb48-236"><a href="#cb48-236" aria-hidden="true" tabindex="-1"></a><span class="fu">### 3.H</span></span>
<span id="cb48-237"><a href="#cb48-237" aria-hidden="true" tabindex="-1"></a>Do you think the model with interaction or the one without it represents the relationship of size and new to the outcome price? What makes you prefer one model over another?</span>
<span id="cb48-238"><a href="#cb48-238" aria-hidden="true" tabindex="-1"></a>The model that adds whether the home is new rather than multiply by it, is a better model more reflective of the actual rates. </span>
</code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div></div></div></div></div>
</div> <!-- /content -->



</body></html>