<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.2.280">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">

<meta name="author" content="Kalimah Muhammad">
<meta name="dcterms.date" content="2022-11-11">

<title>Final Part 2</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1.6em;
  vertical-align: middle;
}
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
    color: #aaaaaa;
  }
pre.numberSource { margin-left: 3em; border-left: 1px solid #aaaaaa;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
code span.al { color: #ff0000; font-weight: bold; } /* Alert */
code span.an { color: #60a0b0; font-weight: bold; font-style: italic; } /* Annotation */
code span.at { color: #7d9029; } /* Attribute */
code span.bn { color: #40a070; } /* BaseN */
code span.bu { color: #008000; } /* BuiltIn */
code span.cf { color: #007020; font-weight: bold; } /* ControlFlow */
code span.ch { color: #4070a0; } /* Char */
code span.cn { color: #880000; } /* Constant */
code span.co { color: #60a0b0; font-style: italic; } /* Comment */
code span.cv { color: #60a0b0; font-weight: bold; font-style: italic; } /* CommentVar */
code span.do { color: #ba2121; font-style: italic; } /* Documentation */
code span.dt { color: #902000; } /* DataType */
code span.dv { color: #40a070; } /* DecVal */
code span.er { color: #ff0000; font-weight: bold; } /* Error */
code span.ex { } /* Extension */
code span.fl { color: #40a070; } /* Float */
code span.fu { color: #06287e; } /* Function */
code span.im { color: #008000; font-weight: bold; } /* Import */
code span.in { color: #60a0b0; font-weight: bold; font-style: italic; } /* Information */
code span.kw { color: #007020; font-weight: bold; } /* Keyword */
code span.op { color: #666666; } /* Operator */
code span.ot { color: #007020; } /* Other */
code span.pp { color: #bc7a00; } /* Preprocessor */
code span.sc { color: #4070a0; } /* SpecialChar */
code span.ss { color: #bb6688; } /* SpecialString */
code span.st { color: #4070a0; } /* String */
code span.va { color: #19177c; } /* Variable */
code span.vs { color: #4070a0; } /* VerbatimString */
code span.wa { color: #60a0b0; font-weight: bold; font-style: italic; } /* Warning */
</style>


<script src="../site_libs/quarto-nav/quarto-nav.js"></script>
<script src="../site_libs/quarto-nav/headroom.min.js"></script>
<script src="../site_libs/clipboard/clipboard.min.js"></script>
<script src="../site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="../site_libs/quarto-search/fuse.min.js"></script>
<script src="../site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="../">
<link href="../images/DACSS_Round_Network.png" rel="icon" type="image/png">
<script src="../site_libs/quarto-html/quarto.js"></script>
<script src="../site_libs/quarto-html/popper.min.js"></script>
<script src="../site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="../site_libs/quarto-html/anchor.min.js"></script>
<link href="../site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="../site_libs/quarto-html/quarto-syntax-highlighting.css" rel="stylesheet" class="quarto-color-scheme" id="quarto-text-highlighting-styles">
<link href="../site_libs/quarto-html/quarto-syntax-highlighting-dark.css" rel="prefetch" class="quarto-color-scheme quarto-color-alternate" id="quarto-text-highlighting-styles">
<script src="../site_libs/bootstrap/bootstrap.min.js"></script>
<link href="../site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="../site_libs/bootstrap/bootstrap.min.css" rel="stylesheet" class="quarto-color-scheme" id="quarto-bootstrap" data-mode="light">
<link href="../site_libs/bootstrap/bootstrap-dark.min.css" rel="prefetch" class="quarto-color-scheme quarto-color-alternate" id="quarto-bootstrap" data-mode="dark">
<script id="quarto-search-options" type="application/json">{
  "location": "navbar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "end",
  "type": "overlay",
  "limit": 20,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit"
  }
}</script>


<meta name="twitter:title" content="Final Part 2">
<meta name="twitter:description" content="Researchers have examined the differences impacting student achievement among genders for decades.">
<meta name="twitter:creator" content="@UMassDACSS">
<meta name="twitter:site" content="@UMassDACSS">
<meta name="twitter:card" content="summary">
</head>

<body class="nav-fixed">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
    <nav class="navbar navbar-expand-lg navbar-dark ">
      <div class="navbar-container container-fluid">
      <div class="navbar-brand-container">
    <a href="../index.html" class="navbar-brand navbar-brand-logo">
    <img src="../images/UMass White Wordmark Horiz.png" alt="" class="navbar-logo">
    </a>
  </div>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse" aria-controls="navbarCollapse" aria-expanded="false" aria-label="Toggle navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
  <span class="navbar-toggler-icon"></span>
</button>
          <div class="collapse navbar-collapse" id="navbarCollapse">
            <ul class="navbar-nav navbar-nav-scroll ms-auto">
  <li class="nav-item">
    <a class="nav-link" href="https://dacss.github.io/603_Fall_2022/">
 <span class="menu-text">Fall 2022 Posts</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="../about.html">
 <span class="menu-text">Contributors</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="https://umass.edu/sbs/dacss">
 <span class="menu-text">DACSS</span></a>
  </li>  
  <li class="nav-item compact">
    <a class="nav-link" href="https://github.com/DACSS/603_Fall_2022"><i class="bi bi-github" role="img" aria-label="GitHub">
</i> 
 <span class="menu-text"></span></a>
  </li>  
</ul>
              <div class="quarto-toggle-container">
                  <a href="" class="quarto-color-scheme-toggle nav-link" onclick="window.quartoToggleColorScheme(); return false;" title="Toggle dark mode"><i class="bi"></i></a>
              </div>
              <div id="quarto-search" class="" title="Search"></div>
          </div> <!-- /navcollapse -->
      </div> <!-- /container-fluid -->
    </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article page-navbar">
<!-- sidebar -->
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">On this page</h2>
   
  <ul>
  <li><a href="#background" id="toc-background" class="nav-link active" data-scroll-target="#background">Background</a></li>
  <li><a href="#hypotheses" id="toc-hypotheses" class="nav-link" data-scroll-target="#hypotheses">Hypotheses</a></li>
  <li><a href="#data" id="toc-data" class="nav-link" data-scroll-target="#data">Data</a></li>
  <li><a href="#methodology-and-results" id="toc-methodology-and-results" class="nav-link" data-scroll-target="#methodology-and-results">Methodology and Results</a></li>
  </ul>
</nav>
    </div>
<!-- main -->
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<div class="quarto-title-block"><div><h1 class="title">Final Part 2</h1><button type="button" class="btn code-tools-button dropdown-toggle" id="quarto-code-tools-menu" data-bs-toggle="dropdown" aria-expanded="false"><i class="bi"></i> Code</button><ul class="dropdown-menu dropdown-menu-end" aria-labelelledby="quarto-code-tools-menu"><li><a id="quarto-show-all-code" class="dropdown-item" href="javascript:void(0)" role="button">Show All Code</a></li><li><a id="quarto-hide-all-code" class="dropdown-item" href="javascript:void(0)" role="button">Hide All Code</a></li><li><hr class="dropdown-divider"></li><li><a id="quarto-view-source" class="dropdown-item" href="javascript:void(0)" role="button">View Source</a></li></ul></div></div>
  <div class="quarto-categories">
    <div class="quarto-category">finalpt2</div>
    <div class="quarto-category">Kalimah Muhammad</div>
  </div>
  </div>



<div class="quarto-title-meta">

    <div>
    <div class="quarto-title-meta-heading">Author</div>
    <div class="quarto-title-meta-contents">
             <p>Kalimah Muhammad </p>
          </div>
  </div>
    
    <div>
    <div class="quarto-title-meta-heading">Published</div>
    <div class="quarto-title-meta-contents">
      <p class="date">November 11, 2022</p>
    </div>
  </div>
  
    
  </div>
  

</header>

<div class="cell">
<details>
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb1"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(tidyverse)</span>
<span id="cb1-2"><a href="#cb1-2" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(dplyr)</span>
<span id="cb1-3"><a href="#cb1-3" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(ggplot2)</span>
<span id="cb1-4"><a href="#cb1-4" aria-hidden="true" tabindex="-1"></a>performance<span class="ot">&lt;-</span> <span class="fu">read_csv</span>(<span class="st">"_data/CompleteDataAndBiases.csv"</span>)</span>
<span id="cb1-5"><a href="#cb1-5" aria-hidden="true" tabindex="-1"></a>knitr<span class="sc">::</span>opts_chunk<span class="sc">$</span><span class="fu">set</span>(<span class="at">echo =</span> <span class="cn">TRUE</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
</div>
<section id="background" class="level2">
<h2 class="anchored" data-anchor-id="background">Background</h2>
<p>Researchers have examined the differences impacting student achievement among genders for decades. Early meta-analyses conducted by Hyde (1990) revealed no significant difference between the groups’ cognitive abilities; yet intelligence and self-perception of ability, or self-esteem, were determined as the strongest predictors of academic success (Spinath et al., 2010, Booth and Gerard, 2011). Some research explains differences in achievement partially by stereotype threat (ST). Stereotype threat, originally used to research the vulnerability of racial stereotypes on aptitude tests, is defined as “being at risk of confirming, as self-characteristic, a negative stereotype about one’s group” (Steele and Aronson, 1995). Conventional research has focused on gender differences to stereotype threat (Moè &amp; Putwain, 2020), and two prevailing theories have emerged.</p>
<p>The first theory suggests that ST affects male and female students differently. Here male students achieve better outcomes when stereotype threat is present than stereotype lift, and the reverse is true for female students who are adversely impacted by stereotype threat and positively impacted by stereotype lift (Johnson et al., 2012). Other studies debunk this theory suggesting no evidence of ST as a phenomenon in female students (Warne, 2022), particularly in the domain of mathematical achievement (Ganley et al., 2013). A second theory exists that the effects of ST may not be fully realized outcomes immediately but affect achievement over time as chronic ST impacts working memory and intellectual helplessness in girls’ math scores (Bedyńska, Krejtz, and Sedek, 2019) and male language arts scores (Bedyńska, Krejtz, and Sedek, 2020).</p>
</section>
<section id="hypotheses" class="level2">
<h2 class="anchored" data-anchor-id="hypotheses">Hypotheses</h2>
<p>This study tests both theories as an assumption in predicting student achievement based on actual student performance data and predictions based on the participants’ exposure to three types of stereotypes activation:<br>
-No stereotypes,<br>
-Case-based stereotypes where students were shown three student profiles in which one female student had a high grade and two male students had low grades, and<br>
-Statistical stereotypes where students were shown statistics that boys performed less well in school than girls.</p>
<p>Based on this experiment and prior research, I will test the following hypotheses: 1. Does exposure to negative stereotypes about male achievement and positive stereotypes of female achievement result in higher predicted achievement among both male and female students?<br>
2. Is there a statistically significant difference between male and female achievement based on the type of stereotype activation within each group?</p>
<div class="cell">
<details>
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb2"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb2-1"><a href="#cb2-1" aria-hidden="true" tabindex="-1"></a>performance<span class="ot">&lt;-</span> <span class="fu">arrange</span>(performance,(index)) <span class="co">#arrange table by index in ascending order</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
</div>
</section>
<section id="data" class="level2">
<h2 class="anchored" data-anchor-id="data">Data</h2>
<p>Data for this project was collected from Kaggle (Performance vs.&nbsp;Predicted Performance, 2022) and is a collection of existing student performance data from a study by Cortez and Silva (2008) on predicting secondary school student performance and the collector’s addition of stereotype activation for machine learning. The data included information on actual student demographics such as gender, parents’ highest level of education, as well as time studying vs.&nbsp;free time, number of absences, and grade on a final exam, among other variables.</p>
<p>A few important variables to define include:<br>
-Index - number of students included in the original and predicted data (N=856 of the original 991 students)<br>
-Participant ID - number associated with participants making predictions (N=107)<br>
-Sex - student’s sex (binary: ‘F’ - female or ‘M’ - male)<br>
-Studytime - weekly study time is categorized as 1= less than 2 hours, 2= 2-5 hours and 3= 5+ hours<br>
-Freetime - free time after school group as 1 = low, 2= medium, 3 = high<br>
-Goout - how often a student goes out with friends where 1 is very low and 4 is very often<br>
-Absences - number of school absences 1 - 7 where 7 represents any absences equal to or above 7<br>
-Walc - weekend alcohol consumption<br>
-Parents_edu - the higher of original variables mother’s edu and father’s edu, where 4 = the highest level of education<br>
-G3 - final grade (numeric: from 0 to 20)<br>
-Reason - The reason for why a student chose to go to the school in question. The levels are close to home, school’s reputation, school’s curricular and other<br>
-PredictedGrade - the grade participants predicted based on actual data and their exposed level of StereotypeActivation<br>
-StereotypeActivation - see three levels of stereotype activation above<br>
-Pass - A binary variable showing whether G3 is a passing grade (i.e.&nbsp;&gt;=10) or not<br>
-PassFailStrategy - A binary variable showing whether the PredictedGrade is a passing grade (i.e.&nbsp;&gt;=10) or not</p>
<p>Below is a summary of the variables.</p>
<div class="cell">
<details>
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb3"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb3-1"><a href="#cb3-1" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(performance)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>     index       ParticipantID     name               sex           
 Min.   :  1.0   Min.   :  1   Length:856         Length:856        
 1st Qu.:241.8   1st Qu.: 27   Class :character   Class :character  
 Median :487.0   Median : 54   Mode  :character   Mode  :character  
 Mean   :486.9   Mean   : 54                                        
 3rd Qu.:727.2   3rd Qu.: 81                                        
 Max.   :990.0   Max.   :107                                        
   studytime        freetime       romantic              Walc      
 Min.   :1.000   Min.   :1.000   Length:856         Min.   :1.000  
 1st Qu.:1.000   1st Qu.:2.000   Class :character   1st Qu.:1.000  
 Median :2.000   Median :2.000   Mode  :character   Median :2.000  
 Mean   :1.887   Mean   :2.183                      Mean   :2.284  
 3rd Qu.:2.000   3rd Qu.:3.000                      3rd Qu.:3.000  
 Max.   :3.000   Max.   :3.000                      Max.   :4.000  
     goout        Parents_edu       absences        reason         
 Min.   :1.000   Min.   :1.000   Min.   :0.000   Length:856        
 1st Qu.:2.000   1st Qu.:2.000   1st Qu.:0.000   Class :character  
 Median :3.000   Median :3.000   Median :2.000   Mode  :character  
 Mean   :3.022   Mean   :2.854   Mean   :2.794                     
 3rd Qu.:4.000   3rd Qu.:4.000   3rd Qu.:5.000                     
 Max.   :4.000   Max.   :4.000   Max.   :7.000                     
       G3           Pass         PredictedGrade  PredictedRank 
 Min.   : 1.00   Mode :logical   Min.   : 0.00   Min.   :1.00  
 1st Qu.:10.00   FALSE:149       1st Qu.:10.00   1st Qu.:2.75  
 Median :12.00   TRUE :707       Median :14.00   Median :4.50  
 Mean   :11.97                   Mean   :13.14   Mean   :4.50  
 3rd Qu.:14.00                   3rd Qu.:16.00   3rd Qu.:6.25  
 Max.   :20.00                   Max.   :20.00   Max.   :8.00  
 StereotypeActivation Predicted_Pass_PassFailStrategy
 Length:856           Mode :logical                  
 Class :character     FALSE:170                      
 Mode  :character     TRUE :686                      
                                                     
                                                     
                                                     
 Predicted_Pass_RankingStrategy
 Mode :logical                 
 FALSE:284                     
 TRUE :572                     
                               
                               
                               </code></pre>
</div>
</div>
<p>The next two graphs compare the actual final grades vs.&nbsp;the predicted grade for both genders.</p>
<div class="cell">
<details>
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb5"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb5-1"><a href="#cb5-1" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(performance, <span class="fu">aes</span>(<span class="at">x=</span>G3, <span class="at">fill=</span>sex))<span class="sc">+</span> <span class="fu">geom_histogram</span>(<span class="at">position =</span> <span class="st">"dodge"</span>)<span class="sc">+</span><span class="fu">labs</span>(<span class="at">x=</span><span class="st">"Students Actual Final Grade (G3)"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stderr">
<pre><code>`stat_bin()` using `bins = 30`. Pick better value with `binwidth`.</code></pre>
</div>
<div class="cell-output-display">
<p><img src="KalimahMuhammad_finalpart2_files/figure-html/unnamed-chunk-4-1.png" class="img-fluid" width="672"></p>
</div>
<details>
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb7"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb7-1"><a href="#cb7-1" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(performance, <span class="fu">aes</span>(<span class="at">x=</span>PredictedGrade, <span class="at">fill=</span>sex))<span class="sc">+</span> <span class="fu">geom_histogram</span>(<span class="at">position =</span> <span class="st">"dodge"</span>)<span class="sc">+</span><span class="fu">labs</span>(<span class="at">x=</span><span class="st">"Students Predicted Final Grade (PredictedGrade)"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stderr">
<pre><code>`stat_bin()` using `bins = 30`. Pick better value with `binwidth`.</code></pre>
</div>
<div class="cell-output-display">
<p><img src="KalimahMuhammad_finalpart2_files/figure-html/unnamed-chunk-4-2.png" class="img-fluid" width="672"></p>
</div>
</div>
<p>In the first graph, there is a fairly normal distribution of actual grades for both male and female students. Male students are more concentrated near the median value of 10 while female students are skewed slightly higher near the 11 value. However, in the second graph of predicted grades for both groups of students, predicted values are skewed higher than actual. Grade predictions for female students are significantly higher than actual as well as predictions for male students.</p>
<div class="cell">
<details>
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb9"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb9-1"><a href="#cb9-1" aria-hidden="true" tabindex="-1"></a>by_sex<span class="ot">&lt;-</span>performance<span class="sc">%&gt;%</span> <span class="fu">group_by</span>(sex)</span>
<span id="cb9-2"><a href="#cb9-2" aria-hidden="true" tabindex="-1"></a>by_sex<span class="sc">%&gt;%</span> <span class="fu">summarise</span>(<span class="fu">mean</span>(studytime))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 2 × 2
  sex   `mean(studytime)`
  &lt;chr&gt;             &lt;dbl&gt;
1 F                  2.07
2 M                  1.71</code></pre>
</div>
<details>
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb11"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb11-1"><a href="#cb11-1" aria-hidden="true" tabindex="-1"></a>by_sex<span class="sc">%&gt;%</span> <span class="fu">summarise</span>(<span class="fu">mean</span>(freetime))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 2 × 2
  sex   `mean(freetime)`
  &lt;chr&gt;            &lt;dbl&gt;
1 F                 2.07
2 M                 2.30</code></pre>
</div>
<details>
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb13"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb13-1"><a href="#cb13-1" aria-hidden="true" tabindex="-1"></a>by_sex<span class="sc">%&gt;%</span> <span class="fu">summarise</span>(<span class="fu">mean</span>(goout))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 2 × 2
  sex   `mean(goout)`
  &lt;chr&gt;         &lt;dbl&gt;
1 F              2.99
2 M              3.05</code></pre>
</div>
<details>
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb15"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb15-1"><a href="#cb15-1" aria-hidden="true" tabindex="-1"></a>by_sex<span class="sc">%&gt;%</span> <span class="fu">summarise</span>(<span class="fu">mean</span>(absences))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 2 × 2
  sex   `mean(absences)`
  &lt;chr&gt;            &lt;dbl&gt;
1 F                 2.70
2 M                 2.89</code></pre>
</div>
<details>
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb17"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb17-1"><a href="#cb17-1" aria-hidden="true" tabindex="-1"></a>by_sex<span class="sc">%&gt;%</span> <span class="fu">summarise</span>(<span class="fu">mean</span>(G3))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 2 × 2
  sex   `mean(G3)`
  &lt;chr&gt;      &lt;dbl&gt;
1 F           12.1
2 M           11.8</code></pre>
</div>
<details>
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb19"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb19-1"><a href="#cb19-1" aria-hidden="true" tabindex="-1"></a>by_sex<span class="sc">%&gt;%</span> <span class="fu">summarise</span>(<span class="fu">mean</span>(PredictedGrade))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 2 × 2
  sex   `mean(PredictedGrade)`
  &lt;chr&gt;                  &lt;dbl&gt;
1 F                       14.0
2 M                       12.3</code></pre>
</div>
</div>
<p>The above tables summarize differences in the mean values for several variables of interest by gender. Here we see, female students score slightly higher in study time (2.07 vs.&nbsp;1.7) and while lower in free time (2.07 vs, 2.3), goout (3 vs.&nbsp;3.05), absences (2.7 vs.&nbsp;2.9). These would suggest female students may have a slightly higher grade based on good practices which is proven by the actual grades in G3 (12.15 vs.&nbsp;11.80). However, the larger discrepancies in predicted rages (14.0 for females vs.&nbsp;12.28 for males) may be attributed to the stereotype activation.</p>
<p>Additionally we can perform a t-test on both male and female actual and predicted score.</p>
<div class="cell">
<details>
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb21"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb21-1"><a href="#cb21-1" aria-hidden="true" tabindex="-1"></a><span class="co">#create two tables for female students and male students</span></span>
<span id="cb21-2"><a href="#cb21-2" aria-hidden="true" tabindex="-1"></a>f_performance<span class="ot">&lt;-</span>performance<span class="sc">%&gt;%</span></span>
<span id="cb21-3"><a href="#cb21-3" aria-hidden="true" tabindex="-1"></a><span class="fu">filter</span>(sex<span class="sc">==</span><span class="st">"F"</span>) </span>
<span id="cb21-4"><a href="#cb21-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb21-5"><a href="#cb21-5" aria-hidden="true" tabindex="-1"></a>m_performance<span class="ot">&lt;-</span>performance<span class="sc">%&gt;%</span></span>
<span id="cb21-6"><a href="#cb21-6" aria-hidden="true" tabindex="-1"></a><span class="fu">filter</span>(sex<span class="sc">==</span><span class="st">"M"</span>) </span>
<span id="cb21-7"><a href="#cb21-7" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb21-8"><a href="#cb21-8" aria-hidden="true" tabindex="-1"></a><span class="fu">t.test</span>(f_performance<span class="sc">$</span>G3)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>
    One Sample t-test

data:  f_performance$G3
t = 87.488, df = 427, p-value &lt; 2.2e-16
alternative hypothesis: true mean is not equal to 0
95 percent confidence interval:
 11.87658 12.42249
sample estimates:
mean of x 
 12.14953 </code></pre>
</div>
<details>
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb23"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb23-1"><a href="#cb23-1" aria-hidden="true" tabindex="-1"></a><span class="fu">t.test</span>(m_performance<span class="sc">$</span>G3)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>
    One Sample t-test

data:  m_performance$G3
t = 83.481, df = 427, p-value &lt; 2.2e-16
alternative hypothesis: true mean is not equal to 0
95 percent confidence interval:
 11.51670 12.07209
sample estimates:
mean of x 
 11.79439 </code></pre>
</div>
<details>
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb25"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb25-1"><a href="#cb25-1" aria-hidden="true" tabindex="-1"></a><span class="fu">t.test</span>(f_performance<span class="sc">$</span>PredictedGrade)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>
    One Sample t-test

data:  f_performance$PredictedGrade
t = 77.636, df = 427, p-value &lt; 2.2e-16
alternative hypothesis: true mean is not equal to 0
95 percent confidence interval:
 13.66150 14.37121
sample estimates:
mean of x 
 14.01636 </code></pre>
</div>
<details>
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb27"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb27-1"><a href="#cb27-1" aria-hidden="true" tabindex="-1"></a><span class="fu">t.test</span>(m_performance<span class="sc">$</span>PredictedGrade)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>
    One Sample t-test

data:  m_performance$PredictedGrade
t = 61.908, df = 427, p-value &lt; 2.2e-16
alternative hypothesis: true mean is not equal to 0
95 percent confidence interval:
 11.88369 12.66304
sample estimates:
mean of x 
 12.27336 </code></pre>
</div>
</div>
<p>Based on the above tests, we can say with a 95% confidence that the following groups have the following means:<br>
Actual female grade - 12.14953<br>
Predicted female grade - 14.01636<br>
Actual male grade - 11.79439<br>
Predicted male grade - 12.27336</p>
<p>The graph below calculates the mean predicted grade for both groups based on the type of stereotype activation.</p>
<div class="cell">
<details>
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb29"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb29-1"><a href="#cb29-1" aria-hidden="true" tabindex="-1"></a>performance<span class="sc">%&gt;%</span></span>
<span id="cb29-2"><a href="#cb29-2" aria-hidden="true" tabindex="-1"></a><span class="fu">group_by</span>(sex, StereotypeActivation)<span class="sc">%&gt;%</span></span>
<span id="cb29-3"><a href="#cb29-3" aria-hidden="true" tabindex="-1"></a><span class="fu">summarise</span>(<span class="fu">mean</span>(PredictedGrade))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stderr">
<pre><code>`summarise()` has grouped output by 'sex'. You can override using the `.groups`
argument.</code></pre>
</div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 6 × 3
# Groups:   sex [2]
  sex   StereotypeActivation `mean(PredictedGrade)`
  &lt;chr&gt; &lt;chr&gt;                                 &lt;dbl&gt;
1 F     CaseBased                              13.4
2 F     None                                   14.1
3 F     Statistics                             14.5
4 M     CaseBased                              12.0
5 M     None                                   12.7
6 M     Statistics                             12.2</code></pre>
</div>
</div>
<p>In the cross tabulation above, participants predicted the grade of female students 1 - 2.35 points higher than the average actual female performance (12.15). For male students, predictions were closer to the average actual performance (11.80) ranging at a difference of 0.16 - 0.88 points. With no stereotype activation, males students garnered their highest predicted average at 12.68 suggesting introducing stereotypes negatively affected predictions in male students although still higher than actual performance. For female students, introducing statistics of lower male performance garnered the highest grade prediction for female students. For both genders, case based stereotype activation which included one example of a high female score and two examples of lower male scores produced the lowest predicted grades.</p>
<p>This may suggest that other variables in the study having an influential role in predicting scores outside of stereotype activation.</p>
</section>
<section id="methodology-and-results" class="level2">
<h2 class="anchored" data-anchor-id="methodology-and-results">Methodology and Results</h2>
<p>To test my hypotheses, I will examine if the predicted grade was higher or lower than the actual grade among the genders controlling for various types of stereotype activation. Here the response variable is the predicted grade, and the explanatory variables are the types of gender as controlled by the exposure of the types of stereotype activation.</p>
<ol type="1">
<li><p>Does exposure to negative stereotypes about male achievement and positive stereotypes of female achievement result in higher predicted achievement among both male and female students?<br>
Based on the cross tabulation above, exposure to negative statistics of male performance, resulted in the highest prediction for female grades even more than no stereotype exposure. However, those same statistics resulted in lower prediction of male grades than no stereotype exposure.</p></li>
<li><p>Is there a statistically significant difference between male and female achievement based on the type of stereotype activation within each group?</p></li>
</ol>
<div class="cell">
<details>
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb32"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb32-1"><a href="#cb32-1" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(<span class="fu">lm</span>(PredictedGrade <span class="sc">~</span> StereotypeActivation, <span class="at">data=</span>f_performance))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = PredictedGrade ~ StereotypeActivation, data = f_performance)

Residuals:
    Min      1Q  Median      3Q     Max 
-13.404  -2.500   0.500   2.939   6.596 

Coefficients:
                               Estimate Std. Error t value Pr(&gt;|t|)    
(Intercept)                     13.4044     0.3186  42.068   &lt;2e-16 ***
StereotypeActivationNone         0.6562     0.4540   1.445   0.1491    
StereotypeActivationStatistics   1.0956     0.4334   2.528   0.0118 *  
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 3.716 on 425 degrees of freedom
Multiple R-squared:  0.01488,   Adjusted R-squared:  0.01024 
F-statistic: 3.209 on 2 and 425 DF,  p-value: 0.04138</code></pre>
</div>
<details>
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb34"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb34-1"><a href="#cb34-1" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(<span class="fu">lm</span>(PredictedGrade <span class="sc">~</span> StereotypeActivation, <span class="at">data=</span>m_performance))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = PredictedGrade ~ StereotypeActivation, data = m_performance)

Residuals:
    Min      1Q  Median      3Q     Max 
-9.2000 -3.2000  0.0368  3.0368  8.0368 

Coefficients:
                               Estimate Std. Error t value Pr(&gt;|t|)    
(Intercept)                     11.9632     0.3516  34.021   &lt;2e-16 ***
StereotypeActivationNone         0.7186     0.5010   1.434    0.152    
StereotypeActivationStatistics   0.2368     0.4783   0.495    0.621    
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 4.101 on 425 degrees of freedom
Multiple R-squared:  0.005007,  Adjusted R-squared:  0.0003245 
F-statistic: 1.069 on 2 and 425 DF,  p-value: 0.3442</code></pre>
</div>
</div>
<p>Here, there appears that activating stereotype statistics resulted in a statistically significant difference in prediction of female grades. For predictions in male students, case based stereotypes resulted in the lowest predictions.</p>
<div class="cell">
<details>
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb36"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb36-1"><a href="#cb36-1" aria-hidden="true" tabindex="-1"></a>performance_fit<span class="ot">&lt;-</span><span class="fu">lm</span>(PredictedGrade <span class="sc">~</span> StereotypeActivation<span class="sc">*</span>sex, <span class="at">data=</span>performance)</span>
<span id="cb36-2"><a href="#cb36-2" aria-hidden="true" tabindex="-1"></a>performance_fit</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = PredictedGrade ~ StereotypeActivation * sex, data = performance)

Coefficients:
                        (Intercept)             StereotypeActivationNone  
                           13.40441                              0.65619  
     StereotypeActivationStatistics                                 sexM  
                            1.09559                             -1.44118  
      StereotypeActivationNone:sexM  StereotypeActivationStatistics:sexM  
                            0.06239                             -0.85882  </code></pre>
</div>
<details>
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb38"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb38-1"><a href="#cb38-1" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(performance_fit) <span class="co">#fit based on gender, predicted grade, and stereotype activation</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = PredictedGrade ~ StereotypeActivation * sex, data = performance)

Residuals:
     Min       1Q   Median       3Q      Max 
-13.4044  -2.9632   0.4091   3.0368   8.0368 

Coefficients:
                                    Estimate Std. Error t value Pr(&gt;|t|)    
(Intercept)                         13.40441    0.33554  39.948  &lt; 2e-16 ***
StereotypeActivationNone             0.65619    0.47811   1.372  0.17028    
StereotypeActivationStatistics       1.09559    0.45639   2.401  0.01658 *  
sexM                                -1.44118    0.47453  -3.037  0.00246 ** 
StereotypeActivationNone:sexM        0.06239    0.67615   0.092  0.92651    
StereotypeActivationStatistics:sexM -0.85882    0.64543  -1.331  0.18367    
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 3.913 on 850 degrees of freedom
Multiple R-squared:  0.05618,   Adjusted R-squared:  0.05063 
F-statistic: 10.12 on 5 and 850 DF,  p-value: 1.989e-09</code></pre>
</div>
</div>
<p>When adding gender as an interacting variables, r-squared and the adjusted r-squared increased and we find a statistically significant result for male grades predicted after exposure to case based stereotypes.</p>
<section id="sources" class="level4">
<h4 class="anchored" data-anchor-id="sources">Sources</h4>
<p>Bedyńska, S., Krejtz, I. &amp; Sedek, G. Chronic stereotype threat and mathematical achievement in age cohorts of secondary school girls: mediational role of working memory, and intellectual helplessness. Soc Psychol Educ 22, 321–335 (2019). https://doi.org/10.1007/s11218-019-09478-6</p>
<p>Bedyńska, S., Krejtz, I., Rycielski, P. et al.&nbsp;Stereotype threat as an antecedent to domain identification and achievement in language arts in boys: a cross-sectional study. Soc Psychol Educ 23, 755–771 (2020). https://doi.org/10.1007/s11218-020-09557-z</p>
<p>Booth MZ, Gerard JM. Self-esteem and academic achievement: a comparative study of adolescent students in England and the United States. Compare. 2011 Sep;41(5):629-648. doi: 10.1080/03057925.2011.566688</p>
<p>Cortez, P. and Silva, A. Using Data Mining to Predict Secondary School Student Performance. In A. Brito and J. Teixeira Eds., Proceedings of 5th FUture BUsiness TEChnology Conference (FUBUTEC 2008) pp.&nbsp;5-12, Porto, Portugal, April, 2008, EUROSIS, ISBN 978-9077381-39-7</p>
<p>Ganley, C. M., Mingle, L. A., Ryan, A. M., Ryan, K., Vasilyeva, M., &amp; Perry, M. (2013). An examination of stereotype threat effects on girls’ mathematics performance. Developmental Psychology, 49(10), 1886–1897. https://doi.org/10.1037/a0031412</p>
<p>Hyde, Janet Shibley. “Meta-analysis and the psychology of gender differences.” Signs: Journal of Women in Culture and Society 16.1 (1990): 55-73.</p>
<p>Johnson, H., Barnard-Brak, L., Saxon, T., &amp; Johnson, M.K. (2012) An Experimental Study of the Effects of Stereotype Threat and Stereotype Lift on Men and Women’s Performance in Mathematics, The Journal of Experimental Education, 80:2, 137-149, DOI: 10.1080/00220973.2011.567312</p>
<p>Moè, A., &amp; Putwain, D. W. (2020). An evaluative message fosters mathematics performance in male students but decreases intrinsic motivation in female students. Educational Psychology, 1–20. https://doi.org/10.1080/01443410.2020.1730767</p>
<p>Spinath, B., Harald Freudenthaler, H., &amp; Neubauer, A. C. (2010). Domain-specific school achievement in boys and girls as predicted by intelligence, personality and motivation. Personality and Individual Differences, 48(4), 481-486. https://doi.org/10.1016/j.paid.2009.11.028</p>
<p>Steele, Claude M., and Joshua Aronson. “Stereotype threat and the intellectual test performance of African Americans.” Journal of personality and social psychology 69.5 (1995): 797.</p>
<p>Warne, R. T. (2022). No Strong Evidence of Stereotype Threat in Females: A Reassessment of the Meta-Analysis. Journal of Advanced Academics, 33(2), 171–186. https://doi.org/10.1177/1932202X211061517</p>
<p>Data source: Anonymous. (2022). <i>Performance vs.&nbsp;Predicted Performance</i> [Data set]. Kaggle. https://doi.org/10.34740/KAGGLE/DSV/4282405</p>


<!-- -->

</section>
</section>

</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const disableStylesheet = (stylesheets) => {
    for (let i=0; i < stylesheets.length; i++) {
      const stylesheet = stylesheets[i];
      stylesheet.rel = 'prefetch';
    }
  }
  const enableStylesheet = (stylesheets) => {
    for (let i=0; i < stylesheets.length; i++) {
      const stylesheet = stylesheets[i];
      stylesheet.rel = 'stylesheet';
    }
  }
  const manageTransitions = (selector, allowTransitions) => {
    const els = window.document.querySelectorAll(selector);
    for (let i=0; i < els.length; i++) {
      const el = els[i];
      if (allowTransitions) {
        el.classList.remove('notransition');
      } else {
        el.classList.add('notransition');
      }
    }
  }
  const toggleColorMode = (alternate) => {
    // Switch the stylesheets
    const alternateStylesheets = window.document.querySelectorAll('link.quarto-color-scheme.quarto-color-alternate');
    manageTransitions('#quarto-margin-sidebar .nav-link', false);
    if (alternate) {
      enableStylesheet(alternateStylesheets);
      for (const sheetNode of alternateStylesheets) {
        if (sheetNode.id === "quarto-bootstrap") {
          toggleBodyColorMode(sheetNode);
        }
      }
    } else {
      disableStylesheet(alternateStylesheets);
      toggleBodyColorPrimary();
    }
    manageTransitions('#quarto-margin-sidebar .nav-link', true);
    // Switch the toggles
    const toggles = window.document.querySelectorAll('.quarto-color-scheme-toggle');
    for (let i=0; i < toggles.length; i++) {
      const toggle = toggles[i];
      if (toggle) {
        if (alternate) {
          toggle.classList.add("alternate");     
        } else {
          toggle.classList.remove("alternate");
        }
      }
    }
    // Hack to workaround the fact that safari doesn't
    // properly recolor the scrollbar when toggling (#1455)
    if (navigator.userAgent.indexOf('Safari') > 0 && navigator.userAgent.indexOf('Chrome') == -1) {
      manageTransitions("body", false);
      window.scrollTo(0, 1);
      setTimeout(() => {
        window.scrollTo(0, 0);
        manageTransitions("body", true);
      }, 40);  
    }
  }
  const isFileUrl = () => { 
    return window.location.protocol === 'file:';
  }
  const hasAlternateSentinel = () => {  
    let styleSentinel = getColorSchemeSentinel();
    if (styleSentinel !== null) {
      return styleSentinel === "alternate";
    } else {
      return false;
    }
  }
  const setStyleSentinel = (alternate) => {
    const value = alternate ? "alternate" : "default";
    if (!isFileUrl()) {
      window.localStorage.setItem("quarto-color-scheme", value);
    } else {
      localAlternateSentinel = value;
    }
  }
  const getColorSchemeSentinel = () => {
    if (!isFileUrl()) {
      const storageValue = window.localStorage.getItem("quarto-color-scheme");
      return storageValue != null ? storageValue : localAlternateSentinel;
    } else {
      return localAlternateSentinel;
    }
  }
  let localAlternateSentinel = 'default';
  // Dark / light mode switch
  window.quartoToggleColorScheme = () => {
    // Read the current dark / light value 
    let toAlternate = !hasAlternateSentinel();
    toggleColorMode(toAlternate);
    setStyleSentinel(toAlternate);
  };
  // Ensure there is a toggle, if there isn't float one in the top right
  if (window.document.querySelector('.quarto-color-scheme-toggle') === null) {
    const a = window.document.createElement('a');
    a.classList.add('top-right');
    a.classList.add('quarto-color-scheme-toggle');
    a.href = "";
    a.onclick = function() { try { window.quartoToggleColorScheme(); } catch {} return false; };
    const i = window.document.createElement("i");
    i.classList.add('bi');
    a.appendChild(i);
    window.document.body.appendChild(a);
  }
  // Switch to dark mode if need be
  if (hasAlternateSentinel()) {
    toggleColorMode(true);
  } else {
    toggleColorMode(false);
  }
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const clipboard = new window.ClipboardJS('.code-copy-button', {
    target: function(trigger) {
      return trigger.previousElementSibling;
    }
  });
  clipboard.on('success', function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copied!");
    let tooltip;
    if (window.bootstrap) {
      button.setAttribute("data-bs-toggle", "tooltip");
      button.setAttribute("data-bs-placement", "left");
      button.setAttribute("data-bs-title", "Copied!");
      tooltip = new bootstrap.Tooltip(button, 
        { trigger: "manual", 
          customClass: "code-copy-button-tooltip",
          offset: [0, -8]});
      tooltip.show();    
    }
    setTimeout(function() {
      if (tooltip) {
        tooltip.hide();
        button.removeAttribute("data-bs-title");
        button.removeAttribute("data-bs-toggle");
        button.removeAttribute("data-bs-placement");
      }
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  });
  const viewSource = window.document.getElementById('quarto-view-source') ||
                     window.document.getElementById('quarto-code-tools-source');
  if (viewSource) {
    const sourceUrl = viewSource.getAttribute("data-quarto-source-url");
    viewSource.addEventListener("click", function(e) {
      if (sourceUrl) {
        // rstudio viewer pane
        if (/\bcapabilities=\b/.test(window.location)) {
          window.open(sourceUrl);
        } else {
          window.location.href = sourceUrl;
        }
      } else {
        const modal = new bootstrap.Modal(document.getElementById('quarto-embedded-source-code-modal'));
        modal.show();
      }
      return false;
    });
  }
  function toggleCodeHandler(show) {
    return function(e) {
      const detailsSrc = window.document.querySelectorAll(".cell > details > .sourceCode");
      for (let i=0; i<detailsSrc.length; i++) {
        const details = detailsSrc[i].parentElement;
        if (show) {
          details.open = true;
        } else {
          details.removeAttribute("open");
        }
      }
      const cellCodeDivs = window.document.querySelectorAll(".cell > .sourceCode");
      const fromCls = show ? "hidden" : "unhidden";
      const toCls = show ? "unhidden" : "hidden";
      for (let i=0; i<cellCodeDivs.length; i++) {
        const codeDiv = cellCodeDivs[i];
        if (codeDiv.classList.contains(fromCls)) {
          codeDiv.classList.remove(fromCls);
          codeDiv.classList.add(toCls);
        } 
      }
      return false;
    }
  }
  const hideAllCode = window.document.getElementById("quarto-hide-all-code");
  if (hideAllCode) {
    hideAllCode.addEventListener("click", toggleCodeHandler(false));
  }
  const showAllCode = window.document.getElementById("quarto-show-all-code");
  if (showAllCode) {
    showAllCode.addEventListener("click", toggleCodeHandler(true));
  }
  function tippyHover(el, contentFn) {
    const config = {
      allowHTML: true,
      content: contentFn,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start'
    };
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      return note.innerHTML;
    });
  }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
});
</script>
<script src="https://giscus.app/client.js" data-repo="DACSS/603_Fall_2022" data-repo-id="R_kgDOH568kA" data-category="Announcements" data-category-id="" data-mapping="title" data-reactions-enabled="1" data-emit-metadata="0" data-input-position="top" data-theme="light" data-lang="en" crossorigin="anonymous" async="">
</script><div class="modal fade" id="quarto-embedded-source-code-modal" tabindex="-1" aria-labelledby="quarto-embedded-source-code-modal-label" aria-hidden="true"><div class="modal-dialog modal-dialog-scrollable"><div class="modal-content"><div class="modal-header"><h5 class="modal-title" id="quarto-embedded-source-code-modal-label">Source Code</h5><button class="btn-close" data-bs-dismiss="modal"></button></div><div class="modal-body"><div class="">
<div class="sourceCode" id="cb40" data-shortcodes="false"><pre class="sourceCode markdown code-with-copy"><code class="sourceCode markdown"><span id="cb40-1"><a href="#cb40-1" aria-hidden="true" tabindex="-1"></a><span class="co">---</span></span>
<span id="cb40-2"><a href="#cb40-2" aria-hidden="true" tabindex="-1"></a><span class="an">title:</span><span class="co"> "Final Part 2"</span></span>
<span id="cb40-3"><a href="#cb40-3" aria-hidden="true" tabindex="-1"></a><span class="an">author:</span><span class="co"> "Kalimah Muhammad"</span></span>
<span id="cb40-4"><a href="#cb40-4" aria-hidden="true" tabindex="-1"></a><span class="an">desription:</span><span class="co"> "Final Part 2: Analyses"</span></span>
<span id="cb40-5"><a href="#cb40-5" aria-hidden="true" tabindex="-1"></a><span class="an">date:</span><span class="co"> "11/11/2022"</span></span>
<span id="cb40-6"><a href="#cb40-6" aria-hidden="true" tabindex="-1"></a><span class="an">format:</span></span>
<span id="cb40-7"><a href="#cb40-7" aria-hidden="true" tabindex="-1"></a><span class="co">  html:</span></span>
<span id="cb40-8"><a href="#cb40-8" aria-hidden="true" tabindex="-1"></a><span class="co">    toc: true</span></span>
<span id="cb40-9"><a href="#cb40-9" aria-hidden="true" tabindex="-1"></a><span class="co">    code-fold: true</span></span>
<span id="cb40-10"><a href="#cb40-10" aria-hidden="true" tabindex="-1"></a><span class="co">    code-copy: true</span></span>
<span id="cb40-11"><a href="#cb40-11" aria-hidden="true" tabindex="-1"></a><span class="co">    code-tools: true</span></span>
<span id="cb40-12"><a href="#cb40-12" aria-hidden="true" tabindex="-1"></a><span class="an">categories:</span></span>
<span id="cb40-13"><a href="#cb40-13" aria-hidden="true" tabindex="-1"></a><span class="co">  - finalpt2</span></span>
<span id="cb40-14"><a href="#cb40-14" aria-hidden="true" tabindex="-1"></a><span class="co">  - Kalimah Muhammad</span></span>
<span id="cb40-15"><a href="#cb40-15" aria-hidden="true" tabindex="-1"></a><span class="co">---</span></span>
<span id="cb40-16"><a href="#cb40-16" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb40-19"><a href="#cb40-19" aria-hidden="true" tabindex="-1"></a><span class="in">```{r}</span></span>
<span id="cb40-20"><a href="#cb40-20" aria-hidden="true" tabindex="-1"></a><span class="co">#| label: setup</span></span>
<span id="cb40-21"><a href="#cb40-21" aria-hidden="true" tabindex="-1"></a><span class="co">#| warning: false</span></span>
<span id="cb40-22"><a href="#cb40-22" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb40-23"><a href="#cb40-23" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(tidyverse)</span>
<span id="cb40-24"><a href="#cb40-24" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(dplyr)</span>
<span id="cb40-25"><a href="#cb40-25" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(ggplot2)</span>
<span id="cb40-26"><a href="#cb40-26" aria-hidden="true" tabindex="-1"></a>performance<span class="ot">&lt;-</span> <span class="fu">read_csv</span>(<span class="st">"_data/CompleteDataAndBiases.csv"</span>)</span>
<span id="cb40-27"><a href="#cb40-27" aria-hidden="true" tabindex="-1"></a>knitr<span class="sc">::</span>opts_chunk<span class="sc">$</span><span class="fu">set</span>(<span class="at">echo =</span> <span class="cn">TRUE</span>)</span>
<span id="cb40-28"><a href="#cb40-28" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb40-29"><a href="#cb40-29" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb40-30"><a href="#cb40-30" aria-hidden="true" tabindex="-1"></a><span class="fu">## Background</span></span>
<span id="cb40-31"><a href="#cb40-31" aria-hidden="true" tabindex="-1"></a>Researchers have examined the differences impacting student achievement among genders for decades. Early meta-analyses conducted by Hyde (1990) revealed no significant difference between the groups’ cognitive abilities; yet intelligence and self-perception of ability, or self-esteem, were determined as the strongest predictors of academic success (Spinath et al., 2010, Booth and Gerard, 2011). Some research explains differences in achievement partially by stereotype threat (ST). Stereotype threat, originally used to research the vulnerability of racial stereotypes on aptitude tests, is defined as “being at risk of confirming, as self-characteristic, a negative stereotype about one's group” (Steele and Aronson, 1995). Conventional research has focused on gender differences to stereotype threat (Moè &amp; Putwain, 2020), and two prevailing theories have emerged. </span>
<span id="cb40-32"><a href="#cb40-32" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb40-33"><a href="#cb40-33" aria-hidden="true" tabindex="-1"></a>The first theory suggests that ST affects male and female students differently. Here male students achieve better outcomes when stereotype threat is present than stereotype lift, and the reverse is true for female students who are adversely impacted by stereotype threat and positively impacted by stereotype lift (Johnson et al., 2012). Other studies debunk this theory suggesting no evidence of ST as a phenomenon in female students (Warne, 2022), particularly in the domain of mathematical achievement (Ganley et al., 2013). A second theory exists that the effects of ST may not be fully realized outcomes immediately but affect achievement over time as chronic ST impacts working memory and intellectual helplessness in girls’ math scores (Bedyńska, Krejtz, and Sedek, 2019) and male language arts scores (Bedyńska, Krejtz, and Sedek, 2020). </span>
<span id="cb40-34"><a href="#cb40-34" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb40-35"><a href="#cb40-35" aria-hidden="true" tabindex="-1"></a><span class="fu">## Hypotheses  </span></span>
<span id="cb40-36"><a href="#cb40-36" aria-hidden="true" tabindex="-1"></a>This study tests both theories as an assumption in predicting student achievement based on actual student performance data and predictions based on the participants' exposure to three types of stereotypes activation:  </span>
<span id="cb40-37"><a href="#cb40-37" aria-hidden="true" tabindex="-1"></a>-No stereotypes,    </span>
<span id="cb40-38"><a href="#cb40-38" aria-hidden="true" tabindex="-1"></a>-Case-based stereotypes where students were shown three student profiles in which one female student had a high grade and two male students had low grades, and    </span>
<span id="cb40-39"><a href="#cb40-39" aria-hidden="true" tabindex="-1"></a>-Statistical stereotypes where students were shown statistics that boys performed less well in school than girls.   </span>
<span id="cb40-40"><a href="#cb40-40" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb40-41"><a href="#cb40-41" aria-hidden="true" tabindex="-1"></a>Based on this experiment and prior research, I will test the following hypotheses:</span>
<span id="cb40-42"><a href="#cb40-42" aria-hidden="true" tabindex="-1"></a><span class="ss">1. </span>Does exposure to negative stereotypes about male achievement and positive stereotypes of female achievement result in higher predicted achievement among both male and female students?   </span>
<span id="cb40-43"><a href="#cb40-43" aria-hidden="true" tabindex="-1"></a><span class="ss">2. </span>Is there a statistically significant difference between male and female achievement based on the type of stereotype activation within each group?  </span>
<span id="cb40-44"><a href="#cb40-44" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb40-47"><a href="#cb40-47" aria-hidden="true" tabindex="-1"></a><span class="in">```{r}</span></span>
<span id="cb40-48"><a href="#cb40-48" aria-hidden="true" tabindex="-1"></a>performance<span class="ot">&lt;-</span> <span class="fu">arrange</span>(performance,(index)) <span class="co">#arrange table by index in ascending order</span></span>
<span id="cb40-49"><a href="#cb40-49" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb40-50"><a href="#cb40-50" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb40-51"><a href="#cb40-51" aria-hidden="true" tabindex="-1"></a><span class="fu">## Data</span></span>
<span id="cb40-52"><a href="#cb40-52" aria-hidden="true" tabindex="-1"></a>Data for this project was collected from Kaggle (Performance vs. Predicted Performance, 2022) and is a collection of existing student performance data from a study by Cortez and Silva (2008) on predicting secondary school student performance and the collector’s addition of stereotype activation for machine learning. The data included information on actual student demographics such as gender, parents' highest level of education, as well as time studying vs. free time, number of absences, and grade on a final exam, among other variables.</span>
<span id="cb40-53"><a href="#cb40-53" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb40-54"><a href="#cb40-54" aria-hidden="true" tabindex="-1"></a>A few important variables to define include:  </span>
<span id="cb40-55"><a href="#cb40-55" aria-hidden="true" tabindex="-1"></a>-Index - number of students included in the original and predicted data (N=856 of the original 991 students)  </span>
<span id="cb40-56"><a href="#cb40-56" aria-hidden="true" tabindex="-1"></a>-Participant ID - number associated with participants making predictions (N=107)  </span>
<span id="cb40-57"><a href="#cb40-57" aria-hidden="true" tabindex="-1"></a>-Sex - student's sex (binary: 'F' - female or 'M' - male)  </span>
<span id="cb40-58"><a href="#cb40-58" aria-hidden="true" tabindex="-1"></a>-Studytime - weekly study time is categorized as 1= less than 2 hours, 2= 2-5 hours and 3= 5+ hours  </span>
<span id="cb40-59"><a href="#cb40-59" aria-hidden="true" tabindex="-1"></a>-Freetime - free time after school group as 1 = low, 2= medium, 3 = high  </span>
<span id="cb40-60"><a href="#cb40-60" aria-hidden="true" tabindex="-1"></a>-Goout - how often a student goes out with friends where 1 is very low and 4 is very often  </span>
<span id="cb40-61"><a href="#cb40-61" aria-hidden="true" tabindex="-1"></a>-Absences - number of school absences 1 - 7 where 7 represents any absences equal to or above 7  </span>
<span id="cb40-62"><a href="#cb40-62" aria-hidden="true" tabindex="-1"></a>-Walc - weekend alcohol consumption  </span>
<span id="cb40-63"><a href="#cb40-63" aria-hidden="true" tabindex="-1"></a>-Parents_edu - the higher of original variables mother's edu and father's edu, where 4 = the highest level of education  </span>
<span id="cb40-64"><a href="#cb40-64" aria-hidden="true" tabindex="-1"></a>-G3 - final grade (numeric: from 0 to 20)   </span>
<span id="cb40-65"><a href="#cb40-65" aria-hidden="true" tabindex="-1"></a>-Reason - The reason for why a student chose to go to the school in question. The levels are close to home, school's reputation, school's curricular and other  </span>
<span id="cb40-66"><a href="#cb40-66" aria-hidden="true" tabindex="-1"></a>-PredictedGrade - the grade participants predicted based on actual data and their exposed level of StereotypeActivation  </span>
<span id="cb40-67"><a href="#cb40-67" aria-hidden="true" tabindex="-1"></a>-StereotypeActivation - see three levels of stereotype activation above  </span>
<span id="cb40-68"><a href="#cb40-68" aria-hidden="true" tabindex="-1"></a>-Pass - A binary variable showing whether G3 is a passing grade (i.e. &gt;=10) or not  </span>
<span id="cb40-69"><a href="#cb40-69" aria-hidden="true" tabindex="-1"></a>-PassFailStrategy - A binary variable showing whether the PredictedGrade is a passing grade (i.e. &gt;=10) or not  </span>
<span id="cb40-70"><a href="#cb40-70" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb40-71"><a href="#cb40-71" aria-hidden="true" tabindex="-1"></a>Below is a summary of the variables.  </span>
<span id="cb40-72"><a href="#cb40-72" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb40-75"><a href="#cb40-75" aria-hidden="true" tabindex="-1"></a><span class="in">```{r}</span></span>
<span id="cb40-76"><a href="#cb40-76" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(performance)</span>
<span id="cb40-77"><a href="#cb40-77" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb40-78"><a href="#cb40-78" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb40-79"><a href="#cb40-79" aria-hidden="true" tabindex="-1"></a>The next two graphs compare the actual final grades vs. the predicted grade for both genders.  </span>
<span id="cb40-80"><a href="#cb40-80" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb40-83"><a href="#cb40-83" aria-hidden="true" tabindex="-1"></a><span class="in">```{r}</span></span>
<span id="cb40-84"><a href="#cb40-84" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(performance, <span class="fu">aes</span>(<span class="at">x=</span>G3, <span class="at">fill=</span>sex))<span class="sc">+</span> <span class="fu">geom_histogram</span>(<span class="at">position =</span> <span class="st">"dodge"</span>)<span class="sc">+</span><span class="fu">labs</span>(<span class="at">x=</span><span class="st">"Students Actual Final Grade (G3)"</span>)</span>
<span id="cb40-85"><a href="#cb40-85" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(performance, <span class="fu">aes</span>(<span class="at">x=</span>PredictedGrade, <span class="at">fill=</span>sex))<span class="sc">+</span> <span class="fu">geom_histogram</span>(<span class="at">position =</span> <span class="st">"dodge"</span>)<span class="sc">+</span><span class="fu">labs</span>(<span class="at">x=</span><span class="st">"Students Predicted Final Grade (PredictedGrade)"</span>)</span>
<span id="cb40-86"><a href="#cb40-86" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb40-87"><a href="#cb40-87" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb40-88"><a href="#cb40-88" aria-hidden="true" tabindex="-1"></a>In the first graph, there is a fairly normal distribution of actual grades for both male and female students. Male students are more concentrated near the median value of 10 while female students are skewed slightly higher near the 11 value. However, in the second graph of predicted grades for both groups of students, predicted values are skewed higher than actual. Grade predictions for female students are significantly higher than actual as well as predictions for male students.   </span>
<span id="cb40-89"><a href="#cb40-89" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb40-92"><a href="#cb40-92" aria-hidden="true" tabindex="-1"></a><span class="in">```{r}</span></span>
<span id="cb40-93"><a href="#cb40-93" aria-hidden="true" tabindex="-1"></a>by_sex<span class="ot">&lt;-</span>performance<span class="sc">%&gt;%</span> <span class="fu">group_by</span>(sex)</span>
<span id="cb40-94"><a href="#cb40-94" aria-hidden="true" tabindex="-1"></a>by_sex<span class="sc">%&gt;%</span> <span class="fu">summarise</span>(<span class="fu">mean</span>(studytime))</span>
<span id="cb40-95"><a href="#cb40-95" aria-hidden="true" tabindex="-1"></a>by_sex<span class="sc">%&gt;%</span> <span class="fu">summarise</span>(<span class="fu">mean</span>(freetime))</span>
<span id="cb40-96"><a href="#cb40-96" aria-hidden="true" tabindex="-1"></a>by_sex<span class="sc">%&gt;%</span> <span class="fu">summarise</span>(<span class="fu">mean</span>(goout))</span>
<span id="cb40-97"><a href="#cb40-97" aria-hidden="true" tabindex="-1"></a>by_sex<span class="sc">%&gt;%</span> <span class="fu">summarise</span>(<span class="fu">mean</span>(absences))</span>
<span id="cb40-98"><a href="#cb40-98" aria-hidden="true" tabindex="-1"></a>by_sex<span class="sc">%&gt;%</span> <span class="fu">summarise</span>(<span class="fu">mean</span>(G3))</span>
<span id="cb40-99"><a href="#cb40-99" aria-hidden="true" tabindex="-1"></a>by_sex<span class="sc">%&gt;%</span> <span class="fu">summarise</span>(<span class="fu">mean</span>(PredictedGrade))</span>
<span id="cb40-100"><a href="#cb40-100" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb40-101"><a href="#cb40-101" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb40-102"><a href="#cb40-102" aria-hidden="true" tabindex="-1"></a>The above tables summarize differences in the mean values for several variables of interest by gender. Here we see, female students score slightly higher in  study time (2.07 vs. 1.7) and  while lower in free time (2.07 vs, 2.3), goout (3 vs. 3.05), absences (2.7 vs. 2.9). These would suggest female students may have a slightly higher grade based on good practices which is proven by the actual grades in G3 (12.15 vs. 11.80). However, the larger discrepancies in predicted rages (14.0 for females vs. 12.28 for males) may be attributed to the stereotype activation.   </span>
<span id="cb40-103"><a href="#cb40-103" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb40-104"><a href="#cb40-104" aria-hidden="true" tabindex="-1"></a>Additionally we can perform a t-test on both male and female actual and predicted score.   </span>
<span id="cb40-105"><a href="#cb40-105" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb40-108"><a href="#cb40-108" aria-hidden="true" tabindex="-1"></a><span class="in">```{r}</span></span>
<span id="cb40-109"><a href="#cb40-109" aria-hidden="true" tabindex="-1"></a><span class="co">#create two tables for female students and male students</span></span>
<span id="cb40-110"><a href="#cb40-110" aria-hidden="true" tabindex="-1"></a>f_performance<span class="ot">&lt;-</span>performance<span class="sc">%&gt;%</span></span>
<span id="cb40-111"><a href="#cb40-111" aria-hidden="true" tabindex="-1"></a><span class="fu">filter</span>(sex<span class="sc">==</span><span class="st">"F"</span>) </span>
<span id="cb40-112"><a href="#cb40-112" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb40-113"><a href="#cb40-113" aria-hidden="true" tabindex="-1"></a>m_performance<span class="ot">&lt;-</span>performance<span class="sc">%&gt;%</span></span>
<span id="cb40-114"><a href="#cb40-114" aria-hidden="true" tabindex="-1"></a><span class="fu">filter</span>(sex<span class="sc">==</span><span class="st">"M"</span>) </span>
<span id="cb40-115"><a href="#cb40-115" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb40-116"><a href="#cb40-116" aria-hidden="true" tabindex="-1"></a><span class="fu">t.test</span>(f_performance<span class="sc">$</span>G3)</span>
<span id="cb40-117"><a href="#cb40-117" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb40-118"><a href="#cb40-118" aria-hidden="true" tabindex="-1"></a><span class="fu">t.test</span>(m_performance<span class="sc">$</span>G3)</span>
<span id="cb40-119"><a href="#cb40-119" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb40-120"><a href="#cb40-120" aria-hidden="true" tabindex="-1"></a><span class="fu">t.test</span>(f_performance<span class="sc">$</span>PredictedGrade)</span>
<span id="cb40-121"><a href="#cb40-121" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb40-122"><a href="#cb40-122" aria-hidden="true" tabindex="-1"></a><span class="fu">t.test</span>(m_performance<span class="sc">$</span>PredictedGrade)</span>
<span id="cb40-123"><a href="#cb40-123" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb40-124"><a href="#cb40-124" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb40-125"><a href="#cb40-125" aria-hidden="true" tabindex="-1"></a>Based on the above tests, we can say with a 95% confidence that the following groups have the following means:  </span>
<span id="cb40-126"><a href="#cb40-126" aria-hidden="true" tabindex="-1"></a>Actual female grade - 12.14953   </span>
<span id="cb40-127"><a href="#cb40-127" aria-hidden="true" tabindex="-1"></a>Predicted female grade - 14.01636     </span>
<span id="cb40-128"><a href="#cb40-128" aria-hidden="true" tabindex="-1"></a>Actual male grade - 11.79439   </span>
<span id="cb40-129"><a href="#cb40-129" aria-hidden="true" tabindex="-1"></a>Predicted male grade - 12.27336   </span>
<span id="cb40-130"><a href="#cb40-130" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb40-131"><a href="#cb40-131" aria-hidden="true" tabindex="-1"></a>The graph below calculates the mean predicted grade for both groups based on the type of stereotype activation.   </span>
<span id="cb40-132"><a href="#cb40-132" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb40-135"><a href="#cb40-135" aria-hidden="true" tabindex="-1"></a><span class="in">```{r}</span></span>
<span id="cb40-136"><a href="#cb40-136" aria-hidden="true" tabindex="-1"></a>performance<span class="sc">%&gt;%</span></span>
<span id="cb40-137"><a href="#cb40-137" aria-hidden="true" tabindex="-1"></a><span class="fu">group_by</span>(sex, StereotypeActivation)<span class="sc">%&gt;%</span></span>
<span id="cb40-138"><a href="#cb40-138" aria-hidden="true" tabindex="-1"></a><span class="fu">summarise</span>(<span class="fu">mean</span>(PredictedGrade))</span>
<span id="cb40-139"><a href="#cb40-139" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb40-140"><a href="#cb40-140" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb40-141"><a href="#cb40-141" aria-hidden="true" tabindex="-1"></a>In the cross tabulation above, participants predicted the grade of female students 1 - 2.35 points higher than the average actual female performance (12.15). For male students, predictions were closer to the average actual performance (11.80) ranging at a difference of 0.16 - 0.88 points. With no stereotype activation, males students garnered their highest predicted average at 12.68 suggesting introducing stereotypes negatively affected predictions in male students although still higher than actual performance. For female students, introducing statistics of lower male performance garnered the highest grade prediction for female students. For both genders, case based stereotype activation which included one example of a high female score and two examples of lower male scores produced the lowest predicted grades.   </span>
<span id="cb40-142"><a href="#cb40-142" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb40-143"><a href="#cb40-143" aria-hidden="true" tabindex="-1"></a>This may suggest that other variables in the study having an influential role in predicting scores outside of stereotype activation.   </span>
<span id="cb40-144"><a href="#cb40-144" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb40-145"><a href="#cb40-145" aria-hidden="true" tabindex="-1"></a><span class="fu">## Methodology and Results   </span></span>
<span id="cb40-146"><a href="#cb40-146" aria-hidden="true" tabindex="-1"></a>To test my hypotheses, I will examine if the predicted grade was higher or lower than the actual grade among the genders controlling for various types of stereotype activation. Here the response variable is the predicted grade, and the explanatory variables are the types of gender as controlled by the exposure of the types of stereotype activation.   </span>
<span id="cb40-147"><a href="#cb40-147" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb40-148"><a href="#cb40-148" aria-hidden="true" tabindex="-1"></a><span class="ss">1. </span>Does exposure to negative stereotypes about male achievement and positive stereotypes of female achievement result in higher predicted achievement among both male and female students?   </span>
<span id="cb40-149"><a href="#cb40-149" aria-hidden="true" tabindex="-1"></a>Based on the cross tabulation above, exposure to negative statistics of male performance, resulted in the highest prediction for female grades even more than no stereotype exposure. However, those same statistics resulted in lower prediction of male grades than no stereotype exposure.   </span>
<span id="cb40-150"><a href="#cb40-150" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb40-151"><a href="#cb40-151" aria-hidden="true" tabindex="-1"></a><span class="ss">2. </span>Is there a statistically significant difference between male and female achievement based on the type of stereotype activation within each group?   </span>
<span id="cb40-152"><a href="#cb40-152" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb40-155"><a href="#cb40-155" aria-hidden="true" tabindex="-1"></a><span class="in">```{r}</span></span>
<span id="cb40-156"><a href="#cb40-156" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(<span class="fu">lm</span>(PredictedGrade <span class="sc">~</span> StereotypeActivation, <span class="at">data=</span>f_performance))</span>
<span id="cb40-157"><a href="#cb40-157" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(<span class="fu">lm</span>(PredictedGrade <span class="sc">~</span> StereotypeActivation, <span class="at">data=</span>m_performance))</span>
<span id="cb40-158"><a href="#cb40-158" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb40-159"><a href="#cb40-159" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb40-160"><a href="#cb40-160" aria-hidden="true" tabindex="-1"></a>Here, there appears that activating stereotype statistics resulted in a statistically significant difference in prediction of female grades. For predictions in male students, case based stereotypes resulted in the lowest predictions.   </span>
<span id="cb40-161"><a href="#cb40-161" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb40-164"><a href="#cb40-164" aria-hidden="true" tabindex="-1"></a><span class="in">```{r}</span></span>
<span id="cb40-165"><a href="#cb40-165" aria-hidden="true" tabindex="-1"></a>performance_fit<span class="ot">&lt;-</span><span class="fu">lm</span>(PredictedGrade <span class="sc">~</span> StereotypeActivation<span class="sc">*</span>sex, <span class="at">data=</span>performance)</span>
<span id="cb40-166"><a href="#cb40-166" aria-hidden="true" tabindex="-1"></a>performance_fit</span>
<span id="cb40-167"><a href="#cb40-167" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(performance_fit) <span class="co">#fit based on gender, predicted grade, and stereotype activation</span></span>
<span id="cb40-168"><a href="#cb40-168" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb40-169"><a href="#cb40-169" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb40-170"><a href="#cb40-170" aria-hidden="true" tabindex="-1"></a>When adding gender as an interacting variables, r-squared and the adjusted r-squared increased and we find a statistically significant result for male grades predicted after exposure to case based stereotypes.   </span>
<span id="cb40-171"><a href="#cb40-171" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb40-172"><a href="#cb40-172" aria-hidden="true" tabindex="-1"></a><span class="fu">#### Sources    </span></span>
<span id="cb40-173"><a href="#cb40-173" aria-hidden="true" tabindex="-1"></a>Bedyńska, S., Krejtz, I. &amp; Sedek, G. Chronic stereotype threat and mathematical achievement in age cohorts of secondary school girls: mediational role of working memory, and intellectual helplessness. Soc Psychol Educ 22, 321–335 (2019). https://doi.org/10.1007/s11218-019-09478-6</span>
<span id="cb40-174"><a href="#cb40-174" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb40-175"><a href="#cb40-175" aria-hidden="true" tabindex="-1"></a>Bedyńska, S., Krejtz, I., Rycielski, P. et al. Stereotype threat as an antecedent to domain identification and achievement in language arts in boys: a cross-sectional study. Soc Psychol Educ 23, 755–771 (2020). https://doi.org/10.1007/s11218-020-09557-z</span>
<span id="cb40-176"><a href="#cb40-176" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb40-177"><a href="#cb40-177" aria-hidden="true" tabindex="-1"></a>Booth MZ, Gerard JM. Self-esteem and academic achievement: a comparative study of adolescent students in England and the United States. Compare. 2011 Sep;41(5):629-648. doi: 10.1080/03057925.2011.566688</span>
<span id="cb40-178"><a href="#cb40-178" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb40-179"><a href="#cb40-179" aria-hidden="true" tabindex="-1"></a>Cortez, P. and Silva, A. Using Data Mining to Predict Secondary School Student Performance. In A. Brito and J. Teixeira Eds., Proceedings of 5th FUture BUsiness TEChnology Conference (FUBUTEC 2008) pp. 5-12, Porto, Portugal, April, 2008, EUROSIS, ISBN 978-9077381-39-7</span>
<span id="cb40-180"><a href="#cb40-180" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb40-181"><a href="#cb40-181" aria-hidden="true" tabindex="-1"></a>Ganley, C. M., Mingle, L. A., Ryan, A. M., Ryan, K., Vasilyeva, M., &amp; Perry, M. (2013). An examination of stereotype threat effects on girls’ mathematics performance. Developmental Psychology, 49(10), 1886–1897. https://doi.org/10.1037/a0031412</span>
<span id="cb40-182"><a href="#cb40-182" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb40-183"><a href="#cb40-183" aria-hidden="true" tabindex="-1"></a>Hyde, Janet Shibley. "Meta-analysis and the psychology of gender differences." Signs: Journal of Women in Culture and Society 16.1 (1990): 55-73. </span>
<span id="cb40-184"><a href="#cb40-184" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb40-185"><a href="#cb40-185" aria-hidden="true" tabindex="-1"></a>Johnson, H., Barnard-Brak, L., Saxon, T., &amp; Johnson, M.K. (2012) An Experimental Study of the Effects of Stereotype Threat and Stereotype Lift on Men and Women's Performance in Mathematics, The Journal of Experimental Education, 80:2, 137-149, DOI: 10.1080/00220973.2011.567312</span>
<span id="cb40-186"><a href="#cb40-186" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb40-187"><a href="#cb40-187" aria-hidden="true" tabindex="-1"></a>Moè, A., &amp; Putwain, D. W. (2020). An evaluative message fosters mathematics performance in male students but decreases intrinsic motivation in female students. Educational Psychology, 1–20. https://doi.org/10.1080/01443410.2020.1730767 </span>
<span id="cb40-188"><a href="#cb40-188" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb40-189"><a href="#cb40-189" aria-hidden="true" tabindex="-1"></a>Spinath, B., Harald Freudenthaler, H., &amp; Neubauer, A. C. (2010). Domain-specific school achievement in boys and girls as predicted by intelligence, personality and motivation. Personality and Individual Differences, 48(4), 481-486. https://doi.org/10.1016/j.paid.2009.11.028</span>
<span id="cb40-190"><a href="#cb40-190" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb40-191"><a href="#cb40-191" aria-hidden="true" tabindex="-1"></a>Steele, Claude M., and Joshua Aronson. "Stereotype threat and the intellectual test performance of African Americans." Journal of personality and social psychology 69.5 (1995): 797.</span>
<span id="cb40-192"><a href="#cb40-192" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb40-193"><a href="#cb40-193" aria-hidden="true" tabindex="-1"></a>Warne, R. T. (2022). No Strong Evidence of Stereotype Threat in Females: A Reassessment of the  Meta-Analysis. Journal of Advanced Academics, 33(2), 171–186. https://doi.org/10.1177/1932202X211061517</span>
<span id="cb40-194"><a href="#cb40-194" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb40-195"><a href="#cb40-195" aria-hidden="true" tabindex="-1"></a>Data source: Anonymous. (2022). <span class="kw">&lt;i&gt;</span>Performance vs. Predicted Performance<span class="kw">&lt;/i&gt;</span> <span class="co">[</span><span class="ot">Data set</span><span class="co">]</span>. Kaggle. https://doi.org/10.34740/KAGGLE/DSV/4282405</span>
</code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div></div></div></div></div>
</div> <!-- /content -->



</body></html>