<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.2.280">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">

<meta name="author" content="Kalimah Muhammad">
<meta name="dcterms.date" content="2022-12-02">

<title>Final Pt.2: Updates</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1.6em;
  vertical-align: middle;
}
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
    color: #aaaaaa;
  }
pre.numberSource { margin-left: 3em; border-left: 1px solid #aaaaaa;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
code span.al { color: #ff0000; font-weight: bold; } /* Alert */
code span.an { color: #60a0b0; font-weight: bold; font-style: italic; } /* Annotation */
code span.at { color: #7d9029; } /* Attribute */
code span.bn { color: #40a070; } /* BaseN */
code span.bu { color: #008000; } /* BuiltIn */
code span.cf { color: #007020; font-weight: bold; } /* ControlFlow */
code span.ch { color: #4070a0; } /* Char */
code span.cn { color: #880000; } /* Constant */
code span.co { color: #60a0b0; font-style: italic; } /* Comment */
code span.cv { color: #60a0b0; font-weight: bold; font-style: italic; } /* CommentVar */
code span.do { color: #ba2121; font-style: italic; } /* Documentation */
code span.dt { color: #902000; } /* DataType */
code span.dv { color: #40a070; } /* DecVal */
code span.er { color: #ff0000; font-weight: bold; } /* Error */
code span.ex { } /* Extension */
code span.fl { color: #40a070; } /* Float */
code span.fu { color: #06287e; } /* Function */
code span.im { color: #008000; font-weight: bold; } /* Import */
code span.in { color: #60a0b0; font-weight: bold; font-style: italic; } /* Information */
code span.kw { color: #007020; font-weight: bold; } /* Keyword */
code span.op { color: #666666; } /* Operator */
code span.ot { color: #007020; } /* Other */
code span.pp { color: #bc7a00; } /* Preprocessor */
code span.sc { color: #4070a0; } /* SpecialChar */
code span.ss { color: #bb6688; } /* SpecialString */
code span.st { color: #4070a0; } /* String */
code span.va { color: #19177c; } /* Variable */
code span.vs { color: #4070a0; } /* VerbatimString */
code span.wa { color: #60a0b0; font-weight: bold; font-style: italic; } /* Warning */
</style>


<script src="../site_libs/quarto-nav/quarto-nav.js"></script>
<script src="../site_libs/quarto-nav/headroom.min.js"></script>
<script src="../site_libs/clipboard/clipboard.min.js"></script>
<script src="../site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="../site_libs/quarto-search/fuse.min.js"></script>
<script src="../site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="../">
<link href="../images/DACSS_Round_Network.png" rel="icon" type="image/png">
<script src="../site_libs/quarto-html/quarto.js"></script>
<script src="../site_libs/quarto-html/popper.min.js"></script>
<script src="../site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="../site_libs/quarto-html/anchor.min.js"></script>
<link href="../site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="../site_libs/quarto-html/quarto-syntax-highlighting.css" rel="stylesheet" class="quarto-color-scheme" id="quarto-text-highlighting-styles">
<link href="../site_libs/quarto-html/quarto-syntax-highlighting-dark.css" rel="prefetch" class="quarto-color-scheme quarto-color-alternate" id="quarto-text-highlighting-styles">
<script src="../site_libs/bootstrap/bootstrap.min.js"></script>
<link href="../site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="../site_libs/bootstrap/bootstrap.min.css" rel="stylesheet" class="quarto-color-scheme" id="quarto-bootstrap" data-mode="light">
<link href="../site_libs/bootstrap/bootstrap-dark.min.css" rel="prefetch" class="quarto-color-scheme quarto-color-alternate" id="quarto-bootstrap" data-mode="dark">
<script id="quarto-search-options" type="application/json">{
  "location": "navbar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "end",
  "type": "overlay",
  "limit": 20,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit"
  }
}</script>


<meta name="twitter:title" content="Final Pt.2: Updates">
<meta name="twitter:description" content="Researchers have examined the differences impacting student achievement among genders for decades.">
<meta name="twitter:creator" content="@UMassDACSS">
<meta name="twitter:site" content="@UMassDACSS">
<meta name="twitter:card" content="summary">
</head>

<body class="nav-fixed">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
    <nav class="navbar navbar-expand-lg navbar-dark ">
      <div class="navbar-container container-fluid">
      <div class="navbar-brand-container">
    <a href="../index.html" class="navbar-brand navbar-brand-logo">
    <img src="../images/UMass White Wordmark Horiz.png" alt="" class="navbar-logo">
    </a>
  </div>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse" aria-controls="navbarCollapse" aria-expanded="false" aria-label="Toggle navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
  <span class="navbar-toggler-icon"></span>
</button>
          <div class="collapse navbar-collapse" id="navbarCollapse">
            <ul class="navbar-nav navbar-nav-scroll ms-auto">
  <li class="nav-item">
    <a class="nav-link" href="https://dacss.github.io/603_Fall_2022/">
 <span class="menu-text">Fall 2022 Posts</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="../about.html">
 <span class="menu-text">Contributors</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="https://umass.edu/sbs/dacss">
 <span class="menu-text">DACSS</span></a>
  </li>  
  <li class="nav-item compact">
    <a class="nav-link" href="https://github.com/DACSS/603_Fall_2022"><i class="bi bi-github" role="img" aria-label="GitHub">
</i> 
 <span class="menu-text"></span></a>
  </li>  
</ul>
              <div class="quarto-toggle-container">
                  <a href="" class="quarto-color-scheme-toggle nav-link" onclick="window.quartoToggleColorScheme(); return false;" title="Toggle dark mode"><i class="bi"></i></a>
              </div>
              <div id="quarto-search" class="" title="Search"></div>
          </div> <!-- /navcollapse -->
      </div> <!-- /container-fluid -->
    </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article page-navbar">
<!-- sidebar -->
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">On this page</h2>
   
  <ul>
  <li><a href="#background" id="toc-background" class="nav-link active" data-scroll-target="#background">Background</a></li>
  <li><a href="#research-questions" id="toc-research-questions" class="nav-link" data-scroll-target="#research-questions">Research Questions</a></li>
  <li><a href="#data" id="toc-data" class="nav-link" data-scroll-target="#data">Data</a></li>
  <li><a href="#hypothesis-testing" id="toc-hypothesis-testing" class="nav-link" data-scroll-target="#hypothesis-testing">Hypothesis Testing</a>
  <ul class="collapse">
  <li><a href="#h1.-does-exposure-to-negative-stereotypes-about-male-achievement-st-and-positive-stereotypes-of-female-achievement-sl-result-in-differences-in-predicted-achievement-among-both-male-and-female-students" id="toc-h1.-does-exposure-to-negative-stereotypes-about-male-achievement-st-and-positive-stereotypes-of-female-achievement-sl-result-in-differences-in-predicted-achievement-among-both-male-and-female-students" class="nav-link" data-scroll-target="#h1.-does-exposure-to-negative-stereotypes-about-male-achievement-st-and-positive-stereotypes-of-female-achievement-sl-result-in-differences-in-predicted-achievement-among-both-male-and-female-students"><em>H1. Does exposure to negative stereotypes about male achievement (ST) and positive stereotypes of female achievement (SL) result in differences in predicted achievement among both male and female students?</em></a></li>
  <li><a href="#h2.-was-there-a-statistically-significant-difference-between-predicted-male-and-female-achievement-based-on-the-type-of-stereotype-activation" id="toc-h2.-was-there-a-statistically-significant-difference-between-predicted-male-and-female-achievement-based-on-the-type-of-stereotype-activation" class="nav-link" data-scroll-target="#h2.-was-there-a-statistically-significant-difference-between-predicted-male-and-female-achievement-based-on-the-type-of-stereotype-activation">H2. <em>Was there a statistically significant difference between predicted male and female achievement based on the type of stereotype activation?</em></a></li>
  </ul></li>
  <li><a href="#model-comparison" id="toc-model-comparison" class="nav-link" data-scroll-target="#model-comparison">Model Comparison</a>
  <ul class="collapse">
  <li><a href="#model-1---predicted-grades-and-presence-of-stereotype-activation" id="toc-model-1---predicted-grades-and-presence-of-stereotype-activation" class="nav-link" data-scroll-target="#model-1---predicted-grades-and-presence-of-stereotype-activation">Model 1 - Predicted Grades and Presence of Stereotype Activation</a></li>
  <li><a href="#model-2-and-3---predicted-grades-by-stereotype-activation-and-gender" id="toc-model-2-and-3---predicted-grades-by-stereotype-activation-and-gender" class="nav-link" data-scroll-target="#model-2-and-3---predicted-grades-by-stereotype-activation-and-gender">Model 2 and 3 - Predicted Grades by Stereotype Activation and Gender</a></li>
  <li><a href="#model-4---predicted-grades-by-other-potential-explanatory-variables" id="toc-model-4---predicted-grades-by-other-potential-explanatory-variables" class="nav-link" data-scroll-target="#model-4---predicted-grades-by-other-potential-explanatory-variables">Model 4 - Predicted Grades by Other Potential Explanatory Variables</a></li>
  </ul></li>
  <li><a href="#diagnostics" id="toc-diagnostics" class="nav-link" data-scroll-target="#diagnostics">Diagnostics</a></li>
  <li><a href="#summary" id="toc-summary" class="nav-link" data-scroll-target="#summary">Summary</a></li>
  </ul>
</nav>
    </div>
<!-- main -->
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<div class="quarto-title-block"><div><h1 class="title">Final Pt.2: Updates</h1><button type="button" class="btn code-tools-button dropdown-toggle" id="quarto-code-tools-menu" data-bs-toggle="dropdown" aria-expanded="false"><i class="bi"></i> Code</button><ul class="dropdown-menu dropdown-menu-end" aria-labelelledby="quarto-code-tools-menu"><li><a id="quarto-show-all-code" class="dropdown-item" href="javascript:void(0)" role="button">Show All Code</a></li><li><a id="quarto-hide-all-code" class="dropdown-item" href="javascript:void(0)" role="button">Hide All Code</a></li><li><hr class="dropdown-divider"></li><li><a id="quarto-view-source" class="dropdown-item" href="javascript:void(0)" role="button">View Source</a></li></ul></div></div>
  <div class="quarto-categories">
    <div class="quarto-category">finalpt2</div>
    <div class="quarto-category">Kalimah Muhammad</div>
  </div>
  </div>



<div class="quarto-title-meta">

    <div>
    <div class="quarto-title-meta-heading">Author</div>
    <div class="quarto-title-meta-contents">
             <p>Kalimah Muhammad </p>
          </div>
  </div>
    
    <div>
    <div class="quarto-title-meta-heading">Published</div>
    <div class="quarto-title-meta-contents">
      <p class="date">December 2, 2022</p>
    </div>
  </div>
  
    
  </div>
  

</header>

<div class="cell">
<details>
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb1"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(tidyverse)</span>
<span id="cb1-2"><a href="#cb1-2" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(dplyr)</span>
<span id="cb1-3"><a href="#cb1-3" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(ggplot2)</span>
<span id="cb1-4"><a href="#cb1-4" aria-hidden="true" tabindex="-1"></a>performance<span class="ot">&lt;-</span> <span class="fu">read_csv</span>(<span class="st">"_data/CompleteDataAndBiases.csv"</span>)</span>
<span id="cb1-5"><a href="#cb1-5" aria-hidden="true" tabindex="-1"></a>knitr<span class="sc">::</span>opts_chunk<span class="sc">$</span><span class="fu">set</span>(<span class="at">echo =</span> <span class="cn">TRUE</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
</div>
<section id="background" class="level2">
<h2 class="anchored" data-anchor-id="background">Background</h2>
<p>Researchers have examined the differences impacting student achievement among genders for decades. Early meta-analyses conducted by Hyde (1990) revealed no significant difference between the groups’ cognitive abilities; yet intelligence and self-perception of ability, or self-esteem, were determined as the strongest predictors of academic success (Spinath et al., 2010, Booth and Gerard, 2011). Some research explains differences in achievement partially by stereotype threat (ST). Stereotype threat, originally used to research the vulnerability of racial stereotypes on aptitude tests, is defined as “being at risk of confirming, as self-characteristic, a negative stereotype about one’s group” (Steele and Aronson, 1995). Conventional research has focused on gender differences to stereotype threat (Moè &amp; Putwain, 2020), and two prevailing theories have emerged.</p>
<p>The first theory suggests that ST affects male and female students differently. Here male students achieve better outcomes when stereotype threat is present than stereotype lift, and the reverse is true for female students who are adversely impacted by stereotype threat and positively impacted by stereotype lift (Johnson et al., 2012). Other studies debunk this theory suggesting no evidence of ST as a phenomenon in female students (Warne, 2022), particularly in the domain of mathematical achievement (Ganley et al., 2013). A second theory exists that the effects of ST may not be fully realized as outcomes immediately but affect achievement over time as chronic ST impacts working memory and intellectual helplessness in girls’ math scores (Bedyńska, Krejtz, and Sedek, 2019) and male language arts scores (Bedyńska, Krejtz, and Sedek, 2020).</p>
</section>
<section id="research-questions" class="level2">
<h2 class="anchored" data-anchor-id="research-questions">Research Questions</h2>
<p>This study tests both theories. First, it questions if there are differences in predicted student achievement based on gender when exposed to negative stereotypes about males and positive stereotypes about females. Second, it evaluates the effect of the perceived prevalence of stereotypes as shown by the participants’ exposure to three types of stereotype activation in predicting grades. The types of stereotype activation include:</p>
<ul>
<li><p>None: Participants were not exposed to stereotypes during this experiment.</p></li>
<li><p>Case-based: Participants were shown three student profiles in which one female student had a high grade, and two male students had low grades.</p></li>
<li><p>Statistics: Participants were shown statistics suggesting boys performed less well in school than girls.</p></li>
</ul>
<p>This study tests the following hypotheses:</p>
<p><strong>H1.</strong> Does exposure to negative stereotypes about male achievement (ST) and positive stereotypes of female achievement (SL) result in higher predicted achievement among both male and female students?</p>
<p><strong>H2.</strong> Was there a statistically significant difference between predicted male and female achievement based on the type of stereotype activation?</p>
</section>
<section id="data" class="level2">
<h2 class="anchored" data-anchor-id="data">Data</h2>
<p>Data for this project was collected from Kaggle (Performance vs.&nbsp;Predicted Performance, 2022) and is a collection of existing student performance data from a study by Cortez and Silva (2008) on predicting secondary school student performance and the collector’s addition of stereotype activation for machine learning. The data included information on actual student demographics such as gender, parents’ highest level of education, as well as time studying vs.&nbsp;free time, number of absences, and grade on a final exam, among other variables.</p>
<p>A few important variables to define include:<br>
-Index - number of students included in the original and predicted data (N=856 of the original 991 students)<br>
-Participant ID - number associated with participants making predictions (N=107)<br>
-Sex - student’s sex (binary: ‘F’ - female or ‘M’ - male)<br>
-Studytime - weekly study time is categorized as 1= less than 2 hours, 2= 2-5 hours and 3= 5+ hours<br>
-Freetime - free time after school group as 1 = low, 2= medium, 3 = high<br>
-Goout - how often a student goes out with friends where 1 is very low and 4 is very often<br>
-Absences - number of school absences 1 - 7 where 7 represents any absences equal to or above 7<br>
-Walc - weekend alcohol consumption<br>
-Parents_edu - the higher of original variables mother’s edu and father’s edu, where 4 = the highest level of education<br>
-G3 - final grade (numeric: from 0 to 20)<br>
-Reason - The reason for why a student chose to go to the school in question. The levels are close to home, school’s reputation, school’s curricular and other<br>
-PredictedGrade - the grade participants predicted based on actual data and their exposed level of StereotypeActivation<br>
-StereotypeActivation - see three levels of stereotype activation above<br>
-Pass - A binary variable showing whether G3 is a passing grade (i.e.&nbsp;&gt;=10) or not<br>
-PassFailStrategy - A binary variable showing whether the PredictedGrade is a passing grade (i.e.&nbsp;&gt;=10) or not</p>
<p>An additional variable I added to the data set, STPresent, identifies whether stereotype activation was present (True or False) for participants when predicting student scores.</p>
<p>Below is a summary of the variables.</p>
<div class="cell">
<details>
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb2"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb2-1"><a href="#cb2-1" aria-hidden="true" tabindex="-1"></a><span class="co">#view top 5 observations</span></span>
<span id="cb2-2"><a href="#cb2-2" aria-hidden="true" tabindex="-1"></a><span class="fu">head</span>(performance, <span class="dv">10</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 10 × 19
   index Parti…¹ name  sex   study…² freet…³ roman…⁴  Walc goout Paren…⁵ absen…⁶
   &lt;dbl&gt;   &lt;dbl&gt; &lt;chr&gt; &lt;chr&gt;   &lt;dbl&gt;   &lt;dbl&gt; &lt;chr&gt;   &lt;dbl&gt; &lt;dbl&gt;   &lt;dbl&gt;   &lt;dbl&gt;
 1   132       1 Anna  F           1       2 no          1     2       4       0
 2   724       1 Mich… M           1       1 no          4     4       4       1
 3   637       1 David M           1       2 no          4     2       2       0
 4   884       1 Brian M           1       1 no          4     4       3       7
 5   194       1 Jenny F           2       2 no          1     4       2       0
 6   388       1 Oliv… M           2       2 no          1     1       4       1
 7    65       1 Lisa  F           2       3 no          2     3       4       1
 8   303       1 Sarah F           3       3 yes         1     3       4       6
 9   312       2 Oliv… M           3       2 yes         2     2       4       7
10   305       2 Lisa  F           3       3 no          2     3       3       7
# … with 8 more variables: reason &lt;chr&gt;, G3 &lt;dbl&gt;, Pass &lt;lgl&gt;,
#   PredictedGrade &lt;dbl&gt;, PredictedRank &lt;dbl&gt;, StereotypeActivation &lt;chr&gt;,
#   Predicted_Pass_PassFailStrategy &lt;lgl&gt;,
#   Predicted_Pass_RankingStrategy &lt;lgl&gt;, and abbreviated variable names
#   ¹​ParticipantID, ²​studytime, ³​freetime, ⁴​romantic, ⁵​Parents_edu, ⁶​absences</code></pre>
</div>
<details>
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb4"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb4-1"><a href="#cb4-1" aria-hidden="true" tabindex="-1"></a><span class="co">#Add column that distinguishes if stereotype activation is present</span></span>
<span id="cb4-2"><a href="#cb4-2" aria-hidden="true" tabindex="-1"></a>performance <span class="ot">&lt;-</span>performance<span class="sc">%&gt;%</span></span>
<span id="cb4-3"><a href="#cb4-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">STPresent =</span> <span class="fu">case_when</span>(StereotypeActivation <span class="sc">==</span> <span class="st">"CaseBased"</span><span class="sc">|</span> StereotypeActivation <span class="sc">==</span> <span class="st">"Statistics"</span> <span class="sc">~</span> <span class="cn">TRUE</span>, StereotypeActivation<span class="sc">==</span><span class="st">"None"</span> <span class="sc">~</span> <span class="cn">FALSE</span>))</span>
<span id="cb4-4"><a href="#cb4-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb4-5"><a href="#cb4-5" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(performance)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>     index       ParticipantID     name               sex           
 Min.   :  1.0   Min.   :  1   Length:856         Length:856        
 1st Qu.:241.8   1st Qu.: 27   Class :character   Class :character  
 Median :487.0   Median : 54   Mode  :character   Mode  :character  
 Mean   :486.9   Mean   : 54                                        
 3rd Qu.:727.2   3rd Qu.: 81                                        
 Max.   :990.0   Max.   :107                                        
   studytime        freetime       romantic              Walc      
 Min.   :1.000   Min.   :1.000   Length:856         Min.   :1.000  
 1st Qu.:1.000   1st Qu.:2.000   Class :character   1st Qu.:1.000  
 Median :2.000   Median :2.000   Mode  :character   Median :2.000  
 Mean   :1.887   Mean   :2.183                      Mean   :2.284  
 3rd Qu.:2.000   3rd Qu.:3.000                      3rd Qu.:3.000  
 Max.   :3.000   Max.   :3.000                      Max.   :4.000  
     goout        Parents_edu       absences        reason         
 Min.   :1.000   Min.   :1.000   Min.   :0.000   Length:856        
 1st Qu.:2.000   1st Qu.:2.000   1st Qu.:0.000   Class :character  
 Median :3.000   Median :3.000   Median :2.000   Mode  :character  
 Mean   :3.022   Mean   :2.854   Mean   :2.794                     
 3rd Qu.:4.000   3rd Qu.:4.000   3rd Qu.:5.000                     
 Max.   :4.000   Max.   :4.000   Max.   :7.000                     
       G3           Pass         PredictedGrade  PredictedRank 
 Min.   : 1.00   Mode :logical   Min.   : 0.00   Min.   :1.00  
 1st Qu.:10.00   FALSE:149       1st Qu.:10.00   1st Qu.:2.75  
 Median :12.00   TRUE :707       Median :14.00   Median :4.50  
 Mean   :11.97                   Mean   :13.14   Mean   :4.50  
 3rd Qu.:14.00                   3rd Qu.:16.00   3rd Qu.:6.25  
 Max.   :20.00                   Max.   :20.00   Max.   :8.00  
 StereotypeActivation Predicted_Pass_PassFailStrategy
 Length:856           Mode :logical                  
 Class :character     FALSE:170                      
 Mode  :character     TRUE :686                      
                                                     
                                                     
                                                     
 Predicted_Pass_RankingStrategy STPresent      
 Mode :logical                  Mode :logical  
 FALSE:284                      FALSE:264      
 TRUE :572                      TRUE :592      
                                               
                                               
                                               </code></pre>
</div>
<details>
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb6"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb6-1"><a href="#cb6-1" aria-hidden="true" tabindex="-1"></a><span class="co">#cross-tabulation of stereotype activation by gender </span></span>
<span id="cb6-2"><a href="#cb6-2" aria-hidden="true" tabindex="-1"></a><span class="fu">xtabs</span>(<span class="sc">~</span>sex <span class="sc">+</span> STPresent, performance)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>   STPresent
sex FALSE TRUE
  F   132  296
  M   132  296</code></pre>
</div>
</div>
<p>There is an even distribution of male and female students (428 each), with 69% of participants exposed to some type of stereotype activation during grade prediction. The actual and predicted rate of passing are similar, 707 students passed versus the predicted 686, approximately 83% to 80% respectively. This may suggest other variables as strong indicators in passing. There is, however, a notable difference in the average actual scores (11.97) and predicted scores (13.14). This is further emphasized by the median actual scores (12) and predicted median (14). This early finding suggest that although the rate of passing was slightly lower, the overall predicted scores are skewed higher than actual.</p>
<p>The next two graphs compare the actual final grade vs.&nbsp;the predicted grade for both genders.</p>
<div class="cell">
<details>
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb8"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb8-1"><a href="#cb8-1" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(performance, <span class="fu">aes</span>(<span class="at">x=</span>G3, <span class="at">fill=</span>sex))<span class="sc">+</span> <span class="fu">geom_histogram</span>(<span class="at">position =</span> <span class="st">"dodge"</span>)<span class="sc">+</span><span class="fu">labs</span>(<span class="at">x=</span><span class="st">"Students Actual Final Grade (G3)"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stderr">
<pre><code>`stat_bin()` using `bins = 30`. Pick better value with `binwidth`.</code></pre>
</div>
<div class="cell-output-display">
<p><img src="KalimahMuhammad_finalpart2_v2_files/figure-html/plot actual and predicted performance-1.png" class="img-fluid" width="672"></p>
</div>
<details>
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb10"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb10-1"><a href="#cb10-1" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(performance, <span class="fu">aes</span>(<span class="at">x=</span>PredictedGrade, <span class="at">fill=</span>sex))<span class="sc">+</span> <span class="fu">geom_histogram</span>(<span class="at">position =</span> <span class="st">"dodge"</span>)<span class="sc">+</span><span class="fu">labs</span>(<span class="at">x=</span><span class="st">"Students Predicted Final Grade (PredictedGrade)"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stderr">
<pre><code>`stat_bin()` using `bins = 30`. Pick better value with `binwidth`.</code></pre>
</div>
<div class="cell-output-display">
<p><img src="KalimahMuhammad_finalpart2_v2_files/figure-html/plot actual and predicted performance-2.png" class="img-fluid" width="672"></p>
</div>
</div>
<p>In the first graph, there is a fairly normal distribution of actual grades for both male and female students. Male students are more concentrated near the median value of 10 while female students are skewed slightly higher near the 11 value. However, in the second graph of predicted grades for both groups, female students are skewed significantly higher near 15 points while predictions for male students spreads near 12 points. This study will investigate if stereotype activation is a possible explanation for this variance.</p>
<div class="cell">
<details>
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb12"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb12-1"><a href="#cb12-1" aria-hidden="true" tabindex="-1"></a><span class="co">#boxplot of predicted grades by gender and if stereotype activation is present</span></span>
<span id="cb12-2"><a href="#cb12-2" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(performance, <span class="fu">aes</span>(<span class="at">x=</span>STPresent, <span class="at">y=</span>PredictedGrade, <span class="at">fill=</span>sex))<span class="sc">+</span></span>
<span id="cb12-3"><a href="#cb12-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_boxplot</span>()<span class="sc">+</span></span>
<span id="cb12-4"><a href="#cb12-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme</span>(<span class="at">legend.position=</span><span class="st">"none"</span>) <span class="sc">+</span></span>
<span id="cb12-5"><a href="#cb12-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ggtitle</span>(<span class="st">"Predicted Grades by Gender and Presence of Stereotype Activation"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output-display">
<p><img src="KalimahMuhammad_finalpart2_v2_files/figure-html/boxplot of grades by ST presence-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<p>The chart above shows more variability in predicted grades for female students without any stereotype activation; yet once present, the concentration of scores skews higher. For male students, predicted scores increased in the presence of stereotype activation accounting for more low scores. Note, male scores were overall predicted lower than females independent of stereotype activation. Is there another variable contributing to this difference?</p>
</section>
<section id="hypothesis-testing" class="level2">
<h2 class="anchored" data-anchor-id="hypothesis-testing">Hypothesis Testing</h2>
<section id="h1.-does-exposure-to-negative-stereotypes-about-male-achievement-st-and-positive-stereotypes-of-female-achievement-sl-result-in-differences-in-predicted-achievement-among-both-male-and-female-students" class="level3">
<h3 class="anchored" data-anchor-id="h1.-does-exposure-to-negative-stereotypes-about-male-achievement-st-and-positive-stereotypes-of-female-achievement-sl-result-in-differences-in-predicted-achievement-among-both-male-and-female-students"><em>H1. Does exposure to negative stereotypes about male achievement (ST) and positive stereotypes of female achievement (SL) result in differences in predicted achievement among both male and female students?</em></h3>
<p>Here the dependent variable is the predicted grade and independent variable is presence of stereotype threat. The Null hypothesis states stereotype activation does not have a statistically significant effect on predicted grades for male and female students and the alternative hypothesis is negative stereotypes about male achievement and positive stereotypes of female achievement result in changes in predicted grades among both male and female students.</p>
<p>I conducted a two directional, two sample t-test to investigate the differences in the mean predicted score for students with it labeled “TRUE” and without stereotype activation labeled “FALSE”.</p>
<div class="cell">
<details>
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb13"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb13-1"><a href="#cb13-1" aria-hidden="true" tabindex="-1"></a><span class="fu">t.test</span>(PredictedGrade <span class="sc">~</span> STPresent, <span class="at">data=</span> performance, <span class="at">alternative =</span> <span class="fu">c</span>(<span class="st">"two.sided"</span>), <span class="at">var.equal =</span> <span class="cn">FALSE</span>, <span class="at">conf.level =</span> <span class="fl">0.95</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>
    Welch Two Sample t-test

data:  PredictedGrade by STPresent
t = 1.1314, df = 539.07, p-value = 0.2584
alternative hypothesis: true difference in means between group FALSE and group TRUE is not equal to 0
95 percent confidence interval:
 -0.2409671  0.8955535
sample estimates:
mean in group FALSE  mean in group TRUE 
           13.37121            13.04392 </code></pre>
</div>
</div>
<p>Although the mean predicted grades for those not exposed to ST are higher (13.37) compared to those where ST was present (13.04), the resulting p-value of 0.26, renders this test not significant in the predicted grades based on if stereotype activation was present. Thus, the null was retained.</p>
<p>The next test isolates predicted grades for male students only.</p>
<div class="cell">
<details>
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb15"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb15-1"><a href="#cb15-1" aria-hidden="true" tabindex="-1"></a><span class="co">#create two tables for female students and male students</span></span>
<span id="cb15-2"><a href="#cb15-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb15-3"><a href="#cb15-3" aria-hidden="true" tabindex="-1"></a>m_performance<span class="ot">&lt;-</span>performance<span class="sc">%&gt;%</span></span>
<span id="cb15-4"><a href="#cb15-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">filter</span>(sex<span class="sc">==</span><span class="st">"M"</span>)</span>
<span id="cb15-5"><a href="#cb15-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb15-6"><a href="#cb15-6" aria-hidden="true" tabindex="-1"></a><span class="co">#t.test for difference in mean of predicted grades for males with and without ST present</span></span>
<span id="cb15-7"><a href="#cb15-7" aria-hidden="true" tabindex="-1"></a><span class="co">#null hypothesis - mean of predicted grades is equals the mean of actual grades</span></span>
<span id="cb15-8"><a href="#cb15-8" aria-hidden="true" tabindex="-1"></a><span class="fu">t.test</span>(PredictedGrade <span class="sc">~</span> STPresent, <span class="at">data=</span> m_performance, <span class="at">alternative =</span> <span class="fu">c</span>(<span class="st">"two.sided"</span>), <span class="at">conf.level =</span> <span class="fl">0.95</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>
    Welch Two Sample t-test

data:  PredictedGrade by STPresent
t = 1.4747, df = 297.81, p-value = 0.1414
alternative hypothesis: true difference in means between group FALSE and group TRUE is not equal to 0
95 percent confidence interval:
 -0.1975596  1.3787636
sample estimates:
mean in group FALSE  mean in group TRUE 
           12.68182            12.09122 </code></pre>
</div>
</div>
<p>The following test isolates predicted grades for female students only.</p>
<div class="cell">
<details>
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb17"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb17-1"><a href="#cb17-1" aria-hidden="true" tabindex="-1"></a><span class="co">#create two tables for female students and male students</span></span>
<span id="cb17-2"><a href="#cb17-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb17-3"><a href="#cb17-3" aria-hidden="true" tabindex="-1"></a>m_performance<span class="ot">&lt;-</span>performance<span class="sc">%&gt;%</span></span>
<span id="cb17-4"><a href="#cb17-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">filter</span>(sex<span class="sc">==</span><span class="st">"F"</span>)</span>
<span id="cb17-5"><a href="#cb17-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb17-6"><a href="#cb17-6" aria-hidden="true" tabindex="-1"></a><span class="co">#t.test for difference in mean of predicted grades for males with and without ST present</span></span>
<span id="cb17-7"><a href="#cb17-7" aria-hidden="true" tabindex="-1"></a><span class="co">#null hypothesis - mean of predicted grades is equals the mean of actual grades</span></span>
<span id="cb17-8"><a href="#cb17-8" aria-hidden="true" tabindex="-1"></a><span class="fu">t.test</span>(PredictedGrade <span class="sc">~</span> STPresent, <span class="at">data=</span> f_performance, <span class="at">alternative =</span> <span class="fu">c</span>(<span class="st">"two.sided"</span>), <span class="at">conf.level =</span> <span class="fl">0.95</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-error">
<pre><code>Error in eval(m$data, parent.frame()): object 'f_performance' not found</code></pre>
</div>
</div>
<p>Both tests have a p-value higher than 0.05 denoting that neither gender experienced a statistically significant difference in predicted average grades based on exposure to stereotype activation or not. Further rejecting hypothesis one.</p>
</section>
<section id="h2.-was-there-a-statistically-significant-difference-between-predicted-male-and-female-achievement-based-on-the-type-of-stereotype-activation" class="level3">
<h3 class="anchored" data-anchor-id="h2.-was-there-a-statistically-significant-difference-between-predicted-male-and-female-achievement-based-on-the-type-of-stereotype-activation">H2. <em>Was there a statistically significant difference between predicted male and female achievement based on the type of stereotype activation?</em></h3>
<p>The graph below calculates the mean predicted grade for both groups based on the type of stereotype activation.</p>
<div class="cell">
<details>
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb19"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb19-1"><a href="#cb19-1" aria-hidden="true" tabindex="-1"></a>performance<span class="sc">%&gt;%</span></span>
<span id="cb19-2"><a href="#cb19-2" aria-hidden="true" tabindex="-1"></a><span class="fu">group_by</span>(sex, StereotypeActivation)<span class="sc">%&gt;%</span></span>
<span id="cb19-3"><a href="#cb19-3" aria-hidden="true" tabindex="-1"></a><span class="fu">summarise</span>(<span class="fu">mean</span>(PredictedGrade), <span class="fu">mean</span>(G3), <span class="fu">mean</span>(PredictedGrade)<span class="sc">-</span><span class="fu">mean</span>(G3))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stderr">
<pre><code>`summarise()` has grouped output by 'sex'. You can override using the `.groups`
argument.</code></pre>
</div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 6 × 5
# Groups:   sex [2]
  sex   StereotypeActivation `mean(PredictedGrade)` `mean(G3)` mean(PredictedG…¹
  &lt;chr&gt; &lt;chr&gt;                                 &lt;dbl&gt;      &lt;dbl&gt;             &lt;dbl&gt;
1 F     CaseBased                              13.4       12.2             1.22 
2 F     None                                   14.1       12.3             1.80 
3 F     Statistics                             14.5       12.0             2.47 
4 M     CaseBased                              12.0       11.6             0.353
5 M     None                                   12.7       11.8             0.932
6 M     Statistics                             12.2       12.0             0.212
# … with abbreviated variable name ¹​`mean(PredictedGrade) - mean(G3)`</code></pre>
</div>
</div>
<p>In the summary above, participants ranked the average predicted scores higher overall than the actual scores irrespective of gender or stereotype activation. The difference in predicted versus actual score was greatest among female students. Here participants exposed to the stereotype statistics predicted the widest difference compared to actual scores (2.47) and the highest overall scores (14.5).</p>
<p>For male students, predictions were closer to the average actual performance (11.80) ranging at a difference of 0.16 - 0.88 points. With no stereotype activation, males students garnered their highest predicted average at 12.68 suggesting introducing stereotypes negatively affected predictions in male students although still higher than actual performance. For female students, introducing statistics of lower male performance than females garnered the highest grade prediction for female students. For both genders, case based stereotype activation which included one example of a high female score and two examples of lower male scores produced the lowest predicted grades.</p>
<div class="cell">
<details>
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb22"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb22-1"><a href="#cb22-1" aria-hidden="true" tabindex="-1"></a><span class="fu">pairwise.t.test</span>(<span class="at">x=</span> performance<span class="sc">$</span>PredictedGrade, <span class="at">g=</span>performance<span class="sc">$</span>StereotypeActivation, <span class="at">p.adjust.method =</span> <span class="st">"none"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>
    Pairwise comparisons using t tests with pooled SD 

data:  performance$PredictedGrade and performance$StereotypeActivation 

           CaseBased None 
None       0.047     -    
Statistics 0.044     0.949

P value adjustment method: none </code></pre>
</div>
</div>
<p>This may suggest that other variables in the study have an influential role in predicting scores outside of stereotype activation.</p>
</section>
</section>
<section id="model-comparison" class="level2">
<h2 class="anchored" data-anchor-id="model-comparison">Model Comparison</h2>
<section id="model-1---predicted-grades-and-presence-of-stereotype-activation" class="level3">
<h3 class="anchored" data-anchor-id="model-1---predicted-grades-and-presence-of-stereotype-activation">Model 1 - Predicted Grades and Presence of Stereotype Activation</h3>
<p>In the first model, I will use PredictedGrade as the outcome or dependent variable and the STPresent variable as the explanatory or independent variable adding in student sex as an interaction term.</p>
<div class="cell">
<details>
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb24"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb24-1"><a href="#cb24-1" aria-hidden="true" tabindex="-1"></a>model1<span class="ot">&lt;-</span> (<span class="fu">lm</span>(PredictedGrade <span class="sc">~</span> STPresent <span class="sc">*</span> sex, <span class="at">data=</span>performance))</span>
<span id="cb24-2"><a href="#cb24-2" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(model1)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = PredictedGrade ~ STPresent * sex, data = performance)

Residuals:
     Min       1Q   Median       3Q      Max 
-13.9966  -3.0126   0.0034   3.0034   7.9088 

Coefficients:
                   Estimate Std. Error t value Pr(&gt;|t|)    
(Intercept)        14.06061    0.34139  41.186   &lt;2e-16 ***
STPresentTRUE      -0.06398    0.41052  -0.156   0.8762    
sexM               -1.37879    0.48280  -2.856   0.0044 ** 
STPresentTRUE:sexM -0.52662    0.58056  -0.907   0.3646    
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 3.922 on 852 degrees of freedom
Multiple R-squared:  0.04948,   Adjusted R-squared:  0.04613 
F-statistic: 14.78 on 3 and 852 DF,  p-value: 2.165e-09</code></pre>
</div>
</div>
<p>Here we find in the absence of stereotype activation, gender is a statistically significant predictor of grades as represented by p-values under 0.05 and higher p-values when ST is present. However, the overall model of presence of stereotype activation and gender are not significant in predicting grades with a p-value of 2.17. This model confirms earlier hypothesis testing results that mean predicted grades based on ST is not as significant but gender may play a role.</p>
</section>
<section id="model-2-and-3---predicted-grades-by-stereotype-activation-and-gender" class="level3">
<h3 class="anchored" data-anchor-id="model-2-and-3---predicted-grades-by-stereotype-activation-and-gender">Model 2 and 3 - Predicted Grades by Stereotype Activation and Gender</h3>
<p>The next two models address the second hypothesis and distinguishes the stereotype activation by type, adding the sex variable as both a second explanatory variable (model 2) and an interaction term (model 3).</p>
<div class="cell">
<details>
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb26"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb26-1"><a href="#cb26-1" aria-hidden="true" tabindex="-1"></a><span class="co">#model2 uses "sex" as explanatory variable</span></span>
<span id="cb26-2"><a href="#cb26-2" aria-hidden="true" tabindex="-1"></a>model2<span class="ot">&lt;-</span>(<span class="fu">lm</span>(PredictedGrade <span class="sc">~</span> StereotypeActivation <span class="sc">+</span> sex, <span class="at">data=</span>performance))</span>
<span id="cb26-3"><a href="#cb26-3" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(model2)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = PredictedGrade ~ StereotypeActivation + sex, data = performance)

Residuals:
     Min       1Q   Median       3Q      Max 
-13.5553  -2.8123   0.4447   3.1877   8.1877 

Coefficients:
                               Estimate Std. Error t value Pr(&gt;|t|)    
(Intercept)                     13.5553     0.2725  49.752  &lt; 2e-16 ***
StereotypeActivationNone         0.6874     0.3382   2.033   0.0424 *  
StereotypeActivationStatistics   0.6662     0.3228   2.064   0.0394 *  
sexM                            -1.7430     0.2676  -6.514 1.25e-10 ***
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 3.914 on 852 degrees of freedom
Multiple R-squared:  0.0533,    Adjusted R-squared:  0.04996 
F-statistic: 15.99 on 3 and 852 DF,  p-value: 4.046e-10</code></pre>
</div>
<details>
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb28"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb28-1"><a href="#cb28-1" aria-hidden="true" tabindex="-1"></a><span class="co">#model3 uses "sex" as interaction terms</span></span>
<span id="cb28-2"><a href="#cb28-2" aria-hidden="true" tabindex="-1"></a>model3<span class="ot">&lt;-</span> <span class="fu">lm</span>(PredictedGrade <span class="sc">~</span> StereotypeActivation <span class="sc">*</span> sex, <span class="at">data=</span>performance)</span>
<span id="cb28-3"><a href="#cb28-3" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(model3)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = PredictedGrade ~ StereotypeActivation * sex, data = performance)

Residuals:
     Min       1Q   Median       3Q      Max 
-13.4044  -2.9632   0.4091   3.0368   8.0368 

Coefficients:
                                    Estimate Std. Error t value Pr(&gt;|t|)    
(Intercept)                         13.40441    0.33554  39.948  &lt; 2e-16 ***
StereotypeActivationNone             0.65619    0.47811   1.372  0.17028    
StereotypeActivationStatistics       1.09559    0.45639   2.401  0.01658 *  
sexM                                -1.44118    0.47453  -3.037  0.00246 ** 
StereotypeActivationNone:sexM        0.06239    0.67615   0.092  0.92651    
StereotypeActivationStatistics:sexM -0.85882    0.64543  -1.331  0.18367    
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 3.913 on 850 degrees of freedom
Multiple R-squared:  0.05618,   Adjusted R-squared:  0.05063 
F-statistic: 10.12 on 5 and 850 DF,  p-value: 1.989e-09</code></pre>
</div>
<details>
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb30"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb30-1"><a href="#cb30-1" aria-hidden="true" tabindex="-1"></a><span class="co">#ANOVA of both models</span></span>
<span id="cb30-2"><a href="#cb30-2" aria-hidden="true" tabindex="-1"></a><span class="fu">anova</span>(model2, model3)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>Analysis of Variance Table

Model 1: PredictedGrade ~ StereotypeActivation + sex
Model 2: PredictedGrade ~ StereotypeActivation * sex
  Res.Df   RSS Df Sum of Sq      F Pr(&gt;F)
1    852 13055                           
2    850 13015  2    39.769 1.2986 0.2734</code></pre>
</div>
</div>
<p>In both models, there is a significance to introducing case based ST for both genders, negatively for male students and positively for female students. The use of statistics garnered less significance for both genders, however still significant for predicting mean grades for female students. Once again the highest predicted scores for males were under conditions when ST was not present.</p>
<p>Comparing the two models, results are similar and there is minimal increase in the R-squared (0.053 to 0.056) and adjusted R-squared (0.050 to 0.051) for using sex as an explanatory variable vs.&nbsp;an interaction term. Residuals are also lower in model 3 than for model 2. The analysis of variance for the two models also confirms this result with lower RSS for model 3, minimizing residuals in the model. Thus model 3 is a better fit than model two.</p>
</section>
<section id="model-4---predicted-grades-by-other-potential-explanatory-variables" class="level3">
<h3 class="anchored" data-anchor-id="model-4---predicted-grades-by-other-potential-explanatory-variables">Model 4 - Predicted Grades by Other Potential Explanatory Variables</h3>
<p>Until now, I investigated stereotype activation as the primary explanatory variable in predicting grades for both genders. However, in both my hypothesis testing and previous models, this variable was not significant in comparing scores with or without the presence of stereotype activation. This next model explores which of the other variables could explain this phenomena including gender as an interaction term.</p>
<p>Variables selected for exploration include:</p>
<p>-Studytime - weekly study time is categorized as 1= less than 2 hours, 2= 2-5 hours and 3= 5+ hours<br>
-Freetime - free time after school group as 1 = low, 2= medium, 3 = high<br>
-Goout - how often a student goes out with friends where 1 is very low and 4 is very often<br>
-Absences - number of school absences 1 - 7 where 7 represents any absences equal to or above 7<br>
-Walc - weekend alcohol consumption<br>
-Parents_edu - the higher of original variables mother’s edu and father’s edu, where 4 = the highest level of education</p>
<div class="cell">
<details>
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb32"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb32-1"><a href="#cb32-1" aria-hidden="true" tabindex="-1"></a>performance<span class="sc">%&gt;%</span></span>
<span id="cb32-2"><a href="#cb32-2" aria-hidden="true" tabindex="-1"></a><span class="fu">group_by</span>(sex)<span class="sc">%&gt;%</span></span>
<span id="cb32-3"><a href="#cb32-3" aria-hidden="true" tabindex="-1"></a><span class="fu">summarise</span>(<span class="fu">mean</span>(studytime), <span class="fu">mean</span>(freetime), <span class="fu">mean</span>(goout), <span class="fu">mean</span>(absences),<span class="fu">mean</span>(G3), <span class="fu">mean</span>(PredictedGrade))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 2 × 7
  sex   `mean(studytime)` `mean(freetime)` `mean(goout)` mean(…¹ mean(…² mean(…³
  &lt;chr&gt;             &lt;dbl&gt;            &lt;dbl&gt;         &lt;dbl&gt;   &lt;dbl&gt;   &lt;dbl&gt;   &lt;dbl&gt;
1 F                  2.07             2.07          2.99    2.70    12.1    14.0
2 M                  1.71             2.30          3.05    2.89    11.8    12.3
# … with abbreviated variable names ¹​`mean(absences)`, ²​`mean(G3)`,
#   ³​`mean(PredictedGrade)`</code></pre>
</div>
</div>
<p>The above tables summarize differences in the mean values for several variables of interest by gender. Here we see, female students score slightly higher in study time (2.07 vs.&nbsp;1.7) and while lower in free time (2.07 vs, 2.3), goout (3 vs.&nbsp;3.05), absences (2.7 vs.&nbsp;2.9). These would suggest female students may have a higher predicted grade based on good practices which is proven by the actual grades in G3 (12.15 vs.&nbsp;11.80). However, there is larger discrepancies in predicted rages (14.0 for females vs.&nbsp;12.28 for males).</p>
<div class="cell">
<details>
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb34"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb34-1"><a href="#cb34-1" aria-hidden="true" tabindex="-1"></a><span class="co">#model other variables as possible explanatory variables </span></span>
<span id="cb34-2"><a href="#cb34-2" aria-hidden="true" tabindex="-1"></a>model4 <span class="ot">&lt;-</span><span class="fu">lm</span>(PredictedGrade <span class="sc">~</span> (studytime <span class="sc">+</span> freetime <span class="sc">+</span> Walc <span class="sc">+</span> goout <span class="sc">+</span> Parents_edu <span class="sc">+</span> absences) <span class="sc">*</span> sex, <span class="at">data=</span>performance)</span>
<span id="cb34-3"><a href="#cb34-3" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(model4)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = PredictedGrade ~ (studytime + freetime + Walc + 
    goout + Parents_edu + absences) * sex, data = performance)

Residuals:
     Min       1Q   Median       3Q      Max 
-14.1916  -2.2127   0.2298   2.2908   9.5489 

Coefficients:
                 Estimate Std. Error t value Pr(&gt;|t|)    
(Intercept)      12.20702    0.90896  13.430  &lt; 2e-16 ***
studytime         1.70283    0.23838   7.143 1.97e-12 ***
freetime          0.32324    0.22396   1.443 0.149303    
Walc             -0.57563    0.16305  -3.530 0.000437 ***
goout            -0.43723    0.18408  -2.375 0.017763 *  
Parents_edu       0.40536    0.15127   2.680 0.007512 ** 
absences         -0.38691    0.05807  -6.663 4.83e-11 ***
sexM             -1.02714    1.30371  -0.788 0.431000    
studytime:sexM   -0.25917    0.33611  -0.771 0.440867    
freetime:sexM    -0.33562    0.30899  -1.086 0.277716    
Walc:sexM        -0.13419    0.22607  -0.594 0.552946    
goout:sexM        0.36529    0.27901   1.309 0.190810    
Parents_edu:sexM  0.29052    0.22058   1.317 0.188168    
absences:sexM    -0.07768    0.08359  -0.929 0.352963    
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 3.279 on 842 degrees of freedom
Multiple R-squared:  0.3435,    Adjusted R-squared:  0.3334 
F-statistic:  33.9 on 13 and 842 DF,  p-value: &lt; 2.2e-16</code></pre>
</div>
<details>
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb36"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb36-1"><a href="#cb36-1" aria-hidden="true" tabindex="-1"></a><span class="fu">anova</span>(model3, model4)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>Analysis of Variance Table

Model 1: PredictedGrade ~ StereotypeActivation * sex
Model 2: PredictedGrade ~ (studytime + freetime + Walc + goout + Parents_edu + 
    absences) * sex
  Res.Df     RSS Df Sum of Sq      F    Pr(&gt;F)    
1    850 13015.3                                  
2    842  9052.6  8    3962.7 46.073 &lt; 2.2e-16 ***
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1</code></pre>
</div>
<details>
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb38"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb38-1"><a href="#cb38-1" aria-hidden="true" tabindex="-1"></a><span class="co">#create matrix of model plots</span></span>
<span id="cb38-2"><a href="#cb38-2" aria-hidden="true" tabindex="-1"></a><span class="fu">par</span>(<span class="at">mfrow =</span> <span class="fu">c</span>(<span class="dv">2</span>,<span class="dv">3</span>)); <span class="fu">plot</span>(model4, <span class="at">which =</span> <span class="dv">1</span><span class="sc">:</span><span class="dv">6</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output-display">
<p><img src="KalimahMuhammad_finalpart2_v2_files/figure-html/model 4-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<p>In this final model, we find similar residuals to model 3 but a large increase in the R-squared (0.057 to 0.34), adjusted r-squared values (0.051 to 0.33) and F-statistic (10.12 on 5 to 33.9 on 13). Based on the p-values, we also note study time, weekly alcohol consumption, parents education, and number of absences as most significant in predicting mean grades. Female students scored slighly more favorably in each of these areas than male students accounting a slight increase in actual grades as well. Thus perhaps participants over-estimated these values in predicting grades.</p>
<p>Comparing model 4 to model 3 using analysis of variance, there is a significant reduction in RSS and increase in p-value significance suggesting the introduction of these behavioral variables as a better fit for predicting grades than the introduction of stereotype activation. Note that in diagnosis the model 4 there are issues in normality (see the Cook’s distance and Residuals vs.&nbsp;Leverage plots) as well as heteroskedasticity (see the Scale-Location plot). Since further evaluation of these variables are outside of the scope of this project, I will select model 3 for diagnostics.</p>
</section>
</section>
<section id="diagnostics" class="level2">
<h2 class="anchored" data-anchor-id="diagnostics">Diagnostics</h2>
<p>For this section, I will evaluate a few assumptions with model 3 which aimed to predict grades by the type of stereotype activation and the sex variable as an interaction term.</p>
<div class="cell">
<details>
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb39"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb39-1"><a href="#cb39-1" aria-hidden="true" tabindex="-1"></a><span class="co">#create matrix of model plots</span></span>
<span id="cb39-2"><a href="#cb39-2" aria-hidden="true" tabindex="-1"></a><span class="fu">par</span>(<span class="at">mfrow =</span> <span class="fu">c</span>(<span class="dv">2</span>,<span class="dv">3</span>)); <span class="fu">plot</span>(model3, <span class="at">which =</span> <span class="dv">1</span><span class="sc">:</span><span class="dv">6</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output-display">
<p><img src="KalimahMuhammad_finalpart2_v2_files/figure-html/diagnostics model 3-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<p><em>Normality of Errors -</em> In the Normal Q-Q plot, most observations fall close to the line assuming normality. Using the Cook’s Distance and Residuals vs.&nbsp;Leverage, we can assume residuals are mostly normal as well with the exception of observation #62 whose leverage makes it an influential observation.</p>
<p><em>Linearity -</em> Viewing the Residuals vs.&nbsp;Fitted plot, we see a relatively straight and horizontal line suggesting the average residual for the fitted values are relatively similar. Note, there are three observations, #62, #348, and #742 that are identified as outliers.</p>
<p><em>Equal Variance of Errors</em> - Although the Residuals vs.&nbsp;Fitted plot show a near equal variance of the error terms based on its straight and horizontal line, the Scale-Location plot shows a decreasing rather than flat trend as the fitted values increase.</p>
</section>
<section id="summary" class="level2">
<h2 class="anchored" data-anchor-id="summary">Summary</h2>
<p>In summary, stereotype activation has some influence in predicting higher scores for certain groups under certain conditions but was not a statistically significant predictor in grades for either male or female students based on this experiment. In this study, stereotypes favored female students over male students. Where this stereotype was present for both case based and statistic stereotypes, there was an increase in female predicted scores versus when ST was absent. Predictions for male grades also benefited from a higher predicted score when ST was absent. This does suggest there is some bias introduced with stereotype activation but not enough to be statistically significant in predicting grades.</p>
<p>A more robust model for predicting grades (model 4) incorporated student behavioral factors such as study time, weekly alcohol consumption, and number of school absences as well demographic factors such as parents education. Future research should further investigate these variables as well as test the inverse of the stereotype which would favor male students. Overall, participants generally predicted grades higher for both genders compared to actual but the average predicted scores were not statistically significant based on stereotype activation.</p>
<section id="sources" class="level4">
<h4 class="anchored" data-anchor-id="sources">Sources</h4>
<p>Bedyńska, S., Krejtz, I. &amp; Sedek, G. Chronic stereotype threat and mathematical achievement in age cohorts of secondary school girls: mediational role of working memory, and intellectual helplessness. Soc Psychol Educ 22, 321–335 (2019). https://doi.org/10.1007/s11218-019-09478-6</p>
<p>Bedyńska, S., Krejtz, I., Rycielski, P. et al.&nbsp;Stereotype threat as an antecedent to domain identification and achievement in language arts in boys: a cross-sectional study. Soc Psychol Educ 23, 755–771 (2020). https://doi.org/10.1007/s11218-020-09557-z</p>
<p>Booth MZ, Gerard JM. Self-esteem and academic achievement: a comparative study of adolescent students in England and the United States. Compare. 2011 Sep;41(5):629-648. doi: 10.1080/03057925.2011.566688</p>
<p>Cortez, P. and Silva, A. Using Data Mining to Predict Secondary School Student Performance. In A. Brito and J. Teixeira Eds., Proceedings of 5th FUture BUsiness TEChnology Conference (FUBUTEC 2008) pp.&nbsp;5-12, Porto, Portugal, April, 2008, EUROSIS, ISBN 978-9077381-39-7</p>
<p>Ganley, C. M., Mingle, L. A., Ryan, A. M., Ryan, K., Vasilyeva, M., &amp; Perry, M. (2013). An examination of stereotype threat effects on girls’ mathematics performance. Developmental Psychology, 49(10), 1886–1897. https://doi.org/10.1037/a0031412</p>
<p>Hyde, Janet Shibley. “Meta-analysis and the psychology of gender differences.” Signs: Journal of Women in Culture and Society 16.1 (1990): 55-73.</p>
<p>Johnson, H., Barnard-Brak, L., Saxon, T., &amp; Johnson, M.K. (2012) An Experimental Study of the Effects of Stereotype Threat and Stereotype Lift on Men and Women’s Performance in Mathematics, The Journal of Experimental Education, 80:2, 137-149, DOI: 10.1080/00220973.2011.567312</p>
<p>Moè, A., &amp; Putwain, D. W. (2020). An evaluative message fosters mathematics performance in male students but decreases intrinsic motivation in female students. Educational Psychology, 1–20. https://doi.org/10.1080/01443410.2020.1730767</p>
<p>Spinath, B., Harald Freudenthaler, H., &amp; Neubauer, A. C. (2010). Domain-specific school achievement in boys and girls as predicted by intelligence, personality and motivation. Personality and Individual Differences, 48(4), 481-486. https://doi.org/10.1016/j.paid.2009.11.028</p>
<p>Steele, Claude M., and Joshua Aronson. “Stereotype threat and the intellectual test performance of African Americans.” Journal of personality and social psychology 69.5 (1995): 797.</p>
<p>Warne, R. T. (2022). No Strong Evidence of Stereotype Threat in Females: A Reassessment of the Meta-Analysis. Journal of Advanced Academics, 33(2), 171–186. https://doi.org/10.1177/1932202X211061517</p>
<p>Data source: Anonymous. (2022). Performance vs.&nbsp;Predicted Performance[Data set]. Kaggle. https://doi.org/10.34740/KAGGLE/DSV/4282405</p>


<!-- -->

</section>
</section>

</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const disableStylesheet = (stylesheets) => {
    for (let i=0; i < stylesheets.length; i++) {
      const stylesheet = stylesheets[i];
      stylesheet.rel = 'prefetch';
    }
  }
  const enableStylesheet = (stylesheets) => {
    for (let i=0; i < stylesheets.length; i++) {
      const stylesheet = stylesheets[i];
      stylesheet.rel = 'stylesheet';
    }
  }
  const manageTransitions = (selector, allowTransitions) => {
    const els = window.document.querySelectorAll(selector);
    for (let i=0; i < els.length; i++) {
      const el = els[i];
      if (allowTransitions) {
        el.classList.remove('notransition');
      } else {
        el.classList.add('notransition');
      }
    }
  }
  const toggleColorMode = (alternate) => {
    // Switch the stylesheets
    const alternateStylesheets = window.document.querySelectorAll('link.quarto-color-scheme.quarto-color-alternate');
    manageTransitions('#quarto-margin-sidebar .nav-link', false);
    if (alternate) {
      enableStylesheet(alternateStylesheets);
      for (const sheetNode of alternateStylesheets) {
        if (sheetNode.id === "quarto-bootstrap") {
          toggleBodyColorMode(sheetNode);
        }
      }
    } else {
      disableStylesheet(alternateStylesheets);
      toggleBodyColorPrimary();
    }
    manageTransitions('#quarto-margin-sidebar .nav-link', true);
    // Switch the toggles
    const toggles = window.document.querySelectorAll('.quarto-color-scheme-toggle');
    for (let i=0; i < toggles.length; i++) {
      const toggle = toggles[i];
      if (toggle) {
        if (alternate) {
          toggle.classList.add("alternate");     
        } else {
          toggle.classList.remove("alternate");
        }
      }
    }
    // Hack to workaround the fact that safari doesn't
    // properly recolor the scrollbar when toggling (#1455)
    if (navigator.userAgent.indexOf('Safari') > 0 && navigator.userAgent.indexOf('Chrome') == -1) {
      manageTransitions("body", false);
      window.scrollTo(0, 1);
      setTimeout(() => {
        window.scrollTo(0, 0);
        manageTransitions("body", true);
      }, 40);  
    }
  }
  const isFileUrl = () => { 
    return window.location.protocol === 'file:';
  }
  const hasAlternateSentinel = () => {  
    let styleSentinel = getColorSchemeSentinel();
    if (styleSentinel !== null) {
      return styleSentinel === "alternate";
    } else {
      return false;
    }
  }
  const setStyleSentinel = (alternate) => {
    const value = alternate ? "alternate" : "default";
    if (!isFileUrl()) {
      window.localStorage.setItem("quarto-color-scheme", value);
    } else {
      localAlternateSentinel = value;
    }
  }
  const getColorSchemeSentinel = () => {
    if (!isFileUrl()) {
      const storageValue = window.localStorage.getItem("quarto-color-scheme");
      return storageValue != null ? storageValue : localAlternateSentinel;
    } else {
      return localAlternateSentinel;
    }
  }
  let localAlternateSentinel = 'default';
  // Dark / light mode switch
  window.quartoToggleColorScheme = () => {
    // Read the current dark / light value 
    let toAlternate = !hasAlternateSentinel();
    toggleColorMode(toAlternate);
    setStyleSentinel(toAlternate);
  };
  // Ensure there is a toggle, if there isn't float one in the top right
  if (window.document.querySelector('.quarto-color-scheme-toggle') === null) {
    const a = window.document.createElement('a');
    a.classList.add('top-right');
    a.classList.add('quarto-color-scheme-toggle');
    a.href = "";
    a.onclick = function() { try { window.quartoToggleColorScheme(); } catch {} return false; };
    const i = window.document.createElement("i");
    i.classList.add('bi');
    a.appendChild(i);
    window.document.body.appendChild(a);
  }
  // Switch to dark mode if need be
  if (hasAlternateSentinel()) {
    toggleColorMode(true);
  } else {
    toggleColorMode(false);
  }
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const clipboard = new window.ClipboardJS('.code-copy-button', {
    target: function(trigger) {
      return trigger.previousElementSibling;
    }
  });
  clipboard.on('success', function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copied!");
    let tooltip;
    if (window.bootstrap) {
      button.setAttribute("data-bs-toggle", "tooltip");
      button.setAttribute("data-bs-placement", "left");
      button.setAttribute("data-bs-title", "Copied!");
      tooltip = new bootstrap.Tooltip(button, 
        { trigger: "manual", 
          customClass: "code-copy-button-tooltip",
          offset: [0, -8]});
      tooltip.show();    
    }
    setTimeout(function() {
      if (tooltip) {
        tooltip.hide();
        button.removeAttribute("data-bs-title");
        button.removeAttribute("data-bs-toggle");
        button.removeAttribute("data-bs-placement");
      }
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  });
  const viewSource = window.document.getElementById('quarto-view-source') ||
                     window.document.getElementById('quarto-code-tools-source');
  if (viewSource) {
    const sourceUrl = viewSource.getAttribute("data-quarto-source-url");
    viewSource.addEventListener("click", function(e) {
      if (sourceUrl) {
        // rstudio viewer pane
        if (/\bcapabilities=\b/.test(window.location)) {
          window.open(sourceUrl);
        } else {
          window.location.href = sourceUrl;
        }
      } else {
        const modal = new bootstrap.Modal(document.getElementById('quarto-embedded-source-code-modal'));
        modal.show();
      }
      return false;
    });
  }
  function toggleCodeHandler(show) {
    return function(e) {
      const detailsSrc = window.document.querySelectorAll(".cell > details > .sourceCode");
      for (let i=0; i<detailsSrc.length; i++) {
        const details = detailsSrc[i].parentElement;
        if (show) {
          details.open = true;
        } else {
          details.removeAttribute("open");
        }
      }
      const cellCodeDivs = window.document.querySelectorAll(".cell > .sourceCode");
      const fromCls = show ? "hidden" : "unhidden";
      const toCls = show ? "unhidden" : "hidden";
      for (let i=0; i<cellCodeDivs.length; i++) {
        const codeDiv = cellCodeDivs[i];
        if (codeDiv.classList.contains(fromCls)) {
          codeDiv.classList.remove(fromCls);
          codeDiv.classList.add(toCls);
        } 
      }
      return false;
    }
  }
  const hideAllCode = window.document.getElementById("quarto-hide-all-code");
  if (hideAllCode) {
    hideAllCode.addEventListener("click", toggleCodeHandler(false));
  }
  const showAllCode = window.document.getElementById("quarto-show-all-code");
  if (showAllCode) {
    showAllCode.addEventListener("click", toggleCodeHandler(true));
  }
  function tippyHover(el, contentFn) {
    const config = {
      allowHTML: true,
      content: contentFn,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start'
    };
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      return note.innerHTML;
    });
  }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
});
</script>
<script src="https://giscus.app/client.js" data-repo="DACSS/603_Fall_2022" data-repo-id="R_kgDOH568kA" data-category="Announcements" data-category-id="" data-mapping="title" data-reactions-enabled="1" data-emit-metadata="0" data-input-position="top" data-theme="light" data-lang="en" crossorigin="anonymous" async="">
</script><div class="modal fade" id="quarto-embedded-source-code-modal" tabindex="-1" aria-labelledby="quarto-embedded-source-code-modal-label" aria-hidden="true"><div class="modal-dialog modal-dialog-scrollable"><div class="modal-content"><div class="modal-header"><h5 class="modal-title" id="quarto-embedded-source-code-modal-label">Source Code</h5><button class="btn-close" data-bs-dismiss="modal"></button></div><div class="modal-body"><div class="">
<div class="sourceCode" id="cb40" data-shortcodes="false"><pre class="sourceCode markdown code-with-copy"><code class="sourceCode markdown"><span id="cb40-1"><a href="#cb40-1" aria-hidden="true" tabindex="-1"></a><span class="co">---</span></span>
<span id="cb40-2"><a href="#cb40-2" aria-hidden="true" tabindex="-1"></a><span class="an">title:</span><span class="co"> "Final Pt.2: Updates"</span></span>
<span id="cb40-3"><a href="#cb40-3" aria-hidden="true" tabindex="-1"></a><span class="an">author:</span><span class="co"> "Kalimah Muhammad"</span></span>
<span id="cb40-4"><a href="#cb40-4" aria-hidden="true" tabindex="-1"></a><span class="an">desription:</span><span class="co"> "Updates to Final Part 2"</span></span>
<span id="cb40-5"><a href="#cb40-5" aria-hidden="true" tabindex="-1"></a><span class="an">date:</span><span class="co"> "12/02/2022"</span></span>
<span id="cb40-6"><a href="#cb40-6" aria-hidden="true" tabindex="-1"></a><span class="an">format:</span></span>
<span id="cb40-7"><a href="#cb40-7" aria-hidden="true" tabindex="-1"></a><span class="co">  html:</span></span>
<span id="cb40-8"><a href="#cb40-8" aria-hidden="true" tabindex="-1"></a><span class="co">    toc: true</span></span>
<span id="cb40-9"><a href="#cb40-9" aria-hidden="true" tabindex="-1"></a><span class="co">    code-fold: true</span></span>
<span id="cb40-10"><a href="#cb40-10" aria-hidden="true" tabindex="-1"></a><span class="co">    code-copy: true</span></span>
<span id="cb40-11"><a href="#cb40-11" aria-hidden="true" tabindex="-1"></a><span class="co">    code-tools: true </span></span>
<span id="cb40-12"><a href="#cb40-12" aria-hidden="true" tabindex="-1"></a><span class="an">categories:</span></span>
<span id="cb40-13"><a href="#cb40-13" aria-hidden="true" tabindex="-1"></a><span class="co">  - finalpt2</span></span>
<span id="cb40-14"><a href="#cb40-14" aria-hidden="true" tabindex="-1"></a><span class="co">  - Kalimah Muhammad</span></span>
<span id="cb40-15"><a href="#cb40-15" aria-hidden="true" tabindex="-1"></a><span class="co">---</span></span>
<span id="cb40-16"><a href="#cb40-16" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb40-19"><a href="#cb40-19" aria-hidden="true" tabindex="-1"></a><span class="in">```{r}</span></span>
<span id="cb40-20"><a href="#cb40-20" aria-hidden="true" tabindex="-1"></a><span class="co">#| label: setup</span></span>
<span id="cb40-21"><a href="#cb40-21" aria-hidden="true" tabindex="-1"></a><span class="co">#| warning: FALSE</span></span>
<span id="cb40-22"><a href="#cb40-22" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb40-23"><a href="#cb40-23" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(tidyverse)</span>
<span id="cb40-24"><a href="#cb40-24" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(dplyr)</span>
<span id="cb40-25"><a href="#cb40-25" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(ggplot2)</span>
<span id="cb40-26"><a href="#cb40-26" aria-hidden="true" tabindex="-1"></a>performance<span class="ot">&lt;-</span> <span class="fu">read_csv</span>(<span class="st">"_data/CompleteDataAndBiases.csv"</span>)</span>
<span id="cb40-27"><a href="#cb40-27" aria-hidden="true" tabindex="-1"></a>knitr<span class="sc">::</span>opts_chunk<span class="sc">$</span><span class="fu">set</span>(<span class="at">echo =</span> <span class="cn">TRUE</span>)</span>
<span id="cb40-28"><a href="#cb40-28" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb40-29"><a href="#cb40-29" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb40-30"><a href="#cb40-30" aria-hidden="true" tabindex="-1"></a><span class="fu">## Background</span></span>
<span id="cb40-31"><a href="#cb40-31" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb40-32"><a href="#cb40-32" aria-hidden="true" tabindex="-1"></a>Researchers have examined the differences impacting student achievement among genders for decades. Early meta-analyses conducted by Hyde (1990) revealed no significant difference between the groups' cognitive abilities; yet intelligence and self-perception of ability, or self-esteem, were determined as the strongest predictors of academic success (Spinath et al., 2010, Booth and Gerard, 2011). Some research explains differences in achievement partially by stereotype threat (ST). Stereotype threat, originally used to research the vulnerability of racial stereotypes on aptitude tests, is defined as "being at risk of confirming, as self-characteristic, a negative stereotype about one's group" (Steele and Aronson, 1995). Conventional research has focused on gender differences to stereotype threat (Moè &amp; Putwain, 2020), and two prevailing theories have emerged.</span>
<span id="cb40-33"><a href="#cb40-33" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb40-34"><a href="#cb40-34" aria-hidden="true" tabindex="-1"></a>The first theory suggests that ST affects male and female students differently. Here male students achieve better outcomes when stereotype threat is present than stereotype lift, and the reverse is true for female students who are adversely impacted by stereotype threat and positively impacted by stereotype lift (Johnson et al., 2012). Other studies debunk this theory suggesting no evidence of ST as a phenomenon in female students (Warne, 2022), particularly in the domain of mathematical achievement (Ganley et al., 2013). A second theory exists that the effects of ST may not be fully realized as outcomes immediately but affect achievement over time as chronic ST impacts working memory and intellectual helplessness in girls' math scores (Bedyńska, Krejtz, and Sedek, 2019) and male language arts scores (Bedyńska, Krejtz, and Sedek, 2020).</span>
<span id="cb40-35"><a href="#cb40-35" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb40-36"><a href="#cb40-36" aria-hidden="true" tabindex="-1"></a><span class="fu">## Research Questions</span></span>
<span id="cb40-37"><a href="#cb40-37" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb40-38"><a href="#cb40-38" aria-hidden="true" tabindex="-1"></a>This study tests both theories. First, it questions if there are differences in predicted student achievement based on gender when exposed to negative stereotypes about males and positive stereotypes about females. Second, it evaluates the effect of the perceived prevalence of stereotypes as shown by the participants' exposure to three types of stereotype activation in predicting grades. The types of stereotype activation include:</span>
<span id="cb40-39"><a href="#cb40-39" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb40-40"><a href="#cb40-40" aria-hidden="true" tabindex="-1"></a><span class="ss">-   </span>None: Participants were not exposed to stereotypes during this experiment.</span>
<span id="cb40-41"><a href="#cb40-41" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb40-42"><a href="#cb40-42" aria-hidden="true" tabindex="-1"></a><span class="ss">-   </span>Case-based: Participants were shown three student profiles in which one female student had a high grade, and two male students had low grades.</span>
<span id="cb40-43"><a href="#cb40-43" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb40-44"><a href="#cb40-44" aria-hidden="true" tabindex="-1"></a><span class="ss">-   </span>Statistics: Participants were shown statistics suggesting boys performed less well in school than girls.</span>
<span id="cb40-45"><a href="#cb40-45" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb40-46"><a href="#cb40-46" aria-hidden="true" tabindex="-1"></a>This study tests the following hypotheses:</span>
<span id="cb40-47"><a href="#cb40-47" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb40-48"><a href="#cb40-48" aria-hidden="true" tabindex="-1"></a>**H1.** Does exposure to negative stereotypes about male achievement (ST) and positive stereotypes of female achievement (SL) result in higher predicted achievement among both male and female students?</span>
<span id="cb40-49"><a href="#cb40-49" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb40-50"><a href="#cb40-50" aria-hidden="true" tabindex="-1"></a>**H2.** Was there a statistically significant difference between predicted male and female achievement based on the type of stereotype activation?</span>
<span id="cb40-51"><a href="#cb40-51" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb40-52"><a href="#cb40-52" aria-hidden="true" tabindex="-1"></a><span class="fu">## Data</span></span>
<span id="cb40-53"><a href="#cb40-53" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb40-54"><a href="#cb40-54" aria-hidden="true" tabindex="-1"></a>Data for this project was collected from Kaggle (Performance vs. Predicted Performance, 2022) and is a collection of existing student performance data from a study by Cortez and Silva (2008) on predicting secondary school student performance and the collector's addition of stereotype activation for machine learning. The data included information on actual student demographics such as gender, parents' highest level of education, as well as time studying vs. free time, number of absences, and grade on a final exam, among other variables.</span>
<span id="cb40-55"><a href="#cb40-55" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb40-56"><a href="#cb40-56" aria-hidden="true" tabindex="-1"></a>A few important variables to define include:\</span>
<span id="cb40-57"><a href="#cb40-57" aria-hidden="true" tabindex="-1"></a>-Index - number of students included in the original and predicted data (N=856 of the original 991 students)\</span>
<span id="cb40-58"><a href="#cb40-58" aria-hidden="true" tabindex="-1"></a>-Participant ID - number associated with participants making predictions (N=107)\</span>
<span id="cb40-59"><a href="#cb40-59" aria-hidden="true" tabindex="-1"></a>-Sex - student's sex (binary: 'F' - female or 'M' - male)\</span>
<span id="cb40-60"><a href="#cb40-60" aria-hidden="true" tabindex="-1"></a>-Studytime - weekly study time is categorized as 1= less than 2 hours, 2= 2-5 hours and 3= 5+ hours\</span>
<span id="cb40-61"><a href="#cb40-61" aria-hidden="true" tabindex="-1"></a>-Freetime - free time after school group as 1 = low, 2= medium, 3 = high\</span>
<span id="cb40-62"><a href="#cb40-62" aria-hidden="true" tabindex="-1"></a>-Goout - how often a student goes out with friends where 1 is very low and 4 is very often\</span>
<span id="cb40-63"><a href="#cb40-63" aria-hidden="true" tabindex="-1"></a>-Absences - number of school absences 1 - 7 where 7 represents any absences equal to or above 7\</span>
<span id="cb40-64"><a href="#cb40-64" aria-hidden="true" tabindex="-1"></a>-Walc - weekend alcohol consumption\</span>
<span id="cb40-65"><a href="#cb40-65" aria-hidden="true" tabindex="-1"></a>-Parents_edu - the higher of original variables mother's edu and father's edu, where 4 = the highest level of education\</span>
<span id="cb40-66"><a href="#cb40-66" aria-hidden="true" tabindex="-1"></a>-G3 - final grade (numeric: from 0 to 20)\</span>
<span id="cb40-67"><a href="#cb40-67" aria-hidden="true" tabindex="-1"></a>-Reason - The reason for why a student chose to go to the school in question. The levels are close to home, school's reputation, school's curricular and other\</span>
<span id="cb40-68"><a href="#cb40-68" aria-hidden="true" tabindex="-1"></a>-PredictedGrade - the grade participants predicted based on actual data and their exposed level of StereotypeActivation\</span>
<span id="cb40-69"><a href="#cb40-69" aria-hidden="true" tabindex="-1"></a>-StereotypeActivation - see three levels of stereotype activation above\</span>
<span id="cb40-70"><a href="#cb40-70" aria-hidden="true" tabindex="-1"></a>-Pass - A binary variable showing whether G3 is a passing grade (i.e. <span class="sc">\&gt;</span>=10) or not\</span>
<span id="cb40-71"><a href="#cb40-71" aria-hidden="true" tabindex="-1"></a>-PassFailStrategy - A binary variable showing whether the PredictedGrade is a passing grade (i.e. <span class="sc">\&gt;</span>=10) or not</span>
<span id="cb40-72"><a href="#cb40-72" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb40-73"><a href="#cb40-73" aria-hidden="true" tabindex="-1"></a>An additional variable I added to the data set, STPresent, identifies whether stereotype activation was present (True or False) for participants when predicting student scores.</span>
<span id="cb40-74"><a href="#cb40-74" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb40-75"><a href="#cb40-75" aria-hidden="true" tabindex="-1"></a>Below is a summary of the variables.</span>
<span id="cb40-76"><a href="#cb40-76" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb40-77"><a href="#cb40-77" aria-hidden="true" tabindex="-1"></a><span class="in">```{r, summary of data}</span></span>
<span id="cb40-78"><a href="#cb40-78" aria-hidden="true" tabindex="-1"></a><span class="co">#view top 5 observations</span></span>
<span id="cb40-79"><a href="#cb40-79" aria-hidden="true" tabindex="-1"></a><span class="fu">head</span>(performance, <span class="dv">10</span>)</span>
<span id="cb40-80"><a href="#cb40-80" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb40-81"><a href="#cb40-81" aria-hidden="true" tabindex="-1"></a><span class="co">#Add column that distinguishes if stereotype activation is present</span></span>
<span id="cb40-82"><a href="#cb40-82" aria-hidden="true" tabindex="-1"></a>performance <span class="ot">&lt;-</span>performance<span class="sc">%&gt;%</span></span>
<span id="cb40-83"><a href="#cb40-83" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">STPresent =</span> <span class="fu">case_when</span>(StereotypeActivation <span class="sc">==</span> <span class="st">"CaseBased"</span><span class="sc">|</span> StereotypeActivation <span class="sc">==</span> <span class="st">"Statistics"</span> <span class="sc">~</span> <span class="cn">TRUE</span>, StereotypeActivation<span class="sc">==</span><span class="st">"None"</span> <span class="sc">~</span> <span class="cn">FALSE</span>))</span>
<span id="cb40-84"><a href="#cb40-84" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb40-85"><a href="#cb40-85" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(performance)</span>
<span id="cb40-86"><a href="#cb40-86" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb40-87"><a href="#cb40-87" aria-hidden="true" tabindex="-1"></a><span class="co">#cross-tabulation of stereotype activation by gender </span></span>
<span id="cb40-88"><a href="#cb40-88" aria-hidden="true" tabindex="-1"></a><span class="fu">xtabs</span>(<span class="sc">~</span>sex <span class="sc">+</span> STPresent, performance)</span>
<span id="cb40-89"><a href="#cb40-89" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb40-90"><a href="#cb40-90" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb40-91"><a href="#cb40-91" aria-hidden="true" tabindex="-1"></a>There is an even distribution of male and female students (428 each), with 69% of participants exposed to some type of stereotype activation during grade prediction. The actual and predicted rate of passing are similar, 707 students passed versus the predicted 686, approximately 83% to 80% respectively. This may suggest other variables as strong indicators in passing. There is, however, a notable difference in the average actual scores (11.97) and predicted scores (13.14). This is further emphasized by the median actual scores (12) and predicted median (14). This early finding suggest that although the rate of passing was slightly lower, the overall predicted scores are skewed higher than actual.</span>
<span id="cb40-92"><a href="#cb40-92" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb40-93"><a href="#cb40-93" aria-hidden="true" tabindex="-1"></a>The next two graphs compare the actual final grade vs. the predicted grade for both genders.</span>
<span id="cb40-94"><a href="#cb40-94" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb40-95"><a href="#cb40-95" aria-hidden="true" tabindex="-1"></a><span class="in">```{r, plot actual and predicted performance}</span></span>
<span id="cb40-96"><a href="#cb40-96" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(performance, <span class="fu">aes</span>(<span class="at">x=</span>G3, <span class="at">fill=</span>sex))<span class="sc">+</span> <span class="fu">geom_histogram</span>(<span class="at">position =</span> <span class="st">"dodge"</span>)<span class="sc">+</span><span class="fu">labs</span>(<span class="at">x=</span><span class="st">"Students Actual Final Grade (G3)"</span>)</span>
<span id="cb40-97"><a href="#cb40-97" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(performance, <span class="fu">aes</span>(<span class="at">x=</span>PredictedGrade, <span class="at">fill=</span>sex))<span class="sc">+</span> <span class="fu">geom_histogram</span>(<span class="at">position =</span> <span class="st">"dodge"</span>)<span class="sc">+</span><span class="fu">labs</span>(<span class="at">x=</span><span class="st">"Students Predicted Final Grade (PredictedGrade)"</span>)</span>
<span id="cb40-98"><a href="#cb40-98" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb40-99"><a href="#cb40-99" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb40-100"><a href="#cb40-100" aria-hidden="true" tabindex="-1"></a>In the first graph, there is a fairly normal distribution of actual grades for both male and female students. Male students are more concentrated near the median value of 10 while female students are skewed slightly higher near the 11 value. However, in the second graph of predicted grades for both groups, female students are skewed significantly higher near 15 points while predictions for male students spreads near 12 points. This study will investigate if stereotype activation is a possible explanation for this variance.</span>
<span id="cb40-101"><a href="#cb40-101" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb40-102"><a href="#cb40-102" aria-hidden="true" tabindex="-1"></a><span class="in">```{r, boxplot of grades by ST presence}</span></span>
<span id="cb40-103"><a href="#cb40-103" aria-hidden="true" tabindex="-1"></a><span class="co">#boxplot of predicted grades by gender and if stereotype activation is present</span></span>
<span id="cb40-104"><a href="#cb40-104" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(performance, <span class="fu">aes</span>(<span class="at">x=</span>STPresent, <span class="at">y=</span>PredictedGrade, <span class="at">fill=</span>sex))<span class="sc">+</span></span>
<span id="cb40-105"><a href="#cb40-105" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_boxplot</span>()<span class="sc">+</span></span>
<span id="cb40-106"><a href="#cb40-106" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme</span>(<span class="at">legend.position=</span><span class="st">"none"</span>) <span class="sc">+</span></span>
<span id="cb40-107"><a href="#cb40-107" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ggtitle</span>(<span class="st">"Predicted Grades by Gender and Presence of Stereotype Activation"</span>)</span>
<span id="cb40-108"><a href="#cb40-108" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb40-109"><a href="#cb40-109" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb40-110"><a href="#cb40-110" aria-hidden="true" tabindex="-1"></a>The chart above shows more variability in predicted grades for female students without any stereotype activation; yet once present, the concentration of scores skews higher. For male students, predicted scores increased in the presence of stereotype activation accounting for more low scores. Note, male scores were overall predicted lower than females independent of stereotype activation. Is there another variable contributing to this difference?</span>
<span id="cb40-111"><a href="#cb40-111" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb40-112"><a href="#cb40-112" aria-hidden="true" tabindex="-1"></a><span class="fu">## Hypothesis Testing</span></span>
<span id="cb40-113"><a href="#cb40-113" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb40-114"><a href="#cb40-114" aria-hidden="true" tabindex="-1"></a><span class="fu">### *H1. Does exposure to negative stereotypes about male achievement (ST) and positive stereotypes of female achievement (SL) result in differences in predicted achievement among both male and female students?*</span></span>
<span id="cb40-115"><a href="#cb40-115" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb40-116"><a href="#cb40-116" aria-hidden="true" tabindex="-1"></a>Here the dependent variable is the predicted grade and independent variable is presence of stereotype threat. The Null hypothesis states stereotype activation does not have a statistically significant effect on predicted grades for male and female students and the alternative hypothesis is negative stereotypes about male achievement and positive stereotypes of female achievement result in changes in predicted grades among both male and female students.</span>
<span id="cb40-117"><a href="#cb40-117" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb40-118"><a href="#cb40-118" aria-hidden="true" tabindex="-1"></a>I conducted a two directional, two sample t-test to investigate the differences in the mean predicted score for students with it labeled "TRUE" and without stereotype activation labeled "FALSE".</span>
<span id="cb40-119"><a href="#cb40-119" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb40-120"><a href="#cb40-120" aria-hidden="true" tabindex="-1"></a><span class="in">```{r, t-test 1}</span></span>
<span id="cb40-121"><a href="#cb40-121" aria-hidden="true" tabindex="-1"></a><span class="fu">t.test</span>(PredictedGrade <span class="sc">~</span> STPresent, <span class="at">data=</span> performance, <span class="at">alternative =</span> <span class="fu">c</span>(<span class="st">"two.sided"</span>), <span class="at">var.equal =</span> <span class="cn">FALSE</span>, <span class="at">conf.level =</span> <span class="fl">0.95</span>)</span>
<span id="cb40-122"><a href="#cb40-122" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb40-123"><a href="#cb40-123" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb40-124"><a href="#cb40-124" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb40-125"><a href="#cb40-125" aria-hidden="true" tabindex="-1"></a>Although the mean predicted grades for those not exposed to ST are higher (13.37) compared to those where ST was present (13.04), the resulting p-value of 0.26, renders this test not significant in the predicted grades based on if stereotype activation was present. Thus, the null was retained.</span>
<span id="cb40-126"><a href="#cb40-126" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb40-127"><a href="#cb40-127" aria-hidden="true" tabindex="-1"></a>The next test isolates predicted grades for male students only.</span>
<span id="cb40-128"><a href="#cb40-128" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb40-129"><a href="#cb40-129" aria-hidden="true" tabindex="-1"></a><span class="in">```{r, t-test male}</span></span>
<span id="cb40-130"><a href="#cb40-130" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb40-131"><a href="#cb40-131" aria-hidden="true" tabindex="-1"></a><span class="co">#create two tables for female students and male students</span></span>
<span id="cb40-132"><a href="#cb40-132" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb40-133"><a href="#cb40-133" aria-hidden="true" tabindex="-1"></a>m_performance<span class="ot">&lt;-</span>performance<span class="sc">%&gt;%</span></span>
<span id="cb40-134"><a href="#cb40-134" aria-hidden="true" tabindex="-1"></a>  <span class="fu">filter</span>(sex<span class="sc">==</span><span class="st">"M"</span>)</span>
<span id="cb40-135"><a href="#cb40-135" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb40-136"><a href="#cb40-136" aria-hidden="true" tabindex="-1"></a><span class="co">#t.test for difference in mean of predicted grades for males with and without ST present</span></span>
<span id="cb40-137"><a href="#cb40-137" aria-hidden="true" tabindex="-1"></a><span class="co">#null hypothesis - mean of predicted grades is equals the mean of actual grades</span></span>
<span id="cb40-138"><a href="#cb40-138" aria-hidden="true" tabindex="-1"></a><span class="fu">t.test</span>(PredictedGrade <span class="sc">~</span> STPresent, <span class="at">data=</span> m_performance, <span class="at">alternative =</span> <span class="fu">c</span>(<span class="st">"two.sided"</span>), <span class="at">conf.level =</span> <span class="fl">0.95</span>)</span>
<span id="cb40-139"><a href="#cb40-139" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb40-140"><a href="#cb40-140" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb40-141"><a href="#cb40-141" aria-hidden="true" tabindex="-1"></a>The following test isolates predicted grades for female students only.</span>
<span id="cb40-142"><a href="#cb40-142" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb40-143"><a href="#cb40-143" aria-hidden="true" tabindex="-1"></a><span class="in">```{r, t-test female}</span></span>
<span id="cb40-144"><a href="#cb40-144" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb40-145"><a href="#cb40-145" aria-hidden="true" tabindex="-1"></a><span class="co">#create two tables for female students and male students</span></span>
<span id="cb40-146"><a href="#cb40-146" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb40-147"><a href="#cb40-147" aria-hidden="true" tabindex="-1"></a>m_performance<span class="ot">&lt;-</span>performance<span class="sc">%&gt;%</span></span>
<span id="cb40-148"><a href="#cb40-148" aria-hidden="true" tabindex="-1"></a>  <span class="fu">filter</span>(sex<span class="sc">==</span><span class="st">"F"</span>)</span>
<span id="cb40-149"><a href="#cb40-149" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb40-150"><a href="#cb40-150" aria-hidden="true" tabindex="-1"></a><span class="co">#t.test for difference in mean of predicted grades for males with and without ST present</span></span>
<span id="cb40-151"><a href="#cb40-151" aria-hidden="true" tabindex="-1"></a><span class="co">#null hypothesis - mean of predicted grades is equals the mean of actual grades</span></span>
<span id="cb40-152"><a href="#cb40-152" aria-hidden="true" tabindex="-1"></a><span class="fu">t.test</span>(PredictedGrade <span class="sc">~</span> STPresent, <span class="at">data=</span> f_performance, <span class="at">alternative =</span> <span class="fu">c</span>(<span class="st">"two.sided"</span>), <span class="at">conf.level =</span> <span class="fl">0.95</span>)</span>
<span id="cb40-153"><a href="#cb40-153" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb40-154"><a href="#cb40-154" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb40-155"><a href="#cb40-155" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb40-156"><a href="#cb40-156" aria-hidden="true" tabindex="-1"></a>Both tests have a p-value higher than 0.05 denoting that neither gender experienced a statistically significant difference in predicted average grades based on exposure to stereotype activation or not. Further rejecting hypothesis one.</span>
<span id="cb40-157"><a href="#cb40-157" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb40-158"><a href="#cb40-158" aria-hidden="true" tabindex="-1"></a><span class="fu">### H2. *Was there a statistically significant difference between predicted male and female achievement based on the type of stereotype activation?*</span></span>
<span id="cb40-159"><a href="#cb40-159" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb40-160"><a href="#cb40-160" aria-hidden="true" tabindex="-1"></a>The graph below calculates the mean predicted grade for both groups based on the type of stereotype activation.</span>
<span id="cb40-161"><a href="#cb40-161" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb40-162"><a href="#cb40-162" aria-hidden="true" tabindex="-1"></a><span class="in">```{r, mean of predicted v. actual grades}</span></span>
<span id="cb40-163"><a href="#cb40-163" aria-hidden="true" tabindex="-1"></a>performance<span class="sc">%&gt;%</span></span>
<span id="cb40-164"><a href="#cb40-164" aria-hidden="true" tabindex="-1"></a><span class="fu">group_by</span>(sex, StereotypeActivation)<span class="sc">%&gt;%</span></span>
<span id="cb40-165"><a href="#cb40-165" aria-hidden="true" tabindex="-1"></a><span class="fu">summarise</span>(<span class="fu">mean</span>(PredictedGrade), <span class="fu">mean</span>(G3), <span class="fu">mean</span>(PredictedGrade)<span class="sc">-</span><span class="fu">mean</span>(G3))</span>
<span id="cb40-166"><a href="#cb40-166" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb40-167"><a href="#cb40-167" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb40-168"><a href="#cb40-168" aria-hidden="true" tabindex="-1"></a>In the summary above, participants ranked the average predicted scores higher overall than the actual scores irrespective of gender or stereotype activation. The difference in predicted versus actual score was greatest among female students. Here participants exposed to the stereotype statistics predicted the widest difference compared to actual scores (2.47) and the highest overall scores (14.5).</span>
<span id="cb40-169"><a href="#cb40-169" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb40-170"><a href="#cb40-170" aria-hidden="true" tabindex="-1"></a>For male students, predictions were closer to the average actual performance (11.80) ranging at a difference of 0.16 - 0.88 points. With no stereotype activation, males students garnered their highest predicted average at 12.68 suggesting introducing stereotypes negatively affected predictions in male students although still higher than actual performance. For female students, introducing statistics of lower male performance than females garnered the highest grade prediction for female students. For both genders, case based stereotype activation which included one example of a high female score and two examples of lower male scores produced the lowest predicted grades.</span>
<span id="cb40-171"><a href="#cb40-171" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb40-172"><a href="#cb40-172" aria-hidden="true" tabindex="-1"></a><span class="in">```{r, pairwise}</span></span>
<span id="cb40-173"><a href="#cb40-173" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb40-174"><a href="#cb40-174" aria-hidden="true" tabindex="-1"></a><span class="fu">pairwise.t.test</span>(<span class="at">x=</span> performance<span class="sc">$</span>PredictedGrade, <span class="at">g=</span>performance<span class="sc">$</span>StereotypeActivation, <span class="at">p.adjust.method =</span> <span class="st">"none"</span>)</span>
<span id="cb40-175"><a href="#cb40-175" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb40-176"><a href="#cb40-176" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb40-177"><a href="#cb40-177" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb40-178"><a href="#cb40-178" aria-hidden="true" tabindex="-1"></a>This may suggest that other variables in the study have an influential role in predicting scores outside of stereotype activation.</span>
<span id="cb40-179"><a href="#cb40-179" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb40-180"><a href="#cb40-180" aria-hidden="true" tabindex="-1"></a><span class="fu">## Model Comparison</span></span>
<span id="cb40-181"><a href="#cb40-181" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb40-182"><a href="#cb40-182" aria-hidden="true" tabindex="-1"></a><span class="fu">### Model 1 - Predicted Grades and Presence of Stereotype Activation</span></span>
<span id="cb40-183"><a href="#cb40-183" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb40-184"><a href="#cb40-184" aria-hidden="true" tabindex="-1"></a>In the first model, I will use PredictedGrade as the outcome or dependent variable and the STPresent variable as the explanatory or independent variable adding in student sex as an interaction term.</span>
<span id="cb40-185"><a href="#cb40-185" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb40-186"><a href="#cb40-186" aria-hidden="true" tabindex="-1"></a><span class="in">```{r, model 1}</span></span>
<span id="cb40-187"><a href="#cb40-187" aria-hidden="true" tabindex="-1"></a>model1<span class="ot">&lt;-</span> (<span class="fu">lm</span>(PredictedGrade <span class="sc">~</span> STPresent <span class="sc">*</span> sex, <span class="at">data=</span>performance))</span>
<span id="cb40-188"><a href="#cb40-188" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(model1)</span>
<span id="cb40-189"><a href="#cb40-189" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb40-190"><a href="#cb40-190" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb40-191"><a href="#cb40-191" aria-hidden="true" tabindex="-1"></a>Here we find in the absence of stereotype activation, gender is a statistically significant predictor of grades as represented by p-values under 0.05 and higher p-values when ST is present. However, the overall model of presence of stereotype activation and gender are not significant in predicting grades with a p-value of 2.17. This model confirms earlier hypothesis testing results that mean predicted grades based on ST is not as significant but gender may play a role.</span>
<span id="cb40-192"><a href="#cb40-192" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb40-193"><a href="#cb40-193" aria-hidden="true" tabindex="-1"></a><span class="fu">### Model 2 and 3 - Predicted Grades by Stereotype Activation and Gender</span></span>
<span id="cb40-194"><a href="#cb40-194" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb40-195"><a href="#cb40-195" aria-hidden="true" tabindex="-1"></a>The next two models address the second hypothesis and distinguishes the stereotype activation by type, adding the sex variable as both a second explanatory variable (model 2) and an interaction term (model 3).</span>
<span id="cb40-196"><a href="#cb40-196" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb40-197"><a href="#cb40-197" aria-hidden="true" tabindex="-1"></a><span class="in">```{r, model 2 and 3}</span></span>
<span id="cb40-198"><a href="#cb40-198" aria-hidden="true" tabindex="-1"></a><span class="co">#model2 uses "sex" as explanatory variable</span></span>
<span id="cb40-199"><a href="#cb40-199" aria-hidden="true" tabindex="-1"></a>model2<span class="ot">&lt;-</span>(<span class="fu">lm</span>(PredictedGrade <span class="sc">~</span> StereotypeActivation <span class="sc">+</span> sex, <span class="at">data=</span>performance))</span>
<span id="cb40-200"><a href="#cb40-200" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(model2)</span>
<span id="cb40-201"><a href="#cb40-201" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb40-202"><a href="#cb40-202" aria-hidden="true" tabindex="-1"></a><span class="co">#model3 uses "sex" as interaction terms</span></span>
<span id="cb40-203"><a href="#cb40-203" aria-hidden="true" tabindex="-1"></a>model3<span class="ot">&lt;-</span> <span class="fu">lm</span>(PredictedGrade <span class="sc">~</span> StereotypeActivation <span class="sc">*</span> sex, <span class="at">data=</span>performance)</span>
<span id="cb40-204"><a href="#cb40-204" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(model3)</span>
<span id="cb40-205"><a href="#cb40-205" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb40-206"><a href="#cb40-206" aria-hidden="true" tabindex="-1"></a><span class="co">#ANOVA of both models</span></span>
<span id="cb40-207"><a href="#cb40-207" aria-hidden="true" tabindex="-1"></a><span class="fu">anova</span>(model2, model3)</span>
<span id="cb40-208"><a href="#cb40-208" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb40-209"><a href="#cb40-209" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb40-210"><a href="#cb40-210" aria-hidden="true" tabindex="-1"></a>In both models, there is a significance to introducing case based ST for both genders, negatively for male students and positively for female students. The use of statistics garnered less significance for both genders, however still significant for predicting mean grades for female students. Once again the highest predicted scores for males were under conditions when ST was not present.</span>
<span id="cb40-211"><a href="#cb40-211" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb40-212"><a href="#cb40-212" aria-hidden="true" tabindex="-1"></a>Comparing the two models, results are similar and there is minimal increase in the R-squared (0.053 to 0.056) and adjusted R-squared (0.050 to 0.051) for using sex as an explanatory variable vs. an interaction term. Residuals are also lower in model 3 than for model 2. The analysis of variance for the two models also confirms this result with lower RSS for model 3, minimizing residuals in the model. Thus model 3 is a better fit than model two.</span>
<span id="cb40-213"><a href="#cb40-213" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb40-214"><a href="#cb40-214" aria-hidden="true" tabindex="-1"></a><span class="fu">### Model 4 - Predicted Grades by Other Potential Explanatory Variables</span></span>
<span id="cb40-215"><a href="#cb40-215" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb40-216"><a href="#cb40-216" aria-hidden="true" tabindex="-1"></a>Until now, I investigated stereotype activation as the primary explanatory variable in predicting grades for both genders. However, in both my hypothesis testing and previous models, this variable was not significant in comparing scores with or without the presence of stereotype activation. This next model explores which of the other variables could explain this phenomena including gender as an interaction term.</span>
<span id="cb40-217"><a href="#cb40-217" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb40-218"><a href="#cb40-218" aria-hidden="true" tabindex="-1"></a>Variables selected for exploration include:</span>
<span id="cb40-219"><a href="#cb40-219" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb40-220"><a href="#cb40-220" aria-hidden="true" tabindex="-1"></a>-Studytime - weekly study time is categorized as 1= less than 2 hours, 2= 2-5 hours and 3= 5+ hours\</span>
<span id="cb40-221"><a href="#cb40-221" aria-hidden="true" tabindex="-1"></a>-Freetime - free time after school group as 1 = low, 2= medium, 3 = high\</span>
<span id="cb40-222"><a href="#cb40-222" aria-hidden="true" tabindex="-1"></a>-Goout - how often a student goes out with friends where 1 is very low and 4 is very often\</span>
<span id="cb40-223"><a href="#cb40-223" aria-hidden="true" tabindex="-1"></a>-Absences - number of school absences 1 - 7 where 7 represents any absences equal to or above 7\</span>
<span id="cb40-224"><a href="#cb40-224" aria-hidden="true" tabindex="-1"></a>-Walc - weekend alcohol consumption\</span>
<span id="cb40-225"><a href="#cb40-225" aria-hidden="true" tabindex="-1"></a>-Parents_edu - the higher of original variables mother's edu and father's edu, where 4 = the highest level of education</span>
<span id="cb40-226"><a href="#cb40-226" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb40-227"><a href="#cb40-227" aria-hidden="true" tabindex="-1"></a><span class="in">```{r, summary other variables}</span></span>
<span id="cb40-228"><a href="#cb40-228" aria-hidden="true" tabindex="-1"></a>performance<span class="sc">%&gt;%</span></span>
<span id="cb40-229"><a href="#cb40-229" aria-hidden="true" tabindex="-1"></a><span class="fu">group_by</span>(sex)<span class="sc">%&gt;%</span></span>
<span id="cb40-230"><a href="#cb40-230" aria-hidden="true" tabindex="-1"></a><span class="fu">summarise</span>(<span class="fu">mean</span>(studytime), <span class="fu">mean</span>(freetime), <span class="fu">mean</span>(goout), <span class="fu">mean</span>(absences),<span class="fu">mean</span>(G3), <span class="fu">mean</span>(PredictedGrade))</span>
<span id="cb40-231"><a href="#cb40-231" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb40-232"><a href="#cb40-232" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb40-233"><a href="#cb40-233" aria-hidden="true" tabindex="-1"></a>The above tables summarize differences in the mean values for several variables of interest by gender. Here we see, female students score slightly higher in study time (2.07 vs. 1.7) and while lower in free time (2.07 vs, 2.3), goout (3 vs. 3.05), absences (2.7 vs. 2.9). These would suggest female students may have a higher predicted grade based on good practices which is proven by the actual grades in G3 (12.15 vs. 11.80). However, there is larger discrepancies in predicted rages (14.0 for females vs. 12.28 for males).</span>
<span id="cb40-234"><a href="#cb40-234" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb40-235"><a href="#cb40-235" aria-hidden="true" tabindex="-1"></a><span class="in">```{r, model 4}</span></span>
<span id="cb40-236"><a href="#cb40-236" aria-hidden="true" tabindex="-1"></a><span class="co">#model other variables as possible explanatory variables </span></span>
<span id="cb40-237"><a href="#cb40-237" aria-hidden="true" tabindex="-1"></a>model4 <span class="ot">&lt;-</span><span class="fu">lm</span>(PredictedGrade <span class="sc">~</span> (studytime <span class="sc">+</span> freetime <span class="sc">+</span> Walc <span class="sc">+</span> goout <span class="sc">+</span> Parents_edu <span class="sc">+</span> absences) <span class="sc">*</span> sex, <span class="at">data=</span>performance)</span>
<span id="cb40-238"><a href="#cb40-238" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(model4)</span>
<span id="cb40-239"><a href="#cb40-239" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb40-240"><a href="#cb40-240" aria-hidden="true" tabindex="-1"></a><span class="fu">anova</span>(model3, model4)</span>
<span id="cb40-241"><a href="#cb40-241" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb40-242"><a href="#cb40-242" aria-hidden="true" tabindex="-1"></a><span class="co">#create matrix of model plots</span></span>
<span id="cb40-243"><a href="#cb40-243" aria-hidden="true" tabindex="-1"></a><span class="fu">par</span>(<span class="at">mfrow =</span> <span class="fu">c</span>(<span class="dv">2</span>,<span class="dv">3</span>)); <span class="fu">plot</span>(model4, <span class="at">which =</span> <span class="dv">1</span><span class="sc">:</span><span class="dv">6</span>)</span>
<span id="cb40-244"><a href="#cb40-244" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb40-245"><a href="#cb40-245" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb40-246"><a href="#cb40-246" aria-hidden="true" tabindex="-1"></a>In this final model, we find similar residuals to model 3 but a large increase in the R-squared (0.057 to 0.34), adjusted r-squared values (0.051 to 0.33) and F-statistic (10.12 on 5 to 33.9 on 13). Based on the p-values, we also note study time, weekly alcohol consumption, parents education, and number of absences as most significant in predicting mean grades. Female students scored slighly more favorably in each of these areas than male students accounting a slight increase in actual grades as well. Thus perhaps participants over-estimated these values in predicting grades.</span>
<span id="cb40-247"><a href="#cb40-247" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb40-248"><a href="#cb40-248" aria-hidden="true" tabindex="-1"></a>Comparing model 4 to model 3 using analysis of variance, there is a significant reduction in RSS and increase in p-value significance suggesting the introduction of these behavioral variables as a better fit for predicting grades than the introduction of stereotype activation. Note that in diagnosis the model 4 there are issues in normality (see the Cook's distance and Residuals vs. Leverage plots) as well as heteroskedasticity (see the Scale-Location plot). Since further evaluation of these variables are outside of the scope of this project, I will select model 3 for diagnostics.</span>
<span id="cb40-249"><a href="#cb40-249" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb40-250"><a href="#cb40-250" aria-hidden="true" tabindex="-1"></a><span class="fu">## Diagnostics</span></span>
<span id="cb40-251"><a href="#cb40-251" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb40-252"><a href="#cb40-252" aria-hidden="true" tabindex="-1"></a>For this section, I will evaluate a few assumptions with model 3 which aimed to predict grades by the type of stereotype activation and the sex variable as an interaction term.</span>
<span id="cb40-253"><a href="#cb40-253" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb40-254"><a href="#cb40-254" aria-hidden="true" tabindex="-1"></a><span class="in">```{r, diagnostics model 3}</span></span>
<span id="cb40-255"><a href="#cb40-255" aria-hidden="true" tabindex="-1"></a><span class="co">#create matrix of model plots</span></span>
<span id="cb40-256"><a href="#cb40-256" aria-hidden="true" tabindex="-1"></a><span class="fu">par</span>(<span class="at">mfrow =</span> <span class="fu">c</span>(<span class="dv">2</span>,<span class="dv">3</span>)); <span class="fu">plot</span>(model3, <span class="at">which =</span> <span class="dv">1</span><span class="sc">:</span><span class="dv">6</span>)</span>
<span id="cb40-257"><a href="#cb40-257" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb40-258"><a href="#cb40-258" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb40-259"><a href="#cb40-259" aria-hidden="true" tabindex="-1"></a>*Normality of Errors -* In the Normal Q-Q plot, most observations fall close to the line assuming normality. Using the Cook's Distance and Residuals vs. Leverage, we can assume residuals are mostly normal as well with the exception of observation #62 whose leverage makes it an influential observation.</span>
<span id="cb40-260"><a href="#cb40-260" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb40-261"><a href="#cb40-261" aria-hidden="true" tabindex="-1"></a>*Linearity -* Viewing the Residuals vs. Fitted plot, we see a relatively straight and horizontal line suggesting the average residual for the fitted values are relatively similar. Note, there are three observations, #62, #348, and #742 that are identified as outliers.</span>
<span id="cb40-262"><a href="#cb40-262" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb40-263"><a href="#cb40-263" aria-hidden="true" tabindex="-1"></a>*Equal Variance of Errors* - Although the Residuals vs. Fitted plot show a near equal variance of the error terms based on its straight and horizontal line, the Scale-Location plot shows a decreasing rather than flat trend as the fitted values increase.</span>
<span id="cb40-264"><a href="#cb40-264" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb40-265"><a href="#cb40-265" aria-hidden="true" tabindex="-1"></a><span class="fu">## Summary</span></span>
<span id="cb40-266"><a href="#cb40-266" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb40-267"><a href="#cb40-267" aria-hidden="true" tabindex="-1"></a>In summary, stereotype activation has some influence in predicting higher scores for certain groups under certain conditions but was not a statistically significant predictor in grades for either male or female students based on this experiment. In this study, stereotypes favored female students over male students. Where this stereotype was present for both case based and statistic stereotypes, there was an increase in female predicted scores versus when ST was absent. Predictions for male grades also benefited from a higher predicted score when ST was absent. This does suggest there is some bias introduced with stereotype activation but not enough to be statistically significant in predicting grades.</span>
<span id="cb40-268"><a href="#cb40-268" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb40-269"><a href="#cb40-269" aria-hidden="true" tabindex="-1"></a>A more robust model for predicting grades (model 4) incorporated student behavioral factors such as study time, weekly alcohol consumption, and number of school absences as well demographic factors such as parents education. Future research should further investigate these variables as well as test the inverse of the stereotype which would favor male students. Overall, participants generally predicted grades higher for both genders compared to actual but the average predicted scores were not statistically significant based on stereotype activation.</span>
<span id="cb40-270"><a href="#cb40-270" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb40-271"><a href="#cb40-271" aria-hidden="true" tabindex="-1"></a><span class="fu">#### Sources</span></span>
<span id="cb40-272"><a href="#cb40-272" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb40-273"><a href="#cb40-273" aria-hidden="true" tabindex="-1"></a>Bedyńska, S., Krejtz, I. &amp; Sedek, G. Chronic stereotype threat and mathematical achievement in age cohorts of secondary school girls: mediational role of working memory, and intellectual helplessness. Soc Psychol Educ 22, 321--335 (2019). https://doi.org/10.1007/s11218-019-09478-6</span>
<span id="cb40-274"><a href="#cb40-274" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb40-275"><a href="#cb40-275" aria-hidden="true" tabindex="-1"></a>Bedyńska, S., Krejtz, I., Rycielski, P. et al. Stereotype threat as an antecedent to domain identification and achievement in language arts in boys: a cross-sectional study. Soc Psychol Educ 23, 755--771 (2020). https://doi.org/10.1007/s11218-020-09557-z</span>
<span id="cb40-276"><a href="#cb40-276" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb40-277"><a href="#cb40-277" aria-hidden="true" tabindex="-1"></a>Booth MZ, Gerard JM. Self-esteem and academic achievement: a comparative study of adolescent students in England and the United States. Compare. 2011 Sep;41(5):629-648. doi: 10.1080/03057925.2011.566688</span>
<span id="cb40-278"><a href="#cb40-278" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb40-279"><a href="#cb40-279" aria-hidden="true" tabindex="-1"></a>Cortez, P. and Silva, A. Using Data Mining to Predict Secondary School Student Performance. In A. Brito and J. Teixeira Eds., Proceedings of 5th FUture BUsiness TEChnology Conference (FUBUTEC 2008) pp. 5-12, Porto, Portugal, April, 2008, EUROSIS, ISBN 978-9077381-39-7</span>
<span id="cb40-280"><a href="#cb40-280" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb40-281"><a href="#cb40-281" aria-hidden="true" tabindex="-1"></a>Ganley, C. M., Mingle, L. A., Ryan, A. M., Ryan, K., Vasilyeva, M., &amp; Perry, M. (2013). An examination of stereotype threat effects on girls' mathematics performance. Developmental Psychology, 49(10), 1886--1897. https://doi.org/10.1037/a0031412</span>
<span id="cb40-282"><a href="#cb40-282" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb40-283"><a href="#cb40-283" aria-hidden="true" tabindex="-1"></a>Hyde, Janet Shibley. "Meta-analysis and the psychology of gender differences." Signs: Journal of Women in Culture and Society 16.1 (1990): 55-73.</span>
<span id="cb40-284"><a href="#cb40-284" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb40-285"><a href="#cb40-285" aria-hidden="true" tabindex="-1"></a>Johnson, H., Barnard-Brak, L., Saxon, T., &amp; Johnson, M.K. (2012) An Experimental Study of the Effects of Stereotype Threat and Stereotype Lift on Men and Women's Performance in Mathematics, The Journal of Experimental Education, 80:2, 137-149, DOI: 10.1080/00220973.2011.567312</span>
<span id="cb40-286"><a href="#cb40-286" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb40-287"><a href="#cb40-287" aria-hidden="true" tabindex="-1"></a>Moè, A., &amp; Putwain, D. W. (2020). An evaluative message fosters mathematics performance in male students but decreases intrinsic motivation in female students. Educational Psychology, 1--20. https://doi.org/10.1080/01443410.2020.1730767</span>
<span id="cb40-288"><a href="#cb40-288" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb40-289"><a href="#cb40-289" aria-hidden="true" tabindex="-1"></a>Spinath, B., Harald Freudenthaler, H., &amp; Neubauer, A. C. (2010). Domain-specific school achievement in boys and girls as predicted by intelligence, personality and motivation. Personality and Individual Differences, 48(4), 481-486. https://doi.org/10.1016/j.paid.2009.11.028</span>
<span id="cb40-290"><a href="#cb40-290" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb40-291"><a href="#cb40-291" aria-hidden="true" tabindex="-1"></a>Steele, Claude M., and Joshua Aronson. "Stereotype threat and the intellectual test performance of African Americans." Journal of personality and social psychology 69.5 (1995): 797.</span>
<span id="cb40-292"><a href="#cb40-292" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb40-293"><a href="#cb40-293" aria-hidden="true" tabindex="-1"></a>Warne, R. T. (2022). No Strong Evidence of Stereotype Threat in Females: A Reassessment of the Meta-Analysis. Journal of Advanced Academics, 33(2), 171--186. https://doi.org/10.1177/1932202X211061517</span>
<span id="cb40-294"><a href="#cb40-294" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb40-295"><a href="#cb40-295" aria-hidden="true" tabindex="-1"></a>Data source: Anonymous. (2022). Performance vs. Predicted Performance<span class="sc">\[</span>Data set<span class="sc">\]</span>. Kaggle. https://doi.org/10.34740/KAGGLE/DSV/4282405</span>
</code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div></div></div></div></div>
</div> <!-- /content -->



</body></html>