<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.0.37">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">


<title>- HW4</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
span.underline{text-decoration: underline;}
div.column{display: inline-block; vertical-align: top; width: 50%;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
    color: #aaaaaa;
  }
pre.numberSource { margin-left: 3em; border-left: 1px solid #aaaaaa;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
code span.al { color: #ff0000; font-weight: bold; } /* Alert */
code span.an { color: #60a0b0; font-weight: bold; font-style: italic; } /* Annotation */
code span.at { color: #7d9029; } /* Attribute */
code span.bn { color: #40a070; } /* BaseN */
code span.bu { } /* BuiltIn */
code span.cf { color: #007020; font-weight: bold; } /* ControlFlow */
code span.ch { color: #4070a0; } /* Char */
code span.cn { color: #880000; } /* Constant */
code span.co { color: #60a0b0; font-style: italic; } /* Comment */
code span.cv { color: #60a0b0; font-weight: bold; font-style: italic; } /* CommentVar */
code span.do { color: #ba2121; font-style: italic; } /* Documentation */
code span.dt { color: #902000; } /* DataType */
code span.dv { color: #40a070; } /* DecVal */
code span.er { color: #ff0000; font-weight: bold; } /* Error */
code span.ex { } /* Extension */
code span.fl { color: #40a070; } /* Float */
code span.fu { color: #06287e; } /* Function */
code span.im { } /* Import */
code span.in { color: #60a0b0; font-weight: bold; font-style: italic; } /* Information */
code span.kw { color: #007020; font-weight: bold; } /* Keyword */
code span.op { color: #666666; } /* Operator */
code span.ot { color: #007020; } /* Other */
code span.pp { color: #bc7a00; } /* Preprocessor */
code span.sc { color: #4070a0; } /* SpecialChar */
code span.ss { color: #bb6688; } /* SpecialString */
code span.st { color: #4070a0; } /* String */
code span.va { color: #19177c; } /* Variable */
code span.vs { color: #4070a0; } /* VerbatimString */
code span.wa { color: #60a0b0; font-weight: bold; font-style: italic; } /* Warning */
</style>


<script src="../site_libs/quarto-nav/quarto-nav.js"></script>
<script src="../site_libs/quarto-nav/headroom.min.js"></script>
<script src="../site_libs/clipboard/clipboard.min.js"></script>
<script src="../site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="../site_libs/quarto-search/fuse.min.js"></script>
<script src="../site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="../">
<link href="../images/DACSS_Round_Network.png" rel="icon" type="image/png">
<script src="../site_libs/quarto-html/quarto.js"></script>
<script src="../site_libs/quarto-html/popper.min.js"></script>
<script src="../site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="../site_libs/quarto-html/anchor.min.js"></script>
<link href="../site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="../site_libs/quarto-html/quarto-syntax-highlighting.css" rel="stylesheet" class="quarto-color-scheme" id="quarto-text-highlighting-styles">
<link href="../site_libs/quarto-html/quarto-syntax-highlighting-dark.css" rel="prefetch" class="quarto-color-scheme quarto-color-alternate" id="quarto-text-highlighting-styles">
<script src="../site_libs/bootstrap/bootstrap.min.js"></script>
<link href="../site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="../site_libs/bootstrap/bootstrap.min.css" rel="stylesheet" class="quarto-color-scheme" id="quarto-bootstrap" data-mode="light">
<link href="../site_libs/bootstrap/bootstrap-dark.min.css" rel="prefetch" class="quarto-color-scheme quarto-color-alternate" id="quarto-bootstrap" data-mode="dark">
<script id="quarto-search-options" type="application/json">{
  "location": "navbar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "end",
  "type": "overlay",
  "limit": 20,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit"
  }
}</script>


<meta name="twitter:title" content="- HW4">
<meta name="twitter:creator" content="@UMassDACSS">
<meta name="twitter:card" content="summary">
</head>

<body class="nav-fixed">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
    <nav class="navbar navbar-expand-lg navbar-dark ">
      <div class="navbar-container container-fluid">
      <a class="navbar-brand" href="../index.html">
    <img src="../images/UMass White Wordmark Horiz.png" alt="">
  </a>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse" aria-controls="navbarCollapse" aria-expanded="false" aria-label="Toggle navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
  <span class="navbar-toggler-icon"></span>
</button>
          <div class="collapse navbar-collapse" id="navbarCollapse">
            <ul class="navbar-nav navbar-nav-scroll ms-auto">
  <li class="nav-item">
    <a class="nav-link" href="https://dacss.github.io/603_Fall_2022/">Fall 2022 Posts</a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="../about.html">Contributors</a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="https://umass.edu/sbs/dacss">DACSS</a>
  </li>  
  <li class="nav-item compact">
    <a class="nav-link" href="https://github.com/DACSS/603_Fall_2022"><i class="bi bi-github" role="img" aria-label="GitHub">
</i> 
 </a>
  </li>  
</ul>
              <div class="quarto-toggle-container">
                  <a href="" class="quarto-color-scheme-toggle nav-link" onclick="window.quartoToggleColorScheme(); return false;" title="Toggle dark mode"><i class="bi"></i></a>
              </div>
              <div id="quarto-search" class="" title="Search"></div>
          </div> <!-- /navcollapse -->
      </div> <!-- /container-fluid -->
    </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article page-navbar">
<!-- sidebar -->
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc">
    <h2 id="toc-title">On this page</h2>
   
  <ul>
  <li><a href="#question-1" id="toc-question-1" class="nav-link active" data-scroll-target="#question-1">Question 1</a></li>
  <li><a href="#question-2" id="toc-question-2" class="nav-link" data-scroll-target="#question-2">Question 2</a></li>
  <li><a href="#question-3" id="toc-question-3" class="nav-link" data-scroll-target="#question-3">Question 3</a></li>
  </ul>
</nav>
    </div>
<!-- main -->
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title">HW4</h1>
</div>



<div class="quarto-title-meta">

    
    
  </div>
  

</header>

<div class="cell">
<div class="sourceCode cell-code" id="cb1"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(smss)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning: package 'smss' was built under R version 4.2.2</code></pre>
</div>
<div class="sourceCode cell-code" id="cb3"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb3-1"><a href="#cb3-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(alr4)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>Loading required package: car</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Loading required package: carData</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Loading required package: effects</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>lattice theme set by effectsTheme()
See ?effectsTheme for details.</code></pre>
</div>
<div class="sourceCode cell-code" id="cb8"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb8-1"><a href="#cb8-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(stats)</span>
<span id="cb8-2"><a href="#cb8-2" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(tidyr)</span>
<span id="cb8-3"><a href="#cb8-3" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(ggplot2)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<section id="question-1" class="level2">
<h2 class="anchored" data-anchor-id="question-1">Question 1</h2>
<section id="for-recent-data-in-jacksonville-florida-on-y-selling-price-of-home-in-dollars-x1-size-of-home-in-square-feet-and-x2-lot-size-in-square-feet-the-prediction-equation-is-y-10536-53.8x1-2.84x2." class="level4">
<h4 class="anchored" data-anchor-id="for-recent-data-in-jacksonville-florida-on-y-selling-price-of-home-in-dollars-x1-size-of-home-in-square-feet-and-x2-lot-size-in-square-feet-the-prediction-equation-is-y-10536-53.8x1-2.84x2.">For recent data in Jacksonville, Florida, on y = selling price of home (in dollars), x1 = size of home (in square feet), and x2 = lot size (in square feet), the prediction equation is ŷ = −10,536 + 53.8x1 + 2.84x2.</h4>
</section>
<section id="a-a-particular-home-of-1240-square-feet-on-a-lot-of-18000-square-feet-sold-for-145000.-find-the-predicted-selling-price-and-the-residual-and-interpret." class="level4">
<h4 class="anchored" data-anchor-id="a-a-particular-home-of-1240-square-feet-on-a-lot-of-18000-square-feet-sold-for-145000.-find-the-predicted-selling-price-and-the-residual-and-interpret.">a) A particular home of 1240 square feet on a lot of 18,000 square feet sold for $145,000. Find the predicted selling price and the residual, and interpret.</h4>
<div class="cell">
<div class="sourceCode cell-code" id="cb9"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb9-1"><a href="#cb9-1" aria-hidden="true" tabindex="-1"></a>predicted_sp <span class="ot">&lt;-</span> <span class="dv">10536</span><span class="fl">+53.8</span><span class="sc">*</span><span class="dv">1240</span><span class="fl">+2.84</span><span class="sc">*</span><span class="dv">18000</span></span>
<span id="cb9-2"><a href="#cb9-2" aria-hidden="true" tabindex="-1"></a>predicted_sp</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 128368</code></pre>
</div>
</div>
<p>Given the measurements and previous selling price of the house, the predicted selling price is $128,368.</p>
<p>Now to calculate the residual between the above figure and the actual selling price of $145,000.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb11"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb11-1"><a href="#cb11-1" aria-hidden="true" tabindex="-1"></a>residual <span class="ot">&lt;-</span> <span class="dv">145000</span><span class="sc">-</span>predicted_sp</span>
<span id="cb11-2"><a href="#cb11-2" aria-hidden="true" tabindex="-1"></a>residual</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 16632</code></pre>
</div>
</div>
<p>The residual is $16,632, which indicates that the home and property sold for $16,632 above the predicted selling price.</p>
</section>
<section id="b-for-fixed-lot-size-how-much-is-the-house-selling-price-predicted-to-increase-for-each-square-foot-increase-in-home-size-why" class="level4">
<h4 class="anchored" data-anchor-id="b-for-fixed-lot-size-how-much-is-the-house-selling-price-predicted-to-increase-for-each-square-foot-increase-in-home-size-why">b) For fixed lot size, how much is the house selling price predicted to increase for each square-foot increase in home size? Why?</h4>
<p>The coefficient for home size in square feet (x1) is 53.8, so the price of the home would go up by $53.80 for each square foot increase.</p>
</section>
<section id="c-according-to-this-prediction-equation-for-fixed-home-size-how-much-would-lot-size-need-to-increase-to-have-the-same-impact-as-a-one-square-foot-increase-in-home-size" class="level4">
<h4 class="anchored" data-anchor-id="c-according-to-this-prediction-equation-for-fixed-home-size-how-much-would-lot-size-need-to-increase-to-have-the-same-impact-as-a-one-square-foot-increase-in-home-size">c) According to this prediction equation, for fixed home size, how much would lot size need to increase to have the same impact as a one-square-foot increase in home size?</h4>
<p>The coefficient for x2 (lot size in square feet) is 2.84, meaning that every square foot increase in property size would add $2.84 to the overall price of the home. For an increase in lot size to have the same impact as a one square foot increase in home size, we have to do some simple division (x1/x2)</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb13"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb13-1"><a href="#cb13-1" aria-hidden="true" tabindex="-1"></a><span class="fl">53.8</span><span class="sc">/</span><span class="fl">2.84</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 18.94366</code></pre>
</div>
</div>
<p>Lot size would have to increase by 18.94 square feet to have the same price impact as a one square foot increase in house size.</p>
</section>
</section>
<section id="question-2" class="level2">
<h2 class="anchored" data-anchor-id="question-2">Question 2</h2>
<section id="data-file-salary-in-alr4-r-package.-the-data-file-concerns-salary-and-other-characteristics-of-all-faculty-in-a-small-midwestern-college-collected-in-the-early-1980s-for-presentation-in-legal-proceedings-for-which-discrimination-against-women-in-salary-was-at-issue.-all-persons-in-the-data-hold-tenured-or-tenure-track-positions-temporary-faculty-are-not-included.-the-variables-include-degree-a-factor-with-levels-phd-and-ms-rank-a-factor-with-levels-asst-assoc-and-prof-sex-a-factor-with-levels-male-and-female-year-years-in-current-rank-ysdeg-years-since-highest-degree-and-salary-academic-year-salary-in-dollars." class="level4">
<h4 class="anchored" data-anchor-id="data-file-salary-in-alr4-r-package.-the-data-file-concerns-salary-and-other-characteristics-of-all-faculty-in-a-small-midwestern-college-collected-in-the-early-1980s-for-presentation-in-legal-proceedings-for-which-discrimination-against-women-in-salary-was-at-issue.-all-persons-in-the-data-hold-tenured-or-tenure-track-positions-temporary-faculty-are-not-included.-the-variables-include-degree-a-factor-with-levels-phd-and-ms-rank-a-factor-with-levels-asst-assoc-and-prof-sex-a-factor-with-levels-male-and-female-year-years-in-current-rank-ysdeg-years-since-highest-degree-and-salary-academic-year-salary-in-dollars.">(Data file: salary in alr4 R package). The data file concerns salary and other characteristics of all faculty in a small Midwestern college collected in the early 1980s for presentation in legal proceedings for which discrimination against women in salary was at issue. All persons in the data hold tenured or tenure track positions; temporary faculty are not included. The variables include degree, a factor with levels PhD and MS; rank, a factor with levels Asst, Assoc, and Prof; sex, a factor with levels Male and Female; Year, years in current rank; ysdeg, years since highest degree, and salary, academic year salary in dollars.</h4>
</section>
<section id="a-test-the-hypothesis-that-the-mean-salary-for-men-and-women-is-the-same-without-regard-to-any-other-variable-but-sex.-explain-your-findings." class="level4">
<h4 class="anchored" data-anchor-id="a-test-the-hypothesis-that-the-mean-salary-for-men-and-women-is-the-same-without-regard-to-any-other-variable-but-sex.-explain-your-findings.">a) Test the hypothesis that the mean salary for men and women is the same, without regard to any other variable but sex. Explain your findings.</h4>
<div class="cell">
<div class="sourceCode cell-code" id="cb15"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb15-1"><a href="#cb15-1" aria-hidden="true" tabindex="-1"></a><span class="fu">data</span>(salary)</span>
<span id="cb15-2"><a href="#cb15-2" aria-hidden="true" tabindex="-1"></a><span class="fu">t.test</span>(salary<span class="sc">~</span>sex,<span class="at">data =</span> salary)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
    Welch Two Sample t-test

data:  salary by sex
t = 1.7744, df = 21.591, p-value = 0.09009
alternative hypothesis: true difference in means between group Male and group Female is not equal to 0
95 percent confidence interval:
 -567.8539 7247.1471
sample estimates:
  mean in group Male mean in group Female 
            24696.79             21357.14 </code></pre>
</div>
</div>
<p>The mean salary for males is $24,696.79 and the mean salary for females is $21,357.14. Based entirely on sex, the mean salary for men and women is not the same, with a $3,339.65 difference in favor of males.</p>
</section>
<section id="b-run-a-multiple-linear-regression-with-salary-as-the-outcome-variable-and-everything-else-as-predictors-including-sex.-assuming-no-interactions-between-sex-and-the-other-predictors-obtain-a-95-confidence-interval-for-the-difference-in-salary-between-males-and-females." class="level4">
<h4 class="anchored" data-anchor-id="b-run-a-multiple-linear-regression-with-salary-as-the-outcome-variable-and-everything-else-as-predictors-including-sex.-assuming-no-interactions-between-sex-and-the-other-predictors-obtain-a-95-confidence-interval-for-the-difference-in-salary-between-males-and-females.">b) Run a multiple linear regression with salary as the outcome variable and everything else as predictors, including sex. Assuming no interactions between sex and the other predictors, obtain a 95% confidence interval for the difference in salary between males and females.</h4>
<div class="cell">
<div class="sourceCode cell-code" id="cb17"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb17-1"><a href="#cb17-1" aria-hidden="true" tabindex="-1"></a>lr_predictors <span class="ot">&lt;-</span> <span class="fu">lm</span>(salary<span class="sc">~</span>degree<span class="sc">+</span>rank<span class="sc">+</span>sex<span class="sc">+</span>year<span class="sc">+</span>ysdeg, <span class="at">data=</span>salary)</span>
<span id="cb17-2"><a href="#cb17-2" aria-hidden="true" tabindex="-1"></a>lr_predictors</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = salary ~ degree + rank + sex + year + ysdeg, data = salary)

Coefficients:
(Intercept)    degreePhD    rankAssoc     rankProf    sexFemale         year  
    15746.0       1388.6       5292.4      11118.8       1166.4        476.3  
      ysdeg  
     -124.6  </code></pre>
</div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb19"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb19-1"><a href="#cb19-1" aria-hidden="true" tabindex="-1"></a><span class="fu">set.seed</span>(<span class="dv">3</span>)</span>
<span id="cb19-2"><a href="#cb19-2" aria-hidden="true" tabindex="-1"></a>mf_pay_rate <span class="ot">&lt;-</span> <span class="fu">data.frame</span>(<span class="at">degree=</span><span class="fu">sample</span>(salary<span class="sc">$</span>degree,<span class="at">size=</span><span class="dv">10</span>,<span class="at">replace=</span>T),</span>
<span id="cb19-3"><a href="#cb19-3" aria-hidden="true" tabindex="-1"></a>                          <span class="at">rank=</span><span class="fu">sample</span>(salary<span class="sc">$</span>rank,<span class="at">size=</span><span class="dv">10</span>,<span class="at">replace=</span>T),</span>
<span id="cb19-4"><a href="#cb19-4" aria-hidden="true" tabindex="-1"></a>                          <span class="at">sex=</span><span class="fu">sample</span>(salary<span class="sc">$</span>sex,<span class="at">size=</span><span class="dv">10</span>,<span class="at">replace=</span>T),</span>
<span id="cb19-5"><a href="#cb19-5" aria-hidden="true" tabindex="-1"></a>                          <span class="at">year=</span><span class="fu">sample</span>(salary<span class="sc">$</span>year,<span class="at">size=</span><span class="dv">10</span>,<span class="at">replace=</span>T),</span>
<span id="cb19-6"><a href="#cb19-6" aria-hidden="true" tabindex="-1"></a>                          <span class="at">ysdeg=</span><span class="fu">sample</span>(salary<span class="sc">$</span>ysdeg,<span class="at">size=</span><span class="dv">10</span>,<span class="at">replace=</span>T))</span>
<span id="cb19-7"><a href="#cb19-7" aria-hidden="true" tabindex="-1"></a><span class="fu">predict</span>(lr_predictors,mf_pay_rate)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>       1        2        3        4        5        6        7        8 
15368.63 20671.56 14287.78 29407.55 20069.45 32082.22 23606.80 16837.87 
       9       10 
21524.03 28077.52 </code></pre>
</div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb21"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb21-1"><a href="#cb21-1" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(lr_predictors)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = salary ~ degree + rank + sex + year + ysdeg, data = salary)

Residuals:
    Min      1Q  Median      3Q     Max 
-4045.2 -1094.7  -361.5   813.2  9193.1 

Coefficients:
            Estimate Std. Error t value Pr(&gt;|t|)    
(Intercept) 15746.05     800.18  19.678  &lt; 2e-16 ***
degreePhD    1388.61    1018.75   1.363    0.180    
rankAssoc    5292.36    1145.40   4.621 3.22e-05 ***
rankProf    11118.76    1351.77   8.225 1.62e-10 ***
sexFemale    1166.37     925.57   1.260    0.214    
year          476.31      94.91   5.018 8.65e-06 ***
ysdeg        -124.57      77.49  -1.608    0.115    
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 2398 on 45 degrees of freedom
Multiple R-squared:  0.855, Adjusted R-squared:  0.8357 
F-statistic: 44.24 on 6 and 45 DF,  p-value: &lt; 2.2e-16</code></pre>
</div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb23"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb23-1"><a href="#cb23-1" aria-hidden="true" tabindex="-1"></a><span class="fu">confint</span>(lr_predictors,<span class="st">'sexFemale'</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>              2.5 %   97.5 %
sexFemale -697.8183 3030.565</code></pre>
</div>
</div>
<p>After conducting a multiple linear regression (with 95% CI), the difference in salary between males and females in this scenario ranges from $697.82 less than male counterparts to $3030.56 more than male counterparts.</p>
</section>
<section id="c-interpret-your-finding-for-each-predictor-variable-discuss-a-statistical-significance-b-interpretation-of-the-coefficient-slope-in-relation-to-the-outcome-variable-and-other-variables." class="level4">
<h4 class="anchored" data-anchor-id="c-interpret-your-finding-for-each-predictor-variable-discuss-a-statistical-significance-b-interpretation-of-the-coefficient-slope-in-relation-to-the-outcome-variable-and-other-variables.">c) Interpret your finding for each predictor variable; discuss (a) statistical significance, (b) interpretation of the coefficient / slope in relation to the outcome variable and other variables.</h4>
<div class="cell">
<div class="sourceCode cell-code" id="cb25"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb25-1"><a href="#cb25-1" aria-hidden="true" tabindex="-1"></a><span class="fu">set.seed</span>(<span class="dv">3</span>)</span>
<span id="cb25-2"><a href="#cb25-2" aria-hidden="true" tabindex="-1"></a>income_df <span class="ot">&lt;-</span><span class="fu">data.frame</span>(<span class="at">degree=</span><span class="fu">sample</span>(salary<span class="sc">$</span>degree,<span class="at">size=</span><span class="dv">10</span>,<span class="at">replace=</span>T),</span>
<span id="cb25-3"><a href="#cb25-3" aria-hidden="true" tabindex="-1"></a>                          <span class="at">rank=</span><span class="fu">sample</span>(salary<span class="sc">$</span>rank,<span class="at">size=</span><span class="dv">10</span>,<span class="at">replace=</span>T),</span>
<span id="cb25-4"><a href="#cb25-4" aria-hidden="true" tabindex="-1"></a>                          <span class="at">sex=</span><span class="fu">sample</span>(salary<span class="sc">$</span>sex,<span class="at">size=</span><span class="dv">10</span>,<span class="at">replace=</span>T),</span>
<span id="cb25-5"><a href="#cb25-5" aria-hidden="true" tabindex="-1"></a>                          <span class="at">year=</span><span class="fu">sample</span>(salary<span class="sc">$</span>year,<span class="at">size=</span><span class="dv">10</span>,<span class="at">replace=</span>T),</span>
<span id="cb25-6"><a href="#cb25-6" aria-hidden="true" tabindex="-1"></a>                          <span class="at">ysdeg=</span><span class="fu">sample</span>(salary<span class="sc">$</span>ysdeg,<span class="at">size=</span><span class="dv">10</span>,<span class="at">replace=</span>T))</span>
<span id="cb25-7"><a href="#cb25-7" aria-hidden="true" tabindex="-1"></a><span class="fu">predict</span>(lr_predictors,income_df)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>       1        2        3        4        5        6        7        8 
15368.63 20671.56 14287.78 29407.55 20069.45 32082.22 23606.80 16837.87 
       9       10 
21524.03 28077.52 </code></pre>
</div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb27"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb27-1"><a href="#cb27-1" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(lr_predictors)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = salary ~ degree + rank + sex + year + ysdeg, data = salary)

Residuals:
    Min      1Q  Median      3Q     Max 
-4045.2 -1094.7  -361.5   813.2  9193.1 

Coefficients:
            Estimate Std. Error t value Pr(&gt;|t|)    
(Intercept) 15746.05     800.18  19.678  &lt; 2e-16 ***
degreePhD    1388.61    1018.75   1.363    0.180    
rankAssoc    5292.36    1145.40   4.621 3.22e-05 ***
rankProf    11118.76    1351.77   8.225 1.62e-10 ***
sexFemale    1166.37     925.57   1.260    0.214    
year          476.31      94.91   5.018 8.65e-06 ***
ysdeg        -124.57      77.49  -1.608    0.115    
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 2398 on 45 degrees of freedom
Multiple R-squared:  0.855, Adjusted R-squared:  0.8357 
F-statistic: 44.24 on 6 and 45 DF,  p-value: &lt; 2.2e-16</code></pre>
</div>
</div>
<p>According to this data set, individuals’ salary increases by:<br>
1) $1388.61 if they have a PhD<br>
2) $5292.36 if they are an associate professor<br>
3) $11,118.76 if they are a full/tenured professor<br>
4) $1166.37 if they are female<br>
5) $475.31 every year they are employed at their institution</p>
<p>Salary decreases by $124.57, however, for every year that passes since the individual received their degree. I may have misinterpreted the meaning of this variable (ysdeg), because this doesn’t really make sense if they get a raise for everything else. Anyway, the values representing respondents’ professorial rank and the length of their employment are statistically significant.</p>
</section>
<section id="d-change-the-baseline-category-for-the-rank-variable.-interpret-the-coefficients-related-to-rank-again." class="level4">
<h4 class="anchored" data-anchor-id="d-change-the-baseline-category-for-the-rank-variable.-interpret-the-coefficients-related-to-rank-again.">d) Change the baseline category for the rank variable. Interpret the coefficients related to rank again.</h4>
<div class="cell">
<div class="sourceCode cell-code" id="cb29"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb29-1"><a href="#cb29-1" aria-hidden="true" tabindex="-1"></a>lr_predictors_rank <span class="ot">&lt;-</span> <span class="fu">lm</span>(salary<span class="sc">~</span>rank<span class="sc">+</span>sex<span class="sc">+</span>degree<span class="sc">+</span>year<span class="sc">+</span>ysdeg, <span class="at">data=</span>salary)</span>
<span id="cb29-2"><a href="#cb29-2" aria-hidden="true" tabindex="-1"></a><span class="fu">set.seed</span>(<span class="dv">3</span>) </span>
<span id="cb29-3"><a href="#cb29-3" aria-hidden="true" tabindex="-1"></a>income_rank <span class="ot">&lt;-</span> <span class="fu">data.frame</span>(<span class="at">rank=</span><span class="fu">sample</span>(salary<span class="sc">$</span>rank,<span class="at">size=</span><span class="dv">10</span>,<span class="at">replace=</span>T),</span>
<span id="cb29-4"><a href="#cb29-4" aria-hidden="true" tabindex="-1"></a>                  <span class="at">sex=</span><span class="fu">sample</span>(salary<span class="sc">$</span>sex,<span class="at">size=</span><span class="dv">10</span>,<span class="at">replace=</span>T),</span>
<span id="cb29-5"><a href="#cb29-5" aria-hidden="true" tabindex="-1"></a>                  <span class="at">degree=</span><span class="fu">sample</span>(salary<span class="sc">$</span>degree,<span class="at">size=</span><span class="dv">10</span>,<span class="at">replace=</span>T),</span>
<span id="cb29-6"><a href="#cb29-6" aria-hidden="true" tabindex="-1"></a>                  <span class="at">year=</span><span class="fu">sample</span>(salary<span class="sc">$</span>year,<span class="at">size=</span><span class="dv">10</span>,<span class="at">replace=</span>T),</span>
<span id="cb29-7"><a href="#cb29-7" aria-hidden="true" tabindex="-1"></a>                  <span class="at">ysdeg=</span><span class="fu">sample</span>(salary<span class="sc">$</span>ysdeg,<span class="at">size=</span><span class="dv">10</span>,<span class="at">replace=</span>T))</span>
<span id="cb29-8"><a href="#cb29-8" aria-hidden="true" tabindex="-1"></a><span class="fu">predict</span>(lr_predictors_rank,income_rank)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>       1        2        3        4        5        6        7        8 
25098.78 25963.92 15676.39 24969.76 22624.44 26255.82 16925.83 29123.01 
       9       10 
31254.18 28077.52 </code></pre>
</div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb31"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb31-1"><a href="#cb31-1" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(lr_predictors_rank)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = salary ~ rank + sex + degree + year + ysdeg, data = salary)

Residuals:
    Min      1Q  Median      3Q     Max 
-4045.2 -1094.7  -361.5   813.2  9193.1 

Coefficients:
            Estimate Std. Error t value Pr(&gt;|t|)    
(Intercept) 15746.05     800.18  19.678  &lt; 2e-16 ***
rankAssoc    5292.36    1145.40   4.621 3.22e-05 ***
rankProf    11118.76    1351.77   8.225 1.62e-10 ***
sexFemale    1166.37     925.57   1.260    0.214    
degreePhD    1388.61    1018.75   1.363    0.180    
year          476.31      94.91   5.018 8.65e-06 ***
ysdeg        -124.57      77.49  -1.608    0.115    
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 2398 on 45 degrees of freedom
Multiple R-squared:  0.855, Adjusted R-squared:  0.8357 
F-statistic: 44.24 on 6 and 45 DF,  p-value: &lt; 2.2e-16</code></pre>
</div>
</div>
<p>I am not entirely sure this is right since all of the values remained the same.</p>
</section>
<section id="e-finkelstein-1980-in-a-discussion-of-the-use-of-regression-in-discrimination-cases-wrote-a-variable-may-reflect-a-position-or-status-bestowed-by-the-employer-in-which-case-if-there-is-discrimination-in-the-award-of-the-position-or-status-the-variable-may-be-tainted.-thus-for-example-if-discrimination-is-at-work-in-promotion-of-faculty-to-higher-ranks-using-rank-to-adjust-salaries-before-comparing-the-sexes-may-not-be-acceptable-to-the-courts." class="level4">
<h4 class="anchored" data-anchor-id="e-finkelstein-1980-in-a-discussion-of-the-use-of-regression-in-discrimination-cases-wrote-a-variable-may-reflect-a-position-or-status-bestowed-by-the-employer-in-which-case-if-there-is-discrimination-in-the-award-of-the-position-or-status-the-variable-may-be-tainted.-thus-for-example-if-discrimination-is-at-work-in-promotion-of-faculty-to-higher-ranks-using-rank-to-adjust-salaries-before-comparing-the-sexes-may-not-be-acceptable-to-the-courts.">e) Finkelstein (1980), in a discussion of the use of regression in discrimination cases, wrote, “[a] variable may reflect a position or status bestowed by the employer, in which case if there is discrimination in the award of the position or status, the variable may be ‘tainted.’” Thus, for example, if discrimination is at work in promotion of faculty to higher ranks, using rank to adjust salaries before comparing the sexes may not be acceptable to the courts.</h4>
</section>
<section id="exclude-the-variable-rank-refit-and-summarize-how-your-findings-changed-if-they-did." class="level4">
<h4 class="anchored" data-anchor-id="exclude-the-variable-rank-refit-and-summarize-how-your-findings-changed-if-they-did.">Exclude the variable rank, refit, and summarize how your findings changed, if they did.</h4>
<div class="cell">
<div class="sourceCode cell-code" id="cb33"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb33-1"><a href="#cb33-1" aria-hidden="true" tabindex="-1"></a>lr_predictors3 <span class="ot">&lt;-</span> <span class="fu">lm</span>(salary<span class="sc">~</span>degree<span class="sc">+</span>sex<span class="sc">+</span>year<span class="sc">+</span>ysdeg,<span class="at">data=</span>salary)</span>
<span id="cb33-2"><a href="#cb33-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb33-3"><a href="#cb33-3" aria-hidden="true" tabindex="-1"></a><span class="fu">set.seed</span>(<span class="dv">3</span>)</span>
<span id="cb33-4"><a href="#cb33-4" aria-hidden="true" tabindex="-1"></a>income_df3 <span class="ot">&lt;-</span> <span class="fu">data.frame</span>(<span class="at">degree=</span><span class="fu">sample</span>(salary<span class="sc">$</span>degree,<span class="at">size=</span><span class="dv">10</span>,<span class="at">replace=</span>T),</span>
<span id="cb33-5"><a href="#cb33-5" aria-hidden="true" tabindex="-1"></a>                  <span class="at">sex=</span><span class="fu">sample</span>(salary<span class="sc">$</span>sex,<span class="at">size=</span><span class="dv">10</span>,<span class="at">replace=</span>T),</span>
<span id="cb33-6"><a href="#cb33-6" aria-hidden="true" tabindex="-1"></a>                  <span class="at">year=</span><span class="fu">sample</span>(salary<span class="sc">$</span>year,<span class="at">size=</span><span class="dv">10</span>,<span class="at">replace=</span>T),</span>
<span id="cb33-7"><a href="#cb33-7" aria-hidden="true" tabindex="-1"></a>                  <span class="at">ysdeg=</span><span class="fu">sample</span>(salary<span class="sc">$</span>ysdeg,<span class="at">size=</span><span class="dv">10</span>,<span class="at">replace=</span>T))</span>
<span id="cb33-8"><a href="#cb33-8" aria-hidden="true" tabindex="-1"></a><span class="fu">predict</span>(lr_predictors3,income_df3)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>       1        2        3        4        5        6        7        8 
15631.50 25840.16 23116.76 29904.74 30290.05 27114.13 19427.73 25588.74 
       9       10 
23098.28 21451.56 </code></pre>
</div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb35"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb35-1"><a href="#cb35-1" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(lr_predictors3)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = salary ~ degree + sex + year + ysdeg, data = salary)

Residuals:
    Min      1Q  Median      3Q     Max 
-8146.9 -2186.9  -491.5  2279.1 11186.6 

Coefficients:
            Estimate Std. Error t value Pr(&gt;|t|)    
(Intercept) 17183.57    1147.94  14.969  &lt; 2e-16 ***
degreePhD   -3299.35    1302.52  -2.533 0.014704 *  
sexFemale   -1286.54    1313.09  -0.980 0.332209    
year          351.97     142.48   2.470 0.017185 *  
ysdeg         339.40      80.62   4.210 0.000114 ***
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 3744 on 47 degrees of freedom
Multiple R-squared:  0.6312,    Adjusted R-squared:  0.5998 
F-statistic: 20.11 on 4 and 47 DF,  p-value: 1.048e-09</code></pre>
</div>
</div>
<p>By excluding ‘rank’, salary decreases by:<br>
1) $3299.35 if the individual has a PhD<br>
2) $1286.54 if the individual</p>
<p>However, salary <em>/increases/</em> by:<br>
1) $351.97 for each year the individual is at their current professorial rank<br>
2) $339.40 every year after the individual receives their PhD</p>
</section>
<section id="f-everyone-in-this-dataset-was-hired-the-year-they-earned-their-highest-degree.-it-is-also-known-that-a-new-dean-was-appointed-15-years-ago-and-everyone-in-the-dataset-who-earned-their-highest-degree-15-years-ago-or-less-than-that-has-been-hired-by-the-new-dean.-some-people-have-argued-that-the-new-dean-has-been-making-offers-that-are-a-lot-more-generous-to-newly-hired-faculty-than-the-previous-one-and-that-this-might-explain-some-of-the-variation-in-salary." class="level4">
<h4 class="anchored" data-anchor-id="f-everyone-in-this-dataset-was-hired-the-year-they-earned-their-highest-degree.-it-is-also-known-that-a-new-dean-was-appointed-15-years-ago-and-everyone-in-the-dataset-who-earned-their-highest-degree-15-years-ago-or-less-than-that-has-been-hired-by-the-new-dean.-some-people-have-argued-that-the-new-dean-has-been-making-offers-that-are-a-lot-more-generous-to-newly-hired-faculty-than-the-previous-one-and-that-this-might-explain-some-of-the-variation-in-salary.">f) Everyone in this dataset was hired the year they earned their highest degree. It is also known that a new Dean was appointed 15 years ago, and everyone in the dataset who earned their highest degree 15 years ago or less than that has been hired by the new Dean. Some people have argued that the new Dean has been making offers that are a lot more generous to newly hired faculty than the previous one and that this might explain some of the variation in Salary.</h4>
</section>
<section id="create-a-new-variable-that-would-allow-you-to-test-this-hypothesis-and-run-another-multiple-regression-model-to-test-this.-select-variables-carefully-to-make-sure-there-is-no-multicollinearity.-explain-why-multicollinearity-would-be-a-concern-in-this-case-and-how-you-avoided-it.-do-you-find-support-for-the-hypothesis-that-the-people-hired-by-the-new-dean-are-making-higher-than-those-that-were-not" class="level4">
<h4 class="anchored" data-anchor-id="create-a-new-variable-that-would-allow-you-to-test-this-hypothesis-and-run-another-multiple-regression-model-to-test-this.-select-variables-carefully-to-make-sure-there-is-no-multicollinearity.-explain-why-multicollinearity-would-be-a-concern-in-this-case-and-how-you-avoided-it.-do-you-find-support-for-the-hypothesis-that-the-people-hired-by-the-new-dean-are-making-higher-than-those-that-were-not">Create a new variable that would allow you to test this hypothesis and run another multiple regression model to test this. Select variables carefully to make sure there is no multicollinearity. Explain why multicollinearity would be a concern in this case and how you avoided it. Do you find support for the hypothesis that the people hired by the new Dean are making higher than those that were not?</h4>
<div class="cell">
<div class="sourceCode cell-code" id="cb37"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb37-1"><a href="#cb37-1" aria-hidden="true" tabindex="-1"></a>lr_predictor4 <span class="ot">&lt;-</span> <span class="fu">lm</span>(salary<span class="sc">~</span>rank<span class="sc">+</span>degree<span class="sc">+</span>sex<span class="sc">+</span>year<span class="sc">+</span>ysdeg<span class="sc">+</span>year<span class="sc">*</span>ysdeg,<span class="at">data=</span>salary)</span>
<span id="cb37-2"><a href="#cb37-2" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(lr_predictor4)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = salary ~ rank + degree + sex + year + ysdeg + year * 
    ysdeg, data = salary)

Residuals:
    Min      1Q  Median      3Q     Max 
-4055.4 -1007.7  -172.6   800.0  9275.7 

Coefficients:
             Estimate Std. Error t value Pr(&gt;|t|)    
(Intercept) 16289.506    944.422  17.248  &lt; 2e-16 ***
rankAssoc    5627.056   1184.705   4.750 2.19e-05 ***
rankProf    11475.286   1389.241   8.260 1.71e-10 ***
degreePhD    1557.213   1028.855   1.514   0.1373    
sexFemale    1233.531    925.994   1.332   0.1897    
year          318.343    174.450   1.825   0.0748 .  
ysdeg        -172.406     89.161  -1.934   0.0596 .  
year:ysdeg      7.094      6.578   1.078   0.2867    
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 2394 on 44 degrees of freedom
Multiple R-squared:  0.8588,    Adjusted R-squared:  0.8363 
F-statistic: 38.22 on 7 and 44 DF,  p-value: &lt; 2.2e-16</code></pre>
</div>
</div>
<p>The slope for ‘year:ysdeg’ is positive, whcih supports the hypothesis that people hired by the new dean make more than those hired beforehand.</p>
</section>
</section>
<section id="question-3" class="level2">
<h2 class="anchored" data-anchor-id="question-3">Question 3</h2>
<section id="a-using-the-house.selling.price-data-run-and-report-regression-results-modeling-y-selling-price-in-dollars-in-terms-of-size-of-home-in-square-feet-and-whether-the-home-is-new-1-yes-0-no.-in-particular-for-each-variable-discuss-statistical-significance-and-interpret-the-meaning-of-the-coefficient." class="level4">
<h4 class="anchored" data-anchor-id="a-using-the-house.selling.price-data-run-and-report-regression-results-modeling-y-selling-price-in-dollars-in-terms-of-size-of-home-in-square-feet-and-whether-the-home-is-new-1-yes-0-no.-in-particular-for-each-variable-discuss-statistical-significance-and-interpret-the-meaning-of-the-coefficient.">a) Using the house.selling.price data, run and report regression results modeling y = selling price (in dollars) in terms of size of home (in square feet) and whether the home is new (1 = yes; 0 = no). In particular, for each variable; discuss statistical significance and interpret the meaning of the coefficient.</h4>
<p>Let’s start with presenting summary data to see what we’re working with:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb39"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb39-1"><a href="#cb39-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(smss)</span>
<span id="cb39-2"><a href="#cb39-2" aria-hidden="true" tabindex="-1"></a><span class="fu">data</span>(<span class="st">"house.selling.price"</span>)</span>
<span id="cb39-3"><a href="#cb39-3" aria-hidden="true" tabindex="-1"></a><span class="fu">head</span>(house.selling.price)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>  case Taxes Beds Baths New  Price Size
1    1  3104    4     2   0 279900 2048
2    2  1173    2     1   0 146500  912
3    3  3076    4     2   0 237700 1654
4    4  1608    3     2   0 200000 2068
5    5  1454    3     3   0 159900 1477
6    6  2997    3     2   1 499900 3153</code></pre>
</div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb41"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb41-1"><a href="#cb41-1" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(house.selling.price)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>      case            Taxes           Beds       Baths           New      
 Min.   :  1.00   Min.   :  20   Min.   :2   Min.   :1.00   Min.   :0.00  
 1st Qu.: 25.75   1st Qu.:1178   1st Qu.:3   1st Qu.:2.00   1st Qu.:0.00  
 Median : 50.50   Median :1614   Median :3   Median :2.00   Median :0.00  
 Mean   : 50.50   Mean   :1908   Mean   :3   Mean   :1.96   Mean   :0.11  
 3rd Qu.: 75.25   3rd Qu.:2238   3rd Qu.:3   3rd Qu.:2.00   3rd Qu.:0.00  
 Max.   :100.00   Max.   :6627   Max.   :5   Max.   :4.00   Max.   :1.00  
     Price             Size     
 Min.   : 21000   Min.   : 580  
 1st Qu.: 93225   1st Qu.:1215  
 Median :132600   Median :1474  
 Mean   :155331   Mean   :1629  
 3rd Qu.:169625   3rd Qu.:1865  
 Max.   :587000   Max.   :4050  </code></pre>
</div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb43"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb43-1"><a href="#cb43-1" aria-hidden="true" tabindex="-1"></a><span class="fu">str</span>(house.selling.price)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>'data.frame':   100 obs. of  7 variables:
 $ case : int  1 2 3 4 5 6 7 8 9 10 ...
 $ Taxes: int  3104 1173 3076 1608 1454 2997 4054 3002 6627 320 ...
 $ Beds : int  4 2 4 3 3 3 3 3 5 3 ...
 $ Baths: int  2 1 2 2 3 2 2 2 4 2 ...
 $ New  : int  0 0 0 0 0 1 0 1 0 0 ...
 $ Price: int  279900 146500 237700 200000 159900 499900 265500 289900 587000 70000 ...
 $ Size : int  2048 912 1654 2068 1477 3153 1355 2075 3990 1160 ...</code></pre>
</div>
</div>
<p>Now I’m going to delve into the regression analysis in which y= selling price (USD) relative to house size, and whether a home is new (1=yes, 0=no).</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb45"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb45-1"><a href="#cb45-1" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(<span class="fu">lm</span>(Price<span class="sc">~</span>Size<span class="sc">+</span>New,<span class="at">data=</span>house.selling.price))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = Price ~ Size + New, data = house.selling.price)

Residuals:
    Min      1Q  Median      3Q     Max 
-205102  -34374   -5778   18929  163866 

Coefficients:
              Estimate Std. Error t value Pr(&gt;|t|)    
(Intercept) -40230.867  14696.140  -2.738  0.00737 ** 
Size           116.132      8.795  13.204  &lt; 2e-16 ***
New          57736.283  18653.041   3.095  0.00257 ** 
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 53880 on 97 degrees of freedom
Multiple R-squared:  0.7226,    Adjusted R-squared:  0.7169 
F-statistic: 126.3 on 2 and 97 DF,  p-value: &lt; 2.2e-16</code></pre>
</div>
</div>
</section>
<section id="b-report-and-interpret-the-prediction-equation-and-form-separate-equations-relating-selling-price-to-size-for-new-and-for-not-new-homes." class="level4">
<h4 class="anchored" data-anchor-id="b-report-and-interpret-the-prediction-equation-and-form-separate-equations-relating-selling-price-to-size-for-new-and-for-not-new-homes.">b) Report and interpret the prediction equation, and form separate equations relating selling price to size for new and for not new homes.</h4>
<p>In this scenario, y= -40230.87+116.13x1+57736.28x2. x1 represents house size and x2 represents whether the home is new or not. Now I will conduct a multiple regression analysis to show the relationship between a new home’s selling price and its size.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb47"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb47-1"><a href="#cb47-1" aria-hidden="true" tabindex="-1"></a>new_sp <span class="ot">&lt;-</span> <span class="fu">lm</span>(<span class="at">formula=</span>Price<span class="sc">~</span>New<span class="sc">+</span>Size,<span class="at">data=</span>house.selling.price)</span>
<span id="cb47-2"><a href="#cb47-2" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(new_sp)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = Price ~ New + Size, data = house.selling.price)

Residuals:
    Min      1Q  Median      3Q     Max 
-205102  -34374   -5778   18929  163866 

Coefficients:
              Estimate Std. Error t value Pr(&gt;|t|)    
(Intercept) -40230.867  14696.140  -2.738  0.00737 ** 
New          57736.283  18653.041   3.095  0.00257 ** 
Size           116.132      8.795  13.204  &lt; 2e-16 ***
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 53880 on 97 degrees of freedom
Multiple R-squared:  0.7226,    Adjusted R-squared:  0.7169 
F-statistic: 126.3 on 2 and 97 DF,  p-value: &lt; 2.2e-16</code></pre>
</div>
</div>
<p>And now a correlation test to go a step further.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb49"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb49-1"><a href="#cb49-1" aria-hidden="true" tabindex="-1"></a><span class="fu">cor.test</span>(house.selling.price<span class="sc">$</span>Size,house.selling.price<span class="sc">$</span>New)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
    Pearson's product-moment correlation

data:  house.selling.price$Size and house.selling.price$New
t = 4.1212, df = 98, p-value = 7.891e-05
alternative hypothesis: true correlation is not equal to 0
95 percent confidence interval:
 0.2032530 0.5399831
sample estimates:
      cor 
0.3843277 </code></pre>
</div>
</div>
<p>Predictor variables ‘new’ and ‘size’ have p-values or 0,00257 and 2w-16 respectively. While different, both p-values are statistically significant, which indicates that the null hypothesis can be rejected. By running a correlation test, we can see that the relationship between these 2 variables is weak, as 0.384.</p>
</section>
<section id="c-find-the-predicted-selling-price-for-a-home-of-3000-square-feet-that-is-i-new-ii-not-new." class="level4">
<h4 class="anchored" data-anchor-id="c-find-the-predicted-selling-price-for-a-home-of-3000-square-feet-that-is-i-new-ii-not-new.">c) Find the predicted selling price for a home of 3000 square feet that is (i) new, (ii) not new.</h4>
<p>First let’s calculate the predicted selling price of a NEW 3000 sqft house</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb51"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb51-1"><a href="#cb51-1" aria-hidden="true" tabindex="-1"></a>predicted_spNEW <span class="ot">&lt;-</span> <span class="sc">-</span><span class="fl">40230.87+116.13</span><span class="sc">*</span><span class="dv">3000</span><span class="sc">+</span><span class="dv">57736</span></span>
<span id="cb51-2"><a href="#cb51-2" aria-hidden="true" tabindex="-1"></a>predicted_spNEW</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 365895.1</code></pre>
</div>
</div>
<p>The predicted selling price for a new house of these measurements is $365,895.10</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb53"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb53-1"><a href="#cb53-1" aria-hidden="true" tabindex="-1"></a>predicted_spOLD <span class="ot">&lt;-</span> <span class="sc">-</span><span class="fl">40230.87+116.13</span><span class="sc">*</span><span class="dv">3000</span></span>
<span id="cb53-2"><a href="#cb53-2" aria-hidden="true" tabindex="-1"></a>predicted_spOLD</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 308159.1</code></pre>
</div>
</div>
<p>The predicted selling price for a NOT new 3000 sqft house is $308,159.10</p>
</section>
<section id="d-fit-another-model-this-time-with-an-interaction-term-allowing-interaction-between-size-and-new-and-report-the-regression-results" class="level4">
<h4 class="anchored" data-anchor-id="d-fit-another-model-this-time-with-an-interaction-term-allowing-interaction-between-size-and-new-and-report-the-regression-results">d) Fit another model, this time with an interaction term allowing interaction between size and new, and report the regression results</h4>
<p>Let’s start by calculating this interaction</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb55"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb55-1"><a href="#cb55-1" aria-hidden="true" tabindex="-1"></a>interaction_size <span class="ot">&lt;-</span> <span class="fu">summary</span>(<span class="fu">lm</span>(Price<span class="sc">~</span>Size<span class="sc">+</span>New<span class="sc">+</span>Size<span class="sc">*</span>New, <span class="at">data=</span>house.selling.price))</span>
<span id="cb55-2"><a href="#cb55-2" aria-hidden="true" tabindex="-1"></a>interaction_size</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = Price ~ Size + New + Size * New, data = house.selling.price)

Residuals:
    Min      1Q  Median      3Q     Max 
-175748  -28979   -6260   14693  192519 

Coefficients:
              Estimate Std. Error t value Pr(&gt;|t|)    
(Intercept) -22227.808  15521.110  -1.432  0.15536    
Size           104.438      9.424  11.082  &lt; 2e-16 ***
New         -78527.502  51007.642  -1.540  0.12697    
Size:New        61.916     21.686   2.855  0.00527 ** 
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 52000 on 96 degrees of freedom
Multiple R-squared:  0.7443,    Adjusted R-squared:  0.7363 
F-statistic: 93.15 on 3 and 96 DF,  p-value: &lt; 2.2e-16</code></pre>
</div>
</div>
<p>With the interaction term connecting ‘size’ and ‘new’, the estimated price increase for each square foot added to a new home is $61.92. The standard error is $21.69 and the t-test value is 2.855.</p>
</section>
<section id="e-report-the-lines-relating-the-predicted-selling-price-to-the-size-for-homes-that-are-i-new-ii-not-new." class="level4">
<h4 class="anchored" data-anchor-id="e-report-the-lines-relating-the-predicted-selling-price-to-the-size-for-homes-that-are-i-new-ii-not-new.">e) Report the lines relating the predicted selling price to the size for homes that are (i) new, (ii) not new.</h4>
<div class="cell">
<div class="sourceCode cell-code" id="cb57"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb57-1"><a href="#cb57-1" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(<span class="at">data=</span>house.selling.price,<span class="fu">aes</span>(<span class="at">x=</span>Size,<span class="at">y=</span>Price, <span class="at">color=</span>New))<span class="sc">+</span></span>
<span id="cb57-2"><a href="#cb57-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_point</span>()<span class="sc">+</span></span>
<span id="cb57-3"><a href="#cb57-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_smooth</span>(<span class="at">method=</span><span class="st">"lm"</span>,<span class="at">se=</span>F)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>`geom_smooth()` using formula 'y ~ x'</code></pre>
</div>
<div class="cell-output-display">
<p><img src="KPopiela_HW4_files/figure-html/unnamed-chunk-26-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<p>The scatterplot above shows the relationship between price and house size (sqft) categorized by whether or not the home is new. Newer houses (light blue) have a higher price baseline than those that are “old” (black); most of the older homes are in the bottom left of the graph. There are also a lot more of them. Finally, none of the light blue dots are fully below the regression line, while about half (or more) of those representing older houses are well below the line.</p>
</section>
<section id="f-find-the-predicted-selling-price-for-a-home-of-3000-square-feet-that-is-i-new-ii-not-new." class="level4">
<h4 class="anchored" data-anchor-id="f-find-the-predicted-selling-price-for-a-home-of-3000-square-feet-that-is-i-new-ii-not-new.">f) Find the predicted selling price for a home of 3000 square feet that is (i) new, (ii) not new.</h4>
<div class="cell">
<div class="sourceCode cell-code" id="cb59"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb59-1"><a href="#cb59-1" aria-hidden="true" tabindex="-1"></a>new_house3000 <span class="ot">&lt;-</span> <span class="sc">-</span><span class="fl">22227.81+104.44</span><span class="sc">*</span><span class="dv">3000</span><span class="fl">-78527.50+61.9</span><span class="sc">*</span><span class="dv">3000</span><span class="sc">*</span><span class="dv">1</span></span>
<span id="cb59-2"><a href="#cb59-2" aria-hidden="true" tabindex="-1"></a>new_house3000</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 398264.7</code></pre>
</div>
</div>
<p>The predicted selling price for a new, 3000 sqft home is $398.264.70</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb61"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb61-1"><a href="#cb61-1" aria-hidden="true" tabindex="-1"></a>older_house3000 <span class="ot">&lt;-</span> <span class="sc">-</span><span class="fl">22227.81+104.4</span><span class="sc">*</span><span class="dv">3000</span></span>
<span id="cb61-2"><a href="#cb61-2" aria-hidden="true" tabindex="-1"></a>older_house3000</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 290972.2</code></pre>
</div>
</div>
<p>The predicted selling price for an older home of the same size is $290,972.20</p>
</section>
<section id="g-find-the-predicted-selling-price-for-a-home-of-1500-square-feet-that-is-i-new-ii-not-new.-comparing-to-f-explain-how-the-difference-in-predicted-selling-prices-changes-as-the-size-of-home-increases." class="level4">
<h4 class="anchored" data-anchor-id="g-find-the-predicted-selling-price-for-a-home-of-1500-square-feet-that-is-i-new-ii-not-new.-comparing-to-f-explain-how-the-difference-in-predicted-selling-prices-changes-as-the-size-of-home-increases.">g) Find the predicted selling price for a home of 1500 square feet that is (i) new, (ii) not new. Comparing to (F), explain how the difference in predicted selling prices changes as the size of home increases.</h4>
<div class="cell">
<div class="sourceCode cell-code" id="cb63"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb63-1"><a href="#cb63-1" aria-hidden="true" tabindex="-1"></a>new_house1500 <span class="ot">&lt;-</span> <span class="sc">-</span><span class="fl">22227.81+104.4</span><span class="sc">*</span><span class="dv">1500</span><span class="fl">-78527.50+61.9</span><span class="sc">*</span><span class="dv">1500</span></span>
<span id="cb63-2"><a href="#cb63-2" aria-hidden="true" tabindex="-1"></a>new_house1500</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 148694.7</code></pre>
</div>
</div>
<p>The predicted selling price for a new, 1500sqft house is $148,694.70</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb65"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb65-1"><a href="#cb65-1" aria-hidden="true" tabindex="-1"></a>older_house1500 <span class="ot">&lt;-</span> <span class="sc">-</span><span class="fl">22227.81+104.4</span><span class="sc">*</span><span class="dv">1500</span></span>
<span id="cb65-2"><a href="#cb65-2" aria-hidden="true" tabindex="-1"></a>older_house1500</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 134372.2</code></pre>
</div>
</div>
<p>The predicted selling price for an older, 1500sqft home is $134,372.20</p>
<p>Now to compare to part f.&nbsp;As size doubles in a new home the price increases by more than double, rising to $398,264.70 from $148,694.70 in new homes. For older homes, the same is also true, but with a lower range of values, rising to $290,972.20 from $134,372.20. This heavily indicates that size is much more valuable than other aspects of a given property.</p>
</section>
<section id="h-do-you-think-the-model-with-interaction-or-the-one-without-it-represents-the-relationship-of-size-and-new-to-the-outcome-price-what-makes-you-prefer-one-model-over-another" class="level4">
<h4 class="anchored" data-anchor-id="h-do-you-think-the-model-with-interaction-or-the-one-without-it-represents-the-relationship-of-size-and-new-to-the-outcome-price-what-makes-you-prefer-one-model-over-another">h) Do you think the model with interaction or the one without it represents the relationship of size and new to the outcome price? What makes you prefer one model over another?</h4>
<p>I think both models could work, but if you’re looking specifically at the relationship between ‘size’ and ‘new’ and the selling price, I think the one without the interaction is better. They don’t necessarily need to interact with each other in order to show their relationship to the price of the home.</p>


</section>
</section>

</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const disableStylesheet = (stylesheets) => {
    for (let i=0; i < stylesheets.length; i++) {
      const stylesheet = stylesheets[i];
      stylesheet.rel = 'prefetch';
    }
  }
  const enableStylesheet = (stylesheets) => {
    for (let i=0; i < stylesheets.length; i++) {
      const stylesheet = stylesheets[i];
      stylesheet.rel = 'stylesheet';
    }
  }
  const manageTransitions = (selector, allowTransitions) => {
    const els = window.document.querySelectorAll(selector);
    for (let i=0; i < els.length; i++) {
      const el = els[i];
      if (allowTransitions) {
        el.classList.remove('notransition');
      } else {
        el.classList.add('notransition');
      }
    }
  }
  const toggleColorMode = (alternate) => {
    // Switch the stylesheets
    const alternateStylesheets = window.document.querySelectorAll('link.quarto-color-scheme.quarto-color-alternate');
    manageTransitions('#quarto-margin-sidebar .nav-link', false);
    if (alternate) {
      enableStylesheet(alternateStylesheets);
      for (const sheetNode of alternateStylesheets) {
        if (sheetNode.id === "quarto-bootstrap") {
          toggleBodyColorMode(sheetNode);
        }
      }
    } else {
      disableStylesheet(alternateStylesheets);
      toggleBodyColorPrimary();
    }
    manageTransitions('#quarto-margin-sidebar .nav-link', true);
    // Switch the toggles
    const toggles = window.document.querySelectorAll('.quarto-color-scheme-toggle');
    for (let i=0; i < toggles.length; i++) {
      const toggle = toggles[i];
      if (toggle) {
        if (alternate) {
          toggle.classList.add("alternate");     
        } else {
          toggle.classList.remove("alternate");
        }
      }
    }
  }
  const isFileUrl = () => { 
    return window.location.protocol === 'file:';
  }
  const hasAlternateSentinel = () => {  
    let styleSentinel = getColorSchemeSentinel();
    if (styleSentinel !== null) {
      return styleSentinel === "alternate";
    } else {
      return false;
    }
  }
  const setStyleSentinel = (alternate) => {
    const value = alternate ? "alternate" : "default";
    if (!isFileUrl()) {
      window.localStorage.setItem("quarto-color-scheme", value);
    } else {
      localAlternateSentinel = value;
    }
  }
  const getColorSchemeSentinel = () => {
    if (!isFileUrl()) {
      const storageValue = window.localStorage.getItem("quarto-color-scheme");
      return storageValue != null ? storageValue : localAlternateSentinel;
    } else {
      return localAlternateSentinel;
    }
  }
  let localAlternateSentinel = 'default';
  // Dark / light mode switch
  window.quartoToggleColorScheme = () => {
    // Read the current dark / light value 
    let toAlternate = !hasAlternateSentinel();
    toggleColorMode(toAlternate);
    setStyleSentinel(toAlternate);
  };
  // Ensure there is a toggle, if there isn't float one in the top right
  if (window.document.querySelector('.quarto-color-scheme-toggle') === null) {
    const a = window.document.createElement('a');
    a.classList.add('top-right');
    a.classList.add('quarto-color-scheme-toggle');
    a.href = "";
    a.onclick = function() { try { window.quartoToggleColorScheme(); } catch {} return false; };
    const i = window.document.createElement("i");
    i.classList.add('bi');
    a.appendChild(i);
    window.document.body.appendChild(a);
  }
  // Switch to dark mode if need be
  if (hasAlternateSentinel()) {
    toggleColorMode(true);
  } 
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const clipboard = new window.ClipboardJS('.code-copy-button', {
    target: function(trigger) {
      return trigger.previousElementSibling;
    }
  });
  clipboard.on('success', function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copied!");
    setTimeout(function() {
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  });
  function tippyHover(el, contentFn) {
    const config = {
      allowHTML: true,
      content: contentFn,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start'
    };
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      let href = ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      return note.innerHTML;
    });
  }
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const cites = ref.parentNode.getAttribute('data-cites').split(' ');
    tippyHover(ref, function() {
      var popup = window.document.createElement('div');
      cites.forEach(function(cite) {
        var citeDiv = window.document.createElement('div');
        citeDiv.classList.add('hanging-indent');
        citeDiv.classList.add('csl-entry');
        var biblioDiv = window.document.getElementById('ref-' + cite);
        if (biblioDiv) {
          citeDiv.innerHTML = biblioDiv.innerHTML;
        }
        popup.appendChild(citeDiv);
      });
      return popup.innerHTML;
    });
  }
});
</script>
<script src="https://giscus.app/client.js" data-repo="DACSS/603_Fall_2022" data-repo-id="R_kgDOH568kA" data-category="Announcements" data-category-id="" data-mapping="title" data-reactions-enabled="1" data-emit-metadata="0" data-input-position="top" data-theme="light" data-lang="en" crossorigin="anonymous" async="">
</script>
</div> <!-- /content -->



</body></html>