<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.2.269">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">


<title>KPopiela_Finalp2</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1.6em;
  vertical-align: middle;
}
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
    color: #aaaaaa;
  }
pre.numberSource { margin-left: 3em; border-left: 1px solid #aaaaaa;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
code span.al { color: #ff0000; font-weight: bold; } /* Alert */
code span.an { color: #60a0b0; font-weight: bold; font-style: italic; } /* Annotation */
code span.at { color: #7d9029; } /* Attribute */
code span.bn { color: #40a070; } /* BaseN */
code span.bu { color: #008000; } /* BuiltIn */
code span.cf { color: #007020; font-weight: bold; } /* ControlFlow */
code span.ch { color: #4070a0; } /* Char */
code span.cn { color: #880000; } /* Constant */
code span.co { color: #60a0b0; font-style: italic; } /* Comment */
code span.cv { color: #60a0b0; font-weight: bold; font-style: italic; } /* CommentVar */
code span.do { color: #ba2121; font-style: italic; } /* Documentation */
code span.dt { color: #902000; } /* DataType */
code span.dv { color: #40a070; } /* DecVal */
code span.er { color: #ff0000; font-weight: bold; } /* Error */
code span.ex { } /* Extension */
code span.fl { color: #40a070; } /* Float */
code span.fu { color: #06287e; } /* Function */
code span.im { color: #008000; font-weight: bold; } /* Import */
code span.in { color: #60a0b0; font-weight: bold; font-style: italic; } /* Information */
code span.kw { color: #007020; font-weight: bold; } /* Keyword */
code span.op { color: #666666; } /* Operator */
code span.ot { color: #007020; } /* Other */
code span.pp { color: #bc7a00; } /* Preprocessor */
code span.sc { color: #4070a0; } /* SpecialChar */
code span.ss { color: #bb6688; } /* SpecialString */
code span.st { color: #4070a0; } /* String */
code span.va { color: #19177c; } /* Variable */
code span.vs { color: #4070a0; } /* VerbatimString */
code span.wa { color: #60a0b0; font-weight: bold; font-style: italic; } /* Warning */
</style>


<script src="../site_libs/quarto-nav/quarto-nav.js"></script>
<script src="../site_libs/quarto-nav/headroom.min.js"></script>
<script src="../site_libs/clipboard/clipboard.min.js"></script>
<script src="../site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="../site_libs/quarto-search/fuse.min.js"></script>
<script src="../site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="../">
<link href="../images/DACSS_Round_Network.png" rel="icon" type="image/png">
<script src="../site_libs/quarto-html/quarto.js"></script>
<script src="../site_libs/quarto-html/popper.min.js"></script>
<script src="../site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="../site_libs/quarto-html/anchor.min.js"></script>
<link href="../site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="../site_libs/quarto-html/quarto-syntax-highlighting.css" rel="stylesheet" class="quarto-color-scheme" id="quarto-text-highlighting-styles">
<link href="../site_libs/quarto-html/quarto-syntax-highlighting-dark.css" rel="prefetch" class="quarto-color-scheme quarto-color-alternate" id="quarto-text-highlighting-styles">
<script src="../site_libs/bootstrap/bootstrap.min.js"></script>
<link href="../site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="../site_libs/bootstrap/bootstrap.min.css" rel="stylesheet" class="quarto-color-scheme" id="quarto-bootstrap" data-mode="light">
<link href="../site_libs/bootstrap/bootstrap-dark.min.css" rel="prefetch" class="quarto-color-scheme quarto-color-alternate" id="quarto-bootstrap" data-mode="dark">
<script id="quarto-search-options" type="application/json">{
  "location": "navbar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "end",
  "type": "overlay",
  "limit": 20,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit"
  }
}</script>


<meta name="twitter:title" content="KPopiela_Finalp2">
<meta name="twitter:description" content="##Intro and Background Info">
<meta name="twitter:creator" content="@UMassDACSS">
<meta name="twitter:site" content="@UMassDACSS">
<meta name="twitter:card" content="summary">
</head>

<body class="nav-fixed">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
    <nav class="navbar navbar-expand-lg navbar-dark ">
      <div class="navbar-container container-fluid">
      <div class="navbar-brand-container">
    <a href="../index.html" class="navbar-brand navbar-brand-logo">
    <img src="../images/UMass White Wordmark Horiz.png" alt="" class="navbar-logo">
    </a>
  </div>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse" aria-controls="navbarCollapse" aria-expanded="false" aria-label="Toggle navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
  <span class="navbar-toggler-icon"></span>
</button>
          <div class="collapse navbar-collapse" id="navbarCollapse">
            <ul class="navbar-nav navbar-nav-scroll ms-auto">
  <li class="nav-item">
    <a class="nav-link" href="https://dacss.github.io/603_Fall_2022/">
 <span class="menu-text">Fall 2022 Posts</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="../about.html">
 <span class="menu-text">Contributors</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="https://umass.edu/sbs/dacss">
 <span class="menu-text">DACSS</span></a>
  </li>  
  <li class="nav-item compact">
    <a class="nav-link" href="https://github.com/DACSS/603_Fall_2022"><i class="bi bi-github" role="img" aria-label="GitHub">
</i> 
 <span class="menu-text"></span></a>
  </li>  
</ul>
              <div class="quarto-toggle-container">
                  <a href="" class="quarto-color-scheme-toggle nav-link" onclick="window.quartoToggleColorScheme(); return false;" title="Toggle dark mode"><i class="bi"></i></a>
              </div>
              <div id="quarto-search" class="" title="Search"></div>
          </div> <!-- /navcollapse -->
      </div> <!-- /container-fluid -->
    </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article page-navbar">
<!-- sidebar -->
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">On this page</h2>
   
  <ul>
  <li><a href="#regime_type3-confidence-effectiveness-regime_type3-and-unnetuse" id="toc-regime_type3-confidence-effectiveness-regime_type3-and-unnetuse" class="nav-link active" data-scroll-target="#regime_type3-confidence-effectiveness-regime_type3-and-unnetuse">1) ‘regime_type3’, ‘confidence’, ‘effectiveness’, ‘regime_type3’, and ‘unnetuse’</a></li>
  <li><a href="#hypothesis-testing-analysis" id="toc-hypothesis-testing-analysis" class="nav-link" data-scroll-target="#hypothesis-testing-analysis">Hypothesis Testing, Analysis</a></li>
  </ul>
</nav>
    </div>
<!-- main -->
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title">KPopiela_Finalp2</h1>
</div>



<div class="quarto-title-meta">

    
  
    
  </div>
  

</header>

<div class="cell">
<div class="sourceCode cell-code" id="cb1"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(poliscidata)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>Registered S3 method overwritten by 'gdata':
  method         from  
  reorder.factor gplots</code></pre>
</div>
<div class="sourceCode cell-code" id="cb3"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb3-1"><a href="#cb3-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(dplyr)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>
Attaching package: 'dplyr'</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>The following objects are masked from 'package:stats':

    filter, lag</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>The following objects are masked from 'package:base':

    intersect, setdiff, setequal, union</code></pre>
</div>
<div class="sourceCode cell-code" id="cb7"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb7-1"><a href="#cb7-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(tidyr)</span>
<span id="cb7-2"><a href="#cb7-2" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(stats)</span>
<span id="cb7-3"><a href="#cb7-3" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(ggplot2)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>##Intro and Background Info</p>
<p>I’ve had more time to think about my final, and I’ve decided to simplify my research topic. Rather than look at ethnic conflict, I’m going to look at how internet usage affects a people’s confidence in their country (institutions and governance). In order to focus on this relationship, I will be using the ‘world’ data set in the ‘poliscidata’ package, and I will be using the following variables: ‘country’, ‘unnetuse’ (internet usage per 100 people), confidence (population’s confidence in their country’s institutions; scaled out of 100), and ‘effectiveness’ (government effectiveness scale).</p>
<p>Below is a general presentation of the data I will be using, filtered down as I described.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb8"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb8-1"><a href="#cb8-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(poliscidata) <span class="sc">%&gt;%</span></span>
<span id="cb8-2"><a href="#cb8-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">data</span>(<span class="st">"world"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning in data(., "world"): data set '.' not found</code></pre>
</div>
<div class="sourceCode cell-code" id="cb10"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb10-1"><a href="#cb10-1" aria-hidden="true" tabindex="-1"></a>world <span class="sc">%&gt;%</span></span>
<span id="cb10-2"><a href="#cb10-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">select</span>(country,regime_type3,unnetuse,confidence,effectiveness)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>                              country        regime_type3 unnetuse confidence
1                         Afghanistan        Dictatorship      1.7         NA
2                             Albania Parliamentary democ     23.9  49.335926
3                             Algeria        Dictatorship     11.9  52.055735
4                              Angola        Dictatorship      3.1         NA
5                           Argentina  Presidential democ     28.1   7.299325
6                             Armenia                &lt;NA&gt;      6.2  27.132735
7                           Australia Parliamentary democ     70.8  46.838886
8                             Austria Parliamentary democ     71.2  49.680190
9                          Azerbaijan        Dictatorship     28.2  54.168485
10                            Bahrain        Dictatorship     51.9         NA
11                         Bangladesh Parliamentary democ      0.3  71.644389
12                            Belarus        Dictatorship     32.1  15.645705
13                            Belgium Parliamentary democ     68.1  43.315162
14                              Benin  Presidential democ      1.8         NA
15                             Bhutan        Dictatorship      6.6         NA
16                            Bolivia  Presidential democ     10.8         NA
17             Bosnia and Herzegovina        Dictatorship     34.7  70.204136
18                           Botswana        Dictatorship      6.2         NA
19                             Brazil  Presidential democ     37.5  32.501337
20                           Bulgaria Parliamentary democ     34.7  38.976006
21                       Burkina Faso        Dictatorship      0.9         NA
22                    Burma (Myanmar)                &lt;NA&gt;      0.2         NA
23                            Burundi        Dictatorship      0.8         NA
24                           Cambodia        Dictatorship      0.5         NA
25                           Cameroon        Dictatorship      3.8         NA
26                             Canada Parliamentary democ     75.3  58.203871
27                         Cape Verde Parliamentary democ     20.6         NA
28           Central African Republic                &lt;NA&gt;      0.4         NA
29                               Chad        Dictatorship      1.2         NA
30                              Chile  Presidential democ     32.5  58.368495
31                              China        Dictatorship     22.5  73.788814
32                           Colombia  Presidential democ     38.5         NA
33                            Comoros        Dictatorship      3.6         NA
34  Congo, Democratic Republic of the                &lt;NA&gt;       NA         NA
35             Congo, Republic of the                &lt;NA&gt;      4.3         NA
36                         Costa Rica  Presidential democ     32.3         NA
37                      Cote d'Ivoire  Presidential democ      3.2         NA
38                            Croatia                &lt;NA&gt;     50.5  44.175465
39                               Cuba        Dictatorship     12.9         NA
40                             Cyprus  Presidential democ     38.8         NA
41                     Czech Republic Parliamentary democ     57.8  35.172868
42                            Denmark Parliamentary democ     83.3  63.137017
43                           Djibouti        Dictatorship      2.3         NA
44                 Dominican Republic                &lt;NA&gt;     21.6         NA
45                            Ecuador        Dictatorship     28.8         NA
46                              Egypt        Dictatorship     16.6  59.227665
47                        El Salvador  Presidential democ     10.6  41.978817
48                  Equatorial Guinea        Dictatorship      1.8         NA
49                            Eritrea        Dictatorship      4.1         NA
50                            Estonia Parliamentary democ     66.2  39.182308
51                           Ethiopia        Dictatorship      0.4         NA
52                               Fiji        Dictatorship     12.2         NA
53                            Finland Parliamentary democ     82.0  46.875924
54                             France                &lt;NA&gt;     67.9  55.116509
55                              Gabon        Dictatorship      6.2         NA
56                        Gambia, The                &lt;NA&gt;      6.9         NA
57                            Georgia        Dictatorship     23.8  38.627903
58                            Germany Parliamentary democ     75.5  52.728927
59                              Ghana  Presidential democ      4.3         NA
60                             Greece Parliamentary democ     43.1         NA
61                          Guatemala  Presidential democ     14.3         NA
62                             Guinea        Dictatorship      0.9         NA
63                      Guinea-Bissau  Presidential democ      2.4         NA
64                             Guyana  Presidential democ     26.9         NA
65                              Haiti                &lt;NA&gt;     10.1         NA
66                           Honduras  Presidential democ     13.1         NA
67                          Hong Kong                &lt;NA&gt;     67.0         NA
68                            Hungary Parliamentary democ     58.5  45.543249
69                            Iceland                &lt;NA&gt;     59.0  63.628568
70                              India Parliamentary democ      4.5  62.205316
71                          Indonesia  Presidential democ      7.9  50.531385
72                               Iran        Dictatorship     32.0  57.685353
73                               Iraq Parliamentary democ      1.0         NA
74                            Ireland Parliamentary democ     62.7  68.497642
75                             Israel Parliamentary democ     47.9         NA
76                              Italy Parliamentary democ     41.8  37.016570
77                            Jamaica Parliamentary democ     57.3         NA
78                              Japan Parliamentary democ     75.2  37.033760
79                             Jordan        Dictatorship     27.0  73.628692
80                         Kazakhstan        Dictatorship     10.9         NA
81                              Kenya  Presidential democ      8.7         NA
82                       Korea, North                &lt;NA&gt;      0.0         NA
83                       Korea, South                &lt;NA&gt;     75.8         NA
84                             Kuwait        Dictatorship     36.7         NA
85                         Kyrgyzstan        Dictatorship     16.1         NA
86                               Laos        Dictatorship      8.5         NA
87                             Latvia Parliamentary democ     60.4  39.220066
88                            Lebanon        Dictatorship     22.5         NA
89                            Lesotho Parliamentary democ      3.6         NA
90                            Liberia        Dictatorship      0.5         NA
91                              Libya        Dictatorship      5.1         NA
92                          Lithuania                &lt;NA&gt;     54.4  48.126086
93                         Luxembourg Parliamentary democ     79.2         NA
94                          Macedonia Parliamentary democ     41.5  12.330052
95                         Madagascar                &lt;NA&gt;      1.7         NA
96                             Malawi  Presidential democ      2.1         NA
97                           Malaysia        Dictatorship     55.8         NA
98                               Mali                &lt;NA&gt;      1.6         NA
99                              Malta Parliamentary democ     48.3         NA
100                        Mauritania        Dictatorship      1.9         NA
101                         Mauritius Parliamentary democ     22.2         NA
102                            Mexico  Presidential democ     22.2  26.040388
103                           Moldova                &lt;NA&gt;     23.4  42.191709
104                          Mongolia                &lt;NA&gt;     12.5         NA
105                        Montenegro                &lt;NA&gt;     47.2         NA
106                           Morocco        Dictatorship     33.0         NA
107                        Mozambique        Dictatorship      1.6         NA
108                           Namibia  Presidential democ      5.3         NA
109                             Nepal Parliamentary democ      1.7         NA
110                       Netherlands Parliamentary democ     87.0  58.481013
111                       New Zealand Parliamentary democ     71.4  38.105963
112                         Nicaragua  Presidential democ      3.3         NA
113                             Niger                &lt;NA&gt;      0.5         NA
114                           Nigeria  Presidential democ     15.9  59.358170
115                            Norway Parliamentary democ     82.5  66.453811
116                              Oman        Dictatorship     20.0         NA
117                          Pakistan        Dictatorship     11.1  51.238722
118                         Palestine                &lt;NA&gt;      9.0         NA
119                            Panama  Presidential democ     27.5         NA
120                  Papua New Guinea Parliamentary democ      1.8         NA
121                          Paraguay        Dictatorship     14.3         NA
122                              Peru        Dictatorship     24.7   6.494946
123                       Philippines  Presidential democ      6.2  63.305240
124                            Poland                &lt;NA&gt;     49.0  65.605741
125                          Portugal                &lt;NA&gt;     42.1  37.364882
126                             Qatar        Dictatorship     34.0         NA
127                           Romania                &lt;NA&gt;     28.8  26.884683
128                            Russia                &lt;NA&gt;     31.9  41.145354
129                            Rwanda        Dictatorship      3.1         NA
130                      Saudi Arabia        Dictatorship     31.5         NA
131                           Senegal                &lt;NA&gt;      8.4         NA
132                            Serbia                &lt;NA&gt;     44.9         NA
133                      Sierra Leone  Presidential democ      0.3         NA
134                         Singapore        Dictatorship     69.6         NA
135                          Slovakia Parliamentary democ     66.0  25.269169
136                          Slovenia Parliamentary democ     55.7  39.855957
137                      South Africa Parliamentary democ      8.6  66.400869
138                             Spain Parliamentary democ     55.4  42.274258
139                         Sri Lanka                &lt;NA&gt;      5.8         NA
140                             Sudan        Dictatorship     10.2         NA
141                          Suriname  Presidential democ      9.7         NA
142                         Swaziland        Dictatorship      6.9         NA
143                            Sweden Parliamentary democ     87.7  56.535110
144                       Switzerland  Presidential democ     75.9  56.553995
145                             Syria        Dictatorship     17.3         NA
146                            Taiwan                &lt;NA&gt;       NA  49.197820
147                        Tajikistan        Dictatorship      8.8         NA
148                          Tanzania        Dictatorship      1.2  78.852623
149                          Thailand Parliamentary democ     23.9         NA
150                       Timor-Leste                &lt;NA&gt;       NA         NA
151                              Togo        Dictatorship      5.4         NA
152               Trinidad and Tobago                &lt;NA&gt;     17.0         NA
153                           Tunisia        Dictatorship     27.1         NA
154                            Turkey Parliamentary democ     34.4  57.070574
155                      Turkmenistan        Dictatorship      1.5         NA
156                            Uganda        Dictatorship      7.9  70.747317
157                           Ukraine                &lt;NA&gt;     10.5  36.022627
158              United Arab Emirates                &lt;NA&gt;     65.2         NA
159                    United Kingdom Parliamentary democ     76.0  56.467760
160                     United States  Presidential democ     75.9  61.785208
161                           Uruguay  Presidential democ     40.2  43.417722
162                        Uzbekistan        Dictatorship      9.0         NA
163                         Venezuela  Presidential democ     25.7  21.375093
164                           Vietnam        Dictatorship     24.2  99.862411
165                             Yemen        Dictatorship      1.6         NA
166                            Zambia  Presidential democ      5.5         NA
167                          Zimbabwe        Dictatorship     11.4  60.019029
    effectiveness
1       13.711584
2       35.460993
3       32.624114
4       19.148937
5       34.988179
6       36.643026
7       90.070923
8       88.888888
9       23.877069
10      65.011820
11      34.042554
12      22.222223
13      90.307329
14      31.914894
15      68.557920
16      34.042554
17      25.295509
18      67.139480
19      41.371158
20      45.153664
21      30.260047
22             NA
23      12.056737
24      33.333333
25      31.914894
26      91.016548
27      41.843972
28      12.765959
29      28.841608
30      74.704493
31      50.827423
32      37.352246
33      26.713949
34             NA
35             NA
36      55.319149
37      25.531915
38      51.063830
39      40.425532
40      70.212766
41      63.120567
42      93.617022
43      25.768322
44             NA
45      23.877069
46      39.007092
47      34.042554
48      14.184397
49      36.170213
50      65.011820
51      25.531915
52      47.990544
53      94.089834
54      86.052008
55      35.933806
56             NA
57      28.368795
58      88.179669
59      46.808511
60      65.248227
61      32.151300
62      28.132388
63      14.657210
64      39.007092
65       9.692673
66      29.314420
67             NA
68      65.011820
69      93.380615
70      43.498818
71      33.333333
72      35.697399
73       7.801419
74      84.869976
75      70.685579
76      68.085107
77      44.917258
78      71.867614
79      55.082743
80      27.659574
81      26.477541
82             NA
83             NA
84      50.354610
85      27.423168
86      27.659574
87      62.411348
88      36.879433
89      40.425532
90      10.874705
91      26.004728
92      60.992908
93      96.926717
94      37.352246
95      37.588653
96      30.496454
97      68.321513
98      26.713949
99      73.995271
100     42.789598
101     59.101654
102     50.118203
103     31.678487
104     42.316785
105            NA
106     48.226950
107     36.879433
108     50.827423
109     34.515367
110     97.163123
111     93.144209
112     26.004728
113     27.895981
114     20.094563
115     90.070923
116     62.884161
117     34.751773
118            NA
119     43.262411
120     28.132388
121     16.075651
122     35.460993
123     45.153664
124     60.992908
125     70.921985
126     62.884161
127     38.770685
128     37.115839
129     27.186761
130     45.390071
131     42.316785
132            NA
133     10.165486
134    100.000000
135     56.028369
136     65.957447
137     58.865248
138     82.742316
139     47.281324
140     20.330969
141     42.789598
142     36.170213
143     90.070923
144    100.000000
145     33.096927
146     70.212766
147     17.494089
148     34.515367
149     53.191489
150            NA
151     18.912531
152            NA
153     61.938534
154     41.843972
155     11.820330
156     36.879433
157     29.078014
158            NA
159     94.562647
160     86.761230
161     58.628841
162     20.567375
163     19.621750
164     40.189125
165     26.004728
166     24.586288
167     27.659574</code></pre>
</div>
</div>
<p>The internet and media consumption play a massive role in politics now; at this point, it’s pretty much expected to find out what is happening in the world on the internet (newspapers, social media, etc.). And as we’ve seen since the 2016 election, the internet also plays a substantial role in domestic politics, whether it be through neutral journalism, activism, whistle-blowing, or misinformation. It is both good and bad, and as Stanford professor Evgeny Morozov writes, the internet’s impact “will depend on individual conditions” such as a given country’s political atmosphere (peaceful, volatile, conservative, liberal, etc.), ease of access to the internet, and how united a population is either in favor or against their current government (“The Internet, Politics and the Politics of Internet Debate”). So, what <em>/is/</em> the relationship between internet use and domestic politics?</p>
<p>Based on my personal and academic experience, I hypothesize that while internet usage definitely does affect people’s confidence in their government, I do not think that it automatically hinders government effectiveness. If a certain country’s subjects have extremely little confidence in its government, the government would have no legitimacy (and would therefore be ineffective); a government’s power largely comes from its subjects’ willingness to accept it. However, there are instances where a country’s population has little confidence in its government with no effect on its efficacy. But, again, for this project I will be focusing on how internet usage impacts confidence in a given regime.</p>
<p>Now to transcribe my research question: Does internet usage (social media, news, etc.) have an impact on people’s confidence in their government (‘confidence’)? If so, is said government more or less effective in its duties?</p>
<p>First, lets look at some summary statistics.</p>
<section id="regime_type3-confidence-effectiveness-regime_type3-and-unnetuse" class="level3">
<h3 class="anchored" data-anchor-id="regime_type3-confidence-effectiveness-regime_type3-and-unnetuse">1) ‘regime_type3’, ‘confidence’, ‘effectiveness’, ‘regime_type3’, and ‘unnetuse’</h3>
<div class="cell">
<div class="sourceCode cell-code" id="cb12"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb12-1"><a href="#cb12-1" aria-hidden="true" tabindex="-1"></a>world_filter <span class="ot">&lt;-</span> world <span class="sc">%&gt;%</span></span>
<span id="cb12-2"><a href="#cb12-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">select</span>(country,regime_type3,confidence,effectiveness,unnetuse)</span>
<span id="cb12-3"><a href="#cb12-3" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(world_filter)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>        country                 regime_type3   confidence     effectiveness    
 Afghanistan:  1   Dictatorship       :61    Min.   : 6.495   Min.   :  7.801  
 Albania    :  1   Parliamentary democ:41    1st Qu.:38.889   1st Qu.: 28.132  
 Algeria    :  1   Presidential democ :31    Median :49.508   Median : 39.007  
 Angola     :  1   NA's               :34    Mean   :48.900   Mean   : 46.036  
 Argentina  :  1                             3rd Qu.:59.523   3rd Qu.: 62.884  
 Armenia    :  1                             Max.   :99.862   Max.   :100.000  
 (Other)    :161                             NA's   :99       NA's   :14       
    unnetuse    
 Min.   : 0.00  
 1st Qu.: 5.25  
 Median :18.65  
 Mean   :26.78  
 3rd Qu.:42.35  
 Max.   :87.70  
 NA's   :3      </code></pre>
</div>
</div>
<ol type="a">
<li><p>regime_type3 – There are 167 entries in the filtered down dataset I am using. Dividing that, 61 countries are classified as dictatorships, 41 as a parliamentary democracy, 34 N/A responses/unclassified regimes, and 31 presidential democracies. Not having doen any statistical analysis yet I can’t speak for the values’ mathematical significance, but politically, it is important to note that 61/167 countries in the data set are classified as dictatorships.</p></li>
<li><p>confidence – Confidence scores in this data set are scaled from 1-100. The minimum confidence score is 6.495 and the maximum, obviously is 100.000. The mean value, 48.508, is below 50.000 which indicates that there are slightly more scores under than 50.000 than over. The median is 49.508 and the 1st and 3rd quantiles are 38.889 and 59.523 respectively. However, these values are not so low that there’s an implication of a widespread (and severe) sense that peoples’ governments are incompetent.</p></li>
<li><p>effectiveness – Similar to ‘confidence’, ‘effectiveness’ is scaled out of 100. Unlike ‘confidence’, however, this variable presents a numerical representation of how effective regimes are at governance (actual governance, welfare, infrastructure/services). The summary values for this variable are, overall, lower than their counterparts under ‘confidence’. The minimum value is 7.801, and the mean is 46.036. The median, 1st, and 3rd quantiles are 39.007, 28.132, and 62.884 respectively. While currently untested, these figures indicate that whether or not people have confidence in their government, said government is not necessarily effective to the same degree.</p></li>
<li><p>unnetuse – Unlike the previous 2 variables, this one is scaled as a percentage of each country’s total population, specifically the number of internet users per 100 people. This variable is more practically tangible; the values are calculated as a percentage, but since it’s also out of 100 people, it’s easy to conceptualize the 1st quantile value for instance: 5.25, which would be about 5 people per 100. On that note, the maximum value, 87.70, is indicative of a high percentage of internet users in a given state.</p></li>
</ol>
</section>
<section id="hypothesis-testing-analysis" class="level2">
<h2 class="anchored" data-anchor-id="hypothesis-testing-analysis">Hypothesis Testing, Analysis</h2>
<p>I will start with some preliminary graphs/visualizations.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb14"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb14-1"><a href="#cb14-1" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(<span class="at">data=</span>world_filter, <span class="fu">aes</span>(<span class="at">x=</span>unnetuse,<span class="at">y=</span>confidence, <span class="at">color=</span>regime_type3)) <span class="sc">+</span> <span class="fu">geom_point</span>() </span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning: Removed 100 rows containing missing values (geom_point).</code></pre>
</div>
<div class="cell-output-display">
<p><img src="KPopiela_FinalP2_files/figure-html/unnamed-chunk-4-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<p>This scatterplot, which measures the relationship between internet usage and popular confidence in government, has no obvious relationship or correlation. The points are grouped by color based on regime type, but there is no notable increase or decrease in the points’ location as a variable increases or decreases. The vast majority of values are located in the middle of the graph.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb16"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb16-1"><a href="#cb16-1" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(<span class="at">data=</span>world_filter, <span class="fu">aes</span>(<span class="at">x=</span>confidence,<span class="at">y=</span>effectiveness, <span class="at">color=</span>regime_type3)) <span class="sc">+</span> <span class="fu">geom_point</span>() </span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning: Removed 99 rows containing missing values (geom_point).</code></pre>
</div>
<div class="cell-output-display">
<p><img src="KPopiela_FinalP2_files/figure-html/unnamed-chunk-5-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<p>While there still isn’t a traditional positive or negative relationship between ‘confidence’ and ‘effectiveness’, it is noteworthy that the majority of values are in the center of the graph. They have a wide range, but they are mostly within 25 and 75 on the x-axis, which does make sense giving that the 1st and 3rd quantiles are included in the initial summary statistics.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb18"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb18-1"><a href="#cb18-1" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(world_filter, <span class="fu">aes</span>(<span class="at">x=</span>unnetuse,<span class="at">y=</span>confidence,<span class="at">color=</span>regime_type3)) <span class="sc">+</span> <span class="fu">geom_point</span>() <span class="sc">+</span> <span class="fu">stat_smooth</span>(<span class="at">method=</span><span class="st">"lm"</span>,<span class="at">col=</span><span class="st">"blue"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>`geom_smooth()` using formula 'y ~ x'</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning: Removed 100 rows containing non-finite values (stat_smooth).</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning: Removed 100 rows containing missing values (geom_point).</code></pre>
</div>
<div class="cell-output-display">
<p><img src="KPopiela_FinalP2_files/figure-html/unnamed-chunk-6-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<p>This visualization is a recreation of the first scatterplot, but with a multiple regression line. The line, at first glance, is straight, but upon closer inspection it ever so slightly slopes down toward the right. This indicates a slightly negative relationship between internet usage (x) and confidence in government institutions (y).</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb22"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb22-1"><a href="#cb22-1" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(world_filter, <span class="fu">aes</span>(<span class="at">x=</span>unnetuse,<span class="at">y=</span>effectiveness,<span class="at">color=</span>regime_type3)) <span class="sc">+</span> <span class="fu">geom_point</span>() <span class="sc">+</span> <span class="fu">stat_smooth</span>(<span class="at">method=</span><span class="st">"lm"</span>,<span class="at">col=</span><span class="st">"blue"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>`geom_smooth()` using formula 'y ~ x'</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning: Removed 15 rows containing non-finite values (stat_smooth).</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning: Removed 15 rows containing missing values (geom_point).</code></pre>
</div>
<div class="cell-output-display">
<p><img src="KPopiela_FinalP2_files/figure-html/unnamed-chunk-7-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<p>The above scatterplot, however, depicts a very clear positive relationship between variables ‘unnetuse’ (x) and ‘effectiveness’ (y). This is indicative of a strong relationship between internet use and government effectiveness. There is what appears to be a heavier concentration of points below 50 on the x-axis, but the general trend is pretty clear that government effectiveness increases as nationals’ internet use does. Although ‘unnetuse’ comes from a 2008 survey, I would argue that this trend still holds up; especially due to COVID-19, the main way that politicians engage with their constituents is on the internet (social media). There is not really a culture of “visit your politician and talk to them” culture anymore, the new norm is for sucht things to be done over the phone, over email, or in some form, over the internet.</p>
<p>My next step is to go into modeling. I’m going to start with a linear regression model. ‘confidence’ is the dependent variable, and ‘unnetuse’, ‘effectiveness’, and ‘regime_type3’ are all independent.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb26"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb26-1"><a href="#cb26-1" aria-hidden="true" tabindex="-1"></a>confidence_lm <span class="ot">&lt;-</span> <span class="fu">lm</span>(confidence<span class="sc">~</span>unnetuse<span class="sc">+</span>effectiveness<span class="sc">+</span>regime_type3, <span class="at">data=</span>world_filter)</span>
<span id="cb26-2"><a href="#cb26-2" aria-hidden="true" tabindex="-1"></a>confidence_lm</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = confidence ~ unnetuse + effectiveness + regime_type3, 
    data = world_filter)

Coefficients:
                    (Intercept)                         unnetuse  
                        43.0725                          -0.5805  
                  effectiveness  regime_type3Parliamentary democ  
                         0.7574                         -15.4561  
 regime_type3Presidential democ  
                       -19.0101  </code></pre>
</div>
</div>
<p>And here is a visualization of the above values.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb28"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb28-1"><a href="#cb28-1" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(<span class="fu">fitted</span>(confidence_lm))</span>
<span id="cb28-2"><a href="#cb28-2" aria-hidden="true" tabindex="-1"></a><span class="fu">abline</span>(<span class="at">h=</span><span class="dv">50</span>, <span class="at">lty=</span><span class="dv">2</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="KPopiela_FinalP2_files/figure-html/unnamed-chunk-9-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb29"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb29-1"><a href="#cb29-1" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(confidence_lm)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = confidence ~ unnetuse + effectiveness + regime_type3, 
    data = world_filter)

Residuals:
    Min      1Q  Median      3Q     Max 
-49.097  -6.527   0.075   7.993  40.399 

Coefficients:
                                Estimate Std. Error t value Pr(&gt;|t|)    
(Intercept)                      43.0725     5.6175   7.668 4.82e-10 ***
unnetuse                         -0.5805     0.1561  -3.719 0.000498 ***
effectiveness                     0.7574     0.1700   4.455 4.61e-05 ***
regime_type3Parliamentary democ -15.4561     6.3577  -2.431 0.018608 *  
regime_type3Presidential democ  -19.0101     6.1730  -3.080 0.003336 ** 
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 15.37 on 51 degrees of freedom
  (111 observations deleted due to missingness)
Multiple R-squared:  0.3376,    Adjusted R-squared:  0.2856 
F-statistic: 6.497 on 4 and 51 DF,  p-value: 0.0002642</code></pre>
</div>
</div>
<p>I’m honestly not entirely sure what these values mean, but I input what I had into the function and I got results.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb31"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb31-1"><a href="#cb31-1" aria-hidden="true" tabindex="-1"></a><span class="fu">AIC</span>(confidence_lm)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 471.6936</code></pre>
</div>
<div class="sourceCode cell-code" id="cb33"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb33-1"><a href="#cb33-1" aria-hidden="true" tabindex="-1"></a><span class="fu">BIC</span>(confidence_lm)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 483.8457</code></pre>
</div>
</div>


</section>

</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const disableStylesheet = (stylesheets) => {
    for (let i=0; i < stylesheets.length; i++) {
      const stylesheet = stylesheets[i];
      stylesheet.rel = 'prefetch';
    }
  }
  const enableStylesheet = (stylesheets) => {
    for (let i=0; i < stylesheets.length; i++) {
      const stylesheet = stylesheets[i];
      stylesheet.rel = 'stylesheet';
    }
  }
  const manageTransitions = (selector, allowTransitions) => {
    const els = window.document.querySelectorAll(selector);
    for (let i=0; i < els.length; i++) {
      const el = els[i];
      if (allowTransitions) {
        el.classList.remove('notransition');
      } else {
        el.classList.add('notransition');
      }
    }
  }
  const toggleColorMode = (alternate) => {
    // Switch the stylesheets
    const alternateStylesheets = window.document.querySelectorAll('link.quarto-color-scheme.quarto-color-alternate');
    manageTransitions('#quarto-margin-sidebar .nav-link', false);
    if (alternate) {
      enableStylesheet(alternateStylesheets);
      for (const sheetNode of alternateStylesheets) {
        if (sheetNode.id === "quarto-bootstrap") {
          toggleBodyColorMode(sheetNode);
        }
      }
    } else {
      disableStylesheet(alternateStylesheets);
      toggleBodyColorPrimary();
    }
    manageTransitions('#quarto-margin-sidebar .nav-link', true);
    // Switch the toggles
    const toggles = window.document.querySelectorAll('.quarto-color-scheme-toggle');
    for (let i=0; i < toggles.length; i++) {
      const toggle = toggles[i];
      if (toggle) {
        if (alternate) {
          toggle.classList.add("alternate");     
        } else {
          toggle.classList.remove("alternate");
        }
      }
    }
    // Hack to workaround the fact that safari doesn't
    // properly recolor the scrollbar when toggling (#1455)
    if (navigator.userAgent.indexOf('Safari') > 0 && navigator.userAgent.indexOf('Chrome') == -1) {
      manageTransitions("body", false);
      window.scrollTo(0, 1);
      setTimeout(() => {
        window.scrollTo(0, 0);
        manageTransitions("body", true);
      }, 40);  
    }
  }
  const isFileUrl = () => { 
    return window.location.protocol === 'file:';
  }
  const hasAlternateSentinel = () => {  
    let styleSentinel = getColorSchemeSentinel();
    if (styleSentinel !== null) {
      return styleSentinel === "alternate";
    } else {
      return false;
    }
  }
  const setStyleSentinel = (alternate) => {
    const value = alternate ? "alternate" : "default";
    if (!isFileUrl()) {
      window.localStorage.setItem("quarto-color-scheme", value);
    } else {
      localAlternateSentinel = value;
    }
  }
  const getColorSchemeSentinel = () => {
    if (!isFileUrl()) {
      const storageValue = window.localStorage.getItem("quarto-color-scheme");
      return storageValue != null ? storageValue : localAlternateSentinel;
    } else {
      return localAlternateSentinel;
    }
  }
  let localAlternateSentinel = 'default';
  // Dark / light mode switch
  window.quartoToggleColorScheme = () => {
    // Read the current dark / light value 
    let toAlternate = !hasAlternateSentinel();
    toggleColorMode(toAlternate);
    setStyleSentinel(toAlternate);
  };
  // Ensure there is a toggle, if there isn't float one in the top right
  if (window.document.querySelector('.quarto-color-scheme-toggle') === null) {
    const a = window.document.createElement('a');
    a.classList.add('top-right');
    a.classList.add('quarto-color-scheme-toggle');
    a.href = "";
    a.onclick = function() { try { window.quartoToggleColorScheme(); } catch {} return false; };
    const i = window.document.createElement("i");
    i.classList.add('bi');
    a.appendChild(i);
    window.document.body.appendChild(a);
  }
  // Switch to dark mode if need be
  if (hasAlternateSentinel()) {
    toggleColorMode(true);
  } else {
    toggleColorMode(false);
  }
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const clipboard = new window.ClipboardJS('.code-copy-button', {
    target: function(trigger) {
      return trigger.previousElementSibling;
    }
  });
  clipboard.on('success', function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copied!");
    let tooltip;
    if (window.bootstrap) {
      button.setAttribute("data-bs-toggle", "tooltip");
      button.setAttribute("data-bs-placement", "left");
      button.setAttribute("data-bs-title", "Copied!");
      tooltip = new bootstrap.Tooltip(button, 
        { trigger: "manual", 
          customClass: "code-copy-button-tooltip",
          offset: [0, -8]});
      tooltip.show();    
    }
    setTimeout(function() {
      if (tooltip) {
        tooltip.hide();
        button.removeAttribute("data-bs-title");
        button.removeAttribute("data-bs-toggle");
        button.removeAttribute("data-bs-placement");
      }
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  });
  function tippyHover(el, contentFn) {
    const config = {
      allowHTML: true,
      content: contentFn,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start'
    };
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      return note.innerHTML;
    });
  }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
});
</script>
<script src="https://giscus.app/client.js" data-repo="DACSS/603_Fall_2022" data-repo-id="R_kgDOH568kA" data-category="Announcements" data-category-id="" data-mapping="title" data-reactions-enabled="1" data-emit-metadata="0" data-input-position="top" data-theme="light" data-lang="en" crossorigin="anonymous" async="">
</script>
</div> <!-- /content -->



</body></html>