<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.2.269">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">

<meta name="author" content="Steph Roberts">
<meta name="dcterms.date" content="2022-10-09">

<title>Final Project: Diabetes Prediction - Part 2</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1.6em;
  vertical-align: middle;
}
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
    color: #aaaaaa;
  }
pre.numberSource { margin-left: 3em; border-left: 1px solid #aaaaaa;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
code span.al { color: #ff0000; font-weight: bold; } /* Alert */
code span.an { color: #60a0b0; font-weight: bold; font-style: italic; } /* Annotation */
code span.at { color: #7d9029; } /* Attribute */
code span.bn { color: #40a070; } /* BaseN */
code span.bu { color: #008000; } /* BuiltIn */
code span.cf { color: #007020; font-weight: bold; } /* ControlFlow */
code span.ch { color: #4070a0; } /* Char */
code span.cn { color: #880000; } /* Constant */
code span.co { color: #60a0b0; font-style: italic; } /* Comment */
code span.cv { color: #60a0b0; font-weight: bold; font-style: italic; } /* CommentVar */
code span.do { color: #ba2121; font-style: italic; } /* Documentation */
code span.dt { color: #902000; } /* DataType */
code span.dv { color: #40a070; } /* DecVal */
code span.er { color: #ff0000; font-weight: bold; } /* Error */
code span.ex { } /* Extension */
code span.fl { color: #40a070; } /* Float */
code span.fu { color: #06287e; } /* Function */
code span.im { color: #008000; font-weight: bold; } /* Import */
code span.in { color: #60a0b0; font-weight: bold; font-style: italic; } /* Information */
code span.kw { color: #007020; font-weight: bold; } /* Keyword */
code span.op { color: #666666; } /* Operator */
code span.ot { color: #007020; } /* Other */
code span.pp { color: #bc7a00; } /* Preprocessor */
code span.sc { color: #4070a0; } /* SpecialChar */
code span.ss { color: #bb6688; } /* SpecialString */
code span.st { color: #4070a0; } /* String */
code span.va { color: #19177c; } /* Variable */
code span.vs { color: #4070a0; } /* VerbatimString */
code span.wa { color: #60a0b0; font-weight: bold; font-style: italic; } /* Warning */
</style>


<script src="../site_libs/quarto-nav/quarto-nav.js"></script>
<script src="../site_libs/quarto-nav/headroom.min.js"></script>
<script src="../site_libs/clipboard/clipboard.min.js"></script>
<script src="../site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="../site_libs/quarto-search/fuse.min.js"></script>
<script src="../site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="../">
<link href="../images/DACSS_Round_Network.png" rel="icon" type="image/png">
<script src="../site_libs/quarto-html/quarto.js"></script>
<script src="../site_libs/quarto-html/popper.min.js"></script>
<script src="../site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="../site_libs/quarto-html/anchor.min.js"></script>
<link href="../site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="../site_libs/quarto-html/quarto-syntax-highlighting.css" rel="stylesheet" class="quarto-color-scheme" id="quarto-text-highlighting-styles">
<link href="../site_libs/quarto-html/quarto-syntax-highlighting-dark.css" rel="prefetch" class="quarto-color-scheme quarto-color-alternate" id="quarto-text-highlighting-styles">
<script src="../site_libs/bootstrap/bootstrap.min.js"></script>
<link href="../site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="../site_libs/bootstrap/bootstrap.min.css" rel="stylesheet" class="quarto-color-scheme" id="quarto-bootstrap" data-mode="light">
<link href="../site_libs/bootstrap/bootstrap-dark.min.css" rel="prefetch" class="quarto-color-scheme quarto-color-alternate" id="quarto-bootstrap" data-mode="dark">
<script id="quarto-search-options" type="application/json">{
  "location": "navbar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "end",
  "type": "overlay",
  "limit": 20,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit"
  }
}</script>


<meta name="twitter:title" content="Final Project: Diabetes Prediction - Part 2">
<meta name="twitter:description" content="According to the World Health Organization (WHO), an estimated 537 million people worldwide are living with diabetes. It is a leading cause of health complications and even death.">
<meta name="twitter:creator" content="@UMassDACSS">
<meta name="twitter:site" content="@UMassDACSS">
<meta name="twitter:card" content="summary">
</head>

<body class="nav-fixed">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
    <nav class="navbar navbar-expand-lg navbar-dark ">
      <div class="navbar-container container-fluid">
      <div class="navbar-brand-container">
    <a href="../index.html" class="navbar-brand navbar-brand-logo">
    <img src="../images/UMass White Wordmark Horiz.png" alt="" class="navbar-logo">
    </a>
  </div>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse" aria-controls="navbarCollapse" aria-expanded="false" aria-label="Toggle navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
  <span class="navbar-toggler-icon"></span>
</button>
          <div class="collapse navbar-collapse" id="navbarCollapse">
            <ul class="navbar-nav navbar-nav-scroll ms-auto">
  <li class="nav-item">
    <a class="nav-link" href="https://dacss.github.io/603_Fall_2022/">
 <span class="menu-text">Fall 2022 Posts</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="../about.html">
 <span class="menu-text">Contributors</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="https://umass.edu/sbs/dacss">
 <span class="menu-text">DACSS</span></a>
  </li>  
  <li class="nav-item compact">
    <a class="nav-link" href="https://github.com/DACSS/603_Fall_2022"><i class="bi bi-github" role="img" aria-label="GitHub">
</i> 
 <span class="menu-text"></span></a>
  </li>  
</ul>
              <div class="quarto-toggle-container">
                  <a href="" class="quarto-color-scheme-toggle nav-link" onclick="window.quartoToggleColorScheme(); return false;" title="Toggle dark mode"><i class="bi"></i></a>
              </div>
              <div id="quarto-search" class="" title="Search"></div>
          </div> <!-- /navcollapse -->
      </div> <!-- /container-fluid -->
    </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article page-navbar">
<!-- sidebar -->
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">On this page</h2>
   
  <ul>
  <li><a href="#diabetes-risk-factors" id="toc-diabetes-risk-factors" class="nav-link active" data-scroll-target="#diabetes-risk-factors">Diabetes risk factors</a></li>
  <li><a href="#research-question" id="toc-research-question" class="nav-link" data-scroll-target="#research-question">Research Question</a></li>
  <li><a href="#hypothesis" id="toc-hypothesis" class="nav-link" data-scroll-target="#hypothesis">Hypothesis</a></li>
  <li><a href="#descriptive-statistics" id="toc-descriptive-statistics" class="nav-link" data-scroll-target="#descriptive-statistics">Descriptive Statistics</a></li>
  <li><a href="#hypothesis-testing" id="toc-hypothesis-testing" class="nav-link" data-scroll-target="#hypothesis-testing">Hypothesis Testing</a></li>
  <li><a href="#model-comparisons" id="toc-model-comparisons" class="nav-link" data-scroll-target="#model-comparisons">Model Comparisons</a>
  <ul class="collapse">
  <li><a href="#model-1" id="toc-model-1" class="nav-link" data-scroll-target="#model-1">Model 1</a></li>
  <li><a href="#model-2" id="toc-model-2" class="nav-link" data-scroll-target="#model-2">Model 2</a></li>
  <li><a href="#model-3" id="toc-model-3" class="nav-link" data-scroll-target="#model-3">Model 3</a></li>
  <li><a href="#model-4" id="toc-model-4" class="nav-link" data-scroll-target="#model-4">Model 4</a></li>
  <li><a href="#model-5" id="toc-model-5" class="nav-link" data-scroll-target="#model-5">Model 5</a></li>
  </ul></li>
  <li><a href="#diagnostics" id="toc-diagnostics" class="nav-link" data-scroll-target="#diagnostics">Diagnostics</a></li>
  </ul>
</nav>
    </div>
<!-- main -->
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<div class="quarto-title-block"><div><h1 class="title">Final Project: Diabetes Prediction - Part 2</h1><button type="button" class="btn code-tools-button dropdown-toggle" id="quarto-code-tools-menu" data-bs-toggle="dropdown" aria-expanded="false"><i class="bi"></i> Code</button><ul class="dropdown-menu dropdown-menu-end" aria-labelelledby="quarto-code-tools-menu"><li><a id="quarto-show-all-code" class="dropdown-item" href="javascript:void(0)" role="button">Show All Code</a></li><li><a id="quarto-hide-all-code" class="dropdown-item" href="javascript:void(0)" role="button">Hide All Code</a></li><li><hr class="dropdown-divider"></li><li><a id="quarto-view-source" class="dropdown-item" href="javascript:void(0)" role="button">View Source</a></li></ul></div></div>
  <div class="quarto-categories">
    <div class="quarto-category">finalproject</div>
    <div class="quarto-category">Steph Roberts</div>
    <div class="quarto-category">dataset</div>
    <div class="quarto-category">ggplot2</div>
  </div>
  </div>



<div class="quarto-title-meta">

    <div>
    <div class="quarto-title-meta-heading">Author</div>
    <div class="quarto-title-meta-contents">
             <p>Steph Roberts </p>
          </div>
  </div>
    
    <div>
    <div class="quarto-title-meta-heading">Published</div>
    <div class="quarto-title-meta-contents">
      <p class="date">October 9, 2022</p>
    </div>
  </div>
  
    
  </div>
  

</header>

<div class="cell">
<details>
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb1"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(tidyverse)</span>
<span id="cb1-2"><a href="#cb1-2" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(ggplot2)</span>
<span id="cb1-3"><a href="#cb1-3" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(dplyr)</span>
<span id="cb1-4"><a href="#cb1-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-5"><a href="#cb1-5" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(magrittr)</span>
<span id="cb1-6"><a href="#cb1-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-7"><a href="#cb1-7" aria-hidden="true" tabindex="-1"></a>knitr<span class="sc">::</span>opts_chunk<span class="sc">$</span><span class="fu">set</span>(<span class="at">echo =</span> <span class="cn">TRUE</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
</div>
<section id="diabetes-risk-factors" class="level3">
<h3 class="anchored" data-anchor-id="diabetes-risk-factors">Diabetes risk factors</h3>
<p>According to the World Health Organization (WHO), an estimated 537 million people worldwide are living with diabetes. It is a leading cause of health complications and even death. The WHO states close to 1.5 million people died due to diabetes and its complication in 2019 alone. It is a growing problem that requires dedicated research to aim at the slowdown and prevention of future cases.</p>
</section>
<section id="research-question" class="level2">
<h2 class="anchored" data-anchor-id="research-question">Research Question</h2>
<ol type="1">
<li>What risk factors are most predictive of diabetes?</li>
</ol>
<p>Research on Diabetes is ongoing and in-depth within the medical field. The prevalence and incidence of diabetes mellitus type 2 (DQ2) have increased consistently for decades, giving way to an increase in mortality related to diabetes. Commonly in the medical field, many risk factors are used to measure a patient’s risk of developing DM2, such as obesity, family history, hypertension and changes in fasting blood sugar levels. Moreno et al.&nbsp;(2018) studied risk parameters for diabetes and concluded “risk of being diabetic rises in patients whose father has suffered an acute myocardial infarction, in those whose mother or father is diabetic and in patients with a high waist perimeter.” Their focus on family history leaves room for studies more focused on individual medical factors, such as blood pressure, BMI, number of pregnancies, etc. That is the aim of this project.</p>
<p>M. L. M. V. J. A. (2018, June 11). Predictive risk model for the diagnosis of diabetes mellitus type 2 in a follow-up study 15 Years on: Prodi2 study. European journal of public health. Retrieved October 9, 2022, from https://pubmed.ncbi.nlm.nih.gov/29897477/</p>
<ol start="2" type="1">
<li>Can the use of regression analysis help predict risk of diabetes based on several medical variables?</li>
</ol>
<p>Other research, such as a Edlitz &amp; Segal (2022) study titled Prediction of type 2 diabetes mellitus onset using logistic regression-based scorecards, does focus on using individual medical factors to predict risk of diabetes through regression. This project aims to conduct similar analysis on different data.</p>
<p>E. Y. S. E. (2022, June 22). Prediction of type 2 diabetes mellitus onset using logistic regression-based scorecards. eLife. Retrieved October 9, 2022, from https://pubmed.ncbi.nlm.nih.gov/35731045/</p>
</section>
<section id="hypothesis" class="level2">
<h2 class="anchored" data-anchor-id="hypothesis">Hypothesis</h2>
<p>Body mass index (BMI), glucose, and age are positive predictors of diabetes mellitus type 2.</p>
<p>This hypothesis has been tested in the above mentioned studies. The contribution from this project will be the additional support for or against the hypotheses from the analysis of different data.</p>
</section>
<section id="descriptive-statistics" class="level2">
<h2 class="anchored" data-anchor-id="descriptive-statistics">Descriptive Statistics</h2>
<p>The data was collected by the “National Institute of Diabetes and Digestive and Kidney Diseases” as part of the Pima Indians Diabetes Database (PIDD). A total of 768 cases are available in PIDD. However, 5 patients had a glucose of 0 and 11 patients had a body mass index of 0. After cleaning the data by removing the cases with numbers that are incompatible with life in categories important to the current research, 752 cases remained. All patients belong to the Pima Indian heritage (subgroup of Native Americans), and are females aged 21 years and above.</p>
<p>The datasets consists of 9 medical predictor (independent) variables and one target (dependent) variable, outcome.</p>
<p><strong>Pregnancies:</strong> Number of times a woman has been pregnant<br>
<strong>Glucose:</strong> Plasma Glucose concentration of 2 hours in an oral glucose tolerance test<br>
<strong>BloodPressure:</strong> Diastolic Blood Pressure (mm hg)<br>
<strong>SkinThickness:</strong> Triceps skin fold thickness(mm)<br>
<strong>Insulin:</strong> 2 hour serum insulin(mu U/ml)<br>
<strong>BMI:</strong> Body Mass Index ((weight in kg/height in m)^2)<br>
<strong>Age:</strong> Age(years)<br>
<strong>DiabetesPedigreeFunction:</strong> scores likelihood of diabetes based on family history<br>
<strong>Outcome:</strong> 0 (doesn’t have diabetes) or 1 (has diabetes)</p>
<div class="cell">
<details>
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb2"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb2-1"><a href="#cb2-1" aria-hidden="true" tabindex="-1"></a>df<span class="ot">&lt;-</span> <span class="fu">read_csv</span>(<span class="st">"_data/diabetes2.csv"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stderr">
<pre><code>Rows: 768 Columns: 9
── Column specification ────────────────────────────────────────────────────────
Delimiter: ","
dbl (9): Pregnancies, Glucose, BloodPressure, SkinThickness, Insulin, BMI, D...

ℹ Use `spec()` to retrieve the full column specification for this data.
ℹ Specify the column types or set `show_col_types = FALSE` to quiet this message.</code></pre>
</div>
<details>
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb4"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb4-1"><a href="#cb4-1" aria-hidden="true" tabindex="-1"></a><span class="fu">dim</span>(df)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 768   9</code></pre>
</div>
<details>
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb6"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb6-1"><a href="#cb6-1" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(df)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>  Pregnancies        Glucose      BloodPressure    SkinThickness  
 Min.   : 0.000   Min.   :  0.0   Min.   :  0.00   Min.   : 0.00  
 1st Qu.: 1.000   1st Qu.: 99.0   1st Qu.: 62.00   1st Qu.: 0.00  
 Median : 3.000   Median :117.0   Median : 72.00   Median :23.00  
 Mean   : 3.845   Mean   :120.9   Mean   : 69.11   Mean   :20.54  
 3rd Qu.: 6.000   3rd Qu.:140.2   3rd Qu.: 80.00   3rd Qu.:32.00  
 Max.   :17.000   Max.   :199.0   Max.   :122.00   Max.   :99.00  
    Insulin           BMI        DiabetesPedigreeFunction      Age       
 Min.   :  0.0   Min.   : 0.00   Min.   :0.0780           Min.   :21.00  
 1st Qu.:  0.0   1st Qu.:27.30   1st Qu.:0.2437           1st Qu.:24.00  
 Median : 30.5   Median :32.00   Median :0.3725           Median :29.00  
 Mean   : 79.8   Mean   :31.99   Mean   :0.4719           Mean   :33.24  
 3rd Qu.:127.2   3rd Qu.:36.60   3rd Qu.:0.6262           3rd Qu.:41.00  
 Max.   :846.0   Max.   :67.10   Max.   :2.4200           Max.   :81.00  
    Outcome     
 Min.   :0.000  
 1st Qu.:0.000  
 Median :0.000  
 Mean   :0.349  
 3rd Qu.:1.000  
 Max.   :1.000  </code></pre>
</div>
<details>
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb8"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb8-1"><a href="#cb8-1" aria-hidden="true" tabindex="-1"></a><span class="fu">head</span>(df)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 6 × 9
  Pregnancies Glucose BloodPressure SkinTh…¹ Insulin   BMI Diabe…²   Age Outcome
        &lt;dbl&gt;   &lt;dbl&gt;         &lt;dbl&gt;    &lt;dbl&gt;   &lt;dbl&gt; &lt;dbl&gt;   &lt;dbl&gt; &lt;dbl&gt;   &lt;dbl&gt;
1           6     148            72       35       0  33.6   0.627    50       1
2           1      85            66       29       0  26.6   0.351    31       0
3           8     183            64        0       0  23.3   0.672    32       1
4           1      89            66       23      94  28.1   0.167    21       0
5           0     137            40       35     168  43.1   2.29     33       1
6           5     116            74        0       0  25.6   0.201    30       0
# … with abbreviated variable names ¹​SkinThickness, ²​DiabetesPedigreeFunction</code></pre>
</div>
</div>
<div class="cell">
<details>
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb10"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb10-1"><a href="#cb10-1" aria-hidden="true" tabindex="-1"></a><span class="co">#check for null entries</span></span>
<span id="cb10-2"><a href="#cb10-2" aria-hidden="true" tabindex="-1"></a><span class="fu">is.null</span>(df)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>[1] FALSE</code></pre>
</div>
</div>
<div class="cell">
<details>
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb12"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb12-1"><a href="#cb12-1" aria-hidden="true" tabindex="-1"></a><span class="co">#Check number of 0s in each column</span></span>
<span id="cb12-2"><a href="#cb12-2" aria-hidden="true" tabindex="-1"></a><span class="fu">colSums</span>(df<span class="sc">==</span><span class="dv">0</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>             Pregnancies                  Glucose            BloodPressure 
                     111                        5                       35 
           SkinThickness                  Insulin                      BMI 
                     227                      374                       11 
DiabetesPedigreeFunction                      Age                  Outcome 
                       0                        0                      500 </code></pre>
</div>
</div>
<p>Glucose, blood pressure, skin thickness, insulin, BMI and Age are not variables that should logically have 0s. Those values, if true, are likely incompatible with life. To reduce the amount of data we exclude, we will only remove observations that have 0s for our explanatory variables. We will remove those cases from analysis.</p>
<div class="cell">
<details>
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb14"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb14-1"><a href="#cb14-1" aria-hidden="true" tabindex="-1"></a><span class="co">#Remove rows with 0 in respective columns</span></span>
<span id="cb14-2"><a href="#cb14-2" aria-hidden="true" tabindex="-1"></a>df <span class="ot">&lt;-</span> df[<span class="fu">apply</span>(df[<span class="fu">c</span>(<span class="dv">2</span>,<span class="dv">6</span>)],<span class="dv">1</span>,<span class="cf">function</span>(z) <span class="sc">!</span><span class="fu">any</span>(z<span class="sc">==</span><span class="dv">0</span>)),] </span>
<span id="cb14-3"><a href="#cb14-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb14-4"><a href="#cb14-4" aria-hidden="true" tabindex="-1"></a><span class="co">#Verify 0s are gone in selected rows</span></span>
<span id="cb14-5"><a href="#cb14-5" aria-hidden="true" tabindex="-1"></a><span class="fu">colSums</span>(df<span class="sc">==</span><span class="dv">0</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>             Pregnancies                  Glucose            BloodPressure 
                     108                        0                       28 
           SkinThickness                  Insulin                      BMI 
                     218                      360                        0 
DiabetesPedigreeFunction                      Age                  Outcome 
                       0                        0                      488 </code></pre>
</div>
</div>
<div class="cell">
<details>
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb16"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb16-1"><a href="#cb16-1" aria-hidden="true" tabindex="-1"></a><span class="co">#Check cleaned data frame</span></span>
<span id="cb16-2"><a href="#cb16-2" aria-hidden="true" tabindex="-1"></a><span class="fu">glimpse</span>(df)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>Rows: 752
Columns: 9
$ Pregnancies              &lt;dbl&gt; 6, 1, 8, 1, 0, 5, 3, 10, 2, 4, 10, 10, 1, 5, …
$ Glucose                  &lt;dbl&gt; 148, 85, 183, 89, 137, 116, 78, 115, 197, 110…
$ BloodPressure            &lt;dbl&gt; 72, 66, 64, 66, 40, 74, 50, 0, 70, 92, 74, 80…
$ SkinThickness            &lt;dbl&gt; 35, 29, 0, 23, 35, 0, 32, 0, 45, 0, 0, 0, 23,…
$ Insulin                  &lt;dbl&gt; 0, 0, 0, 94, 168, 0, 88, 0, 543, 0, 0, 0, 846…
$ BMI                      &lt;dbl&gt; 33.6, 26.6, 23.3, 28.1, 43.1, 25.6, 31.0, 35.…
$ DiabetesPedigreeFunction &lt;dbl&gt; 0.627, 0.351, 0.672, 0.167, 2.288, 0.201, 0.2…
$ Age                      &lt;dbl&gt; 50, 31, 32, 21, 33, 30, 26, 29, 53, 30, 34, 5…
$ Outcome                  &lt;dbl&gt; 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 1, 1, …</code></pre>
</div>
</div>
<div class="cell">
<details>
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb18"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb18-1"><a href="#cb18-1" aria-hidden="true" tabindex="-1"></a><span class="co">#Summarize df</span></span>
<span id="cb18-2"><a href="#cb18-2" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(df)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>  Pregnancies        Glucose       BloodPressure   SkinThickness  
 Min.   : 0.000   Min.   : 44.00   Min.   :  0.0   Min.   : 0.00  
 1st Qu.: 1.000   1st Qu.: 99.75   1st Qu.: 64.0   1st Qu.: 0.00  
 Median : 3.000   Median :117.00   Median : 72.0   Median :23.00  
 Mean   : 3.851   Mean   :121.94   Mean   : 69.7   Mean   :20.72  
 3rd Qu.: 6.000   3rd Qu.:141.00   3rd Qu.: 80.0   3rd Qu.:32.00  
 Max.   :17.000   Max.   :199.00   Max.   :122.0   Max.   :99.00  
    Insulin            BMI        DiabetesPedigreeFunction      Age       
 Min.   :  0.00   Min.   :18.20   Min.   :0.0780           Min.   :21.00  
 1st Qu.:  0.00   1st Qu.:27.50   1st Qu.:0.2440           1st Qu.:24.00  
 Median : 39.00   Median :32.30   Median :0.3770           Median :29.00  
 Mean   : 81.35   Mean   :32.45   Mean   :0.4731           Mean   :33.31  
 3rd Qu.:130.00   3rd Qu.:36.60   3rd Qu.:0.6275           3rd Qu.:41.00  
 Max.   :846.00   Max.   :67.10   Max.   :2.4200           Max.   :81.00  
    Outcome      
 Min.   :0.0000  
 1st Qu.:0.0000  
 Median :0.0000  
 Mean   :0.3511  
 3rd Qu.:1.0000  
 Max.   :1.0000  </code></pre>
</div>
</div>
<p>At a glance, this summary is more fitting after having cleaned our data. An average of 3 pregnancies, considering our 21+ female population, makes sense. A mean glucose of 122, blood pressure of 70, a BMI of 33, and age of 33 are reasonably accurate for our population.</p>
<div class="cell">
<details>
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb20"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb20-1"><a href="#cb20-1" aria-hidden="true" tabindex="-1"></a><span class="co">#Rename columns</span></span>
<span id="cb20-2"><a href="#cb20-2" aria-hidden="true" tabindex="-1"></a><span class="fu">colnames</span>(df) <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="st">"pregnancies"</span>, <span class="st">"glucose"</span>, <span class="st">"bp"</span>, <span class="st">"skin_thickness"</span>, <span class="st">"insulin"</span>, <span class="st">"bmi"</span>, <span class="st">"dpf"</span>, <span class="st">"age"</span>, <span class="st">"diabetes"</span>)</span>
<span id="cb20-3"><a href="#cb20-3" aria-hidden="true" tabindex="-1"></a><span class="fu">dim</span>(df)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 752   9</code></pre>
</div>
</div>
<p>We have 752 observations and 9 variables with which to work. The data is clean and ready for analysis.</p>
<p>Let’s get familiar with the data set by observing the scatterplot matrix and histograms for each variable.</p>
<div class="cell">
<details>
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb22"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb22-1"><a href="#cb22-1" aria-hidden="true" tabindex="-1"></a><span class="co">#Scatterplot matrix</span></span>
<span id="cb22-2"><a href="#cb22-2" aria-hidden="true" tabindex="-1"></a><span class="fu">pairs</span>(df)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output-display">
<p><img src="StephRoberts_finalpart2_files/figure-html/unnamed-chunk-9-1.png" class="img-fluid" width="672"></p>
</div>
<details>
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb23"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb23-1"><a href="#cb23-1" aria-hidden="true" tabindex="-1"></a><span class="co">#Histograms of each variable</span></span>
<span id="cb23-2"><a href="#cb23-2" aria-hidden="true" tabindex="-1"></a><span class="fu">hist.data.frame</span>(df)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-error">
<pre><code>Error in hist.data.frame(df): could not find function "hist.data.frame"</code></pre>
</div>
</div>
<p>The scatterplot matix shows that our variables generally lack linear relationships. Logistics regression may be best for analyzing this type of data.</p>
<p>The histograms show us the distribution of all our variables. Pregnancies is right skewed with more women having a smaller number of pregnancies and a small number having over 10. Glucose appears to follow a close-to-normal distribution with the mean just over 100. BMI follows a similar pattern with a central value of just over 30. Age is right skewed with the majority of the sample appearing to be in their 20s and slower tapering off to ages in their 50s. This is a good place to start. The only variable we cannot view in a histogram is the outcome variable due to its binary nature as a dummy variable.</p>
<div class="cell">
<details>
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb25"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb25-1"><a href="#cb25-1" aria-hidden="true" tabindex="-1"></a>bgap <span class="ot">&lt;-</span> <span class="fu">as.data.frame</span>(df[, <span class="fu">c</span>(<span class="dv">1</span>,<span class="dv">2</span>,<span class="dv">6</span>,<span class="dv">8</span>,<span class="dv">9</span>)])</span>
<span id="cb25-2"><a href="#cb25-2" aria-hidden="true" tabindex="-1"></a><span class="fu">pairs</span>(bgap)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output-display">
<p><img src="StephRoberts_finalpart2_files/figure-html/unnamed-chunk-10-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<div class="cell">
<details>
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb26"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb26-1"><a href="#cb26-1" aria-hidden="true" tabindex="-1"></a><span class="co">#Plot outcome variable</span></span>
<span id="cb26-2"><a href="#cb26-2" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(df, <span class="fu">aes</span>(<span class="at">x=</span><span class="fu">factor</span>(diabetes))) <span class="sc">+</span></span>
<span id="cb26-3"><a href="#cb26-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_bar</span>(<span class="at">fill =</span> <span class="st">"#0073C2FF"</span>)<span class="sc">+</span></span>
<span id="cb26-4"><a href="#cb26-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">scale_x_discrete</span>(<span class="at">labels=</span><span class="fu">c</span>(<span class="st">'No Diabetes'</span>,<span class="st">'Diabetes'</span>))<span class="sc">+</span></span>
<span id="cb26-5"><a href="#cb26-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">xlab</span>(<span class="st">"Outcome"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output-display">
<p><img src="StephRoberts_finalpart2_files/figure-html/unnamed-chunk-11-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<p>About a third of our sample have diabetes.</p>
</section>
<section id="hypothesis-testing" class="level2">
<h2 class="anchored" data-anchor-id="hypothesis-testing">Hypothesis Testing</h2>
<div class="cell">
<details>
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb27"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb27-1"><a href="#cb27-1" aria-hidden="true" tabindex="-1"></a><span class="co">#Create training and test data</span></span>
<span id="cb27-2"><a href="#cb27-2" aria-hidden="true" tabindex="-1"></a><span class="fu">set.seed</span>(<span class="dv">1</span>)</span>
<span id="cb27-3"><a href="#cb27-3" aria-hidden="true" tabindex="-1"></a>bgap <span class="sc">%&gt;%</span> </span>
<span id="cb27-4"><a href="#cb27-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">nrow</span>() <span class="sc">%&gt;%</span> </span>
<span id="cb27-5"><a href="#cb27-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">multiply_by</span>(<span class="fl">0.7</span>) <span class="sc">%&gt;%</span> </span>
<span id="cb27-6"><a href="#cb27-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">round</span>() <span class="ot">-&gt;</span> training_set_size</span>
<span id="cb27-7"><a href="#cb27-7" aria-hidden="true" tabindex="-1"></a>train_indices <span class="ot">&lt;-</span> <span class="fu">sample</span>(<span class="dv">1</span><span class="sc">:</span><span class="fu">nrow</span>(df), training_set_size)</span>
<span id="cb27-8"><a href="#cb27-8" aria-hidden="true" tabindex="-1"></a>train <span class="ot">&lt;-</span> bgap[train_indices,]</span>
<span id="cb27-9"><a href="#cb27-9" aria-hidden="true" tabindex="-1"></a>test <span class="ot">&lt;-</span> bgap[<span class="sc">-</span>train_indices,]</span>
<span id="cb27-10"><a href="#cb27-10" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb27-11"><a href="#cb27-11" aria-hidden="true" tabindex="-1"></a><span class="fu">nrow</span>(train)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 526</code></pre>
</div>
<details>
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb29"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb29-1"><a href="#cb29-1" aria-hidden="true" tabindex="-1"></a><span class="fu">nrow</span>(test)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 226</code></pre>
</div>
<details>
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb31"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb31-1"><a href="#cb31-1" aria-hidden="true" tabindex="-1"></a><span class="fu">head</span>(train)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>    pregnancies glucose  bmi age diabetes
679           7     129 38.5  43        1
129           8      84 38.3  39        0
509           3     124 33.2  26        0
471           0     123 35.2  29        0
299           2     120 39.7  29        0
270           7     106 26.5  29        1</code></pre>
</div>
</div>
<p>As a reminder, pregnancies, age, and BMI are all right skewed. So, we will use the logarithm of those variables in our regressions.</p>
<div class="cell">
<details>
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb33"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb33-1"><a href="#cb33-1" aria-hidden="true" tabindex="-1"></a><span class="co">#Model 1 using all independent variables</span></span>
<span id="cb33-2"><a href="#cb33-2" aria-hidden="true" tabindex="-1"></a>all_var <span class="ot">&lt;-</span> <span class="fu">glm</span>(diabetes <span class="sc">~</span> ., <span class="at">data =</span> train, <span class="at">family =</span> binomial)</span>
<span id="cb33-3"><a href="#cb33-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb33-4"><a href="#cb33-4" aria-hidden="true" tabindex="-1"></a><span class="co">#Model 2 using BMI, glucose, and age</span></span>
<span id="cb33-5"><a href="#cb33-5" aria-hidden="true" tabindex="-1"></a>bga <span class="ot">&lt;-</span> <span class="fu">glm</span>(diabetes <span class="sc">~</span> . <span class="sc">-</span>pregnancies, <span class="at">data =</span> train, <span class="at">family =</span> binomial)</span>
<span id="cb33-6"><a href="#cb33-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb33-7"><a href="#cb33-7" aria-hidden="true" tabindex="-1"></a><span class="co">#Model 3 using BMI and glucose</span></span>
<span id="cb33-8"><a href="#cb33-8" aria-hidden="true" tabindex="-1"></a>bg <span class="ot">&lt;-</span> <span class="fu">glm</span>(diabetes <span class="sc">~</span> .<span class="sc">-</span>age <span class="sc">-</span>pregnancies, <span class="at">data =</span> train, <span class="at">family =</span> binomial)</span>
<span id="cb33-9"><a href="#cb33-9" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb33-10"><a href="#cb33-10" aria-hidden="true" tabindex="-1"></a><span class="co">#Model 4 using BMI, glucose, age, and an interaction between pregnancies and age.</span></span>
<span id="cb33-11"><a href="#cb33-11" aria-hidden="true" tabindex="-1"></a>ia <span class="ot">&lt;-</span> <span class="fu">glm</span>(diabetes <span class="sc">~</span> glucose <span class="sc">+</span> bmi <span class="sc">+</span> age<span class="sc">*</span>pregnancies, <span class="at">data =</span> train, <span class="at">family =</span> binomial)</span>
<span id="cb33-12"><a href="#cb33-12" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb33-13"><a href="#cb33-13" aria-hidden="true" tabindex="-1"></a><span class="co">#Model 5 with BMI, glucose, and pregnancies (without age)</span></span>
<span id="cb33-14"><a href="#cb33-14" aria-hidden="true" tabindex="-1"></a>bgp <span class="ot">&lt;-</span> <span class="fu">glm</span>(diabetes <span class="sc">~</span> . <span class="sc">-</span>age, <span class="at">data =</span> train, <span class="at">family =</span> binomial)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
</div>
<p>Our hypothesis involves the BMI, glucose, and age variables. First we can take a look at them individually.</p>
<div class="cell">
<details>
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb34"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb34-1"><a href="#cb34-1" aria-hidden="true" tabindex="-1"></a><span class="co">#Generalized linear model can be best for predicting categorical outcome</span></span>
<span id="cb34-2"><a href="#cb34-2" aria-hidden="true" tabindex="-1"></a><span class="co">#Regression model on BMI</span></span>
<span id="cb34-3"><a href="#cb34-3" aria-hidden="true" tabindex="-1"></a>mbmi <span class="ot">&lt;-</span> <span class="fu">glm</span>(diabetes <span class="sc">~</span> bmi, <span class="at">data =</span> train)</span>
<span id="cb34-4"><a href="#cb34-4" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(mbmi)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
glm(formula = diabetes ~ bmi, data = train)

Deviance Residuals: 
    Min       1Q   Median       3Q      Max  
-0.8360  -0.3589  -0.2084   0.5492   0.8329  

Coefficients:
             Estimate Std. Error t value Pr(&gt;|t|)    
(Intercept) -0.291366   0.097381  -2.992   0.0029 ** 
bmi          0.019674   0.002933   6.707 5.15e-11 ***
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

(Dispersion parameter for gaussian family taken to be 0.2097284)

    Null deviance: 119.33  on 525  degrees of freedom
Residual deviance: 109.90  on 524  degrees of freedom
AIC: 675.14

Number of Fisher Scoring iterations: 2</code></pre>
</div>
<details>
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb36"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb36-1"><a href="#cb36-1" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(<span class="at">data =</span> train, <span class="fu">aes</span>(<span class="at">x =</span>bmi, <span class="at">y =</span> diabetes)) <span class="sc">+</span></span>
<span id="cb36-2"><a href="#cb36-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_point</span>() <span class="sc">+</span></span>
<span id="cb36-3"><a href="#cb36-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_smooth</span>(<span class="at">method =</span> <span class="st">'lm'</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stderr">
<pre><code>`geom_smooth()` using formula = 'y ~ x'</code></pre>
</div>
<div class="cell-output-display">
<p><img src="StephRoberts_finalpart2_files/figure-html/unnamed-chunk-14-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<p>Interpretation: The residuals are relatively small. The coefficient estimate suggests that for every 1 unit increase of BMI, the chance of diabetes increases 0.019. The standard errors are small. Our t-values are large compared to our standard error and relatively far from 0. All that, combined with a very small p-value of &lt; 5.15e-11, indicate we can reject the null hypothesis and conclude a relationship between BMI and diabetes.</p>
<div class="cell">
<details>
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb38"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb38-1"><a href="#cb38-1" aria-hidden="true" tabindex="-1"></a><span class="co">#Regression model on glucose </span></span>
<span id="cb38-2"><a href="#cb38-2" aria-hidden="true" tabindex="-1"></a>mgluc <span class="ot">&lt;-</span> <span class="fu">glm</span>(diabetes <span class="sc">~</span> glucose, <span class="at">data =</span> train)</span>
<span id="cb38-3"><a href="#cb38-3" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(mgluc)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
glm(formula = diabetes ~ glucose, data = train)

Deviance Residuals: 
    Min       1Q   Median       3Q      Max  
-0.9139  -0.3098  -0.1210   0.3561   0.9847  

Coefficients:
              Estimate Std. Error t value Pr(&gt;|t|)    
(Intercept) -0.5736945  0.0759383  -7.555 1.88e-13 ***
glucose      0.0075512  0.0006039  12.503  &lt; 2e-16 ***
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

(Dispersion parameter for gaussian family taken to be 0.1754047)

    Null deviance: 119.333  on 525  degrees of freedom
Residual deviance:  91.912  on 524  degrees of freedom
AIC: 581.13

Number of Fisher Scoring iterations: 2</code></pre>
</div>
<details>
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb40"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb40-1"><a href="#cb40-1" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(<span class="at">data =</span> train, <span class="fu">aes</span>(<span class="at">x =</span> glucose, <span class="at">y =</span> diabetes)) <span class="sc">+</span></span>
<span id="cb40-2"><a href="#cb40-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_point</span>() <span class="sc">+</span></span>
<span id="cb40-3"><a href="#cb40-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_smooth</span>(<span class="at">method =</span> <span class="st">'lm'</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stderr">
<pre><code>`geom_smooth()` using formula = 'y ~ x'</code></pre>
</div>
<div class="cell-output-display">
<p><img src="StephRoberts_finalpart2_files/figure-html/unnamed-chunk-15-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<p>Interpretation: Interestingly, the values of this regression mirror that of the BMI regression. With a very small p-value, &lt; 2e-16, we can see that the plasma glucose concentrations of the 2 hour oral glucose tolerance test (GGT) are related to our outcome variable, diabetes. This makes sense as GGT is sometimes used as a diagnostic tool for diabetes.</p>
<p>The similarities is regression model values between BMI and glucose sparked a curiosity. Let’s see if BMI and glucose are specifically correlated to one another.</p>
<div class="cell">
<details>
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb42"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb42-1"><a href="#cb42-1" aria-hidden="true" tabindex="-1"></a><span class="fu">cor.test</span>(train<span class="sc">$</span>bmi, train<span class="sc">$</span>glucose, <span class="at">method =</span> <span class="st">"pearson"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>
    Pearson's product-moment correlation

data:  train$bmi and train$glucose
t = 5.8539, df = 524, p-value = 8.477e-09
alternative hypothesis: true correlation is not equal to 0
95 percent confidence interval:
 0.1657727 0.3263371
sample estimates:
      cor 
0.2477554 </code></pre>
</div>
</div>
<p>This shows a very small p-value of 8.477e-09, which is well under the significance level alpha = 0.5. However, the correlation coefficient suggests a weak positive correlation. This suggests the variables are only weakly related.</p>
<p>Let’s continue with our regression model hypothesis testing of individual variables.</p>
<div class="cell">
<details>
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb44"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb44-1"><a href="#cb44-1" aria-hidden="true" tabindex="-1"></a><span class="co">#Regression model on age</span></span>
<span id="cb44-2"><a href="#cb44-2" aria-hidden="true" tabindex="-1"></a>mage <span class="ot">&lt;-</span> <span class="fu">glm</span>(diabetes <span class="sc">~</span> age, <span class="at">data =</span> train)</span>
<span id="cb44-3"><a href="#cb44-3" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(mage)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
glm(formula = diabetes ~ age, data = train)

Deviance Residuals: 
    Min       1Q   Median       3Q      Max  
-0.7495  -0.3120  -0.2531   0.5786   0.7553  

Coefficients:
            Estimate Std. Error t value Pr(&gt;|t|)    
(Intercept) 0.068046   0.060323   1.128     0.26    
age         0.008413   0.001707   4.928 1.12e-06 ***
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

(Dispersion parameter for gaussian family taken to be 0.2176469)

    Null deviance: 119.33  on 525  degrees of freedom
Residual deviance: 114.05  on 524  degrees of freedom
AIC: 694.63

Number of Fisher Scoring iterations: 2</code></pre>
</div>
<details>
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb46"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb46-1"><a href="#cb46-1" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(<span class="at">data =</span> train, <span class="fu">aes</span>(<span class="at">x =</span> age, <span class="at">y =</span> diabetes)) <span class="sc">+</span></span>
<span id="cb46-2"><a href="#cb46-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_point</span>() <span class="sc">+</span></span>
<span id="cb46-3"><a href="#cb46-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_smooth</span>(<span class="at">method =</span> <span class="st">'lm'</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stderr">
<pre><code>`geom_smooth()` using formula = 'y ~ x'</code></pre>
</div>
<div class="cell-output-display">
<p><img src="StephRoberts_finalpart2_files/figure-html/unnamed-chunk-17-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<p>Interpretation: Similar to the previous variable, age also has small residuals and standard error. It shows a p-value of 1.12e-06, indicating a relationship between age and diabetes.</p>
<p>The hypothesis that BMI, glucose tolerance results, and age are positively associated with diabetes is true. Next, we can investigate models that could help predict the outcome using these variables.</p>
</section>
<section id="model-comparisons" class="level2">
<h2 class="anchored" data-anchor-id="model-comparisons">Model Comparisons</h2>
<section id="model-1" class="level3">
<h3 class="anchored" data-anchor-id="model-1">Model 1</h3>
<div class="cell">
<details>
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb48"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb48-1"><a href="#cb48-1" aria-hidden="true" tabindex="-1"></a><span class="co">#Summarize model including BMI, glucose, age, and pregnancies</span></span>
<span id="cb48-2"><a href="#cb48-2" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(all_var)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
glm(formula = diabetes ~ ., family = binomial, data = train)

Deviance Residuals: 
    Min       1Q   Median       3Q      Max  
-2.2423  -0.7382  -0.4133   0.7876   2.3714  

Coefficients:
            Estimate Std. Error z value Pr(&gt;|z|)    
(Intercept) -8.78253    0.86386 -10.167  &lt; 2e-16 ***
pregnancies  0.12194    0.03801   3.208  0.00134 ** 
glucose      0.03583    0.00420   8.533  &lt; 2e-16 ***
bmi          0.08150    0.01762   4.626 3.74e-06 ***
age          0.01328    0.01057   1.257  0.20877    
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

(Dispersion parameter for binomial family taken to be 1)

    Null deviance: 679.74  on 525  degrees of freedom
Residual deviance: 507.97  on 521  degrees of freedom
AIC: 517.97

Number of Fisher Scoring iterations: 5</code></pre>
</div>
</div>
<p>We can see with the all variable model that collectively, independent variables including pregnancies, glucose, bmi, dpf and even blood pressure have low p-values. That suggests those variables have a relationship with the outcome variable. We can use AIC as an indicator of model fitness, with this model being 517.97. Let’s compare this with the following models.</p>
</section>
<section id="model-2" class="level3">
<h3 class="anchored" data-anchor-id="model-2">Model 2</h3>
<div class="cell">
<details>
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb50"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb50-1"><a href="#cb50-1" aria-hidden="true" tabindex="-1"></a><span class="co">#Summarize BMI, glucose, and age model</span></span>
<span id="cb50-2"><a href="#cb50-2" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(bga)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
glm(formula = diabetes ~ . - pregnancies, family = binomial, 
    data = train)

Deviance Residuals: 
    Min       1Q   Median       3Q      Max  
-2.4041  -0.7545  -0.4352   0.7993   2.3643  

Coefficients:
             Estimate Std. Error z value Pr(&gt;|z|)    
(Intercept) -8.744037   0.852715 -10.254  &lt; 2e-16 ***
glucose      0.035131   0.004137   8.492  &lt; 2e-16 ***
bmi          0.079445   0.017191   4.621 3.82e-06 ***
age          0.031119   0.008956   3.474 0.000512 ***
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

(Dispersion parameter for binomial family taken to be 1)

    Null deviance: 679.74  on 525  degrees of freedom
Residual deviance: 518.60  on 522  degrees of freedom
AIC: 526.6

Number of Fisher Scoring iterations: 4</code></pre>
</div>
<details>
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb52"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb52-1"><a href="#cb52-1" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(train, <span class="fu">aes</span>(<span class="at">x=</span>age, <span class="at">y=</span>bmi, <span class="at">color=</span>glucose)) <span class="sc">+</span> <span class="fu">geom_point</span>() <span class="sc">+</span> <span class="fu">facet_grid</span>(<span class="sc">~</span>diabetes)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output-display">
<p><img src="StephRoberts_finalpart2_files/figure-html/unnamed-chunk-19-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<p>The model looking at BMI, age, and glucose as explanatory variables for diabetes has an AIC of 526.6, which is a worse fit than the all variables model.</p>
</section>
<section id="model-3" class="level3">
<h3 class="anchored" data-anchor-id="model-3">Model 3</h3>
<div class="cell">
<details>
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb53"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb53-1"><a href="#cb53-1" aria-hidden="true" tabindex="-1"></a><span class="co">#Summarize BMI and glucose model</span></span>
<span id="cb53-2"><a href="#cb53-2" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(bg)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
glm(formula = diabetes ~ . - age - pregnancies, family = binomial, 
    data = train)

Deviance Residuals: 
    Min       1Q   Median       3Q      Max  
-2.1839  -0.7780  -0.4709   0.7866   2.2925  

Coefficients:
            Estimate Std. Error z value Pr(&gt;|z|)    
(Intercept) -7.66078    0.76033 -10.076  &lt; 2e-16 ***
glucose      0.03728    0.00412   9.049  &lt; 2e-16 ***
bmi          0.07097    0.01677   4.231 2.32e-05 ***
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

(Dispersion parameter for binomial family taken to be 1)

    Null deviance: 679.74  on 525  degrees of freedom
Residual deviance: 530.80  on 523  degrees of freedom
AIC: 536.8

Number of Fisher Scoring iterations: 4</code></pre>
</div>
<details>
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb55"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb55-1"><a href="#cb55-1" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(train, <span class="fu">aes</span>(<span class="at">x=</span>glucose, <span class="at">y=</span>bmi, <span class="at">color=</span>diabetes)) <span class="sc">+</span> <span class="fu">geom_point</span>() <span class="sc">+</span> <span class="fu">facet_grid</span>(<span class="sc">~</span>diabetes)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output-display">
<p><img src="StephRoberts_finalpart2_files/figure-html/unnamed-chunk-20-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<p>This BMI and glucose only model has a worse (higher) AIC, with 536.8, than the 2 previous models. So far, the all variable model appears the best fit.</p>
</section>
<section id="model-4" class="level3">
<h3 class="anchored" data-anchor-id="model-4">Model 4</h3>
<div class="cell">
<details>
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb56"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb56-1"><a href="#cb56-1" aria-hidden="true" tabindex="-1"></a><span class="co">#Summarize model including interaction between age and pregnancies </span></span>
<span id="cb56-2"><a href="#cb56-2" aria-hidden="true" tabindex="-1"></a><span class="co">#This was chosen to see if the impact of age on diabetes is different depending on the number of pregnancies</span></span>
<span id="cb56-3"><a href="#cb56-3" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(ia)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
glm(formula = diabetes ~ glucose + bmi + age * pregnancies, family = binomial, 
    data = train)

Deviance Residuals: 
    Min       1Q   Median       3Q      Max  
-2.4728  -0.6818  -0.4072   0.7648   2.3441  

Coefficients:
                  Estimate Std. Error z value Pr(&gt;|z|)    
(Intercept)     -10.231410   1.028027  -9.952  &lt; 2e-16 ***
glucose           0.035779   0.004238   8.442  &lt; 2e-16 ***
bmi               0.084510   0.017867   4.730 2.25e-06 ***
age               0.053813   0.016978   3.170  0.00153 ** 
pregnancies       0.505863   0.134568   3.759  0.00017 ***
age:pregnancies  -0.009962   0.003337  -2.985  0.00283 ** 
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

(Dispersion parameter for binomial family taken to be 1)

    Null deviance: 679.74  on 525  degrees of freedom
Residual deviance: 498.41  on 520  degrees of freedom
AIC: 510.41

Number of Fisher Scoring iterations: 5</code></pre>
</div>
<details>
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb58"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb58-1"><a href="#cb58-1" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(train, <span class="fu">aes</span>(<span class="at">x=</span>age, <span class="at">y=</span>bmi, <span class="at">color=</span>pregnancies)) <span class="sc">+</span> <span class="fu">geom_point</span>() <span class="sc">+</span> <span class="fu">facet_grid</span>(<span class="sc">~</span>diabetes)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output-display">
<p><img src="StephRoberts_finalpart2_files/figure-html/unnamed-chunk-21-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<p>With an AIC of 510.41, this model appears to be the best fit model of those we have compared. This indicated there is an interaction between age and pregnancies that has a relationship with the outcome variable.</p>
</section>
<section id="model-5" class="level3">
<h3 class="anchored" data-anchor-id="model-5">Model 5</h3>
<div class="cell">
<details>
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb59"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb59-1"><a href="#cb59-1" aria-hidden="true" tabindex="-1"></a><span class="co">#Summarize model including without age</span></span>
<span id="cb59-2"><a href="#cb59-2" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(bgp)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
glm(formula = diabetes ~ . - age, family = binomial, data = train)

Deviance Residuals: 
    Min       1Q   Median       3Q      Max  
-2.2180  -0.7390  -0.4176   0.7806   2.3503  

Coefficients:
             Estimate Std. Error z value Pr(&gt;|z|)    
(Intercept) -8.454908   0.814921 -10.375  &lt; 2e-16 ***
pregnancies  0.147046   0.032598   4.511 6.46e-06 ***
glucose      0.036658   0.004169   8.794  &lt; 2e-16 ***
bmi          0.079282   0.017533   4.522 6.13e-06 ***
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

(Dispersion parameter for binomial family taken to be 1)

    Null deviance: 679.74  on 525  degrees of freedom
Residual deviance: 509.54  on 522  degrees of freedom
AIC: 517.54

Number of Fisher Scoring iterations: 4</code></pre>
</div>
<details>
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb61"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb61-1"><a href="#cb61-1" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(train, <span class="fu">aes</span>(<span class="at">x=</span>pregnancies, <span class="at">y=</span>bmi, <span class="at">color=</span>glucose)) <span class="sc">+</span> <span class="fu">geom_point</span>() <span class="sc">+</span> <span class="fu">facet_grid</span>(<span class="sc">~</span>diabetes)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output-display">
<p><img src="StephRoberts_finalpart2_files/figure-html/unnamed-chunk-22-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<p>Removing age entirely increased the AIC of this model. So, the interaction model seems to be the best fit. That is, model 4 which includes BMI and glucose and controls for an interaction between age and pregnancy has the best fit of all models tested.</p>
<p>We can use ANOVA to analyze the table of deviance of our regression model.</p>
<div class="cell">
<details>
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb62"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb62-1"><a href="#cb62-1" aria-hidden="true" tabindex="-1"></a><span class="co">#ANOVA test on interaction model 4</span></span>
<span id="cb62-2"><a href="#cb62-2" aria-hidden="true" tabindex="-1"></a><span class="fu">anova</span>(ia, <span class="at">test =</span> <span class="st">"Chisq"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>Analysis of Deviance Table

Model: binomial, link: logit

Response: diabetes

Terms added sequentially (first to last)

                Df Deviance Resid. Df Resid. Dev  Pr(&gt;Chi)    
NULL                              525     679.74              
glucose          1  130.061       524     549.68 &lt; 2.2e-16 ***
bmi              1   18.883       523     530.80  1.39e-05 ***
age              1   12.197       522     518.60 0.0004786 ***
pregnancies      1   10.635       521     507.97 0.0011098 ** 
age:pregnancies  1    9.554       520     498.41 0.0019950 ** 
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1</code></pre>
</div>
</div>
<p>All of our variables have small p-values and appear good predictors of the diabetes outcome, with the exception of age. However, age is needed for the interaction variable.</p>
<p>Let’s check one more thing to ensure we have a good fit.</p>
<div class="cell">
<details>
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb64"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb64-1"><a href="#cb64-1" aria-hidden="true" tabindex="-1"></a><span class="co">#Check pseudo R2 for interaction model</span></span>
<span id="cb64-2"><a href="#cb64-2" aria-hidden="true" tabindex="-1"></a><span class="fu">pR2</span>(ia)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-error">
<pre><code>Error in pR2(ia): could not find function "pR2"</code></pre>
</div>
</div>
<p>With a McFadden R-squared of 0.27, model 4 can be considered an excellent fit.</p>
</section>
</section>
<section id="diagnostics" class="level2">
<h2 class="anchored" data-anchor-id="diagnostics">Diagnostics</h2>
<p>To test the model, the next step is to apply it to the test subset of data.</p>
<div class="cell">
<details>
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb66"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb66-1"><a href="#cb66-1" aria-hidden="true" tabindex="-1"></a><span class="co">#Apply model to test data</span></span>
<span id="cb66-2"><a href="#cb66-2" aria-hidden="true" tabindex="-1"></a>fitted.results <span class="ot">&lt;-</span> <span class="fu">predict</span>(ia ,test,<span class="at">type=</span><span class="st">'response'</span>)</span>
<span id="cb66-3"><a href="#cb66-3" aria-hidden="true" tabindex="-1"></a>fitted.results <span class="ot">&lt;-</span> <span class="fu">ifelse</span>(fitted.results <span class="sc">&gt;</span> <span class="fl">0.5</span>,<span class="dv">1</span>,<span class="dv">0</span>)</span>
<span id="cb66-4"><a href="#cb66-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb66-5"><a href="#cb66-5" aria-hidden="true" tabindex="-1"></a>pred <span class="ot">&lt;-</span> <span class="fu">mean</span>(fitted.results <span class="sc">!=</span> test<span class="sc">$</span>diabetes)</span>
<span id="cb66-6"><a href="#cb66-6" aria-hidden="true" tabindex="-1"></a>output <span class="ot">&lt;-</span> <span class="fu">cbind</span>(test, fitted.results)</span>
<span id="cb66-7"><a href="#cb66-7" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb66-8"><a href="#cb66-8" aria-hidden="true" tabindex="-1"></a><span class="fu">print</span>(<span class="fu">paste</span>(<span class="st">'Accuracy'</span>,<span class="dv">1</span><span class="sc">-</span>pred))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>[1] "Accuracy 0.787610619469027"</code></pre>
</div>
<details>
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb68"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb68-1"><a href="#cb68-1" aria-hidden="true" tabindex="-1"></a><span class="fu">head</span>(output)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>   pregnancies glucose  bmi age diabetes fitted.results
9            2     197 30.5  53        1              1
10           4     110 37.6  30        0              0
12          10     139 27.1  57        0              0
13           1     189 30.1  59        1              1
14           5     166 25.8  51        1              1
17           7     107 29.6  31        1              0</code></pre>
</div>
</div>
<p>Testing the interaction model on the test data produces the correct outcome 79% of the time.</p>
<div class="cell">
<details>
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb70"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb70-1"><a href="#cb70-1" aria-hidden="true" tabindex="-1"></a><span class="co">#Diagnostic plot of model</span></span>
<span id="cb70-2"><a href="#cb70-2" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(ia)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output-display">
<p><img src="StephRoberts_finalpart2_files/figure-html/unnamed-chunk-26-1.png" class="img-fluid" width="672"></p>
</div>
<div class="cell-output-display">
<p><img src="StephRoberts_finalpart2_files/figure-html/unnamed-chunk-26-2.png" class="img-fluid" width="672"></p>
</div>
<div class="cell-output-display">
<p><img src="StephRoberts_finalpart2_files/figure-html/unnamed-chunk-26-3.png" class="img-fluid" width="672"></p>
</div>
<div class="cell-output-display">
<p><img src="StephRoberts_finalpart2_files/figure-html/unnamed-chunk-26-4.png" class="img-fluid" width="672"></p>
</div>
</div>
<p><strong>Residuals vs Fitted</strong>: The residuals have 2 distinct patterns of behavior. They start at close to 0 and taper off to a negative slope. Another group of residuals starts large and tapers on a negative slope toward 0.</p>
<p><strong>Normal Q-Q</strong>: The Q-Q plot, which indicates level of asymmetry, tells us our data is not a normal distribution. It appears to have a right tail (see the points drifting from the line at the top), which aligns with our individual variable histogram interpretations. It follows that a model combining variables with right skews may also be skewed to the right. However, it also has values away from the line on the bottom left, away from the intercept. This suggests our model also includes a left tail. This distribution seems to have “fat tails.”</p>
<p><strong>Scale-Location</strong>: This plots the fitted values of the model along the x-axis and the square root of the standardized residuals along the y-axis. The red line does roughly travel horizontal across the plot. However, there is a clear X pattern among residuals. This suggests our model has heteroscedasticity, which is not ideal.</p>
<p><strong>Residuals vs Leverage</strong>: The points on this graph all fall within Cook’s distance, indicating there are not any influential points in our regression model.</p>
<p><em>Plan to work on fixing the heteroscedasticity by log transforming BMI, pregnancies, and age when those variables are included in models because they are right skewed data. However, it is taking time figuring out how to do a multiple logistics regression without errors..</em></p>


<!-- -->

</section>

</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const disableStylesheet = (stylesheets) => {
    for (let i=0; i < stylesheets.length; i++) {
      const stylesheet = stylesheets[i];
      stylesheet.rel = 'prefetch';
    }
  }
  const enableStylesheet = (stylesheets) => {
    for (let i=0; i < stylesheets.length; i++) {
      const stylesheet = stylesheets[i];
      stylesheet.rel = 'stylesheet';
    }
  }
  const manageTransitions = (selector, allowTransitions) => {
    const els = window.document.querySelectorAll(selector);
    for (let i=0; i < els.length; i++) {
      const el = els[i];
      if (allowTransitions) {
        el.classList.remove('notransition');
      } else {
        el.classList.add('notransition');
      }
    }
  }
  const toggleColorMode = (alternate) => {
    // Switch the stylesheets
    const alternateStylesheets = window.document.querySelectorAll('link.quarto-color-scheme.quarto-color-alternate');
    manageTransitions('#quarto-margin-sidebar .nav-link', false);
    if (alternate) {
      enableStylesheet(alternateStylesheets);
      for (const sheetNode of alternateStylesheets) {
        if (sheetNode.id === "quarto-bootstrap") {
          toggleBodyColorMode(sheetNode);
        }
      }
    } else {
      disableStylesheet(alternateStylesheets);
      toggleBodyColorPrimary();
    }
    manageTransitions('#quarto-margin-sidebar .nav-link', true);
    // Switch the toggles
    const toggles = window.document.querySelectorAll('.quarto-color-scheme-toggle');
    for (let i=0; i < toggles.length; i++) {
      const toggle = toggles[i];
      if (toggle) {
        if (alternate) {
          toggle.classList.add("alternate");     
        } else {
          toggle.classList.remove("alternate");
        }
      }
    }
    // Hack to workaround the fact that safari doesn't
    // properly recolor the scrollbar when toggling (#1455)
    if (navigator.userAgent.indexOf('Safari') > 0 && navigator.userAgent.indexOf('Chrome') == -1) {
      manageTransitions("body", false);
      window.scrollTo(0, 1);
      setTimeout(() => {
        window.scrollTo(0, 0);
        manageTransitions("body", true);
      }, 40);  
    }
  }
  const isFileUrl = () => { 
    return window.location.protocol === 'file:';
  }
  const hasAlternateSentinel = () => {  
    let styleSentinel = getColorSchemeSentinel();
    if (styleSentinel !== null) {
      return styleSentinel === "alternate";
    } else {
      return false;
    }
  }
  const setStyleSentinel = (alternate) => {
    const value = alternate ? "alternate" : "default";
    if (!isFileUrl()) {
      window.localStorage.setItem("quarto-color-scheme", value);
    } else {
      localAlternateSentinel = value;
    }
  }
  const getColorSchemeSentinel = () => {
    if (!isFileUrl()) {
      const storageValue = window.localStorage.getItem("quarto-color-scheme");
      return storageValue != null ? storageValue : localAlternateSentinel;
    } else {
      return localAlternateSentinel;
    }
  }
  let localAlternateSentinel = 'default';
  // Dark / light mode switch
  window.quartoToggleColorScheme = () => {
    // Read the current dark / light value 
    let toAlternate = !hasAlternateSentinel();
    toggleColorMode(toAlternate);
    setStyleSentinel(toAlternate);
  };
  // Ensure there is a toggle, if there isn't float one in the top right
  if (window.document.querySelector('.quarto-color-scheme-toggle') === null) {
    const a = window.document.createElement('a');
    a.classList.add('top-right');
    a.classList.add('quarto-color-scheme-toggle');
    a.href = "";
    a.onclick = function() { try { window.quartoToggleColorScheme(); } catch {} return false; };
    const i = window.document.createElement("i");
    i.classList.add('bi');
    a.appendChild(i);
    window.document.body.appendChild(a);
  }
  // Switch to dark mode if need be
  if (hasAlternateSentinel()) {
    toggleColorMode(true);
  } else {
    toggleColorMode(false);
  }
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const clipboard = new window.ClipboardJS('.code-copy-button', {
    target: function(trigger) {
      return trigger.previousElementSibling;
    }
  });
  clipboard.on('success', function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copied!");
    let tooltip;
    if (window.bootstrap) {
      button.setAttribute("data-bs-toggle", "tooltip");
      button.setAttribute("data-bs-placement", "left");
      button.setAttribute("data-bs-title", "Copied!");
      tooltip = new bootstrap.Tooltip(button, 
        { trigger: "manual", 
          customClass: "code-copy-button-tooltip",
          offset: [0, -8]});
      tooltip.show();    
    }
    setTimeout(function() {
      if (tooltip) {
        tooltip.hide();
        button.removeAttribute("data-bs-title");
        button.removeAttribute("data-bs-toggle");
        button.removeAttribute("data-bs-placement");
      }
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  });
  const viewSource = window.document.getElementById('quarto-view-source') ||
                     window.document.getElementById('quarto-code-tools-source');
  if (viewSource) {
    const sourceUrl = viewSource.getAttribute("data-quarto-source-url");
    viewSource.addEventListener("click", function(e) {
      if (sourceUrl) {
        // rstudio viewer pane
        if (/\bcapabilities=\b/.test(window.location)) {
          window.open(sourceUrl);
        } else {
          window.location.href = sourceUrl;
        }
      } else {
        const modal = new bootstrap.Modal(document.getElementById('quarto-embedded-source-code-modal'));
        modal.show();
      }
      return false;
    });
  }
  function toggleCodeHandler(show) {
    return function(e) {
      const detailsSrc = window.document.querySelectorAll(".cell > details > .sourceCode");
      for (let i=0; i<detailsSrc.length; i++) {
        const details = detailsSrc[i].parentElement;
        if (show) {
          details.open = true;
        } else {
          details.removeAttribute("open");
        }
      }
      const cellCodeDivs = window.document.querySelectorAll(".cell > .sourceCode");
      const fromCls = show ? "hidden" : "unhidden";
      const toCls = show ? "unhidden" : "hidden";
      for (let i=0; i<cellCodeDivs.length; i++) {
        const codeDiv = cellCodeDivs[i];
        if (codeDiv.classList.contains(fromCls)) {
          codeDiv.classList.remove(fromCls);
          codeDiv.classList.add(toCls);
        } 
      }
      return false;
    }
  }
  const hideAllCode = window.document.getElementById("quarto-hide-all-code");
  if (hideAllCode) {
    hideAllCode.addEventListener("click", toggleCodeHandler(false));
  }
  const showAllCode = window.document.getElementById("quarto-show-all-code");
  if (showAllCode) {
    showAllCode.addEventListener("click", toggleCodeHandler(true));
  }
  function tippyHover(el, contentFn) {
    const config = {
      allowHTML: true,
      content: contentFn,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start'
    };
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      return note.innerHTML;
    });
  }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
});
</script>
<script src="https://giscus.app/client.js" data-repo="DACSS/603_Fall_2022" data-repo-id="R_kgDOH568kA" data-category="Announcements" data-category-id="" data-mapping="title" data-reactions-enabled="1" data-emit-metadata="0" data-input-position="top" data-theme="light" data-lang="en" crossorigin="anonymous" async="">
</script><div class="modal fade" id="quarto-embedded-source-code-modal" tabindex="-1" aria-labelledby="quarto-embedded-source-code-modal-label" aria-hidden="true"><div class="modal-dialog modal-dialog-scrollable"><div class="modal-content"><div class="modal-header"><h5 class="modal-title" id="quarto-embedded-source-code-modal-label">Source Code</h5><button class="btn-close" data-bs-dismiss="modal"></button></div><div class="modal-body"><div class="">
<div class="sourceCode" id="cb71" data-shortcodes="false"><pre class="sourceCode markdown code-with-copy"><code class="sourceCode markdown"><span id="cb71-1"><a href="#cb71-1" aria-hidden="true" tabindex="-1"></a><span class="co">---</span></span>
<span id="cb71-2"><a href="#cb71-2" aria-hidden="true" tabindex="-1"></a><span class="an">title:</span><span class="co"> "Final Project: Diabetes Prediction - Part 2"</span></span>
<span id="cb71-3"><a href="#cb71-3" aria-hidden="true" tabindex="-1"></a><span class="an">author:</span><span class="co"> "Steph Roberts"</span></span>
<span id="cb71-4"><a href="#cb71-4" aria-hidden="true" tabindex="-1"></a><span class="an">desription:</span><span class="co"> "Final Project Draft 2"</span></span>
<span id="cb71-5"><a href="#cb71-5" aria-hidden="true" tabindex="-1"></a><span class="an">date:</span><span class="co"> "10/9/2022"</span></span>
<span id="cb71-6"><a href="#cb71-6" aria-hidden="true" tabindex="-1"></a><span class="an">format:</span></span>
<span id="cb71-7"><a href="#cb71-7" aria-hidden="true" tabindex="-1"></a><span class="co">  html:</span></span>
<span id="cb71-8"><a href="#cb71-8" aria-hidden="true" tabindex="-1"></a><span class="co">    toc: true</span></span>
<span id="cb71-9"><a href="#cb71-9" aria-hidden="true" tabindex="-1"></a><span class="co">    code-fold: true</span></span>
<span id="cb71-10"><a href="#cb71-10" aria-hidden="true" tabindex="-1"></a><span class="co">    code-copy: true</span></span>
<span id="cb71-11"><a href="#cb71-11" aria-hidden="true" tabindex="-1"></a><span class="co">    code-tools: true</span></span>
<span id="cb71-12"><a href="#cb71-12" aria-hidden="true" tabindex="-1"></a><span class="an">categories:</span></span>
<span id="cb71-13"><a href="#cb71-13" aria-hidden="true" tabindex="-1"></a><span class="co">  - finalproject</span></span>
<span id="cb71-14"><a href="#cb71-14" aria-hidden="true" tabindex="-1"></a><span class="co">  - Steph Roberts</span></span>
<span id="cb71-15"><a href="#cb71-15" aria-hidden="true" tabindex="-1"></a><span class="co">  - dataset</span></span>
<span id="cb71-16"><a href="#cb71-16" aria-hidden="true" tabindex="-1"></a><span class="co">  - ggplot2</span></span>
<span id="cb71-17"><a href="#cb71-17" aria-hidden="true" tabindex="-1"></a><span class="co">---</span></span>
<span id="cb71-18"><a href="#cb71-18" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb71-21"><a href="#cb71-21" aria-hidden="true" tabindex="-1"></a><span class="in">```{r}</span></span>
<span id="cb71-22"><a href="#cb71-22" aria-hidden="true" tabindex="-1"></a><span class="co">#| label: setup</span></span>
<span id="cb71-23"><a href="#cb71-23" aria-hidden="true" tabindex="-1"></a><span class="co">#| warning: false</span></span>
<span id="cb71-24"><a href="#cb71-24" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb71-25"><a href="#cb71-25" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(tidyverse)</span>
<span id="cb71-26"><a href="#cb71-26" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(ggplot2)</span>
<span id="cb71-27"><a href="#cb71-27" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(dplyr)</span>
<span id="cb71-28"><a href="#cb71-28" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb71-29"><a href="#cb71-29" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(magrittr)</span>
<span id="cb71-30"><a href="#cb71-30" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb71-31"><a href="#cb71-31" aria-hidden="true" tabindex="-1"></a>knitr<span class="sc">::</span>opts_chunk<span class="sc">$</span><span class="fu">set</span>(<span class="at">echo =</span> <span class="cn">TRUE</span>)</span>
<span id="cb71-32"><a href="#cb71-32" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb71-33"><a href="#cb71-33" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb71-34"><a href="#cb71-34" aria-hidden="true" tabindex="-1"></a><span class="fu">### Diabetes risk factors</span></span>
<span id="cb71-35"><a href="#cb71-35" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb71-36"><a href="#cb71-36" aria-hidden="true" tabindex="-1"></a>According to the World Health Organization (WHO), an estimated 537 million people worldwide are living with diabetes. It is a leading cause of health complications and even death. The WHO states close to 1.5 million people died due to diabetes and its complication in 2019 alone. It is a growing problem that requires dedicated research to aim at the slowdown and prevention of future cases. </span>
<span id="cb71-37"><a href="#cb71-37" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb71-38"><a href="#cb71-38" aria-hidden="true" tabindex="-1"></a><span class="fu">## Research Question</span></span>
<span id="cb71-39"><a href="#cb71-39" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb71-40"><a href="#cb71-40" aria-hidden="true" tabindex="-1"></a><span class="ss">1. </span>What risk factors are most predictive of diabetes? </span>
<span id="cb71-41"><a href="#cb71-41" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb71-42"><a href="#cb71-42" aria-hidden="true" tabindex="-1"></a>Research on Diabetes is ongoing and in-depth within the medical field. The prevalence and incidence of diabetes mellitus type 2 (DQ2) have increased consistently for decades, giving way to an increase in mortality related to diabetes. Commonly in the medical field, many risk factors are used to measure a patient’s risk of developing DM2, such as obesity, family history, hypertension and changes in fasting blood sugar levels. </span>
<span id="cb71-43"><a href="#cb71-43" aria-hidden="true" tabindex="-1"></a>Moreno et al. (2018) studied risk parameters for diabetes and concluded "risk of being diabetic rises in patients whose father has suffered an acute myocardial infarction, in those whose mother or father is diabetic and in patients with a high waist perimeter." </span>
<span id="cb71-44"><a href="#cb71-44" aria-hidden="true" tabindex="-1"></a>Their focus on family history leaves room for studies more focused on individual medical factors, such as blood pressure, BMI, number of pregnancies, etc. That is the aim of this project.</span>
<span id="cb71-45"><a href="#cb71-45" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb71-46"><a href="#cb71-46" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb71-47"><a href="#cb71-47" aria-hidden="true" tabindex="-1"></a>M. L. M. V. J. A. (2018, June 11). Predictive risk model for the diagnosis of diabetes mellitus type 2 in a follow-up study 15 Years on: Prodi2 study. European journal of public health. Retrieved October 9, 2022, from https://pubmed.ncbi.nlm.nih.gov/29897477/ </span>
<span id="cb71-48"><a href="#cb71-48" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb71-49"><a href="#cb71-49" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb71-50"><a href="#cb71-50" aria-hidden="true" tabindex="-1"></a><span class="ss">2. </span>Can the use of regression analysis help predict risk of diabetes based on several medical variables?</span>
<span id="cb71-51"><a href="#cb71-51" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb71-52"><a href="#cb71-52" aria-hidden="true" tabindex="-1"></a>Other research, such as a Edlitz &amp; Segal (2022) study titled Prediction of type 2 diabetes mellitus onset using logistic regression-based scorecards, does focus on using individual medical factors to predict risk of diabetes through regression. This project aims to conduct similar analysis on different data. </span>
<span id="cb71-53"><a href="#cb71-53" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb71-54"><a href="#cb71-54" aria-hidden="true" tabindex="-1"></a>E. Y. S. E. (2022, June 22). Prediction of type 2 diabetes mellitus onset using logistic regression-based scorecards. eLife. Retrieved October 9, 2022, from https://pubmed.ncbi.nlm.nih.gov/35731045/ </span>
<span id="cb71-55"><a href="#cb71-55" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb71-56"><a href="#cb71-56" aria-hidden="true" tabindex="-1"></a><span class="fu">## Hypothesis</span></span>
<span id="cb71-57"><a href="#cb71-57" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb71-58"><a href="#cb71-58" aria-hidden="true" tabindex="-1"></a>Body mass index (BMI), glucose, and age are positive predictors of diabetes mellitus type 2.  </span>
<span id="cb71-59"><a href="#cb71-59" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb71-60"><a href="#cb71-60" aria-hidden="true" tabindex="-1"></a>This hypothesis has been tested in the above mentioned studies. The contribution from this project will be the additional support for or against the hypotheses from the analysis of different data. </span>
<span id="cb71-61"><a href="#cb71-61" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb71-62"><a href="#cb71-62" aria-hidden="true" tabindex="-1"></a><span class="fu">## Descriptive Statistics</span></span>
<span id="cb71-63"><a href="#cb71-63" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb71-64"><a href="#cb71-64" aria-hidden="true" tabindex="-1"></a>The data was collected by the “National Institute of Diabetes and Digestive and Kidney Diseases” as part of the Pima Indians Diabetes Database (PIDD). A total of 768 cases are available in PIDD. However, 5 patients had a glucose of 0 and 11 patients had a body mass index of 0. After cleaning the data by removing the cases with numbers that are incompatible with life in categories important to the current research, 752 cases remained. All patients belong to the Pima Indian heritage (subgroup of Native Americans), and are females aged 21 years and above.</span>
<span id="cb71-65"><a href="#cb71-65" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb71-66"><a href="#cb71-66" aria-hidden="true" tabindex="-1"></a>The datasets consists of 9 medical predictor (independent) variables and one target (dependent) variable, outcome.  </span>
<span id="cb71-67"><a href="#cb71-67" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb71-68"><a href="#cb71-68" aria-hidden="true" tabindex="-1"></a>**Pregnancies:** Number of times a woman has been pregnant  </span>
<span id="cb71-69"><a href="#cb71-69" aria-hidden="true" tabindex="-1"></a>**Glucose:** Plasma Glucose concentration of 2 hours in an oral glucose tolerance test  </span>
<span id="cb71-70"><a href="#cb71-70" aria-hidden="true" tabindex="-1"></a>**BloodPressure:** Diastolic Blood Pressure (mm hg)  </span>
<span id="cb71-71"><a href="#cb71-71" aria-hidden="true" tabindex="-1"></a>**SkinThickness:** Triceps skin fold thickness(mm)  </span>
<span id="cb71-72"><a href="#cb71-72" aria-hidden="true" tabindex="-1"></a>**Insulin:** 2 hour serum insulin(mu U/ml)  </span>
<span id="cb71-73"><a href="#cb71-73" aria-hidden="true" tabindex="-1"></a>**BMI:** Body Mass Index ((weight in kg/height in m)^2)  </span>
<span id="cb71-74"><a href="#cb71-74" aria-hidden="true" tabindex="-1"></a>**Age:** Age(years)  </span>
<span id="cb71-75"><a href="#cb71-75" aria-hidden="true" tabindex="-1"></a>**DiabetesPedigreeFunction:** scores likelihood of diabetes based on family history  </span>
<span id="cb71-76"><a href="#cb71-76" aria-hidden="true" tabindex="-1"></a>**Outcome:** 0 (doesn't have diabetes) or 1 (has diabetes)</span>
<span id="cb71-77"><a href="#cb71-77" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb71-78"><a href="#cb71-78" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb71-81"><a href="#cb71-81" aria-hidden="true" tabindex="-1"></a><span class="in">```{r}</span></span>
<span id="cb71-82"><a href="#cb71-82" aria-hidden="true" tabindex="-1"></a>df<span class="ot">&lt;-</span> <span class="fu">read_csv</span>(<span class="st">"_data/diabetes2.csv"</span>)</span>
<span id="cb71-83"><a href="#cb71-83" aria-hidden="true" tabindex="-1"></a><span class="fu">dim</span>(df)</span>
<span id="cb71-84"><a href="#cb71-84" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(df)</span>
<span id="cb71-85"><a href="#cb71-85" aria-hidden="true" tabindex="-1"></a><span class="fu">head</span>(df)</span>
<span id="cb71-86"><a href="#cb71-86" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb71-89"><a href="#cb71-89" aria-hidden="true" tabindex="-1"></a><span class="in">```{r}</span></span>
<span id="cb71-90"><a href="#cb71-90" aria-hidden="true" tabindex="-1"></a><span class="co">#check for null entries</span></span>
<span id="cb71-91"><a href="#cb71-91" aria-hidden="true" tabindex="-1"></a><span class="fu">is.null</span>(df)</span>
<span id="cb71-92"><a href="#cb71-92" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb71-95"><a href="#cb71-95" aria-hidden="true" tabindex="-1"></a><span class="in">```{r}</span></span>
<span id="cb71-96"><a href="#cb71-96" aria-hidden="true" tabindex="-1"></a><span class="co">#Check number of 0s in each column</span></span>
<span id="cb71-97"><a href="#cb71-97" aria-hidden="true" tabindex="-1"></a><span class="fu">colSums</span>(df<span class="sc">==</span><span class="dv">0</span>)</span>
<span id="cb71-98"><a href="#cb71-98" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb71-99"><a href="#cb71-99" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb71-100"><a href="#cb71-100" aria-hidden="true" tabindex="-1"></a>Glucose, blood pressure, skin thickness, insulin, BMI and Age are not variables that should logically have 0s. Those values, if true, are likely incompatible with life. To reduce the amount of data we exclude, we will only remove observations that have 0s for our explanatory variables. We will remove those cases from analysis.</span>
<span id="cb71-101"><a href="#cb71-101" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb71-104"><a href="#cb71-104" aria-hidden="true" tabindex="-1"></a><span class="in">```{r}</span></span>
<span id="cb71-105"><a href="#cb71-105" aria-hidden="true" tabindex="-1"></a><span class="co">#Remove rows with 0 in respective columns</span></span>
<span id="cb71-106"><a href="#cb71-106" aria-hidden="true" tabindex="-1"></a>df <span class="ot">&lt;-</span> df[<span class="fu">apply</span>(df[<span class="fu">c</span>(<span class="dv">2</span>,<span class="dv">6</span>)],<span class="dv">1</span>,<span class="cf">function</span>(z) <span class="sc">!</span><span class="fu">any</span>(z<span class="sc">==</span><span class="dv">0</span>)),] </span>
<span id="cb71-107"><a href="#cb71-107" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb71-108"><a href="#cb71-108" aria-hidden="true" tabindex="-1"></a><span class="co">#Verify 0s are gone in selected rows</span></span>
<span id="cb71-109"><a href="#cb71-109" aria-hidden="true" tabindex="-1"></a><span class="fu">colSums</span>(df<span class="sc">==</span><span class="dv">0</span>)</span>
<span id="cb71-110"><a href="#cb71-110" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb71-111"><a href="#cb71-111" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb71-114"><a href="#cb71-114" aria-hidden="true" tabindex="-1"></a><span class="in">```{r}</span></span>
<span id="cb71-115"><a href="#cb71-115" aria-hidden="true" tabindex="-1"></a><span class="co">#Check cleaned data frame</span></span>
<span id="cb71-116"><a href="#cb71-116" aria-hidden="true" tabindex="-1"></a><span class="fu">glimpse</span>(df)</span>
<span id="cb71-117"><a href="#cb71-117" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb71-118"><a href="#cb71-118" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb71-121"><a href="#cb71-121" aria-hidden="true" tabindex="-1"></a><span class="in">```{r}</span></span>
<span id="cb71-122"><a href="#cb71-122" aria-hidden="true" tabindex="-1"></a><span class="co">#Summarize df</span></span>
<span id="cb71-123"><a href="#cb71-123" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(df)</span>
<span id="cb71-124"><a href="#cb71-124" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb71-125"><a href="#cb71-125" aria-hidden="true" tabindex="-1"></a>At a glance, this summary is more fitting after having cleaned our data. An average of 3 pregnancies, considering our 21+ female population, makes sense. A mean glucose of 122, blood pressure of 70, a BMI of 33, and age of 33 are reasonably accurate for our population. </span>
<span id="cb71-126"><a href="#cb71-126" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb71-129"><a href="#cb71-129" aria-hidden="true" tabindex="-1"></a><span class="in">```{r}</span></span>
<span id="cb71-130"><a href="#cb71-130" aria-hidden="true" tabindex="-1"></a><span class="co">#Rename columns</span></span>
<span id="cb71-131"><a href="#cb71-131" aria-hidden="true" tabindex="-1"></a><span class="fu">colnames</span>(df) <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="st">"pregnancies"</span>, <span class="st">"glucose"</span>, <span class="st">"bp"</span>, <span class="st">"skin_thickness"</span>, <span class="st">"insulin"</span>, <span class="st">"bmi"</span>, <span class="st">"dpf"</span>, <span class="st">"age"</span>, <span class="st">"diabetes"</span>)</span>
<span id="cb71-132"><a href="#cb71-132" aria-hidden="true" tabindex="-1"></a><span class="fu">dim</span>(df)</span>
<span id="cb71-133"><a href="#cb71-133" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb71-134"><a href="#cb71-134" aria-hidden="true" tabindex="-1"></a>We have 752 observations and 9 variables with which to work. The data is clean and ready for analysis. </span>
<span id="cb71-135"><a href="#cb71-135" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb71-136"><a href="#cb71-136" aria-hidden="true" tabindex="-1"></a>Let's get familiar with the data set by observing the scatterplot matrix and histograms for each variable.</span>
<span id="cb71-137"><a href="#cb71-137" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb71-140"><a href="#cb71-140" aria-hidden="true" tabindex="-1"></a><span class="in">```{r}</span></span>
<span id="cb71-141"><a href="#cb71-141" aria-hidden="true" tabindex="-1"></a><span class="co">#Scatterplot matrix</span></span>
<span id="cb71-142"><a href="#cb71-142" aria-hidden="true" tabindex="-1"></a><span class="fu">pairs</span>(df)</span>
<span id="cb71-143"><a href="#cb71-143" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb71-144"><a href="#cb71-144" aria-hidden="true" tabindex="-1"></a><span class="co">#Histograms of each variable</span></span>
<span id="cb71-145"><a href="#cb71-145" aria-hidden="true" tabindex="-1"></a><span class="fu">hist.data.frame</span>(df)</span>
<span id="cb71-146"><a href="#cb71-146" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb71-147"><a href="#cb71-147" aria-hidden="true" tabindex="-1"></a>The scatterplot matix shows that our variables generally lack linear relationships. Logistics regression may be best for analyzing this type of data. </span>
<span id="cb71-148"><a href="#cb71-148" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb71-149"><a href="#cb71-149" aria-hidden="true" tabindex="-1"></a>The histograms show us the distribution of all our variables. Pregnancies is right skewed with more women having a smaller number of pregnancies and a small number having over 10. Glucose appears to follow a close-to-normal distribution with the mean just over 100. BMI follows a similar pattern with a central value of just over 30. Age is right skewed with the majority of the sample appearing to be in their 20s and slower tapering off to ages in their 50s. This is a good place to start. The only variable we cannot view in a histogram is the outcome variable due to its binary nature as a dummy variable. </span>
<span id="cb71-150"><a href="#cb71-150" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb71-153"><a href="#cb71-153" aria-hidden="true" tabindex="-1"></a><span class="in">```{r}</span></span>
<span id="cb71-154"><a href="#cb71-154" aria-hidden="true" tabindex="-1"></a>bgap <span class="ot">&lt;-</span> <span class="fu">as.data.frame</span>(df[, <span class="fu">c</span>(<span class="dv">1</span>,<span class="dv">2</span>,<span class="dv">6</span>,<span class="dv">8</span>,<span class="dv">9</span>)])</span>
<span id="cb71-155"><a href="#cb71-155" aria-hidden="true" tabindex="-1"></a><span class="fu">pairs</span>(bgap)</span>
<span id="cb71-156"><a href="#cb71-156" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb71-157"><a href="#cb71-157" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb71-160"><a href="#cb71-160" aria-hidden="true" tabindex="-1"></a><span class="in">```{r}</span></span>
<span id="cb71-161"><a href="#cb71-161" aria-hidden="true" tabindex="-1"></a><span class="co">#Plot outcome variable</span></span>
<span id="cb71-162"><a href="#cb71-162" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(df, <span class="fu">aes</span>(<span class="at">x=</span><span class="fu">factor</span>(diabetes))) <span class="sc">+</span></span>
<span id="cb71-163"><a href="#cb71-163" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_bar</span>(<span class="at">fill =</span> <span class="st">"#0073C2FF"</span>)<span class="sc">+</span></span>
<span id="cb71-164"><a href="#cb71-164" aria-hidden="true" tabindex="-1"></a>  <span class="fu">scale_x_discrete</span>(<span class="at">labels=</span><span class="fu">c</span>(<span class="st">'No Diabetes'</span>,<span class="st">'Diabetes'</span>))<span class="sc">+</span></span>
<span id="cb71-165"><a href="#cb71-165" aria-hidden="true" tabindex="-1"></a>  <span class="fu">xlab</span>(<span class="st">"Outcome"</span>)</span>
<span id="cb71-166"><a href="#cb71-166" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb71-167"><a href="#cb71-167" aria-hidden="true" tabindex="-1"></a>About a third of our sample have diabetes. </span>
<span id="cb71-168"><a href="#cb71-168" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb71-169"><a href="#cb71-169" aria-hidden="true" tabindex="-1"></a><span class="fu">## Hypothesis Testing</span></span>
<span id="cb71-170"><a href="#cb71-170" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb71-173"><a href="#cb71-173" aria-hidden="true" tabindex="-1"></a><span class="in">```{r}</span></span>
<span id="cb71-174"><a href="#cb71-174" aria-hidden="true" tabindex="-1"></a><span class="co">#Create training and test data</span></span>
<span id="cb71-175"><a href="#cb71-175" aria-hidden="true" tabindex="-1"></a><span class="fu">set.seed</span>(<span class="dv">1</span>)</span>
<span id="cb71-176"><a href="#cb71-176" aria-hidden="true" tabindex="-1"></a>bgap <span class="sc">%&gt;%</span> </span>
<span id="cb71-177"><a href="#cb71-177" aria-hidden="true" tabindex="-1"></a>  <span class="fu">nrow</span>() <span class="sc">%&gt;%</span> </span>
<span id="cb71-178"><a href="#cb71-178" aria-hidden="true" tabindex="-1"></a>  <span class="fu">multiply_by</span>(<span class="fl">0.7</span>) <span class="sc">%&gt;%</span> </span>
<span id="cb71-179"><a href="#cb71-179" aria-hidden="true" tabindex="-1"></a>  <span class="fu">round</span>() <span class="ot">-&gt;</span> training_set_size</span>
<span id="cb71-180"><a href="#cb71-180" aria-hidden="true" tabindex="-1"></a>train_indices <span class="ot">&lt;-</span> <span class="fu">sample</span>(<span class="dv">1</span><span class="sc">:</span><span class="fu">nrow</span>(df), training_set_size)</span>
<span id="cb71-181"><a href="#cb71-181" aria-hidden="true" tabindex="-1"></a>train <span class="ot">&lt;-</span> bgap[train_indices,]</span>
<span id="cb71-182"><a href="#cb71-182" aria-hidden="true" tabindex="-1"></a>test <span class="ot">&lt;-</span> bgap[<span class="sc">-</span>train_indices,]</span>
<span id="cb71-183"><a href="#cb71-183" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb71-184"><a href="#cb71-184" aria-hidden="true" tabindex="-1"></a><span class="fu">nrow</span>(train)</span>
<span id="cb71-185"><a href="#cb71-185" aria-hidden="true" tabindex="-1"></a><span class="fu">nrow</span>(test)</span>
<span id="cb71-186"><a href="#cb71-186" aria-hidden="true" tabindex="-1"></a><span class="fu">head</span>(train)</span>
<span id="cb71-187"><a href="#cb71-187" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb71-188"><a href="#cb71-188" aria-hidden="true" tabindex="-1"></a>As a reminder, pregnancies, age, and BMI are all right skewed. So, we will use the logarithm of those variables in our regressions. </span>
<span id="cb71-189"><a href="#cb71-189" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb71-192"><a href="#cb71-192" aria-hidden="true" tabindex="-1"></a><span class="in">```{r}</span></span>
<span id="cb71-193"><a href="#cb71-193" aria-hidden="true" tabindex="-1"></a><span class="co">#Model 1 using all independent variables</span></span>
<span id="cb71-194"><a href="#cb71-194" aria-hidden="true" tabindex="-1"></a>all_var <span class="ot">&lt;-</span> <span class="fu">glm</span>(diabetes <span class="sc">~</span> ., <span class="at">data =</span> train, <span class="at">family =</span> binomial)</span>
<span id="cb71-195"><a href="#cb71-195" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb71-196"><a href="#cb71-196" aria-hidden="true" tabindex="-1"></a><span class="co">#Model 2 using BMI, glucose, and age</span></span>
<span id="cb71-197"><a href="#cb71-197" aria-hidden="true" tabindex="-1"></a>bga <span class="ot">&lt;-</span> <span class="fu">glm</span>(diabetes <span class="sc">~</span> . <span class="sc">-</span>pregnancies, <span class="at">data =</span> train, <span class="at">family =</span> binomial)</span>
<span id="cb71-198"><a href="#cb71-198" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb71-199"><a href="#cb71-199" aria-hidden="true" tabindex="-1"></a><span class="co">#Model 3 using BMI and glucose</span></span>
<span id="cb71-200"><a href="#cb71-200" aria-hidden="true" tabindex="-1"></a>bg <span class="ot">&lt;-</span> <span class="fu">glm</span>(diabetes <span class="sc">~</span> .<span class="sc">-</span>age <span class="sc">-</span>pregnancies, <span class="at">data =</span> train, <span class="at">family =</span> binomial)</span>
<span id="cb71-201"><a href="#cb71-201" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb71-202"><a href="#cb71-202" aria-hidden="true" tabindex="-1"></a><span class="co">#Model 4 using BMI, glucose, age, and an interaction between pregnancies and age.</span></span>
<span id="cb71-203"><a href="#cb71-203" aria-hidden="true" tabindex="-1"></a>ia <span class="ot">&lt;-</span> <span class="fu">glm</span>(diabetes <span class="sc">~</span> glucose <span class="sc">+</span> bmi <span class="sc">+</span> age<span class="sc">*</span>pregnancies, <span class="at">data =</span> train, <span class="at">family =</span> binomial)</span>
<span id="cb71-204"><a href="#cb71-204" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb71-205"><a href="#cb71-205" aria-hidden="true" tabindex="-1"></a><span class="co">#Model 5 with BMI, glucose, and pregnancies (without age)</span></span>
<span id="cb71-206"><a href="#cb71-206" aria-hidden="true" tabindex="-1"></a>bgp <span class="ot">&lt;-</span> <span class="fu">glm</span>(diabetes <span class="sc">~</span> . <span class="sc">-</span>age, <span class="at">data =</span> train, <span class="at">family =</span> binomial)</span>
<span id="cb71-207"><a href="#cb71-207" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb71-208"><a href="#cb71-208" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb71-209"><a href="#cb71-209" aria-hidden="true" tabindex="-1"></a>Our hypothesis involves the BMI, glucose, and age variables. First we can take a look at them individually. </span>
<span id="cb71-210"><a href="#cb71-210" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb71-213"><a href="#cb71-213" aria-hidden="true" tabindex="-1"></a><span class="in">```{r}</span></span>
<span id="cb71-214"><a href="#cb71-214" aria-hidden="true" tabindex="-1"></a><span class="co">#Generalized linear model can be best for predicting categorical outcome</span></span>
<span id="cb71-215"><a href="#cb71-215" aria-hidden="true" tabindex="-1"></a><span class="co">#Regression model on BMI</span></span>
<span id="cb71-216"><a href="#cb71-216" aria-hidden="true" tabindex="-1"></a>mbmi <span class="ot">&lt;-</span> <span class="fu">glm</span>(diabetes <span class="sc">~</span> bmi, <span class="at">data =</span> train)</span>
<span id="cb71-217"><a href="#cb71-217" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(mbmi)</span>
<span id="cb71-218"><a href="#cb71-218" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb71-219"><a href="#cb71-219" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(<span class="at">data =</span> train, <span class="fu">aes</span>(<span class="at">x =</span>bmi, <span class="at">y =</span> diabetes)) <span class="sc">+</span></span>
<span id="cb71-220"><a href="#cb71-220" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_point</span>() <span class="sc">+</span></span>
<span id="cb71-221"><a href="#cb71-221" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_smooth</span>(<span class="at">method =</span> <span class="st">'lm'</span>)</span>
<span id="cb71-222"><a href="#cb71-222" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb71-223"><a href="#cb71-223" aria-hidden="true" tabindex="-1"></a>Interpretation: The residuals are relatively small. The coefficient estimate suggests that for every 1 unit increase of BMI, the chance of diabetes increases 0.019. The standard errors are small. Our t-values are large compared to our standard error and relatively far from 0. All that, combined with a very small p-value of &lt; 5.15e-11, indicate we can reject the null hypothesis and conclude a relationship between BMI and diabetes. </span>
<span id="cb71-224"><a href="#cb71-224" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb71-227"><a href="#cb71-227" aria-hidden="true" tabindex="-1"></a><span class="in">```{r}</span></span>
<span id="cb71-228"><a href="#cb71-228" aria-hidden="true" tabindex="-1"></a><span class="co">#Regression model on glucose </span></span>
<span id="cb71-229"><a href="#cb71-229" aria-hidden="true" tabindex="-1"></a>mgluc <span class="ot">&lt;-</span> <span class="fu">glm</span>(diabetes <span class="sc">~</span> glucose, <span class="at">data =</span> train)</span>
<span id="cb71-230"><a href="#cb71-230" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(mgluc)</span>
<span id="cb71-231"><a href="#cb71-231" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb71-232"><a href="#cb71-232" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(<span class="at">data =</span> train, <span class="fu">aes</span>(<span class="at">x =</span> glucose, <span class="at">y =</span> diabetes)) <span class="sc">+</span></span>
<span id="cb71-233"><a href="#cb71-233" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_point</span>() <span class="sc">+</span></span>
<span id="cb71-234"><a href="#cb71-234" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_smooth</span>(<span class="at">method =</span> <span class="st">'lm'</span>)</span>
<span id="cb71-235"><a href="#cb71-235" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb71-236"><a href="#cb71-236" aria-hidden="true" tabindex="-1"></a>Interpretation: Interestingly, the values of this regression mirror that of the BMI regression. With a very small p-value, &lt; 2e-16, we can see that the plasma glucose concentrations of the 2 hour oral glucose tolerance test (GGT) are related to our outcome variable, diabetes. This makes sense as GGT is sometimes used as a diagnostic tool for diabetes. </span>
<span id="cb71-237"><a href="#cb71-237" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb71-238"><a href="#cb71-238" aria-hidden="true" tabindex="-1"></a>The similarities is regression model values between BMI and glucose sparked a curiosity. Let's see if BMI and glucose are specifically correlated to one another. </span>
<span id="cb71-241"><a href="#cb71-241" aria-hidden="true" tabindex="-1"></a><span class="in">```{r}</span></span>
<span id="cb71-242"><a href="#cb71-242" aria-hidden="true" tabindex="-1"></a><span class="fu">cor.test</span>(train<span class="sc">$</span>bmi, train<span class="sc">$</span>glucose, <span class="at">method =</span> <span class="st">"pearson"</span>)</span>
<span id="cb71-243"><a href="#cb71-243" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb71-244"><a href="#cb71-244" aria-hidden="true" tabindex="-1"></a>This shows a very small p-value of 8.477e-09, which is well under the significance level alpha = 0.5. However, the correlation coefficient suggests a weak positive correlation. This suggests the variables are only weakly related.</span>
<span id="cb71-245"><a href="#cb71-245" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb71-246"><a href="#cb71-246" aria-hidden="true" tabindex="-1"></a>Let's continue with our regression model hypothesis testing of individual variables. </span>
<span id="cb71-249"><a href="#cb71-249" aria-hidden="true" tabindex="-1"></a><span class="in">```{r}</span></span>
<span id="cb71-250"><a href="#cb71-250" aria-hidden="true" tabindex="-1"></a><span class="co">#Regression model on age</span></span>
<span id="cb71-251"><a href="#cb71-251" aria-hidden="true" tabindex="-1"></a>mage <span class="ot">&lt;-</span> <span class="fu">glm</span>(diabetes <span class="sc">~</span> age, <span class="at">data =</span> train)</span>
<span id="cb71-252"><a href="#cb71-252" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(mage)</span>
<span id="cb71-253"><a href="#cb71-253" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb71-254"><a href="#cb71-254" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(<span class="at">data =</span> train, <span class="fu">aes</span>(<span class="at">x =</span> age, <span class="at">y =</span> diabetes)) <span class="sc">+</span></span>
<span id="cb71-255"><a href="#cb71-255" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_point</span>() <span class="sc">+</span></span>
<span id="cb71-256"><a href="#cb71-256" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_smooth</span>(<span class="at">method =</span> <span class="st">'lm'</span>)</span>
<span id="cb71-257"><a href="#cb71-257" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb71-258"><a href="#cb71-258" aria-hidden="true" tabindex="-1"></a>Interpretation: Similar to the previous variable, age also has small residuals and standard error. It shows a p-value of 1.12e-06, indicating a relationship between age and diabetes. </span>
<span id="cb71-259"><a href="#cb71-259" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb71-260"><a href="#cb71-260" aria-hidden="true" tabindex="-1"></a>The hypothesis that BMI, glucose tolerance results, and age are positively associated with diabetes is true. Next, we can investigate models that could help predict the outcome using these variables. </span>
<span id="cb71-261"><a href="#cb71-261" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb71-262"><a href="#cb71-262" aria-hidden="true" tabindex="-1"></a><span class="fu">## Model Comparisons</span></span>
<span id="cb71-263"><a href="#cb71-263" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb71-264"><a href="#cb71-264" aria-hidden="true" tabindex="-1"></a><span class="fu">### Model 1</span></span>
<span id="cb71-267"><a href="#cb71-267" aria-hidden="true" tabindex="-1"></a><span class="in">```{r}</span></span>
<span id="cb71-268"><a href="#cb71-268" aria-hidden="true" tabindex="-1"></a><span class="co">#Summarize model including BMI, glucose, age, and pregnancies</span></span>
<span id="cb71-269"><a href="#cb71-269" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(all_var)</span>
<span id="cb71-270"><a href="#cb71-270" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb71-271"><a href="#cb71-271" aria-hidden="true" tabindex="-1"></a>We can see with the all variable model that collectively, independent variables including pregnancies, glucose, bmi, dpf and even blood pressure have low p-values. That suggests those variables have a relationship with the outcome variable. We can use AIC as an indicator of model fitness, with this model being 517.97. Let's compare this with the following models.</span>
<span id="cb71-272"><a href="#cb71-272" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb71-273"><a href="#cb71-273" aria-hidden="true" tabindex="-1"></a><span class="fu">### Model 2</span></span>
<span id="cb71-274"><a href="#cb71-274" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb71-277"><a href="#cb71-277" aria-hidden="true" tabindex="-1"></a><span class="in">```{r}</span></span>
<span id="cb71-278"><a href="#cb71-278" aria-hidden="true" tabindex="-1"></a><span class="co">#Summarize BMI, glucose, and age model</span></span>
<span id="cb71-279"><a href="#cb71-279" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(bga)</span>
<span id="cb71-280"><a href="#cb71-280" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb71-281"><a href="#cb71-281" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(train, <span class="fu">aes</span>(<span class="at">x=</span>age, <span class="at">y=</span>bmi, <span class="at">color=</span>glucose)) <span class="sc">+</span> <span class="fu">geom_point</span>() <span class="sc">+</span> <span class="fu">facet_grid</span>(<span class="sc">~</span>diabetes)</span>
<span id="cb71-282"><a href="#cb71-282" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb71-283"><a href="#cb71-283" aria-hidden="true" tabindex="-1"></a>The model looking at BMI, age, and glucose as explanatory variables for diabetes has an AIC of 526.6, which is a worse fit than the all variables model. </span>
<span id="cb71-284"><a href="#cb71-284" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb71-285"><a href="#cb71-285" aria-hidden="true" tabindex="-1"></a><span class="fu">### Model 3 </span></span>
<span id="cb71-286"><a href="#cb71-286" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb71-289"><a href="#cb71-289" aria-hidden="true" tabindex="-1"></a><span class="in">```{r}</span></span>
<span id="cb71-290"><a href="#cb71-290" aria-hidden="true" tabindex="-1"></a><span class="co">#Summarize BMI and glucose model</span></span>
<span id="cb71-291"><a href="#cb71-291" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(bg)</span>
<span id="cb71-292"><a href="#cb71-292" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb71-293"><a href="#cb71-293" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(train, <span class="fu">aes</span>(<span class="at">x=</span>glucose, <span class="at">y=</span>bmi, <span class="at">color=</span>diabetes)) <span class="sc">+</span> <span class="fu">geom_point</span>() <span class="sc">+</span> <span class="fu">facet_grid</span>(<span class="sc">~</span>diabetes)</span>
<span id="cb71-294"><a href="#cb71-294" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb71-295"><a href="#cb71-295" aria-hidden="true" tabindex="-1"></a>This BMI and glucose only model has a worse (higher) AIC, with 536.8, than the 2 previous models. So far, the all variable model appears the best fit. </span>
<span id="cb71-296"><a href="#cb71-296" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb71-297"><a href="#cb71-297" aria-hidden="true" tabindex="-1"></a><span class="fu">### Model 4</span></span>
<span id="cb71-298"><a href="#cb71-298" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb71-301"><a href="#cb71-301" aria-hidden="true" tabindex="-1"></a><span class="in">```{r}</span></span>
<span id="cb71-302"><a href="#cb71-302" aria-hidden="true" tabindex="-1"></a><span class="co">#Summarize model including interaction between age and pregnancies </span></span>
<span id="cb71-303"><a href="#cb71-303" aria-hidden="true" tabindex="-1"></a><span class="co">#This was chosen to see if the impact of age on diabetes is different depending on the number of pregnancies</span></span>
<span id="cb71-304"><a href="#cb71-304" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(ia)</span>
<span id="cb71-305"><a href="#cb71-305" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb71-306"><a href="#cb71-306" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(train, <span class="fu">aes</span>(<span class="at">x=</span>age, <span class="at">y=</span>bmi, <span class="at">color=</span>pregnancies)) <span class="sc">+</span> <span class="fu">geom_point</span>() <span class="sc">+</span> <span class="fu">facet_grid</span>(<span class="sc">~</span>diabetes)</span>
<span id="cb71-307"><a href="#cb71-307" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb71-308"><a href="#cb71-308" aria-hidden="true" tabindex="-1"></a>With an AIC of 510.41, this model appears to be the best fit model of those we have compared. This indicated there is an interaction between age and pregnancies that has a relationship with the outcome variable. </span>
<span id="cb71-309"><a href="#cb71-309" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb71-310"><a href="#cb71-310" aria-hidden="true" tabindex="-1"></a><span class="fu">### Model 5 </span></span>
<span id="cb71-311"><a href="#cb71-311" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb71-314"><a href="#cb71-314" aria-hidden="true" tabindex="-1"></a><span class="in">```{r}</span></span>
<span id="cb71-315"><a href="#cb71-315" aria-hidden="true" tabindex="-1"></a><span class="co">#Summarize model including without age</span></span>
<span id="cb71-316"><a href="#cb71-316" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(bgp)</span>
<span id="cb71-317"><a href="#cb71-317" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb71-318"><a href="#cb71-318" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(train, <span class="fu">aes</span>(<span class="at">x=</span>pregnancies, <span class="at">y=</span>bmi, <span class="at">color=</span>glucose)) <span class="sc">+</span> <span class="fu">geom_point</span>() <span class="sc">+</span> <span class="fu">facet_grid</span>(<span class="sc">~</span>diabetes)</span>
<span id="cb71-319"><a href="#cb71-319" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb71-320"><a href="#cb71-320" aria-hidden="true" tabindex="-1"></a>Removing age entirely increased the AIC of this model. So, the interaction model seems to be the best fit. That is, model 4 which includes BMI and glucose and controls for an interaction between age and pregnancy has the best fit of all models tested. </span>
<span id="cb71-321"><a href="#cb71-321" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb71-322"><a href="#cb71-322" aria-hidden="true" tabindex="-1"></a>We can use ANOVA to analyze the table of deviance of our regression model. </span>
<span id="cb71-323"><a href="#cb71-323" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb71-326"><a href="#cb71-326" aria-hidden="true" tabindex="-1"></a><span class="in">```{r}</span></span>
<span id="cb71-327"><a href="#cb71-327" aria-hidden="true" tabindex="-1"></a><span class="co">#ANOVA test on interaction model 4</span></span>
<span id="cb71-328"><a href="#cb71-328" aria-hidden="true" tabindex="-1"></a><span class="fu">anova</span>(ia, <span class="at">test =</span> <span class="st">"Chisq"</span>)</span>
<span id="cb71-329"><a href="#cb71-329" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb71-330"><a href="#cb71-330" aria-hidden="true" tabindex="-1"></a>All of our variables have small p-values and appear good predictors of the diabetes outcome, with the exception of age. However, age is needed for the interaction variable. </span>
<span id="cb71-331"><a href="#cb71-331" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb71-332"><a href="#cb71-332" aria-hidden="true" tabindex="-1"></a>Let's check one more thing to ensure we have a good fit. </span>
<span id="cb71-335"><a href="#cb71-335" aria-hidden="true" tabindex="-1"></a><span class="in">```{r}</span></span>
<span id="cb71-336"><a href="#cb71-336" aria-hidden="true" tabindex="-1"></a><span class="co">#Check pseudo R2 for interaction model</span></span>
<span id="cb71-337"><a href="#cb71-337" aria-hidden="true" tabindex="-1"></a><span class="fu">pR2</span>(ia)</span>
<span id="cb71-338"><a href="#cb71-338" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb71-339"><a href="#cb71-339" aria-hidden="true" tabindex="-1"></a>With a McFadden R-squared of 0.27, model 4 can be considered an excellent fit. </span>
<span id="cb71-340"><a href="#cb71-340" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb71-341"><a href="#cb71-341" aria-hidden="true" tabindex="-1"></a><span class="fu">## Diagnostics</span></span>
<span id="cb71-342"><a href="#cb71-342" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb71-343"><a href="#cb71-343" aria-hidden="true" tabindex="-1"></a>To test the model, the next step is to apply it to the test subset of data. </span>
<span id="cb71-344"><a href="#cb71-344" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb71-347"><a href="#cb71-347" aria-hidden="true" tabindex="-1"></a><span class="in">```{r}</span></span>
<span id="cb71-348"><a href="#cb71-348" aria-hidden="true" tabindex="-1"></a><span class="co">#Apply model to test data</span></span>
<span id="cb71-349"><a href="#cb71-349" aria-hidden="true" tabindex="-1"></a>fitted.results <span class="ot">&lt;-</span> <span class="fu">predict</span>(ia ,test,<span class="at">type=</span><span class="st">'response'</span>)</span>
<span id="cb71-350"><a href="#cb71-350" aria-hidden="true" tabindex="-1"></a>fitted.results <span class="ot">&lt;-</span> <span class="fu">ifelse</span>(fitted.results <span class="sc">&gt;</span> <span class="fl">0.5</span>,<span class="dv">1</span>,<span class="dv">0</span>)</span>
<span id="cb71-351"><a href="#cb71-351" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb71-352"><a href="#cb71-352" aria-hidden="true" tabindex="-1"></a>pred <span class="ot">&lt;-</span> <span class="fu">mean</span>(fitted.results <span class="sc">!=</span> test<span class="sc">$</span>diabetes)</span>
<span id="cb71-353"><a href="#cb71-353" aria-hidden="true" tabindex="-1"></a>output <span class="ot">&lt;-</span> <span class="fu">cbind</span>(test, fitted.results)</span>
<span id="cb71-354"><a href="#cb71-354" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb71-355"><a href="#cb71-355" aria-hidden="true" tabindex="-1"></a><span class="fu">print</span>(<span class="fu">paste</span>(<span class="st">'Accuracy'</span>,<span class="dv">1</span><span class="sc">-</span>pred))</span>
<span id="cb71-356"><a href="#cb71-356" aria-hidden="true" tabindex="-1"></a><span class="fu">head</span>(output)</span>
<span id="cb71-357"><a href="#cb71-357" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb71-358"><a href="#cb71-358" aria-hidden="true" tabindex="-1"></a>Testing the interaction model on the test data produces the correct outcome 79% of the time. </span>
<span id="cb71-359"><a href="#cb71-359" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb71-362"><a href="#cb71-362" aria-hidden="true" tabindex="-1"></a><span class="in">```{r}</span></span>
<span id="cb71-363"><a href="#cb71-363" aria-hidden="true" tabindex="-1"></a><span class="co">#Diagnostic plot of model</span></span>
<span id="cb71-364"><a href="#cb71-364" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(ia)</span>
<span id="cb71-365"><a href="#cb71-365" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb71-366"><a href="#cb71-366" aria-hidden="true" tabindex="-1"></a>**Residuals vs Fitted**: The residuals have 2 distinct patterns of behavior. They start at close to 0 and taper off to a negative slope. Another group of residuals starts large and tapers on a negative slope toward 0. </span>
<span id="cb71-367"><a href="#cb71-367" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb71-368"><a href="#cb71-368" aria-hidden="true" tabindex="-1"></a>**Normal Q-Q**: The Q-Q plot, which indicates level of asymmetry, tells us our data is not a normal distribution. It appears to have a right tail (see the points drifting from the line at the top), which aligns with our individual variable histogram interpretations. It follows that a model combining variables with right skews may also be skewed to the right. However, it also has values away from the line on the bottom left, away from the intercept. This suggests our model also includes a left tail. This distribution seems to have "fat tails."</span>
<span id="cb71-369"><a href="#cb71-369" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb71-370"><a href="#cb71-370" aria-hidden="true" tabindex="-1"></a>**Scale-Location**: This plots the fitted values of the model along the x-axis and the square root of the standardized residuals along the y-axis. The red line does roughly travel horizontal across the plot. However, there is a clear X pattern among residuals. This suggests our model has heteroscedasticity, which is not ideal. </span>
<span id="cb71-371"><a href="#cb71-371" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb71-372"><a href="#cb71-372" aria-hidden="true" tabindex="-1"></a>**Residuals vs Leverage**: The points on this graph all fall within Cook's distance, indicating there are not any influential points in our regression model. </span>
<span id="cb71-373"><a href="#cb71-373" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb71-374"><a href="#cb71-374" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb71-375"><a href="#cb71-375" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb71-376"><a href="#cb71-376" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb71-377"><a href="#cb71-377" aria-hidden="true" tabindex="-1"></a>*Plan to work on fixing the heteroscedasticity by log transforming BMI, pregnancies, and age when those variables are included in models because they are right skewed data. However, it is taking time figuring out how to do a multiple logistics regression without errors..*</span>
</code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div></div></div></div></div>
</div> <!-- /content -->



</body></html>