{
  "hash": "e051bb0a8af8d57f73c1bada539d905c",
  "result": {
    "markdown": "---\ntitle: \"Homework 4\"\nauthor: \"Saaradhaa M\"\ndate: \"11/14/2022\"\nformat: \n  html:\n    df-print: paged\n    toc: true\n    code-copy: true\n    code-tools: true\n    css: \"styles.css\"\ncategories:\n  - hw4\n---\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(tidyverse)\nlibrary(alr4)\nlibrary(smss)\nlibrary(interactions)\n\nknitr::opts_chunk$set(echo = TRUE, warning = FALSE, message = FALSE)\n```\n:::\n\n\n# Qn 1A\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# predicted price.\nyhat <- -10536 + 53.8*1240 + 2.84*18000\n\n# residual.\n145000-yhat\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 37704\n```\n:::\n:::\n\n\nThe model under-predicts by \\$37,704.\n\n# Qn 1B\n\nIt is predicted to increase by \\~\\$53.80. This is because the effects of `x1` and `x2` on `y` are independent of one another, and there is no interaction between them.\n\n# Qn 1C\n\n\n::: {.cell}\n\n```{.r .cell-code}\n53.8/2.84\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 18.94366\n```\n:::\n:::\n\n\nIt would need to increase by \\~19x.\n\n# Qn 2A\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# load dataset.\ndata(salary)\n\n# run model.\nsummary(lm(salary ~ sex, salary))\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n\nCall:\nlm(formula = salary ~ sex, data = salary)\n\nResiduals:\n    Min      1Q  Median      3Q     Max \n-8602.8 -4296.6  -100.8  3513.1 16687.9 \n\nCoefficients:\n            Estimate Std. Error t value Pr(>|t|)    \n(Intercept)    24697        938  26.330   <2e-16 ***\nsexFemale      -3340       1808  -1.847   0.0706 .  \n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n\nResidual standard error: 5782 on 50 degrees of freedom\nMultiple R-squared:  0.0639,\tAdjusted R-squared:  0.04518 \nF-statistic: 3.413 on 1 and 50 DF,  p-value: 0.0706\n```\n:::\n:::\n\n\nThe mean salary for men and women does not differ, *p* = 0.07 (i.e., it is the same).\n\n# Qn 2B\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# run model.\nmodel2B <- lm(salary ~ ., salary)\nsummary(model2B)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n\nCall:\nlm(formula = salary ~ ., data = salary)\n\nResiduals:\n    Min      1Q  Median      3Q     Max \n-4045.2 -1094.7  -361.5   813.2  9193.1 \n\nCoefficients:\n            Estimate Std. Error t value Pr(>|t|)    \n(Intercept) 15746.05     800.18  19.678  < 2e-16 ***\ndegreePhD    1388.61    1018.75   1.363    0.180    \nrankAssoc    5292.36    1145.40   4.621 3.22e-05 ***\nrankProf    11118.76    1351.77   8.225 1.62e-10 ***\nsexFemale    1166.37     925.57   1.260    0.214    \nyear          476.31      94.91   5.018 8.65e-06 ***\nysdeg        -124.57      77.49  -1.608    0.115    \n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n\nResidual standard error: 2398 on 45 degrees of freedom\nMultiple R-squared:  0.855,\tAdjusted R-squared:  0.8357 \nF-statistic: 44.24 on 6 and 45 DF,  p-value: < 2.2e-16\n```\n:::\n\n```{.r .cell-code}\n# get confidence interval.\nconfint(model2B)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n                 2.5 %      97.5 %\n(Intercept) 14134.4059 17357.68946\ndegreePhD    -663.2482  3440.47485\nrankAssoc    2985.4107  7599.31080\nrankProf     8396.1546 13841.37340\nsexFemale    -697.8183  3030.56452\nyear          285.1433   667.47476\nysdeg        -280.6397    31.49105\n```\n:::\n:::\n\n\nSex is still not a significant predictor of salary. The 95% CI for difference in salary between males and females is approx. -698 to 3031.\n\n# Qn 2C\n\n`rank` and `year` are significant predictors of salary, while all others were not.\n\nBoth `rank` and `year` positively predict salary: Associate Professors and full Professors were likely to earn quite a bit more than Assistant Professors, while professors with more years in their current rank also earned more.\n\nLooking at the magnitude of the coefficients, `rank` has a greater impact on salary than `year` does.\n\n# Qn 2D\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# change baseline category.\nsalary$rank <- relevel(salary$rank, ref = 'Assoc')\n\n# re-run model.\nmodel2D <- lm(salary ~ ., salary)\nsummary(model2D)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n\nCall:\nlm(formula = salary ~ ., data = salary)\n\nResiduals:\n    Min      1Q  Median      3Q     Max \n-4045.2 -1094.7  -361.5   813.2  9193.1 \n\nCoefficients:\n            Estimate Std. Error t value Pr(>|t|)    \n(Intercept) 21038.41    1109.12  18.969  < 2e-16 ***\ndegreePhD    1388.61    1018.75   1.363    0.180    \nrankAsst    -5292.36    1145.40  -4.621 3.22e-05 ***\nrankProf     5826.40    1012.93   5.752 7.28e-07 ***\nsexFemale    1166.37     925.57   1.260    0.214    \nyear          476.31      94.91   5.018 8.65e-06 ***\nysdeg        -124.57      77.49  -1.608    0.115    \n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n\nResidual standard error: 2398 on 45 degrees of freedom\nMultiple R-squared:  0.855,\tAdjusted R-squared:  0.8357 \nF-statistic: 44.24 on 6 and 45 DF,  p-value: < 2.2e-16\n```\n:::\n:::\n\n\nWe can see that `rank` now both negatively and positively predicts `salary`. Specifically, Assistant Professors earn less than Associate Professors do, at the same magnitude that was observed in `model1` (approx. \\~\\$5292).\n\n# Qn 2E\n\n\n::: {.cell}\n\n```{.r .cell-code}\nmodel2E <- lm(salary ~ . - rank, salary)\nsummary(model2E)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n\nCall:\nlm(formula = salary ~ . - rank, data = salary)\n\nResiduals:\n    Min      1Q  Median      3Q     Max \n-8146.9 -2186.9  -491.5  2279.1 11186.6 \n\nCoefficients:\n            Estimate Std. Error t value Pr(>|t|)    \n(Intercept) 17183.57    1147.94  14.969  < 2e-16 ***\ndegreePhD   -3299.35    1302.52  -2.533 0.014704 *  \nsexFemale   -1286.54    1313.09  -0.980 0.332209    \nyear          351.97     142.48   2.470 0.017185 *  \nysdeg         339.40      80.62   4.210 0.000114 ***\n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n\nResidual standard error: 3744 on 47 degrees of freedom\nMultiple R-squared:  0.6312,\tAdjusted R-squared:  0.5998 \nF-statistic: 20.11 on 4 and 47 DF,  p-value: 1.048e-09\n```\n:::\n:::\n\n\nExcluding `rank`, both adjusted R^2^ and the overall F-statistic drop. `degree` and `ysdeg` are now significant as well. Curiously, those with a PhD earn less than those with an MS. As years since highest degree increases, so does salary.\n\n# Qn 2F\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# create new variable.\nsalary <- mutate(salary, HireTime = case_when(ysdeg <= 15 ~ \"1\", ysdeg > 15 ~ \"0\"))\nsalary$HireTime <- as.numeric(salary$HireTime)\n\n# run correlation matrix to check for multicollinearity. it's important to do so especially because HireTime is derived from ysdeg, so we would expect them to be highly correlated.\nsubset <- salary %>% select(year, ysdeg, HireTime)\nmatrix <- cor(subset, use=\"complete.obs\")\n```\n:::\n\n\nI would remove `ysdeg` from the regression model since it is highly correlated with `HireTime`, *r* = 0.84.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nmodel2F <- lm(salary ~ . - ysdeg, salary)\nsummary(model2F)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n\nCall:\nlm(formula = salary ~ . - ysdeg, data = salary)\n\nResiduals:\n    Min      1Q  Median      3Q     Max \n-3403.3 -1387.0  -167.0   528.2  9233.8 \n\nCoefficients:\n            Estimate Std. Error t value Pr(>|t|)    \n(Intercept) 18301.04    1301.36  14.063  < 2e-16 ***\ndegreePhD     818.93     797.48   1.027   0.3100    \nrankAsst    -4972.66     997.17  -4.987 9.61e-06 ***\nrankProf     6124.28    1028.58   5.954 3.65e-07 ***\nsexFemale     907.14     840.54   1.079   0.2862    \nyear          434.85      78.89   5.512 1.65e-06 ***\nHireTime     2163.46    1072.04   2.018   0.0496 *  \n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n\nResidual standard error: 2362 on 45 degrees of freedom\nMultiple R-squared:  0.8594,\tAdjusted R-squared:  0.8407 \nF-statistic: 45.86 on 6 and 45 DF,  p-value: < 2.2e-16\n```\n:::\n:::\n\n\nYes, those hired by the new Dean are making more, *p* = .05.\n\n# Qn 3A\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# load dataset.\ndata(house.selling.price)\n\n# run model.\nmodel3A <- lm(Price ~ Size + New, house.selling.price)\nsummary(model3A)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n\nCall:\nlm(formula = Price ~ Size + New, data = house.selling.price)\n\nResiduals:\n    Min      1Q  Median      3Q     Max \n-205102  -34374   -5778   18929  163866 \n\nCoefficients:\n              Estimate Std. Error t value Pr(>|t|)    \n(Intercept) -40230.867  14696.140  -2.738  0.00737 ** \nSize           116.132      8.795  13.204  < 2e-16 ***\nNew          57736.283  18653.041   3.095  0.00257 ** \n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n\nResidual standard error: 53880 on 97 degrees of freedom\nMultiple R-squared:  0.7226,\tAdjusted R-squared:  0.7169 \nF-statistic: 126.3 on 2 and 97 DF,  p-value: < 2.2e-16\n```\n:::\n:::\n\n\nBoth `Size` and `New` significantly positively predict selling price. As each predictor goes up by 1 unit, selling price rises by \\$116 and \\$57,736 respectively.\n\n# Qn 3B\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# new homes.\nnew <- house.selling.price %>% filter(New == 1)\nmodel3B1 <- lm(Price ~ Size, new)\nsummary(model3B1)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n\nCall:\nlm(formula = Price ~ Size, data = new)\n\nResiduals:\n   Min     1Q Median     3Q    Max \n-78606 -16092   -987  20068  76140 \n\nCoefficients:\n              Estimate Std. Error t value Pr(>|t|)    \n(Intercept) -100755.31   42513.73  -2.370   0.0419 *  \nSize            166.35      17.09   9.735 4.47e-06 ***\n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n\nResidual standard error: 45500 on 9 degrees of freedom\nMultiple R-squared:  0.9133,\tAdjusted R-squared:  0.9036 \nF-statistic: 94.76 on 1 and 9 DF,  p-value: 4.474e-06\n```\n:::\n\n```{.r .cell-code}\n# old homes.\nold <- house.selling.price %>% filter(New == 0)\nmodel3B2 <- lm(Price ~ Size, old)\nsummary(model3B2)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n\nCall:\nlm(formula = Price ~ Size, data = old)\n\nResiduals:\n    Min      1Q  Median      3Q     Max \n-175748  -29155   -7297   14159  192519 \n\nCoefficients:\n              Estimate Std. Error t value Pr(>|t|)    \n(Intercept) -22227.808  15708.186  -1.415    0.161    \nSize           104.438      9.538  10.950   <2e-16 ***\n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n\nResidual standard error: 52620 on 87 degrees of freedom\nMultiple R-squared:  0.5795,\tAdjusted R-squared:  0.5747 \nF-statistic: 119.9 on 1 and 87 DF,  p-value: < 2.2e-16\n```\n:::\n:::\n\n\nSize significantly positively predicts price for both new and old houses, but by a greater magnitude for new houses:\n\n-   New: E(Price) = 166\\*Size - 100,755\n\n    -   Adjusted R^2^ for the model is also much higher (0.90 vs. 0.57).\n\n-   Old: E(Price) = 104\\*Size - 22,228\n\n# Qn 3C\n\n-   New: E(Price) = 166\\*3000 - 100,755 = \\$397,245\n\n-   Old: E(Price) = 104\\*3000 - 22,228 = \\$289,772\n\n# Qn 3D\n\n\n::: {.cell}\n\n```{.r .cell-code}\nmodel3D <- lm(Price ~ Size*New, house.selling.price)\nsummary(model3D)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n\nCall:\nlm(formula = Price ~ Size * New, data = house.selling.price)\n\nResiduals:\n    Min      1Q  Median      3Q     Max \n-175748  -28979   -6260   14693  192519 \n\nCoefficients:\n              Estimate Std. Error t value Pr(>|t|)    \n(Intercept) -22227.808  15521.110  -1.432  0.15536    \nSize           104.438      9.424  11.082  < 2e-16 ***\nNew         -78527.502  51007.642  -1.540  0.12697    \nSize:New        61.916     21.686   2.855  0.00527 ** \n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n\nResidual standard error: 52000 on 96 degrees of freedom\nMultiple R-squared:  0.7443,\tAdjusted R-squared:  0.7363 \nF-statistic: 93.15 on 3 and 96 DF,  p-value: < 2.2e-16\n```\n:::\n\n```{.r .cell-code}\ninteract_plot(model3D, pred = Size, modx = New)\n```\n\n::: {.cell-output-display}\n![](HW4_Saaradhaa_files/figure-html/3D-1.png){width=672}\n:::\n:::\n\n\n`Size` and `New` positively interact to affect `Price`, such that `New` amplifies the positive relationship between `Size` and `Price`.\n\n# Qn 3E\n\nReferring to `model3D` above:\n\n-   New: -22,228 + 104\\*Size - 78,528 + 62\\*Size = 166\\*Size - 100,756\n\n-   Old: 104\\*Size - 22,228\n\n# Qn 3F\n\n-   New: 166\\*3000 -100,756 = \\$397,244\n\n-   Old: 104\\*3000 - 22,228 = \\$289,772\n\n# Qn 3G\n\n-   New: 166\\*1500 - 100,756 = \\$148,244\n\n-   Old: 104\\*1500 - 22,228 = \\$133,772\n\nAs size of home goes up, the difference in predicted selling prices between old and new homes becomes larger.\n\n# Qn 3H\n\nQuestions 3F and 3G demonstrate that `size` affects the relationship between `new` and `price`, which reveals some type of dependency between the predictors. Hence, the model with interaction represents the relationships between `size`, `new` and `price` better.\n",
    "supporting": [
      "HW4_Saaradhaa_files"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {
      "include-in-header": [
        "<link href=\"../site_libs/pagedtable-1.1/css/pagedtable.css\" rel=\"stylesheet\" />\n<script src=\"../site_libs/pagedtable-1.1/js/pagedtable.js\"></script>\n"
      ]
    },
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}