{
  "hash": "7eb2e2f6518e490e4e52faa7fb625ab6",
  "result": {
    "markdown": "---\ntitle: \"Final Project Submission 2\"\nauthor: \"Kaushika Potluri\"\ndesription: \"Final Project Submission 2\"\ndate: \"11/11/2022\"\nformat:\n  html:\n    toc: true\n    code-fold: true\n    code-copy: true\n    code-tools: true\neditor: \n  markdown: \n    wrap: sentence\n---\n\n\n#Introduction \nThe research question that I have been interested in is the impact of education about sex and fertility for women and how that changes the fertility rate.\nWomen's education raises the value of time spent working in the market and, as a result, the opportunity cost of spending time to take care of their child seems less.\nAcross time and places, there is a clear negative link between women's education and fertility, although its meaning is ambiguous.\nWomen's level of education may impact fertility through its effects on children's health, the number of children desired, and women's ability to give birth and understanding of various birth control options.\nEach of these are influenced by local, institutional, and national circumstances.\nTheir relative importance may fluctuate as a society develops economically.\nWe analyse the education--fertility relationship by using data on women from Botswana.\nA realistic quantification of such a relationship can be problematic for various reasons.\nFirst, factors such as motivation and ability are associated with fertility and education but cannot be observed and as a consequence cannot be included in the model.\n\n::: callout-tip\n## Research Question\n\nDoes education affect the rate of fertility in Women?\nWhat other factors influence rate of fertility in Women?\n:::\n\n# Hypothesis\n\n::: callout-note\nHo : β1 = β2 = ... = βp-1 = 0\n\nH1 : βj ≠ 0, for at least one value of j\n\nOR\n\nHo : Variances equal, model is significant.\n\nH1 : Variances not equal, model is not significant.\n:::\n\nSome measure of access to birth control could be useful if it varied by region.\nOften, policy changes in the advertisement or availability of contraceptives can be found.\nBut there is no region information(parameters) in our data set.\n\n## Loading in packages:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(readr)\nlibrary(tidyverse)\n```\n\n::: {.cell-output .cell-output-stderr}\n```\n── Attaching packages ─────────────────────────────────────── tidyverse 1.3.2 ──\n✔ ggplot2 3.4.0      ✔ dplyr   1.0.10\n✔ tibble  3.1.8      ✔ stringr 1.4.1 \n✔ tidyr   1.2.1      ✔ forcats 0.5.2 \n✔ purrr   0.3.5      \n── Conflicts ────────────────────────────────────────── tidyverse_conflicts() ──\n✖ dplyr::filter() masks stats::filter()\n✖ dplyr::lag()    masks stats::lag()\n```\n:::\n\n```{.r .cell-code}\nlibrary(ggplot2)\nlibrary(dplyr)\nlibrary(readxl)\nlibrary(DataExplorer)\nlibrary(summarytools)\n```\n\n::: {.cell-output .cell-output-stderr}\n```\n\nAttaching package: 'summarytools'\n\nThe following object is masked from 'package:tibble':\n\n    view\n```\n:::\n\n```{.r .cell-code}\nlibrary(lmtest)\n```\n\n::: {.cell-output .cell-output-stderr}\n```\nLoading required package: zoo\n\nAttaching package: 'zoo'\n\nThe following objects are masked from 'package:base':\n\n    as.Date, as.Date.numeric\n```\n:::\n\n```{.r .cell-code}\nlibrary(car)\n```\n\n::: {.cell-output .cell-output-stderr}\n```\nLoading required package: carData\n\nAttaching package: 'car'\n\nThe following object is masked from 'package:dplyr':\n\n    recode\n\nThe following object is masked from 'package:purrr':\n\n    some\n```\n:::\n\n```{.r .cell-code}\nlibrary(reshape)\n```\n\n::: {.cell-output .cell-output-stderr}\n```\n\nAttaching package: 'reshape'\n\nThe following object is masked from 'package:dplyr':\n\n    rename\n\nThe following objects are masked from 'package:tidyr':\n\n    expand, smiths\n```\n:::\n\n```{.r .cell-code}\nlibrary(sandwich)\n```\n:::\n\n\n## Reading in Data:\n\nThe data was acquired from Professor Sander's article that he used.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nWomendata <-  read.csv(\"_data/data.csv\")\n```\n:::\n\n\n| Variable    | Description of Variables       |\n|-------------|--------------------------------|\n| children    | number of living children      |\n| education   | years of education             |\n| electricity | equals 1 if has electricity    |\n| tv          | equals 1 if has tv             |\n| urban       | equals 1 if live in urban area |\n| evermarr    | equals 1 if ever married       |\n| radio       | equals 1 if has radio          |\n| bicycle     | equals 1 if has bicycle        |\n| knowmeth    | Knows how to use birth control |\n| usemeth     | Has ever used birth control    |\n| age         | age in years                   |\n| firsthalf   | born in first half of year     |\n\n## Descriptive Statistics\n\n\n::: {.cell}\n\n```{.r .cell-code}\nsummary(Womendata)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n       X           mnthborn         yearborn          age       \n Min.   :   1   Min.   : 1.000   Min.   :38.00   Min.   :15.00  \n 1st Qu.:1091   1st Qu.: 3.000   1st Qu.:55.00   1st Qu.:20.00  \n Median :2181   Median : 6.000   Median :62.00   Median :26.00  \n Mean   :2181   Mean   : 6.331   Mean   :60.43   Mean   :27.41  \n 3rd Qu.:3271   3rd Qu.: 9.000   3rd Qu.:68.00   3rd Qu.:33.00  \n Max.   :4361   Max.   :12.000   Max.   :73.00   Max.   :49.00  \n                                                                \n    electric          radio              tv             bicycle      \n Min.   :0.0000   Min.   :0.0000   Min.   :0.00000   Min.   :0.0000  \n 1st Qu.:0.0000   1st Qu.:0.0000   1st Qu.:0.00000   1st Qu.:0.0000  \n Median :0.0000   Median :1.0000   Median :0.00000   Median :0.0000  \n Mean   :0.1402   Mean   :0.7018   Mean   :0.09291   Mean   :0.2758  \n 3rd Qu.:0.0000   3rd Qu.:1.0000   3rd Qu.:0.00000   3rd Qu.:1.0000  \n Max.   :1.0000   Max.   :1.0000   Max.   :1.00000   Max.   :1.0000  \n NA's   :3        NA's   :2        NA's   :2         NA's   :3       \n      educ             ceb            agefbrth        children     \n Min.   : 0.000   Min.   : 0.000   Min.   :10.00   Min.   : 0.000  \n 1st Qu.: 3.000   1st Qu.: 1.000   1st Qu.:17.00   1st Qu.: 0.000  \n Median : 7.000   Median : 2.000   Median :19.00   Median : 2.000  \n Mean   : 5.856   Mean   : 2.442   Mean   :19.01   Mean   : 2.268  \n 3rd Qu.: 8.000   3rd Qu.: 4.000   3rd Qu.:20.00   3rd Qu.: 4.000  \n Max.   :20.000   Max.   :13.000   Max.   :38.00   Max.   :13.000  \n                                   NA's   :1088                    \n    knowmeth         usemeth          monthfm          yearfm     \n Min.   :0.0000   Min.   :0.0000   Min.   : 1.00   Min.   :50.00  \n 1st Qu.:1.0000   1st Qu.:0.0000   1st Qu.: 3.00   1st Qu.:72.00  \n Median :1.0000   Median :1.0000   Median : 6.00   Median :78.00  \n Mean   :0.9633   Mean   :0.5776   Mean   : 6.27   Mean   :76.91  \n 3rd Qu.:1.0000   3rd Qu.:1.0000   3rd Qu.: 9.00   3rd Qu.:83.00  \n Max.   :1.0000   Max.   :1.0000   Max.   :12.00   Max.   :88.00  \n NA's   :7        NA's   :71       NA's   :2282    NA's   :2282   \n     agefm          idlnchld          heduc            agesq       \n Min.   :10.00   Min.   : 0.000   Min.   : 0.000   Min.   : 225.0  \n 1st Qu.:17.00   1st Qu.: 3.000   1st Qu.: 0.000   1st Qu.: 400.0  \n Median :20.00   Median : 4.000   Median : 6.000   Median : 676.0  \n Mean   :20.69   Mean   : 4.616   Mean   : 5.145   Mean   : 826.5  \n 3rd Qu.:23.00   3rd Qu.: 6.000   3rd Qu.: 8.000   3rd Qu.:1089.0  \n Max.   :46.00   Max.   :20.000   Max.   :20.000   Max.   :2401.0  \n NA's   :2282    NA's   :120      NA's   :2405                     \n     urban           urb_educ          spirit          protest      \n Min.   :0.0000   Min.   : 0.000   Min.   :0.0000   Min.   :0.0000  \n 1st Qu.:0.0000   1st Qu.: 0.000   1st Qu.:0.0000   1st Qu.:0.0000  \n Median :1.0000   Median : 0.000   Median :0.0000   Median :0.0000  \n Mean   :0.5166   Mean   : 3.469   Mean   :0.4222   Mean   :0.2277  \n 3rd Qu.:1.0000   3rd Qu.: 7.000   3rd Qu.:1.0000   3rd Qu.:0.0000  \n Max.   :1.0000   Max.   :20.000   Max.   :1.0000   Max.   :1.0000  \n                                                                    \n    catholic         frsthalf          educ0           evermarr     \n Min.   :0.0000   Min.   :0.0000   Min.   :0.0000   Min.   :0.0000  \n 1st Qu.:0.0000   1st Qu.:0.0000   1st Qu.:0.0000   1st Qu.:0.0000  \n Median :0.0000   Median :1.0000   Median :0.0000   Median :0.0000  \n Mean   :0.1025   Mean   :0.5405   Mean   :0.2078   Mean   :0.4767  \n 3rd Qu.:0.0000   3rd Qu.:1.0000   3rd Qu.:0.0000   3rd Qu.:1.0000  \n Max.   :1.0000   Max.   :1.0000   Max.   :1.0000   Max.   :1.0000  \n                                                                    \n```\n:::\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\nstr(Womendata)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n'data.frame':\t4361 obs. of  28 variables:\n $ X       : int  1 2 3 4 5 6 7 8 9 10 ...\n $ mnthborn: int  5 1 7 11 5 8 7 9 12 9 ...\n $ yearborn: int  64 56 58 45 45 52 51 70 53 39 ...\n $ age     : int  24 32 30 42 43 36 37 18 34 49 ...\n $ electric: int  1 1 1 1 1 1 1 1 0 1 ...\n $ radio   : int  1 1 0 0 1 0 1 1 1 1 ...\n $ tv      : int  1 1 0 1 1 0 1 1 0 0 ...\n $ bicycle : int  1 1 0 0 1 0 1 1 0 0 ...\n $ educ    : int  12 13 5 4 11 7 16 10 5 4 ...\n $ ceb     : int  0 3 1 3 2 1 4 0 1 0 ...\n $ agefbrth: int  NA 25 27 17 24 26 20 NA 19 NA ...\n $ children: int  0 3 1 2 2 1 4 0 1 0 ...\n $ knowmeth: int  1 1 1 1 1 1 1 1 1 1 ...\n $ usemeth : int  0 1 0 0 1 1 1 1 1 0 ...\n $ monthfm : int  NA 11 6 1 3 11 5 NA 7 11 ...\n $ yearfm  : int  NA 80 83 61 66 76 78 NA 72 61 ...\n $ agefm   : int  NA 24 24 15 20 24 26 NA 18 22 ...\n $ idlnchld: int  2 3 5 3 2 4 4 4 4 4 ...\n $ heduc   : int  NA 12 7 11 14 9 17 NA 3 1 ...\n $ agesq   : int  576 1024 900 1764 1849 1296 1369 324 1156 2401 ...\n $ urban   : int  1 1 1 1 1 1 1 1 1 1 ...\n $ urb_educ: int  12 13 5 4 11 7 16 10 5 4 ...\n $ spirit  : int  0 0 1 0 0 0 0 0 0 1 ...\n $ protest : int  0 0 0 0 1 0 0 0 1 0 ...\n $ catholic: int  0 0 0 0 0 0 1 1 0 0 ...\n $ frsthalf: int  1 1 0 0 1 0 0 0 0 0 ...\n $ educ0   : int  0 0 0 0 0 0 0 0 0 0 ...\n $ evermarr: int  0 1 1 1 1 1 1 0 1 1 ...\n```\n:::\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\nprint(dfSummary(Womendata, varnumbers = FALSE, plain.ascii = FALSE, graph.magnif = 0.30, style = \"grid\", valid.col = FALSE), \n      method = 'render', table.classes = 'table-condensed')\n```\n\n::: {.cell-output-display}\n```{=html}\n<div class=\"container st-container\">\n<h3>Data Frame Summary</h3>\n<h4>Womendata</h4>\n<strong>Dimensions</strong>: 4361 x 28\n  <br/><strong>Duplicates</strong>: 0\n<br/>\n<table class=\"table table-striped table-bordered st-table st-table-striped st-table-bordered st-multiline table-condensed\">\n  <thead>\n    <tr>\n      <th align=\"center\" class=\"st-protect-top-border\"><strong>Variable</strong></th>\n      <th align=\"center\" class=\"st-protect-top-border\"><strong>Stats / Values</strong></th>\n      <th align=\"center\" class=\"st-protect-top-border\"><strong>Freqs (% of Valid)</strong></th>\n      <th align=\"center\" class=\"st-protect-top-border\"><strong>Graph</strong></th>\n      <th align=\"center\" class=\"st-protect-top-border\"><strong>Missing</strong></th>\n    </tr>\n  </thead>\n  <tbody>\n    <tr>\n      <td align=\"left\">X\n[integer]</td>\n      <td align=\"left\" style=\"padding:8;vertical-align:middle\"><table style=\"border-collapse:collapse;border:none;margin:0\"><tr style=\"background-color:transparent\"><td style=\"padding:0;margin:0;border:0\" align=\"left\">Mean (sd) : 2181 (1259.1)</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0;margin:0;border:0\" align=\"left\">min &le; med &le; max:</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0;margin:0;border:0\" align=\"left\">1 &le; 2181 &le; 4361</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0;margin:0;border:0\" align=\"left\">IQR (CV) : 2180 (0.6)</td></tr></table></td>\n      <td align=\"left\" style=\"vertical-align:middle\">4361 distinct values\n(Integer sequence)</td>\n      <td align=\"left\" style=\"vertical-align:middle;padding:0;background-color:transparent;\"><img style=\"border:none;background-color:transparent;padding:0;max-width:max-content;\" src=\"data:image/png;base64, iVBORw0KGgoAAAANSUhEUgAAADcAAAAnCAQAAAABBBhWAAAAAmJLR0QA/4ePzL8AAAAHdElNRQfmDBUAGS1wIe3+AAAAb0lEQVRYw2P8z0BPwERX24a5dSzInGlUjMhsRhgL2VAWVEXhUHolBotUEexgeMfdqHVD1zoWyo3ADqYishsjQpRm1mHPgcM77katG7Vu1LpR60atG7Vu1Lqhbh0jcv+Emj0gBMhCaokxjnaWh6x1APp7EuZZq43lAAAAJXRFWHRkYXRlOmNyZWF0ZQAyMDIyLTEyLTIxVDAwOjI1OjQ1KzAwOjAwIXzASwAAACV0RVh0ZGF0ZTptb2RpZnkAMjAyMi0xMi0yMVQwMDoyNTo0NSswMDowMFAhePcAAAA9dEVYdGljYzpjb3B5cmlnaHQAQ29weXJpZ2h0IDIwMDcgQXBwbGUgSW5jLiwgYWxsIHJpZ2h0cyByZXNlcnZlZC6eZtwpAAAAI3RFWHRpY2M6ZGVzY3JpcHRpb24AR2VuZXJpYyBSR0IgUHJvZmlsZRqnOI4AAAAASUVORK5CYII=\"></td>\n      <td align=\"center\">0\n(0.0%)</td>\n    </tr>\n    <tr>\n      <td align=\"left\">mnthborn\n[integer]</td>\n      <td align=\"left\" style=\"padding:8;vertical-align:middle\"><table style=\"border-collapse:collapse;border:none;margin:0\"><tr style=\"background-color:transparent\"><td style=\"padding:0;margin:0;border:0\" align=\"left\">Mean (sd) : 6.3 (3.3)</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0;margin:0;border:0\" align=\"left\">min &le; med &le; max:</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0;margin:0;border:0\" align=\"left\">1 &le; 6 &le; 12</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0;margin:0;border:0\" align=\"left\">IQR (CV) : 6 (0.5)</td></tr></table></td>\n      <td align=\"left\" style=\"vertical-align:middle\">12 distinct values</td>\n      <td align=\"left\" style=\"vertical-align:middle;padding:0;background-color:transparent;\"><img style=\"border:none;background-color:transparent;padding:0;max-width:max-content;\" src=\"data:image/png;base64, iVBORw0KGgoAAAANSUhEUgAAADcAAAAnCAQAAAABBBhWAAAAAmJLR0QA/4ePzL8AAAAHdElNRQfmDBUAGS1wIe3+AAAArElEQVRYw+2X0Q2AIAxED8OO7KDzwA5OqV+YkiA5CGAkvT8j+tqTXsRcmKltKm1xnJUX4fmQh+mHkLvDprccAOAc1t2XZpblO1hdgeth9dqDoDjFkXqZuzjSPbOzgBuVnVWpkncginGiCRdB0QOXcUIUI8qw3IvTyjmrc6ss94gn/qCY7UWambOL6aYRV6OSEwNwpS7XDjHFKU5xAIxMnDDkKLuLyDZ6WP4t7gbQhCO0hN7aFQAAACV0RVh0ZGF0ZTpjcmVhdGUAMjAyMi0xMi0yMVQwMDoyNTo0NSswMDowMCF8wEsAAAAldEVYdGRhdGU6bW9kaWZ5ADIwMjItMTItMjFUMDA6MjU6NDUrMDA6MDBQIXj3AAAAPXRFWHRpY2M6Y29weXJpZ2h0AENvcHlyaWdodCAyMDA3IEFwcGxlIEluYy4sIGFsbCByaWdodHMgcmVzZXJ2ZWQunmbcKQAAACN0RVh0aWNjOmRlc2NyaXB0aW9uAEdlbmVyaWMgUkdCIFByb2ZpbGUapziOAAAAAElFTkSuQmCC\"></td>\n      <td align=\"center\">0\n(0.0%)</td>\n    </tr>\n    <tr>\n      <td align=\"left\">yearborn\n[integer]</td>\n      <td align=\"left\" style=\"padding:8;vertical-align:middle\"><table style=\"border-collapse:collapse;border:none;margin:0\"><tr style=\"background-color:transparent\"><td style=\"padding:0;margin:0;border:0\" align=\"left\">Mean (sd) : 60.4 (8.7)</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0;margin:0;border:0\" align=\"left\">min &le; med &le; max:</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0;margin:0;border:0\" align=\"left\">38 &le; 62 &le; 73</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0;margin:0;border:0\" align=\"left\">IQR (CV) : 13 (0.1)</td></tr></table></td>\n      <td align=\"left\" style=\"vertical-align:middle\">36 distinct values</td>\n      <td align=\"left\" style=\"vertical-align:middle;padding:0;background-color:transparent;\"><img style=\"border:none;background-color:transparent;padding:0;max-width:max-content;\" src=\"data:image/png;base64, iVBORw0KGgoAAAANSUhEUgAAADcAAAAnCAQAAAABBBhWAAAAAmJLR0QA/4ePzL8AAAAHdElNRQfmDBUAGS1wIe3+AAAA2UlEQVRYw+2Xaw6DIBCEB+Md9w7lPPQOnpL+sFJiwbIPMZJO4g8D4cvsTni4iJ6autIGx835jzNZMkQA8GmxPB2nuKPqyNi9uzIqUoXmvcLIHaWPDucp3G2evKuNfo+o3K1eyqUsuzQoJjHm3iOZ7Vk0cscpoQFOJkExpYVk4zYQYRHimMX8tWsY47RqLqamY0zcipJ3jIGzQwFNvdOFg42zlMlpXtM7XtmpNxeGk7zy4knArufTfsLnGgCEaBP/Kq4E74az19g4l2fhecpT9pHl2/0fy7fFvQB4DCoxsb4AAQAAACV0RVh0ZGF0ZTpjcmVhdGUAMjAyMi0xMi0yMVQwMDoyNTo0NSswMDowMCF8wEsAAAAldEVYdGRhdGU6bW9kaWZ5ADIwMjItMTItMjFUMDA6MjU6NDUrMDA6MDBQIXj3AAAAPXRFWHRpY2M6Y29weXJpZ2h0AENvcHlyaWdodCAyMDA3IEFwcGxlIEluYy4sIGFsbCByaWdodHMgcmVzZXJ2ZWQunmbcKQAAACN0RVh0aWNjOmRlc2NyaXB0aW9uAEdlbmVyaWMgUkdCIFByb2ZpbGUapziOAAAAAElFTkSuQmCC\"></td>\n      <td align=\"center\">0\n(0.0%)</td>\n    </tr>\n    <tr>\n      <td align=\"left\">age\n[integer]</td>\n      <td align=\"left\" style=\"padding:8;vertical-align:middle\"><table style=\"border-collapse:collapse;border:none;margin:0\"><tr style=\"background-color:transparent\"><td style=\"padding:0;margin:0;border:0\" align=\"left\">Mean (sd) : 27.4 (8.7)</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0;margin:0;border:0\" align=\"left\">min &le; med &le; max:</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0;margin:0;border:0\" align=\"left\">15 &le; 26 &le; 49</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0;margin:0;border:0\" align=\"left\">IQR (CV) : 13 (0.3)</td></tr></table></td>\n      <td align=\"left\" style=\"vertical-align:middle\">35 distinct values</td>\n      <td align=\"left\" style=\"vertical-align:middle;padding:0;background-color:transparent;\"><img style=\"border:none;background-color:transparent;padding:0;max-width:max-content;\" src=\"data:image/png;base64, iVBORw0KGgoAAAANSUhEUgAAADcAAAAnCAQAAAABBBhWAAAAAmJLR0QA/4ePzL8AAAAHdElNRQfmDBUAGS1wIe3+AAAA3ElEQVRYw+1XwQ2EMAxLTuyYHY55cjswZXlAUaBFkDQtKjp/gAph2Y4rigFa4tOU7eV0g3zA7Y4DAMCIyq9lIafjVB1VUfekmQs47O9G9LM2q462Kx1WXNVxtvPsuBMc1FFGR1zhUE6sGBUPQwfd66VDoywCFWp8955porPPqInOnp/ZTJtCZRGkwslQi6JR0deih8ncQ5OiAx0pKJ3MvJthf9lF3DHU3LsUBNNKG1fSRjqbuSgkOEvTme6q+M//Z/phTVEkWFVdam1jM1FW5VflKPsVZuL/sNwt3QytPDg6QO9n5wAAACV0RVh0ZGF0ZTpjcmVhdGUAMjAyMi0xMi0yMVQwMDoyNTo0NSswMDowMCF8wEsAAAAldEVYdGRhdGU6bW9kaWZ5ADIwMjItMTItMjFUMDA6MjU6NDUrMDA6MDBQIXj3AAAAPXRFWHRpY2M6Y29weXJpZ2h0AENvcHlyaWdodCAyMDA3IEFwcGxlIEluYy4sIGFsbCByaWdodHMgcmVzZXJ2ZWQunmbcKQAAACN0RVh0aWNjOmRlc2NyaXB0aW9uAEdlbmVyaWMgUkdCIFByb2ZpbGUapziOAAAAAElFTkSuQmCC\"></td>\n      <td align=\"center\">0\n(0.0%)</td>\n    </tr>\n    <tr>\n      <td align=\"left\">electric\n[integer]</td>\n      <td align=\"left\" style=\"padding:8;vertical-align:middle\"><table style=\"border-collapse:collapse;border:none;margin:0\"><tr style=\"background-color:transparent\"><td style=\"padding:0;margin:0;border:0\" align=\"left\">Min  : 0</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0;margin:0;border:0\" align=\"left\">Mean : 0.1</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0;margin:0;border:0\" align=\"left\">Max  : 1</td></tr></table></td>\n      <td align=\"left\" style=\"padding:0;vertical-align:middle\"><table style=\"border-collapse:collapse;border:none;margin:0\"><tr style=\"background-color:transparent\"><td style=\"padding:0 2px 0 7px;margin:0;border:0\" align=\"right\">0</td><td style=\"padding:0 2px;border:0;\" align=\"left\">:</td><td style=\"padding:0 4px 0 6px;margin:0;border:0\" align=\"right\">3747</td><td style=\"padding:0;border:0\" align=\"left\">(</td><td style=\"padding:0 2px;margin:0;border:0\" align=\"right\">86.0%</td><td style=\"padding:0 4px 0 0;border:0\" align=\"left\">)</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0 2px 0 7px;margin:0;border:0\" align=\"right\">1</td><td style=\"padding:0 2px;border:0;\" align=\"left\">:</td><td style=\"padding:0 4px 0 6px;margin:0;border:0\" align=\"right\">611</td><td style=\"padding:0;border:0\" align=\"left\">(</td><td style=\"padding:0 2px;margin:0;border:0\" align=\"right\">14.0%</td><td style=\"padding:0 4px 0 0;border:0\" align=\"left\">)</td></tr></table></td>\n      <td align=\"left\" style=\"vertical-align:middle;padding:0;background-color:transparent;\"><img style=\"border:none;background-color:transparent;padding:0;max-width:max-content;\" src=\"data:image/png;base64, iVBORw0KGgoAAAANSUhEUgAAADMAAAAVCAQAAABBXR6KAAAAAmJLR0QA/4ePzL8AAAAHdElNRQfmDBUAGS7pKLxEAAAAU0lEQVRIx2P8z0APwEQXW4aZNSzInGlUjagsRhzWMDCEU82SlSi84RU3A5EE0EOUZtYgg2xG4o3BBrJwW4NIadT11/BKAsPLGjolaMbRam3QWgMAe+8IW5jbVGwAAAAldEVYdGRhdGU6Y3JlYXRlADIwMjItMTItMjFUMDA6MjU6NDYrMDA6MDAQlNrWAAAAJXRFWHRkYXRlOm1vZGlmeQAyMDIyLTEyLTIxVDAwOjI1OjQ2KzAwOjAwYcliagAAAD10RVh0aWNjOmNvcHlyaWdodABDb3B5cmlnaHQgMjAwNyBBcHBsZSBJbmMuLCBhbGwgcmlnaHRzIHJlc2VydmVkLp5m3CkAAAAjdEVYdGljYzpkZXNjcmlwdGlvbgBHZW5lcmljIFJHQiBQcm9maWxlGqc4jgAAAABJRU5ErkJggg==\"></td>\n      <td align=\"center\">3\n(0.1%)</td>\n    </tr>\n    <tr>\n      <td align=\"left\">radio\n[integer]</td>\n      <td align=\"left\" style=\"padding:8;vertical-align:middle\"><table style=\"border-collapse:collapse;border:none;margin:0\"><tr style=\"background-color:transparent\"><td style=\"padding:0;margin:0;border:0\" align=\"left\">Min  : 0</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0;margin:0;border:0\" align=\"left\">Mean : 0.7</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0;margin:0;border:0\" align=\"left\">Max  : 1</td></tr></table></td>\n      <td align=\"left\" style=\"padding:0;vertical-align:middle\"><table style=\"border-collapse:collapse;border:none;margin:0\"><tr style=\"background-color:transparent\"><td style=\"padding:0 2px 0 7px;margin:0;border:0\" align=\"right\">0</td><td style=\"padding:0 2px;border:0;\" align=\"left\">:</td><td style=\"padding:0 4px 0 6px;margin:0;border:0\" align=\"right\">1300</td><td style=\"padding:0;border:0\" align=\"left\">(</td><td style=\"padding:0 2px;margin:0;border:0\" align=\"right\">29.8%</td><td style=\"padding:0 4px 0 0;border:0\" align=\"left\">)</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0 2px 0 7px;margin:0;border:0\" align=\"right\">1</td><td style=\"padding:0 2px;border:0;\" align=\"left\">:</td><td style=\"padding:0 4px 0 6px;margin:0;border:0\" align=\"right\">3059</td><td style=\"padding:0;border:0\" align=\"left\">(</td><td style=\"padding:0 2px;margin:0;border:0\" align=\"right\">70.2%</td><td style=\"padding:0 4px 0 0;border:0\" align=\"left\">)</td></tr></table></td>\n      <td align=\"left\" style=\"vertical-align:middle;padding:0;background-color:transparent;\"><img style=\"border:none;background-color:transparent;padding:0;max-width:max-content;\" src=\"data:image/png;base64, iVBORw0KGgoAAAANSUhEUgAAACwAAAAVCAQAAACX+MTvAAAAAmJLR0QA/4ePzL8AAAAHdElNRQfmDBUAGS7pKLxEAAAAVElEQVQ4y2P8z0AbwEQjc4egwSzInGl4AjybkbBhyNpZUKXCcWhZOXiCYugZjBbGpIclkQbjBlOJyaJIKYfIVEEMQPXt0Iu8oWcwzZIb42hBT3ODARNZChq6MZSCAAAAJXRFWHRkYXRlOmNyZWF0ZQAyMDIyLTEyLTIxVDAwOjI1OjQ2KzAwOjAwEJTa1gAAACV0RVh0ZGF0ZTptb2RpZnkAMjAyMi0xMi0yMVQwMDoyNTo0NiswMDowMGHJYmoAAAA9dEVYdGljYzpjb3B5cmlnaHQAQ29weXJpZ2h0IDIwMDcgQXBwbGUgSW5jLiwgYWxsIHJpZ2h0cyByZXNlcnZlZC6eZtwpAAAAI3RFWHRpY2M6ZGVzY3JpcHRpb24AR2VuZXJpYyBSR0IgUHJvZmlsZRqnOI4AAAAASUVORK5CYII=\"></td>\n      <td align=\"center\">2\n(0.0%)</td>\n    </tr>\n    <tr>\n      <td align=\"left\">tv\n[integer]</td>\n      <td align=\"left\" style=\"padding:8;vertical-align:middle\"><table style=\"border-collapse:collapse;border:none;margin:0\"><tr style=\"background-color:transparent\"><td style=\"padding:0;margin:0;border:0\" align=\"left\">Min  : 0</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0;margin:0;border:0\" align=\"left\">Mean : 0.1</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0;margin:0;border:0\" align=\"left\">Max  : 1</td></tr></table></td>\n      <td align=\"left\" style=\"padding:0;vertical-align:middle\"><table style=\"border-collapse:collapse;border:none;margin:0\"><tr style=\"background-color:transparent\"><td style=\"padding:0 2px 0 7px;margin:0;border:0\" align=\"right\">0</td><td style=\"padding:0 2px;border:0;\" align=\"left\">:</td><td style=\"padding:0 4px 0 6px;margin:0;border:0\" align=\"right\">3954</td><td style=\"padding:0;border:0\" align=\"left\">(</td><td style=\"padding:0 2px;margin:0;border:0\" align=\"right\">90.7%</td><td style=\"padding:0 4px 0 0;border:0\" align=\"left\">)</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0 2px 0 7px;margin:0;border:0\" align=\"right\">1</td><td style=\"padding:0 2px;border:0;\" align=\"left\">:</td><td style=\"padding:0 4px 0 6px;margin:0;border:0\" align=\"right\">405</td><td style=\"padding:0;border:0\" align=\"left\">(</td><td style=\"padding:0 2px;margin:0;border:0\" align=\"right\">9.3%</td><td style=\"padding:0 4px 0 0;border:0\" align=\"left\">)</td></tr></table></td>\n      <td align=\"left\" style=\"vertical-align:middle;padding:0;background-color:transparent;\"><img style=\"border:none;background-color:transparent;padding:0;max-width:max-content;\" src=\"data:image/png;base64, iVBORw0KGgoAAAANSUhEUgAAADUAAAAVCAQAAABMQ27NAAAAAmJLR0QA/4ePzL8AAAAHdElNRQfmDBUAGS7pKLxEAAAAUUlEQVRIx2P8z0AvwEQ3m4apVSzInGlUj7gsRhxWMTCEU9WilSi84RlXA5Us0EOXplbBQDYjacbgAlm4rQqnod+GZ7IYnlbRMbEzjlaNQ8YqACkRCFs153sNAAAAJXRFWHRkYXRlOmNyZWF0ZQAyMDIyLTEyLTIxVDAwOjI1OjQ2KzAwOjAwEJTa1gAAACV0RVh0ZGF0ZTptb2RpZnkAMjAyMi0xMi0yMVQwMDoyNTo0NiswMDowMGHJYmoAAAA9dEVYdGljYzpjb3B5cmlnaHQAQ29weXJpZ2h0IDIwMDcgQXBwbGUgSW5jLiwgYWxsIHJpZ2h0cyByZXNlcnZlZC6eZtwpAAAAI3RFWHRpY2M6ZGVzY3JpcHRpb24AR2VuZXJpYyBSR0IgUHJvZmlsZRqnOI4AAAAASUVORK5CYII=\"></td>\n      <td align=\"center\">2\n(0.0%)</td>\n    </tr>\n    <tr>\n      <td align=\"left\">bicycle\n[integer]</td>\n      <td align=\"left\" style=\"padding:8;vertical-align:middle\"><table style=\"border-collapse:collapse;border:none;margin:0\"><tr style=\"background-color:transparent\"><td style=\"padding:0;margin:0;border:0\" align=\"left\">Min  : 0</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0;margin:0;border:0\" align=\"left\">Mean : 0.3</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0;margin:0;border:0\" align=\"left\">Max  : 1</td></tr></table></td>\n      <td align=\"left\" style=\"padding:0;vertical-align:middle\"><table style=\"border-collapse:collapse;border:none;margin:0\"><tr style=\"background-color:transparent\"><td style=\"padding:0 2px 0 7px;margin:0;border:0\" align=\"right\">0</td><td style=\"padding:0 2px;border:0;\" align=\"left\">:</td><td style=\"padding:0 4px 0 6px;margin:0;border:0\" align=\"right\">3156</td><td style=\"padding:0;border:0\" align=\"left\">(</td><td style=\"padding:0 2px;margin:0;border:0\" align=\"right\">72.4%</td><td style=\"padding:0 4px 0 0;border:0\" align=\"left\">)</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0 2px 0 7px;margin:0;border:0\" align=\"right\">1</td><td style=\"padding:0 2px;border:0;\" align=\"left\">:</td><td style=\"padding:0 4px 0 6px;margin:0;border:0\" align=\"right\">1202</td><td style=\"padding:0;border:0\" align=\"left\">(</td><td style=\"padding:0 2px;margin:0;border:0\" align=\"right\">27.6%</td><td style=\"padding:0 4px 0 0;border:0\" align=\"left\">)</td></tr></table></td>\n      <td align=\"left\" style=\"vertical-align:middle;padding:0;background-color:transparent;\"><img style=\"border:none;background-color:transparent;padding:0;max-width:max-content;\" src=\"data:image/png;base64, iVBORw0KGgoAAAANSUhEUgAAAC0AAAAVCAQAAAB4Oq/RAAAAAmJLR0QA/4ePzL8AAAAHdElNRQfmDBUAGS7pKLxEAAAAUklEQVQ4y2P8z0ArwEQzk4eo0SzInGkUB3wWIw6jGRjCKTJ4Jb0CZGgajRbWK8kzhRijcYFsRuLUZeE2GnsKIc8vQzMah6bRNEx8jKNVAd2MBgB0mAhbgfqHkAAAACV0RVh0ZGF0ZTpjcmVhdGUAMjAyMi0xMi0yMVQwMDoyNTo0NiswMDowMBCU2tYAAAAldEVYdGRhdGU6bW9kaWZ5ADIwMjItMTItMjFUMDA6MjU6NDYrMDA6MDBhyWJqAAAAPXRFWHRpY2M6Y29weXJpZ2h0AENvcHlyaWdodCAyMDA3IEFwcGxlIEluYy4sIGFsbCByaWdodHMgcmVzZXJ2ZWQunmbcKQAAACN0RVh0aWNjOmRlc2NyaXB0aW9uAEdlbmVyaWMgUkdCIFByb2ZpbGUapziOAAAAAElFTkSuQmCC\"></td>\n      <td align=\"center\">3\n(0.1%)</td>\n    </tr>\n    <tr>\n      <td align=\"left\">educ\n[integer]</td>\n      <td align=\"left\" style=\"padding:8;vertical-align:middle\"><table style=\"border-collapse:collapse;border:none;margin:0\"><tr style=\"background-color:transparent\"><td style=\"padding:0;margin:0;border:0\" align=\"left\">Mean (sd) : 5.9 (3.9)</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0;margin:0;border:0\" align=\"left\">min &le; med &le; max:</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0;margin:0;border:0\" align=\"left\">0 &le; 7 &le; 20</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0;margin:0;border:0\" align=\"left\">IQR (CV) : 5 (0.7)</td></tr></table></td>\n      <td align=\"left\" style=\"vertical-align:middle\">21 distinct values</td>\n      <td align=\"left\" style=\"vertical-align:middle;padding:0;background-color:transparent;\"><img style=\"border:none;background-color:transparent;padding:0;max-width:max-content;\" src=\"data:image/png;base64, iVBORw0KGgoAAAANSUhEUgAAADcAAAAnCAQAAAABBBhWAAAAAmJLR0QA/4ePzL8AAAAHdElNRQfmDBUAGS7pKLxEAAAAo0lEQVRYw+2X0Q2AIAxEW8OO7qDz4A5OqV81NZFASyVSvD8SyAvctQAe0FJTU5pzXOADTE6Ll8UrglA8HaF00QwAAHvl7nx75xt3i0pkIZInUIyj/NUnMCXf3v04QxX3TBIVi65QxLi6Vu3bu29FJRo/1LJRsbnFSYN6Z+1aBmfrGWlQ73LStWo1TudtL4dJShXM8yEjn729UmsLA+P/We4WdwKoGRmLcpg+BwAAACV0RVh0ZGF0ZTpjcmVhdGUAMjAyMi0xMi0yMVQwMDoyNTo0NiswMDowMBCU2tYAAAAldEVYdGRhdGU6bW9kaWZ5ADIwMjItMTItMjFUMDA6MjU6NDYrMDA6MDBhyWJqAAAAPXRFWHRpY2M6Y29weXJpZ2h0AENvcHlyaWdodCAyMDA3IEFwcGxlIEluYy4sIGFsbCByaWdodHMgcmVzZXJ2ZWQunmbcKQAAACN0RVh0aWNjOmRlc2NyaXB0aW9uAEdlbmVyaWMgUkdCIFByb2ZpbGUapziOAAAAAElFTkSuQmCC\"></td>\n      <td align=\"center\">0\n(0.0%)</td>\n    </tr>\n    <tr>\n      <td align=\"left\">ceb\n[integer]</td>\n      <td align=\"left\" style=\"padding:8;vertical-align:middle\"><table style=\"border-collapse:collapse;border:none;margin:0\"><tr style=\"background-color:transparent\"><td style=\"padding:0;margin:0;border:0\" align=\"left\">Mean (sd) : 2.4 (2.4)</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0;margin:0;border:0\" align=\"left\">min &le; med &le; max:</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0;margin:0;border:0\" align=\"left\">0 &le; 2 &le; 13</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0;margin:0;border:0\" align=\"left\">IQR (CV) : 3 (1)</td></tr></table></td>\n      <td align=\"left\" style=\"vertical-align:middle\">14 distinct values</td>\n      <td align=\"left\" style=\"vertical-align:middle;padding:0;background-color:transparent;\"><img style=\"border:none;background-color:transparent;padding:0;max-width:max-content;\" src=\"data:image/png;base64, iVBORw0KGgoAAAANSUhEUgAAADcAAAAnCAQAAAABBBhWAAAAAmJLR0QA/4ePzL8AAAAHdElNRQfmDBUAGS7pKLxEAAAAlElEQVRYw+3Xyw2AIBBF0TdmeqQHrUd6oErc+BmjQdCBRB12fpLDDSyAIlqOrqn2cY7lg18XciA9Qu4O3n9yAIBQre7ba2ecccYZZ5xxf+D4/PUYAd0TS7LOzaeWRnW1GpNrp9/I179oNmbsTM3GjDrNxmzOAQiP0WzuiC6jBC/kNhQIN4pJTtRXucr2YiJkl+XXchNLMh1laX4YLQAAACV0RVh0ZGF0ZTpjcmVhdGUAMjAyMi0xMi0yMVQwMDoyNTo0NiswMDowMBCU2tYAAAAldEVYdGRhdGU6bW9kaWZ5ADIwMjItMTItMjFUMDA6MjU6NDYrMDA6MDBhyWJqAAAAPXRFWHRpY2M6Y29weXJpZ2h0AENvcHlyaWdodCAyMDA3IEFwcGxlIEluYy4sIGFsbCByaWdodHMgcmVzZXJ2ZWQunmbcKQAAACN0RVh0aWNjOmRlc2NyaXB0aW9uAEdlbmVyaWMgUkdCIFByb2ZpbGUapziOAAAAAElFTkSuQmCC\"></td>\n      <td align=\"center\">0\n(0.0%)</td>\n    </tr>\n    <tr>\n      <td align=\"left\">agefbrth\n[integer]</td>\n      <td align=\"left\" style=\"padding:8;vertical-align:middle\"><table style=\"border-collapse:collapse;border:none;margin:0\"><tr style=\"background-color:transparent\"><td style=\"padding:0;margin:0;border:0\" align=\"left\">Mean (sd) : 19 (3.1)</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0;margin:0;border:0\" align=\"left\">min &le; med &le; max:</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0;margin:0;border:0\" align=\"left\">10 &le; 19 &le; 38</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0;margin:0;border:0\" align=\"left\">IQR (CV) : 3 (0.2)</td></tr></table></td>\n      <td align=\"left\" style=\"vertical-align:middle\">28 distinct values</td>\n      <td align=\"left\" style=\"vertical-align:middle;padding:0;background-color:transparent;\"><img style=\"border:none;background-color:transparent;padding:0;max-width:max-content;\" src=\"data:image/png;base64, iVBORw0KGgoAAAANSUhEUgAAADcAAAAnCAQAAAABBBhWAAAAAmJLR0QA/4ePzL8AAAAHdElNRQfmDBUAGS7pKLxEAAAApUlEQVRYw+2X2w2AIAxFW8OO7KDz4A5OqR9q0ijvAsam/SMmPb30UhB3GBnTUJpwnKELfH12V2sXzMrmDeqOpDoLtqE62b370irhOC3DMUyRulaGkd07xSlOcRAZYq7LIyYyMy0AbJ4SOJOzaDP5k1O2VRT3X1zmW4UG5/RVqOOcvgp1HI0mlCit8TniinE3KD8VLS1HKVIpa5dbYCZloP4s/xZ3AHyKHM3tqOHXAAAAJXRFWHRkYXRlOmNyZWF0ZQAyMDIyLTEyLTIxVDAwOjI1OjQ2KzAwOjAwEJTa1gAAACV0RVh0ZGF0ZTptb2RpZnkAMjAyMi0xMi0yMVQwMDoyNTo0NiswMDowMGHJYmoAAAA9dEVYdGljYzpjb3B5cmlnaHQAQ29weXJpZ2h0IDIwMDcgQXBwbGUgSW5jLiwgYWxsIHJpZ2h0cyByZXNlcnZlZC6eZtwpAAAAI3RFWHRpY2M6ZGVzY3JpcHRpb24AR2VuZXJpYyBSR0IgUHJvZmlsZRqnOI4AAAAASUVORK5CYII=\"></td>\n      <td align=\"center\">1088\n(24.9%)</td>\n    </tr>\n    <tr>\n      <td align=\"left\">children\n[integer]</td>\n      <td align=\"left\" style=\"padding:8;vertical-align:middle\"><table style=\"border-collapse:collapse;border:none;margin:0\"><tr style=\"background-color:transparent\"><td style=\"padding:0;margin:0;border:0\" align=\"left\">Mean (sd) : 2.3 (2.2)</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0;margin:0;border:0\" align=\"left\">min &le; med &le; max:</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0;margin:0;border:0\" align=\"left\">0 &le; 2 &le; 13</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0;margin:0;border:0\" align=\"left\">IQR (CV) : 4 (1)</td></tr></table></td>\n      <td align=\"left\" style=\"vertical-align:middle\">14 distinct values</td>\n      <td align=\"left\" style=\"vertical-align:middle;padding:0;background-color:transparent;\"><img style=\"border:none;background-color:transparent;padding:0;max-width:max-content;\" src=\"data:image/png;base64, iVBORw0KGgoAAAANSUhEUgAAADcAAAAnCAQAAAABBBhWAAAAAmJLR0QA/4ePzL8AAAAHdElNRQfmDBUAGS7pKLxEAAAAkklEQVRYw+3XzQ2AIAwF4FfTHdlB55EdmBIvRms0WLWQqOXGT/LxUg6UMlqOrqn2cY7lJC6FHMiOkK+Dt1sBAJCqpft27ZxzzjnnnHPuDxwfL48ZsP2xFNOF+dfSKF2tjMXa2Wfk8yOWGRUv0zKjIp1lRjUXAKTHqJrbo3fYi9yKSlZPk+xPYpVWthcXIW+WX8tN/KkcZVa4cmgAAAAldEVYdGRhdGU6Y3JlYXRlADIwMjItMTItMjFUMDA6MjU6NDYrMDA6MDAQlNrWAAAAJXRFWHRkYXRlOm1vZGlmeQAyMDIyLTEyLTIxVDAwOjI1OjQ2KzAwOjAwYcliagAAAD10RVh0aWNjOmNvcHlyaWdodABDb3B5cmlnaHQgMjAwNyBBcHBsZSBJbmMuLCBhbGwgcmlnaHRzIHJlc2VydmVkLp5m3CkAAAAjdEVYdGljYzpkZXNjcmlwdGlvbgBHZW5lcmljIFJHQiBQcm9maWxlGqc4jgAAAABJRU5ErkJggg==\"></td>\n      <td align=\"center\">0\n(0.0%)</td>\n    </tr>\n    <tr>\n      <td align=\"left\">knowmeth\n[integer]</td>\n      <td align=\"left\" style=\"padding:8;vertical-align:middle\"><table style=\"border-collapse:collapse;border:none;margin:0\"><tr style=\"background-color:transparent\"><td style=\"padding:0;margin:0;border:0\" align=\"left\">Min  : 0</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0;margin:0;border:0\" align=\"left\">Mean : 1</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0;margin:0;border:0\" align=\"left\">Max  : 1</td></tr></table></td>\n      <td align=\"left\" style=\"padding:0;vertical-align:middle\"><table style=\"border-collapse:collapse;border:none;margin:0\"><tr style=\"background-color:transparent\"><td style=\"padding:0 2px 0 7px;margin:0;border:0\" align=\"right\">0</td><td style=\"padding:0 2px;border:0;\" align=\"left\">:</td><td style=\"padding:0 4px 0 6px;margin:0;border:0\" align=\"right\">160</td><td style=\"padding:0;border:0\" align=\"left\">(</td><td style=\"padding:0 2px;margin:0;border:0\" align=\"right\">3.7%</td><td style=\"padding:0 4px 0 0;border:0\" align=\"left\">)</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0 2px 0 7px;margin:0;border:0\" align=\"right\">1</td><td style=\"padding:0 2px;border:0;\" align=\"left\">:</td><td style=\"padding:0 4px 0 6px;margin:0;border:0\" align=\"right\">4194</td><td style=\"padding:0;border:0\" align=\"left\">(</td><td style=\"padding:0 2px;margin:0;border:0\" align=\"right\">96.3%</td><td style=\"padding:0 4px 0 0;border:0\" align=\"left\">)</td></tr></table></td>\n      <td align=\"left\" style=\"vertical-align:middle;padding:0;background-color:transparent;\"><img style=\"border:none;background-color:transparent;padding:0;max-width:max-content;\" src=\"data:image/png;base64, iVBORw0KGgoAAAANSUhEUgAAADgAAAAVCAQAAAC5veV9AAAAAmJLR0QA/4ePzL8AAAAHdElNRQfmDBUAGS7pKLxEAAAAUUlEQVRIx2P8z0BfwERn+0aAhSzInGn/GRiyGalvCXI6Gf5BOmoh1QELusBUWhQ9SCkfzcJwGti2EoU3/ONw+FuIlmhWkmcKCYBxtAIe8hYCABFiCG3BKofAAAAAJXRFWHRkYXRlOmNyZWF0ZQAyMDIyLTEyLTIxVDAwOjI1OjQ2KzAwOjAwEJTa1gAAACV0RVh0ZGF0ZTptb2RpZnkAMjAyMi0xMi0yMVQwMDoyNTo0NiswMDowMGHJYmoAAAA9dEVYdGljYzpjb3B5cmlnaHQAQ29weXJpZ2h0IDIwMDcgQXBwbGUgSW5jLiwgYWxsIHJpZ2h0cyByZXNlcnZlZC6eZtwpAAAAI3RFWHRpY2M6ZGVzY3JpcHRpb24AR2VuZXJpYyBSR0IgUHJvZmlsZRqnOI4AAAAASUVORK5CYII=\"></td>\n      <td align=\"center\">7\n(0.2%)</td>\n    </tr>\n    <tr>\n      <td align=\"left\">usemeth\n[integer]</td>\n      <td align=\"left\" style=\"padding:8;vertical-align:middle\"><table style=\"border-collapse:collapse;border:none;margin:0\"><tr style=\"background-color:transparent\"><td style=\"padding:0;margin:0;border:0\" align=\"left\">Min  : 0</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0;margin:0;border:0\" align=\"left\">Mean : 0.6</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0;margin:0;border:0\" align=\"left\">Max  : 1</td></tr></table></td>\n      <td align=\"left\" style=\"padding:0;vertical-align:middle\"><table style=\"border-collapse:collapse;border:none;margin:0\"><tr style=\"background-color:transparent\"><td style=\"padding:0 2px 0 7px;margin:0;border:0\" align=\"right\">0</td><td style=\"padding:0 2px;border:0;\" align=\"left\">:</td><td style=\"padding:0 4px 0 6px;margin:0;border:0\" align=\"right\">1812</td><td style=\"padding:0;border:0\" align=\"left\">(</td><td style=\"padding:0 2px;margin:0;border:0\" align=\"right\">42.2%</td><td style=\"padding:0 4px 0 0;border:0\" align=\"left\">)</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0 2px 0 7px;margin:0;border:0\" align=\"right\">1</td><td style=\"padding:0 2px;border:0;\" align=\"left\">:</td><td style=\"padding:0 4px 0 6px;margin:0;border:0\" align=\"right\">2478</td><td style=\"padding:0;border:0\" align=\"left\">(</td><td style=\"padding:0 2px;margin:0;border:0\" align=\"right\">57.8%</td><td style=\"padding:0 4px 0 0;border:0\" align=\"left\">)</td></tr></table></td>\n      <td align=\"left\" style=\"vertical-align:middle;padding:0;background-color:transparent;\"><img style=\"border:none;background-color:transparent;padding:0;max-width:max-content;\" src=\"data:image/png;base64, iVBORw0KGgoAAAANSUhEUgAAACYAAAAVCAQAAACA2lQmAAAAAmJLR0QA/4ePzL8AAAAHdElNRQfmDBUAGS7pKLxEAAAAUklEQVQ4y2P8z0A9wERFswaxYSzInGlEBmA2I4L9H5dhDAzhRBi1kj7eHLyGoYXZSvJMwW4YcWAqchQixSwZsYnbJ4M3AgavYVRNGoyjhSPJAADMfAoabRKQnwAAACV0RVh0ZGF0ZTpjcmVhdGUAMjAyMi0xMi0yMVQwMDoyNTo0NiswMDowMBCU2tYAAAAldEVYdGRhdGU6bW9kaWZ5ADIwMjItMTItMjFUMDA6MjU6NDYrMDA6MDBhyWJqAAAAPXRFWHRpY2M6Y29weXJpZ2h0AENvcHlyaWdodCAyMDA3IEFwcGxlIEluYy4sIGFsbCByaWdodHMgcmVzZXJ2ZWQunmbcKQAAACN0RVh0aWNjOmRlc2NyaXB0aW9uAEdlbmVyaWMgUkdCIFByb2ZpbGUapziOAAAAAElFTkSuQmCC\"></td>\n      <td align=\"center\">71\n(1.6%)</td>\n    </tr>\n    <tr>\n      <td align=\"left\">monthfm\n[integer]</td>\n      <td align=\"left\" style=\"padding:8;vertical-align:middle\"><table style=\"border-collapse:collapse;border:none;margin:0\"><tr style=\"background-color:transparent\"><td style=\"padding:0;margin:0;border:0\" align=\"left\">Mean (sd) : 6.3 (3.6)</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0;margin:0;border:0\" align=\"left\">min &le; med &le; max:</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0;margin:0;border:0\" align=\"left\">1 &le; 6 &le; 12</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0;margin:0;border:0\" align=\"left\">IQR (CV) : 6 (0.6)</td></tr></table></td>\n      <td align=\"left\" style=\"vertical-align:middle\">12 distinct values</td>\n      <td align=\"left\" style=\"vertical-align:middle;padding:0;background-color:transparent;\"><img style=\"border:none;background-color:transparent;padding:0;max-width:max-content;\" src=\"data:image/png;base64, iVBORw0KGgoAAAANSUhEUgAAADcAAAAnCAQAAAABBBhWAAAAAmJLR0QA/4ePzL8AAAAHdElNRQfmDBUAGS7pKLxEAAAAn0lEQVRYw+2X0Q2AIAxED8OO7KDzyA5MqR9GLYikNUAi6f0R5d4VRMBs6KmpK21wnKUNf03kYuoh6Ndh40cOABCaVTf23ClOcYpTnOL4svxX1wq7oQAn2w3vcCDhRLjU6qgybpXD2bLhqdgqNXIAwqNPTi+401AyfJw+zMHMJ+fU8wnnsnnlB6mxl7niFMeUoSvVN7nKzuQHaPSy/FvcDt9MIay4wQ59AAAAJXRFWHRkYXRlOmNyZWF0ZQAyMDIyLTEyLTIxVDAwOjI1OjQ2KzAwOjAwEJTa1gAAACV0RVh0ZGF0ZTptb2RpZnkAMjAyMi0xMi0yMVQwMDoyNTo0NiswMDowMGHJYmoAAAA9dEVYdGljYzpjb3B5cmlnaHQAQ29weXJpZ2h0IDIwMDcgQXBwbGUgSW5jLiwgYWxsIHJpZ2h0cyByZXNlcnZlZC6eZtwpAAAAI3RFWHRpY2M6ZGVzY3JpcHRpb24AR2VuZXJpYyBSR0IgUHJvZmlsZRqnOI4AAAAASUVORK5CYII=\"></td>\n      <td align=\"center\">2282\n(52.3%)</td>\n    </tr>\n    <tr>\n      <td align=\"left\">yearfm\n[integer]</td>\n      <td align=\"left\" style=\"padding:8;vertical-align:middle\"><table style=\"border-collapse:collapse;border:none;margin:0\"><tr style=\"background-color:transparent\"><td style=\"padding:0;margin:0;border:0\" align=\"left\">Mean (sd) : 76.9 (7.8)</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0;margin:0;border:0\" align=\"left\">min &le; med &le; max:</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0;margin:0;border:0\" align=\"left\">50 &le; 78 &le; 88</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0;margin:0;border:0\" align=\"left\">IQR (CV) : 11 (0.1)</td></tr></table></td>\n      <td align=\"left\" style=\"vertical-align:middle\">38 distinct values</td>\n      <td align=\"left\" style=\"vertical-align:middle;padding:0;background-color:transparent;\"><img style=\"border:none;background-color:transparent;padding:0;max-width:max-content;\" src=\"data:image/png;base64, iVBORw0KGgoAAAANSUhEUgAAADcAAAAnCAQAAAABBBhWAAAAAmJLR0QA/4ePzL8AAAAHdElNRQfmDBUAGS7pKLxEAAAApklEQVRYw+2X0Q2AIAxErWFHdtB5cAen1B9jjw8j0AKC3A+amL7kei2Rjqmk5qK0znEGX0hUykEMViiF6TDB1QJkr3N//KKmmSlyUZOkYOa7haw2zIyzUIyLs5DV91bpG6e6xFhecmF/ZsLZ+8lP7pfNTB3uRFzqcLP6HoSBU1RAMuXxj8LJ48/6ae80OxaA0+wYq6aZeQxEERK2LLgFbnMaP8vN4k6Awhp0Ovk82wAAACV0RVh0ZGF0ZTpjcmVhdGUAMjAyMi0xMi0yMVQwMDoyNTo0NiswMDowMBCU2tYAAAAldEVYdGRhdGU6bW9kaWZ5ADIwMjItMTItMjFUMDA6MjU6NDYrMDA6MDBhyWJqAAAAPXRFWHRpY2M6Y29weXJpZ2h0AENvcHlyaWdodCAyMDA3IEFwcGxlIEluYy4sIGFsbCByaWdodHMgcmVzZXJ2ZWQunmbcKQAAACN0RVh0aWNjOmRlc2NyaXB0aW9uAEdlbmVyaWMgUkdCIFByb2ZpbGUapziOAAAAAElFTkSuQmCC\"></td>\n      <td align=\"center\">2282\n(52.3%)</td>\n    </tr>\n    <tr>\n      <td align=\"left\">agefm\n[integer]</td>\n      <td align=\"left\" style=\"padding:8;vertical-align:middle\"><table style=\"border-collapse:collapse;border:none;margin:0\"><tr style=\"background-color:transparent\"><td style=\"padding:0;margin:0;border:0\" align=\"left\">Mean (sd) : 20.7 (5)</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0;margin:0;border:0\" align=\"left\">min &le; med &le; max:</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0;margin:0;border:0\" align=\"left\">10 &le; 20 &le; 46</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0;margin:0;border:0\" align=\"left\">IQR (CV) : 6 (0.2)</td></tr></table></td>\n      <td align=\"left\" style=\"vertical-align:middle\">35 distinct values</td>\n      <td align=\"left\" style=\"vertical-align:middle;padding:0;background-color:transparent;\"><img style=\"border:none;background-color:transparent;padding:0;max-width:max-content;\" src=\"data:image/png;base64, iVBORw0KGgoAAAANSUhEUgAAADcAAAAnCAQAAAABBBhWAAAAAmJLR0QA/4ePzL8AAAAHdElNRQfmDBUAGS7pKLxEAAAAwUlEQVRYw+2XURLCIAxEEyd35A56nngHTok/fmAFYekWtUP+OpPyurBLQZPMrMtU2slxlj9oocGTiMhNu0YrVu4Oq7f5sy9IpKn7OJlBAg3UgePXws3HeXLKbteJYzm0kjuOFkAdO3EN3GR1C3cojpE9AMfw6u9OJqMMa997lADV7f2/n3vtvm+Vdpg9jdqlqK5lhyCje8zwZI45FMzda+EptPfXMYURWkkrDYBC4+ZD63DN++6HHIiuGVzXZflvcQ8jASmHH/65DwAAACV0RVh0ZGF0ZTpjcmVhdGUAMjAyMi0xMi0yMVQwMDoyNTo0NiswMDowMBCU2tYAAAAldEVYdGRhdGU6bW9kaWZ5ADIwMjItMTItMjFUMDA6MjU6NDYrMDA6MDBhyWJqAAAAPXRFWHRpY2M6Y29weXJpZ2h0AENvcHlyaWdodCAyMDA3IEFwcGxlIEluYy4sIGFsbCByaWdodHMgcmVzZXJ2ZWQunmbcKQAAACN0RVh0aWNjOmRlc2NyaXB0aW9uAEdlbmVyaWMgUkdCIFByb2ZpbGUapziOAAAAAElFTkSuQmCC\"></td>\n      <td align=\"center\">2282\n(52.3%)</td>\n    </tr>\n    <tr>\n      <td align=\"left\">idlnchld\n[integer]</td>\n      <td align=\"left\" style=\"padding:8;vertical-align:middle\"><table style=\"border-collapse:collapse;border:none;margin:0\"><tr style=\"background-color:transparent\"><td style=\"padding:0;margin:0;border:0\" align=\"left\">Mean (sd) : 4.6 (2.2)</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0;margin:0;border:0\" align=\"left\">min &le; med &le; max:</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0;margin:0;border:0\" align=\"left\">0 &le; 4 &le; 20</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0;margin:0;border:0\" align=\"left\">IQR (CV) : 3 (0.5)</td></tr></table></td>\n      <td align=\"left\" style=\"vertical-align:middle\">19 distinct values</td>\n      <td align=\"left\" style=\"vertical-align:middle;padding:0;background-color:transparent;\"><img style=\"border:none;background-color:transparent;padding:0;max-width:max-content;\" src=\"data:image/png;base64, iVBORw0KGgoAAAANSUhEUgAAADcAAAAnCAQAAAABBBhWAAAAAmJLR0QA/4ePzL8AAAAHdElNRQfmDBUAGS7pKLxEAAAAlklEQVRYw+2X3Q2AIAyEW8OO7KDz4A5OqS+WVOJPlUJi03tBEsIXOLgirtBTQ1eacVzgHcxfKVs64YvZTsVPR7gaFAEAYFFenW3vHOc4x8FNqpAozurDTITTDTPb3jnOcUId7l1q/ugsrnncW+03Csm2d7ZxjxWBpFOIxDgqRHVYMa7EflNn75AHydwkVUa27eg/y7/FbUdFFO+lGF1BAAAAJXRFWHRkYXRlOmNyZWF0ZQAyMDIyLTEyLTIxVDAwOjI1OjQ2KzAwOjAwEJTa1gAAACV0RVh0ZGF0ZTptb2RpZnkAMjAyMi0xMi0yMVQwMDoyNTo0NiswMDowMGHJYmoAAAA9dEVYdGljYzpjb3B5cmlnaHQAQ29weXJpZ2h0IDIwMDcgQXBwbGUgSW5jLiwgYWxsIHJpZ2h0cyByZXNlcnZlZC6eZtwpAAAAI3RFWHRpY2M6ZGVzY3JpcHRpb24AR2VuZXJpYyBSR0IgUHJvZmlsZRqnOI4AAAAASUVORK5CYII=\"></td>\n      <td align=\"center\">120\n(2.8%)</td>\n    </tr>\n    <tr>\n      <td align=\"left\">heduc\n[integer]</td>\n      <td align=\"left\" style=\"padding:8;vertical-align:middle\"><table style=\"border-collapse:collapse;border:none;margin:0\"><tr style=\"background-color:transparent\"><td style=\"padding:0;margin:0;border:0\" align=\"left\">Mean (sd) : 5.1 (4.8)</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0;margin:0;border:0\" align=\"left\">min &le; med &le; max:</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0;margin:0;border:0\" align=\"left\">0 &le; 6 &le; 20</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0;margin:0;border:0\" align=\"left\">IQR (CV) : 8 (0.9)</td></tr></table></td>\n      <td align=\"left\" style=\"vertical-align:middle\">21 distinct values</td>\n      <td align=\"left\" style=\"vertical-align:middle;padding:0;background-color:transparent;\"><img style=\"border:none;background-color:transparent;padding:0;max-width:max-content;\" src=\"data:image/png;base64, iVBORw0KGgoAAAANSUhEUgAAADcAAAAnCAQAAAABBBhWAAAAAmJLR0QA/4ePzL8AAAAHdElNRQfmDBUAGS7pKLxEAAAAoElEQVRYw+2XUQ6AIAiGo3nH7lDn0Tt0ynqJRj0ICrpy8MJcbZ8//IXCMfWMuSttcFygi0QauYEVgrojPB8tV94bqRu7d45znOMcZxtB9lq8f+u6SSHE4azQToqxezc2TmwVDPRonUOLcTqHfquY0fhMzxbT5vNmcda6GBynqs6hxc6UbscY91aJkVerxqFKzPkiA91camKPlYDBL8u/xZ0aHx2L+zGEIgAAACV0RVh0ZGF0ZTpjcmVhdGUAMjAyMi0xMi0yMVQwMDoyNTo0NiswMDowMBCU2tYAAAAldEVYdGRhdGU6bW9kaWZ5ADIwMjItMTItMjFUMDA6MjU6NDYrMDA6MDBhyWJqAAAAPXRFWHRpY2M6Y29weXJpZ2h0AENvcHlyaWdodCAyMDA3IEFwcGxlIEluYy4sIGFsbCByaWdodHMgcmVzZXJ2ZWQunmbcKQAAACN0RVh0aWNjOmRlc2NyaXB0aW9uAEdlbmVyaWMgUkdCIFByb2ZpbGUapziOAAAAAElFTkSuQmCC\"></td>\n      <td align=\"center\">2405\n(55.1%)</td>\n    </tr>\n    <tr>\n      <td align=\"left\">agesq\n[integer]</td>\n      <td align=\"left\" style=\"padding:8;vertical-align:middle\"><table style=\"border-collapse:collapse;border:none;margin:0\"><tr style=\"background-color:transparent\"><td style=\"padding:0;margin:0;border:0\" align=\"left\">Mean (sd) : 826.5 (526.9)</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0;margin:0;border:0\" align=\"left\">min &le; med &le; max:</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0;margin:0;border:0\" align=\"left\">225 &le; 676 &le; 2401</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0;margin:0;border:0\" align=\"left\">IQR (CV) : 689 (0.6)</td></tr></table></td>\n      <td align=\"left\" style=\"vertical-align:middle\">35 distinct values</td>\n      <td align=\"left\" style=\"vertical-align:middle;padding:0;background-color:transparent;\"><img style=\"border:none;background-color:transparent;padding:0;max-width:max-content;\" src=\"data:image/png;base64, iVBORw0KGgoAAAANSUhEUgAAADcAAAAnCAQAAAABBBhWAAAAAmJLR0QA/4ePzL8AAAAHdElNRQfmDBUAGS7pKLxEAAAAr0lEQVRYw+2XSw6AIAxEB8MduYOeR+7gKXWBktZf5FMSSbszmDwm02mDWdGyhqa0znGWfvho5GTqIWh3WH7kAACLmLq+vVOc4hSHy1Q5amZ7qd5Ie8A5AIvASOvbO8X9F2e//BRSWCN9n9S5PYGN1FGNZSoTcDVmTALurDJHaUZnBifz/NTcvdRdt751cCHu6Fa+jsO2FFDHATwq8QpEpaHX8iJP2fEJJ199B6ExbgMeAiGSzSOiTgAAACV0RVh0ZGF0ZTpjcmVhdGUAMjAyMi0xMi0yMVQwMDoyNTo0NiswMDowMBCU2tYAAAAldEVYdGRhdGU6bW9kaWZ5ADIwMjItMTItMjFUMDA6MjU6NDYrMDA6MDBhyWJqAAAAPXRFWHRpY2M6Y29weXJpZ2h0AENvcHlyaWdodCAyMDA3IEFwcGxlIEluYy4sIGFsbCByaWdodHMgcmVzZXJ2ZWQunmbcKQAAACN0RVh0aWNjOmRlc2NyaXB0aW9uAEdlbmVyaWMgUkdCIFByb2ZpbGUapziOAAAAAElFTkSuQmCC\"></td>\n      <td align=\"center\">0\n(0.0%)</td>\n    </tr>\n    <tr>\n      <td align=\"left\">urban\n[integer]</td>\n      <td align=\"left\" style=\"padding:8;vertical-align:middle\"><table style=\"border-collapse:collapse;border:none;margin:0\"><tr style=\"background-color:transparent\"><td style=\"padding:0;margin:0;border:0\" align=\"left\">Min  : 0</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0;margin:0;border:0\" align=\"left\">Mean : 0.5</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0;margin:0;border:0\" align=\"left\">Max  : 1</td></tr></table></td>\n      <td align=\"left\" style=\"padding:0;vertical-align:middle\"><table style=\"border-collapse:collapse;border:none;margin:0\"><tr style=\"background-color:transparent\"><td style=\"padding:0 2px 0 7px;margin:0;border:0\" align=\"right\">0</td><td style=\"padding:0 2px;border:0;\" align=\"left\">:</td><td style=\"padding:0 4px 0 6px;margin:0;border:0\" align=\"right\">2108</td><td style=\"padding:0;border:0\" align=\"left\">(</td><td style=\"padding:0 2px;margin:0;border:0\" align=\"right\">48.3%</td><td style=\"padding:0 4px 0 0;border:0\" align=\"left\">)</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0 2px 0 7px;margin:0;border:0\" align=\"right\">1</td><td style=\"padding:0 2px;border:0;\" align=\"left\">:</td><td style=\"padding:0 4px 0 6px;margin:0;border:0\" align=\"right\">2253</td><td style=\"padding:0;border:0\" align=\"left\">(</td><td style=\"padding:0 2px;margin:0;border:0\" align=\"right\">51.7%</td><td style=\"padding:0 4px 0 0;border:0\" align=\"left\">)</td></tr></table></td>\n      <td align=\"left\" style=\"vertical-align:middle;padding:0;background-color:transparent;\"><img style=\"border:none;background-color:transparent;padding:0;max-width:max-content;\" src=\"data:image/png;base64, iVBORw0KGgoAAAANSUhEUgAAACQAAAAVCAQAAACEL4QbAAAAAmJLR0QA/4ePzL8AAAAHdElNRQfmDBUAGS7pKLxEAAAAVElEQVQ4y2P8z0AdwEQlcwahQSzInGkkBFg2IwPDf1wGMTCEE2nMStp5bfAZhBZGK8kzBdMg4sHU/wwMDIw4DSI21jBdP/gCe/AZRLXoZxwt2AgCALTiChpJou8BAAAAJXRFWHRkYXRlOmNyZWF0ZQAyMDIyLTEyLTIxVDAwOjI1OjQ2KzAwOjAwEJTa1gAAACV0RVh0ZGF0ZTptb2RpZnkAMjAyMi0xMi0yMVQwMDoyNTo0NiswMDowMGHJYmoAAAA9dEVYdGljYzpjb3B5cmlnaHQAQ29weXJpZ2h0IDIwMDcgQXBwbGUgSW5jLiwgYWxsIHJpZ2h0cyByZXNlcnZlZC6eZtwpAAAAI3RFWHRpY2M6ZGVzY3JpcHRpb24AR2VuZXJpYyBSR0IgUHJvZmlsZRqnOI4AAAAASUVORK5CYII=\"></td>\n      <td align=\"center\">0\n(0.0%)</td>\n    </tr>\n    <tr>\n      <td align=\"left\">urb_educ\n[integer]</td>\n      <td align=\"left\" style=\"padding:8;vertical-align:middle\"><table style=\"border-collapse:collapse;border:none;margin:0\"><tr style=\"background-color:transparent\"><td style=\"padding:0;margin:0;border:0\" align=\"left\">Mean (sd) : 3.5 (4.3)</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0;margin:0;border:0\" align=\"left\">min &le; med &le; max:</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0;margin:0;border:0\" align=\"left\">0 &le; 0 &le; 20</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0;margin:0;border:0\" align=\"left\">IQR (CV) : 7 (1.2)</td></tr></table></td>\n      <td align=\"left\" style=\"vertical-align:middle\">21 distinct values</td>\n      <td align=\"left\" style=\"vertical-align:middle;padding:0;background-color:transparent;\"><img style=\"border:none;background-color:transparent;padding:0;max-width:max-content;\" src=\"data:image/png;base64, iVBORw0KGgoAAAANSUhEUgAAADcAAAAnCAQAAAABBBhWAAAAAmJLR0QA/4ePzL8AAAAHdElNRQfmDBUAGS7pKLxEAAAAkElEQVRYw2P8z0BPwERX24a5dSzInGlIEZnNSC0rkFMHC6pUOJReSSPfDe+4G7Vu1LpR60atG7Vu1LpR66gOWIhTNhXevqGsyUSkdbBGE6VNpsEZmAgAC1byApVk6ygLVALWTaVyB4mg76iTRAhaR8hf5MUhTusI+QomT5q1jMiemEaTrmwWkkMYRzvLQ9Y6AEATGYVh5rlIAAAAJXRFWHRkYXRlOmNyZWF0ZQAyMDIyLTEyLTIxVDAwOjI1OjQ2KzAwOjAwEJTa1gAAACV0RVh0ZGF0ZTptb2RpZnkAMjAyMi0xMi0yMVQwMDoyNTo0NiswMDowMGHJYmoAAAA9dEVYdGljYzpjb3B5cmlnaHQAQ29weXJpZ2h0IDIwMDcgQXBwbGUgSW5jLiwgYWxsIHJpZ2h0cyByZXNlcnZlZC6eZtwpAAAAI3RFWHRpY2M6ZGVzY3JpcHRpb24AR2VuZXJpYyBSR0IgUHJvZmlsZRqnOI4AAAAASUVORK5CYII=\"></td>\n      <td align=\"center\">0\n(0.0%)</td>\n    </tr>\n    <tr>\n      <td align=\"left\">spirit\n[integer]</td>\n      <td align=\"left\" style=\"padding:8;vertical-align:middle\"><table style=\"border-collapse:collapse;border:none;margin:0\"><tr style=\"background-color:transparent\"><td style=\"padding:0;margin:0;border:0\" align=\"left\">Min  : 0</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0;margin:0;border:0\" align=\"left\">Mean : 0.4</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0;margin:0;border:0\" align=\"left\">Max  : 1</td></tr></table></td>\n      <td align=\"left\" style=\"padding:0;vertical-align:middle\"><table style=\"border-collapse:collapse;border:none;margin:0\"><tr style=\"background-color:transparent\"><td style=\"padding:0 2px 0 7px;margin:0;border:0\" align=\"right\">0</td><td style=\"padding:0 2px;border:0;\" align=\"left\">:</td><td style=\"padding:0 4px 0 6px;margin:0;border:0\" align=\"right\">2520</td><td style=\"padding:0;border:0\" align=\"left\">(</td><td style=\"padding:0 2px;margin:0;border:0\" align=\"right\">57.8%</td><td style=\"padding:0 4px 0 0;border:0\" align=\"left\">)</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0 2px 0 7px;margin:0;border:0\" align=\"right\">1</td><td style=\"padding:0 2px;border:0;\" align=\"left\">:</td><td style=\"padding:0 4px 0 6px;margin:0;border:0\" align=\"right\">1841</td><td style=\"padding:0;border:0\" align=\"left\">(</td><td style=\"padding:0 2px;margin:0;border:0\" align=\"right\">42.2%</td><td style=\"padding:0 4px 0 0;border:0\" align=\"left\">)</td></tr></table></td>\n      <td align=\"left\" style=\"vertical-align:middle;padding:0;background-color:transparent;\"><img style=\"border:none;background-color:transparent;padding:0;max-width:max-content;\" src=\"data:image/png;base64, iVBORw0KGgoAAAANSUhEUgAAACYAAAAVCAQAAACA2lQmAAAAAmJLR0QA/4ePzL8AAAAHdElNRQfmDBUAGS7pKLxEAAAAUElEQVQ4y2P8z0A9wERFswaxYSzInGlkBGAWIw7DGBjCSTRqJe28OXgNQwuzleSZgt0w4kA2Ugxm4TaMmNjE7frBGwGD1zCqJg3G0cKRZAAAlrAIW2sAhPEAAAAldEVYdGRhdGU6Y3JlYXRlADIwMjItMTItMjFUMDA6MjU6NDYrMDA6MDAQlNrWAAAAJXRFWHRkYXRlOm1vZGlmeQAyMDIyLTEyLTIxVDAwOjI1OjQ2KzAwOjAwYcliagAAAD10RVh0aWNjOmNvcHlyaWdodABDb3B5cmlnaHQgMjAwNyBBcHBsZSBJbmMuLCBhbGwgcmlnaHRzIHJlc2VydmVkLp5m3CkAAAAjdEVYdGljYzpkZXNjcmlwdGlvbgBHZW5lcmljIFJHQiBQcm9maWxlGqc4jgAAAABJRU5ErkJggg==\"></td>\n      <td align=\"center\">0\n(0.0%)</td>\n    </tr>\n    <tr>\n      <td align=\"left\">protest\n[integer]</td>\n      <td align=\"left\" style=\"padding:8;vertical-align:middle\"><table style=\"border-collapse:collapse;border:none;margin:0\"><tr style=\"background-color:transparent\"><td style=\"padding:0;margin:0;border:0\" align=\"left\">Min  : 0</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0;margin:0;border:0\" align=\"left\">Mean : 0.2</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0;margin:0;border:0\" align=\"left\">Max  : 1</td></tr></table></td>\n      <td align=\"left\" style=\"padding:0;vertical-align:middle\"><table style=\"border-collapse:collapse;border:none;margin:0\"><tr style=\"background-color:transparent\"><td style=\"padding:0 2px 0 7px;margin:0;border:0\" align=\"right\">0</td><td style=\"padding:0 2px;border:0;\" align=\"left\">:</td><td style=\"padding:0 4px 0 6px;margin:0;border:0\" align=\"right\">3368</td><td style=\"padding:0;border:0\" align=\"left\">(</td><td style=\"padding:0 2px;margin:0;border:0\" align=\"right\">77.2%</td><td style=\"padding:0 4px 0 0;border:0\" align=\"left\">)</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0 2px 0 7px;margin:0;border:0\" align=\"right\">1</td><td style=\"padding:0 2px;border:0;\" align=\"left\">:</td><td style=\"padding:0 4px 0 6px;margin:0;border:0\" align=\"right\">993</td><td style=\"padding:0;border:0\" align=\"left\">(</td><td style=\"padding:0 2px;margin:0;border:0\" align=\"right\">22.8%</td><td style=\"padding:0 4px 0 0;border:0\" align=\"left\">)</td></tr></table></td>\n      <td align=\"left\" style=\"vertical-align:middle;padding:0;background-color:transparent;\"><img style=\"border:none;background-color:transparent;padding:0;max-width:max-content;\" src=\"data:image/png;base64, iVBORw0KGgoAAAANSUhEUgAAAC8AAAAVCAQAAAB8z3/sAAAAAmJLR0QA/4ePzL8AAAAHdElNRQfmDBUAGS7pKLxEAAAAUklEQVQ4y2P8z0BLwERT04e48SzInGlUiYgsRhzGMzCEU2z4ShTe0A57ekYteshR3XhsIJuRsBpkkIXbeMyUQ5l/hnbUDm3jaZwwGUerkwEzHgAhughbcf9mygAAACV0RVh0ZGF0ZTpjcmVhdGUAMjAyMi0xMi0yMVQwMDoyNTo0NiswMDowMBCU2tYAAAAldEVYdGRhdGU6bW9kaWZ5ADIwMjItMTItMjFUMDA6MjU6NDYrMDA6MDBhyWJqAAAAPXRFWHRpY2M6Y29weXJpZ2h0AENvcHlyaWdodCAyMDA3IEFwcGxlIEluYy4sIGFsbCByaWdodHMgcmVzZXJ2ZWQunmbcKQAAACN0RVh0aWNjOmRlc2NyaXB0aW9uAEdlbmVyaWMgUkdCIFByb2ZpbGUapziOAAAAAElFTkSuQmCC\"></td>\n      <td align=\"center\">0\n(0.0%)</td>\n    </tr>\n    <tr>\n      <td align=\"left\">catholic\n[integer]</td>\n      <td align=\"left\" style=\"padding:8;vertical-align:middle\"><table style=\"border-collapse:collapse;border:none;margin:0\"><tr style=\"background-color:transparent\"><td style=\"padding:0;margin:0;border:0\" align=\"left\">Min  : 0</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0;margin:0;border:0\" align=\"left\">Mean : 0.1</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0;margin:0;border:0\" align=\"left\">Max  : 1</td></tr></table></td>\n      <td align=\"left\" style=\"padding:0;vertical-align:middle\"><table style=\"border-collapse:collapse;border:none;margin:0\"><tr style=\"background-color:transparent\"><td style=\"padding:0 2px 0 7px;margin:0;border:0\" align=\"right\">0</td><td style=\"padding:0 2px;border:0;\" align=\"left\">:</td><td style=\"padding:0 4px 0 6px;margin:0;border:0\" align=\"right\">3914</td><td style=\"padding:0;border:0\" align=\"left\">(</td><td style=\"padding:0 2px;margin:0;border:0\" align=\"right\">89.8%</td><td style=\"padding:0 4px 0 0;border:0\" align=\"left\">)</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0 2px 0 7px;margin:0;border:0\" align=\"right\">1</td><td style=\"padding:0 2px;border:0;\" align=\"left\">:</td><td style=\"padding:0 4px 0 6px;margin:0;border:0\" align=\"right\">447</td><td style=\"padding:0;border:0\" align=\"left\">(</td><td style=\"padding:0 2px;margin:0;border:0\" align=\"right\">10.2%</td><td style=\"padding:0 4px 0 0;border:0\" align=\"left\">)</td></tr></table></td>\n      <td align=\"left\" style=\"vertical-align:middle;padding:0;background-color:transparent;\"><img style=\"border:none;background-color:transparent;padding:0;max-width:max-content;\" src=\"data:image/png;base64, iVBORw0KGgoAAAANSUhEUgAAADUAAAAVCAQAAABMQ27NAAAAAmJLR0QA/4ePzL8AAAAHdElNRQfmDBUAGS7pKLxEAAAAUUlEQVRIx2P8z0AvwEQ3m4apVSzInGlUj7gsRhxWMTCEU9WilSi84RlXA5Us0EOXplbBQDYjacbgAlm4rQqnod+GZ7IYnlbRMbEzjlaNQ8YqACkRCFs153sNAAAAJXRFWHRkYXRlOmNyZWF0ZQAyMDIyLTEyLTIxVDAwOjI1OjQ2KzAwOjAwEJTa1gAAACV0RVh0ZGF0ZTptb2RpZnkAMjAyMi0xMi0yMVQwMDoyNTo0NiswMDowMGHJYmoAAAA9dEVYdGljYzpjb3B5cmlnaHQAQ29weXJpZ2h0IDIwMDcgQXBwbGUgSW5jLiwgYWxsIHJpZ2h0cyByZXNlcnZlZC6eZtwpAAAAI3RFWHRpY2M6ZGVzY3JpcHRpb24AR2VuZXJpYyBSR0IgUHJvZmlsZRqnOI4AAAAASUVORK5CYII=\"></td>\n      <td align=\"center\">0\n(0.0%)</td>\n    </tr>\n    <tr>\n      <td align=\"left\">frsthalf\n[integer]</td>\n      <td align=\"left\" style=\"padding:8;vertical-align:middle\"><table style=\"border-collapse:collapse;border:none;margin:0\"><tr style=\"background-color:transparent\"><td style=\"padding:0;margin:0;border:0\" align=\"left\">Min  : 0</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0;margin:0;border:0\" align=\"left\">Mean : 0.5</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0;margin:0;border:0\" align=\"left\">Max  : 1</td></tr></table></td>\n      <td align=\"left\" style=\"padding:0;vertical-align:middle\"><table style=\"border-collapse:collapse;border:none;margin:0\"><tr style=\"background-color:transparent\"><td style=\"padding:0 2px 0 7px;margin:0;border:0\" align=\"right\">0</td><td style=\"padding:0 2px;border:0;\" align=\"left\">:</td><td style=\"padding:0 4px 0 6px;margin:0;border:0\" align=\"right\">2004</td><td style=\"padding:0;border:0\" align=\"left\">(</td><td style=\"padding:0 2px;margin:0;border:0\" align=\"right\">46.0%</td><td style=\"padding:0 4px 0 0;border:0\" align=\"left\">)</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0 2px 0 7px;margin:0;border:0\" align=\"right\">1</td><td style=\"padding:0 2px;border:0;\" align=\"left\">:</td><td style=\"padding:0 4px 0 6px;margin:0;border:0\" align=\"right\">2357</td><td style=\"padding:0;border:0\" align=\"left\">(</td><td style=\"padding:0 2px;margin:0;border:0\" align=\"right\">54.0%</td><td style=\"padding:0 4px 0 0;border:0\" align=\"left\">)</td></tr></table></td>\n      <td align=\"left\" style=\"vertical-align:middle;padding:0;background-color:transparent;\"><img style=\"border:none;background-color:transparent;padding:0;max-width:max-content;\" src=\"data:image/png;base64, iVBORw0KGgoAAAANSUhEUgAAACUAAAAVCAQAAABr7e8lAAAAAmJLR0QA/4ePzL8AAAAHdElNRQfmDBUAGS7pKLxEAAAAU0lEQVQ4y2P8z0AtwEQ1kwapUSzInGlEB1w2I4T+j8soBoZwogxaSWsPDk6j0MJqJXmmYDOKWDAVFnWMOI0iLgax+2FwBvvgNIqKiYFxtOgjGgAAwK8KGrKo6AoAAAAldEVYdGRhdGU6Y3JlYXRlADIwMjItMTItMjFUMDA6MjU6NDYrMDA6MDAQlNrWAAAAJXRFWHRkYXRlOm1vZGlmeQAyMDIyLTEyLTIxVDAwOjI1OjQ2KzAwOjAwYcliagAAAD10RVh0aWNjOmNvcHlyaWdodABDb3B5cmlnaHQgMjAwNyBBcHBsZSBJbmMuLCBhbGwgcmlnaHRzIHJlc2VydmVkLp5m3CkAAAAjdEVYdGljYzpkZXNjcmlwdGlvbgBHZW5lcmljIFJHQiBQcm9maWxlGqc4jgAAAABJRU5ErkJggg==\"></td>\n      <td align=\"center\">0\n(0.0%)</td>\n    </tr>\n    <tr>\n      <td align=\"left\">educ0\n[integer]</td>\n      <td align=\"left\" style=\"padding:8;vertical-align:middle\"><table style=\"border-collapse:collapse;border:none;margin:0\"><tr style=\"background-color:transparent\"><td style=\"padding:0;margin:0;border:0\" align=\"left\">Min  : 0</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0;margin:0;border:0\" align=\"left\">Mean : 0.2</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0;margin:0;border:0\" align=\"left\">Max  : 1</td></tr></table></td>\n      <td align=\"left\" style=\"padding:0;vertical-align:middle\"><table style=\"border-collapse:collapse;border:none;margin:0\"><tr style=\"background-color:transparent\"><td style=\"padding:0 2px 0 7px;margin:0;border:0\" align=\"right\">0</td><td style=\"padding:0 2px;border:0;\" align=\"left\">:</td><td style=\"padding:0 4px 0 6px;margin:0;border:0\" align=\"right\">3455</td><td style=\"padding:0;border:0\" align=\"left\">(</td><td style=\"padding:0 2px;margin:0;border:0\" align=\"right\">79.2%</td><td style=\"padding:0 4px 0 0;border:0\" align=\"left\">)</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0 2px 0 7px;margin:0;border:0\" align=\"right\">1</td><td style=\"padding:0 2px;border:0;\" align=\"left\">:</td><td style=\"padding:0 4px 0 6px;margin:0;border:0\" align=\"right\">906</td><td style=\"padding:0;border:0\" align=\"left\">(</td><td style=\"padding:0 2px;margin:0;border:0\" align=\"right\">20.8%</td><td style=\"padding:0 4px 0 0;border:0\" align=\"left\">)</td></tr></table></td>\n      <td align=\"left\" style=\"vertical-align:middle;padding:0;background-color:transparent;\"><img style=\"border:none;background-color:transparent;padding:0;max-width:max-content;\" src=\"data:image/png;base64, iVBORw0KGgoAAAANSUhEUgAAADAAAAAVCAQAAACqaqWJAAAAAmJLR0QA/4ePzL8AAAAHdElNRQfmDBUAGS7pKLxEAAAAUklEQVQ4y2P8z0BbwERj84eBBSzInGlUipAsRhwWMDCEU8H4lSi8oR8H9I1k9PCjgQWYIJuRGGNQQRZuC9BTEeU+GvqRPPQtoHkyZRytcAbcAgD4PAhbcvcO1wAAACV0RVh0ZGF0ZTpjcmVhdGUAMjAyMi0xMi0yMVQwMDoyNTo0NiswMDowMBCU2tYAAAAldEVYdGRhdGU6bW9kaWZ5ADIwMjItMTItMjFUMDA6MjU6NDYrMDA6MDBhyWJqAAAAPXRFWHRpY2M6Y29weXJpZ2h0AENvcHlyaWdodCAyMDA3IEFwcGxlIEluYy4sIGFsbCByaWdodHMgcmVzZXJ2ZWQunmbcKQAAACN0RVh0aWNjOmRlc2NyaXB0aW9uAEdlbmVyaWMgUkdCIFByb2ZpbGUapziOAAAAAElFTkSuQmCC\"></td>\n      <td align=\"center\">0\n(0.0%)</td>\n    </tr>\n    <tr>\n      <td align=\"left\">evermarr\n[integer]</td>\n      <td align=\"left\" style=\"padding:8;vertical-align:middle\"><table style=\"border-collapse:collapse;border:none;margin:0\"><tr style=\"background-color:transparent\"><td style=\"padding:0;margin:0;border:0\" align=\"left\">Min  : 0</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0;margin:0;border:0\" align=\"left\">Mean : 0.5</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0;margin:0;border:0\" align=\"left\">Max  : 1</td></tr></table></td>\n      <td align=\"left\" style=\"padding:0;vertical-align:middle\"><table style=\"border-collapse:collapse;border:none;margin:0\"><tr style=\"background-color:transparent\"><td style=\"padding:0 2px 0 7px;margin:0;border:0\" align=\"right\">0</td><td style=\"padding:0 2px;border:0;\" align=\"left\">:</td><td style=\"padding:0 4px 0 6px;margin:0;border:0\" align=\"right\">2282</td><td style=\"padding:0;border:0\" align=\"left\">(</td><td style=\"padding:0 2px;margin:0;border:0\" align=\"right\">52.3%</td><td style=\"padding:0 4px 0 0;border:0\" align=\"left\">)</td></tr><tr style=\"background-color:transparent\"><td style=\"padding:0 2px 0 7px;margin:0;border:0\" align=\"right\">1</td><td style=\"padding:0 2px;border:0;\" align=\"left\">:</td><td style=\"padding:0 4px 0 6px;margin:0;border:0\" align=\"right\">2079</td><td style=\"padding:0;border:0\" align=\"left\">(</td><td style=\"padding:0 2px;margin:0;border:0\" align=\"right\">47.7%</td><td style=\"padding:0 4px 0 0;border:0\" align=\"left\">)</td></tr></table></td>\n      <td align=\"left\" style=\"vertical-align:middle;padding:0;background-color:transparent;\"><img style=\"border:none;background-color:transparent;padding:0;max-width:max-content;\" src=\"data:image/png;base64, iVBORw0KGgoAAAANSUhEUgAAACQAAAAVCAQAAACEL4QbAAAAAmJLR0QA/4ePzL8AAAAHdElNRQfmDBUAGS7pKLxEAAAAUElEQVQ4y2P8z0AdwEQlcwahQSzInGkkBlgWIw6DGBjCSTBmJW28NvgMQgujleSZgmkQ8SCbkYEhC7dBxMYapssHX2APPoOoFv2MowUbQQAA6Y4IW4HaH7EAAAAldEVYdGRhdGU6Y3JlYXRlADIwMjItMTItMjFUMDA6MjU6NDYrMDA6MDAQlNrWAAAAJXRFWHRkYXRlOm1vZGlmeQAyMDIyLTEyLTIxVDAwOjI1OjQ2KzAwOjAwYcliagAAAD10RVh0aWNjOmNvcHlyaWdodABDb3B5cmlnaHQgMjAwNyBBcHBsZSBJbmMuLCBhbGwgcmlnaHRzIHJlc2VydmVkLp5m3CkAAAAjdEVYdGljYzpkZXNjcmlwdGlvbgBHZW5lcmljIFJHQiBQcm9maWxlGqc4jgAAAABJRU5ErkJggg==\"></td>\n      <td align=\"center\">0\n(0.0%)</td>\n    </tr>\n  </tbody>\n</table>\n<p>Generated by <a href='https://github.com/dcomtois/summarytools'>summarytools</a> 1.0.1 (<a href='https://www.r-project.org/'>R</a> version 4.2.2)<br/>2022-12-21</p>\n</div>\n```\n:::\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\nglimpse(Womendata)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\nRows: 4,361\nColumns: 28\n$ X        <int> 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18…\n$ mnthborn <int> 5, 1, 7, 11, 5, 8, 7, 9, 12, 9, 6, 10, 12, 2, 1, 6, 1, 8, 4, …\n$ yearborn <int> 64, 56, 58, 45, 45, 52, 51, 70, 53, 39, 46, 59, 42, 40, 53, 6…\n$ age      <int> 24, 32, 30, 42, 43, 36, 37, 18, 34, 49, 42, 29, 45, 48, 35, 2…\n$ electric <int> 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1…\n$ radio    <int> 1, 1, 0, 0, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1…\n$ tv       <int> 1, 1, 0, 1, 1, 0, 1, 1, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 1, 1, 1…\n$ bicycle  <int> 1, 1, 0, 0, 1, 0, 1, 1, 0, 0, 1, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0…\n$ educ     <int> 12, 13, 5, 4, 11, 7, 16, 10, 5, 4, 15, 7, 0, 4, 12, 7, 7, 5, …\n$ ceb      <int> 0, 3, 1, 3, 2, 1, 4, 0, 1, 0, 3, 3, 4, 10, 3, 0, 4, 2, 0, 1, …\n$ agefbrth <int> NA, 25, 27, 17, 24, 26, 20, NA, 19, NA, 25, 23, 18, 19, 23, N…\n$ children <int> 0, 3, 1, 2, 2, 1, 4, 0, 1, 0, 3, 3, 2, 8, 3, 0, 4, 2, 0, 1, 0…\n$ knowmeth <int> 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1…\n$ usemeth  <int> 0, 1, 0, 0, 1, 1, 1, 1, 1, 0, 1, 1, 0, 1, 1, 1, 1, 0, 1, 1, 1…\n$ monthfm  <int> NA, 11, 6, 1, 3, 11, 5, NA, 7, 11, 6, 1, 1, 10, 1, NA, NA, NA…\n$ yearfm   <int> NA, 80, 83, 61, 66, 76, 78, NA, 72, 61, 70, 84, 66, 66, 74, N…\n$ agefm    <int> NA, 24, 24, 15, 20, 24, 26, NA, 18, 22, 24, 24, 23, 26, 21, N…\n$ idlnchld <int> 2, 3, 5, 3, 2, 4, 4, 4, 4, 4, 3, 6, 6, 4, 3, 4, 5, 1, 2, 3, 2…\n$ heduc    <int> NA, 12, 7, 11, 14, 9, 17, NA, 3, 1, 16, 7, NA, 3, 16, NA, NA,…\n$ agesq    <int> 576, 1024, 900, 1764, 1849, 1296, 1369, 324, 1156, 2401, 1764…\n$ urban    <int> 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1…\n$ urb_educ <int> 12, 13, 5, 4, 11, 7, 16, 10, 5, 4, 15, 7, 0, 4, 12, 7, 7, 5, …\n$ spirit   <int> 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 1, 1, 0, 0, 0, 0, 1, 0, 1, 0…\n$ protest  <int> 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 1, 1, 0, 1, 0, 1, 0, 1…\n$ catholic <int> 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0…\n$ frsthalf <int> 1, 1, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 1, 1, 1, 1, 0, 1, 0, 0…\n$ educ0    <int> 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0…\n$ evermarr <int> 0, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 1, 1, 1…\n```\n:::\n:::\n\n\nWe can see that we have 28 variables and 4361 observations in this dataset.\nThe dependent variable of interest - number of living children Then I will perform data manipulation to tidy the data.\nThe variables of interest are age, yearborn, month born, urban education and many more variables that seem intriguing.\nVariables like radio, bicycle, electric can be ignored in this.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nhead(Womendata)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n  X mnthborn yearborn age electric radio tv bicycle educ ceb agefbrth children\n1 1        5       64  24        1     1  1       1   12   0       NA        0\n2 2        1       56  32        1     1  1       1   13   3       25        3\n3 3        7       58  30        1     0  0       0    5   1       27        1\n4 4       11       45  42        1     0  1       0    4   3       17        2\n5 5        5       45  43        1     1  1       1   11   2       24        2\n6 6        8       52  36        1     0  0       0    7   1       26        1\n  knowmeth usemeth monthfm yearfm agefm idlnchld heduc agesq urban urb_educ\n1        1       0      NA     NA    NA        2    NA   576     1       12\n2        1       1      11     80    24        3    12  1024     1       13\n3        1       0       6     83    24        5     7   900     1        5\n4        1       0       1     61    15        3    11  1764     1        4\n5        1       1       3     66    20        2    14  1849     1       11\n6        1       1      11     76    24        4     9  1296     1        7\n  spirit protest catholic frsthalf educ0 evermarr\n1      0       0        0        1     0        0\n2      0       0        0        1     0        1\n3      1       0        0        0     0        1\n4      0       0        0        0     0        1\n5      0       1        0        1     0        1\n6      0       0        0        0     0        1\n```\n:::\n:::\n\n\n##Tidying the data\n\n\n::: {.cell}\n\n```{.r .cell-code}\nWomendata <- data.frame(Womendata)\n\nWomendata$mnthborn <- as.factor(Womendata$mnthborn)\nWomendata$age <- as.factor(Womendata$age)\nWomendata$electric <- as.factor(Womendata$electric)\nWomendata$radio <- as.factor(Womendata$radio)\nWomendata$tv <- as.factor(Womendata$tv)\nWomendata$bicycle <- as.factor(Womendata$bicycle)\nWomendata$educ <- as.factor(Womendata$educ)\nWomendata$children <- as.factor(Womendata$children)\nWomendata$knowmeth <- as.factor(Womendata$knowmeth)\n```\n:::\n\n\nThe dependent variable of interest -- number of living children (children) or number of children ever born (ceb) is a count variable.\n\n\n::: {.cell}\n\n```{.r .cell-code}\ntable(is.na(Womendata))\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n\n FALSE   TRUE \n111561  10547 \n```\n:::\n:::\n\n\nHere we can see that we have some missing values in our dataset.\nPlotting the missing values we can check if they are important or not using 'plot_missing' by loading library DataExplorer.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nplot_missing(data = Womendata, geom_label_args = list(size = 1.4), theme_config=list(axis.text=element_text(size = 6 )))\n```\n\n::: {.cell-output-display}\n![](Final-Project-_Kaushika-Potluri_files/figure-html/unnamed-chunk-10-1.png){width=672}\n:::\n:::\n\n\nWe can see how these missing values do not cause much of an issue since these missing observations(parameters) convey less important information than the other parameters.\nHence we can ignore these values.\n\n##Removing missing values and parameters that are not required The aim is to estimate the effect of education on women's fertility flexibly, while controlling for possible linear and non-linear effects of observable and unobservable confounding factors, and to analyse how the effect of education changes when considering different expectiles of the response variable distribution.\nWe also include two variables regarding the knowledge about and the use of birth control methods as well as marital status.All three obviously influence the number of children.\nFurther, we include variables indicating wealth, e.g. about the availability of electricity, a television set or a bicycle.\n\nExcluding variables that have no significant importance from our data.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nWomendata <- subset(Womendata, select = -c(agefm,yearfm,monthfm,heduc))\n```\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\nWomendatacleaned <-Womendata[complete.cases(Womendata), ]\nplot_missing(data = Womendatacleaned, geom_label_args = list(size = 1.4), theme_config=list(axis.text=element_text(size = 6 )))\n```\n\n::: {.cell-output-display}\n![](Final-Project-_Kaushika-Potluri_files/figure-html/unnamed-chunk-12-1.png){width=672}\n:::\n:::\n\n\n## Detecting outliers.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nWomendata %>%\n  ggplot(aes(educ)) +\n  geom_boxplot() +\n  coord_flip()\n```\n\n::: {.cell-output-display}\n![](Final-Project-_Kaushika-Potluri_files/figure-html/unnamed-chunk-13-1.png){width=672}\n:::\n:::\n\n\nWe can see that the variable educ i.e education has some outliers.\nMostly for having education of more than 15 years, but they cannot potentially affect the data set.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nWomendata %>%\n  ggplot(aes(age)) +\n  geom_boxplot() +\n  coord_flip()\n```\n\n::: {.cell-output-display}\n![](Final-Project-_Kaushika-Potluri_files/figure-html/unnamed-chunk-14-1.png){width=672}\n:::\n:::\n\n\nFrom above box plot, age variable has no outliers.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nWomendata %>%\n  ggplot(aes(children)) +\n  geom_boxplot() +\n  coord_flip()\n```\n\n::: {.cell-output-display}\n![](Final-Project-_Kaushika-Potluri_files/figure-html/unnamed-chunk-15-1.png){width=672}\n:::\n:::\n\n\nFrom the above plot we can see that the variable children does have outliers but nothing to be concerned about.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nWomendata %>%\n  ggplot(aes(urb_educ)) +\n  geom_boxplot() +\n  coord_flip()\n```\n\n::: {.cell-output-display}\n![](Final-Project-_Kaushika-Potluri_files/figure-html/unnamed-chunk-16-1.png){width=672}\n:::\n:::\n\n\nFrom the above plot we can see that the variable urban education does have outliers but nothing to be concerned about.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nWomendata %>%\n  ggplot(aes(yearborn)) +\n  geom_boxplot() +\n  coord_flip()\n```\n\n::: {.cell-output-display}\n![](Final-Project-_Kaushika-Potluri_files/figure-html/unnamed-chunk-17-1.png){width=672}\n:::\n:::\n\n\nFrom the above box plot, yearborn variable has no outliers.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nWomendata %>%\n  ggplot(aes(mnthborn)) +\n  geom_boxplot() +\n  coord_flip()\n```\n\n::: {.cell-output-display}\n![](Final-Project-_Kaushika-Potluri_files/figure-html/unnamed-chunk-18-1.png){width=672}\n:::\n:::\n\n\nFrom the above box plot, mnthborn variable has no outliers.\n\n#Exploratory Data Analysis (EDA) Here variables indicating wealth, e.g. about the availability of electricity, a television set or a bicycle can say something about a women's knowledge & use of birth control/ and its impact on how many children they have.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nggplot(Womendatacleaned,aes(x=factor(children),fill=factor(tv)))+\n  \ngeom_bar()+theme(axis.text.x = element_text(face=\"bold\", size=15),axis.text.y = element_text(face=\"bold\", size=15))+\n  \nlabs(\n    title = \"Number of Children based on if they own a Tv or not\",\n    x = \"Number of children\",\n    y = \"Count\",size=15) +\n   \nscale_fill_manual(\n    name = \"Access to Telivision or not\",\n    breaks = c(\"0\", \"1\"),\n    labels = c(\"No Telivision\", \"Owns/ has access to a telivision\"),\n    values = c(\"0\" = \"orange\", \"1\"=\"yellow\")\n  )\n```\n\n::: {.cell-output-display}\n![](Final-Project-_Kaushika-Potluri_files/figure-html/unnamed-chunk-19-1.png){width=672}\n:::\n:::\n\n\nWe can see that most mothers do not own a TV here.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nggplot(Womendatacleaned,aes(x=factor(children),fill=factor(radio)))+\n  \ngeom_bar()+theme(axis.text.x = element_text(face=\"bold\", size=15),axis.text.y = element_text(face=\"bold\", size=15))+\n  \nlabs(\n    title = \"Number of Children based on if they own a radio or not\",\n    x = \"Number of children\",\n    y = \"Count\",size=15) +\n   \nscale_fill_manual(\n    name = \"Access to Radio or not\",\n    breaks = c(\"0\", \"1\"),\n    labels = c(\"No Radio\", \"Owns/ has access to a Radio\"),\n    values = c(\"0\" = \"green\", \"1\"=\"pink\")\n  )\n```\n\n::: {.cell-output-display}\n![](Final-Project-_Kaushika-Potluri_files/figure-html/unnamed-chunk-20-1.png){width=672}\n:::\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\nggplot(Womendatacleaned,aes(x=factor(children),fill=factor(electric)))+\n  \ngeom_bar()+theme(axis.text.x = element_text(face=\"bold\", size=15),axis.text.y = element_text(face=\"bold\", size=15))+\n  \nlabs(\n    title = \"Number of Children based on if they have electricity or not\",\n    x = \"Number of children\",\n    y = \"Count\",size=15) +\n   \nscale_fill_manual(\n    name = \"Access to Electricity or not\",\n    breaks = c(\"0\", \"1\"),\n    labels = c(\"No Electricity\", \"Has access to Electricity\"),\n    values = c(\"0\" = \"pink\", \"1\"=\"yellow\")\n  )\n```\n\n::: {.cell-output-display}\n![](Final-Project-_Kaushika-Potluri_files/figure-html/unnamed-chunk-21-1.png){width=672}\n:::\n:::\n\n\nHere from our bar graph we can see that most mothers that have children do not have electricity.\n\n\n::: {.cell}\n\n```{.r .cell-code}\np <- Womendata %>%\n  ggplot() +\n  geom_bar(aes(Womendata$usemeth)) +\n  ggtitle(\"Individuals that ever used birth control\") + labs(title = \"Individuals that have ever used  birth control\", \nx = \"No. of individuals that have ever used birth control\",y = \"Count\")\n  theme_classic()\n```\n\n::: {.cell-output .cell-output-stdout}\n```\nList of 94\n $ line                      :List of 6\n  ..$ colour       : chr \"black\"\n  ..$ linewidth    : num 0.5\n  ..$ linetype     : num 1\n  ..$ lineend      : chr \"butt\"\n  ..$ arrow        : logi FALSE\n  ..$ inherit.blank: logi TRUE\n  ..- attr(*, \"class\")= chr [1:2] \"element_line\" \"element\"\n $ rect                      :List of 5\n  ..$ fill         : chr \"white\"\n  ..$ colour       : chr \"black\"\n  ..$ linewidth    : num 0.5\n  ..$ linetype     : num 1\n  ..$ inherit.blank: logi TRUE\n  ..- attr(*, \"class\")= chr [1:2] \"element_rect\" \"element\"\n $ text                      :List of 11\n  ..$ family       : chr \"\"\n  ..$ face         : chr \"plain\"\n  ..$ colour       : chr \"black\"\n  ..$ size         : num 11\n  ..$ hjust        : num 0.5\n  ..$ vjust        : num 0.5\n  ..$ angle        : num 0\n  ..$ lineheight   : num 0.9\n  ..$ margin       : 'margin' num [1:4] 0points 0points 0points 0points\n  .. ..- attr(*, \"unit\")= int 8\n  ..$ debug        : logi FALSE\n  ..$ inherit.blank: logi TRUE\n  ..- attr(*, \"class\")= chr [1:2] \"element_text\" \"element\"\n $ title                     : NULL\n $ aspect.ratio              : NULL\n $ axis.title                : NULL\n $ axis.title.x              :List of 11\n  ..$ family       : NULL\n  ..$ face         : NULL\n  ..$ colour       : NULL\n  ..$ size         : NULL\n  ..$ hjust        : NULL\n  ..$ vjust        : num 1\n  ..$ angle        : NULL\n  ..$ lineheight   : NULL\n  ..$ margin       : 'margin' num [1:4] 2.75points 0points 0points 0points\n  .. ..- attr(*, \"unit\")= int 8\n  ..$ debug        : NULL\n  ..$ inherit.blank: logi TRUE\n  ..- attr(*, \"class\")= chr [1:2] \"element_text\" \"element\"\n $ axis.title.x.top          :List of 11\n  ..$ family       : NULL\n  ..$ face         : NULL\n  ..$ colour       : NULL\n  ..$ size         : NULL\n  ..$ hjust        : NULL\n  ..$ vjust        : num 0\n  ..$ angle        : NULL\n  ..$ lineheight   : NULL\n  ..$ margin       : 'margin' num [1:4] 0points 0points 2.75points 0points\n  .. ..- attr(*, \"unit\")= int 8\n  ..$ debug        : NULL\n  ..$ inherit.blank: logi TRUE\n  ..- attr(*, \"class\")= chr [1:2] \"element_text\" \"element\"\n $ axis.title.x.bottom       : NULL\n $ axis.title.y              :List of 11\n  ..$ family       : NULL\n  ..$ face         : NULL\n  ..$ colour       : NULL\n  ..$ size         : NULL\n  ..$ hjust        : NULL\n  ..$ vjust        : num 1\n  ..$ angle        : num 90\n  ..$ lineheight   : NULL\n  ..$ margin       : 'margin' num [1:4] 0points 2.75points 0points 0points\n  .. ..- attr(*, \"unit\")= int 8\n  ..$ debug        : NULL\n  ..$ inherit.blank: logi TRUE\n  ..- attr(*, \"class\")= chr [1:2] \"element_text\" \"element\"\n $ axis.title.y.left         : NULL\n $ axis.title.y.right        :List of 11\n  ..$ family       : NULL\n  ..$ face         : NULL\n  ..$ colour       : NULL\n  ..$ size         : NULL\n  ..$ hjust        : NULL\n  ..$ vjust        : num 0\n  ..$ angle        : num -90\n  ..$ lineheight   : NULL\n  ..$ margin       : 'margin' num [1:4] 0points 0points 0points 2.75points\n  .. ..- attr(*, \"unit\")= int 8\n  ..$ debug        : NULL\n  ..$ inherit.blank: logi TRUE\n  ..- attr(*, \"class\")= chr [1:2] \"element_text\" \"element\"\n $ axis.text                 :List of 11\n  ..$ family       : NULL\n  ..$ face         : NULL\n  ..$ colour       : chr \"grey30\"\n  ..$ size         : 'rel' num 0.8\n  ..$ hjust        : NULL\n  ..$ vjust        : NULL\n  ..$ angle        : NULL\n  ..$ lineheight   : NULL\n  ..$ margin       : NULL\n  ..$ debug        : NULL\n  ..$ inherit.blank: logi TRUE\n  ..- attr(*, \"class\")= chr [1:2] \"element_text\" \"element\"\n $ axis.text.x               :List of 11\n  ..$ family       : NULL\n  ..$ face         : NULL\n  ..$ colour       : NULL\n  ..$ size         : NULL\n  ..$ hjust        : NULL\n  ..$ vjust        : num 1\n  ..$ angle        : NULL\n  ..$ lineheight   : NULL\n  ..$ margin       : 'margin' num [1:4] 2.2points 0points 0points 0points\n  .. ..- attr(*, \"unit\")= int 8\n  ..$ debug        : NULL\n  ..$ inherit.blank: logi TRUE\n  ..- attr(*, \"class\")= chr [1:2] \"element_text\" \"element\"\n $ axis.text.x.top           :List of 11\n  ..$ family       : NULL\n  ..$ face         : NULL\n  ..$ colour       : NULL\n  ..$ size         : NULL\n  ..$ hjust        : NULL\n  ..$ vjust        : num 0\n  ..$ angle        : NULL\n  ..$ lineheight   : NULL\n  ..$ margin       : 'margin' num [1:4] 0points 0points 2.2points 0points\n  .. ..- attr(*, \"unit\")= int 8\n  ..$ debug        : NULL\n  ..$ inherit.blank: logi TRUE\n  ..- attr(*, \"class\")= chr [1:2] \"element_text\" \"element\"\n $ axis.text.x.bottom        : NULL\n $ axis.text.y               :List of 11\n  ..$ family       : NULL\n  ..$ face         : NULL\n  ..$ colour       : NULL\n  ..$ size         : NULL\n  ..$ hjust        : num 1\n  ..$ vjust        : NULL\n  ..$ angle        : NULL\n  ..$ lineheight   : NULL\n  ..$ margin       : 'margin' num [1:4] 0points 2.2points 0points 0points\n  .. ..- attr(*, \"unit\")= int 8\n  ..$ debug        : NULL\n  ..$ inherit.blank: logi TRUE\n  ..- attr(*, \"class\")= chr [1:2] \"element_text\" \"element\"\n $ axis.text.y.left          : NULL\n $ axis.text.y.right         :List of 11\n  ..$ family       : NULL\n  ..$ face         : NULL\n  ..$ colour       : NULL\n  ..$ size         : NULL\n  ..$ hjust        : num 0\n  ..$ vjust        : NULL\n  ..$ angle        : NULL\n  ..$ lineheight   : NULL\n  ..$ margin       : 'margin' num [1:4] 0points 0points 0points 2.2points\n  .. ..- attr(*, \"unit\")= int 8\n  ..$ debug        : NULL\n  ..$ inherit.blank: logi TRUE\n  ..- attr(*, \"class\")= chr [1:2] \"element_text\" \"element\"\n $ axis.ticks                :List of 6\n  ..$ colour       : chr \"grey20\"\n  ..$ linewidth    : NULL\n  ..$ linetype     : NULL\n  ..$ lineend      : NULL\n  ..$ arrow        : logi FALSE\n  ..$ inherit.blank: logi TRUE\n  ..- attr(*, \"class\")= chr [1:2] \"element_line\" \"element\"\n $ axis.ticks.x              : NULL\n $ axis.ticks.x.top          : NULL\n $ axis.ticks.x.bottom       : NULL\n $ axis.ticks.y              : NULL\n $ axis.ticks.y.left         : NULL\n $ axis.ticks.y.right        : NULL\n $ axis.ticks.length         : 'simpleUnit' num 2.75points\n  ..- attr(*, \"unit\")= int 8\n $ axis.ticks.length.x       : NULL\n $ axis.ticks.length.x.top   : NULL\n $ axis.ticks.length.x.bottom: NULL\n $ axis.ticks.length.y       : NULL\n $ axis.ticks.length.y.left  : NULL\n $ axis.ticks.length.y.right : NULL\n $ axis.line                 :List of 6\n  ..$ colour       : chr \"black\"\n  ..$ linewidth    : 'rel' num 1\n  ..$ linetype     : NULL\n  ..$ lineend      : NULL\n  ..$ arrow        : logi FALSE\n  ..$ inherit.blank: logi TRUE\n  ..- attr(*, \"class\")= chr [1:2] \"element_line\" \"element\"\n $ axis.line.x               : NULL\n $ axis.line.x.top           : NULL\n $ axis.line.x.bottom        : NULL\n $ axis.line.y               : NULL\n $ axis.line.y.left          : NULL\n $ axis.line.y.right         : NULL\n $ legend.background         :List of 5\n  ..$ fill         : NULL\n  ..$ colour       : logi NA\n  ..$ linewidth    : NULL\n  ..$ linetype     : NULL\n  ..$ inherit.blank: logi TRUE\n  ..- attr(*, \"class\")= chr [1:2] \"element_rect\" \"element\"\n $ legend.margin             : 'margin' num [1:4] 5.5points 5.5points 5.5points 5.5points\n  ..- attr(*, \"unit\")= int 8\n $ legend.spacing            : 'simpleUnit' num 11points\n  ..- attr(*, \"unit\")= int 8\n $ legend.spacing.x          : NULL\n $ legend.spacing.y          : NULL\n $ legend.key                : list()\n  ..- attr(*, \"class\")= chr [1:2] \"element_blank\" \"element\"\n $ legend.key.size           : 'simpleUnit' num 1.2lines\n  ..- attr(*, \"unit\")= int 3\n $ legend.key.height         : NULL\n $ legend.key.width          : NULL\n $ legend.text               :List of 11\n  ..$ family       : NULL\n  ..$ face         : NULL\n  ..$ colour       : NULL\n  ..$ size         : 'rel' num 0.8\n  ..$ hjust        : NULL\n  ..$ vjust        : NULL\n  ..$ angle        : NULL\n  ..$ lineheight   : NULL\n  ..$ margin       : NULL\n  ..$ debug        : NULL\n  ..$ inherit.blank: logi TRUE\n  ..- attr(*, \"class\")= chr [1:2] \"element_text\" \"element\"\n $ legend.text.align         : NULL\n $ legend.title              :List of 11\n  ..$ family       : NULL\n  ..$ face         : NULL\n  ..$ colour       : NULL\n  ..$ size         : NULL\n  ..$ hjust        : num 0\n  ..$ vjust        : NULL\n  ..$ angle        : NULL\n  ..$ lineheight   : NULL\n  ..$ margin       : NULL\n  ..$ debug        : NULL\n  ..$ inherit.blank: logi TRUE\n  ..- attr(*, \"class\")= chr [1:2] \"element_text\" \"element\"\n $ legend.title.align        : NULL\n $ legend.position           : chr \"right\"\n $ legend.direction          : NULL\n $ legend.justification      : chr \"center\"\n $ legend.box                : NULL\n $ legend.box.just           : NULL\n $ legend.box.margin         : 'margin' num [1:4] 0cm 0cm 0cm 0cm\n  ..- attr(*, \"unit\")= int 1\n $ legend.box.background     : list()\n  ..- attr(*, \"class\")= chr [1:2] \"element_blank\" \"element\"\n $ legend.box.spacing        : 'simpleUnit' num 11points\n  ..- attr(*, \"unit\")= int 8\n $ panel.background          :List of 5\n  ..$ fill         : chr \"white\"\n  ..$ colour       : logi NA\n  ..$ linewidth    : NULL\n  ..$ linetype     : NULL\n  ..$ inherit.blank: logi TRUE\n  ..- attr(*, \"class\")= chr [1:2] \"element_rect\" \"element\"\n $ panel.border              : list()\n  ..- attr(*, \"class\")= chr [1:2] \"element_blank\" \"element\"\n $ panel.spacing             : 'simpleUnit' num 5.5points\n  ..- attr(*, \"unit\")= int 8\n $ panel.spacing.x           : NULL\n $ panel.spacing.y           : NULL\n $ panel.grid                :List of 6\n  ..$ colour       : chr \"grey92\"\n  ..$ linewidth    : NULL\n  ..$ linetype     : NULL\n  ..$ lineend      : NULL\n  ..$ arrow        : logi FALSE\n  ..$ inherit.blank: logi TRUE\n  ..- attr(*, \"class\")= chr [1:2] \"element_line\" \"element\"\n $ panel.grid.major          : list()\n  ..- attr(*, \"class\")= chr [1:2] \"element_blank\" \"element\"\n $ panel.grid.minor          : list()\n  ..- attr(*, \"class\")= chr [1:2] \"element_blank\" \"element\"\n $ panel.grid.major.x        : NULL\n $ panel.grid.major.y        : NULL\n $ panel.grid.minor.x        : NULL\n $ panel.grid.minor.y        : NULL\n $ panel.ontop               : logi FALSE\n $ plot.background           :List of 5\n  ..$ fill         : NULL\n  ..$ colour       : chr \"white\"\n  ..$ linewidth    : NULL\n  ..$ linetype     : NULL\n  ..$ inherit.blank: logi TRUE\n  ..- attr(*, \"class\")= chr [1:2] \"element_rect\" \"element\"\n $ plot.title                :List of 11\n  ..$ family       : NULL\n  ..$ face         : NULL\n  ..$ colour       : NULL\n  ..$ size         : 'rel' num 1.2\n  ..$ hjust        : num 0\n  ..$ vjust        : num 1\n  ..$ angle        : NULL\n  ..$ lineheight   : NULL\n  ..$ margin       : 'margin' num [1:4] 0points 0points 5.5points 0points\n  .. ..- attr(*, \"unit\")= int 8\n  ..$ debug        : NULL\n  ..$ inherit.blank: logi TRUE\n  ..- attr(*, \"class\")= chr [1:2] \"element_text\" \"element\"\n $ plot.title.position       : chr \"panel\"\n $ plot.subtitle             :List of 11\n  ..$ family       : NULL\n  ..$ face         : NULL\n  ..$ colour       : NULL\n  ..$ size         : NULL\n  ..$ hjust        : num 0\n  ..$ vjust        : num 1\n  ..$ angle        : NULL\n  ..$ lineheight   : NULL\n  ..$ margin       : 'margin' num [1:4] 0points 0points 5.5points 0points\n  .. ..- attr(*, \"unit\")= int 8\n  ..$ debug        : NULL\n  ..$ inherit.blank: logi TRUE\n  ..- attr(*, \"class\")= chr [1:2] \"element_text\" \"element\"\n $ plot.caption              :List of 11\n  ..$ family       : NULL\n  ..$ face         : NULL\n  ..$ colour       : NULL\n  ..$ size         : 'rel' num 0.8\n  ..$ hjust        : num 1\n  ..$ vjust        : num 1\n  ..$ angle        : NULL\n  ..$ lineheight   : NULL\n  ..$ margin       : 'margin' num [1:4] 5.5points 0points 0points 0points\n  .. ..- attr(*, \"unit\")= int 8\n  ..$ debug        : NULL\n  ..$ inherit.blank: logi TRUE\n  ..- attr(*, \"class\")= chr [1:2] \"element_text\" \"element\"\n $ plot.caption.position     : chr \"panel\"\n $ plot.tag                  :List of 11\n  ..$ family       : NULL\n  ..$ face         : NULL\n  ..$ colour       : NULL\n  ..$ size         : 'rel' num 1.2\n  ..$ hjust        : num 0.5\n  ..$ vjust        : num 0.5\n  ..$ angle        : NULL\n  ..$ lineheight   : NULL\n  ..$ margin       : NULL\n  ..$ debug        : NULL\n  ..$ inherit.blank: logi TRUE\n  ..- attr(*, \"class\")= chr [1:2] \"element_text\" \"element\"\n $ plot.tag.position         : chr \"topleft\"\n $ plot.margin               : 'margin' num [1:4] 5.5points 5.5points 5.5points 5.5points\n  ..- attr(*, \"unit\")= int 8\n $ strip.background          :List of 5\n  ..$ fill         : chr \"white\"\n  ..$ colour       : chr \"black\"\n  ..$ linewidth    : 'rel' num 2\n  ..$ linetype     : NULL\n  ..$ inherit.blank: logi TRUE\n  ..- attr(*, \"class\")= chr [1:2] \"element_rect\" \"element\"\n $ strip.background.x        : NULL\n $ strip.background.y        : NULL\n $ strip.clip                : chr \"inherit\"\n $ strip.placement           : chr \"inside\"\n $ strip.text                :List of 11\n  ..$ family       : NULL\n  ..$ face         : NULL\n  ..$ colour       : chr \"grey10\"\n  ..$ size         : 'rel' num 0.8\n  ..$ hjust        : NULL\n  ..$ vjust        : NULL\n  ..$ angle        : NULL\n  ..$ lineheight   : NULL\n  ..$ margin       : 'margin' num [1:4] 4.4points 4.4points 4.4points 4.4points\n  .. ..- attr(*, \"unit\")= int 8\n  ..$ debug        : NULL\n  ..$ inherit.blank: logi TRUE\n  ..- attr(*, \"class\")= chr [1:2] \"element_text\" \"element\"\n $ strip.text.x              : NULL\n $ strip.text.y              :List of 11\n  ..$ family       : NULL\n  ..$ face         : NULL\n  ..$ colour       : NULL\n  ..$ size         : NULL\n  ..$ hjust        : NULL\n  ..$ vjust        : NULL\n  ..$ angle        : num -90\n  ..$ lineheight   : NULL\n  ..$ margin       : NULL\n  ..$ debug        : NULL\n  ..$ inherit.blank: logi TRUE\n  ..- attr(*, \"class\")= chr [1:2] \"element_text\" \"element\"\n $ strip.switch.pad.grid     : 'simpleUnit' num 2.75points\n  ..- attr(*, \"unit\")= int 8\n $ strip.switch.pad.wrap     : 'simpleUnit' num 2.75points\n  ..- attr(*, \"unit\")= int 8\n $ strip.text.y.left         :List of 11\n  ..$ family       : NULL\n  ..$ face         : NULL\n  ..$ colour       : NULL\n  ..$ size         : NULL\n  ..$ hjust        : NULL\n  ..$ vjust        : NULL\n  ..$ angle        : num 90\n  ..$ lineheight   : NULL\n  ..$ margin       : NULL\n  ..$ debug        : NULL\n  ..$ inherit.blank: logi TRUE\n  ..- attr(*, \"class\")= chr [1:2] \"element_text\" \"element\"\n - attr(*, \"class\")= chr [1:2] \"theme\" \"gg\"\n - attr(*, \"complete\")= logi TRUE\n - attr(*, \"validate\")= logi TRUE\n```\n:::\n\n```{.r .cell-code}\np\n```\n\n::: {.cell-output .cell-output-stderr}\n```\nWarning: Use of `Womendata$usemeth` is discouraged.\nℹ Use `usemeth` instead.\n```\n:::\n\n::: {.cell-output .cell-output-stderr}\n```\nWarning: Removed 71 rows containing non-finite values (`stat_count()`).\n```\n:::\n\n::: {.cell-output-display}\n![](Final-Project-_Kaushika-Potluri_files/figure-html/unnamed-chunk-22-1.png){width=672}\n:::\n:::\n\n\nMajority of women have used birth control atleast once in their life.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nk <- Womendata %>%\n  ggplot() +\n  geom_bar(aes(Womendata$knowmeth)) +\n  ggtitle(\"Individuals that know about birth control\") + labs(title = \"Individual knows about birth control\", \nx = \"No. of individuals that know about birth control\",y = \"Count\")\n  theme_classic()\n```\n\n::: {.cell-output .cell-output-stdout}\n```\nList of 94\n $ line                      :List of 6\n  ..$ colour       : chr \"black\"\n  ..$ linewidth    : num 0.5\n  ..$ linetype     : num 1\n  ..$ lineend      : chr \"butt\"\n  ..$ arrow        : logi FALSE\n  ..$ inherit.blank: logi TRUE\n  ..- attr(*, \"class\")= chr [1:2] \"element_line\" \"element\"\n $ rect                      :List of 5\n  ..$ fill         : chr \"white\"\n  ..$ colour       : chr \"black\"\n  ..$ linewidth    : num 0.5\n  ..$ linetype     : num 1\n  ..$ inherit.blank: logi TRUE\n  ..- attr(*, \"class\")= chr [1:2] \"element_rect\" \"element\"\n $ text                      :List of 11\n  ..$ family       : chr \"\"\n  ..$ face         : chr \"plain\"\n  ..$ colour       : chr \"black\"\n  ..$ size         : num 11\n  ..$ hjust        : num 0.5\n  ..$ vjust        : num 0.5\n  ..$ angle        : num 0\n  ..$ lineheight   : num 0.9\n  ..$ margin       : 'margin' num [1:4] 0points 0points 0points 0points\n  .. ..- attr(*, \"unit\")= int 8\n  ..$ debug        : logi FALSE\n  ..$ inherit.blank: logi TRUE\n  ..- attr(*, \"class\")= chr [1:2] \"element_text\" \"element\"\n $ title                     : NULL\n $ aspect.ratio              : NULL\n $ axis.title                : NULL\n $ axis.title.x              :List of 11\n  ..$ family       : NULL\n  ..$ face         : NULL\n  ..$ colour       : NULL\n  ..$ size         : NULL\n  ..$ hjust        : NULL\n  ..$ vjust        : num 1\n  ..$ angle        : NULL\n  ..$ lineheight   : NULL\n  ..$ margin       : 'margin' num [1:4] 2.75points 0points 0points 0points\n  .. ..- attr(*, \"unit\")= int 8\n  ..$ debug        : NULL\n  ..$ inherit.blank: logi TRUE\n  ..- attr(*, \"class\")= chr [1:2] \"element_text\" \"element\"\n $ axis.title.x.top          :List of 11\n  ..$ family       : NULL\n  ..$ face         : NULL\n  ..$ colour       : NULL\n  ..$ size         : NULL\n  ..$ hjust        : NULL\n  ..$ vjust        : num 0\n  ..$ angle        : NULL\n  ..$ lineheight   : NULL\n  ..$ margin       : 'margin' num [1:4] 0points 0points 2.75points 0points\n  .. ..- attr(*, \"unit\")= int 8\n  ..$ debug        : NULL\n  ..$ inherit.blank: logi TRUE\n  ..- attr(*, \"class\")= chr [1:2] \"element_text\" \"element\"\n $ axis.title.x.bottom       : NULL\n $ axis.title.y              :List of 11\n  ..$ family       : NULL\n  ..$ face         : NULL\n  ..$ colour       : NULL\n  ..$ size         : NULL\n  ..$ hjust        : NULL\n  ..$ vjust        : num 1\n  ..$ angle        : num 90\n  ..$ lineheight   : NULL\n  ..$ margin       : 'margin' num [1:4] 0points 2.75points 0points 0points\n  .. ..- attr(*, \"unit\")= int 8\n  ..$ debug        : NULL\n  ..$ inherit.blank: logi TRUE\n  ..- attr(*, \"class\")= chr [1:2] \"element_text\" \"element\"\n $ axis.title.y.left         : NULL\n $ axis.title.y.right        :List of 11\n  ..$ family       : NULL\n  ..$ face         : NULL\n  ..$ colour       : NULL\n  ..$ size         : NULL\n  ..$ hjust        : NULL\n  ..$ vjust        : num 0\n  ..$ angle        : num -90\n  ..$ lineheight   : NULL\n  ..$ margin       : 'margin' num [1:4] 0points 0points 0points 2.75points\n  .. ..- attr(*, \"unit\")= int 8\n  ..$ debug        : NULL\n  ..$ inherit.blank: logi TRUE\n  ..- attr(*, \"class\")= chr [1:2] \"element_text\" \"element\"\n $ axis.text                 :List of 11\n  ..$ family       : NULL\n  ..$ face         : NULL\n  ..$ colour       : chr \"grey30\"\n  ..$ size         : 'rel' num 0.8\n  ..$ hjust        : NULL\n  ..$ vjust        : NULL\n  ..$ angle        : NULL\n  ..$ lineheight   : NULL\n  ..$ margin       : NULL\n  ..$ debug        : NULL\n  ..$ inherit.blank: logi TRUE\n  ..- attr(*, \"class\")= chr [1:2] \"element_text\" \"element\"\n $ axis.text.x               :List of 11\n  ..$ family       : NULL\n  ..$ face         : NULL\n  ..$ colour       : NULL\n  ..$ size         : NULL\n  ..$ hjust        : NULL\n  ..$ vjust        : num 1\n  ..$ angle        : NULL\n  ..$ lineheight   : NULL\n  ..$ margin       : 'margin' num [1:4] 2.2points 0points 0points 0points\n  .. ..- attr(*, \"unit\")= int 8\n  ..$ debug        : NULL\n  ..$ inherit.blank: logi TRUE\n  ..- attr(*, \"class\")= chr [1:2] \"element_text\" \"element\"\n $ axis.text.x.top           :List of 11\n  ..$ family       : NULL\n  ..$ face         : NULL\n  ..$ colour       : NULL\n  ..$ size         : NULL\n  ..$ hjust        : NULL\n  ..$ vjust        : num 0\n  ..$ angle        : NULL\n  ..$ lineheight   : NULL\n  ..$ margin       : 'margin' num [1:4] 0points 0points 2.2points 0points\n  .. ..- attr(*, \"unit\")= int 8\n  ..$ debug        : NULL\n  ..$ inherit.blank: logi TRUE\n  ..- attr(*, \"class\")= chr [1:2] \"element_text\" \"element\"\n $ axis.text.x.bottom        : NULL\n $ axis.text.y               :List of 11\n  ..$ family       : NULL\n  ..$ face         : NULL\n  ..$ colour       : NULL\n  ..$ size         : NULL\n  ..$ hjust        : num 1\n  ..$ vjust        : NULL\n  ..$ angle        : NULL\n  ..$ lineheight   : NULL\n  ..$ margin       : 'margin' num [1:4] 0points 2.2points 0points 0points\n  .. ..- attr(*, \"unit\")= int 8\n  ..$ debug        : NULL\n  ..$ inherit.blank: logi TRUE\n  ..- attr(*, \"class\")= chr [1:2] \"element_text\" \"element\"\n $ axis.text.y.left          : NULL\n $ axis.text.y.right         :List of 11\n  ..$ family       : NULL\n  ..$ face         : NULL\n  ..$ colour       : NULL\n  ..$ size         : NULL\n  ..$ hjust        : num 0\n  ..$ vjust        : NULL\n  ..$ angle        : NULL\n  ..$ lineheight   : NULL\n  ..$ margin       : 'margin' num [1:4] 0points 0points 0points 2.2points\n  .. ..- attr(*, \"unit\")= int 8\n  ..$ debug        : NULL\n  ..$ inherit.blank: logi TRUE\n  ..- attr(*, \"class\")= chr [1:2] \"element_text\" \"element\"\n $ axis.ticks                :List of 6\n  ..$ colour       : chr \"grey20\"\n  ..$ linewidth    : NULL\n  ..$ linetype     : NULL\n  ..$ lineend      : NULL\n  ..$ arrow        : logi FALSE\n  ..$ inherit.blank: logi TRUE\n  ..- attr(*, \"class\")= chr [1:2] \"element_line\" \"element\"\n $ axis.ticks.x              : NULL\n $ axis.ticks.x.top          : NULL\n $ axis.ticks.x.bottom       : NULL\n $ axis.ticks.y              : NULL\n $ axis.ticks.y.left         : NULL\n $ axis.ticks.y.right        : NULL\n $ axis.ticks.length         : 'simpleUnit' num 2.75points\n  ..- attr(*, \"unit\")= int 8\n $ axis.ticks.length.x       : NULL\n $ axis.ticks.length.x.top   : NULL\n $ axis.ticks.length.x.bottom: NULL\n $ axis.ticks.length.y       : NULL\n $ axis.ticks.length.y.left  : NULL\n $ axis.ticks.length.y.right : NULL\n $ axis.line                 :List of 6\n  ..$ colour       : chr \"black\"\n  ..$ linewidth    : 'rel' num 1\n  ..$ linetype     : NULL\n  ..$ lineend      : NULL\n  ..$ arrow        : logi FALSE\n  ..$ inherit.blank: logi TRUE\n  ..- attr(*, \"class\")= chr [1:2] \"element_line\" \"element\"\n $ axis.line.x               : NULL\n $ axis.line.x.top           : NULL\n $ axis.line.x.bottom        : NULL\n $ axis.line.y               : NULL\n $ axis.line.y.left          : NULL\n $ axis.line.y.right         : NULL\n $ legend.background         :List of 5\n  ..$ fill         : NULL\n  ..$ colour       : logi NA\n  ..$ linewidth    : NULL\n  ..$ linetype     : NULL\n  ..$ inherit.blank: logi TRUE\n  ..- attr(*, \"class\")= chr [1:2] \"element_rect\" \"element\"\n $ legend.margin             : 'margin' num [1:4] 5.5points 5.5points 5.5points 5.5points\n  ..- attr(*, \"unit\")= int 8\n $ legend.spacing            : 'simpleUnit' num 11points\n  ..- attr(*, \"unit\")= int 8\n $ legend.spacing.x          : NULL\n $ legend.spacing.y          : NULL\n $ legend.key                : list()\n  ..- attr(*, \"class\")= chr [1:2] \"element_blank\" \"element\"\n $ legend.key.size           : 'simpleUnit' num 1.2lines\n  ..- attr(*, \"unit\")= int 3\n $ legend.key.height         : NULL\n $ legend.key.width          : NULL\n $ legend.text               :List of 11\n  ..$ family       : NULL\n  ..$ face         : NULL\n  ..$ colour       : NULL\n  ..$ size         : 'rel' num 0.8\n  ..$ hjust        : NULL\n  ..$ vjust        : NULL\n  ..$ angle        : NULL\n  ..$ lineheight   : NULL\n  ..$ margin       : NULL\n  ..$ debug        : NULL\n  ..$ inherit.blank: logi TRUE\n  ..- attr(*, \"class\")= chr [1:2] \"element_text\" \"element\"\n $ legend.text.align         : NULL\n $ legend.title              :List of 11\n  ..$ family       : NULL\n  ..$ face         : NULL\n  ..$ colour       : NULL\n  ..$ size         : NULL\n  ..$ hjust        : num 0\n  ..$ vjust        : NULL\n  ..$ angle        : NULL\n  ..$ lineheight   : NULL\n  ..$ margin       : NULL\n  ..$ debug        : NULL\n  ..$ inherit.blank: logi TRUE\n  ..- attr(*, \"class\")= chr [1:2] \"element_text\" \"element\"\n $ legend.title.align        : NULL\n $ legend.position           : chr \"right\"\n $ legend.direction          : NULL\n $ legend.justification      : chr \"center\"\n $ legend.box                : NULL\n $ legend.box.just           : NULL\n $ legend.box.margin         : 'margin' num [1:4] 0cm 0cm 0cm 0cm\n  ..- attr(*, \"unit\")= int 1\n $ legend.box.background     : list()\n  ..- attr(*, \"class\")= chr [1:2] \"element_blank\" \"element\"\n $ legend.box.spacing        : 'simpleUnit' num 11points\n  ..- attr(*, \"unit\")= int 8\n $ panel.background          :List of 5\n  ..$ fill         : chr \"white\"\n  ..$ colour       : logi NA\n  ..$ linewidth    : NULL\n  ..$ linetype     : NULL\n  ..$ inherit.blank: logi TRUE\n  ..- attr(*, \"class\")= chr [1:2] \"element_rect\" \"element\"\n $ panel.border              : list()\n  ..- attr(*, \"class\")= chr [1:2] \"element_blank\" \"element\"\n $ panel.spacing             : 'simpleUnit' num 5.5points\n  ..- attr(*, \"unit\")= int 8\n $ panel.spacing.x           : NULL\n $ panel.spacing.y           : NULL\n $ panel.grid                :List of 6\n  ..$ colour       : chr \"grey92\"\n  ..$ linewidth    : NULL\n  ..$ linetype     : NULL\n  ..$ lineend      : NULL\n  ..$ arrow        : logi FALSE\n  ..$ inherit.blank: logi TRUE\n  ..- attr(*, \"class\")= chr [1:2] \"element_line\" \"element\"\n $ panel.grid.major          : list()\n  ..- attr(*, \"class\")= chr [1:2] \"element_blank\" \"element\"\n $ panel.grid.minor          : list()\n  ..- attr(*, \"class\")= chr [1:2] \"element_blank\" \"element\"\n $ panel.grid.major.x        : NULL\n $ panel.grid.major.y        : NULL\n $ panel.grid.minor.x        : NULL\n $ panel.grid.minor.y        : NULL\n $ panel.ontop               : logi FALSE\n $ plot.background           :List of 5\n  ..$ fill         : NULL\n  ..$ colour       : chr \"white\"\n  ..$ linewidth    : NULL\n  ..$ linetype     : NULL\n  ..$ inherit.blank: logi TRUE\n  ..- attr(*, \"class\")= chr [1:2] \"element_rect\" \"element\"\n $ plot.title                :List of 11\n  ..$ family       : NULL\n  ..$ face         : NULL\n  ..$ colour       : NULL\n  ..$ size         : 'rel' num 1.2\n  ..$ hjust        : num 0\n  ..$ vjust        : num 1\n  ..$ angle        : NULL\n  ..$ lineheight   : NULL\n  ..$ margin       : 'margin' num [1:4] 0points 0points 5.5points 0points\n  .. ..- attr(*, \"unit\")= int 8\n  ..$ debug        : NULL\n  ..$ inherit.blank: logi TRUE\n  ..- attr(*, \"class\")= chr [1:2] \"element_text\" \"element\"\n $ plot.title.position       : chr \"panel\"\n $ plot.subtitle             :List of 11\n  ..$ family       : NULL\n  ..$ face         : NULL\n  ..$ colour       : NULL\n  ..$ size         : NULL\n  ..$ hjust        : num 0\n  ..$ vjust        : num 1\n  ..$ angle        : NULL\n  ..$ lineheight   : NULL\n  ..$ margin       : 'margin' num [1:4] 0points 0points 5.5points 0points\n  .. ..- attr(*, \"unit\")= int 8\n  ..$ debug        : NULL\n  ..$ inherit.blank: logi TRUE\n  ..- attr(*, \"class\")= chr [1:2] \"element_text\" \"element\"\n $ plot.caption              :List of 11\n  ..$ family       : NULL\n  ..$ face         : NULL\n  ..$ colour       : NULL\n  ..$ size         : 'rel' num 0.8\n  ..$ hjust        : num 1\n  ..$ vjust        : num 1\n  ..$ angle        : NULL\n  ..$ lineheight   : NULL\n  ..$ margin       : 'margin' num [1:4] 5.5points 0points 0points 0points\n  .. ..- attr(*, \"unit\")= int 8\n  ..$ debug        : NULL\n  ..$ inherit.blank: logi TRUE\n  ..- attr(*, \"class\")= chr [1:2] \"element_text\" \"element\"\n $ plot.caption.position     : chr \"panel\"\n $ plot.tag                  :List of 11\n  ..$ family       : NULL\n  ..$ face         : NULL\n  ..$ colour       : NULL\n  ..$ size         : 'rel' num 1.2\n  ..$ hjust        : num 0.5\n  ..$ vjust        : num 0.5\n  ..$ angle        : NULL\n  ..$ lineheight   : NULL\n  ..$ margin       : NULL\n  ..$ debug        : NULL\n  ..$ inherit.blank: logi TRUE\n  ..- attr(*, \"class\")= chr [1:2] \"element_text\" \"element\"\n $ plot.tag.position         : chr \"topleft\"\n $ plot.margin               : 'margin' num [1:4] 5.5points 5.5points 5.5points 5.5points\n  ..- attr(*, \"unit\")= int 8\n $ strip.background          :List of 5\n  ..$ fill         : chr \"white\"\n  ..$ colour       : chr \"black\"\n  ..$ linewidth    : 'rel' num 2\n  ..$ linetype     : NULL\n  ..$ inherit.blank: logi TRUE\n  ..- attr(*, \"class\")= chr [1:2] \"element_rect\" \"element\"\n $ strip.background.x        : NULL\n $ strip.background.y        : NULL\n $ strip.clip                : chr \"inherit\"\n $ strip.placement           : chr \"inside\"\n $ strip.text                :List of 11\n  ..$ family       : NULL\n  ..$ face         : NULL\n  ..$ colour       : chr \"grey10\"\n  ..$ size         : 'rel' num 0.8\n  ..$ hjust        : NULL\n  ..$ vjust        : NULL\n  ..$ angle        : NULL\n  ..$ lineheight   : NULL\n  ..$ margin       : 'margin' num [1:4] 4.4points 4.4points 4.4points 4.4points\n  .. ..- attr(*, \"unit\")= int 8\n  ..$ debug        : NULL\n  ..$ inherit.blank: logi TRUE\n  ..- attr(*, \"class\")= chr [1:2] \"element_text\" \"element\"\n $ strip.text.x              : NULL\n $ strip.text.y              :List of 11\n  ..$ family       : NULL\n  ..$ face         : NULL\n  ..$ colour       : NULL\n  ..$ size         : NULL\n  ..$ hjust        : NULL\n  ..$ vjust        : NULL\n  ..$ angle        : num -90\n  ..$ lineheight   : NULL\n  ..$ margin       : NULL\n  ..$ debug        : NULL\n  ..$ inherit.blank: logi TRUE\n  ..- attr(*, \"class\")= chr [1:2] \"element_text\" \"element\"\n $ strip.switch.pad.grid     : 'simpleUnit' num 2.75points\n  ..- attr(*, \"unit\")= int 8\n $ strip.switch.pad.wrap     : 'simpleUnit' num 2.75points\n  ..- attr(*, \"unit\")= int 8\n $ strip.text.y.left         :List of 11\n  ..$ family       : NULL\n  ..$ face         : NULL\n  ..$ colour       : NULL\n  ..$ size         : NULL\n  ..$ hjust        : NULL\n  ..$ vjust        : NULL\n  ..$ angle        : num 90\n  ..$ lineheight   : NULL\n  ..$ margin       : NULL\n  ..$ debug        : NULL\n  ..$ inherit.blank: logi TRUE\n  ..- attr(*, \"class\")= chr [1:2] \"element_text\" \"element\"\n - attr(*, \"class\")= chr [1:2] \"theme\" \"gg\"\n - attr(*, \"complete\")= logi TRUE\n - attr(*, \"validate\")= logi TRUE\n```\n:::\n\n```{.r .cell-code}\nk\n```\n\n::: {.cell-output .cell-output-stderr}\n```\nWarning: Use of `Womendata$knowmeth` is discouraged.\nℹ Use `knowmeth` instead.\n```\n:::\n\n::: {.cell-output-display}\n![](Final-Project-_Kaushika-Potluri_files/figure-html/unnamed-chunk-23-1.png){width=672}\n:::\n:::\n\n\nHere, we can see that most individuals know about birth control.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nggplot(data = Womendata,\n       aes(\n         x = children,\n         y = prop.table(stat(count)),\n         fill = factor(usemeth), width = 1,\n         label = scales::percent(prop.table(stat(count)))\n       )) +\n  geom_bar(position = position_dodge()) +\n  geom_text(\n    stat = \"count\",\n    position = position_dodge(0.2),\n    vjust = -1,\n    size = 1.5\n  ) + scale_y_continuous(labels = scales::percent) +\n  labs(title = \"Number of children based on birth control\",\n       x = \"Number of Children\",\n       y = \"Count\") +\n  theme_classic() +\n  scale_fill_discrete(\n    name = \"Birth Control\",\n    labels = c(\"Use birth control\", \"Never used birth control\")\n  )\n```\n\n::: {.cell-output .cell-output-stderr}\n```\nWarning: `stat(count)` was deprecated in ggplot2 3.4.0.\nℹ Please use `after_stat(count)` instead.\n```\n:::\n\n::: {.cell-output-display}\n![](Final-Project-_Kaushika-Potluri_files/figure-html/unnamed-chunk-24-1.png){width=672}\n:::\n:::\n\n\nHere we can see that the number of individuals using birth control is higher than individuals that never used birth control only for individuals have zero children.\nAs the number of children go up we can see that individuals most individuals that have never used birth control are higher than the indivuals that have used birth control.\nThis can imply that the percentage individuals that have children and use birth control are lesser than the percentage individuals that have children and never used birth control.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nggplot(Womendatacleaned,aes(x=factor(children),fill=factor(evermarr)))+\n  \ngeom_bar()+theme(axis.text.x = element_text(face=\"bold\", size=15),axis.text.y = element_text(face=\"bold\", size=15))+\n  \nlabs(\n    title = \"Number of Children based on Marriage status\",\n    x = \"Number of children\",\n    y = \"Count\",size=15) +\n   \nscale_fill_manual(\n    name = \"Married or not\",\n    breaks = c(\"0\", \"1\"),\n    labels = c(\"Not Married\", \"Married\"),\n    values = c(\"0\" = \"blue\", \"1\"=\"red\")\n  )\n```\n\n::: {.cell-output-display}\n![](Final-Project-_Kaushika-Potluri_files/figure-html/unnamed-chunk-25-1.png){width=672}\n:::\n:::\n\n\nMost women have 1 child in majority.\nMajority of those mothers are not married.\nThis could say something about our data.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nWomendata %>%\n  ggplot() +\n  geom_bar(aes(educ)) +\n  theme_classic() + labs(title = \"Number of children based on years of schooling\",\n       x = \"Number of years of schooling\",\n       y = \"Count\")\n```\n\n::: {.cell-output-display}\n![](Final-Project-_Kaushika-Potluri_files/figure-html/unnamed-chunk-26-1.png){width=672}\n:::\n\n```{.r .cell-code}\n  ggtitle(\"No of indviduals educated\")\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n$title\n[1] \"No of indviduals educated\"\n\nattr(,\"class\")\n[1] \"labels\"\n```\n:::\n:::\n\n\nFrom the bar graph we can say that majority of women in our data have education of atleast 5-7 years and the next highest is women with 0 years of education.\nThis can say a lot about our data when we are talking about the relationship between education and fertility.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nggplot(Womendatacleaned,aes(x=factor(age),fill=factor(usemeth)))+\n  \ngeom_bar()+theme(axis.text.x = element_text(face=\"bold\", size=5),axis.text.y = element_text(face=\"bold\", size=15))+\n  \nlabs(\n    title = \"Number of individuals that have used birth control based their age\",\n    x = \"Age\",\n    y = \"Count\",size=15) +\n   \nscale_fill_manual(\n    name = \"Use birth control or not\",\n    breaks = c(\"0\", \"1\"),\n    labels = c(\"Never used birth control\", \"Has used birth control\"),\n    values = c(\"0\" = \"brown\", \"1\"=\"green\")\n  )\n```\n\n::: {.cell-output-display}\n![](Final-Project-_Kaushika-Potluri_files/figure-html/unnamed-chunk-27-1.png){width=672}\n:::\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\nggplot(data = Womendata, aes(x=mnthborn, y= children)) + \n  geom_boxplot(outlier.color = \"red\", outlier.shape = 1, show.legend = T) + \n  facet_wrap(~mnthborn)\n```\n\n::: {.cell-output-display}\n![](Final-Project-_Kaushika-Potluri_files/figure-html/unnamed-chunk-28-1.png){width=672}\n:::\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\nggplot(data = Womendata) + \n  geom_violin(mapping = aes(y=children, x = educ,fill=educ), trim = TRUE, draw_quantiles = c(0.25, 0.5, 0.75))\n```\n\n::: {.cell-output .cell-output-stderr}\n```\nWarning: Groups with fewer than two data points have been dropped.\nGroups with fewer than two data points have been dropped.\nGroups with fewer than two data points have been dropped.\nGroups with fewer than two data points have been dropped.\nGroups with fewer than two data points have been dropped.\nGroups with fewer than two data points have been dropped.\nGroups with fewer than two data points have been dropped.\nGroups with fewer than two data points have been dropped.\nGroups with fewer than two data points have been dropped.\nGroups with fewer than two data points have been dropped.\nGroups with fewer than two data points have been dropped.\nGroups with fewer than two data points have been dropped.\nGroups with fewer than two data points have been dropped.\nGroups with fewer than two data points have been dropped.\nGroups with fewer than two data points have been dropped.\nGroups with fewer than two data points have been dropped.\nGroups with fewer than two data points have been dropped.\nGroups with fewer than two data points have been dropped.\nGroups with fewer than two data points have been dropped.\nGroups with fewer than two data points have been dropped.\nGroups with fewer than two data points have been dropped.\nGroups with fewer than two data points have been dropped.\nGroups with fewer than two data points have been dropped.\nGroups with fewer than two data points have been dropped.\nGroups with fewer than two data points have been dropped.\nGroups with fewer than two data points have been dropped.\n```\n:::\n\n::: {.cell-output-display}\n![](Final-Project-_Kaushika-Potluri_files/figure-html/unnamed-chunk-29-1.png){width=672}\n:::\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\nplot_bar(data = Womendata)\n```\n\n::: {.cell-output-display}\n![](Final-Project-_Kaushika-Potluri_files/figure-html/unnamed-chunk-30-1.png){width=672}\n:::\n\n::: {.cell-output-display}\n![](Final-Project-_Kaushika-Potluri_files/figure-html/unnamed-chunk-30-2.png){width=672}\n:::\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\nWomendata$educ <-as.integer(as.character(Womendata$educ))\nWomendata$age <- as.integer(as.character(Womendata$age))\n\nWomendata$mnthborn <- as.integer(as.character(Womendata$mnthborn))\nWomendata$electric <- as.integer(as.character(Womendata$electric))\n\nWomendata$radio <- as.integer(as.character(Womendata$radio))\nWomendata$tv <- as.integer(as.character(Womendata$tv))\n\nWomendata$bicycle <- as.integer(as.character(Womendata$bicycle))\nWomendata$children <- as.integer(as.character(Womendata$children))\n\nWomendata$knowmeth <- as.integer(as.character(Womendata$knowmeth))\nplot_histogram(data = Womendata)\n```\n\n::: {.cell-output-display}\n![](Final-Project-_Kaushika-Potluri_files/figure-html/unnamed-chunk-31-1.png){width=672}\n:::\n:::\n\n\n## Corelation\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(corrplot)\n```\n\n::: {.cell-output .cell-output-stderr}\n```\ncorrplot 0.92 loaded\n```\n:::\n\n```{.r .cell-code}\nlibrary(RColorBrewer)\n\nM <-cor(Womendata %>% \n         dplyr::select(age, yearborn, educ, ceb, agefbrth, children, usemeth, knowmeth))\n\ncorrplot(M, type=\"upper\", order = \"original\",col=brewer.pal(n=8, name=\"RdYlBu\"))\n```\n\n::: {.cell-output-display}\n![](Final-Project-_Kaushika-Potluri_files/figure-html/unnamed-chunk-32-1.png){width=672}\n:::\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\ncor(Womendata$educ, Womendata$children)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] -0.3705226\n```\n:::\n:::\n\n\nHere we can see that education and number of children have a negative correlation.\nNegative correlation is a relationship between two variables in which one variable increases as the other decreases, and vice versa.\n\n\n::: {.cell}\n\n```{.r .cell-code}\ncor(Womendata$educ, Womendata$ceb)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] -0.3842877\n```\n:::\n:::\n\n\nHere we can see that education and number of children ever born have a negative correlation as well.\nThis does say lot about education and number of children.\n\n\n::: {.cell}\n\n```{.r .cell-code}\ncor(Womendata$age, unclass(Womendata$educ))\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] -0.3096017\n```\n:::\n:::\n\n\nWe can see that age and education have a negative correlation.\n\n\n::: {.cell}\n\n```{.r .cell-code}\ncor(Womendata$age, Womendata$children)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 0.7325709\n```\n:::\n:::\n\n\nAge and number of children have a positive correlation.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(PerformanceAnalytics)\n```\n\n::: {.cell-output .cell-output-stderr}\n```\nLoading required package: xts\n```\n:::\n\n::: {.cell-output .cell-output-stderr}\n```\n\nAttaching package: 'xts'\n```\n:::\n\n::: {.cell-output .cell-output-stderr}\n```\nThe following objects are masked from 'package:dplyr':\n\n    first, last\n```\n:::\n\n::: {.cell-output .cell-output-stderr}\n```\n\nAttaching package: 'PerformanceAnalytics'\n```\n:::\n\n::: {.cell-output .cell-output-stderr}\n```\nThe following object is masked from 'package:graphics':\n\n    legend\n```\n:::\n\n```{.r .cell-code}\nchart.Correlation(Womendata %>% \n              dplyr::select(age,yearborn, educ, ceb, agefbrth, children), histogram=TRUE, pch=19)\n```\n\n::: {.cell-output .cell-output-stderr}\n```\nWarning in par(usr): argument 1 does not name a graphical parameter\n\nWarning in par(usr): argument 1 does not name a graphical parameter\n\nWarning in par(usr): argument 1 does not name a graphical parameter\n\nWarning in par(usr): argument 1 does not name a graphical parameter\n\nWarning in par(usr): argument 1 does not name a graphical parameter\n\nWarning in par(usr): argument 1 does not name a graphical parameter\n\nWarning in par(usr): argument 1 does not name a graphical parameter\n\nWarning in par(usr): argument 1 does not name a graphical parameter\n\nWarning in par(usr): argument 1 does not name a graphical parameter\n\nWarning in par(usr): argument 1 does not name a graphical parameter\n\nWarning in par(usr): argument 1 does not name a graphical parameter\n\nWarning in par(usr): argument 1 does not name a graphical parameter\n\nWarning in par(usr): argument 1 does not name a graphical parameter\n\nWarning in par(usr): argument 1 does not name a graphical parameter\n\nWarning in par(usr): argument 1 does not name a graphical parameter\n```\n:::\n\n::: {.cell-output-display}\n![](Final-Project-_Kaushika-Potluri_files/figure-html/unnamed-chunk-37-1.png){width=672}\n:::\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\nWomendata$educ <- as.factor(Womendata$educ)\nWomendata$age <- as.factor(Womendata$age)\n\nWomendata$mnthborn <- as.factor(Womendata$mnthborn)\nWomendata$electric <- as.factor(Womendata$electric)\n\nWomendata$radio <- as.factor(Womendata$radio)\nWomendata$tv <- as.factor(Womendata$tv)\n\nWomendata$bicycle <- as.factor(Womendata$bicycle)\nWomendata$children <- as.factor(Womendata$children)\n\nWomendata$knowmeth <- as.factor(Womendata$knowmeth)\nWomendata$catholic <- as.factor(Womendata$catholic)\n\nWomendata$frsthalf <- as.factor(Womendata$frsthalf)\nWomendata$educ0 <- as.factor(Womendata$educ0)\n\nWomendata$evermarr <- as.factor(Womendata$evermarr)\nWomendata$protest <- as.factor(Womendata$protest)\nWomendata$spirit <- as.factor(Womendata$spirit)\n\nWomendata$urban <- as.factor(Womendata$urban)\nWomendata$spirit <- as.factor(Womendata$spirit)\n```\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\nsummary(Womendata)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n       X           mnthborn       yearborn          age       electric   \n Min.   :   1   6      : 623   Min.   :38.00   18     : 243   0   :3747  \n 1st Qu.:1091   3      : 406   1st Qu.:55.00   20     : 219   1   : 611  \n Median :2181   9      : 382   Median :62.00   22     : 206   NA's:   3  \n Mean   :2181   1      : 380   Mean   :60.43   16     : 205              \n 3rd Qu.:3271   8      : 363   3rd Qu.:68.00   19     : 205              \n Max.   :4361   7      : 358   Max.   :73.00   26     : 201              \n                (Other):1849                   (Other):3082              \n  radio         tv       bicycle          educ           ceb        \n 0   :1300   0   :3954   0   :3156   7      :1162   Min.   : 0.000  \n 1   :3059   1   : 405   1   :1202   0      : 906   1st Qu.: 1.000  \n NA's:   2   NA's:   2   NA's:   3   10     : 527   Median : 2.000  \n                                     6      : 298   Mean   : 2.442  \n                                     5      : 234   3rd Qu.: 4.000  \n                                     9      : 232   Max.   :13.000  \n                                     (Other):1002                   \n    agefbrth        children    knowmeth       usemeth          idlnchld     \n Min.   :10.00   0      :1132   0   : 160   Min.   :0.0000   Min.   : 0.000  \n 1st Qu.:17.00   1      : 907   1   :4194   1st Qu.:0.0000   1st Qu.: 3.000  \n Median :19.00   2      : 696   NA's:   7   Median :1.0000   Median : 4.000  \n Mean   :19.01   3      : 528               Mean   :0.5776   Mean   : 4.616  \n 3rd Qu.:20.00   4      : 392               3rd Qu.:1.0000   3rd Qu.: 6.000  \n Max.   :38.00   5      : 255               Max.   :1.0000   Max.   :20.000  \n NA's   :1088    (Other): 451               NA's   :71       NA's   :120     \n     agesq        urban       urb_educ      spirit   protest  catholic frsthalf\n Min.   : 225.0   0:2108   Min.   : 0.000   0:2520   0:3368   0:3914   0:2004  \n 1st Qu.: 400.0   1:2253   1st Qu.: 0.000   1:1841   1: 993   1: 447   1:2357  \n Median : 676.0            Median : 0.000                                      \n Mean   : 826.5            Mean   : 3.469                                      \n 3rd Qu.:1089.0            3rd Qu.: 7.000                                      \n Max.   :2401.0            Max.   :20.000                                      \n                                                                               \n educ0    evermarr\n 0:3455   0:2282  \n 1: 906   1:2079  \n                  \n                  \n                  \n                  \n                  \n```\n:::\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\nWomendata$age <- unclass(Womendata$age)\nWomendata$children <- unclass(Womendata$children)\nWomendata$educ <- unclass(Womendata$educ)\n```\n:::\n\n\nRegression Models :\n\n\n::: {.cell}\n\n```{.r .cell-code}\nmodel1 <- lm(children ~ educ, data = Womendata)\nsummary(model1)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n\nCall:\nlm(formula = children ~ educ, data = Womendata)\n\nResiduals:\n   Min     1Q Median     3Q    Max \n-3.495 -1.496 -0.399  1.182  9.505 \n\nCoefficients:\n            Estimate Std. Error t value Pr(>|t|)    \n(Intercept)  4.70519    0.06289   74.81   <2e-16 ***\neduc        -0.20965    0.00796  -26.34   <2e-16 ***\n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n\nResidual standard error: 2.064 on 4359 degrees of freedom\nMultiple R-squared:  0.1373,\tAdjusted R-squared:  0.1371 \nF-statistic: 693.7 on 1 and 4359 DF,  p-value: < 2.2e-16\n```\n:::\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\nmodel2 <- lm(children ~., data = Womendata)\nsummary(model1)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n\nCall:\nlm(formula = children ~ educ, data = Womendata)\n\nResiduals:\n   Min     1Q Median     3Q    Max \n-3.495 -1.496 -0.399  1.182  9.505 \n\nCoefficients:\n            Estimate Std. Error t value Pr(>|t|)    \n(Intercept)  4.70519    0.06289   74.81   <2e-16 ***\neduc        -0.20965    0.00796  -26.34   <2e-16 ***\n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n\nResidual standard error: 2.064 on 4359 degrees of freedom\nMultiple R-squared:  0.1373,\tAdjusted R-squared:  0.1371 \nF-statistic: 693.7 on 1 and 4359 DF,  p-value: < 2.2e-16\n```\n:::\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\nmodel3 <- lm(children ~ educ + age + mnthborn + bicycle + urb_educ + evermarr + yearborn + radio + agefbrth +idlnchld + ceb, data = Womendata)\nsummary(model3)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n\nCall:\nlm(formula = children ~ educ + age + mnthborn + bicycle + urb_educ + \n    evermarr + yearborn + radio + agefbrth + idlnchld + ceb, \n    data = Womendata)\n\nResiduals:\n    Min      1Q  Median      3Q     Max \n-6.0221 -0.0315  0.0745  0.2482  1.2733 \n\nCoefficients:\n              Estimate Std. Error t value Pr(>|t|)    \n(Intercept) -1.0207133  3.1695672  -0.322   0.7474    \neduc        -0.0001782  0.0032429  -0.055   0.9562    \nage          0.0248719  0.0427747   0.581   0.5610    \nmnthborn2   -0.0238081  0.0456270  -0.522   0.6018    \nmnthborn3    0.0671309  0.0426656   1.573   0.1157    \nmnthborn4    0.0529723  0.0451366   1.174   0.2406    \nmnthborn5    0.0374369  0.0462253   0.810   0.4181    \nmnthborn6    0.0572035  0.0388489   1.472   0.1410    \nmnthborn7    0.0378128  0.0439550   0.860   0.3897    \nmnthborn8    0.0419064  0.0450599   0.930   0.3524    \nmnthborn9    0.0501796  0.0453065   1.108   0.2681    \nmnthborn10   0.0197417  0.0503030   0.392   0.6947    \nmnthborn11   0.0135532  0.0561693   0.241   0.8093    \nmnthborn12   0.0537444  0.0613665   0.876   0.3812    \nbicycle1     0.0488972  0.0211513   2.312   0.0209 *  \nurb_educ     0.0019654  0.0028657   0.686   0.4929    \nevermarr1    0.0428377  0.0208819   2.051   0.0403 *  \nyearborn     0.0269700  0.0428099   0.630   0.5287    \nradio1       0.0220766  0.0212752   1.038   0.2995    \nagefbrth     0.0054808  0.0035900   1.527   0.1269    \nidlnchld    -0.0083450  0.0044706  -1.867   0.0620 .  \nceb          0.9004369  0.0067066 134.262   <2e-16 ***\n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n\nResidual standard error: 0.5175 on 3155 degrees of freedom\n  (1184 observations deleted due to missingness)\nMultiple R-squared:  0.9368,\tAdjusted R-squared:  0.9363 \nF-statistic:  2226 on 21 and 3155 DF,  p-value: < 2.2e-16\n```\n:::\n:::\n\n\nWith an adjusted R-squared of 0.9363 model 3 best fits our data.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(MASS)\n```\n\n::: {.cell-output .cell-output-stderr}\n```\n\nAttaching package: 'MASS'\n```\n:::\n\n::: {.cell-output .cell-output-stderr}\n```\nThe following object is masked from 'package:dplyr':\n\n    select\n```\n:::\n\n```{.r .cell-code}\nmodel4<- lm(log(ceb)~., \n                data = na.omit(Womendata))\n\n#Using stepAIC search method for feature selection to simplify model without impacting much on the performance.\nstep.model <- stepAIC(model4,direction = \"both\",trace = FALSE)\n\nsummary(step.model)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n\nCall:\nlm(formula = log(ceb) ~ yearborn + age + electric + radio + educ + \n    agefbrth + children + usemeth + agesq + urban + evermarr, \n    data = na.omit(Womendata))\n\nResiduals:\n     Min       1Q   Median       3Q      Max \n-1.11133 -0.14413  0.01042  0.13234  1.31158 \n\nCoefficients:\n              Estimate Std. Error t value Pr(>|t|)    \n(Intercept)  2.109e+00  8.387e-01   2.515  0.01197 *  \nyearborn    -2.948e-02  1.135e-02  -2.597  0.00946 ** \nage          7.227e-02  1.212e-02   5.962 2.77e-09 ***\nelectric1   -3.135e-02  1.330e-02  -2.357  0.01851 *  \nradio1      -1.997e-02  9.531e-03  -2.096  0.03620 *  \neduc        -3.248e-03  1.270e-03  -2.558  0.01059 *  \nagefbrth    -2.072e-02  1.604e-03 -12.913  < 2e-16 ***\nchildren     2.550e-01  3.157e-03  80.773  < 2e-16 ***\nusemeth      4.749e-02  9.875e-03   4.809 1.59e-06 ***\nagesq       -1.312e-03  6.351e-05 -20.657  < 2e-16 ***\nurban1      -2.796e-02  9.072e-03  -3.083  0.00207 ** \nevermarr1    5.743e-02  9.546e-03   6.016 2.00e-09 ***\n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n\nResidual standard error: 0.2328 on 3106 degrees of freedom\nMultiple R-squared:  0.8895,\tAdjusted R-squared:  0.8891 \nF-statistic:  2272 on 11 and 3106 DF,  p-value: < 2.2e-16\n```\n:::\n:::\n\n\n## Interpreting the results of Linear Regression ( Ordinary Least Squares(ols))\n\n\n::: {.cell}\n\n```{.r .cell-code}\nols <- lm(model3, data = Womendata)\ncoeftest(ols, vcov. = vcovHC, type = 'HC0')\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n\nt test of coefficients:\n\n               Estimate  Std. Error t value Pr(>|t|)    \n(Intercept) -1.02071335  3.07872730 -0.3315  0.74026    \neduc        -0.00017819  0.00298008 -0.0598  0.95232    \nage          0.02487191  0.04161323  0.5977  0.55009    \nmnthborn2   -0.02380807  0.05235867 -0.4547  0.64935    \nmnthborn3    0.06713094  0.04411010  1.5219  0.12814    \nmnthborn4    0.05297229  0.05018473  1.0555  0.29126    \nmnthborn5    0.03743693  0.05071823  0.7381  0.46049    \nmnthborn6    0.05720345  0.04422397  1.2935  0.19593    \nmnthborn7    0.03781281  0.04615904  0.8192  0.41274    \nmnthborn8    0.04190639  0.04450873  0.9415  0.34650    \nmnthborn9    0.05017962  0.04424976  1.1340  0.25688    \nmnthborn10   0.01974173  0.05377659  0.3671  0.71356    \nmnthborn11   0.01355316  0.05443757  0.2490  0.80340    \nmnthborn12   0.05374445  0.06219766  0.8641  0.38760    \nbicycle1     0.04889722  0.01999543  2.4454  0.01452 *  \nurb_educ     0.00196540  0.00225881  0.8701  0.38431    \nevermarr1    0.04283771  0.02093188  2.0465  0.04079 *  \nyearborn     0.02696998  0.04159905  0.6483  0.51682    \nradio1       0.02207657  0.02200372  1.0033  0.31579    \nagefbrth     0.00548083  0.00370002  1.4813  0.13863    \nidlnchld    -0.00834501  0.00567801 -1.4697  0.14174    \nceb          0.90043685  0.00948091 94.9737  < 2e-16 ***\n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n```\n:::\n:::\n\n## Model Evaluation\n\n\n::: {.cell}\n\n```{.r .cell-code}\npar(mfrow=c(2,2)) \n\nplot(model1)\n```\n\n::: {.cell-output-display}\n![](Final-Project-_Kaushika-Potluri_files/figure-html/unnamed-chunk-46-1.png){width=672}\n:::\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\npar(mfrow=c(2,2)) \n\nplot(model2)\n```\n\n::: {.cell-output-display}\n![](Final-Project-_Kaushika-Potluri_files/figure-html/unnamed-chunk-47-1.png){width=672}\n:::\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\npar(mfrow=c(2,2)) \n\nplot(model3)\n```\n\n::: {.cell-output-display}\n![](Final-Project-_Kaushika-Potluri_files/figure-html/unnamed-chunk-48-1.png){width=672}\n:::\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\npar(mfrow=c(2,2)) \n\nplot(model4)\n```\n\n::: {.cell-output-display}\n![](Final-Project-_Kaushika-Potluri_files/figure-html/unnamed-chunk-49-1.png){width=672}\n:::\n:::\n\n\nR\\^2 = 0.8895 and adjusted R\\^2 = 0.8891, F test value = 2272 p-value = 0.001.\nUnder normal distribution assumption.\nAccording to Central limit teorem , every distribution approximated by a normal distribution.\nA normal distribution is approached very quickly as n increases, note that n is the sample size for each mean and not the number of samples If the null hypothesis is true, the above-mentioned F test statistic can be condensed (dramatically).\nThe test statistic will be this sample variance ratio.\nIf the null hypothesis is incorrect, we will disprove both our presumption that they were equal and the null hypothesis that the ratio was equal to 1.\n\n##Checking for Heteroskedasticity Breusch Pagan Test for Heteroskedasticity\n\n    Ho: the variance is constant\n    H1: the variance is not constant\n\n\n::: {.cell}\n\n```{.r .cell-code}\nbptest(ceb ~ ., data = Womendatacleaned)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n\n\tstudentized Breusch-Pagan test\n\ndata:  ceb ~ .\nBP = 319.48, df = 94, p-value < 2.2e-16\n```\n:::\n:::\n\n\nHo hypothesis is rejected since the variance is not constant.\n\nIn multiple regression two or more predictor variables might be correlated with each other and situation is referred as collinearity.\nMulticollinearity is where collinearity exists between three or more variables even if no pair of variables has a particularly high correlation.\nThis means that there is redundancy between predictor variables.Multicollinearity can assessed by computing a score called the variance inflation factor (or VIF), which measures how much the variance of a regression coefficient is inflated due to multicollinearity in the model.\nThe smallest possible value of VIF is one (absence of multicollinearity).\nA VIF value that exceeds 5 or 10 indicates a problematic amount of collinearity.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nvif(step.model)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n  yearborn        age   electric      radio       educ   agefbrth   children \n459.569426 524.025963   1.250912   1.102156   1.523564   1.430945   2.370392 \n   usemeth      agesq      urban   evermarr \n  1.210953  59.396420   1.183061   1.273500 \n```\n:::\n:::\n\n\nAs a thumb rule, since we follow that a VIF value that exceeds 5 or 10 can be a problem.\nThis leads to a simpler model without compromising the model accuracy, which is good.\nSo now the new model will be without yearborn.\n\n## Without Multicollinearity\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(MASS)\nmodel2<- lm(log(ceb)~ mnthborn + age +\n                            electric +\n                            children + knowmeth +\n                            usemeth  +\n                            urban + radio +\n                            tv + bicycle +\n                            I(as.factor(educ)) +\n                            idlnchld+urb_educ +\n                            protest, \n                            data = na.omit(Womendatacleaned))\n\nstep.model2 <- stepAIC(model2, \n                        direction = \"both\", \n                        trace = FALSE)\n\nvif(step.model2) # Variance Inflation Factor (or VIF)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n             GVIF Df GVIF^(1/(2*Df))\nage      3.298838 34        1.017707\nelectric 1.269286  1        1.126626\nchildren 3.353509 13        1.047639\nurban    2.365418  1        1.537992\nradio    1.065265  1        1.032117\nidlnchld 1.215614  1        1.102549\nurb_educ 2.779986  1        1.667329\n```\n:::\n:::\n\n\nNow the new VIF values are all less than 5.\nThis is good for our model.\nThere is no Multicollinearity.\n\nWe expect from our study, if the level of education increases, the number of children is decreasing.\nAlso, it should be same parameters negative corelation for example between education and number of children. We found that if the level of education increases, the number of children is decreasing.\nIn addition, same parameters negative corelation for example between education and number of children or between birth control pill and children every born / children.\nAlso, age and education level is negative corelation.\nAge and number of children are positive corelation.\n\n#Conclusion\nIn both developed and developing countries, better-educated women have fewer children than less-educated women. However, the reasons for this are less clear, since the benefits of education extend beyond the value of women's time. Education can reduce fertility because better-educated women earn more and may raise their children more effectively. Education also improves maternal and child health, thereby increasing a woman's physical capacity to give birth and reducing the (economic) necessity for more children. Nevertheless, understanding modern contraception helps women control birth. Finally, higher education empowers women and includes them in household decision-making on family planning. Each mechanism is significant, depending on the individual and institutional context, but there is limited evidence on the relative importance of each one.\n\n##References \n[1]The effect of women's schooling on fertility by W Sander · 1992 \n[2]The Impact of Women's Schooling on Fertility and Contraceptive Use by M Ainsworth · 1996 [3]Fertility in Botswana: The Recent Decline and Future Prospects by Naomi Rutenberg and Ian Diamond\n",
    "supporting": [
      "Final-Project-_Kaushika-Potluri_files"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}