{
  "hash": "5d3a92c10a36f5def85241ab514d1751",
  "result": {
    "markdown": "---\ntitle: \"DACSS 603: Homework 1\"\nauthor: \"Tory Bartelloni\"\ndesription: \"Analyzing Lung Capacity data\"\ndate: \"10/03/2022\"\nformat:\n  html:\n    toc: true\n    code-fold: true\n    code-copy: true\n    code-tools: true\nexecute: \n  echo: true\n  warning: false\ncategories:\n  - hw1\n  - Tory Bartelloni\n  - LungCap\n  - dplyr\n  - ggplot2\n  - EDA\n  - Descriptive Statistics\n---\n\n\n# Setup\n\nFirst, let's load our packages and read in the data.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(dplyr)\nlibrary(ggplot2)\nlibrary(readxl)\n\nlcdata <- read_xls(\"_data/LungCapData.xls\")\n```\n:::\n\n\n\n# Question 1\n\n## Q1a\n\n*What does the distribution of LungCap look like?*\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlcdata %>% \n  ggplot(aes(x=LungCap)) +\n  geom_histogram(bins=45) +\n  theme_bw() +\n  labs(x=\"Lung Capacity\", y=\"Frequency\", \n       title = \"Lung Capacity Distribution\")\n```\n\n::: {.cell-output-display}\n![](HW1_ToryBartelloni_files/figure-html/unnamed-chunk-2-1.png){width=672}\n:::\n:::\n\n\n\nThe histogram suggests that the distribution is close to a normal distribution. Most of the observations are close to the mean. Very few observations are close to the margins (0 and 15).\n\n## Q1b\n\n*Compare the probability density of the LungCap with respect to Males and Females.*\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlcdata %>%\n  ggplot(aes(x=LungCap)) +\n  geom_boxplot(aes(group=Gender, fill=Gender)) +\n  theme_bw() +\n  theme (axis.text.y = element_blank ()) +\n  labs(x=\"Lung Capacity\", title = \"Lung Capacity Distribution\",\n       subtitle = \"Comparing lung capacity between genders\")\n```\n\n::: {.cell-output-display}\n![](HW1_ToryBartelloni_files/figure-html/unnamed-chunk-3-1.png){width=672}\n:::\n:::\n\nThe boxplot comparison indicates that on average males have larger lung capacity, but it also shows that the range and IQR for each gender are similar and have a significant amount of overlap.\n\n## Q1c\n\n*Compare the mean lung capacities for smokers and non-smokers. Does it make sense?*\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlcdata %>% \n  ggplot(aes(x=LungCap)) +\n  geom_boxplot(aes(fill=Smoke)) +\n  scale_fill_discrete(labels=c(\"Non-Smoker\", \"Smoker\")) +\n  theme_bw() +\n  theme (axis.text.y = element_blank ()) +\n  labs(title=\"Lung Capacity Distribution\", \n       subtitle = \"Comparing smokers and non-smokers\")\n```\n\n::: {.cell-output-display}\n![](HW1_ToryBartelloni_files/figure-html/unnamed-chunk-4-1.png){width=672}\n:::\n:::\n\n\nComparing the distributions shows that Smokers have a higher mean lung capacity and a significantly smaller range and IQR. This does not make sense intuitively so I would want to investigate the data a bit more to understand the possible reasons.\n\n## Q1d\n\n*Examine the relationship between Smoking and Lung Capacity within age groups: \"less than or equal to 13\", \"14 to 15\", \"16 to 17\", and \"greater than or equal to 18\".* \n\n\n::: {.cell}\n\n```{.r .cell-code}\nlc_with_age_groups <- lcdata %>%\n  mutate(Age_Group = factor(case_when(\n    Age <= 13 ~ \"<=13\",\n    Age %in% c(14,15) ~ \"14-15\",\n    Age %in% c(16,17) ~ \"16-17\",\n    Age >= 18 ~ \">=18\"\n      ),\n    levels = c(\"<=13\",\"14-15\",\"16-17\",\">=18\")\n    )\n  )\n\nlc_with_age_groups %>% \n  ggplot(aes(x=Age_Group,y=LungCap)) +\n  geom_boxplot() +\n  theme_bw() +\n  labs(title=\"Lung Capacity Distribution\", \n       subtitle = \"Comparing age groups\",\n       x=\"Age Group\",\n       y=\"Lung Capacity\")\n```\n\n::: {.cell-output-display}\n![](HW1_ToryBartelloni_files/figure-html/unnamed-chunk-5-1.png){width=672}\n:::\n:::\n\nComparing age groups shows a consistent and clear increase in lung capacity as ages increase up to and over 18 years old.\n\n## Q1e\n\n*Compare the lung capacities for smokers and non-smokers  within each age group. Is your answer different from the one in part c? What could possibly be going on here?*\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlc_with_age_groups %>%\n  ggplot(aes(x=Smoke, y=LungCap)) +\n  geom_boxplot(aes(fill=Smoke)) +\n  scale_fill_discrete(labels=c(\"Non-Smoker\", \"Smoker\")) +\n  facet_wrap(~Age_Group) +\n  theme_bw() +\n  labs(title=\"Lung Capacity Distribution\", \n       subtitle = \"Comparing smokers and non-smokers within age groups\",\n       x=\"Age Group\",\n       y=\"Lung Capacity\")\n```\n\n::: {.cell-output-display}\n![](HW1_ToryBartelloni_files/figure-html/unnamed-chunk-6-1.png){width=672}\n:::\n:::\n\nOutside of ages 13 and under all ages groups show higher average, range, and IRQ for non-smokers. It seems likely that the youngest age group, 13 and under, has the largest number of observations of non-smokers which is bringing down the overall average and lower end of the range. This effect is what is causing us to see the higher lung capacity in smokers overall, but we can infer that the causal factor is more likely age than smoking.\n\n## Q1f\n\n*Calculate the correlation and covariance between Lung Capacity and Age (use the cov() and cor() functions in R). Interpret your results.*\n\n\n::: {.cell}\n\n```{.r .cell-code}\nknitr::kable(\n  lcdata %>% summarise(Covariance = cov(LungCap, Age),\n                     Correlation = cor(LungCap, Age)),\n  caption = \"Relationship between lung capacity and age.\"\n)\n```\n\n::: {.cell-output-display}\nTable: Relationship between lung capacity and age.\n\n| Covariance| Correlation|\n|----------:|-----------:|\n|   8.738289|   0.8196749|\n:::\n:::\n\nThe covariance shows us that the relationship is positive and the correlation coefficient shows us that the relationship is a strong, positive relationship. So the older the people in the data the larger the lung capacity was observed, on average.\n\n\n# Question 2\n\n**Let X = number of prior convictions for prisoners at a state prison at which there are 810 prisoners.**\n\n\nFirst I will create two data frames of the values provided that will be used to answers the following questions.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nprison_data <- data.frame(X=c(0,1,2,3,4), Frequency = c(128, 434, 160, 64, 24))\n\nprison_indi_data <- data.frame(X = c(rep(0,128),rep(1,434),rep(2,160),rep(3,64), rep(4,24)))\n```\n:::\n\n\n## Q2a\n\n*What is the probability that a randomly selected inmate has exactly 2 prior convictions?*\n\n\n::: {.cell}\n\n```{.r .cell-code}\nprison_props <-  prison_data %>% group_by(X) %>%\n    summarise(Frequency = Frequency,\n      Proportion = Frequency / sum(prison_data$Frequency))\nknitr::kable(prison_props,\n  caption=\"Proportion of Inmates\"\n\n)\n```\n\n::: {.cell-output-display}\nTable: Proportion of Inmates\n\n|  X| Frequency| Proportion|\n|--:|---------:|----------:|\n|  0|       128|  0.1580247|\n|  1|       434|  0.5358025|\n|  2|       160|  0.1975309|\n|  3|        64|  0.0790123|\n|  4|        24|  0.0296296|\n:::\n:::\n\n\nBy calculating the proportion of inmates with each number of prior convictions we can see that the probability of randomly selecting an inmate with 2 prior convictions is 0.1975 or about 19.8%.\n\n## Q2b\n\n*What is the probability that a randomly selected inmate has fewer than 2 prior convictions?*\n\n\n::: {.cell}\n\n```{.r .cell-code}\nprint(paste(\"Probability of fewer than 2 prior convictions:\",\nsum(filter(prison_props, X < 2)$Proportion)))\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] \"Probability of fewer than 2 prior convictions: 0.693827160493827\"\n```\n:::\n:::\n\n\nSumming prisoners with zero and one prior conviction provides us a probability that 0.6938 or about 69.4% chance that a randomly selected inmate would have less than 2 prior convictions.\n\n## Q2c\n\n*What is the probability that a randomly selected inmate has 2 or fewer prior convictions?*\n\n\n::: {.cell}\n\n```{.r .cell-code}\nprint(paste(\"Probability of 2 or fewer prior convictions:\",\n            sum(filter(prison_props, X <=2)$Proportion)))\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] \"Probability of 2 or fewer prior convictions: 0.891358024691358\"\n```\n:::\n:::\n\n\nSumming the prisoners with two or fewer prior convictions gives us the probability that 0.89 or about 89% probability that a randomly selected inmate would have two prior convictions or fewer.\n\n## Q2d\n\nWhat is the probability that a randomly selected inmate has more than two prior convictions?\n\n\n::: {.cell}\n\n```{.r .cell-code}\nprint(paste(\"Probability of more than 2 prior convictions:\",\nsum(filter(prison_props, X > 2)$Proportion)))\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] \"Probability of more than 2 prior convictions: 0.108641975308642\"\n```\n:::\n:::\n\nThe probability found for either 3 or 4 prior convictions (there is no inmate with more than 4 prior convictions) is 0.1084 or about 10.8% probability.\n\n## Q2e\n\n*What is the expected value for the number of prior convictions?*\n\n\n::: {.cell}\n\n```{.r .cell-code}\nprint(paste(\"The expected value for prior convictions:\", mean(prison_indi_data$X)))\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] \"The expected value for prior convictions: 1.28641975308642\"\n```\n:::\n:::\n\n\nBy taking a weighted average or an average of all possible observations to select from the expected value is 1.28642 or about 1.3 prior convictions.\n\n## Q2f\n\n*Calculate the variance and standard deviation for Prior Convictions.*\n\n\n::: {.cell}\n\n```{.r .cell-code}\nknitr::kable(\n  prison_indi_data %>% summarise(Variance = var(X),\n                     \"Standard Deviation\" = sd(X)),\n  caption = \"Spread of Inmate Prior Convictions\"\n)\n```\n\n::: {.cell-output-display}\nTable: Spread of Inmate Prior Convictions\n\n|  Variance| Standard Deviation|\n|---------:|------------------:|\n| 0.8572937|          0.9259016|\n:::\n:::\n",
    "supporting": [
      "HW1_ToryBartelloni_files"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}