{
  "hash": "778f9621be4b0c945c41fb0e2e65ffd0",
  "result": {
    "markdown": "---\ntitle: \"Final Project: Part 3\"\nsubtitle: \"Florida Homelessness by County 2018-2020\"\nauthor: \"Dane Shelton\"\ndesription: \"Data Exploration, Visualizations, Analysis\"\ndate: \"12/15/2022\"\nformat:\n  html:\n    callout-appearance: \"simple\"\n    callout-icon: FALSE\n    df-print: paged\n    toc: true\n    code-fold: true\n    code-copy: true\n    code-tools: true\ncategories:\n  - finalpart3\n  - shelton\n  - homelessness\n---\n\n\n\n\n## Homelessness in Florida\n\nHomelessness is a complex living situation with several qualifying conditions; at its simplest state, the U.S Dept. of Housing and Urban Development defines it as **lacking a fixed, regular nighttime residence (not a shelter) or having a nighttime residence not designed for human accommodation**^1^.\n\nOn a single night in 2020, over 500,000^2^ people experienced homelessness in the United States. Florida, the third largest state by population , had the fourth largest homeless population of 2020 with 27,487^2^.\n\nFlorida counties represent a wide range of demographic profiles; the state is a hub to a variety of industries including tourism, defense, agriculture, and information technology. Investigating homelessness in Florida counties with robust data can lead to several conclusions about *who* is being impacted *where*, and how state policy is failing (or aiding) groups of a diverse population.\n\n::: panel-tabset\n\n## Research Question\n\nCarole Zugazaga's 2004 study of 54 single homeless men, 54 single homeless women, and 54 homeless women with children in the Central Florida area investigated stressful life events common among homeless people. Interview responses revealed that women were more likely to have been sexually or physically assaulted, while men were more likely to have been incarcerated or abuse drugs/alcohol. Homeless women with children were more likely to be in foster care as a youth.\n\nNearly a decade later, county-level data can be used to investigate the relationship between Zugazaga's reported stressful life events (incarceration, drug arrests, poverty, forcible sex, foster care)^3^ and homelessness rates.\n\n::: callout-note\n## Research Question\n\nDo particular life stressors increase a population's vulnerability to homelessness?\n:::\n\n## Hypothesis\n\nHomelessness is not a new issue in the United States, yet homeless policy targets elimination via criminalization rather than prevention. A 2019 article from [Homeless Voice](https://homelessvoice.org/the-policies-and-laws-of-florida-cities/) provides a brief description of homeless policy in major citites across Florida. Despite state and federal governments being aware of the circumstances that increase vulnerability to homelessness for decades, I anticipate at least one Zugazaga's five stressors to remain significant in a model relating stressors to Florida homelessness counts 2018-2020.\n\n::: callout-note\n## Research Hypothesis\n\n**H~0~:** All stressors are insignificant in predicting homelessness counts **(** B~i~ = 0 for i=0,1,2,...n **)**\n\n**H~A~:** At least one stressor **B~i~** is significant in predicting homelessness counts\n:::\n\n## Introduction to Data\n\n\n\n\n\nThe data `florida_1820.csv` describes population, homelessness counts, poverty counts and several other demographic indicators^3^ at the county level from 2018 to 2020. All 67 Florida counties have observations for the 3 years giving us 201 observations of 15 variables. Each observation provides a count for all variables from a single county for a year. The variables closely mirror the stressors mentioned in Zugazaga's study, along with supplementary variables in an attempt to completely capture the circumstances.\n\nThe data were collected from the [Florida Department of Health](https://www.flhealthcharts.gov/charts/default.aspx). Variable names^3^ were used as search indicators to produce counts for Florida counties. Unfortunately, we cannot accurately analyze the effect of COVID-19 as data is incomplete for the majority of counties in 2021.\n\n:::{.callout-note collapse=\"true\"}\n\n## Intro to Data\n\n\n::: {.cell}\n::: {.cell-output-display}\n`````{=html}\n<div data-pagedtable=\"false\">\n  <script data-pagedtable-source type=\"application/json\">\n{\"columns\":[{\"label\":[\"County\"],\"name\":[1],\"type\":[\"chr\"],\"align\":[\"left\"]},{\"label\":[\"Year\"],\"name\":[2],\"type\":[\"dbl\"],\"align\":[\"right\"]},{\"label\":[\"Homeless (Count)\"],\"name\":[3],\"type\":[\"dbl\"],\"align\":[\"right\"]},{\"label\":[\"Population\"],\"name\":[4],\"type\":[\"dbl\"],\"align\":[\"right\"]},{\"label\":[\"Unemployment Rate\"],\"name\":[5],\"type\":[\"dbl\"],\"align\":[\"right\"]},{\"label\":[\"Median Inc\"],\"name\":[6],\"type\":[\"dbl\"],\"align\":[\"right\"]},{\"label\":[\"Incarceration (Rateper1000)\"],\"name\":[7],\"type\":[\"dbl\"],\"align\":[\"right\"]},{\"label\":[\"Poverty (Count)\"],\"name\":[8],\"type\":[\"dbl\"],\"align\":[\"right\"]},{\"label\":[\"Drug Arrests (Count)\"],\"name\":[9],\"type\":[\"dbl\"],\"align\":[\"right\"]},{\"label\":[\"Relocated (Rate)\"],\"name\":[10],\"type\":[\"dbl\"],\"align\":[\"right\"]},{\"label\":[\"Sub Abuse Enrollment (Count)\"],\"name\":[11],\"type\":[\"dbl\"],\"align\":[\"right\"]},{\"label\":[\"Adult Psych Beds (Count)\"],\"name\":[12],\"type\":[\"dbl\"],\"align\":[\"right\"]},{\"label\":[\"Severe Housing Problems (Rate)\"],\"name\":[13],\"type\":[\"dbl\"],\"align\":[\"right\"]},{\"label\":[\"Forcible Sex (Count)\"],\"name\":[14],\"type\":[\"dbl\"],\"align\":[\"right\"]},{\"label\":[\"Foster Care (Count)\"],\"name\":[15],\"type\":[\"dbl\"],\"align\":[\"right\"]}],\"data\":[{\"1\":\"Alachua\",\"2\":\"2018\",\"3\":\"641\",\"4\":\"263753\",\"5\":\"3.3\",\"6\":\"49078\",\"7\":\"3.3\",\"8\":\"54072\",\"9\":\"1173\",\"10\":\"21.67534\",\"11\":\"519\",\"12\":\"91\",\"13\":\"19.7\",\"14\":\"322\",\"15\":\"277\"},{\"1\":\"Alachua\",\"2\":\"2019\",\"3\":\"714\",\"4\":\"266649\",\"5\":\"3.1\",\"6\":\"49689\",\"7\":\"2.8\",\"8\":\"53601\",\"9\":\"1100\",\"10\":\"21.24971\",\"11\":\"445\",\"12\":\"91\",\"13\":\"NA\",\"14\":\"315\",\"15\":\"263\"},{\"1\":\"Alachua\",\"2\":\"2020\",\"3\":\"657\",\"4\":\"270405\",\"5\":\"5.4\",\"6\":\"50089\",\"7\":\"2.4\",\"8\":\"52647\",\"9\":\"631\",\"10\":\"20.79662\",\"11\":\"405\",\"12\":\"91\",\"13\":\"NA\",\"14\":\"275\",\"15\":\"323\"},{\"1\":\"Baker\",\"2\":\"2018\",\"3\":\"0\",\"4\":\"27488\",\"5\":\"3.4\",\"6\":\"61769\",\"7\":\"18.6\",\"8\":\"3664\",\"9\":\"204\",\"10\":\"12.48794\",\"11\":\"103\",\"12\":\"0\",\"13\":\"10.4\",\"14\":\"14\",\"15\":\"33\"},{\"1\":\"Baker\",\"2\":\"2019\",\"3\":\"0\",\"4\":\"28089\",\"5\":\"3.3\",\"6\":\"63275\",\"7\":\"17.1\",\"8\":\"3017\",\"9\":\"225\",\"10\":\"11.75921\",\"11\":\"65\",\"12\":\"0\",\"13\":\"NA\",\"14\":\"27\",\"15\":\"36\"},{\"1\":\"Baker\",\"2\":\"2020\",\"3\":\"0\",\"4\":\"28588\",\"5\":\"4.9\",\"6\":\"62299\",\"7\":\"17.5\",\"8\":\"2731\",\"9\":\"158\",\"10\":\"10.60835\",\"11\":\"39\",\"12\":\"0\",\"13\":\"NA\",\"14\":\"16\",\"15\":\"58\"}],\"options\":{\"columns\":{\"min\":{},\"max\":[10]},\"rows\":{\"min\":[10],\"max\":[10]},\"pages\":{}}}\n  </script>\n</div>\n`````\n:::\n\n::: {.cell-output .cell-output-stdout}\n```\n    County               Year      Homeless (Count)   Population     \n Length:201         Min.   :2018   Min.   :   0.0   Min.   :   8367  \n Class :character   1st Qu.:2018   1st Qu.:  11.0   1st Qu.:  28089  \n Mode  :character   Median :2019   Median : 151.0   Median : 130642  \n                    Mean   :2019   Mean   : 427.8   Mean   : 317746  \n                    3rd Qu.:2020   3rd Qu.: 563.0   3rd Qu.: 367471  \n                    Max.   :2020   Max.   :3516.0   Max.   :2864600  \n                                                                     \n Unemployment Rate   Median Inc    Incarceration (Rateper1000) Poverty (Count) \n Min.   : 2.100    Min.   :34583   Min.   : 0.60               Min.   :   906  \n 1st Qu.: 3.400    1st Qu.:41401   1st Qu.: 2.50               1st Qu.:  4901  \n Median : 4.000    Median :50640   Median : 3.40               Median : 16210  \n Mean   : 4.697    Mean   :51116   Mean   : 3.84               Mean   : 42922  \n 3rd Qu.: 5.600    3rd Qu.:58093   3rd Qu.: 4.50               3rd Qu.: 46034  \n Max.   :13.500    Max.   :83803   Max.   :18.60               Max.   :482656  \n                                                                               \n Drug Arrests (Count) Relocated (Rate) Sub Abuse Enrollment (Count)\n Min.   :   13        Min.   : 4.689   Min.   :   5.0              \n 1st Qu.:  225        1st Qu.:11.244   1st Qu.:  76.0              \n Median :  729        Median :12.700   Median : 250.0              \n Mean   : 1558        Mean   :13.288   Mean   : 877.6              \n 3rd Qu.: 1903        3rd Qu.:14.544   3rd Qu.:1030.0              \n Max.   :13038        Max.   :22.553   Max.   :6272.0              \n                                                                   \n Adult Psych Beds (Count) Severe Housing Problems (Rate) Forcible Sex (Count)\n Min.   :  0.00           Min.   : 9.6                   Min.   :   0.0      \n 1st Qu.:  0.00           1st Qu.:13.3                   1st Qu.:  14.0      \n Median :  0.00           Median :15.4                   Median :  45.0      \n Mean   : 66.26           Mean   :15.8                   Mean   : 170.5      \n 3rd Qu.: 84.00           3rd Qu.:17.3                   3rd Qu.: 225.0      \n Max.   :778.00           Max.   :29.8                   Max.   :1408.0      \n                          NA's   :134                                        \n Foster Care (Count)\n Min.   :   3.0     \n 1st Qu.:  33.0     \n Median : 153.0     \n Mean   : 326.1     \n 3rd Qu.: 353.0     \n Max.   :2289.0     \n                    \n```\n:::\n\n::: {.cell-output-display}\n`````{=html}\n<div data-pagedtable=\"false\">\n  <script data-pagedtable-source type=\"application/json\">\n{\"columns\":[{\"label\":[\"County\"],\"name\":[1],\"type\":[\"chr\"],\"align\":[\"left\"]},{\"label\":[\"Mean Population\"],\"name\":[2],\"type\":[\"dbl\"],\"align\":[\"right\"]},{\"label\":[\"Mean Homeless\"],\"name\":[3],\"type\":[\"dbl\"],\"align\":[\"right\"]},{\"label\":[\"Avg Homeless Rate\"],\"name\":[4],\"type\":[\"dbl\"],\"align\":[\"right\"]},{\"label\":[\"Avg Median Income\"],\"name\":[5],\"type\":[\"dbl\"],\"align\":[\"right\"]},{\"label\":[\"Mean Poverty\"],\"name\":[6],\"type\":[\"dbl\"],\"align\":[\"right\"]},{\"label\":[\"Avg Poverty Rate\"],\"name\":[7],\"type\":[\"dbl\"],\"align\":[\"right\"]},{\"label\":[\"Avg Incarceration Rate (per 1000)\"],\"name\":[8],\"type\":[\"dbl\"],\"align\":[\"right\"]}],\"data\":[{\"1\":\"Miami-Dade\",\"2\":\"2833087\",\"3\":\"3487\",\"4\":\"1.230695e-03\",\"5\":\"51435\",\"6\":\"454930\",\"7\":\"0.16057763\",\"8\":\"1.433333\"},{\"1\":\"Broward\",\"2\":\"1925443\",\"3\":\"2478\",\"4\":\"1.286804e-03\",\"5\":\"59267\",\"6\":\"249869\",\"7\":\"0.12977206\",\"8\":\"1.800000\"},{\"1\":\"Palm Beach\",\"2\":\"1456920\",\"3\":\"1405\",\"4\":\"9.645917e-04\",\"5\":\"62752\",\"6\":\"176150\",\"7\":\"0.12090549\",\"8\":\"1.266667\"},{\"1\":\"Hillsborough\",\"2\":\"1448564\",\"3\":\"1698\",\"4\":\"1.172426e-03\",\"5\":\"58529\",\"6\":\"204095\",\"7\":\"0.14089497\",\"8\":\"2.166667\"},{\"1\":\"Orange\",\"2\":\"1395458\",\"3\":\"1495\",\"4\":\"1.071094e-03\",\"5\":\"58002\",\"6\":\"197579\",\"7\":\"0.14158717\",\"8\":\"1.866667\"},{\"1\":\"Pinellas\",\"2\":\"978993\",\"3\":\"2412\",\"4\":\"2.463755e-03\",\"5\":\"53988\",\"6\":\"116644\",\"7\":\"0.11914688\",\"8\":\"2.833333\"},{\"1\":\"Duval\",\"2\":\"971693\",\"3\":\"1543\",\"4\":\"1.587607e-03\",\"5\":\"55350\",\"6\":\"135595\",\"7\":\"0.13954476\",\"8\":\"3.300000\"},{\"1\":\"Lee\",\"2\":\"737532\",\"3\":\"601\",\"4\":\"8.144283e-04\",\"5\":\"57377\",\"6\":\"94189\",\"7\":\"0.12770796\",\"8\":\"2.233333\"},{\"1\":\"Polk\",\"2\":\"692551\",\"3\":\"560\",\"4\":\"8.086051e-04\",\"5\":\"50206\",\"6\":\"106580\",\"7\":\"0.15389440\",\"8\":\"3.700000\"},{\"1\":\"Brevard\",\"2\":\"593859\",\"3\":\"788\",\"4\":\"1.326915e-03\",\"5\":\"56831\",\"6\":\"68889\",\"7\":\"0.11600291\",\"8\":\"2.800000\"},{\"1\":\"Volusia\",\"2\":\"539700\",\"3\":\"735\",\"4\":\"1.361867e-03\",\"5\":\"49554\",\"6\":\"74826\",\"7\":\"0.13864422\",\"8\":\"2.633333\"},{\"1\":\"Pasco\",\"2\":\"528527\",\"3\":\"1048\",\"4\":\"1.982868e-03\",\"5\":\"52225\",\"6\":\"66130\",\"7\":\"0.12512125\",\"8\":\"3.066667\"},{\"1\":\"Seminole\",\"2\":\"472273\",\"3\":\"304\",\"4\":\"6.436955e-04\",\"5\":\"66942\",\"6\":\"48468\",\"7\":\"0.10262638\",\"8\":\"2.000000\"},{\"1\":\"Sarasota\",\"2\":\"425909\",\"3\":\"612\",\"4\":\"1.436145e-03\",\"5\":\"61841\",\"6\":\"37595\",\"7\":\"0.08827088\",\"8\":\"2.166667\"},{\"1\":\"Manatee\",\"2\":\"389176\",\"3\":\"517\",\"4\":\"1.329305e-03\",\"5\":\"58336\",\"6\":\"44445\",\"7\":\"0.11420378\",\"8\":\"2.566667\"},{\"1\":\"Collier\",\"2\":\"377216\",\"3\":\"585\",\"4\":\"1.549951e-03\",\"5\":\"68515\",\"6\":\"42258\",\"7\":\"0.11202502\",\"8\":\"1.966667\"},{\"1\":\"Osceola\",\"2\":\"372412\",\"3\":\"225\",\"4\":\"6.032745e-04\",\"5\":\"52627\",\"6\":\"51635\",\"7\":\"0.13865020\",\"8\":\"2.266667\"},{\"1\":\"Marion\",\"2\":\"360875\",\"3\":\"523\",\"4\":\"1.449255e-03\",\"5\":\"45106\",\"6\":\"55235\",\"7\":\"0.15305854\",\"8\":\"3.966667\"},{\"1\":\"Lake\",\"2\":\"355240\",\"3\":\"273\",\"4\":\"7.694321e-04\",\"5\":\"54063\",\"6\":\"40429\",\"7\":\"0.11380652\",\"8\":\"2.466667\"},{\"1\":\"Escambia\",\"2\":\"321524\",\"3\":\"535\",\"4\":\"1.664987e-03\",\"5\":\"51075\",\"6\":\"41366\",\"7\":\"0.12865499\",\"8\":\"4.933333\"},{\"1\":\"St. Lucie\",\"2\":\"310145\",\"3\":\"733\",\"4\":\"2.364483e-03\",\"5\":\"52311\",\"6\":\"42809\",\"7\":\"0.13802991\",\"8\":\"4.100000\"},{\"1\":\"Leon\",\"2\":\"295820\",\"3\":\"872\",\"4\":\"2.946615e-03\",\"5\":\"52994\",\"6\":\"55824\",\"7\":\"0.18871069\",\"8\":\"3.633333\"},{\"1\":\"Alachua\",\"2\":\"266936\",\"3\":\"671\",\"4\":\"2.512466e-03\",\"5\":\"49619\",\"6\":\"53440\",\"7\":\"0.20019805\",\"8\":\"2.833333\"},{\"1\":\"St. Johns\",\"2\":\"252469\",\"3\":\"355\",\"4\":\"1.407434e-03\",\"5\":\"81126\",\"6\":\"19667\",\"7\":\"0.07789867\",\"8\":\"1.766667\"},{\"1\":\"Clay\",\"2\":\"216866\",\"3\":\"70\",\"4\":\"3.227795e-04\",\"5\":\"65683\",\"6\":\"21173\",\"7\":\"0.09763003\",\"8\":\"1.900000\"},{\"1\":\"Okaloosa\",\"2\":\"201280\",\"3\":\"355\",\"4\":\"1.765371e-03\",\"5\":\"63278\",\"6\":\"21855\",\"7\":\"0.10857861\",\"8\":\"3.833333\"},{\"1\":\"Hernando\",\"2\":\"189090\",\"3\":\"161\",\"4\":\"8.532077e-04\",\"5\":\"48374\",\"6\":\"26213\",\"7\":\"0.13862510\",\"8\":\"3.266667\"},{\"1\":\"Charlotte\",\"2\":\"181034\",\"3\":\"163\",\"4\":\"9.003817e-04\",\"5\":\"51149\",\"6\":\"19392\",\"7\":\"0.10711964\",\"8\":\"3.533333\"},{\"1\":\"Santa Rosa\",\"2\":\"179687\",\"3\":\"20\",\"4\":\"1.113049e-04\",\"5\":\"68285\",\"6\":\"16539\",\"7\":\"0.09204356\",\"8\":\"3.633333\"},{\"1\":\"Bay\",\"2\":\"179298\",\"3\":\"407\",\"4\":\"2.268105e-03\",\"5\":\"54209\",\"6\":\"25236\",\"7\":\"0.14074706\",\"8\":\"4.500000\"},{\"1\":\"Martin\",\"2\":\"158243\",\"3\":\"307\",\"4\":\"1.940058e-03\",\"5\":\"61638\",\"6\":\"15907\",\"7\":\"0.10052072\",\"8\":\"2.700000\"},{\"1\":\"Indian River\",\"2\":\"155208\",\"3\":\"473\",\"4\":\"3.047517e-03\",\"5\":\"55007\",\"6\":\"17193\",\"7\":\"0.11077154\",\"8\":\"3.366667\"},{\"1\":\"Citrus\",\"2\":\"147560\",\"3\":\"201\",\"4\":\"1.359899e-03\",\"5\":\"43783\",\"6\":\"22500\",\"7\":\"0.15248035\",\"8\":\"4.300000\"},{\"1\":\"Sumter\",\"2\":\"129910\",\"3\":\"27\",\"4\":\"2.104015e-04\",\"5\":\"57357\",\"6\":\"9941\",\"7\":\"0.07651945\",\"8\":\"3.466667\"},{\"1\":\"Flagler\",\"2\":\"111057\",\"3\":\"88\",\"4\":\"7.953897e-04\",\"5\":\"55307\",\"6\":\"12786\",\"7\":\"0.11513041\",\"8\":\"1.900000\"},{\"1\":\"Highlands\",\"2\":\"103697\",\"3\":\"113\",\"4\":\"1.092924e-03\",\"5\":\"40655\",\"6\":\"18264\",\"7\":\"0.17612475\",\"8\":\"4.133333\"},{\"1\":\"Nassau\",\"2\":\"85216\",\"3\":\"88\",\"4\":\"1.032666e-03\",\"5\":\"69746\",\"6\":\"8400\",\"7\":\"0.09857265\",\"8\":\"3.066667\"},{\"1\":\"Monroe\",\"2\":\"75356\",\"3\":\"637\",\"4\":\"8.453246e-03\",\"5\":\"69689\",\"6\":\"8272\",\"7\":\"0.10977719\",\"8\":\"6.833333\"},{\"1\":\"Putnam\",\"2\":\"73263\",\"3\":\"98\",\"4\":\"1.333097e-03\",\"5\":\"37796\",\"6\":\"16940\",\"7\":\"0.23122176\",\"8\":\"4.466667\"},{\"1\":\"Columbia\",\"2\":\"70291\",\"3\":\"327\",\"4\":\"4.647325e-03\",\"5\":\"45268\",\"6\":\"10225\",\"7\":\"0.14546601\",\"8\":\"3.200000\"},{\"1\":\"Walton\",\"2\":\"70269\",\"3\":\"76\",\"4\":\"1.076819e-03\",\"5\":\"59756\",\"6\":\"8710\",\"7\":\"0.12394808\",\"8\":\"3.566667\"},{\"1\":\"Jackson\",\"2\":\"49395\",\"3\":\"3\",\"4\":\"6.748321e-05\",\"5\":\"39876\",\"6\":\"7775\",\"7\":\"0.15740460\",\"8\":\"5.100000\"},{\"1\":\"Gadsden\",\"2\":\"47481\",\"3\":\"7\",\"4\":\"1.544467e-04\",\"5\":\"41153\",\"6\":\"9732\",\"7\":\"0.20495774\",\"8\":\"2.366667\"},{\"1\":\"Suwannee\",\"2\":\"45544\",\"3\":\"158\",\"4\":\"3.461828e-03\",\"5\":\"45602\",\"6\":\"6575\",\"7\":\"0.14436483\",\"8\":\"3.900000\"},{\"1\":\"Okeechobee\",\"2\":\"41675\",\"3\":\"49\",\"4\":\"1.167757e-03\",\"5\":\"42741\",\"6\":\"7765\",\"7\":\"0.18632125\",\"8\":\"5.866667\"},{\"1\":\"Levy\",\"2\":\"41513\",\"3\":\"27\",\"4\":\"6.423742e-04\",\"5\":\"37970\",\"6\":\"8080\",\"7\":\"0.19463939\",\"8\":\"4.200000\"},{\"1\":\"Hendry\",\"2\":\"40122\",\"3\":\"45\",\"4\":\"1.121589e-03\",\"5\":\"39509\",\"6\":\"10567\",\"7\":\"0.26337390\",\"8\":\"6.300000\"},{\"1\":\"DeSoto\",\"2\":\"36015\",\"3\":\"104\",\"4\":\"2.887659e-03\",\"5\":\"35618\",\"6\":\"9474\",\"7\":\"0.26306388\",\"8\":\"3.966667\"},{\"1\":\"Wakulla\",\"2\":\"32721\",\"3\":\"1\",\"4\":\"4.074897e-05\",\"5\":\"63889\",\"6\":\"2999\",\"7\":\"0.09166480\",\"8\":\"4.266667\"},{\"1\":\"Bradford\",\"2\":\"28452\",\"3\":\"12\",\"4\":\"4.334786e-04\",\"5\":\"45233\",\"6\":\"4896\",\"7\":\"0.17209101\",\"8\":\"5.433333\"},{\"1\":\"Baker\",\"2\":\"28055\",\"3\":\"0\",\"4\":\"0.000000e+00\",\"5\":\"62448\",\"6\":\"3137\",\"7\":\"0.11182796\",\"8\":\"17.733333\"},{\"1\":\"Hardee\",\"2\":\"27439\",\"3\":\"74\",\"4\":\"2.696859e-03\",\"5\":\"38814\",\"6\":\"6356\",\"7\":\"0.23165043\",\"8\":\"4.566667\"},{\"1\":\"Washington\",\"2\":\"25281\",\"3\":\"4\",\"4\":\"1.450384e-04\",\"5\":\"37157\",\"6\":\"5168\",\"7\":\"0.20441180\",\"8\":\"5.266667\"},{\"1\":\"Taylor\",\"2\":\"22521\",\"3\":\"7\",\"4\":\"2.960156e-04\",\"5\":\"38512\",\"6\":\"3687\",\"7\":\"0.16371144\",\"8\":\"5.666667\"},{\"1\":\"Holmes\",\"2\":\"20269\",\"3\":\"1\",\"4\":\"4.933724e-05\",\"5\":\"38975\",\"6\":\"4092\",\"7\":\"0.20187153\",\"8\":\"7.733333\"},{\"1\":\"Madison\",\"2\":\"19402\",\"3\":\"0\",\"4\":\"0.000000e+00\",\"5\":\"35929\",\"6\":\"4665\",\"7\":\"0.24041782\",\"8\":\"3.500000\"},{\"1\":\"Gilchrist\",\"2\":\"17762\",\"3\":\"0\",\"4\":\"0.000000e+00\",\"5\":\"44459\",\"6\":\"2642\",\"7\":\"0.14874172\",\"8\":\"2.666667\"},{\"1\":\"Dixie\",\"2\":\"16662\",\"3\":\"0\",\"4\":\"0.000000e+00\",\"5\":\"39913\",\"6\":\"3031\",\"7\":\"0.18188729\",\"8\":\"8.033333\"},{\"1\":\"Gulf\",\"2\":\"15819\",\"3\":\"3\",\"4\":\"1.685701e-04\",\"5\":\"47548\",\"6\":\"1695\",\"7\":\"0.10716844\",\"8\":\"3.433333\"},{\"1\":\"Union\",\"2\":\"15815\",\"3\":\"0\",\"4\":\"0.000000e+00\",\"5\":\"47060\",\"6\":\"1888\",\"7\":\"0.11938285\",\"8\":\"2.133333\"},{\"1\":\"Calhoun\",\"2\":\"15064\",\"3\":\"1\",\"4\":\"4.425660e-05\",\"5\":\"38405\",\"6\":\"1773\",\"7\":\"0.11770043\",\"8\":\"4.600000\"},{\"1\":\"Jefferson\",\"2\":\"14799\",\"3\":\"2\",\"4\":\"1.351412e-04\",\"5\":\"48165\",\"6\":\"1918\",\"7\":\"0.12960043\",\"8\":\"2.866667\"},{\"1\":\"Hamilton\",\"2\":\"14704\",\"3\":\"30\",\"4\":\"2.040307e-03\",\"5\":\"37151\",\"6\":\"3134\",\"7\":\"0.21314411\",\"8\":\"3.833333\"},{\"1\":\"Glades\",\"2\":\"13174\",\"3\":\"35\",\"4\":\"2.631512e-03\",\"5\":\"40188\",\"6\":\"2110\",\"7\":\"0.16019331\",\"8\":\"2.833333\"},{\"1\":\"Franklin\",\"2\":\"12202\",\"3\":\"0\",\"4\":\"0.000000e+00\",\"5\":\"46104\",\"6\":\"2037\",\"7\":\"0.16691253\",\"8\":\"6.766667\"},{\"1\":\"Liberty\",\"2\":\"8907\",\"3\":\"15\",\"4\":\"1.684006e-03\",\"5\":\"38166\",\"6\":\"1165\",\"7\":\"0.13075369\",\"8\":\"5.233333\"},{\"1\":\"Lafayette\",\"2\":\"8567\",\"3\":\"18\",\"4\":\"2.101086e-03\",\"5\":\"47147\",\"6\":\"1208\",\"7\":\"0.14096728\",\"8\":\"3.600000\"}],\"options\":{\"columns\":{\"min\":{},\"max\":[10]},\"rows\":{\"min\":[10],\"max\":[10]},\"pages\":{}}}\n  </script>\n</div>\n`````\n:::\n:::\n\n\n:::\n\nExpanding **Intro to Data** exposes summary statistics including mean, range, quantiles, and standard deviation for all 15 variables. The table below the summaries provides arranged figures for basic parameters of interest grouped by county.\n\n\n\n## Visualizations\n\n`ggplot2` is used to visualize important relationships between homeless counts and Zugazaga's stressors. The Florida counties have been categorized into 4 `Regions` and 3 `Income Levels`:\n\n:::callout-note\n## `Region`\n  - **Northwest**: Escambia County to Madison County; cities include Pensacola, Panama City Beach, and Tallahassee\n  \n  - **North**: Hamilton County to Marion County; cities include Jacksonville, Gainseville,and Ocala, St. Augustine \n  \n  - **Central**: Lake County to Okeechobee County; cities include Orlando, Kissimmee, Tampa, St. Petersburg\n  \n  - **South**: Sarasota County to Miami-Dade County; cities include Ft. Lauderdale, Ft. Myers, Miami, Boca Raton, West Palm Beach\n:::\n  \n:::callout-note\n## `Income Level`\n  - **High**: Median Income >= 60000\n  \n  - **Medium**: Median Income >= 40000\n  \n  - **Low**: Median Income < 40000\n:::\n  \n\n::: {.cell}\n\n:::\n\n\n:::{.callout-note collapse=\"true\"}\n\n## a) Homeless Rate by Region\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Plot 1 \n\nflorida_box <- florida_og_plot %>%\n    mutate(`Homeless (Rate)` = `Homeless (Rate)`*100 )%>%\n      mutate(`Region`=fct_relevel(`Region`, \"Northwest\", \"North\", \"Central\", \"South\"))%>%\n      ggplot(aes(y=`Homeless (Rate)`, x=`Region`, fill=`Region`)) +\n        geom_boxplot(alpha=0.7)+\n  #Scale of y axis\n          scale_y_continuous(breaks=(seq(0,1.5,by=.25)))+\n  # Dimensions of graph\n            coord_cartesian(ylim=c(0,1.5)) +\n              coord_flip()+\n              scale_fill_brewer(palette = 'Set2')+\n                                   theme_grey()+\n                                     theme(legend.position = \"none\")+\n                                        labs(title= \"Florida Homeless Rates\", \n                                             subtitle=\"2018-2020\", \n                                              x= \" \", \n                                                y= \"Homeless Rate (%)\", \n                                            caption = \"Visualized by Region\")\n\nflorida_box\n```\n\n::: {.cell-output-display}\n![](shelton_final3_files/figure-html/plot1 - boxplot by region-1.png){width=672}\n:::\n:::\n\n- A look at the distributions of homeless rates across Florida counties displays *where* the highest rates in the state exists.\n\n- The state is generally uniform, with the bulk of each region's distribution sitting below 0.25% of county populations. \n  \n  - The largest difference is between the distributions of Northwest Florida and South Florida. This can be attributed to the stark contrast in where the population in these regions are living. \n  \n  - South Florida is the most urbanized region in the state, with  millions living in Miami, Ft. Lauderdale, and West Palm Beach; Northwest Florida is quite the opposite, with small coastal towns and rural inland towns reminiscent of Southern Alabama or Georgia.\n\n:::\n\n:::{.callout-note collapse=\"true\"}\n\n## b) Homeless Rate by Income Level\n\n\n::: {.cell}\n\n```{.r .cell-code}\n\n# Plot 2\nflorida_income <- florida_og_plot %>%\n    mutate(`Homeless (Rate)` = `Homeless (Rate)`*100)%>%\n      mutate(`Income Level` = fct_relevel(`Income Level`, \"Low\", \"Medium\", \"High\"))%>%\n      ggplot(aes(y=`Homeless (Rate)`, x=`Region`,\n                  fill=`Income Level`, \n                    )) +\n      geom_bar(position='dodge', stat='identity')+\n          \n              scale_fill_brewer(palette = 'Set2')+\n                                   theme_grey()+\n                                     \n                    labs(title= \"Barplot: Income Level x Homeless Rate\", \n                           subtitle=\"2018-2020\", \n                              x= \"Region\", \n                                y= \"Homeless Rate (%)\", \n                                  caption = \"Visualized by Income Level\")\n\nflorida_income\n```\n\n::: {.cell-output-display}\n![](shelton_final3_files/figure-html/plot2 - homeless x income-1.png){width=672}\n:::\n:::\n\n\n- The barplot further details the differences mentioned in `Plot 1`. Regions where the populations are less urbanized show Low Income counties reflecting a higher homeless rate as one would assume. \n\n- Once entering South Florida, wealth disparities in urbanized areas breaks this trend -counties with high income now report high homeless rates\n\n:::\n\n:::{.callout-note collapse=\"true\"}\n\n## c) Homeless Rate x Incarceration Rate per1000\n\n\n::: {.cell}\n\n```{.r .cell-code}\n#Plot 3\n\nflorida_incarc <- florida_og_plot %>%\n    mutate(`Homeless (Rate)` = `Homeless (Rate)`*100,\n           `Incarceration (Rateper1000)`= `Incarceration (Rateper1000)`/10)%>%\n      ggplot(aes(y=`Homeless (Rate)`, \n                  x=`Incarceration (Rateper1000)`, \n                    color=`Region`, \n                      label=`County`)) +\n      geom_point(alpha=0.7)+\n  # Must include because of label aesthetic\n      ggrepel::geom_text_repel(show.legend = FALSE, \n                  max.overlaps = 15, \n                  alpha=0.7,\n                    size=2.5, \n                      nudge_x = -.05, \n                        nudge_y =.05)+\n          \n              scale_fill_brewer(palette = 'Set2')+\n                                   theme_grey()+\n                                     \n                    labs(title= \"Scatterplot: Incarceration x Homeless Rate\", \n                           subtitle=\"2018-2020\", \n                              x= \"Incarceration Rate (per100)\", \n                                y= \"Homeless Rate (%)\", \n                                  caption = \"Visualized by Region\")\n\nflorida_incarc\n```\n\n::: {.cell-output-display}\n![](shelton_final3_files/figure-html/plot3 - scatter incarceration x homeless rate-1.png){width=672}\n:::\n:::\n\n\n- One of Zugazaga's male stressors `Incarceration Rate` is illustrated with Homeless Rate; a positive trend exists relating incarceration rates and homelessness rates across Florida counties.\n\n  - Many state correctional facilities are located in rural counties, explaining both **Baker** and **Monroe** observations' large influence on the plot.\n\n:::\n\n:::{.callout-note collapse=\"true\"}\n\n## d) Homeless Rate x Drug Arrest Rate\n\n::: {.cell}\n\n```{.r .cell-code}\n#Plot 4\n\nflorida_drug <- florida_og_plot %>%\n    mutate(`Homeless (Rate)` = `Homeless (Rate)`*100,\n           `Drug Arrests (Rate)`= `Drug Arrests (Rate)`*100)%>%\n      ggplot(aes(y=`Homeless (Rate)`, \n                  x=`Drug Arrests (Rate)`, \n                    color=`Region`, \n                      label=`County`)) +\n      geom_point(alpha=0.7)+\n  # Must include because of label aesthetic\n      ggrepel::geom_text_repel(show.legend = FALSE, \n                  max.overlaps = 15, \n                  alpha=0.7,\n                    size=2.5, \n                      nudge_x = -.05, \n                        nudge_y =.05)+\n          \n              scale_fill_brewer(palette = 'Set2')+\n                                   theme_grey()+\n                                     \n                    labs(title= \"Scatterplot: Drug Arrest Rate x Homeless Rate\", \n                           subtitle=\"2018-2020\", \n                              x= \"Drug Arrests (Rate)\", \n                                y= \"Homeless Rate (%)\", \n                                  caption = \"Visualized by Region\")\n\nflorida_drug\n```\n\n::: {.cell-output-display}\n![](shelton_final3_files/figure-html/plot4 - drug arrest rate x homeless rate-1.png){width=672}\n:::\n:::\n\n- A similar positive association is seen comparing the homeless rate of a county with its `Drug Arrest (Rate)`.\n\n  - The high influence of Northwest Florida is likely due to stricter drug policies held by police in less urbanized areas. \n\n:::\n\n\n## Regression, Diagnostics, and Model Selection\n\n### on Assumption of Validity\n\nWhile over 10 variables are predicting `Homeless (Rate)` across Florida counties, there are still limitations when attempting to comment on the magnitude of an individual stressor. Stressors influence homelessness by driving those in severe situations *out* of their home or *away* from their place of origin. `Homeless (Rate)` is not an ideal measure of magnitude as the homeless population migrating to escape or avoid certain stressors would result in counties with low stressor values having a higher homeless population; this effect is left unexplained by the following models.\n\n- The variable `Relocated (Rate)` is included as an attempt to control for new movement, however this doesn't completely capture county-to-county migration.\n\n- FL Charts has data that records [Population Who Lived in a Different County One Year Earlier](https://www.flhealthcharts.gov/ChartsDashboards/rdPage.aspx?rdReport=NonVitalIndRateOnly.TenYrsRpt&cid=9759), however with the data spanning 2009-2014, using values recorded 4 years prior to our data isn't desirable either.\n\n- The most appropriate data to accurately capture county-to-county migration is [here](https://www.census.gov/data/tables/2019/demo/geographic-mobility/county-to-county-migration-2015-2019.html) via the US Census Bureau. The `-In, -Out, -Net...` spreadsheet provides totals for each county in the United States and movement to all other US counties; unfortunately, this data is too complex to wrangle into the simple data set `florida_1820.csv`.\n\n\n### on Assumption of Linearity \n\n::: {.cell}\n\n```{.r .cell-code}\n# Fit 1: A Linear Regression Model With All Vars\n\n# Checking Linearity of variables not supported by our literature\n\nflorida_matrix <- florida_og_rates %>%\n                    select(-c('County', \n                              'Year', \n                              'Poverty (Rate)', \n                              'Severe Housing Problems (Rate)',\n                              'Incarceration (Rateper1000)',\n                              'Sub Abuse Enrollment (Rate)',\n                              'Drug Arrests (Rate)',\n                              'Adult Psych Beds (Rate)',\n                              'Foster Care (Rate)',\n                              'Forcible Sex (Rate)' ))%>%\n                      pairs()\n```\n\n::: {.cell-output-display}\n![](shelton_final3_files/figure-html/fit1 scatter-1.png){width=672}\n:::\n\n```{.r .cell-code}\nflorida_matrix\n```\n\n::: {.cell-output .cell-output-stdout}\n```\nNULL\n```\n:::\n:::\n\n\nA quick look at stressors with a relationship to homelessness not mentioned in Zugazaga's study, or those that needed further investigation are shown here to confirm linearity with the response, `Homeless (Rate)`. Checking the bottom row,the associations are weak, but a linear approximation is appropriate. \n\n### Linear Regression Models\n\n:::{.callout-note collapse=\"true\"}\n\n## `Fit 1`: All Variables (No Transformations)\n\n::: {.cell}\n\n```{.r .cell-code}\n# Linear relationship appears appropriate for all, possibly attempt log transformation on UE Rate?\n\n# Creating A Linear Model with all variables included: No Transformations\n\n# County Removed as too many levels; improvement: NWFL, NFL, CFL, SWFL, SOFLO categories?\n\nfit1 <- florida_og_rates %>% \n          select(-'County')%>%\n            \n            lm(formula=`Homeless (Rate)` ~.)\n\nsummary(fit1)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n\nCall:\nlm(formula = `Homeless (Rate)` ~ ., data = .)\n\nResiduals:\n       Min         1Q     Median         3Q        Max \n-0.0021639 -0.0008741 -0.0002945  0.0003981  0.0078061 \n\nCoefficients: (1 not defined because of singularities)\n                                   Estimate Std. Error t value Pr(>|t|)  \n(Intercept)                      -5.014e-03  3.408e-03  -1.471   0.1469  \nYear                                     NA         NA      NA       NA  \n`Unemployment Rate`              -1.993e-04  4.062e-04  -0.491   0.6257  \n`Median Inc`                      5.022e-08  3.506e-08   1.433   0.1576  \n`Incarceration (Rateper1000)`     3.479e-05  1.009e-04   0.345   0.7316  \n`Relocated (Rate)`               -6.075e-05  7.624e-05  -0.797   0.4290  \n`Severe Housing Problems (Rate)`  1.584e-04  7.639e-05   2.074   0.0428 *\n`Poverty (Rate)`                  4.429e-03  8.195e-03   0.540   0.5911  \n`Drug Arrests (Rate)`             9.809e-02  7.369e-02   1.331   0.1886  \n`Sub Abuse Enrollment (Rate)`     4.671e-02  1.374e-01   0.340   0.7351  \n`Adult Psych Beds (Rate)`         3.177e+00  2.138e+00   1.486   0.1429  \n`Forcible Sex (Rate)`             3.717e-02  1.093e+00   0.034   0.9730  \n`Foster Care (Rate)`              6.768e-01  3.664e-01   1.847   0.0701 .\n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n\nResidual standard error: 0.00157 on 55 degrees of freedom\n  (134 observations deleted due to missingness)\nMultiple R-squared:  0.3441,\tAdjusted R-squared:  0.2129 \nF-statistic: 2.623 on 11 and 55 DF,  p-value: 0.00914\n```\n:::\n\n```{.r .cell-code}\nrss1 <- deviance(fit1)\nprint(c('RSS Fit 1', rss1))\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] \"RSS Fit 1\"            \"0.000135542075603397\"\n```\n:::\n:::\n\n- The first model predicts `Homeless (Rate)` using all variables, without any transformations or interactions. This causes 134 observations to removed as they are missing values for `Severe Housing Problems (Rate)`. \n\n- Only 1 variable - `Severe Housing Problems (Rate)` - is deemed significant at `alpha = 0.05`; those without a star (see output) are deemed inconsequential in predicting `Homeless (Rate)`  by this model. \n\n- Effect of `Relocated (Rate)` is negative, indicating that migration can 'help reduce' homelessness by county, as predicted in 'Assumptions on Validity' (above)\n\n- Looking at the signs and magnitude of the predicted (insignificant) variables, they seem plausible - Increases in variables like `Drug Arrests (Rate)` or `Sub Abuse Enrollment (Rate)` increase response  `Homeless (Rate)` substantially. \n  \n  - `Sub Abuse Enrollement (Rate)` can be interpreted here an an indication of how many people in the area are suffering from addiction/abuse problems, rather than a suggestion that substance abuse programs increase homelessness.\n\n:::\n\n:::{.callout-note collapse=\"true\"}\n\n## `Fit 1`: Diagnostics\n\n::: {.cell}\n::: {.cell-output-display}\n![](shelton_final3_files/figure-html/unnamed-chunk-11-1.png){width=672}\n:::\n:::\n\n- `Fit 1` does a poor job of obeying the assumptions regarding residuals of linear regression.\n\n- `Residuals vs Fitted` shows a negative trend the greater the fitted value is, violating the linearity and independence assumption. \n \n  - `Scale - Location` confirms this as the standardized residuals increase in magnitude the greater the fitted value is.\n\n- `Q-Q Plot` shows a  deviation from the diagonal, violating the assumption that residuals follow an approximately Normal distribution \n\n- There are several points that could be considered outliers due to their residual or leverage value, how greatly they influence the points around them in the model. \n\n  - **Monroe County** (130), **Hardee County** (73), and **Columbia County** (34) all have large positive residuals, indicating our model greatly under-estimated the number of homeless people in this county.\n  \n  - **Baker County** (4) has worryingly high leverage, its explanatory values have great influence on the data\n  \n  - All of these outliers represent sparsely populated, rural counties, typically outside of more urbanized areas; hence large values for stressors will command great influence on the model.\n\n:::\n\n:::{.callout-note collapse=\"true\"}\n\n## `Fit 2`: All Variables, All Observations (Fill Severe Housing Rate)\n\n\n::: {.cell}\n\n```{.r .cell-code}\nfit2 <- florida_og_rates %>% \n          select(-c('County','Year'))%>%\n            #mutate(`Unemployment Rate` = log(`Unemployment Rate`))%>%\n              fill('Severe Housing Problems (Rate)', .direction=\"down\")%>%\n                 lm(formula=`Homeless (Rate)` ~ . - `Median Inc`)\nsummary(fit2)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n\nCall:\nlm(formula = `Homeless (Rate)` ~ . - `Median Inc`, data = .)\n\nResiduals:\n       Min         1Q     Median         3Q        Max \n-0.0021111 -0.0007576 -0.0001974  0.0004326  0.0090199 \n\nCoefficients:\n                                   Estimate Std. Error t value Pr(>|t|)    \n(Intercept)                      -1.836e-03  7.330e-04  -2.505 0.013085 *  \n`Unemployment Rate`              -3.357e-05  5.905e-05  -0.568 0.570387    \n`Incarceration (Rateper1000)`     1.381e-05  4.539e-05   0.304 0.761261    \n`Relocated (Rate)`               -2.959e-05  3.255e-05  -0.909 0.364418    \n`Severe Housing Problems (Rate)`  1.639e-04  3.067e-05   5.344 2.58e-07 ***\n`Poverty (Rate)`                 -4.018e-03  2.598e-03  -1.547 0.123596    \n`Drug Arrests (Rate)`             1.074e-01  3.062e-02   3.509 0.000562 ***\n`Sub Abuse Enrollment (Rate)`    -4.182e-02  5.887e-02  -0.710 0.478329    \n`Adult Psych Beds (Rate)`         2.129e+00  8.835e-01   2.410 0.016914 *  \n`Forcible Sex (Rate)`             3.309e-01  4.419e-01   0.749 0.454892    \n`Foster Care (Rate)`              4.915e-01  1.606e-01   3.061 0.002524 ** \n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n\nResidual standard error: 0.001266 on 190 degrees of freedom\nMultiple R-squared:  0.2704,\tAdjusted R-squared:  0.232 \nF-statistic: 7.042 on 10 and 190 DF,  p-value: 2.221e-09\n```\n:::\n\n```{.r .cell-code}\nbic2 <- BIC(fit2)\nprint(c('BIC Fit 2:', bic2))\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] \"BIC Fit 2:\"        \"-2059.47818623585\"\n```\n:::\n\n```{.r .cell-code}\nrss2 <- deviance(fit2)\nprint(c('RSS Fit 2', rss2))\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] \"RSS Fit 2\"            \"0.000304345342188934\"\n```\n:::\n:::\n\n- In `Fit 2`, values from `Severe Housing Problems (Rate)` were filled down to restore all observations for use in the model. \n  \n  - Example: Alachua County has the same `Severe Housing Problems (Rate)` for 2018-2020\n  \n- Several key stressors were deemed significant, with `Adult Psych Beds (Rate)` having the largest magnitude\n\n  - Stressors from Zugazaga's study that were found significant by this model include `Drug Arrests (Rate)` and `Foster Care (Rate)`\n\n:::\n\n:::{.callout-note collapse=\"true\"}\n\n## `Fit 2`: Diagnostics\n\n\n::: {.cell}\n::: {.cell-output-display}\n![](shelton_final3_files/figure-html/diagnostics2-1.png){width=672}\n:::\n:::\n\n\n- Using all observations in `Fit 2`has not improved the diagnostic plots, but including 2019 and 2020 values has revealed new outliers.\n\n- 2020 produced **Liberty County** (117) as an outlier, a small, rural county in the Panhandle of Florida.\n  \n  - In late 2018, Hurricane Michael devastated the area; the influence of this observation is likely a direct result of measurements being altered greatly or even unaccounted during 2019 due to the population being \"in a transitional state\" \n  \n  - Liberty's records in 2020 will show a vast difference to the incomplete measures of 2019\n\n:::\n\n:::{.callout-note collapse=\"true\"}\n\n## `Fit 3`: Random Effects Model - Controlling for County over Time\n\n\n::: {.cell}\n\n```{.r .cell-code}\n#tranform to panel data\nflorida_panel <-  pdata.frame(florida_og_rates, index=c('County','Year'))\n\nfit3 <- florida_panel %>%\n          plm(formula = Homeless..Rate. ~ \n         Unemployment.Rate +             \n         Incarceration..Rateper1000. +\n         Relocated..Rate. +           \n         Poverty..Rate. +        \n         Drug.Arrests..Rate. +          \n         Sub.Abuse.Enrollment..Rate. +  \n         Adult.Psych.Beds..Rate. +      \n         Forcible.Sex..Rate. +           \n         Foster.Care..Rate., \n            model= 'random')\n                   \nsummary(fit3)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\nOneway (individual) effect Random Effect Model \n   (Swamy-Arora's transformation)\n\nCall:\nplm(formula = Homeless..Rate. ~ Unemployment.Rate + Incarceration..Rateper1000. + \n    Relocated..Rate. + Poverty..Rate. + Drug.Arrests..Rate. + \n    Sub.Abuse.Enrollment..Rate. + Adult.Psych.Beds..Rate. + Forcible.Sex..Rate. + \n    Foster.Care..Rate., data = ., model = \"random\")\n\nBalanced Panel: n = 67, T = 3, N = 201\n\nEffects:\n                    var   std.dev share\nidiosyncratic 4.793e-07 6.923e-04 0.246\nindividual    1.467e-06 1.211e-03 0.754\ntheta: 0.6866\n\nResiduals:\n       Min.     1st Qu.      Median     3rd Qu.        Max. \n-0.00193525 -0.00026946 -0.00010248  0.00017024  0.00612304 \n\nCoefficients:\n                               Estimate  Std. Error z-value Pr(>|z|)   \n(Intercept)                  4.2668e-04  8.3580e-04  0.5105 0.609699   \nUnemployment.Rate            9.5178e-06  4.1582e-05  0.2289 0.818953   \nIncarceration..Rateper1000.  2.1187e-05  5.9881e-05  0.3538 0.723478   \nRelocated..Rate.            -2.3556e-05  4.4214e-05 -0.5328 0.594191   \nPoverty..Rate.               1.1404e-03  3.2398e-03  0.3520 0.724835   \nDrug.Arrests..Rate.          7.2622e-02  2.7264e-02  2.6637 0.007729 **\nSub.Abuse.Enrollment..Rate. -1.4647e-02  5.4401e-02 -0.2693 0.787736   \nAdult.Psych.Beds..Rate.      2.7492e+00  9.9533e-01  2.7621 0.005743 **\nForcible.Sex..Rate.         -3.1645e-01  4.0769e-01 -0.7762 0.437628   \nFoster.Care..Rate.           2.3889e-01  1.7728e-01  1.3475 0.177804   \n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n\nTotal Sum of Squares:    0.00010218\nResidual Sum of Squares: 9.3309e-05\nR-Squared:      0.086778\nAdj. R-Squared: 0.043746\nChisq: 18.1495 on 9 DF, p-value: 0.033478\n```\n:::\n\n```{.r .cell-code}\n#bic3 <- BIC(fit3)\n#print(c('BIC Fit 3:', bic3))\n\nrss3 <- deviance(fit3)\nprint(c('RSS Fit 3', rss3))\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] \"RSS Fit 3\"            \"9.33086018067315e-05\"\n```\n:::\n:::\n\n\n- Evaluating the model with a random effects model allows us to control for unmeasureable differences between counties.\n\n  - Each county receives its own intercept, drawn from a collection of possible intercepts\n\n- Only variables `Drug Arrests (Rate)` and `Adult Psych Beds (Rate)` retained their significance\n  \n  - `Drug Arrests (Rate)` saw a slight decrease in magnitude whereas `Adult Psych Beds (Rate)` increased.\n  \n  - Both are positive, indicating that increases in either of these rates result in an increase in `Homeless Rate`\n \n \n:::\n\n:::{.callout-note collapse=\"true\"}\n\n## `Fit 4`: Random Effects Model - Zugazaga's variables\n\n\n::: {.cell}\n\n```{.r .cell-code}\nfit4 <- plm(formula = Homeless..Rate. ~ \n              Drug.Arrests..Rate. + \n              lag(Sub.Abuse.Enrollment..Rate.,1) +\n              Forcible.Sex..Rate. +\n              Foster.Care..Rate.,   \n            data = florida_panel,\n            model= 'random')\n                   \nsummary(fit4)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\nOneway (individual) effect Random Effect Model \n   (Swamy-Arora's transformation)\n\nCall:\nplm(formula = Homeless..Rate. ~ Drug.Arrests..Rate. + lag(Sub.Abuse.Enrollment..Rate., \n    1) + Forcible.Sex..Rate. + Foster.Care..Rate., data = florida_panel, \n    model = \"random\")\n\nBalanced Panel: n = 67, T = 2, N = 134\n\nEffects:\n                    var   std.dev share\nidiosyncratic 1.848e-07 4.298e-04  0.12\nindividual    1.350e-06 1.162e-03  0.88\ntheta: 0.7469\n\nResiduals:\n       Min.     1st Qu.      Median     3rd Qu.        Max. \n-0.00193151 -0.00022543 -0.00002260  0.00019457  0.00192708 \n\nCoefficients:\n                                       Estimate  Std. Error z-value Pr(>|z|)\n(Intercept)                          0.00089264  0.00037360  2.3893  0.01688\nDrug.Arrests..Rate.                  0.09055443  0.02068601  4.3776  1.2e-05\nlag(Sub.Abuse.Enrollment..Rate., 1) -0.08876300  0.06165290 -1.4397  0.14995\nForcible.Sex..Rate.                 -0.32816661  0.33634980 -0.9757  0.32923\nFoster.Care..Rate.                   0.25476909  0.15898288  1.6025  0.10905\n                                       \n(Intercept)                         *  \nDrug.Arrests..Rate.                 ***\nlag(Sub.Abuse.Enrollment..Rate., 1)    \nForcible.Sex..Rate.                    \nFoster.Care..Rate.                     \n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n\nTotal Sum of Squares:    2.8828e-05\nResidual Sum of Squares: 2.4526e-05\nR-Squared:      0.14921\nAdj. R-Squared: 0.12283\nChisq: 22.6247 on 4 DF, p-value: 0.00015047\n```\n:::\n\n```{.r .cell-code}\n#bic4 <- BIC(fit4)\n#print(c('BIC Fit 4:', bic4))\n\nrss4 <- deviance(fit4)\nprint(c('RSS Fit 4', rss4))\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] \"RSS Fit 4\"            \"2.45264002390625e-05\"\n```\n:::\n:::\n\n\n- Again using a random effects model with only stressors mentioned in Zugazaga's study, we  see `Drug Arrests (Rate)` as a significant predictor of homelessness at the `alpha = 0.05` level.\n\n- `Forcible Sex` may not capture the circumstances suggested in Zugazaga's study, as an arrest rate for forcible sex crimes captures the perpetrators within a county, rather than the victims.\n\n  - Many sex crimes go unreported or unpunished, due to familial or power relationships between the victim and offender\n  \n- `Foster Care` and `Sub Abuse Enrollement (Rate)` have signs and values that correspond well with Zugazaga's results\n  \n  - Lagging `Sub Abuse Enrollement (Rate)` shows an increase of citizens involved in substance abuse programs can lead to a decrease in homelessness in the following year\n  \n \n:::\n\n\n### Model Selection\n\n:::{.callout-note collapse=\"true\"}\n\n## Stargazer Plot\n\n::: {.cell}\n\n```\n## \n## Homelessness in Florida\n## ======================================================================================================\n##                                                            Dependent variable:                        \n##                                     ------------------------------------------------------------------\n##                                                     Homeless Rate                    Homeless..Rate.  \n##                                                          OLS                              panel       \n##                                                                                          linear       \n##                                              (1)                     (2)              (3)       (4)   \n## ------------------------------------------------------------------------------------------------------\n## Year                                                                                                  \n##                                                                                                       \n##                                                                                                       \n## `Unemployment Rate`                        -0.0002                -0.00003                            \n##                                            (0.0004)               (0.0001)                            \n##                                                                                                       \n## `Median Inc`                               0.00000                                                    \n##                                           (0.00000)                                                   \n##                                                                                                       \n## `Incarceration (Rateper1000)`              0.00003                 0.00001                            \n##                                            (0.0001)               (0.00005)                           \n##                                                                                                       \n## `Relocated (Rate)`                         -0.0001                -0.00003                            \n##                                            (0.0001)               (0.00003)                           \n##                                                                                                       \n## `Severe Housing Problems (Rate)`           0.0002**               0.0002***                           \n##                                            (0.0001)               (0.00003)                           \n##                                                                                                       \n## `Poverty (Rate)`                            0.004                  -0.004                             \n##                                            (0.008)                 (0.003)                            \n##                                                                                                       \n## `Drug Arrests (Rate)`                       0.098                 0.107***                            \n##                                            (0.074)                 (0.031)                            \n##                                                                                                       \n## `Sub Abuse Enrollment (Rate)`               0.047                  -0.042                             \n##                                            (0.137)                 (0.059)                            \n##                                                                                                       \n## `Adult Psych Beds (Rate)`                   3.177                  2.129**                            \n##                                            (2.138)                 (0.883)                            \n##                                                                                                       \n## `Forcible Sex (Rate)`                       0.037                   0.331                             \n##                                            (1.093)                 (0.442)                            \n##                                                                                                       \n## `Foster Care (Rate)`                        0.677*                0.492***                            \n##                                            (0.366)                 (0.161)                            \n##                                                                                                       \n## Unemployment.Rate                                                                   0.00001           \n##                                                                                    (0.00004)          \n##                                                                                                       \n## Incarceration..Rateper1000.                                                         0.00002           \n##                                                                                    (0.0001)           \n##                                                                                                       \n## Relocated..Rate.                                                                   -0.00002           \n##                                                                                    (0.00004)          \n##                                                                                                       \n## Poverty..Rate.                                                                       0.001            \n##                                                                                     (0.003)           \n##                                                                                                       \n## Drug.Arrests..Rate.                                                                0.073***  0.091*** \n##                                                                                     (0.027)   (0.021) \n##                                                                                                       \n## Sub.Abuse.Enrollment..Rate.                                                         -0.015            \n##                                                                                     (0.054)           \n##                                                                                                       \n## Adult.Psych.Beds..Rate.                                                            2.749***           \n##                                                                                     (0.995)           \n##                                                                                                       \n## lag(Sub.Abuse.Enrollment..Rate., 1)                                                           -0.089  \n##                                                                                               (0.062) \n##                                                                                                       \n## Forcible.Sex..Rate.                                                                 -0.316    -0.328  \n##                                                                                     (0.408)   (0.336) \n##                                                                                                       \n## Foster.Care..Rate.                                                                   0.239     0.255  \n##                                                                                     (0.177)   (0.159) \n##                                                                                                       \n## Constant                                    -0.005                -0.002**          0.0004    0.001** \n##                                            (0.003)                 (0.001)          (0.001)  (0.0004) \n##                                                                                                       \n## ------------------------------------------------------------------------------------------------------\n## Observations                                  67                     201              201       134   \n## R2                                          0.344                   0.270            0.087     0.149  \n## Adjusted R2                                 0.213                   0.232            0.044     0.123  \n## Residual Std. Error                    0.002 (df = 55)        0.001 (df = 190)                        \n## F Statistic                         2.623*** (df = 11; 55) 7.042*** (df = 10; 190) 18.150**  22.625***\n## ======================================================================================================\n## Note:                                                                      *p<0.1; **p<0.05; ***p<0.01\n```\n:::\n\n:::\n\n- Comparing Residuals Sum Squared and R^2^ `Fit 2`, `Fit 3`, and `Fit 4` I would select **Fit 3** for inference. Although `Fit 4` (with lag) had a lower Residual Sum Squared value, I appreciate the completeness of `Fit 3` and believe the extra variables provide a better picture of how stressors impact the homeless population in Florida.\n\nTransforming the data into panel data produces more accurate coefficients, as rather than 201 individual observations, the model considers 3 years of 67 individual observations. This results in smaller standard error. The R^2 is only considered in passing, as the goal of the study is inference not prediction.\n\n\n**Research Question:**\n\n- All of Zugazaga's effects had plausible signs demonstrating their influence on homelessness in `Fit 3`, but only `Drug Arrests (Rate)` was significant at the `0.05` level as hypothesized. This significance is a comment on the mathematical properties of the model rather than on the real-life effect of the stressors, which all are influential situations that can contribute to homelessness.\n\n- `Drug Arrests (Rate)` positive slope indicated that as the rate of arrests made for drug abuse/possession is in a county increases, so does the homeless rate in the county.\n\n  - This is a comment on the availability of drugs in Florida counties, and how insufficient addiction treatment can contribute to other socioeconomic issues in a community\n  \n  - Criminalization does not solve the problem, it relocates it; it is likely many returning citizens will be caught in a cycle of drug abuse, incarceration, and homelessness.\n\n## Conclusions\n\n:::callout-note\n\n## Was the Research Question Answered?\n\n- As hypothesized, the model proved several stressors to be significant in predicting Homeless Rates across Florida\n\n  - The significance of `Drug Arrests (Rate)` in the 3 models using all of the observations allows us to reject **H~0~:** No stressors are significant in predicting `Homeless (Rate)`.\n\n- Unfortunately, the study is unable to make a substantial comment on *which* stressors most increased vulnerability to Homelessness, evaluating magnitude. To do this, deeper demographic variables would need to be included, as well as improvements in controlling for stressors as a *push* factor in homeless migration.\n\n- Because of limitations in the data, and the broad scope of the research question, the study isn't able to make any new comments on the status of homelessness in Florida, it instead confirms the relevance of the stressors to homeless life a decade later.\n\n:::\n\n::: callout-note\n\n## Prediction vs Inference\n\n- The goal of this brief study was to make inferences regarding stressors' impact on `Homelessness (Rate)` in Florida. \n\n- If prediction was our focus, I would use new 2021 data from FL Charts without the `Homeless (Rate)` column to test the efficacy of `Fit 2` as a predictive tool.\n:::\n\n## Improvements\n\nWhile the data is quick illustration of homelessness in Florida by county, there are improvements that could be made to both data collection and the research question itself to further the study.\n\n:::callout-note\n## Data\n\n-   Unfortunately, [FL Health Charts](https://www.flhealthcharts.gov/charts/default.aspx) did not provide demographic breakdown for the homeless population (Age, Sex, Race), which would drastically widen the scope of the analysis, leading to far more interesting conclusions.\n\n-   There is only have data for a three year period; this is too small of a range to make a strong statement about the impact of homeless policy on Florida counties or how the relevance of certain stressors has *changed* over time. For a more in depth study I would begin with a 10 year range.\n:::\n\n:::callout-note\n## Research Question\n\n-   Demographic breakdown of stressors' impact (Age, Sex, Race)\n\n-   Specifically hone in on certain stressors and their accompanying varibales to view their impact on a population instead of a broad range of stressors\n\n- Included life stressors not associated with homelessness for comparison\n\n-   Extend the question to the entire country, providing a breakdown by state\n\n-   Compare to foreign countries to contrast governments' approaches to homelessness and leading causes of homelessness around the world.\n:::\n\n\n\n## Codebook\n\n- **County** - Florida county(67 total), divided into Northwest Florida, Northeast Florida, Central Florida, and South Florida for visualizations\n\n- **Population** - Yearly population count for county, used as denomintor of all `rate` variables unless specified.\n\n- **Year** - Years 2018, 2019, 2020 included in this study\n\n- **Homeless (Rate)** - Yearly homeless count of a county divided by county population\n\n- **Unemployment Rate** - The ratio of unemployed to the civilian labor force, expressed as a percent\n\n- **Median Inc** - Median household income is the amount which divides the income distribution into two equal groups\n\n- **Incarceration Rate per 1000** - Number of incarcerated people per 1000 (within county)\n\n- **Poverty Rate** - Number of people living below poverty line divided by population\n\n- **Drug Arrests (Rate)** - Arrests attributed to possession or sale of illegal drugs divided by population\n\n- **Relocated (Rate)** - The number of people over age 1 who lived in a different county the previous year\n\n- **Sub Abuse Enrollment (Rate)** - The number of beds indicates the number of adults (age 18 and over) who may receive substance abuse treatment on an in-patient basis\n\n- **Adult Psych Beds (Rate)** - When adults psychiatric distress are uninsured, charged with crimes or meet state criteria for civil commitment because they are violent/dangerous to themselves or others, psychiatric beds are where they are admitted for treatment. The number of beds indicates the number of people who may potentially receive adult (age 18 and over) psychiatric care on an in-patient basis. Divided by population\n\n- **Severe Housing Problems (Rate)** - The percentage of households with at least one or more of the following housing problems: lack of kitchen facilities; lack of plumbing facilities; more than 1.5 persons per room, severe cost burden (monthly housing costs including utlities exceed 50% of monthly income).\n\n- **Forcible Sex (Rate)** - Any sexual act or attempt involving force is classified as a forcible sex offense regardless of the age of the victim or the relationship of the victim to the offender, divided by population\n\n- **Foster Care (Rate)** - Foster care provides a safe and stable environment for children when the cannot be with their parents for some reason, divided by population\n\n\n\n## References\n\nZugazaga, Carole, \"Pathways to homelessness and social support among homeless single men, single women, and women with children\" (2002). Retrospective Theses and Dissertations. 1744. \n\n\n::: \n\n##### Footnotes\n\n~1.) [Homeless Definition](https://www.law.cornell.edu/uscode/text/42/11302)~\n\n~2.) [US Interagency Council on Homelessness](https://www.usich.gov/tools-for-action/2020-point-in-time-count/)~\n\n~3.) Explanation of variables and collection method in Codebook tab~",
    "supporting": [
      "shelton_final3_files"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {
      "include-in-header": [
        "<link href=\"../site_libs/pagedtable-1.1/css/pagedtable.css\" rel=\"stylesheet\" />\r\n<script src=\"../site_libs/pagedtable-1.1/js/pagedtable.js\"></script>\r\n"
      ]
    },
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}