{
  "hash": "70656b416c73fa36406eff1b7f9d66f1",
  "result": {
    "markdown": "---\ntitle: \"DACSS 603 HW 1 Kimble\"\nauthor: \"Karen Kimble\"\ndescription: \"HW 1 for DACSS 603\"\ndate: \"10/03/2022\"\nformat:\n  html:\n    toc: true\n    code-fold: true\n    code-copy: true\n    code-tools: true\neditor: visual\n---\n\n\n# Question 1: Lung Capacity\n\n### Setup\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(dplyr)\n```\n\n::: {.cell-output .cell-output-stderr}\n```\n\nAttaching package: 'dplyr'\n```\n:::\n\n::: {.cell-output .cell-output-stderr}\n```\nThe following objects are masked from 'package:stats':\n\n    filter, lag\n```\n:::\n\n::: {.cell-output .cell-output-stderr}\n```\nThe following objects are masked from 'package:base':\n\n    intersect, setdiff, setequal, union\n```\n:::\n\n```{.r .cell-code}\nlibrary(readxl)\nlibrary(tidyverse)\n```\n\n::: {.cell-output .cell-output-stderr}\n```\n── Attaching packages\n───────────────────────────────────────\ntidyverse 1.3.2 ──\n```\n:::\n\n::: {.cell-output .cell-output-stderr}\n```\n✔ ggplot2 3.3.6     ✔ purrr   0.3.5\n✔ tibble  3.1.8     ✔ stringr 1.4.1\n✔ tidyr   1.2.1     ✔ forcats 0.5.2\n✔ readr   2.1.3     \n── Conflicts ────────────────────────────────────────── tidyverse_conflicts() ──\n✖ dplyr::filter() masks stats::filter()\n✖ dplyr::lag()    masks stats::lag()\n```\n:::\n\n```{.r .cell-code}\nknitr::opts_chunk$set(echo = TRUE)\n\n# Reading in File\nLungCapData <- read_excel(\"_data/LungCapData.xls\")\n```\n:::\n\n\n## Part A: Distribution\n\n\n::: {.cell}\n\n```{.r .cell-code}\nhist(LungCapData$LungCap)\n```\n\n::: {.cell-output-display}\n![](DACSS-603-HW-1_files/figure-html/unnamed-chunk-2-1.png){width=672}\n:::\n:::\n\n\nThe histogram above shows that the Lung Cap data is roughly normally distributed because a majority of the observations are centered around the mean. There are fewer observations at the tail ends of the histogram.\n\n## Part B: Probability Distribution of LungCap (Males vs. Females)\n\n\n::: {.cell}\n\n```{.r .cell-code}\nboxplot(LungCap ~ Gender, data = LungCapData, main = \"Lung Capacity by Gender\",\n        xlab = \"Gender\", ylab = \"Lung Capacity\")\n```\n\n::: {.cell-output-display}\n![](DACSS-603-HW-1_files/figure-html/unnamed-chunk-3-1.png){width=672}\n:::\n:::\n\n\nFrom the box-plots above, it appears that males in this study had slightly higher lung capacities than females, with the median for males at 9 and the median for females at 8. However, both genders had large ranges, but these ranges reflected the overall pattern of males having slightly higher lung capacities.\n\n## Part C: Smokers vs. Non-Smokers\n\n\n::: {.cell}\n\n```{.r .cell-code}\nsmokers <- filter(LungCapData, Smoke == \"yes\")\nmean(smokers$LungCap)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 8.645455\n```\n:::\n\n```{.r .cell-code}\nnonsmokers <- filter(LungCapData, Smoke == \"no\")\nmean(nonsmokers$LungCap)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 7.770188\n```\n:::\n:::\n\n\nThe mean lung capacity for smokers (8.65) is higher than the mean lung capacity for non-smokers (7.77). Based on what we now know about how smoking affects the lungs, these results don't seem to make sense. However, there is the possibility that smokers may be more used to deep inhales/exhales and therefore could have better lung capacity until the substance has more of an effect on their lungs. There may also be external factors that led to these results that aren't clear from the data right now.\n\n## Part D: Lung Capacity by Smoker/Non-Smoker and Age\n\n\n::: {.cell}\n\n```{.r .cell-code}\nLungCapData <- within(LungCapData, {\n  Age.group <- NA\n  Age.group[Age <= 13] <- \"13 and Under\"\n  Age.group[Age >= 14 & Age <= 15] <- \"14-15\"\n  Age.group[Age >= 16 & Age <= 17] <- \"16-17\"\n  Age.group[Age >= 18] <- \"18 and Over\"\n} )\n```\n:::\n\n\n### Smokers\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Boxplots\n\nsmoking_age <- filter(LungCapData, Smoke == \"yes\")\n\nboxplot(LungCap ~ Age.group, data = smoking_age,\n        main = \"Lung Capacity of Smokers by Age Group\",\n        xlab = \"Age Group\", ylab = \"Lung Capacity\")\n```\n\n::: {.cell-output-display}\n![](DACSS-603-HW-1_files/figure-html/unnamed-chunk-6-1.png){width=672}\n:::\n:::\n\n\nFrom the boxplot above, we can see that smokers' lung capacities reach about a maximum of 12 as age increases, but there is not very much improvement in the maximums. The medians move a bit more as age increases, but still not very dramatically after ages 14 and 15. Smokers that are 18 and over have higher lung capacities overall, but this may just be because of natural aging processes and development.\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Means\n\nsmoking_age %>%\n  group_by(Age.group) %>%\n  summarise_at(vars(LungCap), list(name = mean))\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n# A tibble: 4 × 2\n  Age.group     name\n  <chr>        <dbl>\n1 13 and Under  7.20\n2 14-15         8.39\n3 16-17         9.38\n4 18 and Over  10.5 \n```\n:::\n:::\n\n\nWe see the same trend in means as in the medians: mean lung capacity to increases as the age increases.\n\n### Non-Smokers\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Boxplot\n\nnonsmoking_age <- filter(LungCapData, Smoke == \"no\")\n\nboxplot(LungCap ~ Age.group, data = nonsmoking_age,\n        main = \"Lung Capacity of Non-Smokers by Age Group\",\n        xlab = \"Age Group\", ylab = \"Lung Capacity\")\n```\n\n::: {.cell-output-display}\n![](DACSS-603-HW-1_files/figure-html/unnamed-chunk-8-1.png){width=672}\n:::\n:::\n\n\nIn non-smokers, we see the same trend of increasing lung capacities as age increases, but the median lung capacities in the two older age groups in the non-smoking group are higher than those in the smoking group. There are also more outliers for non-smokers, especially in the 14-15 category.\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Means\n\nnonsmoking_age %>%\n  group_by(Age.group) %>%\n  summarise_at(vars(LungCap), list(name = mean))\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n# A tibble: 4 × 2\n  Age.group     name\n  <chr>        <dbl>\n1 13 and Under  6.36\n2 14-15         9.14\n3 16-17        10.5 \n4 18 and Over  11.1 \n```\n:::\n:::\n\n\nThe means of the non-smoking group by age follow the same trend as the medians, as well as in the smoking group. However, the mean lung capacity for the oldest two age groups in the non-smoking category are higher than the means for those groups in the smoking category.\n\n## Part E: Lung Capacities for Smokers and Non-Smokers within Age Group\n\n### 13 and Under\n\n\n::: {.cell}\n\n```{.r .cell-code}\nLungCapData %>%\n  filter(Age.group == \"13 and Under\") %>%\n  group_by(Smoke) %>%\n  summarise_at(vars(LungCap), list(name = mean))\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n# A tibble: 2 × 2\n  Smoke  name\n  <chr> <dbl>\n1 no     6.36\n2 yes    7.20\n```\n:::\n:::\n\n\nThe mean lung capacity for smokers is higher than the mean lung capacity for non-smokers in the age group 13 and under, which mirrors the general means we found earlier. However, from the boxplot of Smokers by Age Group, we can see that there is a very low outlier in this age group, which might be affecting the mean for this group as well as overall smokers.\n\n### 14-15\n\n\n::: {.cell}\n\n```{.r .cell-code}\nLungCapData %>%\n  filter(Age.group == \"14-15\") %>%\n  group_by(Smoke) %>%\n  summarise_at(vars(LungCap), list(name = mean))\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n# A tibble: 2 × 2\n  Smoke  name\n  <chr> <dbl>\n1 no     9.14\n2 yes    8.39\n```\n:::\n:::\n\n\nIn this age group, the mean lung capacity for non-smokers is higher than the mean lung capacity for smokers--unlike the younger group.\n\n### 16-17\n\n\n::: {.cell}\n\n```{.r .cell-code}\nLungCapData %>%\n  filter(Age.group == \"16-17\") %>%\n  group_by(Smoke) %>%\n  summarise_at(vars(LungCap), list(name = mean))\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n# A tibble: 2 × 2\n  Smoke  name\n  <chr> <dbl>\n1 no    10.5 \n2 yes    9.38\n```\n:::\n:::\n\n\nThe same trend continues in this age group, with the mean lung capacity in non-smokers ages 16 and 17 higher than the mean lung capacity of smokers in this group. Yet as the ages increase, the mean lung capacities for non-smokers and smokers increase about the same amount (by 1).\n\n### 18 and Over\n\n\n::: {.cell}\n\n```{.r .cell-code}\nLungCapData %>%\n  filter(Age.group == \"18 and Over\") %>%\n  group_by(Smoke) %>%\n  summarise_at(vars(LungCap), list(name = mean))\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n# A tibble: 2 × 2\n  Smoke  name\n  <chr> <dbl>\n1 no     11.1\n2 yes    10.5\n```\n:::\n:::\n\n\nIn this oldest age group, the same trend continues: the mean lung capacity for non-smokers is higher than that of smokers. This pattern in the groups 18+, 16-17, and 14-15 are not found in the overall means for smokers and nonsmokers, suggesting that the outlier in the 13 and Under group might have brought down the overall mean for smokers.\n\n## Part F: Correlation & Covariance\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Correlation\n\ncor(LungCapData$Age, LungCapData$LungCap, use = \"everything\")\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 0.8196749\n```\n:::\n:::\n\n\nThe correlation between lung capacity and age is positive and strong. As age increases, lung capacity also increases. The value of 0.8 is close to 1, meaning there is a somewhat strong relationship between the two variables.\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Covariance\n\ncov(LungCapData$Age, LungCapData$LungCap, use = \"everything\")\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 8.738289\n```\n:::\n:::\n\n\nThe covariance is positive, meaning that there is a positive relationship between the varaibles, which is also clear from the correlation (since the correlation coefficient is a function of the covariance). Age and lung capacity have an overall positive relationship: as age increases, so does lung capacity.\n\n# Question 2: Prisoner Convictions\n\n## Part A\n\n\n::: {.cell}\n\n```{.r .cell-code}\n160/810\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 0.1975309\n```\n:::\n:::\n\n\n## Part B\n\n\n::: {.cell}\n\n```{.r .cell-code}\n(434 + 128)/810\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 0.6938272\n```\n:::\n:::\n\n\n## Part C\n\n\n::: {.cell}\n\n```{.r .cell-code}\n(160 + 434 + 128)/810\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 0.891358\n```\n:::\n:::\n\n\n## Part D\n\n\n::: {.cell}\n\n```{.r .cell-code}\n(64 + 24)/810\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 0.108642\n```\n:::\n:::\n\n\n## Part E\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Creating vector\nconvict <- c(rep(0, 128), rep(1, 434), rep(2, 160), rep(3, 64), rep(4, 24))\n\nweighted.mean(convict)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 1.28642\n```\n:::\n:::\n\n\nThe expected value for the number of prior convictions is 1.27--but since prior convictions have to be a whole number, that would be rounded to 1.\n\n## Part F\n\n\n::: {.cell}\n\n```{.r .cell-code}\nvar(convict)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 0.8572937\n```\n:::\n\n```{.r .cell-code}\nsd(convict)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 0.9259016\n```\n:::\n:::\n",
    "supporting": [
      "DACSS-603-HW-1_files"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}