{
  "hash": "b2985e8dd7f6b563855d568021815d99",
  "result": {
    "markdown": "---\ntitle: \"Homework 2\"\nauthor: \"Shoshana Buck\"\ndesription: \"Second homework on confidence intervals\"\ndate: \"10/17/2022\"\nformat:\n  html:\n    toc: true\n    code-fold: true\n    code-copy: true\n    code-tools: true\ncategories:\n  - hw2\n  - Shoshana Buck\n  - dataset\n---\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(tidyverse)\n\nknitr::opts_chunk$set(echo = TRUE)\n```\n:::\n\n\n# Question 1\n\nConstruct the 90% confidence interval to estimate the actual mean wait time for each of the two procedures. Is the confidence interval narrower for angiography or bypass surgery?\n\n## Tail area and standard error for Bypass\n\n\n::: {.cell}\n\n```{.r .cell-code}\ntail_area<- (1-.90)/2\ntail_area\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 0.05\n```\n:::\n\n```{.r .cell-code}\nstandard_error<- 10/sqrt(539)\nstandard_error\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 0.4307305\n```\n:::\n:::\n\n\n## t-value for Bypass\n\n\n::: {.cell}\n\n```{.r .cell-code}\nt_score<- qt(p= 1-tail_area, df= 538)\nt_score\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 1.647691\n```\n:::\n:::\n\n\n## Confidence interval and margin of error for Bypass\n\n\n::: {.cell}\n\n```{.r .cell-code}\nCI<- c(19 - t_score * standard_error, 19 + t_score * standard_error)\nCI\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 18.29029 19.70971\n```\n:::\n\n```{.r .cell-code}\nMOE<- t_score *standard_error\nMOE *1.41\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 1.000692\n```\n:::\n:::\n\n\n## Standard error of angiography\n\n\n::: {.cell}\n\n```{.r .cell-code}\nstandard_error2<- 9/sqrt(847)\nstandard_error2\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 0.3092437\n```\n:::\n:::\n\n\n## t-score for angiography\n\n\n::: {.cell}\n\n```{.r .cell-code}\nt_score2<- qt(p= 1-.05, df= 846)\nt_score2\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 1.646657\n```\n:::\n:::\n\n\n## Confidence interval and margin of error for angiography\n\n\n::: {.cell}\n\n```{.r .cell-code}\nCI<- c(18 - t_score2 * standard_error2, 18 + t_score2 * standard_error2)\nCI\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 17.49078 18.50922\n```\n:::\n\n```{.r .cell-code}\nMOE2<- t_score2 *standard_error2\nMOE2 *1.01\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 0.5143103\n```\n:::\n:::\n\n\nThe Bypass points are \\[18.29029 & 19.70971\\] days and has a margin of error of +/- 0.7. Whereas the angiography is \\[17.49 & 18.50\\] days with a margin of error of +/- 0.5. Angigography is more narrower because it has a larger sample size and the range between the high and low end of the confidence interval is smaller.\n\n# Question 2\n\n## Point estimate P\n\n\n::: {.cell}\n\n```{.r .cell-code}\ns_size<- 1031\nb<- 567\n\npoint_estimate<- b/s_size\npoint_estimate\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 0.5499515\n```\n:::\n:::\n\n\n## 95% confidence interval for P\n\n\n::: {.cell}\n\n```{.r .cell-code}\nprop.test(b,s_size)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n\n\t1-sample proportions test with continuity correction\n\ndata:  b out of s_size, null probability 0.5\nX-squared = 10.091, df = 1, p-value = 0.00149\nalternative hypothesis: true p is not equal to 0.5\n95 percent confidence interval:\n 0.5189682 0.5805580\nsample estimates:\n        p \n0.5499515 \n```\n:::\n:::\n\n\nBased off the point estimate, 54% of the adult Americans that were surveyed by the National Center for Public Policy believe that college education is essential for success. 95% confidence interval of adult Americans who believe that college education is essential for success is \\[0.5189682 0.5805580\\] which contains the true population mean.\n\n# Question 3\n\nAssuming the significance level to be 5%, what should be the size sample?\n\n## Standard Deviation\n\n\n::: {.cell}\n\n```{.r .cell-code}\nsd<- (200-30)/4\nsd\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 42.5\n```\n:::\n:::\n\n\n## Solving for n\n\n\n::: {.cell}\n\n```{.r .cell-code}\n#steps for the equation\n#1. 5 = 1.96 * (42.5/sqrt(n))\n\n#2. 5 = 8.3/sqrt(n)\n\n#3. 5*sqrt(n)= 83.3\n\n#4. sqrt(n) = 83.3/5\n\n#5. n= (83.3/5)^2\n\n#6. n= 278.89\n```\n:::\n\n\nThe standard deviation from the data is 42.5. Since we have solved for the standard deviation we can plug it into the CI equation and solve for n.\n\n## Question 4\n\n### A\n\nTest whether the mean income of female employees differs from \\$500 per week. Include assumptions, hypotheses, test statistic, and P-value. Interpret the result. \\## Assumptions\n\nWe are assuming there is normal distribution, the null hypothesis is: μ= 500 and the alternative hypothesis is 500\\> μ \\<500.\n\n## Standard error\n\n\n::: {.cell}\n\n```{.r .cell-code}\ns_sizef<- 9\nsd<-90\ns_meanf<- 410\nnull_hypo_mean<- 500\n\nstandard_errorf<- sd/sqrt(s_sizef)\nstandard_errorf\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 30\n```\n:::\n:::\n\n\n## t-score\n\n\n::: {.cell}\n\n```{.r .cell-code}\nt_stat<- (s_meanf-null_hypo_mean)/standard_errorf\nt_stat\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] -3\n```\n:::\n:::\n\n\nI took the sample mean of 410 subtracted that from the mu = 500 and then divided it by the standard error = 30.\n\n## p-value\n\n\n::: {.cell}\n\n```{.r .cell-code}\np_value<- (pt(t_stat, df=8)) *2\np_value\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 0.01707168\n```\n:::\n:::\n\n\nThe p-value than the 5% significance level so we can reject the null hypothesis in favor of the alternative hypothesis.\n\n## B +C\n\nReport the P-value for Ha : μ \\< 500. Interpret. Report and interpret the P-value for H a: μ \\> 500.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nupper_p_value<- (pt(t_stat, df=8, lower.tail = FALSE))\nupper_p_value\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 0.9914642\n```\n:::\n\n```{.r .cell-code}\nlower_p_value<- (pt(t_stat, df=8, lower.tail = TRUE))\nlower_p_value\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 0.008535841\n```\n:::\n:::\n\n\nThe upper-tailed p-value is 0.99 and the lower-tailed p-value is 0.008. If you add the two tails together they will equal 1.\n\n## Question 5\n\nShow that t = 1.95 and P-value = 0.051 for Jones. Show that t = 1.97 and P-value = 0.049 for Smith.\n\n\n::: {.cell}\n\n```{.r .cell-code}\njones_sample_mean<- 519.5\nsmith_sample_mean<-519.7\nnull_hyp<- 500\njones_se<- 10\nsmith_se<- 10\n```\n:::\n\n\n### A: Jones t-score and p-value\n\n\n::: {.cell}\n\n```{.r .cell-code}\njones_t_stat<- (jones_sample_mean-null_hyp)/jones_se\njones_t_stat\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 1.95\n```\n:::\n\n```{.r .cell-code}\njones_p_value<- pt(jones_t_stat, df=999, lower.tail = FALSE) *2\njones_p_value\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 0.05145555\n```\n:::\n:::\n\n\n### A: Smith t-score and p-value\n\n\n::: {.cell}\n\n```{.r .cell-code}\nsmith_t_stat<-(smith_sample_mean-null_hyp)/smith_se\nsmith_t_stat\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 1.97\n```\n:::\n\n```{.r .cell-code}\nsmith_p_value<- pt(smith_t_stat, df=999, lower.tail = FALSE)*2\nsmith_p_value\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 0.04911426\n```\n:::\n:::\n\n\n### B\n\nUsing α = 0.05, for each study indicate whether the result is \"statistically significant.\"\n\nThe results are \"statistically significant when the p-value is smaller than the 0.05. Jones p-value is 0.051 which is greater than the 0.05 significance level which means it is not statistically significant and we cannot reject the null hypothesis. Smith's p-value is 0.49 which is smaller than the significance level which means it is statistically significant and that we can reject the null hypothesis in favor of the alternative hypothesis.\n\n### C\n\n\"P ≤ 0.05\" versus \"P \\> 0.05,\" or as \"reject H0\" versus \"Do not reject H0 ,\" is a misleading statement without providing the p-values because it makes it seem that there is a drastic difference between Jones and Smith that caused one hypothesis to be statistically significant and the other one not to be. However, when looking at the actual p-value it can be noted that there is a very small difference between the values.\n\n## Question 6\n\n\n::: {.cell}\n\n```{.r .cell-code}\ngas_taxes <- c(51.27, 47.43, 38.89, 41.95, 28.61, 41.29, 52.19, 49.48, 35.02, 48.13, 39.28, 54.41, 41.66, 30.28, 18.49, 38.72, 33.41, 45.02)\n```\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\nt.test(gas_taxes, mu=45, alternative = 'less')\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n\n\tOne Sample t-test\n\ndata:  gas_taxes\nt = -1.8857, df = 17, p-value = 0.03827\nalternative hypothesis: true mean is less than 45\n95 percent confidence interval:\n     -Inf 44.67946\nsample estimates:\nmean of x \n 40.86278 \n```\n:::\n:::\n\n\nIs there enough evidence to conclude at a 95% confidence level that the average tax per gallon of gas in the US in 2005 was less than 45 cents?\n\nAt the 95% confidence level the p-value is 0.03 which is less than the 5% significance level. This proves that we can reject the null hypothesis and that the average tax per gallon of gas in the US in 2005 was less than 45 cents.\n",
    "supporting": [],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}