{
  "hash": "a0e2765a1bab7ba58077f1f434e83481",
  "result": {
    "markdown": "---\ntitle: \"Homework 2\"\nauthor: \"Lindsay Jones\"\ndescription: The second homework\ndate: \"10/17/2022\"\nformat:\n  html:\n    toc: true\n    code-fold: true\n    code-copy: true\n    code-tools: true\ncategories:\n  - hw2\n---\n\n\n# Homework 2\n\n## Setup\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(readr)\nlibrary(dplyr)\n```\n\n::: {.cell-output .cell-output-stderr}\n```\n\nAttaching package: 'dplyr'\n```\n:::\n\n::: {.cell-output .cell-output-stderr}\n```\nThe following objects are masked from 'package:stats':\n\n    filter, lag\n```\n:::\n\n::: {.cell-output .cell-output-stderr}\n```\nThe following objects are masked from 'package:base':\n\n    intersect, setdiff, setequal, union\n```\n:::\n:::\n\n\n## Question 1\n\nThe time between the date a patient was recommended for heart surgery and the surgery date for cardiac patients in Ontario was collected by the Cardiac Care Network (\"Wait Times Data Guide,\" Ministry of Health and Long-Term Care, Ontario, Canada, 2006). The sample mean and sample standard deviation for wait times (in days) of patients for two cardiac procedures are given in the accompanying table. Assume that the sample is representative of the Ontario population. Construct the 90% confidence interval to estimate the actual mean wait time for each of the two procedures. Is the confidence interval narrower for angiography or bypass surgery?\n\nAngiography\n\n\n::: {.cell}\n\n```{.r .cell-code}\na_mean <- 18\na_sd <- 9\na_ss <- 847\n\na_se <- a_sd/sqrt(a_ss)\n\na_cl <- 0.90  \na_tail <- (1-a_cl)/2\na_tscore <- qt(p = 1-a_tail, df = a_ss-1)\n\na_ci <- c(a_mean - a_tscore * a_se,\n        a_mean + a_tscore * a_se)\nprint(a_ci)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 17.49078 18.50922\n```\n:::\n:::\n\n\nBypass\n\n\n::: {.cell}\n\n```{.r .cell-code}\nb_mean <- 19\nb_sd <- 10\nb_ss <- 539\n\nb_se <- b_sd/sqrt(b_ss)\n\nb_cl <- 0.90  \nb_tail <- (1-b_cl)/2\nb_tscore <- qt(p = 1-b_tail, df = b_ss-1)\n\nb_ci <- c(b_mean - b_tscore * b_se,\n        b_mean + b_tscore * b_se)\nprint(b_ci)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 18.29029 19.70971\n```\n:::\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\n#assessing which confidence interval is larger\n18.50922 - 17.49078\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 1.01844\n```\n:::\n\n```{.r .cell-code}\n19.70971 - 18.29029\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 1.41942\n```\n:::\n:::\n\n\nThe confidence interval is more narrow for angiographies.\n\n## Question 2\n\nA survey of 1031 adult Americans was carried out by the National Center for Public Policy. Assume that the sample is representative of adult Americans. Among those surveyed, 567 believed that college education is essential for success. Find the point estimate, p, of the proportion of all adult Americans who believe that a college education is essential for success. Construct and interpret a 95% confidence interval for p.\n\n\n::: {.cell}\n\n```{.r .cell-code}\n#n = American adults (population), x = sample (surveyed)\nn = 1031\nx = 567\n\n#use prop.test to find p (confidence interval is 95% by default)\nprop.test(x, n)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n\n\t1-sample proportions test with continuity correction\n\ndata:  x out of n, null probability 0.5\nX-squared = 10.091, df = 1, p-value = 0.00149\nalternative hypothesis: true p is not equal to 0.5\n95 percent confidence interval:\n 0.5189682 0.5805580\nsample estimates:\n        p \n0.5499515 \n```\n:::\n:::\n\n\np (the proportion of adult Americans who believe that college education is essential for success) is 0.5499515. The 95% confidence interval is \\[0.5189682, 0.5805580\\], meaning we can be 95% certain this interval captured the true proportion.\n\n## Question 3\n\nSuppose that the financial aid office of UMass Amherst seeks to estimate the mean cost of textbooks per semester for students. The estimate will be useful if it is within \\$5 of the true population mean (i.e. they want the confidence interval to have a length of \\$10 or less). The financial aid office is pretty sure that the amount spent on books varies widely, with most values between \\$30 and \\$200. They think that the population standard deviation is about a quarter of this range (in other words, you can assume they know the population standard deviation). Assuming the significance level to be 5%, what should be the size of the sample?\n\n\n::: {.cell}\n\n```{.r .cell-code}\n#calculating standard deviation using the given\n(200-30)/4\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 42.5\n```\n:::\n:::\n\nSince our significance level is 5%, our confidence level is 95%. A 95% confidence level corresponds to a z-score of 1.96. From here we can calculate the ideal sample size.\n\n\n::: {.cell}\n\n```{.r .cell-code}\n#solve 5 = 1.96((200-30)*.25)/sqrt(x)\n\n(((170*.25)/5)*1.96)^2\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 277.5556\n```\n:::\n:::\n\nUMass needs a sample of approximately 278 students to estimate the mean cost of textbooks. \n\n## Question 4\n\nAccording to a union agreement, the mean income for all senior-level workers in a large service company equals \\$500 per week. A representative of a women's group decides to analyze whether the mean income μ for female employees matches this norm. For a random sample of nine female employees, ȳ = \\$410 and s = 90.\n\n### A) Test whether the mean income of female employees differs from \\$500 per week. Include assumptions, hypotheses, test statistic, and P-value. Interpret the result.\n\nAssumptions: normal distribution, significance level .05 \nH₀: μ=500\nH₁: μ≠500\nTest statistic: 410\n\n\n::: {.cell}\n\n```{.r .cell-code}\n#given\np_mean = 500\ns_mean = 410\ns_size = 9\ns = 90\n\n#find standard error\nsem = s/sqrt(s_size)\n\n#find t-score\nt_score <- (s_mean - p_mean)/sem\nt_score\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] -3\n```\n:::\n\n```{.r .cell-code}\n#find p-value\npvalue = 2 * pt(t_score, df=(s_size - 1))\npvalue\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 0.01707168\n```\n:::\n:::\n\n\nBecause the p-value is less than the significance level (.05), we reject the null hypothesis that μ=500.\n\n### B) Report the P-value for H₁ : μ \\< 500. Interpret.\n\n\n::: {.cell}\n\n```{.r .cell-code}\n#calculate the p-value for lower tail only\nltail <- pt(t_score, df=(s_size - 1), lower.tail = TRUE)\nltail\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 0.008535841\n```\n:::\n:::\n\n\nBecause the p-value of the lower tail is less than the significance level (.05), we reject H₀, meaning we have evidence that μ \\< 50.\n\n### C) Report and interpret the P-value for H₁: μ \\> 500.\n\n\n::: {.cell}\n\n```{.r .cell-code}\n#calculate the p-value for upper tail only\nutail <- pt(t_score, df=(s_size - 1), lower.tail = FALSE)\nutail\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 0.9914642\n```\n:::\n:::\n\n\nBecause the p-value of the lower tail is less than the significance level (.05), we reject H₀, meaning we do not have evidence that μ \\> 500.\n\nChecking my work:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nltail + utail\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 1\n```\n:::\n:::\n\n\n## Question 5\n\nJones and Smith separately conduct studies to test H₀: μ = 500 against H₁ : μ ≠ 500, each with n = 1000. Jones gets ȳ = 519.5, with se = 10.0. Smith gets ȳ = 519.7, with se = 10.0.\n\n### A) Show that t = 1.95 and P-value = 0.051 for Jones. Show that t = 1.97 and P-value = 0.049 for Smith.\n\nJones\n\n::: {.cell}\n\n```{.r .cell-code}\n#t-score\nJt_score = (519.5 - 500)/10\nJt_score\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 1.95\n```\n:::\n\n```{.r .cell-code}\n#p-value\nJp = 2 * pt(Jt_score, df=(1000 - 1), lower.tail = FALSE)\nJp\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 0.05145555\n```\n:::\n:::\n\nSmith\n\n::: {.cell}\n\n```{.r .cell-code}\n#t-score\nSt_score = (519.7 - 500)/10\nSt_score\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 1.97\n```\n:::\n\n```{.r .cell-code}\n#p-value\nSp = 2 * pt(St_score, df=(1000 - 1), lower.tail = FALSE)\nSp\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 0.04911426\n```\n:::\n:::\n\n### B) Using α = 0.05, for each study indicate whether the result is “statistically significant.”\n\nAt α = 0.05, Jones' result is statistically significant (because the p-value is greater than α) but Smith's result is not. \n\n### C) Using this example, explain the misleading aspects of reporting the result of a test as “P ≤ 0.05” versus “P > 0.05,” or as “reject H0” versus “Do not reject H0 ,” without reporting the actual P-value.\n\nJones' p-value is only just barely greater than 0.05, and Smith's p-value is only just barely less than 0.05. It is important to report the p-value because studies with very similar samples could report that the null should or should not be rejected, leading to very different conclusions based on data that is extremely similar. \n\n## Question 6\n\nAre the taxes on gasoline very high in the United States? According to the American Petroleum Institute, the per gallon federal tax that was levied on gasoline was 18.4 cents per gallon. However, state and local taxes vary over the same period. The sample data of gasoline taxes for 18 large cities is given below in the variable called gas_taxes.\n\n\n::: {.cell}\n\n```{.r .cell-code}\ngas_taxes <- c(51.27, 47.43, 38.89, 41.95, 28.61, 41.29, 52.19, 49.48, 35.02, 48.13, 39.28, 54.41, 41.66, 30.28, 18.49, 38.72, 33.41, 45.02)\n```\n:::\n\n\nIs there enough evidence to conclude at a 95% confidence level that the average tax per gallon of gas in the US in 2005 was less than 45 cents? Explain.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nt.test(gas_taxes, mu = 45.0, alternative = \"less\")\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n\n\tOne Sample t-test\n\ndata:  gas_taxes\nt = -1.8857, df = 17, p-value = 0.03827\nalternative hypothesis: true mean is less than 45\n95 percent confidence interval:\n     -Inf 44.67946\nsample estimates:\nmean of x \n 40.86278 \n```\n:::\n:::\n\nSince the p-value is 0.03827, we can reject the null hypothesis that the average tax per gallon was greater than or equal to 45 cents. However, we do not know from what year(s) the data was collected. Therefore we can conclude with certainty that the average tax per gallon in 2005 was less than 45 cents.\n",
    "supporting": [],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}