{
  "hash": "b9820c8b59972bc1ce565f7c298e6189",
  "result": {
    "markdown": "---\ntitle: \"ShoshanaBuck-HW1\"\nauthor: \"Shoshana Buck\"\ndescription: \"First homeowrk on descriptive statistics and probability\"\ndate: \"10/03/22\"\nformat:\n  html:\n    toc: true\n    code-fold: true\n    code-copy: true\n    code-tools: true\ncategories:\n  - hw1\n  - desriptive statistics \n  - probability\n---\n\n::: {.cell}\n\n```{.r .cell-code}\n#install libraries\nlibrary(tidyverse)\n```\n\n::: {.cell-output .cell-output-stderr}\n```\n── Attaching packages ─────────────────────────────────────── tidyverse 1.3.2 ──\n✔ ggplot2 3.3.6      ✔ purrr   0.3.5 \n✔ tibble  3.1.8      ✔ dplyr   1.0.10\n✔ tidyr   1.2.1      ✔ stringr 1.4.1 \n✔ readr   2.1.3      ✔ forcats 0.5.2 \n── Conflicts ────────────────────────────────────────── tidyverse_conflicts() ──\n✖ dplyr::filter() masks stats::filter()\n✖ dplyr::lag()    masks stats::lag()\n```\n:::\n\n```{.r .cell-code}\nlibrary(readxl)\nlibrary(ggplot2)\n```\n:::\n\n\n# Question 1\n\nUse the LungCapData to answer the following questions.\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# read in data\nlung_cap<- read_xls(\"_data/LungCapData.xls\")\nlung_cap\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n# A tibble: 725 × 6\n   LungCap   Age Height Smoke Gender Caesarean\n     <dbl> <dbl>  <dbl> <chr> <chr>  <chr>    \n 1    6.48     6   62.1 no    male   no       \n 2   10.1     18   74.7 yes   female no       \n 3    9.55    16   69.7 no    female yes      \n 4   11.1     14   71   no    male   no       \n 5    4.8      5   56.9 no    male   no       \n 6    6.22    11   58.7 no    female no       \n 7    4.95     8   63.3 no    male   yes      \n 8    7.32    11   70.4 no    male   no       \n 9    8.88    15   70.5 no    male   no       \n10    6.8     11   59.2 no    male   no       \n# … with 715 more rows\n```\n:::\n:::\n\n\n### a. What does the distribution of LungCap look like?\n\n\n::: {.cell}\n\n```{.r .cell-code}\n#plot histogram\nhist(lung_cap$LungCap)\n```\n\n::: {.cell-output-display}\n![](ShoshanaBuck--HW1_files/figure-html/unnamed-chunk-3-1.png){width=672}\n:::\n:::\n\n\nThe histogram shows that the distribution is pretty close to a normal distribution, with an almost a bell shaped curve. Meaning that the data near the mean are more of a frequent occurrence which is true because there are fewer observations near the margins.\n\n### b. compare the probability distribution of the LungCap with respect to Males and Females?\n\n\n::: {.cell}\n\n```{.r .cell-code}\n#Box plot\nggplot(lung_cap, aes (Gender,LungCap)) + geom_boxplot()\n```\n\n::: {.cell-output-display}\n![](ShoshanaBuck--HW1_files/figure-html/unnamed-chunk-4-1.png){width=672}\n:::\n:::\n\n\nThe box plot shows that male's have a slightly higher lung capacity than females. Female's have more values in the first quartile range and a lower minimum value than male's. On the other hand male's have a higher max value and more values in the 3rd quartile range.\n\n### c. Compare the mean lung capacities for smokers and non-smokers. Does it make sense?\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlung_cap %>% \n  group_by(Smoke) %>% \n  summarise(avg_lung_cap = mean(LungCap))\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n# A tibble: 2 × 2\n  Smoke avg_lung_cap\n  <chr>        <dbl>\n1 no            7.77\n2 yes           8.65\n```\n:::\n:::\n\n\nThis does not make sense. Smokers have a higher sample mean than non-smokers which intuitively does not make sense because we would assume non-smokers would have a higher lung capacity.\n\n### d. Examine the relationship between Smoking and Lung Capacity within age groups: \"less than or equal to 13\", \"14 to 15\", \"16 to 17\", and \"greater than or equal to 18\".\n\n\n::: {.cell}\n\n```{.r .cell-code}\n#categorical variable of age_groups \ndf<- lung_cap %>% \ngroup_by(Smoke,LungCap) %>% \n  summarise(age_group = case_when(Age<=13 ~ \"13 & under\",Age ==14 | Age == 15 ~ \"14 to 15\",Age== 16 | Age == 17 ~ \"16 to 17\", Age>=18 ~ \"18 & older\")) \n```\n\n::: {.cell-output .cell-output-stderr}\n```\n`summarise()` has grouped output by 'Smoke', 'LungCap'. You can override using\nthe `.groups` argument.\n```\n:::\n\n```{.r .cell-code}\n#mean of lung capacity with new variable\ndf %>% \n  group_by(Smoke, age_group) %>% \n  summarise(avg_lung_cap = mean(LungCap)) %>% \n  arrange(desc(avg_lung_cap))\n```\n\n::: {.cell-output .cell-output-stderr}\n```\n`summarise()` has grouped output by 'Smoke'. You can override using the\n`.groups` argument.\n```\n:::\n\n::: {.cell-output .cell-output-stdout}\n```\n# A tibble: 8 × 3\n# Groups:   Smoke [2]\n  Smoke age_group  avg_lung_cap\n  <chr> <chr>             <dbl>\n1 no    18 & older        11.1 \n2 yes   18 & older        10.5 \n3 no    16 to 17          10.5 \n4 yes   16 to 17           9.38\n5 no    14 to 15           9.14\n6 yes   14 to 15           8.39\n7 yes   13 & under         7.20\n8 no    13 & under         6.36\n```\n:::\n\n```{.r .cell-code}\n#histogram\nggplot(df, aes(x = LungCap)) + facet_grid(Smoke ~age_group) +geom_histogram()\n```\n\n::: {.cell-output .cell-output-stderr}\n```\n`stat_bin()` using `bins = 30`. Pick better value with `binwidth`.\n```\n:::\n\n::: {.cell-output-display}\n![](ShoshanaBuck--HW1_files/figure-html/unnamed-chunk-6-1.png){width=672}\n:::\n:::\n\n\nUsing the package ***ggplot*** I used the function *facet_grids* to show a good visualization of the lung capacity between non-smokers and smokers within each age group. Looking at the histograms all *age_groups* that are non-smokers have a higher sample mean proving that non-smokers have\n\n### e. Compare the lung capacities for smokers and non-smokers within each age group. Is your answer different from the one in part d. What could possibly be going on here?\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Mean of non-smokers 13 & younger\ndf %>% \n  filter(Smoke == 'no' & age_group == '13 & under') %>% \n  pull(LungCap) %>% \n  mean()\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 6.358746\n```\n:::\n\n```{.r .cell-code}\n# Mean of smokers 13 & younger\ndf %>% \n  filter(Smoke == 'yes' & age_group == '13 &under') %>% \n  pull(LungCap) %>% \n  mean()\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] NaN\n```\n:::\n\n```{.r .cell-code}\n#Mean of non-smokers 14 to 15\ndf %>% \n  filter(Smoke == 'no' & age_group == '14 to 15') %>% \n  pull(LungCap) %>% \n  mean()\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 9.13881\n```\n:::\n\n```{.r .cell-code}\n#Mean of smokers 14 to 15\ndf %>% \n  filter(Smoke == 'yes' & age_group == '14 to 15') %>% \n  pull(LungCap) %>% \n  mean()\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 8.391667\n```\n:::\n\n```{.r .cell-code}\n#Mean of non-smokers 16 to 17\ndf %>% \n  filter(Smoke == 'no' & age_group == '16 to 17') %>% \n  pull(LungCap) %>% \n  mean()\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 10.46981\n```\n:::\n\n```{.r .cell-code}\n#Mean of smokers 16 to 17\ndf %>% \n  filter(Smoke == 'yes' & age_group == '16 to 17') %>% \n  pull(LungCap) %>% \n  mean()\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 9.38375\n```\n:::\n\n```{.r .cell-code}\n#Mean of non-smokers 18 & older\ndf %>% \n  filter(Smoke == 'no' & age_group == '18 & older') %>% \n  pull(LungCap) %>% \n  mean()\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 11.06885\n```\n:::\n\n```{.r .cell-code}\n# Mean of smokers 18 & older\ndf %>% \n  filter(Smoke == 'yes' & age_group == '18 & older') %>% \n  pull(LungCap) %>% \n  mean()\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 10.51333\n```\n:::\n\n```{.r .cell-code}\nlung_cap\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n# A tibble: 725 × 6\n   LungCap   Age Height Smoke Gender Caesarean\n     <dbl> <dbl>  <dbl> <chr> <chr>  <chr>    \n 1    6.48     6   62.1 no    male   no       \n 2   10.1     18   74.7 yes   female no       \n 3    9.55    16   69.7 no    female yes      \n 4   11.1     14   71   no    male   no       \n 5    4.8      5   56.9 no    male   no       \n 6    6.22    11   58.7 no    female no       \n 7    4.95     8   63.3 no    male   yes      \n 8    7.32    11   70.4 no    male   no       \n 9    8.88    15   70.5 no    male   no       \n10    6.8     11   59.2 no    male   no       \n# … with 715 more rows\n```\n:::\n:::\n\n\n### f. Calculate the correlation and covariance between Lung Capacity and Age. (use the cov() and cor() functions in R). Interpret your results.\n\n\n::: {.cell}\n\n```{.r .cell-code}\n#Correlation\ncor(lung_cap$LungCap, lung_cap$Age)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 0.8196749\n```\n:::\n\n```{.r .cell-code}\n#Covariance\ncov(lung_cap$LungCap, lung_cap$Age)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 8.738289\n```\n:::\n:::\n\n\nThe correlation is 0.81 which is pretty close to +1, meaning that the there is a positive relationship between lung capacity and age. The covariance is also high which shows that the two variables of lung capacity and age have a positive relationship. #2 Let X = number of prior convictions for prisoners at a state prison at which there are 810 prisoners.\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# x= prior convictions \nx<-c(0, 1, 2, 3, 4)\nfrequency<-c(128, 434, 160, 64, 24)\nstate_prison<- data_frame(x,frequency)\n```\n\n::: {.cell-output .cell-output-stderr}\n```\nWarning: `data_frame()` was deprecated in tibble 1.1.0.\nℹ Please use `tibble()` instead.\n```\n:::\n\n```{.r .cell-code}\nstate_prison\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n# A tibble: 5 × 2\n      x frequency\n  <dbl>     <dbl>\n1     0       128\n2     1       434\n3     2       160\n4     3        64\n5     4        24\n```\n:::\n:::\n\n\n### a. What is the probability that a randomly selected inmate has exactly 2 prior convictions?\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# 2 prior convictions.P(2)/total\n160/810\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 0.1975309\n```\n:::\n:::\n\n\nThere is a 1.9% probability that a randomly selected inmate has exactly 2 prior convictions.\n\n### b. What is the probability that a randomly selected inmate has fewer than 2 prior convictions?\n\n\n::: {.cell}\n\n```{.r .cell-code}\n#  less than 2 prior convictions. (P(0) + P(1))/total \n(128+434)/810\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 0.6938272\n```\n:::\n:::\n\n\nThere is a 6.9% probability that a randomly selected inmate has fewer than 2 prior convictions.\n\n### c. What is the probability that a randomly selected inmate has 2 or fewer prior convictions?\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# 2 or fewer prior convictions. (P(0) + P(1) + P(2)) +total\n(128+434+160)/810\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 0.891358\n```\n:::\n:::\n\n\nThere is a 8.9% probability that a randomly selected inmate has 2 or fewer prior convictions.\n\n### d. What is the probability that a randomly selected inmate has more than 2 prior convictions?\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# More than 2 prior convictions. (P(3) +P(4)) + total\n(64+24)/810\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 0.108642\n```\n:::\n:::\n\n\nThere is a 10.8% probability that a randomly selected inmate has more than 2 prior convictions.\n\n### e. What is the expected value for the number of prior convictions?\n\n\n::: {.cell}\n\n```{.r .cell-code}\n#Prior convictions. ((0*P(0)) +(1*(P(1)) + (2*P(2)) + (3*P(3)) + (4*P(4)))\ndf<-((128*0/810) +(434*1/810) +(160*2/810) +(64*3/810) +(24*4/810)) \nmean(df)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 1.28642\n```\n:::\n:::\n\n\nThe expected value for number of prior convictions is 1.28\n\n### f. Calculate the variance and the standard deviation for the Prior Convictions.\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# variance\nv<- ((0-1.28)^2) *(128/810) +((1-1.28)^2) * (434/810)+((2-1.28)^2) * (160/810)+((3-1.28)^2) *(64/810) +((4-1.28)^2) * (24/810)\nv\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 0.8562765\n```\n:::\n\n```{.r .cell-code}\n# standard deviation\nsd<- sqrt(v)\nsd\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 0.9253521\n```\n:::\n:::\n\n\nThe variance is 0.856 and the standard deviation is 0.925.\n",
    "supporting": [
      "ShoshanaBuck--HW1_files"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}