{
  "hash": "41f44959098efae63b4b72aa250f441d",
  "result": {
    "markdown": "---\ntitle: \"Homework 2\"\nauthor: \"Kaushika Potluri\"\ndesription: \"Something to describe what I did\"\ndate: \"10/16/2022\"\nformat:\n  html:\n    toc: true\n    code-fold: true\n    code-copy: true\n    code-tools: true\n---\n\n::: {.cell}\n\n```{.r .cell-code}\nknitr::opts_chunk$set(echo = TRUE)\n```\n:::\n\n\n## Loading in packages:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(tidyverse)\n```\n\n::: {.cell-output .cell-output-stderr}\n```\n── Attaching packages ─────────────────────────────────────── tidyverse 1.3.2 ──\n✔ ggplot2 3.3.6      ✔ purrr   0.3.5 \n✔ tibble  3.1.8      ✔ dplyr   1.0.10\n✔ tidyr   1.2.1      ✔ stringr 1.4.1 \n✔ readr   2.1.3      ✔ forcats 0.5.2 \n── Conflicts ────────────────────────────────────────── tidyverse_conflicts() ──\n✖ dplyr::filter() masks stats::filter()\n✖ dplyr::lag()    masks stats::lag()\n```\n:::\n\n```{.r .cell-code}\nlibrary(ggplot2)\nlibrary(dplyr)\nlibrary(stats)\n```\n:::\n\n\n##Question 1\n\nConstruct the 90% confidence interval to estimate the actual mean wait time for each of the two procedures. Is the confidence interval narrower for Angiography or Bypass surgery?\n\n### Angiography\n\n\n::: {.cell}\n\n```{.r .cell-code}\nang_mean <- 18\nang_sd <- 9\nang_ss <- 847\n\nang_se <- ang_sd/sqrt(ang_ss)\n\nang_cl <- 0.90  \nang_tail <- (1-ang_cl)/2\nang_tscore <- qt(p = 1-ang_tail, df = ang_ss-1)\n\nang_ci <- c(ang_mean - ang_tscore * ang_se,\n        ang_mean + ang_tscore * ang_se)\nprint(ang_ci)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 17.49078 18.50922\n```\n:::\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\n#assessing Confidence interval\n18.50922 - 17.49078\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 1.01844\n```\n:::\n:::\n\n\n####Margin of error\n\n\n::: {.cell}\n\n```{.r .cell-code}\nMargin_of_error_ang <- ang_tscore * ang_se\nMargin_of_error_ang * 1.01\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 0.5143103\n```\n:::\n:::\n\n\nWe can be 90% confident that the population mean wait time for the Angiography procedure is between 17.49078 and 18.50922 days with margin of error +/-0.51\n\n### Bypass\n\n\n::: {.cell}\n\n```{.r .cell-code}\nbypass_mean <- 19\nbypass_sd <- 10\nbypass_ss <- 539\n\nbypass_se <- bypass_sd/sqrt(bypass_ss)\n\nbypass_cl <- 0.90  \nbypass_tail <- (1-bypass_cl)/2\nbypass_tscore <- qt(p = 1-bypass_tail, df = bypass_ss-1)\n\nbypass_ci <- c(bypass_mean - bypass_tscore * bypass_se,\n        bypass_mean + bypass_tscore * bypass_se)\nprint(bypass_ci)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 18.29029 19.70971\n```\n:::\n:::\n\n\nWe can be 90% confident that the population mean wait time for the Bypass procedure is between 18.29029 and 19.70971 days.\n\n\n::: {.cell}\n\n```{.r .cell-code}\n#assessing Confidence interval\n19.70971 - 18.29029\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 1.41942\n```\n:::\n:::\n\n\n####Margin of error\n\n\n::: {.cell}\n\n```{.r .cell-code}\nMargin_of_error_bypass <- bypass_tscore * bypass_se\nMargin_of_error_bypass * 1.41\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 1.000692\n```\n:::\n:::\n\n\nTherefore, the confidence interval is more narrow for Angiographies.\n\n## Question 2\n\nA survey of 1031 adult Americans was carried out by the National Center for Public Policy. Assume that the sample is representative of adult Americans. Among those surveyed, 567 believed that college education is essential for success. Find the point estimate, p, of the proportion of all adult Americans who believe that a college education is essential for success. Construct and interpret a 95% confidence interval for p.\n\n\n::: {.cell}\n\n```{.r .cell-code}\n#n = Number of American adults (population), x = sample (surveyed)\nn = 1031\nx = 567 #(believed that college education is essential for success)\n\n#Using prop.test to find p (The CI is 95% by default)\n#This  function will return the range for the point estimate at 95% CI.\nprop.test(x, n)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n\n\t1-sample proportions test with continuity correction\n\ndata:  x out of n, null probability 0.5\nX-squared = 10.091, df = 1, p-value = 0.00149\nalternative hypothesis: true p is not equal to 0.5\n95 percent confidence interval:\n 0.5189682 0.5805580\nsample estimates:\n        p \n0.5499515 \n```\n:::\n:::\n\n\nThe percentage of adult Americans who think a college education is necessary for success is p, which is 0.5499515. We have a confidence interval of 95 percent confidence interval that equals, \\[0.5189682, 0.5805580\\] which contains the true population mean.\n\n## Question 3\n\nSuppose that the financial aid office of UMass Amherst seeks to estimate the mean cost of textbooks per semester for students. The estimate will be useful if it is within \\$5 of the true population mean (i.e. they want the confidence interval to have a length of \\$10 or less). The financial aid office is pretty sure that the amount spent on books varies widely, with most values between \\$30 and \\$200. They think that the population standard deviation is about a quarter of this range (in other words, you can assume they know the population standard deviation). Assuming the significance level to be 5%, what should be the size of the sample?\n\n\n::: {.cell}\n\n```{.r .cell-code}\n#Evaluating standard deviation using the given values\nUMassSD <- (200-30)/4\nUMassSD\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 42.5\n```\n:::\n:::\n\n\nSince the significance level is at 5% our Confidence level is 95%. A 95% confidence level has a z-score of 1.96. With this ideal sample size can be calculated.\n\n\n::: {.cell}\n\n```{.r .cell-code}\n#samplesize = ((UMassSD * zscore)/5)^2\nsamplesize <- ((UMassSD * 1.96)/5)^2\nprint(samplesize)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 277.5556\n```\n:::\n:::\n\n\nThe size necessary for the sample is 278.\n\n## Question 4\n\nAccording to a union agreement, the mean income for all senior-level workers in a large service company equals \\$500 per week. A representative of a women's group decides to analyze whether the mean income μ for female employees matches this norm. For a random sample of nine female employees, ȳ = \\$410 and s = 90.\n\na)  Test whether the mean income of female employees differs from \\$500 per week. Include assumptions, hypotheses, test statistic, and P-value. Interpret the result.\n\nAssuming that the sample is random and that the population has a normal distribution.\n\nNull hypothesis: H0: μ = 500\n\nAlternative hypothesis: Ha: μ ≠ 500\n\nWe will reject the null hypothesis at a p-value less than or equal to 0.05\n\n\n::: {.cell}\n\n```{.r .cell-code}\np_mean <- 500\ns_meanfemale <- 410\ns_sizefemale = 9\nsd = 90\n\n#find standard error\nstandarderrorfemale<- sd/sqrt(s_sizefemale)\nstandarderrorfemale\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 30\n```\n:::\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\n#calculating t-score\nt_stat<- (s_meanfemale-p_mean)/standarderrorfemale\nt_stat\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] -3\n```\n:::\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\n#calculating p value\ndf <- 9-1\np_value<- (pt(t_stat, df=8)) *2\np_value\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 0.01707168\n```\n:::\n:::\n\n\nSince the p value is less than .05 we can reject the null hypothesis\n\nb)  Report the P-value for Ha : μ \\< 500. Interpret.\n\nAssuming that the sample is random and that the population has a normal distribution.\n\nNull hypothesis: H0: μ = 500\n\nAlternative hypothesis: Ha: μ ≠ 500\n\nWe will reject the null hypothesis at a p-value less than or equal to 0.05\n\n\n::: {.cell}\n\n```{.r .cell-code}\npvalue_lower <- pt(-t_stat, df, lower.tail = FALSE)\npvalue_lower\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 0.008535841\n```\n:::\n:::\n\n\nAs p-value is less than the 0.05, we reject the null hypothesis. Therefore, the mean income of female employees is less than \\$500.\n\nc)  Report and interpret the P-value for H a: μ \\> 500.\n\n\n::: {.cell}\n\n```{.r .cell-code}\npvalue_upper <- pt(t_stat, df, lower.tail = FALSE)\npvalue_upper\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 0.9914642\n```\n:::\n:::\n\n\nAs p-value is less than the 0.05, we reject the null hypothesis. Therefore, the mean income of female employees is greater than \\$500.\n\n\n::: {.cell}\n\n```{.r .cell-code}\n#checking if sum = 1\npvalue_upper + pvalue_lower\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 1\n```\n:::\n:::\n\n\n## Question 5\n\nJones and Smith separately conduct studies to test H0: μ = 500 against Ha : μ ≠ 500, each with n = 1000. Jones gets ȳ = 519.5, with se = 10.0. Smith gets ȳ = 519.7, with se = 10.0.\n\na)  Show that t = 1.95 and P-value = 0.051 for Jones. Show that t = 1.97 and P-value = 0.049 for Smith.\n\n### Jones\n\n\n::: {.cell}\n\n```{.r .cell-code}\n#first calculating t-value for Jones\nt_stat_Jones <- (519.5 - 500)/(10)\nt_stat_Jones\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 1.95\n```\n:::\n\n```{.r .cell-code}\ndf <- 1000-1\n#now we calculate p value for Jones\n\n\np_value_Jones <- 2*pt(t_stat_Jones,df, lower.tail = FALSE)\np_value_Jones\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 0.05145555\n```\n:::\n:::\n\n\n### Smith\n\n\n::: {.cell}\n\n```{.r .cell-code}\n#first calculating t-value for Smith\nt_stat_Smith <- (519.7 - 500)/(10)\nt_stat_Smith\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 1.97\n```\n:::\n\n```{.r .cell-code}\ndf <- 1000-1\n\n#now we calculate p value for Smith\np_value_Smith <- 2*pt(t_stat_Smith,df, lower.tail = FALSE)\np_value_Smith\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 0.04911426\n```\n:::\n:::\n\n\nb)Using α = 0.05, for each study indicate whether the result is \"statistically significant.\"\n\nAnswer : When they say 'statistically significant' it means the p-value is smaller than the 0.05. For Jones, the p-value is 0.051 which is greater than the 0.05 significance level. This means that it is not statistically significant and we cannot reject the null hypothesis.\n\nFor Smith, the p-value is 0.049 which is smaller than the significance level. This means it is statistically significant and that we can reject the null hypothesis in favor of the alternative hypothesis.\n\nc)  Using this example, explain the misleading aspects of reporting the result of a test as \"P ≤ 0.05\" versus \"P \\> 0.05,\" or as \"reject H0\" versus \"Do not reject H0 ,\" without reporting the actual P-value.\n\nAnswer : One cannot assess the validity of the result if we do not provide the P-value and you cannot tell how close the p-value is to being significant. Since the values of Jones and Smith's is barely greater and lesser than 0.05 respectively, it is important to report the p-value because studies with very similar samples could report that the null should or should not be rejected. This could draw very different conclusions.\n\n## Question 6\n\nAre the taxes on gasoline very high in the United States? According to the American Petroleum Institute, the per gallon federal tax that was levied on gasoline was 18.4 cents per gallon. However, state and local taxes vary over the same period. The sample data of gasoline taxes for 18 large cities is given below in the variable called gas_taxes.\n\ngas_taxes \\<- c(51.27, 47.43, 38.89, 41.95, 28.61, 41.29, 52.19, 49.48, 35.02, 48.13, 39.28, 54.41, 41.66, 30.28, 18.49, 38.72, 33.41, 45.02)\n\nIs there enough evidence to conclude at a 95% confidence level that the average tax per gallon of gas in the US in 2005 was less than 45 cents? Explain.\n\nAnswer :\n\n\n::: {.cell}\n\n```{.r .cell-code}\ngas_taxes <- c(51.27, 47.43, 38.89, 41.95, 28.61, 41.29, 52.19, 49.48, 35.02, 48.13, 39.28, 54.41, 41.66, 30.28, 18.49, 38.72, 33.41, 45.02)\n```\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\n#Mean of taxes\nMean_gastaxes <- mean(gas_taxes)\nMean_gastaxes\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 40.86278\n```\n:::\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\nt.test(gas_taxes, mu = 45, alternative = 'less')\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n\n\tOne Sample t-test\n\ndata:  gas_taxes\nt = -1.8857, df = 17, p-value = 0.03827\nalternative hypothesis: true mean is less than 45\n95 percent confidence interval:\n     -Inf 44.67946\nsample estimates:\nmean of x \n 40.86278 \n```\n:::\n:::\n\n\nThe p-value is 0.03 at 95% confidence level. This is lesser than the 5% significance level. Therefore, this proves that we can reject the null hypothesis that the average tax per gallon was greater than or equal to 45 cents. We can say that the average tax per gallon of gas in the US in 2005 was less than 45 cents with 95% confidence.\n",
    "supporting": [],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}