{
  "hash": "e850215d7bb583617e5c3484d4d00db4",
  "result": {
    "markdown": "---\ntitle: \"Homework 4 - Emily Duryea\"\nauthor: \"Emily Duryea\"\ndescription: \"The fourth homework assignment for DACSS 603\"\ndate: \"11/14/2022\"\nformat:\n  html:\n    toc: true\n    code-fold: true\n    code-copy: true\n    code-tools: true\ncategories:\n  - hw4\n  - Emily Duryea\n---\n\n\n# Homework 4\n\n## Question 1\n\nFor recent data in Jacksonville, Florida, on y = selling price of home (in dollars), x1 = size of home (in square feet), and x2 = lot size (in square feet), the prediction equation is \n\nŷ = −10,536 + 53.8x1 + 2.84x2.\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Importing needed libraries\nlibrary(readxl)\nlibrary(tidyverse)\n```\n\n::: {.cell-output .cell-output-stderr}\n```\n── Attaching packages ─────────────────────────────────────── tidyverse 1.3.2 ──\n✔ ggplot2 3.3.6      ✔ purrr   0.3.5 \n✔ tibble  3.1.8      ✔ dplyr   1.0.10\n✔ tidyr   1.2.1      ✔ stringr 1.4.1 \n✔ readr   2.1.3      ✔ forcats 0.5.2 \n── Conflicts ────────────────────────────────────────── tidyverse_conflicts() ──\n✖ dplyr::filter() masks stats::filter()\n✖ dplyr::lag()    masks stats::lag()\n```\n:::\n\n```{.r .cell-code}\nlibrary(ggplot2)\nlibrary(dplyr)\nlibrary(stringr)\nlibrary(alr4)\n```\n\n::: {.cell-output .cell-output-stderr}\n```\nLoading required package: car\nLoading required package: carData\n\nAttaching package: 'car'\n\nThe following object is masked from 'package:dplyr':\n\n    recode\n\nThe following object is masked from 'package:purrr':\n\n    some\n\nLoading required package: effects\nlattice theme set by effectsTheme()\nSee ?effectsTheme for details.\n```\n:::\n\n```{.r .cell-code}\nlibrary(smss)\n```\n\n::: {.cell-output .cell-output-stderr}\n```\nWarning: package 'smss' was built under R version 4.2.2\n```\n:::\n:::\n\n\n### Part A\n\nA particular home of 1240 square feet on a lot of 18,000 square feet sold for \\$145,000. Find the predicted selling price and the residual, and interpret.\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Plugging given values into the equation to solve\n-10536 + 53.8*1240 + 2.84*18000\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 107296\n```\n:::\n\n```{.r .cell-code}\n# Calculating the residual\n145000-107296\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 37704\n```\n:::\n:::\n\n\nThe predicted selling price of the house would be \\$107,296, and the residual would be \\$37,704.\n\n### Part B\n\nFor fixed lot size, how much is the house selling price predicted to increase for each square-foot increase in home size? Why?\n\nThe house selling price predicted to increase for each square-foot increase is \\$53.80, based on the multiplier in the prediction equation.\n\n### Part C\n\nAccording to this prediction equation, for fixed home size, how much would lot size need to increase to have the same impact as a one-square-foot increase in home size?\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Calculating using square foot home size multiplier and square foot lot size multipler\n53.8/2.84\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 18.94366\n```\n:::\n:::\n\n\nThe lot size of a fixed size home would have to increase by 18.94366 feet to have the same impact as a one square foot increase in home size.\n\n## Question 2\n\n(Data file: salary in **alr4** R package). The data file concerns salary and other characteristics of all faculty in a small Midwestern college collected in the early 1980s for presentation in legal proceedings for which discrimination against women in salary was at issue. All persons in the data hold tenured or tenure track positions; temporary faculty are not included. The variables include degree, a factor with levels PhD and MS; rank, a factor with levels Asst, Assoc, and Prof; sex, a factor with levels Male and Female; Year, years in current rank; ysdeg, years since highest degree, and salary, academic year salary in dollars.\n\n### Part A\n\nTest the hypothesis that the mean salary for men and women is the same, without regard to any other variable but sex. Explain your findings.\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Importing the data\ndata(salary)\n\n# Conducting a t-test to test hypothesis\nt.test(salary ~ sex, data=salary)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n\n\tWelch Two Sample t-test\n\ndata:  salary by sex\nt = 1.7744, df = 21.591, p-value = 0.09009\nalternative hypothesis: true difference in means between group Male and group Female is not equal to 0\n95 percent confidence interval:\n -567.8539 7247.1471\nsample estimates:\n  mean in group Male mean in group Female \n            24696.79             21357.14 \n```\n:::\n:::\n\n\nBased on the results of the t-test, there is no statistically significant difference in the salary of male and female professors. This is because the p-value (0.09009) is greater than 0.05.\n\n### Part B\n\nRun a multiple linear regression with salary as the outcome variable and everything else as predictors, including sex. Assuming no interactions between sex and the other predictors, obtain a 95% confidence interval for the difference in salary between males and females.\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Creating the model\nsummary(lm(salary ~ degree + rank + sex + year + ysdeg, data=salary))\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n\nCall:\nlm(formula = salary ~ degree + rank + sex + year + ysdeg, data = salary)\n\nResiduals:\n    Min      1Q  Median      3Q     Max \n-4045.2 -1094.7  -361.5   813.2  9193.1 \n\nCoefficients:\n            Estimate Std. Error t value Pr(>|t|)    \n(Intercept) 15746.05     800.18  19.678  < 2e-16 ***\ndegreePhD    1388.61    1018.75   1.363    0.180    \nrankAssoc    5292.36    1145.40   4.621 3.22e-05 ***\nrankProf    11118.76    1351.77   8.225 1.62e-10 ***\nsexFemale    1166.37     925.57   1.260    0.214    \nyear          476.31      94.91   5.018 8.65e-06 ***\nysdeg        -124.57      77.49  -1.608    0.115    \n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n\nResidual standard error: 2398 on 45 degrees of freedom\nMultiple R-squared:  0.855,\tAdjusted R-squared:  0.8357 \nF-statistic: 44.24 on 6 and 45 DF,  p-value: < 2.2e-16\n```\n:::\n\n```{.r .cell-code}\n# Putting model data into a variable\nprofessor_salary <- lm(salary ~ degree + rank + sex + year + ysdeg, data=salary)\n\n#Creating a confidence interval for the variables in the model\nconfint(professor_salary)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n                 2.5 %      97.5 %\n(Intercept) 14134.4059 17357.68946\ndegreePhD    -663.2482  3440.47485\nrankAssoc    2985.4107  7599.31080\nrankProf     8396.1546 13841.37340\nsexFemale    -697.8183  3030.56452\nyear          285.1433   667.47476\nysdeg        -280.6397    31.49105\n```\n:::\n:::\n\n\nThe confidence interval for salary difference based on sex is between -697.8183 and 3,030.56452.\n\n### Part C\n\nInterpret your finding for each predictor variable; discuss (a) statistical significance, (b) interpretation of the coefficient / slope in relation to the outcome variable and other variables\n\n#### Degree\n\nThe p-value is not statistically significant, as the p-value is greater than 0.05. The results indicate that professors with a PhD make \\$1,388.61 than professors without a PhD.\n\n#### rankAssoc\n\nThe p-value is statistically significant, as it is less than 0.05. The results indicate that associate professors make \\$5,292.36 than assistant professors.\n\n#### rankProf\n\nThe p-value is statistically significant. The results indicate that faculty professors make \\$11,118.76 more than assistant professors.\n\n#### Sex\n\nThe p-value is not statistically significant. The results indicate that female professors make \\$1,166.37 more than male professors.\n\n#### Year\n\nThe p-value is statistically significant. The results indicate that with each year as a professor, there is a salary increase of \\$476.31.\n\n#### Ysdeg\n\nThe p-value is not statistically significant. The results indicate that for each year after completing their highest degree, there is a salary decrease of \\$124.57.\n\n### Part D\n\nChange the baseline category for the rank variable. Interpret the coefficients related to rank again.\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Changing the baseline category for the rank variable\nsalary$rank<- relevel(salary$rank, ref = 'Assoc')\n\n# Redoing the model from Part B\nsummary(lm(salary ~ degree + rank + sex + year + ysdeg, data=salary))\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n\nCall:\nlm(formula = salary ~ degree + rank + sex + year + ysdeg, data = salary)\n\nResiduals:\n    Min      1Q  Median      3Q     Max \n-4045.2 -1094.7  -361.5   813.2  9193.1 \n\nCoefficients:\n            Estimate Std. Error t value Pr(>|t|)    \n(Intercept) 21038.41    1109.12  18.969  < 2e-16 ***\ndegreePhD    1388.61    1018.75   1.363    0.180    \nrankAsst    -5292.36    1145.40  -4.621 3.22e-05 ***\nrankProf     5826.40    1012.93   5.752 7.28e-07 ***\nsexFemale    1166.37     925.57   1.260    0.214    \nyear          476.31      94.91   5.018 8.65e-06 ***\nysdeg        -124.57      77.49  -1.608    0.115    \n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n\nResidual standard error: 2398 on 45 degrees of freedom\nMultiple R-squared:  0.855,\tAdjusted R-squared:  0.8357 \nF-statistic: 44.24 on 6 and 45 DF,  p-value: < 2.2e-16\n```\n:::\n:::\n\n\nThe baseline category has been changed to \"Assoc.\" The results indicate that assistant professors make \\$5,292.36 less than Associate professors. Faculty professor are expected to make \\$5,826.40 more than Associate professors. These results are both still statistically significant (p-value \\< 0.05).\n\n### Part E\n\nFinkelstein (1980), in a discussion of the use of regression in discrimination cases, wrote, \\\"\\[a\\] variable may reflect a position or status bestowed by the employer, in which case if there is discrimination in the award of the position or status, the variable may be \\'tainted.\\' \\\" Thus, for example, if discrimination is at work in promotion of faculty to higher ranks, using rank to adjust salaries before comparing the sexes may not be acceptable to the courts. Exclude the variable rank, refit, and summarize how your findings changed, if they did.\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Creating a model without rank\nsummary(lm(salary ~ degree + sex + year + ysdeg, data=salary))\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n\nCall:\nlm(formula = salary ~ degree + sex + year + ysdeg, data = salary)\n\nResiduals:\n    Min      1Q  Median      3Q     Max \n-8146.9 -2186.9  -491.5  2279.1 11186.6 \n\nCoefficients:\n            Estimate Std. Error t value Pr(>|t|)    \n(Intercept) 17183.57    1147.94  14.969  < 2e-16 ***\ndegreePhD   -3299.35    1302.52  -2.533 0.014704 *  \nsexFemale   -1286.54    1313.09  -0.980 0.332209    \nyear          351.97     142.48   2.470 0.017185 *  \nysdeg         339.40      80.62   4.210 0.000114 ***\n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n\nResidual standard error: 3744 on 47 degrees of freedom\nMultiple R-squared:  0.6312,\tAdjusted R-squared:  0.5998 \nF-statistic: 20.11 on 4 and 47 DF,  p-value: 1.048e-09\n```\n:::\n:::\n\n\nAfter removing rank from the model, the results indicate that there is a difference between male and female salaries, with females making \\$1,286.54 less than men. However, this difference is not statistically significant.\n\n### Part F\n\nEveryone in this dataset was hired the year they earned their highest degree. It is also known that a new Dean was appointed 15 years ago, and everyone in the dataset who earned their highest degree 15 years ago or less than that has been hired by the new Dean. Some people have argued that the new Dean has been making offers that are a lot more generous to newly hired faculty than the previous one and that this might explain some of the variation in Salary.\n\nCreate a new variable that would allow you to test this hypothesis and run another multiple regression model to test this. Select variables carefully to make sure there is no multicollinearity. Explain why multicollinearity would be a concern in this case and how you avoided it. Do you find support for the hypothesis that the people hired by the new Dean are making higher than those that were not?\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Creating a variable with categories \"new\" for less than 15 years, and \"old\" for 15 or more years\n#creating a dummy variable new and old dean\nsalary<-mutate(salary, dean= case_when(ysdeg < 15 ~\"new\",\n                               ysdeg >=15 ~\"old\"))\n\n# Rerunning the model with new variable\nsummary(lm(salary ~ dean + degree + sex + rank +year, data=salary))\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n\nCall:\nlm(formula = salary ~ dean + degree + sex + rank + year, data = salary)\n\nResiduals:\n    Min      1Q  Median      3Q     Max \n-3588.0 -1532.2  -232.2   565.7  9132.5 \n\nCoefficients:\n            Estimate Std. Error t value Pr(>|t|)    \n(Intercept)  20468.7      951.7  21.507  < 2e-16 ***\ndeanold      -2421.6     1187.9  -2.038   0.0474 *  \ndegreePhD     1073.5      843.3   1.273   0.2096    \nsexFemale     1046.7      858.0   1.220   0.2289    \nrankAsst     -5012.5     1002.3  -5.001 9.16e-06 ***\nrankProf      6213.3     1045.0   5.946 3.76e-07 ***\nyear           450.7       81.5   5.530 1.55e-06 ***\n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n\nResidual standard error: 2360 on 45 degrees of freedom\nMultiple R-squared:  0.8597,\tAdjusted R-squared:  0.841 \nF-statistic: 45.95 on 6 and 45 DF,  p-value: < 2.2e-16\n```\n:::\n:::\n\n\nBased on the new variable and controlling for other predictors, faculty hired by the old dean make \\$2,421.60 less than new faculty.\n\n## Question 3\n\n(Data file: house.selling.price in **smss** R package)\n\n### Part A\n\nUsing the house.selling.price data, run and report regression results modeling y = selling price (in dollars) in terms of sizeof home (in square feet) and whether the home is new(1 = yes; 0 = no). In particular, for each variable; discuss statistical significance and interpret the meaning of the coefficient.\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Importing needed data\ndata(house.selling.price)\n\n# Creating model based on size and age status\nsummary(lm(Price ~ Size + New, data= house.selling.price))\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n\nCall:\nlm(formula = Price ~ Size + New, data = house.selling.price)\n\nResiduals:\n    Min      1Q  Median      3Q     Max \n-205102  -34374   -5778   18929  163866 \n\nCoefficients:\n              Estimate Std. Error t value Pr(>|t|)    \n(Intercept) -40230.867  14696.140  -2.738  0.00737 ** \nSize           116.132      8.795  13.204  < 2e-16 ***\nNew          57736.283  18653.041   3.095  0.00257 ** \n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n\nResidual standard error: 53880 on 97 degrees of freedom\nMultiple R-squared:  0.7226,\tAdjusted R-squared:  0.7169 \nF-statistic: 126.3 on 2 and 97 DF,  p-value: < 2.2e-16\n```\n:::\n:::\n\n\nBased on the size variable, the house price will increase by \\~\\$116.132 for each square foot increase in size. This finding is statistically significant.\n\nBased on the age of the house variable, a new house is projected to cost \\~\\$57,736.283 more than an old house. This finding is also statistically significant.\\\n\n### Part B\n\nReport and interpret the prediction equation, and form separate equations relating selling price to size for new and for not new homes.\n\nPrediction equation:\n\ny = -40230.867 + 116.13\\*x1 + 57736.283\\*x2\n\nx1 = size\n\nx2 = age of house (old vs. new)\n\nPrediction equation for a new house:\n\ny = -40230.867 + 116.132\\*x1 + 57736.283\n\nPrediction equation for an old house:\n\ny = -40230.867 + 116.132\\*x1\n\n### Part C\n\nFind the predicted selling price for a home of 3000 square feet that is (i) new, (ii) not new.\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Using the prediction model to predict the cost of a new house\n-40230.867 + 116.132*3000 +  57736.283\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 365901.4\n```\n:::\n\n```{.r .cell-code}\n# Using the prediction model to predict the cost of an old house\n-40230.867 + 116.132*3000\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 308165.1\n```\n:::\n:::\n\n\nBased on the prediction model, a new house of 3,000 square feet would cost \\$365,901.40, while an old house of the same size would cost \\$308,165.10.\n\n### Part D\n\nFit another model, this time with an interaction term allowing interaction between size and new, and report the regression results\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Creating a model for an interaction between size and new\nsummary(lm(Price ~ Size + New + Size*New, data=house.selling.price))\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n\nCall:\nlm(formula = Price ~ Size + New + Size * New, data = house.selling.price)\n\nResiduals:\n    Min      1Q  Median      3Q     Max \n-175748  -28979   -6260   14693  192519 \n\nCoefficients:\n              Estimate Std. Error t value Pr(>|t|)    \n(Intercept) -22227.808  15521.110  -1.432  0.15536    \nSize           104.438      9.424  11.082  < 2e-16 ***\nNew         -78527.502  51007.642  -1.540  0.12697    \nSize:New        61.916     21.686   2.855  0.00527 ** \n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n\nResidual standard error: 52000 on 96 degrees of freedom\nMultiple R-squared:  0.7443,\tAdjusted R-squared:  0.7363 \nF-statistic: 93.15 on 3 and 96 DF,  p-value: < 2.2e-16\n```\n:::\n:::\n\n\nBased on this model, the prediction equation would be y = -2227.808 + 104.438\\*x1 + 61.916\\*x2 -78527.502\\*x3, where x1 is the size of the house in square feet, x2 is the size and house age interaction variable, and x3 is the house age variable (old vs new). Both size and the interaction between size and house age are statistically significant. However, the house age variable is no longer statistically significant.\n\n### Part E\n\nReport the lines relating the predicted selling price to the size for homes that are (i) new, (ii) not new.\n\nPrediction equation for a new house:\n\ny = -2227.808 + 166.354\\*x1 - 78527.502\n\nPrediction equation for an old house:\n\ny = -2227.808 + 104.438\\*x1\n\n### Part F\n\nFind the predicted selling price for a home of 3000 square feet that is (i) new, (ii) not new.\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Using the prediction model to predict the cost of a new house\n-2227.808 + 166.354*3000 - 78527.502\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 418306.7\n```\n:::\n\n```{.r .cell-code}\n# Using the prediction model to predict the cost of an old house\n-2227.808 + 104.438*3000\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 311086.2\n```\n:::\n:::\n\n\nBased on the new prediction model, a new house of 3,000 square feet would cost \\$418,306.70, while an old house of the same size would cost \\$311,086.20.\n\n### Part G\n\nFind the predicted selling price for a home of 1500 square feet that is (i) new, (ii) not new. Comparing to (F), explain how the difference in predicted selling prices changes as the size of home increases.\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Using the prediction model to predict the cost of a new house\n-2227.808 + 166.354*1500 - 78527.502\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 168775.7\n```\n:::\n\n```{.r .cell-code}\n# Using the prediction model to predict the cost of an old house\n-2227.808 + 104.438*1500\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 154429.2\n```\n:::\n:::\n\n\nBased on the new prediction model, a new house of 1,500 square feet would cost \\$168,775.70, while an old house of the same size would cost \\$154,429.20. This model demonstrates that small houses vary less in price, regardless of age, than larger houses, where new vs old houses makes much more of a difference.\n\n### Part H\n\nDo you think the model with interaction or the one without it represents the relationship of size and new to the outcome price? What makes you prefer one model over another?\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Calculating predicted house cost of a large new house with first model\n-40230.867 + 116.132*5000 +  57736.283\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 598165.4\n```\n:::\n\n```{.r .cell-code}\n# Calculating predicted house cost of a large old house with first model\n-40230.867 + 116.132*5000\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 540429.1\n```\n:::\n\n```{.r .cell-code}\n# Calculating predicted house cost of a small new house with first model\n-40230.867 + 116.132*1000 +  57736.283\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 133637.4\n```\n:::\n\n```{.r .cell-code}\n# Calculating predicted house cost of a small old house with the first model\n-40230.867 + 116.132*1000\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 75901.13\n```\n:::\n\n```{.r .cell-code}\n# Calculating predicted house cost of a large new house with second model\n-2227.808 + 166.354*5000 - 78527.502\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 751014.7\n```\n:::\n\n```{.r .cell-code}\n# Calculating predicted house cost of a large old house with second model\n-2227.808 + 104.438*5000\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 519962.2\n```\n:::\n\n```{.r .cell-code}\n# Calculating predicted house cost of a small new house with second model\n-2227.808 + 166.354*1000 - 78527.502\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 85598.69\n```\n:::\n\n```{.r .cell-code}\n# Calculating predicted house cost of a small old house with the second model\n-2227.808 + 104.438*1000\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 102210.2\n```\n:::\n:::\n\n\nI think that it depends. For large houses, I would use the second model, because it shows the difference the price a new house vs an old house more greatly. However, for smaller houses, the second model is inaccurate, since it predicts that a new small house would be cheaper than an old small house. I think the first model would be a better predictor for small houses.\n",
    "supporting": [],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}