{
  "hash": "a683ecec5c51ce0d903e61bec5854c4f",
  "result": {
    "markdown": "---\ntitle: \"Homework 2\"\nauthor: \"Emma Rasmussen\"\ndescription: \"The second homework assignment\"\ndate: \"10/13/2022\"\nformat:\n  html:\n    toc: true\n    code-fold: true\n    code-copy: true\n    code-tools: true\ncategories:\n  - hw2\n---\n\n::: {.cell}\n\n```{.r .cell-code}\nknitr::opts_chunk$set(echo = TRUE, warning=FALSE, message=FALSE)\n\nlibrary(readxl)\nlibrary(tidyverse)\nlibrary(ggplot2)\nlibrary(dplyr)\n```\n:::\n\n\n## 1.\n\n\n::: {.cell}\n\n```{.r .cell-code}\n#Bypass\n#calculating t-score for 90% confidence interval\ntscoreb<- qt(p=1-.05, df=539-1)\n\n#calculating standard error\nseb<- 10/sqrt(539)\n\nmeanb<- 19\n\nCIb<- c(meanb- (tscoreb*seb), meanb+ (tscoreb*seb))\nCIb\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 18.29029 19.70971\n```\n:::\n\n```{.r .cell-code}\n#Angiography\n#calculating t-score for 90% confidence interval\ntscorea<- qt(p=1-.05, df=847-1)\n\n#calculating standard error\nsea<- 9/sqrt(847)\n\nmeana<- 18\n\nCIa<- c(meana- (tscorea*sea), meana+ (tscorea*sea))\nCIa\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 17.49078 18.50922\n```\n:::\n:::\n\n\nThe 90% confidence interval for bypass is [18.29, 19.71] days. The 90% confidence interval for angiography is [17.49, 18.51] days. The confidence interval for angiography is narrower, which makes sense given it has a (slightly) smaller standard deviation and a larger sample size (larger sample size reduces margin of error).\n\n## 2.\n\n\n::: {.cell}\n\n```{.r .cell-code}\n#assigning n= number of trials\nn<- 1031\n#assigning k= number agree\nk<- 567\n\n#calculating point estimate\np<- 567/1031\np\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 0.5499515\n```\n:::\n\n```{.r .cell-code}\n#calculating margin of error for 95% CI. I have no idea how to calculate a confidence interval without a sd. I found this formula online.\nmargin<- qnorm(0.975)*sqrt(p*(1-p)/n)\nmargin\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 0.03036761\n```\n:::\n\n```{.r .cell-code}\nCI<- c(p-margin, p+ margin)\nCI\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 0.5195839 0.5803191\n```\n:::\n:::\n\n\nThe 95% confidence interval for American's agreeing that college education is essential for success is [51.96, 58.03]%. The point estimate for this value based on the survey is 55%.\n\n## 3.\n\n\n::: {.cell}\n\n```{.r .cell-code}\n#estimating population standard deviation\n(200-30)/4\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 42.5\n```\n:::\n\n```{.r .cell-code}\n#solving for n in the equation for confidence intervals 5=1.96*(42.5/sqrt(n))\n#n= 277.56 or 278\n```\n:::\n\nBy plugging in 5 to the formula for confidence intervals (the t-value for 95%, and the standard deviation estimate of 42.5) we get a value of n=277.56 or 278 need to be in the sample to retrieve a confidence interval of width 10.\n\n## 4.\n\n### a.\n\n-   Assume data is normally distributed\n-   Ho: μ =500\n-   Ha: μ not equal to 500 \nμ < 500 \nμ > 500\n-   alpha level =0.05\n\n\n::: {.cell}\n\n```{.r .cell-code}\n#calculating the standard error\nsef<- 90/sqrt(9)\nsef\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 30\n```\n:::\n\n```{.r .cell-code}\n#calculating t-score\ntf<-(410-500)/(sef)\ntf \n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] -3\n```\n:::\n\n```{.r .cell-code}\n#calculating the p-value from the test statistic (multiply times two because we are doing a two-sided test)\n(pt(q=-3, df=8))*2\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 0.01707168\n```\n:::\n\n```{.r .cell-code}\n#this represents the probability of getting a random sample from the population with a mean of 410 or lower, as the default calculates the lower tail)\npt(-3, 8)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 0.008535841\n```\n:::\n\n```{.r .cell-code}\n#this represents the probability of getting a random sample from the population with a mean of 410 or higher, as we included lower.tail=FALSE)\npt(-3, 8, lower.tail=FALSE)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 0.9914642\n```\n:::\n\n```{.r .cell-code}\n# since our p-value is 0.99 we do not have evidence that the mean income of female employees is greater than 500 a week\n```\n:::\n\n\nTwo-sided: Since our p-value is 0.017 we can reject the null hypothesis at alpha level=0.05. We have evidence that the mean weekly earnings for women at this company is different from $500. \n### b. \nLower tail: Since our p-value (0.0085) is less than the alpha level of 0.05, we can reject the null. We have evidence that the mean weekly earnings at this company for women is less than $500. \n### c. \nUpper tail: Since our p-value is 0.99 we do not have evidence that the mean income of female employees is greater than $500 a week\n\n## 5.\n\n### a.\n\n\n::: {.cell}\n\n```{.r .cell-code}\n#Jones\n#calculating t-score\n(519.5-500)/(10)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 1.95\n```\n:::\n\n```{.r .cell-code}\n#Calculating from p value from t-score. Because it is a two sided test, we multiply the result times two.\n(pt(q=1.95, df=999, lower.tail=FALSE))*2\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 0.05145555\n```\n:::\n\n```{.r .cell-code}\n#Smith\n##calculating t-score\n(519.7-500)/(10)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 1.97\n```\n:::\n\n```{.r .cell-code}\n#Calculating from p value from t-score. Because it is a two sided test, we multiply the result times two.\n(pt(q=1.97, df=999, lower.tail=FALSE))*2\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 0.04911426\n```\n:::\n:::\n\n\n### b.\nAt the .05 significance level, Jones' findings are not significant but Smith's findings are. \n\n### c.\nThis example shows that there is a very find line between rejecting and not rejecting the null hypothesis. Their findings were extremely similar, the means are different by only 0.2. In this way, reporting the p-value retrieved is actually really important to make this distinction. Similarly, Jones' findings would have been significant at the 0.1 significance level, so rejecting or not rejecting the null hypothesis based on a p-value can be fairly arbitrary.\n\n## 6.\n\n\n::: {.cell}\n\n```{.r .cell-code}\ngas_taxes <- c(51.27, 47.43, 38.89, 41.95, 28.61, 41.29, 52.19, 49.48, 35.02, 48.13, 39.28, 54.41, 41.66, 30.28, 18.49, 38.72, 33.41, 45.02)\nt.test(gas_taxes, mu=45.0, alternative=\"less\")\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n\n\tOne Sample t-test\n\ndata:  gas_taxes\nt = -1.8857, df = 17, p-value = 0.03827\nalternative hypothesis: true mean is less than 45\n95 percent confidence interval:\n     -Inf 44.67946\nsample estimates:\nmean of x \n 40.86278 \n```\n:::\n:::\n\n\nUsing a 95% confidence level we get a p-value of 0.038. We reject the null hypothesis. We have evidence that the average tax per gallon of gas in the U.S. is less than 45 cents.\n",
    "supporting": [],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}